### ISSUE TITLE
[Feature] Ender IO Storage Block

### ISSUE THREAD

**Issue by tjsd** [SleepyTrousers/EnderIO#1005]
So, there is no alternative to AE2 for mass storage. 

I was thinking a crazy storage block with a interface. An upgrade to item conduits to make them into storage buses. 

The block itself works as a crafting terminal, and you can access all storages you have attached to the ender io item conduits with the storage upgrade.

Of course balance of the recipes is important :)

**Comment by tterrag1098** [comment]
Inventory Panel fulfills this
