### ISSUE TITLE
Dimensional Transceiver and (Insulated) Redstone Conduit

### ISSUE THREAD

**Issue by forcemaster89** [SleepyTrousers/EnderIO#1020]
I think it would be really useful if Redstone Conduits, and Gas conduits could be connected via Dimensional Transceivers in the same way as Item, Energy and Fluid conduits. This would be particularly useful if the color system being used with Redstone Conduits would continue to work, allowing 16 redstone signals to be passed through the Transceiver.

**Comment by forcemaster89** [comment]
I know this was a while ago, but is this still going to be implemented? A good way to send and receive Redstone signals is very hard to come by.

**Comment by HenryLoenwind** [comment]
Redstone conduits need a complete rewrite before any features will be added to them. That is one of our TODOs for version 2.4. Gas conduits are suffering from the old "none of the active devs is using Mek himself" problems.

**Comment by forcemaster89** [comment]
That makes sense. The redstone will definitely be more useful anyways. Keep up the amazing work. This is definitely one of my most used mods. :)
