### ISSUE TITLE
Extra utilites tools not usable in farming station.

### ISSUE THREAD

**Issue by Rious** [SleepyTrousers/EnderIO#1064]
Tried to put the reversing hoe and healing axe in the farming station. I can not put it into the interface.
Not sure if intended or not, i did not google this. also very little info on the farming stations to be found aswell.

DNS techpack 7.4.1 from ATLauncher
EnderIO-1.7.10-2.0.8.221

**Comment by Hund** [comment]
Hows it going with the reversing hoe?

**Comment by MatthiasMann** [comment]
Hoes can be added via the config file - try it and see if the hoe works correctly or not.

**Comment by Hund** [comment]
There is no entry for it and I'm not sure what to add myself?
