### ISSUE TITLE
[bug]Insulated and non Insulated Redstone conduit powered by redstone stays on forever

### ISSUE THREAD

**Issue by Skyqula** [SleepyTrousers/EnderIO#1180]
http://imgur.com/4S4rxQm

As can be seen in the pitcture above. In both cases using the left lever can turn the redstone signal on and and off. Using the right lever turns the redstone signal on, but cannot turn it off again.

In addition to this bug, there is also an extended bug throwing rednet into the mix:

http://imgur.com/40PSFEU

* Using either of the rednet lever turns the signal on and off.
* Using the left redstone conduit lever turns the signal on and off.
* Using the right redstone conduit lever turns the signal on but cannot turn it off.

The additional bug here is that after the redstone signal is stuck, turning the left conduit lever on will turn the rednet signal off (while it should be on!) and then turning the left lever off turns the conduit signal off.

**Comment by KittyCancer** [comment]
I'm having the same issue, found any fix yet?
