### ISSUE TITLE
[Suggestion] - Option to disable Dim Transceiver

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#1233]
Hi CrazyPants. EnderIO has a lot of config options, so I would like to ask if it would be possible to add a config for disabling the Dimensional Transceiver (with removing it completely from game).

I am a lead developer of a hard-mode modpack and I am trying to remove the "easy" item/energy teleportation methods and Dim Transceiver is one of those methods. I know that i can make it use more energy for teleporting items, but that I would like to leave as a "last resort"

Thank you

**Comment by Adaptivity** [comment]
Since 1.7.10 (I guess?) it is possible to disable it in Ender IO config. Can be closed.
