### ISSUE TITLE
[Feature Request] Fluid input / output pump for source blocks

### ISSUE THREAD

**Issue by lucom** [SleepyTrousers/EnderIO#1240]
As described in the issues below, I'd also like to have a machine that pumps liquid (source blocks). In addition it would be great to be able to use the pump to fill areas with a certain liquid.

https://github.com/CrazyPants/EnderIO/issues/1088
https://github.com/CrazyPants/EnderIO/issues/309

**Comment by lucom** [comment]
Any idea when or whether you'll implement that?

**Comment by MatthiasMann** [comment]
EnderIO doesn't really has any use for fluids outside of water for which it has the Reservoir.
