### ISSUE TITLE
Farming station requires a hoe to harvest sugar cane

### ISSUE THREAD

**Issue by Professorvennie** [SleepyTrousers/EnderIO#1274]
I set up a farming station for sugar cane and it will planet the sugar cane fine without a hoe but it won't harvest the sugar cane without a hoe.  I am on the latest dev build from the Jenkins.  If you need more information just ask.

**Comment by PapiDimmi** [comment]
Firstly, you can edit comments.

Secondly, like others have said, this is intended. It’s intended because with no tool, the farming station would be unbalanced—_i.e._, _too_ good.

**Comment by mindforger** [comment]
PapiDimmi, this issue is VERY old and closed already by the OP
and would you kindly reduce the usage of that emotes to a degree where you want to support a suggestion, giving thumbs down and confused smileys is kind of rude!

**Comment by PapiDimmi** [comment]
How is it rude? That’s like saying that downvoting comments on Reddit is rude or that disliking videos on YouTube is rude.

**Comment by mindforger** [comment]
this is not reddit, it is github and to be more precise an issue tracker
