### ISSUE TITLE
[Feature] Make the vacuum chest paintable (like the Travel Anchor)

### ISSUE THREAD

**Issue by Xaw4** [SleepyTrousers/EnderIO#1275]
It would be neat to have the possibilty to paint the vacuum chest. i tend to make my mob grinders look somewhat nice, and in that cases, the vacuum chest is one more block that sticks out, but i'd like it to blend in with the floor (or the wall)

**Comment by WoodenPint** [comment]
Since this suggestion is already up, I give this an imaginary upvote. The vacuum chest basically wants/is destined to be paintable in my opinion.

**Comment by Sandriell** [comment]
Was very dissapointed today when I tried to paint one. :( I would love to see this implemented.
