### ISSUE TITLE
alloy smelter gives so much experience when smelting ore

### ISSUE THREAD

**Issue by RaineAndrews** [SleepyTrousers/EnderIO#1295]
Is anyone else having this awesome, but game breaking problem?  I smelted 10 gold ore and went from level 16 to level 32...  Iron ore did this too.

**Comment by Turmfalke2** [comment]
hi,
I just encountered the same issue, smelting a stack of 20 lead dust (thermal expansion) gives me enough experience for 40 levels. (From level 1 to level 41)

In addition to that you can just turn them back to dust in the sag mill for even more experience.

mods:
http://pastebin.com/hiehAvNK

**Comment by RaineAndrews** [comment]
I'm sorry for the long delay, I really have avoided this endeavor, but I have been tinkering with the mods.

To note:Forge (*3.1420), EnderIO (*8.831), Botania (*6-191), BloodMagic (*1.3.2-1)

Something about this combination results in 0 experience when the SAG Mill crushes iron and gold ore and feeds into an Alloy Smelter.  Could this be part of the code that is causing this glitch?  EnderIO with Botania or EnderIO and BloodMagic do not cause issues.  Only in combination does it seem so.

**Comment by MatthiasMann** [comment]
You only get XP when you take out the smelted result from the Alloy Smelter's output slot (in the GUI).
The SAG Mill does not give XP at all.

**Comment by RaineAndrews** [comment]
I'm sorry, I meant after taking the crushed item from the smelter :(

**Comment by RaineAndrews** [comment]
Adding ChickenChunks (*4.16) returns normal function to the experience gain.  Please note that CodeChickenCore (*6.44) by itself did not do this, only after adding both of them (because you can't just add chunks) does normal experience gain.

**Comment by RaineAndrews** [comment]
I took out all my thaumcraft related mods and the experience gain is not present anymore.  I'll have to isolate which mod is causing the huge gains, but the no experience gain issue might be masking what is causing this bug.  Any help is appreciated :)
