### ISSUE TITLE
Add some kind of omnitool/ideas for upgrades

### ISSUE THREAD

**Issue by VivienV** [SleepyTrousers/EnderIO#1307]
The dark pick already has the spoon and travel upgrades which make life a whole lot easier during the game. However, when out exploring and collecting resources, I generally just end up taking my Atomic Dissassembler from Mekanism due to its multi-purpose nature to save inventory space, and I really miss having the same features in my EnderIO tools (which is my favorite mod and what I try to use for everything).

So what I'm thinking is maybe add another tier of tool that combines all other tools into one, so that you can harvest/attack anything in your path with the same tool (plus it doubling as a Travel Staff). This could be done either by upgrading the pick with the specific stuff you want (something like the spoon but for harvesting wood, for example) or (which I personally think is the cooler option) by adding a new tool (maybe crafted by combining all dark tools?).

This, of course, should not be cheap (which is a major gripe I have with the paxels and atomic dissassembler from mekanism). Some ideas I have are:

1. Crafting the omnitool (which would be expensive on it's own) and then upgrading it with each tool you want to have the functionality of (you could even require the component tool to be fully empowered, and having the upgrades not transfer over, to make it more expensive). So, for instance, if I want my omnitool to act as both a pick and a sword, I would have to add a (maybe fully upgraded) pick and sword to it in an anvil.

2. The aesthetics of it could change based on what upgrades you have, similar to Tinker's Construct's tools. So if you add a sword, it would look like you actually added some sort of functional blade to it. (I don't know how feasible such a thing is to do)

3. It would be really really awesome if it could also work as a wrench, which is something I think no omnitool-like item so far does.

4. Maybe adding an upgrade for it so that you can optionally have it not have durability and instead rely entirely on power (the drawback being that if you run out of power it's back to being like using your fists). Reinforced obsidian would be a good item to use in such an upgrade, since obsdian already gives the Unbreaking enchant, reinforced obsidian could make the EnderIO tools unbreakable.

5. Maybe have a way to control the speed? I have a Dark Pick with Efficiency V and Spoon, which is great when mining but absolutely terrible when trying to break stuff (specially dirt) with any precision. This is of course bad planning on my part, but a real omnitool should be able to be useful under any circumstance one finds oneself in, be it breaking that one block or pretending to be a human quarry. I understand, though, that this might be too close to an atomic dissassembler to be worth it.

6. On the subject of human quarries, maybe a way to break multiple blocks at once? IIRC the flux-infused pickaxe can mine a 3x1x1 hole, and there's a pick from Thaumcraft that can mine an offset 5x5x1 hole (great for building rooms and large tunnels). Maybe a way to add some presets like that? (They could each be an independent upgrade, and if the omnitool is a new item and not just a dark pick full of upgrades, it could be so that adding those upgrades to a Dark Pick is permanent and in the omnitool they become new modes of operation and not permanent changes, to keep to the idea that it is the ultimate-tier tool that's useful for everything)

7. Two words: MAGNET UPGRADE. No more wasted hotbar space. Bonus points if there's a way to make it only work for the stuff the tool mines and not everything around you (although I think this would have to work more like instant teleportation to your inventory than a proper magnet... which, now that I think of it, is very Ender-y and cool).

Those are just some ideas I had, they are not polished and certainly I don't expect them to be accepted in their entirety and as-is. Even if the omnitool is out of the question (which I would completely understand), maybe some of those upgrade ideas could be worth something to the existing tools.

**Comment by Badcholo** [comment]
Paxel, combine all 3 tools into a paxel and add all the upgrades into the paxel from all 3 tools as normal.
