### ISSUE TITLE
Stirling Generator fuel burn rate with Octadic Capacitor incorrect?

### ISSUE THREAD

**Issue by rrongol** [SleepyTrousers/EnderIO#1309]
In-game, the Stirling Generator UI lists the following for burn rate with different capacitors:

None = burn rate 2.0x
Double-Layer Capacitor = burn rate 1.5x
Octadic Capacitor = burn rate 1.5x

According to the wiki the burn rate with an Octadic Capacitor is supposed to be 1.0x.  I realize the wiki might be outdated, but shouldn't the Octadic be lower than the Double-Layer Capacitor?

EnderIO-1.7.10-2.2.1.281

BTW, thank you for creating a fantastic mod!

**Comment by RAnders00** [comment]
@CrazyPants poke
