### ISSUE TITLE
[Suggestions / Ideas] Upgrades for Wireless Chargers

### ISSUE THREAD

**Issue by m31317015** [SleepyTrousers/EnderIO#1349]
Well it would be cool if the mod adds the functionality for charging machines in range, the charging rate, also items which is RF-Based inside a machine, or even sth like AE / UE support, that would be awesome! (I didn't mean to request the mod being joined with those power units which mods like Applied Energistics 2 / Universal Electricity / Mekanism / RotaryCraft adds, just want to point out that Couldn't wireless chargers charge machines nearby? btw can you add a slot for capacitors to upgrade the capacitors to actually charges those items?) Thx!

**Comment by Alaberti** [comment]
Is this something that's not likely to happen?

**Comment by m31317015** [comment]
I think so, btw it's been so long that I almost give up minecraft :smile:
