### ISSUE TITLE
Powered spawners don't remain active with chunk loaders

### ISSUE THREAD

**Issue by rrongol** [SleepyTrousers/EnderIO#1366]
I noticed that powered spawners don't remain active if you try to keep them going with a chunk loader.

Here is what I tried:

1) Place a powered zombie spawner next to a creative capacitor bank quite high in the air.  Zombies will begin spawning, fall to their death, and leave rotten flesh on the ground below.

2) Dig a hole three blocks deep right below the spawner.  At the bottom of the hole, place a chickenbones ender chest.  Key a chickenbones ender pouch to the chest, so that they are linked.  On top of the chest, place a pipe/hopper/whatever.  On top of that place an EnderIO vacuum chest.  Now, the vacuum chest will suck up all the rotten flesh and pass it into the ender chest.

3) Place a chickenbones chunk loader or spot loader on the ground near the vacuum hopper to keep the chunk loaded.  Use the lasers or F9 to make sure everything is in the same chunk and should remain loaded.

4) Back away a little ways.  You can open the ender pouch and watch the rotten flesh accumulate in the ender-chest.

5) If I travel up to about seven chunks from the spawner, everything works as expected and rotten flesh continues to accumulate in the ender chest/pouch.  

6) If I travel about eight or more chunks (very approximate) from the spawner, rotten flesh stops accumulating.  I can still see the spawner in the sky at this distance.

7) If I get closer, it starts working again.

Sorry for the long winded explanation.

By similar methods, I did determine that other EnderIO machines such as the farming station do continue to work at long distances with a chunk loader.

Are the mobs just despawning before they hit the ground because no player is near?  I think I have seen something similar to this with minefactory reloaded spawners that does work.

**Comment by czaderak** [comment]
I'm still experiencing this issue in 1.7.10-2.2.8.381, even with spawners not so high in clouds.

I have a really small zombie farm with chunk loader next to it. It works just fine until I leave the server.
