### ISSUE TITLE
World Corruption with Ex Nehilo

### ISSUE THREAD

**Issue by Noxy4u** [SleepyTrousers/EnderIO#1465]
Well this is a serious issue, when using the ex nihilo oak barrels to produce soulsand (putting water and sand in a ex nihilo Barrel that is next to myzel, this error acoures. when using item Ducts from Ender io to insert sand and extract soulsand (top of the barrel to insert, bottom to extrakt) the game closes and the world is corruptet. the onely way to fix that is to deaktivate one of the mods (ex nihilo or ender io) since filling barrels with vanilla hoppers works fine( and other ducts) this may is an error on the side of ender io. maybe the insert/extract is too fast or somwhat like that, im not sure

**Comment by Adaptivity** [comment]
Close? No logs, no feedback.
