### ISSUE TITLE
New ore output preference breaks IC2/GT macerator recipes

### ISSUE THREAD

**Issue by Dominance** [SleepyTrousers/EnderIO#1472]
Simple with newest EnderIO the new preference system seems to be affecting the Macerator recipes. By default there is 0 recipes available for the Macerator for every preference ore listed in core xml. Ive attempted to add it to user .xml to no avail. Recipes are just not there.

**Comment by Dominance** [comment]
:-1:  Sadface

**Comment by Dominance** [comment]
Bump! ?

**Comment by MatthiasMann** [comment]
As the ore dictionary preferences are only used to affect the output of the EIO machines - and do not affect/change anything in the oredict or vanilla recipes itself - it seems very unlikely that this has anything to do with EnderIO.

**Comment by Dominance** [comment]
It has everything to do with EnderIO and or IC2/GT as it does effect industrial crafts macerator recipes. Not my first rodeo and after 8+++++++ hours of dotting I's and crossing T's this is very much a issue that only happens with Ender IO.

**Comment by Dominance** [comment]
I am not sure how this is labeled cannot reproduce. It and its as simple as installing and hitting play. Links again http://www.atlauncher.com/ Installed Beyond Reality any version works :) Now last but not least remove this script https://github.com/Beyond-Reality/BeyondRealityModPack/blob/master/BR1710/scripts/gregtech.zs so that you can reproduce it. Then after you see that everything is broken. Remove EIO and restart to see everything magically start working.

**Comment by tterrag1098** [comment]
It's marked cannot reproduce because I don't have a label for "We do nothing to affect this and I have nowhere to even begin troubleshooting"

**Comment by LeiserGeist** [comment]
To be fair it could be some obscure GT compat issue.

But its a pain in the arse to get a straight answer about any gt bug due to their "issue tracker" being a 600 page long forum topic that your issue gets spammed out in 3 minutes by people asking "hao 2 copper pls"..

**Comment by LeiserGeist** [comment]
(Sorry, can't edit from mobile site)
The issue disappeared for me when I downgraded GT a version or two, which leads me to think its more on GT's end.
The GT devs insist its EIO's fault, the EIO devs insist its not. I don't know what else to add

**Comment by LeiserGeist** [comment]
(Sorry, can't edit from mobile site)
The issue disappeared for me when I downgraded GT a version or two, which leads me to think its more on GT's end.
The GT devs insist its EIO's fault, the EIO devs insist its not. I don't know what else to add
