### ISSUE TITLE
Redstone conduits cause fps drop

### ISSUE THREAD

**Issue by PsionicArchon** [SleepyTrousers/EnderIO#1481]
I've been attempting to track down a source of client lag for several days now. I had a strong suspicion EnderIO conduits were the culprit, especially redstone conduits. 

Example 1: I set up a bundle of redstone conduits here --> http://i.imgur.com/gtgyvly.png

Three of these setups were able to drop the framerate of everyone who entered my base from 60+ to sub 20. 

Monitoring the framerate with an external program will show a constant sudden spike in lag from 60 to 20 over and over again. I tested the above build without the logistics pipes, electric compressor and, shifters. Only removing the redstone conduits alleviated the lag. 

As a test I created this: http://i.imgur.com/Ow3ngik.png

When panning the camera I experienced a significant loss in framerate while the conduits were updating  their lighting effect. You should be able to reproduce this with the above build. For testing purposes I had the timers pulsing twenty times per second. 

I am using version 10-2.2.5.311 of EnderIO with the latest version of Forge. 

I'd settle for a config option to disable the conduit's lighting effect for the time being, unless that already exists and I'm just being stupid.

**Comment by PsionicArchon** [comment]
Just a bit of an update. Liquid conduits are also causing massive fps drops while pumping liquid. 

This setup here is killing the performance of anyone who enters my base: http://i.imgur.com/PkRNU6u.png

Framerate stabilizes while the forge is melting down sand and drops off sharply while the conduits are moving liquid.

**Comment by 6210classick** [comment]
try the Ender Fluid Conduit it does not show the liquid , of course the first and second tier will cause lag because the fluid is showing
