### ISSUE TITLE
Suggestion: Block to disable magnet in radius

### ISSUE THREAD

**Issue by CraigySpider1975** [SleepyTrousers/EnderIO#1496]
I had an idea about creating a block with a radius that automatically turns the Ender IO magnet off, would help so much with growing AE2 seeds when we forget to turn the Magnet off :/

Thanks for reading Craigy.

**Comment by Badcholo** [comment]
Just use AE2Stuff.
It has a block you can grow your seeds in and other much useful things AE2 seems to not want to fix.
http://www.curse.com/mc-mods/minecraft/225194-ae2-stuff

**Comment by HenryLoenwind** [comment]
just BTW: Blacklist (config-based) has been implemented (AE2 seeds are on it be default). Block to turn it off exists: Botania's Solegnolia.

**Comment by Badcholo** [comment]
nice, but i still like AE2Stuff, i never liked the way the seeds had to be grown. Specially with trying to keep a server lag free using clearlag.
