### ISSUE TITLE
Add filter option to Advanced Filter

### ISSUE THREAD

**Issue by quasarea** [SleepyTrousers/EnderIO#1512]
Hi, would be great to have ability to limit pulling and pushing items in a way that one always stays or only one stack is loaded. 

extract => but leave one item
Insert  => just one stack

Thanks, 
q

**Comment by the-vindex** [comment]
@quasarea : I was not able to reproduce this behavior on EIO 2.2.5-331. When I snapshot an inventory, snapshot does show 2 stacks, but when being filled it fills as target inventory as much as possible.

**Comment by quasarea** [comment]
@the-vindex you are right, it was my proposition of how to sort out your request :)

for now I'm using rationing pipes for need as yours Rationing Pipes from extra utilities
