### ISSUE TITLE
[Feature Request] A switch/button

### ISSUE THREAD

**Issue by tjsd** [SleepyTrousers/EnderIO#1514]
So, we all know levers. I want a bit more fancy button with on off state. There was a mod in 1.6.4 that had a switch. Just a small square with a red and green square showing if it was on or off.

Could you please add such a thing? :)
 
It would make my spawner room so much cooler.

**Comment by dominx** [comment]
I second that. The conduit switch has a weird shape and is useless if you're making a flat control panel.
