### ISSUE TITLE
Wireless charger: some type of security card for server play.

### ISSUE THREAD

**Issue by CraigySpider1975** [SleepyTrousers/EnderIO#1528]
To have some type of security card for server play, to stop unwanted players charging and using up your power. Kinda simlur to what AE2 does with the biometric card to allow only players you have the card attached to only, can use your charger :)

**Comment by 6210classick** [comment]
you can change the range in the config file by default it's 24 blocks

**Comment by CraigySpider1975** [comment]
It's not the range this post is about, it's just an idea of something that would be good on a server, because we allow people to come to our base and also true friends on a server, so some type of security card would be a good idea to be able to add your true friends on the server to be able to charge but other people you allow in your base to not be able to charge.
