### ISSUE TITLE
Combustion Generator says it works with all BC compatible fuels and coolants but does not work with TE's Gelid Cryotheum

### ISSUE THREAD

**Issue by iLLHunter** [SleepyTrousers/EnderIO#1544]
Combustion Generator says it works with all BC compatible fuels and coolants but does not work with TE's Gelid Cryotheum
Gelid Cryotheum is an expensive and powerful coolant. It would be great if the generator worked with Gelid Cryotheum and acknowledged its powerfulness.

EnderIO-1.7.10-2.2.5.311.jar

**Comment by 6210classick** [comment]
why ? water is free and infinite so it's useless to use other coolant because the generated power is the same no matter what if doing 2x2 water pool bothers you then use Reservoir

**Comment by tterrag1098** [comment]
Does BC work with cryotheum?

**Comment by drakke1980** [comment]
yes but not IC2s verion

**Comment by iLLHunter** [comment]
Is this fixed? It was closed without comment

**Comment by HenryLoenwind** [comment]
as were over 650 other tickets. comment if this still is an issue in the latest version, I'll re-open those tickets
