### ISSUE TITLE
Alloy smelter does not follow AE2 Interface blocking rules

### ISSUE THREAD

**Issue by drstasis** [SleepyTrousers/EnderIO#1564]
The Applied Energistics 2 Interface block will continue to add items to the Alloy Smelter's input even if the blocking mode is set to "Do not push crafting items if inventory contains items" and there are already items present. The Interface block should be unable to add items to the input if this mode is set and there are items present. This issue is crossposted to the Applied Energistics 2 github.

Using AE2 rv2 beta 1 and Ender IO 2.2.5.311 with Minecraft 1.7.10 and Forge 10.13.2.1230. Issue occurs on a multiplayer server.

**Comment by 6210classick** [comment]
update Forge & EIO then see if the problem still going

**Comment by JeroenVogelpoel** [comment]
Still exists for me with EnderIO-1.7.10-2.2.8.349; might be related to #520?

**Comment by tterrag1098** [comment]
Could you give exact reproducing steps?

**Comment by JeroenVogelpoel** [comment]
Sure.

1. Build AE2 auto-crafting installation with at least 4 crafting CPUs and
prepare patterns for use with ME Interfaces. (for example, 1 cobble to 1
stone)
2. Build 4 alloy smelters.
3. Attach every smelter to AE2 network seperately using thin form ME
Interfaces; making sure each interface is set to blocking mode.
4. Craft 64 stone from 64 cobble.

Expected: Every alloy smelter would convert one cobble to one stone per
time, sorted out over many
Result: Uneven distribution; alloy smelters contain more than one cobble at
a time. Capacitors included or excluded doesn't matter for this behaviour.

Reset the machine to step 3, replacing the alloy smelters with chests.
Craft 64 stone again.

Expected: Every chest would end up containing one cobble.
Result: Every chest contains one cobble.

**Comment by JeroenVogelpoel** [comment]
On that note, the same thing seems to happen with SAG mills as well...

**Comment by momerathe** [comment]
This issue is also on AE's github: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/681

according to them: "Blocking mode is just "do not push items if inventory is not empty" and EiO reports the inventory as empty [even when it isn't]"

**Comment by MatthiasMann** [comment]
EnderIO reports all inventory slots as it should - it's just that some slots can only be inserted, while others can be extracted. But it is always possible to see which items are in which slot.

**Comment by momerathe** [comment]
Well, *something's* not right, as multiple people have this issue, here and on reddit. Obviously, the average user doesn't know who's right and who's wrong, we just hope it gets fixed..

**Comment by Wykks** [comment]
I found a way to overcome this issue by putting a chest between the interface (set to "Do not push crafting items if inventory contains items") and the ender io machine : 

![Solution](http://i.imgur.com/RkvJusM.jpg)

This way, crafts are evenly distributed across all alloy smelter ! :)
