### ISSUE TITLE
Insulated Redstone Conduit suggestion

### ISSUE THREAD

**Issue by tgstyle** [SleepyTrousers/EnderIO#1573]
It would be nice to have a bit more control on the IO, how about an option to invert the signal? This would be nice for cross-mod functions where some things only work on high signal and others on low. Example, a trigger comes in, one mod needs low signal to function, the other needs high. On the output side you can invert it so both turn on with the same trigger.

**Comment by therealeldaria** [comment]
I was googling how I could do this, and I guess I will add my vote for it to be added in the future.
