### ISSUE TITLE
Feature: Show stored liquids in the Dimensional Transceiver

### ISSUE THREAD

**Issue by nzhook** [SleepyTrousers/EnderIO#1594]
The Dimensional Transceiver currently shows items that are incoming/outgoing. Could the stored liquids also be shown.

**Comment by 6210classick** [comment]
does it store liquids in the first place ?

i think it have a buffer of one bucket

**Comment by MatthiasMann** [comment]
The Dimensional Transceiver does not store fluids - if no remote side can accept the fluid you try to pump it - it will not be accepted.
