### ISSUE TITLE
laggy conduits

### ISSUE THREAD

**Issue by deathsiroj** [SleepyTrousers/EnderIO#1612]
hi,

if you put multiple conduits in 1 block in a lot of blocks in a tight space it really eats my fps but not a normal amout like im in a void world and i place a 20 x 10 full of conduit then i go from 1000+ to 10

**Comment by Granik24** [comment]
Maybe same as my issue: https://github.com/CrazyPants/EnderIO/issues/1461

**Comment by tterrag1098** [comment]
Details? Screenshots? Mod list? I can't help you without more info.
