### ISSUE TITLE
Enchanter consumes whole book/quill stack!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#1628]
Putting in a whole stack of book+quill and taking out an enchant consumes the whole stack of book/quill. DOn't think that's supposed to be.

**Comment by tterrag1098** [comment]
Book and quills...don't...stack.

**Comment by Unrepentant-Atheist** [comment]
Oh snap, you're right. I totally forgot I'm running Stackie, to make the unstackable, stackable. Thus causing problem like this. Nevermind. :)

**Comment by tterrag1098** [comment]
Its still a valid problem then. Should be an easy fix.

**Comment by Unrepentant-Atheist** [comment]
Valid or not, Stackie changes a fundamental game mechincs making the unstackable, stackable and/or changing stack sizes around.

Now working around THAT might introduce potential other bugs.
