### ISSUE TITLE
[Feature Request] InvTweaks Support for Vacuum chest

### ISSUE THREAD

**Issue by SnowShock35** [SleepyTrousers/EnderIO#1631]
Hi CrazyPants/tterrag,

I wanted to make a feature request which I think is long overdue which is inventory tweaks support for the vacuum chest.

**Comment by 6210classick** [comment]
since it's storage size is the same as a vanilla single chest i don't think happen unless maybe in future updates if 2 are placed side by side they become double chest 

also i think you need to suggest this to the Author of inventory tweaks mod and not the EIO team

**Comment by tterrag1098** [comment]
All you need to do is add it to the config for it to work. I've done it before.

```
<root>
   <chest class="crazypants.enderio.machine.vacuum.ContainerVacuumChest" row_size="9" large_chest="false" disable_buttons="false"/>
</root>
```

In InvTweaksCompatability.xml

**Comment by SnowShock35** [comment]
Thanks tterrag, the only problem is it's not showing the buttons but the sorting is working. Have no idea why that is :/
