### ISSUE TITLE
Farming Stations are only capable of working 3 levels of TiC ore bushes, adding fourth blocks any harvest of that column

### ISSUE THREAD

**Issue by Barhandar** [SleepyTrousers/EnderIO#1634]
Me and my friend have 7x7x4 oreberry farms, with Farming Station in the middle.
Since the update from 2.2.5.311 to 2.2.6.317, her farming station runs incredibly slowly compared to how it used to be, harvesting every 20th power reduction (seen through UI) or so, while mine refuses to harvest half of the field, only harvesting west side (including bushes north and south from the station itself)

http://i.imgur.com/NHz0wS5.png - looking south-east, half of the bushes are harvested, half are not (light source added for visibility, normally it's dark). Farming station is topped on energy, no capacitor, wooden hoe inside, no axe. Friend's station has both hoe and axe, both wood, no capacitor.

**Comment by hilburn** [comment]
Could you supply some pictures/details of the gui and setup? just helps a bit more with debugging but I'll look into it

**Comment by Barhandar** [comment]
>Could you supply some pictures/details of the gui and setup?

Both farming stations are fed by EnderIO conduits (ender energy in my case, enhanced energy in friend's) from a solar panel, and get items out through actively extracting item conduit and into packager (aluminum nuggets) and Railcraft Metal Chest. Mine additionally drains resulting metal blocks into 4 JABBA barrels and a DSU for aluminum ingots. 
I'll be able to provide screenshots in a few hours, but my farming station's GUI is unmodified - connections are all at "None" and no locks are engaged, and I remember building that station before the locks were implemented. Friend's connection sides are more or less random, but bottom, with conduits, is set to "None".

**Comment by hilburn** [comment]
What items are in the "seed slots"?

**Comment by Barhandar** [comment]
None in either farm, slots are not locked.
It's purely for oreberries and as such wasn't set up for anything else, hoe (and hoe with axe) only getting there because it didn't work otherwise. *Though, apparently, lower side on mine was set to "Push" and I don't remember doing this. Works, or rather doesn't, the same with conduits set to extract instead - it only affects getting items out, not harvesting*

http://imgur.com/OyXiaRB,2zmOHB3,qAqVXQr - mine, friend's, a slighly different position for view of mine - farm is in the center.

My farm has a chunk to itself, but power source is in the other chunk - both are chunkloaded pretty much all the time server is on, and it's full of power. 

My friend's farm is mostly in a single chunk - a single row of oreberries is in another one, but power source (also Solar Flux solar attached through conduits) is in the same one, farm is also full of power now, and the cube it's in is mostly not harvested, except for oreberries which don't have other oreberries over them.

Removing the top oreberry bush on mine (aluminum) causes bushes below to start being harvested.

**Comment by tterrag1098** [comment]
Cannot reproduce this, is it still happening?

**Comment by Bafegox** [comment]
Can confirm issues with the Farming Station and Oreberry Bushes. There doesn't seem to be any clear pattern.
