### ISSUE TITLE
Jump assist from various mods fails to trigger the Travel Anchor using jump to activate

### ISSUE THREAD

**Issue by Cisien** [SleepyTrousers/EnderIO#1635]
Tested the Taumic Tinkerer Kami boots (Boots of the Horizontal Shield) and the botania Globetrotter's Sash.

The Sigil of Haste from blood magic does not cause any issues.

**Comment by 6210classick** [comment]
you can use Staff of Traveling in with travel anchors or any dark steel tool with a  Travel power-up

**Comment by Cisien** [comment]
I am aware of these workarounds. I didn't post this looking for support, but to report inconsistent behavior between mods.
