### ISSUE TITLE
Weird Basic Capacitor bug/visual glitch?

### ISSUE THREAD

**Issue by bookerthegeek** [SleepyTrousers/EnderIO#1647]
When made these capacitors say that the max they hold is 1 million rf as the picture shows
![](http://i.imgur.com/3Z6rQ5y.png)

Then when placed it bumps up to 5million ( only normal capacitors hold this amount)
![](http://i.imgur.com/GWhJqQz.png)

Then once the capactitor that has got over 1million charge in it is picked back up it shows the correct amount of power but with the limit of 1million still
![](http://i.imgur.com/0s2K4qc.png)

Because of this the durability bar also goes a bit weird
![](http://i.imgur.com/59vLxLB.png)

Brought to you by your friends at MyM

**Comment by tterrag1098** [comment]
I can't reproduce thsi at all. What version are you on?

**Comment by bookerthegeek** [comment]
We are using the latest version of The Dark Trilogy
