### ISSUE TITLE
Dark Pick sometimes disappearing when placing blocks (right-clicking)

### ISSUE THREAD

**Issue by DarkStarDS9** [SleepyTrousers/EnderIO#1648]
This (only) happened twice in about 12 hours of gameplay, but sometimes the Dark Pick disappears when you right-click with it to place a block (which is next to it in the hotbar; block-placing is a feature and not a bug, right?)

**Comment by 6210classick** [comment]
wow ! i never knew it does that

**Comment by tterrag1098** [comment]
Sounds like an issue with Inventory Tweaks perhaps? Could you reproduce without it?
