### ISSUE TITLE
Feature Request: NotEnoughKeys API

### ISSUE THREAD

**Issue by Keridos** [SleepyTrousers/EnderIO#1649]
https://github.com/mod-warriors/NotEnoughKeys/tree/dev/src/main/java/modwarriors/notenoughkeys/api

This is an API from NotEnoughKeys that allows Multikey-Keybindings for mods, to have support for keybindings like shift+f or ctrl+k for key presses. Would be awesome if you could add in compatability with that for EnderIO. Ticon and Pneumaticraft already support this.

**Comment by tterrag1098** [comment]
Er...does EIO have any multikey keybindings?

**Comment by Keridos** [comment]
This makes users able to do that, I have not seen any mod that does this, except Thaumcraft with the shift-f combo to unequip focii.

**Comment by tterrag1098** [comment]
Ah, ok then.

**Comment by KevinsCode** [comment]
I think this could be used with the Yeta wrench and having such as Y+E for energy cabling or something
