### ISSUE TITLE
Dimensional Transceiver, no power transmitted

### ISSUE THREAD

**Issue by enkido** [SleepyTrousers/EnderIO#1654]
Ender IO version: EnderIO-1.7.10-2.2.6.317

If two Dimensional Transceiver are set to send and receive power on the same channel, both transceiver accept power at maximum rate but no power gets transmitted. The IO buffer stays empty  and any incoming power lost.

**Comment by 6210classick** [comment]
what are you trying to power with it ? also they store 250k each for a local buffer and use 10/rf tick at all time with 5-10% power loss

**Comment by enkido** [comment]
I tried in a test world, no devices just two transceiver with one connected capacitor bank each. Both transceiver draw from the connected capacitor bank at -640 rf/t

**Comment by 6210classick** [comment]
if you want then change this in the config file

 # Amount of energy lost when transfered by Dimensional Transceiver; 0 is no loss, 1 is 100% loss
    D:transceiverEnergyLoss=0

you might want to use higher tier conduit or directly put the transceiver next to the bank any side works

**Comment by enkido** [comment]
this is not about energy loss, both transceiver draw from the connected banks at maximum rate, but no power gets transmitted. if both io buffers are full no power should be transmitted. But in this case both io buffers stay empty.

**Comment by 6210classick** [comment]
is one set to send and other is receive ?

**Comment by enkido** [comment]
I know it is strange, but both transceiver are set to send and receive on the same channel.
I can upload same screenshots to visualize the setup.

**Comment by 6210classick** [comment]
don't' set one of them to both send and receive at the same time from the same channel

set one to receive and the other to send it's just simple as that

**Comment by Azougon** [comment]
I have a problem similar to this. I've got a dimensional transceiver in the nether and one in the overworld. The one in the overworld has a full internal buffer and a full send/receive buffer. But when i tell the one in the nether to receive on the same channel nothing happens

**Comment by MatthiasMann** [comment]
@Azougon make sure both sides are chunk loaded

**Comment by Azougon** [comment]
Woop,  thanks, I was using the ender-thermic pump so I assumed it would work

**Comment by MCTyler** [comment]
Old issue but I was googling a solution and you meantioned chunloading....Seems IC2's Chunk loader interferes with he operation of the Transceiver. Break the IC2 chunkloader then re create the channels on the transceivers and all works fine....MC 1.10.2
