### ISSUE TITLE
Insulated Conduit not working properly

### ISSUE THREAD

**Issue by MRuth** [SleepyTrousers/EnderIO#1656]
While trying to use some insulated conduits, I noticed that adjacent blocks next to the block that is supposed to be activated were actually being powered instead of the right block.  You can see this in the picture below.  I am currently using version 1.7.10-2.2.6.317
![2015-01-12_21 35 48](https://cloud.githubusercontent.com/assets/3927478/5715748/5eeb30e2-9aa4-11e4-9d45-91e12ba9b817.png)

**Comment by tterrag1098** [comment]
This is working completely fine on my end.

![](http://puu.sh/es1xN.jpg)

**Comment by MRuth** [comment]
Could it be a possible Mod Interaction bug?

**Comment by kurokuno** [comment]
if you swap the band colours in reverse does it still happen Ruth

**Comment by MRuth** [comment]
Yes, I'll send you some pictures when I get back to my computer

**Comment by MRuth** [comment]
Sorry for the late response, got a little busy with classes and work... Here are some more pictures that hopefully helps

![2015-01-18_00 26 47](https://cloud.githubusercontent.com/assets/3927478/5791645/706b1c20-9ea9-11e4-9e99-ff904581d867.png)
![2015-01-18_00 27 03](https://cloud.githubusercontent.com/assets/3927478/5791647/70700c76-9ea9-11e4-8602-9fd43bb964b8.png)
![2015-01-18_00 27 20](https://cloud.githubusercontent.com/assets/3927478/5791646/706bf5aa-9ea9-11e4-9d24-6aa7b8afcbaa.png)

**Comment by MRuth** [comment]
After further testing, I believe this issue is actually related to a Remote IO bug.  If there are no other issues, please feel free to close.

Thanks
