### ISSUE TITLE
exp bug

### ISSUE THREAD

**Issue by jlsafof** [SleepyTrousers/EnderIO#1658]
http://paste.atlauncher.com/view/d9f773ad Log

The bug consist of a exact spot on a server with an almost infinite amount (as of me writing this its still going) of exp, i collected well over 300 exp. 
The bug only happens if you have an electromagnet active on your hotbar.

**Comment by jlsafof** [comment]
Heres an update.
https://www.youtube.com/watch?v=h-x1lw_Lz2Y
a youtube video with proof of the bug

**Comment by 6210classick** [comment]
so when you stand next to MFR spawner this happens ? or next to XP Obelisk ?

is the Spawner active ? if so what mob does it spawn ?

what version of EIO are you using ? what FORGE version are you using ? what MFR version are you using ?

**Comment by jlsafof** [comment]
mod pack version 2.2.2  http://www.atlauncher.com/pack/SkyFactory 
all mods including optional mods except: Infinite Inventories.

minecraft 1.7.10
Minecraft Forge	10.13.2.1277
Ender IO	2.2.6.317
MineFactory Reloaded	2.8.0RC6-9

New update Video: https://www.youtube.com/watch?v=4AtHgh1nhik

from powered spawner (blaze)
to mfr (using collected essence
to Cursed earth spawner

**Comment by tterrag1098** [comment]
Could I please have a copy of your map?

**Comment by jlsafof** [comment]
Can't its a server and sometime has passed since then, the bug has vanished
but I think its due to a server restart.
The video on my channel is all I can give.

**Comment by shortybsd** [comment]
I have my own Modpack I made and have the same issue. I'm sending you a link to my pack as well as world so you can debug it. What I have found out it is always a 2x2x2 area where the infinite experience comes from. In those area's there was nothing out of the ordinary generated (example Thaumcraft alters)

**Comment by tterrag1098** [comment]
What's the exact coords? I want to see if this happens on a blank map.

**Comment by shortybsd** [comment]
On my specific world the two I have found so far are the following:
x2061, z948, y70
x2086, z937, y64

**Comment by shortybsd** [comment]
Fixed in version 2.2.8! Thank you very much tterrag!

**Comment by tterrag1098** [comment]
Tracking under #2690
