### ISSUE TITLE
Ender IO Omniwrench Integration

### ISSUE THREAD

**Issue by nhave** [SleepyTrousers/EnderIO#1662]
Hello im the author of NHAVE's OmniWrench and i would love to see a way of handling the different conduits with my wrench. 

It could be done by expanding the "ITool" interface with
"ConduitDisplayMode getDisplayMode(ItemStack stack, EntityPlayer player);"
"boolean shouldRenderUI(ItemStack stack, EntityPlayer player);"

```
public interface ITool {

  boolean canUse(ItemStack stack, EntityPlayer player, int x, int y, int z);

  void used(ItemStack stack, EntityPlayer player, int x, int y, int z);
  
  boolean shouldHideFacades(ItemStack stack, EntityPlayer player);

  ConduitDisplayMode getDisplayMode(ItemStack stack, EntityPlayer player);

  boolean shouldRenderUI(ItemStack stack, EntityPlayer player);

}
```

**Comment by tterrag1098** [comment]
There are plans for this. Would be a new interface entirely.

**Comment by tterrag1098** [comment]
What I've done for now is move shouldHideFacades to a new interface (but ITool extends this interface as to not break API), and I will be adding a new interface, IConduitControl. This interface will do what you suggest. I was thinking that the setting of display modes would be automatic, i.e. hook into the existing shift+scroll mechanic of EIO and change some NBT values that you need not worry about. If you would like more control I can do that as well.
