### ISSUE TITLE
New Machine: Worker Joe

### ISSUE THREAD

**Issue by MinoCraft** [SleepyTrousers/EnderIO#1663]
Hello,

I play with Ender IO since the beginning and the evolution of the mod is magnificent ! 
I don't play with Thermal Expansion and in Ender IO I think that it misses a block with the same functionality which the autonomous activator.
The mod have Killer Joe and can you added Worker Joe ?
The block is capable to right click or left click, sneaking or not, he have a buffer to stock blocks, liquids. In brief, capable of automating the daily tasks in MineCraft and push the automatism ! 

The block can place block, use wrench, pickaxe, shovel, hoe, a bucket of water (to automate Growthcraft rice farm for example), use essence berry from Tinkers Construct or what the player want.

Worker Joe can consume energy or Nutrient !
I think it's a good addon for Ender IO !

Thanks in advance ! 

Sorry for my bad english, I'm french and I have some difficulties to write what I think, in English ;)

**Comment by 6210classick** [comment]
Awesome IDEA i  would also like to suggest to make it Blast Resistant along side with 
Killer Joe too
