### ISSUE TITLE
Killer joe allows light to pass through

### ISSUE THREAD

**Issue by kurokuno** [SleepyTrousers/EnderIO#1666]
right now joe allows light to pass through him as a block this causes some rather bad compact spawner issues such as having to make it look butt ugly to make it work "i understand if this is intended and have no problems accepting this choice" was just wondering if it would be to much to have it changed

**Comment by 6210classick** [comment]
you could just place him one block backwards he can hit through walls

**Comment by kurokuno** [comment]
hmm i did not know that looking at the bug fix log i could swere somone reported that as a bug and it was listed as fixed so i just assumed from that it would not work =P my bad

**Comment by tterrag1098** [comment]
That no longer works

**Comment by 6210classick** [comment]
just tried it in the latest EIO + Forge it works fine PLZ CrazyPants & tterrag1098 don't change this because most auto wither & mob farms rely on killer joe hitting through walls

**Comment by tterrag1098** [comment]
Well those farms will have to change. It was broken behavior.

**Comment by tterrag1098** [comment]
I think I might implement this by allowing facades to be placed over the killer joe, not sure how much sense that would make though...

**Comment by MatthiasMann** [comment]
Maybe give it a carpet as a curtain to put behind himself
