### ISSUE TITLE
Query/Suggestion: Shiny Dust?

### ISSUE THREAD

**Issue by jmc666** [SleepyTrousers/EnderIO#1675]
When trying to make enderium is it meant to still require a TE pulverizer to get shiny dust? I'm playing on the Resonant Rise pack with the 1.7.10-2.2.6.317 version, so if its just something they've done apologise for wasting time. 
Assuming I/they haven't derped (and fearing any use of MineTweaker with a passion) could the recipe for Ferrous in the SAG Mill be changed to give a 10% for shiny instead of the 3rd ferrous dust?
Thanks for the awesome mod. :D

**Comment by 6210classick** [comment]
hit U on shiny dust and keep changing pages until you see the sagmill page i think there is a chance of getting it from some ore than that it self

**Comment by iTitus** [comment]
Maybe you have to look for Platinum?

**Comment by Adaptivity** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/master/resources/assets/enderio/config/SAGMillRecipes_Core.xml#L573
@tterrag1098 close?
