### ISSUE TITLE
Feature Request: Channels for Fluid Conduits

### ISSUE THREAD

**Issue by Keridos** [SleepyTrousers/EnderIO#1678]
Channels for fluid conduits would be very nice to allow further compaction of builds.

**Comment by 6210classick** [comment]
Ender Fluid Conduits [ the 3rd tier ones ] have a 5 filters in/out per side isn't that enough for now ?

**Comment by DrakeOfTheWest** [comment]
Yes that is a great thing. Priorities, however, would be even greater, so one could void overflow from some sources. Please, please :)
