### ISSUE TITLE
Paintable machines

### ISSUE THREAD

**Issue by Drullkus** [SleepyTrousers/EnderIO#1682]
I'm just sort of thinking, why not make machines paintable?

I'm thinking the base block would be painted, but the machine details would be rendered on the front of the painted block.

**Comment by 6210classick** [comment]
great idea but i don't think the last part is doable can you imagine a Slice & Spice painted as glowstone and the result is glowstone with big red eye glowing when the machine is working so no it's probably not gonna happen any time soon in 1.7.10 maybe in 1.8 updates though
