### ISSUE TITLE
Item Conduit does not check slot validity before inputting

### ISSUE THREAD

**Issue by MikeLydeamore** [SleepyTrousers/EnderIO#1685]
As the issue says.
Other pipes such as the transfer pipe (and also the vanilla hopper) check isItemValidForSlot before inserting the item. It appears as though EnderIO (and Buildcraft, actually) don't check this.
This leads to some interesting interactions, for example you can get items with different ID's into a filing cabinet.

**Comment by MatthiasMann** [comment]
That is strange - as EIO doesn't seem to insert non valid items into other machines which have restrictions on what items they accept.

**Comment by 6210classick** [comment]
you can use different type of filters to blacklist or white-list items also you can right click on the conduit with that item it will tell you where is it gonna end up exactly by default the nearest machine or  inventory is it's first destination you can also set a higher priority the highest number is where item will be put into it

 but indeed it's strange what version of EIO & FORGE are you using ? what's your set up looks like ? if you are using machines from other mods like TE then what version are you using ? please provide more information

**Comment by MikeLydeamore** [comment]
Using EnderIO 2.2.6.317 and Forge 1277, and v1.14 of Ex Astris (which has this method incorrectly returning null in the Auto Hammer). Hoppers, transfer pipes etc will not insert, but EnderIO conduits will.

What I expect (admittedly without searching too deeply) is that the conduit is checking canInsertItem, but not isItemValidForSlot (as this is what I was doing in Ex Astris).

It actually appears as though the Filing Cabinet thing is not the fault of EnderIO, so ignore that one.

**Comment by tterrag1098** [comment]
Ok after further investigation, this issue is actually a bit of a gray area.

EIO checks `ISidedInventory.canInsertItem` which passes the slot and itemstack, so it is possible for some ISidedInventories to add a check to `isItemValidForSlot` inside this method. The javadoc on `canInsertItem` supports this, saying 

>Returns true if automation can insert the given item in the given slot from the given side. 

Therefore I'm not sure I want to *hurt* performance of item conduits to fix what appears to be an API implementation bug.
