### ISSUE TITLE
[Suggestion] Add support for the AE rv14 Spatial API

### ISSUE THREAD

**Issue by sciguyryan** [SleepyTrousers/EnderIO#169]
Hey guys.

AE rv14 (currently in beta) has a new system for allowing tile entities to be moved with its new Spatial API. It is opt-in only and any TE's that aren't listed will not be moved.

Most simple TE's should be movable without using the API but via an intermod message:

FMLInterModComms.sendMessage( "AppliedEnergistics", "movabletile", "appeng.common.AppEngTile" );

More advanced ones will need to register with the API that can be found along with the download here:

http://ae-mod.info/Dev/

Thanks in advance.

**Comment by Adaptivity** [comment]
@tterrag1098 close? Discussion can be continued here: #1067 if needed.
