### ISSUE TITLE
Capacitor stuck output mode with tesseract

### ISSUE THREAD

**Issue by slebreton79** [SleepyTrousers/EnderIO#1697]
Capacitor will stay on input with a tesseract attached.  When you cycle through the mode (input,output disabled etc)  once on input and stop it switches back to output only
versions:
forge: tried version 1230 through to 1286
EnderIO-1.7.10-2.2.6.317
CoFHCore-[1.7.10]3.0.0B9-40
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-13

No other mods installed

**Comment by 6210classick** [comment]
downgrade EIO , the current version uses a new RF API that most mods doesn't even have it

also EIO has it's own version of tesseract called dimensional transceiver try it out

**Comment by tterrag1098** [comment]
@6210classick please stop suggesting people downgrade. It's not helpful and it doesn't solve the issue.

**Comment by 6210classick** [comment]
@tterrag1098 i apologize for that but it's really one of the few solution that works because mods don't get updated as fast as EIO so the problem isn't coming from it but rather TE isn't updated again i apologize

**Comment by slebreton79** [comment]
I do have it working with latest Enderio now but with a specifc version of TE.
CoFHCore-[1.7.10]3.0.0B9-40
ThermalExpansion-[1.7.10]4.0.0B6-16
ThermalFoundation-[1.7.10]1.0.0B3-8
