### ISSUE TITLE
Enhancement - Sag Mill Settings akin to Alloy Smelter Settings.

### ISSUE THREAD

**Issue by ShadowsVengeance** [SleepyTrousers/EnderIO#1705]
Maybe if there was an option for "ore only" (and maybe other settings) in the SAG Mill.  I think it would be cool, and very functional with item conduits' priority feature.

**Comment by 6210classick** [comment]
i don't get it you want the sagmill to do the ores only ? can you give an example of how is it gonna be used ? aside from putting any item filter inside the conduit to make sure that it only do ores

**Comment by ShadowsVengeance** [comment]
I actually don't know why i left such a small comment, I meant to include an example.

Maybe if you were bringing in items from your quarry, you want only the ores to go to the sag mill to double ores, but you don't want coal, certus quartz, etc. to go into the sag mill and clog up your system. Even more with this example, if you are bringing in items from your quarry and mob farm, you don't want your blaze rods and bones to go into the sag mill.

Maybe just early game before you have enough resources for multiple machines to support multiple filters.

**Comment by kurokuno** [comment]
you can do this rather easy with just 1 filter and a buffer chest of some format have all the ores buffer into 1 storage then have them output into multiple machines then back out into your sorting making this very inexpensive

**Comment by 6210classick** [comment]
so you want an internal filter ?

as kurokuno said use filter a normal filter has 5 slot , advanced has 10 , existing item filter has at least 27

**Comment by ShadowsVengeance** [comment]
Well,  kind of like what's acheivable in the alloy smelter,  not super
important,  but would be nice.

**Comment by MatthiasMann** [comment]
The Alloy Smelter will also smelt coal into graphite when you have BigReactors installed.
And if you have one of these zombie flesh to leather smelting mods ...

You can't do what you want without using item filters.

**Comment by ShadowsVengeance** [comment]
Okay,  okay,  i was just saying it could be a useful feature for some.

**Comment by 6210classick** [comment]
now i get it you want 2 modes one for crushing only ores and one for everything else right ? it can be done if but i don't see why it should setting up filters and and routing conduits can be really fun and creative if you know how to do it
