### ISSUE TITLE
Ender IO item conduits are ignoring item filters (advanced and basic) 

### ISSUE THREAD

**Issue by Gregorio21** [SleepyTrousers/EnderIO#1713]
I set up an ender quarry and connected it to a tesseract, the I hooked up some item conduits to the tesseract in my base, that went into an obsidian chest, then later I tried to add a trash can and item filters so that only stone and sandstone would go to the trash can and everything else went to the chest, but all of the items are still going into the chest, and when I click on the pipe with a piece of stone (which shouldn't be able to go in) it says it can go in.

**Comment by MatthiasMann** [comment]
Post screenshots of how you set it up - also include which EnderIO version you use.

I have used item filter, priorities and sticky mode a lot - and it always did what it should.

**Comment by Welshtramp** [comment]
Also had issues with 2.2.6.317 and Item filters, first found in the new buffers, it seems that the machine setting will override the filters. so if I set a machine to push, It will push everything and ignore the filter.

**Comment by tterrag1098** [comment]
Item conduits aren't inventories, I don't see how push mode could interfere, but I'll have a look.
