### ISSUE TITLE
Adjust Sag Mill Recipes to similar Machines.

### ISSUE THREAD

**Issue by OldOpa** [SleepyTrousers/EnderIO#1714]
I experience it quite a lot. For example you can't process shiny dust from Ferrous Ore. Also other recipes are quite different to (e.g. Thermal Expansion Pulverizer). It would be great if you adjust the recipes from other mods (ore processing, ...) to those given by the machines of said mod, because it is quite annoying to redo them every time.

**Comment by 6210classick** [comment]
you can do that by editing SAGMillRecipes_User , read SAGMillRecipes_Core to learn how to add or modify a recipe

**Comment by OldOpa** [comment]
I know, but I find it annoying to change it so often. I don't really like to have couple of different machines to complete the same task. That is why I love the Thermal Expansion integration with the Enderium Base - you don't have to setup another machine to craft it. 
Have there a machine to process this ore, there another machine to process another ore. 
I just want to mention this small unbalance between the mods and I know that you as the modders try to have many mod integration and a balanced mod.

**Comment by hilburn** [comment]
If you provided your modified User recipe file, we could the integrate the missing recipes into Core much more easily

**Comment by OldOpa** [comment]
I do not know if you can read it. If you can't read it please let me know and suggest another file upoad.

https://drive.google.com/file/d/0BymeShgCWcA1N1lnSDBwNHc0ZnM/view?usp=sharing
