### ISSUE TITLE
Hunger Overhaul Right Click Harvest Support

### ISSUE THREAD

**Issue by Choonster** [SleepyTrousers/EnderIO#1716]
Hunger Overhaul adds the ability to right click crops to harvest them without breaking the block (implemented [here](https://github.com/progwml6/HungerOverhaul/blob/master/src/main/java/iguanaman/hungeroverhaul/util/IguanaEventHook.java#L318-L401)). It would be nice if the Farming Station knew to right click crops (that extend BlockCrops) when Hunger Overhaul is loaded.

I could look into opening a pull request for this, the tricky part will be collecting the drops from the world  (though World#getEntitiesWithinAABB will probably work).

**Comment by Barhandar** [comment]
Same for HarvestCraft since it has the option for right-click harvest. Currently Farming Station sometimes removes the crop, though most of the time it correctly "replants".

**Comment by StarkRG** [comment]
Ideally it would do this without the need for a hoe.
