### ISSUE TITLE
[Minor] Many render "bugs" in EnderIO

### ISSUE THREAD

**Issue by TheJulianJES** [SleepyTrousers/EnderIO#1718]
It's a minor bug: Most machines render wrong as thrown item, in the hand, in the inventory and more.
Minor minor bug: 1. EnderIO machines face to the wrong way in the inventory, should face to the right.
2. Machines as item render too far from the "shader".
3. Some machines render large in the hand.
4. Some machines render away from the hand.
5. Machines render too far up in the inventory.
6. Some Machines in the F5 mode render wrong.
7. More, probaly ;)

Screenshots: http://imgur.com/a/G2ooA
Those are minor bugs but they are bugs ;)! Also sorry for my bad English, I'm German!

**Comment by MatthiasMann** [comment]
Provide details - which machine is affected by what.
Also a screenshot for each kind of issue would help.

**Comment by TheJulianJES** [comment]
@MatthiasMann I can't to all details since almost every is affected. Screenshots: http://imgur.com/a/G2ooA

**Comment by TheJulianJES** [comment]
I will try to fix the most parts and create a PR in the next few days ;)
