### ISSUE TITLE
Fortune Machine

### ISSUE THREAD

**Issue by OldOpa** [SleepyTrousers/EnderIO#1724]
Maybe add a expensive machine that will fortune ores inside a container (not in world like you can do with Autonomuos Activators). The crafting recipe and processing cost could be quite expensive. Also maybe you can use enchanted books in the recipe and need special upgrades to go up to fortune three.

**Comment by OldOpa** [comment]
Maybe as a multiblock structure with two tanks on the side of the machine containing liquids that influence the machine in its efficiency. Also adding vibrant crystals and/or pulsating crystals, that will be consumed and last for x amount of tasks, to increase the fortune level (maybe even  guaranteed 3x ore processing)

**Comment by MatthiasMann** [comment]
You can put flint or dark steel balls into a SAG Mill to get a higher chance for bonus outputs for processing ores.

**Comment by OldOpa** [comment]
I know, I thought it would just be an enhancement for middle game as the Sag Mill can be used early game already. Also the main aspect of my idea was the fortune ores not really 3x ores as it was just a addition the modders could make. 
My Idea in the second comment was just reffered to the liquids that you'd put in the tanks. If you have two kind of liquids ore trippling is possible, while providing Liquid Xp (like MFR) with some other liquid will yield fortune (additional fortune tools provided?).
Because most mods have already 3x (or even 5x) ore processing and I thought that EnderIO (although with the dark steel ball greatly increased) doesn't have a proper way to tripple your ores, just to have some extra output.
I would greatly appreciate it if my idea would be added in a similar way because in my builds, I just set up a automated way to produdce Dark Steel Balls and let the ores process through. Adding some kind of similar machine will increase the interest in advanced ore processing with EnderIO middle to late game and add some nice features to the other middle and late game stuff EnderIO provides already.

**Comment by MatthiasMann** [comment]
If you would test the SAG Mill with dark steel balls you would see that you get on average 3x ore.

**Comment by OldOpa** [comment]
Well I tested it as I never really looked at it in depth and working with actually probabilities. It was just a idea that you don't have just machine that will fortune ores, furthermore it would have some other uses. 
Then maybe going back to the original idea, throwing other thoughts and suggestions into the bin.
