### ISSUE TITLE
Electromagnet Lag

### ISSUE THREAD

**Issue by devryb** [SleepyTrousers/EnderIO#1736]
The electromagnet seems to be causing huge lag spikes and timing out most people from the server

http://puu.sh/eUaTH/accd48d50e.png

Version: 1.7.10-2.2.5.311 in the Direwolf20 1.0.3 pack

**Comment by tterrag1098** [comment]
Just how many items are near the person with it on? Seems the cause here is just too many items, not really anything to do with the efficiency of the magnet.

**Comment by Badcholo** [comment]
I'll prob end up disabling the Magnet cause it's causing me massive lag as well, i use the atomic disassebler from mekanism and that thing mines super fast. is there any way to craft maybe a bag that can catch all those items?
