### ISSUE TITLE
Ender fluid conduit filters ignoring black/white list.

### ISSUE THREAD

**Issue by SubsterNL** [SleepyTrousers/EnderIO#1754]
When exporting into a drum (and probably anything else), blacklist/whitelist fail to prevent the wrong types from getting in the drum. Especially when some other fluids are also being transported and are already in the conduit.

Version EnderIO-1.7.10-2.2.7.329

**Comment by MatthiasMann** [comment]
Can you include a screenshot of your setup and the filter settings?

**Comment by SubsterNL** [comment]
Well I since then removed those machines... But it is basically 2 columns of 3 vat's eacht.. 3 producing hooch and 3 producing fire water... With the correct filter settings (only export fire water), it still put water into the drum... Checking the filter settings, they only had firewater whitelisted.. Put down another new drum... Again, exported water into it.

**Comment by MatthiasMann** [comment]
I tested it again - and I the filter work as expected.
Are you sure that you don't have any additional connections (eg from the side) to your drum?

**Comment by SubsterNL** [comment]
Yes no other connections to the drum... There are multiple fluids in the ender fluid conduits though.. Like the water, hootch and fire water that go between the vats but all filters have been set correctly.. It will still poor water in a new empty drum instead of the firewater.. Unless ofc you use a drum with already a bucket of firewater in it.

**Comment by MatthiasMann** [comment]
I have done another test with several drums, white listed insertion filter and many different sources. I had conduits extracting fluid, tanks pushing fluid etc.
All tests have shown no error so far.

Unless you show exactly your setup and how to reproduce this - this issue will be set as "can't reproduce"
