### ISSUE TITLE
EnderIO wither skeleton drops unaffected by beheading modifier

### ISSUE THREAD

**Issue by AmishInvader** [SleepyTrousers/EnderIO#1759]
I'm not sure if this is intended or not, but enderio wither skeletons from powered spawners being killed by a beheading TiCon weapon doesn't increase the chance for skull drops.  Also, they don't drop necrotic bones.

**Comment by tterrag1098** [comment]
@hilburn

**Comment by AmishInvader** [comment]
Also, was #1366 fixed? That still seems to be an issue.
