### ISSUE TITLE
Existing item filter allowing items in that do not pass the filter.

### ISSUE THREAD

**Issue by Euius** [SleepyTrousers/EnderIO#1765]
An "existing item filter" setup as follows:

![2015-01-24_18 05 09](https://cloud.githubusercontent.com/assets/5036506/5889909/aefe50e8-a3f3-11e4-97bd-80894a2a41f9.png)

![2015-01-24_18 05 07](https://cloud.githubusercontent.com/assets/5036506/5889910/b3ed7908-a3f3-11e4-84b3-7410b70c6956.png)

Still lets in extraneous items

![2015-01-24_18 05 04](https://cloud.githubusercontent.com/assets/5036506/5889911/bcd0b21a-a3f3-11e4-8215-0ca9bc88a2d2.png)

**Comment by MatthiasMann** [comment]
I tried to reproduce it - but from the items in your last screen shot only the enchanted chain mail armor did get past that filter. This behavior is correct as enchantments are NBT which are ignored in your setup.

The only issue I found is that the snapshot feature has issues with double chests - which I filed as #1768.

**Comment by Euius** [comment]
FWIW, this setup has all sorts of weirdness.

Mob grinder dumps into source chest.  Source chest has an advanced filter blacklist with only enchanted books in the list (Ignore NBT Data).  Chest 1 is configured as above, Chest 2 is configured with a different existing item filter.  The combined filters of chest 1 and chest 2 doesn't quite represent all items, but that was the intent. 

Chest 1 seems to work as expected. No armor/tools/weapons are getting into that chest.  Neither Chest 1 nor Chest 2 accepts enchanted books, but Chest 2 is receiving enchanted books even though both the output blacklist and the existing item whitelist should stop it.  Chest 2 is also receiving sticks which isn't in either list.

Stopgap solution is to set Chest 2 to both input and output, which causes all the extra material to be sent to Chest 1.  Since the end-intent was for Chest 2 to be a trashcan, this is less than ideal.

EnderIO-1.7.10-2.2.7.325 btw

**Comment by ShadowCabalist** [comment]
I am having a similar issue i think.  I am using the Grinder from MFR to run a cursed earth farm.  Everything works well except the item conduits will not extract the enchanted chain mail.  It will not accept it directly from the Grinder, thereby bringing the effort to an abrupt stop.  When using a chest as a buffer, the enchanted chain mail simply accumulates in the chest.  The regular chain and everything else happily goes along without a hitch.  .

**Comment by MatthiasMann** [comment]
@ShadowCabalist I'm using this filter a lot in my builds and so far I never had any issue. So I'm assuming what you are observing is a configuration issue - you need to provide details about your setup.

**Comment by ShadowCabalist** [comment]
I am sure it is on my end, we are using FTB infinity with Mystrcraft removed and;

Server
 - cauldron-1.7.10-1.1388.1.0-server.jar

Plugins
- Essentials_2.13.1.jar
- EssentialsChat_2.13.1.jar
- EssentialsGroupManager.jar
- EssentialsSpawn_2.13.1.jar
- Multiverse-Core-2.5.jar
- Multiverse-Portals-2.5.jar
- Vault-1.4.1.jar

Specifically my problem is trying to extract the drops from a cursed earth mob farm.  I am just extracting with an ender io item conduit.  It is set to extract without redstone signal and there is no filter or upgrades on the conduit.  The exact problem is that the conduit will not extract enchanted chain mail from either the grinder or a chest.  Nonenchanted chain mail and all other items are handled without a problem.  I understand that with a nonstandard setup, that i am probably causing my own problems and am living with it.  I just though the information might be of some use to you.  Remember also the pack includes fastcraft-1.21,

**Comment by MatthiasMann** [comment]
@ShadowCabalist again - as written already stated - enchantments are NBT data - so you need to ignore NBT to extract also enchanted armor.

And with providing details I meant things like screenshots of how you configured your filters - not which mods are part of your pack. It is very unlikely that other mods affects the functionality of the item filter.

Also if you are claiming that it won't extract enchanted items even without filters installed in both extract and insert side - then this is clearly not the same issue as the original report you highjacked - make a new report for that.
