### ISSUE TITLE
Farming station duplicating seeds with upgraded mattock when config turned off + charge item filter not pulling mattock from farming station

### ISSUE THREAD

**Issue by Cephyric-** [SleepyTrousers/EnderIO#1776]
I created a system that used Tinker's Construct mattocks with a flux modifier (changes the tools to use RF instead of durability) that would automatically alternate between 2 mattocks and recharge themselves. When the system started to level up the mattocks (Iguana's Tinker's Tweaks automatic level up modifiers) at some point it gave it an upgrade that caused seeds to duplicate 100% of the time (I am banking on it being the luck modifier).

List of modifiers are as follows: http://gyazo.com/7c312b6a6a151ae9ac1affcd0eb99c2f

The second bug I found is that the "charged" item filter does not function within farming stations. I have the system set up to pull the mattocks from the farming station when they have 25% or less charge, swap with the fully charged mattock waiting in a chest and recharge the used mattock. Every part of the system functions except pulling the mattock out of the farming station when below 25% charge. You can see in the above screenshot that the mattock has < 25% charge remaining.

Setup of conduit: http://gyazo.com/6a8a93f3435300a4c47907764aaa54b3
Position of conduit relative to farming station: http://gyazo.com/568074c4cdddb53588a7e8635ee30347
Mode of farming station: http://gyazo.com/b8116b7f779942fd6f48a4ab9ed61368

**Comment by MatthiasMann** [comment]
It seems that it's currently not possible to extract the tools from the farming station.
I'll have a look at that soon.

**Comment by MatthiasMann** [comment]
The issue is that once I allow pulling out tools - existing setups will fail to work. The only way I can think of to solve this would be to add an option in the farming station UI to allow pulling out tools.

**Comment by Cephyric-** [comment]
Maybe add it as a flag that is only valid when the charge item filter is in a conduit attached to the farming station, since I can't see any other reason to want to pull out hoes or axes from the stations unless they are powered by RF or similar and need re-charging

**Comment by MatthiasMann** [comment]
What about eg TiC tools which can break and then be repaired etc? I don't like this kind of hard coding.

**Comment by Cephyric-** [comment]
Fair enough. a "mode" on the farming station (as on modes you can configure to faces, like pull and push) that only targets tools could also work. In this way existing setups can continue to function, with people who want to use a setup that recycles tools being satisfied too.

Further information about the other issue I mentioned: I managed to make a 2nd mattock that is exactly the same except it didn't have the luck modifier on it and it didn't give seed drops. Looks like it is the luck modifier (fortune) in TiC that is either communicating with the farming station weirdly and ignoring the config option, or luck on those tools in general

**Comment by tterrag1098** [comment]
I assume you are getting this issue with magical crops? They have a crappy implementation of getDrops, we are passing them the fortune modifier as expected and they are duping the seeds. Out of my hands.

**Comment by Cephyric-** [comment]
Oh derp, yeah sorry that totally skipped my mind. I'll send that half of the bug report to Mark
