### ISSUE TITLE
[New Machines] Taking care of passive mobs

### ISSUE THREAD

**Issue by reznorms** [SleepyTrousers/EnderIO#1788]
Since the mod already include a farming station, Is it possible to have a few more machine to breed animals and like that? I know other mods have them already but I really love how machines works in EnderIO :)

- Breeding Station: Feeds animals, and after a while kills adults that are no more in "love" status. With an option to set how many adults leave around for further breeding. Probably, should also check if there are too many mobs in its range and stop breeding to prevent lag.

- Rancher: this should just get milk from cows and wool from sheeps. Maybe two different machine?

- Fishing traps/Autofisher?

**Comment by JelmarG** [comment]
I've also thought about suggesting something like this, but hadn't gotten around to it.

For a 'Breeding Station', though, be careful that it doesn't become a magic block that can do everything, that just makes it too easy.

**Comment by reznorms** [comment]
Thats why I suggested the rancher as separate block(s). The farming station plants and harvest crops, a block that feeds animals and kills them is more or less the same thing. If you want to make it a bit more harder to use to balance things, maybe make it use nutrient distillation (like the killer joe) and RF at the same time?
