### ISSUE TITLE
Killer Joe can't use Tinker Tools

### ISSUE THREAD

**Issue by grizzlyatoms** [SleepyTrousers/EnderIO#1794]
Not sure if it's a bug or not, could be the latest tinkers as well, but my killer joes won't use any tinker tools. I can't seem to get any heads to drop as well and not sure why.

**Comment by tterrag1098** [comment]
Not a bug, but I do plan to add support for a sword whitelist in the future. Currently it has to extend ItemSword.

**Comment by grizzlyatoms** [comment]
Ah Ok, what about my issues with heads? I've tried all kinds of swords from
vanilla, Redstone arsenal, botanic ect, with different enchants, vorpal,
and still can't get a single head to drop. Vanilla heads that is. Only head
that drops is EIO enderman heads. Any advice on what I should try? I know
in previous versions they dropped from Joes killing sprees but not now.

**Comment by tterrag1098** [comment]
Um, in vanilla heads don't drop. Needs a custom mod that adds that.
