### ISSUE TITLE
[Suggestion] Painter setting to auto-eject original block

### ISSUE THREAD

**Issue by DrakeOfTheWest** [SleepyTrousers/EnderIO#1800]
As the title states I would like to be able to set the painter so that it automatically ejects the block that was used as the blueprint. This way you do not need a Painter for every type of Facade you want to autocraft. 

Alternatively the block could also be consumend, since the new block is pretty much usable just like the blueprint thus (in my oppinion) making some more difficult-to-make decorational blocks a little too cheap.

**Comment by 6210classick** [comment]
a config option that allow the base block to be consumed would be better of course it should be disabled by default

**Comment by DrakeOfTheWest** [comment]
Yes, turning off consumption via config would be a nice bonus, if this route was chosen.
However the auto-eject setting in the painter-GUI remains my preferred choice.
