### ISSUE TITLE
Slice'n'splice not taking silicon

### ISSUE THREAD

**Issue by Osharu** [SleepyTrousers/EnderIO#1808]
I'm not receiving any errors, but the Slice'n'splice block will not allow me to add silicon (the ender io 4312) to it so I cannot complete any recipes.

**Comment by Osharu** [comment]
EnderIO-1.7.10-2.2.7.326

**Comment by tterrag1098** [comment]
Do you have any other items inside it? It will only take items that will fit in the recipes that include the existing items.

**Comment by Osharu** [comment]
I was attempting to make the z-logic controller. I had the 2 soularium, the
zombie head and the redstone, but it wouldnt accept the silicon. Also
discovered it's not accepting ender heads. I'm using sky factory 2 from the
ATlauncher, if that matters.

**Comment by tterrag1098** [comment]
What kind of silicon is it? AE silicon?

**Comment by Osharu** [comment]
It is the enderio silicon #4312

**Comment by tterrag1098** [comment]
Then I can't reproduce this at all. I did exactly what you said and it works fine.

**Comment by Spaisd** [comment]
I have this same issue. I have been able to do it in my previous worlds. I have used the Alloy Smelter and Furnace with all Ender IO recipes for Silicon with no resolution.
