### ISSUE TITLE
[Suggestion] Inhibitor Obelisk

### ISSUE THREAD

**Issue by NightOps007** [SleepyTrousers/EnderIO#1809]
Prevents all entities, including players(exception/whitelist with owner defaulted to excluded from the teleport restriction) from teleporting into its area of effect and prevents teleporting while inside its area of effect. A way to keep mobs that teleport contained and keep those pesky visitors away. No more using staff or travel to force your way in.

**Comment by bookerthegeek** [comment]
This would be good if you could tie into other mods api to cancel their teleport also inside the effected area.
