### ISSUE TITLE
[FEATURE REQUEST] Powered lights without light nodes.

### ISSUE THREAD

**Issue by TheCadde** [SleepyTrousers/EnderIO#1832]
I am running a bunch of mods (http://pastebin.com/DV9bGAcG, forge 1277, Optifine 1.7.10 HD U B4) and i really want to use your powered lights but i have ran into issues where the light nodes persist/stay lit/doesn't update...

While i could try changing optifine settings left and right and try running a clean pack with just ender io... I just want to get to play some, i have been wasting so much time fixing issues and never get anywhere.
Aside from that, i actually don't like the invisible light nodes you are using in the first place. I would much prefer it if there was one light source.

So here's my feature request, add an option to add light nodes or not in the config file.
Muchos thank yous for reading this.

**Comment by TheCadde** [comment]
Oh yeah, even so you might want to know how the light nodes persist...
For starters, removing the bugged powered light keeps the light nodes in the world. I am forced to place regular torches all over the place to update the world lighting AND i have to hunt down the light nodes that persisted and replace them with blocks.

Sometimes (when powered lights are close to each other) they bug out and leave light nodes lit after turning on/off redstone and/or starving them of power.

Along chunk boundaries i get dark edges and chunk sections that are unaffected by light updates until i manually go there and kick butt.
I have had zero issues with other light forms so far. I want to use your powered lights because i don't believe in "free/perpetual" energy. ;)

**Comment by tterrag1098** [comment]
The normal lights do not have nodes, you can simply use them.

**Comment by TheCadde** [comment]
Invalid use of the "invalid" label.

> Similar to the Powered Light, but does **not require power**. Produces an amount of light equivalent to glowstone.

Look, the ONLY reason i wanted to use Ender IO powered lights was because they consume and require POWER.

**Comment by TheCadde** [comment]
Meh. -.- whatever, don't waste your time.
I compiled my own.

**Comment by TheCadde** [comment]
I would and i currently do. I started out using torches like every other MC player but when i got to a certain stage in the game and built my first powered lights i DECIDED that from that point on i will not use a single torch. I have intentionally torn down every single torch i have placed anywhere and am now using powered lights (with the light nodes disabled) and the flood light from rotarycraft. That is, if i need a tunnel to be lit i place a flood light, a magnetostatic (conversion) engine and a lead energy cell. If i leave that running it would run for about 166 minutes.

And i never liked the light nodes anyways, they seemed a bit excessive to me.
I know the floodlight uses invisible light sources too but i only use that for "construction" purposes so it fits my bill.

My factory currently has more than 200 powered lights decorating it as i type, each floor is hooked up to omnidirectional light switches at every entrance, as leaving them on would pull a constant 200+ RF/t for no good reason.

**Comment by tterrag1098** [comment]
What I'm saying is, now that you've removed light nodes, there is no advantage to using the powered lights. They provide no benefit and suck power for no reason. Why not just use regular lights now?

**Comment by Vexatos** [comment]
Just to clarify: There is a block in EIO called "Powered Light" having these light nodes. There also is a block in EIO called "Light" that doesn't have the light nodes and doesn't require power. It appears this might be a cause of misunderstanding.

**Comment by TheCadde** [comment]
Is it so hard to understand that i WANT my light sources to REQUIRE power... In the same line as the "torches burn out after a while" mods. I don't mind them being equivalent in power to glowstone. *le sigh*

**Comment by TheCadde** [comment]
Just for your information, i managed to (finally) get rid of the inconsistent light updates and "ghosting" light sources by calling updates in the next entity update.

That is, in TileElectricLight, i assigned a bool to true where markBlockForUpdate and updateLightByType is called and called those two functions when the bool is true on the next update.

I still have light nodes disabled, still too cheap for my world, so i don't know if that also solves the issues with them or if one needs to do the same delayed update on them.
