### ISSUE TITLE
Painting Sky Stone Block AE2) with glowstone error

### ISSUE THREAD

**Issue by MrSpencerRecor** [SleepyTrousers/EnderIO#1845]
Hello, I tried doing this and the skystone turns invisible in your inventory and in your hand, but when placed down it isn't invisible. So just a graphical glitch

**Comment by neard** [comment]
I've had this bug as well. It happens with all four variations of Sky Stone (regular, block, brick, and small brick). There is absolutely no image for the item; it looks like no item is in that inventory slot unless you put the mouse over it and see the pop-up information. In addition, it seems only to be Sky Stone, not an AE2 incompatibility; for instance, Certus Quartz painted glowstone shows up just fine.
