### ISSUE TITLE
Even wih Mekanism installed, and the config set to true to force them, gas conduits are not available to craft. 

### ISSUE THREAD

**Issue by dragonpaw** [SleepyTrousers/EnderIO#1867]

**Comment by Zaflis** [comment]
I see gas conduits with EnderIO-1.7.10-2.2.7.325 and Mekanism-1.7.10-7.1.2.157.

**Comment by dragonpaw** [comment]
![2015-02-14_19 52 35](https://cloud.githubusercontent.com/assets/74992/6202016/4c6345f6-b483-11e4-88e9-8b9d29e251d6.png)

Screenshot is from EnderIO 2.2.6-317 and Mekansim 1.7.10-7.1.1.127.

Was something fixed since those releases?

**Comment by tterrag1098** [comment]
Not specifically, but you should always test with the latest of both mods.

**Comment by tterrag1098** [comment]
Also it's nearly impossible for me to tell what conduits are in your screenshot because you use a texture pack. Please provide screenshots always using the vanilla textures.

**Comment by dragonpaw** [comment]
Sorry about the texture pack. I can get you another shot with vanilla textures if you like. (The ones shown are the red stone, the three power and fluid conduits, item, and the two ME ones.)

I'll check the newer versions and see if it helps.

**Comment by dragonpaw** [comment]
Also, I even set "S:isGasConduitEnabled=true" in EnderIO.cfg, and that didn't help.

**Comment by dragonpaw** [comment]
Ok more details: Running the same set of mods running locally, the gas conduits exist. But host a dedicated server with those mods, and the conduits disappear.

**Comment by tterrag1098** [comment]
Do you have the config enabled on your client too?

**Comment by dragonpaw** [comment]
Yes.It is set to true not auto in both client and server.
