### ISSUE TITLE
SUGGESTION: Add a slot for shears in the farm block to optionally havest leaves and vines.

### ISSUE THREAD

**Issue by BBHouseRodent** [SleepyTrousers/EnderIO#1869]
Thanks for your consideration and what has become an essential mod.

**Comment by HenryLoenwind** [comment]
Harvesting leaves is in #1877 and may be included in the next version. Vines is harder, as there is no seed to plant on the ground.

**Comment by BBHouseRodent** [comment]
Thanks for pointing out the original suggestion. I had missed it when I was looking to see if it was already suggested. 
My initial thought was to collect the vines growing on Jungle trees when harvesting jungle trees if shears were in the farm block but alternately, if vines only harvested if there was  another vine block above them they would grow back without harvesting the jungle tree. I guess vines could be grown on anything then.
