### ISSUE TITLE
Texture-Fails (Invisible)

### ISSUE THREAD

**Issue by MineLoad** [SleepyTrousers/EnderIO#1876]
Hello, I will making a "private" Modpack with this Mod, but the problem is, there are texture "fails" - Conduits and different Models "Blocks" are Invisible when I place them
My Question is, are you knowing about Mod-Conflicts with the Mod?
I play in the Minecraft V. 1.7.10 - newest Minecraft Forge Version
I have the same problems in: Carpenters' Blocks and Chisel2
I hope you can answer me, thanks in advance.
Sincerly your
MineLoad

**Comment by tterrag1098** [comment]
Do you have optifine installed?

**Comment by kiuny** [comment]
The same bug is happening to me.
http://puu.sh/fClvj/43ad57dd4a.jpg
http://puu.sh/fClyn/7ad4a9e928.jpg
Besides that it's making other blocks (not close to any pipe or something) turn around and face south.
No I don't have optifine installed (http://puu.sh/fClOF/7564baf974.png those are my video settings).

**Comment by tterrag1098** [comment]
What versions do you two have?

**Comment by kiuny** [comment]
EnderIO 1.7.10-2.2.7.325. That's my version. I'm using it with Forge 1284.

**Comment by MineLoad** [comment]
Hello, I have installed Optifine, 
my EnderIO version is:    1.7.10-2.2.8.344
my Optifine version is:     1.7.10_HD_U_A4
and my Forge version is: 1.7.10-10.13.2.1291
Sincerly your
MineLoad

**Comment by MatthiasMann** [comment]
Do these issues also happen without Optifine?

**Comment by MineLoad** [comment]
Hello, I found the mistake now, it was because I used a false Optifine version now it's working.
Thanks for your Support.
Sincerly your
MineLoad

**Comment by kiuny** [comment]
I don't have optifine installed in this instance.
But I do have constant night vision. I didn't get a chance to test without it, but will do it asap.

**Comment by tterrag1098** [comment]
@kiuny Your issue sounds like another mod being buggy, though I'm not sure which.

**Comment by deadgamer1030** [comment]
i have same issue. It might be a multipart issue because when this happens to my conduits it happens to all microblocks. re-logging fixes it for me. I due have optifine installed

**Comment by MatthiasMann** [comment]
EnderIO conduits are neither Forge Multipart or Immibis Multiparts. But in general unless the issue also happens without Optifine you should complain to Optifine.

**Comment by deadgamer1030** [comment]
Well the thing is that these texture glitches happen at the same time , even without optifine. It happens randomly with only when starting my world. Also, computercraft monitors crash the game if you look at them while this is happening. My only guess it that it is a corrupted chunk that is in my base, this is where it happens most often.

**Comment by MatthiasMann** [comment]
Well - try to reproduce this in a new (creative) world - if it still happens start to remove mods (esp Optifine). If it no longer happens - then it is an issue in your world.

But as it also affects others mods besides EnderIO - it is highly unlikely to be an EnderIO issue.
