### ISSUE TITLE
SAG Mill outputs mixed dust types

### ISSUE THREAD

**Issue by h3po** [SleepyTrousers/EnderIO#1881]
Hi,
I'm playing the dw20 1.7.1 pack which currently has EnderIO 2.2.5.311 included. I'm using the SAG Mill to pulverize my ores and have it loaded with steel balls for the bonus output.
When I mill vanilla iron ore, I get thermal foundation pulverized iron plus pulverized ferrous and pulverized tin as bonus. When I mill thermal foundation copper ore, I get industrialcraft copper dust and iron dust as bonus. When milling gold ore, I get thermal foundation pulverized copper as bonus. Similar things happen with the other ores, so I end up with both dust types for all the metals.
TLDR: the bonus outputs from the SAG Mill give different dust types than milling the original ore.

This looks to be a problem with ore dictionary, but I can't see what would be wrong with the config. Example from my SAGMillRecipes_Core.xml:

    <recipe name="CopperOre" energyCost="3600">
      <input>
        <itemStack oreDictionary="oreCopper" />
      </input>
      <output>
        <itemStack oreDictionary="dustCopper" number="2"/>
        <itemStack oreDictionary="dustGold" number="1" chance="0.125"/>                  
        <itemStack modID="minecraft" itemName="cobblestone" chance="0.15" />
      </output>
    </recipe>
 
    <recipe name="GoldOre" energyCost="3600">
      <input>
        <itemStack oreDictionary="oreGold" />
      </input>
      <output>
        <itemStack oreDictionary="dustGold" number="2"/>               
        <itemStack oreDictionary="dustCopper" number="1" chance="0.2" />        
        <itemStack modID="minecraft" itemName="cobblestone" chance="0.15" />
      </output>
    </recipe>

**Comment by MatthiasMann** [comment]
Take a look at OreDictionaryPreferences_Core.xml and OreDictionaryPreferences_User.xml

**Comment by HenryLoenwind** [comment]
Matthias, when looking at the posted config above

    <itemStack oreDictionary="dustCopper" number="2"/>

and

    <itemStack oreDictionary="dustCopper" number="1" chance="0.2" />

should give the same kind of dust, regardless of the content of OreDictionaryPreferences*.xml.

I remember I had problems trying to tweak the OreDictionaryPreferences a while back, too. Do some of the mods have eio compat and send IMS msgs?

**Comment by MatthiasMann** [comment]
That is possible - I don't think you dump the recipes or the IMC message currently.
But recipes with the same name overwrite the already existing ones.
