### ISSUE TITLE
Travel anchor groups

### ISSUE THREAD

**Issue by tivec** [SleepyTrousers/EnderIO#1884]
While trying to figure out where to go in my base today, I stumbled over this situation: http://i.imgur.com/CQV7lzL.png

I thought, "gosh, wouldn't it be great to have these split into groups?" 

My idea would be to have travel anchor "channels". You would do just like with the yeta wrench and use shift mouse-wheel to select what type you're looking for, but instead of the various conduit types, it would rotate between colors. Whenever you have a color chosen, only the ones with that specific color selected would be visible. This would give the player 16 groups of anchors to work with.

World anchors could also have a "transparent" choice, making them always visible no matter what color you have chosen.

**Comment by 6210classick** [comment]
you can change this in the config file to make them look smaller

travelAnchorZoomScale=0.1

you can also set an item icon on it

how about this little neat feature if there is 2 travel anchors one at bottom and one on the surface on the same x coordinates it will teleport to it sort of like how elevators from open blocks

**Comment by tivec** [comment]
I know you can change the scale, and set item icons, but that doesn't solve the issue when you have plenty of anchors in the area. A "channels" system makes filtering a possibility.

**Comment by tterrag1098** [comment]
Hm, that might be neat. I'll see what can be done.
