### ISSUE TITLE
[2.2.8.346] Fluid Conduit - Texture Glitch

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#1889]
I just updated my modpack with latest EnderIO and after logging in, i noticed that all my fluid conduits were with the missing texture icon. I removed them and replaced them, and everything fixed by itself. But...

When I set Fluid Conduit to extract mode and will initiate the extraction (by using redstone signal low, or applying a lever), the liquid will start to come out, but again the missing texture reapears. Before I was using 329 and everything worked correctly.
Here is a screenshot (vanilla textures): 
![2015-02-09_21 44 26](https://cloud.githubusercontent.com/assets/4236895/6115348/48e1218c-b0a5-11e4-98d7-8cdff3241043.png)

Modpack: InfiTech 2
Forge : 10.13.2.1232
Can provide FML log if needed.
Not using Optifine, or Fastcraft during testing

**Comment by PsionicArchon** [comment]
Just dropping in to let you know this issue still persists.

I saw this mentioned in the changelog: "Fix conduits rendering on the alpha pass"

**Comment by tterrag1098** [comment]
Yeah that was unrelated. It's just a missing texture but I keep forgetting
to fix it.

**Comment by tterrag1098** [comment]
Closing as this was only ever an issue in dev builds
