### ISSUE TITLE
Vibrant Capacity Bank bug

### ISSUE THREAD

**Issue by Tearlow** [SleepyTrousers/EnderIO#1892]
Quickly just wanted to note I still see issues #1358 in version 1.7.10-2.2.7.331.

In inventory it is displayed as 25.000.000RF and can be charged up to that level but once you place it down it suddenly becomes 5.000.000RF. Checked the configuration file to be sure and everything seems fine there.

Should also note that this is in Resonant Rise modpack.

**Comment by MatthiasMann** [comment]
I can't reproduce this issue with build 331 or with current master.

**Comment by tterrag1098** [comment]
Also do please test on the latest version released.

**Comment by Tearlow** [comment]
Ack- My bad. I totlaly forgot I had this report going. After some time I found out the cause of this and it's all out of EnderIO's area. I was not aware of it at the time but a friend of mine had replicated it using ProjectE using EMC. After doing some digging it never applied the necessary NBT entries. That's how they ended up Vibrant cells but using basics caps etc.

Again, pardon the delay on this one!
