### ISSUE TITLE
REQUEST: Further Upgrading Machines with Capacitors

### ISSUE THREAD

**Issue by GeneralAtrox** [SleepyTrousers/EnderIO#1894]
Hi CrazyPants

I've looked already to see if anyone else has bought up the idea and it seems not. I apologize if this has been bought up before, or explained why it's like this.

It's a simple feature that expands on the basic, double layer and octadic capacitors. Basically we should have way more available but it should get progressively more expensive! 

An idea to naming is as follows, this is assuming you're following shape names with colours to match intensity that I think follows the game nicely.

- Basic (1x Grey)
- Double Layer (3x Red)
- Octadic (5x Green) 
- Hexadecadic (10x Orange) 
- Icosidodecadic (20x Blue) 
- Hexacontadic (40x Purple) 
- Hecatoicosiodic (80x Enchanted Colour)

Of course the highest tiers would be extremely expensive, think Applied Energistics Storage Cells.

Below is the Crafting Recipe Idea which has been kept within the realms of Ender IO only: 

- 10x, 4 Octadic, 1 Pulsating Iron Block Block 
- 20x, 4 Hexadecadic, 1 Conductive Iron Block
- 40x, 4 Icosidocdecadic, 1 Energetic Alloy Block
- 80x, 4 Hexacontadic, 1 Vibrant Alloy Block

Alternatives for Blocks to craft things out of include, Enderium, Ludicrite, Block of Solid Ender, 

The main reasoning for this mod is that you can reach the performance cap of machines pretty early on (Within Feed the Beast at least), especially if you managed to find The End quite early on which has an extremely large supply of Ender Pearls in the form of plants and Enderman. Another reason is once high powered solutions and machines come into the game, such as Big Reactors, there's not much you can do with 8,000 RF/t when your machines can only output at 100 RF/t. The only solution for high powered is to create more machines, which does get increasingly complicated if you're running Applied Energistics or have a small base. 

Thank you for this absolutely brilliant mod, ever since I've used it I've always had it as a main part of my base and ore processing. Everything about it is just genius.

**Comment by Vexatos** [comment]
> Hecatoicosiodic (80x Enchanted Colour)
Please make the power consumption multiplier exponential (2^80 RF/t sounds fair :dancer:)

**Comment by GeneralAtrox** [comment]
It's the same reason to why you'd ever want 16384K Storage Cell (ExtraCells) in your ME System. For those people who have alot of resources or use Compact Machines, they could opt for the costly and less efficient approach in the attempt to keep their machine room minimal. 

Of course the power consumption/production etc... would have to be fine tuned. I've just tried to scale it from I see.

**Comment by Neodark7** [comment]
Yeah i totally approve this, even with an octadic capacitor machines are really slow sometimes :/

**Comment by tterrag1098** [comment]
The way EIO upgrades work, they simply increase the RATE at which the machine can consume power, not the amount of power it takes per operation. So I don't see these upgrades being all that useful when you can currently just make MORE of the same machine to accomplish the goal.

This idea seems as if it would squander a lot of the intricacies of EnderIO, such as the item conduits that have the ability to distribute evenly between a number of machines -- great for arrays of octadic alloy smelters, for example.

While this is a rather well thought out idea (The names are clever too) I don't think it would benefit the gameplay of the mod.

**Comment by GeneralAtrox** [comment]
Thank you guys for your feedback on the idea. 

I wouldn't say it'd squander anything as these kind of items are expensive and worth while for compact systems. The item conduit distributing or other features are the cheaper options which players would more than likely use early game. There wouldn't be a gameplay improving idea behind this request, more a convenience for players. Maybe some upgrades could allow for more efficient machines, allow flint/dark steel to last longer and add-on slots to process more materials.

Maybe this kind of request could be implemented as a separate add-on mod, similar to Extra Cells. Extra Capacitors could expand on upgrading the machinery.

**Comment by dumle29** [comment]
I'm all for this proposal, as I've mainly switched over to using thermal expansion machines to handle my ore processing from my frame query, as no enderIO setup would keep up, and leave me with any AE2 channels left. Well I guess the interface could be attached to a chest then then distributes out to the machines, and then back into the interface, but this is rather messy, and would be my preferred solution early game, but I'd want to move to a much more compact, but expensive system once I get later game, and tidy up.

**Comment by Wenoc** [comment]
>Seriously, why would you ever want an 80x (read: a lot) multiplier? Just get more machines...

More machines generally increase lag on servers. And it's ugly to have a million of each machine.

**Comment by GeneralAtrox** [comment]
The increase on lag within the server is quite true having multiple active blocks and such. Allowing faster machines can let people choose what they would prefer and allow restraints if necessary.

**Comment by tterrag1098** [comment]
In the end game, "quite expensive" stops meaning anything. Anything can be crafted at that stage. I want to continue to encourage more complex, smart builds, instead of just giving more single-block super-machine solutions.

**Comment by Vexatos** [comment]
:+1: I agree with @tterrag1098. Further machine upgrades really don't make much sense to me. If you want faster machines, just get more of them and let them run in parallel. There's your "end-game" costs.

**Comment by GeneralAtrox** [comment]
Realistically it should be open to the user and their personal requirements. Singular blocks are made for compact reasons over anything.

Is it possible

**Comment by dumle29** [comment]
I do like the idea of making a more complex system, as this mechanic is what makes frame quarries so damn fun to build, but if I want to setup autocrafting of alloys in EiO, and I use the item-conduits to round-robin the alloy ingredients around the different alloy smelters, this can give me issues with half an alloy recipe getting stuck in two alloy furnaces.

I don't know if any feature could be added to the item conduits, that would allow better sorting of alloy blends.

**Comment by SirKastros** [comment]
I have seen a good machine design for end game with the use of eight SAG Mills and eight Alloy Smelters with the high level capacitor and speed upgrades on the machine item conduit input output. for server friendly automation use compact machines this mod will put all machines in a separate dimension then the over world which is a void dimension with unbreakable rooms to build your automation systems in. the endgame cost for the largest one is 8 nether stars which by that time you are killing the wither automatically.
