### ISSUE TITLE
Closing server connection. | A fatal error has occured, this connection has terminated.

### ISSUE THREAD

**Issue by sheynandr** [SleepyTrousers/EnderIO#1901]
Hi. My server terminate connection for player when player load chunk contain mob spawner.
Minecraft client error - "A fatal error has occured. Connection has been terminated".

Also when player try connect to server, console print error. (See full error from console in my gist https://gist.github.com/sheynandr/117ef8559d5754cc7007)

Versions:
>Minecraft 1.7.10 | Forge 10.13.2.1264
>EnderIO-1.7.10-2.2.8.344.jar
>Cauldron 1.7.10-1.1236.06.212

**Comment by sheynandr** [comment]
No answers??

**Comment by tterrag1098** [comment]
That stacktrace doesn't cause disconnects. Please post your entire server log.

**Comment by sheynandr** [comment]
Sorry for long waiting. I'm forgot this issue.
Full server log available in gist https://gist.github.com/sheynandr/f4fb5bd91aff6a9d1414/raw/gistfile1.java

**Comment by sheynandr** [comment]
Any ideas?
