### ISSUE TITLE
killer joe + openblocks

### ISSUE THREAD

**Issue by wakkytabbaky** [SleepyTrousers/EnderIO#1902]
when getting killed by a killer joe you do not drop a openblocks grave like usual , not sure if its ender io side or openblocks so posting on both githubs just in case , both mod versions are 1.7.10

and also is it possible to make the killer joe not attack the person who placed it / owns it?

**Comment by tterrag1098** [comment]
You want a zombie head in a jar to be smart enough to pick you out of a crowd of monsters? :P 

As for the grave issue, what happens do your items disappear or do they just drop as normal?

**Comment by wakkytabbaky** [comment]
they just disappear completly , like they dont even drop to hang around on the ground
