### ISSUE TITLE
[Suggestion] Priorities on fluid conduits.

### ISSUE THREAD

**Issue by AiwendilCiunio** [SleepyTrousers/EnderIO#1932]
I had many situation where this would have been very useful, and I had to do some weird workaround instead.
Example:
My GT Machine is producing oxygen, which is stored in Extra Utils Drum. Rest is voided (void pipe is 1 block further than drum, so stuff gets voided only when the drum is full.
However when I want to pull some oxygen from the drum to supply another machine, half of it gets voided, because this time the void pipe isn't the furthest location. 
A simple priority would solve this with ease. Is it even possible to do?

Sorry for a bad explanation, I'm still very sleepy :P

**Comment by Zaflis** [comment]
> void pipe is 1 block further than drum, so stuff gets voided only when the drum is full

This is not how i've seen fluids to work though. Fluid pipes evenly distribute to all input tanks. When i move fluids from 1 drum into 2 drums with Ender fluid conduit, they both fill same time.

Only mod i know that handles excess fluids well is Mekanism, which can automatically void excess in gas tanks and machines.

That said having priority option on fluid conduits would be very useful.
