### ISSUE TITLE
Staff of traveling going through bedrock and other blocks in the blacklist

### ISSUE THREAD

**Issue by CA2020** [SleepyTrousers/EnderIO#1934]
Version: EnderIO-1.7.10-2.2.6.317

The Staff of Traveling is going through blacklisted blocks. Not when they are a wall or a roof, but if you standing on the block, then it goes through.

For example 1 layer of bedrock, you stand on them and when you use the staff you can go through.

I have this 2 options "false" really not sure if it's the way as it was confusing for me to understand what exactly this 2 configs mean when set both to false, but I'm sure the 2nd needs to be false.

    B:travelStaffBlinkThroughClearBlocksEnabled=false

    B:travelStaffBlinkThroughUnbreakableBlocksEnabled=false

**Comment by 6210classick** [comment]
you are using old version update to the latest and see if the problem still occurs

**Comment by CA2020** [comment]
Hello again, first of all sorry, I was putting together this new pack and forgot to check for new versions.

So now yes I downloaded EnderIO-1.7.10-2.2.8.349 And the issue is still there.

Tried on Bedrock 1 layer only that has no void under it. I'm trying on Bedrock because its a Minecraft block, but I'm looking forward into blocking some blocks from other mods also, the issue is there also for those blocks.

If it's a wall, it blocks perfect, if I'm standing on the block and face down, then I can go trough.

**Comment by RAnders00** [comment]
Try it with just EnderIO, please. Just make a new instance with forge 1291 and the latest ender io from http://ci.tterrag.com/job/EnderIO/lastSuccessfulBuild/. Please report back whether the issue still exists. If you have the time neccessary and the issue does not exist with just EnderIO installed, try boiling it down to a other mod that is causing it (keep adding mods at their latest versions to the new instance, it's tedious I know, but that would help a lot)

**Comment by CA2020** [comment]
Ok I created an Instance with Forge 10.13.2.1291 and with EnderIO 1.7.10-2.3.0.372_beta and the problem is still there. You can see on the image, I can't go trough the Bedrock wall, but if I stand on that bedrock platform look down and activate the Staff of traveling, I go trough it and land in the grass.

Settings are Default, I understand this settings prevent going trough Bedrock, in fact, they do, but no when you standing on it.

B:travelStaffBlinkThroughClearBlocksEnabled=true
B:travelStaffBlinkThroughUnbreakableBlocksEnabled=false

https://imgur.com/a/KsX0v

Haven't tested with the mods I want to ban blocks. (A mod I made myself and Compact Machines, a Mod that create Blocks that when you access them, take you to a room (for example 9x9x9) in a new dimension with unbreakable blocks, with the staff of traveling you can go trough those blocks and get in the void/world from the outside, when that should never happen.

**Comment by RAnders00** [comment]
@tterrag1098 This is not out of date, please update the labels.
