### ISSUE TITLE
Bug[Placement of enderman heads

### ISSUE THREAD

**Issue by Karmacopper** [SleepyTrousers/EnderIO#1935]
Enderman heads aren't aligning correctly when placed in the world.

https://imgur.com/a/muvPl

**Comment by 6210classick** [comment]
provide more info like what Forge & EIO version are you using ?

i'm gonna take a wild guess and say the cause of the problem is probably the texture pack

**Comment by Karmacopper** [comment]
Forge version is 1272, eio is the latest dev 350. It's been like this for a while and isnt resource pack specific. It happens with default textures too.

**Comment by Karmacopper** [comment]
In EnderIO-1.7.10-2.3.0.425_beta.jar this still appears to be present, fixed or will not fix? It's aesthetic I guess...
