### ISSUE TITLE
Me conduits and dark pick bugs.

### ISSUE THREAD

**Issue by deadgamer1030** [SleepyTrousers/EnderIO#1937]
Me conduits do not link with p2p tunnels properly after logging back into a world, they disconnect.
Dark pick with the spoon upgrade does not work on Tic ore gravels. It will break the gravel but not drop anything.

**Comment by 6210classick** [comment]
provide more information please like what Forge & EIO & AE are you using ?

EIO ME Conduit do not interact with any AE2 buses directly you need to use AE2 cable in between also be aware that in almost every version of EIO from 2.2.0 ME Conduits causes alot of problems and crashes its even can corrupt your world permanently ,, couple days ago in version 2.2.8.349 supposedly all ME Conduits related problems has been fixed

**Comment by tterrag1098** [comment]
I would also be interested in the version because I am fairly sure the gravel ores should work.

**Comment by deadgamer1030** [comment]
version 2.2.8.349
