### ISSUE TITLE
Conduit Facades Rendering Incorrectly With Chisel Blocks

### ISSUE THREAD

**Issue by shadowfacts** [SleepyTrousers/EnderIO#1940]
Conduit Facades Painted with Chisel blocks will render incorrectly in the
 "Configure IO" menu. Some Chisel blocks will just display the pink/black missing texture while others will display as the default variation (metadata 0) of the block.

Chisel 2: DEV-2.3.6.9c8364c
Ender IO: 1.7.10-2.2.8.350

Diamond Block (Diamonds in Purple Obsidian)
![2015-02-16_13 41 20](https://cloud.githubusercontent.com/assets/7091588/6217413/973ba38e-b5e1-11e4-9b7b-849f741f15c9.png)

Cobblestone (Huge Cobblestone Tiles)
![2015-02-16_13 42 14](https://cloud.githubusercontent.com/assets/7091588/6217418/a1e42dce-b5e1-11e4-9b4e-4b31ac5f938e.png)

Factory Block (Yellow-Black Hazard Block)
![2015-02-16_13 43 01](https://cloud.githubusercontent.com/assets/7091588/6217427/bca593e6-b5e1-11e4-8d63-cf6320a9684e.png)

Concrete (Partly Weathered Concrete Block)
![2015-02-16_13 42 42](https://cloud.githubusercontent.com/assets/7091588/6217422/b4302bf4-b5e1-11e4-9bc0-055ea60e6626.png)

**Comment by 6210classick** [comment]
you are using old version of EIO & Chisel 2 plz update to the latest then see if the problem still occurs

**Comment by shadowfacts** [comment]
**Update:** Confirmed with latest versions of Chisel 2 (DEV-2.3.6.9c8364c) and Ender IO (1.7.10-2.2.8.350).

P.S. Props to whoever did the new textures for the conduits, they look awesome!

**Comment by 6210classick** [comment]
why do are you using dev versions ?

latest official EIO is v1.7.10-2.2.8.349 & Chisel 2 is v2.3.7 

get them from Curse

**Comment by shadowfacts** [comment]
Because those are the most recently built versions of both mods... If it still happens in the most recent alphas, then it's also going to happen in the stable version which were built **before** the alphas.
