### ISSUE TITLE
Gold ingot x16 ore dictionary overwrite

### ISSUE THREAD

**Issue by greenchem4** [SleepyTrousers/EnderIO#1942]
When I installed this mod the itemstack for gold ingots in the ore dictionary changes from the default (1) to 16.  ex 16 gold ingots = 16 gold ingots.  I am not sure if this effects other mods but after I have noticed that build-craft gold chips seam to need 16 gold ingots now (sometime only requires 1) instead of.

**Comment by MatthiasMann** [comment]
That doesn't make any sense.

First a few general rules about reports: always include the version number, and in cases liek this also the mod list.

Also EnderIO doesn't change how gold is handled in the Ore-Dictionary at all.

**Comment by greenchem4** [comment]
I was doing some double checking by removing some other NEI and walia mods that I was using to test for the bug and discovered that the bug occurred when enderIO is installed WITH ttcore (for walia plugins).  Most likely the problem is on ttcore's end and this is not a bug in EnderIO

As for the bug
th Itemstack.toString() function for the forge ore dictionary entry for ingotGold
without both EnderIO & ttcore: 1xitem.ingotGold@0
with EnderIO & ttcore: 16xitem.ingotGold@0
Information obtained with NEI integration ore dictionary dump

EnderIO version: 1.7.10-2.2.8.349
ttCore version: 

Other mods:
CodeChickenCore: 1.7.10-1.0.4.35-universal (library for NEI)
NotEnoughItems: 1.7.10-1.0.4.83-universal
Walia: 1.58a_1.7.10

NEIIntegration: MC1.7.10-1.06 (forge ore dictionary dumps)
NEIPlugins MC1.7.10-1.10.11-unofficial (in game ore dictionary lookup via NEI)

**Comment by tterrag1098** [comment]
ttCore does add a recipe with 16 gold but all the oredict interaction is in EIO.

**Comment by MatthiasMann** [comment]
and EnderIO copies all ItemStacks it gets from OreDict before using them.

@greenchem4 can you try that again with allowXPBoost=false in the ttCore config?

**Comment by greenchem4** [comment]
That did it,
When I set allowXPBoost=false it did fix the problem so that the ore dictionary for ingotGold is correct.
ttCore version: MC1.7.10-0.1.0-66 (i noticed that this was blank in my last post)

By looking at the ttCore Github I noticed that when allowXPBoot is true then a FMLInterModComms sendMessage() is sent to EnderIO with an enchanter recipe.  Could the problem be that ttCore references the gold ingot through the ore dictionary and with the "number" field set to 16?

Below are two cropped screenshots of the in-game representation of the ore dictionary
(using NEI plugins (unofficial))

**Comment by greenchem4** [comment]
Sorry here are the cropped images
allowXPBoost=false
![ingotgold normal](https://cloud.githubusercontent.com/assets/9666667/6253749/c199258e-b771-11e4-8140-7faa4c781ba2.png)

allowXPBoost=true
![ingotgold bug](https://cloud.githubusercontent.com/assets/9666667/6253762/d871ec82-b771-11e4-8d3b-b02aca5c4053.png)

**Comment by tterrag1098** [comment]
Fixed in above PR
