### ISSUE TITLE
Power Monitor not reading from Capacitor Bank anymore.

### ISSUE THREAD

**Issue by kokono2** [SleepyTrousers/EnderIO#1943]
The Power Monitor doesn't show the the power stored and the power input and output anymore when connected directly to a Capacitor Bank. This wasn't the case a few versions before the latest (I'm not sure which version). It also doesn't read the power usage of machines directly connected to the capacitor bank (like tesseracts). It does work fine when I connect the machines and monitor to conduits.

**Comment by MatthiasMann** [comment]
The power monitor always requires conduits - as it monitors devices attached to that conduit network.

**Comment by Nightcaste** [comment]
I agree.  The power monitor should be able to be connected directly to a capacitor bank and still function as normal.
