### ISSUE TITLE
IMC remove recipe

### ISSUE THREAD

**Issue by Creysys** [SleepyTrousers/EnderIO#1946]
For some reason i am unable to remove the silicon recipe from the sagmill.

Here's my code:
http://pastebin.com/38qU45ru

All it says is: RecipeParser:  Root element not specified before element recipeGroup.

People on IRC couldnt help me either :S

**Comment by 6210classick** [comment]
why do you need to remove silicon ? it's an essential part for some of EIO recipes

**Comment by Creysys** [comment]
Gregtech related mod though rf powered, more optimized and better.

**Comment by 6210classick** [comment]
what version of EIO are you having this problem with ?

**Comment by Creysys** [comment]
EnderIO-1.7.10-2.2.7.331-dev.jar

**Comment by HenryLoenwind** [comment]
@6210classick There are many reasons you'd want to disable one specific recipe. Also, it doesn't necessarily mean you'll remove the item. E.g. "Glass->Silicon; Sand->Dust" is an easy way to make Ender IO Ex Nihilo compatible...

**Comment by HenryLoenwind** [comment]
I've never use the IMC, so I'm guessing here:

* Have you tried putting a `<SAGMillRecipes>` tag around your group?
* Have you tried to send a completely new recipe (with all its subtags and attributes)?
* Have you tried to send a complete silicon recipe?
* Have you tried to send a disable message for the enderIO group?

**Comment by Creysys** [comment]
1. Didnt work
2. Worked
3. Worked
4. Didnt try that out but isnt really what i want either :S

**Comment by HenryLoenwind** [comment]
Ok, thanks for testing it. So it look to me like you cannot disable a single recipe. So you either:

* disable the "enderio" group and send a new group with copies of the ender io recipes you want (a pain...), or
* change the silicon recipe to some item that is create only or otherwise unobtainable

@tterrag1098 Someone who understands the IMC/recipe config should look over that. If we really cannot disable a single recipe, we should add that.

**Comment by Creysys** [comment]
Thank you sir :)

**Comment by tterrag1098** [comment]
I'm not sure why it isn't possible to remove IMC recipes, they are processed into the system *before* the config recipes are loaded. I'll need to dig a bit deeper into this.

**Comment by tterrag1098** [comment]
Ah, what I just said above is exactly the issue, the recipes don't exist yet at the time of IMC processing. To do what you are trying to do, you'll likely need to reference internal classes, which is suboptimal of course...

I'll try to think of a solution, but it's quite the chicken and egg problem :)
