### ISSUE TITLE
mod sorting cycle crash - possible regression on 2.2.8.349

### ISSUE THREAD

**Issue by bbaaxx** [SleepyTrousers/EnderIO#1950]
Today I tried to upgrade EnderIo on my home minecraft server and clients from EnderIO-1.7.10-2.2.6.317 to EnderIO-1.7.10-2.2.8.349 and got a dependency cycle error I pasted on [this gist](https://gist.github.com/bbaaxx/8dfcd2f6bdf29c521744).

The error seems to point to the CoFH mods but it does not happen using EnderIO-1.7.10-2.2.6.317. Anyways I leave the analysis to you guys because I know nothing about mod development but the issue is easily reproducible on my environment so I can provide you with logs and whatnot.

Also, thanks a lot for this amazing mod. My family and I have had a lot of fun with it.

**Comment by 6210classick** [comment]
you probably need to update any mod that uses RF to their latest versions

**Comment by MatthiasMann** [comment]
EnderIO updated the RF API in build 301 - so I don't think it is related to that.
But what I saw in the log @bbaaxx posted was that EnderIO was not part of the dependency cycle.

**Comment by HenryLoenwind** [comment]
it's this one:

    [11:33:55 ERROR]: APIContainer{CoFHAPI:1.0} : before: [redgear_core, Railcraft, BuildCraft|Silicon, BuildCraft|Core, BuildCraft|Transport, BuildCraft|Builders, BuildCraft|Energy, BuildCraft|Factory, CoFHCore, EnderIO, Forestry, BuildCraft|Compat, CompactMachines, RandomThings, ExtraUtilities], after: [CoFHCore]

It should be loaded before and after CoFHCore. Um...

**Comment by tterrag1098** [comment]
Some mod is requiring it be after CoFHAPI|Energy instead of the entire CoFHAPI, this seems to cause issues. EnderIO has a dependency on neither mod so I'm not sure how it could cause this.
