### ISSUE TITLE
[Suggestion(s)] + small issue (or is it intended)

### ISSUE THREAD

**Issue by morgue888** [SleepyTrousers/EnderIO#1953]
Issue:
in-game values for Energy Conduits, Dimensional Transceivers, and possibly Capacitor Banks do not reflect rf storage values as configured in cfg file. (this may be intended I don't know)

Suggestion(s):
Things I would love to see in EnderIO (my new beloved mod.)

Dark Steel Boots Upgrade:
-Sticky upgrade to allow you to walk up walls like spiders do.
-able to hold shift like when on ladders to hold position.
-Possible items for crafting: slime ball + woven spider silk(9 spider silk) + 10-20lvls

Dark Steel torch launcher:
-Somewhat expensive to make and uses energy as all dark steel items do.
-Possible items for crafting: dark steel, blaze rods, slime balls, ender pearls
-use capacitor upgrades (and lvl requirement like DS armor) to increase energy storage and range
-graphic for light source could be a grey stick w/ ender-ish color fire or mechanical looking. 

Dark Steel Armor Upgrade:
-Lava resistance (Read:invulnerability to lava)
-Possible items for crafting: 
compressed obsidian plating (9 obsidian + 1 dark steel ingot = 1 cop) + 30lvls
-Since it is pretty powerful require it to be on all Pieces of armor for it to work (IE:Helm,Chest,Legs,Boots)

Yeta Wrench config reset:
-A mode for the wrench to reset the config of machines/DT/cap banks/conduits to defaults

Dark Steel Helm Upgrade:
-Auto feeder upgrade...
-With all the crazy technology on my server, I think it is acceptable to have an auto-feeder.
-This is the least important on this list.

Side note:
EnderIO is absolutely AMAZING.
Keep up the good work!

Thanks,

morgue888

P.S. If this was an inappropriate location for this please advise.

**Comment by 6210classick** [comment]
how about this little neat feature if there is 2 travel anchors one at bottom and one on the surface on the same x coordinates it will teleport to it sort of like how elevators from open blocks
