### ISSUE TITLE
Facade Issue

### ISSUE THREAD

**Issue by shadowfacts** [SleepyTrousers/EnderIO#1954]
If a torch is placed on a facade and the facade is then broken the torch will remain in place causing this:
![2015-02-17_17 05 05](https://cloud.githubusercontent.com/assets/7091588/6238205/2473f4a0-b6c7-11e4-8cae-d016584058b4.png)

Ender IO: 2.2.8.350

**Comment by amadornes** [comment]
I think this is related to #1407. I reported conduit blocks not causing updates when a conduit/facade is placed or removed. Maybe the commit that fixed it somehow got reverted?
