### ISSUE TITLE
Capacitor removal with WorldEdit dropping Creative Capacitor

### ISSUE THREAD

**Issue by kevinkk525** [SleepyTrousers/EnderIO#1960]
As the title says, removing Vibrant Capacitors with WorldEdit using //set 0 drops every single Capacitor as a Creative Capacitor. No matter what gamemode.

Expected behaviour: drop nothing but if it should drop something then Vibrant Capacitors.

Version: EnderIO-1.7.10-2.2.8.349

Normal removal works correctly.

**Comment by tterrag1098** [comment]
WorldEdit is probably calling breakBlock in which case we cannot tell if the player is in creative mode, not sure how this can be fixed

**Comment by tterrag1098** [comment]
Fixed under #1991

**Comment by tterrag1098** [comment]
This was only partially fixed.
