### ISSUE TITLE
Capacitors causing high client upload

### ISSUE THREAD

**Issue by kevinkk525** [SleepyTrousers/EnderIO#1961]
Long story short: 
If I have a lot of (Vibrant) Capacitors in one or more chunks as a multiblock it causes very high client upload for quite some time while entering the area for the first time.  (that leads to a time of around 1-180sec with no interaction possible) That means after a warp or home command and on login. Time depends on the amount of Capacitors in the area. Seems to be worse if the capacitor has a different shape than a normal rect. ~1000 Capacitors did not cause a visible high upload. But 4000 Capacitors already give a time of 25 sec with maximum client upload. All of the tested chunks were chunkloaded and even in different worlds.

version: EnderIO-1.7.10-2.2.8.349
running on cauldron, forge 1236

**Comment by tterrag1098** [comment]
This would happen if you filled any area with very complex tile entities. 4000 capacitor banks in a small area is a lot and is naturally going to tax your network connection to sync all the data. What is your upload speed, perchance?

**Comment by kevinkk525** [comment]
I understand that large structures need a lot of bandwith to synchronize but why is an upload required? My upload speed is about 110kb/s and during login or teleport to that area the client does use almost the complete upload speed. So of course the client needs to download the whole structure and that takes some time. But why does the client "reupload" almost the same data (it did not have it before the teleport/login of course).

**Comment by tterrag1098** [comment]
The way cap bank networks work, they must request the power data from the server, this means a somewhat large upload spike while it initially loads in. Unavoidable I'm afraid without some major rewrites.
