### ISSUE TITLE
SAG Mill does not work with ExNihilo

### ISSUE THREAD

**Issue by Dream5561** [SleepyTrousers/EnderIO#1962]
SAG Mills does not accept blocks ExNihilo although the recipes are written in SAGMillRecipes_Core.xml files.
Add a recipe SAGMillRecipes_User does not help

version: EnderIO-1.7.10-2.2.8.349

**Comment by HenryLoenwind** [comment]
Could you give a specific example of a non-working recipe? Which Ex Nihilo version are you using?

Thanks

**Comment by MatthiasMann** [comment]
This is an ExNihilo bug - it registers it's items too late. You can work around it by ensuring that ExNihilo is loaded before EnderIO (by renaming one of the JAR files).

**Comment by tterrag1098** [comment]
Actually ExN has changed hands, it is now being developed by
@MikeLyadeamore. So maybe it could be fixed?

**Comment by tterrag1098** [comment]
Sorry, typo. I meant @MikeLydeamore

**Comment by HenryLoenwind** [comment]
Wouldn't a simple @Mod(..., dependencies = "after:exnihilo") on our side help* here, too? Or would that introduce a loop?

I think ex nihilo has good reason to be late, it doesn't want to register dusts for ores that are not in the game. BUT, it should use "dependencies = "after:*"" instead of using the next phase.


(*) I said "help", not "be the correct thing"

**Comment by MatthiasMann** [comment]
registering items where ExNihilo does is too late. It would be easier to just depend on the config flags to enable/disable certain ores.
That would cause much less bugs than potential loading order or dependency cycle issues.

**Comment by MikeLydeamore** [comment]
This is interesting, as has been noted, ExN checks the size of an oredict entry before adding the ores. This is almost necessary to be in post as a lot of ores aren't oredicted until init. I'd also really rather not clog up IDs with sands/dusts/gravels/ingots that have no purpose. Config flags would (I guess) achieve this, *but* that also implies that regular people would check the config values.

Ex Nihilo only depends on forge, so adding a dependency in EnderIO wouldn't cause a cycle, and would guarantee that section of the load order.

I'm open to suggestions, but I really don't want to be generating these things without them having a purpose.

**Comment by HenryLoenwind** [comment]
@MikeLydeamore How about adding before:* to ex nihilo? that way you'd still be one phase late but at least the chances to be so early in the phase that nobody notices are quite high...

**Comment by MikeLydeamore** [comment]
@HenryLoenwind, this works, but makes me nervous. I also can't enforce a minimum forge version, which isn't really a big issue. If there's no other way around this then I guess I can use that.
