### ISSUE TITLE
Ender Rail - direction bug with trains and players

### ISSUE THREAD

**Issue by Terpo** [SleepyTrousers/EnderIO#1968]
EnderIO-1.7.10-2.2.7.325.jar
complete modlist: http://blog.terpo.org/upload/mc/modlist.txt
Forge 1291

----------------------

Youtube video: 
http://youtu.be/10_-3zKtrKQ

----------------------
This bug only occurs when the player is sitting in a train. A single minecart is working correctly. 
If the ender rail is facing in a north-south direction on the receiving end, the player is leaving the train and spawns behind or in front of it.

**Comment by 6210classick** [comment]
first update EIO to the latest version then see if the problem still occurs 

you are not gonna get a reply from EIO team when you report an issue from old version

**Comment by Terpo** [comment]
I can confirm this bug in the newest version of EnderIO (updated the whole modpack yesterday).
This bug also happens with my map in the SinglePlayer.
