### ISSUE TITLE
(Suggestion) Steve's Factory Manager Conduits

### ISSUE THREAD

**Issue by ArcaneTechnician** [SleepyTrousers/EnderIO#1970]
I use EnderIO and Steve's Factory Manager together a lot, and since you added gas conduits, it seems like a step in the right direction.

**Comment by 6210classick** [comment]
there is also ME Conduits ! but i don't see SFM Conduits happening anytime soon because you can already fit up to 6 Conduits in the same block space ! it will be insane to have a 7th 

maybe after 1.8 becomes stable but not right now

**Comment by tgstyle** [comment]
Duplicate of an older request.
https://github.com/CrazyPants/EnderIO/issues/485
