### ISSUE TITLE
Dark Axe on a Forestry tree

### ISSUE THREAD

**Issue by Scratchman** [SleepyTrousers/EnderIO#1972]
The server had the following crash when i attempted to take down a forestry sweet chestnut tree by shift/right clicking on a log at the top of the tree with an empowered dark axe. When i rejoined the server the tree was still standing.

Cauldron
EnderIO-1.7.10-2.2.8.349
forestry_1.7.10-3.4.0.7
Forge 1272

http://pastebin.com/wAXU6djf

ETA: I just tried the same thing on a vanilla oak tree and the server crashed with the same error.

**Comment by 6210classick** [comment]
aren't you suppose to start from the bottom log ?

**Comment by Scratchman** [comment]
I didn't see that requirement mentioned anywhere on the wiki.

**Comment by 6210classick** [comment]
it's common sense to start cutting the tree from the bottom

**Comment by MrGraphic** [comment]
Works for me in both SSP and SMP on forge .1291. It my be caused by Cauldron.

**Comment by HenryLoenwind** [comment]
fixed in #1895
