### ISSUE TITLE
Beg pardon. I apologize. Disregard and ignore this post.

### ISSUE THREAD

**Issue by HowardRoark2016** [SleepyTrousers/EnderIO#1975]
I am using FtB Direwolf20 1.7.10 modpack v1.0.3 that I upgraded with EnderIO 2.2.8 build 349 and ChickenChunks 1.3.4.16. The pack is otherwise default. Please note that I also encountered this issue with the default mod versions in this modpack (EnderIO 2.2.5 build 311, and ChickenChunks 1.3.4.14). I am using a Powered Spawner to spawn zombies for a Blood Magic's well of suffering to produce Life Points. The spawner is centered in a chunk directly above a well of suffering. There is a Chickenchunks chunk loader in the chunk and I've given it a 4 radius to encompass my power production. I've since eliminated power as an issue by placing an EnderIO's creative capacitor bank directly onto the powered spawner. I've tested with a 3 radius and a 5 radius on the chunk loader with same results. My Blood Magic's life points begins to drop when I walk a certain distance away from the spawner even though the entire area of the spawner and well of suffering is chunk loaded. After some testing, that distance appears to be three chunks between the chunk I am in and the chunk the spawner is in (for a total of five chunks). Using the spawner as a reference, my life points climb if I stand at the back of the chunk I am. However, my life points begin to drop if I cross the chunk boundary behind me. Once I cross the boundary, it takes about three to five minutes for my life points to begin to drop (I have a ritual of the green grove running which uses a very small amount of life points). I use Blood Magic's Divination Sigil to check my life points. The radius of the chunk loader appears to have no affect on the distance between the spawner working and not working. The critical distance remains the same regardless of chunk-loading radius.

Using Modular Powersuits, I can quickly fly to the spawner from just three chunks away (takes about a second). So, when my life points begin to drop, I fly over to the spawner to see if zombies are there or not (thinking perhaps zombies were actually spawning but that the issue is might be that the well of suffering was not working when I was a distance away). I fly to the spawner and no zombies are in the area, but zombies are spawned within two or three seconds of my arrival. To test that further, I put a vacuum hopper near the spawner, dumping its collection into an ender chest. I have a matching ender pouch. I get zombie flesh in the pouch when I am three chunks away from the spawner. However, crossing the chunk border putting four chunks between myself and the spawner, I get no flesh in the pouch and my life points begin to drop.

Here's an annotated journeymap image of the area: http://i.imgur.com/C7Vhco4.jpg

**Comment by HowardRoark2016** [comment]
I dismantled the powered spawner. I filled the ground beneath the Blood Altar with cursed earth. Enemy mobs spawned like crazy. I went back to that chunk border where my life points would begin to drop. Well, after about the same amount of time as before, my life points began to drop again. Apparently, this is not an issue with the powered spawner. Please accept my apologies.

**Comment by MatthiasMann** [comment]
well - it might still be possible to fix it :D
