### ISSUE TITLE
Suggestion: Yeta Wrench: show TileEntity Names when selecting direction.

### ISSUE THREAD

**Issue by MaPePeR** [SleepyTrousers/EnderIO#1984]
It would be awesome, if the GUI to select the direction of the Conduit you want to edit (North, South, West, East, Up, Down) would also show the name of the Block/TileEntity,  that the conduit is connected to in that direction.

For most of the cases where you don't connect the same blocktypes with eachother this would make it easier to figure out which direction you need to edit without needing to look at the map/F3 mode.

**Comment by tterrag1098** [comment]
Ooh, I like that

**Comment by MatthiasMann** [comment]
Hmm - why not use the side configuration render instead?
