### ISSUE TITLE
Painted Glowstone painted as Binnie's mods botany blocks, corrupts world.

### ISSUE THREAD

**Issue by Robijnvogel** [SleepyTrousers/EnderIO#1994]
So I just painted glowstone with an Alice Blue Ceramic Block and after I placed it my client crashed. The server just kept running. The crashlog says that it can not cast a painted glowstone block into Binnie's block.IBlockMetadata. When I tried to rejoin the server I got the same crash.

Crashlog: http://pastebin.com/UQ3nAwrj

If this is a Binnie's mods or Waila bug, please tell me and I will try to notify them.

**Comment by Robijnvogel** [comment]
Could you implement a method that checks whether painted glowstone can actually be cast into the block it is painted with, before the painter paints the glowstone? This would be really handy as you should never get any of these sorts of crashes.
Or have you already implemented that and is this just really really really Binnie's fault?

**Comment by tterrag1098** [comment]
This was released under https://github.com/SleepyTrousers/EnderIO/commit/5d08a9d976a3d29072fe17a52945b7e00548795b
