### ISSUE TITLE
[Suggestion] Cosmetic macine chassi block

### ISSUE THREAD

**Issue by p75369** [SleepyTrousers/EnderIO#1999]
Could the machine chassi be turned from an item to an actual block. Like a blank machine with no determinable front for use as a cosmetic block. would be great for creating an EnderIO wall, using a blank machine chassi painted facade to fill in the gaps between actual machines.

**Comment by HenryLoenwind** [comment]
Ender IO Addons ( https://github.com/HenryLoenwind/EnderIOAddons ) has a decorative block that can do that.

![](http://loenwind.info/eioa/deco1.png)
