### ISSUE TITLE
[Suggestion/Request] Power conduit switch

### ISSUE THREAD

**Issue by thekazador** [SleepyTrousers/EnderIO#20]
Any change of make some Power conduit switch? some machinnes like thermionic fabricator, rolling machinnes, laser need constant energy and some ppl of my server suggested this

**Comment by DeleteMetaInf** [comment]
I think, in the new version of Ender IO coming out for 1.19.2(?), that a redstone toggle mode for all conduits should be added. Would be neat, and it’s something that most cable/pipe mods have (e.g., Mekanism and Pipez).

**Comment by Nevrai** [comment]
I think, in the new version of Ender IO coming out for 1.19.2(?), that a redstone toggle mode for all conduits should be added. Would be incredibly useful, and it’s something that most logistics mods have (e.g., Mekanism, Pipez, LaserIO, Pretty Pipes, Refined Pipes).
