### ISSUE TITLE
[Suggestion] - Disable features of DimTransceiver

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#2002]
I recently started to mess with Ender Rails. They are purely awesome, but there is slight issue.... Noone will be using them, because why to use Ender Rail with Cart since I can directly teleport items via Transceiver itself.
So here comes my suggestion. Would it be possible to implememnt configurable Transceiver features so modpack makers who want to put more emphasis on Ender Rail, can disable Item, Fluid and Energy teleportation via Transceivers and leave it only on "complex" Rail systems?

**Comment by MatthiasMann** [comment]
I see the rail teleportation mainly as a design element of your build.

**Comment by 6210classick** [comment]
there is an option to disable Ender Rails in the config if you want

B:enderRailEnabled=false

it's has it's uses maybe you find it useless but some love it , just be aware it causes a memory leak in servers especially when traveling between dimensions

**Comment by Pelirow** [comment]
6210classick:

I have been trying to gather more information about this memory leak. Does it cause memory leaks when limited to single-dimension travel? Can you point me to more information on the memory leak issues?

**Comment by 6210classick** [comment]
in single player & traveling between in the same dimension it shouldn't cause a leak in memory how even in MP especially when the minecart goes back and forth from one dimension to another it will happen it's even worse if a player was in the minecart

**Comment by Pelirow** [comment]
Just to clarify: are you saying that on servers, the issue does NOT appear to occur in inter-dimensional use with players in the minecarts, only cross-dimensional?

**Comment by 6210classick** [comment]
it happens when a player is transported while on the minecart either inter-dimensional or cross-dimensional

**Comment by Pelirow** [comment]
Aw, bummer. Thanks for the clarification and confirmation. Hopefully the issue gets addressed in the upcoming update. Wonderful mod!

**Comment by tterrag1098** [comment]
It's a vanilla bug...happens the same with e.g. mystcraft.

**Comment by Pelirow** [comment]
Oh? By vanilla bug do you mean the memory leak happens with the nether and end portals as well? I can't seem to find any info about it. Is it just specific to minecarts and players in them, or any use of portals?

**Comment by JasonMcRay** [comment]
I am sorry, but its getting a little off-topic in here with all the memory leak problem... All i just suggested is if there could be a way to disable item/fluid/energy transportation via Dimensional Transceivers and leave only Ender Rails and Railcraft contraptions as a way of transporting items/fluid/energy

**Comment by Pelirow** [comment]
Sorry, it is a good suggestion and I hope it gets considered. 

I don't see anything in the configs for modifiying the RF cost for transporting items or energy via transreceiver, but there is an option for fluids, at least. You could set the RF cost prohibitively high for fluid transport, essentially making fluid transport through the transreceiver "disabled."

The config is huge so I may have missed a similar option for items and energy.

**Comment by JasonMcRay** [comment]
Setting an power cost values higher is just a workaround and I think I would start getting "bug reports": "Transcevier ate all my energy and didnt transported single bucket". Or "Power I am sending via transceiver is getting lost, pls fix" :)

Thats why I am looking for direct approach with disabling these 3 trans methods.
