### ISSUE TITLE
Capacitor banks not showing storage in waila

### ISSUE THREAD

**Issue by BuckitHead** [SleepyTrousers/EnderIO#2005]
EnderIO 353
Waila 1.5.9
was working in 352

**Comment by tterrag1098** [comment]
Fixed via https://github.com/CrazyPants/EnderIO/commit/9e6aaf2ac3d335ad7fc0104ffa2fb821251a9ce2

**Comment by BuckitHead** [comment]
So you know after updating to 355 from 354 all farm blocks on the server lost their capacitors so i have to go to everyones farm blocks and replace them. after that everything is fine..

Tom

**Comment by HenryLoenwind** [comment]
Thanks for the info. I thought I tested all cases with existing Farming Stations, but I might have missed that one. I'll look into it later today.

Background: Farming Stations now have one more slot, so the contents have to be shifted when loading an old one.
