### ISSUE TITLE
Server freezes caused by vacuum chests and electromagnets

### ISSUE THREAD

**Issue by thehobojoe** [SleepyTrousers/EnderIO#2012]
There is no error log so reporting this issue is difficult, but every time a vacuum chest is placed, or an electromagnet is enabled, the server goes from running butter smooth to being nearly completely inoperable immediately. Using build #351.

**Comment by superpatosainz** [comment]
A profiler log would be useful @thehobojoe... to see which and whose functions and hooks are buggy.

**Comment by thehobojoe** [comment]
I used opis, but it didn't show anything - it's something outside of its scope, apparently. I dunno how to run other profilers, if you could point me in the right direction I can try to get some more info.

To give some more info though, I did some more thorough testing - the problem only happens when a large number of items are in the range of the vacuum chest / magnet, approx 20+. With the magnet that caused the server to hang for ~30 seconds (running opis at the same time didn't show any problems). With the vacuum chest the hang was worse. A few ticks managed to get through and someone was able to break it after a few minutes which fixed the problem instantly. I know the issue is hard to track down, but that's all the info I have at this point.

**Comment by superpatosainz** [comment]
@thehobojoe here's a cool guide I've used to profile my MC client with VisualVM: <https://bukkit.org/threads/wip-analysis-of-your-server-jvm-using-visualvm.66536/> ... just adapt from bukkit and voilá
