### ISSUE TITLE
ME conduits not showing channels while in facades with Yeta Wrench

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2013]
Just installed build 353 and while I love that the tooltip shows the number of channels in ME conduit now, if the conduit is covered by a facade it goes back to showing power info:
![no facade](https://cloud.githubusercontent.com/assets/10668463/6387667/bae0b70c-bd43-11e4-89fe-93c157a9361a.png)
![facade](https://cloud.githubusercontent.com/assets/10668463/6387669/bd4744d4-bd43-11e4-8921-91dba540e684.png)

**Comment by tterrag1098** [comment]
This was released with https://github.com/SleepyTrousers/EnderIO/commit/6d98bbe35f7cb599dbfa13b75750b065ed91bc8e
