### ISSUE TITLE
Insert and Export pointers not rendering

### ISSUE THREAD

**Issue by kennymoto** [SleepyTrousers/EnderIO#2014]
I am not sure if it is the current version of enderio or cofh updates but the arrows no longer render correctly on the conduits. Must view from weird angles to see them. I noticed the issue on direwolf20 forgecraft video today as well

**Comment by 6210classick** [comment]
what version of EIO & Forge are you using ? it should been fixed on any version higher than 2.2.8 349

**Comment by HenryLoenwind** [comment]
All 2.2.8 releases have this bug. It is fixed for the next major release.
