### ISSUE TITLE
Spelling error in console output

### ISSUE THREAD

**Issue by FixTheBlocks** [SleepyTrousers/EnderIO#2017]
The console output produced by ServerChannelRegister.java has several spelling errors. Transceiver is spelled Transciever and Trasciever. Channels is spelled channles. The capitalization also varies  between lines.

**Comment by tterrag1098** [comment]
Noted, but it's too late to edit the filename now.

**Comment by FixTheBlocks** [comment]
The filenames are all correct if I'm not mistaken.
