### ISSUE TITLE
Soul binder help.

### ISSUE THREAD

**Issue by StoneWall82** [SleepyTrousers/EnderIO#2022]
I don't know if this is an issue or if i am doing something wrong. I have a soul vial and a broken spawner in the soul binder and it only lets me put up to 14.9ish exp when the recipe asks for 15 also i don't know if the storage needs to be at 2,500,00 rf and if it does i have no idea how to get it there. i have a octadic capacitor in it right now and it only gives 500,000 rf.

If you could help it would be greatly appreciated.

**Comment by 6210classick** [comment]
don't worry about the power consumption as long it have constant power it will keep working if for whatever reason the power source stopped the processes will stop and it will continue after the power is back , also try piping in liquid experience

what version of EIO & Forge are you using ?

**Comment by StoneWall82** [comment]
ender io 2.2.8.349
forge 1.7.10
and i will look to see if pumping in exp will work

**Comment by StoneWall82** [comment]
The liquid xp seemed to do it. thank you!

**Comment by 6210classick** [comment]
forge 1.7.10 ? what version are you using not what version for MC ? i would recommend you update to 1291

**Comment by hisorange** [comment]
I was able to reproduct the issue by placing a soul binder put in the items for binding and click to the exp button with less than the required xp then get more xp and click it on again. v2.2.8.349
