### ISSUE TITLE
Dense ME Conduit not working after game restart

### ISSUE THREAD

**Issue by crunkazcanbe** [SleepyTrousers/EnderIO#2028]
Ok long story short me and my wife play MC with each other in lan mode with just 3 mods installed AE2 and Enderio and extra utilities . Well I have a Dense ME Conduit connecting a me controller to a dense energy cell it works fine until I restart MC . So each time we close minecraft down , and start it back up I have to break and replace a whole entire line of Dense ME Conduit , and it starts back working . For now until I know this might work for sure I just replaced all Dense ME Conduit with ME dense cable , and covered em nicely with cable facades . Got pissed and tired of breaking and replacing that every time we start our world back up . There is no errors thrown in the console or logs nothing at all .

Thanx -Crunk

BTW latest version of enderio on jenkins for 1.7.10 is what I am running .

**Comment by tterrag1098** [comment]
Could you please post the version exactly of what you are running?

**Comment by crunkazcanbe** [comment]
I am running this version here http://ci.tterrag.com/job/EnderIO/352/

**Comment by tgstyle** [comment]
I have had something similar happen when I have had dense conduits at right angles next to dense cables with the link in between them disabled (thus forming the right angle). They were attached a block or two higher up the line. Higher as in actually pointing up. I have not observed it at any other angle yet. After a server restart the conduit that is at the right angle with the link disabled between it and the dense cable has to be removed and replaced in order for it to be recognized in the ME network again.

**Comment by tgstyle** [comment]
Here is one example.
http://imgur.com/pGnn4dS

**Comment by crunkazcanbe** [comment]
That is exactly my problem . Thank you for posting a screen shot . I was about to do it. :)

**Comment by tgstyle** [comment]
The Purple book is EnderBook. It works for 1.7.2 and 1.7.10
link here - http://duke605.github.io/mods/ender-book/

**Comment by crunkazcanbe** [comment]
@tgstyle Thanx man! Looks like a nice way of getting around . Anyways back to the point I hope this issue is getting worked on . :)

**Comment by crunkazcanbe** [comment]
Any new info on this ?

**Comment by Mad-Virus** [comment]
Hello,
im usind ENDER IO 1.7.10-2.2.8.349 in FTB:Infinity 1.2.1 Modpack, Forge 1291.
I have similar problem with connecting Dense ME Conduit's behind ME Tunnels.
Line Dense ME Conduit 1 ME Smart Cable ore ME Dense Cable to connect to the Tunnel and behind the Tunnel connecting with Dense ME Conduit. After every server restart i have to remove the cable after the tunnel because it's looking like posted on screenshoot above. also if i put one ME dense or Smart cable after the tunnel and than Dense ME Conduit after a Restart it looks like its still connectet but i have to remove and put it in again because it is'nt connected.

**Comment by MatthiasMann** [comment]
The issue is that AE2 does not issue a neighbor changed event when it changes anything - and the AE2 API doesn't provide any means to work around that.
