### ISSUE TITLE
Technological alternative for the Slice and Splice Components  

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#2029]
Just wanted to request alternate recipes for the item filters and other components that require mob based technology from the Slice and Splice. There is a fatal flaw in your recipe design in that the components are fairly common within your mod but have a heavy reliance on mob heads which are Generally a very rare drop and unless you have a improved enchanting mod or some how manage to get lucky and pull a vorpal sword out of your bum it is Very difficult to obtain in normal servers and next to impossible on peaceful worlds. Considering how EnderIO is a very widely used industrial oriented mod where the ""Advanced Filters"" are pretty much required to be mass produced. I would highly recommend adding an alternate set of Components/Recipes that can be enabled in the mod configurations to allow these components to be produced on peaceful maps where mob heads are not obtainable.

**Comment by MatthiasMann** [comment]
You can use The Ender which has increased drop chance for heads when empowered, and there is also the Peaceful Table (from Extra Utilities).

**Comment by 6210classick** [comment]
also Tinker Construct weapons with Beheading VII (i think ) will always make the mob drop it's head

you think mob heads are hard to get ? put vanilla zombie or skeleton or with killer joe with The Ender and in an matter of hours you will get so many skulls you never gonna know what to do with them

also their is another type of filter called The Existing Item Filter which give you at least 30 slot but you can't blacklist items only white list

**Comment by HenryLoenwind** [comment]
Yes, "The Ender" is a required part of the tech chain here. Having other mods that enable mob head drops just makes it easier fro you.

About peaceful mode: While I see some scenarios where peaceful mode may be useful, Ender IO like most mods is targeted for normal survival. There are solutions out there for players who need peaceful.
