### ISSUE TITLE
[Suggestion] Farming station compatibility with AgriCarft

### ISSUE THREAD

**Issue by tgstyle** [SleepyTrousers/EnderIO#2030]
Right now it will harvest the plant and the crop. Would it be possible for it to leave the crop and replant the seeds in the crop?

**Comment by tgstyle** [comment]
It would also need to be able to remove weeds and plant in the crops again.

**Comment by PavelInt** [comment]
And magicalcrops please.

**Comment by tgstyle** [comment]
https://github.com/InfinityRaider/AgriCraft/issues/92
https://github.com/SleepyTrousers/EnderIO/pull/2316

**Comment by homemmakako** [comment]
I'd say it should harvest the crops without removing the seeds, just like you would do by hand when you rightclick the crops. (and wow, this is an old issue XD )

**Comment by tterrag1098** [comment]
@homemmakako That's what the farming station always does

**Comment by homemmakako** [comment]
@tterrag1098 by crops I mean cropsticks from agricraft; the farming station should leave them, but right now it removes them as if they were mature seeds.

**Comment by HenryLoenwind** [comment]
I'm currently working on the Agricraft integration. But it'll take some time to finish it.
