### ISSUE TITLE
Glitch with ender rails.

### ISSUE THREAD

**Issue by BlizzardPenguin** [SleepyTrousers/EnderIO#2032]
I dont what I am doing with this site but I have found a couple glitches with ender rails. If you use an ender rail on DW20 and you have an angel ring in you inv, it will no longer work when you come out the other side. You have to drop it on the ground and then reequip it so you can start flying again.
If you use the ender rails too close to each other they will glitch out your entire player. The minecart that you were riding disappears and you cant interact with any blocks until you relog.

**Comment by MatthiasMann** [comment]
does the angel ring issue also happen when you use a nether portal?

**Comment by 6210classick** [comment]
what version of EIO are you experiencing this problem with ?

@MatthiasMann isn't this related to the memory leak problem ?

**Comment by BlizzardPenguin** [comment]
@MatthiasMann No angel ring works fine with the nether portal
@6210classick I am using Eio 1.7.10-2.2.5.311

**Comment by MatthiasMann** [comment]
That's a very old version - update to 2.2.8.359 and try again.
But I suspect that you need to contact ExU for issues with the angel ring.
