### ISSUE TITLE
[Suggestion] Disable blocks/machines in config

### ISSUE THREAD

**Issue by Kayot** [SleepyTrousers/EnderIO#2035]
In extra utilities I can disable any block or machine that I want through the config file. A lot of the newer machines that EnderIO comes with complicate the already saturated set of mods that I have. I mainly use EnderIO for it's conduits. I only use it's machines to make said conduits. So I'd love to disable all the newer stuff like killer joe and such. Not just remove the recipe, but the whole item.

**Comment by 6210classick** [comment]
but Killer Joe is Awesome !
