### ISSUE TITLE
Crafter + Extra Utilities Dupe Bug

### ISSUE THREAD

**Issue by shadowfacts** [SleepyTrousers/EnderIO#2038]
When crafting Magical Wood from Extra Utilities in the Crafter the recipe can be set to use 4 books that give a total of 30 Magical Wood in a normal crafting tables, and then input level 1 books, that should only give a couple pieces of Magical Wood. All four level 1 books, the gold, and a bookshelf will be used, and 30 Magical Wood will be output. Not 100% sure about how Extra Utilities does this, but I would guess it is with a custom IRecipe which EIO is not respecting.

CC @RWTema

**Comment by HenryLoenwind** [comment]
Confirmed with current latest code revision.

Reasons:

(1) net.minecraft.item.ItemStack.isItemEqual(ItemStack) ignores NBT data and will happily confirm that an enchanted book with "Bane I" is the same as one with "Protection X".
(2) Output is created as copy of the "ghost" result.
