### ISSUE TITLE
[Suggestions] Separate upgrade for sticky mode and regulating upgrade

### ISSUE THREAD

**Issue by Revemohl** [SleepyTrousers/EnderIO#2045]
It's a pretty useful option, but I believe that limiting it to only advanced item filters makes it a bit too difficult to use. My suggestion is being able to upgrade normal item filters with something so they can also have the sticky mode (and maybe making advanced filters also require that upgrade just for flavor), or something like that. Adding sticky mode to normal item filters would be probably way too cheap.

The other suggestion is adding either an upgrade for item conduits or a new block similar to the item buffer that sort of acts like the regulator from the RP2 of old, i.e. only letting up to a certain amount of something in a whitelist go into an inventory.

**Comment by 6210classick** [comment]
there is the Existing Item Filter which allows at least 30 item filtering slots
