### ISSUE TITLE
Exp Obelisk 

### ISSUE THREAD

**Issue by MFeltmann2** [SleepyTrousers/EnderIO#2046]
on the enderio wiki theres missing the diffrent obelisks.
and how many levels can the exp obelisk store?

**Comment by 6210classick** [comment]
2147483647 levels , plz don't post your questions here this is only for issues there is EIO thread in MC fourm

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291161-1-7-1-6-ender-io-how-many-pipes-in-one-block

if you got any questions feel free to ask in that thread
