### ISSUE TITLE
Up

### ISSUE THREAD

**Issue by THEVOLCO** [SleepyTrousers/EnderIO#2047]
Hi,

I updated some Mods including ender io. when I try to enter my world it crashes and I think ur mod is causing that Problem.

Crash Report:

http://pastebin.com/xtWJFQxc

**Comment by cabralRodrigo** [comment]
Probably problem on DragonApi side.

**Comment by KlutzLament** [comment]
You need to update forge to 1291.

**Comment by THEVOLCO** [comment]
im already using that Version of forge

**Comment by 6210classick** [comment]
AE2 rv1 support has been drooped update to the latest RV2-Beta-8

**Comment by tterrag1098** [comment]
Do you have any conduit facades painted as RotaryCraft blocks?
