### ISSUE TITLE
Power Monitor not updating when offline on a server

### ISSUE THREAD

**Issue by Chaoschunk** [SleepyTrousers/EnderIO#2055]
Hello, 

On the buildguild server I have a power monitor connected to 2 large capacitor banks, and sending a redstone signal to not gate from project red integration. While I am offline and the chucks are loaded with a chunk loader the power monitor does not update it redstone signal to the not gate or just a piece of redstone connected to itI have tested this by breaking the power monitor and replacing it and setting it back up then it will send the correct redstone signal.  I will be casting most of the day 3/5/15 if you would like me to show you the setup. 

Chaoschunk

**Comment by stilleraben** [comment]
Currently noticing this in current mod version for 1.7.10 also. I have to give the redstone directly powered by the EIO power monitor a block update to change its state. Also feel its related to unloaded and reloaded chunks.
