### ISSUE TITLE
[Suggestion] Mod support for farming station

### ISSUE THREAD

**Issue by AiwendilCiunio** [SleepyTrousers/EnderIO#2060]
It's pretty sad that this amazing device won't work with any saplings other than vanilla. Would be great to allow it to use Forestry trees, Greatwood etc.

**Comment by 6210classick** [comment]
what version are you using ?

**Comment by AiwendilCiunio** [comment]
Latest version - 2.2.8.350

**Comment by MatthiasMann** [comment]
Latest dev build is 355, latest release is 2.2.8 build 349

**Comment by AiwendilCiunio** [comment]
Well what are you suggesting? Is it already a feature, or is it not and not gonna be added? I'm confused.

**Comment by 6210classick** [comment]
i think it's already implanted , if you can't put it inside the farming station just plant them around it when it harvest the tree saplings should end up in it

**Comment by AiwendilCiunio** [comment]
No, it didn't harvest the tree at all.

**Comment by Dwargkiller** [comment]
I'm unofficially designating this the catchall issue for farming station mod support. 

Related issues include (but are not limited to):
#2152 
#928
#697 (Half implemented, trees but not crops functioning (consider if IC2 should be supported or not))
#688 (Possibly implemented)

The following is an incomplete list of mods that contain trees that currently are not supported in the farming station that could be (possibly):

Witchery (Ents may provide additional work or difficulty)

Thaumcraft (Issues may arise with size of trees. Need is also
                  reduced due to the size of gathering in the wild, 
                  consider this low priority if at all)
Forestry (Issue is a year old, might be implemented)
Pam's Harvestcraft (Wide variety may introduce problems)
Aether 2
