### ISSUE TITLE
Obelisk visual bug.

### ISSUE THREAD

**Issue by hisorange** [SleepyTrousers/EnderIO#2062]
Aye, the rotating item over the obelisk seems to do a weird rendering behavior. When I stand near to it it appers over the obelisk but as I start to walk away from it the rendered item will start to move out from the block into the the opposite direction. It's not a big deal when there is air around the obelisk but if you put a solid block behind it, the item will be rendered inside in that block.

The emerald rendered halfly in the block behind http://i59.tinypic.com/24m9e0g.png as I get further away it completly dissapers.

v2.2.8.349

**Comment by tterrag1098** [comment]
This is fixed in dev builds.
