### ISSUE TITLE
Crash with Thermal Expansion and Vacuum Chest

### ISSUE THREAD

**Issue by Iomega0318** [SleepyTrousers/EnderIO#2065]
I am not 100% sure this is related to your mod or TE, however the crash report does say a lot about EnderIO so I figured I would start here. If this is indeed related to TE please let me know and I will post this over on their site.

Here is the crash report:
http://paste.ubuntu.com/10565466/

What I did to cause it, I had a Vacuum Chest above a Tesseract connected to it with a power conduit and Item Conduit (I was using it as a quarry set up since Buildcraft updated and has decided to eat all my power and move 10,000 miles an hour it spits items everywhere!) anyways.. I used a wrench to pick up the Tesseract which was immediately picked up by the Vacuum Chest and the server crashed, I logged back in and the Tesseract was fine and inside the chest..

**Comment by HenryLoenwind** [comment]
It looks like the item conduit tried to insert something into the Tesseract when the crash occurred. As the Tesseract wasn't there anymore, I can understand that it didn't quite liked it. ;)

I'll leave finding out why that happened to someone who knows the item conduit code better.

**Comment by Iomega0318** [comment]
Well the only item the Vacuum Chest had to suck up was the Tesseract lol, I wonder if it sucked it up fast enough to try to output it into the Tesseract before it actually finished picking it up?

**Comment by tterrag1098** [comment]
The crash here is in tesserract code. Are you on the latest releases of CoFH mods?
