### ISSUE TITLE
[Waila] Power readings disappear on Thermal Expansion with EnderIO enabled

### ISSUE THREAD

**Issue by benten2000** [SleepyTrousers/EnderIO#2069]
Having a slight problem with Waila tooltip showing the power readings on any Thermal Expansion items when I have EnderIO enabled, once disabled it works again.

Tried on a fresh 1.7.10 Minecraft install with:
Forge 10.13.2.1307
CoFHCore-[1.7.10]3.0.0RC5-207
ThermalDynamics-[1.7.10]1.0.0RC5-94
ThermalExpansion-[1.7.10]4.0.0RC6-138
ThermalFoundation-[1.7.10]1.0.0RC4-58
Waila-1.5.9_1.7.10
EnderIO-1.7.10-2.2.8.349

All the mods by TeamCOFH are release versions but also tested using latest alpha ones but still the same.

**Comment by 6210classick** [comment]
where did you get forge Forge 10.13.2.1307 ?? the latest version that i can find is 1291 ,, it's probably something to do with Waila config EIO option appear in Waila config when installed try messing with those , or use a dev version of EIO and see if this problem still occur

**Comment by tterrag1098** [comment]
This is fixed in dev builds.

**Comment by benten2000** [comment]
Ahh thank you for ino tterrag1098

As for forge 6210classick I use MultiMC that can download any Forge version needed. If need to get it manually then they are located here http://files.minecraftforge.net/minecraftforge/1.7.10

**Comment by hron84** [comment]
@benten2000 You using wrong page to get Forge. The latest supported Forge for 1.7.10 is 10.13.2.1291, 10.13.2.13xx is usable for 1.8. It's a bit difficult, but the 1.7.10 branch is not contains the accepted Forge releases. Use http://files.minecraftforge.net/minecraftforge/ to determine available - and usable - Forge releases to avoid unexpected bugs.

**Comment by tterrag1098** [comment]
Sorry but you're completely wrong. Forge master branch has moved to 1.8 so
any 1.7 releases are now on the 1.7.10 branch. His link is perfectly valid.

**Comment by hron84** [comment]
And how stable these forge releases are? I heard some problems with these new forge and some mods. Is there any new big change that I should worry about?

**Comment by tterrag1098** [comment]
If any mod has bugs with these versions it is their fault. Forge has not broken backwards compat in any way.
