### ISSUE TITLE
Dark Helm nightvision too easy?

### ISSUE THREAD

**Issue by Zaflis** [SleepyTrousers/EnderIO#2071]
Nightvision upgrade can be put directly in the non-empowered Dark helm, is this intended? It doesn't use any RF even if empowered. Also same for sound locator upgrade.

But if it's how it's supposed to work, close this and maybe wiki should be updated with that note. Since it actually claims empowered 1 is requirement: http://wiki.enderio.com/Dark_Helm

EnderIO 1.7.10-2.2.8.349

**Comment by 6210classick** [comment]
it never used any power before but i believe older versions required you to have Empowered before add it , not really a big deal because eventually you will have to add Empowered anyway
