### ISSUE TITLE
Unable to shift blink in space with staff of traveling

### ISSUE THREAD

**Issue by PsionicArchon** [SleepyTrousers/EnderIO#2072]
When floating in space I can no longer blink. I must be standing on a surface.

I am using version 2.2.8.355 of EnderIO and version 3.0.9.293 of Galacticraft.

**Comment by 6210classick** [comment]
what about traveling anchors can you teleport to them while floating in space ?

**Comment by PsionicArchon** [comment]
Yup, works perfectly fine. It's only shift teleporting that's broken.

**Comment by tterrag1098** [comment]
By in space you mean what, galacticraft space?

**Comment by PsionicArchon** [comment]
Yup, it's Galacticraft space within a space station dimension. I can teleport just fine if I'm standing on a block but I loose the ability to shift blink while floating.
