### ISSUE TITLE
Soulbound not working with Baubles

### ISSUE THREAD

**Issue by fabbe50** [SleepyTrousers/EnderIO#2074]
The Soulbound enchantment is not working with items in the baubles slots.

Running EnderIO Version: 2.2.8.349
and Baubles Version: 1.0.1.10
on Minecraft 1.7.10

This happened after updating EnderIO from 2.2.7.325 to 2.2.8.349!
Help is much appreciated!

**Comment by tterrag1098** [comment]
Not a bug, just a missing feature. The baubles inventory is separate from the normal player's inventory so there is no way for EIO to know it exists without special compat.

**Comment by HenryLoenwind** [comment]
@tterrag1098 Actually that's not the reason it doesn't work. Baubles adds its items nicely to the list of items to be dropped. But only *after* Ender IO has removed the Soulbound items from the list. And Ender IO *has* to do that early so no gravestone mod can snatch them away...
