### ISSUE TITLE
Conduit and facade don't drop anymore on survival

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2086]
On survival gamemode, breaking a facade with a pickaxe won't drop the item anymore (it's lost forever). If there's a conduit inside the face then both the conduit and the facade are lost when broken.
In creative, it seems to work as expected: breaking a facade won't destroy the conduit inside.
May be related to issue #2082.

**Comment by tterrag1098** [comment]
Fixed via 110355829a43dfe359284157bfec072b8a4a066d
