### ISSUE TITLE
[SAG Mill] Quartz Ore (nether) produces certus quartz dust, not nether quartz dust

### ISSUE THREAD

**Issue by GauHelldragon** [SleepyTrousers/EnderIO#2090]
The SAG Mill recipe for Quartz Ore (nether quartz) has a chance of producing certus quartz dust, not nether quartz dust.

**Comment by 6210classick** [comment]
replace SAGMillRecipes_User.XML with this one

https://www.dropbox.com/s/xvr54gw0n1iqsoi/SAGMillRecipes_User.xml?dl=0

**Comment by tterrag1098** [comment]
Certus Quartz Dust is oredicted to dustNetherQuartz. I can fix this in the default oredict prefs file.
