### ISSUE TITLE
Dimensional Transceiver fails to power Electric Pump

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2094]
The dimensional transceiver (DT) is set to receive power. When I place it next to the power connector of a Mekanism's electric pump, it won't power it. Note that the same DT can power other machines and that a power conduit or a capacitor bank can power the electric pump as expected. While I can only see this bug with Mekanism's electric pump, it may affect other machines. The special thing about this pump is that it only accepts power on a single side (rather than all 6 like most machines). It would be nice if someone can test it with another machine that only gets power on 1 side.

Addendum: looks like a DT can't power a fluidic plenisher at all.

**Comment by tterrag1098** [comment]
It's likely mek's end screwing up the RF API, this wouldn't be the first time.

**Comment by emperor06** [comment]
Can be.
I was just puzzled because both TE's energy cell and EIO's capacitor bank can power it (both using the RF api right?). Shall I open an issue at Mekanism's?

**Comment by ProRedHD** [comment]
Probably the same issue as in #2538
