### ISSUE TITLE
Farming Station drops items on the ground

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2096]
When a farming station harvests too many items and overflows its internal item buffer, items are dropped on the ground leading to potential server lags and item loss.
This happens quite often when farming trees with shears on as a tree can produce quite a large number of items (wood, leaves, fruits) or when a slow speed pipe is used to extract the items from the station.
A vacuum chest can be used as a workaround tho.

**Comment by HenryLoenwind** [comment]
This is the intended behavior. However, it may be a good idea to extend the internal storage, now that we shear leaves. Goes to my TODO list.Thanks for the heads up.

**Comment by roboderpy** [comment]
Still seems to be a problem.
![2016-09-09_13 30 30](https://cloud.githubusercontent.com/assets/6339511/18377637/6e073e10-7692-11e6-956c-e1a2099fad40.png)
![2016-09-09_13 38 32](https://cloud.githubusercontent.com/assets/6339511/18377638/6e2cefa2-7692-11e6-82cb-0ac85d200cd6.png)
Basically, farm station should try to push items immediately into configured side when it's internal inventory overflows when it chops trees
