### ISSUE TITLE
Farming Station tree shearing bug

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2097]
According to commit a79ae8b0d3075a32ba53795cccb30ec1f82ccb6b,
* Farming stations will use shears if available and there are enough sapling in store
* Otherwise they will break the leaves with the axe

I can't seem to be able to get this behaviour. Regardless of how many saplings I put in any slot (or all of them), I always end up running out of saplings. All my farming stations happily shear everything even tho they have no more saplings in store :)

**Comment by HenryLoenwind** [comment]
tterrag removed that feature when pulling the PR

**Comment by emperor06** [comment]
Aww what a shame, that would have been a wonderful feature. Thanks for the input.

**Comment by HenryLoenwind** [comment]
@tterrag1098 If I'd re-implement it, with a nice config setting or two, would you pull it?

**Comment by emperor06** [comment]
Just my 2 cents, as far as tree farming is concerned I can hardly see any real difference between MFR Harvester+Planter and EIO's Farming Station as it is now. One has less server lag and consumes tools, the other is more realistic visually but function-wise, they work pretty much the same for users. They both need 2 farms to get leaves (one for leaves and one for saplings). MFR can't handle a fully automatic leaves farming because the planting is done on a separate machine. That's why, imho, I think it would be nice to have this feature in EIO, at least as a non-default config option :)

**Comment by tterrag1098** [comment]
I thought it would be confusing to a new user (one that doesn't read commit messages, lol), because it confused me trying to use it.

**Comment by HenryLoenwind** [comment]
I think a way to not confuse users would be to harvest 50:50 when low on saplings. So people *will* see the expected leaves in the output.
