### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2098]
Textures are missing (invisible objects) and 3d models look screwed since commit c989340b02997893e9c4e481f0452cfc77c97fca (Implement combustion gen model and add system for rotatable ISBRH models)

**Comment by tterrag1098** [comment]
Whoops, my bad. Fixed in https://github.com/SleepyTrousers/EnderIO/commit/6cccf5f7347013e9cffdaa48f3625423d3293317

**Comment by HenryLoenwind** [comment]
Zombie Gen, Killer Joe, Dim Trans and Enchanter are still texture-less.

**Comment by tterrag1098** [comment]
Closing as this was only present in dev builds
