### ISSUE TITLE
Item Buffer painting duplication bug

### ISSUE THREAD

**Issue by Unumati** [SleepyTrousers/EnderIO#2099]
Sry if this is already reported i tried to search for it but i couldn't find it. 

If you put, lets say 4 Item Buffer in a Painting Machine, you will get 4 painted Item buffers as an output but it only consumes one. I don't know if its pack related (Custom, based on Bevo Techpack)

Now I didn't test every paintable block but as of now I just was able to dupe Item Buffers

I'm using the latest version of Ender IO.
(english is not my main language so in the case anything was poorly explained, I will add a vid for proof)

https://vid.me/M8Nh

**Comment by tterrag1098** [comment]
This is fixed in dev builds, but not in release.
