### ISSUE TITLE
Only null may change this block's settings

### ISSUE THREAD

**Issue by PsionicArchon** [SleepyTrousers/EnderIO#2102]
Using the latest jenkins release I am no longer able to change the travel anchor's settings.

Example: http://i.imgur.com/dIsec8m.png

**Comment by Tsunayoshi** [comment]
I have the same problem. But I am not getting any messages. Click an old Anchor (placed in the EnderIO version before) the game crashes: http://pastebin.com/0LKs2XAX

**Comment by shady2k** [comment]
Same problem here. Than right click on anchor "Only null may change this block settings" appeared.

**Comment by Soundtoxin** [comment]
I am also experiencing this issue on the latest version of EnderIO, and I experienced it on one several versions back. I take great pride in the neat labeling of my Travel Anchors, so I hope this bug is considered high priority.
