### ISSUE TITLE
Model issues

### ISSUE THREAD

**Issue by dmodoomsirius** [SleepyTrousers/EnderIO#2104]
https://www.irccloud.com/pastebin/TrFrZm0g

**Comment by DarkGuardsman** [comment]
java.lang.ClassCastException: com.builtbroken.mc.lib.render.model.FixedTechneModel cannot be cast to net.minecraftforge.client.model.techne.TechneModel
	at crazypants.render.TechneUtil.getModel(TechneUtil.java:200)

I'm going to fix the casting issue on my end. What I suggest is that the loader ender IO is using check for file path. This way it doesn't override mine or other mod's model loaders. Even if I fix the casting issue I may lose the model fixes I employ.

**Comment by tterrag1098** [comment]
EnderIO rendering would probably be messed up if you alter all loaded
techne models. Why are you doing this?

**Comment by DarkGuardsman** [comment]
I have not noticed any issues with EnderIO's models being messed up. As my loader is designed to mess with my models. However, its been overridden by EnderIO's loader due to forge loading order.

**Comment by tterrag1098** [comment]
What? EnderIO doesn't have a model loader. It just uses forge's.

**Comment by DarkGuardsman** [comment]
Then why do I see crazypants.render.TechneUtil.getModel(TechneUtil.java:200) when my renderer call for there models.

**Comment by tterrag1098** [comment]
This crash is occurring when EnderIO tries to load it's models and expects
the forge techne class.

**Comment by DarkGuardsman** [comment]
Ignore me, i finally looked at the code. Its on my end though you should add an instance of check to https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/render/TechneUtil.java#L200

**Comment by tterrag1098** [comment]
And in the case that it can't load any models? What then? Please don't
override all techne models with your mod.

**Comment by DarkGuardsman** [comment]
Ya ya, the plan is to recode it to be selective. Sorry for the trouble of assuming it was your fault.

**Comment by DarkGuardsman** [comment]
Issue is solved on my end https://github.com/BuiltBrokenModding/VoltzEngine/commit/f5f2115957325da16ef16c6fe6a1d838c09d8b83

I still suggest adding an instanceof check with maybe a throw. As i'm not the only one using a model loader like this. Resoant engine uses the same exact loader and most likely Nova API.

**Comment by tterrag1098** [comment]
They really should not be overwriting the loader for .tcn, that is bound to cause issues.

**Comment by tterrag1098** [comment]
There, I've added a workaround so this cannot happen again.
