### ISSUE TITLE
[Suggested feature] Upgraded versions of Transceiver / wires with superconductor property and limitless fluid transfer

### ISSUE THREAD

**Issue by kotoroshinoto** [SleepyTrousers/EnderIO#2106]
Basically make it behave more like a tesseract in that respect when upgraded.

When working with mods like Bigreactors, we need power lines that can handle more current than the ones enderIO currently provides, and the transceiver apparently suffers from the same limit the wires do. (though you can run them parallel on a large capacitor to try to deal with it.)

I strongly prefer the transceiver UI to the tesseract UI, but i'm  unable to use the transceivers to feed water / steam  to the bigreactors due to its throughput limits. Ditto on the power output.

**Comment by 6210classick** [comment]
i don't think there is a limit to how much fluid it can transfer in my test world i'm pumping 7 different fluids each from 5 creative TE tanks the way i see it is that you aren't extracting/inserting the water fast enough from the DT

you can tweak it in the config , change it to this
# Amount of energy lost when transfered by Dimensional Transceiver; 0 is no loss, 1 is 100% loss
    D:transceiverEnergyLoss=0

    # Maximum RF/t sent and received by a Dimensional Transceiver per tick. Input and output limits are not cumulative
    I:transceiverMaxIoRF=2,147,483,647

    # Number of RF/t required to keep a Dimensional Transceiver connection open
    I:transceiverUpkeepCostRF=0

    # The cost in RF of transporting a bucket of fluid via a Dimensional Transceiver.
    I:transceiverBucketTransmissionCostRF=0

this basically makes it better than a tesseract

**Comment by kotoroshinoto** [comment]
ah TY

**Comment by kotoroshinoto** [comment]
incidentally, it wouldn't hurt to have the ability to transfer mekanism gases through the transceiver (i haven't checked if you have a tab for that, as i JUST added mekanism to my mods.)

I am fairly certain your gas conduits will be broken against mekanism 8's gas transfer. I think they changed the way it works, or at least the function's location in the code. (been testing it, and enderio gas conduits for mekanism crash the development version).

**Comment by tterrag1098** [comment]
I have no plans to implement infinite conduits either.
