### ISSUE TITLE
Mekanism Gas conduits will likely be broken against version 8 of Mekanism

### ISSUE THREAD

**Issue by kotoroshinoto** [SleepyTrousers/EnderIO#2110]
I am fairly certain your gas conduits will be broken against mekanism 8's gas transfer. I think they changed the way it works, or at least the requisite function's location in their code. (I have been testing it, and enderio's gas conduits for mekanism crash against the development version).

**Comment by kotoroshinoto** [comment]
incidentally, it wouldn't hurt to have the ability to transfer mekanism gases through the transceiver (i haven't checked if you have a tab for that, as i JUST added mekanism to my mods.)

**Comment by TheFireRodan** [comment]
I would also like to add that this is *world-corrupting, as once the conduit is placed it crashes the world every time the block is loaded. 

*assuming you don't have the knowledge&power to use MCEDIT to remove the tiles.

**Comment by tterrag1098** [comment]
@TheFireRodan Mekanism can simply be downgraded to fix the issue.

**Comment by Cuppycake** [comment]
Yes Mekanism can be downgraded but is that really a fix? I don't want to sacrifice one mod in a modpack for another.

**Comment by kotoroshinoto** [comment]
downgrading is not a fix

**Comment by kotoroshinoto** [comment]
you CAN turn off the enderio mekanism gas conduits in the config prior to the release of the fixed version

**Comment by Cuppycake** [comment]
Though turning off the configuration does nothing for pre existing machine setups in the world.

**Comment by kotoroshinoto** [comment]
depends on how enderio works internally, if it doesn't provide for those items to exist, they might auto-delete. You could always just remove the offending blocks with mcedit or temporarily downgrade and remove them prior to upgrading. It could be part of a fix, but the point is that downgrading is the best solution to this problem given the user wants to use the updated mekanism version.

**Comment by kotoroshinoto** [comment]
its also marked as "code complete" so you might want to check if they have any jenkins builds or see if you can pull the sources and dependencies and do a custom build yourself ;p

**Comment by Mementh** [comment]
has anything been done on this? i would love a world with a cleaer interface that ender IO gives.

**Comment by tterrag1098** [comment]
EnderIO 2.2.X will be compatible with Mekanism 7. EnderIO 2.3.X will be compatible with Mekanism 8. End of story.

**Comment by Mementh** [comment]
thanks :) hope 2.3 comes out soon :)
