### ISSUE TITLE
ME conduit crash

### ISSUE THREAD

**Issue by pyro482** [SleepyTrousers/EnderIO#2113]
With the newest update I seem to still be getting an crash from the ME conduit being placed down.

**Comment by TehNut** [comment]
Log?

**Comment by pyro482** [comment]
http://pastebin.com/HH29vGb6

**Comment by pyro482** [comment]
Sorry i think i sent you the wrong crash report log. here it is with the
updated ender IO

http://pastebin.com/FvbFJvAJ

**Comment by MatthiasMann** [comment]
AE2 rv1 is no longer supported (since EnderIO 2.2.6 as written in the release notes).
Update to rv2.

**Comment by Anora** [comment]
I'm using build 2.2.8.349 for EnderIO and I am getting this crash on conduit connection for ME conduits
the AE version I am using is appliedenergistics2-rv1-stable-1

http://pastebin.com/y3VfYm6F

**Comment by MatthiasMann** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/master/ReleaseNotes.txt#L127

**Comment by KamranMackey** [comment]
@pyro482 ^
