### ISSUE TITLE
Breaking a Telepad creates a sound bug

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2118]
If the telepad is broken while being teleporting something, the teleportation sound will loop (endlessly?). There may be other consequences I don't know about.
Note that reloading the world fixes the sound issue (maybe a chunk reload too).

**Comment by tterrag1098** [comment]
I haven't experienced this, can you reproduce it on the latest build?

**Comment by emperor06** [comment]
Yes, I just reproduced it. Breaking the telepad manually won't trigger the bug. Using an obsidian TNT triggers it (probably regular TNT too).

1. Make a 3x3 telepad and power it.
2. Set the destination to Y=200 (let's blast the skies! :)
3. Put an obsidian TNT on the telepad.
4. Now lit the TNT and quickly launch the teleportation

As the distance is too far away, the TNT will detonate before getting teleported, destroying the telepad and its surroundings. The teleportation sound then loops forever.

**Comment by tterrag1098** [comment]
Should be fixed via https://github.com/SleepyTrousers/EnderIO/commit/9d4a5ccccc8726d5a00fc52175fbba23d29bb1b6, was an oversight

**Comment by emperor06** [comment]
Confirmed, you fixed it.
You actually fixed it faster than I can compile it, that's scary :)

**Comment by tterrag1098** [comment]
Closing as this was only present in dev builds
