### ISSUE TITLE
Farming Station sapling feeding with shears

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2119]
Follow up #2109
It seems that the way the farming station works doesn't make the shearing easy.
The problem is the harvested saplings always end up in the first available slot inventory.

Let's supposed you are on a stone platform with a farming station and a single piece of dirt on its south-east side. Now you feed it with saplings in its SE slot and you give it an axe and a shear.
When the SE inventory drops below the limit (8 by default), the farming station will start its 50-50 leaves breaking to get some saplings. But those will end up in the SW inventory and the whole process will quickly stop, defeating the new feature brought by #2109. Putting a different type of sapling in slot 1 or locking it to stay empty may sound to be a good workaround but there are many common cases where it won't work (for example, all 4 slots planting the same type of trees).

Note that this has always been the case with crops and normal tree farming (without shearing) but it was not a big deal. When the first slot is full, the seeds will then go to the next slot and so on until all the slots are full. Unfortunately this cannot happen when shearing the trees since getting the saplings is now conditional.

With the default limit of 8, putting the same type of sapling in all slots always result in all slots running out of saplings except for the first one. I haven't tried yet with a limit of 64 but even if it works it will be tricky for users since: 1. that's not the default limit and 2. you cannot put stacks of 64 saplings in a slot using the GUI (you need to pipe them). I have no clue how this can be fixed without deep changes in how the farming station works :(

**Comment by HenryLoenwind** [comment]
Summary: Shearing 50:50 will not produce enough saplings to keep the farming station stocked. With stocked=(full, full, full,8) saplings.

I'll have a look if there is a way to insert harvested saplings into the slot for the section they were harvested from first. That might help (and is generally a "should this way" thing).

Next would be to play around with the ratio. A fixed ratio might not be a good ideas, as different trees give different amounts of saplings. Maybe scaling the ratio between 10% and 100% from 0 to 10 saplings could work.

**Comment by tterrag1098** [comment]
Why do it based on 0-10? Why not 100% saplings when it's empty, and
interpolate to 0% when the slot is full?

**Comment by emperor06** [comment]
Another idea that may solve this without too many modifications would be to rebalance the slots each time something is planted (or maybe inserted). Something similar to the auto-sorting mode on Mekanism's factories.
For example:
- slot 1 has 16 oak saplings
- slot 2 has 1 oak sapling
- slot 3 has 64 seeds
- slot 4 is empty
This would result in slot 1 = 9 saplings, slot 2 = 8 saplings, and the other slots unchanged.

**Comment by HenryLoenwind** [comment]
@tterrag1098 Typo, I wanted to write 0-16 (16 is full for the cap-less farmer). And I wanted to start with 10% shearing so people will always see leaves coming out of it (remember when you thought it was broken?).

@emperor06 That would be a big lot of code to do it.

**Comment by tterrag1098** [comment]
@HenryLoenwind that sounds reasonable

**Comment by emperor06** [comment]
@HenryLoenwind not sure it would be that big to implement. I just tried a very lazy, probably buggy, quick and dirty piece of code just to see if it's feasible and it seems to work quite ok.
I tried to call the following method in takeSeedFromSupplies(), just after the call to setInventorySlot() and before the return: http://pastebin.com/dHDRCw9y

Sure, takeSeedFromSupplies() is not the best place to do this, maybe insertItem()? Or maybe each time a slot changes (as long as it doesn't end up in an infinite balancing loop ^^)

**Comment by HenryLoenwind** [comment]
I just ran a test with the new code. I started a fully updated Farming Station with one oak sapling in each quadrant and fed it shears (hard work with those flimsy vanilla shears!) and bone meal. After a while all quadrants were full of oak saplings and the seed slots fluctuated between 6 and 16 saplings.

**Comment by emperor06** [comment]
Amazing! The fact the saplings prioritize the quadrant they come from is very nice and it feels a lot more intuitive. Even better, it works on other crops/seeds right?
Off topic, I saw you were working on adding bone meal to the stations, I can't wait to try this! :)

**Comment by HenryLoenwind** [comment]
Yes, it works on everything that is harvested. Bone meal is done, too. Please let me know if the frequency it is used (every fifth time it touches a block that cannot be harvested) works. It may be too often, but if you add bone meal you want fast results and not the bone meal lasting for days, don't you?

**Comment by emperor06** [comment]
A little feedback about the saplings: I have 2 tree-farming stations running on my server, one has 8 dirt blocks around, the other has 5. With the default limit of 8 some of the quadrant went empty. Rising the limit to 16 helped (I think more leaves are broken so my sapling supply is now sufficient). Note that I'm playing with Hunger Overhaul which modifies greatly how veggies/trees grow and how many seeds/saplings they give so it may not reflect a "normal" farming :)

About bone meal, I have only tested it on my solo world (can't use bone meal on my server because of Hunger Overhaul). I think 5 times is the upper limit. It's quite fast and nice on a basic farm but it starts feeling a bit slow when an octadic capacitor is used (trees are visited less often). That's just my opinion and many more experienced players may think otherwise, but yeah when I use a fertilizer that's for speeding up the process ^^ I think between 3 and 5 times is reasonable. Let's see what other people think.
From my experience with MFR's industrial fertilizer (on crops), the only time you want to hold on fertilizing is when a crop is about to naturally grow to the next stage (so you don't waste a fertilizer). The problem is the time it takes for a crop to naturally advance is absolutely huge compared to the time between 2 fertilizing so, imo, there's no real gain slowing the fertilizing process in the hope a crop will behave ^^ Which leads me to think that spamming a fertilizer is always the best option. So best if the farming station can handle a relatively fast fertilizing (relative = not too fast to avoid lags and to keep it a bit realistic). The real speed will then be given by how fast we can produce this fertilizer (bone meal for example).
To give you a order of magnitude, I chop about 15 trees per minutes with those 2 farming stations (13 trees planted). They are fertilized by 6 Thaumcraft's lamp of growth.
