### ISSUE TITLE
farming station using half energy

### ISSUE THREAD

**Issue by moTechPlz** [SleepyTrousers/EnderIO#2121]
It says it uses 40,
![2015-03-19_18 46 07](https://cloud.githubusercontent.com/assets/11203133/6738014/90382ef8-ce6f-11e4-9ab5-03b62c3ae9c7.png)
but if i measure the conduit it says 20. I'm also able to keep the energy buffers at the same level with only one 20RF/t stirling.
![2015-03-19_18 44 45](https://cloud.githubusercontent.com/assets/11203133/6738077/f02ba11e-ce6f-11e4-9f5b-67ba798a3a71.png)
![2015-03-19_20 23 42](https://cloud.githubusercontent.com/assets/11203133/6738977/f2dcf150-ce75-11e4-8f06-87ea97e0e640.png)

**Comment by HenryLoenwind** [comment]
I'll have a look, dev version already has some work done in this area and needs a fix or two.

**Comment by HenryLoenwind** [comment]
BTW: It was doing the useEnergy() after the check to only do certain things every second tick...
