### ISSUE TITLE
farm station insert seed up to stacksize

### ISSUE THREAD

**Issue by moTechPlz** [SleepyTrousers/EnderIO#2122]
With a non upgraded farmStation, if you manually place seeds into the grid it will only go up to 16. But when you insert the seeds through an item conduit from a chest it will add up to 64 seeds per grid space.
![2015-03-19_19 57 40](https://cloud.githubusercontent.com/assets/11203133/6738502/d9980a48-ce72-11e4-83aa-4fb7e945c816.png)

**Comment by HenryLoenwind** [comment]
Shift-clicking also stacks up to 64, and there's also a client/server desync happening.

**Comment by moTechPlz** [comment]
Shift-clicking a non upgraded fills the slots to 16;
![2015-03-20_06 49 31](https://cloud.githubusercontent.com/assets/11203133/6746750/ff14e2f4-cecd-11e4-8e3f-d7ae7c98ad97.png)
Upgraded with a double layer up to 32;
![2015-03-20_06 50 01](https://cloud.githubusercontent.com/assets/11203133/6746783/6bacaeec-cece-11e4-961c-54902f92b5c3.png)
And upgraded with a octadic capacitor to 64;
![2015-03-20_06 50 24](https://cloud.githubusercontent.com/assets/11203133/6746773/55783d44-cece-11e4-8591-8e9a490f321f.png)

However, if you automatically insert them with a item conduit they stack up as if the farming station is upgraded with a octadic capacitor.
