### ISSUE TITLE
SMP Server crash at start (NoClassDefFoundError EntityClientPlayerMP)

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2128]
On commit 6d8cf393d9bd4612f640ec2a8558c535e493f26a
The client starts just fine but the server crashes. 

[Server thread/ERROR] [FML]: Caught exception from EnderIO
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP

Full log here:
http://pastebin.com/jKYgcXe2

**Comment by Kodos-Atoz** [comment]
Do you by chance use Galacticraft?

**Comment by emperor06** [comment]
Nope.
It seems to be related to magnet/bauble. I use Thaumcraft which relies on bauble too if I remember correctly. I don't know if that's the cause.

**Comment by Kodos-Atoz** [comment]
Hm, can you pastebin your full log?

**Comment by emperor06** [comment]
There you go:
http://pastebin.com/C6qpQQEt

**Comment by emperor06** [comment]
If I had @SideOnly(Side.CLIENT) to MagnetController.handleKeypress(), the server is happy. But I don't know if the whole method was intended to run only on client side.

**Comment by HenryLoenwind** [comment]
Trusting the IDE to auto-set the type of a local variable correctly *usually* works. Unless it's Forge...

Could you please test if this works or if now the Yeta wrench crashes because the KeyTracker is Client-only?

**Comment by emperor06** [comment]
Sure, testing now

**Comment by emperor06** [comment]
As far as I can tell:
- no crash at start on server nor client
- no crash neither in single player
- no crash with the Yeta wrench
- Yeta wrench can wrench and its key binding works perfectly
- magnet activates properly when the key binding is used

The only thing that doesn't seem to work is I can't slot the magnet in my bauble slots (or maybe that's intended?)

**Comment by tterrag1098** [comment]
The key tracker should be a client side class. What is loading it on the
server?

**Comment by HenryLoenwind** [comment]
It wasn't the KeyTracker, it was the key handling method in the Commander, that used a client-only player class as parameter. Crash on classloading. But I added a clientonly annotation while fixing it on the keyhandler, and there's a method in the yeta that references the keyhandler. I was not 100% sure if that would crash on classloading (happening on server) or execution (not happening ob server). It is the later, so we're good.
