### ISSUE TITLE
Secure travel anchor can eat or duplicate items

### ISSUE THREAD

**Issue by McFrugal** [SleepyTrousers/EnderIO#2135]
If you attempt to use a travel anchor that requires an access code, then press a hotbar button while hovering over one of the slots, the actual item will be put there, not a phantom item. It can be recovered, sortof, by pressing a hotbar button while hovering over the item, but it will then be considered a phantom item itself and if you try to create another phantom item by putting it in the access code slots, it will just go right in there as if it's a normal slot.

You can take phantom items out of the slots by using the hotbar like this. They destroy themselves if you try to stack them with other similar items, and if used as a tool they disappear on the first use. They are valid items in a crafting grid, however, so resources can be duplicated like this.

This was observed in the Material Energy^4 modpack, with EnderIO-1.7.10-2.2.6.317

**Comment by MatthiasMann** [comment]
That is a very old version - update EnderIO and see if that is still an issue.
