### ISSUE TITLE
Dimensional Transceiver empty whitelist filter issue

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2137]
Dimensional Transceivers default to whitelist filter mode, but send and receive items even though the whitelist is empty. Should they default to blacklist mode?

**Comment by MatthiasMann** [comment]
EnderIO handles an empty whitelist as "everything allowed". This is also true for the item conduits, vacuum chest and the transceiver.

**Comment by BillH1949** [comment]
Fair enough. Feel free to close if this is not considered a bug. Although the "everything allowed" state is more accurately defined by an empty blacklist, breaking existing constructs just to be "accurate" probably isn't worth it.
