### ISSUE TITLE
Weather obelisk UI is very dark

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2138]
(as of build 363)
Normal inventory UI:
![normal ui](https://cloud.githubusercontent.com/assets/10668463/6763986/43b4b75a-cf54-11e4-99a9-0306c4cb47dd.png)

Weather obelisk UI:
![weather obelisk ui](https://cloud.githubusercontent.com/assets/10668463/6763989/4aa260b2-cf54-11e4-867c-69b1dacbcf41.png)

**Comment by HenryLoenwind** [comment]
how does it look without your resource pack?

**Comment by BillH1949** [comment]
The same:
![default resource pack](https://cloud.githubusercontent.com/assets/10668463/6765226/eef9ecb8-cf93-11e4-91cc-978645c0030e.png)

**Comment by tterrag1098** [comment]
This is very bizzare, I don't know what could cause that
