### ISSUE TITLE
Round robin speed slow?

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2139]
This may be a feature request rather than a bug.  I've set up a cobble generator with two Extra Utilities transfer nodes feeding into an item buffer, which then feeds 9 fully upgraded crafters (all generating compressed cobblestone).  The item conduit on the buffer is set to extract with 15 speed upgrades.  I'm noticing that the item conduit can't seem to deliver cobblestone fast enough to keep the crafters running steadily in round robin mode; based on stopwatch timings each crafter has to wait  ~4.45s between stacks of cobble, presumably because it takes that long to cycle through all nine crafters.  Is round robin supposed to be this slow?

**Comment by MatthiasMann** [comment]
speed upgrades increase the number of items per transfer - the number of transfers per second is fixed. You can improve it by using multiple extract conduits.

**Comment by BillH1949** [comment]
That helps a lot.  Thanks!
