### ISSUE TITLE
Crash Running with Optifine

### ISSUE THREAD

**Issue by gixmy** [SleepyTrousers/EnderIO#2140]
I'm getting a crash with Optifine OptiFine_1.7.10_HD_U_B5.jar with Ender IO.

I've been running EnderIO 2.2.1 for some time with no issues. Updating to EnderIO-1.7.10-2.2.6.317.jar or later causes the crash. Removing Optifine stops it from crashing.

I can log on to minecraft ok but within a minute or so of moving around the client crashes.
 
I haven't checked if 2.2.5 crashes or not.

See http://pastebin.com/RkMwqbv6 for the crash report.

**Comment by MatthiasMann** [comment]
If it only crashes with Optifine installed then that is an Optifine bug and not an EnderIO bug.

**Comment by Brycey92** [comment]
@gixmy have you tried updating to EnderIO 2.2.8.349 or later? Builds past 349 can be found here: http://ci.tterrag.com/job/EnderIO/

**Comment by gixmy** [comment]
Thanks @Brycey92 - I tried 364 but that crashes my server on startup. Build 363 at least starts ok. Having the energy conduit in my field of view which previously caused a crash no longer crashes. However I still had the Tessellator.func_78371_b crash - this time when an item conduit came into my field of view.

**Comment by Brycey92** [comment]
Someone else was having an Optifine issue on HD_U_B5 with another mod, and they switched from ultra to standard, and it fixed their issue. Could be worth a shot.

**Comment by tterrag1098** [comment]
Optifine is not supported, report any issues running Optifine to that mod, not here.
