### ISSUE TITLE
Server crash right-click-harvesting Harvestcraft chili pepper with Dark Axe

### ISSUE THREAD

**Issue by BlooBeuts** [SleepyTrousers/EnderIO#2142]
What a curious interaction.

http://pastebin.com/KHazUCU1

I had also just activated my Blood Magic Sigil of Magnetism, in case that's important.

**Comment by HenryLoenwind** [comment]
Just don't do that...and wait for Ender IO 2.3. ;)

Right-clicking with the dark axe is not server-compatible in 2.2.8. We've fixed it a while ago, but the next release is taking some time.

**Comment by BlooBeuts** [comment]
Doctor, it hurts when I do this!

"Fixed, but not yet live" is heard. Thanks!
