### ISSUE TITLE
Disconnected from server on right click of conduits bundles.

### ISSUE THREAD

**Issue by joshricker** [SleepyTrousers/EnderIO#2144]
I'm running Ender IO build 363 and whenever I right click on parts of a conduit bundle I am disconnected from the server with internal server error.

Part I clicked on: http://puu.sh/gKjVL/f420749309.jpg

Server side: http://pastebin.com/d5bzDYVa

Client side: http://pastebin.com/YA9qdGU9

**Comment by MatthiasMann** [comment]
Which language do you use in Minecraft?

**Comment by joshricker** [comment]
In English. I downgraded to 362 and the issue seems mostly gone.

**Comment by MatthiasMann** [comment]
what does "mostly gone" mean?

**Comment by joshricker** [comment]
I've never had it happen to me since but one of my players had it happen once since we downgraded. The may have been unrelated tho as I do not have any logs for that event.
