### ISSUE TITLE
Gas Conduits with Mekanism 8 electrolytic separator. 

### ISSUE THREAD

**Issue by Aulton** [SleepyTrousers/EnderIO#2151]
http://pastebin.com/qeenTEp3

Same setup worked just fine with pressurized tubes instead of conduits.

**Comment by kotoroshinoto** [comment]
API changed, enderio needs to integrate the new api.

**Comment by Aulton** [comment]
I figured as much, just thought I'd leave this here to alert them.

**Comment by 6210classick** [comment]
there is a new update for Mekansim 8.0.1 that stops crashes with EIO 2.2.8 349 but at the moment EIO gas conduit does not work with Mekanism 8 and above

**Comment by tterrag1098** [comment]
See #2110
