### ISSUE TITLE
Suggestion: Four Ender Markers sets a vertical boundary

### ISSUE THREAD

**Issue by MAYarbrough** [SleepyTrousers/EnderIO#2154]
So the the ender quarry can be limited vertically. I specifically ran into this problem with the Material Energy 4 pack. (the Spatial IO infrastructure is under a layer of bedrock in the main chamber and the quarry had no problem chewing right through it :D)

Awesome mod BTW!

**Comment by tjsd** [comment]
ender quarry is a part of extra utilities :) not Ender IO

**Comment by MAYarbrough** [comment]
HAH! wups :D. You're right. Love the conduits though!
