### ISSUE TITLE
EnderIO Configs Reverting.

### ISSUE THREAD

**Issue by Kirimato** [SleepyTrousers/EnderIO#2155]
Apparently whenever I load up my custom modpack with edited EnderIO configs related to power. It reverts the whole file back to vanilla configs. This has been constant in the past couple versions. 
It upsets the balance within my pack and it is on the verge of being removed from my pack. Any ideas on why it does this?

This also on Version 349.

**Comment by HenryLoenwind** [comment]
Did you read the embedded documentation? Quote:

    IMPORTANT:
      This is the core recipe file. Modifying this file will have no effect.
      It will be rewritten by EnderIO and all modifications made to it will be lost. To add
      or modify recipes please use 'AlloySmelterRecipes_User.xml'

Or which file are you trying to edit?

**Comment by Kirimato** [comment]
This has nothing to do with recipes. Its related to power configurations such as RF/Tick. Im trying to edit the regular EnderIO.cfg.

**Comment by Kirimato** [comment]
I also tested it out with only EnderIO as a different instance. Still the same outcome. The EnderIO.cfg reverts back to vanilla upon modpack launch.

**Comment by Kirimato** [comment]
Update: I have also tested with editing the EnderIO.cfg in FTBInfinity and I still get the same problem. Configs reverting as if nothing was changed.

**Comment by tterrag1098** [comment]
No one else has ever reported this issue. I have no idea what is going
wrong but I severely doubt it is caused by the mod.

**Comment by Kirimato** [comment]
Well apparently the EnderIO.cfg doesnt like decimals when editing the numerics for power. That has what been causing the config reverting back. I guess only whole numbers can be used.

**Comment by MatthiasMann** [comment]
EnderIO uses RF as power system - which is integer based.

**Comment by tterrag1098** [comment]
The config options are very clearly labeled with a capital I. Anything that
is a decimal will have a capital D. in the future this is how you can
easily tell what is supported
