### ISSUE TITLE
Electrolitic Separator + Gas Conduit Server Crash 

### ISSUE THREAD

**Issue by yepidoodles** [SleepyTrousers/EnderIO#2157]
When a Mekanism electrolitic separator tries to export into a enderIO gas conduit it crashes the server - I have sent this report to the Mekanism dev as well as I don't know which mod is causing the issue

Crash report:
https://drive.google.com/file/d/0ByS9NIAvqyexQnZrUFVNSHBfLUE/view?usp=sharing

EnderIO version: 1.7.10-2.2.8.349
Mekanism Version: 8.0.2.199

**Comment by 6210classick** [comment]
as of Mekanism 8 gas conduits no longer works you need to wait until EIO gets updated

**Comment by Brycey92** [comment]
This version uses the latest Mek 8 API: http://ci.tterrag.com/job/EnderIO/364/
The site above is also where all dev builds are currently posted. This is the main page: http://ci.tterrag.com/job/EnderIO/

**Comment by tterrag1098** [comment]
See #2110
