### ISSUE TITLE
Different Types of Power Conduits not connecting

### ISSUE THREAD

**Issue by Foxtails3** [SleepyTrousers/EnderIO#2159]
In Ender IO, Having a problem where different types of power conduits do not connect to each other. Same types do, but the different level power conduits do not. Using FTB Infinity, MC 1.7.10.

Tried using the yeta wrench to connect, no success.

I can use a capacitor bank to connect, but a rather expensive way of doing this,

**Comment by MatthiasMann** [comment]
That is by design - you can use an Energy Buffer for bridging between different conduit levels.

**Comment by 6210classick** [comment]
there is also an option in the config to make them connect to each other 
B:powerConduitCanDifferentTiersConnect=true

**Comment by tterrag1098** [comment]
Intended
