### ISSUE TITLE
Energy conduits not connecting to Mek8 machines

### ISSUE THREAD

**Issue by Greylocke** [SleepyTrousers/EnderIO#2160]
This is expected with the new Mek API, but I didn't see a ticket for it.

Using Mek 8.0.2.201, EIO 2.2.8.364. Energy conduits will not connect to Mekanism machines. Fluid and Item conduits connect normally.

**Comment by MatthiasMann** [comment]
Sounds like an issue with Mek's implementation of the RF API.

**Comment by Greylocke** [comment]
Good point
https://github.com/aidancbrady/Mekanism/issues/2377

**Comment by Greylocke** [comment]
fyi - Aidan's response:
This is due to the integration changes made to prevent crashes - CoFHCore in its entirety is now required for interaction with the RF API.
