### ISSUE TITLE
crash 2.2.8.349 

### ISSUE THREAD

**Issue by Cronosus** [SleepyTrousers/EnderIO#2162]
Hello
We have these crashes on server (repeat every day)
Source of crash unknown. :/
Thanks in advance

<code>---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 3/25/15 4:41 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: crazypants.enderio.item.darksteel.ItemDarkSteelPickaxe.doRightClickItemPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;IIIIFFF)Z
	at crazypants.enderio.item.darksteel.ItemDarkSteelAxe.func_77648_a(ItemDarkSteelAxe.java:178)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:534)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:149)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:489)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:875)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-042stab093.4
	Java Version: 1.7.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4258257832 bytes (4060 MB) / 7462518784 bytes (7116 MB) up to 7462518784 bytes (7116 MB)
	JVM Flags: 17 total; -Xmx7G -Xms7G -Xmn512m -XX:PermSize=1024m -XX:MaxPermSize=4096M -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=15 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=40 -XX:GCPauseIntervalMillis=150 -XX:+AggressiveOpts -XX:+TieredCompilation -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:CompileThreshold=1000
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.88.1307 git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1307 78 mods loaded, 78 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.88.1307} [Forge Mod Loader] (cauldron-1.7.10-1.1307.06.218-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1307} [Minecraft Forge] (cauldron-1.7.10-1.1307.06.218-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft-Core{1.0} [LanteaCraft Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OldModelLoader{1.0} [OldModelLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Artifacts{1.1.1} [Artifacts] (Artifacts-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	thexfactor117_ascension{b1.2.3} [Ascension] (Ascension-b1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0RC5} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC5-207.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	asielib{0.3.9} [asielib] (AsieLib-1.7.10-0.3.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bdlib{1.6.5.52} [BD Lib] (bdlib-mc1710-1.6.5.52.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.0RC6} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC6-138.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BinnieCore{2.0-pre7} [Binnie Core] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Botany{2.0-pre7} [Botany] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraBees{2.0-pre7} [Extra Bees] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraTrees{2.0-pre7} [Extra Trees] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Genetics{2.0-pre7} [Genetics] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.1.323} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chisel{2.3.7.76} [Chisel 2] (Chisel2_DEV-2.3.7.76.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	colorfularmor{1.7.10-2.5} [Colorful Armor] (colorfularmor-1.7.10-2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cookiecore{1.3.1} [Cookie Core] (CookieCore-1.7.10-1.3.1-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	dualhotbar{1.6} [Dual Hotbar] (dualhotbar-1.7.10-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	easycoloredglass{1.0.1} [Easy Colored Glass] (EasyColoredGlass-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderIO{1.7.10-2.2.8.349} [Ender IO] (EnderIO-1.7.10-2.2.8.349.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForestryExtras{3.1} [Forestry Extras] (ForestryExtras-2-3.1_B28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.1.323} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	fossil{1.7.10 Build 7.0.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft{1.0.0-68} [LanteaCraft] (LanteaCraft-1.7.10-68.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lmmx{1.0} [lmmx] (littleMaidMobX-1.7.x_0.0.8pre3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MMMLibX{1.7.x-srg-1} [MMMLibX] (littleMaidMobX-1.7.x_0.0.8pre3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	zabuton{1.0} [zabuton] (littleMaidMobX-1.7.x_0.0.8pre3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MagicBees{1.7.10-2.1.22} [Magic Bees] (magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	minechem{5.0.5.385} [Minechem] (Minechem-1.7.10-5.0.5.385.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	modtweaker2{0.7} [Mod Tweaker 2] (ModTweaker2-1.7.X-0.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	morechisels{@VERSION@} [More Chisels] (MoreChisels-1.7.10-1.0-17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC4-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	recipemod{0.2} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.2(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	pressure{1.0.7.62} [Pressure Pipes] (pressure-mc1710-1.0.7.62.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstoneArsenal{1.7.10R1.1.0RC4} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC4-54.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	simplyjetpacks{1.4.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ttCore{MC1.7.10-0.1.1-68} [ttCore] (ttCore-MC1.7.10-0.1.1-68.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RArm{1.7.10-1.1-22} [Redstone Armory] (RedstoneArmory-1.7.10-1.1-22-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RWG{Alpha 1.3.01} [Realistic World Gen Alpha] (RWG-alpha-1.3.01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Sampler{1.17} [Sampler] (sampler-1.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	snapdoors{1.7.10-1.1.0} [SnapDoors] (SnapDoors-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SolarExpansion{1.4e} [Solar Expansion] (SolarExpansion-Basic-1.4f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	StargateTech2{0.7.7-Alpha} [StargateTech 2] (StargateTech2-Alpha-0-7-7-MC1710-Forge1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	statues{2.1.4} [Statues] (statues-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalDynamics{1.7.10R1.0.0RC5} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0RC5-94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalSmeltery{1.7.10-1.1.1} [Thermal Smeltery] (ThermalSmeltery-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	sgs_treasure{1.0} [SGS Treasure 1.7.10] (Treasure-1.7.10-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TSteelworks{1.7.10-1.1.0} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.0-6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WorldEdit{6.0.0-SNAPSHOT} [WorldEdit] (worldedit-forge-6.0.0-SNAPSHOT-shadow.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	aobd{2.4.0} [Another One Bites The Dust] (AOBD-2.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.1.323} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore: -[1.7.10]3.0.0RC5-207
	ThermalFoundation: -[1.7.10]1.0.0RC4-58
	ThermalExpansion: -[1.7.10]4.0.0RC6-138
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0RC4-10
	RedstoneArsenal: -[1.7.10]1.1.0RC4-54
	ThermalDynamics: -[1.7.10]1.0.0RC5-94
	List of loaded APIs: 
		* asielibAPI (1.0) from AsieLib-1.7.10-0.3.9.jar
		* asielibAPI|chat (1.0) from AsieLib-1.7.10-0.3.9.jar
		* asielibAPI|tile (1.0) from AsieLib-1.7.10-0.3.9.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
		* BuildCraftAPI|core (1.0) from SolarExpansion-Basic-1.4f.jar
		* BuildCraftAPI|statements (1.0) from Railcraft_1.7.10-9.5.0.0.jar
		* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.5.0.0.jar
		* BuildCraftAPI|tools (1.0) from SolarExpansion-Basic-1.4f.jar
		* BuildCraftAPI|transport (3.0) from Railcraft_1.7.10-9.5.0.0.jar
		* ChiselAPI (0.0.2) from Chisel2_DEV-2.3.7.76.jar
		* ChiselAPI|Carving (0.0.2) from Chisel2_DEV-2.3.7.76.jar
		* CoFHAPI (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|block (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHAPI|core (1.7.10R1.0.3) from SolarExpansion-Basic-1.4f.jar
		* CoFHAPI|energy (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|fluid (1.7.10R1.0.5) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHAPI|inventory (1.7.10R1.0.3) from SolarExpansion-Basic-1.4f.jar
		* CoFHAPI|item (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|items (1.7.10R1.0.3) from SolarExpansion-Basic-1.4f.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHAPI|tileentity (1.7.10R1.0.3) from SolarExpansion-Basic-1.4f.jar
		* CoFHAPI|transport (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHAPI|world (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHLib (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|audio (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|gui (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|gui|container (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHLib|gui|element (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHLib|gui|slot (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHLib|inventory (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHLib|render (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHLib|render|particle (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|util (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|util|helpers (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|util|position (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|world (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.0RC5-123.jar
		* CoFHLib|world|feature (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* ComputerCraft|API (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|FileSystem (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Lua (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Media (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Peripheral (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Redstone (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Turtle (1.73) from ComputerCraft1.73.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.349.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.349.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.349.jar
		* ForestryAPI|apiculture (1.1) from GraveStone-2.11.3.jar
		* ForestryAPI|arboriculture (1.0) from GraveStone-2.11.3.jar
		* ForestryAPI|circuits (1.0) from GraveStone-2.11.3.jar
		* ForestryAPI|core (1.1) from GraveStone-2.11.3.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.4.0.7.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.4.0.7.jar
		* ForestryAPI|fuels (1.0) from GraveStone-2.11.3.jar
		* ForestryAPI|genetics (2.4.0) from forestry_1.7.10-3.4.0.7.jar
		* ForestryAPI|hives (4.0.0) from forestry_1.7.10-3.4.0.7.jar
		* ForestryAPI|lepidopterology (1.1) from GraveStone-2.11.3.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.4.0.7.jar
		* ForestryAPI|recipes (2.1.0) from Railcraft_1.7.10-9.5.0.0.jar
		* ForestryAPI|storage (2.3.0) from Railcraft_1.7.10-9.5.0.0.jar
		* ForestryAPI|world (1.0) from forestry_1.7.10-3.4.0.7.jar
		* IC2API (1.0) from Railcraft_1.7.10-9.5.0.0.jar
		* minechemAPI (1.7.10R1) from Minechem-1.7.10-5.0.5.385.jar
		* pressureAPI (1.0.7) from pressure-mc1710-1.0.7.62.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|carts (1.3.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|core (1.2.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|signals (1.1.0) from Railcraft_1.7.10-9.5.0.0.jar
		* RailcraftAPI|tracks (1.2.0) from Railcraft_1.7.10-9.5.0.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.5.0.0.jar
		* TSteelworksAPI (1.1) from TSteelworks-1.7.10-1.1.0-6.jar
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Info: The following plugins have been disabled in the config: buildcraft.recipes, buildcraft.statements, buildcraft.transport, equivelent.exchange, farm.craftory
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 9 / 20; [EntityPlayerMP['DaerwenenCZ'/88935, l='world', x=3536.38, y=137.48, z=2246.29](DaerwenenCZ at 3536.3787472969384,137.47718678617764,2246.2878465064073), EntityPlayerMP['Tichus'/162190, l='world', x=-406.21, y=78.00, z=1765.70](Tichus at -406.21236886485775,78.0,1765.704367614976), EntityPlayerMP['DrHalloween'/160781, l='world', x=-419.33, y=80.50, z=1817.91](DrHalloween at -419.33108787329985,80.5,1817.908348391613), EntityPlayerMP['janekmatousek'/208570, l='world', x=-2685.68, y=50.00, z=1875.54](janekmatousek at -2685.678103762223,50.0,1875.5368937911185), EntityPlayerMP['Moterr123'/221545, l='world', x=-1991.30, y=67.00, z=-392.70](Moterr123 at -1991.300000011921,67.0,-392.69999998807907), EntityPlayerMP['MaratFili'/231328, l='world', x=-211.00, y=50.00, z=1476.70](MaratFili at -210.99884900483445,50.0,1476.6992559472205), EntityPlayerMP['Hussi9'/249667, l='world', x=1816.23, y=69.23, z=-79.17](Hussi9 at 1816.2276933660728,69.23152379758702,-79.17116341751748), EntityPlayerMP['tom11technik'/197853, l='world', x=1871.99, y=78.00, z=-53.09](tom11technik at 1871.9921728716183,78.0,-53.0897163127378), EntityPlayerMP['monokl99'/243787, l='world', x=-2400.61, y=91.00, z=-1723.46](monokl99 at -2400.6061951429156,91.0,-1723.4604671013706)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)</code>

**Comment by HenryLoenwind** [comment]
This is a known bug in 2.2.8, it will be fixed in the upcoming 2.3.

For now, tell your players to not right-click with the dark axe.

@tterrag1098 backport?

**Comment by tterrag1098** [comment]
Yes, this has already been reported.
