### ISSUE TITLE
IConduitBundle - crash on load

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#2163]
I updated EnderIO to build 2.2.8.364 and I got greeted by following crash: http://pastebin.com/aVgbJCwc

EnderIO: 2.2.8.364
Forge: 10.13.2.1263
Modpack: InfiTech 2

Little edit: Crash doesnt occur at 363 version

**Comment by BuckitHead** [comment]
I second this.... same issue

**Comment by 6210classick** [comment]
isn't forge 1291 is the recommended version now ?

**Comment by JasonMcRay** [comment]
Using 1263 because of issues I experienced in higher forge versions + gregtech 5.

But just for a reference: Still crashes for me if I get forge 1291
