### ISSUE TITLE
Enderman Head drops

### ISSUE THREAD

**Issue by SirKastros** [SleepyTrousers/EnderIO#2165]
I have setup a MFR Spawner and a Killer Joe with The Ender and the enderman does not drop his head. when I am in the area to kill enderman with a TC sword myself and they drop. The heads use to drop with Killer joe kill them on the 2.2.8.349 build but they have not on any builds 350 +

**Comment by 6210classick** [comment]
is The Ender empowered ? try adding looting 3

**Comment by tterrag1098** [comment]
Yes, is it empowered? The head drop bonus only occurs when the ender is empowered. Also it might not work with the MFR grinder.

**Comment by SirKastros** [comment]
the ender  is not empowered. in the 2.2.8.349 and 2.2.8.367 builds and it was droping  enderman heads without it being empowered with a low drop rate. The caption on the ender says increased skulls and ender pearl drops. on the 2.3 dev build this is not the case.

**Comment by SirKastros** [comment]
I can't use the 2.2.8.364 build because I do not have mekinism installed.

**Comment by SirKastros** [comment]
ok I have tested this on the 2.2.8.365 build which is the latest dev build and the endermen heads are droping when killed by Killer joe using the Ender not empowered.

**Comment by tterrag1098** [comment]
I think you just had a bout of bad luck. Nothing concerning head drops changed in any of those builds.

**Comment by SirKastros** [comment]
I guess so
