### ISSUE TITLE
 RS control crash Autonomous Activator

### ISSUE THREAD

**Issue by devryb** [SleepyTrousers/EnderIO#2166]
Getting this crash intermittently with autonomous activators being redstone controlled via enderio conduits

http://pastebin.com/jSAT4cj1

https://github.com/CoFH/Feedback/issues/347

**Comment by 6210classick** [comment]
high signal or low signal ? which type of redstone conduits cause this the insulated one or the normal one ?

**Comment by devryb** [comment]
From what it was is an auto wither spawning setup with autonomous activators to place the soul sand and wither skulls.  It was the insulated type and I believe high signal.

**Comment by HenryLoenwind** [comment]
I left a comment in the other issue. There's nothing obvious wrong with our code and I cannot look at the actually crashing code, so we need some feedback from the COFH side of this.

**Comment by KingLemming** [comment]
We've put in a sanity check on our side to prevent invalid interaction, but fundamentally your RS conduits need a complete rewrite.

**Comment by devryb** [comment]
I wouldn't worry about the conduits being the issue here, here is several other crashes with the activators that prove otherwise:

http://pastebin.com/sZ0i09kU
http://pastebin.com/45nskNFr
http://pastebin.com/YP6haXYe
