### ISSUE TITLE
Thaumcraft Essentia Conduits

### ISSUE THREAD

**Issue by adamvan2000** [SleepyTrousers/EnderIO#2167]
We totally need conduits for essentia, like the AE conduits and Ender conduits. :)

**Comment by 6210classick** [comment]
also we need SFM conduits but that's not a high priority now never the less less what an interesting choice !

**Comment by kurokuno** [comment]
i think should would be great but for balance they would require buffers be the main recipe part if you want it to function as a normal pipe and not have back stuffing issues
