### ISSUE TITLE
Crash while editing Item COnduits

### ISSUE THREAD

**Issue by oskar9955** [SleepyTrousers/EnderIO#2172]
When ever I edit the options for the item coduits eg. Input, output and ect it crashes after about 2 seconds after opening the GUI. This is my crash log http://paste.ee/p/ExeD9

**Comment by MatthiasMann** [comment]
Try without Optifine

**Comment by oskar9955** [comment]
It fixed it. But why is it happening? Is there any way to get around it?

**Comment by tterrag1098** [comment]
Any crash that *only* occurs with optifine installed must be the fault of optifine. Report it to them.
