### ISSUE TITLE
tterrag1098 Not responding to DM's in Twitter!

### ISSUE THREAD

**Issue by Chaoschunk** [SleepyTrousers/EnderIO#2173]
Hello, 

Bug: tterrag not responding to twitter DM's :-)

Would love to have you on the show for an interview if your interested! 

Chaoschunk

**Comment by TehNut** [comment]
@tterrag1098 Major bug. Please fix ASAP. Unplayable until fixed.

**Comment by SgtPunishment** [comment]
I can confirm this rendered my world unplayable, hoping it's fixed soon

**Comment by Cracks777** [comment]
the code has been done, he just has not pushed out a build? he wont build until he "feels there's been enough changes"
