### ISSUE TITLE
Gas condiut visual render bug with mekanism 8

### ISSUE THREAD

**Issue by mindcloud69** [SleepyTrousers/EnderIO#2174]
http://i.imgur.com/R8cE311.png

using.
EnderIO-1.7.10-2.2.8.364.jar
Mekanism-1.7.10-8.0.3.588.jar

Tried removing and replacing. it didn't help.

Neither Optifine or FastCraft are installed.

**Comment by hisorange** [comment]
Can reproduce, but none the less the Mekanism 8 is just coming out and changing hour by hour.

**Comment by mindcloud69** [comment]
Will continue to test and report if it is working with newer versions. FYI it also glitches when they are stand alone not just hooked up to a Mek machine.

**Comment by hisorange** [comment]
Also with Mek8 the Yeta wrench visibility option and the NEI recipe for gas conduit missing for me.

**Comment by Iomega0318** [comment]
This is the same for me, glitched texture and missing recipe using:
EnderIO-1.7.10-2.3.0.368_beta
Mekanism-1.7.10-8.1.0.215

**Comment by tterrag1098** [comment]
Fixed via https://github.com/SleepyTrousers/EnderIO/commit/d3a341337e694a0b2431996d04bb0fc90db7b019, tracking under #2110
