### ISSUE TITLE
Powered Light

### ISSUE THREAD

**Issue by aschmois** [SleepyTrousers/EnderIO#2178]
First off, I love this mod, with all my life. I just have one gripe. I can't seem to power lights through blocks. Connecting a cable straight on a powered light is incredibly ugly and completely unnecessary. I hope it's possible to be able to input electricity on one side of the block (that the light is placed on) and then the light will suck power from that, kind of how redstone works.

If this becomes too difficult or just outright impossible, I was looking at the wireless lights, however these wireless chargers hold way too much charge and making a "real" system is impossible because it would take way too long to waste the charge in the wireless chargers.

If there is a different solution, please, I'm all ears.

**Comment by MatthiasMann** [comment]
Use conduit facades to cover the energy conduit - and place the powered light on the under side.

**Comment by aschmois** [comment]
Oh yes, thank you, very much. That was hard to figure out (what with the wiki broken and whatnot). I do want to keep this suggestion open for the second part of the issue. Having a config for a wireless charger capacity would be wonderful.

**Comment by tterrag1098** [comment]
You can apply Redstone to a wireless charger to shut it off.

**Comment by aschmois** [comment]
While, that's a solution, that's not the solution. I want to make a faux-real solution, where a power outage actually causes things to turn off. While I do think it's kind of childish of me to ask for it, I'm just putting it out there in case you decide it's really not that hard to implement. Either way, it's your choice. I've already gone the non-wireless route either way so this issue no longer affects me. You're welcome to close it or leave it open as you wish. 

Off topic: Thank you for the great mod by the way, my experience would be totally different without it.

**Comment by tterrag1098** [comment]
Also @ your other issue, there is an inverted version of every light in case you don't want to run redstone. The wireless charger buffer size is a non-issue, so closing
