### ISSUE TITLE
Fluid Tank Cant reset configuration

### ISSUE THREAD

**Issue by Woche** [SleepyTrousers/EnderIO#2180]
Hi
I like playing with this mod. Just stumbled into a problem
I have put down, configured and used the fluid tank. When i empty it and pick it up it dont stack with other fluid tanks. The mouseover has a (configured) text. I have tried to set all side to "none" but the (configured) text wont go away. I have not found any documentation how to reset the tank to "unconfigured" state. 
Is this a bug or is it supposed to work in this manner?

regards
Woche

**Comment by MatthiasMann** [comment]
You can craft all EIO machines in a crafting table or your inventory and it will *delete* all items, fluids and configurations stored inside.

**Comment by Woche** [comment]
Ah
Works fine, thanks for the information
I do think it is unintuitive but i guess there is a reason why there isnt a button on the EIO machines or that the yeta wrench doesnt have a option for this. 
Any way it is a nice mod

Thanks for the superquick answer MattiasMann
