### ISSUE TITLE
Build #364 EnderIO Crash - ClassNotFound

### ISSUE THREAD

**Issue by Trayaurus** [SleepyTrousers/EnderIO#2181]
There seems to be a crash in which it is trying to find if Mekanism is found and if its not found it will throw and exception where it will say that it doesn't find the IGasHandler and then it throws a fit about IConduitBundle

I am using build 364 from the Jenkins server

Provided the crash log:
http://pastebin.com/7kTLKCac

**Comment by enterprise12nx** [comment]
^ support this

**Comment by enterprise12nx** [comment]
i also ask you to please take a look at this, CoFH, Mekanism and EnderIO all seem to have a problem(at least they are pointing fingers around) 
its a crash my players are having and cannot join the server: https://github.com/CoFH/Feedback/issues/365

**Comment by b0bst3r** [comment]
@Trayaurus 

Forge{10.13.2.1307}

This is likely the issue, AFAIK EIO is supposed to be on 10.13.2.1291

**Comment by Ianaver** [comment]
confirmed oh and @b0bst3r forge 10.13.2.1291 is the MINIMUM REQUIRED not the one that you HAVE TO use..... you can use higher versions XD

**Comment by tterrag1098** [comment]
Tracking under #2110
