### ISSUE TITLE
cant mine conduit sometimes

### ISSUE THREAD

**Issue by shadoxxhd** [SleepyTrousers/EnderIO#2182]
sometimes it works, sometimes they just re-place themselves and dont drop

**Comment by Ianaver** [comment]
de-sync?

**Comment by shadoxxhd** [comment]
no, local world

**Comment by Ianaver** [comment]
I know but forge is an integrated server so its trying to sync with the integrated server.

**Comment by tterrag1098** [comment]
The conduit that is broken is determined by a raytrace, in some cases the raytrace returns nothing, so no conduit is removed. Make sure to aim at the conduit you want to break or this can happen.
