### ISSUE TITLE
Disappearing blocks (render bug)

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2183]
I got the latest version and found that for some odd reason a few of the blocks seem to go invisible when placed in the world and reappear every once in a while (removing optifine seemed to fix this)

if you still don't support optifine I understand if you just close this after reading this...

**Comment by tterrag1098** [comment]
You are correct, any issues which only occur with optifine installed are OPTIFINE'S PROBLEM
