### ISSUE TITLE
SAG Mill shouldn't be able to duplicate blocks if we can't duplicate ingots

### ISSUE THREAD

**Issue by keturn** [SleepyTrousers/EnderIO#2184]
The [isExcludedFromBallBonus](https://github.com/SleepyTrousers/EnderIO/blame/master/src/main/java/crazypants/enderio/machine/crusher/CrusherRecipeManager.java#L67) function automatically excludes all ingots from the grinding ball's chance to double output. It does not, however, exclude blocks made from 9 ingots, which yield 9 powder before the bonus.

I don't know enough about the ore dictionary to know if it's a good idea to use the same `name.startsWith` check for `"block"`, but it seems like either that or an update to the core config is desirable if we don't want people endlessly duplicating metals by pulverizing ingots and smelting them again.

**Comment by tgstyle** [comment]
You can put this in the SAG Mill user XML http://pastebin.com/9kNWd5zy
 
https://github.com/SleepyTrousers/EnderIO/issues/1523

**Comment by tterrag1098** [comment]
Implemented via https://github.com/SleepyTrousers/EnderIO/commit/b16d5cc04ff61e98e92291cc212043a1a5127428
