### ISSUE TITLE
can ya add 1 item to this very awesome mod  

### ISSUE THREAD

**Issue by mr2q** [SleepyTrousers/EnderIO#2187]
would be nice if this ender io mod had a void tank or pipe something you could put liquids in that deletes them if that could be done that would be great i hope i'm typing this  in the correct spot

**Comment by HenryLoenwind** [comment]
My idea would be to "break" a transceiver so it sends everything into the void. I think I'll have a look on the weekend...

**Comment by Soundtoxin** [comment]
If you play with modpacks you can use a void fluid pipe from BuildCraft. They are quite cheap to make. One downside is that you can't hook BuildCraft pipes to EnderIO pipes. Now THAT is a feature I'd like to see, though. Some sort of thing that shows up like the Conduit Connector and allows different mods' pipes to interface, assuming they're both under the RF API.

**Comment by mr2q** [comment]
I don't use mod packs I put my own together and I think believe that
BuildCraft is for little kids
On Apr 5, 2015 2:30 AM, "Bradley Haggerty" <notifications@github.com> wrote:
>
> If you play with modpacks you can use a void fluid pipe from BuildCraft.
They are quite cheap to make. One downside is that you can't hook
BuildCraft pipes to EnderIO pipes. Now THAT is a feature I'd like to see,
though. Some sort of thing that shows up like the Conduit Connector and
allows different mods' pipes to interface, assuming they're both under the
RF API.

**Comment by Soundtoxin** [comment]
That's a pretty interesting point of view considering BuildCraft is the most complex pipe mod there is.

Also, multiple mods used in unison = a modpack. I also design my own. This does not mean I don't play with modpacks.

**Comment by mr2q** [comment]
Ya but it causes a lot of lag his mod I would greatly appreciated it if you
would be able to add 1 of those pipes and I can't seem to get you 1 block
that is like a tesseract working

**Comment by RAnders00** [comment]
These blocks exist already (*Buildcraft* Void Fluid Pipe, *Thermal Expansion* Nullifier, *Extra Cells* Fluid Void) in most mod constellations, I don't think Ender IO needs to implement one, at least not by just adding a new block, it should be a relatively innovative mechanic then. (Like the one with sending it into the void)
