### ISSUE TITLE
Capacitor bank never gets to 100% full

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2190]
I'm using ComputerCraft to control a dual-turbine BigReactors setup with an 84-block vibrant capacitor bank.  In the past, I've used the Power Monitor for engine control and noticed that entering 100% for the upper threshold never worked; now with ComputerCraft I'm seeing that although Waila reports the capacitor bank as being full, getEnergyStored() never reports the full capacity:
![capbank_1](https://cloud.githubusercontent.com/assets/10668463/6907185/dcd9f9a4-d6e8-11e4-8078-24042274579f.png)
![powerlog](https://cloud.githubusercontent.com/assets/10668463/6907187/df98f974-d6e8-11e4-90d4-a170278b76e8.png)

**Comment by tterrag1098** [comment]
It's not meant to as the full storage is a long value. You want
getEnergyStoredL()

**Comment by BillH1949** [comment]
cool, thanks!

**Comment by BillH1949** [comment]
getEnergyStoredL()  is not a valid function. I'm using ComputerCraft 1.73, OpenPeripheral 1.7.10 AIO-1 and OpenModsLib 1.7.10-0.6, which appear to be the latest versions.

**Comment by BillH1949** [comment]
listMethods() returns the following methods available for the capactor bank:
pullItem
getInventorySize
destroyStack
swapStacks
pushItemIntoSlot
getEnergyStored
getAdvancedMethodsData
getMaxEnergyStored
pullItemIntoSlot
listMethods
getInventoryName
expandStack
pushItem
getAllStacks
condenseItems
getStackInSlot
listSources

**Comment by tterrag1098** [comment]
None of those mods have EnderIO support. Use computronics

**Comment by BillH1949** [comment]
Switching to computronics fixes the problem.  Thanks!
