### ISSUE TITLE
Unable to access travel anchor GUI

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2191]
Since build 363 I have been unable to access the travel anchor gui.  This behavior is present in build 365 as well.

**Comment by hisorange** [comment]
Similar here, but also sometime I get a chat message when I right click "Only null can access this" or something like that :D

**Comment by LyraelRayne** [comment]
I experience the same issue in build 365.

**Comment by BillH1949** [comment]
This is fixed in build 367.
