### ISSUE TITLE
Cannot paint travel anchor in the painting machine

### ISSUE THREAD

**Issue by LyraelRayne** [SleepyTrousers/EnderIO#2192]
The tooltip says that we can, but the painting machine won't accept it in the "to be painted" slot.

Version: EnderIO-1.7.10-2.2.8.365

**Comment by tterrag1098** [comment]
Fixed via https://github.com/SleepyTrousers/EnderIO/commit/fbb58a2c8ba0caf4109e1fbadd051801eb8fc00b
