### ISSUE TITLE
Dark steel boots taking fall damage with /fly

### ISSUE THREAD

**Issue by yepidoodles** [SleepyTrousers/EnderIO#2193]
As I said in the title, the dark steel boots take fall damage even when the player doesn't - We have /fly on our server as a voting reward and it is important for our donators to get this fixed.

Thanks a bunch

- Alice

**Comment by Dwargkiller** [comment]
May be related to the vanilla bug where a player may take fall damage (including to equipment) despite hitting the ground at slow speed after flying.

**Comment by yepidoodles** [comment]
It doesn't happen to any other armour except these

**Comment by tterrag1098** [comment]
Tracking under #2266
