### ISSUE TITLE
Server Crashing upon unloading area

### ISSUE THREAD

**Issue by PlanetBeast** [SleepyTrousers/EnderIO#2194]
Hello there. I'm having an issue with either EnderIO or Thermal Expansion. I'm going to post an issue with TE if I can find out where as well as here but anyways I'm getting a server crash whenever I am unloading my base whether its through a /tp /home or whatever. I checked the crash report on the server and it seems its an issue with EnderIO and TE interacting. I'm not quite sure but I'd appreciate some help on whats going on :)
http://pastebin.com/9ZM9maFp

**Comment by tterrag1098** [comment]
This is a strange interaction between EnderIO and TE, that only happens when using redstone conduits on an Autonomous Activator. I believe the next TE version will have safeguards against this crash.

**Comment by PlanetBeast** [comment]
I submitted a bug with TE as well and they told me it was an issue with EnderIO not them so I'm not sure what's going on.

**Comment by devryb** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/2166
