### ISSUE TITLE
Transceiver sends items to the wrong channel when overflowing

### ISSUE THREAD

**Issue by kaidenyo** [SleepyTrousers/EnderIO#2195]
I have a Resonant Retriever on an Impulse Itemduct pushing items into the Transceiver (1), which should send to Channel "Processing". The "Processing" Transceiver(2) pushes items into machines and also recieves processed Items back and sends them to "Storage" Trancseiver(3). When the Transceiver which SENDS to Channel "Processing" overflows, it also sends ores to "Storage" (1 to 3 ), which should not happen.

Pic http://i.imgur.com/6nBDbYZ.jpg

**Comment by MatthiasMann** [comment]
Show screenshots of how the transceiver are configured. Also does this happen when using EnderIO item conduits?

**Comment by kaidenyo** [comment]
Cant reconfigure it and make screenshots since the system is running atm ( with another config )
Transceiver (T1) - was configured to SEND "Processing Channel"  ( to T2)
Transceiver (T2) - was configured to RECEIVE from "Processing Channel " ( from T1) and SEND "Storage" (T3)
Transceiver (T3) - was configured to RECEIVE "Storage" from (T2)

Problem is, items get pushed into the "SEND"-Slot of Transceiver T2, which will then send unprocessed or to T3 ... I dont know why it fills the Send-Slot of the Transceiver since no other Channels were used.

**Comment by MatthiasMann** [comment]
I looked at the code and see no way that items received from a transceiver could end up in it's own send slot.
Maybe one of your many pipes or conduits was extracting the item and putting it back in?

**Comment by kaidenyo** [comment]
Seems to be a bug with Thermal Dynamics. Works fine with Conduits.
