### ISSUE TITLE
Lite Mode?

### ISSUE THREAD

**Issue by Pleek** [SleepyTrousers/EnderIO#2197]
I absolutely love this mod; it allows for a single (yet complex) piping system, turning Medusa's hair into a single pipeline. However, I feel the mod adds too much. I like using buildcraft/ industrialcraft/ Thermal Expansion, which add their own ores/processing, and I really would prefer an Ender IO download that gave only it's piping features. I understand this would require a rework of the recepies, but I feel a "Lite" version would be much easier to use with other tech mods.

**Comment by MatthiasMann** [comment]
EnderIO offers a lot more than just conduits - and you have to use the Alloy Smelter to make the alloys for the conduits.
If you don't want to use the rest of the mod - that's up to you.

**Comment by Pleek** [comment]
That's exactly what I mean though, Ender IO has a lot to offer that other mods offer as well. A "lite" version with simpler crafting recipes without the need for another power source and machine would blend in so much more when used with other tech mods.

**Comment by enterprise12nx** [comment]
i dont really see the point to that, every mod has their own way of machines, i dont see why you would need to make a lite version of this, its a tremendous amount of work, all recipes would have to be changed.

You can literally just use the parts of the mod you want

**Comment by SirKastros** [comment]
the way this can be done is split up the alloys to it's own mod and make it required (core) then conduits, upgrade items for conduits and filters in another  and last the machines and other blocks in the last mod. the alloys can be made into blends by combining the items used now to make a dust of that alloy then smelt them in any furnace. this feature can be turned on and off in the configs to make it require the alloy smelter to make the alloys or the blend crafting recipe.

names suggestion for the mod split
EnderIO-Core (alloy recipes and api) *required by the other two
EnderIO-Conduits (conduits and items needed for them)
EnderIO-Machines (All machines, capacitor banks, capacitor items and xp related blocks)
