### ISSUE TITLE
MFR biofuel generates 4 RF/t in the combustion generator

### ISSUE THREAD

**Issue by goosezilla** [SleepyTrousers/EnderIO#2198]
Seems like it should be 40 RF/t and theres a missing 10x multiplier somewhere.

MFR configs set their own biofuel generator output with a 10x multiplier so the default in the config is set to 16 giving an actual output of 160 RF/t.

**Comment by tterrag1098** [comment]
Something else is registering that fuel improperly, EnderIO does not have that by default.
