### ISSUE TITLE
EnderIO crashes when Mekanism is not installed (is this intentional)?

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2199]
I get an instant crash when that mod is not installed with Iconduitbundle being the culprit

http://pastebin.com/fGGPGB5k

**Comment by tterrag1098** [comment]
> EnderIO{1.7.10-2.2.8.364} [Ender IO] (EnderIO-1.7.10-2.2.8.364.jar) Unloaded->Constructed->Errored

Use 365

**Comment by Ianaver** [comment]
I was trying to find the newest version but yesterday and today I was unable to find version 365, unless its not on the jenkins page :/

**Comment by Ianaver** [comment]
nvm I found it sorry for the troubles!
