### ISSUE TITLE
what happen to the new textures of ender io?

### ISSUE THREAD

**Issue by aldra2012** [SleepyTrousers/EnderIO#2200]
what happen to the new textures of ender io i loved them and now i am getting the old plain ones, using the latest build of ender IO

**Comment by 6210classick** [comment]
maybe it wasn't that good for some people or there is gonna be an option in the config to revert back to old the EIO textures

**Comment by tterrag1098** [comment]
The latest build is of the 2.2.8 branch, it's not a new dev release.

**Comment by aldra2012** [comment]
:( but i love the new textures they look very futuristic and fits the mod perfectly

**Comment by tterrag1098** [comment]
The new textures are not gone, the latest build on the jenkins IS NOT A DEV BUILD

**Comment by aldra2012** [comment]
Cool
