### ISSUE TITLE
crash with ender io gas conduits with mekansim

### ISSUE THREAD

**Issue by aldra2012** [SleepyTrousers/EnderIO#2201]
http://pastebin.com/vxrNyPy7

**Comment by NickSProud** [comment]
http://pastebin.com/4SBz4FM9

Found the same thing,
Happened when I connected a enderio fluid conduit to one of mekanisms Electrolytic Separator. At the same time it was set to move the gas out of the other side with a gas conduit.

**Comment by aldra2012** [comment]
the gas conduits are still broken no matter if you change what your using to put fluids in and/or power once you connect the gas conduit to any mekanism machines it crashes and corrupts the world

**Comment by tterrag1098** [comment]
#2110
