### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by hisorange** [SleepyTrousers/EnderIO#2202]
Aye, I got a huge fps issue with ender io but cannot really find out what, I am sure this mod causing it (removed mods one by one) and I also know which specific chunk causing it, it has like 200 conduit in it, which does not causing lag normally (have 800 other conduit around it without any problem) but sometime I have to remove and reconnect all the conduit in that chunk to solve the issue, tried to find it with opis but it's a rendering error and opis shows that there is 250 call to a function which each takes way too long but it say <ERROR> for each field but timing ~

Is there a tool or a way to profile rendering issues for conduits? I really want to solve this mystery :D

**Comment by hisorange** [comment]
Btw the difference when that chunk loaded is 250fps -> 7fps so not something like weak pc (also its happening with / without optifine).

**Comment by tterrag1098** [comment]
What version are you using?

**Comment by hisorange** [comment]
#365 but the issue was present in #349 too,
just now hit out 16 block of conduit and the lag is gone, with / without facade does not matter, but the stack had all but gas conduit in it.

**Comment by hisorange** [comment]
Shame on me, build 366 solves it, just checked the version when seen a new build is out, I did not suspect that the buffers could cause lag and just wrenched them with the conduits in line...

Sorry to bother @@
