### ISSUE TITLE
Buildcraft 6.4.6 incompatibility with SAG Mill

### ISSUE THREAD

**Issue by tgstyle** [SleepyTrousers/EnderIO#2207]
I updated to the latest hotfix and it has broke certus quartz ore in the SAG mill. Checked the logs and I cannot see anywhere why it would fail to load the recipe. The recipe is in the core xml.

**Comment by tgstyle** [comment]
It seems to be SAG Mill recipes in general. In the logs it shows it loaded them but they are not all available.

**Comment by tgstyle** [comment]
Hmm, I just reverted to 349 and it still has the same issues, I am now checking other mods that were updated recently. I will report back with the findings.

**Comment by tgstyle** [comment]
It appears to be buildcraft 6.4.6, reverting to 6.4.5 fixed the issue.

**Comment by Ianaver** [comment]
btw I think the latest hotfix was the epril fools joke XD

**Comment by tterrag1098** [comment]
No, it was not. And I have no clue what BC could be doing to cause that. If it's caused by their update then it can't be our issue, however.

**Comment by asiekierka** [comment]
@tterrag1098 - and if you look at the code we changed closely, you'll realize that we haven't touched anything that could have influenced it. http://asie.pl/645-646.txt

This must be some kind of coincidence.

**Comment by tterrag1098** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/2177

**Comment by tgstyle** [comment]
Just to note, I don't use Thermal Science.

**Comment by Ianaver** [comment]
@tterrag1098 what happened to the new items you added? seems that they disappeared in the latest update :/

**Comment by tterrag1098** [comment]
@Ianaver The latest 2 builds on the server are ***not*** dev builds, they are hotfixes on the 2.2.8 branch. Thus they do not contain the 2.3 features.

**Comment by Ianaver** [comment]
@tterrag1098 oh sorry my bad :)
