### ISSUE TITLE
Mekanism V8 and EnderIO crash with solar evaporation plants

### ISSUE THREAD

**Issue by enterprise12nx** [SleepyTrousers/EnderIO#2208]
I have been having a discussion with KingLemming, and aidancbrady

there has been a crash when players approach solar evaporation plants, after removing mods its been determined its a conflict between EnderIO and Mekanism

im using Mekanism V8.0.2 and Enderio dev build number 364

Discussion: https://github.com/aidancbrady/Mekanism/issues/2426#issuecomment-88320208

**Comment by Xaethon** [comment]
Also getting this with Mekanism 8.0.3.212 and EnderIO dev 365. The client does not crash to desktop, simply stops responding and hangs forever.

**Comment by enterprise12nx** [comment]
yep, the mekanism author needs somebody in charge of EnderIO to respond, since crazypants has been away.
