### ISSUE TITLE
Cannot Craft Alloy Smelter

### ISSUE THREAD

**Issue by adstanley84** [SleepyTrousers/EnderIO#2209]
I found issue #2080 was the same problem but doesnt go in depth on how it was fixed and the image linked was dead. I have tried 3 types of copper ingot and I cant craft the Alloy smelter at a crafting table. I really hate to cheat it in. I am running MC 1.7.10. Is there anything I can do to check the internal files or what am I doing wrong?

**Comment by GauHelldragon** [comment]
If you are using the latest version of enderIO, the alloy smelter is crafted with 4 iron ingots, 1 machine frame, a cauldron and 3 furnaces.
Iron         Furnace  Iron
Furnace  Frame     Furnace
Iron         Cauldron Iron

**Comment by adstanley84** [comment]
ah sweet I will try this when I get home THX! FTB must not be up to date then

**Comment by tterrag1098** [comment]
In the future I recommend NEI...it tells you all recipes

**Comment by adstanley84** [comment]
I tried to use NEI but it wouldnt load
