### ISSUE TITLE
Conduit Probe Overlay Covers Chat

### ISSUE THREAD

**Issue by natedogith1** [SleepyTrousers/EnderIO#2210]
The conduit probe's overlay hides chat, which is just annoying in general (and shares this issue with the yetta wrench). However, what makes this of enough note for me to mention on here is that the conduit probe outputs its information to chat, meaning that I have difficulty seeing the information it's supposed to tell me because the information is being covered up.

**Comment by tterrag1098** [comment]
implemented via https://github.com/SleepyTrousers/EnderIO/commit/4cf30def99d3fbfd84ebc09dd90ec7967e2a4bf6

**Comment by tterrag1098** [comment]
Relased in the latest official release
