### ISSUE TITLE
Capacitor Banks not properly implementing IEnergyProvider

### ISSUE THREAD

**Issue by hilburn** [SleepyTrousers/EnderIO#2211]
I know I talked about this in IRC a while ago but:

https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/capbank/TileCapBank.java#L679

Still doesn't actually allow you to extract power from the Capacitor Banks.
Please either implement it or remove the interface as I'm getting thoroughly fed up of getting asked about this.

**Comment by tterrag1098** [comment]
Complete via https://github.com/SleepyTrousers/EnderIO/commit/f95895a38db9cd76306e84d4adfdf29c0cc09eac#diff-adc302456f7fc40a4fb68a20aa07bfcbL46

Not seeing any adverse effects yet.
