### ISSUE TITLE
[Feature Request] Conduit Upgrade Tool

### ISSUE THREAD

**Issue by andrewring** [SleepyTrousers/EnderIO#2212]
Brief: 
I'd love a tool which could be used to identify the size of contiguous connected conduit sections and then to swap out the entire segment with a different class of conduit.

Details:
When laying down conduit, particularly early on, the lowest level functional conduit is often used to mitigate the material expense.  As time progresses, needs change as well, particularly with respect to power.  A tool such as this would both allow for a meaningful analysis of resources required to replace a segment (count of conduits needed), as well as simplifying the replacement process.  I imagine something similar to Thaumcraft's Wand Focus: Equal Trade, but working on conduit segments.

Segments remain more isolated in part because conduits of different tiers do not connect to one another (energy <-/-> ender energy, fluid <-/-> pressurized fluid, etc).  replacing an adjacent cable segment would, in this scenario, present a potential change in the network; should newly compatible adjacent cables connect with one another?  I suggest a toggle within the tool which would select between allowing those connections to form or defaulting to leaving the conduits isolated.

Bonus:
My current method of bridging between cable types is to use a buffering block, such as a capacitor or tank.  I would love to see an inline conversion block which would allow, for example, regular energy conduit to pull power off of a high power ender energy trunk.  Inline is key, as it stops possible disruptions in other conduits running through that block space (which is the key killer feature of enderIO conduits).

**Comment by MatthiasMann** [comment]
You can use an energy buffer (or omni buffer) to bridge energy (and item) networks.

**Comment by drifter397** [comment]
I was thinking something like this but just taking a previous tier conduit and using the next tier ingot or nuggets from that ingot to upgrade it. I just think having old conduits laying in your storage is not that ideal.

**Comment by andrewring** [comment]
@MatthiasMann 
Good to know.  What about Fluid, Redstone and ME?  Do those propagate through the buffers as well?

@drifter397 
That sounds great too, but to be clean, my suggestion is for something to swap out already placed conduits, not modify ones in inventory.

**Comment by keturn** [comment]
See also #1698.
