### ISSUE TITLE
Travel Anchor does not telport me

### ISSUE THREAD

**Issue by Kralle160** [SleepyTrousers/EnderIO#2214]
Travel Anchor does not telport me when i wear the Globetrotter´s Sash from Botania. I think it´s because i jump too high.

**Comment by XFactHD** [comment]
This isn't a bug in EnderIO, it's the same scenario as with travel anchors and open blocks elevators in galacticraft space station.

**Comment by psychofad** [comment]
I used to have this same issue, holding shift while jumping will allow you to use the travel anchor as sneaking disables the Sash's abilities.
