### ISSUE TITLE
enderio wiki does not allow creation of new pages

### ISSUE THREAD

**Issue by TheBlueTroll** [SleepyTrousers/EnderIO#2216]
well i say the wiki doesn’t, but in fact its because of cloud flare, when a page doesn’t exist media wiki steps in and instead asks the user if he wants to make a new page by that name, instead CloudFlare steps in with its "SmartErrors powered by CloudFlare" page,  
which results in new pages being impossible to make.
how to reproduce:
Go to http://wiki.enderio.com
click on discussion link at top
...
profit

note: unsure of where to post this issue, as the wiki doesn’t have a issue tracker. and as such sorry ahead of time.

on a side note the 3 links at the footer of the main page does not exist.

**Comment by Nentify** [comment]
Fixed. Thanks for letting me know!

**Comment by TheBlueTroll** [comment]
no problem

**Comment by TheJulianJES** [comment]
Please close this issue now ;)
