### ISSUE TITLE
Farming station unable to cope with plants that are planted and grow in water

### ISSUE THREAD

**Issue by justicesays** [SleepyTrousers/EnderIO#2221]
The "witchery" mod has a plant called "water artichoke", this plant is planted in still water, and otherwise acts like a normal plant with regards to growth stages, harvesting etc.
The Farming station appears unable to plant them , giving a "no seeds" messages , when there are eligible water blocks in range to plant the water artichokes, and all quadrents are filled with the seeds.

**Comment by HenryLoenwind** [comment]
Ender IO currently only supports IPlantables of EnumPlantType.Nether and EnumPlantType.Crops.

**Comment by justicesays** [comment]
Thanks for the fast enhancement @HenryLoenwind !

**Comment by HenryLoenwind** [comment]
No need to thank me, that was a fast and easy one. And I have to thank you, this gave me the opportunity to learn about EnumPlantType.
