### ISSUE TITLE
Visual Glitch with Telepad, Farming Station and The Vat

### ISSUE THREAD

**Issue by Neodark7** [SleepyTrousers/EnderIO#2222]
http://i.imgur.com/WSDKc0j.png
http://i.imgur.com/RIQfkps.png
http://i.imgur.com/72IXVBW.png

 EIO 2.3.0.368_beta

**Comment by HenryLoenwind** [comment]
sorry, wrong ID referenced

**Comment by Ianaver** [comment]
try with optifine standard instead of ultra, run the game quit and get ultra again.... (if you are using optifine)

**Comment by tterrag1098** [comment]
This is not occuring for me. Please uninstall optifine if you do have it installed.

**Comment by Neodark7** [comment]
What ? Im not gonna uninstall optifine to play enderio... To loose 40% fps and have an horrible chunk loading just for a the telepad ? ( even if it's awesome ) it's your block from your mod please try to fix it and don't ask people to remove other mods...

**Comment by Ianaver** [comment]
@Neodark7 use HD standard optfine not ultra, ultra implements code that can cause a lot of visual weirdness... sadly you may lose some FPS with standard but its better than without.

**Comment by Neodark7** [comment]
i have 225+ mods who works fine with optifine ultra... so i don't think it's non fixable

**Comment by tterrag1098** [comment]
I'm not asking you to remove anything. Fact is EnderIO guarantees *NO*
compatability with Optifine due to the massive hacks it uses to improve
performance. *If* you remove it, and it solves your issue, then we know the
source of the problem.

**Comment by ate0ate** [comment]
I can't speak for tterrag, but I don't think he meant for you to remove optifine in order to play with ender io, I believe he simply wanted you to see if the problem persists without optifine...

**Comment by Neodark7** [comment]
hmm ok sorry i tought it was the classic "heh not my problem, just remove optifine"... i try that now

**Comment by tterrag1098** [comment]
If it does turn out to be optifine, it is indeed not my problem. The
rendering works in vanilla and that's all I need to know. It must be
optifine's fault if they cause it to no longer work properly.

**Comment by Ianaver** [comment]
I had this issue and it seems that optifine standard doesn't implement the glitchy code that makes those blocks disappear.

**Comment by Neodark7** [comment]
yeah i confirm it's from the chunk loading setting, works fine on default and smooth but not on mult-core

**Comment by Ianaver** [comment]
hmm never knew that, thx!

**Comment by Neodark7** [comment]
yeah the ultra version just add the chunk loading setting :) to increase fps and really increase the chunk loading... so i think it's really important to try to make ender io work with that it's not "it's optifine hack not my problem..." as i know every other block from other mods works fine with that...

**Comment by tterrag1098** [comment]
I am quite confident that threaded rendering would be the cause, as none of
the rendering code in EIO is written to be thread safe. EIO does not expect
threads to be introduced into the game. I have a large doubt that EIO is
the only mod affected by this change.

**Comment by Neodark7** [comment]
as i said even with 225+ mods i never had an issue with this setting and i play a lot, so as i can tell it's the only one, at least no one of the most popular. optifine is not recommended by many modders but with proper settings it's really stable... ( at least if you don't use ichun mods ), it's not a situation where every mod would be involved it's just these 3 blocks

**Comment by tterrag1098** [comment]
I know Cofh mods use the same non-thread-safe method for rendering, storing
the render pass in a volatile field. @skyboy can confirm this too.

**Comment by Neodark7** [comment]
you mean that mods ? http://i.imgur.com/b2nPljw.png i'm not a modder so i'm not familiar with code details, what i can say, it's as a player everything works fine for me with cofh mods ( by that you TE TF TD and MFR ? ) no glitches and i am ofc on multi-core

**Comment by Neodark7** [comment]
Same with EIO except for the recent builds

**Comment by asiekierka** [comment]
@Neodark7 This is not debuggable, as OptiFine is closed-source and no developer bar sp614x has any idea of how it modifies Minecraft, in addition it cannot be tested in a development system.

You either ask him to fix it or find the reason yourself - modders already have enough on their plate.

**Comment by Xuerian** [comment]
@Neodark7 FastCraft has an excellent chunk loading mechanism you should be able to use instead of OptiFine's. 

This doesn't fix your problem or change the fact that mod authors really shouldn't be expected to fix issues OptiFine didn't anticipate (That is sp614x's job), but it could help.

**Comment by skyboy** [comment]
Since I was pinged, I'm gonna laugh that TE/MFR's rendering nonsense works without issue.
