### ISSUE TITLE
electrolytic seperator/gas conduits crashing the server

### ISSUE THREAD

**Issue by nightstalker6669** [SleepyTrousers/EnderIO#2225]
mekanism 8.1.0.214
enderIO 2.2.8.367
forge 1307

you can connect power to the seperator just fine, but as soon as you connect a gas conduit to either side of the seperator it immediately crashes the server to the point that you have to have forge remove the tile entity before the server will start up.

**Comment by HenryLoenwind** [comment]
oh come on, don't you people at least spent 2 seconds looking at the existing reports?

**Comment by nightstalker6669** [comment]
sorry most of the post i've seen about anything to do with the electrolytic seperator have been closed. so i was under the assumption they were closed because they were fixed with the recent enderIO update. which they obviously weren't. hence why i was posting it. i'm sorry if my bug post offended you and it won't happen again.

**Comment by HenryLoenwind** [comment]
#2110
