### ISSUE TITLE
Inability to make villager spawners

### ISSUE THREAD

**Issue by akvgergo** [SleepyTrousers/EnderIO#2226]
It's impossible to place a soul vial containing a villager and a broken spawner into the soul binder at the same time.
(Not sure if it's intended.)
Using a modified version of FTB infinity, with EIO 2.2.8.367

**Comment by MatthiasMann** [comment]
That's not a bug - it is black listed by default in the config.

**Comment by akvgergo** [comment]
If it's disabled by default, then is there an ingame way of indicating what's disabled and what's not? Maybe a big red tooltip on the soul vial appearing in the machine GUI saying that you can't do that? Just to clear up future confusion of something. :P

**Comment by 6210classick** [comment]
only villagers & iron golems are blacklisted everything else can be used to make a spawner including modded mobs

**Comment by akvgergo** [comment]
Well, yes, I know what's blacklisted now, I meant that it would be neat if something made me aware of this in-game.

**Comment by 6210classick** [comment]
the fact that you can't capture it means you can't create a spawner for it

**Comment by tterrag1098** [comment]
Not true, you can still put villagers in soul vials.
