### ISSUE TITLE
Wither Skeleton powered spawner not working

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2227]
With build 367, my wither skeleton powered spawner does not spawn anything, whether in the overworld or in the nether.  If I examine the gui, the progress flames cycle as expected but no mobs spawn.

**Comment by TehNut** [comment]
Are you... On peaceful?

**Comment by BillH1949** [comment]
Nope.  My other powered spawners (enderman, blaze, zombie, cave spider, creeper) work just fine.

**Comment by BuckitHead** [comment]
I second this. Mine no longer works as well. I think 364 was around the time I used it last.

**Comment by MatthiasMann** [comment]
Due to issues with the wither skeletons - they have been disabled in the 2.2.8 branch.
You can re-enable them in the config, or create a normal skeleton spawner and hope they turn to withers.

**Comment by BuckitHead** [comment]
Are you talking this: (both are from the config on my server)  
# Separates wither and normal skeletons into different entities, enables the powered spawner to treat them differently [EXPERIMENTAL - MAY CAUSE ISSUES WITH OTHER MODS]
    B:replaceWitherSkeletons=false

Or This:(poweredSpawnerConfig_core)

    "enderzoo.Enderminy" : "10",
    "enderzoo.ConcussionCreeper" : "1.5",
    "enderzoo.enderzoo.FallenKnight" : "1",
    "enderzoo.WitherWitch" : "3",

    "enderio.witherSkeleton" : "20"
  },
  
  "blackList": [
    "VillagerGolem",
    "Villager"
  ]
}

**Comment by 6210classick** [comment]
how's your power generation ?

**Comment by BillH1949** [comment]
My spawners are connected to vibrant energy conduit routed to a 2B RF capacitor bank. As long as I don't try to run the enderman and blaze spawners at the same time (all have octadic capacitors) power gen is fine.

Changing B:replaceWitherSkeletons to true resolves the problem.

**Comment by 6210classick** [comment]
then your problem is that you created a Wither Skeleton spawner from build 349 which B:replaceWitherSkeletons is set to true but in build 367 it's set to false by default to avoid any mods compatibility issues

quick fix is to change your spawner to normal skeleton spawner but that will require you to use the spawner in the nether to get Wither Skeletons

**Comment by tterrag1098** [comment]
Indeed this is a problem with the update removing the entity your spawner was attuned to.

**Comment by ate0ate** [comment]
I was just curious, what were the problems/conflicts that were being encountered with the ender io wither skeletons?

**Comment by tterrag1098** [comment]
Reported issues of console spam and massive entity spawns to the point of
lag. We still haven't pinned down the cause of these issues, but hope to
get it solved for the 2.3 release
