### ISSUE TITLE
Crash on loading (client and server) with latest beta

### ISSUE THREAD

**Issue by Nick-77ab2** [SleepyTrousers/EnderIO#2229]
idk if its EnderIO but the crash states that extrautilities cant find its item, but if i change EnderIO back to its latest stable version everything works fine. Also in the crash EnderIO is the one that makes the Unloaded-->pre-initialized go to Unloaded, as in it starts on EnderIO.

crash: http://pastebin.com/jyi5pdXx

**Comment by HenryLoenwind** [comment]
Could you do us a a favor and try with builds 365, 361 and 360? I cannot recreate the crash with my dev setup, and building an installation with all the mods you have would take ages. Thanks!

**Comment by tterrag1098** [comment]
#2203

**Comment by Nick-77ab2** [comment]
can you re-add it, i did get a crash with baubles too

**Comment by Nick-77ab2** [comment]
re-open

**Comment by Nick-77ab2** [comment]
http://pastebin.com/Q3HCzwEB this DID have bauble sin it

**Comment by Nick-77ab2** [comment]
confirmed that fastcraft, baubles, Enderio, and extrautilities are in it and they crash, same versions and all
