### ISSUE TITLE
Capacity Tank - Display Panel Issue

### ISSUE THREAD

**Issue by chloeprince** [SleepyTrousers/EnderIO#2230]
Hey guys, what happen to the display panel feature on the multiblock capacitor tank?
Using: EnderIO-1.7.10-2.2.8.367.jar

It used to show both INPUT and OUTPUT RF that is being input or draw out, at the same time. Now it only shows one or the other, but not both at the same time any more.

Could you make it so the display panel shows:
-Stored RF
-Total Capacity
-Precent Free
-INPUT
-OUTPUT
 
If you could add these in the GUI config to turn on or off too, that would be great. That way the user can determine all the things they want to see on the screen.

**Comment by MatthiasMann** [comment]
You mean the capacitor bank?

If you make the info panel higher than wide it will show input and output separate - each on it's own row.

**Comment by chloeprince** [comment]
I did that, and your right, it used to do that - now it doesn't in the latest release.

**Comment by MatthiasMann** [comment]
Build 376 is a 2.2.8 hotfix release - if you want a 2.3 dev build - use 368.

**Comment by SirKastros** [comment]
you have to wench the face of the block to get the numbered input/output to show and it only shows if there is power loss or gain on the capacitor bank and the red bar show how much RF is in the bank if you want to monitor the input and output of the whole system you will need to put down a power monitor.that shows what power is in the machines, conduit and capacitor banks this is on the 2.2.8.367 build

**Comment by SirKastros** [comment]
here is a screen shot
![2015-04-04_22 52 42](https://cloud.githubusercontent.com/assets/6454124/6995685/51b0c1c6-db1d-11e4-9a9b-8d71a43ab416.png)

**Comment by tterrag1098** [comment]
@chloeprince what SPECIFIC version are you reporting the bug on?

**Comment by tterrag1098** [comment]
build 367 is NOT a 2.3 dev build

**Comment by SirKastros** [comment]
367 is what original post says. I will look at build 368 to see if it works like the picture posted by chloeprince.

**Comment by SirKastros** [comment]
this is working on the 2.3.369 beta build like in choeprince
![2015-04-05_13 32 55](https://cloud.githubusercontent.com/assets/6454124/6998010/32e10db6-db98-11e4-99b9-736f87aeabd4.png)
