### ISSUE TITLE
Unable to save config

### ISSUE THREAD

**Issue by jztmanyl** [SleepyTrousers/EnderIO#2234]
Hey I tried to remove 
  "blackList": [
    "VillagerGolem",
    "Villager"
  ]
from the config and save it but when I loaded my minecraft the file got overwritten and the blacklist appeared again

**Comment by tterrag1098** [comment]
You really should read the comments...

**Comment by jztmanyl** [comment]
And so did I, but when I made my own config (the user one) it still didn't work

**Comment by tterrag1098** [comment]
The user one already exists...just edit it

**Comment by jztmanyl** [comment]
And that's what I have done, I edited it to exactly the core but with empty blacklist, it might be something really obvious since the glock is 3 at the night and I am really sleepy

**Comment by jztmanyl** [comment]
{
 
  "_comment": "New entites are added, one already in _Core will have their values replaced with those in this file,",
  "costMultiplier": {
  },
  
  "blackList": [

  ]
}

Is my user file and it doesn't work, any help?

**Comment by tterrag1098** [comment]
What version are you using?

**Comment by lexa8774** [comment]
Hi, I'm having the same problem. I was originally using 2.2.5.311, but I just updated to 2.2.8.367 to see if there might have been a fix and I still have the same issue. I will edit the User file and once I load my game (single player), the config is still not working. Any ideas?

**Comment by tterrag1098** [comment]
WOW, sorry about that, I totally derped when messing with that code a while ago. Question is now, is this worth another 2.2.8 hotfix...
