### ISSUE TITLE
Big Reactors and Redstone Conduit

### ISSUE THREAD

**Issue by katur239** [SleepyTrousers/EnderIO#2236]
Both the normal Redstone Conduit and Insulated Restone Conduits will not connect to either a Redstone port or a RedNet port on a Big Reactor.

Tried with Bog Reactors version 4.3 and Ender IO 2.2.8 and 2.3

**Comment by SirKastros** [comment]
you need the insulated redstone conduit to connect to the redstone port of the reactor.I have the redstone port toggle the reactor on and off. This has been tested in both 2.2,8 and 2.3 dev builds. 
![2015-04-04_22 25 15](https://cloud.githubusercontent.com/assets/6454124/6995602/7a1e4808-db19-11e4-8fca-a602d23617f7.png)

**Comment by SirKastros** [comment]
make sure the conduit is in in/out mode for it to work.

**Comment by katur239** [comment]
Oh crap, you're right. Sorry D:
