### ISSUE TITLE
2.3 Beta 368 - Mekanism Gas Conduit missing

### ISSUE THREAD

**Issue by katur239** [SleepyTrousers/EnderIO#2238]
Using Mekanism 8.1.0 and the gas conduits are not enabled even though it is enabled in config.

**Comment by JigglesTheFett** [comment]
Just want to second this problem. Assumed the gas conduit issue with the newer versions of mekanism was fixed in this release :(

**Comment by tterrag1098** [comment]
Fixed via https://github.com/SleepyTrousers/EnderIO/commit/d3a341337e694a0b2431996d04bb0fc90db7b019

**Comment by katur239** [comment]
I noticed this commit was part of build 370 so not sure if it was actually fixed in that build. However I did test it again and gas conduits still do not appear with Mekanism.
