### ISSUE TITLE
crash when right clicking telepad

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2241]
http://pastebin.com/UTd1yrUg

**Comment by tterrag1098** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/0511a0e2a255b2b11461cf9466189020bb0dcf6b

**Comment by tterrag1098** [comment]
Download the latest build

**Comment by Ianaver** [comment]
wow I somehow started this after you added that build and never knew! XD sorry again!
