### ISSUE TITLE
Telepad sound loop

### ISSUE THREAD

**Issue by psychofad** [SleepyTrousers/EnderIO#2242]
Using:
EnderIO-1.7.10-2.2.8.365.jar

Using this on my private server, I set up a Telepad in my base and one at a remote location.  Both are chunkloaded.  I set the coordinates on the one in my base to teleport me directly on top of the one at the remote location (also tried offsetting by a couple of blocks just in case), and set the other one to teleport me back.  Both are being powered with a tesseract directly below the center block.  I am using Redstone conduit on both of them with conduit covers and a button to trigger  the teleport event.  When I press the button on the one at my base it teleports me as expected (sometimes the sound loop starts here but sometimes not) and when I teleport back then the sound loop starts and it sounds like the telepad is wound all the way up and the sound is positioned on the telepad.  If I continue to teleport between the two then I end up with a sound loop (sometimes even several layers of sound loops) on both telepads and it becomes louder (maybe from the overlay).  If I disconnect from the server and then reconnect the sound loop stops until I use the telepads again.

Let me know if you can't reproduce this and I can upload a video to youtube so you can see (hear rather) what I mean.

**Comment by psychofad** [comment]
As a test I just decided to try teleporting one way and then flying back to the telepad I just used and the sound was still playing on it...sounds like it is not unloading the sound after the player leaves the area?  Weird.

**Comment by tterrag1098** [comment]
I haven't experienced this myself. A video would be helpful.

**Comment by psychofad** [comment]
Ok...uploaded the video to youtube.  Just for reference, Quintac is my in-game name.  My attempt to fly was a bit embarrassing :blush:, but you can definitely hear what I am talking about in the video.  Let me know if you need anything else from me.  I also have a test server/pack that I use before I push updates that I can try out any possible fixes on if you need me to.

https://youtu.be/8kkyJJ42o3s

**Comment by tterrag1098** [comment]
Oops, this should be fixed via https://github.com/SleepyTrousers/EnderIO/commit/0a5b59884ee7c9141b5a84e20c6eacc9348fb3c1

**Comment by psychofad** [comment]
I can confirm the latest development build fixes the sound loop issue!  Thanks, I will let you close this when you are ready!
