### ISSUE TITLE
"Blades" in the telepad seem to dissapear after a teleport (no animation)

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2244]
no animations 
(no optifine used)
![2015-04-05_10 26 36](https://cloud.githubusercontent.com/assets/8153290/6999087/881314e8-dbaf-11e4-8082-2cda39580216.png)

**Comment by psychofad** [comment]
This happened to me once when i teleported to the default coordinates  (on top of the telepad i just built), I had to break all the blocks and rebuild it to get the blades to reappear.

**Comment by tterrag1098** [comment]
How odd. There does seem to be some issues with teleporting to a place that
requires 0 power. This may be related.

**Comment by Ianaver** [comment]
I am sorry I am still new to this feature as I could not find any info on youtube or the official wiki, am I looking in the wrong location?

**Comment by 6210classick** [comment]
@Ianaver yes it's a new feature that will be available in 2.3 version you will not find any info about it it's currently being tested in the dev versions ( BETA )

**Comment by Ianaver** [comment]
ok

**Comment by tterrag1098** [comment]
This should be fixed
