### ISSUE TITLE
Crash with beta build #368-latest, installed: baubles, enderio, extrautilities, and fastcraft

### ISSUE THREAD

**Issue by Nick-77ab2** [SleepyTrousers/EnderIO#2246]
http://pastebin.com/Q3HCzwEB 
heres the crash, different crash than last time.

**Comment by Nick-77ab2** [comment]
extra utilites version: 1.2.3
fastcraft version: 1.2.1
baubles version: 1.0.10

**Comment by Nick-77ab2** [comment]
and still the unloaded-->Constructed's last one is on the mod before EnderIO

**Comment by Nick-77ab2** [comment]
so this should fix it?

**Comment by Nick-77ab2** [comment]
if so then nice another bug crushed with the ban hammer

**Comment by Nick-77ab2** [comment]
I'll close this if the next build works for me
*Crosses fingers*

**Comment by HenryLoenwind** [comment]
I don't think this will fix it completely, but it is part of the solution. The other part is either the mega-refactoring #2249 or a simple annotation on the mod class.

**Comment by Nick-77ab2** [comment]
ok

**Comment by Nick-77ab2** [comment]
yep with 371 i can confirm it is still happening

**Comment by Nick-77ab2** [comment]
but you said it would still happen right?

**Comment by Nick-77ab2** [comment]
so you probably already knew

**Comment by Nick-77ab2** [comment]
and i your #2249 thing it says there's pull request conflicts that must be resolved

**Comment by Nick-77ab2** [comment]
so has this been fixed?

**Comment by crunkazcanbe** [comment]
This issue is fixed as of EnderIO-1.7.10-2.3.0.398_beta and EnderCore-1.7.10-0.0.1.7_alpha . 

Thank you guys at lest it now loads with baubles .
