### ISSUE TITLE
Server crash when completing a itemduct network.

### ISSUE THREAD

**Issue by Properpeanut** [SleepyTrousers/EnderIO#2254]
So my server died today, cause a player made an item Conduits network between a ExNihilo barrel and a normal chest. The crash occured when the last item conduit was placed and the network was formed.

Here's the pastebin: http://pastebin.com/5tJYHAZn

Stopping the server and removing EnderIO, has ressurected my server, but what a loss :)

**Comment by MatthiasMann** [comment]
These things are called item *conduit*.
And this is an ExNihilo bug which has been fixed in version 1.37 - so update that mod and your world will be fine.

**Comment by Properpeanut** [comment]
Thank you for the quick reply. I'll try :)
