### ISSUE TITLE
Farming Station Light Level

### ISSUE THREAD

**Issue by BuckitHead** [SleepyTrousers/EnderIO#2256]
Everything works great but the light level its putting off will not allow anything that needs darkness grow. Can we get a dimmer button LOL. light level around it is 11

**Comment by HenryLoenwind** [comment]
I'll think about a way to do this. In the meantime, by placing 5 block directly adjacent, you can hide the light.

**Comment by BuckitHead** [comment]
Yes I did that, but i am now using another visual pipe(TD) off the top that has facades that don't block light as well. The light on the old farm block does not emit a light lvl...

**Comment by BuckitHead** [comment]
How is this a suggestion ? You provide a block that has a config to harvest oreberry's but it puts out so much light that they will not grow around it. This is not a issue with Old farm station.  I would love to continue testing your most updated beta on my servers but had to roll back for this issue as I have people with huge farms.

**Comment by HenryLoenwind** [comment]
The definition for "bug" is: "something isn't doing what is is supposed to do". That does not apply here, as you can see in the commit I linked in. So you're suggesting we change something (back). That's why it's tagged "suggestion".

And BTW: My schedule says I should have time for that mid to end next week. Mostly Real Life(tm) related.

**Comment by BuckitHead** [comment]
Please don't take this the wrong way as I took the "suggestion" Tag. I was mearly taken back by the idea of a suggestion for something that was wrong with the farm block. These have never put out this much light and the idea of suggestion was kinda strange to me.  I have been around testing and reporting to help for a bit and I never come off like that. I appreciate everything you all do and in the timely way you all handle issues. This Mod handles issues faster then any other by far. Again if you took it in a way that offended you I'm sorry.

**Comment by BuckitHead** [comment]
Great Fix, Thanks for all your hard work on this Mod.
