### ISSUE TITLE
Ender Rails will not teleport minecarts

### ISSUE THREAD

**Issue by passengerpigeon** [SleepyTrousers/EnderIO#2263]
Hello,
On the world I am building, I am having an issue that is preventing me from building my interdimensional rail network. My setup is shown in [this image] (http://postimg.org/image/tntrmy5l1/), and is intended to take occupied carts from the Nether to the Overworld and vice versa. The transceiver on the right of the image sends to the "Nether-Overworld" channel, and the transceiver on the left of the image receives from the "Overworld-Nether" channel. I have the exact same setup in the Overworld, only with the sending and receiving channels switched. My problem is that whenever I roll over the rail in a cart, nothing happens and I get dumped in the hole after the transceiver. My config file allows player transport and I have had this work on a superflat test world. The carts drive on the left, by the way.
Edit: I am using the latest Direwolf20 pack.

**Comment by MatthiasMann** [comment]
Make sure both ends are chunk loaded - and that you have enough power.

**Comment by passengerpigeon** [comment]
I chunkloaded both ends and it now works perfectly from the Nether to the Overworld, but when I go the other way I get placed on the correct rail and the cart spawns beside the tracks.

**Comment by passengerpigeon** [comment]
I played around a bit more with this and I managed to get the cart to appear on the track, but I always arrive about 1 second before the cart, which then spawns empty with no momentum. What can I do to get through inside the cart?

**Comment by BillH1949** [comment]
I'm also seeing a similar problem with build 371; Although both ends are chunkloaded and sufficiently powered, and B:enderRailTeleportPlayers=true in the config file, I always get dumped from the minecart once it hits the ender rail.

**Comment by BillH1949** [comment]
After some Forge updates I'm getting teleported now.  I added a third rail segment in the Nether, and while the overworld segments are fine, I get dumped as soon as I hit the Nether segment.
