### ISSUE TITLE
remove power input cap on machines

### ISSUE THREAD

**Issue by kurokuno** [SleepyTrousers/EnderIO#2264]
well i have noticed that more or less everything in EnderIO has an input cap and i am talking sag mills furnaces farms so on my issue with this is that there are mods out there that increase tick on machines to make them go faster and even if you can drop 5 million RF into a single side of the machine its capped so low that you cant keep them powered

**Comment by asiekierka** [comment]
Mods that increase ticks on machines use massive hacks to do it - so massive that BuildCraft actually works around this by not relying on the machine-specific ticks to tick, but rather the world ticking time.

**Comment by kurokuno** [comment]
well its not that machines cant be easily increased in speed and behavior is more or less perfect no signs of duplications or anything else its just a case of how much power per tick a machine allows in some mods machines that are without this cap have no issue being increased "take draconic evolution's furnace it when increased 3600% in speed has no issues because its not capped on total power input allowed per tick

**Comment by MatthiasMann** [comment]
EnderIO machines have upgrades which define how much power and speed a single machine handles. If you want to increase your production further use more machines.

**Comment by tterrag1098** [comment]
The cap is there as a mechanic and is not being removed because some mod is hacking the system.
