### ISSUE TITLE
Capacitor banks loosing inventory after upgrade.

### ISSUE THREAD

**Issue by Gunner76th** [SleepyTrousers/EnderIO#2269]
Situation is this, if you place an item into a capacitor bank to charge, then wrench the capacitor bank, the item remains inside. If you then take the capacitor back (with the item inside it) and use it in an upgrade recipe to make the next tier capacitor bank, the amount of charge that was in the previous capacitor bank is reflected in the new upgrade, however the item that was in the previous level's inventory is lost.

To prevent this:
 1) the new capacitor bank should be created with not only the combined charge of the previous tier banks used to craft it, but also with the inventory of the previous banks (however this presents an issue if both lower tier banks both have 4 items)

2) when a capacitor bank is wrenched up, all inventory in the charge slots should be dropped to the ground, similar to when you harvest a vanilla chest. This would prevent the possibility of using 2 lower tier capacitor banks that each have 4 items being charged from causing a glitch when the new tier bank is created.

3) Have the crafting recipe do a check on the inventory of the capacitor bank like it does on the charge stored. If the check returns a TRUE value on "does inventory contain items" then do not allow the bank to be used in crafting. This again would prevent the item from being lost because of the upgrade, as well as prevents being able to use 2 banks to create a higher tier bank, that both contain 4 items, thus causing a glitch.

Of the 3 methods, dropping any items in the capacitor banks inventory would be the easiest and probably best method to resolve this issue.

**Comment by tterrag1098** [comment]
@MatthiasMann That code is yours, any chance you could resolve this?
