### ISSUE TITLE
Reservoir Visual Bug

### ISSUE THREAD

**Issue by thunder1221sa** [SleepyTrousers/EnderIO#2270]
After updating to the latest version(1.7.10-2.2.8.349) I realized the reservoir looks like lava is inside, instead of water. I right clicked on it with a bucket and water comes out instead of what I thought would(lava). I came to the conclusion that it was probably just a visual glitch.
P.S I am using the Direwolf20 pack 1.7.10 version 1.2.1
Photo:
https://cloud.githubusercontent.com/assets/10692987/7082184/55269ed0-df04-11e4-8108-826eb71362c3.png

**Comment by katur239** [comment]
I've noticed once it looked like a Metal sheet inside the reservoir. I logged in the next day and it was normal. May have been a texture pack issue. This was using 2.3.370

**Comment by thunder1221sa** [comment]
I have not used a texture pack with this mod pack before.

**Comment by thunder1221sa** [comment]
The issue is gone after resetting.

**Comment by thunder1221sa** [comment]
Let me know if this happens to others
