### ISSUE TITLE
Waila Buildcraft EnderIO Energy Tooltip Problem

### ISSUE THREAD

**Issue by jorgebonafe** [SleepyTrousers/EnderIO#2271]
I've been playing FTB direwolf20's pack without enderIO, and I've recently enabled it. I noticed that the power usage of buildcraft blocks, that was previously displayed when looking at a buildcraft block, wasn't being displayed anymore. I disabled and enabled enderIO again to confirm that was indeed what was causing it. Here are some screenshots, showing the difference when enderIO is disabled and enabled.

![with enderio](https://cloud.githubusercontent.com/assets/1023068/7083083/d4a5668a-df33-11e4-85b8-34285dbf560e.png)
![without enderio](https://cloud.githubusercontent.com/assets/1023068/7083084/d4a8dc84-df33-11e4-94f7-9f8e798d6b0a.png)

**Comment by MatthiasMann** [comment]
That has been fixed - update to EnderIO 2.2.8 build 367

**Comment by jorgebonafe** [comment]
Indeed it works now. I apologize for not trying to get the latest version before posting the issue. Thank you for the insanely fast response :)
