### ISSUE TITLE
Suggestion for ME conduits

### ISSUE THREAD

**Issue by Gameswithjohn** [SleepyTrousers/EnderIO#2275]
Make ME conduits fit into the same spaces/attach to things (such as in the same block as P2P, busses, and condensed ME interfaces) that regular ME cables are able to. I've been trying to use the ender io conduits because they are infinitely superior when it comes to making any type of transport/ME system and the facades are much better than anything else has, but have run into issues when trying to utilize the dense conduits since they won't hook up to the P2P networking on the internal side, thus trying to make a system that needs to carry more than 8 lines from one place back to the controller still requires multiple lines negating the ability to fit everything into one block space. Implementing this feature would help to alleviate having to use the standard ME cable simply to connect back into a system.

Thanks for already making a fun and useful mod.

**Comment by tterrag1098** [comment]
This is an extremely complex feature, and I have attempted it before. I do not see it happening any time soon.

**Comment by Gameswithjohn** [comment]
what about an adapter that interacts with them instead of the actual conduit, the adapter could have direct interaction with the AE parts and also the conduits without the issue of fitting the conduit into the same spot? that would be similar to how the AE dense cables cannot be in the same spot but the regular cables can. 

honestly a colab. of AE and EnderIO would be great in certain aspects as both seem to be trying to do similar things and have distinct good features(other than the crystal growth part of AE2 thats just annoying) and a combination of the two in parts would be all the better.

**Comment by MatthiasMann** [comment]
That adapter already exists and is called a fluix cable.

**Comment by Gameswithjohn** [comment]
that works alright until you try to do a run of cable that needs to be more than 8 channels then it fails. 

by the way, thank you guys for responding so quickly. this may only be about a mod to a game but it shows a dedication to the community behind it.

**Comment by MatthiasMann** [comment]
AE2 only allows to place parts against fluix cables (8 channels) - not dense cables.
The AE2 API makes it very hard to put parts somewhere else - and we don't want to reimplement everything.
So I suggest you get creative with your machine placement instead - as there are no plans to add parts support.
