### ISSUE TITLE
(2.3.0.370) Farming Station visual glitch

### ISSUE THREAD

**Issue by katur239** [SleepyTrousers/EnderIO#2277]
The Farming Station doesn't look right.
![2015-04-10_16 12 12](https://cloud.githubusercontent.com/assets/10789738/7097592/abeff7aa-df9c-11e4-953c-d63a756e60db.png)

**Comment by tterrag1098** [comment]
Stop using optifine.

**Comment by katur239** [comment]
Ah right. I forget it can cause this and that I have it installed D: I am sorry.
