### ISSUE TITLE
Additional upgrades to alloy smelter?

### ISSUE THREAD

**Issue by Zaflis** [SleepyTrousers/EnderIO#2278]
Would be great if we could somehow further increase speed of alloy smelters. Even with Octadic capacitors making vibrant alloy is very slow. Maybe 1 or 2 more tiers of capacitors? I wouldn't even mind if the tier 4 would only double the speed at cost of 4 octadic capacitors and a nether star. Anything but more machines, that's just path to more game lag.

Sagmills could use these upgrades too. I'm using 6 of them in current endgame base just for ore processing. (3 alloy smelteries were enough to keep them full of darksteel balls)

**Comment by Dwargkiller** [comment]
The current state of the mod is that beyond octadic capacitors, further throughput is achieved through more machines.

As I see it, there are a few possible paths to take on this question:
1. Do nothing, higher throughput beyond Octadic = more machines
2. Add third tier of Capacitor, further increasing speed
3. Consider optimizing machines for less lag

Option 1 has potential for lag, in endgame setups. The example above has 9 machines for just the sag mill operation of ore processing. It scales pretty quickly in the end, and thus can lag things up.

Option two is probably the simplest in terms of implementation (rote work in adding the fourth tier to relevant locations as well as recipes etc), the question is whether we actually want to speed the machines up further. A possible route to take is to make the recipe ludicrously expensive (Ludicrite from Big reactors is an example) to really make it an end game thing. 

Option three may not be possible if they're already optimized. Do we have an option to disable the animations (low intensity as they are)? May help things.

**Comment by tterrag1098** [comment]
I have no plans to simply implement more capacitor tiers, see #1894. I may do SOME kind of mechanic in the future that achieves this goal, but simply adding a new tier of capacitors will not be it.
