### ISSUE TITLE
Suggestion: Pacifist recepies 

### ISSUE THREAD

**Issue by KaffeMyers** [SleepyTrousers/EnderIO#2280]
Playing (modded) Minecraft, I've found myself being a great fan of gathering materials (aside from mining) by farming and other non-violent ways. I'm nigh-pacifist, or to the greatest extent I can manage. I also love working with Ender IO, it's simply great, to not start an erotic explanation of my feelings toward the mod. <3

However, some stuff requires a kill (or many) -- things like various heads. I would like to see an alternative way of gathering materials for those recipes -- Ender Cabbage (Endermen head) and Putrid Cauliflower (Zombie head) as a couple of silly examples to help kick start a brainstorming session. It doesn't have to be something you grow like farm crops, but just a way to remove any unnecessary bloodshed (*snort*). You can balance it by making it a harder/longer path than killing and what not (growing ender pearls with ender-lily seeds sure takes its sweet, sweet time).

Honestly, I actually go out of my way to NOT kill (before I start with bees, I scour the desert for cinder pearls to get blaze powder -- I don't go to the nether and camp at a blaze spawner, and so on).

I think I needn't write anything else. You most likely have gotten the idea by now. :)

Thanks for reading and potentially considering my request.

**Comment by tterrag1098** [comment]
Related to #1474
