### ISSUE TITLE
Crash when loading my world

### ISSUE THREAD

**Issue by abdullamu** [SleepyTrousers/EnderIO#2281]
when i load my world i get this crash 

http://pastebin.com/VCpu2EVG

**Comment by MatthiasMann** [comment]
Hmm - stack trace is Mekanism - don't think that has anything to do with EnderIO.

**Comment by abdullamu** [comment]
i updated it to tthe latest still happening i even removed the conduits in mcedit now showing another coordinates

**Comment by tterrag1098** [comment]
Get rid of optifine, This is not an EIO issue, the crash log doesnt even mention it,

**Comment by abdullamu** [comment]
i did remove it and the problem still there http://pastebin.com/RCqNdcL8
 if its not supported that doesnt mean its the problem i have been using optifine since i started my world and without it my frames will be 0.5 fps, anyway the problem happened after i updates some mods

**Comment by abdullamu** [comment]
i found the problem it was after i updated forge to the latest and the cause of the problem is Fluid changes introduced with latest Forge
