### ISSUE TITLE
Client Crash on Startup

### ISSUE THREAD

**Issue by martindiv** [SleepyTrousers/EnderIO#2283]
Receive a crash when updating to 2.3.0.371 beta on the client side only. Server is loading ok. This is the only mod I updated in the pack at the time.

http://pastebin.com/xVneebBs

**Comment by SirKastros** [comment]
Enderio does not have gravestone and there is also some errors with thaumcraft on the crash report

**Comment by martindiv** [comment]
Actually, it's saying it can't find thaumcraft. This makes sense since I don't have it installed.

I'm pointing at Enderio because it only happens when I have Enderio 2.3.0.371 beta installed. If I revert to 2.2.8.349 I don't get the crash.

**Comment by SirKastros** [comment]
I have tested this build in my mod pack and I am not getting any crash. are you using the gravestones mod this might be the cause of the crash.

**Comment by SirKastros** [comment]
GraveStone{2.11.1} [GraveStone] (GraveStone 2.11.1.jar) Unloaded I seen this line in the crash report and the crash is cause by this mod

**Comment by SirKastros** [comment]
the lastest EnderIO 2.2.8 is build 367 which has alot of fixes from build 349 also build 371 is a beta build so it might have some issues working together with other mods.

**Comment by SirKastros** [comment]
I have tested the with the latest version of gravestone (2.12.2) and the client did not crash. Please update gravestone mod.
