### ISSUE TITLE
Can't acess an Ender IO when using a Chicken Chunks Chunk Loader and cannot access an ME System with a staff of travelling and an Ender IO

### ISSUE THREAD

**Issue by TheMonkey78** [SleepyTrousers/EnderIO#2284]
I used a Chicken Chunks chunk loader for my Ender IO, however when I go out of my Render Distance I can't access it. I have read on the FTB wiki and the Ender IO wiki that if I load the chunk the Ender IO is in, I can access it from anywhere with a Staff of Travelling. Also, I cannot use an ME Terminal or ME Crafting Terminal from an Ender IO as well. I can open my ME Drives, or anything with a GUI from another mod, just not the ME Terminal and Crafting Terminal. I am in 1.7.10 and am using Chicken Chunks 1.3.4.16, AE2 RV2 Beta 9, and Ender IO 2.2.8.349.

**Comment by MatthiasMann** [comment]
The EnderIO (and Travel Anchors) must be in rendering range to be accessible. And there is a config option "enderIoMeAccessEnabled" which can disable the use of an ME terminal via the EnderIO.

**Comment by tterrag1098** [comment]
Yes, this is not a bug. Chunk loaders load on the server, the Ender IO requires clientside rendering to function.
