### ISSUE TITLE
Cannot use NEI shortcuts when any EIO UI is open

### ISSUE THREAD

**Issue by Xuerian** [SleepyTrousers/EnderIO#2285]
Pretty straightforward.

Using latest two beta versions.

**Comment by tterrag1098** [comment]
Such as? I'm not aware of any issues along those lines. Also...version?

**Comment by Xuerian** [comment]
Such as R and U -- Left clicking NEI itemsoutside of cheat mode still works.

Forge 1360
NotEnoughItems-1.7.10-1.0.4.95-universal.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
EnderIO-1.7.10-2.3.0.371_beta.jar

Shortcuts work with EnderIO-1.7.10-2.2.8.367.jar
