### ISSUE TITLE
[Minor Change] Travel anchor

### ISSUE THREAD

**Issue by hisorange** [SleepyTrousers/EnderIO#2286]
Aye, when you stand on a travel anchor and wana teleport /jump/ to an another one, the one you stand on displays it's "name / icon" which is mostly invisible but when you have an anchor up high and your destionation is kinda under you, you can't see it from the one you stand on, and it's kinda unnecessary to display where you stand at. It's just blocking your view when a text in your face so not a huge issue just a minor convenience. :3

build 370 ish ~ (not sure since when this in the builds)

http://postimg.org/image/r85l9s959/ example

**Comment by tterrag1098** [comment]
Implemented via https://github.com/SleepyTrousers/EnderIO/commit/2d33e7ad5592e63c330950360a213f009cfd9400

**Comment by hisorange** [comment]
Great! Minor features like this makes the Ender IO so nice to play. Thanks :)

**Comment by tterrag1098** [comment]
We keep issues open until release for easier searching.
