### ISSUE TITLE
Fluid conduit in/out mode doesnt work as expected.

### ISSUE THREAD

**Issue by justicesays** [SleepyTrousers/EnderIO#2287]
I have an example set up here, two tanks connected by a pressured fluid conduit, and a redstone conduit attached to both and to a lever.
The tank on the right has no I/O configured on the tank itself. The fluid conduit is set to "in/out" with auto extract redstone mode set to "Active with signal".
The tank on the left has no I//O configured on the tank itself. The fluid conduit is set to "in/out" with auto extract redstone mode set to "Active without signal".
My expectation here is that when I apply a redstone signal via the lever, fluid will flow from the right tank to the left tank, and when I remove the signal, fluid would flow from the left tank to the right tank.
In fact, neither of these occur. Regardless of the signal sent, fluid just stays in the same tank, no extraction occurs
![2015-04-12_01 14 44](https://cloud.githubusercontent.com/assets/10358888/7103861/bd8a8770-e0b2-11e4-9d42-813285a35239.png)
![2015-04-12_01 14 39](https://cloud.githubusercontent.com/assets/10358888/7103862/bdb6ed9c-e0b2-11e4-9825-0e3935d8bb17.png)
![2015-04-12_01 14 28](https://cloud.githubusercontent.com/assets/10358888/7103863/bdbb35be-e0b2-11e4-886e-92d8a3d69021.png)

**Comment by tterrag1098** [comment]
Fixed via https://github.com/SleepyTrousers/EnderIO/commit/a24ca2c10975e53a0b27baeb635567b8777a719f

Read the commit notes on that to see the new behavior, I think it's more along the lines of what most would expect.

**Comment by emperor06** [comment]
I was a bit puzzled because the behaviour described by justicesays is what I have been using already and it works fine. So I tried with 2.2.8.367, turns out it only works as expected with ender fluid conduits (fluid moves from tank to tank on redstone signal). Normal and pressurized conduits don't react at all.
Could it be an issue with those specific tiers of conduit? (I know the system has changed in the recent commits, just wondering)

**Comment by justicesays** [comment]
Following on from emperor06's comment, I replaced the pressurized conduit with an ender conduit and it indeed worked as I originally expected.

**Comment by justicesays** [comment]
I imagine the reason it works with ender fluid conduits is that on extraction , the fluid is immediately transported to the destination conduit and inserted.
With the other pipes, the fluid is moved to the output conduit, then immediately re-inserted into the same tank, as that tank is still a valid insert target under the current code.
The destination search for the ender conduit likely excludes the local tank.

**Comment by tofof** [comment]
This should probably not have been closed. In/Out mode is functionally the same as 'Disabled' mode on non-ender fluid conduit. The option for in/out mode should be removed, or its functionality should match the behavior of ender fluid conduit (for runs carrying only a single type of fluid, obviously).
