### ISSUE TITLE
Using shortcut  in the travel anchor authorization dialog destroys items

### ISSUE THREAD

**Issue by ariscop** [SleepyTrousers/EnderIO#2289]
https://youtu.be/FjZ_AL30fXs
Using the hotbar shortcuts (in this case, pressing 1) places the item in the password prompt, from which it cannot be recovered.

Current Material Energy 4 pack
Not sure which version is installed since the main menu has no textures and i don't know which button shows mods

**Comment by tterrag1098** [comment]
This is already fixed in dev versions.
