### ISSUE TITLE
CoFH dependency stated nowhere

### ISSUE THREAD

**Issue by vixblu** [SleepyTrousers/EnderIO#2291]
Through testing I just found out Ender IO needs CoFH Core installed to work, but couldn't find the information on that depency in the forum post, on CurseForge or MFL list, did I overlook something or should it be added to the mod information perhaps?

(I'm playing with a small personal modpack, didn't have the need to add CoFH Core before.)

**Comment by MatthiasMann** [comment]
It should not depend on CoFH core - which version and what error did you get?

**Comment by vixblu** [comment]
http://pastebin.com/MEdwpGrj

Forge 10.13.1343
Ender IO 2.2.8.367

**Comment by tterrag1098** [comment]
EnderIO ships the missing class reported in that stacktrace, we have no dependency on the CoFH API. Some other mod is interfering. Make sure you are up to date on all mods.

**Comment by vixblu** [comment]
Thanks, will check all my mods!
