### ISSUE TITLE
Crouch to activate travel anchor option

### ISSUE THREAD

**Issue by Xuerian** [SleepyTrousers/EnderIO#2296]
A simpler version of/precursor to #1140

Once you have a few items that enhance jump capacity or add flight, jumping to travel can get a little wonky.

**Comment by 6210classick** [comment]
it's not a bug it's just the dafault behavior , i believe the same thing also happens with open blocks elevators

**Comment by Xuerian** [comment]
@6210classick I know, this was a feature suggestion. GitHub doesn't really let issue creators not on the project label issues, it'll get labeled by someone.
