### ISSUE TITLE
Cannot access an ME System with a staff of travelling and an Ender IO

### ISSUE THREAD

**Issue by TheMonkey78** [SleepyTrousers/EnderIO#2297]
I cannot acess a ME Terminal or ME Crafting Terminal from an Ender IO using a Staff of Travelling . I can open my ME Drives, or anything with a GUI from another mod, just not the ME Terminal and Crafting Terminal. Someone said there was a config option however I haven't found it, only something for ME Conduits. I am in 1.7.10 and am using Chicken Chunks 1.3.4.16, AE2 RV2 Beta 9, and Ender IO 2.2.8.349.

**Comment by 6210classick** [comment]
B:enderIoMeAccessEnabled=true

you are using old versions of your mods the current latest is Ender IO 2.2.8.367 , ChickenChunks 	1.3.4.19 , AE2 RV2 Beta 18 is the current recommended version

**Comment by MatthiasMann** [comment]
You already opened issue #2284 - why did you open a new one?!?
You already got all answers making a new issues with the same text won't get you any more/different answers.

**Comment by TheMonkey78** [comment]
The other thread was closed.

**Comment by Ianaver** [comment]
I do believe that this is also configurable in the config so go and check there because it may be enabled so enderIOs can't interact with ME networks :/

**Comment by oxyum** [comment]
If somebody interested, this bugs reproducible with following configuration:

* MC 1.7.10
* Forge 10.13.4.1448
* Applied Energistics2 rv2-stable-10
* EnderIO 2.2.8.381

```
"personal settings" {
    B:enderIoMeAccessEnabled=true
}
```
