### ISSUE TITLE
Invisible Machines

### ISSUE THREAD

**Issue by ultrasn0w** [SleepyTrousers/EnderIO#2298]
Hey there,
with latest build from Jenkins the Combustion Generator is invisible :)
https://i.imgur.com/jX1ASd5.png

Greetings
ultrasn0w

**Comment by MatthiasMann** [comment]
Are you using Optifine? try without.

**Comment by ultrasn0w** [comment]
Yes, I am.
Sorry, but I'm not able to test without OptiFine. I guess I have to live with the Invisible Combustion Generator then.

**Comment by Dwargkiller** [comment]
General rule of thumb is to try without Optifine before reporting issues, as it tends to break half the mods it interacts with. If it's an Ender IO issue, it'll usually be an issue even without Optifine, 9/10 times.

**Comment by ultrasn0w** [comment]
Okay, sorry, just wanted to help you finding bugs :)
