### ISSUE TITLE
[Suggestion] Conduit Facade Rotability

### ISSUE THREAD

**Issue by drifter397** [SleepyTrousers/EnderIO#2299]
Having said, the ability for logs to be placed sideways is nice and it would be nice for the facades to do that too. Same goes for the other blocks which can be oriented differently. Maybe add a function to the wrench or a separate tool to do that?

**Comment by MatthiasMann** [comment]
You can already rotate log facades with a wrench and their initial orientation depends on how you place them.

**Comment by drifter397** [comment]
How are you supposed to rotate them when the wrench hides the facade when  holding it? Also, I tried placing it against another

**Comment by MatthiasMann** [comment]
You need to switch the yeta wrench into a mode in which it does not hide the facades (eg the opposite of show all conduit types => show no conduits).

**Comment by Dwargkiller** [comment]
We could add documentation on the wiki for it (http://wiki.enderio.com/Conduit_Facade or  http://wiki.enderio.com/Yeta_Wrench perhaps (or both)
