### ISSUE TITLE
Killer Joe issue? (2.3.0.371

### ISSUE THREAD

**Issue by katur239** [SleepyTrousers/EnderIO#2303]
Not exactly sure what's goin on but Killer Joe will stop attacking for some reason. There aren't any errors to look at, but I cant ever seem to get it to start attacking again, putting down another Joe and it'll attack fine for a little bit, but it'll stop too.

![2015-04-12_17 37 32](https://cloud.githubusercontent.com/assets/10789738/7107924/4d8f297e-e13b-11e4-8686-e83ce47f812b.png)

**Comment by MatthiasMann** [comment]
It needs the tank at least 2/3 full - otherwise he can't reach it (he has no straw).

**Comment by katur239** [comment]
OH is that it? I've been filling it with buckets, so I tried to top it off but of course that doesn't work. until it is at half.

Guess I'll need to pipe in conduits.. 

I did not see anywhere it needed 2/3 tank though.

Thanks for your help.

**Comment by 6210classick** [comment]
both killer joe and zombie generator require the tank o be more than 75% full to work any lower they will stop working
