### ISSUE TITLE
[enhancement] fluid conduits containing luminous fluids should provide light

### ISSUE THREAD

**Issue by keturn** [SleepyTrousers/EnderIO#2304]
If the contents of a conduit are visible, and that content is luminous, the conduit should provide light.  
The amount of light should scale to the fullness of the conduit and the luminosity of the fluid.  
(and, if plausible, light color.)

**Comment by tterrag1098** [comment]
Do they not?

**Comment by keturn** [comment]
In a dark area, I filled some basic fluid conduits with TE's energized glowstone (which has a luminosity level 15), and it didn't change the light level.

The version of EnderIO on this server is a few months old (2.2.6.317), so we could be out of date, but the source looks like conduits don't override the default `getLightValue`.

**Comment by tterrag1098** [comment]
Yeah, they used to, not sure what happened. I'm looking into it now.

**Comment by tterrag1098** [comment]
Implemented via https://github.com/SleepyTrousers/EnderIO/commit/ad107a14fbf48cdc37a878b25497c308de038e2e
