### ISSUE TITLE
[Feature Request] Powered lights with integrated daylight sensors!

### ISSUE THREAD

**Issue by MFernflower** [SleepyTrousers/EnderIO#2306]
Not certain if its been requested before. Just thought its a good idea!

**Comment by emperor06** [comment]
Imho, since the powered light already requires a power cable, nothing prevents you from adding a redstone conduit plugged to a daylight sensor. On the other hand, it may be a cool feature for wireless powered lights.

**Comment by MFernflower** [comment]
Why not have it for bolth, Wired lights will then loose there ability to take redstone

**Comment by emperor06** [comment]
For me, the ability to have control with a redstone signal is more valuable. It allows to switch on and off the lights with a switch, a daylight sensor, a player detector, an inventory comparator, etc.
