### ISSUE TITLE
[Bug] Hotbar Assignment does not work with Ender IO interfaces open

### ISSUE THREAD

**Issue by tjsd** [SleepyTrousers/EnderIO#2307]
Whenever I open a inventory from Ender IO, sag mill, alloy smelter, killer joe, buffers it is impossible to hover over a item and press a hot bar number to move that item. This works fine in other inventories and mods interface.

**Comment by TehNut** [comment]
If I'm understanding what you mean, that is actually Vanilla functionality.

**Comment by tjsd** [comment]
It could be vanilla yeah.. might be I was wrong in thinking it was inventory tweaks. Anyway, that does not work with Ender IO :)

**Comment by tterrag1098** [comment]
This was fixed under https://github.com/SleepyTrousers/EnderIO/issues/2285
