### ISSUE TITLE
Reservoir Filling Issue

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2309]
I have 2 issues with the Reservoir as multiblock:
1. Only 1 of the 4 blocks can be manually filled with a bucket. When clicking on any of the 3 others, nothing happens on first click then the next click will spill water in the world. Which block can be clicked to get filled depends on the order you placed the 4 blocks (and seems pretty erratic ^^).
2. Fluids cannot be piped in multiblock reservoirs.

Nota: single block reservoirs seems to work fine. It only affects the multiblock version.

**Comment by 6210classick** [comment]
what version are you experience this problem with ?

you fill the Reservoir with 2 buckets of water and it will keep generating water so why do you need to pipe water into it ???

is the multiblock formed correctly ? it needs to be 2x2x1

**Comment by emperor06** [comment]
1. Using latest commit on branch master.

2. Commit f2f6bdd3 says: "Full IN+OUT: Tank, Reservoir, XP Obelisk, Soul Binder". Since "IN" is not working, I think it's better to mention it regardless of the reservoir common usage.

3. The multiblock is formed correctly (hard to do it wrong since the visual changes when it's complete). I have tried all 3 possible setups: 2x2x1, 2x1x2, 1x2x2. Same issue on all.

**Comment by HenryLoenwind** [comment]
Darn, I know what happened. When I combined the right-click code into the super-class, I trashed the special coding the reservoir (as a multi-bock) needs. Oops.

**Comment by emperor06** [comment]
:)

**Comment by tterrag1098** [comment]
Fixed via https://github.com/SleepyTrousers/EnderIO/commit/215dcd425ce799a7f9b47ba968e55b535796a02d
