### ISSUE TITLE
[Question] New In/Out System for Fluid Conduits

### ISSUE THREAD

**Issue by emperor06** [SleepyTrousers/EnderIO#2310]
According to commit a24ca2c10975e53a0b27baeb635567b8777a719f
Improve liquid conduit behavior with in/out mode
  - This means in/out can only input if extraction is not active, and vice versa

I just tried with a couple of Fluid Tanks and a fluid conduit between them.
Tank 1 is full of water, connection set to extract mode (always active).
Tank 2 is empty, connection set to in/out with auto-extract always active too.
I would expect things to stay static since Tank 2 can "only" extract (input should be disabled) but what happens is Tank 1 fills Tank 2.
Is this a bug or is there something I haven't understood in the commit's message?

**Comment by tterrag1098** [comment]
If tank 2's conduit is set to in/out with always active, it should not be able to be filled. I'll look into this.

**Comment by justicesays** [comment]
Is there any meaning behind extract and insert only modes if the "always extract" and "never extract" are options on in/out mode? Seems like those functionalities overlap and one or the other should be removed.

**Comment by justicesays** [comment]
After some more thought, , given extract only mode also has a redstone signal, I can see that that doesn't completely overlap with in/out (always extract) , as you can prevent insertions while also not extracting.
I don't believe insert mode has a redstone signal though, it always allows inserts. 
Should that be changed (to take a signal to allow or prevent insertions) ? or should "Never extract" on in/out mode removed?
