### ISSUE TITLE
Energy Conduit crash in 1.7.10

### ISSUE THREAD

**Issue by Imonthetop** [SleepyTrousers/EnderIO#2320]
whenever i place an energy conduit, the game freezes and then crashes, can someone explain how and why this happens and how to fix it? crash report: http://pastebin.com/raw.php?i=PqunpGTY

**Comment by HenryLoenwind** [comment]
It seems your Ender IO version still uses Buildcraft MJ, but your Buildcraft version uses RF.

Try updating Ender IO, but not too far---the current versions no longer support AE2 rv1.

**Comment by Imonthetop** [comment]
My ender io energy conduit says it carries rf. I'll look at the updates.

**Comment by tterrag1098** [comment]
Your version is almost a year out of date. If you expect any support please
update.

**Comment by Imonthetop** [comment]
what version would you suggest?

**Comment by tterrag1098** [comment]
The latest version?

**Comment by Imonthetop** [comment]
Thanks,  the latest version worked perfectly.
