### ISSUE TITLE
[Mod Compatibility] Painted Mystcraft Crystals

### ISSUE THREAD

**Issue by BarbasTheDog** [SleepyTrousers/EnderIO#2322]
Not sure if possible, but very simple idea: Just like Painted Glowstone but with Mystcraft portal Crystals. The original texture Crystal is very ugly, it would be awesome if we could paint it.

**Comment by 6210classick** [comment]
you could surround the Portal Crystal with forge multiparts covers , or use Enhanced Portals mod.

**Comment by BarbasTheDog** [comment]
I know I could do those things. This isn't as much a problem that I'm faced with as it is a cool inter-mod feature suggestion.

**Comment by MatthiasMann** [comment]
While we could easily paint these blocks - the result would be an EnderIO block and no longer work as a Mystcraft block.
Why not make a texture pack and change the texture for that block?

**Comment by tterrag1098** [comment]
That depends on if there is an interface or class we can extend that would
allow this. If mystcraft is hard coded to use its own block this will not
be possible.

**Comment by TheJulianJES** [comment]
Maybe ask @XCompWiz

**Comment by XCompWiz** [comment]
I could be open to ways to flag other blocks as usable in portals, but I'd need to rewrite my pathing system to do it, I think.  I currently use block metadata to track the direction to the portal receptacle and do all of my structure maintenance and construction "in-world."
I think that'll have to change anyway, given changes to Minecraft, so it should be doable when Mystcraft updates to 1.9.
