### ISSUE TITLE
Mekanism AI outdated? EIO, NEI, Mekanism combo crashes minecraft.

### ISSUE THREAD

**Issue by Robijnvogel** [SleepyTrousers/EnderIO#2323]
The current versions of EnderIO, Not Enough Items and Mekanism seem to crash Minecraft. Removing the Mekanism API from the EnderIO .jar seemed to fix the problem. I am wondering if this API is outdated and/or obsolete.

Details here:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods?page=1068

**Comment by vixblu** [comment]
Related to #2291, where I wrongly stated the problem as Ender IO having a CoFHCore depency (that issue can kept closed, as it would be misleading I guess).

**Comment by Robijnvogel** [comment]
You are correct, I think. In the case I am describing, adding CoFHCore to the setup also solved the problem.

**Comment by vixblu** [comment]
It did solve it (it's the same case :-) sorry: platform names are different), but isn't a fix in the long run I guess, since Ender IO wouldn't need/want that depency I guess. I'm very curious still if it isn't just an outdated/obsolete API.

**Comment by MatthiasMann** [comment]
EnderIO does not require CoFHCore at all. You just change the load order by adding that mod which causes the correct version of the API to be used. This is not an EnderIO bug.

**Comment by vixblu** [comment]
I know :-) But for now it's a solution/patch. Sorry if the CoFHCOre thing confuses the question, please disregard this part. (But thanks for explaining what/how it does, didn't know).

**Comment by tterrag1098** [comment]
It is outdated. This is due to FML's @API annotation not doing its job and preferring the newer version. Nothing I can do here, removing the API from our jar is a good fix for now.
