### ISSUE TITLE
TD Ducts and Conduit weirdness (RF)

### ISSUE THREAD

**Issue by tgstyle** [SleepyTrousers/EnderIO#2326]
I am using the latest 2.2.8 hotfix, so if this is fixed in the 2.3 series please ignore.

I think the title says it all. They do not play nice together at all, nor with capacitor banks. Each one used on their own work as designed, however the moment you try to use them together bizarre stuff starts to happen. If you run duct between two capacitors it will dump the Max Input value in to the receiving capacitor and no more. Combos of conduits and ducts are even more weird. Sometimes they don't work at all together, sometimes you have to specify Extract or Input. If you don't the power will back flow and keep looping back and forth.

**Comment by Dwargkiller** [comment]
To clarify: Thermal Dynamics ducts don't work as intended when used with our machines and conduits? Are our conduits behaving strangely with the Thermal mods too?

**Comment by tgstyle** [comment]
Machines are fine when using conduits or ducts on their own to give them power. It seems to just be when mixing conduits and ducts together. Capacitor banks seem to extract power OK with ducts, just not input.

**Comment by tgstyle** [comment]
To test, place a full capacitor bank, then an RF duct, then a conduit, then another RF duct, then an empty capacitor.

**Comment by tgstyle** [comment]
You will see the capacitor drain and it will look fine. then when it is fully drained (it does not balance out between the two) you will see the power start to back flow in to the first capacitor then drain, it does this over and over.

**Comment by MatthiasMann** [comment]
The balancing of the capacitor banks is a special feature of EnderIO energy conduits. It will not work with other mods' pipes.

**Comment by tgstyle** [comment]
Well even if you place a charged capacitor bank then an RF duct and an empty capacitor bank, it will move up to the Max Input value and nothing more.

**Comment by Dwargkiller** [comment]
On top of that, due to the differences in how mods handle transportation of RF, it's very not recommended. Completely not never do it recommendeded.

To combine different ducts/conduits, use intermediary buffers. Energy Converters, different sides of capacitor banks, anything but connecting modA:Conduit to modB:Conduit or pipe or duct or whatever.

**Comment by tterrag1098** [comment]
Cap banks should not allow anything but pull/push/disabled when connected to non-conduit RF blocks. If they are allowing push/pull (i.e. no mode) that is a bug.

**Comment by tterrag1098** [comment]
This is for exactly the reason you are describing...it results in infinite back/forth

**Comment by tgstyle** [comment]
I just noticed as long as I set the push pull on the side of the capacitor bank power will flow OK with ducts between two capacitor banks.

**Comment by tgstyle** [comment]
@Dwargkiller there needs to be some kind of proper mod interaction, as Cryo-Stabalized flux duct blows any mods capability of power transfer out of the water. However, it seems as long as you set the input/ouput on the side of the capacitor bank with the duct, it seems to move the power fine. So as long as there is an intermediary like the capacitor bank to bridge the 2 power systems, this should be acceptable.

**Comment by MatthiasMann** [comment]
The EnderIO power system works nicely and is balanced. I see no point to change anything just because other mod's pipes do not work as well as conduits.

Energy conduits know the difference between a capacitor bank, a generator and a consumer and do intelligent energy transfer (excess energy goes into cap banks, if more energy is required than available from the generators it is taken from the cap banks).

**Comment by tterrag1098** [comment]
@MatthiasMann Cap banks are normal RF API implementing blocks, when it comes down to it. There should be no issues as long as other mods properly implement the API as well. Yes, power conduits have special code, this is true, but that doesn't mean cap banks should not or do not support other mods.
