### ISSUE TITLE
Latest EnderIO+ latest MFR

### ISSUE THREAD

**Issue by excelcrafter** [SleepyTrousers/EnderIO#2328]
server: cauldron 1307 + many mods

client: forge 1291 + many mods

everything works fine, till I add MineFactoryReloaded-[1.7.10]2.8.0-104.jar
then:

http://pastebin.com/szggiXfB

**Comment by MatthiasMann** [comment]
The crash happens in ExtraCells code - and seems to be related to the new forge fluid API changes.
Not an EnderIO problem.

**Comment by excelcrafter** [comment]
thank you

I am using ExtraCells-1.7.10-2.2.68bNIGHTLY because this version ExtraCells-1.7.10-2.2.69bNIGHTLY doesnt work at all with setup I have...

**Comment by OldOpa** [comment]
update forge since changes happened in newer versions (above version 10.13.3.1355) that contains fluids.

**Comment by excelcrafter** [comment]
thank you very much for an advice, will try that...

my server uses forge 1307 :( so still need to wait for update, but going to try in singleplayer forge 1355+

**Comment by excelcrafter** [comment]
with my modpack, I need probably still wait...
gregtech shows error
railcraft shows error

forge-1.7.10-10.13.3.1374-1.7.10

**Comment by tterrag1098** [comment]
Blame Extracells for requiring a forge version that is not well supported yet. This is exactly why I have not made this change in EIO

**Comment by excelcrafter** [comment]
I am not blaming anybody, I am happy for every single mod developped. Just wanted to report something, because it can maybe help...
