### ISSUE TITLE
[Suggestion] Yeta Wrench compatibility with MFR

### ISSUE THREAD

**Issue by tgstyle** [SleepyTrousers/EnderIO#2331]
I have noticed the TE Crescent Hammer works for removal and use on MFR machines (obviously). Could this same functionality be added to the Yeta Wrench?

**Comment by Dwargkiller** [comment]
I expect to have this finished by the end of the day.

**Comment by Dwargkiller** [comment]
And I was mistaken. Can't seem to figure out the way it works.

**Comment by tgstyle** [comment]
Wonder if @skyboy could provide some insight?
