### ISSUE TITLE
Huge amount of XP levels with some ores...

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2335]
Some ore's after taking them out of the alloy smelter give a "normal" amount of XP. Like 1-2 levels or so.

A stack of Iron Ingots boosts be up to level 50+. A stack of copper does not. A stack of lead ingot boosts me up to 40+.

Something's awry...I'm thinking maybe some calculation does 64*xp, like each ingot gives 0.7*xp, the calculation goes 64*0.7 or something. I dunno....

**Comment by MatthiasMann** [comment]
The calculation is correct - it is the same as a vanilla furnace.

**Comment by HenryLoenwind** [comment]
I went through that code with the fine comb back in February. There's nothing in it that could produce different results for different ores.

**Comment by Unrepentant-Atheist** [comment]
Damn...I used to have that problem...then it resolved...now it's back again....I have no idea... I guess I'll just /xp -100L then.

**Comment by Unrepentant-Atheist** [comment]
So far, I've found that Lead, Ferrous Ingot and Silver causes these xp spikes.

**Comment by MatthiasMann** [comment]
Please - try the same in the vanilla furnace.

**Comment by Benguin** [comment]
When you test this, ensure that your XP is always at 0 before taking anything out of the furnace, as levels get way more expensive after level 15, and even more expensive after 30. Use the XP obelisk to empty it each time.

**Comment by downslope7** [comment]
I'm seeing this too on 367. It doesn't always happen, but right now if I smelt 64 Mekanism Iron dust I get 61 levels. If I do the same in a Vanilla furnace i get ~4.

**Comment by MatthiasMann** [comment]
How do you take out the items (eg how do you click etc) - I never saw anything like that.
