### ISSUE TITLE
Travel Anchor name won't accept an 'e'

### ISSUE THREAD

**Issue by braddr** [SleepyTrousers/EnderIO#2342]
There was a commit that was supposed to address this issue, but as of 2.3.0.273_beta, which should include that commit, it still isn't allowing 'e's in anchor names.

**Comment by eduardog3000** [comment]
It isn't working in the latest build, 374, either.

**Comment by tterrag1098** [comment]
Fixed via 5cbacb0e7b357f2410dbee75926ca7ca29f97ed3
