### ISSUE TITLE
[Request] More Configurations?

### ISSUE THREAD

**Issue by JAWSAWN** [SleepyTrousers/EnderIO#2344]
EnderIO lacks of configs. Players should able to disable almost all of the items/machines like how MFR and TE does.

**Comment by MatthiasMann** [comment]
Many of the EnderIO machines are required to craft other things - it doesn't make sense to disable these.
What exactly do you want to disable and why?
You can always use Minetweaker to remove recipes.

**Comment by JAWSAWN** [comment]
Yes I can always use minetweaker but just suggesting to add more disable-ability.

Also kinda out of topic, how can I disable all of the alloyer/sagmill recipes? Just want to know.

**Comment by Dwargkiller** [comment]
The easiest EIO native way of disabling recipes in a machine is to go into the user config and put an invalid recipe in. 

This would disable the sag milling of certus  quartz ore, if put in the SAGMillRecipes_User.xml file, as stated in said file. Same format for other machines.
<recipeGroup name="Applied Energistics">
  <recipe name="CertusQuartzOre"/>
</recipeGroup>

**Comment by MatthiasMann** [comment]
@Dwargkiller EIO has support for removing recipes - no need for invalid ones.

**Comment by Dwargkiller** [comment]
@MatthiasMann The sag mill config literally says, and I quote:

"To disable individual recipes, simply provide an invalid recipe for them"

Recipe groups can be disabled with a false flag, individual ones can't.
