### ISSUE TITLE
ender rail

### ISSUE THREAD

**Issue by squall2044** [SleepyTrousers/EnderIO#2347]
i don't know if it is a bug or if it is intentional but the ender rail crashes servers if someone tries to ride through in the minecart.

**Comment by MatthiasMann** [comment]
Well - as you did not provide any of the following we can't do anything:
- crash log
- version information
- ways to reproduce

**Comment by 6210classick** [comment]
it's not recommended to use it on servers as it causes memory leaks specially when travel to another dimension

**Comment by HenryLoenwind** [comment]
@6210classick Could you please stop this? We've been through this multiple times now. The only memory leak it causes is the normal vanilla leak you get every time you switch dimensions.

**Comment by squall2044** [comment]
I'll reproduce it when i get home and post those things sorry that I forgot I don't normally post online.
