### ISSUE TITLE
dark steel anvil uses all of repair item

### ISSUE THREAD

**Issue by braddr** [SleepyTrousers/EnderIO#2350]
Using 2.3.0.372_beta, place a barely damaged invar hoe in a dark steel anvil with more than one invar ingot.  The result is the entire amount of invar is consumed.  I tested with both a full stack as well as just 2 invar ingots.  In both cases, all were consumed.  The same behavior with iron pickaxe and sword (just for the sake of finding out if it was material or tool specific).

**Comment by MatthiasMann** [comment]
The dark steel anvil does not have any code on it's own - it's just a vanilla anvil with different durability values.

**Comment by tterrag1098** [comment]
Correct, this must be bad behavior on TE's side.

**Comment by braddr** [comment]
I'll dig more.  The problem occurs with iron too (as noted in the original report).  That ought to takes TE off the hook.  But if all EIO does is play with durability, that puts it closer to forge or minecraft core.  Something's wrong somewhere though.
