### ISSUE TITLE
Crash with ExU + EnderIO + NEI

### ISSUE THREAD

**Issue by juniorjunior** [SleepyTrousers/EnderIO#2352]
Not sure if this is from EnderIO or ExtraUtilities (ExU) so I'm posting in both.
If you have ExU OR EnderIO + NEI it works fine. If you have ExU AND EnderIO + NEI it crashes.

http://pastebin.com/Qisxk7vZ

CodeChickenCore 1.0.5.37
EnderIO 2.3.0.375_beta
ExU 1.2.4b
NEI 1.0.4.95
Forge 1.7.10_1381 (also tested _1355 and _1389)

Edit: Please forgive the messed up crash report (hasty Vi edit). Fixed now.

**Comment by Unrepentant-Atheist** [comment]
Because everybody know what ExU stands for... :-1:

**Comment by tterrag1098** [comment]
What is up with this crash log? Why does every line end with 'g'?

**Comment by HenryLoenwind** [comment]
Seems like ExU is including the Baubles API in its jar and somehow it won't load properly when there are other mods that also can use it. I'd recommend to not include a the Baubles API but use the proper fml annotations (@Optional.interface) instead.

**Comment by juniorjunior** [comment]
@HenryLoenwind: True enough. That ends up biting folks in the butt way too many times in way too many mods.

**Comment by TheJulianJES** [comment]
@juniorjunior You could try to remove the baubles api from the jar :D

**Comment by juniorjunior** [comment]
Already tried that. Didn't seem to help.

**Comment by Cherry** [comment]
This smells familliar; https://github.com/SleepyTrousers/EnderIO/issues/2203

**Comment by tterrag1098** [comment]
#2203

**Comment by Ianaver** [comment]
@tterrag1098  seems that the issue is not existant when EnderIO is renamed to anything that doesn't start with "E" however, it would be nice if I wouldn't have to do that everytime I download an update for this mod. :)

**Comment by tterrag1098** [comment]
It's a load order issue, but as well stated in the other issue, EIO does not ship Baubles nor touch anything related to ExU, so it being our fault is extremely unlikely. Until I find any evidence that it *is* our fault, this issue remains closed.

**Comment by Ianaver** [comment]
@tterrag1098 yeah but I believe that maybe somewhere in the code, when that combo of mods is used without renaming the mod, something is still calling baubles even if its not included in the mod itself... this is just a theory and I am most likely wrong however maybe after looking, the issue may be found and resolved.. :)
