### ISSUE TITLE
Enderio conduits ignoring priority [TPPI2]

### ISSUE THREAD

**Issue by Euphoreich** [SleepyTrousers/EnderIO#2353]

**Comment by MatthiasMann** [comment]
Well - without steps to reproduce / screenshots of your setup etc - this bug report is basically invalid.

**Comment by Euphoreich** [comment]
Sorry, I couldnt get them to work at all in a variety of setups. Ill screenshot a few.

**Comment by Euphoreich** [comment]
Sorry was a really poor bug report.

https://imgur.com/SIIN7hG
https://imgur.com/z1Ns18Q

I have enderio coming from a harvester going to a planter. The one on the tesseract is set to -2 priority, and the one on the planter is set to 4. Was hoping this would send items that can be entered into the planter (saplings), and everything else to the tesseract. The item conduit coming out of the planter even lists the planter as the first destination, but instead saplings are being sent to the tesseract.

My thought for possible cause, is that it reads the wood as unable to be sent to the planter, and doesn't then check the saplings? If this is intentional by design to reduce lag I understand.

**Comment by Euphoreich** [comment]
I'm actually having trouble reproducing it now, I'll get back to you if I'm able to.
