### ISSUE TITLE
Baubles API issue surfaced again but differently....

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2354]
weelll hate to break it to ya but this time its when this SPECIFIC combo is used that I get crashes:
 NEI, EnderIO, extra utils (removing EIO or extra utils or NEI fixes this)

sorry it this whole this seems to not make sense (grammer etc), had to write it in a hurry

paste: http://pastebin.com/rxA9WEDR

**Comment by 6210classick** [comment]
this is might be because of the new forge fluid handler.

 try forge 1377 as i read it's the best version if you don't have railcraft installed

**Comment by tterrag1098** [comment]
This is no different than #2352
