### ISSUE TITLE
Capacitor bank duplication

### ISSUE THREAD

**Issue by PharMiki** [SleepyTrousers/EnderIO#2359]
I found a way to duplicate capacitor banks (any) and create some weird creative capacitor banks in survival mode MC 1.7.10 with enderIO 2.2.8.349 and BloodMagic (private modpack)

I'm not sure if I should post the process here as I'm not sure if that could cause cheating on servers

**Comment by tterrag1098** [comment]
That version is out of date and I am fairly sure the issue you are referring to is fixed.

See #2053

**Comment by PharMiki** [comment]
Oh, sorry for the false alarm

It is fixed in v2.2.8.367 for every item EXCEPT dark steel pressure plates, which still get duped (same way)
