### ISSUE TITLE
[Request] Compact 1 Block Mob Resource Collection

### ISSUE THREAD

**Issue by Noobsloth** [SleepyTrousers/EnderIO#2360]
In a late game setting, you sometimes have the need for a utter crap ton of mob resources like wither skulls and ender pearls. In most settings your only option is to make a laggy grinder that outputs what you need. There's a lot of problems with this setup in terms of server tps impact and single player system performance.

In order to solve this, implement something that bypasses the spawning and grinding of mobs in general that causes a huge drag on systems. A block that is resource intensive that will within this single block generate mob drops while consuming rf. You could configure the block to generate mob drops from a certain mob with its soul and after a while the soul would deteriorate and the player will have to go get another (optional balancing?). This is essentially an extra utilities peaceful table, but with mob drop specification and a balanced option to playing on a difficulty other than peaceful.

**Comment by 6210classick** [comment]
a block that is similar to Botatnia Loomium but uses alot of RF to generate mob drops ?

**Comment by Noobsloth** [comment]
Well, yes and now. Instead of dungeon loot it'd be purely mob drops, no armors from them or anything special. If you put in a ender soul, you get enderpearls and maybe chances for some heads.
