### ISSUE TITLE
2 dark pressure plate issues

### ISSUE THREAD

**Issue by ghost** [SleepyTrousers/EnderIO#2361]
version used: MC 1.7.10 enderIO 2.2.8.367

1. a picked up dark pressure plate (silent or normal) stacks (and changes its type to fit silent->normal or vice versa) to any other (painted to the same block) you have in your inventory (if you don't have another dark pressure plate in your inventory everything works fine)

2. the dupe bug from #2053 still works for dark pressure plates (always producing a non painted one). The duplication only happens if the pressure plate sits on top of the teleposer.

(the dark pressure plate is also the only item from enderIO that drops when destroyed in creative, could be connected to 2.)

**Comment by HenryLoenwind** [comment]
1 is fixed in Ender IO 2.3
