### ISSUE TITLE
Workaround for extractEnergy

### ISSUE THREAD

**Issue by hisorange** [SleepyTrousers/EnderIO#2362]
Aye, so I trying to find a workaround for the way EiO handles the extractEnergy from the CoFH api as you guys know the RF providers will always return 0 on this function and run their own /pushing/ mechanism (didn't gone throught the capbank's way but read throught the generators way) and this explains why SteveAddons can't extract energy from EiO IEnergyProviders / also I am in the same trouble since the generator will go and check if there is a tile which can accept the RF at that coord with the required interface.

So I come here to ask if there is a way to reimplement the extractEnergy or any workaround?

**Comment by 6210classick** [comment]
i believe in the latest dev version capbanks now shows power generation & usage separately

**Comment by hisorange** [comment]
I am not sure if that's connected to this in any possible way :D

**Comment by MatthiasMann** [comment]
In the 2.3 beta builds you should eb able to extract energy from the cap banks.

**Comment by hisorange** [comment]
Nope, I have the build 375 in dev and my real problem is this [part](https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/generator/AbstractGeneratorEntity.java#L28)  when I call generatorTile.extractEnergy(...) I get 0,  so basicly the EiO always pushing energy to touching IEnergyReceivers?(https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/generator/stirling/TileEntityStirlingGenerator.java#L213)[fn]

**Comment by tterrag1098** [comment]
RF is push based, generators are not extractable. Blame CoFH for providing interfaces which force an extraction method which we do not wish to provide.

**Comment by hisorange** [comment]
There is no1 to blame :D I was opening the issue to get in contact with the devs, I used the enderio's code as learning material to understand java, and when I got stuck with this was wondering is this a direct act or a missed code.

I have a backup plan to support EiO just fine. Thanks for the reply. Closing the issue since it's not a real issue and nothing to fix :)
