### ISSUE TITLE
Can't change Dark Steel durability drain w/ Empowered

### ISSUE THREAD

**Issue by Soundtoxin** [SleepyTrousers/EnderIO#2363]
I'd like Empowered IV on all my Dark Steel to make the durability stop going down entirely rather than only absorbing 0.95 durability damage with power. I'm endgame. I put a lot of work into all my stuff. It is not difficult to repeatedly repair my armor. It's tedious, and annoying. The fact that my helmet can break and I lose all those upgrades? Ridiculous.

I've tried changing 0.95 to 1.0 and 1. Neither is changing anything in-game. I made the change on both client and server and saw that the armor reflected it as 100% now in the tooltip, however I can watch my durability go down every few hits still.

No logs as it is not a crash.
Modlist: http://sprunge.us/UARV

**Comment by tterrag1098** [comment]
What enchants do you have on the armor?

**Comment by Soundtoxin** [comment]
Just Soulbound on my armor.

**Comment by MatthiasMann** [comment]
Did you attack anything with thorns on it? Because damage caused by thorns bypasses all damage handling code.

**Comment by Soundtoxin** [comment]
Nope. I just went down to my mobspawner room and let an armored zombie hit me.

**Comment by 6210classick** [comment]
yes thorn will damage your armor durability directly

**Comment by Soundtoxin** [comment]
I don't think every zombie had thorns on his armor, and I heard from another player with Dark Steel that their durability still goes down as well. It should be safe to rule out the thorns theory.

**Comment by MatthiasMann** [comment]
Is your armor fully charged?

**Comment by Soundtoxin** [comment]
Yes, yes. I was hoping to not get these simple questions, but I suppose I never said so. My armor is fully charged with a Tier 5 Jetplate from Simple Jetpacks keeping them constantly fully charged. There's no rational reason for this change not working.

**Comment by Soundtoxin** [comment]
My friend on my server with fire resistance on his armor takes a lot of durability damage when swimming in lava, but I do not. I don't seem to take durability damage from anything anymore. Since I last posted I have updated my entire pack, including newer EnderIO.

**Comment by tterrag1098** [comment]
Odd, I tested it specifically with 100% to make sure it worked. Something must have changed, I will investigate.

**Comment by tterrag1098** [comment]
Testing this now, it seems to work fine. What were you being hit with?

**Comment by Soundtoxin** [comment]
Initially I tested it with a mob spawner in a roguelike dungeon. The armored zombies were able to hurt me. I also took durability damage from walking into my autonomous activator with a sword in it.

**Comment by tterrag1098** [comment]
100% does not mean it protects you from 100% of damage, it means that it will never take durability damage from attacks. What sword was in the activator?

**Comment by Soundtoxin** [comment]
I know exactly what it means. I even bothered to type out "durability damage". Please do not make assumptions. The sword in the AA was irrelevant as it was not the only thing that damaged me. Both a TCon Cleaver and Rapier had been in there. My dark armor negates fall damage, so I can't test with that, but I also had a player hit me and cause damage to my armor. I don't care about damage to myself. I've got 3 bars of HP. I care that my expensive armor with a bunch of upgrades can just break and disappear for good despite my config change to avoid this. Are we on the same page now?
