### ISSUE TITLE
Vat does not use the correct amount of RF when modified in the config file

### ISSUE THREAD

**Issue by 6210classick** [SleepyTrousers/EnderIO#2364]
i changed this in the config file from 20 to 160 and 320

Power use (RF/t) used by the vat.
    I:vatPowerUserPerTickRF=160

however it seems that it only uses 80 RF/tick no matter what number i change it to . i used capacitor bank next to  monitor the power consumption , also it seems that the power monitor doesn't identity the Vat power consumption , is this intended for all machines ? or it's just for monitoring power cells , banks . etc ???

Ender IO v2.2.8 367 
Forge 1377

**Comment by MatthiasMann** [comment]
Did you connect the Vat to the Capbank & power monitor via a single energy conduit? Because the power monitor only monitors the energy conduit network.

**Comment by 6210classick** [comment]
yes i did it showed nothing but if i connected a capacitor bank the power monitor will show that it using 80 RF ( the same result when monitored by capacitor bank ) per tick even thought i changed the setting to 160 RF and even 320 RF.

it seems that it will use a maximum of 80 RF per/tick if "vatPowerUserPerTickRF" is increased to above 80 RF

**Comment by HenryLoenwind** [comment]
The code for the power use of machines has changed massively in 2.3.

**Comment by 6210classick** [comment]
good to know ! THX
