### ISSUE TITLE
Ender Rail player teleportation

### ISSUE THREAD

**Issue by cronoise** [SleepyTrousers/EnderIO#2365]
Version: ftb Infinity 1.4.1 with EnderIO 2.2.8.367
Everything is set up correctly and empty minecarts teleport just fine.
I tried this with and without any armor or other fancy mod stuff wearing or sitting in my inventory. Results are the same.

Description: If a player is sitting in a minecart he will be ported but - on his client only - will seem to exit the minecart on arrival. Entities become "invisible" for this player. The player can move around freely, for bystanding players he still sits in his minecart. On pressing shift he will be ported to the position the minecart actually is at.

Entities will reappear after reconnecting the client. The players position also will be updated, resulting in still sitting in the minecart.

There seem to be no entries in any log.

This problem also has been described here: http://forum.feed-the-beast.com/threads/1-0-3-ender-rail-makes-minecart-disappear.66347/

**Comment by cronoise** [comment]
Did some further testing and this only seems to happen when porting from overworld to overworld. When porting from overworld to End, entities are visible as usual. The cart is being placed near the ender rail while the player appears directly above the ender rail (disembarked). I'll try some other setups too, just need more time to play mc :)

**Comment by cronoise** [comment]
Ok, I'll try to be as specific as I can:
1) Porting Overworld -> Overworld
Results in bug as being described in OP

2) Porting Overworld -> End
It works, but results vary: Most of the times, the player is being placed before the minecart is placed, resulting in the player standing on the tracks and the minecart appearing besides. Very rarely the teleport works in resulting the player spawning sitting in the minecart and on the tracks.

3) Porting End -> Overwrold
On arrival the player seems to float in space. Nothing is being rendered and no interaction is possible. Journeymap shows Overwrold though. Couldn't verify what happens to the minecart. Need to reconnect, the player appears on block in front of the Ender Rail.

4) Porting Overworld -> Nether and Nether -> Overworld
It works flawless!

Do you want/need some pictures? Should I check any specific logfile or setting? Want me to test any specific dimension next?

Thank you for Ender IO, I love this mod =)

**Comment by zenups** [comment]
Having the same problem. Overworld -> Deep Dark results in the same behavior as overworld -> overworld. Love the mod. I'll be glad to asset testing this if needed.

**Comment by behdahh** [comment]
I would like to add that this issue can also be observed in a single-player world, not only on servers (with EnderIO 2.2.8.381 using Direwolf20 pack v. 1.8.0 for MC 1.7.10).
