### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by Shadow232** [SleepyTrousers/EnderIO#2366]
crash - log http://pastebin.com/V6M043B9

ender io version - latest, compiled
forge - 1291

**Comment by HenryLoenwind** [comment]
please don't cut away the version information for the installed mods from the crashlog

**Comment by Shadow232** [comment]
crash then you place ender ME tube

**Comment by Shadow232** [comment]
http://pastebin.com/05JjEEJV

**Comment by MatthiasMann** [comment]
AE2 rv1 is not supported since EIO 2.2.6.
