### ISSUE TITLE
Liquid Duplication

### ISSUE THREAD

**Issue by SethWilliamson** [SleepyTrousers/EnderIO#2369]
**Steps to Reproduce**
1. Place 1-999 mB of liquid in a pressurized or normal fluid tank
2. Right click on tank with an empty bucket to receive 1000 mB

The above steps can be automated with other mods to turn 1 mB into 1000 mB in a loop for infinite liquid.

Works as of 2.2.8.367

**Comment by MatthiasMann** [comment]
That has been fixed in the 2.3 beta builds

**Comment by SethWilliamson** [comment]
Duplicate of #2164 

Oops, I should know better. I didn't think to check closed tickets since the bug exists in the most recent publicly available version. Sorry about that.
