### ISSUE TITLE
[Suggestion] Machine balance input mode

### ISSUE THREAD

**Issue by tgstyle** [SleepyTrousers/EnderIO#2370]
Machines currently have pull, push, and push/pull capabilities on the sides, how about a balance mode? Something similar to what Mekanism does in a factory for auto-sort. This however would balance the input slot across multiple machines so items can be processed in parallel instead of whatever machine fills it's buffer first (yes I know conduits can do round robin, but this is quite different).

**Comment by tterrag1098** [comment]
How exactly would this be useful for EIO machines?

**Comment by tgstyle** [comment]
In the case of machines, it would really only be useful for Alloy Smelters or SAG mills. It would allow for the machines to balance their input slot across each other for faster processing. Say if you build 10 SAG mills in a row, you input items in to 1 SAG Mill, it detects the other 10 SAG Mills that all have the balance mode enabled on whatever side they are all touching on, Then proceeds to balance that input across all 10 SAG mills input slots. Then all 10 sag mills process that input vs. just one.

**Comment by tterrag1098** [comment]
That case is handled by item conduits round robin mode, I don't see the purpose of re-implementing it in machines. It would require quite a bit of code to make machines a "multiblock" like that.

**Comment by tgstyle** [comment]
Yes I have mentioned RR. That only works if you even use conduits. This would be for purposes other then a conduit. The machines already have non-conduit capabilities. I understand it wouldn't be an easy task, and quite a bit of code =).

**Comment by tterrag1098** [comment]
@tgstyle The problem is that I do not want to implement features which obsolete other features already in the mod. "I don't want to use conduits" is not a valid reason for a feature. It's the same reason I don't want to implement wireless power, because it would remove the need for power conduits.

**Comment by tgstyle** [comment]
How about Tiered SAG Mills and Alloy smelters then that do this internal to the block? Similar to Mekanism Factories?
