### ISSUE TITLE
Powered Spawner doesn't spawn in liquids

### ISSUE THREAD

**Issue by dgbonomo** [SleepyTrousers/EnderIO#2373]
As described.  I had a look at the code and this seems to be on purpose.  However, it does prevent a squid spawner from working underwater.  To get my squid spawner to work I had to extend my redstone and energy conduits from the bottom of my water-reservoir and place the spawner just above the water level so that spawned squids appear mid-air and then fall into the water, which is quite silly.  More importantly though, it's visually unappealing.  It's not a major issue, but it probably isn't too hard to add an exception, so I figured I'd post it as an issue.

**Comment by 6210classick** [comment]
have you tried  spawners from other mods ? if so can they spawn squids outside water ??

**Comment by dgbonomo** [comment]
I have not.

**Comment by hisorange** [comment]
I use squid spawner as well, but it seems less of an issue, since squids do not care about the attractor / water current your only way to move them around is either a conveyor belt or some kind of a fan, (they don't have AI to force them to move anywhere) so spawning them in water makes a hard kill.

**Comment by dgbonomo** [comment]
That's true, I noticed the same problems (oh the hours spent trying to work out why the obelisk wasn't working, heh).  I've had good success with fans placed exactly under the bottom, although it does mean they don't extend far into the water above (a single layer, I think).  Still, most squids seem to end up going down and in doing so get blown towards my grinders.  It'd be neat if they'd actually spawn in the water there instead of me having to spawn them up in the air and hope for the best, though!

**Comment by dgbonomo** [comment]
(Woops, pressed the wrong button.  That's what I get for writing while barely awake.  Sorry.)

**Comment by HenryLoenwind** [comment]
When I need ink sacs, I either setup a stack of "water source, x*flowing water, sign, hopper" or a spawner and a vacuum chest in a dry room...

**Comment by hisorange** [comment]
I spawn them ina 7x5x7 room with 2 water source in the NE-NW corners and has a killer joe in the center of the south side, with this setup without they die before the next spawn come. (the water is only there so they can move around and get in the range of joe, they seems to do it fairly quicky, also slimes does not have AI either but in 1.7.10 they get moved by the water current so the room can be used for them as well)
