### ISSUE TITLE
Powered Lights, TileLightEntity spawning other entities

### ISSUE THREAD

**Issue by madpinger** [SleepyTrousers/EnderIO#2379]
At various times, while Moving around with a Staff of the Traveler or Logging in, Blue Orchids would spawn,  sometimes Poppy.  Then One time as seen in the linked image, with sag mills.:
http://madpinger.com/images/games/minecraft/2015-04-26_12.04.35.png

Removing the lights removed the entities, cept the flowers I picked up.

This is with FTB Infinity 1.4.1 dedicated server with fastcraft

**Comment by HenryLoenwind** [comment]
The reason for this is that some mod has a bug in its handling of air and is doing something on teleport events.

(Background: There are 2 kinds of air in Minecraft, "nothing there" air and blocks that act like air. The later are rare, but the powered lights use them to spread light outside the block's lighting radius.)

Now finding out which mod that is...um, yeah...

**Comment by madpinger** [comment]
Well,  in that area are chisel blocks of stone and glowstone with default redstone blocks,  Railcraft Motor switches, reinforced track, track switch, Levers, and the likely trigger of the event, myself. 

It had only ever been Flowers that spawned up till that point.   These sag mill iterations of the event were not to be touched on death of your client :D 

As I stated tho, removing them resolved the issue.  I considered trying to reproduce it in a single player map, but others on server advised I just post with that SS.

In the mean time,  lots of glow stone I suppose ^.^

**Comment by beringtom** [comment]
railcraft is bad at spawning fake "air" blocks, i know we have problems with them on our server
