### ISSUE TITLE
Obelisk animation is choppy in multiplayer

### ISSUE THREAD

**Issue by BBoldt** [SleepyTrousers/EnderIO#2386]
EnderIO-1.7.10-2.3.0.375_beta

The spinning animation is laggy/desynced in multiplayer, but looks fine in single player.

Probably related, I had this same issue with Botania last year:
https://github.com/Vazkii/Botania/issues/154

**Comment by RAnders00** [comment]
Double dropbox 404 by the way, it would be nice if you could upload the videos unlisted to youtube.

**Comment by BBoldt** [comment]
Oh, sorry about that. I ran out of space and had to delete some things.

That Botania issue I linked shows basically the same thing though, just with different objects.

**Comment by RAnders00** [comment]
No big deal then, there could have been some other visual artifacts as well that were not reported to that Botania issue.
