### ISSUE TITLE
AE2 Certus Quartz Crystal and ore SagMill recipes

### ISSUE THREAD

**Issue by bochen415** [SleepyTrousers/EnderIO#2388]
Something very strange is going on here: 
https://github.com/SleepyTrousers/EnderIO/blob/master/resources/assets/enderio/config/SAGMillRecipes_Core.xml#L737:L754

What it should be like:
CertusQuartzOre -> SagMill -> crystalCertusQuartz x **2 + 10% chance of dust**
and
CertusQuartzCrystal -> SagMill -> **crystalCertusdust (100%)**

What actually happens is:
CertusQuartzOre -> SagMill -> crystalCertusQuartz x **1 + crystalCertusdust x 1**
and
CertusQuartzCrystal -> SagMill -> **crystalCertusdust (about 10%)**

The last one being the worst as it looses most of the items.

Disclaimer: if I'm an idiot please close this issue and yell at me.

**Comment by Lilylicious** [comment]
Already fixed in a previous pull request. Sorry for making a recipe adjustment while tired!

**Comment by bochen415** [comment]
Ok, let me grab a sandwich and regenerate those configs.

**Comment by Lilylicious** [comment]
Build 376 contains the fix you're after.

**Comment by bochen415** [comment]
Configs regenerated. Issue gone. Closing. Thanks
