### ISSUE TITLE
Duplication bug with fluids 

### ISSUE THREAD

**Issue by zed-hex** [SleepyTrousers/EnderIO#2390]
If you click a fluid tank that has less than 1000mb with a bucket it will give you a bucket of the fluid that is in the tank this basically means that 1 mb of a fluid is turned into 1000mb. I don’t believe this bug has been reported yet. 
Here is a quick video of the bug: https://youtu.be/cVVJo1fV-yU

**Comment by HenryLoenwind** [comment]
Hey, duplication bug with issues. ;)

#2164 #2369
