### ISSUE TITLE
some blocks wont show up in ender io. they are just not there

### ISSUE THREAD

**Issue by ana1316** [SleepyTrousers/EnderIO#2394]
what do i do????

**Comment by tjsd** [comment]
have you tried looking for them?

**Comment by ana1316** [comment]
yea. im creative mode, when you place them, they dont show up on the ground

**Comment by tjsd** [comment]
maybe they are behind you.


or you are using optifine.

**Comment by ana1316** [comment]
im using optifine...why, is that a problem?

**Comment by Lilylicious** [comment]
Optifine is notorious for breaking just about every mod out there. Before you make any issues, disabling optifine is a good start.

**Comment by tterrag1098** [comment]
Optifine is the problem, yes

**Comment by Lilylicious** [comment]
To put it more bluntly, the problem is on Optifine's end, not ours.
