### ISSUE TITLE
Item conduits do not accept pulverized coal

### ISSUE THREAD

**Issue by stdrth** [SleepyTrousers/EnderIO#2399]
Item conduits do not pull TE pulverized coal.

From SAG mills or chests.

Leads to clogged SAG mills.

**Comment by Lilylicious** [comment]
Ender IO version? Do they pull everything else? Any filters? What in the conduit?

**Comment by stdrth** [comment]
EnderIO - 1.7.10 - 2.2.8.367

Yes they pull everything else so far.

Currently tested: 
enderstorage ender chest with no filters set to extract always.
SAG mill with advanced filter for sticky coal ore. Processes ore, coal and cobble taken but not bonus pulverized coal

**Comment by Lilylicious** [comment]
Is the destination filtered? If there's no valid destination, it doesn't pull the item out. I'm using 367, and TE pulverized coal is getting pulled out of chest A to chest B for me.

**Comment by stdrth** [comment]
Maybe these helps

![setup](https://cloud.githubusercontent.com/assets/12176330/7401168/e26e0fca-eeb9-11e4-9434-03f56d78fd50.png)
![input not draining](https://cloud.githubusercontent.com/assets/12176330/7401169/e808e7f2-eeb9-11e4-8053-60c3ffc86949.png)
![dialog](https://cloud.githubusercontent.com/assets/12176330/7401170/eae9e19c-eeb9-11e4-906a-8067fd91a0b9.jpg)

I test with other junk, it extracts e.g. tinker tools. Plenty of space in destination.

Does not pull from SAG mill either.

**Comment by MatthiasMann** [comment]
Is it the same ender chest?

**Comment by stdrth** [comment]
No. Origin is at z=607 (white-w-w). Destination is z=610 (blue-w-w). Tested with other junk, works. 

Also fails pull from SAG mill.

![bug](https://cloud.githubusercontent.com/assets/12176330/7401354/3ff44cbc-eebb-11e4-9b25-325324dddbcf.jpg)
![bug2](https://cloud.githubusercontent.com/assets/12176330/7401355/424db2f0-eebb-11e4-9f58-37953972e52c.jpg)

**Comment by MatthiasMann** [comment]
Check for filters in the destination. Without filters the item conduits do not even look at the items they move - but they ask the destination if the item can be inserted.

**Comment by stdrth** [comment]
I try iron ore. Bonus builds up until furnace smelts all iron dust. Then it draws bonus ferrous.

I try destination chest with and without filter. Makes no difference.
![bug2](https://cloud.githubusercontent.com/assets/12176330/7401522/cc8a095e-eebc-11e4-8430-54e8a78fb3fb.jpg)
![bug](https://cloud.githubusercontent.com/assets/12176330/7401523/ce9f74cc-eebc-11e4-836e-d25f5289e012.jpg)

**Comment by tterrag1098** [comment]
Could you show the settings on the sag mill item conduit?

**Comment by stdrth** [comment]
![bug](https://cloud.githubusercontent.com/assets/12176330/7401585/48b34784-eebd-11e4-9582-66cbebbe4b23.jpg)
![bug2](https://cloud.githubusercontent.com/assets/12176330/7401586/4b825220-eebd-11e4-9e04-d32201b2da94.jpg)
![bug3](https://cloud.githubusercontent.com/assets/12176330/7401590/4d9d35fc-eebd-11e4-90b9-7fa22766deb8.jpg)

**Comment by stdrth** [comment]
I think ender io wants treat coal dust like other dusts and put into furnace. 

The furnace does not accept, so it stays put. It doesnt go to outlet chest like other junk e.g. cobblestone, tinker tools

**Comment by tterrag1098** [comment]
If the furnace is on sticky mode this could happen, otherwise, it will go to the closest inventory, which should be the ender chest.

**Comment by stdrth** [comment]
Furnace is sticky.

You right it should go to closest inventory - ender chest at z=610. But does not. So I bug report.

![bug3](https://cloud.githubusercontent.com/assets/12176330/7402016/6d629fdc-eec0-11e4-8565-d5ea18d7c19a.jpg)

**Comment by tterrag1098** [comment]
Aha! You have metadata ignored, and coal dust is the same ID as those other dusts. Enable metadata and it will work fine.

**Comment by Lilylicious** [comment]
Mystery solved! TE uses one item ID with metadata for all their dusts, including coal.

**Comment by stdrth** [comment]
Aha I enable metadata and it works!

Thankyou for help.

Not know what metadata or NBT tags mean. Long testing yesterday to get whitelist as "this and only this" using sticky!

Perhaps interface improve? :) Thankyou!

**Comment by tterrag1098** [comment]
@stdrth Metadata is the damage value of the item, the "sub id". NBT is data on the item, such as energy stored, etc.
