### ISSUE TITLE
Mekanism 8.2 incompatibility with gas conduits

### ISSUE THREAD

**Issue by ShneekeyTheLost** [SleepyTrousers/EnderIO#2403]
Mekanism 8.2 seems to be breaking Gas Conduits. Again. It fixed the Electrolytic Separators not working because of the change to the Forge Fluid Handler in Forge 1351, but apparently broke compatibility with gas conduits.

**Comment by TehNut** [comment]
EnderIO version?

**Comment by ShneekeyTheLost** [comment]
2.2.8.367

**Comment by tterrag1098** [comment]
Crash log please

**Comment by octoberxp** [comment]
I'm having the same issue. I initially saw it with build 349, but I'm still seeing it with 367. Here's a crash log:  http://pastebin.com/satAaxJG

**Comment by MatthiasMann** [comment]
EnderIO 2.2.8 is NOT compatible with Mek 8.x

**Comment by eduardog3000** [comment]
Yay, another clone of #2110.
