### ISSUE TITLE
[Request] AutoSmelt Enchant in the Farming Station

### ISSUE THREAD

**Issue by Noobsloth** [SleepyTrousers/EnderIO#2404]
It would be nice to see the autosmelt enchant from ttCore usable in the farming station. Early game it would be a nice avenue to go down to get some power without smelting wood into charcoal.

Enchant works manually with the Dark Steel axe, just not in the station.

**Comment by HenryLoenwind** [comment]
can do.

However, there are some pitfalls: (1) Much(!) more code to run. (2) Axe damage is controlled by axe. (3) Special harvesting code of axes could run and interact with harvesting. (4) Energy use would be off for non-standard axes or if, we compensate, different than now for all axes.

(reminder for me: captureDrops(true); harvestBlock(); captureDrops(false); )

**Comment by TheBeast5282PCN** [comment]
Bump plz

**Comment by Noobsloth** [comment]
It looks like someone else shares the same dream of swimming in crap tons of charcoal as I do. :')

**Comment by TheBeast5282PCN** [comment]
Yessshhhhh
On Jan 30, 2016 3:23 AM, "Noobsloth" <notifications@github.com> wrote:
>
> It looks like someone else shares the same dream of swimming in crap tons
of charcoal as I do. :')
