### ISSUE TITLE
Item Filters Ignored (With Video!)

### ISSUE THREAD

**Issue by sonicer105** [SleepyTrousers/EnderIO#2406]
### The Problem:
When extracting items using item conduits, filters seem to be out right ignored. i have created a video to better illustrator my point: https://www.youtube.com/watch?v=RWpotbzG3gA
### The Specifics:
I am using the following game and mod versions:

* Minecraft 1.7.10
* FTB Infinity 1.4.1
* Minecraft Forge 10.13.2.1352
* Forge Mod Loader 7.10.103.1352
* Minecraft Coder Pack 9.05
* Ender IO 2.2.8.367

It's also worth noting that this occurred on a server, not single player.

**Comment by tterrag1098** [comment]
Railcraft multiblocks extract from adjacent chests automatically.

**Comment by sonicer105** [comment]
Wow i'm an idiot. Thanks for clearing that up.

**Comment by tterrag1098** [comment]
No problem, it's a pretty obscure feature to be fair.
