### ISSUE TITLE
Crash on start-up.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2414]
I'm trying to set up a mod-testing environment, and I can't get it even to start....

http://hastebin.com/egiraqihec.coffee

Whut?

**Comment by Unrepentant-Atheist** [comment]
Resolved by adding Thaumcraft in. Guess it doesn't work without, seeing as the ItemMagnet can be worn around the neck i.e. Baubles i.e. Thaumcraft.

That's some...strange...dependency....

**Comment by Lilylicious** [comment]
The dependency is actually Baubles, not thaumcraft. Thaumcraft downloads Baubles for you when it launches, which is why it resolved the issue.

**Comment by tterrag1098** [comment]
I see no reason it should crash without baubles...

**Comment by HenryLoenwind** [comment]
When I look at the crashlog:

    Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed

Baubles was already there? But loaded very late.

**Comment by tgstyle** [comment]
I see a similar issue in build 378.
https://gist.github.com/tgstyle/c2adfb2cd154e781adc6

**Comment by HenryLoenwind** [comment]
Wait a second...

    Caused by: java.lang.NullPointerException
    	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)

It seems a class transformer is returning null when transforming IBaubles.

**Comment by tterrag1098** [comment]
No, that's just the lowest error when a class is not found.

**Comment by tgstyle** [comment]
FYI renaming the mod to append a z to the name (zEnderIO.x.x.x.jar) allows it to load after Baubles initializes, and fixes the issue.

**Comment by MatthiasMann** [comment]
This should be fixed by f9c0d9d348d847458ed699f94a45f7f12bfdc0a1
