### ISSUE TITLE
Farmer not getting Magical Crops 4.0.0 (Beta 2) Seeds

### ISSUE THREAD

**Issue by sirnephilim** [SleepyTrousers/EnderIO#2417]
Farmer is picking up the essences but not the seeds. Something changed in the handling on MC's end, where "breaking" the plant leaves a plant at zero growth and drops essence and rarely a seed, while breaking the plant completely (at zero growth) always yields a seed. Latest MFR Harvester and Picker can't handle it either, with no result whatsoever from those machines.

Honestly not sure if this is something that can be fixed without special logic just for MC, I'm mentioning this on their thread as well. It'd be a real shame if you couldn't automate MC all of a sudden.

**Comment by tterrag1098** [comment]
Magical crops still has no official releases since over 6 months ago. Let me know when they actually have a public release of this version and aren't just vaporware.

**Comment by sirnephilim** [comment]
Fair enough, just making the issue known. Looks like they're actually working on the mod though, tons of changes in the beta.

**Comment by Adaptivity** [comment]
@tterrag1098 http://minecraft.curseforge.com/mc-mods/228834-magical-crops/files/2235126?

**Comment by tterrag1098** [comment]
What in the world? I loaded that page last night and there was no such
file. Regardless, I can only support one version at a time, so I will be
waiting until this is full release.
