### ISSUE TITLE
EnderIO tile tick

### ISSUE THREAD

**Issue by toarii** [SleepyTrousers/EnderIO#2422]
Hi,

I have a server crash when I use ender io fluid conduit to insert water in railcraft high pressure boiler 3x3x4, when insert water when the boiler is empty, he's explode and the server crash.
I have this error log...

http://pastebin.com/9ti8vKJE

Thank you.

**Comment by HenryLoenwind** [comment]
It looks to me like the railcraft block destroys the conduit network when and while(!) being filled by it.

https://github.com/SleepyTrousers/EnderIO/blob/2.2.8/src/main/java/crazypants/enderio/conduit/liquid/LiquidConduit.java#L281

**Comment by tterrag1098** [comment]
@toarii Could you please try this on the latest version? You are one release behind.

**Comment by toarii** [comment]
Hi,

Same think with EnderIO-1.7.10-2.2.8.367, when the boiler exploded, my server crash.

http://pastebin.com/dgs6MXus

**Comment by HenryLoenwind** [comment]
"when the boiler exploded". Yes, Railcraft destroys the conduit block while the conduit is filling it. Report that to Railcraft, that's not a bug at our side.

**Comment by toarii** [comment]
I have tried without your conduits, just putting water bucket in the boiler, he has exploded, but the server was not crash. I think the problem is when the conduit want to insert water in the next conduit or in object when he will broke. When the boiler explode, all conduits are updated in the same time of explosion. I think.

**Comment by HenryLoenwind** [comment]
Yes exactly. The Boiler is destroyinf the conduit while the conduit's code is running. It is like removing the dance floor while the dancers are dancing on it and then complaining that the dancers fall down.

**Comment by toarii** [comment]
I will report to Railcraft, thanks.
And can I turn conduit resistant to explosion ? Or maybe some explosion except TnT ?

**Comment by tterrag1098** [comment]
@toarii A hardened facade will do that job.
