### ISSUE TITLE
cannot add solar 1 into dark helmet

### ISSUE THREAD

**Issue by raven0ak** [SleepyTrousers/EnderIO#2424]
slight bug I think, for some reason helm displays solar 1 as possible upgrade with 1 photovoltaic cell and 10 levels, but when using anvil it says recipe is invalid. (helm is empowered)

**Comment by tterrag1098** [comment]
Are you using the basic photovoltaic panel? Not tier 2.

**Comment by tterrag1098** [comment]
A screenshot would be nice.

**Comment by raven0ak** [comment]
tier 1 ones

**Comment by tterrag1098** [comment]
Any news?

**Comment by inkgig** [comment]
same problem here - screenshot attached
![2015-07-17_20 27 41](https://cloud.githubusercontent.com/assets/13385147/8754273/a5bdd17c-2cc2-11e5-9972-5f8766e373df.png)

**Comment by MatthiasMann** [comment]
@inkgig no idea what you are trying to add to the helmet - but that is for sure not an EnderIO photovoltaic panel.

**Comment by TehSeph** [comment]
@inkgig That is the photovoltaic cell from [Solar Expansion](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2188753). Make sure you're using the photovoltaic cell from EnderIO.

**Comment by inkgig** [comment]
yep, using the correct photovoltaic cell helps... human error. thx
