### ISSUE TITLE
Not loading SagMill user xml

### ISSUE THREAD

**Issue by Landstryder** [SleepyTrousers/EnderIO#2427]
I've been trying to modify the recipes for the sag mill but nothing is happening. I've tried every variation of adding recipes, using mod ID and name, oreDict, but the recipe never shows up. The pack I'm using has EnderIO-1.7.10-2.2.8.367 loaded.

Here is the last attempt I made-
```xml
<SAGMillRecipes>

   <recipeGroup name="ExNihilo">
  
	<recipe name="exIronGravel" energyCost="3600">
      <input>
        <itemStack <itemStack oreDictionary="exIron" /> />
      </input>
      <output>          
        <itemStack oreDictionary="dustIron" number="2"/>              
        <itemStack oreDictionary="dustTin" number="1" chance="0.05" />        
        <itemStack oreDictionary="dustNickel" number="1" chance="0.1" />
        <itemStack modID="minecraft" itemName="cobblestone" chance="0.15" />
      </output>
    </recipe>
	  
	</recipeGroup> 

</SAGMillRecipes>
```
I used MineTweaker to add all the kinds of exNihilo iron to an oreDict entry. I had also tried the same recipe using `<itemStack modID="exnihilo" itemName="iron_gravel" />`

**Comment by MatthiasMann** [comment]
Are there any errors in the log file?

**Comment by MatthiasMann** [comment]
Actually - it might help to actually fix your XML file first - even the syntax highlighting in Github shows you that it is wrong.

**Comment by RAnders00** [comment]
Yeah, it's syntax is wrong: http://prntscr.com/731ahv
Please come back to this if the issue persists after removing the syntax mistake

**Comment by Landstryder** [comment]
I'm not sure where those extra characters came from when I pasted it here, they are not present in my file.
```xml
<SAGMillRecipes>

   <recipeGroup name="ExNihilo">
  
	<recipe name="exIronGravel" energyCost="3600">
      <input>
        <itemStack modID="exnihilo" itemName="iron_gravel" />
	  </input>
      <output>          
        <itemStack oreDictionary="dustIron" number="2"/>              
        <itemStack oreDictionary="dustTin" number="1" chance="0.05" />        
        <itemStack oreDictionary="dustNickel" number="1" chance="0.1" />
        <itemStack modID="minecraft" itemName="cobblestone" chance="0.15" />
      </output>
    </recipe>
	  
	</recipeGroup> 

</SAGMillRecipes>
```
here is what is in the file currently and still not working at all.

**Comment by RAnders00** [comment]
@tterrag1098 Reopen pls, I just validated it at [w3c](http://www.w3schools.com/xml/xml_validator.asp) and the file is fine.

**Comment by MatthiasMann** [comment]
@Landstryder check the log file - it should print "Finished processing SAG Mill recipes" - and around that it should display information about the parsed recipes.

**Comment by Landstryder** [comment]
Found this line that might indicate the problem..
 Could not create an item stack from the attributes [modID=exnihilo][itemName=iron_gravel]
but what to do about it?

**Comment by EntropicPariah** [comment]
I'm having the exact same issue. I modified the file and it does absolutely nothing. This is literally everything in the file.


<SAGMillRecipes>

  <recipeGroup name="Vanilla">

    <recipe name="Netherrack" energyCost="2400">
      <input>
        <itemStack modID="minecraft" itemName="netherrack" />
      </input>
      <output>
        <itemStack oreDictionary="dustSulfur" chance="0.15" />     
        <itemStack oreDictionary="dustGlowstone" chance="0.10" />
        <itemStack oreDictionary="dustGlowstone" chance="0.05" />  
      </output>
    </recipe>

    <recipe name="Cobblestone" energyCost="2400">
      <input>
        <itemStack modID="minecraft" itemName="cobblestone" />
      </input>
      <output>
        <itemStack oreDictionary="dustIron"  chance="0.05" />
        <itemStack oreDictionary="dustYellorium"  chance="0.01" />
        <itemStack oreDictionary="dustCopper"  chance="0.05" />
        <itemStack modID="minecraft" itemName="diamond"  chance0.001" />
      </output>
    </recipe>

  </recipeGroup>

</SAGMillRecipes>

**Comment by MatthiasMann** [comment]
@EntropicPariah you have a syntax error in your 2nd recipe.

Always check the log file when the recipes don't work as you expect.

**Comment by EntropicPariah** [comment]
I don't see the error in the 2nd recipe, I'll look again but it's driving me nuts. I've looked at this half a dozen times at least and I still can't figure out why it's not working.

**Comment by MatthiasMann** [comment]
@EntropicPariah the 4th output is missing a =" after chance

**Comment by EntropicPariah** [comment]
I didn't realize that if you screw up one thing it invalidates every recipe in the entire list. Thanks for the help, problem is corrected.

**Comment by Adaptivity** [comment]
@tterrag1098 definitely should be closed.
