### ISSUE TITLE
GUI Bug in latest build

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2428]
There's an armor slots gui bug in the latest build:

http://i.imgur.com/jheF2D5.jpg

**Comment by HenryLoenwind** [comment]
Your texture pack is outdated.

**Comment by tterrag1098** [comment]
Don't use texture packs with dev builds, you're asking for trouble. Why would you think this is our fault?

**Comment by Unrepentant-Atheist** [comment]
Ah yes, my bad. I like using dev builds. And do report bugs without thinking sometimes. Chill y'all. Mea culpa.
