### ISSUE TITLE
Reservoir wont work anymore (?)

### ISSUE THREAD

**Issue by lllMohandarlll** [SleepyTrousers/EnderIO#2429]
Even in singleplayer creative, if you try to put water in reservoir it wont accept it.
Is because of any Ender IO mod change with new version or it's just a bug?

http://i.imgur.com/1IItTJz.jpg (a symbolic image of water behind and down the reservoir that cannot be filled as result)

**Comment by tterrag1098** [comment]
What version?

**Comment by enterprise12nx** [comment]
i believe its build beta 376

**Comment by tterrag1098** [comment]
Please try 377

**Comment by enterprise12nx** [comment]
i'll get around to it eventually haha

**Comment by tterrag1098** [comment]
Alright well, I know this is fixed, so I'm going to close

**Comment by lllMohandarlll** [comment]
is the 377 out actually? 0:

**Comment by enterprise12nx** [comment]
http://ci.tterrag.com/job/EnderIO/
