### ISSUE TITLE
Machines should not carry redstone signal

### ISSUE THREAD

**Issue by beringtom** [SleepyTrousers/EnderIO#2430]
It seams that machines can carry redstone signals just like normal blocks, this means you can't place the machines right next to eachother without them shareing the redstone signal
![2015-05-06_23 44 59](https://cloud.githubusercontent.com/assets/3480271/7504364/f24f6b60-f449-11e4-8c2a-d425314638dc.png) if the bottom machine gets a redstone signal it's transfered to the machine above.

**Comment by tterrag1098** [comment]
There is a solution for this, disable the "Strong Signal" check box on the redstone conduits.

**Comment by beringtom** [comment]
You are absolutly right, my fault, delete this issue please.

Sorry.
