### ISSUE TITLE
[Feature Request] Item ejecting conduit

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2431]
I've got a build on my base that incorporates pipes that eject items from it. Currently it's done with Buildcraft pipes. They work fine.

However, I'd like to use ender io item conduit and the facades for that build. So an item ejecting conduit or filter or item that can be put into the conduit UI would be great!

**Comment by MatthiasMann** [comment]
You could use a dropper, Botania open crate etc...
