### ISSUE TITLE
Vibrant capacitor bank I/O UI not recognizing multiblock

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2432]
Using build 377, I've noticed that the I/O UI only displays the adjacent blocks to the selected capacitor block instead of the full multiblock:
![capacitor bank ui](https://cloud.githubusercontent.com/assets/10668463/7512592/f7ab92aa-f462-11e4-8db3-435a3e9519c0.png)

**Comment by MatthiasMann** [comment]
How many capacitor banks do you have in your multi block? The UI will show only the selected one when your multi block has 200 or more blocks.

**Comment by BillH1949** [comment]
Ah, that's it then -- I have 260 blocks in my bank at the moment.  Incidentally, is there an upper limit?

**Comment by MatthiasMann** [comment]
The multiblock will work just fine - the limit is only in the UI to prevent it from getting too slow.

**Comment by BillH1949** [comment]
Feel free to close as a nonissue then.  Thanks!
