### ISSUE TITLE
Server Stall Report:

### ISSUE THREAD

**Issue by Too-DAMN-Much** [SleepyTrousers/EnderIO#2435]
http://paste.ubuntu.com/11009776/

**Comment by beringtom** [comment]
I think it would help if you could descibe the problem a bit :)

**Comment by Too-DAMN-Much** [comment]
your mod rapes the performance of the server, not sure what other description you could need. see attached.

**Comment by Too-DAMN-Much** [comment]
this is about a month old now, i had to move houses in between when it was reported and now, i can't say i have any more specific information at any rate, don't worry about it for the time being since i've been away from MC anyway lately and i'll report it again if it comes up again.

also, aren't the stall reports enough information?

**Comment by MatthiasMann** [comment]
@Too-DAMN-Much screenshots of the setup and a way to reproduce are required. I expect that there are energy loops between different mods / piping system. The EnderIO conduits on their own don't form loops.
