### ISSUE TITLE
Powdered Coal

### ISSUE THREAD

**Issue by Joesalago** [SleepyTrousers/EnderIO#2438]
for some reason the SAG mil wont give powdered coal looked all through everything in the programming found it don't know how to change it
I think that dust coal is the primary and powdered coal should be the secondary at 10% with sulfur maybe just a typo I have no idea 
![sagmill issues](https://cloud.githubusercontent.com/assets/12303744/7524488/5c000b42-f4d0-11e4-9ba6-f346ea2e6156.png)

**Comment by MatthiasMann** [comment]
what is powdered coal - and why do you need it?

**Comment by TheJulianJES** [comment]
I guess he means Coal Powder.

**Comment by Joesalago** [comment]
yep... meant coal powder my bad

**Comment by tterrag1098** [comment]
coal powder is equivalent to every other "coal dust" out there. There is no reason to specifically need the EnderIO version.

**Comment by Joesalago** [comment]
thanks for the help guys/gals
