### ISSUE TITLE
bug with the sag mill

### ISSUE THREAD

**Issue by isaacBD** [SleepyTrousers/EnderIO#2445]
Hi, 
I'm playing in the direwolf20 modpack (v.1.7) and the sag mill seems not working with the vanilla ores.
Has someone a solution ? ;)
Thank you

**Comment by tjsd** [comment]
seems not to be working is a rather vague description. Can you explain what happens when you put in a vanilla ore, does it happen for all vanilla ores? Try making a creative world and try every ore.

No matter what the problem is, it must be relater to the pack and not Ender IO itself.

**Comment by isaacBD** [comment]
So it just happens nothing ^^ , the ore isn't grinded. But I think it's a problem of the server because it works perfectly in soloplayer.  But if you know what I have to change in the server files  I would be vers grateful.

**Comment by tjsd** [comment]
A wild guess is that there is something wrong with the config files. My advice is to delete the Ender IO folder from /configs/ and let it regenerate on server boot.
