### ISSUE TITLE
more EnderIO.cfg typos

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2447]
Line 526: "The BaulesType the magnet" should be "The BaublesType of the magnet"
Line 566: "This should match the with OpenBlocks" -> "This should match with OpenBlocks"
Line 940: "travelled" should be "traveled"
Lines 937, 940: "Staff of the Traveling" should be "Staff of Traveling"

**Comment by ajloveslily14** [comment]
mate this is a easy fix, why not just make a PR yourself? :blush:

**Comment by BillH1949** [comment]
Because it's not my code and I don't know the procedure?

**Comment by HenryLoenwind** [comment]
"The BaublesType the of magnet should be." ???

**Comment by BillH1949** [comment]
From https://github.com/SleepyTrousers/EnderIO/blob/b0783a22913f709114a691a12a55aee04472c3c5/src/main/java/crazypants/enderio/config/Config.java, line 1063:
`"The BaulesType the magnet should be, 'AMULET', 'RING' or 'BELT' (requires Baubles to be installed and magnetAllowInBaublesSlot to be on)").getString();`

vs.

"The BaublesType of the magnet should be, 'AMULET', 'RING' or 'BELT'..."
