### ISSUE TITLE
Machine fps spikes

### ISSUE THREAD

**Issue by menglish59** [SleepyTrousers/EnderIO#2449]
Multiple people on our server are having issues with ender io machines causeing fps spikes when near them.  Spikes go away when machines are removed and not noticed anything with machines from other mods

**Comment by tjsd** [comment]
Please post forge version and ender io version.
Also a list of machines that causes the issue helps in trying to replicate.
A full list of mods or pack name also helps.

**Comment by tterrag1098** [comment]
Screenshot as well...

**Comment by menglish59** [comment]
Forge version is 1291

Tested with SAG mill, alloy furnace and stirling gen

Pack is hatpack (mod list: http://www.hatfilms.co.uk/topic/10494-hat-pack-v4-modlist/)

The setup was simply a stirling gen next to the sagmill or alloy furnace.  From other players on the server it seems it is occuring with any ender io machines.  Dont have the slightest idea why its happening though :/

**Comment by tterrag1098** [comment]
1. That mod list shows no versions

2. What were you fueling the Stirling generators with?

**Comment by menglish59** [comment]
Updated that link with mod versions

The stirling gen was running on coal, however tested of a big reactor and had the same problem.  It causes the spikes when the block is placed (seems to cause spikes but to a lesser extent when not powered, worse spikes when powered and running, I drop from 150fps to 30-40 when placed and down to 0 for a few seconds at a time when powered)

**Comment by tterrag1098** [comment]
First off I would recommend against using unstable dev builds in a popular public pack, you are asking for trouble.

I will look into this issue soon.

**Comment by menglish59** [comment]
Thanks for the help so far.  Some extra info for you, tested with the current pack in single player and had no issues with it.

When running on a server (iv'e been using the shift f3 pie chart) I go from 4-5% tick speed which increases by ~5% for every machine placed.  Had someone with a lower end machine test it and they started on about 35-40% with a 25% increase for each machine placed.

Both the server and the client are using forge 1291.

We had no problems in a previous version of the pack (running ender io 329)

I shall try and see what version the issue appears and let you know

**Comment by tterrag1098** [comment]
If you could revert to the latest official release (on curse) and try to
reproduce that would be helpful.

**Comment by menglish59** [comment]
Im not able to get on our dev server for the moment to test with the lastes offical.

However one of our players noticed this in the ftb client console
 http://pastebin.com/kXzNGLDe
The client console loops that error when the machine is placed and stops when removed.

Hope this is of help, i'll test with 367 asap!

**Comment by MatthiasMann** [comment]
This is has been fixed already in EnderIO 2.3 beta build 373 or newer.

**Comment by menglish59** [comment]
Now I feel somewhat embarresed....

Seems when I added the mods versions I was looking at the files for the next pack patch.... not the files currently being used.

Really sorry for wasting your time somewhat, but a huge thank you for your help!
