### ISSUE TITLE
crash with ex astris

### ISSUE THREAD

**Issue by jacky8399** [SleepyTrousers/EnderIO#2450]
I was trying to insert some cobblestones when it crashed. I am using the newest versions of ex nihilio, ex astris and also ender io.
the crash report given:
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2015/5/9 下午 6:38
Description: Exception in server tick loop

java.lang.NoSuchMethodError: exnihilo.registries.HammerRegistry.registered(Lnet/minecraft/item/ItemStack;)Z
	at ExAstris.Block.TileEntity.TileEntityHammerAutomatic.func_102007_a(TileEntityHammerAutomatic.java:315)
	at crazypants.util.ItemUtil.doInsertItem(ItemUtil.java:89)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertItem(NetworkedInventory.java:265)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertIntoTargets(NetworkedInventory.java:226)
	at crazypants.enderio.conduit.item.NetworkedInventory.doTransfer(NetworkedInventory.java:178)
	at crazypants.enderio.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:151)
	at crazypants.enderio.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:98)
	at crazypants.enderio.conduit.item.ItemConduitNetwork.doTick(ItemConduitNetwork.java:208)
	at crazypants.enderio.conduit.item.ItemConduitNetwork.access$100(ItemConduitNetwork.java:23)
	at crazypants.enderio.conduit.item.ItemConduitNetwork$InnerTickHandler.tickEnd(ItemConduitNetwork.java:230)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:47)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:35)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_104_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 120131472 bytes (114 MB) / 1572339712 bytes (1499 MB) up to 1572339712 bytes (1499 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1536M -Xms1536M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.141.1403 Minecraft Forge 10.13.3.1403 88 mods loaded, 87 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.141.1403} [Forge Mod Loader] (forge-1.7.10-10.13.3.1403-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1403} [Minecraft Forge] (forge-1.7.10-10.13.3.1403-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.106} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.106-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	deconstruction{2.2.5} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.5].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv2-stable-1} [Applied Energistics 2] (appliedenergistics2-rv2-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	autopackager{1.5.2} [AutoPackager] (autopackager-1.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bdlib{1.7.0.70} [BD Lib] (bdlib-mc1710-1.7.0.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.4.13} [BuildCraft] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.4.13} [BC Transport] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.4.13} [BC Silicon] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.4.13} [BC Builders] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.4.13} [BC Energy] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.4.13} [BC Factory] (buildcraft-6.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderIO{1.7.10-2.2.8.367} [Ender IO] (EnderIO-1.7.10-2.2.8.367.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.4.build939} [Tinkers' Construct] (TConstruct-1.7.10-1.8.4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	exastris{MC1.7.10-1.16-32} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	extracells{2.2.68} [ExtraCells] (ExtraCells-1.7.10-2.2.69bNIGHTLY.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraUtilities{1.2.4a} [Extra Utilities] (extrautilities-1.2.4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mystcraft{0.11.3.00} [Mystcraft] (mystcraft-1.7.10-0.11.3.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-513.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	simplyjetpacks{1.4.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SolarFlux{1.7.10-0.5b} [Solar Flux] (SolarFlux-1.7.10-0.5b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Torcherino{2.1s} [Torcherino] (Torcherino-1.7.10-2.1s.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ttCore{MC1.7.10-0.1.0-67} [ttCore] (ttCore-MC1.7.10-0.1.0-67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wailaplugins{MC1.7.10-0.0.1-14} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	YABM{1.0.6} [Yet Another Backup Mod] (YABM-1.7.10-1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	zcraftingmanager{1.1.0} [Crafting Manager] (zCraftingManager ALPHA 1.0.17 mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	zcraftingmanagercore{1.1.0} [Crafting Manager Core] (minecraft.jar) Unloaded->Disabled
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.2-262
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.0.0-122
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-1.jar
		* BuildCraftAPI|blueprints (1.2) from buildcraft-6.4.13.jar
		* BuildCraftAPI|boards (1.0) from buildcraft-6.4.13.jar
		* BuildCraftAPI|core (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|events (1.0) from buildcraft-6.4.13.jar
		* BuildCraftAPI|facades (1.0) from buildcraft-6.4.13.jar
		* BuildCraftAPI|filler (3.0) from buildcraft-6.4.13.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-6.4.13.jar
		* BuildCraftAPI|gates (4.0) from buildcraft-6.4.13.jar
		* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|power (1.3) from buildcraft-6.4.13.jar
		* BuildCraftAPI|recipes (2.1) from buildcraft-6.4.13.jar
		* BuildCraftAPI|robots (1.0) from buildcraft-6.4.13.jar
		* BuildCraftAPI|statements (1.0) from buildcraft-6.4.13.jar
		* BuildCraftAPI|tiles (1.1) from buildcraft-6.4.13.jar
		* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|transport (4.0) from buildcraft-6.4.13.jar
		* ChiselAPI (0.0.2) from Chisel2-2.3.10.37.jar
		* ChiselAPI|Carving (0.0.2) from Chisel2-2.3.10.37.jar
		* CoFHAPI (1.7.10R1.0.0) from extrautilities-1.2.4a.jar
		* CoFHAPI|block (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHAPI|core (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHAPI|energy (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.367.jar
		* CoFHAPI|fluid (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHAPI|inventory (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHAPI|item (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHAPI|tileentity (1.7.10R1.0.4) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHAPI|transport (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHAPI|world (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHLib (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHLib|audio (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHLib|gui (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHLib|gui|container (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHLib|gui|element (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHLib|gui|slot (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHLib|inventory (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHLib|render (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHLib|render|particle (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHLib|util (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHLib|util|helpers (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHLib|util|position (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
		* CoFHLib|world (1.7.10R1.0.0B8) from CoFHLib-[1.7.10]1.0.1-151.jar
		* CoFHLib|world|feature (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.367.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.367.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.367.jar
		* IC2API (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* MystcraftAPI (0.1) from mystcraft-1.7.10-0.11.3.00.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|carts (1.3.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|core (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|signals (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.6.1.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['jacky8399'/246, l='Test World Mod Millenaire-less', x=168.82, y=64.60, z=-141.68]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MatthiasMann** [comment]
That is not an EnderIO bug - the crash happens within ExAstris/ExNihilo - probably incompatible versions.

**Comment by jacky8399** [comment]
lel i found out that ex nihilo updated without updating the forum post
