### ISSUE TITLE
Lamps + Tile Ents = Performance Issue

### ISSUE THREAD

**Issue by SirWilli** [SleepyTrousers/EnderIO#2451]
hey,

is there any way that the lamps get changed that they no longer spawn tile ents to create the light. Thaumcraft also changed the arcane lamps to improve the performance.

Quote out of the Thaumcraft Changelog:
> 4.2.3.1
> - glimmers of light produced by arcane lamps are no longer tile entities and do not produce particle FX anymore.

**Comment by MatthiasMann** [comment]
The powered lights have already been rewritten - which version are you using?

**Comment by SirWilli** [comment]
Currently EnderIO-1.7.10-2.2.8.367

**Comment by MatthiasMann** [comment]
they have been rewritten in 2.3 beta build 377

**Comment by SirWilli** [comment]
Oh ok, great. Do you know where I can find the dev builds?

**Comment by SirWilli** [comment]
Ah ok thanks.
