### ISSUE TITLE
Ender IO Conduits - Performance

### ISSUE THREAD

**Issue by Sir-Will** [SleepyTrousers/EnderIO#2452]
hey,

would it be possible to change the tile entity conduit bundles to not tick like IC2 it does? This would increase the performance enormous.

**Comment by MatthiasMann** [comment]
I already started to remove some parts of the ticking - but the redstone conduits need a rewrite to finish this.

**Comment by SirWilli** [comment]
Great, I hope you will do more improvements as 80% of all tile ents are conduits.

**Comment by MatthiasMann** [comment]
Well - that won't change.

**Comment by tterrag1098** [comment]
Yes, conduits already do this for the most part. The TE ticks are used for per-block things, such as extracting fluids, etc.

**Comment by beringtom** [comment]
"could" this be the culprit to major server lag if you got say, 10k+ Ender Energy Conduits spread over an area of say, 2.5k x 2.5k? :)

**Comment by MatthiasMann** [comment]
@beringtom Well - 10k is a lot - but a Opis report or VisualJVM would help to give you an answer.
