### ISSUE TITLE
Top texture of reservior is flipped... EIO 2.3.0.377

### ISSUE THREAD

**Issue by ate0ate** [SleepyTrousers/EnderIO#2454]
Its very minor of course, but the top texture of the reservior is flipped once the multiblock is formed...

http://imgur.com/S8yUMfZ

**Comment by tterrag1098** [comment]
Interesting, I do not see this happening. Could you try with today's build?

**Comment by HenryLoenwind** [comment]
Are you using a texture pack?

**Comment by ate0ate** [comment]
Okay, after further testing I really don't get it. I am using today's build and no texture pack. At first I could not replicate the bug either, but I've narrowed it down to only occurring in certain chunks. I have no idea why, but it happens in some chunks and not in others. Here's an example...

http://imgur.com/w7yGt95

**Comment by tterrag1098** [comment]
I went to your exact position and recreated your screenshot. As you can see, there is no issue:

![](http://puu.sh/hHy5g.jpg)

I suspect another mod is causing this issue. What other blocks do you have in the chunk?

**Comment by ate0ate** [comment]
An EIO sag mill, alloy smelter, and capacitor bank along with a mekanism digital miner, eloctrolytic seperator and hydrogen generator. I'll play around with some stuff and see if I can come up with anything more. Thanks tterrag.

**Comment by tterrag1098** [comment]
Hmm I might know the cause of this. One moment.

**Comment by tterrag1098** [comment]
Yes, this is mekanism, caused by this code https://github.com/aidancbrady/Mekanism/commit/09ba6fd8b465ee50e16c2fc0236b9e884edf8543

See this issue: https://github.com/aidancbrady/Mekanism/issues/2617
