### ISSUE TITLE
Game crashing when fluid goes inside conduits

### ISSUE THREAD

**Issue by jmfe10** [SleepyTrousers/EnderIO#2457]
My modpack crashes when I place a fluid conduit to extract liquid from an aqueous accumulator.

I observed that when i place it on an empty accumulator it doesn't crashes but with something inside instantly the game closes and i can't load my world.

**Comment by MatthiasMann** [comment]
Mod version and crash log

**Comment by jmfe10** [comment]
It's the EnderIO-1.7.10-2.2.8.367 and here is the crash log:
![crash1](https://cloud.githubusercontent.com/assets/12219971/7554202/550c3564-f6f5-11e4-8dd4-8d97c4fa46d3.png)
![crash2](https://cloud.githubusercontent.com/assets/12219971/7554203/55127f50-f6f5-11e4-9073-6a66d748a1d5.png)
![crash3](https://cloud.githubusercontent.com/assets/12219971/7554204/551a97c6-f6f5-11e4-8250-954c36d3c682.png)
![crash4](https://cloud.githubusercontent.com/assets/12219971/7554205/551edf84-f6f5-11e4-9b88-0e84cbf78c85.png)
![crash5](https://cloud.githubusercontent.com/assets/12219971/7554206/5520568e-f6f5-11e4-87ea-cac6304797d4.png)
![crash6](https://cloud.githubusercontent.com/assets/12219971/7554207/552b325c-f6f5-11e4-9d42-0db6faf661c3.png)
![crash7](https://cloud.githubusercontent.com/assets/12219971/7554208/552d1f36-f6f5-11e4-8b30-c9c392323bb3.png)
![crash8](https://cloud.githubusercontent.com/assets/12219971/7554209/55354012-f6f5-11e4-8bbc-0af3b3e4ae7f.png)

**Comment by MatthiasMann** [comment]
... use a paste site for the log next time ...

You use Optifine - that is not supported. Try without Optifine.

**Comment by jmfe10** [comment]
Sorry i'm new here at the site. But what do you recomend to use for a better performance? My computer isn't so good...

**Comment by iTraumatik** [comment]
@jmfe10  If you havent tried Fastcraft by player .  Im using it with ender io and about 220 other mods and works good.
