### ISSUE TITLE
Recipes don't use the Ore Dictionary for Gears

### ISSUE THREAD

**Issue by Xee1** [SleepyTrousers/EnderIO#2459]
For recipes that uses Basic Gear(registered with gearStone) , I can't use other gearStone (For example Stone Gear from Buildcraft).

**Comment by Velandil** [comment]
Basic Gears cannot be crafted like this: http://ftbwiki.org/Basic_Gear.
Instead I get Stone Gears like this: http://ftb.gamepedia.com/Stone_Gear_%28BuildCraft%29

**Comment by tterrag1098** [comment]
@Xee1 Basic gears are not the same as stone gears. They are crafted differently.

**Comment by Xee1** [comment]
Oh ok, sorry! Thanks for answer
