### ISSUE TITLE
Conduit Button

### ISSUE THREAD

**Issue by RlonRyan** [SleepyTrousers/EnderIO#2462]
Vanilla levers and buttons are great and all, but at times they can feel a bit... **Unsightly**

That's why I propose the addition of an EnderIO variant of the button.

Features:
- Paintable or Illuminating, matching the color of the utilized red stone channel.
- Toggleable.

Now these buttons are not designed to replace the conduit switch, which has a place of it's own, rather assist those of us who use EnderIO to make everything nice and pretty.

Sure, these sound a bit like the restone illumar buttons from redpower..., but those come from an inferior mod!

**Comment by notchriss** [comment]
You may want to look into buttons from Carpenter's Blocks mod, they are "paintable" in a sense, just not togglable but I don't think buttons should be togglable, that just would add confusion. You can ofcourse make any button effectively togglable with redstone logic
