### ISSUE TITLE
Soul Vial and stored Items vanishing.

### ISSUE THREAD

**Issue by SkyKadet** [SleepyTrousers/EnderIO#2463]
Hello. This one is really strange.
I will lay it all out for you.
In a private server, I made an EnderIO Enchanter, a Soul Binder, a Soul Vial, a Vibrant Crystal, A spell Book and an Angel Ring.
My plan was to apply 'Soulbound I' to the Angel ring. I got to the step where I needed the soul of an endermen. So I placed my Angel ring, Vibrant Crystal and Spell book in a vanilla chest for safe keeping while I ventured off to find an enderman to fill the vial. After finding one (about 300m from my base) and captureing it's soul in the vial, I returned to base to finish Soulbinding the Angel ring. 
When I went to retrieve the three items I left in the chest, much to my despair, they all where gone! Nothing else in the chest was missing, just those three items.

So, the next day, I repeated the same exact thing, however, I didn't have the angel ring yet, and this time I put the spell book and vibrant crystal in my ME drive. I went off, and captured an enderman's soul and returned. Once again, I went to retrieve the items I had just deposited in my ME Drive, and they were gone! 

It Appears, to me, that there is some adverse connection with the last items placed in a storage device, and the capturing of a soul using a soul Vial.

**Comment by tterrag1098** [comment]
Server you say...are you sure you were not just stolen from? Or this is an AE bug?

**Comment by SkyKadet** [comment]
No, It is just Me my brother and my Nephew. None of whom were online when it happened. Also, the first time it happened, the vanished items were placed in a vanilla 'minecraft' chest.

**Comment by MatthiasMann** [comment]
Could be a corrupted chunk - check your log files for any errors/warning.

**Comment by tterrag1098** [comment]
There is zero possibility that the missing items were caused by a soul vial...that is a ridiculous conclusion. A thousand more things are more likely. Someone took it. A chunk is corrupted. A bug in another mod. etc.
