### ISSUE TITLE
Ender IO Sag mill and Applied Energistics quartz recipe changes not sticking.

### ISSUE THREAD

**Issue by Virezz** [SleepyTrousers/EnderIO#2464]
Hi, 

Im changing the config option in SAGMillRecipes_Core.xml
Problem is the recipe changes doesnt stick.
like recipe i want it to have:

    <recipe name="CertusQuartzCrystal" energyCost="2400">
      <input>
        <itemStack oreDictionary="crystalCertusQuartz" number="2" />
      </input>
      <output>
        <itemStack oreDictionary="dustCertusQuartz"  />
        <itemStack oreDictionary="dustCertusQuartz" chance="0.1" />
      </output>
    </recipe>

when i save it and starts the game it changes to this:

    <recipe name="CertusQuartzCrystal" energyCost="2400">
      <input>
        <itemStack oreDictionary="crystalCertusQuartz" number="2" />
      </input>
      <output>
        <itemStack oreDictionary="dustCertusQuartz" chance="0.1" />
      </output>
    </recipe>

so it doesnt keep the one Itemstack output
using APPLIEDENERGISTICS2-RV2-BETA-31.jar, ENDERIO-1.7.10-2.3.0.375_BETA.jar from the ATlauncher with forge 1401

The recipe shows with 1 certusquartz crystal to 1 certusquartz dust in the ae2 hand cranked grinder and in TE's pulverizer so thats correct

**Comment by eduardog3000** [comment]
Don't change `SAGMillRecipes_Core.xml`, change `SAGMillRecipes_User.xml`.

**Comment by 6210classick** [comment]
you need to add it to SAGMillRecipes_User.xml not the core file
