### ISSUE TITLE
Farming station side config GUI crash

### ISSUE THREAD

**Issue by INSANEMODE** [SleepyTrousers/EnderIO#2465]
http://paste.ee/p/zDkyA
When i open the farming station and click the Configuration IO gear, i crash.

the crash report seems to indicate an unsupported function when rendering the GUI (around line 520 or so).

this happens to me in the 2.3 beta, as well as the last stable version for 1.7.10.

**Comment by HenryLoenwind** [comment]
Seems your GPU driver doesn't support OpenGL 1.4. What GPU do you have in your system?

**Comment by tterrag1098** [comment]
@CrazyPants Why are we using non-GL1.1 compatible methods?

**Comment by CrazyPants** [comment]
Didn't you tell me earlier we could even use shades? ;-)

**Comment by tterrag1098** [comment]
Well there would be a config if we did :p

**Comment by tterrag1098** [comment]
Unfortunately this will not be fixed, you can avoid the issue by not using the configure GUI and configuring with the wrench. Any configure GUI will crash you, on any machine, because of your severely outdated graphics.
