### ISSUE TITLE
[Suggestion] Add compatibility with Fluid Patterns in Filters

### ISSUE THREAD

**Issue by tgstyle** [SleepyTrousers/EnderIO#2466]
ExtraCells 2 has fluid patterns for managing fluids in an AE2 ME. Would it be possible to allow the fluid patterns to work with filters on fluid conduits?

**Comment by MatthiasMann** [comment]
Ender Fluid conduits have filters.

**Comment by tgstyle** [comment]
Correct. This is to allow Fluid Patterns to set a filter like a bucket does.

**Comment by tterrag1098** [comment]
A quick look at the extra cells repo tells me there is nothing in the API
for this.

**Comment by tgstyle** [comment]
Well that sucks...

**Comment by tgstyle** [comment]
Just to make sure you checked EC2 repo not the EC repo?

**Comment by tterrag1098** [comment]
Yes
