### ISSUE TITLE
ProjectRed Not Gate + Insulated Redstone conduit + piston + timer = odd on/off flickering

### ISSUE THREAD

**Issue by rezonant** [SleepyTrousers/EnderIO#2467]
I noticed this back in the 1.6 versions as well but EIO for 1.7 was well underway and much different by that point. My versions: Modpack is CrackPack (Minecraft 1.7.10) with ProjectRed 1.7.10-4.5.7.58 and EnderIO 1.7.10-2.2.6.317.

An uninverted NOT gate (so, emitting redstone) into an insulated redstone conduit, into a piston, with the device ends set to In/Out. Meanwhile, feed a ProjectRed timer into another side of the piston. While the piston stays extended when the conduits are the only redstone source, when the pulse from the timer hits the piston the signal drops for a tick or so, and the piston will "flicker" into off state and then back on. Issue does not occur when an activated lever signal is passed into the conduit instead of the Not gate (while the timer is still feeding a signal in) nor when ProjectRed wire is used, nor when vanilla redstone is used (and there are no insulated redstone conduits involved). 

And o/ @CrazyPants and @tterrag1098! Long time no see!

EDIT: I previously didn't realize the timer was affecting the block :-B The flicker only occurs when the timer fires a pulse.

**Comment by MatthiasMann** [comment]
Update EnderIO - 2.2.8 build 367 is the latest released version.
