### ISSUE TITLE
[BUG] EnderIO & Mekanism

### ISSUE THREAD

**Issue by spannerman79** [SleepyTrousers/EnderIO#2471]
Error;
[05:20:42 ERROR]: The mod EnderIO (Ender IO) requires mod versions [Mekanism@[7.0,8.0)] to be available
[05:20:42 ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.MissingModsException:
Missing Mods:
        Mekanism : [7.0,8.0)

Mekanism is already present;

EnderIO-1.7.10-2.2.8.379.jar
Mekanism-1.7.10-8.1.2.229.jar
MekanismGenerators-1.7.10-8.1.2.229.jar
MekanismTools-1.7.10-8.1.2.229.jar

EnderIO-1.7.10-2.2.8.367.jar doesn't have this issue

**Comment by tterrag1098** [comment]
This is *NOT AN ERROR*. There is a reason it requires Mekanism 7 explicitly.

**Comment by tgstyle** [comment]
Instead of the dependency, can't gas conduits just be force disabled if Mekanism 8 is installed?

**Comment by zortag** [comment]
there was a problem with a major mod, a new release is out 5 hours ago and have a bigger issue... why do you not changed the mekanism api version before the last release? i hope you do it soon. i agree with tgstyle's idea at least

**Comment by MatthiasMann** [comment]
This was just a bugfix release - for existing mod packs. EnderIO 2.2.8 never supported Mek 8.
