### ISSUE TITLE
EnderIO 2.2.8.379 Needs Mekanism 7.0.8.0 to load

### ISSUE THREAD

**Issue by iTraumatik** [SleepyTrousers/EnderIO#2472]
I have Mekansim 8.1.2.229 and generators and tools of same version(the recommended build on a's website.)   Minecraft doesnt load because of this.

**Comment by spannerman79** [comment]
I already reported this on #2471 and it was closed

**Comment by iTraumatik** [comment]
thanks , i just checked and didnt see 2471 on the list.  But thanks.

**Comment by spannerman79** [comment]
I suggest (at the moment) getting http://ci.tterrag.com/job/EnderIO/378/ @iTraumatik

**Comment by iTraumatik** [comment]
@spannerman79  TY for the link and understanding.  Loading now.

**Comment by tterrag1098** [comment]
@iTraumatik Mekanism v8 broke the Gas API, see #2110 (And all the referenced issues...there's a lot). 

You are free to use dev builds but know that they are often unstable and could break your world.

**Comment by spannerman79** [comment]
From memory @tterrag1098 it was 8.1.2.229 Mekanism that changed the fluid registry.
I *think* 8.1.1.228 was before Forge 1355

**Comment by iTraumatik** [comment]
TY.  just read it all and will be wary with the issues.  I am aware of the issues using dev builds and have been aware of that also.  Kind of use to mods breaking stuff , even the recommended builds so its cool.

**Comment by tterrag1098** [comment]
@spannerman79 That is not the part that matters, *ALL* v8 versions have the new Gas API, which is not backwards compatible.

**Comment by spannerman79** [comment]
Well I did a quick little FRAPS and upped it to youtube @tterrag1098 https://youtu.be/wAKXEBEmT78

There is a bug where if the Gas Conduit already has gas in it you cannot place down an empty EnderIO gas conduit unless its empty but that's manageable (378)

**Comment by spannerman79** [comment]
Thank you @tterrag1098 for the latest (308) release for EnderIO ( http://minecraft.curseforge.com/mc-mods/64578-ender-io/files/2238336 ).

I didn't want to create a new issue as there was no need to :)
