### ISSUE TITLE
newest ender IO looking for dated Mekinism 

### ISSUE THREAD

**Issue by ShawnRHayes** [SleepyTrousers/EnderIO#2473]
the Recommended DL for Mekinism is 8.1.2.229

**Comment by TheJulianJES** [comment]
#2472

**Comment by ShawnRHayes** [comment]
so I am confused , the Gas conduit was created for Mekinism and now that it has upgraded its Gas api and added more content along with it we have to downgrade instead of the " broken conduit " getting disabled ???

**Comment by MatthiasMann** [comment]
The gas conduit is not broken - it is only compatible with Mek 7 - which is required for existing mod packs.
EnderIO 2.3 (currently in beta) will be compatible with Mek 8.

**Comment by ShawnRHayes** [comment]
ahh ok EnderIO 2.3.0.378 i missed the numbering , 2.2 / 2.3
