### ISSUE TITLE
after update to latest version i get this crash

### ISSUE THREAD

**Issue by abdullamu** [SleepyTrousers/EnderIO#2476]
it was working fine but after updated to latest version of ender io im getting this crash disabling EE3 seems to fix it no crash after
http://pastebin.com/q7aKFBYv

**Comment by Staegrin** [comment]
I'm having the same crash. Updating ender io causes crash alongside ee3
crashlog:
http://pastebin.com/L9YLytnC
fml-client-latest:
https://gist.github.com/Staegrin/2b5d1630d76d48f73f45

**Comment by GodNero** [comment]
We are also managing to get this crash, though we are crashing against Extra TiC.
crashlog: http://pastebin.com/fmicTYZN

Forge version - 13.3.10.1401
Ender IO version - 2.2.8.380
Extra TiC version - 1.4.3

-Nero RR3 PackDev

**Comment by tterrag1098** [comment]
Fixed via a70b4805d00391a8e32b9bcb9a3c3578c8fa0a13 (fa729415b1ef2ba0bc4939019d6e8c58e76203fc)

**Comment by SkinHeadBaby** [comment]
how am i suppose to fix it with those codes

**Comment by Staegrin** [comment]
New version will be uploaded @SkinHeadBaby

**Comment by SkinHeadBaby** [comment]
ohh i thought i was supposed to fix it thanks

**Comment by Staegrin** [comment]
New version seems to have fixed it.
