### ISSUE TITLE
Dark Steel Shear recipe non-existent

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2480]
I see config options for dark steel shears, but it isn't available in game. dark steel, darksteel, shear, nothing in NEI.

**Comment by tterrag1098** [comment]
Huh?

![](http://puu.sh/hPGQb.jpg)

**Comment by MatthiasMann** [comment]
@Unrepentant-Atheist which version are you using?

**Comment by Unrepentant-Atheist** [comment]
Always the latest from Curse.

**Comment by MatthiasMann** [comment]
Numbers!

**Comment by Unrepentant-Atheist** [comment]
https://imgur.com/a/dgw1V

**Comment by MatthiasMann** [comment]
@Unrepentant-Atheist you need to look at the version number - the one you used was 2.2.8 - the dark steel shears are a new feature of 2.3 which is currently in beta and not yet on Curse.
