### ISSUE TITLE
[Feature Request] Upgrade conduits in-place

### ISSUE THREAD

**Issue by dgbonomo** [SleepyTrousers/EnderIO#2485]
When you have a lot of conduits built and wish to upgrade to a higher tier of the same type, it can get very challenging. I'm not sure how feasible it would be, but it might be nice if there were craftable conduit upgrades that you could right-click to upgrade an existing conduit in-place.  There may be other challenges with this (I didn't think it through much) but I just thought I'd at least get it out there.

**Comment by HenryLoenwind** [comment]
It may be possible to change the code that rejects placing a conduit if there already is one of that type there to "just" exchange them. I'll have a look, as I've had the same problems in the past ;)

**Comment by tterrag1098** [comment]
#2486 Was nonfunctional, this has been fixed via https://github.com/SleepyTrousers/EnderIO/commit/5a6a35ac144d286451ce33dd7a86d2b0f9a029e3 and is present in [build 402](http://ci.tterrag.com/job/EnderIO/402/).

**Comment by HenryLoenwind** [comment]
Any post-mortem why it worked for me and not others?

And BTW: You sure your want to spawn the item entity in the center of the conduit block? That way it has the tendency to go everywhere, just not where the player can pick it up...

**Comment by tterrag1098** [comment]
@HenryLoenwind in most circumstances, `placeAt` would not be null, thus it would always return `true` before ever getting to the replace code. Moving it to `onItemUseFirst` guarantees it to override other behavior.
