### ISSUE TITLE
Allow Enderman Heads added by Hardcore Ender Expansion to be used in Ender IO recipes

### ISSUE THREAD

**Issue by Proaxel** [SleepyTrousers/EnderIO#2487]
I'm playing the FTB Infinity pack 1.5.0, with some mods I updated, disabled, or added manually. One of those is Ender IO, which is manually updated to the latest version. I also have Hardcore Ender Expansion installed.  

Here's the problem: HEE adds its own Enderman Heads, and after a few hours or so of my Enderman farm running, I have gotten quite a few of HEE heads, but no Ender IO heads. That means that the Enderman heads that were added by HEE are overriding the Ender IO head drops.
The bad part is that those heads can't be used in recipes like the Soul Binder and the like! So lately I have been going to NEI Cheat Mode, deleting one HEE head and giving myself an Ender IO head in return.

An easy solution would be to add those heads to the "Ore dictionary", so they are allowed to be used in Ender IO crafting recipes.

**Comment by tterrag1098** [comment]
HEE heads do not override the EnderIO heads, I know this for a fact because I have played packs with both mods. EnderIO enderman heads are much rarer, and this is intentional to maintain balance. If you are not getting enough, you should upgrade your "The Ender" sword.
