### ISSUE TITLE
GasConduit = auto not working

### ISSUE THREAD

**Issue by Wolf68k** [SleepyTrousers/EnderIO#2488]
EnderIO 2.2.8.381 and Mekanism 8.1.2.229
S:isGasConduitEnabled=auto the Gas Conduit doesn't show up. Using true it works just fine.

**Comment by MatthiasMann** [comment]
EnderIO 2.2.8 is NOT compatible with Mekanism 8 (as they changed their API and it's not possible to support both versions).

Which means "auto" is working perfectly as it disabled the gas conduits.

**Comment by Wolf68k** [comment]
Mekanism 7 is way too old. And with out going to the Legacy Downloads the oldest is 8.0.1.198 and that's too old as well, and it still doesn't work.

If nothing else it would have been nice to informed about this in the change log that having to set it to true in the configs when using the latest Mekanism.

**Comment by HenryLoenwind** [comment]
You're right, I'll hop into my time machine, jump back to last year and put into the changelog: "When Mekanism will change their API to be no longer compatible with the Mekanism API Ender IO is programmed against, you have to do stuff."

**Comment by MatthiasMann** [comment]
Setting that config flag to true will not make EIO 2.2.8 compatible with Mek 8.x either.

You will need to update to the EnderIO 2.3 beta builds when you want to use gas conduits with Mek 8.

**Comment by Wolf68k** [comment]
Actually setting the flag to true does allow EIO 2.2.8.381 and Mekanism 8.x to work perfectly fine.
I've tested it, I wouldn't made my last post if I had not tested it or of I had and it didn't work.
I can take screen shots to show you proof if you want.
In the mean time; my test set up was Mekanism Electric Pump over a water source, Rotary Condensentrator turns water into oxygen, then a gas tank. Connections: pump and R.Con. using EIO Ender Fluid and Energy Conduits. R.Con to Gas Tank using EIO Gas Conduit. I even use an EIO creative capacitor bank to power it.

**Comment by tterrag1098** [comment]
Yes, that's not what we are talking about though. Setting it to true will
not enable gas conduits. This is *so that* Mek 8 will not crash with them.

**Comment by Wolf68k** [comment]
Setting it to true DOES enable gas conduits. The recipe works and they work as they should.
The most list of the test instance I've been testing with: http://i.imgur.com/KkUcGFK.png
With the gas conduit in place filling the gas tank: http://i.imgur.com/pOcpGy1.png
With the gas conduit filled with oxygen because the tank is fill: http://i.imgur.com/I8EMibK.png
Now other than a few other mods truly only EIO and Mek are in this instance. However I've also tested with the full pack I'm working with and again it still works just fine.

I'm not trying to rub anyone the wrong way or get on anyone's bad side or whatever. I truly enjoy the mod and truly enjoy helping people find problems and sort them out. But I wouldn't have started this thread if I hadn't tried every possible thing I can think of to show that there is a problem with either the setting that should be working but isn't or that there should have been a note to pack makers to manually set it to true.

If after everything I've said, and now shown, you guys and you still don't believe me, try it for yourself.

And just in case it might matter; the test instance is running Forge 1403 and the pack I'm working with is running Forge 1388.

The only thing that's not working like it does with other conduits is the In/Out mode doesn't let you set anything for the Extract and Insert modes. Here I admit I never really messed with Mek and EIO enough in the past to see if that is normal or not.

Now if there some other reason that I'm missing that you guys say as to why the gas conduits in the above versions of the mods should not be working then please explain in detail what you mean.

The only crash I ever got was with EIO 379 and the same Mek listed above. That's when I got this http://i.imgur.com/E1cqzz4.png
Now to me that says it need Mek 7.0 or 8.0. At first I thought it something I or MultiMC had done to mess up enabling Mek. It was after narrowing down the cause to EIO that I went for the 381 update, which according to it's change log didn't seem like enough of an reason for me to get since my pack doesn't have EE3 but I tried it anyway. It was after that and loading my test world to see gas conduits was missing that started all of this: my testing and this thread.

Please forgive me if I'm seem like a nuisance, that is not my intent. Just trying to help.

**Comment by MatthiasMann** [comment]
As has been pointed out several times - EnderIO 2.2.8 builds ARE NOT compatible with Mekanism *8*.

If you use the EnderIO 2.2.8 gas conduits with Mekanism 8 you risk a world corruption. This is the reason they are disabled when Mekanism 8 is detected.

**Comment by tterrag1098** [comment]
That screenshot should be impossible. Gas conduits force themselves off if
there is no "7" at the beginning of the version number.

**Comment by Wolf68k** [comment]
Ok, "risk a world corruption" an answer that makes sense to me. "Not compatible" in this case makes it sound like "does not work" or "can't be enabled" or anything along those lines. Like saying you cannot connect EIO energy conduits to IC2 machines, which is of course true. 
In this case it does work but comes with a risk.

However I would like to say that as far as I know, no one has complained about any world issues and I'm sure there are loads of people using the pack that do the Mek 4x or even 5x ore processing. Granted as of now not using 381 but it is EIO 2.2.8 and Mek 8.1x

 @tterrag1098 
Not sure what to tell you. Sorry? You're welcome? I don't know.

**Comment by HenryLoenwind** [comment]
"No one has complained"? *We* had 18 issues for this so far. See #2110

**Comment by Wolf68k** [comment]
Ok fair enough. I meant no one at the forums where the pack I work on is at.
