### ISSUE TITLE
Compatability with current dev version of SuperMassiveTech?

### ISSUE THREAD

**Issue by Keridos** [SleepyTrousers/EnderIO#2489]
Currently EnderIO crashes with the latest SuperMassiveTech build from the jenkins (build 110) with this log: http://paste.ee/p/9e2Ni

**Comment by tterrag1098** [comment]
This is unavoidable, too many changes have been made to EIO. SMT will be
updated once this version of EIO is properly released.

**Comment by Keridos** [comment]
Ok

**Comment by Keridos** [comment]
Just a small question: Could you at least just disable the compat somehow so we can at least play with the 2 mods at the same time?

**Comment by tterrag1098** [comment]
The compat is in SMT, so for organizations sake, make an issue there.

**Comment by Keridos** [comment]
Ok
