### ISSUE TITLE
[Feature request] Electricraft conduit

### ISSUE THREAD

**Issue by notchriss** [SleepyTrousers/EnderIO#2490]
Hey, could you add conduits for electricraft electricity? They could be functionally exactly the same as Electricraft's wires (power loss, power split, etc) as long as we can bundle them together with other conduits and use Ender IO covers. Ender IO currently has the best conduit system by far, and since you added gas conduits and applied energistics conduits, I figured maybe you could support one more mod :) 

Electricraft by Reika: https://sites.google.com/site/reikasminecraft/electricraft

**Comment by beringtom** [comment]
Maybe just make the normal ender IO power cabels support the mod if it has an API to help, then we don't need another new cable ;)

**Comment by tterrag1098** [comment]
@beringtom That would be hard, considering the two power types are very separate (and allowing free conversion to RF would break the mod)

**Comment by notchriss** [comment]
Electricraft electricity work in a very different way from RF, I don't think it's a good idea to make them run on the same cables.

**Comment by Unrepentant-Atheist** [comment]
Everybody and their grandma need their own power generation system. KingLemming created RF for a reason...

**Comment by tterrag1098** [comment]
@Unrepentant-Atheist You really should try something before you discount it. Electrical Age is very neat, not "just another power system". It definitely does enough different to deserve its own system.

**Comment by notchriss** [comment]
I was talking about Electricraft by Reika, an addon to Rotarycraft, but what tterrag1098 still stands. The way shaft power/Electricity works is a huge part of mod's appeal and RF certainly wasn't created to destroy that (nor was it created to replace mana from Botania, essence from ArsMagica, et cetera et cetera).
