### ISSUE TITLE
Still having the I baubles item magnet issue

### ISSUE THREAD

**Issue by Nick-77ab2** [SleepyTrousers/EnderIO#2492]
is it going to be fixed or something? after that last report was abandoned I was very confused and still am as to if it's going to be fixed
(i'm just generally confused)

**Comment by tterrag1098** [comment]
I believe this sums it up? https://github.com/SleepyTrousers/EnderIO/issues/2352#issuecomment-95753443

**Comment by Nick-77ab2** [comment]
ok thats way more helpful
