### ISSUE TITLE
Coordinate Selector crashing when selecting Chisel blocks!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2493]
When I select blocks from Chisel mod, the game crashes: http://hastebin.com/ivinucaxex.coffee

**Comment by tterrag1098** [comment]
This has nothing to do with the block selected, it doesn't even check. How did you obtain this item? The NBT data seems corrupted (missing)

**Comment by Unrepentant-Atheist** [comment]
What do you mean, how did I obtain it? I crafted it in my Ars Magica 2 table. Ima going to try craft it on my Thaumcraft table and vanilla table. With and without shiftclicking.

I read somewhere, that sometimes NBT data get's kaput if you shiftclick craft something.

**Comment by tterrag1098** [comment]
Only in the AM2 table? Or any table?

**Comment by Unrepentant-Atheist** [comment]
Seems to be any table. Arcane Table from Thaumcraft, Vanilla Crafting Table too. As long as I don't shift+click craft, it works.
