### ISSUE TITLE
EnderIO conduit crash

### ISSUE THREAD

**Issue by Slimdude** [SleepyTrousers/EnderIO#2494]
Placing an EnderIO power conduit causes the following crash: http://pastebin.com/cSxykJUK.
The crash happened when trying to hook up power to a Mekanism machine.  I've posted the same information in the Mek forums to see if I can find a solution there. 

Minecraft info and affected mods:
- MC version 1.7.10
- Forge 1400
- EnderIO 2.3.0 383_beta (also tried the stable 2.2.8 381, but got the same crash)
- Mekanism 1.7.10-8.1.2.229 (latest version)

**Comment by tterrag1098** [comment]
Don't use optifine

**Comment by MatthiasMann** [comment]
You are using Optifine. Try without.
