### ISSUE TITLE
Free Global Wireless charging, Multiplayer server.

### ISSUE THREAD

**Issue by itanshi** [SleepyTrousers/EnderIO#2498]
http://youtu.be/95NTk9Ay7Gs for example.
https://github.com/CoFH/Feedback/issues/539

We're still doing tests but we're under the impression removing ender io wireless charger from the pack will fix it.

Edit: I think I misused the term 'free'. It draws from the power of the person that placed it.

**Comment by tterrag1098** [comment]
What version of EnderIO?

**Comment by itanshi** [comment]
2.2.8.367 (sky factory 2)

**Comment by itanshi** [comment]
I played with modsauce2 2.2.2.2 and have not had this issue, so I guess its fixed.
