### ISSUE TITLE
[Feature Request] XP Juice placeable fluid!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2504]
You already can take out buckets xpjuice out of tanks. You can't place it though. Which is too bad, because if you could, one could then convert between MFR mobessence fluid or openblock xpjuice fluid.

**Comment by 6210classick** [comment]
did you tried MFR Unifier ? as i recall immibs xpjuice can be turned to  MFR mobessence this way not sure about OB  MFR xpjuice though

**Comment by Unrepentant-Atheist** [comment]
I tried. Not working. I don't have immibis nor openblocks (anymore).

**Comment by tterrag1098** [comment]
This is intended, you cannot place OpenBlocks XP, so this could cause issues if you add/remove that mod (and the block disappears)
