### ISSUE TITLE
[BUG] Entity tracking errors caused by wither skeletons (incomplete separation of withers from skeletons) 

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2505]
paste:http://pastebin.com/Cup3ZtBW

I narrowed this down to the withers since during the entire time that MC was writing THIS log I was in the overworld since I was trying to put the finishing touches on my wither skeleton farm and only the withers cause this issue no other mobs do this.... (this never happened in the past without enderIO)

EnderIO v385*

*exists in just about all of the versions before this...

Edit: the only workaround I have found is to make sure to keep withers and skeletons as the same entity rather than different since withers are bugged as there were no more errors after changing withers to be the same as skeletons. My theory on why this is happening is that although separating the entities worked (sort of) Minecraft is trying to track withers as (I am not sure how to explain this) skeletons AND withers or in other words two entities in one if that makes sense,  I think that simply changing the "name" of the entity could solve this (WAILA and NEI etc. should show the name as wither skeleton but the enity's ID is changed) that way minecraft is not trying to track them as two entities in one. 

Another method to solve this that might work better if the first one doesn't is to override skeletons entirely that way minecraft doesn't even try to track them as two entities in one and leaves them separate as it no longer has any connection to the entities as they are now from enderIO and not from MC

P.S. I am still in the learning stages of the Java programming language so this could fail horribly.

**Comment by MatthiasMann** [comment]
Which EnderIO version?

**Comment by Ianaver** [comment]
my bad, latest atm: v385 (this exists in all of the versions that I know of....)

**Comment by itanshi** [comment]
there is an experimental config related to this iirc

**Comment by Ianaver** [comment]
@itanshi what does iirc stand for exactly? (no really, have no clue what it stands for)

**Comment by tterrag1098** [comment]
#1899

**Comment by Ianaver** [comment]
@tterrag1098 just curious, was my theory right?

**Comment by tterrag1098** [comment]
No, the internal name of our entity is different from vanilla, that is not the issue.

**Comment by Ianaver** [comment]
@tterrag1098 do you know what could cause this? no thaumcraft was installed at the time
