### ISSUE TITLE
ME Conduits do not connect to adjacent P2P Tunnels on server restart

### ISSUE THREAD

**Issue by predakanga** [SleepyTrousers/EnderIO#2506]
This is potentially a duplicate of #2028, but I think the issue experienced by @Mad-Virus (https://github.com/SleepyTrousers/EnderIO/issues/2028#issuecomment-86051965) and myself is different to the OP.

In short, if you have an ME Conduit connected to the tunnelled side of an AE2 P2P Tunnel (that is, the side that makes use of the tunnel, not the side that carries it), the conduit will be unable to reconnect after a server restart.

The issue can only be resolved by removing and re-placing the conduit or tunnel; using the wrench to adjust the conduit's inputs and outputs does not help, as the tunnel's direction is grayed out.

@MatthiasMann suggests in #2028 that the issue is due to AE2 not sending neighbour changed events - would it be possible to work around this by storing in the conduit's NBT (or wherever you store conduit settings - not too familiar with EIO source) that a conduit is attached to an AE2 device and on load, delay the connectivity check by a tick or two to allow the AE2 devices to initialize?

The issue occurs regardless of whether the conduit is inside a facade, and happens very regularly - almost every restart triggers the issue, though there are some rare instances where the conduits will reconnect with no problem.

Known Affected Versions:
EnderIO-1.7.10-2.2.8.367.jar (FTB Direwolf20 1.3.1 pack)
ENDER IO 1.7.10-2.2.8.349 (FTB Infinity 1.2.1 pack)

Screenshots
Pre-restart: ![2015-05-25_19 11 13](https://cloud.githubusercontent.com/assets/830645/7794898/b01f0110-0312-11e5-9518-b2b0f5fd9a76.png)
Post-restart: ![2015-05-25_19 11 40](https://cloud.githubusercontent.com/assets/830645/7794899/b0246f2e-0312-11e5-82d1-a4338f50a5b1.png)

As an SSP player, this is quite a pain - having to rewire hidden sections of my base on each reload is not very fun, which is why I suggest a workaround for now.

**Comment by 6210classick** [comment]
you could just use a normal AE cable to connect it to the tunnel and everything else is using the ME conduits

**Comment by tterrag1098** [comment]
Yes, #2028 is fixed in dev builds, but not in official release. This is indeed a duplicate.

**Comment by predakanga** [comment]
Fantastic, thanks :)
