### ISSUE TITLE
Conduit Facade does not make place block sound when placed (bug/request)

### ISSUE THREAD

**Issue by rrongol** [SleepyTrousers/EnderIO#2510]
Placing a conduit facade block does not make a place block sound.  Is this intentional or a bug?  I would prefer to have the sound if possible.  Breaking one does make the break block sound as expected.

EnderIO-1.7.10-2.3.0.385_beta

**Comment by tterrag1098** [comment]
Not a bug, just not implemented.

**Comment by tterrag1098** [comment]
I went ahead and redid most of the sound stuff for conduits, they should always play sounds now (and facades will play the sound of the painted block)
