### ISSUE TITLE
[Feature Request] TiCon AutoSmelt Farming Station Support?

### ISSUE THREAD

**Issue by ProRedHD** [SleepyTrousers/EnderIO#2511]
Would it be possible to add said feature?
Also if it is possible make sure to check if there is luck on the axe , because you get more charcoal that way in the "vanilla" ticon.

**Comment by tterrag1098** [comment]
We call the harvest methods on the item....This should already work

**Comment by ProRedHD** [comment]
Nope, not working Video: https://youtu.be/pRIyYFTaKDM
Using FTB Infinity 1.5.1, therefor EnderIO version 367.

**Comment by 6210classick** [comment]
he meant in the dev version AKA the new EIO 2.3 beta .

**Comment by tterrag1098** [comment]
No I didn't

**Comment by 6210classick** [comment]
@ tterrag1098 i thought this was implemented in the latest dev version am i wrong ?

**Comment by ProRedHD** [comment]
Sorry wrong button :(
