### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Aleksejus1** [SleepyTrousers/EnderIO#2513]
Hello, i with a few of my friends are setting up a server for our selves, and we wanted to use EnderIO in it, but when i launch the game i get this:
http://pastebin.com/TRh9w3NW

**Comment by tterrag1098** [comment]
Please try the latest version, you are out of date.

**Comment by Aleksejus1** [comment]
if the latest version is EnderIO-1.7.10-2.2.8.381.jar then i have indeed tried it, and the same thing happened, should i put the crashlog for it as well?
