### ISSUE TITLE
Power buffers behaving weirdly.

### ISSUE THREAD

**Issue by ClockworkGod** [SleepyTrousers/EnderIO#2515]
I have a big reactor creating 12k RF/t going into a capacitor bank and from there into green conduit. the capacitor bank is a double bank with the default values so it can output max of 50000 RF/t. I am trying to power a powered enderman spawner with a red capacitor in it. if I put a power buffer inline between the capacitor banks and the spawner, the spawner is power starved, the RF is definitely going into the buffer, but it is always empty, regardless of how much I let in/out via the GUI. The RF is just gone. if I remove the buffer and just use a hard connection, it can more than keep up just fine.

**Comment by MatthiasMann** [comment]
Which version of EnderIO - and can you attach a screenshot of the setup and also measure the conduits with the conduit probe please.

**Comment by ClockworkGod** [comment]
I am using the latest public release of enderIO, not the beta. I was tinkering around with it more last night and it seems like the powered spawner is the main cause. if I have hard line from the powered spawner to the capacitor bank, everything is fine, but if I have anything else in between, I get a problem, after the initial spawn of enderman, the spawner consumes it's entire buffer in less than a second and the power can never again keep up. I tried this with the buffer, like I said before, no matter the settings in the GUI, the spawner was always starved. I also tried it with a piece of cryo-cooled flux duct from thermal dynamics, it has an infinite throughput capacity so it should let through all that is needed, but again, same behavior of the spawner. The only way I got enough power to go to the spawner is with a direct connection of conduit. I will take some screen shots and post them asap.

**Comment by ClockworkGod** [comment]
![2015-05-28_22 54 47](https://cloud.githubusercontent.com/assets/8566920/7875625/8633f892-058d-11e5-997b-8d08ffecb251.png)
![2015-05-28_22 54 50](https://cloud.githubusercontent.com/assets/8566920/7875626/8634eed2-058d-11e5-8500-819fd1aed976.png)
![2015-05-28_22 55 02](https://cloud.githubusercontent.com/assets/8566920/7875628/863adcb6-058d-11e5-9c21-81a411b7becc.png)
Power goes into the top of the buffer and comes out the sides and bottom.

![2015-05-28_22 55 05](https://cloud.githubusercontent.com/assets/8566920/7875630/863d2264-058d-11e5-9ddc-76f3bffe02fa.png)
The buffer has it's default settings for power in/out.

![2015-05-28_22 57 09](https://cloud.githubusercontent.com/assets/8566920/7875627/8639ee28-058d-11e5-95db-9a3a2beda702.png)
The conduit probe readouts for the lines in order top to bottom and counter clockwise.

![2015-05-28_22 57 27](https://cloud.githubusercontent.com/assets/8566920/7875629/863bd94a-058d-11e5-9295-39c77acbc078.png)
The spawner starts out with a full internal buffer.

![2015-05-28_22 57 31](https://cloud.githubusercontent.com/assets/8566920/7875633/8645b35c-058d-11e5-9030-b83b01e52a9c.png)
During the first spawn wave power distribution keeps up with consumption.

![2015-05-28_22 57 59](https://cloud.githubusercontent.com/assets/8566920/7875632/864407e6-058d-11e5-9a77-9d95eaabf9d0.png)
After the first wave has spawned and about a third into the second wave, the internal buffer rapidly empties. From then on the power goes somewhere, but it's not into the spawner. and the buffer stays empty.

![2015-05-28_22 58 37](https://cloud.githubusercontent.com/assets/8566920/7875631/864267ec-058d-11e5-9c85-ea57ddfd9191.png)
The capacitor bank is set to out only, so the power isn't somehow making it's way back here.

**Comment by CrazyPants** [comment]
Matthias, I remember seeing a similar issue that was caused by the stored
power in a machine becoming negative I would check for that

**Comment by MatthiasMann** [comment]
I'll look into how the powered spawner uses power.
I don't think the stored energy levels of the EnderIO machines can go negative - the base classes handle that for every machine and I haven't seen any report for that yet.

**Comment by tterrag1098** [comment]
I think this issue is with the spawner. The energy handling on the buffers
is standard. We had kane_hart reporting a similar issue today in irc.

**Comment by MatthiasMann** [comment]
It's not the spawner - when the energy conduits are set to in/out on both the power buffer and on the cap bank and the power buffer to "none" - then the energy is oscillating between these and not going where it should.

To best solve this set the sides of the power buffer or the conduits how you want your energy to flow.

**Comment by ClockworkGod** [comment]
I had the capacitor bank set to out only, could the power be oscillating between the buffer and the conduits themselves?

**Comment by MatthiasMann** [comment]
hmm - not sure - try setting the sides explicitly
