### ISSUE TITLE
[Dev build] crash with extrautils

### ISSUE THREAD

**Issue by jacky8399** [SleepyTrousers/EnderIO#2517]
crash report: http://pastebin.com/pdb4drd9
i think this should work because it worked from direwolf20's forgecraft series
EnderIO-1.7.10-2.3.0.385_beta.jar

**Comment by CrazyPants** [comment]
This crash is coming from extra utilities. It appears baubles isn't found
when creating the angle ring

**Comment by tterrag1098** [comment]
Also #2352
