### ISSUE TITLE
[Request] Enhance texture pack posibilities by changing texture mappings

### ISSUE THREAD

**Issue by Fiirah** [SleepyTrousers/EnderIO#2518]
Currently a number of the machines with custom models draw all their textures from the same few files making it very difficult to make any texture pack more varied then the current plain grey gradients. 

For example the Combustion generator draws textures for it's top and sides from the standard machine sides texture and then tiles them, making it necessary for any machine textures to also tile.

**Comment by tterrag1098** [comment]
This has been changed in the dev builds
