### ISSUE TITLE
The Zombie Generator does not render in the Configure IO window

### ISSUE THREAD

**Issue by rrongol** [SleepyTrousers/EnderIO#2519]
The Zombie Generator does not render in the Configure IO window.  If its full of juice you just see a green fluid cube.  If its empty nothing renders.

EnderIO-1.7.10-2.3.0.385_beta

**Comment by tterrag1098** [comment]
This is due to it being a TESR...once we get the new model from @CyanideX (if there is going to be one) this can be changed, hopefully.

**Comment by CyanideX** [comment]
There will be one. :grin: Just need to clear up my schedule a bit.
