### ISSUE TITLE
Tessalator error with kinesis pipes and capacitor banks

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2520]
After FINALLY deciding to go and play around with Buildcraft, I saw that they moved to the RF api. I then set down a capacitor bank and started putting kinesis pipes down and a kinesis pipe is put down too fast and attached to the cap. bank, this weird thing happens.... to reproduce this put capacitor bank then (in my case; diamond kinesis pipe but other kinesis pipes achieve this affect too) and make sure it is attached to the capacitor bank, then really quickly put down more diamond (or any other kinesis pipe) and a wooden one quick too, a crash happens. You may need to try this several times as this is mainly caused by the speed of placement rather than the fact that the pipe is there. I tried this with thermal expansion and had no problems. If this error occurs you have to delete your world or use a backup as the tessalator error will crash your game every time the world is opened, so make sure it is not a world you have worked on for weeks if you try to reproduce this....

paste: http://pastebin.com/ErKPyA6F

edit: apparently even thermal expansion is effected. @KingLemming I guess your mod hates me too! XD

**Comment by Ianaver** [comment]
Closed (not enderIO's bug); must be some MC/Java derps that happen when conduits or pipes are placed too quick, not any mod's fault or bug. sorry for the useless report!

**Comment by MatthiasMann** [comment]
You have Optifine installed - tessalator related crashes are most likely caused by Optifine.

**Comment by Ianaver** [comment]
ok
