### ISSUE TITLE
(RARE) Conduit tessalator crash

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2521]
if conduits are placed down too quick on occasion a tessalator crash will occur and force you to delete your world as your mc will crash every time you open that world after inducing the error in that world.

refer to #2520 as it is similar except in this case it does this with conduits

**Comment by Ianaver** [comment]
closed; I think this is just some MC/java derps that happen and are not on any mod's end

**Comment by MatthiasMann** [comment]
Again - try without Optifine.

**Comment by Ianaver** [comment]
it stopped so..... yeah.... its just happens on occasion if I place the conduits too fast other than that its fine
