### ISSUE TITLE
 Could not spawn mod entity - Nether

### ISSUE THREAD

**Issue by Ryahn** [SleepyTrousers/EnderIO#2525]
From about line 52 down, it shows spamming of trying to spawn a mod entity in the nether. It has caused a few players to get a fatal error and disconnect.

http://pastebin.com/SxdSXGa8

**Comment by 6210classick** [comment]
what version are you using ?

**Comment by b0bst3r** [comment]
in enderIO.cfg changed the below to false and restart server:

    B:replaceWitherSkeletons=false
