### ISSUE TITLE
Recipes should use Ore Dictionary ingotDarkSteel

### ISSUE THREAD

**Issue by leagris** [SleepyTrousers/EnderIO#2529]
Crafting and Repair shall use Ore Dictionary names so it can use ingotDarkSteel from other mods.

With GregTech 5.08.18.jar maintained by @Blood-Asp, Dark Steel ingots are unified to gt:ingotDarkSteel, but these don't work for crafting Dark Steel Ball or repairing Dark Tools and Armour.

**Comment by MatthiasMann** [comment]
I don't think GT's dark steel is comparable to EnderIO's?

**Comment by leagris** [comment]
It is not, but Gregtech 5.08.18 unificate DarkSteel Ingots from EnderIO into gt:ingotDarkSteell.
I just opened a related issue https://github.com/Blood-Asp/GT5-Unofficial/issues/34 because until EIO can use Ore Dictionary names in recipes, it shall not default to unification.

**Comment by MatthiasMann** [comment]
Well - why should we allow oredict use for EnderIO specific ingots - just because they have the same name?

**Comment by leagris** [comment]
Currently EnderIO register ingotDarkSteel to the OreDictionary but does not use the OreDictionary name within recipes.
To have other mods to play nicely, either:
If DarkSteel can be produced/referenced by other mods
Then: Use OreDictionary name in recipes
Else: Register a distinct namespace.

Anyway, it seems illogical to register an OreDictionary Name and not make use of it.

**Comment by Blood-Asp** [comment]
GT tries to integrade as many mods as possible into it's material/tool system to allow deeper cross mod interaction.
While Dark Steel is allready in for quite some time, i only activated it's active usage a few versions back on request. 
The default unification taget not being EnderIO is my mistake and i will fix it soon. But it is right, that registering something in the oredic and not using oredic recipes makes no sense. If you do not allow materials of the same worth from other mods, then do not register it in the first place.

**Comment by tterrag1098** [comment]
Fixed via https://github.com/SleepyTrousers/EnderIO/commit/d98be8dd86e02b7ed40419ae01db27ee58063b7e
