### ISSUE TITLE
EnderIO crash on startup

### ISSUE THREAD

**Issue by Slimdude** [SleepyTrousers/EnderIO#2531]
I get this error when I try to start Minecraft. http://pastebin.com/i29qc53W.  Looks like the Staff of Travelling is causing a problem.  Could this be an ID conflict, or a problem with the latest version of Forge?

**Comment by MatthiasMann** [comment]
Upload the full log - seems one of your mods contains an incomplete version of the RF API

**Comment by b0bst3r** [comment]
Mek 8 pre-req is that it requires Cofhcore mod, add it and these go away.
