### ISSUE TITLE
Capacitor bank ..Again

### ISSUE THREAD

**Issue by bosto2** [SleepyTrousers/EnderIO#2533]
http://prntscr.com/7bz4i3
This occurs at times when i log onto while being near a capacitor bank.

**Comment by GauHelldragon** [comment]
What am I looking at here?

**Comment by bosto2** [comment]
Capacitor banks that spewed out countless of "Staff of power" witch is a item that

**Comment by MatthiasMann** [comment]
what is a "staff of power" - did you put these into the cap banks?

**Comment by b0bst3r** [comment]
bosto2 
1) Was the Staff of power in the cap bank eing charged?
2) Did you log out when the staff of power was still in the cap bank?
3) Did you break the cap bank at all (I don't see it)?
4) Are you therefore saying that:-

I inserted a Staff of Power in the cap bank, logged off, logged back in and there were dupes and dupes of Staffs laying around?

**Comment by bosto2** [comment]
1 Yes
2 Yes
3 No
4 well yes

**Comment by MatthiasMann** [comment]
Ok, let's start with the basics - which version of EnderIO ?

**Comment by bosto2** [comment]
@MatthiasMann 
It is a item from Draconic evolution the actual name is "Draconic staff of power" and it can be charged
Also EnderIO Version: 2.2.8.381

**Comment by bosto2** [comment]
Sorry that i cant give you that many details about what happen i just logged off and on and there ware a lot of duped items on the ground

**Comment by b0bst3r** [comment]
Cap bank - how many blocks, which cap bank was it?

**Comment by bosto2** [comment]
Vibrant capacitor bank and the amount does not matter happened to a friend to and he only had one while i had several

**Comment by TheJulianJES** [comment]
I guess chunkloading?

**Comment by bosto2** [comment]
It is partly chunk loading But do you chests spewing out duplications?
It can be fixed and it is on the EnderIO side
