### ISSUE TITLE
Teleporter kaput?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2534]
I'm trying to enter individual coordinates, without the coordinate reader, because I wanna teleport around and I can't seem to do it. I have the lock in the UI and can't seem to unlock it.

What's going on`?

**Comment by MatthiasMann** [comment]
depends on config

**Comment by tterrag1098** [comment]
You need to use the coord selector to set the coordinates

**Comment by Unrepentant-Atheist** [comment]
Then it would be nice if we could store more than 1 coordinate. I like teleporting around various points of interest in my world.

**Comment by tterrag1098** [comment]
#2497
