### ISSUE TITLE
Universal cable issue

### ISSUE THREAD

**Issue by aolko** [SleepyTrousers/EnderIO#2538]
Why i can't connect enderio conduits/machines with universal cables? (latest enderio/lastest mekanism (8.1.3.231))
![img1](http://i.imgur.com/UbAvBBr.png)
![img2](http://i.imgur.com/wFzZnis.png)
![img3](http://i.imgur.com/SL5N57y.png)

**Comment by MatthiasMann** [comment]
This is most likely caused by Mekanism as the energy conduits connect with other mods just fine.

**Comment by MatthiasMann** [comment]
The issue is a wrong mod dependency inside Mekanism for the RF API.

**Comment by aolko** [comment]
please tag as solved
