### ISSUE TITLE
bio generator not hooking to power conduits

### ISSUE THREAD

**Issue by surenakitten** [SleepyTrousers/EnderIO#2539]
running forestry 1.7.10-3.5.6.15 and ender io 1.7.10-2.2.8.318

so the ender io fluid pips hook into the bio generator just fine, how ever the energy conduits wont hook in to any of the 6 sides of the generator and beating it with the yeta wrench didn't help either X3

**Comment by MatthiasMann** [comment]
This is a Mekanism bug - see #2538

**Comment by MatthiasMann** [comment]
The Forestry BioGenerator produces EU and not RF - so it can't work with the EnderIO energy conduits.
