### ISSUE TITLE
Possible duplication bug with Crafter

### ISSUE THREAD

**Issue by rrongol** [SleepyTrousers/EnderIO#2541]
The Liquid Dirt mod has a shapeless recipe for making mud:
Dirt + Water Bucket -> Bucket of Liquid Dirt

This recipe works fine in a vanilla Crafting Table, but when crafted in an EnderIO Crafter it produces an extra bucket:
Dirt + Water Bucket -> Bucket of Liquid Dirt + Empty Bucket

Is this bug caused by an error in the Liquid Dirt mod, or with EnderIO?  

EnderIO-1.7.10-2.3.0.388_beta.jar
liquidDirt-1.3.jar

BTW, EnderIO is fantastic.  Thanks for all the hard work you put into this mod.

**Comment by MatthiasMann** [comment]
This requires that a crafting event is fired by the crafter
