### ISSUE TITLE
Painting Machine first slot is not positioned correctly

### ISSUE THREAD

**Issue by CatDany** [SleepyTrousers/EnderIO#2542]
Basically, it's what the title says.
http://i.imgur.com/j89uP7w.png
Move it one pixel to the right, and I think it'll be fine.
Using v2.2.8.381 (latest one atm on Curse)

**Comment by tterrag1098** [comment]
Nope, the actual slot size is wrong, in the texture. Fixing

**Comment by tterrag1098** [comment]
How this went unnoticed for so long is an absolute mystery.

**Comment by CatDany** [comment]
Yeah, everyone just thinks that their version is outdated, this bug has already been reported, etc. :P

**Comment by CatDany** [comment]
@tterrag1098 Err.. You keep issues open while the version with a fix isn't released or what?

**Comment by tterrag1098** [comment]
Correct

**Comment by CatDany** [comment]
Well..that took some time
