### ISSUE TITLE
Exception while updating neighbours

### ISSUE THREAD

**Issue by GodNero** [SleepyTrousers/EnderIO#2543]
Minecraft - 1.7.10
--------Involved Mods------
Ender IO - 2.2.8.381
Sanguimancy - 1.1.9-29
Mekinism - 8.1.3.231
--------Crash Report-------
Pastebin - http://pastebin.com/menKawd7

I can't tell you what was going on before this crash happened as this is from one of the servers using the Resonant Rise pack. I am still trying to recreate this issue, just thought you might have some insight on this one.

**Comment by tterrag1098** [comment]
This issue is between Sanguimancy and Mekanism...EIO is just triggering it.

**Comment by GodNero** [comment]
cool just checking.
