### ISSUE TITLE
Texture issues with the Inventory Panel

### ISSUE THREAD

**Issue by b0bst3r** [SleepyTrousers/EnderIO#2544]
Using plain default textures this will not be evident but the left edge of the inv panel is the wrong way around

Good sides the back and edges meet 
http://postimg.org/image/m5bq8v4qx/

The bottom is good too, however the left edge is the wrong way around 
http://postimg.org/image/imzqch3ux/

Also the inv panel in the hand doesn't look right 
http://postimg.org/image/p1yr95akp/

It looks like the edge showing in hand is taken from somewhere in the middle of the texture.  In this picture you can see the full blankMachinePanel.png in the floor.

**Comment by tterrag1098** [comment]
The inventory panel uses completely vanilla rendering. I don't see how to fix this.
