### ISSUE TITLE
Yeta Wrench menu gone

### ISSUE THREAD

**Issue by SneakyDevil** [SleepyTrousers/EnderIO#2545]
What it says on the tin. Was messing with graphic options in game, touched mipmap(I think) and now the menu no longer appears. I have restarted my game and tried each mipmap option, restarting in between, and the menu will not reappear.
![2015-06-05_18 40 26](https://cloud.githubusercontent.com/assets/11374726/8016560/e303fb28-0bb2-11e5-8df8-c2df62df5f64.png)

**Comment by b0bst3r** [comment]
Tried removing texturepack?

**Comment by SneakyDevil** [comment]
...I should be insulted but I supoe you just have to expect that level of intellect on the internet at this point.

Yes. I have removed the texture pack and nothing changed.(even restarted.)
![2015-03-02_02 16 16](https://cloud.githubusercontent.com/assets/11374726/8016609/a67b19e2-0bb3-11e5-8a8f-713095cc92d8.png)Proof that it works with this texture pack.

**Comment by SneakyDevil** [comment]
Proof that it doesn't work with default texture pack either
![2015-06-05_18 51 35](https://cloud.githubusercontent.com/assets/11374726/8016638/0009a2bc-0bb4-11e5-9748-00314a31777d.png)
.

**Comment by tterrag1098** [comment]
What version?

**Comment by SneakyDevil** [comment]
most recent forge(.1428) version and most recent ender io(.381) version for minecraft 1.7.10

**Comment by tterrag1098** [comment]
In the latest EIO the yeta wrench overlay was moved to the bottom right. So your minimap is covering it

**Comment by tterrag1098** [comment]
In fact I can see it in the screenshots

**Comment by SneakyDevil** [comment]
I move my minimap to stop covering up things in the top right to the lower right...only to cover up things. How...painful.
