### ISSUE TITLE
Travel Anchor is offset by 1 block on x/z axis

### ISSUE THREAD

**Issue by theit8514** [SleepyTrousers/EnderIO#2546]
Just started using Travel Anchors in FTB Infinity (Additional mods: Torcherino, TSteelworks and Soul Shards: TOW), and I'm running into an interesting issue with the anchor blocks having an offset when traveling to them.

When I place the anchor in the middle of the area, it works fine, but the location you get sent to is +1 x +1 z from the actual anchor itself.

Here is my first test with the anchor in the middle: http://imgur.com/a/ZReE4

Later, I was moving things around and experienced a totally different issue related to this offset that appears to be happening. When the +1 +1 coordinate is blocked, and I try to teleport when pointed at the bottom right of the target block, I get a Destination is Obstructed message and I do not get teleported. However, when I target the top left of the target block, I get the message, but I also get teleported as well. Note in both of these examples, the actual coordinates of the target is not obstructed, only +1 +1.

My second batch of tests: http://imgur.com/a/JzRgq

I have confirmed that I am on the latest release (2.2.8.381) and in that release, it does appear that the [relevant code](https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/teleport/TravelController.java#L411) means that the message only gets output if the teleport fails. Not sure how I could be failing the check but still getting teleported.

Hopefully this makes sense.

**Comment by tterrag1098** [comment]
This was a rounding error with negative coordinates, it has been fixed (FTB is out of date)

**Comment by tterrag1098** [comment]
Actually I take that back, the fix is not in the latest official release. It is however fixed in dev builds.

**Comment by tterrag1098** [comment]
Fixed in https://github.com/SleepyTrousers/EnderIO/commit/91b455e20ff470b857aeeebdc5d9d8e3bc6d2732

**Comment by theit8514** [comment]
Just tested the 388 beta and both issues above are resolved. Thanks!
