### ISSUE TITLE
(RR3 3.2.6.4) Changing replacewitherskeletons to false with an existing world corrupts server mod files

### ISSUE THREAD

**Issue by Zsashas** [SleepyTrousers/EnderIO#2547]
Modpack: Resonant Rise 3
Version: 3.2.6.4 (Current latest)
We currently have the option to make Wither Skeletons a separate mob, set to true. However, this is causing players to time out with a fatal error while in the nether, with this in the client console:

[03/6/2015 14:06:23 PM] java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 67 at ( -1589.46875,53.0, -352.46875) Please contact mod author or server admin.

Attempting to change the config option to false causes corruption of the enderio mod files on the server. This only happens when trying to change it back on an existing world, making a new world with it set to false works fine, but we'd rather not reset the world again right now...(too many resets lately).

**Comment by MatthiasMann** [comment]
EnderIO version, log files, crash reports etc?

**Comment by TheJulianJES** [comment]
Have the clients + the server the config option?

**Comment by Zsashas** [comment]
The clients and server configs match. No crashes, just disconnect. That bit I posted above is the what appears in the logs when the fatal errors happen.

Ender IO version: 2.2.1.381.

**Comment by TheJulianJES** [comment]
Wow, I think the EnderIO version is a bit outdated, right?

**Comment by Zsashas** [comment]
So, this is indeed fixed in newer versions? -sigh- now we just have to wait for RR3 to update again, and hope another reset isn't required. Thanks, though. Didn't realize how outdated it was.

**Comment by tterrag1098** [comment]
That is the latest official eio release

**Comment by TheJulianJES** [comment]
I thought the latest was EnderIO 1.7.10 2.2.8.381

**Comment by tterrag1098** [comment]
I think he typed the version wrong...what he said is not a real version.

**Comment by TheJulianJES** [comment]
@tterrag1098 Okay :)

**Comment by Zsashas** [comment]
Wait what? So that's NOT the latest version? But thats what the site says.

**Comment by tterrag1098** [comment]
2.2.8.381 is the latest official release.
