### ISSUE TITLE
crash when using extra utilities and enderio 

### ISSUE THREAD

**Issue by carlobon** [SleepyTrousers/EnderIO#2548]
enderio: build 388
extra utilities 1.2.5

**Comment by Kodos-Atoz** [comment]
Rename the ExU jar to have an A on the first part.  It's a conflict of Baubles APIs, and ExU needs to load first.

**Comment by carlobon** [comment]
thanks now it works!

**Comment by Kodos-Atoz** [comment]
Yup. Be sure to close this =)
