### ISSUE TITLE
Redstone Conduit connection issue with BC7.0.6

### ISSUE THREAD

**Issue by GodNero** [SleepyTrousers/EnderIO#2549]
Mods in Question:
Buildcraft - 7.0.6
Buildcraft Compat - 7.0.5
Forestry - 3.5.7.16
Logistics Pipes - 0.10.0.1
Ender IO - 2.2.8.381

----
The issue I am having is that Ender IO Redstone and Insulated Redstone Conduits do not connect or interact with any Buildcraft based blocks. Energy/Item/Fluid Conduits are having no issues.

**Comment by MatthiasMann** [comment]
have you tried the insulated redstone one - which can be set to emit a strong signal?

**Comment by GodNero** [comment]
yes, neither conduit will connect to a BC based block

**Comment by GodNero** [comment]
here is a photo representation of what I am referring to, You can see both vanilla and MFR connecting to the BC engines but not the insulated conduit (tried this with non-insulated as well):
http://puu.sh/ieVuR/f4066cbf39.jpg

**Comment by tterrag1098** [comment]
Insulated conduits can be forced to connect to anything. Just wrench the
side of the conduit facing the engine

**Comment by MatthiasMann** [comment]
you can force connect the insulated one by using a yeta wrench and shift left clicking on the conduit.
The normal one never visually connects as it broadcasts the signals to all neighbor blocks.

**Comment by GodNero** [comment]
Huh didn't know that was a thing, however that seems to do it, odd they don't auto connect though. Thanks.

-Nero

**Comment by tterrag1098** [comment]
Why would they? Nothing about engines is special compared to any other
block, redstone wise. If BC is so inclined, there is an interface they can
use for automatic connection (cc @asiekierka)

**Comment by asiekierka** [comment]
Too much hackery would be required. Sorry. I will try and think of something, maybe.

**Comment by tterrag1098** [comment]
Hackery? O.o it's just an interface for the block

**Comment by tterrag1098** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/api/redstone/IRedstoneConnectable.java

**Comment by asiekierka** [comment]
BuildCraft has a strict rule of not pulling in any external mod-specific code or APIs to BC itself, instead utilizing Compat for it.

**Comment by tterrag1098** [comment]
Er...well that's problematic. Not sure how that's a good idea, strict interfaces are often required.

**Comment by tterrag1098** [comment]
Actually sorry, there is a non-interface way to do this

https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/api/IMC.java#L131

**Comment by asiekierka** [comment]
@tterrag1098 - makes maintenance a lot easier. See how BCCompat works.
