### ISSUE TITLE
Ender io item sorting(filters) dont working

### ISSUE THREAD

**Issue by LaberosLabros** [SleepyTrousers/EnderIO#2551]
Hey, i have 1 single chest and i wanna make a sorting system that sorts every item i have specified to the correct chests. 8 chests so far. Sry for the link but this will help you understant what im trying to do: https://www.youtube.com/watch?v=fxO1gCUSeLY&list=PLaiPn4ewcbkEC_hsSjPSqN8Mz3qWVC_MA&index=9

So i did exactly like the video, i did put item conduits under the chests and i configured them correctly.The sorting chest is excract mode always active, and all other 8 are insert mode always active. So its time for sorting. I putted in my most favorite chests Mod Sorting filters and i wrote the name of my mods that wanna get sorted there. No luck.The items still goes to the closest chest they encounter. Not the filted one. Same i removed the Mod Sorting filters and i did put Existing item filters so i can snapshot everything in the chest. But the exact same problem. Even if everything is snapshoted the items are continue going into the first chest they encounter. The fitlers just dont work... Im really annoyed pls i really need your help for this.

Sry for any english issue.

**Comment by MatthiasMann** [comment]
Make screenshots of your setup (including the GUIs).

**Comment by LaberosLabros** [comment]
My Full Conduit Setup:
![full conduit setup](https://cloud.githubusercontent.com/assets/12781007/8022982/6f33c2d6-0cfd-11e5-922d-a65708786cd3.png)


My Item Sorting Chest:
![item sorting chest](https://cloud.githubusercontent.com/assets/12781007/8022987/984c69ca-0cfd-11e5-8f3a-d9b93bcf55b4.png)


Chest with Existing Item filter:
![chest with existing filter](https://cloud.githubusercontent.com/assets/12781007/8022988/b72fb9dc-0cfd-11e5-8e4d-1d5cc7dfd02e.png)


Snapshot Test:
![snapshot test](https://cloud.githubusercontent.com/assets/12781007/8022989/cc22dcf2-0cfd-11e5-8195-a132bf62579e.png)


Chest with Mod Sorting Filter:
![chest with mod sorting filter](https://cloud.githubusercontent.com/assets/12781007/8022990/e7b0206a-0cfd-11e5-97d0-b57e748dda19.png)


Random near chest:
![random near chest](https://cloud.githubusercontent.com/assets/12781007/8023001/48b94b0c-0cfe-11e5-9186-a14b23987ec5.png)


These screenshots should help alot.

**Comment by MatthiasMann** [comment]
Ahh ok - now I understand what you mean.

Basically if all insert pipes have the same priority then the one nearest to the extraction point is used. And if you have multiple valid destinations (eg insert without filters etc) then the items might not go where you expect.

You can either use priorities to override the distance based priority (which is always applied for equal user set priority). Or you can enable the sticky mode on the insert filters.

The sticky mode basically prevents items matched by this filter to go anywhere else (unless there is also a sticky filter which accepts this item).

**Comment by LaberosLabros** [comment]
Thank you very much. Now all i need is to add filters the filters i want to every chest?

**Comment by MatthiasMann** [comment]
Yes, setup filter as you like and also setup priorities when you have multiple chests which can accept a certain item.
Also keep an eye on the meta data when you set it to ignore meta data as eg Lapis Lazuli and Bonemeal are the same item with different meta data.
