### ISSUE TITLE
EnderIO and CoFH Bug

### ISSUE THREAD

**Issue by enterprise12nx** [SleepyTrousers/EnderIO#2555]
Seems to be a bug between CoFH and EnderIO
using Beta V388 
CoFHCore-[1.7.10]3.0.2-262
ThermalFoundation-[1.7.10]1.0.0-81
ThermalExpansion-[1.7.10]4.0.1-182
ThermalDynamics-[1.7.10]1.0.0-122
RedstoneArsenal-[1.7.10]1.1.0-80

Bug Report: http://pastebin.com/iCmBk1k0

**Comment by MatthiasMann** [comment]
This is an CoFH / TE bug.

This is the relevant code from EnderIO:
((ISidedInventory) inv).getAccessibleSlotsFromSide(direction.getOpposite().ordinal());
and direction is a ForgeDirection so the worst case value possible would be 6 - but the except shows a 7.

**Comment by enterprise12nx** [comment]
sigh, this seems always the case.
each mod accuses its the other mod, i report bugs between mekanism enderio and CoFH and they all say its not them and it never gets fixed.
