### ISSUE TITLE
Dark Armor Empowered Upgrading

### ISSUE THREAD

**Issue by rdylanm01** [SleepyTrousers/EnderIO#2556]
Using Dev Build 2.3.0.390
Tested only Empowered 1 to Empowered 2 with Helmet, Chest, Legs, and Boots.
When upgrading from Empowered 1 to Empowered 2, if the armor with Emp. 1 has some RF in it, upgrading it will cause it to lose RF. Unsure whether this is a bug or intentional. On Forge .1408

**Comment by MatthiasMann** [comment]
I think this is intentional - as all other upgrades keep the stored energy. Same with dark steel tools.

**Comment by rdylanm01** [comment]
Ok. Was just making sure. I just started playing with the newest betas 2 days ago, and started upgrading the armor all in one night. Never really used the armor enough to realize it.
