### ISSUE TITLE
mouseover appearing on item filter GUI when it shouldn't be

### ISSUE THREAD

**Issue by b0bst3r** [SleepyTrousers/EnderIO#2557]
orrrrr button missing, I'll let you decide :)

http://postimg.org/image/sefw4scsp/

EnderIO-1.7.10-2.3.0.388_beta.jar

Occurs only when chargeable item filter is inserted

Oh it would seem the button is missing as the existing item filter also has the issue

http://postimg.org/image/ojci27tmx/

**Comment by tterrag1098** [comment]
This was only ever a bug in dev builds, closing
