### ISSUE TITLE
Comparator Frame Rate Lag on Capacitor Bank

### ISSUE THREAD

**Issue by ArcaneTechnician** [SleepyTrousers/EnderIO#2558]
Having a comparator on a capacitor bank causes a significant decrease in frame rate(nearly 30 fps drop).

**Comment by MatthiasMann** [comment]
Can you provide a screenshot of that setup?

**Comment by ArcaneTechnician** [comment]
It is simply having a comparator on any side of the capacitor bank. I had to disassemble it, as it was causing problems with the server I was playing on.
