### ISSUE TITLE
[Request] Enchanter Automation

### ISSUE THREAD

**Issue by Sil3ntStorm** [SleepyTrousers/EnderIO#2559]
It would be nice if the Enchanter would be able to take the required Experience from an Experience Obelisk or pipes/conduits (I think many other machines are already able to?).
While at it could it be changed so that the Enchanter accepts items from automation systems such as ME export / import buses?

**Comment by nick4fake** [comment]
Am I right that this issue is closed without any comments or fix?

**Comment by tyler489** [comment]
Correct

**Comment by HenryLoenwind** [comment]
nah, got a comment for you...

**Comment by Tanju42** [comment]
could you guys please implement this a automation would be really nice
