### ISSUE TITLE
Soulbound armor persists through Syncs => Dupe bug

### ISSUE THREAD

**Issue by CatDany** [SleepyTrousers/EnderIO#2560]
Basically, title says everything about this problem.
You wear Soulbound armor, you create a new Sync, then go inside and now you have your Soulbound armor on your new Sync body. Put it in the chest, go back and repeat until you have unlimited amount of those armor pieces.

Sync: http://ichun.us/mods/sync/

**Comment by HenryLoenwind** [comment]
This should not happen with the latest Soulbound changes. The item should be only on the new body. For it to stay on the old one, Sync would need to stop telling us that the player has died on the cloning event.
