### ISSUE TITLE
[Bug] Alloy Smelter wont accept items

### ISSUE THREAD

**Issue by Rexaking** [SleepyTrousers/EnderIO#2561]
Currently playing SkyFactory 2.4, and I have experienced this issue before.
Issue: After a good while, the Alloy Smelter stops accepting certain items or all together, items needed to craft various alloys. Ive tried numerous things to make it work.
Just to clarify, the Alloy Smelter has been working for a long time, crafted manymany items, then suddenly stops accepting more than 1 item, if even that. I have more than sufficient power, tried breaking it, crafting a new one, resetting it in the crafting window to clear it, multiple locations, nothing!

**Comment by MatthiasMann** [comment]
In which mode was the alloy smelter and which items have you tried to put in?

Could you check what the recipe button shows (eg how many recipes and if the one you wanted to use is part of that list)?

**Comment by Rexaking** [comment]
Tried both in All Smelting and alloys only mode.
Electric Steel is one I've tried, with iron ingot, pulverized coal and silicone, checked it and the recipe is definitely there!

**Comment by evolvex** [comment]
I have the same issue when trying to make Electric Steel when using Sky Factory 2.4 (EnderIO-1.7.10-2.2.8.367.jar. Just trying EnderIO-1.7.10-2.2.8.381.jar.

**Comment by MatthiasMann** [comment]
how did you configure the sides of the alloy smelter?

**Comment by evolvex** [comment]
Hi MatthiasMann, Can remove mine, I think it was down to a "user to stupid" moment - think I was trying it with charcoal instead of coal. Latest version seems fine when I use the right thing.
