### ISSUE TITLE
Improved display on Vibrant Capacitor Bank

### ISSUE THREAD

**Issue by WalterWeight** [SleepyTrousers/EnderIO#2562]
I really like the display that can be toggled on vibrant capacitor banks (VCB) by shift right clicking with an empty hand, however, instead of it just showing the net input or output, why can't it show both the total input and output per tick?

Currently, if your VCB is empty, and there's a input of 100rf/t, and an output of 50rf/t, it shows the net difference, which would be "input 50rf/t". This tells you that you are generating more than you are using, which is great, however when the VCB is full, it will then show "i/o 0rf/t". In this case, how much spare power generation capacity do you have? You know it's 50 from the example, but when the display shows "i/o 0rf/t", all you know is that you are capable of generating as much as you are using, but how much spare power generation capacity do you have? 0rf/t? 100rf/t? 100,000rf/t? You've no idea.

Instead, if the display on a fully charged VCB showed both the input and output, you'd see "input 50rf/t & output 50rf/t". Knowing your power generation system was capable of producing 100rf/t, you'd now know that you are capable of generating 50rf/t more than you're using.

Not only would it be useful, but when you build big powerful power systems, say your VCB was full, and you were generating 65,535rf/t and using 65,535 rf/t, I'd want it to display those figures, rather than just show a boring "i/o 0rf/t".

You could take it a step further and have it show the storage too, e.g. "Input 65,535 rf/t, Output 65,535 rf/t, Stored 200,000,000 rf"

**Comment by MatthiasMann** [comment]
It will show both when you make the display taller than wide.

**Comment by WalterWeight** [comment]
Really? didn't realise this. In which case, apologies, I'll close the issue.
