### ISSUE TITLE
Suggestion: New Explosives

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2564]
Almost every techmod, magicmod, whathaveyoumod add new items, blocks, tools, etc. but strangely almost none of them add any new explosives to the game.

I kinda want to have more choices besides TNT. Bigger, smaller, better, different, anything, really :).

New kaboom is gud! The TNT y'all got in are funny to work with, but I'd like to actually have different destructive TNTs :)

**Comment by widd** [comment]
I'm on board with this. A start could be a block/TNT version of the Concussion Creeper's explosion from Ender Zoo.

**Comment by CrazyPants** [comment]
That already exists in ender zoo

**Comment by widd** [comment]
Ah, I haven't worked with Ender Zoo as much. Still agree that some explosives could be added.

**Comment by tterrag1098** [comment]
@Unrepentant-Atheist was this meant to be proposed for EnderZoo? EIO has no explosives currently.

**Comment by Unrepentant-Atheist** [comment]
Yes, EnderIO. EnderZoo has these concussion something tnt. I thought since EnderIO already is a tech mod, it might implement some bigger kaboom explosive than these punny vanilla chinese crackers.

**Comment by Badcholo** [comment]
It would be nice to have something similar to ICBM explosives, even without the missles. I really miss the Antimatter Explosive.

**Comment by MatthiasMann** [comment]
There is nothing in EnderIO which requires explosions and I don't see how explosions would fit into it.

**Comment by Badcholo** [comment]
an option to remove it. maybe just 1?
