### ISSUE TITLE
farming station disappeared

### ISSUE THREAD

**Issue by BIGE1** [SleepyTrousers/EnderIO#2566]
I played on sky factory for a wile with the farming station up and running and as I go in the station it disappeared can someone help please

**Comment by b0bst3r** [comment]
Most likely what happened is the farming station errored as Forge in Skyfactory2 is set to delete/remove erroring blocks.  This Forge setting is highly experimental (it even says so on the setting) and is NOT recommended but pack makers insist on turning it on.  The result is your blocks which may cause you to error are deleted in front of your eyes.

Suggest you turn off  B:removeErroringEntities=true in forge.cfg

There's absolutely nothing the EIO devs can do without a crash report and AFAIK that setting above stops a crash report from being generated.

**Comment by tterrag1098** [comment]
Indeed, we need the crash log. I need to speak to Bacon about this...

**Comment by RossBoss74** [comment]
Didnt work for me :(
