### ISSUE TITLE
Duping Glitch [I'm explaining it because I don't want people to abuse it in servers]

### ISSUE THREAD

**Issue by DKnightADRI** [SleepyTrousers/EnderIO#2567]
Hey, I discovered kind of a duping glitch while using this mod.
Developpers (Original mod authors), could I send you a private message about it, or can I get your skype or something?
Thank you

Regards
DKnightADRI / Adriaan

**Comment by tterrag1098** [comment]
IRC is the best place for this, PM me there.

**Comment by DKnightADRI** [comment]
You mean here? http://irc.lc/freenode/github/
If so, is your name there tterrag1098 as well?
Thank you
~DKnightADI

**Comment by tterrag1098** [comment]
http://webchat.esper.net/?nick=&channels=EnderIO

**Comment by DKnightADRI** [comment]
Alright, I pm'd you there. I hope you can fix this.
~DKnightADRI

**Comment by HenryLoenwind** [comment]
which one was this, has it been handled?

**Comment by tterrag1098** [comment]
Unfortunately I've forgotten the details as well. A refresher would be appreciated.
