### ISSUE TITLE
Add more powerful energy conduit?

### ISSUE THREAD

**Issue by widd** [SleepyTrousers/EnderIO#2568]
Been using EnderIO for a long time now and I think that some sort of high-cost/high-power cable is in order. Endgame content where massive amounts of power are required forces some poor design choices for complex machine setups.

Keeping in touch with the measure of conduit throughput, could there be some sort of "ultimate" energy conduit with around 80k rf/t throughput? Higher cost would obviously be required.

The limits of the dimensional transceiver make sense but seeing as capacitor banks have cumulative throughput power dependent on their multiblock size, I feel as if this should've been in the mod awhile ago.

**Comment by MatthiasMann** [comment]
You can just use multiple connects of the ender energy conduit - as the 20k RF/t limit is per connection.

**Comment by widd** [comment]
I'm well aware - that's why I suggested around 80k rf/t. Realistically I cannot use every single side of a machine as most machines have input/output on at least one side, sometimes two or more. Most EnderIO machines do not have this issue, but capacitor banks do. Splitting a ~3  billion total RF capacitor bank between 20k rf/t conduits is not very practical.

**Comment by HenryLoenwind** [comment]
20k is more than enough if Ender Io is used on its own. If you use it in combination with other mods, you should configure the mods to work nicely with each other. One of those config options is the RF limit of our conduits and cap banks.
