### ISSUE TITLE
Enderman Spawner 

### ISSUE THREAD

**Issue by BuckitHead** [SleepyTrousers/EnderIO#2570]
Forge 1420 
EIO 390

Enderman spawner will not spawn enderman. Just keep cycling.

**Comment by MatthiasMann** [comment]
How did you set it up? Eg how much space is around it?

**Comment by BuckitHead** [comment]
8x8 5 high. It will not spawn in the open. It's acting like the wither skelly spawner did some time ago when it was having issues.

**Comment by BuckitHead** [comment]
ok sorry it was the guy on my servers fault...
