### ISSUE TITLE
Cross-mod crash with Thermal Expansion

### ISSUE THREAD

**Issue by Cobra1117** [SleepyTrousers/EnderIO#2571]
After updating to 2.2.8.381, my server has been occasionally crashing with this log:
http://pastebin.com/0b1E25fD

**Comment by tterrag1098** [comment]
Update your TE

**Comment by Cobra1117** [comment]
I'm running Thermal Expansion 4.0.1-182, which is the latest version available (as far as I can tell)

**Comment by MatthiasMann** [comment]
This is a duplicate of #2166
