### ISSUE TITLE
null pointer exception; add growable ores v390

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2579]
crash with proj. red 4.7.0 pre 1

paste http://pastebin.com/wM8tt2f6

**Comment by MatthiasMann** [comment]
Some mod added a block without registering a name for it - while this is not an EnderIO bug we will just add a guard to not crash.

But this crash might still happen for other mods.

**Comment by Ianaver** [comment]
ok

**Comment by CptSpaceToaster** [comment]
sorry for spam... probably isn't relevant.  Wrong link.

**Comment by Ianaver** [comment]
@MatthiasMann can I close this for now since the issue is fixed?
