### ISSUE TITLE
How to remove Villager and Iron Golem from the blacklist in the Powered Spawners config file?

### ISSUE THREAD

**Issue by timverhaag** [SleepyTrousers/EnderIO#2581]
I tried various ways to remove the Iron Golem and the Villager but it does not seem to work for me. Thanks for your help in advance.

**Comment by tgstyle** [comment]
It should just be something like this in the user file

{
    "costMultiplier": {},
    "blackList": []
}

**Comment by 6210classick** [comment]
https://www.dropbox.com/s/ucwe12mfiphqbry/PoweredSpawnerConfig_User.json?dl=0

**Comment by djmulder** [comment]
dropbox file doesn't exist anymore... and I tried the blacklist: [] (are they square brackets? I'd assume curly)
