### ISSUE TITLE
Broken blockIngotStorage recipes in latest beta build (391)

### ISSUE THREAD

**Issue by srs-bsns** [SleepyTrousers/EnderIO#2582]
EnderIO-1.7.10-2.3.0.391_beta

9 Ingots are returning a single ingot of the same type instead of Blocks.
The recipe for 1 Block -> 9 ingots still works.
I believe the problem is with commit: d98be8dd86e02b7ed40419ae01db27ee58063b7e

![](https://i.imgur.com/Q5MGf8A.png)
![](https://i.imgur.com/IiSSLce.png)

**Comment by tterrag1098** [comment]
Must have made a typo...
