### ISSUE TITLE
Empty Portable Tank Clicking on Combustion Engine Crash

### ISSUE THREAD

**Issue by ReportBot9009** [SleepyTrousers/EnderIO#2584]
Hello,

I just spoke to the webchat about this bug: When I right-click with an *empty Portable tank (I had only used a resonant portable tank at the time) into a combustion engine, it causes my client to crash. This is on a local single-player game.

Here is the crash log:
http://pastebin.com/C8svYxMw

Take care,
littlecrafterfin

**Comment by Lilylicious** [comment]
Same issue arises with empty fluid containers from other mods, not Portable Tank specific.

**Comment by MatthiasMann** [comment]
The crash has been fixed for the 2.3 beta branch.
