### ISSUE TITLE
Potential Conduit Rendering Issue Involving Render Passes

### ISSUE THREAD

**Issue by ReikaKalseki** [SleepyTrousers/EnderIO#2586]
The semitransparent liquid texture from conduits may be rendering on pass zero, occluding other TESRs it lies in front of (due to OpenGL transparency treatment):

![](https://photos-5.dropbox.com/t/2/AABiT9ojjaLbAsEyvhvh3qV_cT4JnM0QQ8SX4r9H6K4zEQ/12/70622753/png/32x32/1/1434326400/0/2/Screenshot%202015-06-14%2018.06.50.png/CKG81iEgASACIAMgBCAFIAYgBygBKAI/SA3d4u2scpI5qi9I9_6LkQI--i5lTxtHUPla373UT5M?size=1280x960&size_mode=2)

I would double-check this, and move it to pass 1 if it is not there already to avoid further issues of this nature.

**Comment by tterrag1098** [comment]
Last I checked TESRs only get one pass...

**Comment by ReikaKalseki** [comment]
No, they can be set to render on passes zero and one. By default, the TileEntities only do run their renderers on pass zero, but you can override the canRenderInPass(int pass) function.

**Comment by tterrag1098** [comment]
Interesting but I can't see that being usable from a conduit, since they
all use the same renderer.

**Comment by ReikaKalseki** [comment]
??

**Comment by tterrag1098** [comment]
Rendering all conduits In the second pass would not be a good idea. Unless
there is a way to get the current pass inside the TESR?

**Comment by ReikaKalseki** [comment]
Easily. MinecraftForgeClient.getRenderPass().

**Comment by utoc** [comment]
I'd like to chime in on this issue as well.  My users have found a bug where using waterstone/lavastone Chisel 2 textures in a painting machine on glowstone results in either the main stone texture missing (you see only lava/water in that case) or the water/lava texture missing resulting in a cheap X-Ray block, able to see through opaque blocks.  Fences exhibit some unique behavior as well.

When using the bugged block by itself, you get an X-Ray block by default.  When it is using connected textures with a real Chisel 2 block, one block of painted glowstone will result in missing the stone texture, the other will look as it it were a tank.  This seems to be a north/south bias.

Here are some pictures to explain what my words undoubtedly confuse.  The block on the left and right are painted glowstone of the same variety as the genuine Chisel 2 block in the middle: https://i.imgur.com/5NkSJvd.png

Here is another example of the same setup:  https://i.imgur.com/S1gGh0x.png

Additionally, you get some kind of weird artifact/noise in your inventory/item-in-hand rendering as can be seen here https://i.imgur.com/2vljSKX.png and here https://i.imgur.com/3LTN8Y7.png

Fences painted with lavastone/water stone are just plain broken, no water/lava texture seems to be applied:  https://i.imgur.com/93scUdu.png

Finally, I reported this bug earlier with Chisel 2, as seen here https://github.com/Chisel-2/Chisel-2/issues/334 but was told this was not their issue.

Thanks for taking a moment to look at that.  I appreciate all the effort.

**Comment by MatthiasMann** [comment]
@utoc why did you add this unrelated issue here? Don't put multiple things into one issue report.

**Comment by utoc** [comment]
@MatthiasMann My apoligies, @ReikaKalseki issue sounded very similar to mine.
