### ISSUE TITLE
[Mod interaction] [Rotorycraft] this and railcraft cause a null item stacks issue

### ISSUE THREAD

**Issue by Ianaver** [SleepyTrousers/EnderIO#2587]
A crash happens when this mod is installed with rotarycraft and you happen to view usage or recipes in rotorycraft. The crash shows that something is adding null item stacks in recipes (I think its in recipes) and Railcraft and this mod are two known culprits. Either way, this issue should be investigated to at least see what could be doing this.
paste: http://pastebin.com/1w1TYxVX

post on railcraft repo (same as here)

CovertJaguar/Railcraft#636

**Comment by MatthiasMann** [comment]
@Ianaver well - does it crash with only EIO and RotaryCraft or only with Railcraft and Rotarycraft?

From looking at RotaryCraft's code:
https://github.com/ReikaKalseki/RotaryCraft/blob/master/Auxiliary/RecipeManagers/RecipesLavaMaker.java#L47
this can't be caused by EnderIO as it does not modify any of the standard Minecraft blocks.

**Comment by Ianaver** [comment]
@MatthiasMann evidently not however with my current pack, something makes the crash happen

mods:
![mods](https://cloud.githubusercontent.com/assets/8153290/8177260/b9d818ee-13b7-11e5-8e93-70a7cb55e59e.PNG)

**Comment by MatthiasMann** [comment]
@Ianaver does it still crash if you just remove EIO?

**Comment by Ianaver** [comment]
@MatthiasMann if EIO or railcraft and NEI (and core) and rotarycraft and liteloader are present, crash occurs. Why? I am not sure. I don't even know anymore so I might as well close this before my brain explodes.... :P I hate when an issue instead of only being 2 mods max its 4 or more because it actually took me legit 3 hours of constant searching to find this.... I am sorry
