### ISSUE TITLE
Please add peaceful recipes to EnderIO

### ISSUE THREAD

**Issue by KristjanKr** [SleepyTrousers/EnderIO#2591]
I suggest adding a feature for us, peaceful players.. that would like to craft the inventory panel for example, that requires catching witch which is impossible to do on peaceful modpack. :)

**Comment by Thiana** [comment]
The peaceful recipes added for frankenZombie/sentientEnder require an ender resonator and a zombie controller... Neither of which can be created in peaceful mode.
