### ISSUE TITLE
Feature request: Magical power system

### ISSUE THREAD

**Issue by wizard1399** [SleepyTrousers/EnderIO#2593]
Hello,
I would like to request a feature. I am trying to put together a modpack concept where there is no such thing as rf. The only generators in my pack would be Botania and Ancient Warfare 2. Could a magical means of running your machines be added either through a config or other option? For example, could your machines be powered by the blood magic soul system or possible by centivis from thaumcraft? Yes, I know that Botania has a block that can convert mana to rf, but that would go against the concept of my modpack. What I really want is a means of using magic mods to power ender io.

**Comment by Sandriell** [comment]
Ancient Warfare 2 can directly power anything that uses RF as that is what it generates.

**Comment by wizard1399** [comment]
Wether Ancient Warfare 2 can use rf power or not is not what I asked for. The concept of the pack is magic and adventure, NOT technology.  I want to use some form of MAGIC system to power machines. Something like, place a blood magic orb in the capacitor slot and the machine runs on the power in your sould network or add an upgrade that allows the machine to run via the power from an energized node from thaumcraft.

**Comment by XFactHD** [comment]
I think this isn't an idea for EnderIO itself, but more for an add-on mod to EnderIO.
