### ISSUE TITLE
Energy Conduits Render as Natura Sticks in Inventory Panel

### ISSUE THREAD

**Issue by shadowfacts** [SleepyTrousers/EnderIO#2596]
The first tier Energy Conduits render as Eucalyptus sticks from Natura in the right section of the Inventory Panel GUI. The title of item in the same section is displayed as "Stick" instead of Energy Conduit.

EnderIO version: 2.3.0.393_beta

Searching for "stick":
![Searching for "stick"](http://puu.sh/iuQaN.png)

Taking half the stack:
![Taking half the stack](http://puu.sh/iuQf7.png)

**Comment by tterrag1098** [comment]
O_o

**Comment by shadowfacts** [comment]
This problem appears to have been fixed after restarting the game.

Side note: I'm still confused the fuck by this, if anyone figures out what happened, please tell me.

**Comment by tterrag1098** [comment]
Sounds like IDs got swapped around somehow. Very bizzare. Might be an edge
case in the database code.
