### ISSUE TITLE
Redstone Conduit Strong Signal Issue

### ISSUE THREAD

**Issue by forcemaster89** [SleepyTrousers/EnderIO#2599]
I have found that when strong signal is enabled on any of the four sides of an Insulated Redstone Conduit, all four sides will receive output regardless of color (when that color is active). In the picture only brown is active via Redstone lever, but all 4 lamps light up. 

When strong signal is disabled, only blocks connected to the block the conduit is pointing into will receive a signal. So in the scenario in the picture none of the lamps would power up without a strong signal, but attach a lamp to any side of the lamp connected to the brown interface, and that one would power up.

I'm not sure exactly how these mechanics are meant to operate, but it doesn't seem quite right.

Thanks for the awesome mod, keep up the great work!

![2015-06-21_11 25 07](https://cloud.githubusercontent.com/assets/792389/8272641/4dc94830-1808-11e5-9008-2ca72b0bfbf1.png)

**Comment by tterrag1098** [comment]
Cannot reproduce

**Comment by forcemaster89** [comment]
Just re-tested this on a fresh install with just forge and EnderIO, and I couldn't reproduce it either. I must have something else installed that is causing this. 
Thanks for checking anyways!
