### ISSUE TITLE
Ender io and Botania compatibility

### ISSUE THREAD

**Issue by Bellwar** [SleepyTrousers/EnderIO#2600]
I have problem with ender Io item conduit connecting redstring container. Im playing botania 191 build and ender io 2.2.8.381. 

Screenshots: http://imgur.com/8nVgPas,jUVpUJs#0

**Comment by MatthiasMann** [comment]
EnderIO item conduits connect to any inventory which exposes slots. Maybe it is missing a block update?

Try placing a block (eg dirt) next to the conduit in question and then use the Yeta wrench shift-click to open the conduit GUI.

**Comment by tterrag1098** [comment]
If that is the case then this is on botania's end, they need to send out a
time update when accessibility changes.

**Comment by Bellwar** [comment]
Firstly, it isnt for everyone few of them connects right away, few just need me to stand there (right next to them) for a while. 
Second I have wierd problem, i was trying to replace the redstring container. When i removed first of them ender conduit attached to the second redstring and when i placed it down it just dont attached, then  i broke the second connected and it connced to the first one and same problem again (maybe this will need video.)

PS: Im not sure but i think this problem is just with connections where is used Item filter with Existing Item Filter because i dont have problem with mod item filters to connect.

**Comment by Bellwar** [comment]
OK after breaking it littlebit and restarting instance it just start to work good same as at the time i set it up. But i think after while it will just start doing same thing again. Still wierd...

**Comment by MatthiasMann** [comment]
Item filter have no influence on where or how a conduit connects - they can only affects which items are transferred.
This really sounds like a missing neighbor update from Botania.

**Comment by Vazkii** [comment]
I have to do what now?

**Comment by tterrag1098** [comment]
Send a neighbor update so that bordering TEs know something has changed

**Comment by Bellwar** [comment]
Ok so i reposted this report on Botania's tracker so maybe you can close it here. Thx for helping.
