### ISSUE TITLE
The Crafter can lose buckets on save/load

### ISSUE THREAD

**Issue by rrongol** [SleepyTrousers/EnderIO#2601]
If the Crafter has ingredients to perform a craft, and if the output slot of the Crafter is full including an item and empty bucket, when you save/quit/load the game the Crafter seems to do another craft cycle which destroys the empty bucket from the previous cycle.  Sorry, that's probably not well written, so here is an easy way to reproduce the error using the Rain Muffler recipe from Extra Utilities, since it is a simple recipe.  I verified the error with several other recipes.  

1) In creative, place a Crafter next to a Creative Capacitor Bank
2) Get a couple of stacks of wool, and several full water buckets in you inventory
3) Open the Crafter and "program" the recipe on the left side.  It's a water bucket in the middle surrounded by eight wool.
4) Now put one water bucket and a couple of stacks of wool on the right ingredients side of the Crafter.
5) After a second or so, the water bucket and eight wool disappear, and a Rain Muffler appears in the finished product slot.  Don't pick it up yet!
6) Place another water bucket in the center slot of the ingredients grid.  Nothing happens because the Crafter if waiting for you to take the Rain Muffler and empty bucket from the product slot.  Don't pick them up yet!
7) Close the Crafter interface, Save and Quit, then reload the game.
8) Open the Crafter interface.  Now there are two Rain Mufflers in the product slot.  Go ahead and pick them up now.  One empty bucket will appear in the product slot.  Take it too.  That's all you get.  One bucket is missing now.

If you have a conduit feeding water buckets into the Crafter like I had you will loose a bucket every time you save/load the game.

Sorry for the wall of text.

**Comment by MatthiasMann** [comment]
Yes, the containerItems list which stores the "overflow" is not saved.

**Comment by rrongol** [comment]
OK, that makes sense.  I'll have to redesign my Rube Goldberg assembly line to account for this.

Hmm.  Maybe I can combine this with issue  #2541 to break even on buckets.  :-)

**Comment by tterrag1098** [comment]
@MatthiasMann would you consider this a bug? I would...
