### ISSUE TITLE
Ok another crash with latest dev build as of right now

### ISSUE THREAD

**Issue by crunkazcanbe** [SleepyTrousers/EnderIO#2603]
As soon as I click the creative tab for enderio i get this crash http://pastebin.com/qgX4RyaC

**Comment by crunkazcanbe** [comment]
Thank you I will just compile endercore from the source since i dont wanna wait. Thanx again

**Comment by tterrag1098** [comment]
I don't think it's fixed, it must be something else. Investigating...

**Comment by tterrag1098** [comment]
That should do it, pending a small code change in EIO

**Comment by tterrag1098** [comment]
Ok, fixed in build 397
