### ISSUE TITLE
Killer Joe triggering Social Zombie spawning.

### ISSUE THREAD

**Issue by Crumbology** [SleepyTrousers/EnderIO#2605]
As the title says, when Joe hits a zombie he has a chance of spawning another zombie near him, had quite a few packs of them roaming my base, not sure if this is actually an issue, but it's a definite annoyance.

**Comment by MatthiasMann** [comment]
This is vanilla mechanic (or another mod - not sure which). But definitely not done by EnderIO / Killer Joe.
