### ISSUE TITLE
keep getting this same crash with TE and its core mods installed - Not working with enderio alone and baubles

### ISSUE THREAD

**Issue by crunkazcanbe** [SleepyTrousers/EnderIO#2612]
Crash log here http://pastebin.com/kwTh2pXC

I have Mekanism ,and TE and all its core mods installed with many other mods small pack .

Edit  : Using the latest Cofhcore that was released yesterday . Is there a certain one I should use.
Just wondering why you didnt build this against the latest stable Cofhcore instead of a alpha version of it cause its hard to find the right version of Cofhcore cause theres so many .

**Comment by b0bst3r** [comment]
Add cofhcore to your pack, it's Mek's fault.

**Comment by crunkazcanbe** [comment]
CoFHcore 3.0.2 - 262 is clearly in my mods folder and in fact looking in the log you will see I even tried dev builds of CoFHcore . The version above 3.0.2 - 262 is the stable version that does not work either . 

If you dont mind my ignearnce what versions of ThermalFoundation ThermalExpansion ThermalDynamics CoFHLib CoFHCore should I be running . All stable builds or the DEV builds ?

**Comment by crunkazcanbe** [comment]
OK big news!How can it now be mekanism fault ;because I just totally removed it with the same crash here http://pastebin.com/usvUdPT2 Got thermal expansion and all its core mods the stable versions installed .

**Comment by crunkazcanbe** [comment]
Ok now look I now have only TE and its core mods installed with enderIO ,and its the smae issue http://pastebin.com/E6BJKc8w

**Comment by b0bst3r** [comment]
What you have there is a mod shipping an incorrect version of the COFHCore API, since you left off the mod list from the first pastebin I guessed and guessed wrong.

**Comment by crunkazcanbe** [comment]
Found the mod causing this and its the Baubles-1.7.10-1.0.1.10 mod. When removed it works fine . Sad thing is I have the latest version of it and alot of mods rely on it. What can I do is there anyway I could open the jar ,and update it myself the api ?

**Comment by crunkazcanbe** [comment]
I claim this is a official issue with the Baubles mod a conflict with Baubles and enderio .

**Comment by crunkazcanbe** [comment]
Enderio Needs to be updated to the new baubles API ;because just to many mods rely on this version of it .

**Comment by ate0ate** [comment]
The dev builds of ender io work fine with that version of baubles. At least that's what I am using.

**Comment by crunkazcanbe** [comment]
Well maybe its cause I am using forge 1481 the latest DEV build what version of forge do you recommend ?

**Comment by crunkazcanbe** [comment]
Is there any way I can just disable the damn magnet ? Because running latest forge recommended build now with latest dev enderio and latest baubles I keep crashing while loading the game . If I remove baubles bam prob solved ,and it works ,but I need baubles for many other mods that don't have issues with it .

**Comment by crunkazcanbe** [comment]
EnderIO-1.7.10-2.3.0.397_beta and EnderCore-1.7.10-0.0.1.6_alpha DO not load up MC with Baubles-1.7.10-1.0.1.10 Unless there is a certain version of forge I need , But I will say I tried it with latest DEV build of forge 10.13.4.1481 and the forge recommended version 10.13.4.1448 . Same results .

**Comment by MatthiasMann** [comment]
This whole things has nothing to do with CoFH or Mekanism.

It is a class loading issue with baubles - the exact reason/cause has not yet been found.

**Comment by MatthiasMann** [comment]
Same stack trace as #2246

**Comment by tterrag1098** [comment]
EnderIO does not ship the baubles API
