### ISSUE TITLE
Item graphic display issue in the creative tab

### ISSUE THREAD

**Issue by crunkazcanbe** [SleepyTrousers/EnderIO#2613]
Screen shot here http://imgur.com/2fdvoGF 

Its been like this for the last 50 or so dev builds ,but just now getting to pointing it out .

**Comment by tterrag1098** [comment]
Which build? It doesn't happen for me.

**Comment by crunkazcanbe** [comment]
The latest one here http://minecraft.curseforge.com/mc-mods/64578-ender-io/files also the latest DEV build here http://ci.tterrag.com/job/EnderIO/398/ does it to . :/

**Comment by MatthiasMann** [comment]
Which GPU do you have?

**Comment by crunkazcanbe** [comment]
Amd R9295x2
