### ISSUE TITLE
Constant errors on server console

### ISSUE THREAD

**Issue by shortybsd** [SleepyTrousers/EnderIO#2619]
These EnderIO errors have been spamming since I installed the mod. Recently, I had a power outage in which messed up 2 chunks. I loaded it in MCEdit and assumed it fixed it. Yet it continues to spam, any pointers? http://pastebin.com/9TLBc774
Back when I ran cauldron I used a plugin called AutoSave which worked very well with zero chunk corruption if there was an outage. Forge itself is horrible with world saving (and yes I know I need a APC/UPC battery backup). Any suggestions?

**Comment by tterrag1098** [comment]
It's still corrupted if you are getting those errors. Your best bet is to completely wipe and regen the broken chunks.
