### ISSUE TITLE
Powered Lights causing major TPS issues

### ISSUE THREAD

**Issue by wompzilla** [SleepyTrousers/EnderIO#2620]
I had built a 39x39x6 base on my server.  Lit it up with 81 powered lights, spaced evenly with 3 blocks in between each light.  When I started server today, I kept getting massive 13 second lag spikes, and the server was skipping up to 300 ticks.  Server was outputting the "Server cannot keep up" warning.  I removed all of the powered lights and it went from constantly skipping 300 ticks to skipping only about 50 occasionally.

**Comment by MatthiasMann** [comment]
Which EnderIO version? The powered lights have been reworked in the 2.3 beta.

**Comment by wompzilla** [comment]
Ah, alright thanks. I had been using 2.2.8 version that is provided with FTB Infinity.  I'll be sure to update it.  Thanks.  If I still have any issues, i'll be sure to give an update.
