### ISSUE TITLE
EnderIO and BCA need EnderCore and ttCore, but they don't work together

### ISSUE THREAD

**Issue by erkro1** [SleepyTrousers/EnderIO#2621]
Like the title says, (latest) Enderio needs EnderCore and BCA needs ttCore, but they don't work together. Please fix this.

**Comment by MatthiasMann** [comment]
https://github.com/SleepyTrousers/EnderCore/issues/2

**Comment by tterrag1098** [comment]
BCA? Wat?

**Comment by erkro1** [comment]
BuildCraft Additions

**Comment by tterrag1098** [comment]
BCA doesn't require ttCore that I know of...

**Comment by erkro1** [comment]
Well I got quite some mods installed and I tried without it and it says it needed it.

**Comment by AEnterprise** [comment]
@erkro1 it can't be BCA i'm 100% sure of that (as i'm the one making it) to prove that: just make a new instace with BC, BCA and eureka and it'll run just fine

**Comment by erkro1** [comment]
@AEnterprise You were right, it was Wailaplugins, when it crashed it didn't show what mod caused it so for some reason I thought of BCA. Thanks for the help and also very much thank you and everyone else maintaining this cool mod for it's awesomeness.

**Comment by AEnterprise** [comment]
if you don't know sure what mod is causing the crash, please DON'T blame a random mod, provide logs and we'll be able to tell you what the mod causing the issue is

**Comment by erkro1** [comment]
I know normally I don't do this, for some reason I was certain it was BCA when it wasn't.
