### ISSUE TITLE
Ender IO & Ender Zoo Requesting Endercore ??

### ISSUE THREAD

**Issue by Cooolaid** [SleepyTrousers/EnderIO#2622]
It seems that now my minecraft wont start anymore 
without me installing something called 'Endercore v1.7.10-00.0.1.8_alpha'
Last night the game started fine, and played for hours.  The only mods I remember updating are whats in this picture.
http://i.imgur.com/o4igkVc.png
today its now requesting endercore .... Im a bit confused...
I went to the curse download pages & Ender-IO official website to find such file, nothing there.
I am using Ender Io v1.7.10-2.2.8.381 - & - EnderZoo v1.7.10-1.0.11.28 & Forge 448.
Also - Ender Utilities v0.4.1 - EnderTech v1.7.10-03.2.386 - Ender Compass v1.1 & EnderStorage v1.4.7.36

The reason why I posted every mod im using regarding 'Ender', is to notify you of everything I am using regarding Ender.

Picture Below.
http://i.imgur.com/r1dOhRP.png

**Comment by AnrDaemon** [comment]
Please don't lie to us.
If you only did what you said you did, this absolutely can not happen.
If you updated mods, you should know, which ones you updated and why.
Before you clear your head and start speaking truth, …

**Comment by tterrag1098** [comment]
Actually this *can* happen. You updated WAILA Plugins, the changelog for which *clearly* states that it has moved to use EnderCore. For now the only place to get it is jenkins. Though I'd suggest you hold off on updating if you aren't using dev-channel mod versions.

**Comment by AnrDaemon** [comment]
If he did not do anything at all, other than playing MC and going to sleep through the night, this absolutely can not happen. Computers don't work by magic. If they do something, YOU allowed them to do it.
