### ISSUE TITLE
Connecting an Item Conduit causes world corruption

### ISSUE THREAD

**Issue by Kane122** [SleepyTrousers/EnderIO#2623]
I have found a reproducible crash which seems to be related to an interaction between EnderIO and Thermal Expansion. Placing an EnderIO Item Conduit on top of a Thermal Expansion Phytogenic Insolator and setting the machine's output slot to "open but colourless" (whatever is it's actual name) causes a crash and corrupts the world. Here is the crashlog I get when I try to load the corrupted world.

http://pastebin.com/5AwLcMZi

Note that this was a test world, with only the latest versions of Cofhcore, Thermal Foundation, Thermal Expansion and EnderIO installed.

I don't know which of the mods is causing the issue, but I figured I should probably post it here.

**Comment by tterrag1098** [comment]
This is a TE bug
