### ISSUE TITLE
not possible to craft a broken spawner villager

### ISSUE THREAD

**Issue by wleds** [SleepyTrousers/EnderIO#2625]
not possible to craft a broken spawner villager in the binder soul will I put a vial villager soul I can not meter the broken spawner is inversely

I try to change the config file user but still not possible I can make you this video you want. I esseiller to add a mob in disable it is these well disable

sorry for the quality of translation

**Comment by MatthiasMann** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/2581

**Comment by wleds** [comment]
ths it works
