### ISSUE TITLE
Enchanter uncraftable

### ISSUE THREAD

**Issue by cloakable** [SleepyTrousers/EnderIO#2626]
![2015-07-02_18 48 04](https://cloud.githubusercontent.com/assets/1534182/8483768/f293b072-20ea-11e5-8d89-7200507f9158.png)
EnderIO 2.3.0.398, picture says it all really

**Comment by b0bst3r** [comment]
lol recipe is wrong it's 3 ingots across the middle and 1 at the bottom middle
