### ISSUE TITLE
EnderCore not working

### ISSUE THREAD

**Issue by TimeToStryke** [SleepyTrousers/EnderIO#2629]
I recently installed EnderIO via the ATLauncher and it says that I need to install EnderCore. If I'm correct, EnderCore should automatically install or is in built with EnderIO which doesn't make sense then. I tried deleting EnderIO but so it won't need EnderCore but even though EnderIO doesn't exist, it's still says I need EnderCore.

**Comment by MatthiasMann** [comment]
The recent EnderIO 2.3 beta builds require EnderCore. In addition to that other mods have started to port from ttCore over to EnderCore.

But without log files I can't say anything to your situation.

**Comment by TimeToStryke** [comment]
Here is the log. I'm using a modified version of an instance.
http://paste.atlauncher.com/view/7a9bba4c

**Comment by TimeToStryke** [comment]
Actually nevermind. I found endercore on curse and I installed it separately and it fixed it.
