### ISSUE TITLE
Rendering of glass facades bugged ?

### ISSUE THREAD

**Issue by mindforger** [SleepyTrousers/EnderIO#2633]
when i place glass facades and glass blocks, the rendering is derped up
the lower 3 glass are regular glass, the upper 3 are glass facades, the regular glass is rendered behind the facades, thats not vanilla like :(
http://puu.sh/iMUDL/5e1a9753e9.jpg from below 
http://puu.sh/iMUEe/9ad3d5f8b6.jpg from above

**Comment by tterrag1098** [comment]
There's nothing I can really do about this, vanilla glass decides when to render the sides, and I cannot override that behavior.

**Comment by mindforger** [comment]
meh, okay :P i just thought i might mention it ... i could probably move to other glass but because i use carpenters slopes on the "edges" there is no adequate looking glass that derps on carpenter blocks than the vanilla glass
