### ISSUE TITLE
Cant get wither skelectons to spawn in overworld

### ISSUE THREAD

**Issue by tubs5** [SleepyTrousers/EnderIO#2634]
ender io version: 2.2.8.381
Pack: modified FTB infinety
Config: https://gist.github.com/tubs5/43645b3551be8e02f6fc
If i am not mistaken this is the way to do it: http://imgur.com/a/GWLxA
I have not changed any the config option as I could not find it.

**Comment by MatthiasMann** [comment]
The config open "B:replaceWitherSkeletons" is set to false - so you can't make a wither skeleton spawner in the overworld. Which is also visible by the fact that the tool tip says "Skeleton" and not "Wither Skeleton" (or similar).
