### ISSUE TITLE
Startup Crash with latest BETA Versions

### ISSUE THREAD

**Issue by Shadowhunter82** [SleepyTrousers/EnderIO#2635]
My Client / Server is crashing with the last 2 EnderIO Beta 2.3.0 -398 + 399 Versions
The client crashed with my full game client and the small test client (only enderio, ender core, ender zoo and NEI)

Crashlog full client: http://pastebin.com/W5nnZy0g
Crashlog test client: http://pastebin.com/c1eYfA3h

**Comment by MatthiasMann** [comment]
Your EnderCore is too old - you need at least version 1.10_alpha

**Comment by Shadowhunter82** [comment]
thx 
I didn´t look in the jenkins for new endercore versions
