### ISSUE TITLE
Can't use alloy ingots without accessing internal classes

### ISSUE THREAD

**Issue by XFactHD** [SleepyTrousers/EnderIO#2636]
I am trying to make an addon to provide aditional recipes for EnderIO's alloys. To access the alloy ingots, I use GameRegistry.findItem("EnderIO", "ingotConductiveIron"). "ingotConductiveIron" is replaced with the respective alloy.
Because the GameRegistry doesn't find the items, Thermal Expansion throws this error for each recipe:
http://pastebin.com/DETa4AsS

Using the OreDictionary is also not possible, because it can't return a single item.
The code of my mod can be found here: https://github.com/XFactHD/EIORecipesTEInductionSmelter

**Comment by MatthiasMann** [comment]
Looking up the items via the game registry should work. Same as using the oredict. After all the recipe system of EnderIO is doing the same thing.

**Comment by tterrag1098** [comment]
The name of the ingot is not `ingotConductiveItem` it's `itemAlloy`

**Comment by XFactHD** [comment]
I tried it again, this time with an additional helper class (http://pastebin.com/ihRjkUh4) but it still doesn't work.

**Comment by tterrag1098** [comment]
You are making sure to do this after EnderIO has loaded, yes?

**Comment by XFactHD** [comment]
If it is "if (Loader.isModLoaded("EnderIO")) {MetaItemGetter.init}" what I need to use, then I am making sure it is loaded or do I need another function to do this?

**Comment by tterrag1098** [comment]
You need to make sure your mod loads after EnderIO, OR do recipe stuff in init, not pre-init.

**Comment by XFactHD** [comment]
Now it works, thank you for your help.
