### ISSUE TITLE
Capacitor Banks and Draconium Blocks

### ISSUE THREAD

**Issue by Hypocrisy** [SleepyTrousers/EnderIO#2640]
EDIT: I just realized it is all Capacitor Banks.

If you shift click a stack of Draconium Blocks instead of dropping them in with a mouse you can put an entire stack of them into a Capacitor Bank and charge them all at once for the cost of one.

**Comment by tterrag1098** [comment]
This is DE's fault, we had the same issue with stacked capacitor bank items in the past, so we blocked charging of them when they are stacked. Report this to @brandon3055
