### ISSUE TITLE
Connected textures

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#2641]
I have chisel mod installed and it has some blocks with connected textures. But the connection is not appearing with EnderIO Facades painted to same block.

Example:
I have Marble (with dent) placed in ring and I put eIO conduit facade painted with same Marble, it does not connect the texture to normal Marble (with dent). eIO conduit facades are correctly connecting to other eIO conduit facades.
Screeshot:
![2015-07-06_16 15 53](https://cloud.githubusercontent.com/assets/4236895/8524246/5087cc6a-23fa-11e5-9eb6-bb0428991c57.png)
On left are all blocks Marble with Dent
On right the outside is made with Marble with Dent and the inside is made of 2 Conduit Facades.

Same is happening with Extra Utilities blocks which have connected textures

**Comment by tterrag1098** [comment]
This was a chisel issue. Update to 2.4.1

**Comment by JasonMcRay** [comment]
I have chisel 2.4.1

**Comment by JasonMcRay** [comment]
i assume since with Chisel blocks it was Chisel issue; it does go with ExU the same?

**Comment by tterrag1098** [comment]
@JasonMcRay Please double check that you have Chisel 2.4.1 and CTMLib 1.0.1.5

**Comment by JasonMcRay** [comment]
I have Chisel 2.4.1, I do not have CTMLib. I thought it is bundled with Chisel 2.

Tried to install CTMLib, it conflicts with Chisel
![2015-07-06_16 47 35](https://cloud.githubusercontent.com/assets/4236895/8525007/bbe42ab8-23fe-11e5-8f90-c4f4ad47dd39.png)

**Comment by tterrag1098** [comment]
Check the version in the mod list

**Comment by JasonMcRay** [comment]
As I said I have Chisel 2.4.1.40. If I add CTMLib mod, it shows the conflict above

**Comment by tterrag1098** [comment]
Check the mod list for the ***CTMLib version***

**Comment by JasonMcRay** [comment]
I do not have any CTMLib. When i download it from http://www.curse.com/mc-mods/minecraft/232154-ctmlib and put it into mods folder i get the conflict.

**Comment by tterrag1098** [comment]
You do have it. It is included with Chisel 2. Look at the ingame mod list and tell me what version it is.

**Comment by JasonMcRay** [comment]
Oh sorry. I must have misunderstood you. CTMLib 1.0.1.5

**Comment by tterrag1098** [comment]
And, what EnderIO version?

**Comment by JasonMcRay** [comment]
I am really lazy today to get all necessary information in one go, sorry about that.
eIO: 2.2.8.381

**Comment by tterrag1098** [comment]
I have no idea what could be causing this, and no one else can reproduce it.
