### ISSUE TITLE
Heavyweight Dupe Bug Rematch: Magnet Vs. Baubles.. coming soon to PPV

### ISSUE THREAD

**Issue by srs-bsns** [SleepyTrousers/EnderIO#2642]
Forge:
* Forge10.13.4.1448

Mods loaded:
* EnderIO-1.7.10-2.3.0.399_beta
* EnderCore-1.7.10-0.0.1.12_alpha
* Baubles-1.7.10-1.0.1.10
* CodeChickenLib-1.7.10-1.1.3.138
* CodeChickenCore-1.7.10-1.0.7.46
* NotEnoughItems-1.7.10-1.0.5.111

EnderIO Configuration:
* B:magnetAllowInBaublesSlot=true
* B:magnetAllowDeactivatedInBaublesSlot=true

Game type:
* SSP (not tested on a remote server, so there may or may not be other underlying synch issues related.)

This is related to some previous issues with a magnet in a baubles slot, but this one involves item duplication and item destruction.

This Issue is a bit complex and I have a bad habit of creating walls of text, so you should pour yourself a nice cold drink before reading. Also, there is a power issue associated with a magnet being in a baubles slot.. it is likely a separate issue (and may partially, or entirely, be intended behavior) so I will open a separate issue for it.

## The issue:
- Toggling a disabled magnet **ON** (with hotkey) while in a baubles slot causes an activated clone (not a true duplicate at this point, see below) of the magnet to be placed into the hotbar destroying any item that was in that hotbar slot. (RIP in peace TiCon Pickaxe of Doom that I spent weeks gaining XP on :rage:)
- The original magnet remains in the baubles slot and becomes 'activated.' (Any magnet put into a baubles slot, regardless of being active or not, acts like it is active and uses power, so in this case it merely starts glowing.)
  - The hotbar slot that the clone goes into depends on the baubles slot that the original is in as per **S:magnetBaublesType**. If this behavior is a bug it's surely Baubles' fault?
  - Bauble Amulet --> Hotbar Slot 1
  - Bauble Ring1 --> Hotbar Slot 2
  - Bauble Ring2 --> Hotbar Slot 3
  - Bauble Belt --> Hotbar Slot 4

- Initially, after the clone is made:
  - If the (new) magnet in the hotbar is toggled **OFF** by sneak+right click, or if it is put directly into an external inventory (chest, cap bank, etc), then the clone will become a true duplicate with it's own separate power drain and will toggle individually with the hotkey afterwards, **OTHERWISE...**
  - While both magnets are active, they will BOTH use 3x the power from the setting **I:magnetPowerUsePerTickRF**... 2x for the magnet in the hotbar (part of the separate power issue) + 1x for the one in the baubles slot.
  - Using the hotkey again appears to toggle both magets off, however, BOTH will show a normal power drain associated with a single active magnet (the one in the baubles slot?).
  - They can continue to be toggled on and off together using the hotkey and both continue to drain the same amount of power.
  - If either magnet is moved anywhere else in the player's inventory immediately after clone creation then they will start acting like individuals, but the magnet that wasn't moved will no longer be able to be shift+clicked around in the inventory (drag&drop still works) and will disappear from existance if put into the hotbar and right-clicked or sneak+right-clicked, but will otherwise continue to function normally (can be moved (drag&drop only), recharged, toggled on/off with the hotkey.) Since I'm not currently able to test this on a remote server, I'm not sure how this would synch up in SMP, but at this point it seems the server considers one magnet to not exist or something, but the client isn't aware of it.. perhaps some pointer confusion?. The fact that the 'broken' magnet still seems to function is odd though, so it has to exist to some degree.

## Possible solutions:
1. Quick and Dirty: This issue pretty much only exists because of **B:magnetAllowDeactivatedInBaublesSlot**. If it is set to **false** then a deactivated magnet could never be in a baubles slot to begin with, so no dupes can be created. Furthermore, an activated magnet in a baubles slot can't be deactivated with the hotkey. Removing this setting and only allowing an activated magnet in a baubles slot makes this issue go away. However, players may want the option of being able to toggle the magnet on/off while it's in a baubles slot.

2. Remove the hotkey to toggle the magnet on/off. Since the magnet is required to be in the hotbar for it to work normally anyways, it doesn't really add much convenience. Selecting the slot it's in and sneak+righclicking isn't much harder. A hotkey toggle only really makes sense when it's not that convenient to do so, such as having to go into one's inventory to free up a hotbar slot, move the magnet to the slot, turn it on/off, then back into the inventory to remove the magnet and put the previous item back in that hotbar slot... that's when a toggle key makes sense.

3. Remove Baubles support completely and allow a magnet to be toggled on/off with the hotkey while it's in the normal inventory (config option?) and not just the hotbar, with some sort of feedback informing the user that the magnet is toggled, like when toggling speed or step assist on DS armor.

4. (More of a suggestion than a solution, and perhaps in addition to 3 above) Add an additional upgrade to a piece of DS armor to add a magnet + 30 levels of XP giving that piece of armor a magnet ability that can be toggled on/off with a hotkey. This solves the issue and gives players the option of having a toggleable magnet without it cluttering up their inventory, which is the whole purpose of making it a bauble to begin with. I suggest DS leggings, because the helmet already has enough upgrades, the boots seem like a poor choice for such an upgrade (makes no sense), and although the chestplate might seem like the best choice, there are too many other items from other mods that people will be using in their chest slot (jetpacks, flux packs, camel packs, etc..) Atleast with leggings it can be accepted as being a belt accessory or a cod piece:
![cod piece](http://media.giphy.com/media/3qgSQVx6FrwEo/giphy.gif)

**Comment by MatthiasMann** [comment]
This has been fixed in build 400 of EnderIO now available on the CI server.
