### ISSUE TITLE
Magnet power use issues.

### ISSUE THREAD

**Issue by srs-bsns** [SleepyTrousers/EnderIO#2643]
Forge:
* Forge10.13.4.1448

Mods loaded:
* EnderIO-1.7.10-2.3.0.399_beta
* EnderCore-1.7.10-0.0.1.12_alpha
* Baubles-1.7.10-1.0.1.10
* CodeChickenLib-1.7.10-1.1.3.138
* CodeChickenCore-1.7.10-1.0.7.46
* NotEnoughItems-1.7.10-1.0.5.111

EnderIO Configuration:
* B:magnetAllowInBaublesSlot=true
* B:magnetAllowDeactivatedInBaublesSlot=true

Game type:
* SSP (not tested on a remote server)

## The issues:

1. An inactive magnet will work and use power when put into a baubles slot.

2. An active magnet in the hotbar, or in the normal inventory when **B:magnetAllowInMainInventory=true**, uses twice the power that it should. 2x whatever **I:magnetPowerUsePerTickRF** is set to. This is not contingent on **B:magnetAllowInBaublesSlot=true** and **B:magnetAllowDeactivatedInBaublesSlot=true**

I'm reporting these issues together because they seem like they could be related to the same code.

**Comment by MatthiasMann** [comment]
This has been fixed in build 400 of EnderIO now available on the CI server.
