### ISSUE TITLE
 Spawner dupe bug Drac Evo icw EnderIO

### ISSUE THREAD

**Issue by vendris-DeVcoFTB** [SleepyTrousers/EnderIO#2644]
Greetings,

We are encountering a bug with Draconic Evolution’s ‘Draconic Staff of Power’ in combination with EnderIO.

If the staff is set to ‘safe’ mode, its possible to duplicate vanilla spawners.

Clicking any block with AOE enabled in safe mode, in the reach of the spawner, results in an error message that operation has been canceled because a tile entity had been detected.

Once this safety has engaged, you can keep clicking (left mouseclick) with the staff on the spawner, and it will dump a broken EnderIO version of the spawner.

http://puu.sh/iQG7S/c67e26f7a4.jpg

Modpack used was Infinity 1.7, on the FTB Launcher.

-Vendris DeVcoFTB Staff.

**Comment by MatthiasMann** [comment]
Which EnderIO version?

**Comment by vendris-DeVcoFTB** [comment]
Infinity is currently sporting EnderIO 1.7.10-2.2.8.381 and Draconic Evolution 1.7.10-1.0.1c

**Comment by JosephRymer** [comment]
I haven't encountered any issues with that version but if i do i leave a comment

**Comment by MatthiasMann** [comment]
@vendris-DeVcoFTB try with the latest EnderIO 2.3 beta build - the part for dropping spawners has been changed some time ago.

**Comment by tterrag1098** [comment]
Will close soon if no response is given
