### ISSUE TITLE
Capacitor Bank + ComputerCraft problem

### ISSUE THREAD

**Issue by unpure** [SleepyTrousers/EnderIO#2645]
Hey there.
I'm currently trying to setup my reactor control with computercraft.
My script checks a connected capacitor bank and stops the reactor at 90% capacitor level.
It worked fine the last time i used it, but now i cant connect the capacitor bank.
For some reason its not possible to activate the modem connected to the capacitor bank.
Is there any known bug that i cant find? Or is there anything that has changed about that?

Sorry for my bad english, i hope its not to hard to understand.

**Comment by tterrag1098** [comment]
Capacitor Banks do not support CC integration, but the mod Computronics allows that. Perhaps you uninstalled that mod between now and the last time you tried?

**Comment by unpure** [comment]
I never had Computronics installed.
