### ISSUE TITLE
Fluid pipes without liquid cannot connect to fluid pipes with liquid

### ISSUE THREAD

**Issue by ZdudeXY** [SleepyTrousers/EnderIO#2646]
Not sure if this is supposed to happen but when you try to place a fluid conduit new to one that,
lets say, has lava in it, they wont connect. This is a pretty big problem because if you are setting up a system and make a mistake, it could mean you have to break the whole thing.

**Comment by tterrag1098** [comment]
They don't connect automatically to make it easier to place parallel pipes for different fluids. All you have to do is wrench to force the connection.

**Comment by ZdudeXY** [comment]
Thanks man!
