### ISSUE TITLE
Stall reports and EnderIO

### ISSUE THREAD

**Issue by utoc** [SleepyTrousers/EnderIO#2648]
I have a very strange issue occuring and I'm not sure how to report this; so I'll start with EnderIO.  My SMP world has been progressing a bit; we have several active players and currently I restart the server twice daily to keep the memory leaks to a minimum.  We have a special case that is just now starting to happen.  If three hours pass from the time the server restarts to the time someone logs in, the server will stall upon the next login to the point where I must Control+C to get any response.  

Here are the stall-reports:

1) http://pastebin.com/1baVur0X
2) http://pastebin.com/1QcY3Vnt
3) http://pastebin.com/PFavh9NS
4) http://pastebin.com/rhieWUpT
5) http://pastebin.com/t36yc4dH
6) http://pastebin.com/fVfX4u7M

I spoke with Player about his stall reports and he told me that the mod listed under SERVER THREAD is usually the mod that has gotten hung up.

Part of the issue is covered here: https://github.com/SleepyTrousers/EnderIO/issues/1959 I can confirm with ChinkenChunk's /chunkloaders command that there are a lot of places on the map without chunkloaders that are loaded without tickets.  The one unifying feature of these places are that we all love our EnderIO conduit bundles.  This could be a factor in the stalling.

What is unusual is that at my base, I have completely gotten rid of EIO conduits and yet still, as soon as I connect after the three hour window from a restart, the server will stall.  

I am running the [follow mods](https://www.reddit.com/r/BBQSauce/wiki/modlist)
EnderIO 1.7.10-2.2.8.381
FML 1448

I apologize that I don't have more information to give you.. let me know any troubleshooting steps I can take to help you guys in any way.

**Comment by tterrag1098** [comment]
Could you update to a beta build and see if anything is resolved? It's hard to confirm such a vague issue unless you are on the latest code base.

**Comment by utoc** [comment]
Sorry it took so long, I was able to test this today using beta build 401 and Endercore build 12 alpha
Here is the stall report for today: http://pastebin.com/5euy0HdN

**Comment by tterrag1098** [comment]
Do you have large redstone conduit networks? See #1959

**Comment by utoc** [comment]
We don't have any large redstone conduit networks on the server, most redstone conduit bundles are limited to maybe 25-30 redstone conduits, however, most of the people using those redstone conduits also have 200+ other conduits (power, item, fluid).

#1959 definitely plays a part in this issue, the unique characteristic of my report was that the server is actually going in to a deadlock (or whatever the technical term is) because of this and it only happens if no one logs in for three hours after a restart.  If you like, I can close this issue and add it to #1959.  Let me know, whatever makes your life easy :)
