### ISSUE TITLE
Update Eio Armor appearance. 

### ISSUE THREAD

**Issue by Badcholo** [SleepyTrousers/EnderIO#2650]
While i like vanilla. I have made Eio armor the top pvp tier armor on my server. It would be nice if it had a more futuristic or epic look to it, rather than a colored vanilla armor. I really like their abilities and love the Eio anvil to enchant extra stuff onto the armor, but the appearance doesn't fit the abilities.
Thank you for your time. I was hoping for something like power armor or Iron man suit look. I'll post some ideas if i find any.

**Comment by AnrDaemon** [comment]
Go ahead and make it.
Minecraft supports resource packs since prehistoric times, and it now even supports server-side packs.

**Comment by tterrag1098** [comment]
The armor has already been retextured in the beta builds.

**Comment by Ikabodo** [comment]
https://www.patreon.com/posts/1681637

This looks exactly like what you are looking for.

**Comment by Badcholo** [comment]
I don't like the skirt, Everything else looks pretty cool.

**Comment by Unrepentant-Atheist** [comment]
I like the skirt! Do want.
