### ISSUE TITLE
Spawner exact copy

### ISSUE THREAD

**Issue by laci200270** [SleepyTrousers/EnderIO#2651]
It would be great if powered spawner support exact copy,because wither skeleton spawning(now when i spawn wither skeletons it simply spawn normal skeletons) I request this because I not want to put MFR just for this to my pack

**Comment by MatthiasMann** [comment]
EnderIO has an option to replace wither skeletons with it's own version - which can then be spawned. As an alternative you can put a skeleton spawner in the nether.

**Comment by tterrag1098** [comment]
Exact copy is very abusable, even though MFR provides a blacklist, there are still ways to abuse it in almost any pack out there. I don't want to open that can of worms. Do what @MatthiasMann said and spawn them in the nether.
