### ISSUE TITLE
Item Conduits not stops working

### ISSUE THREAD

**Issue by DarknessShadow** [SleepyTrousers/EnderIO#2652]
When the items conduits are connected to a block and configured to insert/extract it stops working when the blocks changes (mfe to mfsu with upgrade) and you have to break the item conduits and place it again to fix it.

Tested on a server with Infitech2 modpack v.3.1.3
EnderIO-1.7.10-2.2.8.381
industrialcraft-2-2.2.745-experimental

**Comment by AnrDaemon** [comment]
Unless you can reproduce it with 2.3, I don't think your report is useful.

**Comment by tterrag1098** [comment]
Seems like IC2's fault
