### ISSUE TITLE
Combustion Generators

### ISSUE THREAD

**Issue by MysticalBacon** [SleepyTrousers/EnderIO#2653]
Hello,

I have a performance issue with the combustion generators. 
I have about 200 of them in my base and everytime i look at them my frames drop from 60 to 30fps.
I planned to have about a thousand of them but this cancels my plan :(

**Comment by b0bst3r** [comment]
Which version?
Are you using Fastcraft or Optifine?

**Comment by MysticalBacon** [comment]
Version: 1.7.10 - 2.2.8.381 
Yes, fastcraft is enabled but optifine is not.

**Comment by tterrag1098** [comment]
Are you playing singleplayer or multiplayer?

**Comment by MysticalBacon** [comment]
Singleplayer

**Comment by tterrag1098** [comment]
Just tested ~200 combustion generators, no discernable FPS difference.

**Comment by b0bst3r** [comment]
Hardware spec?
Java RAM?
ResourcePack?

**Comment by MysticalBacon** [comment]
Resource pack: unity complete 1.2.0
Ram: 4gb
Cpu: Intel core i5 3470 overclocked to 4ghz
Gpu: Nvidia geforce gtx 660 OC 

Picture looking away
![2015-07-14_23 10 06](https://cloud.githubusercontent.com/assets/13334390/8685261/c4f78ab6-2a7d-11e5-9a33-dffb9e0f4b0b.png)

Picture looking to it
![2015-07-14_23 10 09](https://cloud.githubusercontent.com/assets/13334390/8685280/db1fd528-2a7d-11e5-8988-3f536fce7de6.png)

**Comment by tterrag1098** [comment]
Disable the experimental model....

**Comment by MysticalBacon** [comment]
experimental model?

**Comment by tterrag1098** [comment]
B:useCombustionGenModel=true

Change that to false in EnderIO.cfg. The default is false.

**Comment by MysticalBacon** [comment]
Still not any better
![2015-07-14_23 33 01](https://cloud.githubusercontent.com/assets/13334390/8685695/c1825458-2a80-11e5-93d6-9dfb6108e4d0.png)

I can send you the savegame if you want

**Comment by tterrag1098** [comment]
Honestly the best thing you could do is profile the game with Opis or JVisualVM

**Comment by MysticalBacon** [comment]
So i tried Opis and still haven't found the cause and i think you were right: it isn't caused by the generators, sorry about the inconvenience. 
I dunno whats going on here and honestly i gave up.
I tried making a reddit post https://www.reddit.com/r/feedthebeast/comments/3e0agv/weird_frame_issues/ 
but no answers.
The lag has officialy won.
