### ISSUE TITLE
Unbreaking Enchantment on Tools

### ISSUE THREAD

**Issue by NullMagic** [SleepyTrousers/EnderIO#2654]
I know this was discussed in issue 1665 (https://github.com/SleepyTrousers/EnderIO/issues/1665), but I don't really feel the problem was fixed, the issue isn't with the tools in question, it's with the way your code is applying the damage effect. Even vanilla tools with Unbreaking x are still being damaged, the issue is that your code makes no allowance for any type of enchantment, including the regular Unbreaking I - III, it simply straight up does 1 damage to the tool regardless of any modifiers or effects upon it. Yet just a few lines down (291 through 294) it's clear that you are able to get enchantment effects because you do so for looting and fortune, the very simple answer to this issue would be to add a line that checks for the level of Unbreaking enchantment, and then generates a Random Number from 1 to 100, and if a number from a certain range is generated (range size depending on enchantment level) it simply redefines the int used to damage the tool as 0 instead of 1.

The calculation for unbreaking is fairly simple for most items (except armor which we won't go into right now) being a (100/(enchantment level +1))  percent chance of doing damage, so with a level of 0 you do damage every time (100% chance because 100/1 is 100), so the simplest answer would be for the number range to be 100/level+1 (if this were c++ it would look something like "if(Random > 100/(level+1))") meaning you don't even have to define a number range per level of enchantment, as the code will simply do it for you.

**Comment by tterrag1098** [comment]
Unbreaking handling is done by vanilla in `ItemStack.damageItem`, so it should be applied.

**Comment by NullMagic** [comment]
Hmmm that's odd, because at the very least it should have only a 9% chance (give or take some decimals) to damage a tool with Unbreaking X, yet it decreases with regularity in the farming station, at least in so far as I've seen. Perhaps I am simply terribly unlucky, I think this calls for more testing.
