### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by nobledogger** [SleepyTrousers/EnderIO#2655]
I am trying to use the Crafter to make Railway tickets (from railcraft). I add a golden ticket and a piece of paper to make the ticket, no problem. I have used the admin capacitor to provide the power, and linked the output to a chest to receive the completed item. I set the crafter to only work with a signal and added a button to the front. When I push the button, the game freezes every time. I am able to move, and all the sounds are still there, but I am unable to interact with anything and nothing is moving. I tested this a second time to make another item - Poppy to Rose Red dye, with no complications what so ever. I am using forge 10.13.4.1481, and Ender IO version 1.4.7.36, and , if needed, Railcraft 9.6.1.0. Not sure if there might be a mod conflict, or a version conflict, or just simply a bug. Thank you for your time.

**Comment by MatthiasMann** [comment]
Which EnderIO version ?!?

**Comment by nobledogger** [comment]
I am using forge 10.13.4.1481, and Ender IO version 1.4.7.36, and , if needed, Railcraft 9.6.1.0.

**Comment by MatthiasMann** [comment]
@nobledogger again - that doesn't make any sense - EnderIO 1.x was Minecraft 1.6.x or even older.

**Comment by nobledogger** [comment]
My apologies, I was looking at Ender Storage version. The Ender IO version that I am using is 2.2.8.381.

**Comment by Surrogard** [comment]
Hi,
same behavior here: the server freezes completely, no messages in the log no commands working on the admin console.
Used versions here: 
- Server: 1.7.10
- EnderIO 2.2.8.381
- Railcraft 9.6.1.0

**Comment by MatthiasMann** [comment]
The crafting has been fixed in the 2.3 beta.

**Comment by BlackAce21** [comment]
Not sure if it is related but crafting Melon Smoothies using Pam's harvestcraft and the juicer produces the same result in 2.2.8.381, if its the same cause and its fixed nothing to worry about, if not it might be worth looking at. Could be non-consumed items causing it -shrug- just want to make sure you know

**Comment by tterrag1098** [comment]
Any item which leaves itself in the crafting table will cause this issue

**Comment by MatthiasMann** [comment]
@BlackAce21 any report related to auto crafting based on 2.2.8 is useless - as the auto crafting has been completely rewritten.

**Comment by BlackAce21** [comment]
Excellent, thank you for the fast response ^_^
