### ISSUE TITLE
Killer Joe Texture Glitch with Extra Utilities Kikoku

### ISSUE THREAD

**Issue by angelnc1989** [SleepyTrousers/EnderIO#2657]
I'm not sure if it's on RWTema's end or yours:
http://imgur.com/a/fMY7U

All other swords I tried look normal.

**Comment by tterrag1098** [comment]
We can't accurately support swords with models, unfortunately. If I code support for this sword specifically, there is a very high chance it would not work with ANY other sword with a custom renderer.
