### ISSUE TITLE
Insulater Redstone Conduit lights up when placed next to freshly placed CC Computer

### ISSUE THREAD

**Issue by D3add3d** [SleepyTrousers/EnderIO#2658]
The title is self-explanatory... this is probably only visual bug, the connectors are set to In/Out(only other option is Disabled)
Screenshot:
![2015-07-17_22 24 00](https://cloud.githubusercontent.com/assets/1764903/8756435/8df003ac-2cd2-11e5-9e48-60930dcb9ca3.png)

Also as required by Player: using FastCraft - just FYI

**Comment by blarghhh** [comment]
this is not a visual bug but it is actually outputting a signal
