### ISSUE TITLE
Lead in a sag mill = nothing/ore lost

### ISSUE THREAD

**Issue by TheQuadShot** [SleepyTrousers/EnderIO#2659]
I'm running version .381
it will only produce some cobble, and the recipe show's lead in, some cobble out
putting the ore in the alloy smelter produces the ingot
![2015-07-18_16 19 47](https://cloud.githubusercontent.com/assets/11265900/8763894/dca99850-2d68-11e5-8959-2ae7b7a08a23.png)

**Comment by AnrDaemon** [comment]
The recipe clearly shows only cobble out.
Bring your modpack issues to the modpack author.

**Comment by tterrag1098** [comment]
This seems like a configuration problem, or maybe there is no such thing as lead dust in your pack? That's what the recipe should output.

**Comment by TheQuadShot** [comment]
I did,(https://github.com/K-4U/Hydraulicraft/issues/140) he said to bring it here (over irc).... there is lead dust in the pack

**Comment by b0bst3r** [comment]
Ask your server owner if this exists in config\enderio\sagmillrecipes_Core.xml

    <recipe name="LeadOre" energyCost="3600" >
      <input>
        <itemStack oreDictionary="oreLead" />
      </input>
      <output>
        <itemStack oreDictionary="dustLead" number="2" />
        <itemStack oreDictionary="dustSilver" chance="0.1" />
        <itemStack modID="minecraft" itemName="cobblestone" chance="0.15" />
      </output>
    </recipe>

Also ask him to check there's nothing in the SAGMillRedcipes_User.xml related to Lead.
Also check if this is the same in SSP with the pack you're using.

**Comment by TheQuadShot** [comment]
I'm running single player (I could bring up a dedicated server, but I don't think it will tell me much), 
Yes that recipe for lead is in the config, verbatim. 
There is nothing in the ...User.xml  file that relates to lead.
Hydraulicraft is the only mod I have that adds lead.
and I looked at the mod's source code and it looks to me (I don't know java very well) that he registers copper and lead the same way, and the copper works.

I can't make dust with his mod, as there is a bug that won't let me process any dust in his mod at this time. Which is why I'm trying to use the SAGMill as a sort of work around for now.

**Comment by MatthiasMann** [comment]
EnderIO does not add lead dust as an item - it uses the item which is registered as "dustLead" in the oredict - which in your case doesn't seem to be registered at all. So this is not EnderIO's fault.

**Comment by TheQuadShot** [comment]
Ok, sorry for my derp....
