### ISSUE TITLE
Staff of Travelling not working properly with Travel Anchors

### ISSUE THREAD

**Issue by TheChance** [SleepyTrousers/EnderIO#2660]
When I first placed travel anchors around my base, they worked fine. A couple days later, I began noticing the glitch depicted in this video http://youtu.be/WWEAUmR6G2c

I couldn't get it to happen while recording, but much of the time, I'll find a sweet spot with the cursor, such that the anchor will sort of flicker between red and its natural texture. If I time my right-click JUST right, I can catch it while it's flickering.

But the flicker isn't reliable, and the result of all this has been that the staff is nearly useless :\

We are running the current version of DW20 for 1.7. I couldn't point to a specific change in the base that might have precipitated this, as I've been building a LOT the past few days.

**Comment by Cherry** [comment]
This seems to be quite similar to https://github.com/SleepyTrousers/EnderIO/issues/1399 which I reported a while back. The hover-state seems quite unreliable and causes odd behaviour especially with the Ender IO block.

**Comment by tterrag1098** [comment]
this may be fixed under #2546 could you try to reproduce in the beta builds?

**Comment by XFactHD** [comment]
I am getting the same problem. When my frame rate is high it doesn't matter if the travel anchor is 10 or 50 blocks or more away. But if I have a frame rate between 10 and 20, the anchor does not turn orange at all or it flickers. At the same time I have solid 20 tps. So I don't think it has something to do with the issue that @Cherry nor the one that @tterag1098 mentioned.

**Comment by TheChance** [comment]
Apologies for the delay. It's on a server, so swapping versions is not so trivial, but I will clone the world to my computer and try it with the beta build as soon as I can get FTP access (should be a few hours). I'll report back ASAP.

**Comment by TheChance** [comment]
No change in the beta builds.

Before updating, I did manage to capture footage of the [flicker](https://www.youtube.com/watch?v=WUu3D9QVBW0).

**Comment by TheChance** [comment]
I realize it's been several months, but I've switched packs, and am still getting this behavior, so I thought I'd update. Now running DNS Techpack 7.7.2 for MC 1.7.10, with EnderIO 2.2.8, all on Java 1.8. I'm happy to provide any further info to make it easier to repro.

It seems to be 100% tied to frame rate. When my frame rate dips below 10fps, the Staff stops working with Anchors entirely. With a frame rate between 10-20fps, the Travel Anchor flickers as described above. As soon as my frame rate hits 20fps, the flickering stops and the Staff works normally.

It's not really game-breaking, since I usually have a decent frame rate outside of my base, and inside the base I can just jump from anchor to anchor. Plus, with practice, I've gotten REALLY good at nailing the flickering Travel Anchor! Still, it's clearly not your intention, so I wanted to update.
