### ISSUE TITLE
Conduits connecting where they should not

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#2661]
EnderIO conduits are connecting to the blocks they should not connect. For example it visualy connects Fluid Conduit to GregTech Cable. Not sure if its something that needs to be taken care of on your side on GT side. So I am reporting this on both issue trackers
![2015-07-19_23 11 50](https://cloud.githubusercontent.com/assets/4236895/8767938/5929aa5e-2e6e-11e5-9646-32a0e52610e3.png)+

GT issue: https://github.com/Blood-Asp/GT5-Unofficial/issues/92

**Comment by MatthiasMann** [comment]
If the tile support fluid interaction - then the conduits will by default connect.

**Comment by tterrag1098** [comment]
To add on to that...The fluid API provides no way to "validate" a connection. Just disconnect the conduits manually.

**Comment by DarknessShadow** [comment]
The ender fluid conduits connects to me smart fluix cable

<a href="http://imgur.com/AH9yx1Z"><img src="http://i.imgur.com/AH9yx1Z.jpg" title="source: imgur.com" /></a>
EnderIO-1.7.10-2.2.8.381
appliedenergistics2-rv2-stable-10

**Comment by MatthiasMann** [comment]
@DarknessShadow if you would have read the answer in this issue so far - then you would know that this is nothing which can be changed.
