### ISSUE TITLE
Checking for redstone power every tick

### ISSUE THREAD

**Issue by unpairedbracket** [SleepyTrousers/EnderIO#2665]
TileElectricLight checks for redstone power using the world method getStrongestIndirectPower every tick. This is firstly quite inefficient, and secondly causes issues with chunkloading.

When there is an Electric Light placed on the inner boundary of a chunkloaded area (i.e. in a chunkloaded chunk, directly adjacent to a block in a non-chunkloaded chunk), this method (being insensitive to whether blocks are loaded or not) attempts to check for redstone power in blocks that have become unloaded, and causes any adjacent chunks to load again as soon as they are unloaded. Because chunk loading (in this instance) is synchronous, and unloading is async, this causes the new chunk instance to be loaded and new TileEntities to be created before the old chunk instance's TileEntity unload methods have been called. This can cause pathological behaviour in some blocks, namely aidancbrady/Mekanism#2733.

I believe that vanilla redstone mechanics require (due to vanilla redstone not using TileEntities) any redstone update to be accompanied by a block update, so it should be safe to cache the value of isActivated (or at least the return value of hasRedstoneSignal), and only recalculate it on block update.

**Comment by tterrag1098** [comment]
Thanks for the detailed report, fixed :)
