### ISSUE TITLE
Stained clay in SAG mill

### ISSUE THREAD

**Issue by pacthchristensen** [SleepyTrousers/EnderIO#2666]
I am trying to add stained clay to the SAGMillRecipes_User.xml file. I basically just want it to work like the normal clay block. I added the following to my config but only the white colored ones will go into the machine. How do I get it to do all the colors. I had to take the less than signs off the front to get it to show up in the post

	recipe name="stained_hardened_clay" energycost="6500"
     input>
        itemStack modID="minecraft" itemName="stained_hardened_clay" />
      /input>
      output>
        itemStack modID="minecraft" itemName="clay_ball" number="2" />
        itemStack modID="minecraft" itemName="clay_ball" number="1" chance="0.2" />
      /output>
  
I am probably doing something wrong but I did know if this was a bug or what. Any suggestions would be great.
Thanks
Patch

**Comment by pacthchristensen** [comment]
Ok for some reason it is not posting the recipe
	<recipe name="stained_hardened_clay" energyCost="6500" >
      <input>
        <itemStack modID="minecraft" itemName="stained_hardened_clay" />
      </input>
      <output>
        <itemStack modID="minecraft" itemName="clay_ball" number="2" />
        <itemStack modID="minecraft" itemName="clay_ball" number="1" chance="0.2" />
      </output>
    </recipe>

**Comment by tterrag1098** [comment]
You can use `itemMeta="*"` to allow all damage values (in the input tag)

**Comment by pacthchristensen** [comment]
Sweet thanks I will try that!

**Comment by pacthchristensen** [comment]
That worked! Thank you so much. Thanks for all your hard work on this mod. You guys need a pateron  page or a donate button.
