### ISSUE TITLE
Apiarist's Pipe/Item Filter

### ISSUE THREAD

**Issue by mysticdreamer76** [SleepyTrousers/EnderIO#2667]
Hi,

(I can't seem where to find the spot to add the suggestion label to this, sorry in advance).

The apiarists pipe in forestry for buildcraft pipes allows for separation of bees based on species. I would prefer to use your pipes, as they seem less laggy, more efficient. However, the current item filters in place seem to only allow for separation based on "bee/not bee", where I would love it to be based on "drone", "princess", "meadows/meadows", "meadows/forest", etc etc. Combined with the priority mode(s)  you already have, it would be quite an awesome addition. 

http://ftbwiki.org/Apiarist's_Pipe

Thank you for your consideration.

**Comment by CaptiveCreeper** [comment]
That would be really cool.  I also would much rather prefer enderio's conduits to really any piping system but when dealing with bees am stuck with build craft pipes.  Would love to see this happen
