### ISSUE TITLE
2.2.8 Wither Skeleton PoweredSpawner RF Consumption low.

### ISSUE THREAD

**Issue by jiji110** [SleepyTrousers/EnderIO#2668]
Hi

As title, Wither Skeleton PoweredSpawner consume RF low regardless of config file( PoweredSpawnerConfig_Core.json ) setting multiplyer at 20.
It consumes only 160 RF/t without any capacitor.
I want to increase by 1500 RF/t to take the game balance.

( I understand that the development EnderIO 2.2.* is done.
However I want to know the solution of this problem, if it exists. )

**Comment by tterrag1098** [comment]
Wither skeletons are not their own entity...they are just variants of normal skeletons. So you cannot set their multiplier separate from normal skeletons.

**Comment by jiji110** [comment]
Thanks for reply.

Is it applied in case of Wither Skeleton replaced by EnderIO?

**Comment by tterrag1098** [comment]
Yes

**Comment by jiji110** [comment]
i see, thanks.
