### ISSUE TITLE
AE2 Devices aren't picking up channels.

### ISSUE THREAD

**Issue by jtgraphic** [SleepyTrousers/EnderIO#2669]
I originally posted this as an issue to AE2: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1737

This is my original post there:

>I *think* this might be related to the distance from the controller, which is about 80 blocks.

>Here is a video of the behavior: http://screencast.com/t/SOHUceuRd

>Basically at one point along the cable they will pick up a channel, but one block farther, they won't. The cable they pick up a channel on is the 77th and the one they don't is the 78th.

>There is cable from both Ender IO and AE2 in this chain. It's dense cable until the 68th section and regular cable from there.

>This is TPPI2 0.1.5, which has AE2 rv2-beta-28 I think.

>I am not providing a crash log because there is no crash.

>Here are some images of the same issue if you don't want to download the video:

>http://screencast.com/t/Xs1hmwrhrW
>http://screencast.com/t/si62eMNvp4YZ

>Interestingly, those are from last night and are occurring on the 76th and 77th cable. I'm not sure if this is even a bug, but the people at /r/feedthebeast made comments that made me think it might be.

I updated to `rv2-stable-10` as they recommended and the issue persists.

Per a thread on Reddit that I started, I ran an AE2 dense cable the length from my controller to the issue and it resolved. (Thank you /u/MrGrey1)

The Reddit thread is here:

https://www.reddit.com/r/feedthebeast/comments/3eei9y/is_there_a_length_limit_on_me_cable/

**Comment by tterrag1098** [comment]
I mean...the network seems to stop dead BETWEEN ME CABLES, not EIO ones...I honestly have no clue how I could even cause this issue if I wanted to. How could our conduits 3 blocks away be messing with these? I'm at a loss...AE2 has a mind of its own and at this point I'm tired of dealing with it. It would also be nice if one of the AE2 devs would comment...

**Comment by jtgraphic** [comment]
Is there a place I can send a copy of the world?

**Comment by jtgraphic** [comment]
Ok, so I've got it working. I've tried a bunch of stuff, so I can't be sure what changed it. I *think* what might have done it is that I replaced every single cable in the chain. Update issue somewhere along the way?
