### ISSUE TITLE
Wireless Charger forcing chunks to stay loaded when powered

### ISSUE THREAD

**Issue by RoyCurtis** [SleepyTrousers/EnderIO#2671]
When a Wireless Charger has power in its buffer, it forces its chunk to always stay loaded. This is regardless of any chargable machinery or items in its vicinity, or if a redstone signal turns off the wireless charger.

This causes surrounding chunks to load by other means such as conduits and machinery from other mods, which then become unloaded during auto-save and immediately loaded again by the Wireless Charger keeping the chunk alive.

# Details

## Discovered on

* Direwolf20 1.7.10 1.5.0 and 1.6.1 live server
* Forge 10.13.4.1448
* [EnderIO 2.2.8.381](http://minecraft.curseforge.com/mc-mods/64578-ender-io/files/2238375)

# Reproduction

## Testing environment

*Edit: Re-tested without Thermal suite*

* Forge 1.7.10 10.13.4.1448
* [EnderIO](http://ci.tterrag.com/job/EnderIO/) 2.3.0.403_beta
* [EnderCore](http://ci.tterrag.com/job/EnderCore/) 0.0.1.13_alpha
* [ChickenChunks](http://chickenbones.net/maven/codechicken/ChickenChunks/1.7.10-1.3.4.19/) 1.3.4.19 & [CodeChickenCore](http://chickenbones.net/maven/codechicken/CodeChickenCore/1.7.10-1.0.7.46/) 1.0.7.46 

## Steps

1. Create a flatland creative world with cheats enabled
2. Execute `/tp 0 8 0` and then `/setworldspawn` (keeps spawn chunks away from testing areas)
3. Execute `/tp 1000 8 1000`
4. [Place an EnderIO wireless charger on the ground, with a Creative Capacitor Bank next to it](http://i.imgur.com/JsEtrK5.png)
5. Execute `/tp 0 8 0`
6. Press ESC to open the main menu and force a chunk purge
7. Resume game and execute `/chunkloaders`. A new window will open under Minecraft
8. [Observe that chunk with the Wireless Charger is kept loaded](http://i.imgur.com/KjShKlx.png)

# Workarounds

Wireless Chargers only chunkload if they have power in their buffer. Therefore, drain the charger of any stored energy to prevent it from chunk loading. Note that applying a redstone signal to disable the charger has no effect.

# Notes

I discovered this bug as part of a [long running investigation as to why chunks are mysteriously loading and unloading at random on my server](https://www.reddit.com/r/feedthebeast/comments/3897ky/dw20_130_troubleshooting_mystery_forced_chunks/). It has since been found that other mods and bugs are contributing to this problem; this one in particular.

To determine the existence of this bug, I took an offline copy of an affected base and tore it down machine by machine (e.g. reactor, turbine, EnderIO conduits, etc) and teleported in and out, until I was able to unload the chunk.

Because of time constraints and lack of experience with the Ender IO codebase, I am unable to offer specific technical advice or pull requests. However, if it helps, please see this similar bug report I had filed for AE2:

* [Multi-block ME controllers forcing chunks to stay loaded #1656](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1656)
* [Fix by yueh for the above bug](https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/f5e3ae8949950428ebdb59c9f5b4bddfa0a156fc)

**Comment by MatthiasMann** [comment]
First of all - you don't need anything from CoFH at all. EnderIO has creative capacitor banks.

I'll take a look at the wireless charger.

**Comment by RoyCurtis** [comment]
You're right; my bad. I have re-tested without CoFH mods and simplified the above reproduction.

Thanks for looking into this!

**Comment by MatthiasMann** [comment]
Looks like the redstone checks keeps the chunk loaded:
https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/wireless/TileWirelessCharger.java#L161

**Comment by tterrag1098** [comment]
That code change did nothing, `blockExists` is already checked by `isPoweredRedstone`

**Comment by tterrag1098** [comment]
However, the relevant code change in EnderCore may have fixed this issue
