### ISSUE TITLE
Redstone conduits forcing chunks to stay loaded when high signal

### ISSUE THREAD

**Issue by RoyCurtis** [SleepyTrousers/EnderIO#2672]
Redstone and Insulated Redstone conduits, when powered with any level of signal to activate the conduit, forces the chunk to remain loaded. This is regardless of any other inputs or outputs present on the conduit network.

# Details

## Discovered on

* Direwolf20 1.7.10 1.5.0 and 1.6.1 live server
* Forge 10.13.4.1448
* [EnderIO 2.2.8.381](http://minecraft.curseforge.com/mc-mods/64578-ender-io/files/2238375)

# Reproduction

## Testing environment

* Forge 1.7.10 10.13.4.1448
* [EnderIO](http://ci.tterrag.com/job/EnderIO/) 2.3.0.403_beta
* [EnderCore](http://ci.tterrag.com/job/EnderCore/) 0.0.1.13_alpha
* Chickenbones mods
  * [CodeChickenCore](http://chickenbones.net/maven/codechicken/CodeChickenCore/1.7.10-1.0.7.46/) 1.0.7.46
  * [ChickenChunks](http://chickenbones.net/maven/codechicken/ChickenChunks/1.7.10-1.3.4.19/) 1.3.4.19
  * [NotEnoughItems](http://chickenbones.net/maven/codechicken/NotEnoughItems/1.7.10-1.0.5.111/) 1.0.5.111 (for chunkborders using F9)

## Steps

1. Create a flatland creative world with cheats enabled
2. Execute `/tp 0 8 0` and then `/setworldspawn` (keeps spawn chunks away from testing areas)
3. Execute `/tp 500 8 500`
4. [Place an EnderIO Insulated Redstone conduit and a Redstone block together](http://i.imgur.com/CyiDnqN.png)
5. Execute `/tp 0 8 0`
6. Press ESC to open the main menu and force a chunk purge
7. Resume game and execute `/chunkloaders`. A new window will open under Minecraft
8. [Observe that chunk with the Insulated Redstone conduit is kept loaded](http://i.imgur.com/46cE4gy.png)
9. Repeat steps 3 to 6, but with [an Ender IO (naked) Redstone conduit](http://i.imgur.com/lZpqdQt.png) attached to the Redstone block instead
10. In the chunkloaders window, observe that the chunk with the Redstone conduit is kept loaded

## Alternative reproduction

* [Detailed reproduction circuit with weakest possible signal, before causing chunkload](http://i.imgur.com/csrfaOB.png)
* [...and after completing circuit, which causes chunkload](http://i.imgur.com/4a6AzhN.png)
* [The 2x2 chunks forcefully loaded by the above due to crossing chunk boundaries](http://i.imgur.com/Y6N3oYY.png)

# Notes

Sorry to file a similar bug report so soon; there is a more severe but related bug report pending after this one also.

**Comment by tterrag1098** [comment]
Thank you for such a detailed report, this is fixed now.
