### ISSUE TITLE
Incompatibility with Dynamic Lights

### ISSUE THREAD

**Issue by KuroNeko87** [SleepyTrousers/EnderIO#2678]
Testing with EnderCore-1.7.10-0.0.1.13_alpha and EnderIO-1.7.10-2.3.0.403_beta while Dynamic Lights is present results in a crash.

Crashlog available here: https://gist.github.com/KuroNeko87/d31b277d7f79168be144

**Comment by tterrag1098** [comment]
I don't see how this is our fault, the crash occurs solely in DynamicLights code. Also get rid of that lotr mod that's spamming your log.

**Comment by KuroNeko87** [comment]
Yeah, been trying to bug him (Maven) to fix his stuff but they won't fix the code lol and his source is closed. I could just decompile, fix, and then send it to them. As for dynamic lights, I’ll bug atomic. Thanks for checking it out.
