### ISSUE TITLE
ME conduit recipe request

### ISSUE THREAD

**Issue by TheTrueForce** [SleepyTrousers/EnderIO#2684]
Hi,
I've just started to swap most of my AE2 Fluix Cables over to your ME Conduits, and I find it annoying to have to craft all those cables all over again. Could I request a crafting recipe to make Fluix Cables into ME Conduits? I was thinking something like 3 Conduit Binders and 2 Fluix Cables makes 2 ME conduits.

**Comment by MatthiasMann** [comment]
You can add such a recipe very easily on your own using Minetweaker.

**Comment by TheTrueForce** [comment]
I'm aware that that's possible. I'm playing on a DW20 server, and I should probably ask the admins, but I think that such a recipe would be of considerable use to plenty of people.
