### ISSUE TITLE
computercraft support for capacitor bank

### ISSUE THREAD

**Issue by soulji** [SleepyTrousers/EnderIO#2685]
For what I can tell, the 2 useful methods/functions for computer craft is getMaxEnergyStored and getEnergyStored.  I was wondering if you could add a couple more such as:

setMaxInput - modify the maximum amount of energy the capacitor bank will take in
setMaxOutput - modify the maximum amount of energy the capacitor bank will give
getMaxIO - get max allowable input/output the capacitor can produce
getCurrentUsage - get current input/output of rf/t (not as needed)

story as to why (no need to read the rest..)
Being able to do this will help with minimizing the power usage of my big reactor, which can produce 500k, but I only want it to produce the minimum amount necessary to keep my capacitor bank full.

**Comment by MatthiasMann** [comment]
All this is available via Computronics.

**Comment by soulji** [comment]
thanks MatthiasMann, I haven't heard of it before, but I'll check it out.

**Comment by XFactHD** [comment]
OpenPeripherals has this integration, too.

**Comment by Vexatos** [comment]
@XFactHD It only has partial integration, Computronics fully supports the capacitor bank.

**Comment by XFactHD** [comment]
@Vexatos Thank you, didn't know that.
