### ISSUE TITLE
Suggestion: Farming Station Power Input

### ISSUE THREAD

**Issue by LC14199** [SleepyTrousers/EnderIO#2686]
As of version 1.7.10-2.2.8.381 the farming station seems to have a limited power input. Even with an octadic capacitor installed, it struggles to input enough power to handle harvesting trees like the 2x2 spruce trees. Even with a creative energy cell pushing 1.21 GRF into this machine, it still doesn't seem to have enough power... So I'm thinking that it's the actual power input limit. If there is a power input limit, can we please remove it or at least explain why it exists? I can understand machine operational speed having a limit, but having a cap on power input doesn't make much sense to me? 

Cheers,
LC14199

**Comment by MatthiasMann** [comment]
The power input isn't the issue - as the tree is chopped at once so the limit is the internal power storage. This is a design element.

**Comment by LC14199** [comment]
I'm aware the tree is cut at once. However, if you place a power source next to an empty farming station, and watch it charge, it charges at around ~100 RF/t. The 100 RF/t base use to me indicates power usage for cutting the wood, not necessarily the power input limit... There is a limit on the amount of RF that can go into this machine because if you look at any other machine, it fills significantly faster.

**Comment by LC14199** [comment]
I'm generating somewhere around 100k RF/t. At that kind of throughput, you'd expect a machine to fill almost instantly, or within seconds. Not a solid minute or more...
