### ISSUE TITLE
Cross Compatibility Bug Matter Overdrive and Sophisticated Wolves

### ISSUE THREAD

**Issue by NullMagic** [SleepyTrousers/EnderIO#2687]
This bug.. I don't even have words for how this thing has infuriated me for several days now as I've attempted to track down the source and cause. Originally we thought it was sophisticated wolves, because they were showing up in the error report, but removing the mod didn't fix it, then we tried Matter Overdrive, and for a while it stopped happening, it was the wolves again, so we removed that, and it kept happening, then we went through every single creature added by any mod and it was indeed from matter overdrive, the scientist. So we stripped our server down to Matter Overdrive and Thermal Expansion alone, and the bug stopped happening. After adding mods back in a small handful at a time I finally found that whenever Ender IO is installed this crash occurs.

http://pastebin.com/uCNC5NuH

I've tested all the way back to the builds from February, and all the way forward to the latest build on jenkins, and each and every build causes the same crash, and it is the weirdest thing I've encountered.

Having both mods installed either server or client side doesn't cause this crash, servers boot up fine, single player worlds run without a problem. But when a player attempts to play on a server, that's when things get really interesting.

Just having EnderIO installed client side causes this crash whenever a Matter Overdrive Scientist, or a Sophisticated Wolf is encountered, it doesn't even have to be on the server. Further, it only crashes the player, not the server, and as you can see from that error report there's pretty much no indication of what occurred at all.

And if that isn't bad enough, it gets weirder. If you have Ender IO installed client side (But not on the server!) and log in any existing entity in the area becomes a mob called a "failed chicken", I can't even tell if that's server side or not, but it's certainly weird.

oi, anyway, I don't even know where to go from here. Is this some kind of basic incompatibility between the mods? Is it on your side or theirs? I can't even begin to tell you, and for that I'm sorry, I really hope this can be figured out.

**Comment by MatthiasMann** [comment]
Well - having EnderIO installed only on one side (server or client) is not supported.

**Comment by NullMagic** [comment]
It's not only installed on one side, it's installed on both sides, however the crash doesn't occur in a single player game, or on the server, but only when a client with EnderIO connects to the server and it only crashes the client. If EnderIO is not on the server the same crash occurs anyway.

**Comment by tterrag1098** [comment]
I would advise you to test with your full set of mods, excluding EnderIO, and see if the crash still occurs. I can't see how EnderIO could cause this at all.

**Comment by NullMagic** [comment]
Alright, we'll go back to testing and see if we can't figure out what the hell it is.

**Comment by NullMagic** [comment]
Alright, we found the problem. It turns out we DID have a mod installed on only the client and not the server (By accident, I assure you), though it didn't show up in any of the crash logs as being active, so that might be why I missed it. Removing the mod fixed everything.

I now feel horribly stupid and am going to go gibber quietly to myself in a corner.
