### ISSUE TITLE
Facades not updating nearby

### ISSUE THREAD

**Issue by hajile00** [SleepyTrousers/EnderIO#2688]
If you place a lever (or any other block that needs to be placed on the side of another) on the side of a facade that has a conduit in it then break the facade, the lever (or other block) does not recieve an update and will persist until it is updated.

Version is 2.2.8.349 (I assume. That is the end of the mod file name)

**Comment by MatthiasMann** [comment]
This has been fixed in the 2.3 beta builds.

**Comment by tterrag1098** [comment]
#1954
