### ISSUE TITLE
SAG Mill Sandstone Recipe == item dupe

### ISSUE THREAD

**Issue by mindforger** [SleepyTrousers/EnderIO#2689]
well, it is only sand but endless niter/saltpeter is a bit game breaking

the sag mill outputs more sand than used in the recipe when using dark steel ball, maybe tune it by default a bit more to the pulverizer, like main output 2 sand always and secondary ONLY niter/saltpeter with slightly higger 25% chance

**Comment by tterrag1098** [comment]
Fixed via https://github.com/SleepyTrousers/EnderIO/commit/b22832fd6af02430c06cc206ac041f940c4da92f

**Comment by mindforger** [comment]
not fixed imho, i commented on the commit

**Comment by mindforger** [comment]
the new builds are pretty more balanced
