### ISSUE TITLE
Unlimited XP Bug with turned on Electromagnet

### ISSUE THREAD

**Issue by duffdunker** [SleepyTrousers/EnderIO#2690]
Found a similar issue here: https://github.com/SleepyTrousers/EnderIO/issues/1658

Hovering at one certain point gives the player unlimited XP. There are no XP-related blocks nearby.

Take a look here: http://youtu.be/g2XolyKFb3E

FTB Infinity 1.7 (v1.8.2) Mod Pack
Minecraft Version 1.7.10
Forge 10.13.4.1448
EnderIO-1.7.10-2.2.8.381

**Comment by tterrag1098** [comment]
I'm at a loss on this issue, just as I was before. The magnet shouldn't be causing anything like this.

**Comment by duffdunker** [comment]
Hey,

the bug is gone now. Two changes were made:

The server got an update to the newest FTB Infinity Modpack (v1.9) and therefore a sever restart.
Second, there was a quarry hole with water source blocks on top (and of cource floating water) next to it (not the one i am hovering in in the video,) which has been filled.


Greets

duff

**Comment by Badcholo** [comment]
I have the latest Ender io and am still experiencing this issue. Also massibe server lag with the magnet and using mekanism Atomic disassembler.
EnderIO-1.7.10-2.3.0.417_beta
EnderCore-1.7.10-0.1.0.25_beta
I'll be creating a new issue.
