### ISSUE TITLE
[Suggestion] Config: Powered lights RF/tick cost

### ISSUE THREAD

**Issue by arkcane** [SleepyTrousers/EnderIO#2691]
I find that Powered lights use up to much RF a Tick for anyone on my survival server to actually use. but I understand that for the sake of over all balance why it is as high as it is.

Could we get the cost per tick as part of the config so that I can tune it.

Thank you for your consideration

**Comment by MatthiasMann** [comment]
It already uses only 1 RF/t - will not be easy to lower it :)

**Comment by arkcane** [comment]
That's fair

I realized that the wiki says 10RF a second not a tick. thank you for answering
