### ISSUE TITLE
Jenkins download

### ISSUE THREAD

**Issue by Tsunayoshi** [SleepyTrousers/EnderIO#2692]
Hi,
your Jenkins download doesn't work for me (can't confirm it for all over the world).

http://ci.tterrag.com/job/EnderIO/
http://ci.tterrag.com/job/Ender%20Zoo/

EnderIO-1.7.10-2.3.0.405_beta-api.jar is the only file I can download.
all other from EnderIO only load 12kb and then stops.

All EnderZoo doesn't start. (Version EnderZoo-1.7.10-1.0.11.29)

This could be a local probelm with my IPS but I want to report it to be sure.

**Comment by Dream-Master** [comment]
Works well from germany.

**Comment by Tsunayoshi** [comment]
I am from germany, too. So I think this is a ISP problem.
Thank you for testing!

**Comment by tterrag1098** [comment]
My server is running out of disk space lately. It is a problem I am attempting to solve. I have just now removed some old files, this should allow files to be downloaded again.

**Comment by Tsunayoshi** [comment]
Yeah thank you, I have downloaded the newest versions. Works fine :smile:
