### ISSUE TITLE
dimensional tranceiver not storing filtered items

### ISSUE THREAD

**Issue by gamerred** [SleepyTrousers/EnderIO#2693]
When you close the dimensional tranceiver it dont store any settings at all

**Comment by tterrag1098** [comment]
Version?

**Comment by gamerred** [comment]
newest beta.

**Comment by MRuth** [comment]
I can confirm this is an issue in the latest eIO beta 416 as well.  Here are some screenshots.

![2015-10-07_15 02 53](https://cloud.githubusercontent.com/assets/3927478/10349531/8e9f704a-6d04-11e5-8639-9276fb55be3d.png)
![2015-10-07_15 02 59](https://cloud.githubusercontent.com/assets/3927478/10349532/8ea34922-6d04-11e5-9de7-4c7b5f4cae25.png)
