### ISSUE TITLE
EnderIO/BluePower/Qmunity Lib stall reports

### ISSUE THREAD

**Issue by AiwendilCiunio** [SleepyTrousers/EnderIO#2694]
Hello, I'm a player on Infitech 2 modpack server:
http://forum.feed-the-beast.com/threads/1-7-10-infitech-2-modpack-v3-1-5-gregtech-balanced-hard-mode-modpack-updated-7-26-2015.50185/
http://infitech.enjin.com/

We've been dealing with severe lag problems since quite some time, and are trying to fix the issue.
I looked at stall reports, and almost each one of them under SERVER THREAD has EnderIO, Qmunity Lib and Bluepower listed.

Because I'm not a programmer my question is - is this possible that one of the mod, or maybe interaction between them (likely something to do with redstone) is the cause of our lag? Please look at these stall reports and tell me what you get out of them:
http://pastebin.com/vp52CGCK (that's how it look most of the time)
http://pastebin.com/1YV9Rs4m (this is a bit unusual as there's no enderio on the list)

Or could the source of the lag be related to the conduit issues described in these tickets?
https://github.com/SleepyTrousers/EnderIO/issues/2673
https://github.com/SleepyTrousers/EnderIO/issues/2672
https://github.com/SleepyTrousers/EnderIO/issues/1959

**Comment by tterrag1098** [comment]
What versions of these mods?

**Comment by AiwendilCiunio** [comment]
EnderCore -> 0.0.1.13
Enderio -> 2.2.8.381
BluePower -> 0.2.954
QmunityLib -> 0.1.114
