### ISSUE TITLE
Server crash with click to center of conduits

### ISSUE THREAD

**Issue by Granik24** [SleepyTrousers/EnderIO#2695]
Hi there, I have crash report.

EDIT:
You can't click to center of the conduit. If you click it, server will crash.

There is crash report: http://pastebin.com/FVFZb0gk
Server core: KCauldron:1.7.10-1492.150
EnderIO:  EnderIO{1.7.10-2.3.0.404_beta}

**Comment by tterrag1098** [comment]
Thanks, I guess I figured those methods were called clientside

**Comment by Granik24** [comment]
Thanks, fixed.

**Comment by Granik24** [comment]
I found another problem. After this fix, it don't crashing server, it just kick player from server with "A fatal erroer has occured, this connection is terminated".

This will happened, if you click part, that is on screen.
![2015-08-04_14 41 25](https://cloud.githubusercontent.com/assets/4377405/9060749/ef1325f0-3ab6-11e5-9129-d631e24c9ef5.png)

**Comment by tterrag1098** [comment]
I need the error log from the server.

**Comment by MageRoyal** [comment]
I am having the same issue with only Item conduit. There is no error log the server just prints that i have disconnected from the server no other information. Nor does it provide a crash report. It just boots you off the server states there was a fatal error then you can immediately log back in. I will say the cable is still functional it is almost like it is trying to pull up a gui that inst there so it crashes you. It only occurs when you click the grey location indicated by his cross-hair. you can still configure the conduit and everything if you precisely click it.

**Comment by tterrag1098** [comment]
There is always a stacktrace. It is either on the client or the server. Find it and give it to me. Until that happens I cannot help anyone.

**Comment by Granik24** [comment]
Finally, I found it in fml-client-latest.log.. There is it: http://pastebin.com/YV2vfdTF
