### ISSUE TITLE
The Vat recipe problem

### ISSUE THREAD

**Issue by Granik24** [SleepyTrousers/EnderIO#2696]
Hi there, we have problem with The Vat. 

If you pull to The Vat Redstone, Gunpowder and Water, you will get fuel, no hootch.

**Comment by MatthiasMann** [comment]
That isn't a very clear description - can you clarify what is happen and which EnderIO version?

**Comment by Granik24** [comment]
We ussing EnderIO-1.7.10-2.3.0.404_beta
Problem: First of all you don't have water in The Vat. If you pull to The Vat Redstone and Gunpowner and after that all water, you will get Rocket Fuel.

**Comment by Granik24** [comment]
Thanks, fixed.
