### ISSUE TITLE
API hack: "RF-Big"

### ISSUE THREAD

**Issue by SoniEx2** [SleepyTrousers/EnderIO#2700]
Make it so you return a negative integer from the RF API indicating how many times you should call it again to get all the bits. For longs, you'd return -2. Other negative integers would require BigInteger precision (except -1 which would be invalid).

I like to call this negative variant/hack "RF-Big", because it's passing BigIntegers thru the RF API. It's similar to how Unicode/UTF-8 works.

**Comment by KingLemming** [comment]
Well. This is certainly a terrible idea.

**Comment by SoniEx2** [comment]
At worst it'll cause crashes. At best it'll make everything behave weirdly.

It does need a way to trigger it into providing the extra data. Maybe something with ForgeDirection.UNKNOWN or whatever Minecraft uses nowadays?

**Comment by KingLemming** [comment]
ForgeDirection.UNKNOWN already has valid use cases.

**Comment by SoniEx2** [comment]
Then add a ForgeDirection.EXTRA :> (or a way to provide metadata thru the RF API)

**Comment by SoniEx2** [comment]
Also if you're using FD.UNKNOWN then you're already doing special stuff, adding special handling to special handling sounds... pretty normal actually.

**Comment by SoniEx2** [comment]
I don't feel like arguing.

**Comment by tterrag1098** [comment]
I have no need for this, EnderIO currently works perfectly fine.

**Comment by SoniEx2** [comment]
What about a conduit that can transfer up to 2^63-1 RF/t?

**Comment by tterrag1098** [comment]
Not planned.

**Comment by tterrag1098** [comment]
Now that I have a moment I can elaborate. There are no plans in EIO for anything that could make use of this horrible hack. Currently the only thing which can deal with >INT_MAX values of RF is capacitor bank networks, and in this case it is dealt with cleanly and there are no existing (known) issues. Each individual bank will return it's percentage of the total network's power for the API methods. This is contrary to Draconic Evolution which just caps out at INT_MAX and lies about being full.
