### ISSUE TITLE
Dark boots do not work with Kingdom of the overworld mod

### ISSUE THREAD

**Issue by leinad92cl** [SleepyTrousers/EnderIO#2702]
Step assist of the dark boots don't work when Kingdom of the overworld mod is installed.

**Comment by MatthiasMann** [comment]
Do other items which provide step assist work in this combination?

**Comment by leinad92cl** [comment]
Power armor Leggings from Modular Powersuit mod and boots of the traveller from thaumcraft 4 mod, work fine.
