### ISSUE TITLE
Bucket handler doesn't check if bucket is iron bucket

### ISSUE THREAD

**Issue by DarkGuardsman** [SleepyTrousers/EnderIO#2703]
https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/fluid/BucketHandler.java#L36

A few users have been reporting bugs to me regarding bucket usage and enderIO fluids. In which the bucket will return an Iron Bucket from Ender IO. According to the code linked above the issue is EnderIo is not ensuring that the ItemStack passed in is an Iron Bucket.

**Comment by MatthiasMann** [comment]
What exactly is the issue? The linked code will return an EnderIO bucket for EnderIO fluids only.

**Comment by DarkGuardsman** [comment]
Yes but it will always return an ender IO bucket regardless of the inputted item. In this case its a wooden bucket but is returning an ender IO iron bucket full of fluid.

**Comment by MatthiasMann** [comment]
Ok, that makes now sense - I'll take a look at it later.

**Comment by tterrag1098** [comment]
@DarkGuardsman the problem is the wooden bucket may not have a "version" for EnderIO fluids. However we can do some checks to see if one exists. I agree that we should only return a metal bucket if the player clicked with a vanilla bucket.

**Comment by DarkGuardsman** [comment]
The wooden bucket is coded as a fluid container so doesn't contain a version per fluid. Instead it uses NBT to store the fluid inside the item cutting down on item IDs.

https://github.com/BuiltBrokenModding/SingleBlockMods/blob/master/woodenBucket/src/main/java/com/builtbroken/woodenbucket/ItemWoodenBucket.java

**Comment by tterrag1098** [comment]
That link is a 404 but I get what you're saying. That is also not the only wooden bucket that exists, I am talking in a more general sense. Of course if there is a filled version of that container we can use that. The problem is when there isn't.

**Comment by HenryLoenwind** [comment]
No, we don't need to use anything. If someone adds a custom container, they need to handle filling it themselves. The only container we, as the providers of new fluids, need to handle are the vanilla ones.

In theory, Forge should handle it as they convert Minecraft to their Fluid system...

**Comment by DarkGuardsman** [comment]
TBH forge doesn't handle much, also only thing you guys need to do is an instance of check for vinalla bucket. This should solve the issue and any future issues with custom contains that want to use the fill bucket event.

**Comment by HenryLoenwind** [comment]
No, an instance check would be exactly the wrong thing to do. It would also accept modded items that extend buckets. Have a look at the fix above.

**Comment by DarkGuardsman** [comment]
Not exactly as it would cover half of the user cases. Either way I was using instance of in a broad way of saying "check for the item needed for the use case". Anyways the code looks good just got a chance to look at it on my PC. Once that is pulled it should fix the issue for this mod.
