### ISSUE TITLE
[Suggestion] Wireless Charger GUI

### ISSUE THREAD

**Issue by Anarcraft** [SleepyTrousers/EnderIO#2704]
You previously added the redstone control to the wireless charger after I asked for it, thank you!  Now if you want to take it to the next level there are a few things you could do:
1. Give the wireless charger an interface when right clicked (like other machines).
2. Putting in a capacitor would increase it's RF storage, RF/t and range.
3. Redstone and side configuration buttons in the GUI (like other machines).

The GUI could note the current capacity, transfer rate and range.

**Comment by tterrag1098** [comment]
My improvements to the IRanged system should easily allow it to have a "show range" button as well
