### ISSUE TITLE
[Suggestion] Another tier of capacitor bank

### ISSUE THREAD

**Issue by Sasstraliss** [SleepyTrousers/EnderIO#2706]
I believe there needs to be another tier of capacitor bank to compete with the resonant storage cell from TE. I myself have a vibrant capacitor bank of over 10b RF, and I think a more expensive but compact solution would be nice.

I suggest 100m RF per block and a crafting recipe that involves using four of the vibrant capacitor banks plus a little extra (like some capacitors or diamonds). If you want you could make a 200m capacitor bank that requires 8 vibrants, with some other required item in the centre.

This way you can pay a slightly higher price for a more compact solution.

**Comment by HenryLoenwind** [comment]
Ender IO's capacitor bank is a multiblock, so you can make it any capacity you want. I understand that you're interested in compactness, but tbh, does it matter? Just put your base on a foundation of cap banks ;). (y=5 to y=64 gives 384.000 MRF per chunk)

**Comment by Anarcraft** [comment]
Yes it matters.  The less tile entities the better.

**Comment by Sasstraliss** [comment]
Henry, while it is multiblock, that's not the point. TE energy cells can be multiblock too if you really want, but that's again not the point.

- Saving on performance from having many blocks in a structure
- More options for compact storage to compete with other mods

**Comment by tterrag1098** [comment]
Trust me, the performance hit from using 10x as many banks is extremely minimal.

**Comment by tterrag1098** [comment]
Also, I have no interest in competition.
