### ISSUE TITLE
[Suggestion] Add Anvil Enchantments to Redstone Arsenal and Simply JetPacks Armor

### ISSUE THREAD

**Issue by DrakoAlcarus** [SleepyTrousers/EnderIO#2712]
Pretty much what the title says.

The Capacitors don't need to be added to the armor, since it's already expensive and hold energy on their own, but I like the upgrades, but I don't want to have to carry around two sets of armor just to have these abilities.

**Comment by MatthiasMann** [comment]
The upgrades of the dark steel armor are part of that armor - they can't be just added to other mod's armor.

**Comment by DrakoAlcarus** [comment]
What a disappointment. Thanks anyway!

**Comment by tterrag1098** [comment]
Well, it is technically possible for the other mods to support the upgrades, but it'd have to be done on their end. So, bug them!

**Comment by DrakoAlcarus** [comment]
That's a good solution. I'll see.
