### ISSUE TITLE
Pressured Fluid Conduits extracting from wrong tank using Genetics

### ISSUE THREAD

**Issue by arkoftruth** [SleepyTrousers/EnderIO#2713]
Minecraft Version: 1.7.10
Mod Pack: Direwolf20 for Minecraft 1.7.10
Mod Pack Version: 1.6.1
Happens on: Singleplayer and Multiplayer

Pressured Fluid Conduits have suddenly started taking fluids out of the input tank instead of the output one. A couple of days ago the conduits used to take growth medium out of the output tank on of the incubator and feed it to the next one along in the chain but now it is remove fluid from the input tank instead.

**Comment by MatthiasMann** [comment]
That is not an EnderIO problem - it can only access the tanks which are exposed as either input or output tank by that TileEntity - so you need to report that issue with them.

**Comment by tterrag1098** [comment]
^
