### ISSUE TITLE
Unable to open item conduit's GUI

### ISSUE THREAD

**Issue by Silly511** [SleepyTrousers/EnderIO#2714]
I have shift-left-clicked with the yeta wrench, I have shift-right-clicked with a empty hand, and done everything in between. But I can not open the item conduit's GUI. Version 2.2.8.381 of ender io.

**Comment by AnrDaemon** [comment]
"Latest" is not a version number.

**Comment by tterrag1098** [comment]
The item conduit is connected to something, right? There is no GUI to open if there are no connections.

**Comment by tterrag1098** [comment]
Screenshots would help.

**Comment by Silly511** [comment]
Sorry that was the problem.
