### ISSUE TITLE
Ender IO Farming Station Issue with seeds

### ISSUE THREAD

**Issue by lordkelemvore** [SleepyTrousers/EnderIO#2715]
I have the latest version of Ender IO installed on my server and with a fully upgraded magical crop and farming station farm every so often the farming station will harvest and then destroy the crop entirely. Is this a bug or function of the farming station? (using Magical Crops 4.0.0 PUBLIC BETA may also be an issue but unsure)

**Comment by tterrag1098** [comment]
Are you using the full release or just the Core version? Exact version numbers for both mods would be nice.

**Comment by MatthiasMann** [comment]
You need to disable to auto replanting in the magic crops config.

**Comment by lordkelemvore** [comment]
I will check and get the version numbers for you in the am. I think it's
the full release but knowing myself.... I'm probably wrong haha

**Comment by lordkelemvore** [comment]
I am using EnderIO-1.7.10-2.2.8.381.jar
May 15, 2015
and Magical crops version 4.0.0 PUBLIC_BETA-3.jar files.

**Comment by lordkelemvore** [comment]
I also looked into the config file @MatthiasMann to find that setting and disable it for now but I must not be seeing it. (of course I could be overlooking it)   But for more info on the problem: If I have a farming station running and it destroys the crop it DOES give essence but does not give any seeds when harvesting with a mattock with luck on it. Manually harvesting does though.
