### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MySt1k** [SleepyTrousers/EnderIO#2717]
http://pastebin.com/MZ0afYf9

Version: last commit (9243263)

**Comment by tterrag1098** [comment]
Need some more info here, I don't see how that crash could be possible. What were you doing?

**Comment by MySt1k** [comment]
Opened inventory have broken mechanism

**Comment by MatthiasMann** [comment]
@MySt1k if you expect that someone will be able to help with your crash - you should try to explain what is happening in readable English.
So far you haven't provide any steps to reproduce or description of what you did.

**Comment by MySt1k** [comment]
http://youtu.be/tM8umj7D3Ug
