### ISSUE TITLE
TE4 Hardened Glass recipe inconsistency

### ISSUE THREAD

**Issue by Gambigobilla** [SleepyTrousers/EnderIO#2719]
In Thermal Expansion 4 Hardened Glass recipe is dustObsidian\*4 + ingotLead = Hardened Glass\*2, but in AlloySmelterRecipes_Core.xml it requires 8 dustObsidian instead of 4

**Comment by tterrag1098** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/8a91daa2931e1988069a4cb1d3759cf0686a61b2
