### ISSUE TITLE
Allow the player to lock Coordinate Selectors

### ISSUE THREAD

**Issue by Komic** [SleepyTrousers/EnderIO#2722]
Nothing too fancy for this suggestion, I just feel like it could avoid quite a few mishaps. Not sure about the way you could implement that, maybe a simple craft with just the Coordinate Selector to alternate between Locked and Unlocked.

Keep up the great work and thank you for reading !

(EDIT: Speaking of the Telepad, could we get a capacitor slot in order to speed it up a bit ?)

**Comment by SlashLife** [comment]
Hi, I agree; it is extremely easy to accidentally lose coordinates in the coordinate selector.

I think I'd actually even make that default behavior: Once you select coordinates, the selector will automatically be locked.
To unlock it, you could craft it by itself on an empty grid to reset the coordinates stored.
