### ISSUE TITLE
Crash with EnderOI facades and Galacticraft

### ISSUE THREAD

**Issue by 23Link89** [SleepyTrousers/EnderIO#2723]
When I go on the moon I crash only when I have a conduit hooked up to a sealer on the moon. Crash: http://pastebin.com/8YvxDYPh I think it may have something to do with JRE 8 and the being on the moon with no sound accept I have a frequency module which allows me to hear on the moon when I have it on. Thank you for your time.

**Comment by XFactHD** [comment]
This doesn't have anything to do with EnderIO, the crash report doesn't even mention EnderIO. Please report this to Galacticraft.
