### ISSUE TITLE
Sag mill- can't imput flint

### ISSUE THREAD

**Issue by patchchristensen** [SleepyTrousers/EnderIO#2726]
We updated to Aug9-407 and it seems that we can't put flint in the sag mill any longer. Dark steel balls still seem to work. Tried picking up the block and replacing and same result. 

Anyone else seeing this issue?
Thanks
Kevin

**Comment by NonQueueingMatt** [comment]
I think that's intentional. NEI and shift click on flint doesn't show that they can be used.

**Comment by pacthchristensen** [comment]
So they changed that? You could always put in flint to give an increase in yield from the sag mill.

**Comment by pacthchristensen** [comment]
I looked at the sagmillrecipescore.xml file and the lines are still in there. I have to think that if it was on purpose they would have removed it out of there.

  <grindingBalls>
    <grindingBall id="Flint" grindingMultiplier="1.2" chanceMultiplier="1.25" powerMultiplier="0.85" durationRF="24000" >
      <itemStack oreDictionary="flint" />
    </grindingBall>
    <grindingBall id="DarkSteelBall" grindingMultiplier="1.5" chanceMultiplier="2" powerMultiplier="0.7" durationRF="100000" >
      <itemStack modID="EnderIO" itemName="itemMaterial" itemMeta="7" />
    </grindingBall>

**Comment by NonQueueingMatt** [comment]
Huh, that's weird. Shifting on the flint doesn't show anything, and nor does putting it in a SAG mill do anything. It's likely a bug, then.

**Comment by 6210classick** [comment]
try changing itemStack oreDictionary="flint" /> to <itemStack modID="minecraft" itemName="flint" />

to my knowledge flint does not have an entry in the Ore Dictionary

**Comment by pacthchristensen** [comment]
This is from the recipe core file and can not be changed (by the end user). Any changes you make to that file just get over written.

**Comment by tterrag1098** [comment]
@6210classick EnderCore ensures there is a registration for flint.

@pacthchristensen You could override it in the user file.

**Comment by grydian** [comment]
I am using the latest jenkins builds for both EnderIO and Endercore and I also cannot put flint into the sag mill.  I tried changing the user file but it didn't seem to work.  Any reason why flint would suddenly not be working?

**Comment by lehjr** [comment]
I had the same issue with EnderIO-1.7.10-2.3.0.407_beta.

Is the problem with this line?
<itemStack oreDictionary="flint" />

Minetweaker shows the oredict name to be itemFlint and when I copy the <grindingBalls> section to the user file, and change the line to <itemStack oreDictionary="itemFlint" /> it works fine.

**Comment by tterrag1098** [comment]
Yeah that's probably it. Thanks, didn't notice the name was wrong.

**Comment by pacthchristensen** [comment]
Glad I am not the only one to have the problem... confirms that I am only sightly crazy. Thanks tterrag you are awesome. You do a great job.
