### ISSUE TITLE
Crash Report when loading an existing World

### ISSUE THREAD

**Issue by chloeprince** [SleepyTrousers/EnderIO#2727]
My MC Crashes when I load a previous world that was running EnderIO-1.7.10-2.2.8.381
If I try starting a new world, it tries to start, then it says, shutting down internal server... then I get the same crash log as I do when I try loading an existing world.

When I update to these: 
EnderIO-1.7.10-2.3.0.407_beta.ja
EnderCore-1.7.10-0.0.1.17_alpha.jar

I get this crash:
http://pastebin.com/MwZh3fdN

Using Forge .1448

**Comment by tterrag1098** [comment]
None of this mentions EnderIO, the crash is from mapwriter. Not sure what to do there.

**Comment by XFactHD** [comment]
I had that crash too a while ago. I just removed Opis (mapwriter is included in the opis jar), removed all the configs from mapwriter and after launching the game and the world once, I put Opis back in the mods folder.
