### ISSUE TITLE
[Feature Request] Portable Power

### ISSUE THREAD

**Issue by louismiller** [SleepyTrousers/EnderIO#2728]
It would be nice if there was a battery or device that when placed in a players inventory it would charge any RF powered items or armor, similar to TE3's Flux Capacitor.

It could:
* Be toggled on / off by the player
* Doesn't need to be on the hotbar to charge items, but just in the inventory itself (or nested in a bag, to charge any items placed in the bag, if possible, not sure if an inventory like that ticks)
* Different tiers (+capacity, +charging speed, +discharging speed)
* Be charged by the Dark Steel Helm solar panel upgrade, wireless chargers, or by placing it into a Capacitor Bank

Silly, fun, possibly pointless, or just not fitting for EnderIO:
* Charge items in the inventory that does not use RF, example: EU
* An area of effect version/upgrade/tier that charges other players inventories (if possible)
* Be used as a weapon, Overcharge: expend energy to damage nearby enemies and players
* Be used as defensive weapon, Shield: uses energy to absorb damage taken

**Comment by tterrag1098** [comment]
@MatthiasMann I could have sworn there was something that did this already. Is there not?

**Comment by MatthiasMann** [comment]
Simply Jetpacks has a dark soularium jetplate which can charge other items and can itself be charged from the solar panel upgrade.

**Comment by HenryLoenwind** [comment]
I personally don't really see a need for this. The wireless charger covers most of its use cases.

Also, items that do something when they are in the inventory are quite expensive---the server has to check every inventory slot of every player every tick to see if there is an item of that kind and then find out if it is switched on and has power. And that check has to be repeated for every item of every mod that works that way.

**Comment by NonQueueingMatt** [comment]
Agreed with Henry - you can always take an energy cell/capacitor bank and a wireless charger with you, then have all your items charged on the go.

**Comment by HenryLoenwind** [comment]
PS: About the idea of charging items in a bag: As you might have guessed from my answer above, that very much is a "no way to do" thing. Minecraft is not calling any code on the item itself. So no "inside-out" processing. Instead the mod's code that is called on every tick has to check the inventories, and would need to dig into the bags ("outside-in"). For that it'd need to know about all the different bag types---Minecraft doesn't now bags, so every mod has its own implementation.

One notable exception are the Baubles slots. They DO call code on the items. Great invention!

**Comment by louismiller** [comment]
@MatthiasMann True, a lot of mods have items like this, but I would like to see one in EnderIO with out relying on another mod to provide it.

@NonQueueingMatt Every player on our server, myself included already does this, it works but.. could be nicer.

@HenryLoenwind The wireless charger is great when we are in our base but out exploring and mining under the ground, with no sunlight to charge, this would be a great item. The magnet when placed in the Baubles slot does this, maybe this battery item could be placed in the slot too. It gives the player a choice between more power, or further item pickup.

**Comment by tterrag1098** [comment]
@HenryLoenwind onUpdate is called regardless, on every item in the player's inv. The expensive part is that we would AGAIN need to iterate every slot for charging.

**Comment by HenryLoenwind** [comment]
@tterrag1098 nice detail. seems the magnet needs another update, though...
