### ISSUE TITLE
ME Gas Conduit conencts to ME cables automatically

### ISSUE THREAD

**Issue by adamcirillo** [SleepyTrousers/EnderIO#2732]
I updated my Enderio to 2.3.0.407 Beta to get the Mekanism 8 gas conduits working and was replacing my mechanism ones and whenever I ran into a ME Dense Cable or ME Smart Cable it would auto connect the connector plate to. I believe this behaviour is wrong as the ME Gas Conduits don't gain anything by connect to the ME Cables.

Also ME Conduits don't connect to Import/Export Bus have to use a ME Smart Cable.

Mod Versions
Enderio 2.3.0.407
Mekanisum 8.1.7
AE2 RV2b10

**Comment by XFactHD** [comment]
Are you using ExtraCells? If so, then thats the cause.

**Comment by adamcirillo** [comment]
Yeah I'm using extracells 2 anyway to disable that?

**Comment by XFactHD** [comment]
No, ExtraCells has an integration to store gas in the me system (unfinished thus unusable). For cable parts to work with the gas api, the cable has to offer the gas api to the neighboring blocks even though there is no part using the api (the same problem exists for the forge fluid api).

**Comment by tterrag1098** [comment]
The gas API has no way to tell if a connection is possible (unlike RF's canConnectEnergy), so this is unfixable.
