### ISSUE TITLE
Botania + EnderIO issue

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2733]
When activating the flight thingamajing Flügel from Botania, the night vision from the Dark Helm deactivates. It re-activates again when the Flügel is turned off.

I don't know if this is intended or not.

**Comment by MatthiasMann** [comment]
Check your key bindings.

**Comment by Unrepentant-Atheist** [comment]
My keybindings are fine. Flying (flügel) activates with double jump. Night Vision via numpad 2.

**Comment by HenryLoenwind** [comment]
Does it play the deactivation sound?

**Comment by tterrag1098** [comment]
What is this item? I can't find it in NEI.

**Comment by NonQueueingMatt** [comment]
@tterrag1098 type in Tiara in NEI and the Flugel thing should pop up, I think NEI doesn't register special characters like ü

**Comment by srs-bsns** [comment]
I can confirm that there is a rendering issue between these two mods.

If nightvision is turned on while wearing a tiara (but not flying) then the nightvision will work properly. However, starting to fly while nightvision is turned on causes the nightvision effect (in the sky texture only) to fade in and out in-synch with the flapping of the tiara's wings. The nightvision effect on the world is not effected and works properly though (seeing through water, etc..)

If nightvision is toggled ON while already in flight, the nightvision effect will not render at all until you stop flying (double-jumping to toggle flight, or the tiara's energy bar becomes depleted) at which time it will start rendering properly.

Using a vanilla nightvision potion has no rendering problems at all, so I would assume that this problem exists with EnderIO, but you may want to contact @Vazkii about this if you can't find the source.

Tested with:
EnderCore build 20
EnderIO build 408
Botania Build 217

**Comment by Unrepentant-Atheist** [comment]
Aynthing done about it? Nightvision still is bugged.
