### ISSUE TITLE
Transparent facades not showing conduits

### ISSUE THREAD

**Issue by perrydt** [SleepyTrousers/EnderIO#2737]
The release notes mention that facades painted with transparent blocks should render conduits as of version 2.2.2, but this doesn't seem to work.

I'm using 2.2.8.381 in the FTB Infinity 1.10.1 modpack -- I also tried a test world with just EnderIO, same version, and got the same result.  When I paint a facade with plain glass, then put it over a conduit, the conduit vanishes.

I also noticed that if there's a light source behind the conduit/facade, the light is also blocked by the facade and in some cases, such as glowstone, it renders the entire lighted block as black... although I don't know if that's normal behavior.  Up until now I'd been using opaque blocks as facades.

Is this a bug, or is there an option or recipe I'm not following to get the facade to render the conduits inside?

Edit: found the original feature request where this was added: #1265

**Comment by tterrag1098** [comment]
This is definitely working in the dev bulds so I'll just guess that it was fixed some time along the way :P

![](http://puu.sh/jMiaK.jpg)
