### ISSUE TITLE
Dimensional Transceiver Should Extend Inventory Panel

### ISSUE THREAD

**Issue by rcistano** [SleepyTrousers/EnderIO#2738]
I am having problems with the Dimensional Transceiver. I am trying to use it as a relay to my Inventory System and when I use that with the Inventory Panel it doesn't fully work.

**Comment by tterrag1098** [comment]
That is not intended to work that way, however, it is a decent suggestion.

**Comment by rcistano** [comment]
Im trying to have an inventory system other than the ME System

**Comment by SeeJayEmm** [comment]
Is there a way to vote in Github? Because I'd vote for this one.

**Comment by Badcholo** [comment]
give a star in the right hand top corner, where is says Watch, Star or Fork

**Comment by tterrag1098** [comment]
That stars the repo, not the issue

**Comment by Badcholo** [comment]
They still deserve it.

**Comment by VT-14** [comment]
+1 for wanting this.

**Comment by praetoras** [comment]
Also +1 for wanting this.

However, I originally came across this while trying to find out if it was possible to run an inventory panel directly off of nutrient fluid from a DT. So far I haven't been able to, not even by transferring the fluid from the DT into a tank.

**Comment by VT-14** [comment]
What is the current dev opinion on this enhancement?

**Comment by HenryLoenwind** [comment]
That it'd be nice but tricky to do right.
