### ISSUE TITLE
enderio glider upgrade kicks me from my server.

### ISSUE THREAD

**Issue by ziba1** [SleepyTrousers/EnderIO#2743]
Hi, me and a friend have our own server running the 1.7.10 pack which has the enderIO mod.

We just updated recently the server recently to the 0.7.9f version which has the 2.3.0.393 version of the mod installed

Now randomly whenever my friend is using his enderio glider upgrade, I am  booted from the server, not necessarily instantly, but within like 30 seconds or so of him using it.  There is nothing specific I am doing when this happens, I can just be stood still.

This is the console message I get when it happens:

[23:18:10] [Server thread/INFO]: zibafu lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Une connexion Ã©tablie a Ã©tÃ© abandonnÃ©e par un logiciel de votre ordinateur hÃ´te], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

Hes stopped using the glider since then, and Ive stopped getting kicked.

**Comment by HenryLoenwind** [comment]
Could you please also have a look in the client log files if there are more error messages? The above is just a "lost connection" and not really helpful for finding the cause...

**Comment by ziba1** [comment]
will do, probably tonight, will get my mate to use his glider again and try to recreate the problem.

Which sods law will say that I then don't disconnect haha

**Comment by ziba1** [comment]
Ok, literaterly just logged on with my mate, asked him to put his suit on and deploy the glider, soon as he did I was kicked, so it definitely seems to be something to do with the glider

Anyhow, here are the logs

http://paste.ubuntu.com/12208845/

http://paste.ubuntu.com/12208862/




Cheers guys.

**Comment by tterrag1098** [comment]
Quite a few errors in those logs aside from you getting kicked. But still nothing helpful.

**Comment by ziba1** [comment]
You think it could be a combination of things ?

I might update the modpack on my server today, then get my mate to test it again later

**Comment by rladams** [comment]
Using Revolution pack 1.0.10.0, EIO 2.3.0.407_beta on a server. All players get kicked when any ability (jump in this case) is toggled by the player using the dark steel armor.

**Comment by tterrag1098** [comment]
Is your world in offline mode? Also this is unrelated.

**Comment by rladams** [comment]
No, we run with online mode and full auth.

Our issue matches the problem description where an ability is used and it results in other players being kicked off. In my case it is all players (5-7).

**Comment by tterrag1098** [comment]
That error can't happen unless a player's GameProfile is null, which only happens in offline mode.

**Comment by rladams** [comment]
I just confirmed in our server.properties file, "online-mode=true".

I uploaded client logs. I can only try to accurately report the behavior that has caused issues on the server. I can't say how things work, or try to contradict you.

We have reliably demonstrated that if you toggle a darksteel ability, everyone else gets kicked. If you care to login, I'd be happy to whitelist you.

I've also raised the issue to the modpack author and perhaps we can troubleshoot if it's an unusual mod interaction. I was going to work with him first until I found an open issue that matched what we experienced and I wanted to share that information.

Thank you for your time.

**Comment by HenryLoenwind** [comment]
The GameProfile can also be null on the clients of the other players (but don't ask me why or in which cases), and that is what crashes here. I think.

**Comment by Kohlerslave** [comment]
Same problem here while using the 1.7.10 Pack ver. 0.8.0.  Here's the bit from the log:

http://pastebin.com/gWCJMqsF

Happens consistently.

**Comment by Kohlerslave** [comment]
Tried with another player online and it didn't boot him.  I believe it may be a key bind issue, as my wife and I have the same keys bound to the same items.  My brother didn't change the default key binds and it didn't boot him while he was online with me.  I will try again tomorrow and have her unbind her keys for Ender IO.  I'll report back if it changes anything.

**Comment by ziba1** [comment]
Ok, updated to 0.8.0 of the 1.7.10 pack, and its still doing it

New pasted log for you

http://paste.ubuntu.com/12294428/

My mate is going to record himself using the glider in case somehow this gives you a better idea of whats going on

**Comment by ziba1** [comment]
ok, well we just tested it some more, and it seems that he can only use his glider when I am in the same chunk, or possibly close chunks,  but my base is several thousand blocks away, and he tries to use it when I am in my base, and he is in his, it kicks me.

I just borrowed his armor, and the kick happens upon simply deploying or putting away the glider after a certain range from another player

**Comment by ziba1** [comment]
video of us testing

https://www.youtube.com/watch?v=ZzVyPIVAf7M&feature=youtu.be

**Comment by JasonMcRay** [comment]
I can confirm that players are having the same issue in my InfItech 2 modpack. If need be, we can provide logs, but i took a look into them, and there is nothing really telling much. All there is in the client console is this:
http://pastebin.com/AX4FK1hg

**Comment by Baughn** [comment]
Can confirm the same issue in TPPI 2.

**Comment by ToXIQuE** [comment]
I can confirm that this is happening on the server I play on as well, Glider kicks everyone out.

**Comment by wlhlm** [comment]
@ToXIQuE Try updating to 416/417.

**Comment by ToXIQuE** [comment]
Ah I see we are on 413 beta, Ill ask the server owners, thanks for the reply!

**Comment by HenryLoenwind** [comment]
@tterrag1098 maybe you could use the "milestone" functionality to match issues to builds?

**Comment by wlhlm** [comment]
@HandGrenade As has been stated in this issue _multiple_ times, the fix came with 416, so please update.

**Comment by Badcholo** [comment]
have you guys checked the properties file to see if flight is enabled?
allow-flight=true

**Comment by ToXIQuE** [comment]
The update fixed it
