### ISSUE TITLE
Vibrant Capacitor Bank voiding energy

### ISSUE THREAD

**Issue by MrJoki007** [SleepyTrousers/EnderIO#2746]
I've got two big reactors attached to a lot of vibrant capacitor banks. Each reactor is outputting 20k Rf/t and the energy use is 25k Rf/t. The capacitor banks are full but wont stop accepting energy. I can see that in the power monitor and the buffers of the reactors arent filling. If i set in the capacitor bank that it isnt allowed to accept or output power, the buffers are filling

**Comment by HenryLoenwind** [comment]
What kind of cabling are you using? Ender IO conduits? Direct connection?

**Comment by MrJoki007** [comment]
Im usind Ender Energy Conduits to connect the reactors to the capacitor banks and then thers a tesseract direct to the bank
