### ISSUE TITLE
Conduit only package?

### ISSUE THREAD

**Issue by edgard** [SleepyTrousers/EnderIO#2750]
Hey guys, I'd like to suggest the creation of a conduit-only EnderIO package.

I'd love to use Ender IO conduits, but currently I'm unable to do so because of all other stuff it adds. My users are already used to the machines on the server and adding all this other stuff would just create overlap and confusion.

Thanks for all the work, awesome mod.

**Comment by tterrag1098** [comment]
Modularization is on the roadmap.
