### ISSUE TITLE
Bug with Vacuum Chest [Important!]

### ISSUE THREAD

**Issue by Patrick15a** [SleepyTrousers/EnderIO#2752]
The interface of Vacuum Chest is not closed during the break Vacuum Chest. Thus items can be doubled. Please this bug as soon as possible treat!

PS: Srry my english is bad!

**Comment by HenryLoenwind** [comment]
Which version does this happen with? I ask because we already did some fixes to its GUI in v2.3.

**Comment by Patrick15a** [comment]
EnderIO-1.7.10-2.2.8.381
In FTB Infinity

**Comment by tterrag1098** [comment]
Duplicate of #2717 (same fix for that fixes this)
