### ISSUE TITLE
Immibis Microblocks Support

### ISSUE THREAD

**Issue by border999** [SleepyTrousers/EnderIO#2753]
I have this issue where whenever I attempt to place a microblock in the same space as a conduit I'm unable to. The reverse is also true as I can't place a conduit in the same space as a microblock.

**Comment by MatthiasMann** [comment]
Nope

**Comment by NonQueueingMatt** [comment]
That would destroy the functionality of conduit facades..

**Comment by MatthiasMann** [comment]
Conduit facades are still the best solution in terms of client performance as they actually reduce the amount of things rendered while micro blocks add more things to be rendered.

**Comment by border999** [comment]
very well, message recieved

**Comment by tterrag1098** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/9c315e755706fb8afa6e4d03c2d00ce0601f569f
