### ISSUE TITLE
Its all about aesthetics

### ISSUE THREAD

**Issue by zHawky** [SleepyTrousers/EnderIO#2758]
Hi, what do you think about redesign your armor, because armor look same as vanilla meanwhile thaumcraft, steampower mod and even twilight forest have some different armor look.
Would be better if chestplate have wings like openblocks but smaller, or boots have same look as portal or mekanism boots. In general just displayed enchantments.
So how this idea?
(wow so much issues, i think mod is work perfectly..)

**Comment by tterrag1098** [comment]
This has already been started in the 2.3 beta. The glider and solar panel render on the model.

**Comment by zHawky** [comment]
Yep thats it, then close issue.
