### ISSUE TITLE
[Bug | Crash] Ender IO Teleporter GUI causes crash when interacting with it.

### ISSUE THREAD

**Issue by SnowShock35** [SleepyTrousers/EnderIO#2760]
Hi @tterrag1098 & Other EIO Devs

Found a bug/crash with the new telepad UI. 

Minecraft 1,7,10
Forge 10.13.4.1448
EnderCore 0.1.0.22_beta
Ender IO 2.3.0.412_beta

Crash report: http://paste.ee/p/coMj0

Steps to repeat...
1. Create the telepad multiblock (3x3x1)
2. Open it's UI
3. Crash and burn! 
4. Eat cookies?

**Comment by tterrag1098** [comment]
Fixed via SleepyTrousers/EnderIO/28d0627cf7118b392b3deeb4289f9f3c236ce8ba
