### ISSUE TITLE
Sneaking should prevent upgrading conduits

### ISSUE THREAD

**Issue by zzApotheosis** [SleepyTrousers/EnderIO#2763]
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1492
EnderIO-1.7.10-2.3.0.413_beta
EnderCore-1.7.10-0.1.0.23_beta

When I try connecting a Dense ME Conduit to a standard ME Conduit, it overwrites the standard conduit and leaves only the Dense ME Conduit instead of connecting the two together. This also happens in the reverse order (Standard ME Conduit over Dense ME Conduit).

**Comment by tterrag1098** [comment]
Screenshots? I'm not sure what you mean. Are you trying to place the dense conduit into the bundle? Or next to an existing bundle?

**Comment by zzApotheosis** [comment]
https://drive.google.com/file/d/0B_wljXPJi507RjN4cVdHZjVtSHc/view?usp=sharing

I think "replace" is a better word to use. I'm not sure if they're supposed to replace each other.

**Comment by tterrag1098** [comment]
Oh right! That. That's actually intentional, so that you can upgrade conduits in-place. Shift should cancel it. If it doesn't, that's a bug.

**Comment by tterrag1098** [comment]
For most types of conduits there is no reason to attach different "tiers" together, ME conduits are a bit of a special case in that regard.

**Comment by zzApotheosis** [comment]
Okay, that makes sense. I do like the upgrade feature, but I did test shift-right-click in the video and it didn't work.

**Comment by HenryLoenwind** [comment]
Yes, MEs are the only conduits where the different tiers of the same type actually connect. I overlooked that when implementing the replacement feature. I didn't add shift-handling, because it's usually not relevant for block placing.
