### ISSUE TITLE
[Question] Energy Extraction

### ISSUE THREAD

**Issue by SonarSonic** [SleepyTrousers/EnderIO#2770]
Hey,
I'm the maker of the Calculator Mod. In the mod there is a system for distributing power evenly.
Anyway I can't seen to extract from a capacitor bank using extractEnergy, I looked at the code and noticed you haven't implemented it. Is there another way to remove power from the capacitor banks/conduits without allowing using the receiveEnergy method in my TileEntity.

Thank You
Ollie

**Comment by tterrag1098** [comment]
No, capacitor banks force push-based energy. In fact in the beta I have removed the IEnergyProvider interface from them.

**Comment by SonarSonic** [comment]
Is there a way to pull using the Ender IO API?

**Comment by tterrag1098** [comment]
No. Why do you need to pull?
