### ISSUE TITLE
[Beta 413] Inverted Powered Light Bug

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#2778]
When I start my server all Inverted Powered Lights are off and will stay off unless I replace the power conduits on which they are (they turn on when I remove the conduit).
![2015-09-07_15 53 02](https://cloud.githubusercontent.com/assets/8670392/9718121/364e5098-5579-11e5-85e8-c480fe0c5f57.png)
![2015-09-07_15 57 17](https://cloud.githubusercontent.com/assets/8670392/9718122/36505a6e-5579-11e5-960c-928dd4d26789.png)

**Comment by tterrag1098** [comment]
What version?

**Comment by HenryLoenwind** [comment]
Title says Beta 413

**Comment by Xiaminou** [comment]
Okay, I suppose I should have mentioned a few things:

 - I cannot reproduce the bug in a modpack with ender IO alone.
 - The bug happens in my world which also has 250+ other mods
 - The power line gets its power from a P2P Tunnel
 - It's not only on server restart but also when placing lights, I have to place the light first then the power conduit or it won't work
 - I haven't tried applying a redstone signal to it to see what happens.

**Comment by Rukachan** [comment]
I can confirm using 416. You can reproduce it easily by:
1: putting down any full capacitor
2: putting down any conduit
3: putting down the inverted powered light.
The light will be fully charged, but it will not work nor it will use any RF.

I should also mention that when I break the conduit, or if I place a block next to the light it will start working again.
If the light is put directly to the capacitor, everything will work as expected.

**Comment by Rukachan** [comment]
I can also confirm this in 417.

**Comment by TheJulianJES** [comment]
If I put a light on a duct (from Thermal Dynamiscs). I have to update the light block first.

**Comment by mindforger** [comment]
i can second @TheJulianJES it seems to miss to update itself when placed and only activates when i update the block by placings something around it

**Comment by TheJulianJES** [comment]
Yeah :)

**Comment by TheJulianJES** [comment]
I also have this in build 417, placing a powered light (inverted) on a duct or conduit will load the light to 100/100 RF but the light will not turn on, relogging/server restart does not fix this. So it is problay not just a render thing. So I guess it is missing something like that:
´´´
public static void onTick() {
   if(this.getEnergy() > 0) {
       world.markBlockForUpdate(x,y,z);
    }
}
´´´

**Comment by TheJulianJES** [comment]
Normal lights also won't be updated correct: https://gyazo.com/abdc8b9e04eb2e47901d67e6302569d2

**Comment by SeeJayEmm** [comment]
I am experiencing, what I believe, is another aspect of this issue since updating from 2.2.8.381 to 2.3.0.417_beta.  I can easily recreate it.

I have a series of inverted powered lights connected via energy conduit. If the lights run out of power they turn off as expected but once power is reapplied will not turn back on. The easiest way to get them turned back on is to cause a block update by placing a block next to the light.

If it matters this is on a server. I have not tried it locally yet.

**Comment by TheJulianJES** [comment]
Yeah, same :(

**Comment by haXs** [comment]
Is this still in state "cannot reproduce" or do you still need help replicating the issue?

**Comment by TheJulianJES** [comment]
I can also reproduce this with JUST EnderIO. New world...

**Comment by HenryLoenwind** [comment]
I think atm it is in the state "all our developers are currently busy. please hold the line. your bug will be connected to the next free developer" ;)

I'd remove the "cannot reproduce", too, but I haven't even had a chance to try it.

**Comment by TheJulianJES** [comment]
Thank you :)

**Comment by HenryLoenwind** [comment]
Let's try not to use a hammer to solve this? ;)

**Comment by Badcholo** [comment]
Yeah, use a Pick...

**Comment by TheJulianJES** [comment]
Thank's :D

**Comment by haXs** [comment]
Can this fix be applied just server side or would the clients need an update also?

**Comment by HenryLoenwind** [comment]
This change alone would be ok to be added server-side only. You'd have to build your own version with just it though.

**Comment by haXs** [comment]
I have compiled this into my version ( beta 415 ) and it does fix the issue for the wired powered lights but the issue still seems to persist for the wireless variant ( both inverted and normal ) these still require a block update to change state.

**Comment by HenryLoenwind** [comment]
ok, I'll look at them. I thought they shared that code, but I didn't specifically test them.
