### ISSUE TITLE
[Question] Power Spawner behaviour

### ISSUE THREAD

**Issue by AiwendilCiunio** [SleepyTrousers/EnderIO#2783]
I made this:
http://imgur.com/Aj6AbhS

You can see 4 spawners there - just above spikes. The problem I have is it's not spawning mobs as fast as it should. Could it be because they can only spawn below the spawner and space above them is covered by blocks?

How does the spawner work? Does it check for available space or just tries to spawn mobs randomly and if there's no space where it tried to spawn, the mobs just won't spawn?

**Comment by tterrag1098** [comment]
The powered spawner uses the same logic as the vanilla spawners. You are cutting off a lot of the available area the way it is, but you could make it spawn faster by upgrading them.

**Comment by AiwendilCiunio** [comment]
So my setup is making the process slower? This is what I found on minecraft wiki:
"The block will attempt to spawn 4 mobs at randomly chosen points within the spawning area"

But also
" If the block fails to spawn any mobs because it did not pick any suitable locations, it will repeat this process every tick until it succeeds."

How exactly does this work? When the location picked by the spawner is not "suitable", the mob will not spawn? Or will it attempt to spawn it somewhere else?

Also is the range 4 blocks in EVERY direction (so also up and down)?. Would a perfect spawner placement be in the middle of an 9x9x9 room?

**Comment by tterrag1098** [comment]
No I don't think it's 4 up/down, I believe it's 2. So a 9x5x9 room is optimal. Again upgrading your spawners should make them faster.
