### ISSUE TITLE
Any RF Mod - TE

### ISSUE THREAD

**Issue by Mattabase** [SleepyTrousers/EnderIO#2786]
https://dl.dropboxusercontent.com/u/15990261/ShareX/2015/09/crash-2015-09-08_05.16.30-server.txt

This happens when putting any RF producing next to a Cap Bank or Conduit, with the exception of Thermal Expansion itself.

**Comment by covers1624** [comment]
And just for reference that tile implements IEnergyHandler.

**Comment by MatthiasMann** [comment]
Power Converters is probably using the old RF API

**Comment by covers1624** [comment]
i don't ship the RF API, it is most likely another mod providing an out dated version of the RF API.

**Comment by HenryLoenwind** [comment]
* CoFHAPI|energy (1.7.10R1.0.1) from buildcraft-7.0.22.jar

?
