### ISSUE TITLE
Painted glowstone not connecting textures after breaking

### ISSUE THREAD

**Issue by AiwendilCiunio** [SleepyTrousers/EnderIO#2789]
When placed down for the first time, it connects with other blocks. After breaking and replacing it doesn't connect until painted again. 

Tried with Chisel 2 blocks.

**Comment by HenryLoenwind** [comment]
which Ender IO version?

**Comment by AiwendilCiunio** [comment]
EnderCore 0.0.1.17_alpha
EnderIO 2.3.0.407_beta

**Comment by tterrag1098** [comment]
Screenshots? I can't reproduce this.

**Comment by sdayton** [comment]
I also have this problem on the Project Ozone (Curse) modpack.  It's running the following jars:
- EnderCore-1.7.10-0.2.0.31_beta.jar
- EnderIO-1.7.10-2.3.0.422_beta.jar

I painted a glowstone block with a Chisel block (happens with Extra Utilities blocks as well).
I noticed that the metadata value changed from 10 before placement to 0 after it was broken.

![2016-01-21_15 13 57](https://cloud.githubusercontent.com/assets/29515/12493417/f0a0255e-c052-11e5-9ba7-92dcf2ec8d7f.png)
![2016-01-21_15 14 23](https://cloud.githubusercontent.com/assets/29515/12493419/f25f62ce-c052-11e5-903e-7a81b4c47c93.png)
![2016-01-21_15 14 27](https://cloud.githubusercontent.com/assets/29515/12493422/f428a2f0-c052-11e5-9739-cc35619954c4.png)
![2016-01-21_15 14 36](https://cloud.githubusercontent.com/assets/29515/12493424/f63a6da8-c052-11e5-8f3e-dadb25cf6193.png)

**Comment by HenryLoenwind** [comment]
Found the problem. We inherited vanilla's stupid "drop all blocks as items with meta=0" default.
