### ISSUE TITLE
EnderIO + TE Facade render crash

### ISSUE THREAD

**Issue by GuntherDW** [SleepyTrousers/EnderIO#2794]
Something strange seems to be happening when we upgrade from EIO 2.2 to the 2.3 beta's on our server.

Whenever someone (or there already is from before the update) places a facade on a TE cable close to a travel anchor, it will crash the client, whilst the server will run fine.
The strange issue is that so far we have only found this to happen with Ender IO Travel anchors.
With other blocks like a mekanism/TE Energy cell or anything else it doesn't crash.
The other weird thing is that it isn't even the block next to the travel anchor, but the 2nd block from the anchor.

Example screenshot from someone on our server when trying to figure out what was causing the crashes : http://puu.sh/k4k0d/2e8d2f7915.jpg
The particular blocks on the facade doesn't matter, it can also by a regular vanilla block and it will still trigger the crash.

The crashlog on the other hand does not contain any Ender IO code though, which makes it even weirder.
crashlog : http://pastebin.com/nCRLsuWH

Ender IO : 1.7.10-2.3.0.413_beta
Ender Core : 1.7.10-0.1.0.23_beta
Forge : 10.13.4.1490-1.7.10
Thermal Dynamics : [1.7.10]1.1.0-161

I'm not entirely sure where to post this, but seeing as an Ender IO block caused this particular crash it only seemed fitting to post it here. When we downgrade back to the 2.2 stable releases it works just fine and doesn't crash the client.

**Comment by MatthiasMann** [comment]
There is nothing in this which indicates that EnderIO is causing this - post this on the TD bug tracker.

**Comment by GuntherDW** [comment]
The issue is in that TD hasn't been touched between these updates. Only EnderIO has been updated and has since been starting to crash clients. But indeed I'll post it over there as well, even though only Ender IO blocks trigger this crash (as we can tell so far).

**Comment by tterrag1098** [comment]
Update chisel

**Comment by GuntherDW** [comment]
@tterrag1098 Chisel update didn't really do anything. It still crashes exactly the same.

http://pastebin.com/tKFvT6ic

**Comment by tterrag1098** [comment]
Waiting for feedback from @KingLemming or @skyboy because this needs to be debugged on TD's end.

**Comment by skyboy** [comment]
**You** are implementing IBlockAppearance and returning null from getVisualBlock.

**Comment by tterrag1098** [comment]
@skyboy Nowhere is it documented or even suggested that doing so is illegal.

**Comment by skyboy** [comment]
`This function returns the block that is being shown on a given side.`
Nowhere is it possible to render a null block.

**Comment by tterrag1098** [comment]
One could argue that "the block being shown" is only applicable when the block is *not* rendering its base state. Regardless I am working on changing this, but it will require a bit of restructuring as null values were pretty deeply ingrained in our system.

**Comment by KingLemming** [comment]
It's a fair argument either way. Since Mojang moved away from nulls, we've tended to as well. Either way, I think we know the root cause at this point.
