### ISSUE TITLE
Travel Anchor Item Label not displaying correctly

### ISSUE THREAD

**Issue by GauHelldragon** [SleepyTrousers/EnderIO#2797]
The travel anchor as a slot where you can place an item to use as an additional label. It shows up when you have a staff of traveling equipped. However: it only renders correctly when you are facing towards the south. Any other direction and the item label starts to turn, until it is completely out of view.

![2015-09-10_20 06 54](https://cloud.githubusercontent.com/assets/2829037/9806280/9c0a77ba-57f7-11e5-953b-483a47352fdf.png)
![2015-09-10_20 06 59](https://cloud.githubusercontent.com/assets/2829037/9806281/9c0d11aa-57f7-11e5-8dfb-a6e4890eabab.png)
![2015-09-10_20 07 05](https://cloud.githubusercontent.com/assets/2829037/9806285/9ee6323a-57f7-11e5-86c7-e444817c1587.png)

**Comment by GauHelldragon** [comment]
relevant code here, i believe: https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/teleport/anchor/TravelEntitySpecialRenderer.java#L125

**Comment by tterrag1098** [comment]
The problem is fast graphics are not accounted for. Will fix
