### ISSUE TITLE
Dump files are not created

### ISSUE THREAD

**Issue by Tsyklop** [SleepyTrousers/EnderIO#2798]
registered in the file "SAGMillRecipes_User.xml" is:

[dumpRegistry modObjects = "true" /]
[dumpRegistery oreDictionary = "true" /]

But the files are not created ...

P.S. If you write here "<" and ">" then the text is not displayed. Posted brackets.

**Comment by HenryLoenwind** [comment]
Have you looked in Ender IO's config directory? The help text is a bit vague here.

And btw, it also is wrong. It should be `<dumpRegistery oreDictionary="true" modObjects="true" /` if you want both. Note the typo on "registry"...

**Comment by Tsyklop** [comment]
@HenryLoenwind yes. Looked

**Comment by HenryLoenwind** [comment]
I just tried here,

```
<SAGMillRecipes>
<dumpRegistery oreDictionary="true" modObjects="true" />
</SAGMillRecipes>
```

gives me both files in config\enderio.

I don't know if there was something fixed in the last year or so, so: which version of ender io are you using?

**Comment by Tsyklop** [comment]
@HenryLoenwind Excuse me.I forgot to specify the version. EnderIO-1.7.10-2.2.8.381

**Comment by HenryLoenwind** [comment]
np, that's the version I assumed. It is the most widespread one ;)

However, I h ave no mc with that version set up here to check it. Let me see if I can find out if there was something fixed since then.

**Comment by Tsyklop** [comment]
@HenryLoenwind 1.7.10

**Comment by Tsyklop** [comment]
I can not understand...
I write in the file "SAGMillRecipes_User.xml"
like this:
[<SAGMillRecipes>

<dumpRegistry oreDictionary = "true" modObjects = "true" />

   <recipeGroup name = "Common Ores / Ingots">
  
     <recipe name = "NickelIngot" energyCost = "2400">
       <input>
         <itemStack modID = "ThermalFoundation" itemName = "material" itemMeta = "68" />
       </ input>
       <output>
         <itemStack modID = "ThermalFoundation" itemName = "material" itemMeta = "36" />
       </ output>
     </ recipe>

   </ recipeGroup>
</ SAGMillRecipes>]
But it does not create files and kraft nickel does not change ... slot ingot substituted OreDist, but indicated that the config ingot TE

**Comment by HenryLoenwind** [comment]
No, there was no change to this since Jan 2014. So it should work.

**Comment by HenryLoenwind** [comment]
_Registery_, the typo is in the code...

**Comment by Tsyklop** [comment]
@HenryLoenwind Ohhh. The file is created. Thank you

**Comment by Tsyklop** [comment]
But the recipe for nickel is not working. He still sticks OreDict ingots

**Comment by HenryLoenwind** [comment]
For that you better set the OreDict default in OreDictionaryPreferences_User.xml

**Comment by Tsyklop** [comment]
I have set. 
##  
<preference oreDictionary="ingotNickel">    
    <itemStack modID="ThermalFoundation" itemName="material" itemMeta="68" />    
  </preference>##

But still...

**Comment by HenryLoenwind** [comment]
Oops, didn't think it through. Sorry.

The smelting recipe is a vanilla furnace recipe. It is not oreDicted, nor configured in Ender IO. You need something like ModTweaker to change the vanilla furnace recipe.

Your new recipe might work (a) configure it in the Alloy Smelter config and (b) set the alloy smelter to "alloy" mode.

**Comment by Tsyklop** [comment]
AlloySmelterRecipes works fine ...
It does not work SAGMill

**Comment by HenryLoenwind** [comment]
ok, let's take a step back:

You want to sagmill nickel ingots into nickel dust? Right?

The default recipe for this is:

```
    <recipe name="NickelIngot" energyCost="2400" >
      <input>
        <itemStack oreDictionary="ingotNickel" />
      </input>
      <output>
        <itemStack oreDictionary="dustNickel" />
      </output>
    </recipe>
```

So any kind of oreDicted nickel ingot is grind into oreDicted nickel dust.

Nickel dust oreDict preferences are:

```
  <preference oreDictionary="dustNickel" >
    <itemStack modID="ThermalFoundation" itemName="material" itemMeta="36" />
  </preference>
```

So that gives TE nickel dust as result.

We don't need any oreDict preferences for the ingots, as they are the input.

Please check if above config snippets match you *_core configs. There may have been a change since 2.2.8. If not, put them into your *_user configs.

**Comment by Tsyklop** [comment]
Sorry) script does not work because there was one little mistake. I redid all knitted and everything works as it should. Thanks for the info!

**Comment by Tsyklop** [comment]
What's wrong?
`

 
    <recipe name="ElectrumBlock" energyCost="3600">
      <input>
        <itemStack modID="ThermalFoundation" itemMaterial="Storage" itemMeta="7" />
      </input>
      <output>
        <itemStack modID="ThermalFoundation" itemMaterial="material" itemMeta="71" number="9" />
      </output>
    </recipe>
    
    
    
    <recipe name="SilverBlock" energyCost="3600">
      <input>
        <itemStack modID="ThermalFoundation" itemMaterial="Storage" itemMeta="2" />
      </input>
      <output>
        <itemStack modID="ThermalFoundation" itemMaterial="material" itemMeta="66" number="9" />
      </output>
    </recipe>

    
    
    <recipe name="BronzeBlock" energyCost="3600">
      <input>
        <itemStack modID="ThermalFoundation" itemMaterial="Storage" itemMeta="9" />
      </input>
      <output>
        <itemStack modID="ThermalFoundation" itemMaterial="material" itemMeta="73" number="9" />
      </output>
    </recipe>
    
    
    
    <recipe name="SteelBlock" energyCost="3600">
      <input>
        <itemStack modID="Mekanism" itemMaterial="BasicBlock" itemMeta="5" />
      </input>
      <output>
        <itemStack modID="Railcraft" itemName="ingot" itemMeta="0" number="9" />
      </output>
    </recipe>
    
    
    
    <recipe name="BrassBlock" energyCost="3600">
      <input>
        <itemStack modID="Steamcraft" itemMaterial="blockBrass" itemMeta="0" />
      </input>
      <output>
        <itemStack modID="Steamcraft" itemMaterial="steamcraftIngot" itemMeta="2" number="9" />
      </output>
    </recipe>
`
