### ISSUE TITLE
Crash on holding iWrench(FunkyLocomotion)

### ISSUE THREAD

**Issue by SirFlip** [SleepyTrousers/EnderIO#2803]
The client crashes when you hold an iWrench in render distance to a conduit facade.
Crash log: https://pastebin.com/x3s8s7TC

Versions:
EnderIO-1.7.10-2.2.8.381.jar
funky-locomotion-1.7.10-beta-7.jar

See also: rwtema/FunkyLocomotion#79

**Comment by tterrag1098** [comment]
Since this crash is in ASM generated code I can't really debug it. This is on @RWTema's end as it seems one of our API methods is missing from his wrench.

**Comment by rwtema** [comment]
Ah right, ITool has a sub interface. My bug.

**Comment by tterrag1098** [comment]
You mean superinterface? Then yeah, it extends `IHideFacades`.
