### ISSUE TITLE
Ender IO spamming console

### ISSUE THREAD

**Issue by deadgamer1030** [SleepyTrousers/EnderIO#2804]
I just updated to ender io  1.7.10-2.3.0.415_beta and ender core-1.7.10-0.1.0.24_beta off of jenkins and as soon I open my world the console gets spammed with this message.
[17:29:35] [Server thread/WARN] [EnderIO]: NetworkPowerManager: Exception thrown when updating power network java.lang.ArrayIndexOutOfBoundsException: 8
This happening  several times a second.
Any reason this might be happening?

**Comment by Adaptivity** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/1998

**Comment by deadgamer1030** [comment]
maybe, it happen when updated it. maybe an outdated rf api somewhere.

**Comment by hron84** [comment]
Is there a way to avoid spamming log with this message? I mean, I know there is a problem, but not everybody is able to debug and fix problems like this. But the fml logs can grow to insane sizes if you spam console with error messages in every tick.

Btw, for me this is happens if Calculator mod's Flux Point/Flux plugs works with EIO cables (in my case IIRC there is a flux point dropped to a EIO cable).

**Comment by HenryLoenwind** [comment]
Not really. this is actually the program crashing hard. It's just that we abort the termination of the server and write out a message about it.

What could be done was to add the information to the message that is needed to find out what actually happened there.

**Comment by hron84** [comment]
Yeah, I experienced it now, Calculator and ImmersiveEngineering does not have a protection against this and this exception is crashed my client.

**Comment by HenryLoenwind** [comment]
After the change #2930 has gone live, please post one of the extended error outputs here.

**Comment by hron84** [comment]
@HenryLoenwind please inform me which build contains the fix and we will try it as soon as it is possible. I have to talk with our server owner, but I think he will be open for it.

**Comment by HenryLoenwind** [comment]
@hron84 That'd be the next one, 418. I'll try to remember to post in here when it's made.

**Comment by hron84** [comment]
I'll keep this page open anyway.

**Comment by Divineaspect** [comment]
having this as well with "crazypants.enderio.machine.generator.stirling.BlockStirlingGenerator@a55560e" being repeated endlessly.

**Comment by HenryLoenwind** [comment]
Please post the log. Every tenth error message should have a full stack trace.

**Comment by Divineaspect** [comment]
clarifying, fml-server-latest.log?

**Comment by HenryLoenwind** [comment]
I need the log lines that read "NetworkPowerManager: Exception thrown when updating power network" and have a stack trace after them.

**Comment by Divineaspect** [comment]
I am not finding that string anywhere in a .log I can search. My console I have to search manually.

**Comment by HenryLoenwind** [comment]
Then you have another problem than the one this issue is about. Please make a new issue and post the part of the log you have an issue with.

**Comment by Divineaspect** [comment]
will do

**Comment by hron84** [comment]
@Divineaspect if you see it in your client console, you should also check fml-client-latest.log on client too. It contains log messages displayed on the in-game console.
