### ISSUE TITLE
[CRASH] Fluid tank crashes if you use RailCraft creosote oil bottles on it

### ISSUE THREAD

**Issue by hron84** [SleepyTrousers/EnderIO#2806]
I tried to right click with a creosote oil bottle on a newly-created Fluid Tank, and... crash: http://paste.feed-the-beast.com/view/6f60128c

Affected mods (I mention both IE and RC since they both add creosote bottle, however  **my** bottle was from RC):

 - EnderIO 2.3.0-393
 - Immersive Engineering 0.4.4
 - RailCraft 9.6.1.0

**Comment by hron84** [comment]
I'm not sure why or how, but it seems Fluid tank also converts RC creosote to IE creosote as it produces IE creosote bottles.

**Comment by hron84** [comment]
Regarding to this issue: Tank consumes bottles from RC creosote bottle, but not from IE one. Something weird happening about creosote oil.

**Comment by HenryLoenwind** [comment]
About the bottles: We never decide what item or fluid to produce and the only instance where we change the result is when emtying water bottles (we add an empty bottle). All data comes from the items or the Forge FluidContainerRegistry.

About the crash: I'll have to look up which source version matches your ender io version to find the line that crashes.

**Comment by hron84** [comment]
@HenryLoenwind [this one](https://github.com/SleepyTrousers/EnderIO/tree/1213b8e465d7c6082414031b9b5fe63ccd2bad83)

**Comment by HenryLoenwind** [comment]
thx!

**Comment by hron84** [comment]
> About the bottles: We never decide what item or fluid to produce and the only instance where we change the result is when emtying water bottles (we add an empty bottle). All data comes from the items or the Forge FluidContainerRegistry.

It's right, Fluid Tank displays the RC creosoe oil's texture (as I put in RC bottle), however, when I put in an empty bottle, I get IE creosote bottle. Even if it is not a problem for me, this behavior is very strange.

**Comment by HenryLoenwind** [comment]
I think that bottle is strange. What happens here is that we try to fill it, it suceeds (and removes fluid from the tank) but does not return a filled bottle. So we crash when we try to add the missing filled bottle into the player's inventory.

**Comment by hron84** [comment]
@HenryLoenwind agree, that's what happening (after the second crash I was able to see the tank's inventory - with 1000 mB of creosote oil). However, if I put in the bottle that caused crash (I had more thank one bottle in the slot), tank consumes it without crashing and without yielding an empty bottle. 

Also, my inventory was not full, I had an inventory space - but my hotbar was full.

**Comment by HenryLoenwind** [comment]
yes, the case of bottles that are consumed isn't handled correctly here. I just don't know why, it is a standard case afterall. (And I handle it on other locations.) Maybe some changed the code after I wrote it ;)

**Comment by hron84** [comment]
@HenryLoenwind just to be sure: I know I use a bit outdated beta, but this issue affects master too?

**Comment by HenryLoenwind** [comment]
I think so, I looked at the code at master and it looks the same.

**Comment by hron84** [comment]
Good to know, thanks
