### ISSUE TITLE
Vibrant Capacitor Transfer Energy issue

### ISSUE THREAD

**Issue by HadesDurin** [SleepyTrousers/EnderIO#2808]
i use latest ender io version 2.2.8.381
latest mekanism version 8.1.7.252
latest big reactor version 0.4.3A
my vibrant capacitor banks are hooked up to a big reactor which outputs ~29,5 kRF/t
then i use ultimate universal energy cable (128kRF/t) to transfer the energy into an induction cell from mekanism.
problem is that i have to double the output value (59.000) to get 29,5kRF/t send to the induction cell

![2015-09-13_15 35 37](https://cloud.githubusercontent.com/assets/5231067/9836968/7ba7b08a-5a2e-11e5-9da2-11ba9254ef2e.png)
![2015-09-13_15 35 49](https://cloud.githubusercontent.com/assets/5231067/9836970/7babbf2c-5a2e-11e5-96c7-2dbc7dcdbe88.png)
![2015-09-13_15 36 02](https://cloud.githubusercontent.com/assets/5231067/9836969/7bab6946-5a2e-11e5-8d26-c0124b763079.png)

**Comment by tterrag1098** [comment]
Can you try this with some other form of power transfer? Maybe TD ducts? I want to confirm this isn't caused by Mekanism.
