### ISSUE TITLE
Small Bug - Conduits

### ISSUE THREAD

**Issue by zzApotheosis** [SleepyTrousers/EnderIO#2810]
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1492
EnderIO-1.7.10-2.3.0.415_beta

I'm not entirely sure if this is a bug in Ender IO or in Waila, but I'll go with Ender IO because it was fine before. In this version of Ender IO, Waila won't display an energy conduit's internal buffer and instead, displays "Conduit Connector". Tested with Tier 1 and Tier 3 energy conduits.

![2015-09-13_18 45 59](https://cloud.githubusercontent.com/assets/11908793/9840031/bbfed118-5a47-11e5-93cf-19825887539a.png)

**Comment by pja1982** [comment]
All so happening ME conduits not showing channels
