### ISSUE TITLE
Dark Steel Armor Durability.. Oddity?

### ISSUE THREAD

**Issue by leminlyme** [SleepyTrousers/EnderIO#2814]
I have a set of Dark Steel armor pretty heavily enchanted and what not, that functions mostly as expected, except for some reason one piece of armor seems to always take exponentially more damage to it's durability than the rest. Not in a sense of one of them is getting low while the others are at like half, but more like most of them are less than 10 durability damage by the time one of them is breaking. At first, it was my shoes, but since I made new shoes because they broke when I wasn't paying well enough attention, now it's my pants. Any source of mob damage I take typically reduces it's durability by about 4-8 pts per hit. Lava does the expected 1/20~ damage ticks I lose 1 durability, on all pieces including the pants. 
http://i.imgur.com/A0peuMv.gifv
http://i.giphy.com/3o85xBseCRXhQX0RtS.gif 2big for imgur
http://i.imgur.com/j5EOp32.png
Not sure what could be causing this behavior. 
I use a flux infused jetplate with similar enchants as my chestpiece, it powers all my dark steel nonstop. I tested with and without fluxplate, it still functions the same.

Mods in my pack include
```
AE2 Stuff by bdew
AOBD 2 by ganymedes01
Applied Energistics by AlgorithmX2
Aroma1997Core by Aroma1997
Aroma1997s Dimensional World by Aroma1997
Baubles by Azanor
Bdlib by bdew
BetterFps by Guichaguri
BetterRain by Wirsbo
BiblioCraft by Nuchaz
Big Reactors by Erogenous Beef
BigDoors by jaquadro
Biomes O' Plenty by TDWP_FTW, Adubbz
Blood Magic by WayofTime
Brandon's Core by brandon3055
Buildcraft by CovertJaguar, SirSengir, Krapht, cpw, spacetoad, asiekierka
Carpenter's Blocks by Mineshopper
ChickenChunks by Chickenbones
Chisel 2 by warlordjones, tterrag1098, TheCricket26, Drullkus
CodeChickenCore by Chickenbones
CodeChickenLib by Chickenbones
CoFH Core by CoFH team
CoFH Lib by CoFH Team
ComputerCraft by Dan200
Dimensionguard by Hilburn
Doors by iChun
Draconic Evolution by brandon3055
EJML Core by Peter Abeles
EnderCore by tterrag
EnderIO by CrazyPants
EnderStorage by Chickenbones
Equivalent Exchange 3 by Pahimar
Ex Nihilo by Erasmus_Crowley
Extra Cells by Leonelf
Extra Utilities by RWTema
ExtraTiC by Glassmaker
FastCraft by Player - Granted
Forestry by SirSengir
Forge Multipart by Chickenbones
Funky Locomotion by RWTema
Greg's Lighting by Greg_Ewing
HarvestCraft by MatrexsVigil, Rhodox
Hats by iChun
iChunUtil by iChun
Iguana Tweaks for Tinker's Construct by iguana_man, boni
In-Game Wiki Mod by MineMaarten
IndustrialCraft 2 by IC2 Dev Team
INpure Core by denoflionsx
Inventory Tweaks by Kobata
IronChests by cpw, progwml6
JABBA by ProfMobius
JourneyMap by techbrew
LogisticsPipes by davboecki, theZorro266, GUIpsp, AartBluestoke, ArtForz
Malisis Core by Ordinastie
Malisis Doors by Ordinastie
MalisisAdvert by Ordinastie
Mantle by mDiyo, progwml6
Mekanism by aidancbrady
MineFactory Reloaded by skyboy026, powercrystals
Mystcraft by XCompWiz
Natura by mDiyo
NEI Addons by bdew
NEI Integration by Tonius
NetherOres by skyboy026, powercrystals
Not Enough Items by Chickenbones
Not Enough Resources by hilburn and way2muchnoise
Open Peripheral Intergration by OpenMods, boq
OpenBlocks by Mikeemoo, boq
OpenComputers by Sangar
OpenModsLib by Mikeemoo, boq
OpenPeripheral Core by Mikeemoo, boq
PlanetGuyLib by Planetguy
Player API by Divisor
PneumaticCraft by MineMaarten
Prattle by ProfMobius, RazzleberryFox
Project Red by MrTJP, Chickenbones
Railcraft by CovertJaguar
Realistic World Gen by ted80
Redstone Arsenal by CoFH team
Redstone In Motion by jakj
Roguelike Dungeons by Greymerk
Simply Jetpacks by Tonius
Squake by squeek502
Steve's Addons by Hilburn
Steve's Factory Manager by Vswe
Steve's Workshop by Vswe
Thaumcraft by Azanor
Thaumic Energistics by Nividica
Thaumic Tinkerer by pixlepix, nekosune, Vazkii
Thermal Dynamics by TeamCoFH
Thermal Expansion by CoFH team
Thermal Foundation by CoFH team
TiC Tooltips by squeek502
Tinker's Construct by boni, mDiyo
Tinker's Mechworks by mDiyo
Translocators by Chickenbones
Twilight Forest by Benimatic
Waila by ProfMobius
Waila Harvestability by squeek502
WAILAPlugins by tterrag
Wawla by Darkhax
Wireless Redstone CBE by Chickenbones
```

**Comment by leminlyme** [comment]
Might I also add that I read a funny requested feature about invincible armor, which I agree would be stupid, but could you consider the idea of armor breaking into an unusable state rather than deleting itself? Like tinkers tools, I invested hundreds of levels into these sets of armors and I don't want to see them break from some strange oddity like this, I was quite sad to see it happen randomly at one point  D:

**Comment by HenryLoenwind** [comment]
Minecraft asks the armor pieces one after the other to reduce the damage. The remaining damage is then removed from the player's health. What seems to happen here is that the first armor piece already takes all the damage armor can absorb, so the following ones don't have anything to do.

BTW: Please state at least Ender IO's version number in bug reports. Thanks

**Comment by leminlyme** [comment]
I see. Why do they all lose durability at super slow paces, but one of them gets broken in about a minute of usage then? :S 

Currently on EnderCore-1.7.10-0.1.0.23_beta

**Comment by HenryLoenwind** [comment]
ok, I was hoping that was all to it...

**Comment by justicesays** [comment]
Do you have a thorns enchant on any of the pieces?
Thorns damages the armor on top of the damage you take from the mob.

**Comment by leminlyme** [comment]
no sir! Regretfully I don't even have this world anymore, and I haven't made any dark steel armor on the new betas I've played a bit of.

But I do remember I specifically did not have thorns. I think one of those gifs probably shows everything I had on them.

**Comment by Badcholo** [comment]
There is a config option to stop ender io armor from taking damage when it is powered.
