### ISSUE TITLE
Dimensional Tranceiver Buffer drain

### ISSUE THREAD

**Issue by robotunicr0n** [SleepyTrousers/EnderIO#2815]
Honestly don't know if this is a bug or the way it's supposed to work, but it seems more on the buggy side so I wanted to lodge it here. I have run into an issue a couple of times with my digital miner and dimensional tranceiver setup. Description of the network is that we have a large windmill farm running and pumping power via tranceiver. I have a public channel set up for the PowerTree as it's called, and I use it to fill a capacitor bank at my main base and also powers the digital miner as we move it around.

This issue occurs when we move the digital miner. I use the TE crescent wrench to pop the digiminer and the tranceiver, which were running seamlessly. We move a chunkloader around with the digiminer but I don't think that factors into this issue. So after taking down the mining setup I traveled to its next destination and put down the digiminer with a full internal buffer of power, and put the chest attached to the back and the tranceiver on top with 1 advanced universal cable connected between the digiminer and the tranceiver. When I set this up a couple of days ago and turned the system on, the internal buffer in the digiminer drained out, harvesting perhaps 1-2 items, and then emptied. I checked the tranceiver and it had 2 full color bars on the first page (local and internal buffer or something like that). First the bar on the right starts going down and then the bar on the left starts going. It loses power at around 20RF per tick, and with 400000 in each buffer (or whatever the enormous values are) it takes a whole real life day or so before it fully drains out. I haven't logged back in to check on it yet but in the past after this internal buffer drain occurs, it fills up again normally and begins working. I'm hoping that will happen this time too, but if not I'm going to be rather upset.

One last slightly unrelated thing - did I totally miss a spot on one of the UI windows for the dimensional tranceiver to charge items? I was way out in the boonies and my jetpack took a bigger fuel hit than I figured it would so I wanted to charge it in the dimensional tranceiver cause it provides power and that makes sense (unless I'm crazy...)! Instead after getting frustrated at finding nowhere to charge it, I stuck it in the send box on the main page thinking i had finally found the power... and was rewarded by the tranceiver sending it as an item back to my base. :'(

**Comment by tterrag1098** [comment]
Dimensional Transceivers have an idle draw, it takes energy to keep a transceiver active.

**Comment by robotunicr0n** [comment]
Sure, but if I place it on a new location and hook it up to the digiminer, shouldn't it start pulling power again and filling the internal buffer? All I saw happening was the power drain all the way without powering the digital miner in the meantime. It only starts powering the digital miner after the internal buffer drains all the way, and then it acts like it's brand new and you've just placed it and hooked it up to your channel for the first time.

**Comment by tterrag1098** [comment]
Are you sure that the power source for the transceiver is chunk loaded? And that it is connected to that channel on receive?

**Comment by robotunicr0n** [comment]
Yep I double checked when I placed it and it was still receiving from PowerTree which is chunkloaded. One thing I haven't thought of though is if one of the other players on my server stole the chunkloader from the tree, I'll have to double check, but I'm inclined to think it isn't that.

**Comment by robotunicr0n** [comment]
Okay someone stole the chunk loader... so the issue here is clearly that the power plant wasn't chunkloaded. I thought I had seen other situations where this issue occurs, so if I manage to find them I'll report back, but for now I'll close.
