### ISSUE TITLE
EE3 Support

### ISSUE THREAD

**Issue by jztech101** [SleepyTrousers/EnderIO#2817]
EE3 support for its items?

**Comment by HenryLoenwind** [comment]
I've been looking into it yesterday. Most if Ender IO's items would have EMC values, but there are bugs in EE3 that prevent that. Main one is that is fails to compute EMC as soon as an item in the recipe has multiple oreDict names. I plan on adding the support, but until EE3 gets an update that addresses this, it's not high on my TODO list---I don't want to add code to compute EMC for items that EE3 should compute itself.

**Comment by jztech101** [comment]
Hmm I'm confused. Because EE3 seems to lack EMC for most of the alloys and stuff. I assumed it ws because they go through a machine that EnderIO needed to inform EE3 about. Should those be computed automatically?

**Comment by HenryLoenwind** [comment]
No, alloys and liquids need to be added from our side. But EE3 doesn't manage to compute EMC for e.g. the Basic Gear---which is just 4 cobble and 4 sticks. Depending on the installed mods, many or even most of the basic recipes---which only contain vanilla items---fail to compute. That is what makes it not so useful to add the alloy and fluid emc values.

**Comment by jztech101** [comment]
Hmm. Then how are Furnace recipes auto-computed? Can't you simply add the
Alloy Furnace as another "furnace" for alloys? Also, as for the failure to
calculate EE3 I have found that installing EE3helper resolves the issue.
Though that would explain why I have to Forge Lexicon one mods Copper Ingot
to another to get the proper EMC when the mod claims to add EMC values for
all the equivalent ore dict items.

**Comment by tterrag1098** [comment]
The fact that you need *another* mod to make EE3 work properly makes me less inclined to add support for it.

**Comment by jztech101** [comment]
The thing is, it seems the development version of EE3 appears to fix the issue (based on what I have seen on Soaryns Stream and Dire's series) with the lack of DynEMC values being calculated. the problem with that is.. it seems that pahimar has yet to do a proper release. And this version just does not work properly. I have heard rumors of buildcraft being an issue among other things.

**Comment by HenryLoenwind** [comment]
As tt said. However, I plan to do so. It is not much hassle to register our liquids and alloys. *If* the automatic calculation for crafting recipes works.

It'd be nice if EE3 had an IMC API. It's much simpler to send a couple of messages than to include yet another batch of code.

**Comment by HenryLoenwind** [comment]
Recipes with glass, sand, sticks or ender pearls still fail to compute in EE3. I force some of the more basic ones (gears, binder, item conduits) to get a least most things values.

**Comment by WolfAmaril** [comment]
I know I'm a bit late to the party, but I would like to add the EE3H has never claimed to add oreDic support for EMC. What it does add is a command you can use to add custom EMC to an oreDic entry from the console or as an OP inside an instance.

This ability is also available in EE3, albeit slightly more difficult to implement for your average user.
