### ISSUE TITLE
[Suggestion] More Upgrades for tools?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2819]
I'd like to be able to upgrade my pickaxe for example, to be able to dig 3x3 area. Should of course cost way more RF too if upgraded.

Other upgrades for other tools I'll leave up to you. Cos the pickaxe is my main tool, probably every minecrafters :P.

**Comment by Badcholo** [comment]
How about a Paxel?

**Comment by tterrag1098** [comment]
Actually a mod by @MikeLydeamore and myself called ToolUtilities allows 3x3 mining with EnderIO tools, if you want it :p

**Comment by Badcholo** [comment]
That mod seems really cool, i really like it. Thanks.
With the max mining speed of stone on my server, this mod destroys the Atomic Disassembler from mekanism and makes EnderIO the top tier tool set.
https://github.com/SleepyTrousers/EnderIO/issues/2943
