### ISSUE TITLE
Appears to be Compact Machine issue

### ISSUE THREAD

**Issue by LucidTheStick** [SleepyTrousers/EnderIO#2821]
Running the 0.1.0 Ferret Business pack on kcauldron when we hit this...

http://pastebin.com/gQGuQuu4

**Comment by tterrag1098** [comment]
Your beta version is extremely outdated

**Comment by LucidTheStick** [comment]
*sigh* Mod pack authors.  Also got the details from the player.  Appears to be when connected to the Compact Machine interface in this screenshot.

http://i.imgur.com/Lhu60EV.png

**Comment by tterrag1098** [comment]
I can't help you until you try with the latest beta release, I have no idea what the code looked like in that version.

**Comment by HenryLoenwind** [comment]
I get the feeling we should wrap all mek api calls in a `try {} catch (*) { disableGasConduitsWithMessage() }`...
