### ISSUE TITLE
server crash on start after updating

### ISSUE THREAD

**Issue by BBoldt** [SleepyTrousers/EnderIO#2822]
No idea what I did, and the crashlog keeps changing >.>

https://gist.github.com/bed297aa2d8967e53d43
https://gist.github.com/634b2681f187809098a1

* EnderCore-1.7.10-0.1.0.24_beta.jar
* EnderIO-1.7.10-2.3.0.415_beta.jar
* Forge 10.13.4.1492
* bunch of other mods (see log)

Reverting back to the old version doesn't fix it either.
* EnderCore-1.7.10-0.0.1.12_alpha.jar
* EnderIO-1.7.10-2.3.0.402_beta.jar

https://gist.github.com/d5950c88d660f02c811a

I'm guessing it was one of the other mods I updated, unfortunately I updated 59 mods at once so i'm not sure which it is.
Update list:
https://gist.github.com/97ce14878dedd1d7494a

I've seen both galacticraft and mekanism get mentioned in the logs, but there is also that one where they don't get mentioned. I tried disabling gas conduits but that didn't help either.

Any idea what happened here?

**Comment by BBoldt** [comment]
Found this in the server log, seems to be related:

https://gist.github.com/c47b5f862a2c1dcb47bf

**Comment by HenryLoenwind** [comment]
You save file got corrupted. No matter what the original cause was, your problems will not go away until you delete all corrupt blocks.

@tterrag1098 FYI: I started going through eio and type-hardening all getTileEntity() calls. Things like this are happening too often.

**Comment by BBoldt** [comment]
I think the block IDs in my world got scrambled.

Removed enderio completely and similar issues persist with other mods, such as AE2 or Agricraft.

https://gist.github.com/3d43bce320bd9e64237d
