### ISSUE TITLE
Speed Upgrade Dark Steel Armor

### ISSUE THREAD

**Issue by MattMLeonard** [SleepyTrousers/EnderIO#2825]
I put speed upgrade on my Dark Steel armor on the leggings and every time that I push the hot key to turn it on or off it will boot everyone else on the server off. There is nothing in the crash logs to indicate why this might be happening just says Fatal Error to the people that are kicked off. Using endercore version 1.7.10-10.1.0.23_Beta and EnderIO Version 1.7.10-2.3.0.414_Beta.

**Comment by HenryLoenwind** [comment]
Same as #2743
