### ISSUE TITLE
Lapis Block to Lapis Lazuli Recipe Bug

### ISSUE THREAD

**Issue by andersleet** [SleepyTrousers/EnderIO#2828]
I noticed that in NEI the recipe for Lapis Lazuli from a Lapis Block (not dense, even though in NEI both say they yield the same) using an alloy smelter (in furnace mode) says you will get 18 Lapis Lazuli. However, you only get one. Since I found this out on a server I play on with friends that has many, many mods loaded, I created an ender IO-only world and was able to recreate the same issue.

**Comment by HenryLoenwind** [comment]
Please check what happens in a vanilla furnace and give your Ender IO version.

**Comment by andersleet** [comment]
1 Lapis from vanilla furnace.

I am using Ender IO version 1.7.10-2.2.8.381

**Comment by HenryLoenwind** [comment]
Ok, then Ender Io is working as expected---in furnace mode it mimics the vanilla furnace.

I'll have a look at the NEI display later.
