### ISSUE TITLE
Vibrant capacitor dupe bug

### ISSUE THREAD

**Issue by xenoflot** [SleepyTrousers/EnderIO#2829]
I can see that there are some similar issues open but I'm not sure if they're directly relevant. My apologies if this ticket is unnecessary..

I have a capacitor bank consisting of 96 vibrant capacitors arranged in a simple 7x7x2-high cuboid with tesseracts occupying 2 corner slots. The entire system is within a single chunk, none of the sides touching the chunk boundary. The area is covered by my chunk loader which should unload the chunks when I go offline.

I'm finding that if Items left in the charging slots, the capacitor bank is periodically shedding duplicates of these items. I haven't been able to determine the exact circumstances under which is happens though. I logged off the server last night and when I logged in this morning, my magnet picked up 37 of each of the items I'd left in to charge. While writing this report, I disconnected from the server for a couple of mins to see if that would trigger it, but it didn't.

It would seem that the dupe works for anything that'll go in the slots. So far I have duped resonant energy cells, resonant exchangers, Tier 5 Jetpacks and TiCo picks.

ChickenChunks-1.7.10-1.3.4.19-universal
EnderIO-1.7.10-2.2.8.381
EnderCore-1.7.10-0.1.0.19_beta
Forge 10.13.4.1492
Forgemodloader 7.10.99.99

If there's anything I can do to help track down this issue, please let me know.

**Comment by tterrag1098** [comment]
These issues should be fixed in the beta, can you try that?

**Comment by xenoflot** [comment]
I'm playing on a server where I don't have control over mod versions. I'll suggest that to the boss. Thanks for the snappy reply!

**Comment by TheUltimateHose** [comment]
I'm playing with:
-EnderIO 1.7.10-2.3.0.407_beta
-EnderCore 1.7.10-0.0.1.17_alpha
-Forge 10.13.4.1448-1.7.10

and I have the same issue with the basic capacitor bank. Although it's not chunkloaded, copies of the items in the charging slots spawn on the ground near the capacitor bank. It looks like the amount of the spawned copies is based on the time the capacitor bank was unloaded (I was the only player during tests), these copies don't spawn while I am online.

**Comment by mindforger** [comment]
>EnderIO 1.7.10-2.3.0.407_beta

@TheUltimateHose current version is 417! please update first and test again!

**Comment by TheUltimateHose** [comment]
Now I have updated to the newest version and now the Items in the charging slots disappear and only the copies on the ground remain.

**Comment by mindforger** [comment]
wait what? 

the "copy" drop to the ground and the original items in the slot disappear?
so what you meant to say, your issue is now that the items just become dropped(which is not really an issue) but they do not get duplicated are they ?

**Comment by TheUltimateHose** [comment]
So the Situation with the new version is:
1. I put Items in the charging slots
2. I log off
3. After some time, I log back on
4. Depending how long I was offline, multiple copies of the items which were in the charging slots spawn on the ground. The "original" items disappear, so only the duped items remain.

**Comment by mindforger** [comment]
@tterrag1098 this sounds like a cross chunkboundary issue to me

@TheUltimateHose can you verify the whole battery is within one chunk boundary and if not, does the number of copys anyway aproximate to the count of blocks inside any  chunk?

**Comment by xenoflot** [comment]
Closing this issue now. Having a related problem but the dupe appears gone.
