### ISSUE TITLE
Invisible Facades with transparent blocks

### ISSUE THREAD

**Issue by SanAndreasP** [SleepyTrousers/EnderIO#2833]
EnderIO 1.7.10-2.3.0.415-beta
Forge 10.13.4.1492

So, when I try to use transparent blocks, they appear to be invisible:
<img>http://i.imgur.com/hLR988B.png</img>
<img>http://i.imgur.com/SZNAVHT.png</img>

I'd assume this is a bug, since it works in the "old" EnderIO versions 2.2.x.

**Comment by XFactHD** [comment]
What do you expect it to be?

**Comment by SanAndreasP** [comment]
uh... I expect there to be some sort of texture.

I gave the facade the same texture as the glass block which you can see in the WAILA tooltip and placed the facade on that conduit I point at.

**Comment by HenryLoenwind** [comment]
@XFactHD see #2737 for how it should look.

BTW: @SanAndreasP Did you try with vanilla glass, too?

**Comment by SanAndreasP** [comment]
yes
http://i.imgur.com/UooXPf0.png

**Comment by HenryLoenwind** [comment]
Sorry to ask for another test, but I didn't notice your texture pack earlier: Could you try without it, just to see if it renders then? Thanks!

**Comment by SanAndreasP** [comment]
There you go:
http://i.imgur.com/qUkpF8p.png

I've removed Fastcraft and FPSPlus as well and still not showing up.
(btw, the texture pack is CoterieCraft)

**Comment by XFactHD** [comment]
@HenryLoenwind thanks for pointing that out to me, I thought that a facade painted with glass would make the whole block invisible.

**Comment by tterrag1098** [comment]
Likely caused by #2812
