### ISSUE TITLE
immibis multipart API cannot be @Optional'ed out

### ISSUE THREAD

**Issue by HenryLoenwind** [SleepyTrousers/EnderIO#2838]
java.lang.NoClassDefFoundError: mods/immibis/core/api/multipart/ICoverSystem
    	at java.lang.Class.getDeclaredConstructors0(Native Method)
    	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
    	at java.lang.Class.getConstructor0(Class.java:3075)
    	at java.lang.Class.newInstance(Class.java:412)
    	at com.enderio.core.common.BlockEnder.createTileEntity(BlockEnder.java:61)

The reason is that the method getCoverSystem() has two different definitions:

    ICoverableTile:
    	public ICoverSystem getCoverSystem();
    IMicroblockSupporterTile:
    	public IMicroblockCoverSystem getCoverSystem();

As a result Java will generate a synthetic method---which does not have the ```@Optional``` annotation:

      public synthetic bridge getCoverSystem()Lmods/immibis/core/api/multipart/ICoverSystem;

in addition to the 'real' method:

      public getCoverSystem()Lmods/immibis/microblocks/api/IMicroblockCoverSystem;
      @Lcpw/mods/fml/common/Optional$Method;(modid="ImmibisMicroblocks")

**Comment by tterrag1098** [comment]
`striprefs = true` should solve this, as per the javadoc

> Strip references to this interface in method declarations? (Useful to kill synthetic methods from scala f.e.)

**Comment by tterrag1098** [comment]
Where are the synthetic methods generated?

**Comment by HenryLoenwind** [comment]
The one above is in TileConduitBundle, I haven't looked if there's another implementation of getCoverSystem() somewhere

**Comment by tterrag1098** [comment]
I'm not sure if putting an `@Optional` on a class without the interface will work. Maybe the IM interface should be implemented on TileConduitBundle itself instead of IConduitBundle.

**Comment by HenryLoenwind** [comment]
No, there must be an interface that is implemented on the class *and* the method def must reference it by name somehow. As the offending on is a super-interface of the one we need, it should be ok to just add it to the TE. I'm on it, after my dessert...

**Comment by tterrag1098** [comment]
Ok, I'm assuming you have a test case for this so I'll let you handle it.

**Comment by HenryLoenwind** [comment]
Yes, I have my test set up.

Also, Forge is not helpful here. The synthetic looks like:

```
 // access flags 0x1041
  public synthetic bridge getCoverSystem()Lmods/immibis/core/api/multipart/ICoverSystem;
   L0
    LINENUMBER 1 L0
    ALOAD 0
    INVOKEVIRTUAL crazypants/enderio/conduit/TileConduitBundle.getCoverSystem ()Lmods/immibis/microblocks/api/IMicroblockCoverSystem;
    ARETURN
    MAXSTACK = 1
    MAXLOCALS = 1
}
```

and the interface that bring us this method is ```mods.immibis.core.api.multipart.ICoverableTile```. Forge does:

```
if (found && stripRefs)
    for methods
        if (node.desc.contains(ifaceName))
```

That is not helpul at all.

**Comment by tterrag1098** [comment]
could we tell it to strip `ICoverSystem`? Would that fail?

**Comment by HenryLoenwind** [comment]
I looked at their code, no.

We can tell it to:

(a) strip an implemented interface from a class
(b) strip a method by annotating
(c) strip methods that mentions an interface from a class that implements it

There's just no other ways to have something stripped. Unless we add our own transformer, then we could just call that existing stripMethod() on any method.

I also found out that we cannot get rid of the synthetic with any tricks like inheriting the interfaces on different levels or so.

**Comment by tterrag1098** [comment]
Honestly the problem here is that immibis overrides the method in his own interface, right? Is that necessary at all?

**Comment by HenryLoenwind** [comment]
Yes, that is the problem. (Java language says that two methods that only differ in the return value are the same method. The JVM says they are two different methods. So the Java compiler has to bridge the gap with a synthetic.)

I haven't had a good look at what the interface does, but I'd say it is never necessary. A second getWhatever() method would have done fine. But now it's there...

**Comment by tterrag1098** [comment]
@immibis I will ping him here to get his opinion. I'll also try to get to him on IRC.

**Comment by HenryLoenwind** [comment]
BTW: This has been fixed in OpenJDK: https://bugs.openjdk.java.net/browse/JDK-6695379 but it seems, not in Oracle's JDK. I guess that's why this doesn't happen when using the Jenkins builds.

**Comment by tterrag1098** [comment]
Oh, so as long as we build it...it's fine? >.>

**Comment by tterrag1098** [comment]
Automatic DRM :D

**Comment by HenryLoenwind** [comment]
Yeah. First time a come across a Java program where it makes a difference which compiler it is compiled with. ;)
