### ISSUE TITLE
Inconsistent OreDict entries.

### ISSUE THREAD

**Issue by KingLemming** [SleepyTrousers/EnderIO#2839]
Just a heads up - your block and ingot for Pulsating Iron are OreDict'd as "PhasedIron" while the nugget is "PulsatingIron" and "itemPulsatingIronNugget"

For Vibrant Alloy, the block and ingot are OreDict'd as "PhasedGold," which while somewhat curious, is again inconsistent with the nugget, which is "nuggetVibrantAlloy" AND "itemVibrantNugget"

So yeah anyways, just a heads up there. :) It'd be good to have them all line up, whichever way that ends up being.

**Comment by tterrag1098** [comment]
The original names for those ingots were the "Phased" variants. We had oredict names for them then. Then the name changed (and the oredict stayed the same) and the nuggets were added. I think the oredict were left untouched to maintain compatibility.

**Comment by KingLemming** [comment]
I figured it was for reasons of backwards compatibility, but in that case the nuggets should really also use the old name.

**Comment by UndeadZeratul** [comment]
Would registering them under both the old name as well as the correct/new ones be a problem?

**Comment by tterrag1098** [comment]
No, and that's probably what I will end up doing.

**Comment by HenryLoenwind** [comment]
I already coded the registering of both names yesterday but got interupted by work and a crashing eclipse. Solution incoming tonight.
