### ISSUE TITLE
Wireless Powered Lights Not elighting

### ISSUE THREAD

**Issue by CrazyCodeUK** [SleepyTrousers/EnderIO#2841]
Wireless Powered Lights (inverted in this instance). When they lose power do not turn back on when they receive power.
EnderCore-1.7.10-0.1.0.24_beta.jar
EnderIO-1.7.10-2.3.0.415_beta.jar

https://www.dropbox.com/s/9ak497ydn0lu4qs/Screenshot%202015-09-22%2020.33.30.png?dl=0

**Comment by tterrag1098** [comment]
Duplicates #2778
