### ISSUE TITLE
[Suggestion] Copy and paste machine configuration with Conduit Probe

### ISSUE THREAD

**Issue by Glockshna** [SleepyTrousers/EnderIO#2849]
Hi, are there any plans to add copy and paste functionality to the machines using the conduit probe? Configuring inputs and outputs of large banks of machines is really tedious as it is right now.

Thanks for all you do!

**Comment by default0** [comment]
What is the reasoning for closing the enhancement request? Is this considered redundant/too powerful? Or is there already an option to do this in the mod that I am missing? Or would it simply be too much work to feasibly implement?

My current "solution" for not destroying my hands by manually configuring hundreds of machines is placing them all down in survival (+capacitors, thank god you can just right-click on machines to put them in (except Crafters ._.)), configuring one, switching to creative to use the pick block + NBT, and replacing the machines with the NBT-stored one in creative.
