### ISSUE TITLE
WAILA conduit view not working

### ISSUE THREAD

**Issue by Keyarose** [SleepyTrousers/EnderIO#2850]
Versions
EnderIO 415 beta
Waila 1.5.10

When looking at conduits in previous versions WAILA would display information for that section( e.g. power stored for a power conduit).  Now in the current version it just reads the conduit as a conduit connector, displaying none of the specialized info.
![2015-09-23_15 12 24](https://cloud.githubusercontent.com/assets/1906772/10054187/384cfb08-6206-11e5-82e6-1504d72ad770.png)

**Comment by tterrag1098** [comment]
Duplicate #2810
