### ISSUE TITLE
Suggestion: Electromagnet support for Botania's Solegnolia

### ISSUE THREAD

**Issue by Sandriell** [SleepyTrousers/EnderIO#2852]
Would it be possible to have the Electromagnet work with the anti-magnet Solegnolia flower from Botania? 

Simply put the flower prevents Botania's Ring of Magnetization from picking up items dropped around the flower.

http://botaniamod.net/lexicon.php#solegnolia

**Comment by HenryLoenwind** [comment]
There's no clean way to do that. Luckily the dirty way is easy, simple and straightforward.

**Comment by Sandriell** [comment]
Wow, thanks for the quick response. :D
