### ISSUE TITLE
Possible memory leak with Ender IO.

### ISSUE THREAD

**Issue by iKaneki-Ken** [SleepyTrousers/EnderIO#2863]
I updated to the latest beta version of Ender IO and have noticed that ever since I have, a massive memory leak occurs, now I'm not entirely sure where to begin on diagnosing memory leaks and while yes I understand I can find out if it's Ender IO by simply removing it, I want to try and find the root cause. 

I've used VisualVM to find out what classes are using up the most memory, and from what I've seen ```int[]``` is taking up most of my servers memory with a total of 3.4GB of RAM out of 7GB allocated. I profiled my other servers and seen that ```int[]``` should normally only take up around 800MB to 1GB of RAM, and unfortunately, I can't delve into ```int[]``` to find out what precisely is causing it to take up so much memory, and so I'm here wondering if anyone can help me by link a tool or something to help me hook into ```int[]``` to find out what exactly is causing the issue

Please note as well, when this started happening, it started right after I updated Ender IO, I didn't update any other mods.

**Comment by HenryLoenwind** [comment]
Looks like the number of loaded chunks is abnormally high. (Those should be the only big int[]s.)

Just a 2 second diagnosis, maybe that info can help you.
