### ISSUE TITLE
Xp Obelisk Glitched?

### ISSUE THREAD

**Issue by ArmyOps** [SleepyTrousers/EnderIO#2864]
I was wondering can i input liquid exp from vaccuum hopper into obelisk, and it worked. Then i took all the levels out there i dont know, did i used Shift click or something but after that, i didnt get any levels and cant gain any new.
So i asked ppls what could be wrong, but no answers, trought the google i only get answers about vanilla smp glitches, but im sure thats not it.
So i was able to use /exp command on the server (Essentials plugin) and it shows me this unlogical message.
http://prntscr.com/8lupat

To throw over some questions im saying, that everything works fine in other servers. But point was to inform bug right?

I used to play Infinity 1.10.1 when it happened.

**Comment by deadgamer1030** [comment]
I’ve had this happen. I think I used /kill and it fixed this. It happen about 3 months ago but it cant hurt to try.

**Comment by ArmyOps** [comment]
I tryed to kill myself several times, didnt helped to fix issue. Admin set my exp to 0 but when i tryed to use obelisk again, then it automaticaly inserted 27k exp level in it. Looks like all the exp got stucked there somehow, but didnt exactly knew where to go. Il leave it to specialists to figure out.

**Comment by HenryLoenwind** [comment]
You're on an old version of Ender IO? I think I remember something being fixed there half a year ago or so.

**Comment by tterrag1098** [comment]
Yes, the negative XP bug was fixed ages ago.

**Comment by ArmyOps** [comment]
I dont know what version of Ender IO is on Infinity 1.10.1, but i quess its not that old.

**Comment by tterrag1098** [comment]
Find out what version it is, if it's recent we can reopen.
