### ISSUE TITLE
Invisible Enchant Not working with Dark Steel Helm

### ISSUE THREAD

**Issue by Sandriell** [SleepyTrousers/EnderIO#2865]
I have a Dark Steel Helm with the solar upgrade that I applied the Invisible enchant (Added by Artifice) to and the helm itself is invisible as expected, however the solar panel is still being rendered on top of my head.

http://i.imgur.com/qOQkUUz.jpg

EnderIO 1.7.10-2.3.0.408_beta

**Comment by tterrag1098** [comment]
I need to look into how to support this. It seems that Artifice uses the `SetModelEvent` which I've never seen/used before, personally.
