### ISSUE TITLE
[Suggestion] Spawning Error Handlin

### ISSUE THREAD

**Issue by agowa338** [SleepyTrousers/EnderIO#2867]
As mentioned in IRC, can I suggest one feature? An error message in the GUI, if the hight is wrong. Eg. "Lower the spawner by one" or "no room to the sides to spawn"

or maybe like MatthiasM2 sayd: how about spawning an ender dragon to make more room for spawning :D

**Comment by HenryLoenwind** [comment]
Start with a Wither. Only spawn the dragon if that doesn't help...

For the text I imagine the hovering text the farming station uses.

**Comment by agowa338** [comment]
How would a wither fit into the "Ender*" theme?
