### ISSUE TITLE
Item deleteion (& duplication?) via numbers

### ISSUE THREAD

**Issue by benedict42** [SleepyTrousers/EnderIO#2870]
When you move an item by pressing the number that the item is assigned to on your hotbar, the item will be physically removed from your hotbar and into an enderio/travel anchor label, and vice-versa.

**Comment by benedict42** [comment]
Oh, this applies to the latest beta build.

**Comment by HenryLoenwind** [comment]
I'm on this. Time to kill the TemplateSlot and replace it with the GhostSlot.
