### ISSUE TITLE
Inventory Panel loses items

### ISSUE THREAD

**Issue by cloakable** [SleepyTrousers/EnderIO#2871]
When crafting, if I left-click the result out everything is fine. If I right-click to grab the entire amount though, some goes missing.

Example: Four emeralds, surrounded by 32 vibrant nuggets. Right-clicking results in three vibrant crystals. No sign of the missing crystal.

**Comment by HenryLoenwind** [comment]
Somehow Minecraft treats our crafting grid a bit different than the vanilla one. And as we are using the vanilla one to do our work, we are hit be the fact that it isn't able to handle right-clicks correctly by itself.

In short, we are first asked to craft half a crafting result (normal right-click picks up half the stack!), then for whole results until the hand stack is full. The vanilla crafting grid will happily craft half a result...
