### ISSUE TITLE
Suggestion: Give the Dimensional Transceiver a slight RF/t buff.

### ISSUE THREAD

**Issue by jinks** [SleepyTrousers/EnderIO#2872]
Currently the Dimensional Transceiver can transfer 20,480 RF/t per direction. That's usually enough for most applications, but it falls slightly short of being able tu supply a Speed 3 Ender Quarry from ExUtils, which consumes roughly 24,000 RF/t. I think an increase to either 25k or 32k would do the Transceiver good in terms of popularity. I rarely see people using it on your usual popular Let's Plays and streams, everybody runs straight to TE Tesseracts. (Note: I'm not advocating infinite everything here, just giving it a bit more utility.)

And yes, I *do* know that it's configurable, but *defaults matter*. Most packs go with the default values, and when I run a server with a FTB pack for example I can hardly make all my users all change their configs manually. (In that light, having the client get the values from the server instead of relying on their own settings would also be great.)

**Comment by tterrag1098** [comment]
Client taking values from the server is part of EnderCore, problem is the EnderIO config is so expansive it would take me hours to make the switch. I will get to it eventually. Meanwhile I think 20k is a perfectly reasonable default.
