### ISSUE TITLE
Add pistons/noteblock to redstone connectable list

### ISSUE THREAD

**Issue by GameOverGaming** [SleepyTrousers/EnderIO#2875]
The Redstone Conduids do not seem to connect at all to the following devices:
Noteblock
Piston
Sticky Piston
Gold/Iron Pressure Plate
Devices from other mods

Proof Image:
![2015-10-04_21 22 19](https://cloud.githubusercontent.com/assets/12983326/10271484/05cd8ac2-6ade-11e5-92c2-b08bd77f2075.png)

**Comment by tterrag1098** [comment]
If you just wrench the side next to the block it will connect. There is no way for us to tell what blocks are "connectable".

**Comment by GameOverGaming** [comment]
Oh. I thought that was a bug of some kind.

**Comment by tterrag1098** [comment]
Just for you

![](http://puu.sh/kAa1c.jpg)

**Comment by hron84** [comment]
This is why I love this mod, there is no "impossible" just "hard to implement" :-)

**Comment by tterrag1098** [comment]
In this case it was rather easy...there is just a list of vanilla blocks it connects to. Pistons and note blocks were forgotten.

**Comment by hron84** [comment]
Poor note blocks... nobody uses them :-)
