### ISSUE TITLE
Crash after updating EnderIO version?

### ISSUE THREAD

**Issue by xJon** [SleepyTrousers/EnderIO#2876]
Hi,
Recently I got a report from someone using my modpack, that after he updated the modpack (and the mod), he crashed with [this](http://pastebin.com/0J69mjWx) log.
Any idea?
Thanks!

**Comment by tterrag1098** [comment]
That log is crazy, it mentions IC2 and Mekanism. I see no way this could be caused by us, it seems like world corruption to me.

**Comment by xJon** [comment]
I see. Do you think it's *world corruption* or chunk corruption?
