### ISSUE TITLE
Crash with NPE Unexpected Error when focus Telepad Block.

### ISSUE THREAD

**Issue by karakufire** [SleepyTrousers/EnderIO#2877]
Crash report 
http://pastebin.com/Que0nxWW

**Comment by Unrepentant-Atheist** [comment]
Can confirm: http://hastebin.com/betayugoca.1c

**Comment by Fabboz** [comment]
I've got a crash when targeting a travel anchor only with waila installed

**Comment by techniumgaming** [comment]
Also have this crash.

**Comment by tterrag1098** [comment]
Update to 417

**Comment by techniumgaming** [comment]
TY
