### ISSUE TITLE
The Vat input/output fluid

### ISSUE THREAD

**Issue by Gysburi** [SleepyTrousers/EnderIO#2878]
Maybe i found a bug in the IN/Output fluid...
If i put 1 poisonous potato and 1 sugar with 8000mb of water the vat creates 2000mb of hootch...
then no problem!
but if i use 1000mb it creates again 2000mb
in the config says: 
input fluid = IM * 1000 
but the vat works even if the fluid is minor of required fluid
and the output fluid is indipendent from the input
output = IM * fluid multiplier *1000
maybe you can add a variable to check if the fluid is enough to start the operation... or a variable to save the inserted fluid to calculate the output
ex:
output =IM * fluid multiplier * inserted fluid

**Comment by tterrag1098** [comment]
What version?

**Comment by Gysburi** [comment]
2.3.0.415 beta

**Comment by Gysburi** [comment]
2.3.0.415 beta

2015-10-06 23:24 GMT+02:00 tterrag1098 <notifications@github.com>:

**Comment by Gysburi** [comment]
happens even in the 2.3.0.416
