### ISSUE TITLE
Crash when looking at power buffer, with Waila

### ISSUE THREAD

**Issue by Oxosorrel** [SleepyTrousers/EnderIO#2879]
When I 'look' at a power buffer with Waila I get this crash on the client. Server keeps on trucking. I can look at conduits and capacitors, sag mills, alloy smelters all work fine..Only power buffers cause the crash the client when inspected by waila.

http://pastebin.com/R5kJHHZT

Forge{10.13.4.1492}
Waila{1.5.10} [Waila]
error occurs with and without WailaHarvestability{1.1.2}
EnderIO{1.7.10-2.3.0.416_beta}
endercore{1.7.10-0.1.0.25_beta}

This crash occurs with and without texture packs.

Removing waila of course is a work around for the time being, but a very painful one.

Interestingly, when I first removed walia, all the conduits were invisible (just hitboxes). I then broke the power buffer, and doing that caused all the conduits to render again.

**Comment by HenryLoenwind** [comment]
dupe to #2877 (although this has the better title ;) )

**Comment by Oxosorrel** [comment]
Duplicated indeed... And I looked to see if it was already reported and everything (admittedly I was did a quick search for WAILA in the open issues)... now I has a sad. I though I found a new bug. ;)
