### ISSUE TITLE
Glider function disconnects players on MP server

### ISSUE THREAD

**Issue by LarsBorris** [SleepyTrousers/EnderIO#2883]
Hello,

I am running the FTB Infinity pack version 1.11.2 and every time a player activates the glider function within the dark steel armor some if not all players are kicked from the server and can then reconnect with no issues. Issue occurs every time a player enables / disables the glider function.

The FTB Infinity 1.11.2 uses Ender IO version: 2.3.0.415_Beta

I have read the change notes on the new 2.3.0.416_Beta and there are no mentions on this issue.
If you need log files let me know, i have access to both server and clients.

Thanks.

**Comment by wlhlm** [comment]
#2743

**Comment by HenryLoenwind** [comment]
it's that one:

    Don't crash if in MP a client doesn't have another player's profile (commit: 367d530f8faf62c8dc6093ad1659ff1511d51ba5)

**Comment by LarsBorris** [comment]
Alright - ignore this then :)
Thanks for the feed back - I will update to 2.3.0.416_Beta
