### ISSUE TITLE
[Enhancement] Redstone Settings for Fluid Insertion 

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#2888]
I believe that enderio will become infinitely more useful if you could set up red-stone control for fluid insertion

The problem i run into using fluid conduits i when you need to control how much fluid is inserted into a device when the source of the fluid is far away from the destination. 

For example when casting items for tinkers construct you may have a large quantity of molten metal stored in the conduits themselves but only want a small amount of the fluid sent into the casting table

It would be much easier to set up if i could set the insertion point to only insert on red-stone signal however red stone control is only available on the extraction point. 

This is only one example of how adding redstone controll to fluid insertion points can be beneficial

another example is when you have one conduit leading to multiple destination machines that will send multiple fluids at varying intervals without redstone control for insertion nodes fluids can end up going to the wrong destination.

I am personally shocked that this function has not already been implemented

**Comment by SeeJayEmm** [comment]
I was also looking for this functionality. Has anyone figured out a work-around in the interim?

**Comment by HenryLoenwind** [comment]
I'll look into this.

A workaround would be using dimensional transceivers, they do respect redstone signals for their fluid transfers. Not cheap, but exact.

Another workaround would be using two tanks to put the liquid into/out of buckets and then transferring the buckets. Not as precise, but cheaper.
