### ISSUE TITLE
Add Config Option to not use A Enchanted Item as the item used in the Creative tab for EnderIO

### ISSUE THREAD

**Issue by crunkazcanbe** [SleepyTrousers/EnderIO#2889]
There is a bug in 1.7 with the Creative tabs that when using a Enchanted Item as the creative tab image the tabs will turn transparent ,and cause the tab along with other tabs from other mods to double . Thanks

**Comment by Rukachan** [comment]
The bug is in the stable forge, and this bug report is a duplicate (#2710, #1318). The last forge version has fixed it.

**Comment by crunkazcanbe** [comment]
I am using forge 1517 the latest for 1.7.10 and the issue is still there . Your the 3rd person to say the issue is fixed to me but its not sadly . I always use the latest forge version as soon as its released . I will post a screen shoot of F3 showing the forge version and the issue with the tabs if you need it .

**Comment by HenryLoenwind** [comment]
This is a known issue and caused by Forge. I'd recommend to use NEI's Creative+ mode instead.
