### ISSUE TITLE
IC2 Rubber Tree Support ( Breaking the log + Leaves )

### ISSUE THREAD

**Issue by Swapy97** [SleepyTrousers/EnderIO#2892]
Hey, 

I would really like it if the Farming Station works with the Rubber Saplings from IC2.

I read they are implemented and they get planted ingame, but they dont get farmed when the Tree grew...

btw: rly nice and awesome mod :+1:  :)

PS: sry for my bad english!

**Comment by HenryLoenwind** [comment]
You need to put a treetap into the tools slot for it to harvest the rubber...

**Comment by Swapy97** [comment]
Ohh, damn.. Thanks anyway :tractor: :dash:
