### ISSUE TITLE
Fertilizer missing from farming station?

### ISSUE THREAD

**Issue by LafinJack** [SleepyTrousers/EnderIO#2895]
Hello! I'm using Direwolf20 1.7, which includes Ender IO 2.2.8.381, and recently switched to using the farming station. I saw the notes here that said it now supports fertilizing in *.363/364, and the updated UI sprite, but the UI I see in game doesn't show the fertilizer boxes above the output. Also, my UI only shows four output boxes, not six. Is this some config the server I play on has turned off, or am I missing something?

Thanks for the great mod!

![farm](https://cloud.githubusercontent.com/assets/2436397/10384126/0cad8ac8-6dfd-11e5-8082-07732b84cc2d.jpg)

**Comment by LafinJack** [comment]
I did forget to mention that I am using a custom resource pack, but that the display is the same with the default pack.

**Comment by tterrag1098** [comment]
The fertilizer slots were only added in the beta versions.

**Comment by LafinJack** [comment]
Ah, gotcha. Oh well, thanks!
