### ISSUE TITLE
Inventory Panel Crafting Grid Result Slot bugged

### ISSUE THREAD

**Issue by HenryLoenwind** [SleepyTrousers/EnderIO#2896]
Right-clicking the Inventory Panel Crafting Grid Result Slot yields 4 items less than the recipe in the crafting grid should give. (e.g. 1 block gives 5 ingots)

build 417/dev env

**Comment by cloakable** [comment]
Duplicate of https://github.com/SleepyTrousers/EnderIO/issues/2871
