### ISSUE TITLE
Block in travel anchor

### ISSUE THREAD

**Issue by ENeMy235** [SleepyTrousers/EnderIO#2898]
When you put block to travel anchor in 2.3.0.417, it will do this:

http://jpeg.cz/images/2015/10/09/ABdCt.png
http://jpeg.cz/images/2015/10/09/VzUME.png

Water will glitch and items in NEI will burn.

**Comment by HenryLoenwind** [comment]
I just worked in the travel anchor, this doesn't happen without an other mod installed. Could you try to find out which one it is?

**Comment by ENeMy235** [comment]
I'm in process to find witch mod it is and in half of disabled mod is something which did the water bug. But the fire is still there.

**Comment by HenryLoenwind** [comment]
Great thanks.

BTW: There's a good chance that fixing the rendering probs with one mod will fix it for all.

**Comment by ENeMy235** [comment]
I try it with no other mods and it is broken there 
http://jpeg.cz/images/2015/10/09/3rARk.png

**Comment by tterrag1098** [comment]
@HenryLoenwind I believe he is saying it only occurs when there is a block as the icon item.

**Comment by ENeMy235** [comment]
Exactly

**Comment by HenryLoenwind** [comment]
Yes, I got that. However, I worked on the anchor earlier today (putting items in all slots...) and it didn't happen for me. So there must be another factor that triggers this.

**Comment by ENeMy235** [comment]
I tried it in completly new profile on curse only with EnderCore-1.7.10-0.1.0.25_beta and EnderIO-1.7.10-2.3.0.417_beta and forge 10.13.4.1517

**Comment by TheRadioGuy** [comment]
Maybe it's Fastcraft contributing to this? Also try holding XU's flying ring

**Comment by tterrag1098** [comment]
No, it was our code. It's fixed now.

**Comment by TheRadioGuy** [comment]
Guess the fix ain't on 2.3.417_beta then?

**Comment by tterrag1098** [comment]
No, check the tag. It was added in 420.
