### ISSUE TITLE
[enhancement] up and downcrafting recipies for capacitor banks 

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#2901]
The tiers of capacitor banks increase by a set multiple of 5 I wanted to suggest several shapeless crafting recipes 

5 basic banks form a bank 
5 banks form a Vibrant bank
and vice versa 
a vibrant bank breaks down into 5 banks
a bank breaks down into 5 basic banks

**Comment by tterrag1098** [comment]
There are already recipes to do this
