### ISSUE TITLE
Solar panel crash on server

### ISSUE THREAD

**Issue by Bennyboy1695** [SleepyTrousers/EnderIO#2903]
Not sure what happens but this crash we have been getting a lot lately and are not sure what is causing it https://gist.github.com/Bennyboy1695/e35cd6a856ba83952449

**Comment by HenryLoenwind** [comment]
I'd say some other mod is patching around wildly and is damaging Ender IO while doing so. As you might have noticed, one part of Ender IO is trying to call another part of Ender IO...which is not there. If that was a coding error on our side, Ender IO would have failed to compile in the first place.

Nothing we can do here. Sorry.

**Comment by Badcholo** [comment]
Dude update your cauldron to version 1492. 152 and don't go for the latest. just use version 152
