### ISSUE TITLE
[Bug] Insulated Redstone Conduits disconnect from redstone lamps

### ISSUE THREAD

**Issue by lucom** [SleepyTrousers/EnderIO#2905]
Normally conduit connectors directly connect to redstone lamps while placing them. After reloading the map or walking far away and coming back, some of these connectors disappeared and the lamps stayed dark. I then took a wrench and reattached those connectors. This seems to permanently fix that issue.

Is there an issue with the initial state of these connectors?

**Comment by HenryLoenwind** [comment]
Yes, the issue is that there is no way to find out if another block accepts redstone signals. So the initial state of the conduits is "guess". That does not work very well, as you noticed, especially when a chunk is unloaded and reloaded.
