### ISSUE TITLE
problem with Botania recipe in crafter

### ISSUE THREAD

**Issue by kotoroshinoto** [SleepyTrousers/EnderIO#2906]
mortar and pestle + petals returns the mortar & pestle to the crafting grid without using it, but this seems to be a problem for the crafter. when I try to use this recipe, it causes disconnects requiring the removal of the offending machine with mcedit

**Comment by kotoroshinoto** [comment]
There doesn't appear to be anything in the logs about it client-side or server side that I could see.

**Comment by HenryLoenwind** [comment]
Let me guess, you are using a version that's about 3/4 of a year old?

**Comment by kotoroshinoto** [comment]
actually was using EnderIO-1.7.10-2.2.8.381.jar, which was the most recent non-beta release. I don't mind updating to beta, but you shouldn't fault users for using the released version.

**Comment by HenryLoenwind** [comment]
That wasn't about you using an old version but about not stating your version in the report. That's something that happens so often that it becomes really hard to be polite about. Sry.
