### ISSUE TITLE
[Enhancement] Make Powered Spawners Modular

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#2908]
I was noticing that the method of tuning powered spawners is quite roundabout and i wanted to suggest a more modular system where broken spawners are crafted into a stable item that is inserted into the spawners inventory to serve as the tuning mechanism 

additionally this would result in reusability because the tuning item can than be removed and placed into a soul binder to reset it. this would make the soul binder infinitely more useful and provide reuse-ability to the spawning system 

currently there exists no method to recover or re-tune the broken spawner once placed inside a powered spawner and if you compare the spawning mechanics of EnderIO to MFR and DE you'll notice its excessively overcomplicated

**Comment by mindforger** [comment]
in my opinion it's quiet right, because it spawns mobs from power only  .. it does not need any mobessence like MFR, thus it's more "easy" to keep it running, but more complicated to setup

**Comment by tterrag1098** [comment]
Overcomplicated? Or just not simple? Not allowing changing of the spawn target is very intentional.

**Comment by usafphoenix** [comment]
Want to be able to change the target mob you're spawning? use MFR.
But first you'll have to kill a few enderman and a ghast, a few blazes, and have a couple emeralds. 
not cheap. but you can change the "target" mob with a simple SFM or computer craft tinkering. limiting the enderIO spawner to a single mob is, IMO a good way to keep things different/fresh and make choices have impact.

**Comment by Badcholo** [comment]
I love the Ender IO spawners and how they work.
No Work Needed. I get plenty of Broken spawners from all over.
It was very easy to learn.
