### ISSUE TITLE
Wither Skelly issues in the nether 

### ISSUE THREAD

**Issue by BuckitHead** [SleepyTrousers/EnderIO#2909]
I think bug #1899 has returned in latest version. Person on the server has Ender IO skeleton spawner in the Nether. After he left the nether and some time passed the server started lagging and TPS went thru the roof. When I was able to get to the Nether and did killall command there was 5320 Wither Skelly's and 2866 skelly's. Every time the spawner is running and you leave and come back in less then a min. there are 10-15. spawned outside away from the spawner. 

Forge server 10.13.4.1517
Ender IO .417
Ender core .25

**Comment by HenryLoenwind** [comment]
That one never got fixed because we never found out which other mod causes it to happen. All that got changed was that the config option is now "off" by default (I think).

**Comment by BuckitHead** [comment]
Ok... This was also causing issues with Draconic spawner as well. I reverted the server back to EnderIO.414 and Core to 24 and this issue is no longer happening. I'm not sure what happened on 415 and up but between this and the Conduit visual glitch I have no doubt that something went wrong.

**Comment by chezpaul** [comment]
So what is the fix to this error? No one really says what to do.
I clicked all over the web.
I'm running EnderIO-1.7.10-2.3.0.421_beta and still get this error.(Kcauldron 1492.152)
I've read to turn of Wither Skeletons in config but that's not an option in my ender config.
What should I do? My console is spammed every 30 seconds.
Thanks.

**Comment by wlhlm** [comment]
You can try it without kcauldron, and see if it's fixed then.

**Comment by chezpaul** [comment]
That's everyone's answer... Try it without KCauldron! 
Which I try every time and it always is the same, with or without KCauldron.
But of course, I will try... but my haunch is that it will still be there.

**Comment by Badcholo** [comment]
I don't see what the big deal about not supporting KCauldron is. I'd understand after 1.7.10, but while it's there, why not? a lot of players / server owners use it. Plus if that's what you use, why would you remove it to see if it still works? I think you can update KCauldron to a later version than 1492 now, but i haven't done testing to find the latest that works. I'm still at 1492.152

**Comment by chezpaul** [comment]
I've tried updating to a later version and there's some bugs I can't live with so I went back down to 1492.152. I'm not complaining about KCauldron. I don't understand that not everyone is using it.
Every models first phrase is always, bug me if you are on forge only. Which I just got use to it.
So I always have my forge equivalent.

**Comment by Badcholo** [comment]
I can't find forge version of my plugins so it kinda suxs or i'd totally convert.

**Comment by Robijnvogel** [comment]
Try Forge Essentials. This mod incorporates most of the essential Bukkit Plugins' functionality. Worldguard, worldborder, worldedit, multiworld etc.

But I should give KCauldron a shot as well. If I can get it set up on a Multicraft server, that is.

**Comment by bookerthegeek** [comment]
Issue is that their is no equivalent as good as prism for forge as there is for kcauldron.

**Comment by HenryLoenwind** [comment]
I wouldn't blame KCauldron for this. We've seen this in many different setups. Just not on our machines, sadly.

**Comment by tterrag1098** [comment]
The solution is to disable `replaceWitherSkeletons` in the config. The issue is not fixed.

**Comment by chezpaul** [comment]
That is not the solution, at least not to me and others like me. My Wither Skeletons have always been disabled.

**Comment by tterrag1098** [comment]
If that config is disabled then EnderIO does nothing with wither skeletons, so your issue is not caused by us.
