### ISSUE TITLE
Rendering glitch with Travel Anchors

### ISSUE THREAD

**Issue by ranger135xp** [SleepyTrousers/EnderIO#2910]
Hello,

I was trying to see what the space in the GUI next to the name field of the travel anchor was for. I read on the wiki that it used to be for naming the block. I thought I'd try putting a block in there, and then I noticed a big render bug. Many items appear to be affected and I decided to record the action.

I'm using EnderIO 2.3.0.417_beta

Here's my mod list: http://pastebin.com/sA7wne3a

https://youtu.be/rPUEW8z1lyk

EDIT: this appears to happen with and without the Staff of Traveling.

**Comment by HenryLoenwind** [comment]
that's the same as #2898, isnt it?

**Comment by tterrag1098** [comment]
Yes
