### ISSUE TITLE
Ender io compatibility

### ISSUE THREAD

**Issue by Idento** [SleepyTrousers/EnderIO#2911]
Hello,

I want to know why when I download ender and another mod, as Mekanism , why they are not compatible ? For example, when I want to connect a cable of ender io with a generator of mekanism, they don't want be connected

And sorry for my bad english and thanks to answer me.

**Comment by HenryLoenwind** [comment]
They are. Maybe you are doing something wrong? Give details: Version of Forge, Ender IO, Mekanism. Other Mods installed? Screenshot of problem?

**Comment by Idento** [comment]
[url=http://www.noelshack.com/2015-42-1445073127-screen.png][img]http://image.noelshack.com/minis/2015/42/1445073127-screen.png[/img][/url] 

So I tried it again today , but with less mod and I have this error, but when I can create a world with these mod i can't connect all cable of ender io with mekanism.

and here is the mod that I use usually:

EnderIO-1.7.10-2.2.8.381; Mekanism 1.7.10-8.1.7.252; CodeChickenCore	1.0.4.29; NotEnoughItems	1.0.3.74; Applied energistics 2 -rv2-stable-10; optifine 1.7.10 HD_C1; BuildCraft 7.1.10 Stable; 1.7.10-Forge10.13.4.1448-1.7.10

**Comment by Idento** [comment]
http://image.noelshack.com/fichiers/2015/42/1445078899-2015-10-17-12-45-22.png
http://image.noelshack.com/fichiers/2015/42/1445078900-2015-10-17-12-47-02.png

So my first problem is that

**Comment by tterrag1098** [comment]
If our conduits are working with other mods then it must be on Mekanism's side.

**Comment by Idento** [comment]
Yes maybe, but I do not know which side come the problem so i ask if anyone know this problem ^^

**Comment by tterrag1098** [comment]
The problem comes from Mekanism's side. Ask them.
