### ISSUE TITLE
[BUG] Render issues with conduits

### ISSUE THREAD

**Issue by miuirussia** [SleepyTrousers/EnderIO#2913]
Some times conduits will disappeared (latest beta from curse, release version not have this bug) no fastcraft, optifine or other graphic mods installed 
![2015-10-17_22 05 45](https://cloud.githubusercontent.com/assets/1270028/10560704/efe05f58-751b-11e5-98a6-19c90eebd362.png)

**Comment by wlhlm** [comment]
#2862, #2812

**Comment by miuirussia** [comment]
Reverted ConduitBundleRenderer.java from this commit and all working now!
https://github.com/SleepyTrousers/EnderIO/commit/dfff76c0d7b240d95ff45929958f7a1d9add89ed#diff-ab2849483359c85b2ca5204960267ed3R117

**Comment by tterrag1098** [comment]
Those changes were made for a reason, reverting them may not end well (especially without reverting the entire commit)
