### ISSUE TITLE
[Enhancement] Lapis Dust Recipie for SAG Mill

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#2914]
Can you please add SAG Mill support for IC2 Lapis Dust

**Comment by HenryLoenwind** [comment]
What's the technical item name, meta value, is it oreDicted, and what's the recipe?

(For technical item names: in NEI under Options->tools is a "dump" button for items. That will write a list of all items to a csv file. Meta (a.k.a damage value) is displayed in the tooltip if it is enabled in NEI.)

**Comment by Teksid** [comment]
It's IC2:itemDust, meta 12. Oredictionary is dustLapis. One lapis macerates to one dust, or a full block to nine dust.
