### ISSUE TITLE
Client/Server Entity Mismatch (See Picture)

### ISSUE THREAD

**Issue by sonicer105** [SleepyTrousers/EnderIO#2915]
I first made this report on Thermal Expansion's bug tracker but KingLemming said it was an issue with Ender Zoo, not TE.

Whenever I have Ender Zoo on my client but **not the server**, the Thermal Expansion mobs appear as Ender Zoo mobs. See this picture:
![](https://cloud.githubusercontent.com/assets/6855083/10556829/ded41168-7445-11e5-8f0c-f34c69fdacd0.png)

EDIT:

In regaurds to this, KingLemming said the following:

"This is an Ender Zoo issue. Basically if it causes that sort of problem when it's only on one side, then it should be required on both client and server. We do this for all of our mods; they should be doing it for theirs."

**Comment by tterrag1098** [comment]
So it seems the solution is to disable it on your client...?

**Comment by tterrag1098** [comment]
Also, this is the wrong repository

**Comment by sonicer105** [comment]
I apologize. I thought I clicked Ender Zoo's repository. My bad. I am however, not finished with this issue. Seeing that issues can't be moved between repositories easily on GitHub, I created a new one here: https://github.com/SleepyTrousers/EnderZoo/issues/114
