### ISSUE TITLE
Fused Quartz

### ISSUE THREAD

**Issue by jazzabee123** [SleepyTrousers/EnderIO#2917]
Yeah, just a small thing, I don't know if you've ever noticed that glass is literally the same thing as fused quartz. I just thought a slight name change might make it a bit more realistic. Something along the lines of Hard Glass or something idk, just a suggestion.

**Comment by XFactHD** [comment]
Naming it Hard Glass would make it almost equal in names to TE's Hardened Glass which could be confusing.

**Comment by HenryLoenwind** [comment]
Maybe it should have been named "Fused Nether Quartz", but (in Minecraft chemistry) it certainly isn't made from the same thing that sand is made of.

**Comment by koalalord9999** [comment]
I think Bonded Quartz would work, or maybe Synthesized :P
