### ISSUE TITLE
Conduit Crash

### ISSUE THREAD

**Issue by hasezoey** [SleepyTrousers/EnderIO#2923]
pastebin : http://pastebin.com/1KL56DXU

I have a day a problem with the conduits the conduits disappearing and comming (rendering problem i using spax x64 and optifine, i play FTB Infinity 1.11.2 with 5 extra mods) 

I hope you can help (fast) it :)

(I*m German)

**Comment by Badcholo** [comment]
remove optifine and spax and see if it still happens.

**Comment by hasezoey** [comment]
why is that? :)

**Comment by hasezoey** [comment]
ähm but i load the world save and quit and go to the other world save and quit and load the 1. world it will crash ( pastebin )

**Comment by tterrag1098** [comment]
This has nothing to do with EnderIO, your world seems to be corrupted somehow. The code was triggered by EnderIO but it has nothing to do with the error.
