### ISSUE TITLE
Feature Suggestion: Blast Resistant Conduits

### ISSUE THREAD

**Issue by Badcholo** [SleepyTrousers/EnderIO#2927]
I use a mod called Matter Overdrive. Well the anomaly seems to eat conduits if they are too close or if the anomaly is too big. Also It's very easy to accidently break the conduits sometimes if place a powered spawner and the mob shoots out fireballs and stuff. 
It would be cool if there was a conduit that couldn't be removed or very difficult unless you wrenched it.
Also blast resistant so that it couldn't be blown off by accident. I don't think anyone would mind the same texture.

**Comment by MyNameIsKodos** [comment]
pretty sure there's blastproof conduit facades

**Comment by tterrag1098** [comment]
There are
