### ISSUE TITLE
[Enhancement] Logistic Pipes Integration

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#2929]
Any chance you can enable enderio conduits (item and fluid) to connect to logistics pipes directly while most people use ME logi pipes still has a special place in the hearts of old schoolers and frankly its just convienant to be able to have enderio endpoints feed directly into a logi sorting system this would especially make handling liquid metals in tinkers construct much easier as a meshing between enderio fluid conduits and logi fluid pipes would allow extremely precise sorting and control of liquid flow rates that enderio does not support

at the moment you can sort of jury rig this using the item buffer but it can be janky and to the best of my knowledge there exists no fluid buffer

**Comment by ranger135xp** [comment]
I support this. LP is sweet and still has a relevant place in modding. @mikeloeven couldn't you use a small tank block or portable tank as a buffer for the systems?

**Comment by mikeloeven** [comment]
yes but than you loose the ability of the ender fluid conduits to carry multiple liquids at the same time unless you use one tank per fluid
