### ISSUE TITLE
Conduits disconnecting from Alvearies

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#2931]
Firstly if this has been reported, my apologizes. I tried to search for something similiar to this, but did not found anything

With Forestry v3.x everything was fine, but after we updated Forestry to v4.x players have started to experience this problem. Item Conduits are randomly disconnecting from formed forestry alvearies. I know that Forestry did some changes to the Alveary multiblocks, so maybe that is the cause?

When you put a block near the conduit (to force block update), it will again connect. But after some time (possibly after chunk unloads/loads) the disconnection happens again.

eIO: 2.3.0.417
Forestry: 4.0.10.39
Inside InfiTech 2 modpack

If needed more info: https://github.com/JasonMcRay/InfiTech-1.7/issues/399

**Comment by HenryLoenwind** [comment]
It is extremely likely a problem on Forestry's side. 

If I had to guess, I'd say the multiblock has to re-form after the chunk is loaded, but for a moment it is just a bunch of blocks---that don't have an inventory to connect to. So far it's fine, but then the multiblock forms and doesn't tell the blocks around it that it now does accept connections.

**Comment by mindforger** [comment]
you shall report this to forestry and tell them the alveary is not updating blocks when formed, causing issues with blocks requireing access to the inventory ... a random guess would be, they are rendering the alveary as real multiblock now instead of blockrendering

**Comment by JasonMcRay** [comment]
Seems like someone already beat me to it: https://github.com/ForestryMC/ForestryMC/issues/923

Closing this
