### ISSUE TITLE
Crash Not a JSON Object

### ISSUE THREAD

**Issue by MySt1k** [SleepyTrousers/EnderIO#2932]
http://pastebin.com/AqZmtNKK

**Comment by HenryLoenwind** [comment]
(1) The message is from Endercore, not Ender IO.

(2) You didn't read this part of the error log: "Found the following problem(s) with your installation: "Optifine is installed. This is NOT supported." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it." (Although in this case I doubt that is the problem)

(3) It seems one of your config files is damaged. That is usually not a programming error of the program that tries to read it. I'll have a look if you open this in Endercore.

**Comment by MySt1k** [comment]
Good. Something you are very negative to Optifine

**Comment by Badcholo** [comment]
Not negative to Optifine. You should just report the problems to the proper areas.
Remove optifine. If the mod works nicely, then it's an Optifine issue and you need to report it to them.
