### ISSUE TITLE
Feature request: A black list for the farm block. / Agracraft compatability.

### ISSUE THREAD

**Issue by NJM1564** [SleepyTrousers/EnderIO#2934]
I'm hopping that that by black-listing the crop sticks it'll allow the farm block to work with agracraft

**Comment by mindforger** [comment]
are you sure you mean blacklisting (like forbiudding something to use on something) and not whitelisting?
explain your issue a bit closer, why can't you use agracraft with the farm block ?

**Comment by HenryLoenwind** [comment]
Agricraft support is in the pipeline, after all I wrote the Agricraft API... It just got delayed a bit because "all the other things"(tm). ;)
