### ISSUE TITLE
Shift-clicking from Vacuum Chest inventory won't fill rightmost slot in hotbar

### ISSUE THREAD

**Issue by wlhlm** [SleepyTrousers/EnderIO#2935]
I'm not sure if this is a safety mechanism, but when I shift-click items from the Vacuum Chest inventory into the player's inventory, it won't fill the rightmost slot in the hotbar.

__Steps to reproduce:__  
1. Fill player inventory (except for the hotbar) with items
2. Fill Vacuum Chest inventory with items
3. Open Vacuum Chest inventory
4. Shift-click item in Vacuum Chest inventory to have it automatically placed in the player's hotbar (without having to move the mouse cursor; vanilla mechanic)

__What happens:__  
- The rightmost hotbar slot won't get filled, even if all other inventory slots are filled.

![2015-10-28_12 02 23](https://cloud.githubusercontent.com/assets/1928113/10788062/2b9b0898-7d75-11e5-96f1-7f81188b0e97.png)

EnderCore: 1.7.10-0.1.0.26_beta
Ender IO: 1.7.10-2.3.0.417_beta
Forge: 10.13.4.1448-1.7.10

**Comment by HenryLoenwind** [comment]
I fixed a bug like that in the shift-clicking code in spring. Seems the Vacuum Chest is using its own version.

**Comment by wlhlm** [comment]
Sounds like an off-by-one error...

**Comment by HenryLoenwind** [comment]
Yes it was. Also a "we need a copy of this code here, here, here and there" error.

**Comment by wlhlm** [comment]
Fixed in 419. Thanks!
