### ISSUE TITLE
Remote awareness upgrade slot not appearing on item conduits

### ISSUE THREAD

**Issue by lamodetix48** [SleepyTrousers/EnderIO#2939]
Remote awareness upgrade not appearing on item conduits with ender io 2.3.0-415 beta version.

**Comment by HenryLoenwind** [comment]
define "not appearing", please

**Comment by wlhlm** [comment]
You means the slot won't appear?

Please update to 417 and see if it still happens.

Works for me with just EIO 417 and  EnderCore  installed. Maybe  it's a cross-mod problem?
![2015-10-31_11 29 12](https://cloud.githubusercontent.com/assets/1928113/10863112/f466aecc-7fc2-11e5-902f-f581043403c3.png)

**Comment by lamodetix48** [comment]
Ok that's what i mean. I upgraded and it works just fine. Thank you

**Comment by HenryLoenwind** [comment]
Great!
