### ISSUE TITLE
[Suggestion] Soul Binder Recipes as XML file

### ISSUE THREAD

**Issue by Dream-Master** [SleepyTrousers/EnderIO#2940]
Why the Soul Binder not have a Recipe XML file and a User xml file like the other Machines in Enderio too?, It would be very nice to have the ability to add some new recipes.(Nice for Pack-Makers and Minetweaker Freaks like me :) )

**Comment by tterrag1098** [comment]
The problem is that all the existing recipes have custom logic, like NBT on items, which is not currently possible with the XML system.

**Comment by HenryLoenwind** [comment]
Yeah, I just had a quick look. I'd rate it near-impossible to express most of the build-in recipes as xml (without implementing a scripting language). It should, however, be possible make simpler recipes be addable that way. But don't hold your breath, we're aren't over-staffed and there are more important/more visible things to do.

**Comment by Dream-Master** [comment]
Ok no problem. Thanks to look inside it.
