### ISSUE TITLE
[Suggestion] Oredict flour

### ISSUE THREAD

**Issue by Rukachan** [SleepyTrousers/EnderIO#2945]
AE2 uses "dustWheat"
Natura uses "foodFlour" for both of its flours and adds a extra "foodEqualswheat" for the wheat flour
Pam's HarvestCraft uses foodFlour and flourEqualswheat

**Comment by HenryLoenwind** [comment]
We register as "dustWheat". Do we really need to spam all those names...?

**Comment by Rukachan** [comment]
@HenryLoenwind In the last beta (417) its unlocalised name is enderio.dustwheat but it is not registered in the oredictionary.

**Comment by HenryLoenwind** [comment]
Oh, you are right. All the powders don't register as the ingots and blocks do. I'll have to look into this.
