### ISSUE TITLE
[bug?] Power Monitor not working

### ISSUE THREAD

**Issue by huldu** [SleepyTrousers/EnderIO#2946]
I'm using EnderIO-1.7.10-2.3.0.417_beta and the power monitor just isn't working at all. It displays nothing at all, just 0's. Normally it would display power going in and out of the system but, nothing at all currently. It doesn't matter where I plug it in, it accepts power up until it hits the cap but like I wrote, nothing more than 0's appear.

**Comment by HenryLoenwind** [comment]
It works for me. Can you give some more infos, maybe a screenshot, list of installed mods and such?

**Comment by huldu** [comment]
I feel so dumb now, apparently it requires you to use conduits, I was using the power pipes from TE. My bad, sorry!

**Comment by HenryLoenwind** [comment]
np, it isn't obvious. They read the data from the conduit network...
