### ISSUE TITLE
Client Crash; Travel Anchor painted with oak log

### ISSUE THREAD

**Issue by BBoldt** [SleepyTrousers/EnderIO#2948]
https://gist.github.com/5b8b41e5963a83d73d5d

* EnderCore-1.7.10-0.1.0.25_beta
* EnderIO-1.7.10-2.3.0.417_beta

The solution the person experiencing this issue used was to MCEdit the offending block out of the world.

**Comment by HenryLoenwind** [comment]
From that stack trace, I'm 99.9% sure that thing was not painted as oak log.

**Comment by BBoldt** [comment]
@Nonsanity told me it was :fearful:

**Comment by mindforger** [comment]
what he wanted to say was, the travel anchor was painted as travel anchor, which was probably painted as oak wood before am i right?
