### ISSUE TITLE
Can't get SAGmill XML file to work for me.

### ISSUE THREAD

**Issue by WolfAmaril** [SleepyTrousers/EnderIO#2949]
I'm trying to remove the Metallurgy 4 Nether Ores from the SAG mill. I've added the following between <SAGMillRecipes> and </SAGMillRecipes> in the User.xml file, but the recipes still show up in NEI and work in game.

[Code here] (http://pastebin.com/mWuk3nkv)

**Comment by HenryLoenwind** [comment]
Is that the whole file? In that case you're missing the ```<SAGMillRecipes>``` and ```</SAGMillRecipes>```. If not, what does the log file say about parsing the recipes?

**Comment by WolfAmaril** [comment]
Answer to first question, I put it between those two tags in the pregenned SAGMillRecipes_User.xml file.

What would I search for in latest.log to find what you're looking for?
it's over 75K lines long and just looking for EnderIO is gonna take me hours to get through.
