### ISSUE TITLE
SAG Mill does not accept any items.

### ISSUE THREAD

**Issue by SeeJayEmm** [SleepyTrousers/EnderIO#2950]
I've recently updated from 2.2.8.381 to 2.3.0.417_beta on my forge server. Since this update I am unable to successfully use the SAG Mill. I am able to place items into the GUI but nothing happens. As soon as I exit the GUI the items are thrown to the floor for me to pick up.  This happens both for the item to be milled and the flint I put in the helper slot. 

I've tried several items (i.e. sand, cobblestone) with no success. I've also tried building a new SAG Mill in the event that there was an issue with my pre-existing mill.

No errors are output to the console.  I've also checked the fml-server-latest.log and cannot find any interesting messages there either.

**Comment by Badcholo** [comment]
have you made a new machine? Disconnect power / reconnect? Wrench it, break it? place it again?

**Comment by SeeJayEmm** [comment]
> I've tried several items (i.e. sand, cobblestone) with no success. I've also tried building a new SAG Mill in the event that there was an issue with my pre-existing mill.

**Comment by SeeJayEmm** [comment]
Also I've restarted the server, several times (that's a separate bug I need to write). Still doesn't work.

I cannot recreate it on single player.

**Comment by SeeJayEmm** [comment]
Well. I'm embarrassed to say this was user error and I apologize for wasting anyone's time.  I managed to screw up the permissions on my SAGMillRecipes_Core.xml file and the server could not read it on startup.

Thanks

**Comment by HenryLoenwind** [comment]
Thx for the update. I couldn't find any reasonable cause for this in the code.
