### ISSUE TITLE
Farming station does not accept Thermal Foundation Hoes

### ISSUE THREAD

**Issue by wlhlm** [SleepyTrousers/EnderIO#2952]
Hoes added by Thermal Foundation (Copper, Bronze, etc.) cannot be put into a Farming Station. I assume that this is a bug since TF Axes and Shears work without a problem.

EnderIO 1.7.10-2.3.0.417_beta
EnderCore 1.7.10-0.1.0.26_beta
CoFH Core 3.0.3
Thermal Foundation 1.2.0

**Comment by wlhlm** [comment]
I found the [Hoe whitelist](https://github.com/SleepyTrousers/EnderIO/blob/16b682e1cd235f3986d055919ff4f7bbba0ed20a/src/main/java/crazypants/enderio/config/Config.java#L310) in the config and it only includes the Invar Hoe, so this _seems_ to be intentional, but I wonder why only the Invar Hoe is enabled, and why aren't there whitelists for axes and shears (at least I wasn't able to find them in the configs)?

**Comment by HenryLoenwind** [comment]
That's because Minecraft has "Axes" and "Pickaxes", but not "Hoes"---just one "Hoe". So there is no way for Ender IO to see if an item is a hoe (unless it is an extension of the one existing hoe).

If you give me the data for the whitelist, I can add them into the default. Unless they have some behavior that won't work in the machine (like the one that is commented out for that), it most probably is an oversight and not intentional.

**Comment by b0bst3r** [comment]
have a load of hoes :)

        minecraft:wooden_hoe
        minecraft:stone_hoe
        minecraft:iron_hoe
        minecraft:diamond_hoe
        minecraft:golden_hoe
        MekanismTools:ObsidianHoe
        MekanismTools:LapisLazuliHoe
        MekanismTools:OsmiumHoe
        MekanismTools:BronzeHoe
        MekanismTools:GlowstoneHoe
        MekanismTools:SteelHoe
        Steamcraft:hoeBrass
        Steamcraft:hoeGildedGold
        Railcraft:tool.steel.hoe
        TConstruct:mattock
        appliedenergistics2:item.ToolCertusQuartzHoe
        appliedenergistics2:item.ToolNetherQuartzHoe
        ProjRed|Exploration:projectred.exploration.hoeruby
        ProjRed|Exploration:projectred.exploration.hoesapphire
        ProjRed|Exploration:projectred.exploration.hoeperidot
        magicalcrops:magicalcrops_AccioHoe
        magicalcrops:magicalcrops_CrucioHoe
        magicalcrops:magicalcrops_ImperioHoe
        BiomesOPlenty:hoeAmethyst
        BiomesOPlenty:hoeMud
        Eln:Eln.Copper Hoe
        Thaumcraft:ItemHoeThaumium
        Thaumcraft:ItemHoeElemental
        Thaumcraft:ItemHoeVoid
        ThermalFoundation:tool.hoeInvar
        ThermalFoundation:tool.hoePlatinum
        ThermalFoundation:tool.hoeBronze
        ThermalFoundation:tool.hoeElectrum
        ThermalFoundation:tool.hoeNickel
        ThermalFoundation:tool.hoeLead
        ThermalFoundation:tool.hoeSilver
        ThermalFoundation:tool.hoeTin
        ThermalFoundation:tool.hoeCopper
        GalacticraftCore:item.steel_hoe
        GalacticraftMars:item.titanium_hoe
        GalacticraftMars:item.deshHoe

**Comment by wlhlm** [comment]
@b0bst3r I see you've added Galacticacraft Hoes to the whitelist. I could add them to #2953, but I'm unfamiliar with them (never tried Galacticacraft), can you just quickly test to make sure nothing breaks when you insert them in the Farming Station?
