### ISSUE TITLE
Travel Anchor Label and Password mixups (version 1.7.10-2.2.8.381)

### ISSUE THREAD

**Issue by DoomRater** [SleepyTrousers/EnderIO#2955]
Tested with version 1.7.10-2.2.8.381
User SixtyEmeralds on my server set password to Wireless Advanced Pocket Computer on a travel anchor. when she was done the LABEL of the travel anchor was set to Wireless Advanced Pocket Computer, not only revealing the password but also destroying the label she set on the travel anchors.  I as user DoomRater then attempted to use the password set and was denied, even though I know I used the same item to set the password.  I wanted to make sure the label was not supposed to be part of the password, or influencing/setting the password.  We're about to retry with Item Magnet turned off as the password to see if it wasn't an NBT data issue with Pocket Computers.
I also found when setting passwords the label of my travel anchors would change as well once I exited, even though I didn't set it myself.  I cleared the label since it was otherwise giving away the password, but others were able to use my travel anchors with the password afterwards.

**Comment by HenryLoenwind** [comment]
If it isn't already fixed in the beta, it will definitely be fixed by #2897 (which rewrites the whole password/name system).
