### ISSUE TITLE
TInkers Mattock in farming station

### ISSUE THREAD

**Issue by cauliflower69** [SleepyTrousers/EnderIO#2957]
Worked for a bit then crash loop 

http://pastebin.com/pB1f3KUt

**Comment by HenryLoenwind** [comment]
That crash is not related to the hoe used, it happens when right-clicking a mature plant with an empty hand to harvest it.

Does anyone know what line 356 in net.minecraft.server.management.ItemInWorldManager actually is? @tterrag1098?

**Comment by HenryLoenwind** [comment]
Could you please check your logfile for the server startup: Does any mod claim to patch net.minecraft.server.management.ItemInWorldManager.func_73078_a() or net.minecraft.server.management.ItemInWorldManager.activateBlockOrUseItem()?

**Comment by HenryLoenwind** [comment]
The latest version contains a change that **might** help. I'd really like to get some feedback on this. Thx.

**Comment by Mr-Rixa** [comment]
Tested with newest version of EnderIO and Endercore, no crash with Tinkers mattock in farming station on SMP.
