### ISSUE TITLE
The Coord selector crashes when right clicking and when looking at the tooltip.

### ISSUE THREAD

**Issue by XFRGod** [SleepyTrousers/EnderIO#2961]
http://pastebin.com/BeDbj00V

**Comment by tterrag1098** [comment]
How did you create this item? It seems to be missing its NBT data.

**Comment by XFRGod** [comment]
I crafted it and then shift+right clicked on a block below me(It was a telepad block but I tried it with dirt and other things). Then it crashed. Then I put it in my AE system and whenever I mouse over it it crashes.
