### ISSUE TITLE
[Suggestion]  solar helmets

### ISSUE THREAD

**Issue by Cronosus** [SleepyTrousers/EnderIO#2962]
Hello
only suggestion
Can you please add solar helmets?
it will be nice. :)

thanks in advance

**Comment by tterrag1098** [comment]
This already exists...

**Comment by wlhlm** [comment]
@Cronosus The Dark Helm has solar upgrades. They is available after Empowered I has been applied to the Helm.

I guess that the confusion stems from the [missing documentation of said upgrade on the wiki page](http://wiki.enderio.com/Dark_Helm#Upgrades). Would be nice if that gets added (unfortunately, I don't see a way to edit the wiki page myself).

**Comment by tterrag1098** [comment]
@wlhlm You need to ask for access, we have had issues with spammers when registration was open

**Comment by Cronosus** [comment]
yes, dark helm has this upgrade, but its only one ... 
ok

**Comment by wlhlm** [comment]
There are actually two upgrades...

**Comment by HenryLoenwind** [comment]
no, three...

;)

**Comment by wlhlm** [comment]
I can only see [two](https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/item/darksteel/upgrade/SolarUpgrade.java#L30-L31).

**Comment by wlhlm** [comment]
Ok, the 1.8.9/1.9 port has a [third](https://github.com/SleepyTrousers/EnderIO/blob/1.8.9-exp/src/main/java/crazypants/enderio/item/darksteel/upgrade/SolarUpgrade.java#L17-L19), but that didn't exist at the time of answering ;).

It still has to be documented in the wiki though…
