### ISSUE TITLE
Suggestion: Advanced Item Buffer or upgrade

### ISSUE THREAD

**Issue by Teksid** [SleepyTrousers/EnderIO#2964]
I use item buffers to subnet item conduit networks, and one that has per-slot item filtering could be really handy in some situations. For example, I have a subnet for Forestry ethanol; if my fermenter fills up with saplings they start to clog up the buffer, eventually blocking apple flow to the squeezer and bringing the entire process to a deadlock.

There are other ways I could go about it to avoid that, but a buffer with per-slot filtering would still be pretty handy.

**Comment by HenryLoenwind** [comment]
BTW: The Ender IO Addons' Impulse Hopper can do that. You'd need one per item, though.

**Comment by Teksid** [comment]
I did not know about that mod, thanks. Definitely going to use that power monitor all over the place. I'm not sure the Impulse Hopper would really fit though, unless I'm misunderstanding it. It looks like it's for specific quantities of different items, whereas a buffer with filtered slots could be configured to ensure that one item backing up couldn't end up filling up all 9 buffer slots and blocking everything else.

**Comment by HenryLoenwind** [comment]
After starting to write down how it would fit, it came to me that a second buffer with an insert filter set to "apples" would do the same thing. Oops. ;)

(But I think the Impulse Hopper would also make a good "parent" for your suggestion.)

**Comment by justicesays** [comment]
Just going to ref #2514 here, as its basically the same request.

**Comment by HenryLoenwind** [comment]
#2514 is actually a better use case for using an Impulse Hopper than this one. Still not perfect if you don't care about the exact makeup of the item mix. Thx for linking it in.
