### ISSUE TITLE
Baubles: Battery Around The Neck

### ISSUE THREAD

**Issue by Badcholo** [SleepyTrousers/EnderIO#2965]
Some sort of battery to wear in the Baubles slot to keep armor charged up. or for it to pull from inventory batteries / capacitors.

**Comment by HenryLoenwind** [comment]
Design decision was to have the wireless charger instead of a battery. Sorry.

(This has been asked/requested before, closing.)

**Comment by Badcholo** [comment]
Oh, i see, what about running out of power in long pvp matches?

**Comment by tterrag1098** [comment]
I think there are other mods that do this. It may be looked into but it's not a priority atm.

**Comment by Badcholo** [comment]
ok thanks
