### ISSUE TITLE
[Request] Reloading recipe configs in game

### ISSUE THREAD

**Issue by karakufire** [SleepyTrousers/EnderIO#2974]
It's anoying relauching game to reload recipe config.
I want to apply recipe changes quickly.

**Comment by Badcholo** [comment]
lol, you want someone to configure your recipes too?

**Comment by HenryLoenwind** [comment]
I feel your pain. I have to restart the game 30 to 40 times a day when working on Ender IO.

However, priority goes to game play things, so don't hold your breath,

**Comment by aionys** [comment]
If you restart that often working on the mod, it seems to me that an in-game reload command would be worth the savings in time you'd get from not needing to restart the game that often anymore when working on it.

**Comment by VT-14** [comment]
+aionys I doubt that very many of Henry's 30-40 restarts a day are simple config changes.
