### ISSUE TITLE
[Feature Request] Dark Steel Hammer

### ISSUE THREAD

**Issue by Protheus** [SleepyTrousers/EnderIO#2976]
A dark steel hammer, mines 3x3 initial and with upgrade goes up and faster and more RF storage.

**Comment by Badcholo** [comment]
http://www.curse.com/mc-mods/minecraft/224591-toolutilities

This mod adds in 3x3 to the ender io pick. other features can be disabled or keep em.
It gives more upgrades to the pick and other tools. It does increase rf usage as well.

**Comment by Protheus** [comment]
Nice will try it out. Just want to remove tinkers but still like to keep the 3x3 on mining and instant tree cutting.

But hope EIO makes something like a hammer or upgrade to the pickaxe

**Comment by Badcholo** [comment]
Yes, me too. Ender io axe does a pretty good job at cutting down trees. I didn't like tinkers either.
Check out my modpack.
http://www.technicpack.net/modpack/mojangsters.583708
Youtube channel
https://www.youtube.com/channel/UCVRDbrSypbA696FHcaiBhkg

**Comment by Protheus** [comment]
Nice modpack - start doing a lets play on your channel and I will sub ;)

**Comment by Badcholo** [comment]
thanks
