### ISSUE TITLE
Feature Suggestion: Anvil Can Remove Enchantments.

### ISSUE THREAD

**Issue by Badcholo** [SleepyTrousers/EnderIO#2978]
It would be nice if i could remove the enchantments off loot armor and place it in books.
This sounds like a nice feature for everyone. Not abilities like empowered, just regular enchantments.

**Comment by HenryLoenwind** [comment]
Ender IO Addons has a machine that does this.

**Comment by Badcholo** [comment]
I thought it would be a nice feature for the anvil to be able to remove enchantments off "any" item and place them into a book. Since my enchantments go up to example Sharpness X in survival. I really liked the anvil level increase config, Thanks thou.

Quote from Ender io addons page."Please note that this is not an universal recycler. It only processes vanilla and Ender IO tools, weapons and armor However, it also strips the enchantments off those items."
