### ISSUE TITLE
Enchanter and higher enchants

### ISSUE THREAD

**Issue by Badcholo** [SleepyTrousers/EnderIO#2982]
On my server players can get higher level enchants, such as protection X.
The enchanter shows that i can get level X but i'd have to imput 160 dark steel.
I don't know how i can do this.
Modpack location.
http://www.technicpack.net/modpack/mojangsters.583708
![2015-11-08_19 40 29](https://cloud.githubusercontent.com/assets/10932905/11024798/00d9c470-8651-11e5-8a4d-3d680b23a3bd.png)

**Comment by Badcholo** [comment]
I would like to say that you can get protection X in survival. As well as Fortune V Fire Aspect V Haste X and so on in survival. I don't know if it is possible to adapt the enchanter to this. It would be cool to see it compatible with this mod, but i understand you have bigger issues.
http://www.planetminecraft.com/mod/152-superenchants-v03-recoded---high-leveled-enchants-protection-10-etc-continued-by-twinklez/

**Comment by mindforger** [comment]
how about making books with the max possible enchant and then force the players to combine them in the anvil .. increases the required level by a decend level

**Comment by Badcholo** [comment]
I already sell the books with the enchants at the Global Market. Some players don't like being forced to purchase items from the shop. Also With Better anvils mod. 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286937-better-anvils-removes-the-level-limit
You can combine books of the same to get a higher enchant. 
Also you can strip enchants from armor making it pretty useful for all that junk armor i get off mob drops.
I just really like the enchanter and want to make it better. It really makes it easy to understand what you need to what you get. I quite a bit of enchants like plague, pain, acid, as an example.
Is there a way to add these enchants and to what they cost?
