### ISSUE TITLE
Server reboot after a user connects.

### ISSUE THREAD

**Issue by bakaie** [SleepyTrousers/EnderIO#2983]
Running FTB Infinity 2.0.2 with a few extra mods installed.

We are getting a server crash and reboot after a user logs in.

http://pastebin.com/s8bJ0JkV

Looks like an issue with his farming station when he loads his chunks.  I talked with the user he has 2 farming stations, one is not powered currently, the second has power, me import bus and is farming Ender Lilies, nether wart, cotton, and a few magical crops. It currently has an amethyst hoe in it. We have several other users with Farming stations setup and working with no issue, it is just this one user.

Let me know if you need any additional information.

Thanks.

**Comment by neogenix** [comment]
(I'm the user) We also tried rolling to the latest version (from a few days ago), as well as updated both EnderIO and EnderCore. It seems like when I login the chunk loads, and something odd happens. I wasn't touching the active, or inactive, station, or even in the same vicinity. The active one has been running with these plants for a few days. The only changes to it have been to add more magical crops, and remove some of the cotton, but of the same type of magical crops, no new plants.

We did have it doing essence berries, but that caused random berries, so we disabled it using the property (as it seems it's happened to others before).

**Comment by mindforger** [comment]
related to https://github.com/SleepyTrousers/EnderIO/issues/2957

**Comment by HenryLoenwind** [comment]
Yes, that's the same crash.

It seems that either the fake player or the world object that is part of it are not there. Really funny business; it's not as if we had a change there recently. I'll see to put some sanity checks into the next version.

**Comment by HenryLoenwind** [comment]
Could you please check your logfile for the server startup: Does any mod claim to patch net.minecraft.server.management.ItemInWorldManager.func_73078_a() or net.minecraft.server.management.ItemInWorldManager.activateBlockOrUseItem()?

**Comment by bakaie** [comment]
I am not seeing any in the ones that i looked at before taking off for work.  I will do a search on all the server logs later today and let you know/attach the log files if i find any.  Thanks for jumping on this and helping out.

**Comment by neogenix** [comment]
Linked to duplicate #2985, closed parent.

**Comment by bakaie** [comment]
Sorry for the slow response, I have looked through the log files and do not
see any of the lines you asked about.

On Mon, Nov 9, 2015 at 12:38 PM, Patrick <notifications@github.com> wrote:

> Linked to duplicate #2985
> <https://github.com/SleepyTrousers/EnderIO/pull/2985>, closed parent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-155168204>
> .
>



-- 
Thanks
Brian

**Comment by HenryLoenwind** [comment]
No problem, I didn't really expect you to.

**Comment by HenryLoenwind** [comment]
The latest version contains a change that **might** help. I'd really like to get some feedback on this. Thx.

**Comment by bakaie** [comment]
I was running 2.2.8.381 on my server and we had no issues using farming
stations.  After the upgrade to 2.3.0.417 is when it broke.  At this point
I have rolled my server back to a date before the issue came up and just
destroyed all of the farming stations.  This seems to have fixed the crash,
but I have told everyone to not use the farming stations or killer joe
until we get a fix.  I did make a clone of the container before i did the
roll back so i could test new code when it is released to see if it will
fix the issue.

Let me know if you would like any more info.  Like I said i have a clone of
the server that will crash and can test/run anything you have to verify it
fixes the issue.

On Sat, Nov 14, 2015 at 8:39 PM, Henry Loenwind <notifications@github.com>
wrote:

> The latest version contains a change that *might* help. I'd really like
> to get some feedback on this. Thx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-156776043>
> .
>



-- 
Thanks
Brian

**Comment by bakaie** [comment]
Just read that again,  I will download the new version and try it on my
clone to see if it takes care of the problem.

Thanks


On Sun, Nov 15, 2015 at 11:07 AM, Brian Norris <brian.norris.it@gmail.com>
wrote:

> I was running 2.2.8.381 on my server and we had no issues using farming
> stations.  After the upgrade to 2.3.0.417 is when it broke.  At this point
> I have rolled my server back to a date before the issue came up and just
> destroyed all of the farming stations.  This seems to have fixed the crash,
> but I have told everyone to not use the farming stations or killer joe
> until we get a fix.  I did make a clone of the container before i did the
> roll back so i could test new code when it is released to see if it will
> fix the issue.
>
> Let me know if you would like any more info.  Like I said i have a clone
> of the server that will crash and can test/run anything you have to verify
> it fixes the issue.
>
> On Sat, Nov 14, 2015 at 8:39 PM, Henry Loenwind <notifications@github.com>
> wrote:
>
>> The latest version contains a change that *might* help. I'd really like
>> to get some feedback on this. Thx.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-156776043>
>> .
>>
>
>
>
> --
> Thanks
> Brian
>



-- 
Thanks
Brian

**Comment by bakaie** [comment]
I put the new version of EnderIO and EnderCore on the clone and started the server.  After login with my client I went to the players base and the server crashed as soon as the chunks loaded.  

Here is the crash report with the new versions installed.

http://pastebin.com/WPqTERZi

Let me know if you need anything else or would like me to test something different.

**Comment by HenryLoenwind** [comment]
I'd like to send you a debugging version, because you have such a nice test setup. Would that be possible? You'd need to temporarily install immibis microblocks for it to run, as I cannot compile a version of ender io that runs without it (bug in Oracle's compiler).

**Comment by bakaie** [comment]
Sure, just let me know what i need and how you want it setup.

On Sun, Nov 15, 2015 at 11:50 AM, Henry Loenwind <notifications@github.com>
wrote:

> I'd like to send you a debugging version, because you have such a nice
> test setup. Would that be possible? You'd need to temporarily install
> immibis microblocks for it to run, as I cannot compile a version of ender
> io that runs without it (bug in Oracle's compiler).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-156842849>
> .
>



-- 
Thanks
Brian

**Comment by HenryLoenwind** [comment]
Great.

You only need to add Immibis Microblocks and Core from http://immibis.com/mcmoddl/ --- you can trow them out afterwards.

Then use this version: http://loenwind.info/eioa/EnderIO-1.7.10-2.3.0.419a_beta.jar

Let it crash and look at the logfile. If it crashed at the same position (in PickableFarmer.harvestBlock) there will be a big debug output directly above the crash. That's what I want to see.

If it crashes somewhere else, try again. If you cannot get it to crash in PickableFarmer.harvestBlock again, I have to make a version with more debug points.

**Comment by bakaie** [comment]
np, I have everything downloaded and will get it on the server and tested after work tomorrow.  I will let you know what happens/provide you with the data.

**Comment by HenryLoenwind** [comment]
thx very much

**Comment by bakaie** [comment]
Ok i have tested the mod and am getting a different crash.  I have attached
the crash report and the log for you to review.  Let me know when you are
ready for me to retest or want me to change anything.

Crash Report:
http://pastebin.com/VaJTvMLB

Server Log File:
http://pastebin.com/Yq5kiXqH

Thanks again for all your work on fixing the issue.

On Mon, Nov 16, 2015 at 2:42 AM, Henry Loenwind <notifications@github.com>
wrote:

> thx very much
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-156971156>
> .
>



-- 
Thanks
Brian

**Comment by HenryLoenwind** [comment]
Looks like you missed the Immibis Core

**Comment by bakaie** [comment]
grr, ok let me check, i thought i copied it.  Sorry if i missed it and
wasted your time.  I will run it again tonight.

On Tue, Nov 17, 2015 at 1:26 AM, Henry Loenwind <notifications@github.com>
wrote:

> Looks like you missed the Immibis Core
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-157307234>
> .
>



-- 
Thanks
Brian

**Comment by bakaie** [comment]
Ok i have copied and verified the immibis core file is in the mods folder
and i get about the same error as yesterday.  I will link the crash report
just to make sure i am not missing something.  I will also look into
immibis as i have not used it before and maybe i am missing something in
the setup/conflict with another mod i have installed.

http://pastebin.com/p9tAdWn7

On Tue, Nov 17, 2015 at 11:49 AM, Brian Norris <brian.norris.it@gmail.com>
wrote:

> grr, ok let me check, i thought i copied it.  Sorry if i missed it and
> wasted your time.  I will run it again tonight.
>
> On Tue, Nov 17, 2015 at 1:26 AM, Henry Loenwind <notifications@github.com>
> wrote:
>
>> Looks like you missed the Immibis Core
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-157307234>
>> .
>>
>
>
>
> --
> Thanks
> Brian
>



-- 
Thanks
Brian

**Comment by bakaie** [comment]
Please ignore the post above, i was missing the core, only had the
multiblock, I have it now and the server boots but as soon as the world
loads it does a reboot with a different error then the farming station.
Let me play around with it for a few and see if I can get something
different.  If not I will post the crash report and see if that has
anything helpful.

On Tue, Nov 17, 2015 at 5:52 PM, Brian Norris <brian.norris.it@gmail.com>
wrote:

> Ok i have copied and verified the immibis core file is in the mods folder
> and i get about the same error as yesterday.  I will link the crash report
> just to make sure i am not missing something.  I will also look into
> immibis as i have not used it before and maybe i am missing something in
> the setup/conflict with another mod i have installed.
>
> http://pastebin.com/p9tAdWn7
>
> On Tue, Nov 17, 2015 at 11:49 AM, Brian Norris <brian.norris.it@gmail.com>
> wrote:
>
>> grr, ok let me check, i thought i copied it.  Sorry if i missed it and
>> wasted your time.  I will run it again tonight.
>>
>> On Tue, Nov 17, 2015 at 1:26 AM, Henry Loenwind <notifications@github.com
>> > wrote:
>>
>>> Looks like you missed the Immibis Core
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-157307234>
>>> .
>>>
>>
>>
>>
>> --
>> Thanks
>> Brian
>>
>
>
>
> --
> Thanks
> Brian
>



-- 
Thanks
Brian

**Comment by bakaie** [comment]
Ok got it working, server will stay up until i connect and load the chunks
that were causing the crash.  Here are all the logs from the server:

Crash log:
http://pastebin.com/kN0qSZy4

fml-server-log:
http://pastebin.com/Q9sxvdh7

Server log:
http://pastebin.com/cSyg1BuM

Lets see if that helps a little.  let me know if you need any further
testing.

On Tue, Nov 17, 2015 at 6:19 PM, Brian Norris <brian.norris.it@gmail.com>
wrote:

> Please ignore the post above, i was missing the core, only had the
> multiblock, I have it now and the server boots but as soon as the world
> loads it does a reboot with a different error then the farming station.
> Let me play around with it for a few and see if I can get something
> different.  If not I will post the crash report and see if that has
> anything helpful.
>
> On Tue, Nov 17, 2015 at 5:52 PM, Brian Norris <brian.norris.it@gmail.com>
> wrote:
>
>> Ok i have copied and verified the immibis core file is in the mods folder
>> and i get about the same error as yesterday.  I will link the crash report
>> just to make sure i am not missing something.  I will also look into
>> immibis as i have not used it before and maybe i am missing something in
>> the setup/conflict with another mod i have installed.
>>
>> http://pastebin.com/p9tAdWn7
>>
>> On Tue, Nov 17, 2015 at 11:49 AM, Brian Norris <brian.norris.it@gmail.com
>> > wrote:
>>
>>> grr, ok let me check, i thought i copied it.  Sorry if i missed it and
>>> wasted your time.  I will run it again tonight.
>>>
>>> On Tue, Nov 17, 2015 at 1:26 AM, Henry Loenwind <
>>> notifications@github.com> wrote:
>>>
>>>> Looks like you missed the Immibis Core
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-157307234>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> Thanks
>>> Brian
>>>
>>
>>
>>
>> --
>> Thanks
>> Brian
>>
>
>
>
> --
> Thanks
> Brian
>



-- 
Thanks
Brian

**Comment by HenryLoenwind** [comment]
Ok, one thing I can say for sure: Some mod is changing Minecraft's player class heavily. There's a field missing that should be there, and my debugging code is crashing when trying to print its value.

Here's a version that should not crash if there's something missing from the class: http://loenwind.info/eioa/EnderIO-1.7.10-2.3.0.419b_beta.jar Maybe that will give us some data on what's actually happening...

**Comment by mindforger** [comment]
there are not that much mods in his list that change the player class to add additional slots and stuff

**Comment by bakaie** [comment]
sweet i will get this one loaded up tonight and send you all the data.

On Wed, Nov 18, 2015 at 3:07 AM, mindforger <notifications@github.com>
wrote:

> there are not that much mods in his list that change the player class to
> add additional slots and stuff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-157664711>
> .
>



-- 
Thanks
Brian

**Comment by bakaie** [comment]
Ok here is today's set of files.

fml server log:
http://pastebin.com/CSDJ4knH

crash report:
http://pastebin.com/0ew7FGD1

server log:
http://pastebin.com/36PY9tLy

Let me know how this one works out/or if you need me to run anything else.


On Wed, Nov 18, 2015 at 10:10 AM, Brian Norris <brian.norris.it@gmail.com>
wrote:

> sweet i will get this one loaded up tonight and send you all the data.
>
> On Wed, Nov 18, 2015 at 3:07 AM, mindforger <notifications@github.com>
> wrote:
>
>> there are not that much mods in his list that change the player class to
>> add additional slots and stuff
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-157664711>
>> .
>>
>
>
>
> --
> Thanks
> Brian
>



-- 
Thanks
Brian

**Comment by HenryLoenwind** [comment]
the fml server log you posted is from the restart of the server (starting at 15:56:19) after the crash (at 15:56:14). I'd need the one with the output just before the crash...

thx again for doing all this testing!

**Comment by bakaie** [comment]
my bad they had the same time stamp so i grabbed the wrong one. Here is the
correct file:

http://pastebin.com/yX0zcLqV


On Wed, Nov 18, 2015 at 7:07 PM, Henry Loenwind <notifications@github.com>
wrote:

> the fml server log you posted is from the restart of the server (starting
> at 15:56:19) after the crash (at 15:56:14). I'd need the one with the
> output just before the crash...
>
> thx again for doing all this testing!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-157924221>
> .
>



-- 
Thanks
Brian

**Comment by HenryLoenwind** [comment]
http://loenwind.info/eioa/EnderIO-1.7.10-2.3.0.420a_beta.jar

This should fix your crash. Could you please try it out before I propose the fix for inclusion with the official version?

Thanks.

**Comment by bakaie** [comment]
I will try it out tonight.


On Thu, Nov 19, 2015 at 10:08 AM, Henry Loenwind <notifications@github.com>
wrote:

> http://loenwind.info/eioa/EnderIO-1.7.10-2.3.0.420a_beta.jar
>
> This should fix your crash. Could you please try it out before I propose
> the fix for inclusion with the official version?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-158120955>
> .
>



-- 
Thanks
Brian

**Comment by bakaie** [comment]
Ok all looks good,  With that version I was able to login with no issue.  I
went to the farm station with a watering can to force a bunch of plants to
grow and get harvested.  All looks good.  Thanks again for all the work in
getting it fixed.  I will be waiting with anticipation for the next
release.  Also just throwing it out but if you guys need a test bed again
just let me know.  My current setup uses containers so i can clone my
active world/server and run them side by side with little effort.



On Thu, Nov 19, 2015 at 11:09 AM, Brian Norris <brian.norris.it@gmail.com>
wrote:

> I will try it out tonight.
>
>
> On Thu, Nov 19, 2015 at 10:08 AM, Henry Loenwind <notifications@github.com
> > wrote:
>
>> http://loenwind.info/eioa/EnderIO-1.7.10-2.3.0.420a_beta.jar
>>
>> This should fix your crash. Could you please try it out before I propose
>> the fix for inclusion with the official version?
>>
>> Thanks.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SleepyTrousers/EnderIO/issues/2983#issuecomment-158120955>
>> .
>>
>
>
>
> --
> Thanks
> Brian
>



-- 
Thanks
Brian
