### ISSUE TITLE
[Idea] GregTech power conduits

### ISSUE THREAD

**Issue by Invincible92** [SleepyTrousers/EnderIO#2987]
It would be a nice idea create a GT power conduit (one of each tier of voltage that GregTech has) in order to connect machines in a very tight design with multiple pipes though one face of the block, for example. Currently, using only GT and Ender IO mods, GregTech power needs a face of the block, item import/export needs another one and, only if you're using liquids, a fluid import/export needs an extra one.

Being possible to import/export items and power the machines via one face of the block (in tight places) would be a nice advantage.

**Comment by spacebuilder2020** [comment]
I am currently working on an addon mod that will add ic2 and gt conduits
#2944 
https://github.com/spacebuilder2020/Random_Enderio_Addons

**Comment by HenryLoenwind** [comment]
@spacebuilder2020 You might want to try to avoid people getting confused about "Ender IO Addons" and "Random Ender IO Addons"...

**Comment by spacebuilder2020** [comment]
ok... I will think of a different name.

**Comment by Badcholo** [comment]
Is there a download to a jar file Random Enderio Addons?
https://github.com/spacebuilder2020/Random_Enderio_Addons/issues/1

**Comment by spacebuilder2020** [comment]
Not yet, cause it requires changes to ender io core to not crash.

**Comment by Badcholo** [comment]
ok, i'll be around
