### ISSUE TITLE
Minor issue with capacitor bank charge level indicator

### ISSUE THREAD

**Issue by Teksid** [SleepyTrousers/EnderIO#2988]
If you [place any capacitor blocks](http://i.imgur.com/MyVQJ0i.png), cover one of the indicator faces with [another capacitor block](http://i.imgur.com/yIm2gqV.png), then remove that block, [the indicator will not reappear](http://i.imgur.com/xa39Jyu.png). If that block is removed and replaced, it will reappear only if there is a block with an indicator face above or below it. If this is done for all indicator faces, [this kills the charge indicator](http://i.imgur.com/QU293T0.png).

**Comment by MatthiasMann** [comment]
You can toggle what is displayed on a capbank site by shift right clicking with an empty hand

**Comment by Teksid** [comment]
I had no idea that could be done. I suppose this isn't really an issue then, just a derp on my part.
