### ISSUE TITLE
[Issue] Thermal Expansion Energy Cells Self Feed And Consume All Conduit Throughput

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#2990]
When you have a bank of Cells connected in series it will cause a self feed loop that consumes all the conduit throughput instead of acting like a on demand RF Storage

**Comment by MatthiasMann** [comment]
well - use EnderIO capacitor banks instead

**Comment by mikeloeven** [comment]
sure as soon as you add a equivalent to the resonant cell 80M RF

**Comment by HenryLoenwind** [comment]
RF energy is transfered by pushing. So the energy cell is pushing it into the conduit, which in turn offers it to all connected blocks. Nothing we can do here.

Also, you can build a loop with anything. Unless all blocks belong to the same mod, there is no chance for any mod to recognize it as a loop.

**Comment by HenryLoenwind** [comment]
![](http://i.imgur.com/7VkZ95D.png)

**Comment by mikeloeven** [comment]
yes a cap bank can get those values but only when you stack them in a multiblock the cells are single blocks with 80M RF 

I generally like my systems as compact as possible and single blocks generally win over multi-block

**Comment by HenryLoenwind** [comment]
![](http://i.imgur.com/cz4ngjm.png)

**Comment by mindforger** [comment]
can i insert an other cross mod issue her as i think it fits perfectly?! when i drop 2 EIO Caps and plug an immersive wire between, both caps start pumping into each other in an infinite loop ... cap 1 -> cap2 until cap1 empty then cap1 <- cap2 until cap2 empty .. wasting energy .. unless i specify the power flow direction, which is nt configured by default ...

**Comment by MatthiasMann** [comment]
That is the same issue - EnderIO conduits & capbanks work closely together to provide an easy and optimized power system.

As soon as you start to mix power transfer/storage systems - you have to carefully configure every part or things go wrong.

**Comment by HenryLoenwind** [comment]
@mindforger A cap bank will not accept energy if it is full. So the wire must be taking the energy even if it has nowhere to put it, and voiding it.

RF is quite clear: Any block that provides energy pushes it into any connected block that can accept energy. That block must then say how much of that energy it actually took. The providing block has no idea, what the receiving block does with it. It may use it to light up, or it may offer it to another block in turn (that's what wires, conduits, ducts... do).

Cap banks do exactly that. They look how much energy they have and how much they are allowed to output per tick. Then they go over all connected blocks, offering each of them that amount and reduce it by the amount that block took. That's it. Done. No magic, no special cases.

On the receiving side, Ender IO machines and cap banks are as direct, too. They look at the offered amount and if they can fit (part of) it into their buffer, they do so and return the amount they took.

Conduits have some special cases for cap banks, so those don't store energy that could be put into a machine and won't be drained for another cap bank if both are on in+out.

**Comment by mikeloeven** [comment]
ok looks like the server admins tweaked the configs since the server i play on has them set to 80m

**Comment by mindforger** [comment]
>Conduits have some special cases for cap banks, so those don't get offered energy that could be put into a machine and won't be drained for another cap bank if both are on in+out.

is there some API to that ?

**Comment by Znubbis** [comment]
Is this also the reason why measuring the current flow trough capacitor is hard? Id like a way to see how much RF that are passing trough a capacitor not just how much it goes up or down.

**Comment by Badcholo** [comment]
Get Compact Machines mod. Done.
