### ISSUE TITLE
Item Panel - NEI doesn't show

### ISSUE THREAD

**Issue by Tyrindor** [SleepyTrousers/EnderIO#2991]
Whenever I use the Item Panel, NEI does not show. I've tried hitting "o" and all the other things. As soon as I interact with the block, NEI disappears, and comes back when I exit it.

This makes using it very frustrating because you can't shift click NEI recipes, and constantly have to back out of it to go to a normal crafting table.

There's a NEI autosync option so I can only assume its a bug. I am using FTB Infinity Evolved 2.1.2 with Expert mode enabled.

**Comment by Tyrindor** [comment]
Should of tried restarting the game before posting.

That fixed it.

**Comment by Tyrindor** [comment]
Problem returned. If I adjust UI scale to anything other than "auto" I see NEI. I'm running 4k resolution so there may be a problem with the scaling.

**Comment by tterrag1098** [comment]
When NEI doesn't have enough room to show (as determined by the GUIs size variables) it hides itself. You need to change your GUI scale or find some other solution, there's nothing we can do from this end.
