### ISSUE TITLE
Hexadecadic Capacitor [Feature request]

### ISSUE THREAD

**Issue by EntropicPariah** [SleepyTrousers/EnderIO#2992]
Similar ideas have probably been suggested before but I'd like something on this order for machine upgrades. I try to smelt cobble from an AE2 storage module even using 7 smelters going at once with octadic capactors and I'm still backing up 2 diamond chests in queue with cobblestone. I try to cut down on tile entities whenever possible because I don't exactly have a spectacular computer but even powerful ones can get dogged by too many things running at once.

**Comment by Badcholo** [comment]
Faster Smelters? They seem pretty fast for me. Maybe i just woke up, but what are you asking for?
Just wondering..

**Comment by mindforger** [comment]
well i must say he has one point there, and i know how dev do not like to be compared with other mods, but in this case i must admit i prefere fully overclocked e-furnace or fully augmented thermal redstone furnace over the alloy smelter for speed in temrs of simple furnace recipes! but they draw a huge lot more power per item when upgraded ... the octatic makes the alloy smelter cheaper per item so it is balanced imho

**Comment by Badcholo** [comment]
I like the speed of it. It is very balanced even with the upgrade.

**Comment by EntropicPariah** [comment]
I'm not complaining about anything being unbalanced. As far as power usage concerns, I have Big Reactors installed so I couldn't run out of RF if I tried. I want to get more speed out of the alloy smelter via an upgrade rather than increasing the number of smelters. I guess if I have to I'll just add a second bank of smelters but the more tile entities I have at one spot the laggier it gets.

**Comment by HenryLoenwind** [comment]
Just FYI: There are plans to change the capacitor system from having 3 caps that are hardcoded into every machine to a dynamic system where the data is on the cap. Once that is done, we can add as many caps with different stats as we want. Until then, any change would mean to change every single machine.

I'm closing this because we already have a couple of Issues asking for new/better/more caps. Not because we reject the request.

**Comment by Badcholo** [comment]
What could you possibly need so much furnace speed for? I only use 1 with the upgrade

**Comment by wlhlm** [comment]
@EntropicPariah I get your idea, but your use case is pretty weak. When you're looking for a quick smooth stone generator, have a look at the [Igneous Extruder from Thermal Expansion](http://teamcofh.com/docs/thermal-expansion/machines/igneous-extruder/), a machine specifically made for generating cobblestone, smooth stone, and obsidian from water and lava. Fully decked out, it can produce up to 32 stone at once and it doesn't even require power.

Also, a fully upgraded Redstone Furnace is faster than an octadic Alloy Smelter (but requires more power).

**Comment by Badcholo** [comment]
Dude, This thing can produce so much cobble, Stone and Sand ect.
I didn't install this cause i thought it was too op, but it seems to be useful for your needs.
http://minecraft.curseforge.com/projects/ender-io-addons
