### ISSUE TITLE
Item Panel missing/late items

### ISSUE THREAD

**Issue by Tyrindor** [SleepyTrousers/EnderIO#2994]
Using FTB Infinity Evolved, latest version.

I send items via the item panel back to the chests, but they don't show back up for a very long time. Sometimes never. I have to remove the awareness upgrade from that chest and put it back in to fix it. It's also regularly pulling the wrong items (aka redstone chipsets instead of wood), etc.

**Comment by HenryLoenwind** [comment]
see #2755
