### ISSUE TITLE
FTB Infinity Evolved: Ender IO Harvester crash

### ISSUE THREAD

**Issue by Mr-Rixa** [SleepyTrousers/EnderIO#2995]
TL;DR: Harvester + Essence berry bush = Crash

http://pastebin.com/HTVsh3Bs

**Comment by HenryLoenwind** [comment]
same crash as in #2957

**Comment by HenryLoenwind** [comment]
The latest version contains a change that **might** help. I'd really like to get some feedback on this. Thx.

**Comment by Mr-Rixa** [comment]
Confirmed. Problem resolved with updating to latest Ender IO and Ender Core on SMP

**Comment by HenryLoenwind** [comment]
Nice. Could you have a look in your logfile if there are any warnings starting with the text "Ender IO Farming station fake player is being transfered to world"? If yes, I'd like to see them and the following stacktrace very much. Thx

**Comment by Mr-Rixa** [comment]
I'll check my server logfiles, I'll report back if I find something

**Comment by Mr-Rixa** [comment]
```
/minecraft/FTB_infini$ find -name \* -print0 | xargs -0 zgrep -Hi "EnderIO" | grep -i farm
--
```
