### ISSUE TITLE
[Enhancement] Support For Configuring Filters by Dragging Items Directly From NEI

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#2998]
Please add support for enderio Filters to recieve configuration information directly from NEI Currently to configure filters on item conduits the player must have the item they wish to set in their inventory and  drag it over the filter. There are several mods that allow item filters to be populated by dragging items directly from NEI which makes it much easier to initially set up item filters.

**Comment by wlhlm** [comment]
That definitely sounds convenient. What other mods support that feature?

**Comment by mikeloeven** [comment]
Logi pipes does this Generally for complex crafting operations using machines i just the crafting pipe hooked to an output buffer and a satellite to an input buffer with enderio conduits providing the back-end item transport between the machine array and the output buffer.
