### ISSUE TITLE
More robust createNetworkForType() that will enable custom conduits

### ISSUE THREAD

**Issue by spacebuilder2020** [SleepyTrousers/EnderIO#2999]
I am working on a mod that will add ic2 and gt power conduits, however, it crashes since the createNetworkForType() method from ConduitUtil.java only works with default conduits. It was suggested at #2944 that this be implemented as a method in IConduit, in #2944, I took a shot at implementing that, as well as moving the default code from ConduitUtil to AbstractConduit for a default method to avoid breaking existing code.

https://github.com/spacebuilder2020/Spacebuilder2020-s-addon-mod-for-ender-io

**Comment by spacebuilder2020** [comment]
I have tested it with my mod and it is working correctly.

**Comment by HenryLoenwind** [comment]
Hi,

Pls have a look at the latest commits, there is a new way to register for the yeta wrench (display modes!)
