### ISSUE TITLE
EnderIO-1.7.10-2.3.0.419 crash

### ISSUE THREAD

**Issue by usafphoenix** [SleepyTrousers/EnderIO#3000]
Getting java.lang.ClassNotFoundException: crazypants.enderio.conduit.BlockConduitBundle,
and java.lang.NoClassDefFoundError: mods/immibis/core/api/multipart/IMultipartRenderingBlockMarker

crashlog: http://paste.atlauncher.com/view/cdd71440

**Comment by usafphoenix** [comment]
(is this the same thing that was happening a few months back with cofh's outdated apis? i seem to recall something like this happening previously.

**Comment by HenryLoenwind** [comment]
Hard to say, I need to download that log and cut it into sessions.

First guess would be load order.

**Comment by tterrag1098** [comment]
Try updating immibis core
