### ISSUE TITLE
Build 419 cannot add private channels on multiplayer Dim Trans

### ISSUE THREAD

**Issue by tgstyle** [SleepyTrousers/EnderIO#3001]
Trying to add a private channel to a Dim Trans, and it will only let me add/see public. The JSON file appears in the server folder with the right private channel name and player, but it does not show in the GUI.

**Comment by HenryLoenwind** [comment]
That is the same as #2367, isn't it?

**Comment by tgstyle** [comment]
Looks like it could be.
