### ISSUE TITLE
Add support more bundled cable APIs

### ISSUE THREAD

**Issue by Rukachan** [SleepyTrousers/EnderIO#3004]
Posting this here as requested on the IRC.

For the currently implemented bundled cable APIs MFR or Computercraft should be installed, making the interaction with other mods while these two are not installed not possible. (eg interacting via using the OC lua bundled redstone functions)
The suggestions are:
1: Implement other bundled cable APIs (eg: Redlogic - https://github.com/asiekierka/RedLogic-asie/tree/master/src/main/java/mods/immibis/redlogic/api/wiring, Bluepower - see bellow)
2: Do not require MFR or Computercraft to be installed to use their bundled cable APIs.

**Comment by fnuecke** [comment]
details on integrating with BluePower (Bundled) Redstone:
- [Relevant API](https://github.com/Qmunity/BluePower/tree/master/src/main/java/com/bluepowermod/api/wire/redstone)
- Maven / Gradle dependency:
```
repositories {
    maven {
        name = "BluePower"
        url = "http://maven.bluepowermod.com/"
    }
}
dependencies {
    provided "com.bluepowermod:BluePower:0.2.962:deobf"
}
```
- Basically
  - Register a [IRedstoneProvider](https://github.com/Qmunity/BluePower/blob/master/src/main/java/com/bluepowermod/api/wire/redstone/IRedstoneProvider.java) via `BPApi.getInstance.getRedstoneApi.registerRedstoneProvider(...)` whenever you initialize your mod integration stuffs.
  - Implement [IBundledDevice](https://github.com/Qmunity/BluePower/blob/master/src/main/java/com/bluepowermod/api/wire/redstone/IBundledDevice.java) and return that from the provider.
  - For the `getBundledConnectionCache`, use `BPApi.getInstance.getRedstoneApi.createBundledConnectionCache` and store that in a field.

**Comment by fnuecke** [comment]
Details on Project Red:
- [Relevant API](https://github.com/MrTJP/ProjectRed/tree/master/src/mrtjp/projectred/api).
- Maven / Gradle stuffs
```
repositories {
    maven {
        name 'ProjectRed'
        url 'http://files.projectredwiki.com/maven/'
    }
}
dependencies {
    compile ("mrtjp:ProjectRed:1.7.10-4.6.2.82:dev") {
        exclude module: 'CoFHCore'
    }
}
```
- Read via `ProjectRedAPI.transmissionAPI.getBundledInput`.
- Output by implementing [IBundledTile](https://github.com/MrTJP/ProjectRed/blob/master/src/mrtjp/projectred/api/IBundledTile.java) on the TileEntity.
