### ISSUE TITLE
SAG Mill idea(s)

### ISSUE THREAD

**Issue by neogenix** [SleepyTrousers/EnderIO#3007]
So I've come up with two ideas, and wondering what you guys thought:

- It would be great if there could be one level above the Dark Steel Balls (Bedrock Balls) that are super end-game, that provide higher yields, and perhaps last a little longer.

- It would be great if there were a few more pre-defined recipes that did : 
  - Elemental Blocks (into Elemental Shards)
  - Cinnabar Ore (into Cinnabar)
* I've added this one locally as a user defined recipe, but perhaps it's something that others would like.

**Comment by neogenix** [comment]
I can do a PR for the recipes if you guys are keen?

**Comment by tterrag1098** [comment]
If there is a precedent for the recipes in other mods, then by all means make a PR.
