### ISSUE TITLE
ME Conduit and small interfaces?

### ISSUE THREAD

**Issue by neogenix** [SleepyTrousers/EnderIO#3008]
Hey, 

I've read a few random articles about 'ME conduits not fitting in the same block as small interfaces' but I don't see anything in the bugs/issues, wiki, etc... that says it shouldn't work (other than it doesn't work). Is this expected behavior?

I've tried: 
- Storage Bus 
- Input Bus
- Export Bus 

Thanks!

**Comment by tterrag1098** [comment]
Yes it's expected, we don't support FMP or any form of multipart, so AE2 cannot put its busses inside our block. It's a feature we'd love to have, but is unfortunately very complicated to do. Might happen one day, but unlikely.

**Comment by neogenix** [comment]
Thanks for the update!
