### ISSUE TITLE
[enhancement] Opencomputer Conduits For Computercraft?

### ISSUE THREAD

**Issue by HyperionNexus** [SleepyTrousers/EnderIO#3011]
The title says it all.

note: I haven't used Opencomputers conduits as I really don't understand the mod. However, a friend of mine suggested that it'd be good for more compact wiring.

I know this is short and sweet but I'm not the best at explaining...

Thanks for reading this I guess.

**Comment by tterrag1098** [comment]
Duplicate of #46 

Yes, 46.

**Comment by HyperionNexus** [comment]
Woops, didn't notice it.
