### ISSUE TITLE
NPE selecting Yeta Wrench on hotbar

### ISSUE THREAD

**Issue by shortybsd** [SleepyTrousers/EnderIO#3012]
EnderIO Version: EnderIO-1.7.10-2.3.0.420_beta
EnderCore Version: EnderCore-1.7.10-0.2.0.31_beta

When scrolling with mouse across hotbar and selecting Yeta Wrench, client locks up then crashes with the following NPE:

http://pastebin.com/ZJtqwZm8

**Comment by HenryLoenwind** [comment]
see #3006

**Comment by tterrag1098** [comment]
Known #3006
