### ISSUE TITLE
[Bug?] Electromagnet hotkey to deactivate doesn't work when placed on the baubles inv

### ISSUE THREAD

**Issue by cgmtaus** [SleepyTrousers/EnderIO#3015]
The electromagnet isn't responsive of the hotkey to deactivate itself when is on the baubles inventory, also can't be placed it when isn't active. Is this a bug, or intended behaviour?

**Comment by HenryLoenwind** [comment]
The second one is the intended behavior. The first one only if the inventory is full.

There is a config setting to allow a deactivated magnet into the Baubles slot.

**Comment by Timeslice42** [comment]
The magnet won't turn on with the hotkey in a baubles slot if I have the config set to allow a deactivated magnet in the slot.
