### ISSUE TITLE
[Enhancement] High capacity Buffer Variations

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#3017]
I ran into an issue where a system was overloading the item buffer due to too many types being sent to the location Cannot Use a Diamond Chest as push pull functionality is needed plus due to the location the chest could not be opened to monitor. 

There exists a need for capacity upgrades to the item buffers to handle high throughput such as the ore outputs of a quarry into a sag mill array which can easily overwhelm the 9 item slots.

**Comment by MatthiasMann** [comment]
You can always use item conduits with speed upgrades - they can move a stack at a time.

**Comment by mikeloeven** [comment]
This only works when you have items coming in that are of the same type if your processing a quarry a lot of times you will have small quantities but many ore types and these build up
