### ISSUE TITLE
TODO: Rename changed GUI textures before release

### ISSUE THREAD

**Issue by HenryLoenwind** [SleepyTrousers/EnderIO#3019]
otherwise we'll get many reports like this:

![](https://cloud.githubusercontent.com/assets/8468011/11293615/7eec1bc0-8f29-11e5-8450-b67f3c155a59.png)

**Comment by tterrag1098** [comment]
Yeah we should probably just rename the GUI folder at this point, lol

**Comment by HenryLoenwind** [comment]
I was thinking about "gui/*" => "gui/23/*"---makes it easier to repeat later.

**Comment by wlhlm** [comment]
> otherwise we'll get many reports like this

Yeah ;-) F32Organization/Faithful32-1.7.10#506
