### ISSUE TITLE
[Feature] add rubberwood to axe

### ISSUE THREAD

**Issue by Protheus** [SleepyTrousers/EnderIO#3021]
Add the rubberwood from MFR to the dark axe so it can chop down the whole rubber tree.

**Comment by Protheus** [comment]
that was fast :-) :+1:

**Comment by HenryLoenwind** [comment]
just a sec, was that the rubberwood that grows those rubberthingies you tap? If it is the other one it should work already.

**Comment by XFactHD** [comment]
It's "the other one", the one you use the tap on IC2 rubber wood.

**Comment by HenryLoenwind** [comment]
ok, then I have to have a look what's wrong. Thx.

**Comment by Protheus** [comment]
Minefactory reloaded has a rubber tree. That one. No idea about the IC2 one
