### ISSUE TITLE
Pulsating Iron Nuggets disabled? 

### ISSUE THREAD

**Issue by ZakMC1** [SleepyTrousers/EnderIO#3022]
I started a modpack based off the dns techpack and updated the Ender IO mod to the latest one and can't figure out why the pulsating iron nuggets are disabled can someone help me find the mod that is doing this or find the file in Ender IO that is doing this?

**Comment by HenryLoenwind** [comment]
Easy: Ender IO does not have nuggets for its alloys.

I think AOBD is the mod that adds nuggets for them: http://minecraft.curseforge.com/projects/another-one-bites-the-dust

**Comment by cloakable** [comment]
So item conduit no longer uses pulsating iron nuggets? Because I'm running latest beta and it does for me ;)

**Comment by HenryLoenwind** [comment]
Ok, second look. We do not have nuggets, they were removed in 9/2013, but we have a material that is named nuggetPulsatingIron right between binderComposite and pulsatingCrystal, and acts like a nugget and was added in 2/2014.  Okey, make sense. Not.

So it is part of the materials and there is nothing in Ender IO stopping (part of) the material item from being registered.

So I'd look at MineTweaker/ModTweaker. Those are the mods that remove stuff.

**Comment by ZakMC1** [comment]
I looked at both of those mods (minetweaker) which i do not have and I do
have aobd but. It just weird I only added 5 mods to the Dns tech pack
Decocraft crayfish furniture armor add on for tinkers better fps and blood
magic. I think I'll just remove armor it said something about nuggets in
its cfg file plus the mode is quite basic and crappy anyways. And then I'll
just the configuration for aobd

**Comment by mindforger** [comment]
if i remember right, there was an issue with the nuggets beeing a whole other type of material (and recipe), thus they were renamed and in meantime usable both but now not anymore

**Comment by ZakMC1** [comment]
Alright the mod Armory an add on for TC was the issue. It disables the
nuggets for a lot of ingots.
