### ISSUE TITLE
alloy smelter only smelting one item at a time

### ISSUE THREAD

**Issue by theboo89** [SleepyTrousers/EnderIO#3026]
so im having an issue with the alloy smelter... say im wanting to make quite clear glass, if i put 3 stacks of sand in, it smelts 3 at a time like it always has. But if you just put 1 stack in a single slot, it only smelts one at a time, i dont know if this was intentional or not, but it creates a problem because when you put 3 stacks of sand in to the smelter, it only pulls sand from the left hand slot, and when it runs out it starts pulling from the middle slot, but since only 2 slots have sand, it is now only smelting 2 at a time, and when thats gone it pulls from the right slot and only smelts one at a time... seems kinda weird

im using the 417 beta on my server, but i just loaded 420 in single player with no other mods and i am having the same issue.

i can understand if you want it to only smelt 3 at a time when all 3 slots are filled, but if were gonna have that, it should pull equally from all 3 slots ...

thanks!
Tristan 

edit: Forgot to mention, i looked up and down throughout the configs and couldnt find anything for this, so hopefully im not just blind haha

edit2: i think it all evens out in the end because it scaled the time based on how many blocks its smelting, but it still seems weird that it works this way

**Comment by HenryLoenwind** [comment]
The Alloy Smelter only smelts 3 at a time for furnace recipes (vanilla glass), not alloy smelter recipes (quite clear glass). It also pulls input items from the lowest slot is can find them. Always been that way.

**Comment by theboo89** [comment]
i c... well it does smelt 3 quite clear glass at a time if all 3 slots have items.. so i dont know if thats intentional or not... anyways, thx for the response

**Comment by HenryLoenwind** [comment]
Oh, someone added 2 additional recipes to the config some time ago. One that takes 2*1 sands and one that takes 3*1. There are none for 3*1, 1*1+2*1 and 2*1+1*1.

Intentional? Not really, those additional recipes are there because the normal recipe actually reads "1 slot with 1 or more sand, 2 empty slots"---and would fail if there were 3 slots of sand. It was a hotfix back then and never got improved.
