### ISSUE TITLE
Farming station vs. oreberry bush

### ISSUE THREAD

**Issue by ArcasCZ** [SleepyTrousers/EnderIO#3029]
Hello there!

I'm little bit confused, 'cause in EnderIO 2.2 we can use Farming Station to farm oreberry bushes. But now, there is no way how to user farming station this way. Is it bug in your code, or between my chair and keyboard?

**Comment by HenryLoenwind** [comment]
It still should work. Can you describe and/or screenshot what you are doing?

**Comment by ArcasCZ** [comment]
It says no seed but where I have to put seeds, when oreberry has no seeds...?

**Comment by TsumiHokiro** [comment]
The machine has no need for seeds to start working. Once it is in range of a oreberry bush it will start collecting it even without seeds, it will, however, it still accuses there are no seeds. This will work with flowers from vanilla as well in case you have a farm of those.
I've tested the machine with version  2.3.0.421 with several mods.

**Comment by ArcasCZ** [comment]
And what kind of tool you have to use? :-)

**Comment by TsumiHokiro** [comment]
You can use any kind of hoe (as far as I've seen, it registers pretty much any hoe that has durability).
