### ISSUE TITLE
[issue][mod interaction] Insulated Redstone Conduit Cannot Connect To TE Servos

### ISSUE THREAD

**Issue by mikeloeven** [SleepyTrousers/EnderIO#3033]
When a insulated Redstone conduit is placed next to a TE duct the duct will appear to connect to the conduit however the connector from enderio does not render thus you cannot set the Redstone channel you want the servo to react to

These servos can be triggered using a uninsulated Redstone conduit however there is once again no way to make a uninsulated endpoint trigger by a specific color signal

**Comment by MatthiasMann** [comment]
Use the Yeta wrench to toggle the connection mode to In/Out. There is no way to find out which blocks can accept redstone and which not - so it only connects by default to a list of known blocks - all others need to be manually configured.

**Comment by mikeloeven** [comment]
Ill try that thanks though one would think TE servos would be on the list as :/
