### ISSUE TITLE
Mekanism error

### ISSUE THREAD

**Issue by Rognaro** [SleepyTrousers/EnderIO#3036]
I use the mostly recent version of mekanism and the ender io ask to install mekanism!!
Screenshot: http://prntscr.com/96igoi
Mekanism version: Mekanism-1.7.10-8.1.7.254
Log: http://pastebin.com/pebCgVZq

**Comment by MatthiasMann** [comment]
This should be fixed first:
Unable to read the jar file Mekanism-1.7.10-8.1.7.254.jar - ignoring
java.util.zip.ZipException: error in opening zip file

**Comment by Rognaro** [comment]
thanks
