### ISSUE TITLE
YetaWRench Overlay Error

### ISSUE THREAD

**Issue by mrdeadlocked** [SleepyTrousers/EnderIO#3037]
http://pastebin.com/RpGmAsGw

I went to use my yeta wrench after awhile of having not used it. I got the crash above immediate upon putting the wrench into my hotbar.

**Comment by wlhlm** [comment]
#3006

**Comment by mrdeadlocked** [comment]
Crap. I search for 'overlay' and not yeta wrench. X.X

**Comment by cloakable** [comment]
Should be, just waiting for the build server to actually -build- 421. It's been sat on it's butt for a week now.

**Comment by mrdeadlocked** [comment]
I will be waiting as well. DO you have a link to the build server?

**Comment by wlhlm** [comment]
http://ci.tterrag.com/job/EnderIO/
