### ISSUE TITLE
NEI not working and crashing when looking up a smelting recipe with EnderIO mod added

### ISSUE THREAD

**Issue by MCEventHorizon** [SleepyTrousers/EnderIO#3040]
Only by removing EnderIO from my modpack will NEI work normal and won't crash on smelting recipes, not 100% if it's EnderIO.

Crashlog: http://pastebin.com/YKiXrkZP

**Comment by Keyarose** [comment]
Try updating NEI and it's dependencies there are newer versions available that, for me at least, work.  I'm using ChickenCore 1.0.7.47 and NEI 1.0.5.118
