### ISSUE TITLE
Unable to craft Electrical Steel

### ISSUE THREAD

**Issue by badddness** [SleepyTrousers/EnderIO#3043]
I am using the pack FTB Infinity Evolved v2.1.3 and I am unable to craft Electrical Steel in an alloy smelter.

Whether I use the all smelting function or alloys only, it will not allow me to craft Electrical Steel.

I can add either Iron or silicon into the gui, but never both. It will not allow me to add pulverized coal (Thermal Expansion) or Coal Dust (IC2).

**Comment by tterrag1098** [comment]
Are you sure that is the recipe?

**Comment by badddness** [comment]
Yes. It is displayed in NEI as well as in the recipes page in the Alloy Smelter GUI.

**Comment by badddness** [comment]
Turns out I cant craft a reservoir either. Perhaps the modpack has an issue or Ender IO has a few bugs?

**Comment by tterrag1098** [comment]
It's unlikely our recipes simply don't work, as that would be quite a large issue (many reports). I'd check with your server owner (if applicable) or the pack creator.
