### ISSUE TITLE
Inventory Terminal saving recipe output (even if the recipe doesn't exist)

### ISSUE THREAD

**Issue by Teibidh** [SleepyTrousers/EnderIO#3049]
So, this is probably a pretty unique situation ... but since it happened to me, it could happen to someone else:

I used MineTweaker to create recipes to make Thaumcraft mana beans of compound aspects (one Aer bean and one Ignis bean give two Lux beans, for example.) In one of these recipes I spelled the output aspect incorrectly, so when I tried to put the appropriate beans in to the crafting grid of the Inventory Terminal the Thaumcraft bean renderer caused a crash. No big deal, certainly not something Ender IO did wrong.

I figured, no problem, let me go in and fix the recipe and reload the scripts, then it will be fine. Nope. Still crashed when I opened the Inventory Panel.

Next step was to remove the recipe entirely, if there's nothing there, it can't put together a recipe, and I know the two component beans are working properly. Still crashes.

I broke the terminal and put it back, hoping to clear the contents... no joy. Wrench, of course, picks it up in tact as well.

What we need is for either the Inventory Terminal to recalculate what the output of a given recipe will be every so often, or every time it's opened (before trying to render the UI) or (and I think I would like this for most of the Ender IO machines, personally) have the Terminal drop all of its contents and reset its configuration if it's broken with a tool instead of using a wrench.

(I'm going to just trash the terminal and make another as I'm late game enough that resources aren't an issue and I don't want to wait for this to get resolved, but this is something that should probably be thought about in the future since I'm sure there will be other occurrences of people doing stupid things with MineTweaker :))

**Comment by wlhlm** [comment]
Can you reproduce the same behaviour using other crafting grids, like an AE Crafting Terminal, Draconic Chest, etc.?

**Comment by Teibidh** [comment]
EnderIO is the only "tech" mod I have that offers this functionality. I do have TC4 (Arcane Worktable), Ars Magica 2 (Magician's Workbench), and neither of these seem to suffer the same issue. If I attempt to craft an invalid bean recipe in one of those the game does crash. But if I fix the recipe before re-opening the crafting interface they provide it then renders the "correct" bean just fine.
