### ISSUE TITLE
Soulbound vs. Quantum Suit

### ISSUE THREAD

**Issue by ArcasCZ** [SleepyTrousers/EnderIO#3054]
Hello there!

Players on my friend's server have a little problem. They can't use SoulBound enchant for any part of QuantumSuit from IC2. We use latest version of EnderIO and EnderCore.

So, where is problem?

**Comment by HenryLoenwind** [comment]
define "can not use"

**Comment by ArcasCZ** [comment]
When i put quantum helmet and book with this enchant into anvil, arrow is crossed by red cross and no item show at last box.

**Comment by tterrag1098** [comment]
You can't enchant quantum. That is a decision by the IC2 devs and not something we can fix.
