### ISSUE TITLE
Strange behavior from conduits (mostly EnderIO AE conduits)

### ISSUE THREAD

**Issue by PsionicArchon** [SleepyTrousers/EnderIO#3056]
Using version .421 of EnderIO on forge .1448.

I'm noticing some unusual behavior from my conduits that's been fraying my nerves. Every so often I have to dig through my cabling to diagnose why a connection has failed (usually resulting in storage getting cut off from the network or autocrafting to fail).

Cables will render as connected yet will not transmit over the AE network. At times they need to be placed in highly specific positions. 

Examples: This works: http://i.imgur.com/qknOCtk.png

This does not: http://i.imgur.com/jDUWUjW.png

The only difference being that I added a single EnderIO conduit in setup 2 that wasn't present in setup 1. I have numerous similar setups all functioning yet this one refuses to. I'm running into instance after instance of cables not functioning in one location yet functioning perfectly elsewhere. I was reluctant to post this as the issue its self confounds me. 

Something is very wrong with the conduit network. As it stands, I will have to switch back exclusively to standard AE cables if the issue persists. It's becoming far too much of a headache.

Edit: Example one is randomly disconnecting its self. The EnderIO conduit will render as if it's connected yet the AE cable will not, cutting off that array of storage buses.

**Comment by HenryLoenwind** [comment]
As far as AE conduits are involved: This is a shortcoming in AE's API. We have a whole bunch of code that tries to work around it, but short of forcing the whole AE network to recompute each and every tick we cannot do more about it.

**Comment by PsionicArchon** [comment]
Is there any additional information you could provide? If it's entirely on AE2's end, I'd like to leave a bug report.

I don't remember cables behaving in this way in previous versions of AE2. The whole issue confounds me and is nearly impossible to reproduce due to its random nature. 

I'm running into a new issue now. Every so often this cable here: http://i.imgur.com/QTgAqLP.png will detach from the EnderIO conduit it's attached to. I had to replace the AE glass cable with a dense cable to prevent them from disconnecting hourly. Now they only seem to disconnect on server reload. 

It might be worth stating that I'm using RV3 of AE2. Is there a known issue with EnderIO and RV3 compatibility? 

I'd really like to track this down because, it simply can't be worked around. We have massive AE networks on our server. I'm talking thousands upon thousands of cables. Attempting to debug these networks has become more trouble than it is worth. I am not noticing this issue when exclusively using AE glass cables. The issue only occurs with enderio ae conduits.

**Comment by tterrag1098** [comment]
We do not currently test with rv3 as it is still in alpha. And the AE2 devs say that alphas will probably not work with addons (that includes EnderIO).

**Comment by PsionicArchon** [comment]
Understandable. I'd switch back to RV2 but there are various fixes only in RV3 I rely on. Extra Cells has also added Mek gas support to their latest update for RV3 which I'm using.

I'm going to load up a test world tonight and see if I can reproduce these issues under RV2.

**Comment by HenryLoenwind** [comment]
MatthiasM2 was the last one to try to get it to work correctly. He says:

well - AE2 has no way to query if a tile or side of it can be connected to
so what we do we just guess if it can - and if yes you will be allowed to toggle the conduit to connect in that direction
once we try to connect in that direction we expose a AE2 network node
and according to their API this should magically link up with other nodes ...
which sometimes fails

**Comment by PsionicArchon** [comment]
Interesting, that does make quite a bit of sense. So this is an issue with EnderIO having the ability to unlatch cable connections and AE2 lacking that feature? 

From what I'm gathering, the AE2 dev would have to address this?

**Comment by tterrag1098** [comment]
Please, test with build 423 and see if it is any better.

**Comment by PsionicArchon** [comment]
Just pushed this update out to my server. I haven't noticed anything breaking yet, I'll update this after some testing.

May this update save me from many a gray hair.
