### ISSUE TITLE
Redstone auto extract mode for gas conduits non-functional

### ISSUE THREAD

**Issue by Keyarose** [SleepyTrousers/EnderIO#3058]
Gas conduits will extract gasses regardless of the setting for the redstone control. For example when connected to a mekanisim electrolytic separator a gas conduit will continue to extract gas even when set to active with signal, and there is no signal.

![2015-12-11_20 52 00](https://cloud.githubusercontent.com/assets/1906772/11759048/a782b11c-a049-11e5-8d4b-a4b6d63ea45d.png)
System setup

![2015-12-11_20 51 49](https://cloud.githubusercontent.com/assets/1906772/11759051/babc268c-a049-11e5-9569-ceb34f75bc30.png)
Electrolytic separator gui

![2015-12-11_20 51 36](https://cloud.githubusercontent.com/assets/1906772/11759063/cb096996-a049-11e5-8f9d-f8961cded00c.png)
Gas conduit gui

Using EnderIO 2.3.0.421

**Comment by HenryLoenwind** [comment]
Just a first check: Are you sure it is not the machine that is pushing the gas out? For most conduits the redstone mode only controls active pulling, not accepting/rejecting pushes (that'd be in/out/disabled mode).

**Comment by Keyarose** [comment]
I'm afraid I don't know, the separator does not have the same ability to be configured as many of the core mekanisim machines do.  There's no automatic eject option, likely because the I/O sides are all fixed.

**Comment by Keyarose** [comment]
However I have had this issue with the gas storage tanks as well as the separator. I can't remember a specific instance with anything else offhand though.

**Comment by HenryLoenwind** [comment]
Ok, I'll have a look at our code in the next days.

**Comment by HenryLoenwind** [comment]
I had a look at it. The redstone checks are called correctly. For more I'll have to setup a debugging environment and trace it.

**Comment by Keyarose** [comment]
Well thanks for looking, at least its just a minor annoyance rather than build breaking.

**Comment by VT-14** [comment]
The Electrolytic Separator automatically dumps gas to tanks/machines/pressurized tubes on either side of it.  The gas tanks automatically output to the side that has the red mark on the front.  This is just how Mekanism has set up its gas system.

**Comment by HenryLoenwind** [comment]
Thx VT-14, that was what I suspected. @Keyarose are you ok with me closing this ticket as it seems all is working as intended?

**Comment by Keyarose** [comment]
Sure, I might try and see if i can use a autonomous activator with a wrench to control the gas flow.  If anyone's interested in the result send me a message.
