### ISSUE TITLE
Caught exception from EnderIO java.lang.NoClassDefFoundError: zs

### ISSUE THREAD

**Issue by Tsyklop** [SleepyTrousers/EnderIO#3059]
game crash on start up: http://pastebin.com/xrZFXfbA (error from log file)

crash report: http://pastebin.com/F6sZUAVR

ImmersiveEngineering-0.6.4 immersiveintegration-0.6.5 EnderIO-1.7.10-2.3.0.421_beta EnderIOAddons-1.7.10-2.3.0.421_beta-0.9.10.038_beta

https://github.com/marcin212/LodeLoader/issues/3

**Comment by HenryLoenwind** [comment]
see #3055
