### ISSUE TITLE
Suggestion: Matching the TE Cryo Fluxduct

### ISSUE THREAD

**Issue by Pyrohazard** [SleepyTrousers/EnderIO#3061]
I like Ender IO a lot because of how compact and clean the wiring is. However, it doesn't quite meet the same level of power as Thermal Dynamics. Specifically, Thermal Dynamics has the Cryo-Stabilized Flux Duct, which can transmit an infinite number of RF per tick, which is really necessary for an end-game base that chugs very large amounts of power. What I'm asking of you guys is to make an energy conduit to match that. That way I wouldn't need to have both Thermal Dynamics and Ender IO in my world. 

Taking things a step further would be to add item and fluid conduits to go along with the energy one, and then maybe even expanding upon the capacitors... but since Ender IO has its recipes pretty carefully balanced, an entire new tier probably wouldn't make sense. 

So, as it is, there's a small discrepancy in power, which makes me need TE in my world. Once again, there probably isn't room for a better conduit, but anyway, thanks for reading.

**Comment by HenryLoenwind** [comment]
Press ESC
Click "Mod Options..."
Select "Ender IO"
Click "Config"
Click "Power Settings"
Scroll down to "powerConduitTierThreeRF"
Enter 2000000000 into the field
Click "Done"
Click "Done"
Click "Done"
Click "Save and Quit to Title"
Click "Quit Game"
Restart the game

**Comment by MatthiasMann** [comment]
Just because other mods use insane amounts of energy and other things doesn't mean every one else has to jump the insane bandwagon too.

**Comment by Pyrohazard** [comment]
Wow that was fast. Alright I'll just modify the vibrant energy conduit. Sorry for the trouble.

**Comment by cloakable** [comment]
Also: Mechanically, the cryo fluxduct doesn't transfer unlimited RF/t. It transfers int_max, a number of times per tick needed to transfer the amount needed.

This can mean transferring twice per tick... or 50 thousand times. This can corrupt worlds. (Reported from someone who ran an actively cooled Mekanism fusion reactor into a ("large amount") of Big Reactors turbines.

**Comment by wlhlm** [comment]
> This can corrupt worlds. (Reported from someone who ran an actively cooled Mekanism fusion reactor into a ("large amount") of Big Reactors turbines.

Doesn't this require Liquiducts?

**Comment by cloakable** [comment]
>Doesn't this require Liquiducts?
Pressure Pipes would be the recommended solution to transferring the amounts of steam a Mek reactor can produce. It starts at 150 buckets a tick, scaling up to 3675 buckets. Enough for over 1500 BR turbines. xD
