### ISSUE TITLE
Redstone-Conduit / Project-Red - Bus

### ISSUE THREAD

**Issue by DerTobi01** [SleepyTrousers/EnderIO#3063]
I think it would be awesome to have an one-block-port from project red bundled cables to EnderIO conduits and back, like I built in this picture: http://puu.sh/lUnAR/e4209a01dc.png
Would be very useful! 🙂

**Comment by HenryLoenwind** [comment]
Which 16-channel protocol do they support? We support RedNet and ComputerCraft.

**Comment by DerTobi01** [comment]
I don't really know, haha. What I know is, that there are computer craft programs which can show and log project red-channels on a monitor. 

I also have got another idea, will post that later :)

-Tobi
