### ISSUE TITLE
ItemPhysic spins items inside Obelisk

### ISSUE THREAD

**Issue by CreativeMD** [SleepyTrousers/EnderIO#3065]
Hello,
i'm the author of ItemPhysics, lately i got a report of spinning items inside the Obelisk with ItemPhysic installed(https://github.com/CreativeMD/ItemPhysic/issues/15).

There is a rather easy way to fix it:

You only have to add this line
```java
RenderItem.renderInFrame = true;
```
at the beginning of
```java
private void renderItemStack(T te, World world, double x, double y, double z, float tick)
```
inside ObeliskSpecialRenderer
and this line at the end of the method
```java
RenderItem.renderInFrame = false;
```

This will prevent ItemPhysic from spinning the item instead it will be handled as an item inside a frame.

**Comment by HenryLoenwind** [comment]
It's not quite that easy. renderInFrame also disables vanilla rotation, so we'll have to do that ourselves.

**Comment by CreativeMD** [comment]
Yes, i forgot that part :D
Never saw an Obelisk therefore i thought the item would stand still.
