### ISSUE TITLE
[SUGGESTION] Gas conduits

### ISSUE THREAD

**Issue by DerTobi01** [SleepyTrousers/EnderIO#3067]
Hey, another idea of me would be gas conduits, especially for mekanism, because the gas tubes are really uncomfortable, as seen here:

**Comment by DerTobi01** [comment]
http://puu.sh/lY7UW/4389c31f2d.jpg

**Comment by MatthiasMann** [comment]
Umm - you know that EnderIO had (and still has) gas conduits for a very long time now already?
