### ISSUE TITLE
FakeNetHandlerPlayServer error

### ISSUE THREAD

**Issue by MySt1k** [SleepyTrousers/EnderIO#3069]
http://pastebin.com/x5JMvR7w

**Comment by HenryLoenwind** [comment]
```
EnderIO: Found the following problem(s) with your installation:
                 An unsupported base software is installed: 'kcauldron, cauldron, craftbukkit, mcpc'. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
```

If you get me the source of the NetHandlerPlayServer class that is used in your environment, I'll have a look if I can work around it. Otherwise: Ender IO works with the Minecraft classes as they are shipped by Mojang and patched by Forge.

**Comment by Calenria** [comment]
https://github.com/spannerman79/KCauldron/blob/master/patches/net/minecraft/network/NetHandlerPlayServer.java.patch
