### ISSUE TITLE
Update BuildCraft dependency to 7.2.x build

### ISSUE THREAD

**Issue by crunkazcanbe** [SleepyTrousers/EnderIO#3076]
As the title says . Thank you . :)

**Comment by HenryLoenwind** [comment]
why?

**Comment by crunkazcanbe** [comment]
Well for one because the apiece here is out dated by a long shot and for two there are quite a few changes in the new BC . I was looking at the source and to build this mod against the new BC apiece you will need to change a good bit of your code including alot if not all of the imports for BC in this mod are no longer any good .

The new BC engine do not work with your capacitors anymore . Alot of this code needs updated in your mod to work with the new BC.

Just thought I would tell you this . I noticed this when I threw your source in my eclipse and all the BC imports are bad now . I actually went a head and updated the mod for the new BC for personal use .

**Comment by wlhlm** [comment]
BC 7.2 is for Minecraft 1.8.8, so it won't work with EnderIO.

**Comment by crunkazcanbe** [comment]
It's originally for 1.7.10 they just ported it to 1.8.8 . My gosh do you not
look at curse or there github? I don't know how you don't know about 7.2 because
alot if not most mods have updated to it and it was big new awhile back on a
couple big sites.



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On Mon, Dec 21, 2015 at 5:12 AM, Wilhelm Schuster < notifications@github.com [notifications@github.com] > wrote:
BC 7.2 is for Minecraft 1.8.8, so it won't work with EnderIO.

—
Reply to this email directly or view it on GitHub
[https://github.com/SleepyTrousers/EnderIO/issues/3076#issuecomment-166259323] .[https://github.com/notifications/beacon/AFZoALci5aFux7WQWJAtdTLgCvR5n8Cdks5pR8e7gaJpZM4G34qR.gif]

**Comment by MatthiasMann** [comment]
If you already made the changes necessary - why not create a PR?

**Comment by wlhlm** [comment]
Sorry, I haven't heard about it. Are you sure you aren't mixing it up with 7.1? There is no stable 7.2 release yet neither on Curse, nor on Github, nor on their website.

I just went through a couple of the most popular open source mods on CurseForge and all of them depend on BC 7.0 or 7.1. This includes OpenComputers, AE2, Forestry, Gendustry, Railcraft, Minetweaker, OpenPeripheral-Integration, Refined Location. Can you give me an example of an updated mod?

**Comment by crunkazcanbe** [comment]
Yeah that's what I ment



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On Mon, Dec 21, 2015 at 7:04 AM, Wilhelm Schuster < notifications@github.com [notifications@github.com] > wrote:
Sorry, I haven't heard about it. Are you sure you aren't mixing it up with 7.1?
There is no stable 7.2 release yet neither on Curse, nor on Github, nor on their
website.

I just went through a couple of the most popular open source mods on CurseForge
and all of them depend on BC 7.0 or 7.1. This includes OpenComputers, AE2,
Forestry, Gendustry, Railcraft, Minetweaker, OpenPeripheral-Integration, Refined
Location. Can you give me an example of an updated mod?

—
Reply to this email directly or view it on GitHub
[https://github.com/SleepyTrousers/EnderIO/issues/3076#issuecomment-166285591] .[https://github.com/notifications/beacon/AFZoAACmIgflEUoxuXvhKMIaBdvp3wMVks5pR-JMgaJpZM4G34qR.gif]
