### ISSUE TITLE
Issue with EnderIO...

### ISSUE THREAD

**Issue by ingersolljones** [SleepyTrousers/EnderIO#3077]
Sorry to put this here, this may be innappropriate, because I understand that this is a bug tracker and it's purpose is to notify you guys of whatever issues the community comes across with the mod.

I don't have a bug or issue to report. I just want to say that EnderIO is by far my favorite mod that I have ever played with, and I want to heap all of the possible praise and adoration on it's authors. I hope you all will support this mod as long as possible, and keep up the amazing work.

o7 -bnzjnz

**Comment by tterrag1098** [comment]
This is definitely the wrong place. Twitter, or IRC, or Minecraft Forums, or CurseForge, all would have been much better suited.

However, we appreciate the kind words.
