### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bookerthegeek** [SleepyTrousers/EnderIO#3079]
Simple enough I think....

Dimension blacklisting.

Mainly for the runic dungeons, witchery and thaumcraft dimensions.

**Comment by MatthiasMann** [comment]
blacklisting for what?

**Comment by HenryLoenwind** [comment]
What should blacklisted? The crafting of Ender IO machines, their placing or their operation? And why?

**Comment by bookerthegeek** [comment]
For the staff of travelling. Sorry for the derp of not specifying that. Oops.

**Comment by MatthiasMann** [comment]
You can black list blocks which should not be teleported through

**Comment by bookerthegeek** [comment]
The blocks themself? Ah, must of missed that. Only saw the ability for air or not air.

**Comment by bookerthegeek** [comment]
lines 513 and 516 (notepade++)
# If travelStaffBlinkThroughSolidBlocksEnabled is set to false and this is true: the travel staff can only be used to blink through transparent or partial blocks (e.g. torches). If both are false: only air blocks may be teleported through.
B:travelStaffBlinkThroughClearBlocksEnabled=false

# Allows the travel staff to blink through unbreakable blocks such as warded blocks and bedrock.
B:travelStaffBlinkThroughUnbreakableBlocksEnabled=false

then at the bottom

line 1013 (notepade++)* werid this seems to be wording wrong. But setting it to false makes it not possible to pass through the blocks.
# If set to false: the travel staff can be used to blink through any block.
B:travelStaffBlinkThroughSolidBlocksEnabled=false

**Comment by bookerthegeek** [comment]
Sorry for the formating my phone is stupid.
