### ISSUE TITLE
[SERVER CRASH] left click with yeta wrench on Project Red alloy wire

### ISSUE THREAD

**Issue by ericcotelnu** [SleepyTrousers/EnderIO#3084]
I clicked with my yeta wrench on a laid down piece of alloy wire and the server crashed. I do have fastcraft installed. I saw some fastcraft-related messages in the report.

[crash-2015-12-20_23.31.19-server.txt](https://github.com/SleepyTrousers/EnderIO/files/68104/crash-2015-12-20_23.31.19-server.txt)

**Comment by HenryLoenwind** [comment]
As we have no action on the left-click of a wrench if the clicked block is not a conduit bundle, could you please also raise this issue with Project Red? Thank you.

At first glance I see nothing that points to one of our functionalities, we don't send custom block placement packages or place blocks with the wrench. However, with only the result of the action on the client, not no stack trace of the actual action on the server, it is hard to say. (In simple terms: Something happens on the server that makes only the client cough.)
