### ISSUE TITLE
[Crash]   java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by Dream-Master** [SleepyTrousers/EnderIO#3085]
I get a crash using Ender IO 422

Modpack

https://github.com/GTNewHorizons/NewHorizons

crash log:

https://gist.github.com/Dream-Master/24b0a7182b790ba0db03#file-crash-ender-io

**Comment by wlhlm** [comment]
This is the same as #3069

```
An unsupported base software is installed: 'kcauldron, cauldron, craftbukkit, mcpc'. This is NOT supported.
```

**Comment by Dream-Master** [comment]
Yes whe using KCauldron. Why this inst supported ?

**Comment by Dream-Master** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/60bbf22d7ebb9bec2efa0719087bcb9944728801

**Comment by Dream-Master** [comment]
it is not exact the same error.

**Comment by HenryLoenwind** [comment]
With Ender IO you get support in different levels:

Level 1: It works with Minecraft and the Forge version that is listed in the dependencies.

Level 2: It works with other mods by the same developers.

Level 3: It works with the mods that are directly supported in the version that is listed in the dependencies.

Level 4: It works alongside big mods. It works with newer version of Forge. It works with newer versions of the directly supported mods as long as they don't change their API.

Level 5: It works alongside mods that in turn play nice (use Forge correctly, don't patch Minecraft in a incompatible way, react to bug reports, ...).

Level 6: Everything else that is open source.

Level 7: Everything else that is closed source. Mods that don't play nice.

KCauldron is level 6. That is the first level we call "unsupported", although that distinction is completely arbitrary---the only reason there is any support at all is that some people just do it.

And BTW: It is the same error, just triggered by another FakePlayer on our side.

**Comment by Dream-Master** [comment]
Ok understand but why version 421 works fine?

**Comment by wlhlm** [comment]
Because for 422, the fake player has been tweaked to be more "life-like", this closed a couple of open issues. See #3018

**Comment by Dream-Master** [comment]
Make it sense to ask on KCauldrons site to ask for a solution ?
