### ISSUE TITLE
[Suggestion] RF Limiter

### ISSUE THREAD

**Issue by EtherG** [SleepyTrousers/EnderIO#3092]
I think there should be a block that allows the exact limitation of RF going through it, i know the capacitors could but the capacitors are kinda expensive compared to the cheapness a RF limiter could be.

**Comment by MatthiasMann** [comment]
Use the energy buffer - it is doing exactly that.

**Comment by EtherG** [comment]
oh, i didnt realize that i was using an old version. welp, sorry for suggesting something in the mod already
