### ISSUE TITLE
beta422 messes up resourcepacks

### ISSUE THREAD

**Issue by b0bst3r** [SleepyTrousers/EnderIO#3094]
No idea if this is even fixable in a resourcepack.

Previous to this update - http://postimg.org/image/s6xeggx55/ we had simple transparent boxes with backgrounds on.

They got removed and you somehow overlay the item texture into the box, works great for vanilla but doesn't work at all for resourcepacks. 

http://postimg.org/image/dz7prtkg9/

There's nothing in those slots but it looks like there is.

Is it possible to fix this, I see no alpha transparency textures on anything in the mod?

**Comment by HenryLoenwind** [comment]
The resource pack needs to also needs to implement a transparency mask that matches the slot backgrounds. It is part of the widget sheet.

**Comment by HenryLoenwind** [comment]
Just as a reference for the next time this comes up:

This is the icon that needs to be set to resemble the slot background:

![](http://i.imgur.com/4DpJkQi.png)

(That's the endercore widget sheet)

**Comment by b0bst3r** [comment]
As I said in IRC what you've done makes the GUI a confusing mess and just to prove the point http://postimg.org/image/9oxn9z4qx/

**Comment by tterrag1098** [comment]
@HenryLoenwind I had assumed that the overlays would hide when something is in the slot. If that's not the case, it needs to be. Otherwise @b0bst3r is absolutely correct.

**Comment by HenryLoenwind** [comment]
I mirrored the old behavior exactly. (Aside from the shuffling)
