### ISSUE TITLE
Extra Cells 2 Integration

### ISSUE THREAD

**Issue by DeathCorps69** [SleepyTrousers/EnderIO#3098]
I'm not sure if this should be a request here or through Extra Cells' tracker let me know if i should repost it there. 

The buses added by extra cells do not attach to the ME Conduits and would be very helpful to have.

Just in case it's a bug i'm Running (short-version):
EnderIO-1.7.10-2.3.0.422_beta
ae2stuff-rv3-0.5.1.9-mc1.7.10.jar
AE2TechAddOn-1.7.10-1.0-b81-universal.jar
ExtraCells-1.7.10-2.3.6b172.jar
appliedenergistics2-rv3-beta-1.jar

**Comment by XFactHD** [comment]
You also cannot attach AE2  busses to me conduits. This is not a bug. This feature has often been requested but it is nearly impossible to do at the moment.

**Comment by DeathCorps69** [comment]
Oh... i don't even know how i didn't notice that >.<
