### ISSUE TITLE
Inventory Panel Not pulling items into crates

### ISSUE THREAD

**Issue by lgcjoker** [SleepyTrousers/EnderIO#3099]
I have been using EnderIO for my inventory for a while now and all of a sudden a few days ago, all panels have quit pulling the items in the return section out to chests.  I checked all settings and connections to the panel and nothing has changed there.  If you would like to look at the issue, let me know and I can give you the IP of our server.

Thanks

**Comment by MatthiasMann** [comment]
Did you switch the mode of the area to crafting storage? you can click on the title to toggle the mode.

**Comment by lgcjoker** [comment]
Wow, did not know that.  I just clicked on it and the items returned to inventory.  I had it set on storage and not return.

I have also seen another issue with the conduit.  Would you like me to post that here or start a new report?

**Comment by MatthiasMann** [comment]
If it's not already reported then post each as a separate issue.
