### ISSUE TITLE
Conduit will disappear at random

### ISSUE THREAD

**Issue by lgcjoker** [SleepyTrousers/EnderIO#3100]
I have seen on our server that once we got a good amount of EnderIO conduits in place, they will just disappear and re appear at random.  At times when they re appear, they have lost connection.  This seems to happen the most to all the conduit that I have around my Big Reactors. Not sure if it is a bug, a glitch on my server, or what but wanted to report.  As always, I can give you the IP to my server to see for yourself.

**Comment by wlhlm** [comment]
This is a known bug and was fixed in newer versions AFAIK. See #2812. What version of EnderIO are you running?

Also, Optifine amplifies this issue. Using "Default" chunk rendering will resolve this. See [#2862 (comment)](https://github.com/SleepyTrousers/EnderIO/issues/2862#issuecomment-150161935)
