### ISSUE TITLE
Ender IO bug

### ISSUE THREAD

**Issue by Necko1996** [SleepyTrousers/EnderIO#3106]
Ender IO not working with BuildCraft Fuel
I use latest version of bouth.
In Combustion Generator use a ton of wather (tested with a ton of unlimited water) and still not make a energy.

**Comment by MatthiasMann** [comment]
a) explicitly state the version you use
b) provide a screenshot of the combustion generator UI
c) if it uses water - it will also generate energy and consume fuel
