### ISSUE TITLE
Auto Crafter Crash?

### ISSUE THREAD

**Issue by Cracks777** [SleepyTrousers/EnderIO#3107]
http://pastebin.com/ktqLTf5T

**Comment by MatthiasMann** [comment]
Have you seen this:
EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.13 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from IC2NuclearControl-2.3.3a-Exist.jar).
                    It is a supported version, but that difference may lead to problems.
                 An unsupported base software is installed: 'kcauldron, cauldron, craftbukkit, mcpc'. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

**Comment by HenryLoenwind** [comment]
see  #3069
