### ISSUE TITLE
Crash when i open the "Vibrant Capacitor Bank"

### ISSUE THREAD

**Issue by TYPTheYoloPanda** [SleepyTrousers/EnderIO#3111]
This is log I'm playing in a private server
EnderIO Version 2.3.0.422
EnderCore 0.2.0.31
I tried to update all mods in my pack but doesn't work :'(
http://pastebin.com/tBJZpsZC

**Comment by HenryLoenwind** [comment]
You have some vanilla Minecraft item like dirt or sand in one of your Baubles slots, I'd guess from that stacktrace. What happens when you use your normal inventory?

**Comment by TYPTheYoloPanda** [comment]
No no one vanille item in my inventory when i open my capacitor bank but i crash anyway...
