### ISSUE TITLE
Request for a Higher tier conduit

### ISSUE THREAD

**Issue by Mementh** [SleepyTrousers/EnderIO#3112]
I love that the tiers of conduits are here.. it does allow more options to grow..

but i figure with todays energy usage it can get troublesome.. There is a machine wall that if they are all active i can't keep them powered with the highest tier of power conduit.

I would ask that there be two new conduits added and the current ones changed around. 

the basic energy conduit level would carry 2.5k/tick 

the enchanced conduit would carry 15-20k rf/tick.

the tender conduit would carry 30-50k

Tier 4 would carry 60-100k and the conduit binder would be binder around a zombie electrode? this would use a new alloy dark energetic alloy nuggets for the center? ( dark steel mixed with energetic alloy)

tier 5 would be infinate simalar to the cryo flux ducts and be a complex wire to setup with the new binders from tier 4 but the wire between would requie a ender resonator head in the middle of two dark energetic ender alloy ? ( enderium ingot plus dark steel and energetic alloy )

feel fee to suggest other things?

**Comment by XFactHD** [comment]
This has been requested multiple times already and it was rejected every time.

**Comment by Mementh** [comment]
@XFactHD why? I like how i can hide the cables.. but they just can't move enough power to be usefull on a bigger setup.
is there a way to have other wires become useable with these somehow ?

**Comment by MatthiasMann** [comment]
The conduit limit is per connector (not per network) - so you just need to plan your wiring a bit more careful - eg connect it at multiple points to the capacitor banks.

Just because some mods try to outdo others by going bigger numbers for everything is no reason why others should follow this insane path.

**Comment by Mementh** [comment]
@MatthiasMann I prefer using tesseracts to get power to a place.. but I might not understand.. are you saying that a single setup of wire that has say all 6 sides of a tesseract covered has 60k rf/tick available or only 20k? because the rf/t suggests the entierty of wire not individual connections

**Comment by MatthiasMann** [comment]
All 6 sides - each side 20kRF ==> 120k RF

**Comment by Mementh** [comment]
so bascally your saying that if you use another mods wire that is infinate you can get the max power it just will just be just a box in the corner of the room/hidden and the ender IO is infinate just 20k per connection input.. 

soooooooooooo why not just make a infinite wire or one that does alot more per connection? 

what is the reason for the limit? personal preferance? balance of some kind? or some other logical reason?

**Comment by tterrag1098** [comment]
See #2706 #2278 #1894

**Comment by tterrag1098** [comment]
I may add, the values are configurable. I see no reason to add another tier of fluff when you can just buff the existing tiers to your liking.

**Comment by HenryLoenwind** [comment]
And let me add this: It is the modpack author's job to configure the mods in the modpack in a way that they work nicely with each other. So if you have machines that (prod)uce more RF than the highest tier of conduits, they didn't so their job.

**Comment by Mementh** [comment]
i will poke the mod author.. maybe there is a balance that could be done

**Comment by Badcholo** [comment]
I agree, it is our job. It's so hard being us.
http://www.technicpack.net/profile/1206272/modpacks
