### ISSUE TITLE
waila shows too much for ender io

### ISSUE THREAD

**Issue by Mementh** [SleepyTrousers/EnderIO#3113]
if there is a config option that i am missing i apologize but i don't see a way to show less in the waila then what i have here

http://imgur.com/nPqaH49

**Comment by tterrag1098** [comment]
lol dang. I guess ender fluid conduits should probably not show anything, since they don't actually hold any fluid.

**Comment by CrazyPants** [comment]
fixed

**Comment by Mementh** [comment]
*cheers luvs*

**Comment by FlavaSava** [comment]
Is the bug back? I have the exact same issue with 
- MC 1.7.10
- Waila 1.7.3
- Ender IO 2.7.6

**Comment by HenryLoenwind** [comment]
> Is the bug back? I have the exact same issue with
> 
> * MC 1.7.10
> * Waila 1.7.3
> * Ender IO 2.7.6

2.7.6 is a fork by the GTNH team -> https://github.com/GTNewHorizons/EnderIO

It also is quite outdated, 2.8.17 is the current version.
