### ISSUE TITLE
Applied Energistics 2 RV3 Beta crashing

### ISSUE THREAD

**Issue by shader301202** [SleepyTrousers/EnderIO#3115]
Hi, when I try to run Minecraft with Ender IO (2.3.0.422 Beta) and Applied Energistics 2 RV3 Beta 3, my game crashes. Crash log: https://paste.ee/p/pAo4Y
In the lines 10372 to 30374: " * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-3.jar).  Ender IO was build against API version rv2 and my not work with newer version."

**Comment by wlhlm** [comment]
The log shows that you're also running a whole bunch of other mods, and the stacktrace doesn't indicate that it's an EnderIO issue.

Does it work when you update EnderIO to 423, or maybe downgrade AE2 to rv2 or rv3-beta-3?

**Comment by shader301202** [comment]
With AE2 RV2 I get this: "EnderIO: Found the following problem(s) with your installation: *The RF API that is being used (1.7.10R1.1.0 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from buildcraft-7.1.14.jar). It is a supported version, but that difference may lead to problems.|
And where can download Ender IO 423?

**Comment by wlhlm** [comment]
Oops, I forgot that it wasn't published to curseforge. 423 is test build that fixes some problems related to ME Conduits.

http://ci.tterrag.com/job/EnderIO/

**Comment by wlhlm** [comment]
Ahh, found the relevant bit:

```
EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-3.jar).
                    Ender IO was build against API version rv2 and my not work with newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
```

RV3 simply is not supported at this point.

**Comment by Dream-Master** [comment]
Ender IO 421 and Applied Energistics rv3 beta 2 works well together. I not get any crash.

**Comment by shader301202** [comment]
With the 423 version i got no crashes.

**Comment by HenryLoenwind** [comment]
Oops, I derped a bit when writing that text. It should be "and may not work with a newer version". Stress on the "may". Or even "may or may not".

**Comment by HenryLoenwind** [comment]
And for the original crash, I think the error message is quite clear:"Conflicting biomes forced game to crash"

It seems the mod "antiidconflict" stops the game from being loaded because it detects an ID conflict between vanilla biomes and Biomes Of Plenty biomes. However, judging from the names of the conflicting BoP biomes, I would *guess* that BoP is replacing all vanilla biomes on purpose and antiidconflict wrongly detects that as a conflict. Raise a ticket with its author (elix_x?).

**Comment by shader301202** [comment]
Yeah, Anti ID conflict and BoP were the problem. I asked the author of BoP and he said, that any Anti ID conflict mod is incompatible with BoP.

**Comment by bookerthegeek** [comment]
Wird, just go change the id's of the biomes. Their is a configuration folder anti Id. This will show you the id's and the mod that are conflicting.

**Comment by HenryLoenwind** [comment]
@bookerthegeek Look at the crash log. There is no conflict. BoP replaces the vanilla biomes and antiidconflict reports that as a conflict between vanilla and BoP.

**Comment by LeEpicTroll** [comment]
i am having the same issues (in project ozone 2) but also when i change the versions of ender io and applied energistics, i boot up the game but it tells me to use the latest version that is causing me the issues
