### ISSUE TITLE
Minimum EnderIO version required 1.7.10-2.3.0.423_beta ???  LOL WuT

### ISSUE THREAD

**Issue by SugarDaddii** [SleepyTrousers/EnderIO#3117]
hey whenever i want to start my minecraft this bug will print on my screen!

here is my fml log

http://paste.ee/p/loLL4

**Comment by wlhlm** [comment]
You are using EnderIO Addons for EnderIO 423.

EnderIO is a testing build which tries to fix issues with ME Conduits and wasn't published to Curseforge.

You can either download EnderIO 423 [here](http://ci.tterrag.com/job/EnderIO/423/), or downgrade EnderIOAddons.

**Comment by SugarDaddii** [comment]
thx my friend! i will try it :)
