### ISSUE TITLE
is gas conduit supposed to handle multiple gasses ?

### ISSUE THREAD

**Issue by Mementh** [SleepyTrousers/EnderIO#3118]
I am curious if the gas conduit is supposed to work like the fluid conduits and handle multiple gasses on one conduit or just one gas per conduit?

**Comment by MatthiasMann** [comment]
It behaves like a normal (not the Ender) fluid conduit - or the Mekanism gas conduits - only a single gas type at a time.

**Comment by Mementh** [comment]
thanks :) mekanism is single.. i was hoping it would do more now that the versions are compatable .. :/ maybe in the future having a option to do multiple ?

**Comment by sinspawn1024** [comment]
I can't tell you how much I would love it if the gas conduits could handle multiple Mekanism gases. One of my favorite features of the  conduits is to assign color channels to inputs and outputs. It makes IO networks so tidy and organized!
