### ISSUE TITLE
Custom recipes doesn't work.

### ISSUE THREAD

**Issue by wujekbrezniew** [SleepyTrousers/EnderIO#3119]
I want to edit some recipes from EIO machines so I wrote <a href="http://pastebin.com/pr6QSG7C"> this</a> code in user config but... it didn't work.
It is a bug or my code is incorrect?

**Comment by MatthiasMann** [comment]
Did you check the log files to see if there are any errors?

**Comment by HenryLoenwind** [comment]
Please first start the game and look in the logfile. There should be some messages about recipe loading.

**Comment by wujekbrezniew** [comment]
<a href"http://pastebin.com/gWWAxWTx">This?<a\>

**Comment by wujekbrezniew** [comment]
This?
http://pastebin.com/gWWAxWTx

**Comment by HenryLoenwind** [comment]
Yes. However, I didn't expect it to fail that hard. Have me look into the code, why it crashes instead of giving you an error message. Which Ender IO version are you using?

**Comment by wujekbrezniew** [comment]
Code is in link in first post.
I try to use different versions of EnderIO. The newest beta version and the last release.
EnderCore which I use is always the newest beta.

**Comment by HenryLoenwind** [comment]
From the crash it looks like you are creating a recipe group without a name. However, the xml you posted has only one group and that one has a name...

**Comment by wujekbrezniew** [comment]
And?
