### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Divineaspect** [SleepyTrousers/EnderIO#3121]
I am having the string  "crazypants.enderio.machine.generator.stirling.BlockStirlingGenerator@a55560e" 
repeated many many times in my console.

I have tracked down the following facts, there is one stirling generator loaded when it happens, and it is in contact with 2 calculator machines.

A casual search of the open issues lead me to believe that it was related to #2804.

**Comment by HenryLoenwind** [comment]
So that is the complete line? No text before it, or after it? No timestamp? Nothing?

Then it is not from Ender IO. What other mods do you have around that could be interacting with a sterling generator?
