### ISSUE TITLE
Fused Quartz has same blast resistance as Reinforced Obsidian... bug?

### ISSUE THREAD

**Issue by koalalord9999** [SleepyTrousers/EnderIO#3122]
Is this a bug? I was watching Hypno play FTB Inifnity Expert - and he used Fused Quartz as a reactor proof wall for his reactor chamber. I'm pretty sure fused quartz isn't supposed to stop a nuclear reactor explosion... or am I wrong? (It would stop a wither as well, if it can stop nuclear reactor) This effectively makes Reinforced Obsidian worthless.

**Comment by tterrag1098** [comment]
Even if this is a bug, it definitely DOES NOT mean it can stop withers. Withers can break anything. Reinforced obsidian has special code to prevent it.

**Comment by koalalord9999** [comment]
Oh, alright :P figured the wither explosion was a blast level cause even bedrock has a blast cap, granted its like 2 million tnt on one block at same spot or something like that, but figured wither just did really high blast damage.

**Comment by tterrag1098** [comment]
No, withers don't do blast damage, they just destroy blocks.

**Comment by Badcholo** [comment]
They can't destroy blocks from the Fortress mod.
https://www.youtube.com/watch?v=XbJwb1JLgNc
