### ISSUE TITLE
Problems with testing in IDEA

### ISSUE THREAD

**Issue by ShadowT1me** [SleepyTrousers/EnderIO#3123]
Hey guys, occured problem (error) when i wanted to test mod in idea client build. How to fix it?

http://pastebin.com/3bhYc7Ta
http://imgur.com/22akanG

**Comment by tterrag1098** [comment]
Looks like you have duplicated CodeChickenCore.

**Comment by mindforger** [comment]
CCC installs itself on launch sometimes in the 1.7.10 folder under mods and causes double installation

**Comment by FirKys** [comment]
I've also encountered this issue. Looking for someone who could help me through skype or teamviewer?
