### ISSUE TITLE
NEI does not show machine-specific recipes

### ISSUE THREAD

**Issue by Zsashas** [SleepyTrousers/EnderIO#3124]
I saw that this was added in a previous version, but it looks like it's gone again.

**Comment by HenryLoenwind** [comment]
Which version of Ender IO and NEI are you using? What kind of integration do you expect/is not working for you?

**Comment by Zsashas** [comment]
2.3.0.421 Ender IO
1.0.5.120 NEI

The recipe button in the Alloy Smelter does nothing when I click it, I can't see ANY of the recipes.

**Comment by HenryLoenwind** [comment]
I just checked (Ender IO 2.3.0.423 and NEI 1.0.5.111), it works for me. So it is not generally broken from our side. Could you please check your logfile for any errors or warning messages? Both at startup and when you click the recipes button. And: Does the recipes button work for the other Ender IO machines? Can you find the alloy smelter's recipes in NEI when looking at the recipes for things (R key) or when looking at the uses of things (U key)?

If you cannot find anything in the logfile, please: Create a new Creative world and place an alloy smelter in it, re-start the game and enter that world, click the recipes button, exit the alloy smelter GUI, crash the game by holding F3+C for 6 seconds, and send us the logfile, e.g. by attaching it to this ticket.

**Comment by Zsashas** [comment]
It happens both with the smelter recipe button and R /U in NEI. Neither shows ANY alloy recipes. I'll get that new log after work tonight (8h).

**Comment by Zsashas** [comment]
Looks like SAG Mill Recipes aren't showing up either, probably all Ender IO machine recipes.

**Comment by Zsashas** [comment]
Confirmed cannot see recipes in the Alloy Smelter, SAG Mill, Vat, or anything else. Will try downgrading NEI as that may have been the cause....
