### ISSUE TITLE
ender io terminal bug 

### ISSUE THREAD

**Issue by johnfg10** [SleepyTrousers/EnderIO#3129]
ender io version 2.3.0422 

video of bug listed here https://www.dropbox.com/s/1bjs0a99tzads7d/bug%204.avi?dl=0

**Comment by HenryLoenwind** [comment]
Please reproduce the problem, then press F3+C for 6 seconds to crash the game. attach the logfile to this ticket.

**Comment by johnfg12** [comment]
ok

**Comment by johnfg12** [comment]
[logs.zip](https://github.com/SleepyTrousers/EnderIO/files/90205/logs.zip)

**Comment by johnfg12** [comment]
its in there

**Comment by johnfg12** [comment]
i didnt close mc so should be in there

**Comment by johnfg12** [comment]
and its stopped doing it know but it has been doing this randomly to multiple people

**Comment by MatthiasMann** [comment]
Can you enable the item IDs and meta data in the tool tip (I think this is an NEI option) and check if the IDs match with one of these lines in your log file?
Fixed item id mismatch Metallurgy:bronze.ingot: 5491 (init) -> 5392 (map).

**Comment by johnfg12** [comment]
right i have no idea how to do that

**Comment by wlhlm** [comment]
Vanilla also has this built-in: Press F3+H.

**Comment by tterrag1098** [comment]
@johnfg12 could you please install this build on your client AND server, and then post your log file after reproducing the bug? http://puu.sh/mvNsR.jar

**Comment by johnfg12** [comment]
i can test it on my client the sever will be up to the mod pack creator i can ask him to come over if you would like

**Comment by tterrag1098** [comment]
However you do it, it would be a huge help to have this info as this bug is very had to reproduce.

**Comment by johnfg12** [comment]
thats the problem i cant reproduce the bug all the time i will ask the pack dev to pop over see if he can help

**Comment by tterrag1098** [comment]
Well keep the version on until you do. It doesn't produce that many log lines, it shouldn't be a big deal. I just need the log directly after it reoccurs.

**Comment by johnfg12** [comment]
ok if it hapens again il do that ive asked the pack dev to pop over he is alot better at this stuff then i am. he will now how to help u with this also nice mod :D

**Comment by knoxz** [comment]
Had the same issues a few times so far.
I also have the same issue from https://github.com/SleepyTrousers/EnderIO/issues/2755
From time to time. Items I put in just vanish until I manually refresh the invenotry (by removing and adding the awareness upgrade on the Conduit), also adding the item manually into the chests again seems to fix the issue. 
Maybe the placeing into the chest is not prompting an update correctly? Would explain both issues. I may try to only use vanilla chests to see if that fixes the issue. You cant really say it is rare. At least the vanishing.
We are using EnderIO-1.7.10-2.3.0.422_beta and I also use Gold/Diamond chests.

**Comment by tterrag1098** [comment]
It's rare because it only seems to happen on certain servers. Please if you are experiencing the issue, use the debug build above.

**Comment by knoxz** [comment]
It's a cauldron server setup. Does this help?

**Comment by tterrag1098** [comment]
I doubt that's the cause. Please, test with the debug jar, else I can't really do much about this bug.

**Comment by bookerthegeek** [comment]
@tterrag1098 Would this need to be installed on both server and client, or just one/either?

We are having this issue on our server and am more then willing to help out by testing.

**Comment by tterrag1098** [comment]
@bookerthegeek both, I need to compare the log from both sides.

**Comment by bookerthegeek** [comment]
Ok, I'll update our server tonight, should have some logs for you by Wednesday.

**Comment by johnfg12** [comment]
@bookerthegeek is this live on the main server or a test version?

**Comment by bookerthegeek** [comment]
Sorry for the delay in logs, we are currently having an issue  that is wrecking our server. I'll update as soon as we get it fixed.

**Comment by tterrag1098** [comment]
Any news?

**Comment by bookerthegeek** [comment]
Sorry, got lost. I'll have information. For you inside of 48 hours.

**Comment by charlesbevans** [comment]
It happened again. This time raw plastic, freshly added, was the culprit.
[crash-2016-03-11_10.33.43-client.txt](https://github.com/SleepyTrousers/EnderIO/files/169749/crash-2016-03-11_10.33.43-client.txt)
When I reloaded, the plastic was visible.

**Comment by MatthiasMann** [comment]
This dump doesn't help - I need the debug log messages from the fml-client-latest.log (on the server) and latest.log on the client.

**Comment by charlesbevans** [comment]
Sorry, my mistake. I was just having a problem with the panel finding components for IC2 reactor vents so I crashed it again.
[Archive.zip](https://github.com/SleepyTrousers/EnderIO/files/169926/Archive.zip)

**Comment by tterrag1098** [comment]
@charlesbevans Just to clarify, you did have the custom jar installed on BOTH client and server when you generated these logs, correct?

**Comment by charlesbevans** [comment]
SSP on the FTB launcher. No separate server. No modifications. Infinity Evolved, expert mode.

**Comment by MatthiasMann** [comment]
Please install the latest EnderIO version from http://ci.tterrag.com/job/EnderIO/ and if the issue happens again upload both logs again. This build contains the debug messages we need to analyze this.

**Comment by MonkeyTonk** [comment]
Hello @tterrag1098,

I have logs for you: SSP
* [latest.log](https://gist.github.com/MonkeyTonk/75dda5e2284cf556a91d)
* [fml-client-latest.log](https://gist.github.com/MonkeyTonk/3210350fc28840af80b4)

Happened around 15:00 to 15:05. The Pneumatic Servo from Thermal Expansion is in the connected Modular Storage but doesn't show up in the Inventory Panel. It was inserted into the Modular Storage via Return area of Inventory Panel.

I don't see DEBUG messages in latest.log. Do I have to set the loglevel of another LOGGER I didn't recognize?

![Connections - Modular Storage](https://cloud.githubusercontent.com/assets/357704/13956715/0f48f14e-f04a-11e5-815e-ef3e657042b4.png)
![Connections - Inventory Panel](https://cloud.githubusercontent.com/assets/357704/13956723/1462757e-f04a-11e5-80e6-46782777a3cb.png)
![Contents - Modular Storage](https://cloud.githubusercontent.com/assets/357704/13956725/17c5fefc-f04a-11e5-9366-e5f79f8146ba.png)
![Contents - Inventory Panel](https://cloud.githubusercontent.com/assets/357704/13956733/1bc8e5dc-f04a-11e5-8179-33fa1ccfaa33.png)
![Contents - Inventory Panel after reset through removing and installing awareness upgrade again](https://cloud.githubusercontent.com/assets/357704/13956777/4905a2ce-f04a-11e5-9a44-a68af830a7b8.png)

**Comment by HenryLoenwind** [comment]
@MonkeyTonk You are still using an old Ender IO version that doesn't have the debug output.

**Comment by MonkeyTonk** [comment]
Since which version is the DEBUG output enabled?

**Comment by MonkeyTonk** [comment]
I have updated my previous comment:
_Same behaviour with version EnderIO-1.7.10-2.3.0.424_beta.jar_

**Comment by tterrag1098** [comment]
```
[20:27:31] [Client thread/INFO] [EnderIO/]: Looking up item minecraft:glass. ID: 20  side: CLIENT
[20:27:31] [Client thread/INFO] [EnderIO/]: Looking up item minecraft:glass. ID: 20  side: CLIENT
[20:27:31] [Client thread/INFO] [EnderIO/]: Looking up item minecraft:iron_ingot. ID: 265  side: CLIENT
[20:27:31] [Server thread/INFO] [EnderIO/]: Loading item from ID 20. Result: minecraft:glass  side: SERVER
[20:27:31] [Server thread/INFO] [EnderIO/]: Loading item from ID 20. Result: minecraft:glass  side: SERVER
[20:27:31] [Server thread/INFO] [EnderIO/]: Loading item from ID 265. Result: minecraft:iron_ingot  side: SERVER
```

Those are all the lines I have in that log. Did you get the bug DURING that game instance?

**Comment by MonkeyTonk** [comment]
Yes. I started up Minecraft, did some other things, then reproduced the same setting and got the "bug". The time 20:27 does match the time when I created the pneumatic servo, put it the modular storage and inspected the inventory panel.

**Comment by MatthiasMann** [comment]
@MonkeyTonk so - just that I understand your issue - you inserted an item into your modular storage via the return area, and it didn't showed up in the panel? how long did you wait?

The panel is scanning the connected inventory one after another - the more slots an inventory has the longer it takes to do it. This is done to prevent excessive server load.

The debug messages have been added to debug a case where the item displayed was item "A" and once you take it out it turned into item "B" - so far this only seem to happen on some servers (maybe related to some server mods - no idea yet).

**Comment by MonkeyTonk** [comment]
@MatthiasMann: yes, quite right. I did wait some time. First some seconds, then again after a while.. maybe between 1 and 3 minutes. It wouldn't show up until I replaced the remote awareness upgrade.
But maybe this is not enough. Especially when you say
> the more slots an inventory has
Via the storage module tier 2 the modular storage has 200 slots.

Regarding the debug messages: Is this the wrong issue for my mentioned behaviour? I have been forwarded to this issue here (from another one).

**Comment by MatthiasMann** [comment]
hmm - 200 slots means 24 ticks pause (1.2 seconds) - how many remote awareness upgrades do you have on your network?

**Comment by MonkeyTonk** [comment]
@MatthiasMann: the panel is on a network with 3 storages resulting in 3 remote awareness upgrades.
1 modular storage with storage module tier 2 (200 slots)
1 diamond chest (108 slots)
1 iron chest (54 slots)

Only the modular storage has the conduit interface set to insert mode. All other inferfaces are set to extract mode.

**Comment by HenryLoenwind** [comment]
link #3473
