### ISSUE TITLE
1.8 Support?

### ISSUE THREAD

**Issue by chaos234** [SleepyTrousers/EnderIO#3130]
Searched for a ticket for MC1.8 Support because Ender Zoo already have it but not EnderIO.

It will be glad to here if there are some betas ore testing alphas available.

**Comment by XFactHD** [comment]
The RF API did not get ported to 1.8 until now, so I don't think there will be a 1.8 version of EnderIO in the near future.

**Comment by wlhlm** [comment]
AFAIK, there is no work being done on an EnderIO port for 1.8.9. There simply are not enough devs/time. Work currently is done to get out a stable 2.3 release for 1.7.10.

**Comment by chaos234** [comment]
Good to know and thanks for the fast response.
So my Modpack will definitly be on/at 1.7.10 :)


Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
Am 14.01.2016 13:50:30 schrieb Wilhelm Schuster <notifications@github.com>:
AFAIK, there is no work being done on an EnderIO port for 1.8.9. There simply are not enough devs/time. Work currently is done to get out a stable 2.3 release for 1.7.10.

**Comment by HenryLoenwind** [comment]
as wlhlm said, we're short on manpower.
