### ISSUE TITLE
Fluids getting into item conduits from machines and fluid conduits

### ISSUE THREAD

**Issue by isochronous** [SleepyTrousers/EnderIO#3132]
This is using EnderCore 0.2.0.31 beta and Ender IO 2.3.0.422 beta on MC 1.7.10 (obviously), Forge 10.13.4.1558.

I keep having issues with fluids getting into my item conduits, both when hooked directly to a machine (e.g. MFR Harvester) or when run alongside fluid conduits. For example, I have a pressurized fluid conduit going from a harvester to a sludge boiler, and an item conduit going from the sludge boiler back to a tesseract.  If I run the item conduit in the same block as the fluid conduit, and the fluid conduit has fluid in it, the *instant* I add the item conduit it fills with 1,000mB of Sludge, and any "downstream" item conduit will also fill with sludge.  That then backs up the sludge boiler, as it has no where to export its inventory, so it stops accepting sludge. Then the harvester has no fluid conduit into which its sludge can go, so it exports sludge *into its item conduit!*

I should note that the amount in the item conduits is always exactly 1,000mB, so I suspect it has something to do with Minecraft/Forge going "oh, 1000mB is one bucket, so it must be transporting a bucket of \<liquid\>"... but it never gets inserted on the far end (though now that I think about it, that may have been because it had no inventory that would accept them).

I've made a backup of the world I'm playing on and the gaggle of mods I've assembled, so if you need to check those out to repro the issue, that option is available. Or you can reach me through the comments here, I can give you a login to my private server, and you can check it out that way.  For now I've ironed out all of the kinks (mostly by never allowing item conduit and fluid conduit to occupy the same block, and by ensuring that machines never get backed up with fluid), but I can easily put things back into an error state.

**Comment by HenryLoenwind** [comment]
How do you determine there is something in an item conduit?

**Comment by wlhlm** [comment]
I wasn't able to reproduce this with just MFR+EnderIO. Can you provide a video demonstrating the issue?
![2016-01-16_01 41 19](https://cloud.githubusercontent.com/assets/1928113/12369060/52661c4a-bbf2-11e5-99bc-bbd596b23dcc.png)

Mods installed:

- CoFHCore 3.0.3
- EnderIO 422
- EnderCore 0.2.0.31
- MFR 2.8.0-104
- WAILA 1.5.10

**Comment by isochronous** [comment]
I think I can manage that. I'll capture some footage tonight and update
this thread.

As for how I could tell, I was using the Yeta wrench and looking at the
tooltip, which said "item conduit: 1000mB sludge". If that had been all, I
would have assumed it was just a tooltip bug, but the system also *acted*
as if it was jammed up with something it couldn't get rid of, and even the
item conduit in its own separate block said the same thing if it was
downstream of the point of contact. Once I broke the conduit and just ran
it so it never touched the sludge, it worked fine. The same thing happened
with item conduits that touched pressurized fluid conduits filled with
sewage: they got sewage in them at 1000mB per segment. In that case the fix
was also to run the item conduits so never touched a fluid conduit until
it's terminating point (breeder/rancher/planter/etc).

**Comment by isochronous** [comment]
What you're showing in that screenshot isn't a problematic setup. Do this: put down a chest full of stuff. Attach an item conduit to it. Then run that item conduit into the same block as a segment of full fluid conduit - not on a terminating end of it. That's what caused the problem for me.

**Comment by HenryLoenwind** [comment]
I'd really love to see this in action (series of screenshots would be fine for me) because an item conduit just has no place to put any fluids...

**Comment by isochronous** [comment]
Aaaand I'm completely wrong.  The tooltip is just extremely misleading.  Sorry to have wasted your time!
