### ISSUE TITLE
Feature Request: Add a single item filter to non-ender fluid conduits on extract

### ISSUE THREAD

**Issue by isochronous** [SleepyTrousers/EnderIO#3133]
I'd really, really, REALLY like it if non-ender fluid conduits supported filtering on extract.  Some machines output more than one type of fluid, and will alternate outputting multiple kinds into the same conduit as long as the conduit is empty at the time. The problem is, the fluid container the conduits empty into won't accept  a second type of fluid.

For example, the MFR Slaughterhouse produces liquid meat and pink slime. If I hook up a single fluid conduit (for meat, as pink slime generates much more slowly) that's flowing into a drum, it works great until all of the liquid meat has been drained, but if there's any pink slime in the machine, it will then export THAT into the same conduit. But since that conduit is only hooked up to one output, and that output contains a different liquid, the pink slime just sits in the conduit until I either break it or detach the drum and put down a different one.  Having a white/blacklist filter (that only supports a single fluid type) for basic & pressurized fluid conduits would fix this problem.  Right now I *have* to use Ender Fluid conduits, because even if I use multiple pressurized conduits, there's nothing to force the MFR machine to always output one fluid to one conduit and one fluid to the other - I can just wind up with TWO fluid conduits with no valid outputs.

**Comment by MatthiasMann** [comment]
You can right click a non ender fluid conduit witha  filled fluid container (eg a bucket) to lock the conduit into this type of fluid.

**Comment by isochronous** [comment]
Holy crap! I wish that had been ANYWHERE on the wiki pages I read

**Comment by isochronous** [comment]
Then I guess my request is that this information be added to the official wiki. I went to go add it myself but it looks like registration is disabled.

**Comment by wlhlm** [comment]
I will add it.
