### ISSUE TITLE
Incompatibility with Modular Powersuits

### ISSUE THREAD

**Issue by Zsashas** [SleepyTrousers/EnderIO#3136]
Tested with Modular Powersuits armor in a basic capacitor bank, the slots simply won't accept it.

**Comment by MatthiasMann** [comment]
Does the suit accept RF power or does it require EU?

**Comment by Zsashas** [comment]
It uses RF, last I checked.

**Comment by HenryLoenwind** [comment]
see linked ticket

**Comment by Badcholo** [comment]
The armor pulls power from any source in your inventory right?
I usually just place a cell in my inventory and remove batteries from my PA. 
The PA batteries just add weight anyways.

**Comment by Zsashas** [comment]
What do you mean by cell? I don't have Thermal anything so...
