### ISSUE TITLE
[Suggestion] Allow to use Metallurgy tools by default in Farming Stations

### ISSUE THREAD

**Issue by hron84** [SleepyTrousers/EnderIO#3139]
I know the config options, however Metallurgy has a dozen type of tools (one set for almost all metals), and I do not want to add them one-by-one to my config. Instead, it would be good if FarmingStations can accept them by default.

**Comment by HenryLoenwind** [comment]
We'd be happy to add those to the default config. If you'd provide an item list?

**Comment by hron84** [comment]
@HenryLoenwind Why not include everything that looks like an axe/hoe and provide a blacklist for banned items?

**Comment by hron84** [comment]
Also, I wonder if ThermalFoundation shears are supported

**Comment by HenryLoenwind** [comment]
We already do that. The problem are those tools that do not "look" like an axe or a hoe. Unless you wanted to suggest to utilize image recognition on the the icon? ;)

**Comment by hron84** [comment]
But.... Metallurgy axes are [look like an axe](https://github.com/TeamMetallurgy/Metallurgy4/blob/master/src/main/java/com/teammetallurgy/metallurgy/tools/Axe.java) because they're inheriting from `ItemAxe`.

**Comment by HenryLoenwind** [comment]
Then someone will have to investigate why https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java#L57 doesn't catch them.

(I'm short on time this week)

**Comment by hron84** [comment]
@HenryLoenwind now, it smells like a bug...

**Comment by hron84** [comment]
@CrazyPants thanks for solving this issue. Will it be ported back to 1.7.10 too?
