### ISSUE TITLE
 Capacitors increasing the amount of RF produced by Solar 2

### ISSUE THREAD

**Issue by RealKC** [SleepyTrousers/EnderIO#3140]
So, capacitors should increase the Amount of RF that is produced when you have Solar 2 on your Dark Helm in this order: Basic Capacitor makes that it will produce 128RF/t, Double-Layer 256RF/t and Octadic Capacitor 1024RF/t

**Comment by MatthiasMann** [comment]
This would then produce *much* more than a normal photo voltaic panel and that on a smaller area - doesn't sound like a balanced idea.

**Comment by RealKC** [comment]
Than we should be able to upgrade them too?

**Comment by RealKC** [comment]
Actually I remembered that the Advanced Solar Panel produces 4RF/t.. so, 12.8;  25.6 and 102.4?

**Comment by HenryLoenwind** [comment]
We now have a third tier of solar panel. It produces enough energy for a full set of Ender IO items, so I see no need for action here. When Ender IO is used together with other mods, it's the modpack creater's job to configure the mods to work well together, i.e. to set energy production and usage values into a comparable range. The solar upgrades can be configure that way.

So closing. Feel free to try me to convince to reopen, I'll still be getting notifications for comments here.
