### ISSUE TITLE
Nether Crash

### ISSUE THREAD

**Issue by GabrielGamer66** [SleepyTrousers/EnderIO#3142]
![b86349723838b4952a1685f0c94137c902072c3df3c0981d70 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11839986/12399261/08373bf8-be00-11e5-93dc-191d8cbd500b.jpg)

**Comment by tterrag1098** [comment]
Your entity IDs do not match between server and client. This is not an EnderIO bug.

**Comment by GabrielGamer66** [comment]
I exclude configs Ender IO server and EnderIO configs client too, but, the error continue
