### ISSUE TITLE
Strange Issue with Capacitor and Baubles Stuff in Botania

### ISSUE THREAD

**Issue by mindforger** [SleepyTrousers/EnderIO#3143]
please see https://github.com/Vazkii/Botania/issues/1757 for details and logs

ignore the closed state it just happened without festcraft so false positive

something odd is happening when opening the capacitor inventory 
botania bauble check is beeing fired from the entwork thread with an very odd error

**Comment by tterrag1098** [comment]
What is the status on this?

**Comment by HenryLoenwind** [comment]
Status is "waiting for Azanor". As of now, (and #3164 applied) I see nothing wrong in our implementation, it seems this is part of Baubles' not quite rock-solid implementation.

**Comment by mindforger** [comment]
Botania released 249 testing this evening if my crash persists
