### ISSUE TITLE
Feature Request: button for facades

### ISSUE THREAD

**Issue by Ezoteric** [SleepyTrousers/EnderIO#3146]
Hey is it possible to make a button (switch) on facades so it can act as redstone switch ?
prefer also a red to green icon with a normal color and light (like project red) 

thnx in advance :)

**Comment by HenryLoenwind** [comment]
You can simply place a vanilla button on a facade.

About the rest: Sorry, I don't understand what you want.

**Comment by Ezoteric** [comment]
The mod project red adds lights to MC, they also a have a button that emits light when active or pressed ON.

So my question is, can you add a button that makes the button glow (emit light) green when active (on) and red when deactivated (off) 

Now you might ask why add this when project red has them, well first off all that means i need to add another mod just for a button and besides that, project red is very laggy. people say the core is a lag source. and my fps drop drop from 50 to 10 just by having that mod in my modpack and starting a new world let alone when i use a bunch of their stuff :(

**Comment by HenryLoenwind** [comment]
Ok, that I understand. I'd like such a button myself, too.

**Comment by Ezoteric** [comment]
Yay :) that would be totally awesome so all machine setups are clean and nice lookin :)

**Comment by Greylocke** [comment]
If you're moving ahead with this, can I toss in the idea that you make a toggle-type button in addition to the vanilla momentary-on button? (push on / push off)

**Comment by Ezoteric** [comment]
Yeah that was the idea. Thnx for adding that info haha totally slipped my mind :o

**Comment by HenryLoenwind** [comment]
Um, yeah. A push button that lights up while you press it isn't really useful ;)

**Comment by Ezoteric** [comment]
Maybe for the compulsive ppl under us ;)

**Comment by tterrag1098** [comment]
#1097 is very similar to this. It being a facade is a logical extension of the idea.
