### ISSUE TITLE
Mekanism mj power accept?

### ISSUE THREAD

**Issue by Walki07** [SleepyTrousers/EnderIO#3147]
Hallo Guys 
Ist there a oppertunity that ender io accept mj from Mekanism, also it ist an only rf mod 
😊

**Comment by MatthiasMann** [comment]
MJ doesn't exist anymore.

**Comment by Walki07** [comment]
Sorry i mean kJ

**Comment by XFactHD** [comment]
If you have CoFHCore or CoFHLib in your pack, you can connect EnderIO machines to Mekanism cables. This is a measure (probably for safety) in Mekanism.

**Comment by MatthiasMann** [comment]
Or a bad implementation of the RF API - as there is no need to have either of these mods in your pack to use RF.

**Comment by HenryLoenwind** [comment]
Would be the second mod this week that on COFH instead of the RF API.

**Comment by XFactHD** [comment]
That's something only @aidancbrady can answer.
