### ISSUE TITLE
EnderIO/Flan's Mod player.func conflict

### ISSUE THREAD

**Issue by CanoLathra** [SleepyTrousers/EnderIO#3152]
<s>EnderIO and Flans Mod are both asking for player.func_71045_bC and equipped.func_77973_b simultaneously, but look for different instanceof variables (IConduitControl vs. ItemGun). This is somehow causing EnderIO to overwrite the crouch+scroll function within Flans', causing the ItemGun to attempt to change its EnderIO Yeta Wrench mode, which it obviously doesn't have, instead of it's intended crouch+scroll function of initiating dual-wield.

<s>To replicate bug:

<s>Install Forge 10.13.4.xxxx
<s>Install EnderIO
<s>Install Flans
<s>Run and close MineCraft
<s>Add at least one gun pack (and all dependency packs) to 'flan' folder
<s>Equip any pistol to two (2) hotbar slots
<s>Select one pistol as active hotbar slot
<s>Crouch+Scroll
<s>Observe
<s>Close MineCraft
<s>Remove EnderIO
<s>Run MineCraft
<s>Select one pistol as active hotbar slot
<s>Crouch+Scroll
<s>Observe

<s>Thank you for your time. If this cannot be fixed on your end, please let me know.</s>

EDIT: Found config option that can fix this bug. If it could become default-upon-detect it would be appreciated.

**Comment by HenryLoenwind** [comment]
If Shift+Scroll does anything when there is no Yeta-Wrench in the player's hand, that indeed would be a bug. So if you'd be so nice to describe what actually happens, so I don't have to hunt down Flan's, setup a new Minecraft installation, find out how those pistols work, and test it out just to see if there is a bug?

**Comment by CanoLathra** [comment]
It isn't just Shift+Scroll, as I have crouch remapped to LCONTROL and it still happens. Simply put, when I crouch+scroll with no Flans Mod single-handed guns or  Yeta Wrenches in the hotbar, the hotbar scrolls as normal. When I have a Yeta Wrench in the hotbar, it scrolls as normal until I reach the wrench, then scrolls the wrench. When I have a Flans single-handed gun in my hotbar, it scrolls as normal until I reach the gun, then stops, with no visible action. When I changed the Yeta Wrench mode in the config file, crouch+scroll works as normal, scrolling the hotbar until reaching a Flans Single-handed gun, then entering Dual-Wield mode.
