### ISSUE TITLE
Config useSneakMouseWheelYetaWrench ignored by Ender IO

### ISSUE THREAD

**Issue by Psithief** [SleepyTrousers/EnderIO#3154]
I changed my EnderIO.cfg to prevent the shift and the mouse wheel from changing the conduit mode, but Ender IO is ignoring the setting.

```txt
# If true, shift-mouse wheel will change the conduit display mode when the YetaWrench is equipped.
B:useSneakMouseWheelYetaWrench=false
```

![2016-01-23_23 14 08](https://cloud.githubusercontent.com/assets/1124846/12530881/db07f8e4-c227-11e5-8b68-56fcb1b7eddb.png)

Are there any known conflicts, or maybe something broke in e67338531c113825263161f7e9c03d90d5d53037?

---

## Versions

* Ender IO 1.7.10-2.3.0.423_beta
* Forge 10.13.4.1558

**Comment by HenryLoenwind** [comment]
```
    if(Config.useSneakMouseWheelYetaWrench) {
      ToolTickHandler th = new ToolTickHandler();
      MinecraftForge.EVENT_BUS.register(th);
      FMLCommonHandler.instance().bus().register(th);
    }
```

That code is about as straight-forward as it gets. I don't really see a way for it misbehaving...

Did you restart the game after changing the setting?

**Comment by Psithief** [comment]
Many times.

**Comment by Psithief** [comment]
Is this perhaps a problem caused by that fancy configuration screen?

**Comment by Psithief** [comment]
I certainly restarted the game many times, is there anything else I can try?

**Comment by Psithief** [comment]
I found the problem @ [/src/main/java/crazypants/enderio/config/Config.java#L726-L729](https://github.com/SleepyTrousers/EnderIO/blob/fa18bf0636ec3ed56b3547727685f66fe1914d14/src/main/java/crazypants/enderio/config/Config.java#L726-L729)

This behaviour is intentional? But there's a keyboard key for it!

**Comment by HenryLoenwind** [comment]
Thx, that was well hidden. I think the key came later.

**Comment by Psithief** [comment]
:+1:
