### ISSUE TITLE
Farming station and Pam's Harvest Craft seed-n-crops

### ISSUE THREAD

**Issue by adamsonich** [SleepyTrousers/EnderIO#3155]
I am using EnderIO-1.7.10-2.3.0.417_beta
I have problems with mod Pam' Harvest Craft: if i place crops and seeds on them, farming station broke crops and place seeds on dirt. 

because of this problem i have problem with sugarcane seeds (from pam harvest craft) on crops with sand under them. farming station harvest it, breake crops and don't replant them.

**Comment by MatthiasMann** [comment]
Try build 423 and see if it is fixed in that version.

**Comment by HenryLoenwind** [comment]
"crops"? That sounds like AgriCraft to me. The normal Framing Station does not support AgriCraft crops, for that you need the "AgriCraft Farming Station". It is part of Ender IO Addons, http://minecraft.curseforge.com/projects/ender-io-addons

**Comment by adamsonich** [comment]
Yep, i am using AgriCraft. Too bad that for me.
I dont see 423 version http://minecraft.curseforge.com/projects/ender-io/files

**Comment by wlhlm** [comment]
That version wasn't published to CF. Download it here: http://ci.tterrag.com/job/EnderIO/423/

**Comment by HenryLoenwind** [comment]
Or use 422. There have been no Farming Station related changes for some time.

**Comment by adamsonich** [comment]
will it work with crops?

**Comment by HenryLoenwind** [comment]
No, the normal Framing Station will not, and most probably will never, work with crops. The mechanics are just too different for crops, that's why there is a second machine or that.
