### ISSUE TITLE
farming station and thaumic tinkerer infused seeds

### ISSUE THREAD

**Issue by adamsonich** [SleepyTrousers/EnderIO#3156]
I am using EnderIO-1.7.10-2.3.0.417_beta.
Farming station takes infused seeds and place minecraft wheat seeds.

**Comment by HenryLoenwind** [comment]
Let me guess, those "infused seeds" are normal seeds with some NBT data added?

**Comment by adamsonich** [comment]
infused seeds is seeds crafted in thaum altar and has diff ID

**Comment by HenryLoenwind** [comment]
Ok, found them. The Farming Station is working correctly, it asks the seeds which plant to create and they answer "wheat":

https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/blob/1.7-final/src/main/java/thaumic/tinkerer/common/item/ItemInfusedSeeds.java#L44

**Comment by nekosune** [comment]
Sorry about this, it will be fixed

**Comment by HenryLoenwind** [comment]
No need to be sorry.

We have a full moon, which means we're getting all sorts of tickets and are a bit on the edge ourselves... ;/

**Comment by adamsonich** [comment]
Thank U very very

**Comment by nekosune** [comment]
is it possible to set a seed as not placable by the farming station? As this seed does weird things to the block underneath it.

**Comment by HenryLoenwind** [comment]
This has been answered on IRC, but on the slim chance someone may find this in the future:

No, there is no blacklist. We might add one in the future, but prefer to add custom planters instead. One can also include a custom planter with their mod. Here's an example: https://github.com/wyldmods/KitchenCraft/blob/master/Foods/src/main/java/org/wyldmods/kitchencraft/foods/common/compat/EnderIOCompat.java

**Comment by nekosune** [comment]
I was there on IRC, saw that and alredy implementing my own thankyou!
