### ISSUE TITLE
ClassCastException placing conduit near GC arc lamp

### ISSUE THREAD

**Issue by plaguewolf** [SleepyTrousers/EnderIO#3157]
relevant logs: http://pastebin.com/qSGah5N6

enderIO 2.3.0.421 beta
galacticraft 3.0.12.375

game locked up then crashed, when placing a teir 1 conduit, on the ceiling, near  a GC arc lamp.

also posted on https://github.com/micdoodle8/Galacticraft/issues/2042

**Comment by HenryLoenwind** [comment]
link #2835

**Comment by HenryLoenwind** [comment]
Fixed in Galacticraft.

Hint for others: Check if invalidate() calls super().
