### ISSUE TITLE
id conflicts

### ISSUE THREAD

**Issue by colt05** [SleepyTrousers/EnderIO#3159]
0.o Ender IO ids conflict with the Ender IO mod ids already set and also OpenBlocks
```
Caught exception from OpenBlocks
java.lang.IllegalStateException: OpenBlocks tried to register a block for ID: 424 but it was in use
```
and Magical Crops
```
431: enderio.blockHyperCube from EnderIO - BlockOreEssenceNether from magicalcrops
```

**Comment by HenryLoenwind** [comment]
Block IDs? Sorry mate, we no longer support the old versions for Minecraft 1.6/1.5.

**Comment by colt05** [comment]
oh right *facepalm*

**Comment by colt05** [comment]
i forgot

**Comment by HenryLoenwind** [comment]
However, I am quite sure there's a config file for the block IDs. So you have to find free IDs for all the mods. That's how it worked in those ancient times ;)
