### ISSUE TITLE
[Enhancement] Tinkers Construct Inventory Compat.

### ISSUE THREAD

**Issue by vsilvar** [SleepyTrousers/EnderIO#3162]
The Soulbound enchantment isn't working with items in the Tinkers Construct inventory.
Specifically the Knapsack.

EnderIO: 2.3.0.422_beta
Tinkers Construct: 1.8.8
Forge: 1.7.10-10.13.4.1614

**Comment by mindforger** [comment]
the knapsack isn't designed to keep items on death of when removed from the slot if i remember correct?! when you die or remove it, it adds all your stored items to the drop list and drops it to the ground .. so the enchantment won't probably make sense at all !?

**Comment by vsilvar** [comment]
Oh, yeah, you're right.
It would still be useful for some of the other items though.
