### ISSUE TITLE
Conduit facade wrong rendering with Chisel blocks

### ISSUE THREAD

**Issue by Esctogrillo** [SleepyTrousers/EnderIO#3165]
By using Polished Stone Brick on conduits I get this wrong texture:

![2016-01-24_22 25 09](https://cloud.githubusercontent.com/assets/14919996/12644625/4a5ef950-c5ab-11e5-9e2c-dc278d70521e.png)
![2016-01-24_22 24 56](https://cloud.githubusercontent.com/assets/14919996/12644626/4d64f3ca-c5ab-11e5-96c6-63de9ff46261.png)

* Using EnderIO-1.7.10-2.3.0.422_beta
* And Chisel2-2.5.0.43

**Comment by tterrag1098** [comment]
Polished Stone Brick is not from Chisel, it is from Tcon. That said, it works fine here http://puu.sh/nnX69.jpg
