### ISSUE TITLE
Suggestion - New ME Conduit type or new funtionality

### ISSUE THREAD

**Issue by UberAffe** [SleepyTrousers/EnderIO#3166]
First, Thank you for ME Conduits, so much more convenient than AE2 cables.

On the topic of convenience I keep finding my network cabling sprawling out farther and farther as my base grows, and things start getting really messy as I try to keep it compact. It would be nice if the ME conduits had a color code option on their connections to identify which network they belong to. This would allow multiple networks to run through the block space.

Obvious balance issue, this basically invalidates the (ME) P2P tunnel.

**Comment by tterrag1098** [comment]
Yeah, I decided against doing color-capable ME conduits as it completely ruins the gameplay that AE2 has attempted to create. Currently ME conduits add no benefit other than being allowed in conduit bundles, and I plan to keep it that way.

**Comment by UberAffe** [comment]
That took waaay less time for a response than I expect. I figured as much but I thought I'd bring it up just in case.

**Comment by tterrag1098** [comment]
We have issues post in our IRC channel, and I happened to be looking at the channel at the time. Or maybe I'm some freak who constantly refreshes github notifications. Whatever you want to believe ;)
