### ISSUE TITLE
Crash EnderIO-1.7.10-2.3.0.422_beta

### ISSUE THREAD

**Issue by kostay99** [SleepyTrousers/EnderIO#3169]
Hello. When you open the Capacitor Bank crash the client, but not always. http://pastebin.com/0FJxPup8

**Comment by HenryLoenwind** [comment]
see #3143, Vazkii/Botania#1757

**Comment by HenryLoenwind** [comment]
Just one thing, can you double check that the game does not crash when you access the Baubles inventory but does so when accessing the Capacitor Bank?

**Comment by mindforger** [comment]
@HenryLoenwind i just read this again, how could this slip my notifications ... it's only crashing when opening the capacitor, never in my baubles inventory

**Comment by HenryLoenwind** [comment]
thx @mindforger, I'll note it in the upstream ticket
