### ISSUE TITLE
Zombie Generator permanently stops when full

### ISSUE THREAD

**Issue by CyricV** [SleepyTrousers/EnderIO#3170]
I'm running into what I believe is an error with the Zombie Generator and I'd like to know if there is a bug I should report or if I'm messing things up myself.

The Generator works fine until it fills up both it's stored energy and Nutrient Distillation. At this point it stops generating energy and will not start again. The 100K RF buffer can be emptied out just fine, but the Generator will sit with 2000/2000 mB of Nutrient Distillation and 0/100000 RF doing nothing. As long as the generator never maxes out both Nutrient Distillation and RF it's fine, but once that happens it becomes stuck and must be broken and replaced.

Ender IO 2.3.0.422
EnderCore 0.2.0.31

**Comment by HenryLoenwind** [comment]
Can you please check that you didn't set a redstone mode on the generator?

**Comment by CyricV** [comment]
Confirmed, I've tested with all different redstone modes on independent generators and they all have the same issue. I'm going to do a quick test with only Ender IO installed to see if the issue is related to other mods.

**Comment by HenryLoenwind** [comment]
Thx for doing so, in my dev env (with minimal mods...) it doesn't happen.

**Comment by CyricV** [comment]
OK, I think I've figured it out, part of the trouble I had testing was a non default config following me around between Minecraft instances, but discovering that actually helped me sort the issue.

It seems that when both the RF and Distillation are maxed on a Zombie Generator it goes into a kind of standby, and to wake it up again you need to lower the stored RF by a certain amount. For the default 80 RF/T happens when you drop it to about 90K RF in the buffer. However, if you set the generation rate higher that also seems to increase the amount you need to pull to wake it back up. At 400 RF/T it must be dropped to about 20K before it wakes up and with 600 RF/T it cannot be woken back up even if completely drained. I'm not sure if this is intended behavior or just a weird artifact that no one has found or cared to mention since I seem to be the only person who likes the Zombie Generator anyways. I'm going to see what I can set the max RF/T to before it stops being able to function.

**Comment by CyricV** [comment]
Seems like 499 RF/T is the cutoff point, so at 500 RF/T the generator will not wake up after going into standby.

**Comment by HenryLoenwind** [comment]
It says:

```
    //once full, don't start again until we have drained 10 seconds worth of power to prevent
    //flickering on and off constantly when powering a machine that draws less than this produces
```

Yeah, that'd be your 500*20*10 >= 10000

**Comment by CyricV** [comment]
Is this technically a bug then? That comment snippet sounds like a pretty good little feature. I feel like this is more of a usability issue. Should we leave this open or closed, and should we remove the un-reproducible tag?

How difficult might it be to add a config option to set the buffer capacity of the Zombie Generator and a note in the config explaining how this works?

**Comment by HenryLoenwind** [comment]
Oops, I forgot to re-tag this. Happens all the time when an issue gets so long that the tags scroll out of view. It would be a bug if we generally had validity checks on config values.

The PR above contains code that prevents a config value that is so large that the gen would stall from taking. It also has a new config setting to tweak those 10 seconds. So to set higher values than 500, you'd need to reduce that time also.

The buffer size is taken from the capacitor used. It's one of the few machines that actually do this, and as we want to change all machines to take those values from the capacitors to allow for more than 3 hardcoded capacitors, I don't want to change this.

**Comment by CyricV** [comment]
I've updated to Ender IO 2.3.0.424_beta and the Combustion Generator now seems to be exhibiting this behavior as well. If the internal buffer fills, the machine goes to sleep and does not wake up. Is there going to be a GeneratorResumeTime config option for them? I haven't tested it yet, but I assume the Photovoltaic Cells and Stirling Generator have this feature incorporated too?

**Comment by CyricV** [comment]
Closing issue and moving to #3219.
