### ISSUE TITLE
Control click in inventory panel picks up a full stack

### ISSUE THREAD

**Issue by r0rs** [SleepyTrousers/EnderIO#3173]
I'm using EnderIO-1.7.10-2.3.0.422_beta. In the inventory panel when I try to control click to pick up a single item from a stack it takes the full stack. This wouldn't be a big deal except I can't use the return area to send some items back because automated processing fills up the storage drawers nearly instantly.

I'm not sure if this a bug or intentional but control clicking works everywhere else I've tried.

**Comment by wlhlm** [comment]
Similar issue: #2997

**Comment by HenryLoenwind** [comment]
Unrelated.

This has do do with the fact that the inventory area isn't really slots but only looks that way. It basically is a big picture that will retrieve items when you click into it and attach them to your mouse cursor. So every mouse action has to be coded explicitly, and the Control-Click was missed.

(Assuming Control-Click is vanilla. It's not an action I was aware of.)

**Comment by tterrag1098** [comment]
I don't think it's anything. However, it is how AE2 behaves. So maybe we should consider it.
