### ISSUE TITLE
dimensional transceiver don´t send rf to second 

### ISSUE THREAD

**Issue by skulldrago** [SleepyTrousers/EnderIO#3174]
Hi i´m using your beta 422 build.
I have the problem that the first one which should send the rf fills his buffer but the send buffer is empty.
I have made a channel and configured the one to send and the second to receive.
The second have no violet color in it. I tryed to fill it manually with rf so it becomes violet but no transfer.

I tested it in sp and at server

**Comment by tterrag1098** [comment]
Working fine here. Do you have some screenshots of the issue?
