### ISSUE TITLE
Power Monitor's Engine Control not working after map load

### ISSUE THREAD

**Issue by Benie76** [SleepyTrousers/EnderIO#3175]
Mod Pack: FTB presents Direwolf20 (v1.10.0)

So I have a Power Monitor connected to the side of a Tier 2 Capacitor Bank (which can hold 10 million RF). I got the Power Monitor set to control the Steam Dynamos (there are 5 of them) using EnderIO conduits.
Current settings for the Engine Control, is to emit signal when reaching 10% power, and off when reaching 90% power of the Capacitor Bank.

It works flawless; does exactly what I need it to do. But the problem lies on having to quit the game completely and load it again (through FTB). It seems to "forget" it's supposed to be working; like chunks aren't being loaded (when I have a Chunk Loader that is loading chunks well within range of it).
The way I've been fixing it, is removing blocks that are sitting ontop of the dynamos. This turns them off and makes the Power Monitor work correctly.

Yet if I leave the blocks not being there, then close out completely and rerun the game, the problem will happen again. I place the blocks back on the Dynamos, and they turn off. There's some block updating bug going on. I guess anyway.

Can someone please help with this?

**Comment by mindforger** [comment]
which "chunk loader" in particular? try with world anchors or MFR Chunkloaders ... i would guess you are using chickenchunks ... they behave oddly sometimes on world load

**Comment by HenryLoenwind** [comment]
could you post a screenshot of your setup? thx.

**Comment by Benie76** [comment]
@mindforger It's ChickenChunks, yes. If you could recommend something different that won't behave oddly in the pack I'm using, I'll consider it.

@HenryLoenwind Stand by.

**Comment by mindforger** [comment]
Chunkloaders from MineFactoryReloaded, Worldanchors from Railcraft come to my mind this instant ... you can config their resource cost to 0 if required

just as hint, quarrys do only need their machine block chunkloaded (permanently).. and probably the powersource ... the rest of the quarry area is self loading

**Comment by Benie76** [comment]
Alright, I switched out the ChickenChunks loader with the World Anchor from Railcraft. I also disabled the requirement for Ender Pearls. Loaded up the game, and the Power Monitor _seems_ to be working by turning off the Dynamos and not waste fuel.
I'm going to try to fill up the area, quit completely and reload again and see if the problem comes back.

**Comment by HenryLoenwind** [comment]
Ok, I'll close this then.

The reason I wanted the screenshot was to see what was not working, the monitor or the propagation of the redstone signal from the redstone conduits (or possibly other means) to the generators.

BTW: The connection-by-touch between capacitor bank and power monitor only powers the monitor. The data the monitor displays and acts on comes from the conduit network it is connected to.
