### ISSUE TITLE
[Feature Request] Insulated Redstone Conduit Upgrades

### ISSUE THREAD

**Issue by sinspawn1024** [SleepyTrousers/EnderIO#3177]
I'd like to request a feature for the (Insulated) Redstone Conduit. Basically, when it's connected to a block, it would be nice if there was a slot where different redstone devices - like comparators - could be placed. That way, when connected to blocks that don't necessarily produce a redstone signal themselves could be used to control things in the Ender IO network.

**Comment by ShadowDrakken** [comment]
Damn, was just about to post the same request. That'll teach me not to use search in the future ;)

I'm guessing the closed with no comment was just a flat "nope"? :(

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
we now have a standard text text ^
