### ISSUE TITLE
Inventory tooltips for conduits do not reflect altered config values.

### ISSUE THREAD

**Issue by Karmacopper** [SleepyTrousers/EnderIO#3178]
If you change a conduit default in the config file this value is not reflected in the toioltip when hovering the item in NEI/inventories. It does however reflect the config value when moused over in the world.

Version is EnderIO-1.7.10-2.3.0.421_beta

**Comment by tterrag1098** [comment]
What configs? What conduits? I just tested them and they all work fine.

**Comment by Karmacopper** [comment]
I'm playing FTB Infinity on  a private server in my home. EIO version is: EnderIO-1.7.10-2.3.0.421_beta
We haver the energy conduits deliver more than default config energy.
![2016-02-28_11 02 07](https://cloud.githubusercontent.com/assets/7628623/13378829/0d7e28a8-de0b-11e5-9bb7-20530ebd5dad.png)
![2016-02-28_11 02 20](https://cloud.githubusercontent.com/assets/7628623/13378830/0d833122-de0b-11e5-8075-7d57027d20b6.png)

As you can see, the NEI tooltip shows the deafult whereas the conduit in world shows the actual ammount set in the config file.

**Comment by tterrag1098** [comment]
Have you changed this config value on both sides, or only the server? The tooltip reads the clientside config, there's nothing we can do if they are different.

**Comment by Karmacopper** [comment]
No, the configs were not changed in the clients. SO I guess that explains it. Thanks.
