### ISSUE TITLE
No idea what this is, yet. ["NoClass" Crash]

### ISSUE THREAD

**Issue by Fortist** [SleepyTrousers/EnderIO#3179]
http://pastebin.com/PTfuca0t
Finally decided to install this after installing a bunch of other mods for the past week, and I get this crash. I have a feeling Im missing something but I dont know or remember what, as this worked fine on my other instances, which probably means it's either a new mod conflicting or a config thing.
Gonna troubleshoot a bit.

Now that I think about it, it could be a forge thing.

**Comment by HenryLoenwind** [comment]
Could you have a look into your logfile to see if the stacktrace is longer there? The part that is not following "Caused by: java.lang.ArrayIndexOutOfBoundsException" would be very interesting...

**Comment by Fortist** [comment]
http://pastebin.com/MnZ9KiC5
Im not exactly sure what Im looking for, I did remove all mods except this and Thermal E/F/D, and still got the crash, but I just realized I didnt try one more configuration.

**Comment by Fortist** [comment]
Interesting development, to say the least.
Okay, so I downgraded to the last stable non beta version, It worked.
I then realized that I still had liteloader, so I removed that, but added all my mods + the beta .422
It worked
I took it a step further and just re-enabled Liteloader. It worked.

However, the .422 beta wasnt the one I just downloaded from curse, but an older version of the same file I had from my older instance. (only a month or two old)

So, I have a three theories, 
first is that the older version of .422 is different from this latest version, which I'd doubt. 
I had to load up some kind of config file for it to continue loading.
Or because I had endercore in the 1.7.10 folder instead of the main mod folder (I like keeping "Core" like mods in there)

As, everything is exactly the same as to when I started trying to load the first time.
Newest forge, Liteloader, all the mods I had already installed. The only thing different is moving endercore and the "old" version.

**Comment by tterrag1098** [comment]
It looks like your version of the EnderIO jar is corrupted. Did you tamper with it in any way?

```
[17:34:53] [Client thread/DEBUG] [FML/]: Identified a mod of type Lcpw/mods/fml/common/Mod; (crazypants.enderio.EnderIO) - loading
[17:34:53] [Client thread/TRACE] [EnderIO/]: Parsed dependency info : [Forge@[10.13.4.1448,), endercore@[1.7.10-0.2.0.31_beta,)] [Forge@[10.13.4.1448,), endercore@[1.7.10-0.2.0.31_beta,), MineFactoryReloaded, Waila@[1.5.10,), Thaumcraft, appliedenergistics2@[rv2-beta-8,)] []
[17:34:53] [Client thread/ERROR] [FML/]: Unable to read a class file correctly
java.io.EOFException: Unexpected end of ZLIB input stream
```

**Comment by Fortist** [comment]
I dont remember If I did, but I dont think so. Maybe I messed up the download?

**Comment by mindforger** [comment]
there is liteloader present and you are using multimc ... try maybe after removing liteloader and finally again with just forge
i bet it's liteloader :P

**Comment by HenryLoenwind** [comment]
Yes, "Unexpected end of ZLIB input stream" usually means the download stopped before the file was transferred completely.

**Comment by Fortist** [comment]
Mind, if you actually read what I wrote it wasnt liteloader.

And Henry, I think that might have been it, but I downloaded it a week ago so I dont really know if I can confirm.
Anyway, no problems anymore. Thanks for trying.

**Comment by tterrag1098** [comment]
@Fortist turns out my server's HDD was filled up with jenkins logs thanks to a bug. I've resolved the issue so downloads should work fine now.
