### ISSUE TITLE
Enchanter recipe for holding doesn't work.

### ISSUE THREAD

**Issue by technolem** [SleepyTrousers/EnderIO#3181]
The Holding enchant in thermal expansion has 4 levels, so it requires 4 strongboxes, right? Unfortunately strongboxes don't stack, so you can't get past level 1. You could just change it to "Glass" which is hardened glass, the upgrade item for reinforced strongboxes and such.

**Comment by tterrag1098** [comment]
They don't stack? Even without any items in them? That seems pointless. Well, I'll look into changing that recipe to something better.

**Comment by technolem** [comment]
You can't even craft more than one at a time. Same goes for satchels.

**Comment by technolem** [comment]
That close button.... Right next to the comment one. Bad location in my opinion.

**Comment by HenryLoenwind** [comment]
It's the same as with the other enchantments. Once you go over a certain level, you need to enchant books and combine them.

**Comment by technolem** [comment]
All of the other enchantments work just fine? Are there any in particular that don't? I only know of this one.

**Comment by HenryLoenwind** [comment]
I'm too lazy to look up the max levels of those enchants, but you cannot get Sharpness VI, Smite VI or any of the Protections V because of the stacksize limit.

**Comment by technolem** [comment]
...um. the limits for sharpness and attack enchants are V, and protection enchantmens are IV. Which you can get. They are exactly set up to be able to just get them. If you try to go higher the anvil will actually downgrade your enchantment book to these caps, unless you're in creative.

**Comment by HenryLoenwind** [comment]
ok, I found what I remembered: #2982

Yes, I noticed the magic words in it.

**Comment by technolem** [comment]
Ah, yes, I see. Well, I'm just fine with the normal limits here, you just can't reach them is all.
