### ISSUE TITLE
Minecraft fence gate can't be used as a unit for painting

### ISSUE THREAD

**Issue by dimitriy0810** [SleepyTrousers/EnderIO#3182]
When I put fence gate in the slot for paiting, nothing happens and the fence gate even doesn't put in this slot. With a fence that does not happen. Versions: EnderIO-1.7.10-2.3.0.423_beta, EnderCore-1.7.10-0.2.0.31_beta, Forge-1.7.10-10.13.4.1614. List of mods: https://gyazo.com/a56a4b41e2795639f2a04bdcce753303. Screenshots: fence https://gyazo.com/944b995a3260fbe2f02ec66552b620bb, fence gate https://gyazo.com/12bf9a9b192d5e80d0603fe7f9cfd986. There is MalisisDoors in the modpack

**Comment by chrisk123999** [comment]
MalisisDoors changes fence gates making it no longer work.

**Comment by dimitriy0810** [comment]
How I can then paint the fence gate? With MalisisDoors and EnderIO

**Comment by chrisk123999** [comment]
You can't.  It's a mod incompatibility.

**Comment by tterrag1098** [comment]
Well, MalisisDoors could add compatibility with EnderIO. It's pretty easy really. @Ordinastie

**Comment by dimitriy0810** [comment]
Are you make a new version, which will compatible with MalisisDoors?

**Comment by tterrag1098** [comment]
I can't do anything. It's up to @Ordinastie to implement it on their side.
