### ISSUE TITLE
Powered Spawner consumes RF but won't spawn Cows

### ISSUE THREAD

**Issue by Sheldor5** [SleepyTrousers/EnderIO#3185]
I have a 9x9 area with a powered spawner (cow) in the center and as soon as there are ~9 cows in this fenced area the spawner will continue consuming energy but won't spawn the cows.

http://imgur.com/WNr33OA

The other blocks are from MineFactory Reloaded (1 Auto-Spawner aside the powered spawner, 1 Grinder, 4 Sewer, Tesseract beneath the powered spawner).

**Comment by MatthiasMann** [comment]
Yes, there is a limit on the number of nearby entities which stops the spawning

**Comment by HenryLoenwind** [comment]
Exactly. Entity limit applies, it can be configured in the config file as "poweredSpawnerMaxNearbyEntities". Some additional checks from vanilla may run, too. They can be disabled with "poweredSpawnerUseVanillaSpawChecks" (sic!).

**Comment by GuntherDW** [comment]
Is there a reason it's kept as "SpawChecks" and not fixed to "Spaw**n**Checks"?

**Comment by Sheldor5** [comment]
This limitation should be mentioned in the wiki.
