### ISSUE TITLE
Farming station crash with vanilla seeds

### ISSUE THREAD

**Issue by leagris** [SleepyTrousers/EnderIO#3186]
Farming station has been filled with vanilla minecraft seeds, but at some point it reached area where it was handled as infused seeds from ThaumicTinkerer

Some bad interaction occurs with ThaumicTinkerer. Bug report for ThaumicTinkerer here: https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/833

Crash report: https://gist.github.com/leagris/d0c768eff1ecde0279a9

**Comment by nekosune** [comment]
Latest Commit should fix

**Comment by HenryLoenwind** [comment]
see Thaumic-Tinkerer/ThaumicTinkerer#833
