### ISSUE TITLE
Can't anvil potion of swiftness onto dark leggings

### ISSUE THREAD

**Issue by isochronous** [SleepyTrousers/EnderIO#3187]
Using:
Ender IO v2.3.0.422
Ender Core v0.2.0.31
Forge 10.13.4.1614

When I try to add a potion of swiftness to my empowered dark leggings, I just get the red X - no "you need more levels" text or anything.  It's a vanilla potion of swiftness I brewed in a vanilla brewing stand.  I also tried spawning one via NEI with the same results.  I've tried doing it at all levels of empowerment (I, II, III, IV), and in both the dark steel anvil and the regular anvil.

Here's a screenshot showing the exact situation. The potion I'm hovering over is the exact same as the potion in the anvil.
![Screenshot](http://i.imgur.com/rxhDGOb.png)

**Comment by MatthiasMann** [comment]
Sometimes there are 2 potions with the same name but different meta data (the number after the colon). Typically the ones which do not work are these found in dungeon loot - no idea why.

**Comment by isochronous** [comment]
Well, like I said, I brewed those myself, so if I happen to come across one in dungeon loot I'll try that and report back.

**Comment by isochronous** [comment]
Just figured it out - it has to be the 3 minute potion of swiftness (awkward + sugar). Maybe something to add to the documentation, but not a bug.

**Comment by totte1015** [comment]
> Just figured it out - it has to be the 3 minute potion of swiftness (awkward + sugar). Maybe something to add to the documentation, but not a bug.

Nope, this is wrong.

Just tried it now and it doesnt work

**Comment by tyler489** [comment]
did u brew the potion yourself?

**Comment by isochronous** [comment]
It definitely works with some variant of the potion, but it's been a long
time since I did this, and don't remember which variant worked.

**Comment by HenryLoenwind** [comment]
Yes, this is a known issue; first potions cheated in from NEI don't work as the have different data than brewed ones, second all variants of the potion have the same name (blame Mojang...) so you have to look at the NEI recipe to see which one to use. (We had NEI recipes for the upgrades, didn't we?)

**Comment by klebann** [comment]
For me it worked with 8:00 potion
3:00 dosn't work
