### ISSUE TITLE
Custom Grinding Balls Not Using Configured Stats

### ISSUE THREAD

**Issue by CyricV** [SleepyTrousers/EnderIO#3188]
Upon adding the following code to the SAG Mill config:

```
<SAGMillRecipes>
    <grindingBalls>
        <grindingBall id="VoidMetalNug" grindingMultiplier="1.5" chanceMultiplier="2.0" powerMultiplier="0.4" durationRF="16000" >
            <itemStack oreDictionary="nuggetVoid" />
        </grindingBall>
    </grindingBalls>
</SAGMillRecipes>
```

Void Metal Nuggets appear in game as a viable grinding ball and display the appropriate percentages (150 200 60) but do not decay inside the SAG Mill (one is consumed and remains at 100%) and output results are comparable to no grinding ball being present (based on 10*64 Iron Ore sample size). Also there is no change in power consumption between a SAG Mill using Void Metal Nuggets and one using no grinding ball.

**Comment by tterrag1098** [comment]
Is this on a server?

**Comment by CyricV** [comment]
Single player. I can test on a server tomorrow, however.

**Comment by CyricV** [comment]
Confirmed in single player with only Ender IO and Thaumcraft.

Ender IO 2.3.0.424_beta
Ender Core 0.2.0.31_beta
Thaumcraft 4.2.3.5

Config Used:
`<SAGMillRecipes>
    <grindingBalls>
        <grindingBall id="DarkSteelBall" remove="true" />
        <grindingBall id="DarkSteelBallTellura" grindingMultiplier="1.3" chanceMultiplier="1.5" powerMultiplier="0.7" durationRF="100000" >
            <itemStack oreDictionary="itemDarkGrindingBall" />
        </grindingBall>
        <grindingBall id="VoidMetalNug" grindingMultiplier="1.5" chanceMultiplier="2.0" powerMultiplier="0.4" durationRF="16000" >
            <itemStack oreDictionary="nuggetVoid" />
        </grindingBall>
    </grindingBalls>
</SAGMillRecipes>`

Ball-less acts as Default (as it should)
Flint acts as Default (as it should)
Dark Steel Ball acts as Default (Incorrect behavior)
Void Nugget acts as Ball-less (Incorrect behavior)

**Comment by CyricV** [comment]
I notice this still has the waiting for feedback tag, is there anything more I can do to test this for you?

**Comment by HenryLoenwind** [comment]
got lost between not having enough time and doing the 1.8.9 upgrade...
