### ISSUE TITLE
[enhancement] Travel Anchor Expansion

### ISSUE THREAD

**Issue by Leasara** [SleepyTrousers/EnderIO#3189]
This idea is two-fold

First, with all the mods that add some kind of speed enhancement standing on a Travel Anchor can get a bit fiddly, so I'd love to be able to expand it as a multi block to a 3x3 pad centered on the Travel Anchor.

Second, It might be handy to make Empowered Anchors that would let you travel further, taking RF from armor or the like.

**Comment by MatthiasMann** [comment]
You could use the teleporter pad - hich is a 3x3 multi block.

**Comment by Leasara** [comment]
Thanks!  I looked at it, but it's rather expensive just to traverse the six 20-30 block jumps I have around my base.
