### ISSUE TITLE
Minor "bug" with creative capacitors in inventory.

### ISSUE THREAD

**Issue by CyricV** [SleepyTrousers/EnderIO#3193]
Wireless Chargers will attempt to charge creative capacitors in players' inventories, causing them to become power black holes. I know this is technically correct behavior, but it caused me quite a bit of confusion. I would love to see this fixed if there is an easy solution, but it's a very minor and has little impact outside of a few weird edge cases.

**Comment by MatthiasMann** [comment]
well - see it as a way to check if your wireless charger is working :)

**Comment by CyricV** [comment]
It a feature!

**Comment by mindforger** [comment]
did you guys ever middle mouse click a creative cap bank? the one i got from middle cklicking was always empty then O_o

**Comment by HenryLoenwind** [comment]
yes, that's a known bug/feature. Bug because getting an empty creative bank makes no sense, feature because there was some mod interaction that allowed people to get creative banks in survival that way. That might actually a thing of the (distant) past.

**Comment by mindforger** [comment]
well i noticed as i was trolling around some friends XD after i read this issue

**Comment by tterrag1098** [comment]
073a1fd020ebcf76d822679ebb0048f2d0cf47a0

**Comment by CyricV** [comment]
Still getting used to using gethub, but I believe tterrag1089 just blocked the Creative Cap Bank from being able to draw from Wireless Chargers. This issue could also be changed to a feature request for adding a UI and blacklisting ability to the Wireless Charger.
