### ISSUE TITLE
Maybe a GUI bug with Inventory Panel and NEI

### ISSUE THREAD

**Issue by Andre--D** [SleepyTrousers/EnderIO#3195]
I am playing in 1280x1024 with Minecraft GUI Scale Large.
Never had a problem. Only in the Inventory Panel i can´t see the NEI items. 

minecraft 1.7.10 EnderIO-1.7.10-2.3.0.422_beta   EnderCore-1.7.10-0.2.0.31_beta
Forge 10.13.4.1558 CodeChickenCore-1.7.10-1.0.7.47    NotEnoughItems-1.7.10-1.0.5.120

I have try different versions and also, with only NEI and Enderio

GUI Scale Large: 
![invpanellarge1](https://cloud.githubusercontent.com/assets/9842044/12989862/79b153a8-d107-11e5-8603-ee1c5f2c58f6.png)

Test with large GUI from RFTools:
![rftoolslarge1](https://cloud.githubusercontent.com/assets/9842044/12989878/8facf982-d107-11e5-8fb9-3f5ae8cd24ba.png)

With GUI Scale Normal everything is ok. But it´s too small for me.
![invpanelnormal1](https://cloud.githubusercontent.com/assets/9842044/12989888/a029ba66-d107-11e5-83c7-57c3e8e1b635.png)

**Comment by HenryLoenwind** [comment]
I *think* NEI switches off if it has less than 3 columns of space left.

**Comment by tterrag1098** [comment]
Yes. There is nothing we can do here.
