### ISSUE TITLE
magnet in baubles slot

### ISSUE THREAD

**Issue by Mementh** [SleepyTrousers/EnderIO#3196]
How do we put it in there? I understand per https://github.com/SleepyTrousers/EnderIO/issues/2313 its available to do.. but how?

is there a setting i am missing or a option that is not in anymore

**Comment by Beiserkeren** [comment]
same her

**Comment by wlhlm** [comment]
The Magnet only works in the baubles slot when the inventory is full (#3015).

**Comment by Mementh** [comment]
how do you get it IN the baubles slot???? i had a full inventory and it wont click in? 

i had it active??? 

I know i am missing something

**Comment by HenryLoenwind** [comment]
If it is active you should be able to simply pull it into the amulet slot. If not, check on which Ender IO version you are. If its 2.2.8, then no, too old. If you are on 2.3, check if "magnetAllowInBaublesSlot" is set to true in the config. (ESC->Mod Options->Ender IO->Options->Magnet)

Inventory full has nothing to do with it at all.

**Comment by Mementh** [comment]
dang its the old version... is 2.3 a dev/beta version or a solid release?

**Comment by mindforger** [comment]
@Mementh it's totally stable imho :D

**Comment by HenryLoenwind** [comment]
It's a beta, but for about half a year we more ore less just fixed bugs and tweaked stuff. So it is quite stable. The next version (424) may be a bit unstable, it has a lot of cleanup stuff in it, which means new code, which means potential for new bugs.
