### ISSUE TITLE
ComputerCraft Cable Conduits

### ISSUE THREAD

**Issue by Yanniclord** [SleepyTrousers/EnderIO#3197]
So i am quite sure it has been asked before, but would it be possible now to add support for ComputerCraft Conduits in some way, same as for ME Dense/Normal Conduits and Mekanism Gas Conduits? It is somewhat of an annoyance that ComputerCraft still hasn't added any support for any of the Facade or Cover mods, which isn't exactly helpful to hide cables if you ask me. The Immibis Multiblock thing is non functional, because i havent seem any of them available, and i have Forge Microblocks, AE2 and BuildCraft Facades and Thermal Expansion Covers.

So, is there any possibility to add ComputerCraft conduits to EnderIO so that we all can run those cables through those neat little Conduit Facades?

Thanks :)

**Comment by Yanniclord** [comment]
Also, im note sure how to mark this as an "enhancement" or such, but i am quite sure i cannot do that anyway :)

**Comment by tterrag1098** [comment]
#46
