### ISSUE TITLE
[Suggestion] Staff of Traveling Upgrades

### ISSUE THREAD

**Issue by Neodark7** [SleepyTrousers/EnderIO#3198]
Can you, like for the Dark Armor, add "Enchant upgrades" for the staff ? 
You can maybe reduce the base energy storage of the staff to 100kRf and make like :

Basic Capacitor + 10lvl = 250krf
Double-layer Capacitor + 15lvl = 500krf
Octadic Capacitor + 20lvl = 1MRf

**Comment by Neodark7** [comment]
@CrazyPants why are you closing that without even answering something ? -_-

**Comment by HenryLoenwind** [comment]
because adding a comment to over 650 old tickets would be an insane amount of work?

**Comment by Neodark7** [comment]
ofc if you wait 2 years without answering anything... the solution is not to close everything in one row and start again wtf :D
