### ISSUE TITLE
Farming station crash (With cotton from Natura)

### ISSUE THREAD

**Issue by leroy627** [SleepyTrousers/EnderIO#3200]
http://pastebin.com/591n6Zi7 
Now I'm in an infinite crash loop, the second I get on, it tries to harvest the cotton, and I crash.

**Comment by mindforger** [comment]
did you ask the mod author of that claim mod for help? 'latmod.ftbu.world.claims.ClaimedChunks.canPlayerInteract(ClaimedChunks.java:268)'

**Comment by MatthiasMann** [comment]
Old version of the FTBUtilities mod?

**Comment by mindforger** [comment]
wow .. this fakeplayer stuff is branching out very very far 
https://github.com/SleepyTrousers/EnderIO/issues/2575
https://github.com/SleepyTrousers/EnderIO/issues/2983
yeah, as @MatthiasMann said try updating everything, from "forge" itself over "forge essentials" to "forge utils"

**Comment by leroy627** [comment]
everything that has "forge" in its name?

**Comment by leroy627** [comment]
It's apparently been here since june according to those two issues, hard chance they patched it , gonna try anyways

**Comment by mindforger** [comment]
at least forge utils had several updates
FTBUtilities-1.7.10-1.0.14.2 VS FTBUtilities-1.7.10-1.0.17.1 (severely outdated)
FTBLib-1.7.10-1.0.14.3 VS FTBLib-1.7.10-1.0.17.2 (severely outdated)
forge-1.7.10-10.13.4.1558 VS 10.13.4.1614 (well according to changelogs, minor fixes, just something with skull placing and armorstads and fuel handling)

**Comment by HenryLoenwind** [comment]
BTW, the next Ender IO version (424) will have some "please don't crash" adaption in the fake player that _might_ help. #3071

I'll take to tt about making that build later today.

**Comment by leroy627** [comment]
Thanks, it worked, still though, FTB should really update the pack
