### ISSUE TITLE
SoulBound enchant stripping armor when crossing dimensions

### ISSUE THREAD

**Issue by Solidflip** [SleepyTrousers/EnderIO#3203]
Using EnderIO 0.2.0.31

When a player moves across dimensions via portals or a warping system, their soulbound armor is taken off. Tested it and it only affects soulbound armor. Is there a fix for this other than not using the enchantment?

**Comment by HenryLoenwind** [comment]
Sorry, Ender IO for Minecraft 1.5.2 or 1.6.2 (sorry, I cannot see which one it is exactly by the version number) is no longer supported. If you are using Minecraft 1.5.2, try upgrading to Ender IO 0.3.6.98, which is the last one that was created for that Minecraft version. If you are using Minecraft 1.6.2, try upgrading to Ender IO 0.11.0.307, which is the last one that was created for that Minecraft version.

**Comment by Solidflip** [comment]
Im sorry my phone messed up the version. Its happenening on ender io 1.7.10
v2.3.0.422

On Feb 17, 2016 2:17 PM, "Henry Loenwind" <notifications@github.com> wrote:
>
> Sorry, Ender IO for Minecraft 1.5.2 or 1.6.2 (sorry, I cannot see which
one it is exactly by the version number) is no longer supported. If you are
using Minecraft 1.5.2, try upgrading to Ender IO 0.3.6.98, which is the
last one that was created for that Minecraft version. If you are using
Minecraft 1.6.2, try upgrading to Ender IO 0.11.0.307, which is the last
one that was created for that Minecraft version.

**Comment by HenryLoenwind** [comment]
"portals or a warping system" Please be a bit more specific. Does it happen with Nether Portals in an installation with just Ender IO? If not, does it happen with nether portals and your other mods? In that case, which mods are that. Or doesn't it happen at all with nether portals? In that case which mod's portals does it happen with?

**Comment by Solidflip** [comment]
It does occur with the end portal, as well as the teleporters from RFTools. It only happens with soulbound items, they are taken off and placed into the inv as if you died, however if your inv is full they are dropped on the ground.

**Comment by tterrag1098** [comment]
Must be related to player cloning. @Mcjty do your teleporters clone the player?

**Comment by McJty** [comment]
Here is the code (for 1.7.10) that RFTools uses to teleport a player to another dimension: RFTools/src/main/java/mcjty/rftools/blocks/teleporter/TeleportationTools.java (teleportToDimension)

**Comment by tterrag1098** [comment]
I uh...think your link messed up there

**Comment by McJty** [comment]
Oops, here is the correct link: https://github.com/McJty/RFTools/blob/master/src/main/java/mcjty/rftools/blocks/teleporter/TeleportationTools.java

**Comment by HenryLoenwind** [comment]
I've looked at our code _again_, I see no way for this to happen.

We do not have any code to drop items on the ground on death/respawn/clone. So if they are dropped, some other mod is doing the dropping. We only copy them (a) from the "to drop" list to the old body's inventory and (b) from the old body's inventory to the new body's inventory.

So some mod is messing with the death logic badly.

**Comment by HenryLoenwind** [comment]
nothing more can be learned from this (to quote another famous mod). So thx for the report, but I'm closing it now.
