### ISSUE TITLE
conduits

### ISSUE THREAD

**Issue by TTLPcraft** [SleepyTrousers/EnderIO#3204]
can you please make mekanism universal cable conduits that can transfer rf, eu and joule and make cyro stabilised conduits that can transfer infinite rf?

**Comment by MatthiasMann** [comment]
lol

**Comment by HenryLoenwind** [comment]
![okay?](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTsDWPXQnSDBF0tcsigEyLr2IhQnS3zRFxiL_389_rp1wSIQWdU)

**Comment by tterrag1098** [comment]
Not interested. See #3061 #1894
