### ISSUE TITLE
Item Sorting

### ISSUE THREAD

**Issue by MaylarSnow** [SleepyTrousers/EnderIO#3205]
Hello,

I am currently using FTB Direwolf20 modpack and I am having an issue. It would seem to me the sticky function is not working with the advanced item filter. It will still send ore blocks to a chest when the SAG Mill only has 3 items in it. (Say you drop 10 iron ore into the input chest, 3 will go to the sag mill and 7 will go into another chest.) I also have a problem with items being removed from the Alloy Furnace. They just sit there.

This is my current setup. And I had to use alot of filters to get this far. Ender Chest (ChickenBones) input. This goes down, 3 blocks away is a ME input. I have this set to Priority 1 and installed an Advanced Item filter to blacklist my ores or it would do the split I mentioned earlier. The line continues  down to 2 Sag Mills that pulls in from the top (The SAGs are set to pull from the top and the conduits are set to push). They are set to Priority 10 with Advanced Item filters with sticky mode on. ignore MBT/NBT and ore Dic. they are set to a white list. This is the green channel. 

Now, I had to end up pulling from the bottom of the SAGs onto a different line or the Dusts would split and go between the ME input and the Alloy Furnaces. Even though I have sticky mode as well For those Furnaces. Now, the Dusts go into the Furnaces and the by-products (Cobble, ect.) go into an Item Buffer to go back into the original line. This small line does not seem to give me a problem with items splitting. The Dusts go to the Furnace like the should. They are setup to push/pull on the bottom. The item conduit is set the same. It loads the furnaces, but does not pull the items out to send to the item buffer. 

What will sometimes solve this? If I go to the input conduit for the item buffer and change the channel color and change it back. it will unload the furnace until a new item type is smelted. Then it jams again.

So, am I not using the sticky mode correctly? I thought with it enabled, it would put the ores only into the SAG Mills.

**Comment by tterrag1098** [comment]
Fairly sure the DW20 pack ships an older version. What version are you running?
