### ISSUE TITLE
Text for named travel anchors shows as white boxes

### ISSUE THREAD

**Issue by IronHide4** [SleepyTrousers/EnderIO#3208]
#### Issue Description:
When looking at a travel anchor, either with a staff of travelling in hand or standing on another anchor, the name given to the block shows as white boxes instead of letters.  The block itself is white when viewed at certain angles.

http://imgur.com/LXntTAe
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.422_beta
- EnderCore: 1.7.10-0.2.0.31_beta
- Minecraft: 1.7.10
- Forge:10.13.4.1614-1.7.10

**Comment by tterrag1098** [comment]
Do you have any mods like Optifine present?

**Comment by IronHide4** [comment]
The mod psychedelicraft had shaders that were effecting them, so I uninstalled it and now they are fine.
