### ISSUE TITLE
Wrong value for burn rate in stirling generators

### ISSUE THREAD

**Issue by KristjanKr** [SleepyTrousers/EnderIO#3211]
#### Issue Description:
Burn rate shows with octatic capacitor in stirling generator as: 1,3333334x which seems incorrect.

#### What happens:

Burn rate is 1,3333334x in stirling generator(when using octatic capacitor) without capacitor it shows 1.0x(which seems more logical then 1.3333334x)

#### What you expected to happen:

It would be logical if the burn rate followed the same logic, as without capacitor, for example 1,4x or 1,3x instead of 1.3333334x 

#### Steps to reproduce:

1.Get EnderIO 424.
2.Place down stirliing generator with octatic capacitor.
3.Look that it shows 1,3333334x instead of round number.
![umm](https://cloud.githubusercontent.com/assets/6142226/13373007/4c641944-dd64-11e5-90ff-9508088b10bf.png)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:beta 424
- EnderCore:beta 0.2.0.21
- Minecraft: 1.7.10
- Forge:1614

**Comment by AnrDaemon** [comment]
The value is correct per se (1.333 is 4/3), but formatting… that can be improved I believe.
