### ISSUE TITLE
nutrient distillation

### ISSUE THREAD

**Issue by barkos** [SleepyTrousers/EnderIO#3212]
rotten flesh and nether wart not working anymore in the vat on 424 ver ?

**Comment by joye-ramone** [comment]
Same for me. Looks like that part of recipes does not work any more in latest version. Even if I re-add it manually using user config file.

**Comment by tterrag1098** [comment]
@HenryLoenwind

**Comment by CristinoValdigem** [comment]
On Your Game the Vat when u put her on floor he turn invisible ??
