### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by TheDEAS** [SleepyTrousers/EnderIO#3214]
#### Issue Description:
I've tested the new system Weather Obelisk and my server crashed.

#### What happens:
I filled out the GUI in different liquids (cloud seed, the best seed cloud and sunshine). Then I put a firework rocket and launched it when it took off, the server crashed.

#### Steps to reproduce:
1. Put a weather obelisk.
2. Loaded it with energy.
3. Poured liquid.
4. Put in weather obelisk the firework rocket.
5. Pressed the tick
6. He started flying
7. Crashed

___________________
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10 2.3.0.424 beta
- EnderCore: 1.7.10 0.2.0.31 beta
- Minecraft: 1.7.10
- Forge: 1.7.10 10.13.4.1614

#### Your most recent log file where the issue was present: 
[Crash-report](http://pastebin.com/FAK2KiVd)

**Comment by JSX4** [comment]
First post here- my apologies for any incorrect formatting. 

I have also had this exact same issue. Can be reproduced exactly as stated above. I have input energy through ender energy conduits, and the liquid inside is concentrated cloud seed. Hope to see a fix soon.

**Comment by tterrag1098** [comment]
424 is 3 builds old. Could you try updating?

**Comment by HenryLoenwind** [comment]
This was fixed in commit 9ba0554651a2d40359d741e695005235e1c392eb (build 425), 3 months ago.
