### ISSUE TITLE
Item(s) duplication

### ISSUE THREAD

**Issue by ooxblodin** [SleepyTrousers/EnderIO#3217]
#### Issue Description:
Item(s) duplication

#### What happens:
When I remove 1 capacity bank from a 2 block capacity bank multi-block with item(s) inside, then place the bank back, all item(s) duplicate. This works with other mods and this mod.

#### What you expected to happen:
Basically not getting any duplicated item(s).

#### Affected Versions :

- EnderIO: 2.2.8.381
- EnderCore:
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

**Comment by tterrag1098** [comment]
This has been fixed in the beta versions.

**Comment by yaroslav4167** [comment]
If you try again ( 2-3 times) - duplication of work again.
