### ISSUE TITLE
Farming Station will not plant Rotarycraft Canola Anymore

### ISSUE THREAD

**Issue by aetherpirate** [SleepyTrousers/EnderIO#3221]
#### Issue Description:
Farming Station will not plant Rotarycraft canola anymore, it tills the land, and tosses the seeds on the ground. In the previous version of Enderio and Endercore, this worked fine. I had also updated RC to v11b, I am not sure if this is Reika's issue or yours, or if this function has just been removed. 

#### What happens:

RC canola seeds tossed on ground instead of planted

#### What you expected to happen:

seeds to be planted, grown, and harvested

#### Steps to reproduce:

1. Place Farming Station
2.Add power, hoe, and canola seeds
3.It will till the land, and then toss seeds. They eventually de-spawn. 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.424_beta
- EnderCore 1.7.10-0.2.0.31_beta.jar
- Minecraft: 1.7.10
- Forge:1492

#### Your most recent log file where the issue was present: 

This issue does not cause a crash. 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Can the seeds be planted on that farmland?

The Farming Station has no code to create item entities for seeds, only code to create blocks. So I suspect it creates a block that directly "itemifies" itself, just like e.g. torches do when you remove the block they are attached to.

**Comment by MatthiasMann** [comment]
RotaryCraft changed the seeds in V11b and the requirements for planting. I think you now need a lot of light in order to plant them.

**Comment by aetherpirate** [comment]
I'll do some testing later and see.

**Comment by aetherpirate** [comment]
Nevermind, they just need water now. Dug some trenches, poured in some water, and it all works fine now.
