### ISSUE TITLE
Machines using the PowerDistributor are trying to connect using the wrong direction

### ISSUE THREAD

**Issue by HenryLoenwind** [SleepyTrousers/EnderIO#3222]
#### Issue Description:

https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/power/PowerDistributor.java#L75

Here the direction is reversed needlessly.

Place any machine that has its top side disabled onto a Transceiver, Stirling Generator, Energy Buffer, Zombie Generator or Combustion Generator. Fire the power source up.

Expected: Machine gets energy.

Reality: Machine doesn't get energy.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 424

**Comment by 4rz0** [comment]
How comes no one ever noticed that before?

**Comment by HenryLoenwind** [comment]
I'd even go so far to say that people very rarely use "disabled" at all. And in all the other modes machines are still open for power.
