### ISSUE TITLE
Me interface not behaving properly when trying to place it on an ME conduit

### ISSUE THREAD

**Issue by border999** [SleepyTrousers/EnderIO#3223]
#### Issue Description:
I was attempting to rewire my me network so I I could also feed power to a non-AE block.
It all worked swimmingly until I tries to put the interface onto the conduit. It placed backwards and my WAILA told me it was offline. Please note that the ME conduit that I was trying to place on also had the lowest tier energy cable in the same block space.

#### What you expected to happen:
For these two mod creators to have expected this problem, and for the ME interface to connect to the conduit like it would ME cable.

#### Steps to reproduce:

1.Have both latest Ender IO and latest stable Applied Energistics installed.
2.Play down an ME conduit.
3.Try to place an interface on it.
#### Affected Version
- EnderIO: EnderIO-1.7.10-2.3.0.424_beta
- EnderCore: EnderCore-1.7.10-0.2.0.31_beta
- Minecraft: 1.7.10
- Forge: 1.7.10-Forge10.13.4.1614-1.7.10

**Comment by wlhlm** [comment]
See #2275.

**Comment by MatthiasMann** [comment]
The ME import/export/etc buses/interfaces and terminals are multi blocks which can't be placed into the EnderIO conduit block. So you need to use a normal fluix cable at a place where you want to use one of these.

To "Fix" this would require rewriting a lot of the AE2 code on the EnderIO side - so this is a won't fix.
