### ISSUE TITLE
[Suggestion] additional Overlay Textures to Facaded Cables when connecting to something

### ISSUE THREAD

**Issue by mindforger** [SleepyTrousers/EnderIO#3224]
at first, i have absolutely no idea how complicated such an improvement would be, but i have seen chisels from other mods beeing able to overlay transparent textures over existing blocks where this this idea just got into my mind!

how about adding an overlay after rendering the facades that will only be visible when a conduit from the inside is connecting to the outside to something

the texture would be something like 2 or 3 squares stacked into each other with increasing opacity/darkness to the middle 
size aproximately the size of the connection plate you get when a conduit interferes with something

this would look like a wall socket then and improve the visual quality imho ... but thats really just my optinion .. others may not find it good and larger pipes would probably render this overlay useless as they may be bigger than the actual overlay and thus not visible at all :)

i just wanted my idea not to go completely unnoticed

i did not test yet but i just got another idea, if it would probably possible to chisel a facade block ... and if so i could add the texture by myself so this wouldn't be neccesary at all XD

**Comment by CyricV** [comment]
This would be a neat visual change.

**Comment by HenryLoenwind** [comment]
Are you talking about something like this:

![](http://www.scope-online.de/upload_weka/9288870_big_859865.jpg)

![](http://www.prechter-renner.de/images/Bilder_Kabeldurchfuehrung/Kabeldurchfuehrung_DX_3.jpg)

![](http://i42.tinypic.com/30j487n.jpg)

**Comment by mindforger** [comment]
something simpler like that

![conduitconnectorfacadeoverlay](https://cloud.githubusercontent.com/assets/2683555/13778750/dd08c21e-eab7-11e5-931f-126c73025364.png)

and if desired some texturepack maker can replace it by something more fancy

**Comment by mindforger** [comment]
stupid close button -.-

**Comment by HenryLoenwind** [comment]
Simple solution: Make the connector plate extend 0.01 blocks out of its block space and render it even in facades. Easy to do.

I was more thinking along conduits coming out of facades. That looks a bit magical to me.

**Comment by mindforger** [comment]
can you give me a hint where i need to edit the code, then i can try to build a testversion to see how it looks
i am a little bit afraid of z-fighting issues when the connector is extending out of its blockspace

**Comment by MatthiasMann** [comment]
Z-fighting only happens if you have 2 polygons on the same plane - if one intersects the other at an angle then there will be no z-fighting.

**Comment by HenryLoenwind** [comment]
Z-fighting with the neighboring block. I had that problem with some of the hollow eioa blocks. the eio io overlay was z-fighting with my inside walls. But there are not that many hollow blocks out there, an most of them have a wall that is 1 pixel thick, at least.
