### ISSUE TITLE
Conduit facades

### ISSUE THREAD

**Issue by Fluoxi** [SleepyTrousers/EnderIO#3226]
#### Issue Description:
Latest version: EnderIO-1.7.10-2.3.0.424_beta, does not seem to hide conduits anymore when using Quite Clear Glass facades.

#### What happens:
Still seeing conduits when hiding with Conduit Facades painted with Quite Clear Glass.

#### What you expected to happen:
Conduits properly being hidden like before.

#### Steps to reproduce:

Paint a conduit facade with quite clear glass in a painting machine then using that facade on conduits.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.424_beta
- EnderCore: 1.7.10-0.2.0.31_beta
- Minecraft: 1.7.10
- Forge: ForgeMultipart-1.7.10-1.2.0.345-universal

#### Your most recent log file where the issue was present: 

[http://pastebin.com/J7tY8f4D]

**Comment by MatthiasMann** [comment]
Well - glass is transparent - so you see the conduits.

**Comment by HenryLoenwind** [comment]
great now we get reports telling us that we fixed a bug people liked...

**Comment by HenryLoenwind** [comment]
see #2737

**Comment by mindforger** [comment]
i prefere to see the cable through the glass... either way it would be unrealistic!

sorry to say that, but not beeing able to hide cable properly and using glass to make them invisible is very cheap thinking

**Comment by mouro001** [comment]
I would prefer how it was before. Maybe add a crafting recipe that with a painted facade + glowstone or vanilla glass make it to hide the conduits inside?

**Comment by HenryLoenwind** [comment]
could people please stop suggesting things that already exist?

Also, why necro this and not comment in the open ticket #3358 ?
