### ISSUE TITLE
[Request] Disable Soulbound if Ars Magica is present

### ISSUE THREAD

**Issue by Zsashas** [SleepyTrousers/EnderIO#3228]
Or at least a config option to disable the enchantment.

Speaking of which, just how different is it from the Ars Magica one? Both enchantment and imbuement.

**Comment by MatthiasMann** [comment]
Well - never really played with Ars Magica so no idea how it behaves.
But the EnderIO enchantment will keep all enchanted items in your inventories (Vanilla, Baubles and Galacticraft) when you die.

**Comment by Zsashas** [comment]
The effect is the same. I just didn't know if they were internally different in any way.

**Comment by HenryLoenwind** [comment]
um, there is an option for that, "enchantmentSoulBoundEnabled"...
