### ISSUE TITLE
Ignoring "addRegisterdNameTooltip" Config Option

### ISSUE THREAD

**Issue by GeoTerra** [SleepyTrousers/EnderIO#3230]
EnderCore: v1.7.10-0.2.0.31_beta
EnderIO: v1.7.10-2.3.0.424_beta

Checked this against a fresh install of EC & EIO, still occurs. Also checked against the Infinity Evolved modpack to ensure this wasn't a pack-specific bug with the same versions, config was still ignored.

Regards.

**Comment by HenryLoenwind** [comment]
Indeed. There is no code that acts on that config flag. I need to do a history search to find out where it was and went.

**Comment by HenryLoenwind** [comment]
It was killed by this commit: https://github.com/SleepyTrousers/EnderIO/commit/ac982993d7f69f0515180a805d7ddf8600651a31 "Port tooltip system to EnderCore"

**Comment by GeoTerra** [comment]
Ah, okay. Wasn't aware that the tooltip system was ported over. Thanks Henry. I can see the config settings in the EnderCore config file.

Perhaps a line could be added to the EIO config to mention that this (and the OreDict) setting(s) have been moved to EnderCore's config? If not, then now I know better, at least. Thanks.
