### ISSUE TITLE
Experience obelisk

### ISSUE THREAD

**Issue by BuckitHead** [SleepyTrousers/EnderIO#3232]
Experience obelisk allows you to store all but only allows you to retrieve 6 lvls. If you keep hitting store all/ retrieve all it keeps increasing the stored lvl.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.8.9-3.0.0.14
- EnderCore:1.8.9-0.3.0.11
- Minecraft: 1.8.9
- Forge: 1764

**Comment by CrazyPants** [comment]
Fix in the latest dev build
