### ISSUE TITLE
Conduits not properly detecting pipes (from other mods)

### ISSUE THREAD

**Issue by Timeslice42** [SleepyTrousers/EnderIO#3234]
This ticket *might* be considered a duplicate of #2929. Also, I'm not 100% sure cross connection is supposed to be supported in the first place.

Two examples/issues. The second issue is probably on your side, the first probably isn't.

First: Connecting too often
When placing item or fluid conduits near any blocks from GregTech (such as a power cable) they always default to connecting. Part of this is due to the way that all blocks in GT are handled. However I'm hoping there's a "handlesFluids()/handlesItems()" method that you can call or something.

Second: Not connecting often enough
There's some inconsistency with connecting to Buildcraft and Logistic Pipes pipes. Waterproof pipes and fluid conduits connect on both sides, which is great. Waterproof pipes attempt to connect to item conduits, which is weird. Item pipes/basic LP pipes and item conduits do not attempt to connect to each other at all, which is sad (this one is probably a very complicated "fix"). The LP fluid insertion pipe tries to connect to fluid conduits, but the fluid conduit does not connect back. This is the issue I'm most interested in getting fixed. I'm guessing this is because the LP fluid insertion pipe can carry both items *and* fluids. I'm hoping it's just a simple case of the fluid conduit detecting that the LP pipe accepts items and not bothering to check that it also accepts fluids.

Finally, now that I've made this ticket, it seems like a bit of a mess. Depending on feedback, I'm thinking I should make an issue for just the LP Fluid Insertion pipe.

**Comment by MatthiasMann** [comment]
There is no API to detect if fluid or item transports should connect or not. If the correct API is exposed (inventory or fluid handler) than the conduit will connect.

In generally you should avoid connecting pipes of different mods with each other - put a buffer/tank in between.

**Comment by Timeslice42** [comment]
Any clue why the waterproof pipes try to connect to item conduits?

**Comment by Timeslice42** [comment]
Also, to confirm: the LP fluid insertion pipe is not exposing the correct fluid API, but the BC waterproof pipes are?

**Comment by MatthiasMann** [comment]
No idea - as long as nothing crashes you just have to live with this "undefined" behavior.

**Comment by tterrag1098** [comment]
Any conduit block exposes an IFluidHandler interface and we have no way to say that a connection to us should not be made. This is one of the benefits of the upcoming capabilities system in forge 1.8.
