### ISSUE TITLE
Broken Recipes

### ISSUE THREAD

**Issue by Thiana** [SleepyTrousers/EnderIO#3238]
#### Issue Description:

JEI reports broken recipes with EnderIO 1.8.9-3.0.0.15 items.

<pre>
[22:09:11] [Client thread/ERROR] [JEI/]: Found a broken recipe: net.minecraftforge.oredict.ShapedOreRecipe@27f9b652
Output ItemStacks: [[1x (null)]]
Output Fluids: []
Input ItemStacks: [[1xenderio:itemMaterial@1], [1xminecraft:stick@0], [1xenderio:itemMaterial@1], [1xminecraft:stick@0], [], [1xminecraft:stick@0], [1xenderio:itemMaterial@1], [1xminecraft:stick@0], [1xenderio:itemMaterial@1]]
Input Fluids: []
</pre>
and
<pre>
[22:09:11] [Client thread/ERROR] [JEI/]: Found a broken recipe: net.minecraftforge.oredict.ShapedOreRecipe@388f2bca
Output ItemStacks: [[1x (null)]]
Output Fluids: []
Input ItemStacks: [[1xenderio:itemMaterial@1], [1xminecraft:stick@0], [1xenderio:itemMaterial@1], [1xminecraft:stick@0], [], [1xminecraft:stick@0], [1xenderio:itemMaterial@1], [1xminecraft:stick@0], [1xenderio:itemMaterial@1]]
Input Fluids: []
</pre>

#### Steps to reproduce:

1. Install JEI and EnderIO together.
2. Run Minecraft, create a world.
3. Read log ;)

#### Affected Versions:
- EnderIO: 1.8.9-3.0.0.15
- EnderCore: 1.8.9-3.0.0.11
- Minecraft: 1.8.9
- Forge: 1765

**Comment by mezz** [comment]
@HenryLoenwind Was this fixed or ignored? I still see this in EnderIO-1.8.9-3.0.0.17_alpha. Thanks.

**Comment by HenryLoenwind** [comment]
build 17 was ages ago...

Also, I went to see my architect today. Told him that my roof was leaking. He was a bit busy overseeing the workers who were laying the first row of bricks for my ground floor, but he noted it down. I think I'll better tell him that there's a problem with the stair to the second floor---I can't find them.

Or in other words: Errors with recipes for items that aren't even in the game yet will be ignored.

**Comment by mezz** [comment]
Ok, just looking for an explanation. "The 1.8.9 port is incomplete." works for me, thanks.
