### ISSUE TITLE
can you add support for other enchantments to the enchanter

### ISSUE THREAD

**Issue by wpinda** [SleepyTrousers/EnderIO#3243]
Like absorption, stealth, gravity resist, last stand, unstable, etc. 
You can use items like sponge, invisibility potion, feather, essence bucket and gunpowder

**Comment by MatthiasMann** [comment]
You can add these in the EnchanterRecipes_User.xml inside the config/enderio folder.

**Comment by wpinda** [comment]
I tried that but it doesnt really work
This is what I have http://i.imgur.com/zsb1BZH.png
If I try to put in the dirt and the book, I can see the enchanted book with last stand and pull it out, but when I try to interact with it (put it on my armour), it disappears and the dirt and book appear in the enchanter again

**Comment by MatthiasMann** [comment]
Are you playing on a server? If yes then you need to update the config on both server and all clients.

**Comment by HenryLoenwind** [comment]
no further questions? must be solved then.

BTW: If you have a list of enchantments and suitable items (if possible in already tested xml form), you can send it to us to be included with the next Ender IO release.
