### ISSUE TITLE
Insulated Redstone Conduit + Computer Craft CRASH

### ISSUE THREAD

**Issue by AragurDEV** [SleepyTrousers/EnderIO#3244]
#### Issue Description:
If you place an Insulated Redstone Conduit next to a Computer (ComputerCraft) your game (Server)  is crashing.

#### What happens:
EnderIO is searching a deprecaded ComputerCraft API. (maybe)

#### What you expected to happen:
No game crash :)

#### Steps to reproduce:

1. Place a Computer
2. Place Insulated Redstone Conduit next to a Computer
3. Crash :)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.18
- EnderCore: 0.3.0.12
- Minecraft: 1.7.10
- Forge: 11.15.1.17794
- ComputerCraft 1.79pr1

#### Your most recent log file where the issue was present: 

http://pastebin.com/D5gu2gYk

**Comment by AragurDEV** [comment]
Update: Crash is hapenning on all machines. (EnderIO included)

**Comment by tterrag1098** [comment]
Your report specifies MC 1.7.10. This is incorrect, right?

**Comment by AragurDEV** [comment]
No, i'm using 1.8.9

**Comment by VT-14** [comment]
I also had a similar Insulated Redstone crash when placed next to an Ender IO Powered Spawner.  It was in one of the 1.8.9 builds from a few days ago, but I am currently away from that PC and don't know the exact version or have the log with me.

Normal Redstone Conduit was fine, but I have been having trouble forcing it to connect to anything (including the spawner and Sterling Generators).  This could just be me not knowing how to force a connection correctly (I can't recall ever doing it before) or a bad mod interaction/keybind preventing me from opening that GUI.

**Comment by Nytoca** [comment]
I also had a similar issue with Insulated Redstone Conduits. Placed one behind a Power Monitor and the game crashed.
I'm using the latest build from Jenkins, so I will wait for the next version.
http://pastebin.com/iDuukdxR

**Comment by MakeLord** [comment]
I got this crash too, so I tested it with just EnderIO, EnderCore and ComputerCraft. Without ComputerCraft it works just fine...

**Comment by HenryLoenwind** [comment]
As Crazy is not available atm, it seems I need to take care of this. Does anyone know where I can get the ComputerCraft API?

**Comment by MakeLord** [comment]
I think contacting dan200 would be the best option to get the latest API.

**Comment by HenryLoenwind** [comment]
done
