### ISSUE TITLE
Haunted SAG Mill

### ISSUE THREAD

**Issue by NewEpochGaming** [SleepyTrousers/EnderIO#3245]
#### Issue Description:

My SAG Mill is Haunted...
http://www.negaming.org/forum/m/30382475/viewthread/26669538-writing-on-my-macine/page/1

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by b0bst3r** [comment]
You need ghostbusters not EIO devs.

**Comment by HenryLoenwind** [comment]
Your nick starts with an "N".

Tell me something I don't yet know...
