### ISSUE TITLE
[1.8.9] Null World Crash in Chunk-Loaded Dimension

### ISSUE THREAD

**Issue by oitsjustjose** [SleepyTrousers/EnderIO#3247]
#### Issue Description:
Cross Reference [BuildCraft #3279](https://github.com/BuildCraft/BuildCraft/issues/3279)
Recurrent crash on world-load due to BuildCraft tank null worldObj access

#### What happens:

My server (and in single-player) world crashes on load when my BuildCraft tank in the nether (which is chunk-loaded) is loaded on world startup. This seems to occur because the conduits are trying to access the BuildCraft tank, whose worldObj has not yet been initialized (so a race condition).

#### What you expected to happen:

...Not crashing? ;D
Possible Solution: check for null world object before accessing, if the tile's world object is null, then ... somehow wait until it isn't null?

#### Steps to reproduce:

1. Place a BloodMagic Teleposer in the overworld, linked to another Teleposer in the nether
2. Prepare some sort of conduit setup in the nether to modify the contents of the tank to be Teleposed
3. Activate the teleposer while standing near enough to be teleposed with it. When you and the tank are teleposed, the server begins this recurring crash loop.

____
#### Affected Versions

- EnderIO: 3.0.0.19-alpha
- EnderCore: 0.3.0.12-beta
- Minecraft: 1.8.9
- Forge: 11.15.1.1764

#### Your most recent log file where the issue was present: 

[FML Crash Report](http://puu.sh/nVMGO/7fcb2dbd9f.txt)

**Comment by AlexIIL** [comment]
Sorry, I missed that this was a Blood Magic teleposer. Its not enderio's fault then :P

**Comment by oitsjustjose** [comment]
:P I'll go leave Way a bug report then ;D
