### ISSUE TITLE
Placing a Sterling Generator in the world crashes the server

### ISSUE THREAD

**Issue by Hund** [SleepyTrousers/EnderIO#3248]
I'm running my own server with some mods and today I added EnderIO. The first and only thing I crafted was a Stirling Generator and when I placed it in the world the server crashed.

I tried EnderIO (same setup) in a new single player world before I added the mod to the server, and there it worked just fine.

* Minecraft 1.8.9
* Forge 11.15.1.1808
* EnderIO 3.0.0.20
* EnderCore 0.3.0.13
* [latest.log](http://pastebin.com/Mwzpk1Cs)

List of my mods:

* [Client](http://pastebin.com/iE6GhJzZ)
* [Server](http://pastebin.com/ZkzYkUwz)

**Comment by tterrag1098** [comment]
Your EnderIO and EnderCore versions do not match. @HenryLoenwind we should be putting explicit requirements into the @Mod dependencies

**Comment by Hund** [comment]
Oh. I just assumed the latest available versions of the mods would work together. How do I know which version of to use?

**Comment by tterrag1098** [comment]
You don't really. But EnderIO should work with the EnderCore that was built just before. Look at the build times.

**Comment by Hund** [comment]
So. EnderIO-1.8.9-3.0.0.20_alpha.jar is built 1d 10h ago and EnderCore-1.8.9-0.3.0.13-beta.jar is built 2d 7h ago. But I should use EnderCore-1.8.9-0.3.0.12-beta.jar that was build 9 days ago instead?

**Comment by Hund** [comment]
So. EnderIO-1.8.9-3.0.0.20_alpha.jar is built 1d 10h ago and EnderCore-1.8.9-0.3.0.13-beta.jar is built 2d 7h ago. But I should use EnderCore-1.8.9-0.3.0.12-beta.jar that was build 9 days ago instead?

**Comment by Hund** [comment]
I tried the previous version (0.3.0.12) and now it says "endercore : minimum version required is 1.8.9-0.3.0.13-beta". So I was using the right version after all?

**Comment by HenryLoenwind** [comment]
Please don't stealth-edit your post and then pretend we are to stupid to read it. You did state using Ender IO build 13 originally. There's nothing wrong in admitting to have made a copy&paste error, that happens to us all. There's everything wrong with shifting the blame for your mistakes to others.

**Comment by Hund** [comment]
I wrote the same version number for both mods by mistake. I noticed it when I was writing my last reply and changed it right away. 

I never blamed anyone for anything. 
I'm sorry if my edit looked like so, as it was never my intention. 

So, back to topic. I was using using the right version and it did not work. What could be the problem?

**Comment by Hund** [comment]
This works with version 3.0.0.21.
