### ISSUE TITLE
RF connection not working with IEnergyReceiver and IEnergyProvider on the same tile entity

### ISSUE THREAD

**Issue by LemADEC** [SleepyTrousers/EnderIO#3249]
#### Issue Description:

EnderIO power interface is making invalid assumption on CoFH Energy blocks
#### What happens:

When connecting with a tile entity implementing both IEnergyReceiver and IEnergyProvider, EnderIO only check for the latest and doesn't realize that the same tile entity can also receive energy.
As seen here: https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/power/PowerHandlerUtil.java#L21
#### What you expected to happen:

EnderIO should support tile entities with both direction of RF energy.
#### Steps to reproduce:
1. place a WarpDrive energy bank
2. fill the bank with energy by placing a EnderIO creative capacitor next to it
3. empty the bank with energy by placing an empty EnderIO capacitor next to it

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: EnderIO-1.7.10-2.3.0.424_beta-dev
- EnderCore: EnderCore-1.7.10-0.2.0.31_beta-dev
- Minecraft: 1.7.10
- Forge: 10.13.4.1490
#### Your most recent log file where the issue was present:

N/A

**Comment by MatthiasMann** [comment]
Umm - I don't know why you think the code is wrong - but it actually checks for IEnergyHandler first, and the EnergyHandlerPI  class is both input and output.

**Comment by LemADEC** [comment]
EnergyHandlerPI is missing all the implementations to handle an energy provider.

PowerHandlerUtil assums you can be both IEnergyReceiver and IEnergyProvider which is incorrect as reported in the API comments here: https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/cofh/api/energy/IEnergyHandler.java#L15

**Comment by LemADEC** [comment]
I've got confused with another bug in my mod, there's indeed no missing in EnergyHanderPI. I've updated the original post accordingly.

**Comment by Barhandar** [comment]
>but it actually checks for IEnergyHandler first

Didn't that get deprecated as separate interface and is now just a shorthand for receiver+provider?

**Comment by LemADEC** [comment]
yes, that's the object of this issue and the related pull request
