### ISSUE TITLE
[Edited] Painted conduit facade causes crash

### ISSUE THREAD

**Issue by HaruDasom** [SleepyTrousers/EnderIO#3251]
#### Issue Description:
4 members play on my server. Let them A, B, C, and D(It's me). A and D don't crash, but B and C crash when they come close to our village. B and C don't crash at first time, but they have started crashing since we develop our village.

First time, we play with EnderIO 1.7.10-2.2.8-381. However, they still crash despite updating almost all mods and Kcauldron that we play with.

※ OS of each members' computers
A : windows 10
D : windows 7

B : windows 8
C : windows 8

#### What happens:
when they enter the world, MC immediately crashes and show them only crash report.

I tries to move their characters far from our village. It prevents them from crashing, but they still crash near the village.

#### What you expected to happen:
I suppose that some machines cause crash, especially Ender IO's conduits or conduit facades because I could see 'enderio's, 'conduit's, and 'conduitbundle's on crash report.

**[[Update]]**
Now I have figured out what causes crash. I made a cactus with **painted conduit facades**, which are cause crash.

#### Steps to reproduce:

I don't know how to reproduce it right now, but I'll update it as soon as possible.

**[[Update]]**
1. Paint conduit facades with painting machine
2. Build something large (I found that small building doesn't cause crash)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO 1.7.10-2.2.8-381 and 1.7.10-2.3.0-442
- EnderCore: EnderCore-1.7.10-0.2.0.32_beta
- Minecraft: 1.7.10
- Forge: 1.7.10-10.13.4.1614

#### Your most recent log file where the issue was present: 

http://pastebin.com/fvfE7uLK

**Comment by HenryLoenwind** [comment]
see #2856
