### ISSUE TITLE
Crash when inserting a capacitor into a Sterling Generator

### ISSUE THREAD

**Issue by kd8lvt** [SleepyTrousers/EnderIO#3254]
#### Issue Description:
Crash on putting a Capacitor (in my case Octadic) into a sterling generator. Not tested on any other machines.

#### What happens:
It crashes with this log. The mod-list is included as well: http://pastebin.com/xt2dc08M

#### What you expected to happen:
I expected the capacitor to go into the capacitor slot (yes I was putting it in the slot under the power gauge) and increase power yield and fuel consumption, as per usual.

#### Steps to reproduce:

1. Make a Sterling Generator and Octadic Capacitor (or grab them from the creative menu)
2. Put the Capacitor in the Generator (note, it may require the generator to be running. Not sure.)
3. It should crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.8.9-3.0.0.20_alpha
- EnderCore: 1.8.9-0.3.0.13-beta
- Minecraft: 1.8.9
- Forge: 1.8.9-11.15.1.1808

#### Your most recent log file where the issue was present: 

http://pastebin.com/xt2dc08M

**Comment by kd8lvt** [comment]
Never mind, my fault, I gave myself an invalid capacitor with /give Though, that's another thought, maybe a failsafe for that sort of thing should be implemented?

**Comment by HenryLoenwind** [comment]
And another thought, maybe you could let us finish the functionality before putting a failsafe in?

And the other question: Why did you ignore the message about not reporting issues with unfinished functionality? I need to know how to change that message to something that actually works.
