### ISSUE TITLE
Fluid being voided with P2P Fluid Tunnels from AE2

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#3255]
#### Issue Description:
Fluid is being voided when inserting it with Fluid Conduits into P2P Fluid tunnels and extracting it on the other side into storage that is using the fluid, regulating the amount or not being able to transfer that much fluid.

#### What happens:
Fluid is being constantly drained from source when inserting into P2P tunnels with Fluid Conduits when the target storage is being constantly drained slower than the fluid is being inserted.

#### What you expected to happen:
Fluid not being voided at all. In the end there should be same amount of fluid as it was on input side

#### Steps to reproduce:

1. Connect tank with Pressurized Fluid Conduits into P2P Fluid tunnel
2. Connect IC2 Fluid Regulator (or anything else which is able to regulate the fluid amount passing though) and set the regulation to 1mB/t (or anything really low)
3. Put tank next to the regulator output
4. Start extracting the fluid
5. Fluid in the final tank will not match the amount of fluid at the start.

Screeshots:
Setup:
![2016-04-03_17 39 23](https://cloud.githubusercontent.com/assets/4236895/14233244/82990b02-f9c3-11e5-97b9-e72bcb212358.png)
![2016-04-03_17 39 39](https://cloud.githubusercontent.com/assets/4236895/14233249/974e2960-f9c3-11e5-8bc5-aed7a96290ee.png)
Begining of process (input tank with 16000mB of water, being extracted by fluid conduit):
![2016-04-03_17 39 31](https://cloud.githubusercontent.com/assets/4236895/14233267/e374df82-f9c3-11e5-93d4-e3111cbb8156.png)
Final (output tank with only 10000mB of water fed through IC2 Fluid Regulator set to 5mb/s, 6000mB is lost)
![2016-04-03_17 41 10](https://cloud.githubusercontent.com/assets/4236895/14233258/c520eb0c-f9c3-11e5-8d2d-d28f50b29b7b.png)

Also a video reproducing the issue (when transfering 256 buckets of liquid):
https://www.youtube.com/watch?v=5sf6j-GUdwA&feature=youtu.be
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.424_beta
- EnderCore: 0.2.0.32_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1566
- AE2: rv3-beta-5

#### Your most recent log file where the issue was present: 
NONE

**Comment by JasonMcRay** [comment]
workaround:
use one gt pipe between fluid conduit and p2p

**Comment by MatthiasMann** [comment]
The EIO fluid conduits only consume the amount of fluid which was accepted by the target:
https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/conduit/liquid/AdvancedLiquidConduitNetwork.java#L120

**Comment by tterrag1098** [comment]
The issue here must be something telling us it accepted more fluid than it really did. That is the only way a mismatch could happen.

**Comment by JasonMcRay** [comment]
Thing is this is a big cross mod thing. I am not sure where to look and what mod is the cause. Tests were done with IC2 and GT. Both were acting the same way. In GT the machine used was just turbine using up the LPG to produce fuel.
https://www.youtube.com/watch?v=rXwPFKkrJ_8&feature=youtu.be - is video of that

**Comment by HenryLoenwind** [comment]
Are you in single-player (or can you test this in single-player)? If so, I can make you a diagnostics build that will tell you exactly what's happening as far as Ender IO is involved.

**Comment by JasonMcRay** [comment]
Yes I am performing all the tests regarding my modpack in singleplayer, so I can test it with the diagnostic build.

**Comment by HenryLoenwind** [comment]
Good. I'll build it it tonight. That'll  be in about 6-8h.

**Comment by HenryLoenwind** [comment]
Here you go: http://loenwind.info/EnderIO-1.7.10-2.3.0.424t1_beta.jar

Diagnostics are in the logfile.

**Comment by JasonMcRay** [comment]
1st test one with P2p Tunnels in the same setup as in OP
- https://paste.ee/p/Aqm1N
- Fluid Difference (IN vs. OUT): 4410mB

2nd test was done without P2p Tunnel (directly inserted water into Fluid Regulator: 
- https://paste.ee/p/moisg
- Fluid Difference (IN vs. OUT): 0mB

3rd test was done with buildcraft Fluid Pipe in between the P2P and Fluid Conduit
(BC Tank -> Fluid Conduit -> BC Fluid Pipe (Golden) -> P2P IN -> P2P OUT -> Fluid Regulator -> BC Tank):
- https://paste.ee/p/tJPWt
- Fluid Difference (IN vs. OUT): 5000mB

4th test i just done with BC pipe and P2P tunnel. Fluid was voided as well. This time nothing from enderIO. So I guess we can safely assume, that there is something wrong with AE2 and P2P tunnels.

**Comment by JasonMcRay** [comment]
I was going to say no idea why its not happening with GregTech pipes... But just did a test to be safe, and its happening also with the workaround i posted above. The diff was not that big (only 83mB) but thats because the fluid was not always going through because of liquid sloshing.

**Comment by HenryLoenwind** [comment]
Yes. from the logs it looks like the P2P always accepts all fluid it is offered and voids what it cannot put anywhere.

**Comment by JasonMcRay** [comment]
Thanks for providing the debug build. Much appreciated.
Closing as not an eIO issue.
