### ISSUE TITLE
Placing a Energy Conduit in the world crashes the server to a unrecoverable state

### ISSUE THREAD

**Issue by Hund** [SleepyTrousers/EnderIO#3256]
I gave the new version a shot. This time I could place the Stirling Engine with success, so I proceeded to make a few other machines and then some Energy Conduits. But when I placed my first Energy Conduit the server crashed. And now it's in a unrecoverable state. - *Yay for backups!*

* Minecraft 1.8.9
* Forge 11.15.1.1808
* EnderIO 3.0.0.21
* EnderCore 0.3.0.13
* [latest.log](http://pastebin.com/ZBBDPLh8) [1]

As for the other mods, they are still the same version as noted in [my previous ticket](https://github.com/SleepyTrousers/EnderIO/issues/3248#issue-145226297).

[1]: This is the log from when I try to start the server after the first crash. For some reasone the log from the actual crash went missing.

**Comment by KitKat31337** [comment]
I am getting the same result here.  but anyone moving into the area with the conduit will crash out.

lastest.log -> http://pastebin.com/tbQUAkkP
FML-latest.log -> http://pastebin.com/sE9JHWpw

**Comment by KitKat31337** [comment]
Also to note specifically, I am also using the same versions listed above.

**Comment by magerooster** [comment]
I have the same issue. The initial server crash when placing a conduit was identical to KitKat's Could not initialize class crazypants.enderio.conduit.ConduitDisplayMode and every time I tried to restart the server, I got Hund's Ticking block entity / IconEIO crash.

**Comment by KitKat31337** [comment]
For the moment I was able to roll back to EnderCore 12 and EnderIO 19 to get my server up and running ok.  Eagerly awaiting this fix though.

**Comment by Hund** [comment]
Closed without feedback or confirmation from my side. What did I do to get you guys so pissed of?

**Comment by HenryLoenwind** [comment]
see my response to #3258

And no, I'm not upset. A bit annoyed, but not at you specifically but at the sheer number of reports in combination with the number of people who demand access to these alpha versions.

**Comment by Hund** [comment]
Ah. Well, I never demanded anything. :)

I though as these alpha builds are public I'd try them out. I'm fully aware of that alpha means that the shit could hit the fan at any time and I'm then all alone without any kind of support from you.

While I was using the alpha build I found a bug - as expected. I then searched among the tickets and I couldn't find a ticket related to my issue. So I thought I'd create a ticket to let you know about it, just in case you didn't know about it already.

I never demanded anything to be fixed or I never expected it to be fixed anytime soon. I was just trying to help. If you dont want people to report bugs on your testing branch, then you need to state this somewhere. :)
