### ISSUE TITLE
Activating Sound Locator Crashes The Game

### ISSUE THREAD

**Issue by dh47** [SleepyTrousers/EnderIO#3257]
#### What happens:
Activation of the sound location for use on the dark steel helmet crashes the game when the hot key to active it is used.

#### Steps to reproduce:

1. Craft the Dark Steel Helmet
2. Combine the Helmet with the note block to get the sound location ability 
3. Press the hotkey to activate the ability 

#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.8.9-3.0.0.21_alpha
- EnderCore: EnderCore-1.8.9-0.3.0.13-beta
- Minecraft: 1.8.9
- Forge: 11.15.1.1808

#### Your most recent log file where the issue was present: 

http://pastebin.com/rPbr9rJ4

**Comment by HenryLoenwind** [comment]
Please don't use features that are not yet ported to 1.8. Thank you.
