### ISSUE TITLE
[Suggestion] Disable infinite water source in Reservoir

### ISSUE THREAD

**Issue by skprime** [SleepyTrousers/EnderIO#3261]
My suggestion is very simple.

Some people (Like me) want to create hard to play modpacks, and there should be a boolean somewhere (For example in config file) to allow people disable infinite water source in reservoir (After filling with 2 buckets). I want to create modpack without infinite water sources. I'm able to disable minecraft's infinite water sources (Using other mods), but I'm not able to disable infinite water in reservoir.

**Comment by HenryLoenwind** [comment]
The config flag is named "reservoirEnabled".
