### ISSUE TITLE
Painted Clear Glass Client Crash

### ISSUE THREAD

**Issue by Siriuo** [SleepyTrousers/EnderIO#3262]
#### Issue Description:
Breaking painted quite clear glass

#### What happens:

Client crashes with error see below:
[crash-2016-04-06_22.29.15-client.txt](https://github.com/SleepyTrousers/EnderIO/files/207381/crash-2016-04-06_22.29.15-client.txt)

#### What you expected to happen:
Block to break with no crashing

#### Steps to reproduce:

1. Paint clear glass using the painting machine
2. Place block in the world
3. Break block
4. Client crashes to desktop
5. if multiple painted blocks are placed the client crashes upon login every time.

Appears to only happen when in survival.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.8.9-exp - Commit 3b9c3a7868611929defeeaef67e91bdec717d832 dated 06/04/2016 at 22:06 (UK - BST)
- EnderCore: 1.8.9  - Commit 7f36749dd696090257f64544434701dadd0edd3d dated 31/04/2016 (UK - BST)
- Minecraft: 1.8.9
- Forge: 11.15.1.1808

#### Your most recent log file where the issue was present: 

[crash-2016-04-06_22.29.15-client.txt](https://github.com/SleepyTrousers/EnderIO/files/207381/crash-2016-04-06_22.29.15-client.txt)

**Comment by HenryLoenwind** [comment]
got it
