### ISSUE TITLE
The game crashed because of EnderIO

### ISSUE THREAD

**Issue by shader301202** [SleepyTrousers/EnderIO#3264]
#### Issue Description:
I have no idea why, but my game crashed. In the crash log there was 
`	EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-5.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                  * The RF API that is being used (1.7.10R1.1.0 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from IC2NuclearControl-2.3.4a.jar).
                    It is a supported version, but that difference may lead to problems.`

Should I remove IC2NuclearControl and go back to the rv2 version of Applied Energistics?
#### What happens:
???

#### What you expected to happen:
???

#### Steps to reproduce:
1. I moved in Minecraft
2. The game crashed

____
#### Affected Versions
- EnderIO: 2.3.0.424_beta
- EnderCore: 0.2.0.32_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

#### Your most recent log file where the issue was present: 
https://paste.ee/p/lkkuR

**Comment by HenryLoenwind** [comment]
Please look at the crash, not the diagnostics that is printed out below the crash to help developers determine the state of your installation.

Which is in your case full of stuff interfering with each other. Try removing mods until it no longer crashes to find what is causing this. I'd start with LiteLoader.
