### ISSUE TITLE
Experience Obelisk desappear ?

### ISSUE THREAD

**Issue by Uranne** [SleepyTrousers/EnderIO#3269]
#### What happens:
The experience obelisk desappear

#### What you expected to happen:
After the fight with the dragon, we use it to store our levels. When I use my pickaxe to take it, it got sucks by something and desappear. We were near the end exit.

#### Steps to reproduce:

1. kill the dragon
2. put the obelisk on the floor
3. retake it and watch.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.424_beta
- EnderCore: IDK
- Minecraft: 1.7.10
- Forge: IDK
In the modpack FTB infinity reloaded

#### Your most recent log file where the issue was present: 

I don't have it, sorry, it was on a server.

**Comment by HenryLoenwind** [comment]
You might want to read the instruction text before you delete it:

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author.
