### ISSUE TITLE
[1.8.9] Powered Spawner Wither Skeletons Spawn with Bows??

### ISSUE THREAD

**Issue by oitsjustjose** [SleepyTrousers/EnderIO#3270]
#### Issue Description:
Wither Skeletons spawned via a powered spawner are spawned with bows instead of swords? Not a huge deal, just an observation ;D

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.8.9-0.3.0.13
- EnderCore: 1.8.9-0.3.0.13
- Minecraft: 1.8.9
- Forge: 11.15.1.1808

**Comment by HenryLoenwind** [comment]
got it. thx.
