### ISSUE TITLE
[1.8.9] Redstone Interaction Bugs

### ISSUE THREAD

**Issue by oitsjustjose** [SleepyTrousers/EnderIO#3271]
#### Issue Description:

Sorry, I know you guys are busy with 1.8.9 and its renderers + bigger things, but I thought I'd let you know about bugs as I find them just in case you weren't aware of them. Setting Redstone interaction in a Machine's GUI ignores actual Redstone in-world.

#### What you expected to happen:

Redstone Required: High should require a Redstone signal to run: applying a Redstone signal does not work.

#### Steps to reproduce:

1. Place down almost any EnderIO Machine
2. Set Redstone Required: High in the Redstone Config GUI
3. Give a Redstone signal and note that it doesn't work as intended

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.8.9-0.3.0.13
- EnderCore: 1.8.9-0.3.0.13
- Minecraft: 1.8.9
- Forge: 11.15.1.1808

**Comment by Xiaminou** [comment]
Works just fine for me, make sure you're applying a strong signal, Ender IO's machine do not detect weak redstone signals.

**Comment by oitsjustjose** [comment]
You're right. Machines didn't used to require strong signals, did they???

Oh well - closing.
