### ISSUE TITLE
Villager spawner 1.8

### ISSUE THREAD

**Issue by BuckitHead** [SleepyTrousers/EnderIO#3273]
#### Issue Description:
Villager soul vial will not go into soul binder with broken spawner. 

#### What happens:
will not allow villager spawner creation

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.8.9-3.0.0.24_alpha
- EnderCore: 3.0.13
- Minecraft: 1.8.9
- Forge:1855

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Thanks for confirming the configuration file works as expected.
