### ISSUE TITLE
endercore crash with sponge api

### ISSUE THREAD

**Issue by scootashy** [SleepyTrousers/EnderIO#3274]
hi endercore and ender io crash when ran on sponge with the voxel plugin also most plugins wont load up when ran and i narrowed it down to it happening only when endercore 1.8.9 is installed. running on latest forge with latest sponge. every other mod i tested it on with sponge worked. with endercore plugins like pex act like they ain't even there. is there a way endercore can be updated to be compatable with sponge?

**Comment by HenryLoenwind** [comment]
that template you deleted without reading was there for a reason
