### ISSUE TITLE
Conduits are missing background of "Insert/Extract/Disabled" selector

### ISSUE THREAD

**Issue by Barhandar** [SleepyTrousers/EnderIO#3275]
#### Issue Description:

Conduits no longer have the background on mode selector and the arrow color on the selector was switched from red to white. Because the selector text, aforementioned Insert/Extract/Disabled, is _white_ and the GUI is very light gray, it causes contrast issues and is aggravating. The file seemingly responsible is widgetsv2.png, but it cannot be manually overridden without editing as it has different layout from old/widgets.png.
EIO 2.2.8, background present: http://i.imgur.com/ReTFJtU.png
EIO 2.3.0, background absent:  http://i.imgur.com/Iv2WgSQ.png
#### What happens:

Missing selector background.
#### What you expected to happen:

Selector background not missing, allowing proper readability of white text.
#### Steps to reproduce:
1. Load 2.3.0+ version of EnderIO.
2. Place a conduit next to applicable block (for purposes of testing, Item Conduit and a chest were used)
3. Open connection GUI.

---
#### Affected Versions:
- EnderIO: Tested and confirmed background absence on 2.3.0.424_beta and 2.3.0_411_beta, tested and confirmed background presence on 2.2.8.381, presumed to exist on all 2.3.0 versions.
- EnderCore: Tested and confirmed absence with 0.2.0.33_beta and 0.1.0.22_beta, tested and confirmed presence with ttCore 0.1.1-78.
- Minecraft: 1.7.10
- Forge: Confirmed using 10.13.4.1558, non-confirmed using 10.13.3.1395.

**Comment by CrazyPants** [comment]
This has been fixed in 1.9.4
