### ISSUE TITLE
Bug with telepad

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#3276]
#### Issue Description:

When teleporting chestcart with Telepad across dimensions the items stored in the chest cart will get duped after teleport.

It doesnt happen for teleporting in the same dimension.
#### What happens:

When you move chestcart with items in on top of the Telepad and then initiate the teleport, the cart will teleport to designated cords in the specified dimension, the items in the chest cart will remain in the cart. But also the items will get spit on the ground on the place with telepad. This effectively dupes everything in the cart by spilling on the ground.
#### What you expected to happen:

Either the items spill on the ground, but will not get teleported with the cart. (this would be better, because for Cart teleporting we have ender rails/transceiver combo).
or
The items will get teleported with the cart, but no spillage on the ground. 
#### Steps to reproduce:
1. Build a Telepad
2. Set the coords for different dimension (for example nether)
3. Get Chestcart and fill it with items
4. move the chest cart on top of the telepad
5. initiate the teleport.
6. ???
7. Items contained in the chest cart will spill out on the ground
8. Chest cart will get teleported to other dimension still containing the items
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 2.3.0.424
- EnderCore: 0.2.0.32
- Minecraft: 1.7.10
- Forge: 10.13.4.1566
#### Your most recent log file where the issue was present:

None

**Comment by JasonMcRay** [comment]
Am I right to assume that this is not going to be fixed in 1.7? I read that 1.7 EnderIO development is closed?

**Comment by HenryLoenwind** [comment]
there will be a final release to fix some remaining bugs. We'll have to see if this one can easily be fixed. Also, as we are quite busy at the time, that may take a while.

**Comment by Eufranio** [comment]
a while like?
