### ISSUE TITLE
EnderIO + ComputerCraft not working

### ISSUE THREAD

**Issue by DarkIceXD** [SleepyTrousers/EnderIO#3279]
#### What happens:
Minecraft crashed when placed down Insulated Redstone Conduit on a ComputerCraft Computer. After you restart Minecraft you cant join the map anymore because it instantly crashes the game.

#### Steps to reproduce:

1. Place Computer
2. Place Insulated Redstone Conduit on it
3. Crash

____
#### Affected Versions:

- Minecraft 1.8.9
- forge 1.8.9-11.15.1.1808
- EnderCore-1.8.9-0.3.0.13-beta
- EnderIO-1.8.9-3.0.0.24_alpha
- ComputerCraft1.79

#### Crash Log: 

http://pastebin.com/pejw0Vfg

**Comment by Vexatos** [comment]
Which version of ComputerCraft are you using?

**Comment by DarkIceXD** [comment]
ComputerCraft1.79

**Comment by Vexatos** [comment]
Are you able to reproduce the issue with only the latest build of EnderIO and ComputerCraft present?

**Comment by DarkIceXD** [comment]
Removed all mods except ComputerCraft and EnderIO and still the same.
http://pastebin.com/Q5zpxn43

**Comment by Vexatos** [comment]
This is not `fml-client-latest.log`, this is a normal crash log.

**Comment by DarkIceXD** [comment]
Here you go:
http://pastebin.com/Bqkwww2x

**Comment by Vexatos** [comment]
The strange thing is, [EnderIO is calling the method correctly](https://github.com/SleepyTrousers/EnderIO/blob/1fd68472aef30f26572d6bbba678731ee49cf2ec/src/main/java/crazypants/enderio/conduit/redstone/RedstoneConduit.java#L263) and not as implied by the crash log. It has for a while now, but you appear to be using the correct versions of CC and EnderIO... Really strange.

**Comment by DarkIceXD** [comment]
Are you sure its the right method? Maybe the ComputerCraft API changed since 1.8.9?!

**Comment by DarkIceXD** [comment]
Are you sure its the right method? Maybe the ComputerCraft API changed since 1.8.9?!

**Comment by DarkIceXD** [comment]
Will the fix be available on jenkins?

**Comment by HenryLoenwind** [comment]
I'm in the process of making some bigger changes, and I'd prefer to not have a "half way through" build of those. So it'll be a couple of days until the next build.
