### ISSUE TITLE
Server tried to update attributes of a non-living entity

### ISSUE THREAD

**Issue by superdude808** [SleepyTrousers/EnderIO#3282]
#### Issue Description:
so it just casually crashes 
cause of an entity from enderio having it's
attributes updated when it's a non living entity 

#### What happens:
game freezes then closes leading
to the crash log being displayed on the launcher 
like with most if not all crashes that happen with minecraft

#### What you expected to happen:
it to run as it has been for a quite awhile with out anything going wrong

#### Steps to reproduce:

1.waiting for it to happen or directly on world load 

#### temporary fixes

going into mc-edit and deleting all loaded entitys in the area surrounding 
the player for that world save
____
#### Affected Versions
- EnderIO:1.7.10-2.3.0.424_beta
- EnderCore:1.7.10-0.2.0.31_beta
- Minecraft: 1.7.10
- Forge:10.13.4.1614-1.7.10-

#### log file
http://pastebin.com/NtPVy61y

**Comment by HenryLoenwind** [comment]
do you have a world backup where you can try mcediting? I'm interested in knowing if deleting any specific modded entity in the area solves this, or if it is the rocket itself.

**Comment by superdude808** [comment]
after using the crash log and mutiple copies of the world save to locate the location of the entity in question's location mc edit says theres only a vanila skeleton within a block or so distance to where the crash log places the rocket but after deleting all entities within a small 4 block radius of the rockets potential location i.e where the crash log says it is in minecraft coordinates x=-1805.88, y=30.00, z=1203.47 the save crashes on load giving me this crash log http://pastebin.com/6wxHuz76

**Comment by superdude808** [comment]
the crash log references the rocket again but in a different location which i going to have to track down

**Comment by mindforger** [comment]
besides not knowing what the actual cause may be @HenryLoenwind did you notice the origin of this call?

`at weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:104)`

**Comment by superdude808** [comment]
i have notified the author of the mod that is interacting with enderio like this and am waiting for a response have been tracking down the entity for awhile now using mcedit and trying to find exact coodinates in it is hard

**Comment by mindforger** [comment]
yeah i was just hinting it may be a right call at the wrong time, my guess was the "illegalstate" resulting from calling a method at a time which it is not designated to be called or not given the neccesary informations to run like expected

**Comment by HenryLoenwind** [comment]
The ReplacementMainThread thing is unrelated. That's way out in the game launcher area.

Just to be sure: Is there really a weather rocket where the crash says one should be?

Then: The relevant entities are listed with their locations in the crash log.

**Comment by superdude808** [comment]
have located the rocket listed in the new crash log but there is no entity in it's location which is concerning cause if the crash is being caused a non existent entity im going to cry cause herobine is supposed to be a bad creepypasta that went meme staus

**Comment by superdude808** [comment]
ok so is this rocket thing something im supposed have made/placed into the game world or is it a naturaly spawning thing? cause after some review of the rockets locations listed in the crash logs i have found nothing there but vanila skeletons but after deleting all the entities in a small 2 block radius of the entities locations the saves load fine and no longer crashes

**Comment by HenryLoenwind** [comment]
It is an entity created by the weather obelisk after a player pressed a button in its GUI. So you'd probably know if there should be one.

Now that help the matter immensely. We know that there is no weather rocket on the server, but the client tries to update one. That means the client and server are not in sync about the available entities. Check the configs of all mods that add entities to the game between server and client. At least one entity is enabled on the server but disabled on the client (or the other way around). I'd start with Ender IO's WitherSkeleton, then EnderZoo. For those mods I know that disabling the entity also disables registering it.

**Comment by superdude808** [comment]
ok i disabled all the ender zoo mobs via config and the wither skeleton replacement and that seems to have fixed it going to do some more tests with the other 5 identical world saves from when this first happened though it did fix itself at one point when i switched to peaceful for a bit to grab something in another world save  before i started doing stuff with configs  which should of indicated it was a problem with hostile mobs

**Comment by HenryLoenwind** [comment]
Yes, that sounds like configs not being in sync between server and client.

**Comment by superdude808** [comment]
judging by the fact it was skeletons/wither skeletons in the area of the false entity registration then it is probably the wither skeleton override doing it
