### ISSUE TITLE
1.8.9 Ender IO / Core

### ISSUE THREAD

**Issue by rcistano** [SleepyTrousers/EnderIO#3283]
There seems to be a problem. I cannot seem to get the Alpha/Beta for Ender IO / Ender Core to work with my 1.8.9

**Comment by rcistano** [comment]
Why was this closed without a solution?

**Comment by HenryLoenwind** [comment]
Because without any information on what you are doing, it would take me a couple of days to write down a solution. I'd have to start on how to power on a computer...
