### ISSUE TITLE
[1.8.9] Crash when updating to 3.0.0.25

### ISSUE THREAD

**Issue by Cobra1117** [SleepyTrousers/EnderIO#3285]
#### Issue Description:
EnderIO-1.8.9-3.0.0.25_alpha.jar crashes during startup, presumably due to an incompatibility with FTB Utilities.

#### What happens:
Server crashes on startup

#### What you expected to happen:
Server doesn't crash on startup

#### Steps to reproduce:
Unknown. Error occurred during upgrade to 3.0.0.25. (Note: Rolling back to 3.0.0.24 fixed the problem)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.8.9-3.0.0.25_alpha
- EnderCore: 1.8.9-0.3.0.14-beta
- Minecraft: 1.8.9
- Forge: 11.15.1.1808

#### Your most recent log file where the issue was present: 
http://pastebin.com/TGxfNXun

**Comment by HenryLoenwind** [comment]
Yes, that's why I recommended dismantling your machines before upgrading.

**Comment by Cobra1117** [comment]
@HenryLoenwind Hrm... I must have missed a block somewhere. Thanks for the info.

For everyone else who may be having this issue: Because I was unable to find all of the blocks, this was my fix:

1. Remove the EnderIO jar file from the mods folder
2. Start the world, fly around making sure chunks load where you had EnderIO items/machines
3. Exit the game
4. Add the new EnderIO jar file to the mods folder
5. Start the game
This _should_ fix the problem, although your EnderIO items/blocks will all be deleted.

**Comment by HenryLoenwind** [comment]
BTW: I'll release a new build later today that'll catch that error. The machine in question may have invalid data, but it won't crash anymore.

**Comment by Cobra1117** [comment]
Awesome! Thanks for the quick responses :-)
