### ISSUE TITLE
[1.8.9] Placing Teleporter causes server-side crash

### ISSUE THREAD

**Issue by Cobra1117** [SleepyTrousers/EnderIO#3286]
#### Issue Description:
Placing a teleporter block causes a server-side crash

#### What happens:
Server crashes

#### What you expected to happen:
Server doesn't crash

#### Steps to reproduce:
1. Place a teleporter block

____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: 1.8.9-0.3.0.14-beta
- EnderCore: 1.8.9-3.0.0.25_alpha
- Minecraft: 1.7.10
- Forge: 11.15.1.1808

#### Your most recent log file where the issue was present: 
http://pastebin.com/KAXvzuSw

**Comment by HenryLoenwind** [comment]
git it. thx.
