### ISSUE TITLE
Reinforced Obsidian + Thaumometer = Crash

### ISSUE THREAD

**Issue by ThePixelbrain** [SleepyTrousers/EnderIO#3290]
If you try to scan (or just even look at) a Reinforced Obsidian block with a Thaumometer you're Minecaft will crash. I tested it with EnderIO Version 2.0.32 and Thaumcraft Version 4.2.3.5 and the Infinity Evolved Skyblock Modpack.

____
#### Affected Versions

- EnderIO: 2.3.0.424
- EnderCore: 0.2.0.32
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

#### Your most recent log file where the issue was present: 

[http://pastebin.com/3B3iEpmP](url)

**Comment by HenryLoenwind** [comment]
Update EnderCore
