### ISSUE TITLE
FTB Infinity crashed because of EnderIO Block

### ISSUE THREAD

**Issue by FTBInfinityplayer** [SleepyTrousers/EnderIO#3291]
#### Issue Description:
My FTB Infinity Evolved crashed after I timed out. In my log is something about a EnderIO block. Can you say me, what I can do?

#### What happens:
FTB closed because of an Ender IO block.

#### What you expected to happen:
That somebody can say me, which block it is and how I can fix the problem and can play on the server again

____
#### Affected Versions (Do *not* use "latest"):

-FTB Infinity Evolved 2.5.0
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

http://pastebin.com/P8WeBimz

**Comment by HenryLoenwind** [comment]
Update EnderCore to the current version.
