### ISSUE TITLE
issue with computercraft and ender IO 1.7.10

### ISSUE THREAD

**Issue by CitiesXL2815** [SleepyTrousers/EnderIO#3293]
There problem with the capacitor bank not connecting to wired modem, right click modem doesn't turn red and tells you the code to put in the computer coding.

**Comment by MatthiasMann** [comment]
The new issue template is there for a reason - but yet you used deleted the template and did not provide any of the information required.

**Comment by CitiesXL2815** [comment]
how was i supposed to know that it was template, next time please say that it's template for bugs and issues in the notes. i was so confuse, but can i make same report with the template this time or no

**Comment by mindforger** [comment]
how could this very simple template be confusing, just read at least a few lines of it

**Comment by CitiesXL2815** [comment]
when your new to seeing this new template for the first time, they used to have no template before, i thought it was telling me the rules in reporting bugs so i deleted it and report my issue, but i was supposed to report it in the template, but Matt you said used deleted the template, please say nicely way next time when people are new and don't know it's template, best way say (The new template is there for a reason so we can help fix the problem of Ender IO) when people report without template please say that, but we will fix the problem, report the issue in our template next time, when say something like that gives people to use the template for the issue, but when you say to me (but yet you used deleted the template and did not provide any of the information required) it starts getting people in confused stage, next time say nicer way, i did not know about the template, now i do and the next time i report issue to report it in the template.
