### ISSUE TITLE
Unable to craft Machine Chassis after modifying the Config

### ISSUE THREAD

**Issue by Ra-Zim** [SleepyTrousers/EnderIO#3294]
#### Issue Description:
I made some adjustments to the config for Ender IO and do not recall making adjustments that would impact the Machine Chassis. I've gone through the config twice and either I'm blind or nothing should have disabled the ability to craft the chassis. The recipe is still present according to NEI; however, when attempting to craft it, the items required for the recipe simply go back into the player's inventory. I have "fixed" this by deleting the recipe and adding a new one via ModTweaker, but is still an issue.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.2.8.381
- EnderCore: N/A
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

#### Your most recent log file where the issue was present: 

Nothing shows in the logs, but here is the config, EnderIO.cfg: http://pastebin.com/XrpkRGGq

**Comment by MatthiasMann** [comment]
Did you look in NEI what materials are required? because you told it in your config:
B:useSteelInChassi=true
that you want to use steel for making chassis. This is the "normal" steel which is also used by mods like Mekanism and not the EnderIO electrical steel.

**Comment by Ra-Zim** [comment]
Yes, I did look at the recipe in NEI, two of my players did as well, it still required iron, but that would explain why it wouldn't craft.

**Comment by HenryLoenwind** [comment]
If a normal crafting recipe shows up in NEI but doesn't work and vice versa, that means that server and client configs are not in sync. While Ender IO does sync configs when connecting to a server, there are things where that does nothing---crafting recipes are registered with the game on startup.
