### ISSUE TITLE
cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by dabaer** [SleepyTrousers/EnderIO#3301]
#### Issue Description:
After updating to DragonAPI v13b, EnderIO crashes on both client and server. Because those mods are not referenced at all in the stack trace i'm posting here first.

#### Affected Versions (Do *not* use "latest"):
- EnderIO: 2.2.8.381, 2.3.0.425
- EnderCore:
- Minecraft: 1.7.10
- Forge: 1614

#### Your most recent log file where the issue was present: 
Latest FML client log: https://gist.github.com/dabaer/1dff4a750e418debc68163157f9b76eb

**Comment by mindforger** [comment]
could you please upload the crashlog located in the crashlog folder not the whole server/client-logfile?

located in your C:\Users\Jadenn\AppData\Roaming\.technic\modpacks\crux\crash-reports\crash-2016-05-12_19.02.54-client.txt

**Comment by HenryLoenwind** [comment]
Check your config file, the "travelStaffBlinkBlackList" contains an invalid value (one without ":"). Shame on Forge for crashing on it.

**Comment by dabaer** [comment]
@mindforger Everything in the crash log is already in the Forge log i posted verbatim.

@HenryLoenwind I don't see any invalid values in that list unfortunately :<

```
# Lists the blocks that cannot be teleported through in the form 'modID:blockName' [default: [minecraft:bedrock], [Thaumcraft:blockWarded]]
    S:travelStaffBlinkBlackList <
        minecraft:bedrock
        Thaumcraft:blockWarded
     >
```

Okay, I doubled back to Reika's Issue tracker and found the crash related to what you've suggested (for some reason when I searched that crash yesterday github returned no results here or there). I am getting the stack you see here on the client, but i'm also getting the stack trace from #3298 on the server side.

I thought it was an issue with Thermos that made the stack different but I assumed it was the same issue on both sides. Also, the configurations are identical (no seemingly invalid items in the list).

I'll leave this open and reference it in the other thread as the "client" side crash to this issue.

Regards,
Jadenn

**Comment by ReikaKalseki** [comment]
I think this one might be mine; there was a typo in a registry name. v13c is coming soon.

**Comment by tterrag1098** [comment]
It's a valid issue though, we should have more sanity checks on external data.

**Comment by HenryLoenwind** [comment]
I looked at Forge in multiple versions. I'd say when our code was first written, it was ok to call that constructor with a colon-less string. And in 1.8.9 it is ok again.

**Comment by ReikaKalseki** [comment]
WTF?

**Comment by HenryLoenwind** [comment]
No, first they simplified their parsing code to use String.split() (forgetting to check .length), then in 1.8.9 changed it so that it defaults to "minecraft:" if there's no mod id in the String.

**Comment by HenryLoenwind** [comment]
I think this should be clear now? Closing.

**Comment by pikkon38** [comment]
So what exactly is the fix here that I should be doing? Sorry I can't quite figure it out. I am still getting this crash with all my mods updated, but I don't understand what is wrong with the config

[crash-2016-06-01_09.28.20-server.txt](https://github.com/SleepyTrousers/EnderIO/files/293886/crash-2016-06-01_09.28.20-server.txt)

**Comment by pikkon38** [comment]
Yeah I have been trying all day with the latest Ender IO and the latest ChromatiCraft to no avail.

**Comment by bookerthegeek** [comment]
The fix is coming in the next update of either mod.

**Comment by dani485b** [comment]
And yet still waiting for an update on this topic since there's no workaround
