### ISSUE TITLE
[Suggestion][1.7.10] Add config options to change TelePad energy usage/energy buffer.

### ISSUE THREAD

**Issue by OneEyeMaker** [SleepyTrousers/EnderIO#3306]
Hello.
This suggestion is very simple: energy capacity, energy usage, and amount of receiving energy is hardcoded ([link](https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/teleport/telepad/TileTelePad.java#L56)).
Please, add config options to change these values.

Example: I want to make teleports more expensive (1M RF for inter-dimensional teleportation). But if I want to teleport tp another dimension, I should wait nearly a minute (1M RF / 1000 RF/t = 1000 ticks = 50 seconds.) It's not cool at all...

P. S. Sorry for my English, I'm from Russia.

**Comment by HenryLoenwind** [comment]
see https://github.com/SleepyTrousers/EnderIO/blob/1.8.9-exp/src/main/java/crazypants/enderio/teleport/telepad/TileTelePad.java#L65

**Comment by OneEyeMaker** [comment]
Hmm... That's interesting... But I'm asking about 1.7.10...

**Comment by OneEyeMaker** [comment]
@HenryLoenwind 
Please, see #3309

**Comment by HenryLoenwind** [comment]
@tterrag1098 is the maintainer, I'm just the poor guy who does the 1.8.9 port ;)
