### ISSUE TITLE
Item Count Bug (Inventory Panel)

### ISSUE THREAD

**Issue by zzApotheosis** [SleepyTrousers/EnderIO#3308]
#### Issue Description:
The inventory panel doesn't update item counts when items are extracted or inserted. However, it does update item counts when the item count increases from 0 to any value OR decreases from any value to 0.

You can see for yourself here:
https://drive.google.com/file/d/0B_wljXPJi507X2ZxRUFhV29sVFE/view?usp=sharing

You can also see in the video that the item count displays properly when re-accessing the Inventory Panel.

#### What you expected to happen:
Item count decreases when taking items out or increases when putting items in.

#### Steps to reproduce:

1. Build valid Inventory Panel system.
2. Experience bug.

#### Affected Versions:

- EnderIO: EnderIO-1.8.9-3.0.0.26_alpha
- EnderCore: EnderCore-1.8.9-0.3.0.14-beta
- Minecraft: 1.8.9
- Forge: 11.15.1.1902

#### Your most recent log file where the issue was present: 

https://drive.google.com/file/d/0B_wljXPJi507NlRfUlVpTkJwRjg/view?usp=sharing

And on a side note, I would vote to just skip over 1.8 for the most part since modded 1.9 is already available. I've heard that the 1.8 modding environment is a pain in the ass, anyhow.

**Comment by CrazyPants** [comment]
We have moved to 1.9.4  (first dev builds are up now) so I will close this. I am not sure what state the Inv Panel is in after the update.
Thanks for reporting.
