### ISSUE TITLE
Redstone conduits dont update properly

### ISSUE THREAD

**Issue by MisterObvious25** [SleepyTrousers/EnderIO#3311]
When using redstone(dust) together with redstone conduits of insulated redstone conduits, afters unpowering the redstone(dust) the conduits stay powered until you manually give it a block update. might be related to #2740 but not sure considering that one was fixed??

**#### What happens**:

The conduit does not update properly

**#### What you expected to happen**:

For the conduit to update properly

**#### Steps to reproduce**:
1. Place a redstone line
2. Connect a redstone conduit or Insulated redstone conduit to it
3. Power the redstone line(not the conduit)
4. Unpower the redstone line

**#### Affected Versions**:

Minecraft 1.7.10
Forge mod loader 10.13.4.1566-1.7.10
EnderIO 1.7.10-2.3.0.425
EnderCore 1.7.10-0.2.0.34

![2016-05-20_17 47 07](https://cloud.githubusercontent.com/assets/19491809/15433625/6425e7a2-1eb3-11e6-901c-f64de3e1813e.png)
![2016-05-20_17 47 17](https://cloud.githubusercontent.com/assets/19491809/15433624/6425be08-1eb3-11e6-980a-9faac517e891.png)
![2016-05-20_17 47 39](https://cloud.githubusercontent.com/assets/19491809/15433626/64261740-1eb3-11e6-82ac-01a423cf1afe.png)
![2016-05-20_17 47 51](https://cloud.githubusercontent.com/assets/19491809/15433627/64267b54-1eb3-11e6-91f0-12f4fabc55eb.png)

**Comment by SharkWipf** [comment]
Getting (I assume) the same issue on my 1.10.2 server. 
In my case I'm trying to power a row of adjacent redstone lamps with a row of insulated redstone conduits, all set to different colours, and all powered by a line of redstone connected to a redstone block (to be replaced with a daylight sensor eventually). 
When breaking the redstone at the start, not all lamps turn off. Most do, some don't. Repeating this process seems to have the same result with the same lamps misbehaving. 
I haven't tested it with a real line of lamps yet, in my test I've made a 15x15 "diamond" that I'm trying to power, but the effect should be the same. 
Can provide screenshots tomorrow if wanted.

**Comment by SharkWipf** [comment]
Has this been fixed, or was this closed for other reasons?  
Last time I checked the issue was still very much there, and I don't see a commit related to this issue,  although I might be overlooking it.

**Comment by HenryLoenwind** [comment]
I batch-closed all 1.7 tickets because there will be no new release for 1.7.

**Comment by SharkWipf** [comment]
Ah. Should I make a new ticket for this issue on 1.10.2 then?

**Comment by HenryLoenwind** [comment]
As the redstone conduit code is completely different between 1.7 and 1.10, that'd make sense...

**Comment by HenryLoenwind** [comment]
BTW, I just tried the setup from above with the current version and cannot reproduce the problem.
