### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by xM1ckiMan** [SleepyTrousers/EnderIO#3313]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### Steps to reproduce:

https://www.youtube.com/watch?v=ePY2GA2sFLI

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by XFactHD** [comment]
What about filling out the versions, etc? The issue template is there for a reason!
