### ISSUE TITLE
Forestry wood doesn't work with facades

### ISSUE THREAD

**Issue by implayin** [SleepyTrousers/EnderIO#3314]
#### Issue Description:
When painting facades with forestry wood, they render with a large ! in-world.

#### What happens:
After the update Forestry 4, all my balsa wood facades were just a white box with a large ! on them. They render just fine in the inventory.

#### What you expected to happen:
The facades look like the block they were painted with

#### Steps to reproduce:

1. Grab Forestry 4
2. Paint a facade with one of its wood planks.
3. Be disappointed by the look of these

#### Affected Versions
- EnderIO: 1.7.10-2.3.0.424_beta
- EnderCore: 1.7.10-0.2.0.34_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1566

#### Your most recent log file where the issue was present: 

don't think this will show up in log, but can provide one if requested

**Comment by HenryLoenwind** [comment]
That means that Forestry rejects to provide the block's texture when Ender IO asks for it. Nothing we can do here.
