### ISSUE TITLE
Alloy Smelter custom recipes didn't work

### ISSUE THREAD

**Issue by nidico100** [SleepyTrousers/EnderIO#3321]
#### Issue Description:
I would send the problem to the modpack creator, but I made it :D
I tried to change all copper ingots in my modpack to just one copper ingot, so you don't have tons of different ones in your chests.
The last thing I have to change, is that the EnderIO Alloy Smelter smelts the ores and the dust into the right copper and not the copper it currently does.
In the AlloySmelterRecipes_User.xml I added the following lines:

```
<AlloySmelterRecipes>
    <exclude>
        <itemStack oreDictionary="oreCopper"/> 
    </exclude>
    <recipeGroup name="Ingots">
        <recipe name="ingotCopper" energyCost="2000">   
        <input>
            <itemStack oreDictionary="oreCopper"/>
        </input>     
        <output>
            <itemStack modID="exnihilo" itemName="exnihilo.copper_ingot"/>
        </output>
        </recipe>
    </recipeGroup>
</AlloySmelterRecipes> 
```

But this didn't work. All ores are still smelted to Thermal Foundation copper. Even this recipe isn't removed as the <exclude> command should do. Anyone can help me?

#### What happens:
Custom Recipes for Alloy Smelter didn't work.

#### What you expected to happen:
All copper ores/dusts are smelted to ex nihilo copper, not thermal foundation copper.

#### Steps to reproduce:

1. Install the ftb mopack via packcode: thenewworld
2. Copy the lines from above into AlloySmelterRecipes_User.xml
3. Use NEI to see recipes

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.424_beta
- EnderCore: 1.7.10-0.2.0.31_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1558

**Comment by HenryLoenwind** [comment]
you are missing the ```<vanillaFurnaceRecipes>``` tag around the excludes. Look at your logfile, it should full or error messages.

**Comment by nidico100** [comment]
Oh my fault, i thought vanilla means vanilla minecraft, i will try it

**Comment by HenryLoenwind** [comment]
"recipes of the vanilla furnace" in contrast to "alloy smelter recipes"

**Comment by nidico100** [comment]
yeah now i understand, but i thought that are the recipes in the normal minecraft furnace

**Comment by HenryLoenwind** [comment]
yes, they are. the alloy smelter does both, normal smelting using the vanilla furnace's recipes and its own special (3-input) recipes. That's why there's an exclude list on the one hand and the possibility to change recipes on the other.

**Comment by nidico100** [comment]
one question is left, i see the recipe now ingame, but only with one ore not every ore of there ore dict, where's the problem?

**Comment by HenryLoenwind** [comment]
hard to say from here (with here me being at work and having only a web browser available ;) ). Maybe someone of the regulars could chime in? Otherwise I'd need to look at it tonight.

**Comment by nidico100** [comment]
the thing i don't unnderstand is, i changed any recipe to for example the ex nihilo copper, normal furnace and so on, but the alloy smelter still smelt it into thermal foundation O.o 
i just changed a dust smelting to something different and the alloy smelter directly noticed that and changed it too. But not to the wanted ingot..

**Comment by HenryLoenwind** [comment]
oh, yes. have a look at the OreDictionaryPreferences_Core.xml, too. Another problem with Ex Nihilo is that it, as I remember, registers its items after all the recipes are registered so they are not yet visible for us.

**Comment by nidico100** [comment]
is it possible to make minetweaker/modtweaker support for enderio? it would be ways easier :)

**Comment by HenryLoenwind** [comment]
there's nothing stopping them from adding support for ender io. We expose some imc messages that take the same xml as the config files...

**Comment by nidico100** [comment]
i hope they will add it :/ else i have to try on or remove all the last changes :/

**Comment by CrazyPants** [comment]
OreDictionaryPreferences_Core.xml should fix this for you

**Comment by nidico100** [comment]
`  <preference oreDictionary="ingotCopper" >
    <itemStack modID="exnihilo" itemName="exnihilo.copper_ingot" itemMeta="0" />
  </preference>`
this is what i added to oredict :/

**Comment by nidico100** [comment]
It's not working for me.. I don't get it working.
Can anyone help me?
I made a list of the 4 ingots, that have to be changed incl. all names of the items, that are affected
here's the list:
[Pastebin](http://pastebin.com/Y621Dsah)
