### ISSUE TITLE
Crash on server Start

### ISSUE THREAD

**Issue by 6J0ker9** [SleepyTrousers/EnderIO#3322]
#### Issue Description:
Server Crashed when updating to your newest dev build 
Running some hand picked mods but this is undeniably the culprit

#### What happens:
Crash when starting dedicated server

#### What you expected to happen:
It to start

#### Affected Versions (Do *not* use "latest"):

- EnderIO:.29 dev
- EnderCore: .21 dev
- Minecraft: 1.9.4
- Forge: 12.17.0.1922

#### Your most recent log file where the issue was present: 

Crash Report: http://pastebin.com/nkQHAbDs 

Forge Log: http://pastebin.com/sLfA12qH

**Comment by 6J0ker9** [comment]
Also singleplayer worked completely fine, only when starting the dedicated server did it crash.

**Comment by whatthedrunk** [comment]
Same thing is happening for me. Reverting back to yesterday's build seemed to work.

**Comment by 6J0ker9** [comment]
Yup, just thought this was definitely something that should be posted in issues 

I'll wait for those new fancy cables before I start the mod :P

**Comment by CrazyPants** [comment]
Fix will be in the next build.

Which fancy new cables are you talking about btw?

**Comment by 6J0ker9** [comment]
When i did test single player worlds I saw that the other types of conduits were ported over

**Comment by CrazyPants** [comment]
Fix is available now in version 3.0.0.30
