### ISSUE TITLE
General bugs in .29 alpha, just FYI

### ISSUE THREAD

**Issue by jubalearly** [SleepyTrousers/EnderIO#3323]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

Bug reporting for alpha .29 with endercore .21

Dimensional Transceiver does not work with power, does work with items, did not test with liquids,
The dimensional transceiver send/receive buggers do not fill up on the receiving transceiver under any circumstances.  

KillerJoe is wacky loud, sound appears broken.  Turning sound off in config does not work on killerjoe but does silence other machines.

attractor obelisk does not seem to work with blazes although I never tested blazes under 1.7.10 so maybe this never worked.

I have tested most of the other basic machines with great success.  Thanks.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4    .29 alpha
- EnderCore:1.9.4   .21
- Minecraft: 1.9.4
- Forge:12.17.0.1920

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by CrazyPants** [comment]
The attractor obelisk needs to be looked at. I like the idea but it is too difficult to get a reliable implementation for all the different mobs.

**Comment by CrazyPants** [comment]
Fixes are available now in version 3.0.0.30

Thanks for the reports
