### ISSUE TITLE
invisible Vat and broken recipe Nutrient destilation

### ISSUE THREAD

**Issue by tetkris** [SleepyTrousers/EnderIO#3324]
#### What happens: 
The Vat is invisible, but work. Do not work recipe Nutrient destilation. I have minecraft 1.710 and forge 0.2.0.32 forge 

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 0.2.0.32
- EnderCore:
- Minecraft: 1.7.10
- Forge: recomended

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by CrazyPants** [comment]
I am not sure what you are using, but there are no releases of EIO with a version anything close to that. Make sure you have the latest version from here: http://mods.curse.com/mc-mods/minecraft/ender-io
