### ISSUE TITLE
getExplosionResistance() returns too high value for blast resistant blocks

### ISSUE THREAD

**Issue by HenryLoenwind** [SleepyTrousers/EnderIO#3327]
_developer ticket_
#### Issue Description:

We return 2000 from getExplosionResistance() for blast resistant blocks because that is what is used for setResistance() for obsidian. However, for vanilla blocks that value is multiplied by 3 when being store in blockResistance and then divided by 5 when returned by getExplosionResistance(). So the correct value of obsidian actually is 1200.
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: all versions

**Comment by CrazyPants** [comment]
Fixed in 1.9.4
