### ISSUE TITLE
1.9.4-3.0.0.31_alpha randomly crashes while place water on lava

### ISSUE THREAD

**Issue by kreezxil** [SleepyTrousers/EnderIO#3328]
#### Issue Description:
I'm the pack author for Uno Niner Four Mega Pack, we're experiencing a random crashing issue on the client when place water down near lava. Obsidian is still made however.

#### What happens:
Client crashes.

#### What you expected to happen:
Client not to be crashed. 

#### Steps to reproduce:

1. place bucket of water down on block that is even level with top of lava
2. enjoy the crash if you are lucky (I don't know how to make that sound less crass)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.31_alpha 
- EnderCore: 1.9.4-0.4.0.21-alpha
- Minecraft: 1.9.4
- Forge: build 1922

#### Your most recent log file where the issue was present: 

http://pastebin.com/SQcRGa4L

**Comment by HenryLoenwind** [comment]
your description doesn't really fit the crash. We are crashing while processing a bucketFillEvent. So if you are really not filling a bucket, you need to report this to Forge.
