### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Imnuts7** [SleepyTrousers/EnderIO#3335]
#### Issue Description:

Refer to title.

#### What happens:

Refer to title.

#### Steps to reproduce:

1. Start Minecraft.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.31_alpha
- EnderCore: 0.4.0.21-alpha
- Minecraft: 1.9.4
- Forge: 12.17.0.1926

#### Your most recent log file where the issue was present: 

https://gist.github.com/Imnuts7/efe4c8f5c6832a088567620133b3a7b1

**Comment by Serifina** [comment]
I'm also having the same crash. Crashlog [here](https://gist.github.com/Serifina/f279fff24de756217db41bc775847fa0). Forge 1925 instead of 1926, but it's pretty much otherwise identical.

**Comment by CrazyPants** [comment]
This is due to a change in forge 1.9.4-12.17.0.1925
I am looking into now but you can use a previous version on forge until then

**Comment by CrazyPants** [comment]
I have raised an issue on forge for this one:
https://github.com/MinecraftForge/MinecraftForge/issues/2924

I have disabled the registration of I crash callable for now to resolve the issue. Will be working again in the next build.

**Comment by CrazyPants** [comment]
Fixed in forge version 12.17.0.1932
