### ISSUE TITLE
[1.9] Item conduits have no support for IItemHandler

### ISSUE THREAD

**Issue by raoulvdberge** [SleepyTrousers/EnderIO#3337]
#### Issue Description:
I might be wrong here but on EnderIO for MC 1.9.4 item conduits do not connect to non-`IInventory` tiles.

This is a problem for mods that use `getCapability` and return a `IItemHandler` on their tiles.

https://github.com/SleepyTrousers/EnderIO/blob/1.9/src/main/java/crazypants/enderio/conduit/item/ItemConduit.java#L446

`getExternalInventory` doesn't check for `getCapability`.

#### What happens:
Connect a item conduit to a tile that uses capabilities, there is no connection.

#### What you expected to happen:
There should be a connection.

#### Steps to reproduce:

1. Place the block that has no `IInventory` on their tile
2. Connect a conduit

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.32_alpha
- EnderCore: 1.9.4-0.4.0.21-alpha
- Minecraft: 1.9.4
- Forge: 1932

**Comment by CrazyPants** [comment]
This a reasonably big job, but it should be done 'soon' : )

**Comment by CrazyPants** [comment]
Would you be able to test with build 34+ from here: http://ci.tterrag.com/job/EnderIO-1.9.4/
I have added support but it is not well tested yet.

**Comment by raoulvdberge** [comment]
Will do, thanks for the quick fix.

**Comment by raoulvdberge** [comment]
It seems to be working in my initial tests, didn't test thorough enough so I suggest you leave this issue open. Thanks again!
