### ISSUE TITLE
Conduits dont place

### ISSUE THREAD

**Issue by 6J0ker9** [SleepyTrousers/EnderIO#3338]
#### Issue Description:
Problem with conduits

#### What happens:
When placing Conduits they never actually place, and or leave my inventory

#### What you expected to happen:
The conduits to place

#### Steps to reproduce:

1.Place conduit
2.Breaking will result in a invisible block
3.It never left your inventory in the beginning
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: .32
- EnderCore: .21
- Minecraft: 1.9,4
- Forge:  1.9.4-12.17.0.1922

#### Your most recent log file where the issue was present: 

Forge Log: http://pastebin.com/G7C3W5LF

**Comment by 6J0ker9** [comment]
Someone close this didnt know forge had a new version

**Comment by HenryLoenwind** [comment]
gah, I nearly clicked on "reopen issue" to close it for you ;)
