### ISSUE TITLE
(Closed Old one by Mistake) Server side conduits

### ISSUE THREAD

**Issue by 6J0ker9** [SleepyTrousers/EnderIO#3339]
#### Issue Description:
Conduits wont place server side

#### What happens:
On servers Conduits do not place properly

#### What you expected to happen:
It to place

#### Steps to reproduce:

1.Place Conduit on server, attempt to use/break

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: .21
- EnderCore: .32
- Minecraft: 1.9.4
- Forge: 1.9.4-12.17.0.1922-1.9.4

#### Your most recent log file where the issue was present: 

http://pastebin.com/G7C3W5LF

**Comment by CrazyPants** [comment]
Do you mean, when connected to a server you cannot place conduits, but it works fine in single player?
Do you get any error messages?

**Comment by 6J0ker9** [comment]
Yes I do, seems identical to the one in the forge log I posted

**Comment by CrazyPants** [comment]
This should already be fixed. Can you try the latest build here: http://ci.tterrag.com/job/EnderIO-1.9.4/
and let me know if it is resolved?

**Comment by 6J0ker9** [comment]
No it seems :P

**Comment by 6J0ker9** [comment]
This is what appears in the console

**Comment by 6J0ker9** [comment]
http://pastebin.com/hkgCNB97

**Comment by 6J0ker9** [comment]
Is this problem just for me? or is it just that no one is using a server?

**Comment by CrazyPants** [comment]
Sorry, I stuffed up and forgot to kick off the build server, so .34 didn't have the fix.I have just started the build now so .35 should be done soon and that should resolve the issue

**Comment by 6J0ker9** [comment]
Seems to have fixed it thanks :D
