### ISSUE TITLE
[1/9/4] EnderIO SAGMill Dusts not smeltable

### ISSUE THREAD

**Issue by kwpugh** [SleepyTrousers/EnderIO#3340]
#### Issue Description:
I'm the modpack owner and server owner.  We are experiencing an issue with the SAGMill create EnderIO dusts from ores (i.e. gold, iron, etc.) that cannot be smelted in the AlloySmelter or any other furnace in the game (vanilla or modded).

#### What happens:
Dusts created in SAGMill are not smeltable

#### What you expected to happen:
Expected them to be meltable

#### Steps to reproduce:

1.put ore block in SAGMill and it outputs EnderIO dust
2.Put EnderIO dust in AlloySmelter
3.Nothing happens, machine won't process dust
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.9.4-3.0.0.32_alpha.jar
- EnderCore:EnderCore-1.9.4-0.4.0.21-alpha.jar
- Minecraft: 1.9.4
- Forge:1924

#### Your most recent log file where the issue was present: 

https://gist.githubusercontent.com/kwpugh/16a8981ecfb13f7f61f5b78dfb32d583/raw/f48a717044c8907e9c855046f94bb818a67ed81a/gistfile1.txt

**Comment by b0bst3r** [comment]
Use the latest build - http://ci.tterrag.com/job/EnderIO-1.9.4/

**Comment by kwpugh** [comment]
Testing now.

**Comment by kwpugh** [comment]
Iron, gold, lead, silver work.   EnderIO copper and tin dusts do not, nor aluminum from TechReborn.

**Comment by kwpugh** [comment]
My base ore mods are TechReborn and FunOres.

**Comment by b0bst3r** [comment]
Other dusts wont work until a later EIO version, it's a known issue.
