### ISSUE TITLE
[1.9] Updated Russian Translate

### ISSUE THREAD

**Issue by xMrVizzy** [SleepyTrousers/EnderIO#3341]
#### Issue Description:
Hello! I updated Ender IO ru_RU.lang translate, I'm man which translate so many mods, and I have experience. But when I saw previous translation, I was furious from the terrible translation from former translators! And I fixed many lines, and added new 1.9 lines! Now translation became many times better!
____
#### Affected Versions:

- EnderIO for Minecraft: 1.9

[Download 1.9 RU BEST Translation!](https://drive.google.com/file/d/0Bz1oau056ysIUV9WYVh1cFVBTFk/view)

**Comment by xMrVizzy** [comment]
By the way, I also do [Faithful 1.9, 1.10](http://minecraft.curseforge.com/projects/faithful-1-10), which has 263,266 downloads which guarantees my skills :)

**Comment by CrazyPants** [comment]
Thanks very much. This will be in the next build.

**Comment by xMrVizzy** [comment]
Okay!
