### ISSUE TITLE
IMPORTANT MAJOR AND GENERAL BUG (1.9 and 1.9.4) : Catched unhandled exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by Hypsellis** [SleepyTrousers/EnderIO#3342]
IMPORTANT : THIS BUG IS GENERAL TO ALL THE MODS OF MINECRAFT 1.9 and 1.9.4
-------------------------------------------------------------------------------------------------------------------------------

A strange bug happens when a tile entity is destroyed, Almost all the time an exception is thrown when the bug happens : Catched unhandled exception  [name of the tile entity] java.lang.NullPointerException 
For some particular blocks, Minecraft totally freezes and finished to crash with the error code -805306369 without any crash report. Here is the list of all the blocks wich are confirmed to provocate Minecraft to freeze and crashs with this error.

- Building Brick : all the glass, ice and packed ice blocks
- Deep Resonance : resonant crystal
- Biomes O Plenty : celestial crystal
- Botania : mana prism
- Blood Arsenal : blood stained glass block and pane
- Evilcraft : darktank
- EnderIO : killer joe, zombie generator, all the fused quartz glasses
- Random Things : lapis lamp, quartz lamp, rainbow lamp, biome glass, spectre block, fluid display

All these blocks follow the same error, only the name of the tile entity between the [ ] changes. Here is an example of how the error happens. The example is made with the resonant crystal of deep resonance. This is a full log and contains the launching of minecraft and the loading of a world, the moment where I brick the block and the bug happens is the moment where the exception [class com.hea3ven.buildingbricks.core.tileentity.TileMaterial] java.lang.NullPointerException is thrown : http://pastebin.com/KhwV1WKg

-------------------------------------------------------------------------------------------------------------------------------

Moreover some tile entities wich has brokner provocates Minecraft to totally crash with a crash report. Here is the list of all the block concerned and their crash report

- EvilCraft : box of eternal closure http://pastebin.com/JzRYf5Ex
- Cooking for block heads : fridge and oven http://pastebin.com/vcmx49qn http://pastebin.com/6zd4qq5w
- Storage Drawers : framing table http://pastebin.com/3077W3Wz

-------------------------------------------------------------------------------------------------------------------------------

I let you know that all the tests possible has already been made before I create this general issue and post it. I already tried to :
- Test the mod one by one only by installing them and forge without any other mods
- Change of Forge Version
- Change between the 1.9 and 1.9.4 version
- Change of mod version
- Play without optifine and any shaders
- Switch between the creative and survival mode
Nothing of all that change anything, the bug still happens in the same way for the same blocks listed at the top. 

-------------------------------------------------------------------------------------------------------------------------------

I precise that almost all the mods in Minecraft 1.9.4 and 1.9 are touched by this bug, because even if they don't provocate Minecraft to freeze or crash, almost always at each time a tile entity is broken, the exception Catched unhandled exception  [name of the tile entity] java.lang.NullPointerException is thrown.
I precise too that the list of all the tile entities listed at the top can be incomplete. I want you know that I tried to break block by block all the blocks of almost all the most popular mods on 1.9.4 and 1.9, so for summarizing something like 50 mods with more than 2000 blocks. So it's possible that I missed some blocks.
It's why I send this issue to all the mods even if no ones of their block are concerned by the bug.
I invite all the mod developpers to try by themselves to break all the tile entities of their mod for seeing they provocate the throwing of the exception, and maybe causes Minecraft to freeze.

**Comment by HenryLoenwind** [comment]
spam

**Comment by Hypsellis** [comment]
This isn't spam O____o'

**Comment by williewillus** [comment]
Saying ZOMG IMPORTANT MAJOR and then posting the same ticket to 15 other mods' trackers is pretty spammy

**Comment by b0bst3r** [comment]
And http://pastebin.com/KhwV1WKg doesn't even have Ender IO in the bloody log file. talk about waste mod devs time

**Comment by Dhvagra** [comment]
if 15 mods have the same problem with you, couldn't the problem lie with you?

**Comment by Hypsellis** [comment]
I just try to warn the maximum of people the presence of this bug. This bug touches many mods.
Do you really think that I take to try all the blocks of 50 mods one by one for seeing if they provocate the bug, and then write a pretty well described presentation of the bug to all the potential mods touches by this bug ?
I passed one week to try all the block one by one for seeing wich one provocated the bug. To try the mods alone with only Forge, to change the Minecraft and Forge version for seeing if it changed something.

**Comment by XDjackieXD** [comment]
Then why are you the only one able to reproduce it?

**Comment by HenryLoenwind** [comment]
To be a bit productive: This message is produced by WAILA. And it is produced in the network thread, where no code is allowed to access the world, let alone talk to any tile entity. So I'd recommend you report it to WAILA: https://bitbucket.org/ProfMobius/waila/issues?status=new&status=open

**Comment by AnrDaemon** [comment]
![popcorn](http://www.elite-games.ru/conference/images/smiles/show.gif)

**Comment by Hypsellis** [comment]
Ok think what you want. You can think that I'm a spammer, I don't really care. I don't want to anger me with things like that. I toke a lot of time and made a lot of different tries before to write this issue and inform many developpers to the existence of this issue wich touches many blocks of many mods. But it seemed to be useless.

**Comment by raoulvdberge** [comment]
You don't have to inform "many developers", you have to inform the developer that caused the bug. Why would EnderIO care about a bug that is caused by WAILA?

**Comment by Hypsellis** [comment]
Because the bug happens even without Waila.

**Comment by AnrDaemon** [comment]
If it is reproducible without EnderIO, without WAILA, without… anything, then… report it to Mojang, k?

**Comment by Hypsellis** [comment]
Have you even readed what I had written, I had described wich blocks was touched by the bug, and there EnderIO blocks wich provocated this bug.

**Comment by AnrDaemon** [comment]
Dude, you're digging your own grave.
Nobody care what you write until you start reading what people are replying to your nonsense.
Right now you have two and only two choices:
1. Get outta here by yourself, and report the issue where it belogs.
2. Get booted for being a nuisance.

**Comment by Hypsellis** [comment]
Waila isn't linked to the bug because even when EnderIO is alone, the beug happens for the blocks I had specified. But anyway it's useless that I justify me here because everybody think that I'm wrong and did it only for the fun of spamming, like if I had only that to do in my life...

**Comment by HenryLoenwind** [comment]
So, get me a log without WAILA and I'll look into it

**Comment by Hypsellis** [comment]
I tried it with only EnderIO installed on the last 1.9.4 Forge version. The bug still happens for the same blocks, here I tried it by breaking a fused quartz block. http://pastebin.com/qMChpNSY
I can't give you more informations, I don't get any crash reports.

**Comment by HenryLoenwind** [comment]
ok, so that message you quote is totally unrelated to your problem. A nice Red Herring.

http://hopper.minecraft.net/help/exit-code/code-805306369/

**Comment by Dhvagra** [comment]
lol. So, what have you learned, @Hypsellis? ;)

**Comment by Hypsellis** [comment]
It's impossible, I have 16 Go, I set my instance to 12 Go, and Minecraft only uses 6 to 8 Go. If you don't trust me, you can see it by yourself. 
![capture](https://cloud.githubusercontent.com/assets/17103411/15636464/f68dc346-25ff-11e6-8caf-afffdea29e39.PNG)

**Comment by williewillus** [comment]
It's what mojang's article says

**Comment by Dhvagra** [comment]
yeah 12 is ridicilously high. max that to 5 or 6.

**Comment by Hypsellis** [comment]
Yeah maybe it's too hight, but it's surely not because it's too hight that this bug happens.
