### ISSUE TITLE
Farming station will not accept TechReborn rubber saplings.

### ISSUE THREAD

**Issue by varukasalt** [SleepyTrousers/EnderIO#3345]
Issue Description: Farming station will not accept TechReborn rubber saplings. It will also not harvest manually planted rubber trees. It will remove the leaves, but will not harvest the wood. 

What happens: Leaves from manually planted TechReborn rubber trees are harvested, but wood is not. Saplings are not accepted for planting.

 What you expected to happen: Expected farming station to accept TechReborn rubber sapling for planting. It would not accept. Expected farming station to harvest TechReborn rubber tree. Only leaves were harvested. 

Steps to reproduce: No special steps required. Normal use of machine.

EDIT : I mistakenly labeled as 1.7.  Bug is occurring in 1.9.4

 Information updated.

1.Attempt to place TechReborn rubber sapling in Farming station for planting
2.Farming Station will not accept sapling for planting.
3.
...

____
#### Affected Versions (Do *not* use "latest"): 1.9.4-3.0.0.35_alpha

- EnderIO: 1.9.4-3.0.0.36_alpha
- EnderCore: 1.9.4-0.4.0.23-alpha
- Minecraft: 1.9.4
- Forge:1.9.4-12.17.0.1932-1.9.4

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Farming Station support for modded plants has not yet been ported to 1.9

**Comment by varukasalt** [comment]
Thanks. Appreciate the response.

**Comment by HenryLoenwind** [comment]
Oh, I completely forgot. I added the IDs to the Framing Station a while ago, so this might work now. Could you give it a test? Thx.

**Comment by varukasalt** [comment]
Still not working. Tried TechReborn rubber saplings and Industrial Craft rubber saplings (<this is the one I really need). Neither are accepted.

**Comment by varukasalt** [comment]
Still not working in 1.10 

Thanks.

**Comment by varukasalt** [comment]
EnderIO-1.10-3.0.0.50_alpha

Still no workey.

Thanks.

**Comment by varukasalt** [comment]
1.10-3.0.0.51_alpha

Nope. :(

Please?

**Comment by varukasalt** [comment]
1.10-3.0.0.55_alpha

Still no go. 

Status update please? Thank you.

**Comment by varukasalt** [comment]
1.10-3.0.0.60_beta

Nope.

**Comment by HenryLoenwind** [comment]
They should work now. Make sure to supply the Framing Station with a treetap.

**Comment by varukasalt** [comment]
Working with TechReborn saplings, but not IndustrialCraft 2

**Comment by varukasalt** [comment]
Also does not harvest the wood, only leaves and the sap. I guess that's intentional?

**Comment by HenryLoenwind** [comment]
yes

**Comment by varukasalt** [comment]
Now working! Thank you!
