### ISSUE TITLE
(Suggestion) Dimensional Transceiver with gas

### ISSUE THREAD

**Issue by oddalucard** [SleepyTrousers/EnderIO#3346]
I use Mekanism which has a lot of gas types and even though in the latest a version of wireless transporter that can handle gas I prefer the multiple channels of the dimensional transceiver so it would be great if something with multiple channels could be implemented for gas on the dimensional transceivers.

**Comment by CrazyPants** [comment]
Thanks for the suggestion. I would be open to merging a PR with this functionality but I am not planning on adding this functionality myself.
