### ISSUE TITLE
[1.9] Render Bug

### ISSUE THREAD

**Issue by xMrVizzy** [SleepyTrousers/EnderIO#3351]
#### Issue Description:
Look at the picture. Menu on the second screen render double left image on first screen

#### Affected Versions:

- EnderIO for Minecraft: 1.9

![9159ebb5bfb19346c2d8fdd59520059f](https://cloud.githubusercontent.com/assets/7906418/15675743/c15eccb6-275c-11e6-9ed3-83a0eae9effa.png)
![7c1cc0104c728336d988ff9de9ce943e](https://cloud.githubusercontent.com/assets/7906418/15675745/c46e5b9c-275c-11e6-9e37-cd473ce36ef0.png)

**Comment by HenryLoenwind** [comment]
That's a problem with the texture pack.

**Comment by xMrVizzy** [comment]
@HenryLoenwind no. I checked

**Comment by xMrVizzy** [comment]
It's not texture pack problem it's ui bug.

**Comment by xMrVizzy** [comment]
This bug with many machines, but transiver doesn't :)
![d32d995edd24c2a9f5a1e14372cddf4e](https://cloud.githubusercontent.com/assets/7906418/15689558/feb66466-2798-11e6-8247-cc18da58bb76.png)

**Comment by CrazyPants** [comment]
The power monitor looks fine with no texture pack:
![screenshot 2016-06-01 14 21 56](https://cloud.githubusercontent.com/assets/5211188/15700080/62c3ffde-2804-11e6-9df3-3589f6f08a03.png)

As such, it is definitely a resource pack issue.

**Comment by 4rz0** [comment]
Are the tabs on the power monitor longer than the one on the transciever?

**Comment by tterrag1098** [comment]
He is not wrong, they render differently. It is an inconsistency and makes texturing difficult.

**Comment by HenryLoenwind** [comment]
I'l redo those tab graphics. I wanted to go over the tab code anyways.

**Comment by HenryLoenwind** [comment]
For anyone who wants to texture the tabs with the news system:

There are now 3 textures that are rendered above each other. Lowest layer is the background (3rd "row' on the icon sheet). It will be rendered left-aligned, overlapping the main window by 3px and will be 3px shorter than the tab width. For inactive tabs those pixels will be skipped. Next is the left side (2nd texture). It will be rendered the same way as the background. Last one is the right side. It will be rendered right-aligned, 3px shorter than the tab width (meaning it will not overlap the main window).

Depending on your border style you may not want the left or right texture to render all the way. In that case just delete most of one of them. You only need the outermost 3px, the rest is overlapped.

If there's a need for it, it'll change the background texture u-mapping to align with the main texture's width. But for this I'd have to know the tiling grid size of your background (or make a texture that is as wide as possible).
