### ISSUE TITLE
[1.9] UI Experience Obelisk and Crafter

### ISSUE THREAD

**Issue by xMrVizzy** [SleepyTrousers/EnderIO#3352]
#### Issue Description:
Crafter (Right Side) and Experience Obelisk (Down Side) need render on 1 pixel more.
____
#### Affected Versions (Do *not* use "latest"):
- EnderIO for Minecraft: 1.9

![29fcc9d951be578315a9950f4b387f72](https://cloud.githubusercontent.com/assets/7906418/15689717/c07d0898-2799-11e6-9734-f6a90d721dad.png)
![a0dc4221f8938b07b7e783434fd5e440](https://cloud.githubusercontent.com/assets/7906418/15689718/c07d2f62-2799-11e6-8ddf-b131505a7328.png)

![0a73396e96555352eb16871aaf6ab835](https://cloud.githubusercontent.com/assets/7906418/15689722/c3e5dbe0-2799-11e6-9f14-85c794c84c67.png)

**Comment by HenryLoenwind** [comment]
again, your texture pack is off.

**Comment by xMrVizzy** [comment]
No...

**Comment by xMrVizzy** [comment]
I give you 16x16 version and 32x32

**Comment by xMrVizzy** [comment]
@HenryLoenwind you said it's texture bug: look at the screenshots first 16x16 vanila mod texture second my 32x32 faithful texture.
![2d1953c1bb14a7893a8f45c8ed0b008f](https://cloud.githubusercontent.com/assets/7906418/15690236/1470df18-279c-11e6-9309-1f902a5e7a0f.png)
![4877ef1c44d49a1f8df5584639689668](https://cloud.githubusercontent.com/assets/7906418/15690246/182582c6-279c-11e6-961f-054d60f5dd51.png)

**Comment by CrazyPants** [comment]
Whats the issue here?
Everything looks ok to me.

**Comment by tterrag1098** [comment]
I think you guys might need to get your eyes checked, lol. The black border is missing off the bottom. Our ySize is one pixel too small.

**Comment by xMrVizzy** [comment]
Yes ySize is one pixel too small. :)

**Comment by CrazyPants** [comment]
Even knowing what I am looking for it looks good to me!
Old man eyes I guess ;)
