### ISSUE TITLE
Server crash with 

### ISSUE THREAD

**Issue by pikkon38** [SleepyTrousers/EnderIO#3355]
#### Issue Description:
I am running Ender IO in my extremely large modpack called Modsplosion. It is semi private on the ATLauncher and this issue only occurs in servers.

#### What happens:
When installing Reika's Chromaticraft, I receive this crash report for servers only. Client side, everything works fine and as expected.

#### What you expected to happen:
Expected result is for the server to start up normally

#### Steps to reproduce:

1. Search for "modsplosion" in the ATLauncher and create a server
2. Open the mods folder and install Reika's ChromatiCraft 1.7.10 V13b (all dependency mods already installed)
3. Start server and observe crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.426_beta  &&  1.7.10-2.3.0.424_beta
- EnderCore: 1.7.10-0.2.0.35_beta &&   1.7.10-0.2.0.31_beta
- Minecraft: 1.7.10
- Forge: 1566

#### Your most recent log file where the issue was present: 

http://pastebin.com/qZcgR3f2

**Comment by HenryLoenwind** [comment]
see #3301
