### ISSUE TITLE
1.7.10 Crush

### ISSUE THREAD

**Issue by Leytek** [SleepyTrousers/EnderIO#3359]
I just update EnderIO from 1.7.10-2.3.0.422_beta to new version and get this:
http://pastebin.com/z8EnFzZA

Exactly same crush in any version from 424 to 426.

Then i delete all mods, and try only EnderIO:
http://pastebin.com/S8Hmmj5t

Seems same. So, what i am doing wrong ?
____

- EnderIO: EnderIO-1.7.10-2.3.0.426_beta
- EnderCore: EnderCore-1.7.10-0.2.0.35_beta
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by HenryLoenwind** [comment]
One of the Java libraries that ship with Minecraft exists in an unusually old version on your system. Is you Minecraft installation quite old by chance? When did you start it with the vanilla launcher for the last time?

Try starting a vanilla Minecraft with the vanilla launcher once. Maybe that updates that library.

**Comment by TheTemportalist** [comment]
You have a crush on 1.7.10 EnderIO??

**Comment by Leytek** [comment]
All your guesses are correct. I reinstall Minecraft. Now, it works fine. My mistake. Thanks for the help.

**Comment by HenryLoenwind** [comment]
No mistake there, just something we both didn't know or expect.
