### ISSUE TITLE
[1.7.10] Ticking Entity: Fallen Knight

### ISSUE THREAD

**Issue by perfect007** [SleepyTrousers/EnderIO#3361]
#### Issue Description:
Fallen Knight's occasionally (Not always) exhibit the Ticking Entity syndrome that crashes the server

#### What happens:
Server crash

#### What you expected to happen:
Fallen Knights should not crash the server

#### Steps to reproduce:

1. Find area full of mobs
2. Grind Mobs until crash
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:2.3.0.422
- EnderCore:0.2.0.31
- Minecraft: 1.7.10
- Forge:10.13.4.1558

#### Your most recent log file where the issue was present: 

http://pastebin.com/WeQfd3zK

**Comment by HenryLoenwind** [comment]
wrong project
