### ISSUE TITLE
[1.9.4] - [Crash]: java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by Lanse505** [SleepyTrousers/EnderIO#3362]
If Requested I can make a quick video showcasing the issue at hand, though it's pretty much straight forward.

#### What happens:
When breaking a EnderIO Conduit it crashes.
This Crashlog points towards Wawla and EnderIO however the crash occurs when breaking the EnderIO Conduit not when looking at it. Thus I'm reporting it to both Devs.

#### What you expected to happen:
I'm expecting it to break without a crash :P 

#### Steps to reproduce:

1. Break EnderIO 
2. Crash
3. .... Profit?

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.36
- EnderCore: 1.9.4-0.4.0.23
- WAILA: 1.7.0-B3_1.9.4
- WAWLA: 1.9.4-2.2.1.190
- Minecraft: 1.9.4
- Forge: 12.17.0.1940

#### Your most recent log file where the issue was present: 

http://pastebin.com/QSPuUhB2

**Comment by HenryLoenwind** [comment]
this has been fixed 19 hours ago. thx anyways
