### ISSUE TITLE
Autonomous Activator (Suggestion)

### ISSUE THREAD

**Issue by idevicerhelper** [SleepyTrousers/EnderIO#3363]
Please Ender-IO coders, make a machine that right clicks and left clicks!! There is no machinery like that for 1.8 or 1.9!!! Please make it for 1.9.4 it is a really really important machine for automation!!

**Comment by HenryLoenwind** [comment]
I'm a bit reluctant here. The Autonomous Activator is kind of a Deus Ex Machina device, it gives you an easy out for an unlimited number of problems, which should actually have their own solutions.

So if you could list your problems, we might get some ideas for new machines to solve them.
