### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Ar97x** [SleepyTrousers/EnderIO#3366]
#### Issue Description:
Hi, I'm crashing and it seems that the responsibles are Ender IO and Mekanism.  
I got this little text from the log that might help:

* The RF API that is being used (1.7.10R1.1.0 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.10 from Mekanism-1.7.10-9.0.2.271.jar).
                    It is a supported version, but that difference may lead to problems.

#### What happens:
Game crashes at world initialization

#### What you expected to happen:
I think I expected the world to load :)

#### Steps to reproduce:

1.
2.
3.
...
 IDK what should be done above.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.426_beta
- EnderCore: EnderCore-1.7.10-0.2.0.35_beta
- Minecraft: 1.7.10
- Forge:10.13.4.1614-1.7.10

The Mekanism version is 1.7.10-9.0.2.271, if pertinent to the case.

#### Your most recent log file where the issue was present: 
Crash Report in the case:
https://www.dropbox.com/s/hye3el9u5o2s3jk/crash-2016-06-04_00.13.44-server.txt?dl=0

**Comment by HenryLoenwind** [comment]
java.lang.NullPointerException: Exception getting block type in world
    at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150818_a(SourceFile:57)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:595)
    at net.minecraft.world.World.func_147465_d(World.java:451)
    at cofh.core.wo

    ----^ go there

Please report this to the people who made the code that is crashing, not the ones who are telling you how your installation looks.

**Comment by Ar97x** [comment]
I'm not a coder so I basically just found what was right in front of me,
thanks for guiding me the right way.
