### ISSUE TITLE
Farming Station Doesn't Work with Cocoa Beans (3.0.0.36 Alpha)

### ISSUE THREAD

**Issue by homemmakako** [SleepyTrousers/EnderIO#3367]
#### What happens:

The Farming Station does not accept cocoa beans as a valid seed. The item won't even go into the farming station. 

#### Steps to reproduce:

Simply place a Farming Station down and try inserting a cocoa bean into the seed slot

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.9.4-3.0.0.36_alpha
- EnderCore: EnderCore-1.9.4-0.4.0.23-alpha
- Minecraft: 1.9.4
- Forge: 12.17.0.1940

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
not yet ported
