### ISSUE TITLE
Breaking conduits crashes game

### ISSUE THREAD

**Issue by Boundarybreaker** [SleepyTrousers/EnderIO#3370]
#### Issue Description:

Breaking an ender energy conduit results in game crash

#### What happens:

If you break an ender energy conduit (I haven't tried with other conduits), your game will crash.

#### What you expected to happen:

The conduit would break without the game crashing

#### Steps to reproduce:

1. Break an ender energy conduit with wrench or hand

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.36
- EnderCore: 0.4.0.23
- Minecraft: 1.9.4
- Forge: 1.9.4-12.17.0.1951

#### Your most recent log file where the issue was present: 

http://pastebin.com/17b2P7Eu

**Comment by HenryLoenwind** [comment]
see #3362
