### ISSUE TITLE
1.9.4-3.0.0.37_alpha - Crash on clicking the search tab in the creative inventory

### ISSUE THREAD

**Issue by OhiraKyou** [SleepyTrousers/EnderIO#3372]
Crash on clicking the search tab in the creative inventory. Does not affect 1.9.4-3.0.0.36_alpha.

- EnderIO:  1.9.4-3.0.0.37_alpha
- EnderCore: 1.9.4-0.4.0.23
- Minecraft: 1.9.4
- Forge: 1.9.4-12.17.0.1951

[Crash report](http://pastebin.com/8AWzkAEm)

**Comment by HenryLoenwind** [comment]
ok, next build will no longer crash...that way ;)

JEI is ok, I think? I'd have noticed a crash there, I think.

**Comment by OhiraKyou** [comment]
Yeah, everything \@enderio is fine in JEI

**Comment by HenryLoenwind** [comment]
Thx, so I don't need to push an emergency update. I hate those.

**Comment by JAWSAWN** [comment]
everybody panic :p

**Comment by JAWSAWN** [comment]
WAIT! This time it crashed me for no reason. I was pressing esc to exit out of the jei. And It suddenly crashed with a similar crash report.

https://gist.github.com/JAWSAWN/1fe42d0ea81f6851a9c8b71c89569a2b
