### ISSUE TITLE
Game crashes when attempting to access creative inventory search function

### ISSUE THREAD

**Issue by varukasalt** [SleepyTrousers/EnderIO#3374]
Issue Description: Hard Crash

 What happens: Game crashes while in creative mode when trying to click on the search icon in the creative inventory

 What you expected to happen: Expected search bar to come up.

Steps to reproduce:

1.Go into creative mode
2.Open inventory
3.Click on search icon
4.Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.9.4-3.0.0.37_alpha
- EnderCore:EnderCore-1.9.4-0.4.0.23-alpha.jar
- Minecraft: 1.9.4
- Forge:forge-1.9.4-12.17.0.1951

#### Your most recent log file where the issue was present: 

http://pastebin.com/N6yWYE6V

**Comment by Lanse505** [comment]
Getting the same crash!
http://pastebin.com/YMbz2AVb

:)

:+1:

**Comment by HenryLoenwind** [comment]
see #3372
