### ISSUE TITLE
[1.9.4] Crash on Creative Mode when trying to select EnderIO Tab or Search Bar

### ISSUE THREAD

**Issue by MrAmericanMike** [SleepyTrousers/EnderIO#3377]
#### Issue Description:
When playing on Creative, trying to witch to the Search Items tab or the EnderIO tab, crashes the pack.

#### What happens:
Pack crashes

#### What you expected to happen:
A tab to be opened

#### Steps to reproduce:

1. Just install EnderIO and EnderCore on Forge.
2. Get in game, switch to creative mode and try to open EnderIO tab

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.37_alpha
- EnderCore: 1.9.4-0.4.0.23-alpha
- Minecraft: 1.9.4
- Forge: 12.17.0.1954

#### Your most recent log file where the issue was present: 
http://pastebin.com/uCizt75u

**Comment by varukasalt** [comment]
Also happens when clicking on the Ender IO tab in creative inventory.

**Comment by varukasalt** [comment]
See Issue [#3372 ](https://github.com/SleepyTrousers/EnderIO/issues/3372)
