### ISSUE TITLE
[1.9] Add JEI Support to Inventory Panel

### ISSUE THREAD

**Issue by xMrVizzy** [SleepyTrousers/EnderIO#3378]
#### Issue Description:
Hi. Many players now using [JEI ](http://mods.curse.com/mc-mods/minecraft/238222-just-enough-items-jei) in 1.9 and 1.8 instead NEI. Can you add [JEI](http://mods.curse.com/mc-mods/minecraft/238222-just-enough-items-jei) support?
;)
____
#### Affected Versions:

- EnderIO for Minecraft: 1.9

**Comment by TheTemportalist** [comment]
It should already have support, I use their support in my modpack.

**Comment by AnrDaemon** [comment]
Excuse my curiosity, what exactly doesn't work for you in JEI-slash-EnderIO combination?

**Comment by Xiaminou** [comment]
Yes in the latest version for 1.9.4 the machines recipes are no longer showing up for some reason.

**Comment by Xiaminou** [comment]
Did you just update Ender IO to EnderIO-1.9.4-3.0.0.37_alpha.jar from a previous version? I had the same bug and I fixed it by deleting Ender IO's config folder.

**Comment by xMrVizzy** [comment]
No no no. I said add support JEI for inventory panel, and fix string in localisation! 
![79278319250c6f788307417879d20021](https://cloud.githubusercontent.com/assets/7906418/15831704/49fb1874-2c38-11e6-8d49-9324059555e2.png)
![a6a66d0f6c826969be75cd4785fbb83b](https://cloud.githubusercontent.com/assets/7906418/15831705/49fe8edc-2c38-11e6-8ff1-831861e2c0bb.png)

**Comment by MatthiasMann** [comment]
Well - you may have intended to say/write it - but you didn't. Which is why your post caused such negative replies.

**Comment by Xiaminou** [comment]
Guess I'm gonna open a new issue then

**Comment by HenryLoenwind** [comment]
The lang file strings are for the NEI support, which still exists. It is commented out as long as there's no NEI for 1.9, but not removed for good.

About the search syncing in the invPanel, I need to research if that is possible with JEI.

**Comment by xMrVizzy** [comment]
@HenryLoenwind people don't will use NEI in 1.9, because all mods transfer to JEI, (NEI - poop :))

**Comment by xMrVizzy** [comment]
I can help you with JEI integration if you want, i'm too coding mods

**Comment by Xiaminou** [comment]
You should also look into adding the "+" compatibility for JEI, it didn't work back in 1.8.9, don't know if there's been any changes. And back in 1.8.9 the sorting would reset whenever you closed and re-opened the inventory panel.
Oh and one last bug, again from my time in 1.8.9, it used to randomly "go crazy" and mix up item numbers and names, where it would show one type of item having the number of another type of item.
for example having 39 cobblestone and 1 torch, it would show 39 torch and 1 cobblestone.

**Comment by HenryLoenwind** [comment]
closing this issue in favor of of my TODO list regarding the invPanel and JEI integration
