### ISSUE TITLE
[1.9.4] Recipe button broken on servers.

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3379]
Recipes have been broken after the last update (EnderIO-1.9.4-3.0.0.37_alpha), it can be fixed for singleplayer by deleting the config folder.
However it remains broken on servers.

**Comment by MatthiasMann** [comment]
What happened to the template and specifying exact version numbers?

**Comment by Xiaminou** [comment]
Life happened

**Comment by MatthiasMann** [comment]
Do you know which parameters have changed between your old config and the new default config?

**Comment by Xiaminou** [comment]
No I don't

**Comment by HenryLoenwind** [comment]
There's nothing in the config that could prevent our JEI handler from being registered.

However, I noticed it can take up to 2 minutes for JEI to process all recipes and recipe plugins. And that's with just Ender IO. So be sure to give it a moment or two before you give up. You can watch the client log, one of our recipe plugins spits out a message when it's running.

**Comment by Xiaminou** [comment]
Okay maybe it was that 2 minutes thing, or maybe it fixed itself, I don't know, but now it works.
