### ISSUE TITLE
[CLIENT] 1.9.4-3.0.0.37_alpha crashes when open creative tab search 

### ISSUE THREAD

**Issue by kreezxil** [SleepyTrousers/EnderIO#3380]
#### Issue Description:
This bug occurs in my mod Uno Niner Four Mega Pack, I am the author of it.

#### What happens:
Client crashes when opening inventory while in creative and you click on the compass to search for an item.

#### What you expected to happen:
Expected creative search to appear

#### Steps to reproduce:

1. enter creative mode
2. hit 'e' for inventory
3. click the compass to activate a search

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.37_alpha
- EnderCore: 1.9.4-0.4.0.23-alpha
- Minecraft: 1.9.4
- Forge: 12.17.0.1954

#### Your most recent log file where the issue was present: 

crash report: http://pastebin.com/W4pfHH3i

fml-client-latest: https://gist.github.com/kreezxil/f7864aa40454414af5897fae0ce66a0f

**Comment by MatthiasMann** [comment]
see #3372
