### ISSUE TITLE
XP Boost showing for armor in enchantment table

### ISSUE THREAD

**Issue by foxanthony1** [SleepyTrousers/EnderIO#3382]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
I put a pair of diamond pants in the vanilla enchantment table and saw XP Boost as an enchant I could put on them.

#### What you expected to happen:
Not that. Vanilla enchanting in 1.8+ is really good. If mods break that with a lot of useless/inappropriate enchants that will be very disappointing. I'd really hate to have to decide between vanilla and Ender IO - that'd be painful.

#### Steps to reproduce:

1.Just try enchanting enough armor and you'll see it.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.9.4-3.0.0.36_alpha
- EnderCore:EnderCore-1.9.4-0.4.0.23-alpha
- Minecraft: 1.9.4
- Forge:12.17.0.1940

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
wrong project
