### ISSUE TITLE
[1.9.4] Opening creative search tab crashes the client

### ISSUE THREAD

**Issue by JAWSAWN** [SleepyTrousers/EnderIO#3385]
#### Issue Description:
After updating enderio, opening creative search tab crashes the client

#### What happens:

Creative Search tab causing client crash

#### What you expected to happen:

creative search tab open up normally

#### Steps to reproduce:

1.Open Creative search tab

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.37
- EnderCore: 1.9.4-0.4.0.23
- Minecraft: 1.9.4
- Forge: 1954

#### Your most recent log file where the issue was present: 

https://gist.github.com/JAWSAWN/89653b86b2fa3962c9e244236a4a6b13

**Comment by HenryLoenwind** [comment]
see #3372
