### ISSUE TITLE
Pull Requests!

### ISSUE THREAD

**Issue by xMrVizzy** [SleepyTrousers/EnderIO#3391]
Authors why you doesn't check [Pull Requests](https://github.com/SleepyTrousers/EnderIO/pulls)? I am already tired out there to write @-tag messages like "@HenryLoenwind merge please!", "Hey, has anyone here alive?". Please check them!

**Comment by AnrDaemon** [comment]
Stop being a spoiled child. All requests will be investigated, when time permits.

**Comment by xMrVizzy** [comment]
Surely it's so hard to press one button tu merge my translate!

**Comment by xMrVizzy** [comment]
And the joke is that I have this trouble only with Ender IO. All other mods check their pull requests at least 3 times in week

**Comment by AnrDaemon** [comment]
Nobody's obliged to merge your requests into their projects in first place.
And with your behavior, it is entirely possible that they will be refused just because how bad you are.
Nobody want to deal with a bad person.

**Comment by AnrDaemon** [comment]
Not to mention, your PR didn't pass CI test, which is a clear sign that it is not going to be merged in any imaginable future.

**Comment by AnrDaemon** [comment]
И, да, ты вообще проверял, твой перевод на экран помещается?…
А в стандартном размере окна MC?
Я вижу дохрена строк, у которых бездумно увеличена длина без существенного изменения смысловой нагрузки.

**Comment by xMrVizzy** [comment]
Yes, in this you are exactly right!

**Comment by xMrVizzy** [comment]
Например

**Comment by xMrVizzy** [comment]
Какие строки?

**Comment by xMrVizzy** [comment]
Вот у меня такой вопрос. Почему встречается на просторах интернета куча умников, которые поправляют других, а сами ничего не делают. Если ты лучше можешь это перевести, дак сделай перевод, умник.

**Comment by xMrVizzy** [comment]
Какой ты мод переводил? а? Да могу поспорить, что ничего ты сам то не перевёл. А я уже кучу модов переводил и не кто его не критиковал как ты, хотя его смотрел Адаптивити который делал переводы всех глобальных модов, IC2, BuildCraft, Forestry, Thaumcraft, Thermal Expansion и в том числе он тоже делал EnderIO пару строк.

**Comment by AnrDaemon** [comment]
Мод? JourneyMap.
Доволен?
А теперь кончай демонстрировать свой гонор и умерь пыл.
Тебе никто ничего не должен, ты ничего никому не должен.
Исходить желчью бессмысленно.

**Comment by xMrVizzy** [comment]
JourneyMap и всё да? Потуши свой пукан, мальчик. Я абсолютно спокоен!

**Comment by AnrDaemon** [comment]
Ты спросил про мод - я ответил. Хамить то зачем?
А вообще переводами игр я с 2005 занимаюсь.
