### ISSUE TITLE
[1.9.4] Placing facade painted with Quite Clear Glass crashes client

### ISSUE THREAD

**Issue by RealGrep** [SleepyTrousers/EnderIO#3392]
#### Issue Description:
Painted a facade with Quite Clear Glass. When I tried to place it, the client crashed. It now crashes immediately on login. This seems related to https://github.com/SleepyTrousers/EnderIO/issues/3353 . Would have thought the related commit might have fixed this as well.

**EDIT**: Removed it with MCEdit, went back in. Tried placing a normal Quite Clear Glass back to replace the facade (yes, with conduits next to it). Got another crash, so I don't think the fix you made entirely worked, and I think this turns out to be a duplicate PR.

#### What happens:
Place facade painted with Quite Clear Glass, client crashes and does so on each login, after.

#### What you expected to happen:
Well, it not crashing when I place the facade. :)

#### Steps to reproduce:

1. Paint facade with Quite Clear Glass
2. Place facade. It was next to Quite Clear Glass and an energy and insulated redstone conduit, in case this is relevant.
3. Kaboom.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.9.4-3.0.0.38_alpha.jar
- EnderCore: EnderCore-1.9.4-0.4.0.23-alpha.jar
- Minecraft: 1.9.4
- Forge: forge-1.9.4-12.17.0.1954-universal.jar

#### Your most recent log file where the issue was present: 

http://pastebin.com/uvN8fCaL

**Comment by HenryLoenwind** [comment]
thx, next build will no longer crash (exactly this way)
