### ISSUE TITLE
[1.9.4] Server crash when joining.

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3394]
Server crashes when I join after updating to EnderIO-1.9.4-3.0.0.39_alpha.
Client doesn't crash.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.9.4-3.0.0.39_alpha
- EnderCore: EnderCore-1.9.4-0.4.0.24-alpha
- Minecraft: 1.9.4
- Forge: 1954

#### Your most recent log file where the issue was present: 

Crash Report: http://pastebin.com/ZSqk04Ab

**Comment by Xiaminou** [comment]
that was fast ;)

**Comment by HenryLoenwind** [comment]
I'll talk to crazy about it
