### ISSUE TITLE
[1.9.4] Inventory Panel Issue(s)

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3395]
1. Inventory Panel now support JEI's "+" integration however it doesn't detect if you actually have the items, would it be possible to integrate that too?

2. [CLOSED] Inventory Panel now supports Storage Drawers, thank you!

3. Inventory Panel does not keep the sorting preference in mind:  https://youtu.be/ZCcOS7_l73c

4. Inventory Panel behaves badly when shift-clicking "+" in JEI: https://youtu.be/BGNW0Jjzmu0 (may be linked to #3421)

5. Inventory Panel will not refill some recipes, even if it has the items and they stack: https://youtu.be/XtPrxf1VsK8

6. Withdrawing a stack of items from the Inventory Panel will cause the rest of the items to disappear, being rescanned? And you will have to wait until it's finished to pick-up the next stack, making large withdraws annoying:  https://youtu.be/hT8VQ13S8rY (may be linked to #3421)

**Comment by Xiaminou** [comment]
Updated with 3 new issues (4, 5 and 6).

**Comment by HenryLoenwind** [comment]
4. Are there actually multiple stacks of diamonds and obsidian available?

**Comment by Xiaminou** [comment]
Yes
