### ISSUE TITLE
[1.9.4] Facades (as items) not showing any textures

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3397]
![2016-06-11_15 28 26](https://cloud.githubusercontent.com/assets/8670392/15985320/47b875c0-2fe9-11e6-9c7b-5a50125d8495.png)

**Comment by HenryLoenwind** [comment]
Painting with anything but vanilla blocks is not yet implemented. It may work for things that behave the same, but that's it.

**Comment by Xiaminou** [comment]
Oh, okay, thanks.
