### ISSUE TITLE
[1.9.4] Powered Spawner can't be combined with Broken Spawner in Anvil

### ISSUE THREAD

**Issue by Melakion** [SleepyTrousers/EnderIO#3398]
Forge 1958
EnderCore-1.9.4-0.4.0.24-alpha
EnderIO-1.9.4-3.0.0.39_alpha

**Comment by HenryLoenwind** [comment]
at least share a screenshot of what you are doing...

**Comment by Melakion** [comment]
http://i.imgur.com/2GRQmCQ.png

Seems to be something else in the pack interfering with it though, EIO does it fine by itself. Sorry, I should have tested more extensively.

**Comment by Melakion** [comment]
Seems to be caused by wuestUtilities. https://github.com/Brian-Wuest/MC-WuestUtilities/issues/2

Not sure how...

**Comment by Melakion** [comment]
https://github.com/Brian-Wuest/MC-WuestUtilities/blob/MC-1.9.4/src/main/java/wuest/utilities/Events/WuestEventHandler.java#L225 deals with the anvil, but I don't know how it works enough to know if it would break EIO stuff..

**Comment by Brian-Wuest** [comment]
I think I see the problem, Before I check for "ItemBook" I am setting the output to null which would interfere with any other mods working with the Anvil. This was a new feature which obviously wasn't tested with other mods in mind.

I just committed an update to remove that line of code. An update to CurseForge will be uploaded shortly.
