### ISSUE TITLE
Killer Joe causes crashes/Phantom block in SMP 1.9.4  3.0.0.39_alpha

### ISSUE THREAD

**Issue by sandervend** [SleepyTrousers/EnderIO#3399]
#### Issue Description:
After placing killer joe down initial crash occured. After removing WAILA a relog to the server was possible, but the block remained a phantom block, could be broken but never actually removed from the block space, the player cannot pass through the block and if another block is placed on to the space server crash occurs.

#### What happens:
Server crashes if block is placed initially, or another block is placed where the phantom block is.
Player crashes if has WAILA on and looks at the phantom block.

#### What you expected to happen:
Not crash and have a block.

#### Steps to reproduce:

1.Play on a SMP server
2.Craft and Place down Killer Joe on stone.
3.Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.9.4-3.0.0.39_alpha
- EnderCore: 1.9.4-0.4.0.24-alpha
- Minecraft: 1.9.4
- Forge:forge-1.9.4-12.17.0.1958-

#### Your most recent log file where the issue was present: 

Initial crash: http://pastebin.com/7BYz6sH1
Crash after placing block onto phantom block: http://pastebin.com/GgyZR2KX

#### Additional

I realize that there are additional mods running, however none of them should be affecting this crash, if they are I apologize.

**Comment by HenryLoenwind** [comment]
see #3394
