### ISSUE TITLE
1.9.4 Enchanter

### ISSUE THREAD

**Issue by Krutontar** [SleepyTrousers/EnderIO#3400]
#### Issue Description:
Not a proper pack.  Just a collection thrown together on Curse.

#### What happens:
Some recipes work, some don't.  XP is never consumed, neither is the main material or the book.  Lapis is always consumed.  If you just put lapis into the lapis slot, it's gone regardless if anything else is in the other slots.  When the recipe wants to work, the book appears in the lapis slot, never the output slot.  No crashes.
I had one case where everything worked properly (went to the correct slots and everything was consumed that should have been).  No idea what was different.  It was a recipe that failed earlier for me: Fire Aspect II.  I had recently broken and moved the Enchanter.

#### What you expected to happen:
To insert ingredients and receive enchant books.

#### Steps to reproduce:

1.  Attempt to use the Enchanter.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.39
- EnderCore: 4.0.24
- Minecraft: 1.9.4
- Forge: 12.17.0.1959

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
No crash log because there was no crash.

**Comment by Krutontar** [comment]
Apparently breaking and replacing it after the 3.0.0.39 update fixed it.

**Comment by HenryLoenwind** [comment]
Makes sense, that update added the lapis slot.

I'll close this ticket. If you encounter the problem again just comment here, I'll see that and re-open it.
