### ISSUE TITLE
Game crashes when using teleporter

### ISSUE THREAD

**Issue by LordHellscream** [SleepyTrousers/EnderIO#3401]
#### Issue Description:
Game crashes when use the telepad

#### What happens:

Game crashes

#### Steps to reproduce:

1. Build 3x3 telepad
2. use coordiante selector to select a nearby coordinate
3. set the coordinate
4. teleport

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-0.4.1.2.4
- EnderCore: 3.0.0.40
- Minecraft: 1.9.4
- Forge: 1957

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
http://pastebin.com/Nge6haAL

**Comment by HenryLoenwind** [comment]
thx, fixed in next build
