### ISSUE TITLE
[1.9.4] Server crash when re-joining (java.lang.Error)

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3402]
After leaving my server for a few hours I rejoined and the server crashed.

Crash Report: http://pastebin.com/4ixEsfgZ

**Comment by HenryLoenwind** [comment]
Some core mod is patching net.minecraft.world.World.isOutsideBuildHeight(BlockPos) in a bad way. Report this crash with that mod. You logfile may tell you which one is patching it (most of them announce it when they do), if not, report this to all listed core mods that do not write a notice about patching something into the log.

**Comment by Xiaminou** [comment]
not sure which one it is, so here is the log: https://drive.google.com/file/d/0BxQWn9jKBIAJYm53SlllQjVmNTQ/view?usp=sharing
