### ISSUE TITLE
[1.9.4] Telepads crashing after teleport

### ISSUE THREAD

**Issue by Zekralyx** [SleepyTrousers/EnderIO#3404]
#### Issue Description:

The game client/server crashes when using the Telepad immediatly after teleporting.

#### What happens:
When trying to teleport in the Telepad 3x1x3 structure, right after the game teleports the player to the center block of the Telepad, immedietly crash the client/server.

#### What you expected to happen:
If the teleport is not configured (or WIP), it should do nothing or just teleport to the same telepad without any issue.

#### Steps to reproduce:

In a Creative or Survival World, do the following:
1. Create a 3x1x3 structure of the Telepad anywhere in the overworld.
2. Access the Telepad and push the button "teleport"

I don't know if I'm missing something when using it, but it should't crash anything.
____
#### Affected Versions

- EnderIO: 3.0.0.40_alpha (also in 3.0.0.37 )
- EnderCore: 0.4.0.24-alpha
- Minecraft: 1.9.4
- Forge: 12.17.0.1956

#### Crash Log
http://pastebin.com/RK5VY8S0

**Comment by HenryLoenwind** [comment]
see #3401
