### ISSUE TITLE
[1.9.4] Retrieving XP from Killer Joe sometimes fails

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3405]
When trying to retrieve XP from the Killer Joe sometimes it'll give you 100% of a level without giving you the level, and then you won't be able to retrieve anymore XP until you gain/lose XP from another source.
![2016-06-13_02 16 40](https://cloud.githubusercontent.com/assets/8670392/15994759/18824d88-310d-11e6-8f6f-d3fcc0dda11f.png)
![2016-06-13_02 16 42](https://cloud.githubusercontent.com/assets/8670392/15994758/18824a68-310d-11e6-8089-98cafc4a4667.png)

**Comment by HenryLoenwind** [comment]
Have you found a way to reproduce this? I had it once when doing the changes, but then it went away and I couldn't reproduce it.

**Comment by Xiaminou** [comment]
I don't know how to reproduce it but it's happened to me twice already, I'll keep trying.

**Comment by HenryLoenwind** [comment]
I got some good tips from the helpful people who hand out in our chat all day. This should fix it. (next build...)
