### ISSUE TITLE
[1.9.4] Bad tooltip background color

### ISSUE THREAD

**Issue by Granik24** [SleepyTrousers/EnderIO#3406]
#### What happens:
In IO configuration, tooltip about how much liquid is in getting bad background after configuring IO to push. 
See video for details: https://youtu.be/u1f0Uc3HKLw

#### Steps to reproduce:

1. Place tank
2. Add some liquid in
3. Configure IO to push into other tank/conduit

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.40_alpha
- EnderCore: 1.9.4-0.4.0.24-alpha
- Minecraft: 1.9.4
- Forge: 1.9.4-12.17.0.1959

![2016-06-13_14 53 28](https://cloud.githubusercontent.com/assets/4377405/16008117/9f591ef4-3176-11e6-8f9c-02346010a545.png)

**Comment by CrazyPants** [comment]
Thanks for the great report. Fixed in the next build.

**Comment by Granik24** [comment]
Fixed, thanks guys!
