### ISSUE TITLE
Farming Station will not harvest Ore Berries (TiC)

### ISSUE THREAD

**Issue by aetherpirate** [SleepyTrousers/EnderIO#3407]
Not sure if this is a feature request or a bug. Have read about previous versions working. I've tried adding a hoe, removing the hoe, adding octadic capacitor, removing. 

#### What happens:

I place a Farming Station in a dark room. I add oreberry bushes around it (copper, tin, iron, gold, aluminum, essence). It will only farm essence berries. Ores are ignored. 

#### What you expected to happen:

I'd like it to grab it all. 

#### Steps to reproduce:

1. Place farming station
2. Place orebushes. Wait for them to grow. 
3.Note lack of harvesting. 
...

____
#### Affected Versions (Do *not* use "latest"):

-:EnderIO-1.7.10-2.3.0.426_beta
- EnderCore-1.7.10-0.2.0.35_beta
- Minecraft: 1.7.10
- Forge:1614

[fml-client-latest.txt](https://github.com/SleepyTrousers/EnderIO/files/312467/fml-client-latest.txt)

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
This may be related to the Farming Station being wonky in 426. Could you try with 425? (Don't forget to backup your world.)

**Comment by aetherpirate** [comment]
Success!

Downgrading to 425 works fine. 

Thank you very much for your quick response.

**Comment by HenryLoenwind** [comment]
link in #3344
