### ISSUE TITLE
[1.9.4] Travel Anchor label sprites flipped horizontally

### ISSUE THREAD

**Issue by Gotolei** [SleepyTrousers/EnderIO#3408]
https://i.imgur.com/3u6J09o.png
https://i.imgur.com/jSoSbCm.png

EnderIO: 1.9.4-3.0.0.40_alpha
EnderCore: 1.9.4-0.4.0.24-alpha
Forge: 12.17.0.1962

(Pack: 1.9 Unstable 4.0.7)

**Comment by HenryLoenwind** [comment]
thx, next build will have a working render for that overlay again. The old one was never properly ported.
