### ISSUE TITLE
Ender IO 1.7.10 inventory panel & storage drawers " video for better visual "

### ISSUE THREAD

**Issue by tarzan1376** [SleepyTrousers/EnderIO#3412]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

https://www.youtube.com/watch?v=Z1uGLdXlNqc&feature=youtu.be

#### What you expected to happen:
For the item to be properly stored in the storage drawer through the inventory panel

#### Steps to reproduce:

1.Storage drawers all connected with item conduits with awareness upgrades in them, items scattered all over.
2. put new item not in the system " modded item "
3. See if it changed to new item " visually "
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.424_beta
- EnderCore: 1.7.10-0.2.0.31_beta
- Minecraft: 1.7.10
- Forge: forge-10.13.4.1614

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
#3129
