### ISSUE TITLE
[1.9.4] Obelisks push you off when you stand on them

### ISSUE THREAD

**Issue by Drullkus** [SleepyTrousers/EnderIO#3413]
When you stand on the EnderIO Obelisk (Weather, Attractor, etc), it pushes you off. It is behavior similar to being inside a block.

Pack - FTB Unstable 4.0.7

Version - EnderIO-1.9.4-3.0.0.40_alpha

**Comment by HenryLoenwind** [comment]
Known issue we haven't yet decided on is we like it or not.
