### ISSUE TITLE
1.9.4 Gui issue

### ISSUE THREAD

**Issue by tyler489** [SleepyTrousers/EnderIO#3414]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".
its the Knoxz 1.9 Testpack but it is reproducable with just enderio/ender core

#### What happens:
Phantom items in hotbar

#### What you expected to happen:
Shouldnt be hapening
https://gyazo.com/8105ab677be6b3546d0e90f732f37d2b

#### Steps to reproduce:

1. Open a slice and splice

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.0.40_alpha

- EnderCore: 1.9.4.0.4.0.24-alpha
- Minecraft: 1.9.4
- Forge:

#### Your most recent log file where the issue was present: 
NA

i know 1.9.4 is unfinished but i wanted to report just in case this wasnt known

**Comment by HenryLoenwind** [comment]
thx, fixed in next build
