### ISSUE TITLE
End Dragons are not spawnable despite IBossDisplayData mobs config being allowed.

### ISSUE THREAD

**Issue by Drullkus** [SleepyTrousers/EnderIO#3415]
Pack - FTB Unstable 4.0.7

EnderIO Jar Filename - EnderIO-1.9.4-3.0.0.40_alpha.jar

Withers/Pink Withers/Other Mobs with IBossDisplayData are spawnable from EnderIO's Powered Spawner (allowed in config), however when I attempt to spawn the End Dragon, nothing happens. It should be spawning the End Dragon. The Powered Spawner is located in the End.

**Comment by HenryLoenwind** [comment]
![image](https://cloud.githubusercontent.com/assets/1485873/16167567/05ae7914-34f7-11e6-9284-1e1fea4cdfa7.png)

works for me. Did you give it enough space? It is big. It's so big that you cannot spawn it from a Soul Vial because it collides with you.

However, it seems just spawning it like any other mob doesn't set all of its data. So we'll need some special code for that :(

**Comment by Drullkus** [comment]
Hm, you might be right on the limited space. What's the size? I had some obsidian pillars near where I was attempting to spawn it.

**Comment by HenryLoenwind** [comment]
Another problem is that you cannot capture it---because you cannot right-click it. It seems to have no proper hitbox.

**Comment by HenryLoenwind** [comment]
And btw, it is 16x8x16 blocks.

**Comment by Drullkus** [comment]
That's friggin' chunk!

I think the real entity hotbox might be somewhere on the dragon's torso.

**Comment by HenryLoenwind** [comment]
It has some kind of hitbox, just not the kind that can be right-clicked with an item.

Also, I found another problem. The whole dragon AI is in a separate singleton class. So there can always only be one (moving and fighting) dragon and it can only be in the end.

**Comment by Drullkus** [comment]
Huh, that must have been changed from the 1.7 version.

**Comment by HenryLoenwind** [comment]
Yes, that code  is new. I even found a part that scans for an "old" dragon to adopt it.

**Comment by HenryLoenwind** [comment]
I'd say we'll leave "spawning multiple ender dragons anywhere" to another mod. That's a huge task, you basically have top copy most of that code. So I'm blacklisting the dragon hard. Sorry :-(

**Comment by Drullkus** [comment]
Not too bothered by the blacklisting anyway, it's kind of automatable as-is already.

Why not just add the dragon to the config blacklist instead?

**Comment by HenryLoenwind** [comment]
Because people will try to remove it...and fail. I'm only blacklisting the Soul Vial "Ender Dragon" from JEI/Creative Inventory anyway, as the cragon cannot be soul vialed...
