### ISSUE TITLE
[1.9.4] add enchantment tooltip support [minor] 

### ISSUE THREAD

**Issue by tyler489** [SleepyTrousers/EnderIO#3416]
Enchantments are missing  tooltip discreption for instance Autosmelt.
It says no enchantment discription is found for endercore autosmelt please contact the modmaker...

Minor thing just an fyi
Using knoxz 1.9 testpack

**Comment by tyler489** [comment]
EnderIO: 1.9.4-3.0.0.0.40_alpha

EnderCore: 1.9.4.0.4.0.24-alpha

Minecraft: 1.9.4

**Comment by tyler489** [comment]
Its all enchantments from all your mods i dont know if enderio has any enchantments

Pps no hurry i know 1.9 is incompleate just a reference note

**Comment by tterrag1098** [comment]
Uh, what exactly is saying that? We have our own system for enchantment descriptions and it works fine.

**Comment by tyler489** [comment]
https://gyazo.com/82f18ac4244ebf5c43f7051db5b2579f

**Comment by tyler489** [comment]
https://gyazo.com/d33e20abf1d9c7f4e9c6211b969b4c75
Could it be Waila

**Comment by tterrag1098** [comment]
I don't know what it is, but they are being extra obnoxious. Why not just display nothing if there's no support for it? I don't understand. Either way, as you can see, we already have descriptions and I see no need to duplicate information.
