### ISSUE TITLE
[Suggestion] Tinkers' Construct Integration for alloys

### ISSUE THREAD

**Issue by yepidoodles** [SleepyTrousers/EnderIO#3419]
Would be awesome to add the alloys to Tinkers' - I asked there but they said it was best to ask here

https://github.com/SlimeKnights/TinkersConstruct/issues/2178

Thanks

- Alice
DragonTechMC

**Comment by HenryLoenwind** [comment]
I had a quick look. I see two problems: (a) We don't yet have the recipes in pre-init, (b) we have no way of looking up the fluid names for our input items (aside from our own metals), and (c) all I get from Tinkers in my development environment is crashes.

**Comment by CrazyPants** [comment]
This would be great but, being realistic, I cant see us implementing this in the near future due to time constraints.
