### ISSUE TITLE
[1.9.4] Inventory Panel Doesn't Display Items In Large Storage Networks

### ISSUE THREAD

**Issue by praetoras** [SleepyTrousers/EnderIO#3420]
#### Issue Description:
Inventory Panel stops working when available inventory slots exceed a certain number.

#### What happens:
I have a storage system set up with a network of RFTools Modular Storage units. Admittedly, I have a lot of them. However, I discovered that when I hooked up the network, while the inventory will take items from the return area and place them into the network with no trouble, it will not display the inventory of the network at all. I had to disable parts of the network in order to get the inventory to show up.

What is the limit to the number of inventory slots the inventory panel can scan? As noted below, if there's a hard limit to the number of inventory slots it can access, I just need to know what it is so I can build/plan accordingly. If there's a way to lift it without breaking something, that would be fantastic.

#### What you expected to happen:
I expected the inventory storage to show the inventories of the modular storage units.

#### Steps to reproduce:

1. Build a network of RFTools Modular Storage units (each with a 3rd tier module).
* Conduit links are all set to insert only with the Remote upgrade.
* Network is 6 groups of 144 modular storage units.
* I have the groups three blocks tall, three blocks wide, and 24 blocks long.
* Outer blocks are storage units, and the middle "lane" is used for the item conduits.
2. Hook up an inventory panel to the network - the inventory area will show grayed out.
3. Disconnect several of the networked groups from the storage network.
4. After disconnecting, the inventory shows up in the Inventory Panel just fine.

Image Album here: http://imgur.com/a/HE6zH

****NOTE:**** I'll totally understand if that behavior was somehow disabled for performance or memory reasons. However, I had a network of Storage Drawers set up of similar capacity, which appeared to work fine until I discovered it wouldn't display any item with more than 64 in its stack, so I switched to the RFTools Storage Module.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.40_alpha
- EnderCore: 1.9.4-0.4.0.24-alpha
- Minecraft: 1.9.4
- Forge:forge-1.9.4-12.17.0.1965-universal

#### Your most recent log file where the issue was present: 

There isn't a log file currently, as there was no crash. The Inventory Panel just didn't display any items at all.

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
I had a quick look but haven't found any code to limit the number of inventories that can be connected

**Comment by praetoras** [comment]
I appreciate the reply!

I recall reading somewhere that it typically takes X amount of time to scan an inventory slot. Is it possible that it's somehow just taking a long time to load everything? I've been experimenting with the inventories, and I laid out a line of 49 of the modular storage units. It took about 30-40 seconds for it to "reach" storage units further down the line. I had tested that on the full network (by sitting with the inventory window open for a while) but it never seemed to load. If so, is there any way I can set things up to mitigate it?

**Comment by praetoras** [comment]
Just to confirm here, I experimented more with my full network, and I found that if I put wool across the network and then filter for wool in the Inventory Panel search, it will take over 15 minutes for the inventory panel to actually show all of them, with the wool popping up one at a time as the panel 'discovered' it in the network, but they do (eventually) all show up.

**Comment by praetoras** [comment]
Related Issue:

To try and get around the 'network lag' of one storage network, I attempted to set up multiple inventory panels, each on a different channel/signal to different groups of storage. However, I discovered that unless the conduits themselves were completely separate from each other (from the panel to the storage units) the panels still attempted to scan the entire network, and so suffered the same amount of delay.
