### ISSUE TITLE
[Suggestion] 1.9.4 Refined Storage Cables for enderio

### ISSUE THREAD

**Issue by Exanadu** [SleepyTrousers/EnderIO#3422]
Since Enderio supported ME cables for AE2, it would be fantastic if something similar was created for refined storage as it seems to be an up and coming mod in the the FTB packs.

**Comment by CrazyPants** [comment]
Thanks for the suggestion. If somebody creates a PR for this (i.e. does the coding) I would be happy to include the functionality. 
Given time restraints I am not planning to add any new conduit types myself.
