### ISSUE TITLE
Removing Mekanism cable crashes server.

### ISSUE THREAD

**Issue by RedGuy54** [SleepyTrousers/EnderIO#3425]
Issue Description: When disconnecting a Mekanism Universal cable from a power buffer, my server crashes.

What you expected to happen:

Steps to reproduce:

1. Disconnect a universal cable from a power buffer

Affected Versions (Do *not* use "latest"):

- EnderIO: 2.2.8.381
- Minecraft: 1.7.10
- Forge: 10.13.4.1558
- Mekanism 9.0.2.271

Your most recent log file where the issue was present: 

http://pastebin.com/JvxUHqAf

**Comment by HenryLoenwind** [comment]
That crash is "on the other side", it's the receiving block that crashes when we try to sent energy to it.
