### ISSUE TITLE
[Suggestion] 1.9.4: Add a "Creative Aversion Obelisk" that works for the entire server" (For dev usage)

### ISSUE THREAD

**Issue by starg09** [SleepyTrousers/EnderIO#3427]
Right now we were having a problem with zombies and waila in a pack beta testing group, and this idea came: Would it be viable (as in, not server-breaking) to include either a creative version of the Aversion Obelisk, with server-wide range for the spawning prevention? Or, as an alternative, a Creative Capacitor that makes the original Obelisk not use any energy, and have the same effect (This might be more handy if you need to make another "Creative _____" in the future)

**Comment by CrazyPants** [comment]
There is already a creative capacitor bank. You can do what you want already by placing a normal obelisk next to a creative cap. bank.

**Comment by HenryLoenwind** [comment]
@CrazyPants you're missing the point here: infinite range...

However, I'd rather change the "stop squids" config setting to a blacklist

**Comment by starg09** [comment]
What Henry said: this is not about energy, but restricting mob spawning globally, without a range restriction (for the purpose of debugging, and while developing/testing a pack). Always assuming that this won't cause problems to the world due to the way the spawning restriction works, but I guess if you have a "Stop Squids" config, then this could be implemented with no major complications :)
