### ISSUE TITLE
[1.9.4] - Ticking block entity

### ISSUE THREAD

**Issue by Lazarix** [SleepyTrousers/EnderIO#3428]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

Issue with Ender IO 3.0.0.43 and RFtools 4.64

https://gist.github.com/Lazarix/a69a9c61033bd0eaeb154053ea043c68

**Comment by HenryLoenwind** [comment]
Please post a full log. Ender IO and RFTools work well together in other environments.

**Comment by HenryLoenwind** [comment]
(oops, I misclicked that label)

**Comment by Lazarix** [comment]
Full log:

https://gist.github.com/Lazarix/650d545278a06adff6e88f684af48ccb

**Comment by HenryLoenwind** [comment]
ok, found it,

Mekanismn is shipping their own version of the RF API that is incompatible with the rest of the world. That gives you the choice: Either Mekanism or any other RF-based mod.

**Comment by CrazyPants** [comment]
Or maybe update mekanism?
