### ISSUE TITLE
[Suggestion] Advanced Generators Syngas as fuel for Combustion Generator

### ISSUE THREAD

**Issue by Dragnier** [SleepyTrousers/EnderIO#3430]
Cannot find any way to add Syngas produced via Advanced Generators mod as a fuel available for the Combustion Generator. It pumps through fluid pipes from EIO just fine though. It's just that the generator doesn't know what to do with it.

It is basically carbon atomized into steam to create a fuel that is better than simple coal. The main point here is to allow the EIO combustion generator to stand in as an stand in between building the syngas producer and a gas turbine generator, since they are multi-blocks and take a fair amount of resources.

**Comment by CrazyPants** [comment]
You can add fuels via IMC. See: https://github.com/SleepyTrousers/EnderIO/blob/1.9/src/main/java/crazypants/enderio/api/IMC.java#L106
If you need any help just ask on the EIO IRC channel

**Comment by Dragnier** [comment]
Oh, I'm just an end-user of the mod. It isn't mine. I was just hoping there was a config option in EIO to add the fuel... guess I'll share this post with the mod author.
