### ISSUE TITLE
Crash on load when sing HARD recipes

### ISSUE THREAD

**Issue by KennyBurch** [SleepyTrousers/EnderIO#3431]
#### Issue Description:
When the config is set to use hard recipes ie:

    # How expensive should the crafting recipes be? -1=don't register any crafting/smelting recipes, 0=cheapest, 1=cheaper, 2=normal, 3=expensive
    I:recipeLevel=3

The game crashes on load:

#### What happens:

java.lang.RuntimeException: Recipes config file recipe_materials.xml is invalid: Could not find a crafting ingredient for 'CHASIS_METAL' (stack=null, object=null) in recipe 'Gear'
	at crazypants.enderio.CommonProxy.init(CommonProxy.java:94)
	at crazypants.enderio.ClientProxy.init(ClientProxy.java:258)
	at crazypants.enderio.EnderIO.load(EnderIO.java:441)

#### What you expected to happen:

No crashing...

#### Steps to reproduce:

1. Define recipe level to 3
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.43alpha
- EnderCore: 0.4.0.26-alpha
[crash-2016-06-20_17.38.52-client.txt](https://github.com/SleepyTrousers/EnderIO/files/324610/crash-2016-06-20_17.38.52-client.txt)

- Minecraft: 1.9.4
- Forge: 1968

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
thx, will be fixed in next build
