### ISSUE TITLE
 [1.9.4] Crash Distillation Furnace + EnderIO Tanks

### ISSUE THREAD

**Issue by JCMais** [SleepyTrousers/EnderIO#3432]
EnderIO: 1.9.4-3.0.0.43
EnderCore: 1.9.4-0.4.0.26
PowerAdvantage: 1.9.4-2.2.1

If it's an issue with the other mod, feel free to close that issue, it was reported [here](https://github.com/cyanobacterium/PowerAdvantageAPI/issues/26) to the other mod author.

Crash log: https://gist.github.com/knoxhack/a1b5dabba3b57eb0900395d3979c4a76

![2016-06-20_23 29 54](https://cloud.githubusercontent.com/assets/1041647/16216258/b1fe07bc-373f-11e6-916b-a928039b6e3a.png)

Left tank had Crude Oil and was configured to push, right one was set to pull, so it could receive the Refined Oil from the distillation furnace.

**Comment by CrazyPants** [comment]
The crash is coming from PowerAdcantage code.
