### ISSUE TITLE
Wither skeletons shooting arrows when power spawned

### ISSUE THREAD

**Issue by Kraege** [SleepyTrousers/EnderIO#3434]
#### Issue Description:
When using a powered spawned in the overworld, Wither skeletons shoot flaming arrows. They do not produce any wither effect nor do they have or use a sword.

#### What you expected to happen:
Wither skeletons should spawn with swords and cause the wither effect if they hit you with the sword.

#### Steps to reproduce:
1. Catch Wither skeleton in Soul Vial
2. Create Powered Spawner with said Soul Vial 
3. Place Powered Spawner in the Overworld
4. Power up and Spawn Wither Skeletons

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.9.4-3.0.0.43_alpha
- EnderCore: EnderCore-1.9.4-0.4.0.26-alpha
- Minecraft: 1.9.4
- Forge: 1.9.4-forge1.9.4-12.17.0.1965

#### Your most recent log file where the issue was present: 
It is a compressed file and I do not know how to open it to paste in pastebin. When I try to uncompress the file it comes out as garbage symbols and lettering.

**Comment by AnrDaemon** [comment]
Check if vial NBT matches the spawner NBT, and of those mobs spawned by it.

**Comment by Kraege** [comment]
I have no clue how that would be done, sorry.

**Comment by HenryLoenwind** [comment]
wither skeleton code isn't yet done for 1.9

**Comment by Kraege** [comment]
That would explain it. Good to know

**Comment by HenryLoenwind** [comment]
in the next build this will work as expected again.
