### ISSUE TITLE
[1.9.4] Powered spawner ignores redstone triggers

### ISSUE THREAD

**Issue by c0rn3j** [SleepyTrousers/EnderIO#3435]
#### Issue Description:
Putting a pressure plate/lever/redstone torch next to a powered spawner(didn't test with other machines) set to "Activate with signal" is ignored and machine does not turn on.

#### What happens:
http://imgur.com/a/C5DjV

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.9.4-3.0.0.45_alpha
- EnderCore: EnderCore-1.9.4-0.4.0.26-alpha
- Minecraft: 1.9.4
- Forge: forge-1.9.4-12.17.0.1969

**Comment by HenryLoenwind** [comment]
Cause is that for some reason we need a strong redstone signal. Something wasn't ported right. Known issue, just hasn't been looked at.

**Comment by HenryLoenwind** [comment]
will be fixed in next build
