### ISSUE TITLE
RF Gauge - Crash

### ISSUE THREAD

**Issue by Elvarion** [SleepyTrousers/EnderIO#3438]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Crashed when rightclicking with a RF Gauge on a Vibrant Capacitor Bank

#### What you expected to happen:
Not sure, just testing out the new stuff in 1.9.4

#### Steps to reproduce:

1. Rightclick a Vibrant Bank with a RF Gauge

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.45_Alpha
- EnderCore: 0.4.0.26_Alpha
- Minecraft: 1.9.4
- Forge: 12.17.0.1980-1.10.0

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
http://pastebin.com/SKnXwy6T

**Comment by Myknakryu** [comment]
Well for me it also crashes when i rightclick stirling generator.

Forge: 12.17.0.1980-1.10.0
Minecraft: 1.9.4
EnderIO: 3.0.0.45_Alpha
EnderCore: 0.4.0.26_Alpha

Logs:
http://pastebin.com/Fj3TJCBB

**Comment by HenryLoenwind** [comment]
Found it. That's a "bug" in Forge, report it there.

**Comment by ZiggyAdventures** [comment]
What is the bug you found so we can report it on forge. As far as I can tell, it only happens in -45, -43 is clean, but I don't know how to look at commit changes to EnderIO to find the forge bug.

**Comment by HenryLoenwind** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/3021
