### ISSUE TITLE
[1.7.10] Painted Glowstone is buggy when placed by RFTools Builder, crashes server when broken

### ISSUE THREAD

**Issue by TheBrain0110** [SleepyTrousers/EnderIO#3439]
#### Issue Description:

(Yes, this involves cross-mod interaction, but the crash seems most likely to be fixed on the EnderIO side)

I was building a nifty space station, and wanted to automate adding new levels to it, so I set up an RFTools Builder in Copy mode. Part of my build had Painted Glowstone painted as the Chisel Laboratory block.

When I supplied the Builder with the correctly-painted Laboratory Block-Painted Glowstone, it got placed down with the vanilla glowstone texture. When I tried to break the block to replace it, I got disconnected from the server with an Internal Server error, and upon rejoin the block was still there.

Then I got clever and tried breaking it with an autonomous activator, in which case the whole server crashed.

There was no client-side error reports, you just get disconnected. We'll see if I can get a log from the server owner.

I did reproduce it in singleplayer, where upon breaking the buggy block, you crash immediately to desktop. I did get a helpful crash report that way:
https://gist.github.com/TheBrain0110/59420d2b2cf39f400d790afa6943b80b
#### What happens:

Placing Painted Glowstone (possibly other painted blocks? haven't tried) using an RFTools Builder block results in it having the vanilla glowstone texture, and the game to crash when breaking it.

My guess is some of the NBT data is missing, but that's just a hunch.
#### What you expected to happen:

A correctly-behaving painted block, regardless of what means was used to place it.

And if a block does happen to be missing some data, handle it gracefully instead of crashing.
#### Steps to reproduce:
1. Paint some Glowstone. Doesn't matter what you paint it as.
2. Place it somewhere, then put RFTools Space Chamber blocks around the corners to copy the area.
3. Link a Space Chamber Card to it, and put it in a Builder block.
4. Give the Builder block power, and put a chest on top with more Painted Glowstone blocks for it to place.
5. Apply redstone signal. It should copy the area you defined, and any painted glowstone blocks will be placed with the vanilla glowstone texture.
6. Try and break them. The game will crash.

Notes:

WAILA will show the block as "Painted Glowstone", not the name of the block it was painted with.
If you right-click the Space Chamber card in your hand after its been linked to the Space Chamber Controller block, it will show a list of the blocks to be copied. Any painted glowstone blocks are listed simply as "Painted Glowstone."

The RFTools Builder is normally pretty good about handling TileEntities, and it is still paying attention to what the source blocks are painted as. If you put glowstone painted as a _different_ block in the chest, it won't use it. It has to be the correctly painted block, but then some data seems to get lost on placing.

---
#### Affected Versions (Do _not_ use "latest"):

Modpack: FTB Infinity Evolved 2.5.0
- EnderIO: 2.3.0.424_beta
- EnderCore: 0.2.0.32_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614
#### Your most recent log file where the issue was present:

https://gist.github.com/TheBrain0110/59420d2b2cf39f400d790afa6943b80b

**Comment by HenryLoenwind** [comment]
(PainterUtil:78)
