### ISSUE TITLE
1.9.4 - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by p455w0rd** [SleepyTrousers/EnderIO#3440]
#### Issue Description:
Placed stirling generator, crashed.

#### What happens:
Upon placing stirling generator, client crashes (just me no one else on server)

#### What you expected to happen:
Stirling Generator to just place

#### Steps to reproduce:

1. Place stirling generator

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.45_alpha
- EnderCore: 1.9.4-0.4.0.26-alpha
- Minecraft: 1.9.4
- Forge: 1.9.4-12.17.0.1980-1.10.0 (yeah this was a 1.10 "pre branch" or something like that..I dunno..so I guess this is more of a heads up)

#### Your most recent log file where the issue was present: 

http://pastebin.com/G2nX7svT

**Comment by HenryLoenwind** [comment]
see #3438
