### ISSUE TITLE
[1.8.9] farming station does not recognize mod seeds as seeds

### ISSUE THREAD

**Issue by kotoroshinoto** [SleepyTrousers/EnderIO#3441]
I am not currently aware if this feature is considered to be working or still in development, but I figured the feedback might be useful.

Want to be able to grow industrial hemp seeds from immersive engineering. they are plantable on regular ground OR farmland, so in theory they should work, but the block doesn't recognize them as seeds.

#### What happens:
Text saying "no seeds"

#### What you expected to happen:
Plant the seeds.

#### Steps to reproduce:

1. Run enderio and immersive engineering together
2. Make, place, and power a farming station, and give it a hoe tool
3. Place industrial hemp seeds  in the seed slots
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.26_alpha
- EnderCore: 0.3.0.14
- Minecraft: 1.8.9
- Forge: 11.15.1.1890

**Comment by kotoroshinoto** [comment]
it does recognize the seeds from Pam's Harvestcraft though

**Comment by HenryLoenwind** [comment]
1.8.9 has no support for IE. That was only ported after we switched to 1.9.

**Comment by AnrDaemon** [comment]
Are these seeds oredicted?

**Comment by kotoroshinoto** [comment]
examining the seed item with /mt hand I notice it is NOT in an oredict entry with  a name seedX

**Comment by HenryLoenwind** [comment]
oreDict has nothing to do wuth seeds

**Comment by kotoroshinoto** [comment]
is it unrealistic to maintain a backport for 1.8.9 for at least a while? some of the tech mods haven't made the jump beyond 1.8, some haven't even released anything beyond 1.7.10 yet.

**Comment by HenryLoenwind** [comment]
at the moment it is unrealistic to finish the 1.9 port anytime soon...

**Comment by kotoroshinoto** [comment]
odd, it also collected the "raspberry crop" item from pam's instead of waiting for the plant to grow.
