### ISSUE TITLE
[1.9.4] Suggestion - XP Tank for XP Obelisk

### ISSUE THREAD

**Issue by praetoras** [SleepyTrousers/EnderIO#3442]
#### Reason for Suggesting:

If you have large bases with multiple crafting stations where XP is needed, having it accessible at those locations would be very useful.

- The XP obelisk itself can hold an apparently unlimited amount of XP. You can extract this to a tank, but doing so isn't a good idea because then you have finite storage.
- If you have multiple obelisks, you can connect them to a central obelisk for storage, but then you can't see how many levels you have available unless you to go the storage obelisk.

#### Suggestion:

- Create an XP-specific fluid "tank" which has a digital readout of the number of levels stored, and isn't limited on the amount of XP it can contain.
- Enable Remote Awareness Upgrades for the tank or its conduits, so that connected XP obelisks can display the number of levels available in the tank.

**Comment by HenryLoenwind** [comment]
added to the suggestion list

**Comment by condensedapple** [comment]
Possible workaround: Fluid Storage Bus from Extra Cells => Liquid XP in your ME System and therefore easily distributable

**Comment by bookerthegeek** [comment]
Even better, linked obelisk with shared tanks?
