### ISSUE TITLE
[1.9.4] [3.0.0.45] Redstone Conduits not picking up, or dropping off signal

### ISSUE THREAD

**Issue by Rosethorns** [SleepyTrousers/EnderIO#3443]
#### Issue Description:
RS Conduits do not always seem to pick up signals or even deliver them.
Please refer to screenshot.
http://i.imgur.com/YjugJYa.jpg
This seems to be worse on multi-coloured networks
Strong/Weak setting changes absolutely nothing

#### What happens:

Redstone signals are not appropriately transfered using RS conduits

#### Steps to reproduce:

1. connect conduit to a redstone output, (preferably non vanilla source like your power monitor)
2. connect conduit to a redstone input, (this can be redstone or other vanilla source)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.45
- EnderCore: 0.4.0.26
- Minecraft: 1.9.4
- Forge: 12.17.0.1968

#### Your most recent log file where the issue was present: 
No log.

**Comment by tahg** [comment]
The redstone input block needs a block update for the conduit to supply power to it (it connects visually when placed)

**Comment by CrazyPants** [comment]
Hopefully fixed in 3.0.0.46
