### ISSUE TITLE
GUI crash

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [SleepyTrousers/EnderIO#3444]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### Steps to reproduce:

1. set block (farming station or conduit)
2. open GUI
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.9.4-3.0.0.45_alpha
- EnderCore:EnderCore-1.9.4-0.4.0.26-alpha
- Minecraft: 1.9.20
- Forge: forge 12.17.0.1980

#### Your most recent log file where the issue was present: 

crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  LoadingPlugin (Quark-beta-29.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 6/24/16 10:29 AM
Description: Ticking screen

java.lang.NoSuchMethodError: net.minecraftforge.common.ForgeHooks.canInteractWith(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/inventory/Container;)Z
	at com.enderio.core.client.gui.GuiContainerBase.func_73876_c(GuiContainerBase.java:158)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1719)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.enderio.core.client.gui.GuiContainerBase.func_73876_c(GuiContainerBase.java:158)

-- Affected screen --
Details:
	Screen name: crazypants.enderio.conduit.gui.GuiExternalConnection

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheInternetGuy'/1, l='MpServer', x=-1002.95, y=84.00, z=-1000.18]]
	Chunk stats: MultiplayerChunkCache: 195, 195
	Level seed: 0
	Level generator: ID 06 - skyworld, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,86,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 57624 game time, 21945 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['TheInternetGuy'/1, l='MpServer', x=-1002.95, y=84.00, z=-1000.18]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:390)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 556932624 bytes (531 MB) / 1220018176 bytes (1163 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.28 Powered by Forge 12.17.0.1980 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1980-1.10.0.jar) 
	UCHIJAAAA	Forge{12.17.0.1980} [Minecraft Forge] (forge-1.9.4-12.17.0.1980-1.10.0.jar) 
	UCHIJAAAA	MineTweaker3{3.0.9} [MineTweaker 3] (CraftTweaker-1.9-3.0.9.jar) 
	UCHIJAAAA	dimensionalcake{0.0.1} [Dimensional Cake] (dimensionalcake-1.9.4-0.0.1.jar) 
	UCHIJAAAA	endercore{1.9.4-0.4.0.26-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.26-alpha.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.9.4-3.0.0.45_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.45_alpha.jar) 
	UCHIJAAAA	enderthing{0.6.8} [Enderthing] (enderthing-1.9.4-0.6.8.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.9.4-alpha-1.0.0a.jar) 
	UCHIJAAAA	inventorytweaks{1.61-beta-54-009e843} [Inventory Tweaks] (InventoryTweaks-1.61-beta-54.jar) 
	UCHIJAAAA	IronChest{6.0.146.788} [Iron Chest] (ironchest-1.9.4-6.0.146.788.jar) 
	UCHIJAAAA	jacb{1.0.6} [JACB] (JACB-1.9.4-1.0.6.jar) 
	UCHIJAAAA	JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar) 
	UCHIJAAAA	jeresources{0.4.6.39} [Just Enough Resources] (JustEnoughResources-1.9.4-0.4.6.39.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4b.jar) 
	UCHIJAAAA	planttech{1.6.0} [Planttech] (planttech-1.6.0 - 1.9.4.jar) 
	UCHIJAAAA	quantumflux{2.0.7} [QuantumFlux] (quantumflux-1.9.4-2.0.7.jar) 
	UCHIJAAAA	Quark{beta-29} [Quark] (Quark-beta-29.jar) 
	UCHIJAAAA	refinedstorage{0.7.16} [Refined Storage] (refinedstorage-0.7.16.jar) 
	UCHIJAAAA	skyresources{0.6.8 Alpha} [Sky Resources] (skyresources-0.6.8 Alpha.jar) 
	UCHIJAAAA	terrainCrystals{1.0.8} [Terrain Crystals] (Terrain Crystals - 1.9.4 - 1.0.8.jar) 
	UCHIJAAAA	wailafeatures{0.3.1.11} [WAILA Features] (WAILA-features-1.9.4-0.3.1.11.jar) 
	UCHIJAAAA	Woot{1.9.4-0.3.0-beta} [Woot] (woot-1.9.4-0.3.0-beta.jar) 
	Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
LoadingPlugin (Quark-beta-29.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'Intel' Version: '3.0.0 - Build 8.15.10.2279' Renderer: 'Intel(R) HD Graphics Family'
	EnderIO: No known problems detected.
	Launched Version: forge-12.17.0.1980
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics Family GL version 3.0.0 - Build 8.15.10.2279, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: net.minecraft.client.Minecraft$15@ad95940
[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
see #3438

**Comment by TheGuyFromTheInternet** [comment]
got it. Thank you.
