### ISSUE TITLE
Any way to toggle off certain enchantments in the game like XP Boost etc?

### ISSUE THREAD

**Issue by LordHellscream** [SleepyTrousers/EnderIO#3447]
#### Issue Description:
Other than soulbound, I do not see options in config to toggle off some of the custom enchantments, is there a way to do it ? (such as toggle off XP Boost, auto smelt etc).

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.41_alpha
- EnderCore: 0.4.0.24
- Minecraft: 1.9.4
- Forge: 1960

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by CrazyPants** [comment]
The enchantments are added by Ender Core and can be turned off in its config file.
