### ISSUE TITLE
[1.7.10] SAG Mill creates infinite Matter Overdrive Tritanium

### ISSUE THREAD

**Issue by forrester-marc** [SleepyTrousers/EnderIO#3448]
Matter Overdrive Tritanium Plates cost two ingots to craft, and mill into three dust.
- EnderIO: 2.3.0.426_beta
- EnderCore: 0.2.0.35_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

**Comment by HenryLoenwind** [comment]
We don't have any recipes for any item with "matter", "over" or "trit" in its name.

**Comment by forrester-marc** [comment]
This may be the Matter Overdrive mod injecting their own recipe, then.
Will do some detective work.

**Comment by Zsashas** [comment]
I can confirm this happens, with version 0.4.1 (latest for 1.7.10, other than mysterious beta releases) of Matter Overdrive. Two Tritanium Ingots side-by-side to make a Tritanium Plate, which can be SAG-Mill'd into 3 Tritanium Dust.
