### ISSUE TITLE
Fluid conduit will not connect to Tinker's Construct tank

### ISSUE THREAD

**Issue by lanAnderson** [SleepyTrousers/EnderIO#3449]
Minecraft 1.10.0
Forge 12.18.0.1996
EnderCore 1.10-0.4.0.29
EnderIO 1.10.3.0.0.50_alpha
Tinkers Construct 1.9.4-2.3.3

It stopped working after the fluid changes in Forge for 1.9.4, so it also does not connect in the 1.9.4 build.

**Comment by HenryLoenwind** [comment]
see #3375
