### ISSUE TITLE
generator swapped names

### ISSUE THREAD

**Issue by generilisk** [SleepyTrousers/EnderIO#3451]
#### Issue Description:
Stirling Generator & Combustion Generator names are swapped.

#### What happens:
Stirling generator utilizes combustion, Combustion generator utilizes heat exchange.

#### What you expected to happen:
Combustion generator utilizes combustion, Stirling generator utilizes heat exchange.

#### Steps to reproduce:
1.Read the names

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.9.4-3.0.0.43-alpha
- EnderCore:1.9.4-0.1.0.26-alpha
- Minecraft: 1.9.4
- Forge:12.17.0.1968

**Comment by AnrDaemon** [comment]
Thanks for a good laugh.

**Comment by AnrDaemon** [comment]
And to be absolutely clear, Combustion generator uses coolant just like your usual vehicle engine does.
It does not use "heat exchange".

**Comment by AnrDaemon** [comment]
That said, may be add an optional Coolant input for Stirling? To increase its efficiency?

**Comment by CrazyPants** [comment]
The combustion generator is an internal combustion generenator, just like you car, that noisy dielsal generator that stinks so much etc
