### ISSUE TITLE
[Enh] Add optional Coolant input for Stirling engine

### ISSUE THREAD

**Issue by AnrDaemon** [SleepyTrousers/EnderIO#3453]
From the most laughable #3451, this is just an idea: add an optional Coolant input for Stirling? To increase its efficiency.

**Comment by MatthiasMann** [comment]
What about a 2nd coolant block which can be placed on top / below the stirling engine and make it a multi block?
Maximum 1 coolant block per engine, requires constant water feed etc...

**Comment by AnrDaemon** [comment]
Sounds interesting.Some kind of "heat exchanger", which can benefit some other machines may be.
And below, of course :D I'm feeding fuel from the top!

**Comment by HenryLoenwind** [comment]
added to the list
