### ISSUE TITLE
1.7.10 -- Integration with Magical Crops - Farming Station only harvests seeds and primary essence drop

### ISSUE THREAD

**Issue by PegasusRider** [SleepyTrousers/EnderIO#3454]
#### Issue Description:

Farming Station plants and harvests crops quite well. However, all drops beyond the seed for the crop and it's primary essence type seem to be lost in the bit bucket.  (This would be the Essence of Nature and Weak Essence rare drops from crops that drop them.)
#### What happens:

When harvesting, seeds fill machine input inventory and then output, primary essence type goes to output, other drops never appear in machine inventory or on the ground from harvest operations.
#### What you expected to happen:

All drops to be recognized and placed in the machine's appropriate inventory for use and/or transport to storage.
#### Steps to reproduce:
1. Set up any non-fruit/vegetable crop from Magical Crops (magicalcrops-1.7.10_0.1) as you would any other farm crop
2. Observe the output from the Farming Station.
3. I've tried various types of vanilla hoes, and the Shiny Hoe from TE... other hoes won't seem to go in the machine. /shrug
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: EnderIO-1.7.10-2.3.0.427_beta
- EnderCore: EnderCore-1.7.10-0.2.0.36_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

It's not really an error, so please forgive the lack of logs. I've figured out a way to just use the Farming Station as a planter and harvest with other methods to get all the drops, but it's tedious to set up and might not suit other's needs/space limits. It would be merely a convenience if this could be corrected in mod. Of course, if I'm doing something wrong... let me know, as my search via the web revealed no assistance.

**Comment by HenryLoenwind** [comment]
We collect everything the plant gives us. If anything is missing that means that the plant has not returned it to us.

**Comment by PegasusRider** [comment]
I'm intrigued to understand how Magical Crops knows that a machine is doing the harvesting then. LOL I ran Coal, Dye, Air, Water, Fire, and Earth several cycles with Farming Stations not one Essence of Nature or Weak Essence... doing it by hand took less than one same size area of one crop to get a drop. I can't believe my luck with the machines could be that bad. This is not to argue your statement at all, I believe it. Just wonder how the other mod knows the difference and refuses to drop the additional stuff.

**Comment by mindforger** [comment]
@PegasusRider ` other drops never appear in machine inventory or on the ground from harvest operations` this line makes me believe, it is an intended mod behaviour, checking if a real or a fake palyer is harvesting and not granting the drops for making it not too easy! 

You might think it is a neat idea of automating several methods of gaining resources, but often the mod developer has an special mechanic for that and wan't you to use it or he wan't you to do it by hand all the time!

Mod devs also have intentions when writing mods and sometimes they force you to follow em ... *cough* *cough* botanias endoflame *cough* *cough*

**Comment by PegasusRider** [comment]
There is that. But... figuring out how to automate is part of the fun for me. Once I figure out how to do it (even in vanilla I could auto farm these crops, tedious to set up mind you)... the bar on having a machine just do it is fairly moot. Mod developer's intent is understood, but after a certain point it's just a tedium that should be skip-able. I'm at the point where I'm just playing to see what can and can't be done. MFR won't work (I don't have the right version for the "patch" to work or I have too dang many mods or ?) But I only really wanted a planter. Ender IO to the rescue... I just noted that the rares weren't ever showing up if harvesting too. If it's not EIO's fault, then no big deal. I know Magical Crops has attacked the automated farming "problem" from a lot of directions in the past, I'm sure it is an ongoing effort (when in dev) since so many people get upset about things being too easy. (Believe it or not, me too) But there should be a way of breaking that barrier down eventually. And Ender's stuff is pretty top end, expense wise, so you won't ever just start out with these things. LOL

**Comment by mindforger** [comment]
`Mod developer's intent is understood, but after a certain point it's just a tedium that should be skip-able` well then ask the other mod dev if this is a mishap on his side eventuall as Henry said earlier or if he would kindly ignore the fake player situation or give adives on how to get the dropped stuff to work :D 
sometimes there is an option in the configs, you could have a look there first

**Comment by HenryLoenwind** [comment]
I had a look at magical crops. The essences are not dropped by the plants themselves. Instead there is an event handler for the HarvestDropsEvent which looks if the harvester is a player with one of the magical crops hoes in its hand and then creates the essence.

**Comment by PegasusRider** [comment]
Mark has been decidedly silent for some time (from what I saw on the forums). Configs also didn't show anything obvious, though it's certain I could have missed something.

**Comment by HenryLoenwind** [comment]
it's a side effect of the way it checks for the tool that is being used. Which just won't work for a plant that uses the vanilla seeds way of getting harvested.

**Comment by PegasusRider** [comment]
@HenryLoenwind Well, alrighty then :)

Oddly, if you sticky piston the farmland and push it (from below) with a mature crop... everything drops that you expect if you did it by hand. Programming is so... interesting.

**Comment by PegasusRider** [comment]
Probably it's forcing a crop drop (the piston) rather than a harvest and so it gets the same Event handler?

**Comment by PegasusRider** [comment]
At any rate, thanks for looking into it deeper than I know how to go. Truly appreciated!

**Comment by HenryLoenwind** [comment]
it would just get a blockBreak, no harvest or such things. I see no handling for that, but it's not really easy to see when looking with a decompiler into an obfuscated jar...

**Comment by PegasusRider** [comment]
^^^ exactly my point. I have not enough of an idea what you're talking about.  LOL  Hence, really and sincerely, thank you.

**Comment by PegasusRider** [comment]
Honestly, with all the awesome conduits provided, and the vacuum chests... the piston package and timer is a small cost to me. I was just hoping it might be something addressable programmatically, for compactness of final build ;)  (unavoidable... okies!)  Understanding why they aren't dropping makes so much more sense now.

**Comment by mindforger** [comment]
i have an evil idea @HenryLoenwind XD you can fire the event with the given tool in the slot and if it is not invalidated, then catch the event and cancle it yourself, then do your normal way of crop treatment ?!

**Comment by HenryLoenwind** [comment]
yes, or we could generate the essence ourselves, which I'd prefer in this case. However, we are quite understaffed, and added new features to 1.7.10 is so very low on the agenda... :(

**Comment by mindforger** [comment]
wait this is 1.7 ??? *facepalm* @PegasusRider use an Autonomous Activator from Thermal Expansion, this should probably do the trick

**Comment by PegasusRider** [comment]
@mindforger AA was a no go, not with any tool would it harvest anything.

**Comment by mindforger** [comment]
did you power it properly and configure it properly to use either left or right click and use first slot item only mode!?

**Comment by PegasusRider** [comment]
indeed :)

**Comment by mindforger** [comment]
then welp and sorry for OT, good luck with porting
