### ISSUE TITLE
Necrotic Bones drop too frequently

### ISSUE THREAD

**Issue by MineWitherMC** [SleepyTrousers/EnderIO#3455]
#### Issue Description:
If replaceWitherSkeletons in EnderIO config is set to true each skeleton drops TiCon necrotic bone. And by default it's set to true.

#### What happens:
I tested in gamemode 1, killed 12 W.S. and got 12 necrotic bones. Also I got 2 wither skulls, not sure if this is intended. The sword didn't have Looting nor it was Dark-Steel sword (normal diamond sword).

#### What you expected to happen:
I disabled that option, teleported into the nether as W.S. only spawn there, killed 20 Wither Skeletons (with same sword) and got 5 necro-bones and 1 wither skull.

#### Steps to reproduce:

1. Set option replaceWitherSkeletons to true (or simply don't change it), install TiCo
2. Each skeleton (or at least 90%) will drop TiCo necrotic bone.
3. Profit!
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.427
- EnderCore: 0.2.0.36
- TinkersConstruct: 1.8.8.991
- Minecraft: 1.7.10
- Forge: build 1566

**Comment by HenryLoenwind** [comment]
We do not create any items on the death of our skeleton, much less a modded item from another mod. Those are generated by TiC.

**Comment by MineWitherMC** [comment]
Ok, thanks for support!

**Comment by HenryLoenwind** [comment]
just a sec, I'm checking something else

**Comment by HenryLoenwind** [comment]
this will take a day or two, I need to talk to someone who's not online atm. I'll come back to you

**Comment by Fer121345** [comment]
I am playing on 1.7.10 and the skeletons are not dropping the necrotic bones, I thought it was a problem on my friend's server and went on to singleplayer and it still doesn't work, I don't know how to set the config for EnderIO to true so they drop the bones
could you let me know how to do it please

**Comment by Fer121345** [comment]
ok, I found out how to do it, I did it on singleplayer and still nothing, they won't drop them, I don't know what else to do
