### ISSUE TITLE
[1.9.4] Cannot put lever on killer joe

### ISSUE THREAD

**Issue by LordHellscream** [SleepyTrousers/EnderIO#3456]
#### Issue Description:
Note: Somehow I wasn't able to place a lever on the killer joe

#### What happens:

Not able to put lever on killer joe, was able to do so on other Ender io machines.

#### What you expected to happen:

Put lever on

#### Steps to reproduce:

1. make a killer joe
2. place it on flat land
3. stay sufficiently away to put a lever on it
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.46
- EnderCore: 0.4.0.26
- Minecraft: 1.9.4
- Forge: 1960

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Levers can only be placed on solid blocks, that is a vanilla mechanic.
