### ISSUE TITLE
[1.9.4] XP absorbed by killer joe doesn't repair sword with mending enchant (other enchant works fine)

### ISSUE THREAD

**Issue by LordHellscream** [SleepyTrousers/EnderIO#3457]
#### Issue Description:
XP absorbed by killer joe doesn't repair sword with mending enchant (other enchant works fine)

#### What happens:

XP absorbed by killer joe doesn't repair sword with mending enchant (other enchant works fine)

#### What you expected to happen:
Mending works with killer joe like other enchantments

#### Steps to reproduce:

1. equip killer joe with mending sword 
2. watch it kill stuff
3. observe sword for damage
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.46
- EnderCore: 0.4.0.26
- Minecraft: 1.9.4
- Forge: 1960

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Have you enabled Mending support in the config?

**Comment by LordHellscream** [comment]
Wow, you guys thought of everything, I did not notice that.
