### ISSUE TITLE
(sorry I have no idea what but it crashed) Maybe Telepad? 1.9.4

### ISSUE THREAD

**Issue by Bellwar** [SleepyTrousers/EnderIO#3458]
#### Issue Description:
It is a modpack in Brave Technology - New World, but the author is gone for vacation so he can´t help with it at all.
Crashlog is full of crashed code from a Telepad classes.
I got crash after returning from the nether after problem with HQM

#### What happens:
So after a crash in Nether from HQM got the Nether reset. I build a portal from obsidian and went back to the world which wasn't reset. I got just crashed with HUGE crash log

#### What you expected to happen:
Not to crash the game after coming from the nether.

#### Steps to reproduce:
Maybe this way, I have no idea.
1. Use quest that is in Brave Technology and goes to the nether.
2. Go back from the nether.
3. Crash?
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-0.4.0.26-alpha
- EnderCore: 1.9.4-3.0.0.46_alpha
- Minecraft: 1.9.4
- Forge: 12.17.0.1987

#### Your most recent log file where the issue was present: 

Crash log:
http://pastebin.com/5Qq6wRWy

log file: (you can see the first lines are from the start up it's not so much after the HQM crash)
http://pastebin.com/QLnMdZdV

**Comment by HenryLoenwind** [comment]
How did you even get one? The TelePad is disabled because it doesn't work...

**Comment by Bellwar** [comment]
I have no idea I don't even know what it is. I just came from Nether how I told you.
BTW it crash after loading again.

**Comment by CrazyPants** [comment]
you will need to delete it using world edit or something
we have removed the recipe because it doesnt work

**Comment by HenryLoenwind** [comment]
if you never built a telepad that means your overworld got corrupted too. Because now there is a block that has the telepad's ID...

**Comment by Bellwar** [comment]
God I hate HQM it is so buggy and not supported well... THX i will see what can I get from it or from backups
