### ISSUE TITLE
[1.10] Soul Binder not functioning properly on server only

### ISSUE THREAD

**Issue by dirtyfargo** [SleepyTrousers/EnderIO#3460]
#### Issue Description:
When on a server, the Soul Binder will accept my levels for the recipe, but then pause and not do anything else. When I switched my world to single-player it seemed to fix the issue and functioned as intended.

#### Steps to reproduce:

1. Start up a server with EnderIO, EnderCore, & Forge versions listed below
2. Connect & place a creative capacitor & Soul Binder & Insert Correct Recipe Ingredients
3. Click use levels, and it should freeze or pause instead of completing the task

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.51_alpha
- EnderCore: 0.4.0.31-alpha
- Minecraft: 1.10
- Forge: 12.18.0.2000

#### Your most recent log file where the issue was present: 
-- I can post the full fml-server log if needed, not sure if relevant. Here's a picture of what it looks like when it freezes if that's any help:

![f895122e3f0149436ccba217cf003c68](https://cloud.githubusercontent.com/assets/10457528/16428181/901d3bcc-3d25-11e6-89fb-7e43b7b866a8.png)

**Comment by CrazyPants** [comment]
I am guessing that the configs are not in sync between server and client. The default XP cost was changed recently. I am guessing your client thinks it costs 4 levels, while the server thinks it costs 10.
As such, the client (via the GUI) sends four levels to the server and thinks its done, while the server does nothing as it didnt get enough XP.

Could you check this is the case and let us know?

**Comment by dirtyfargo** [comment]
Yes that is exactly what was going on, just checked the configs, thank you :)
