### ISSUE TITLE
[Suggestion] Killer Joe

### ISSUE THREAD

**Issue by CristinoValdigem** [SleepyTrousers/EnderIO#3461]
Hi, i use the killer joe on my mobtrap and i need do a lot of swords for leave on Killer Joe... And i try to put the broadswords "from tinker's construct mod" inside of killer joe and don't accept. I Think the integration can be a very interesting because i can add more durability and do a sword with higher damage and when the sword broke and i can repair her for use again instead make another sword... have a possibility to add this integration on mod to minecraft version 1.7.10 ?

**Comment by HenryLoenwind** [comment]
added to the list, thx.

**Comment by CristinoValdigem** [comment]
Thanks ;)
