### ISSUE TITLE
[1.9.4] - Waila capacitor block name and icon missing

### ISSUE THREAD

**Issue by Lazarix** [SleepyTrousers/EnderIO#3462]
#### Issue Description:
Icon for capacitor block when placed in the world and block description missing. :
http://i.imgur.com/Mnj6vZb.png

#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.9.4-3.0.0.46_alpha
- EnderCore: EnderCore-1.9.4-0.4.0.26-alpha
- Minecraft: 1.9.4
- Forge: forge-1.9.4-12.17.0.1987-universal.jar

**Comment by HenryLoenwind** [comment]
That's a bug in WAILA. One of many.
