### ISSUE TITLE
Suggestion: Gas conduits to support Mekanism gases.

### ISSUE THREAD

**Issue by SpeedySpy52** [SleepyTrousers/EnderIO#3464]
This is a mod compatibility thing (obviously), which I understand is probably not high on the priority list, but it would really be a good quality-of-life addition. I much prefer EnderIO conduits to all of the other options from various tech mods because of their ability to be placed in the same block as another conduit and their extreme flexibility. Mekanism is a popular tech mod, but its special gases aren't able to be carried by any of EnderIO's conduits - meaning you have to use the mod's built-in tubes, which aren't nearly as awesome as conduits. **So basically my suggestion is this: conduits that can carry those gosh darn annoying gases.**

**Another option would be letting gases through fluid conduits** (which is honestly better in my opinion; after all, a _fluid_ is technically a liquid _or_ a gas). It would also mean that there wouldn't have to be any extra items added. The only reason this wasn't my first suggestion was because i'm not sure how feasible it is from a coding standpoint.

I realize that this kind of thing really isn't that important, but i'm suggesting it anyway because i'm annoyed with Mekanism pipes and want to use EnderIO more in my world.

Please consider this as a possible compatibility addition.

**Comment by mindforger** [comment]
@SpeedySpy52 did you ever try searching former issues with the words "gas conduit" ?

**Comment by HenryLoenwind** [comment]
if this gets suggested one more time I will *remove* our gas conduits...

**Comment by SpeedySpy52** [comment]
After seeing this reply i realized how much of a spoon I am...
Sorry xD

**Comment by MatthiasMann** [comment]
@SpeedySpy52 just to clarify why you haven't seen these already in the game - which language do you use in Minecraft and for what have you searched? Also which Mek and EIO version are you using?

**Comment by HenryLoenwind** [comment]
and don't feel too bad, this happens to many people. We get this suggestion about once per month...
