### ISSUE TITLE
[1.9.4] The Attractor Obelisk does not "Attract" instead it "Repels"

### ISSUE THREAD

**Issue by sigsus** [SleepyTrousers/EnderIO#3465]
#### Issue Description:
so the issue is in the title, it repels the mobs instead of attract them.
it also pushes the mobs towards North dirrection
Edit: EnderIO version : EnderIO-1.9.4-3.0.0.46_alpha
modpack : Avant 2 (1.9.4) version : 1.14
Mob : Blaze

#### What you expected to happen:
that mobs get attracted

#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- Minecraft: 1.9.4

#### Your most recent log file where the issue was present: 

https://gyazo.com/37fa2068a81d7019496fa900d71b35e3

**Comment by HenryLoenwind** [comment]
It works here, so this will be difficult to diagnose...

**Comment by sigsus** [comment]
dont know if other mobs than blazes work

**Comment by HenryLoenwind** [comment]
ok, I haven't tried blazes, so let's hope it's them ;)

**Comment by HenryLoenwind** [comment]
yes, it is blazes. I guess it's because they go on distance for attacking.

**Comment by AnrDaemon** [comment]
Hunters. It's always hunters.

**Comment by sigsus** [comment]
may skeletons do the same cuz they also go the distance?

**Comment by HenryLoenwind** [comment]
no, skeletons work. They are handled differently. Blazes have their own special handling, which seems to need some adaptions to 1.8, 1.9 or 1.10 vanilla changes.

**Comment by HenryLoenwind** [comment]
will work in next build
