### ISSUE TITLE
[Enhancement?] fluid tank control [Bug?] fluid conduits do not attach to tinkers smeltery

### ISSUE THREAD

**Issue by tom89194** [SleepyTrousers/EnderIO#3466]
The redstone control for the fluid tank effects the filling and emptying of buckets, but not the sides configured to push or pull. This would be a handy feature as a second and separate configuration of redstone control, (I can think of situations where one would want redstone to control the use of buckets but not effect the push/pull)

When I attempted to use fluid conduits on the tinkers smeltery drains they refused to connect.
(If this is due to unfinished implementation of the new fluid handler ignore me, I am not trying to hurry you guys on the new fluid handler. I only mention this in case it is a bug)

these are on a server environment

Reproduction
On multiplayer server

Observe that tanks now interface with the tinkers smeltery again (hurray, and Thanks)
Place fluid conduit next to drain
Observe that it does not automatically connect to drain
Curse whilst smacking offending conduit with Yeta Wrench on side of conduit facing drain
Curse again cause you thought that since the tanks interfaced with the smeltery then surely the conduits would too............ ;}
____
#### Affected Versions (*Do* use "latest", do not claim "latest"):

- EnderIO: 1.10-3.0.0.51
- EnderCore: 1.10-0.4.0.31
- Minecraft: 1.10
- Forge: 1.10-12.18.0.2000

Thanks again

**Comment by HenryLoenwind** [comment]
#3375 is still open and on the first page of the issues...
