### ISSUE TITLE
[1.9.4] issue with yeta wrench crash

### ISSUE THREAD

**Issue by CitiesXL2815** [SleepyTrousers/EnderIO#3467]
#### Issue Description:
My issue is hovering the cursor over the yeta wrench causes the game to crash, plus i don't know what the other 3 lines are supposed to be for.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.46
- EnderCore: 0.4.0.26
- Minecraft: 1.9.4
- Forge: 12.17.0.1987

#### Your most recent log file where the issue was present: 

[https://gist.github.com/CitiesXL2815/26df6ecba0c865510b9b90fc8662f7d5]

**Comment by HenryLoenwind** [comment]
My suggestion would be:

1. Configure the key binding for the yeta wrench to a key combo, e.g. Ctrl+Y
2. Hover the mouse over a yeta wrench item
3. Press shift

**Comment by HenryLoenwind** [comment]
should work in the next build, at least if my guess of a key combo was right.

**Comment by CitiesXL2815** [comment]
oh i think, i know why it's bind to my mouse, thats why it crashed thx for your help
