### ISSUE TITLE
[suggestion] [1.7.10] Galacticraft Oxygen

### ISSUE THREAD

**Issue by Cronosus** [SleepyTrousers/EnderIO#3468]
Hello

#### Issue Description:
Conduits (except energy conduit) are not compatible with galacticraft machines,
working with Oxygen. (liquid and gas)

conduits not connect to them and not transfer gas or liquid oxygen.

Please, can you make it compatible?

Thanks in advance.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.427_beta
- EnderCore:EnderCore-1.7.10-0.2.0.36_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

**Comment by HenryLoenwind** [comment]
added to the list. However, there is nobody working on the "new features for 1.7" list.
