### ISSUE TITLE
Crash when right clicking Vibrant Capacitor Bank (maybe any capacitor bank)

### ISSUE THREAD

**Issue by TopWraith** [SleepyTrousers/EnderIO#3476]
#### What happens:

I right click my vibrant capacitor bank to see its current storage and attempt to charge items on my friends server. My client crashes and I have to relog into the server.
#### What you expected to happen:

The capacitor bank inventory opens up.
#### Steps to reproduce:
1. Login to Server
2. Right Click Capacitor Bank
3. Crashes 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.7.10-2.3.0.427_beta
- EnderCore: 1.7.10-0.2.0.36_beta
- Minecraft: 1.7.10
- Forge: 7.10.99.99
#### Your most recent log file where the issue was present:

[crash-2016-07-05_20.09.52-client.txt](https://github.com/SleepyTrousers/EnderIO/files/347507/crash-2016-07-05_20.09.52-client.txt)

**Comment by mindforger** [comment]
hasn't this been fixed?! 

just by chance, do you have a botania item in your slots? remove it and if it does not persist, update botania to the very last version

**Comment by HenryLoenwind** [comment]
See https://github.com/Azanor/Baubles/issues/121

**Comment by TopWraith** [comment]
It might have been, i'll have to let my friend know, he's set the mods up himself so might not have the latest ones that we should use. 

I'll take a look Henry, thanks. 

I don't have botania items in my inventory, i havent started with that mod.

**Comment by TopWraith** [comment]
Okay, i removed my ring of flight, and that meant i can access capacitor banks successfully. I'll see if we can get this figured out. :)

Thanks for the help!

**Comment by HenryLoenwind** [comment]
Ok, short summary of the issue: Baubles can act strangely which leads to item callbacks being called with bad data. Items that don't expect that will crash.

**Comment by TopWraith** [comment]
Yeah, I was reading through. From what I read in the other thread, there was a fix posted?
Can you please confirm the fix and I'll see if I am able to get my friend to update EnderIO with that fix?

**Comment by HenryLoenwind** [comment]
The fix was for that one Botania item to ignore the bad data and not crash. Here the com.baublelicious.items.ItemFlyingRing is crashing.

**Comment by TopWraith** [comment]
Okay, similar but different. I'll not use that ring for the moment, also look into using maybe the extra utilities flying ring. :)

Thanks for the help, I'm kinda horrible at figuring out those crashes. I thought this was related to a different issue, bow of the wyvern doesn't charge unless its 'cheated in' but it's not, and atleast I figured that out.

**Comment by mindforger** [comment]
this one was confusing the first time as well :D
you should report this over to baubleicious and hint them the changes from botania to adapt it
