### ISSUE TITLE
Endercore saying minimum of core version 0.3.0.14-beta when using 3.0.0.26

### ISSUE THREAD

**Issue by COMTOP1** [SleepyTrousers/EnderIO#3477]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Crashes and opens up the forge bad install screen

#### What you expected to happen:
To start normally

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.8.9
- Forge:1.8.9-1890

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Doesn't it say "cannot load mod endercore because it is for Minecraft 1.9.4 and you are using Minecraft 1.8.9"?
