### ISSUE TITLE
Server Crash [1.9.4] : After Long Idle Time

### ISSUE THREAD

**Issue by arakielG** [SleepyTrousers/EnderIO#3478]
#### Issue Description:
If my server has been idle too long (possibly long enough to unload chunks from memory) the next login will cause the server to hang and eventually crash.  Restarting the server 'fixes' the problem.

#### What happens:
Server crash

#### What you expected to happen:
No crash

#### Steps to reproduce:

1.  Logout from a server and wait awhile for chunks to unload (seems to be a couple hours on my setup)
2. Login
3. Get in world but unable to interact with anything for 2-3 minutes, eventually get disconnected.  Server has crashed.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.9.4
- Forge:

#### Your most recent log file where the issue was present: 

http://pastebin.com/Xq1d5cha

**Comment by Spencer-H** [comment]
I believe this may be the same error. We leave the server idling over night and when someone tries to log in the next day this occurs.

[crash-2016-07-10_13.03.35-server.txt](https://github.com/SleepyTrousers/EnderIO/files/356131/crash-2016-07-10_13.03.35-server.txt)

**Comment by HenryLoenwind** [comment]
This should be fixed with the changes in build 58
