### ISSUE TITLE
Relocation obelisk doesn't appear to do anything

### ISSUE THREAD

**Issue by LordHellscream** [SleepyTrousers/EnderIO#3480]
#### Issue Description:
relocation obelisk (I assuming will teleport anything within the area of effect that match the soul bottles) away. But it doesn't work.
#### What happens:
relocation obelisk doesn't appear to work

#### Steps to reproduce:

1. place the relocation obelisk, put in a zombie soul bottle, connect to RF source and make sure its powered, and make sure the redstone option is set to always active
2. spawn a few zombies in the area of effect
3. observe
Nothing happens!
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.0.46
- EnderCore: 0.4.0.26
- Minecraft: 1.9.4
- Forge: 1960

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
it only relocates naturally spawning mobs

**Comment by LordHellscream** [comment]
Ok, i did another test, this time I am doing on my regular survival world. I created a obelisk without any soul vials, and its teleporting my endermans! (the ones I am spawned by powered spawner), and it does absolutely nothing to the zombies that knocking on my door (with or without the soul vial with zombie soul).

**Comment by LordHellscream** [comment]
Ok I did another tests this time on my survival world with zombie soul vial, and it doesn't do anything to do the zombie (which are naturally spawned).

**Comment by VT-14** [comment]
I haven't seen this block yet, but I assume it is meant to act similarly to an Extra Utils Magnum Torch.  Mobs that spawn in its are of effect either don't spawn at all, or are more likely just teleported away the moment they spawn.  All other mobs (spawners, cursed earth, player moved, probably even walk-ins, etc.) are allowed to spawn and/or enter the area of effects so you can still have usable mob farms.

To test if it is working that way, go into a super flat world, make it daytime, and construct 2 dark rooms, one under the effects of the Obelisk and the other outside of the effects.  Turn the difficulty to anything other than peaceful (hard would be best).  The room outside the effects should spawn mobs quite quickly, the one inside the area of effects should be empty, and if it is teleporting mobs then it should have a bunch of mobs outside of it.

**Comment by HenryLoenwind** [comment]
You can also just put it down, add power and soul vials, fly up 30 blocks and make it night. That works for my in my dev env.

Also, please not that Zombies, Zombie Villagers and Husks are 3 different mobs type for Ender IO machines.
