### ISSUE TITLE
server crash enderio bug report

### ISSUE THREAD

**Issue by IchigoGames** [SleepyTrousers/EnderIO#3481]
#### Issue Description:
hello lately i've had some issues with enderio that are crashing my server i am also the modpack author of The New Frontier on curse. a 1.1.0 test pack i was not going to make this report at first as i know you have a lot on your plate. but as this is the only thing crashing the server atm i decide to go ahead and make it.

#### What happens:
the server crashes tho its hard for me to give you more info as i was not on when it happened i think it could be buggy forge code. but it looks like forge is no longer going to do anymore updates to 1.10 if thats the case then sorry for bothering you.

#### What you expected to happen:
well for it not to crash.

#### Steps to reproduce: 

1.it seems to do it more when no players are online so its hard to say for sure.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:-1.10-3.0.0.55_alpha
- EnderCore:-1.10-0.4.0.33-alpha
- Minecraft: 1.10
- Forge:1.10-12.18.0.2000

#### Your most recent log file where the issue was present: 

https://www.dropbox.com/s/pe0bcptweh6rtgy/fml-server-latest.log?dl=0

https://www.dropbox.com/s/9jbs1ihvk5ubzdm/crash-2016-07-05_20.19.22-server.txt?dl=0

**Comment by HenryLoenwind** [comment]
see #3478
