### ISSUE TITLE
[1.10] Redstone Conduit Crash

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [SleepyTrousers/EnderIO#3482]
#### Issue Description:
This does occur in a modpack, and I work by the modpack devs side, it doesn't seem to be connected to any other mod, but again I am not the best at reading logs.

#### What happens: Server closes as i joined, this only happened twice, I restarted and the server is fine now. I'm only reporting this just in case it is an issue. some of the questions asked do not really apply.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:{1.10-3.0.0.55_alpha}
- EnderCore:{1.10-0.4.0.33-alpha}
- Minecraft: 1.10
- Forge: 2000

#### Your most recent log file where the issue was present: 
http://pastebin.com/p0MUZUvp

**Comment by HenryLoenwind** [comment]
#3478

**Comment by EPIICTHUNDERCAT** [comment]
can you direct me to the first post? i looked for a similar post but didnt find one, i do apologize.

**Comment by mindforger** [comment]
just hit the issue number he wrote, it is a link, it is beeing worked on

**Comment by HenryLoenwind** [comment]
Yes, that.

Sry I'm on mobile, so short on words ;)

**Comment by EPIICTHUNDERCAT** [comment]
Haha no issue, yeah I noticed after I asked, thanks and sorry for not noticing!
