### ISSUE TITLE
[Request] Support for Actually Additions Canola plants for Farming Station

### ISSUE THREAD

**Issue by b0bst3r** [SleepyTrousers/EnderIO#3483]
Can you please add support for the canola plants, atm the farming station does plant them and does harvest them but does not pick up the canola (produce) or the canola seeds.

seedCanola
cropCanola

Plants are 1 high and drop multiples of both the seed and crop but neither is picked up.

ActuallyAdditions-1.10.2-r47
EnderIO-1.10-3.0.0.55_alpha
EnderCore-1.10-0.4.0.33-alpha
Forge-1.10.2-12.18.0.2005

Want me to post a forge log for this?

**Comment by HenryLoenwind** [comment]
no need for logs. This sounds like the produce is dropped on the ground? In that case please report it to Actually Additions, that would be a bug on their side.

**Comment by HenryLoenwind** [comment]
Update: I had a look at their code, it looks fine. I'll have to load this into a debugger to se what's going on. But not today or tomorrow, sry.

**Comment by b0bst3r** [comment]
Nvm I'm an idiot.... the problem is between the keyboard and chair
