### ISSUE TITLE
[Enh] Direct color picker for conduits.

### ISSUE THREAD

**Issue by AnrDaemon** [SleepyTrousers/EnderIO#3485]
Please add a direct color picker for conduit connectors.
A small dialogue poping up with a square of colors like this one:
![ProjectBlue panel wiring](http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/ProjectBlue/doc/Colours.png)

Preferable with the same color layout.

**Comment by HenryLoenwind** [comment]
tagged to be found again, closed to keep the list of open issues short
