### ISSUE TITLE
1.10.2 - Killer joe does not repair mending tools

### ISSUE THREAD

**Issue by garyyo** [SleepyTrousers/EnderIO#3486]
#### Issue Description:
the mending enchantment causes items with the enchantment to repair for the cost of experience, instead of the experience being collected. the killer joe kills things, and collects the experience it drops, so logically you might expect it to be able to handle the mending enchantment. this does not happen. 

#### What happens:
mending sword does not get repaired in killer joe with xp

#### What you expected to happen:
mending sword does get repaired in killer joe with xp

#### Steps to reproduce:

1. Place mending sword in killer joe
2. allow killer joe to kill and collect xp
3. watch as the sword with mending enchant does not get mended

____
#### Affected Versions 

- EnderIO: 0.10-3.0.0.55_alpha
- EnderCore: 1.10-0.4.0.33-alpha
- Minecraft: 1.10.2
- Forge: 12.18.0.2008

#### Your most recent log file where the issue was present: 
this is not that kind of issue...

**Comment by HenryLoenwind** [comment]
have you enabled that feature in the config?

**Comment by garyyo** [comment]
no. turns out i missed it.

**Comment by KidPerneta** [comment]
I'm having the same problem but i enabled the feature in the config
