### ISSUE TITLE
[1.10.2] Boat Crash?

### ISSUE THREAD

**Issue by 63502** [SleepyTrousers/EnderIO#3487]
#### Issue Description:
For some reason, whenever I place a boat in my world, my game freezes completely and permanently for the world unless I remove the boat entity with MCEdit.

#### What happens:

World freezes completely.

#### What you expected to happen:

Nothing, I am just placing a boat.

#### Steps to reproduce:

1. Place vanilla boat of any type
2. Watch game freeze

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10-3.0.0.60_beta
- EnderCore:1.10-0.4.0.35-beta
- Minecraft: 1.7.10
- Forge:1.10.2 - 12.18.0.2008

#### Your most recent log file where the issue was present: 

https://gist.github.com/63502/d9880a7645c30725dcea5df25b074624

Since the error does not crash the game, I have taken a piece of the game output from the launcher instead. Everything after the first two lines is related to the boat error (I think...:P). If this is not an EnderIO error, if possible, please tell me where it originates from so I can post it in the right place for it to be fixed (I am not a programmer, so I cant really tell much past the obvious stuff).

Thanks,
     63502

**Comment by HenryLoenwind** [comment]
Report this to "Streams - Real Flowing Rivers!", they are crashing.

**Comment by 63502** [comment]
thanks :P
