### ISSUE TITLE
[1.10.2] Crash on server startup

### ISSUE THREAD

**Issue by kwpugh** [SleepyTrousers/EnderIO#3488]
#### Issue Description:
Crash on server startup

#### What happens:

Crash on server startup

#### What you expected to happen:

Not crash?

#### Steps to reproduce:

1.update new versions of EnderIo and EnderCore
2.Start server
3.Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.0.1.62_beta.jar
- EnderCore:EnderCore-1.10.2-0.4.1.38-beta.jar
- Minecraft: 1.10.2
- Forge: 2008

#### Your most recent log file where the issue was present: 

http://pastebin.com/raw/ArkryvE3

**Comment by HenryLoenwind** [comment]
build 63 is on its way

**Comment by kwpugh** [comment]
Thank you.   You are doing great work with this mod.

**Comment by kwpugh** [comment]
Server starts fine.   Now we get client-side crash joining the server.   Doesn't seem to play nicey nicey with RFTools.

crash report: http://pastebin.com/raw/G3Pg0X6V

**Comment by HenryLoenwind** [comment]
Just a simple and dumb copy&paste error, giving the wrong coordinate as parameter.

Fixed in next build.

**Comment by kwpugh** [comment]
Everything fine in build 64.
