### ISSUE TITLE
[Suggestion] New end-tier (hah) alloy.

### ISSUE THREAD

**Issue by Dhvagra** [SleepyTrousers/EnderIO#3489]
It occurred to me that the mod doesn't have an alloy/material made with endstone. I think such an alloy would be a cool addition (since it is called **Ender**IO). 

I was thinking this alloy could be used for some Obelisks or something in that corner. Another thought was a new tier capacitor, made with the new alloy.

Please feel free to do whatever you want with this idea. Don't feel pressured.

Thanks for the wonderful mod, guys!

**Comment by AnrDaemon** [comment]
May be purpur then? Because End Stone is… like… Like a regular stone.

**Comment by b0bst3r** [comment]
vibrant ingot + crushed end stone + energetic ingot = IEnder Ingot (white in color) make Hoe with it (3000 durability) to give Farming station less maintenance

**Comment by Dhvagra** [comment]
Ooh purpur is a nice idea. Would be a nice purple ingot. And would fit in
the colour scheme.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by VT-14** [comment]
Unbreakable Tools to be used by automation would be really nice.  Maybe make them only effectively usable by automation?  Maybe make the block breaking speed take a ridiculously long time (machines break instantly anyway) and have attack damages of 0 or massively long attack recharge times.  I think the set would only need an Axe, Hoe, and Shears to cover all the Ender IO machines.  A sword would be a fair addition for the Killer Joe; ideally doing very little damage if held by a player but doing a good amount of damage when held by a Killer Joe.

Maybe keep the right click functionalities?  Hoes make Tilled Soil, a Shovel could make Grass Path, and Shears could shear sheep.
