### ISSUE TITLE
[Suggestion] Inventory Panel Security

### ISSUE THREAD

**Issue by Unforgiven31** [SleepyTrousers/EnderIO#3492]
If I play on a Public Server, anyone can access my Inventory Panel, is there a way to add security system to it, maybe like the Travel Anchor (Private,Protected,Public)

Thanks for the wonderful mod!

**Comment by AnrDaemon** [comment]
So does anyone can acces your chests or machines. Inv. panel is no magic, it's a techincal device.
If you have social issues, this is not the way you can solve them.

**Comment by Unforgiven31** [comment]
Normally Public Servers have Anti Grief Systems on Chests at least, and you can claim chunks for your base, where only you can place blocks, i can secure my base, but if anyone can reach the Panel will have access to all items.

The way i would do without the security system is removing the Inventory Panel every time i logout, and is not a social issue, its a public server after all, if you don't care about your items they easily disappear.

Thanks anyway (sorry if i misspelled something, i'm not a native english speaker)

**Comment by HenryLoenwind** [comment]
added to the list

**Comment by AnrDaemon** [comment]
Same anti-grief protection that prevent interaction with chests, will prevent interaction with panel.
This is not EIO's problem to solve.

**Comment by HenryLoenwind** [comment]
All Ender IO GUIs now ask the Forge Permission System for permission before opening.
