### ISSUE TITLE
1.10.2 - Dark boots drain of charge when flying with elytra

### ISSUE THREAD

**Issue by garyyo** [SleepyTrousers/EnderIO#3493]
#### Issue Description:
Dark boots constantly drain RF while falling. This is normally not an issue (albeit rather strange) but when using elytra to fly this RF constantly drains. This causes for any long form flights to completely drain the boots of power and is kinda uncool. This rampant RF drain does not happen when using the dark chestplate and glider upgrade.

#### What happens:
Using dark boots empowered upgrade with elytra flight continually drains RF from boots.

#### What you expected to happen:
Dark boots use RF when reducing fall damage, 

#### Steps to reproduce:

1. get pair of dark boots with the empowered upgrade
2. charge them
3. equip elytra and fly around
4. notice how boots have discharged

____
#### Affected Versions

- EnderIO: 3.0.1.64
- EnderCore: 0.4.1.38
- Minecraft: 1.7.10
- Forge: 12.18.0.2008

**Comment by HenryLoenwind** [comment]
Found the issue. The Elytra forces the fall distance to be "1" all the time while flying. (Other methods of flight set it to "0".)

Starting with the next build, the boots will ignore fall distances of 1 and below. Note that diving with the Elytra does produce fall distances that still will be removed for RF. There's no way for the boots to look into the future to see if you'll hit the ground or pull up in time. I tried just disabling the fall damage reduction while flying with the Elytra---and died hitting the ground on my first flight...
