### ISSUE TITLE
Storage drawers issue specific to the inventory panel.

### ISSUE THREAD

**Issue by Darkritual1117** [SleepyTrousers/EnderIO#3495]
#### Issue Description:

Thank you and apologies to Tterrag for directing me here. Sadly i am not able to provide as much information as i would like to on these issues as the files are gone, but i am still posting this in the hopes it may be helpful. Also i see there have been a few updates to Ender IO since i was last able to play so some of this may have been resolved, however is case it hasnt im going to give as much information as i can.

These issues are specific to the inventory panel working with the storage drawers mod. The reason i say this is that 2 other inventory mods were tested at the same time(logistic pipes and AE2) both of those mods were able to accurately read the storage drawers inventory, only the inventory panel had an issue. I have seen this happen through multiple versions of ender io and through multiple modpacks.

Inventory panel will report multiple items, from several other mods, as different items. Inventory panel will sometimes pull items for recipes incorrectly.
First time posting here so forgive me if i mess anything up. 
#### What happens:

This happened with several blocks when using an inventory panel hooked up to storage drawers, but say i wanted a draconic core. if i looked in the inventory panel for that it would not be there but in reality it was there but the inventory panel was reporting it as another item, in this case i think it was a sky stone block from AE2. there were many other blocks that had similar issues but this one stuck out in my memory. also there were times where you would pull a recipe into the inventory panel from nei and it would pull all the needed items but not put the recipe in the correct order in the crafting grid.
#### Steps to reproduce:

Unfortunately i am unable to provide the steps to reproduce this. as all the files are gone in a windows reformat where i forgot to backup the minecraft directory. This did happen in Infinity evolved(i understand that was heavily modified and may not be relevant)  and in both sky factory 2.4 and 2.5(once again a modpack but i have my reasons for reporting it here so please do not be irritated)

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO:  EnderIO-1.7.10-2.2.5.311.jar   -   EnderIO-1.7.10-2.3.0.424_beta
- EnderCore:    -    EnderCore-1.7.10-0.2.0.32_beta
- Minecraft: 1.7.10 some similar issues seen on the 1.10 versions being streamed by those on the forgecraft server.
- Forge:  10.13.0.1208 - 10.13.4.1614
#### Your most recent log file where the issue was present: unable to provide due to the aforementioned windows reformat.

I hope that some of this helps. i know its not much to work with(darn windows 10 reformat).

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
This has been fixed recently.

**Comment by tterrag1098** [comment]
Maybe. I think it's at worth investigating if it's still an issue as I'm not sure the recent fix addresses this.

**Comment by 016Nojr** [comment]
I have also experienced this.
