### ISSUE TITLE
[QoL] Killer Joe uses sword until it has 1 durability left

### ISSUE THREAD

**Issue by Peach774** [SleepyTrousers/EnderIO#3496]
Apparently the killer joe will use a weapon until it breaks, even if it is a nice enchanted weapon. It would be nice if it would use it until right before it breaks, so that you can repair the weapon.

**Comment by AnrDaemon** [comment]
Mending, or just not give it a sword you can't lose.

**Comment by Peach774** [comment]
Mending doesnt work. That was something else I wanted to bring up.

**Comment by AnrDaemon** [comment]
It is not "doesn't work", it is disabled by default.

**Comment by Peach774** [comment]
Mending is disabled by default?

**Comment by Peach774** [comment]
why?

**Comment by AnrDaemon** [comment]
Do read mod config before posting, please.

**Comment by Peach774** [comment]
Why is it disabled by default. That makes no sense. And If I dont want to enable this to encourage using the anvil, It should still leave the weapon with 1 durability. This post isnt worthless.

**Comment by AnrDaemon** [comment]
If something doesn't make sense FOR YOU, that doesn't mean it doesn't make sense at all.
You're not the Lord Creator of the Universe, and your opinion isn't the truth in the last instance.
If you want that option, there's a config you can enable for it. Case closed.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
