### ISSUE TITLE
Photovoltaic Cells not craftable when disabling Dimensional Transceiver

### ISSUE THREAD

**Issue by Cakestory** [SleepyTrousers/EnderIO#3498]
#### Issue Description:
Photovoltaic Cells are not craftable when disabling Dimensional Transceiver in EnderIO.cfg under category "item enabling".
Only tested with Dimensional Transceiver. Disabling other items in this category may lead to same error.

#### Steps to reproduce:

1. Navigate to EnderIO.cfg file
2. Set "B:transceiverEnabled=true" under category "item enabling" to false 
3. Look up recipe for Photovoltaic Cells in JEI or try to craft them manually -> NOT working.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.64_beta
- EnderCore: 1.10.2-0.4.1.38-beta
- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.0.2009

**Comment by HenryLoenwind** [comment]
fixed in next build
