### ISSUE TITLE
[1.10.2] [server crash]

### ISSUE THREAD

**Issue by DaemosDaen** [SleepyTrousers/EnderIO#3501]
Issue:
	Farming station crashes server
	
Description:
	When planting trees with farming station it will crash a deticated server, this does not happen in singleplayer. This occured with BOP trees and Vanilla on BOP loamey dirt/grass

Expectation:
	For trees to be planted and harvested w/o crashing the server

Replicate:
	connect to deticated server (can be in creative)
	drop a farming station
	Put saplings in it (did nto test forrestry saplings)
	put a charged capasitor (any quality) on it.
	collect crash logs.
	
Crash log:
EnderCore-1.10.2-0.4.1.38-beta.jar
EnderIO-1.10.2-3.0.1.64_beta.jar
forge-1.10.2-12.18.0.2010
Minecraft version 1-10-2-0

Full mod list attached

[crash-2016-07-10_20.11.10-server.txt](https://github.com/SleepyTrousers/EnderIO/files/356292/crash-2016-07-10_20.11.10-server.txt)
[crash-2016-07-10_20.12.56-server.txt](https://github.com/SleepyTrousers/EnderIO/files/356291/crash-2016-07-10_20.12.56-server.txt)
[crash-2016-07-10_20.30.55-server.txt](https://github.com/SleepyTrousers/EnderIO/files/356293/crash-2016-07-10_20.30.55-server.txt)
[crash-2016-07-10_20.39.19-server.txt](https://github.com/SleepyTrousers/EnderIO/files/356295/crash-2016-07-10_20.39.19-server.txt)
[Mod List.txt](https://github.com/SleepyTrousers/EnderIO/files/356294/Mod.List.txt)

**Comment by HenryLoenwind** [comment]
It seems some mod is adding a new type to Forge's EnumPlantType. Which will lead to crashes with all mods that handle plants.

**Comment by HenryLoenwind** [comment]
Update: Which seems to be exactly what Forge intends. The adding, not the crashing.

**Comment by DaemosDaen** [comment]
It was also happening with vanilla saplings.

**Comment by HenryLoenwind** [comment]
Which is a clear sign that someone adds a new plant type and modifies vanilla saplings. Because vanilla saplings are not plantables, and the code would have crashed 10 times typing to get to where you have the crashes with unmodified saplings.

("CustomSeedFarmer" should actually be named "DefaultSeedFarmer")

**Comment by DaemosDaen** [comment]
Unfortunately it works in single player, which is gonna make it hard to find out who is doing it.
