### ISSUE TITLE
EnderIO crashes on Forge 12.18.0.2007

### ISSUE THREAD

**Issue by bence98** [SleepyTrousers/EnderIO#3502]
#### Issue Description:
EnderIO will refuse to start on Forge 12.18.0.2007, saying that it needs at least Forge 12.18.0.2007

#### What happens:
It shows a prompt about unsatisfied dependencies

#### What you expected to happen:
That the game would start, as I am on the correct Forge version

#### Steps to reproduce:

1. Start EnderIO with Forge 12.18.0.2007
2. Stare at the screen

____
#### Affected Versions:

- EnderIO: 1.10.2-3.0.1.65-beta
- EnderCore: 1.10.2-0.4.1.38-beta
- Minecraft: 1.10.2
- Forge: 12.18.0.2007

#### Your most recent log file where the issue was present: 

http://pastebin.com/UDCUynHp

(Most relevant lines: line 2, line 124, line 476-477)

**Comment by HenryLoenwind** [comment]
That message comes from Forge, not us.

**Comment by bence98** [comment]
Yes, but it complains about EnderIO's dependency

**Comment by HenryLoenwind** [comment]
Which contains exactly the same version number we use to compile against. I have no idea what Forge is doing with their version numbers, and quite honestly I have better things to do with my time then debugging Forge. We still have over 40 known bugs and unported features on our TODO list and I haven't even started porting my own mod. And it's not as if this was a general problem. For most people it works.

**Comment by mindforger** [comment]
@bence98 
`This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR`

the "crash report" around line 100 is not an crash at all

but if it crashes, can you please post the crashlog from your crashlog folder instead the logfile, which does not contain any crash report at all?
