### ISSUE TITLE
[1.10.2] Crash on server startup

### ISSUE THREAD

**Issue by kwpugh** [SleepyTrousers/EnderIO#3503]
#### Issue Description:
Server crashes on start with new version of EnderIO

#### What happens:
Server crashes on start with new version of EnderIO

#### What you expected to happen:
No crash

#### Steps to reproduce:

1.Add updated EnderIO
2.Start server
3.Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.0.1.66_beta.jar
- EnderCore:EnderCore-1.10.2-0.4.1.38-beta.jar
- Minecraft: 1.10.2
- Forge:2010

#### Your most recent log file where the issue was present: 

http://pastebin.com/raw/ixYXWRz6

**Comment by HenryLoenwind** [comment]
fixed in next build
