### ISSUE TITLE
Server Crash Issue #3478 Still Happening but on 1.10.2 Now

### ISSUE THREAD

**Issue by arakielG** [SleepyTrousers/EnderIO#3504]
#### Issue Description:

After server has been idle for long periods, when a player logs in the server gets hung up and eventually crashes
#### What happens:

After server has been idle for long periods, when a player logs in the server gets hung up and eventually crashes
#### What you expected to happen:

No crash
#### Steps to reproduce:
1.  Leave server idle, overnight usually will do it but i've seen it happen after just a few hours
2. Logon to server
3. Server will eventually crash, crash log attached
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: EnderIO-1.10.2-3.0.1.67_beta
- EnderCore: EnderCore-1.10.2-0.4.1.38-beta
- Minecraft: 1.10.2
- Forge: 12.18.0.2010
#### Your most recent log file where the issue was present:

http://pastebin.com/FepZjT9w

**Comment by arakielG** [comment]
I should have mentioned, as before, when you start the server back up everything is fine again

**Comment by HenryLoenwind** [comment]
All those watchdog-related crashes should be gone with the current Endercore. Closing this, please comment if it still happens, I can re-open the ticket then.
