### ISSUE TITLE
1.10.2 - Forge Bucket from Fluid Tank

### ISSUE THREAD

**Issue by Peach774** [SleepyTrousers/EnderIO#3506]
With Forge Buckets enabled you can not pull liquids out of a fluid tank from the inventory.

**Comment by HenryLoenwind** [comment]
Forge buckets do not register as buckets, that's a bug in Forge

**Comment by Peach774** [comment]
What? But it hasn't been 'fixed' in forge and no one else is having a problem. Doesn't that make it your fault?

**Comment by mindforger** [comment]
why is this his fault?! its a missing support at most.

I prefere him working on real issues instead of workarounds for other peoples faults that may be patched later, rendering the effort for the workaround a waste of time :)
