### ISSUE TITLE
Buckets and Fluid Tanks

### ISSUE THREAD

**Issue by Susjin** [SleepyTrousers/EnderIO#3507]
#### Issue Description:

When right-click with an empty bucket in an tank with some kind of liquid, i get a thousand of buckets of that liquid

#### What you expected to happen:

Get only 1 bucket of that liquid

#### Steps to reproduce:

1.Fill an tank with any liquid
2.right-click with an empty bucket

___
#### Affected Versions (Do *not* use "latest"):

- EnderIO:3.0.1.64_beta
- EnderCore:0.4.1.38-beta
- Minecraft: 1.10.2

**Comment by HenryLoenwind** [comment]
Forge buckets or Ender IO buckets?

**Comment by Susjin** [comment]
I'm using the forge buckets, and i updated for ender io 3.0.1.67 beta and still the same

it's missing the log file because i didn't saw nothing related to ender io, but if you want i can put it

**Comment by HenryLoenwind** [comment]
Ok, that is a bit surprising, as Forge buckets aren't supposed to work with Ender IO at all.

I think what is happening is that some other mod had the same problems with those buckets and they decided to solve it by registering those buckets in the bucket registry themselves. But they made a small mistake and instead registering "1 bucket of x = 1000 mB of y" they registered either "1 bucket of x = 1 mB of y" or "1000 bucket of x = 1000 mB of y".

**Comment by Susjin** [comment]
Oh ok, that make sense, i'll try to disable forge buckets and see if it will work, thanks for the help!

**Comment by Susjin** [comment]
Well that didn't fix it, i still getting a thousand of buckets of the liquid inside the tank, the only thing i can think is that another mod is causing that problem, but for me to test it will be very hard, because the game take a lot (like 30 minutes) to enter a world, and that's because i don't have much RAM, i'll post the modlist here and if you know what mod is causing that problem i would be grateful

http://pastebin.com/pWiqgZhC

**Comment by mindforger** [comment]
can you go to the log folder, remove all logs, launch a game up where you are standing in front of a tank with a buckt in your hand, take a bucket and then close the game (to keep the log as short as possible)

then upload the logs as attachment, maybe there can be found some usefull info in the logs

**Comment by HenryLoenwind** [comment]
I can make a debug build of ender io tomorrow, so we can see what exactly is in the registry. However, I don't think we can find out who puts it there easily. We'd need a debug build of Forge for that.

I'll look at the modlist when I get home. There shouldn't be too many mods in there that handle buckets. I can test them in my dev env. That only takes 4-5 minutes to boot up, not 30... ;)

**Comment by Susjin** [comment]
http://pastebin.com/kBuZKuBj

this is the log, and i know it should not take that long time to load, but for some reason it takes, the MultiMC log freeze when appear something like Registered Plugin from JEI and then an message like

"Can't keep up! Did the system time change, or is the server overloaded? Running 713345ms behind, skipping 14266 tick(s)"

and sometimes take less time, sometime more, but i really think the problem is because i have only 4GB RAM and my pc have a lot of things

**Comment by mindforger** [comment]
combathelp-1.9.4-1.0.2.jar seems broken, please redownload
something is very badly interfering with your IC2 Mod, some foreign Core Mod seems to corrupt it!
your open computer core seems not compatible with minecraft 1.10.2

but this has nothing to do so far with your issue, just a hint for fixing other bugs

**Comment by HenryLoenwind** [comment]
I just got home. And I'm too tired to do anything useful. I'll have a look tomorrow evening. Sorry.

If you want to help me: Which of those mods (apart from the well-known big ones) does have machines/tanks that interact with buckets?

**Comment by Susjin** [comment]
mindforger thanks for the help, i'll see what i can do =D

I found out today that the Universal fluid cell from IC2 doesn't get me a thousand of cells of that liquid
There is no problem if you are tired, i do not want to force you to do these things

For the mods, Deep Resonance adds a tank and the liquid of the mod has its own properties, i don't know if when you take that liquid in a bucket it will remain its properties, but that could be the problem.This is the only not big one mod that add tanks

**Comment by kamyflouge** [comment]
i've been having the same problem since i updated my industrialcraft2  from -2-2.6.1-ex110 to industrialcraft-2-2.6.11-ex110. it started happening to me since i updated it.

**Comment by HenryLoenwind** [comment]
sounds like a good lead, thx!

**Comment by Susjin** [comment]
Well the industrialcraft version that i have is the 2.6.10-ex110 and still happening, didn't you install any other mod? or just updated industrialcraft?

**Comment by HenryLoenwind** [comment]
I can confirm this with industrialcraft-2-2.6.11-ex110 installed. Now I can start debugging...

**Comment by HenryLoenwind** [comment]
And found it. Yes, IC2 is the culprit. One of its JEI recipe handlers calls getRegisteredFluidContainerData() and modifies the item stacks that are returned, making it so that filling a bucket with water gives 1000 water buckets.
