### ISSUE TITLE
Crash on World Loading with Funky Locomotion

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [SleepyTrousers/EnderIO#3510]
I Setup a large Funky Locomotion Setup and I use EIO cables to provide power to them, and I hidden the conduicts (Tier2 power + redstone) using facades. I when I left the world I was helding a Funky Locomotion Wrench (I believe). Now everytime I try to load up the world my client crashes because it tries to hide the facades because I hold the FLM wrench.

- EnderIO-1.7.10-2.3.0.427_beta.
- EnderCore-1.7.10-0.2.0.36_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

crash report: http://paste.ee/p/XrSAn

**Comment by HenryLoenwind** [comment]
Yes, this is caused by Funky Locomotion.

**Comment by HenryLoenwind** [comment]
and here's the existing issue: https://github.com/rwtema/FunkyLocomotion/issues/88

**Comment by SmokeyTheBandicoot** [comment]
How can I solve this? If I remove FLM I will lose my contraption. Deleting my inventory would solve the issue?

**Comment by HenryLoenwind** [comment]
Visit rwtema at home and hit him with a rubber duck until he fixes his mod? ;)

But yes, purging your inventory would help.
