### ISSUE TITLE
Alloy smelter duplication bug

### ISSUE THREAD

**Issue by Pyrocrafter** [SleepyTrousers/EnderIO#3511]
#### Issue Description:
Alloy smelter duplication bug

#### What happens:
the bug is produced by using the shortcuts from the ''simple inventory sorting'' mod by cpw. By inserting items in the top slot of the alloy smelter and then middle clicking on one of the items, the total number of items in the tops slots will go up by 1 or more, depending on how many items are already inserted. The more items are inserted, the more items appear.

#### Steps to reproduce:

1. put down an alloy smelter and put at least 4 items in the top slots. it has to be at least 4, as the smelter will immediatly smelt 3 of the inserted items. ( I don't know if the smelter has to be powered, but i didn't have enough time to thoroughly test it.)
2. click with the scroll wheel on one of the top 3 slots.
3. the total number in the top slots should increase by 1 or more, depending on the amount of items already present in the top slots.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.8.9-3.0.0.26_alpha
- EnderCore: 1.8.9-0.3.0.14_alpha
- Simple Inventory Sorting: 0.7.7+27
- Minecraft: 1.7.10
- Forge Mod Loader: 8.0.99.99
- Minecraft Forge: 11.15.1.1902

**Comment by AnrDaemon** [comment]
Are You sure you didn't messed the version info?

**Comment by HenryLoenwind** [comment]
This sounds like one of many bugs in inventory sorter that have been fixed in the meantime. : https://github.com/cpw/inventorysorter/issues?q=is%3Aissue+is%3Aclosed
