### ISSUE TITLE
Slice'N'Splice Destroys Materials with JEI (1.10.2)

### ISSUE THREAD

**Issue by Wolftousen** [SleepyTrousers/EnderIO#3512]
Issue Description:

Not sure if this should go to the JEI developer(s) or you.
JEI shift click to build all in Slice'N'Splice destroys all but one set of materials.

What happens:

One set of the materials you had gets built into the proper output, but the rest of the materials are destroyed.

No Crash

What you expected to happen:

Excess materials to remain in inventory or Slice'N'Splice to allow stacks of material sets.

Steps to reproduce:

Have 24 Soularium, 12 Zombie Heads, 24 Silicon and 12 Redstone Dust in your inventory.
Click to open the Slice'N'Splice.
Have an Iron Axe, Iron Shears, Double-Layer Capacitor in the Slice'N'Splice along with full energy and always on redstone setting (no other configuration).
Use JEI to find the Z-Logic Controller and shift click the + to build all.

Affected Versions (Do not use "latest"):

JEI: JEI_1.10.2-3.7.5.227
EnderIO: EnderIO-1.10.2-3.0.1.64_beta
EnderCore: EnderCore-1.10.2-0.4.1.38-beta
Minecraft: 1.10.2
Forge: 12.18.0.2010

**Comment by HenryLoenwind** [comment]
This is a bug in JEI. A new one, as the bug that JEI inserted whole stacks into the Slice'n'Splice was recently fixed. Seems that fix introduced a new one. Reference: https://github.com/mezz/JustEnoughItems/issues/298
