### ISSUE TITLE
[Request]Chisel connected textures

### ISSUE THREAD

**Issue by Susjin** [SleepyTrousers/EnderIO#3513]
In earlier versions of Ender IO (1.7.10), when an conduit facade was painted with any chisel blocks, it would connect to other chisel blocks that were they are not a facade, and that was awesome, i would like it a lot if the 1.10.2 version connects to 1.10.2 chisel version too

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
