### ISSUE TITLE
[1.10.2] Dark Clear Glass does not Block Light

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3516]
Just updated my modpack from 1.9.4 to 1.10.2 and Dark Clear Glass does not seem to block light anymore.
EnderIO: 1.10.2-3.0.1.67_beta

![2016-07-14_17 50 11](https://cloud.githubusercontent.com/assets/8670392/16846390/88e5a618-49ec-11e6-958d-58dba93b03ce.png)

**Comment by HenryLoenwind** [comment]
fixed in next build
