### ISSUE TITLE
Soulbound enchant dramatically reduces opportunities for more practical enchants

### ISSUE THREAD

**Issue by foxanthony1** [SleepyTrousers/EnderIO#3517]
Suggestion/complaint:

The Soulbound enchant shows up so often in vanilla enchanting it is frustrating as it takes up the slot a more generally useful enchant would.

Vanilla enchanting in 1.8+ is actually really useful unlike in previous versions of MC; so this wasn't really a problem. 

I just realized I can disable it in config and have done so.

That being said, maybe it should ship disabled?

Since the mod has it's own enchanting system why even put enchants in the vanilla enchanting table? [I'm saying this rhetorically, I don't really care if there is an answer for that question.]

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
BTW: you can configure the rarity of the soulbound enchantment in the config; they key is called "enchantmentSoulBoundWeight"
