### ISSUE TITLE
Farming Station works only once

### ISSUE THREAD

**Issue by IfElifElse** [SleepyTrousers/EnderIO#3518]
#### Issue Description:
The farming station in this mod works on 2 quadrants before stopping and never activating again. The station has full power, has a diamond hoe in it and 16 seeds in each of the seed slots. I'm using the station with crops from the magical crops mod. It is placed over water if that makes any difference.

#### What happens:
Once I place the station block down, it will harvest and replant the seeds in the northern and western quadrant before stopping completely.

#### What you expected to happen:
I expected the farm to harvest and replant the seeds in all quadrants and continue to do this every so often.

#### Steps to reproduce:
Inside of a minecraft world, Place down a farming station block.

#### Affected Versions:

- EnderIO: 1.7.10-2.3.0.426_beta
- EnderCore: 1.7.10-0.2.0.35_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1566

**Comment by HenryLoenwind** [comment]
update
