### ISSUE TITLE
[1.10.2] IC2 rubber wood in alloy smelter

### ISSUE THREAD

**Issue by cindylo** [SleepyTrousers/EnderIO#3521]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Getting Jungle Wood but it has a black and purple square texture.

#### What you expected to happen:
Smelting IC2 Rubber Wood in an allow smelter to gain jungle wood like normal.

#### Steps to reproduce:

1. Place an allow smelter
2. Put ic2 rubber wood in the alloy smelter
3. Wait for it to finish smelting
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.70_beta
- EnderCore: 1.10.2.0.4.1.40-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2011

#### Your most recent log file where the issue was present: 

http://aero-tech.me/sharex/uploads/U9V8W3P3.png

**Comment by HenryLoenwind** [comment]
What happens if you smelt it in a vanilla furnace?

**Comment by cindylo** [comment]
Normal jungle logs come out with no problems. Same with any other furnace that I tried. You can even place the black and purple one from the alloy smelter, it doesn't crash or break anything but the resulting item itself just doesn't work quite right.

**Comment by HenryLoenwind** [comment]
next build will handle cases like this better
