### ISSUE TITLE
[1.10.2]Item conduct crash when use to extract floppy disk to Hard drive (refine storage)

### ISSUE THREAD

**Issue by NanayaQ** [SleepyTrousers/EnderIO#3522]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

FTB Unstable 1.10 modpack

#### What happens:
I made a creative world for testing, I use storage drawer with an infinite withdraw of Floppy Disk 64k (Refine storage). I then connected the item conducts to all 8 Hard Drive and configure to item conduct to extract (with 15 speed upgrade) without red signal.

#### What you expected to happen:
Back in 1.9 It will extract the floppy disk and insert it to the hard drive, however on 1.10.2 it crashes throw an error.

#### Steps to reproduce:

1. Use Storage Drawers put in floppy drive 64k (refine storage) with an infinite withdrawal upgrade.
2. Place 1 or more hard disk drive (refine storage) then connect the items conducts to the infinite storage that has the floppy disk 64k.
3. use 15 speed upgrade on the item conduct that is connect to the storage with the infinite floppy disk 64k. Make sure all item conduct is config to insert on the Hard disk drive then turn off red stone signal.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.70_beta
- EnderCore: EnderCore-1.10.2-0.4.1.40-beta
- Minecraft: 1.10.2
- Forge: Forge Mod Loader version 12.18.1.2014

#### Your most recent log file where the issue was present: 
crash log:
http://pastebin.com/211hRYb7
[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
fixed in next build
