### ISSUE TITLE
1.10 - Crash when viewing an item recipe with inventory panel GUI open

### ISSUE THREAD

**Issue by Nentify** [SleepyTrousers/EnderIO#3523]
Crash log: http://pastebin.com/iuYgEM1D

Setup: ![](http://i.nentify.me/bTcx5Z3l.png)

Screen: ![](http://i.nentify.me/ORMsjUbI.png)

To reproduce, just hover over an item in your inventory and press 'R'

**Comment by HenryLoenwind** [comment]
Panel offline, no item database to check availability against...

Fixed in next build
