### ISSUE TITLE
Crash on RedstoneConduitNetwork.notifyConduitNeighbours

### ISSUE THREAD

**Issue by utoc** [SleepyTrousers/EnderIO#3524]
#### Issue Description:

Greetings.  This issue has been mentioned in a closed ticket, https://github.com/SleepyTrousers/EnderIO/issues/3429

I am seeing this issue persist in the current beta, 67, so I have opened a new ticket.  I cannot produce this at will, rather it seems to happen when the primary user of redstone conduits is offline and someone goes near his base.  I suspect that chunks are loading and unloading but I cannot be sure.  I'm sorry that I don't have more information than that.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.67_beta
- EnderCore: 1.10.2-0.4.1.38-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2011

#### Your most recent log file where the issue was present: 

I have three occurrences of it on a small server with only one user using redstone conduits.

MOST RECENT CRASH: http://pastebin.com/CadKag0Y

http://pastebin.com/8uyyTUhK
http://pastebin.com/iaG4uKvw
http://pastebin.com/qTqUXPUW
http://pastebin.com/2SPK4FC2
http://pastebin.com/eEBzvzby

EDIT: moved all my crash reports into one post to avoid bumping too often.  Most recent crashes will be towards the top

**Comment by utoc** [comment]
Not to beat a dead horse but I did confirm this behavior is present still in Beta 70.

http://pastebin.com/iaG4uKvw

**Comment by tterrag1098** [comment]
This not seem to be caused by EIO, we are just what is triggering the redstone update.

**Comment by HenryLoenwind** [comment]
I wouldn't rule our our redstone notifications running for too long, that's why I'd like CrazyPants to have a second look at his recent changes.

But all in all, the Watchdog killing the server because "it takes too long" without any more information on what's actually taking that time is not helpful at all.

**Comment by utoc** [comment]
@HenryLoenwind Is there anything I can do to get you guys more relevant information in regards to these crashes?  Debug/dev builds/anything.. Let me know, I'll be happy to implement it.

**Comment by CrazyPants** [comment]
I have had a look at this and I am not even sure it is EIO at fault.
Without more to go on I don't think there is much we can do.
Is the problem still happening?
If so, can you try and figure out what blocks are connected to redstone conduits in the area with the issue.

**Comment by utoc** [comment]
I've disabled the Redstone Conduits entirely for the past month so we haven't had any other crashes since then.  The only block at this point I can say we used conduits with were soul shards spawners, I may have had users using them with other blocks but a quick poll of my online users came up empty. We could never trigger this on command, it was random at best but consistently got worse as the number of RS conduits grew. The mods in my pack may present an edge case so it might be best to close this report and wait for someone else to come along experiencing it.

**Comment by CrazyPants** [comment]
Thanks for the update. I will do as suggested and wait for a more up to date report.

**Comment by utoc** [comment]
We've run across this issue again today.  This could be a one-off though

Crash here: http://pastebin.com/sb6tac70

Running FML 2095, EnderCore-1.10.2-0.4.1.56, EnderIO-1.10.2-3.0.1.116_beta

This crash happened during a user login attempt.  Like before, these crashes seem to always happen when the server has been empty for a few hours and then someone logs in.  There are no redstone conduits on the server, all other types though (item, power, fluid) are available.

Stall report (sampler mod) 1: http://pastebin.com/5t1gSBSr
Stall report (sampler mod) 2: http://pastebin.com/bv7j1fM6

Full log here:  https://gist.github.com/utoc/9c8697da8cc74cca36ec284eb7753bad

What are your thoughts about disabling the MC 1.10 watchdog and letting the server go on for as long as it wanted?
