### ISSUE TITLE
Fluid Tank duping Buckets

### ISSUE THREAD

**Issue by rockohamilton** [SleepyTrousers/EnderIO#3526]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### Steps to reproduce:

1.attach to water source (ender io)
2. put empty bucket in
3. collect 1000 full buckets
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.70
- EnderCore: 0.4.1.40
- Minecraft: 1.10.2
- Forge: 12.18.1.2014

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by mindforger** [comment]
and you probably duplicated a bug :D
https://github.com/SleepyTrousers/EnderIO/issues/3507
check if there is IC2 present

**Comment by HenryLoenwind** [comment]
yes, known bug in IC2
