### ISSUE TITLE
ender io base items will not craft. 

### ISSUE THREAD

**Issue by kain184** [SleepyTrousers/EnderIO#3527]
#### Issue Description:
conduit binder and capacitors will not remove from crafting bench.
#### What happens:
items when placed in crafting bench or any crafting 9x9 shows recipies. but when clicking or shift clicking from the bench the items pop back to the window without crafting. 
#### What you expected to happen:
items crafted after crafting process completes. 

#### Steps to reproduce:

1.place items into crafting window
2.pull items fail to pull from window
3.rage quit...
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.0.1.67_beta.jar
- EnderCore:EnderCore-1.10.2-0.4.1.38-beta.jar
- Minecraft: 1.10.2
- Forge:forge-1.10.2-12.18.0.2010-universal.jar

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
First, check that configs are the same on server and client. Second, check the server logfiles for recipe loading errors. Third, post the logfiles here.
