### ISSUE TITLE
Unlimited Lava bucket

### ISSUE THREAD

**Issue by pribibazsi** [SleepyTrousers/EnderIO#3528]
#### Issue Description:
The fluid tank generate lava.

#### What happens:
I ran a stirling generator with lava bucket. I fill the fluid tank with lava (This is in the top), and I set both machines to push pull. This works perfectly but the fluid tank generated unlimited amount of lava bucket.

Please fix the bug. It's unlimited amount of lava.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.0.1.70_beta
- EnderCore:1.10.2-0.4.1.40_beta
- Minecraft: 1.10.2
- Forge:12.18.1.2014
- FTB Unstable 1.10 v:4.2.3

#### Your most recent log file where the issue was present: 
Note: I have attached pictures.
[https://www.dropbox.com/s/ao532teutey6xcb/logs.rar?dl=0]

**Comment by HenryLoenwind** [comment]
That's a bug in IC2 exp, please report it to them. See #3507
