### ISSUE TITLE
[Suggestion] 1.9/1.10 Add support for TESLA (Energy) API

### ISSUE THREAD

**Issue by Tomson124** [SleepyTrousers/EnderIO#3529]
As a lot of mdos use it already and many of the already existing mods add support for it, it would be really good if you can add support for it, too, in the newer versions of EnderIO.
If you don't know to what I'm reffering: 
[https://github.com/Darkhax-Minecraft/Tesla](https://github.com/Darkhax-Minecraft/Tesla)

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by Tomson124** [comment]
Yo! 


I  just wanted to show you something  really amazing,  please check  it  out here <http://web.flatpennybarandgrill.com/e6lcq>

Later, tomson124
