### ISSUE TITLE
Bucket Dupe bug [1.10.2]

### ISSUE THREAD

**Issue by 016Nojr** [SleepyTrousers/EnderIO#3530]
#### Steps to reproduce:

1. Place fluid tank
2. Fill fluid tank
3. Insert bucket in top right slot
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.70_beta
- EnderCore: 1.10.2-0.4.1.40-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2014

#### Your most recent log file where the issue was present: 

Logs: http://pastebin.com/dN8gs68M

**Comment by HenryLoenwind** [comment]
Report this to IC2, they are causing this.

see #3507

**Comment by 016Nojr** [comment]
ahh, those bastards! :P
