### ISSUE TITLE
[1.10.2] Compatibility with EvilCraft's dark tank fluids

### ISSUE THREAD

**Issue by C0rn3j** [SleepyTrousers/EnderIO#3531]
I do not know on which side the problem is so I'm reporting it to both.

https://github.com/CyclopsMC/EvilCraft/issues/435

Below is a copy pasted issue linked above:

I'm trying to transfer blood from one dark tank to another through dimensional transceivers. Chunks are loaded, fluid transfer is enabled and set correctly, pipes are set correctly, I checked multiple times. It just won't transfer through the transceiver.

I tried extracting the blood from Tconstruct smeltery and it worked just fine, so I really don't know what the problem is.

Sending transceiver fluid menu: http://i.imgur.com/CyS5DRv.png

Receiving end: http://i.imgur.com/uw8fEwl.png

Modlist: http://pastebin.com/nvyVt5EE
Client forge 2014, Server forge 2010.

**Comment by c0rn3j** [comment]
Looks like I had 2 different types of blood in each tank, so EnderIO works as intended, I guess this can be closed.
