### ISSUE TITLE
[1.10.2] klicking Reservoir with empty bucket gets you 1000 buckets full of water in one stack

### ISSUE THREAD

**Issue by DietmarKrause** [SleepyTrousers/EnderIO#3533]
#### What happens:
since the last update of the pack to 1.10.2 (from 1.10) to Vers. 4.3.2.1-1.10.2 the Reservoir from enderio has a bug if you klick on it with an empty bucket to get water out of it, it gets you 1000 buckets full of water, in one stack. To get rid of them you can drop the "stack", log off and on again. This was definitly not the case in the last version of the pack.
PS: Ther reservoir was build in the prior version of the pack, 
This issue war reorted to the FTb makers of the mod, too.
Report here to be complete
 

#### What you expected to happen:
get a bucket full of water. Only one :)

#### Steps to reproduce:

1. build up a reservoir in a grid 2 x2
2. fill it with water
3. try to get a bucket full of water by clicking on it with a empty bucket
...

**Comment by HenryLoenwind** [comment]
This is a bug in IC2, report it there
