### ISSUE TITLE
Electromagnet works anywhere in inventory

### ISSUE THREAD

**Issue by warlordjones** [SleepyTrousers/EnderIO#3534]
While the tooltip says hotbar or bauble slot only. I'm not sure which is intended behaviour. 

____
#### Affected Versions:

- EnderIO: 3.0.1.64
- EnderCore: 0.4.1.38
- Minecraft: 1.10.2
- Forge: 12.18.0.2010

**Comment by HenryLoenwind** [comment]
check your config

**Comment by warlordjones** [comment]
Is that enabled by default?

**Comment by warlordjones** [comment]
Nope...my bad. Sorry!

**Comment by warlordjones** [comment]
That said, might be nice to have the tooltip changed based on config. Probably not worth it though.

**Comment by HenryLoenwind** [comment]
good point, I'll look into it. may be simple to do or may not be, depending on which tooltip framework the magnet uses. (sadly our items are split 50:50 there...)

**Comment by warlordjones** [comment]
Well that's neat, cheers :+1:
