### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AuaerAuraer** [SleepyTrousers/EnderIO#3535]
Hi SleepyTrousers :)
I have a suggestion about 2 of your mods : 

1- Ender Zoo : 
Concussion Creepers drop clay instead of gunpowder (Since the clay is very rare and is required by the conduits in EnderIO)

2- Ender IO : 
NEW BLOCK : Concussion TNT which is made of sand and clay instead of gunpowder (Since we gave the clay concussion ability then it would be terrible if we don't put it in a TNT)

That's all & THX for the awesome mods

**Comment by CristinoValdigem** [comment]
3 - Dimensional Transceivers
 You can turn her to send/receive infinite RF like Tesseract from Thermal Expansion

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
