### ISSUE TITLE
Missing texture - conduit probe

### ISSUE THREAD

**Issue by lilrichy** [SleepyTrousers/EnderIO#3536]
#### What happens:
Missing texture on the conduit probe when you switch it to copy mode.
Probe mode has texture. Copy mode does not.

#### What you expected to happen:
Should have a texture.

#### Steps to reproduce:
1.Equip Conduit probe.
2.Hold shift and scroll mouse wheel to switch to copy mode.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.71_beta
- EnderCore: 1.10.2-0.4.1.41-beta
- Minecraft: 1.10.2
- Forge:12.18.1.2014

#### Your most recent log file where the issue was present: 

![image](https://cloud.githubusercontent.com/assets/8129775/16969367/5a042eb0-4de2-11e6-80bd-962c4399c685.png)

**Comment by HenryLoenwind** [comment]
will be fixed in next build
