### ISSUE TITLE
Facades not orientating correctly

### ISSUE THREAD

**Issue by DnTheMn** [SleepyTrousers/EnderIO#3537]
#### Issue Description:
im using version 1.10.2 and the facades will not orient correctly

#### What happens:
most wont blocks wont matter but for logs they wont go horizontal only vertical

#### What you expected to happen:
i expected the log to go horizontal but it went vertical

#### Steps to reproduce:

1.get conduit
2.get facade
3.place facade on conduit
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.71
- EnderCore: 1.9.4-1.5.292
- Minecraft: 1.10.2
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Sorry, we don't have any artificial intelligence that could learn from your screen what a block does when you click at a certain position.

Just rotate it until it looks like you want it.
