### ISSUE TITLE
Suggestion: Dark Steel Shield

### ISSUE THREAD

**Issue by GabrielCorso** [SleepyTrousers/EnderIO#3538]
Hello, i'd like to make a suggestion for the mod team that i think would be fitting, a Dark Steel Shield.
Currently the only shields we have available are the vanilla ones, with terrible durability values, so i think an empowerable dark steel shield would be a nice addition to EnderIO.

**Comment by VT-14** [comment]
Can I get a link to the original suggestion? I want to see what responses it got, but I don't see anything related when searching for 'Shield.'
