### ISSUE TITLE
MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)

### ISSUE THREAD

**Issue by Gamerbolts** [SleepyTrousers/EnderIO#3539]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens: When loading the world the console is spammed with minecraft:builtin/missing. I only have Endercore 1.10.2, 3.0.1.73 and EnderIO 1.10.2, 0.4.1.41

There is no crash. But I do notice lagging in the world. And the console is spammed 5 times a second.

#### What you expected to happen:
Not having lag. And console not to be spammed

#### Steps to reproduce:

1. Have EnderIO/EnderCore Installed
2. Have Forge 2011 installed
3. Minecraft 1.10.2 - Run
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2, 0.4.1.41
- EnderCore: 1.10.2, 3.0.1.73
- Minecraft: 1.10.2
- Forge: 2011

#### Your most recent log file where the issue was present: 

[http://pastebin.com/r5srNGDH]

I am not a programmer or coder but when i see my console spammed with red I can't help but think something is wrong. Sorry if I am mistaken. Thanks for the assistance!

**Comment by HenryLoenwind** [comment]
That message is printed by Forge. And it is absolutely bogus.
