### ISSUE TITLE
[1.10.2] JEI Plugin not loading

### ISSUE THREAD

**Issue by exp111** [SleepyTrousers/EnderIO#3540]
The Just Enough Items Integration of EnderIO is not working, because the JEI Plugin is not loading correctly.
It doesn't crash but it's still annoying.
A few days ago it worked fine.

Don't know if it's JEI's fault or EnderIO one's.

- EnderIO: 3.0.1.71_beta
- EnderCore: 0.4.1.40-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2014
-JEI: 3.7.7.233

Found this in the log while JEI loaded the plugins:
Full log (too big for pastebin):
http://puu.sh/q88p3/822afc37e7.log

Specific Issue:
http://pastebin.com/nh4w2bea

**Comment by HenryLoenwind** [comment]
Please report this to the authors of the code that is actually crashing first. In this case (ignoring Forge): "alexndr"

**Comment by Sinhika** [comment]
Got it, working on it at my end.

**Comment by exp111** [comment]
Sinhika fixed it with a quick update of SimpleCore
