### ISSUE TITLE
Unable to open doors holding Yeta Wrench

### ISSUE THREAD

**Issue by 016Nojr** [SleepyTrousers/EnderIO#3541]
#### Steps to reproduce:

1. Right click a door with a Yeta Wrench

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.70_beta
- EnderCore: 1.10.2-0,4,1,40-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2014

**Comment by AnrDaemon** [comment]
Try opening and closing the door by hand before  that.
I've had a lot of issues like these even in 1.7.10.

**Comment by 016Nojr** [comment]
Done it multiple times, still happen

**Comment by HenryLoenwind** [comment]
right-clicking a door with a wrench should actually rotate it.

**Comment by CrazyPants** [comment]
it rotates if you click the bottom half of the door

**Comment by HenryLoenwind** [comment]
ok, that's a limitation in the forge rotation code. it can only rotate blocks that have a rotated blockstate (it doesn't actually rotate but retrieves t eblockstate for "rotated").

However, I think we could add a special case for doors.
