### ISSUE TITLE
Having to break and replace EIO power conduits upon chunk reload

### ISSUE THREAD

**Issue by utoc** [SleepyTrousers/EnderIO#3542]
I'm using EnderIO conduits to power my Shield projector which I've been told is not using Tesla but still on rf.  When I leave my base and return, the shield projector has 0 rf 

#### What happens:

An rfTools block does not recieve any power until breaking and replacing any single point in the power conduit run from the capacitor to the block itself

#### What you expected to happen:

I expect not having to break the conduit.

#### Steps to reproduce:

1. Use shield projector with EnderIO's power conduits.  Machine powers itself fine
2. Leave chunk entirely causing it to unload and return
3. the shield block has no power and is not showing any increase in rf.  Break any one conduit piece in the length between the capacitor to the shield, replace it, and the block is then powered.

____

rfTools 1.10-5.06
mcJtyLib 1.10-1.9.8
EnderIO 1.10.2-3.0.1.73
EnderCore 1.10.2-0.4.1.41
FML 1.10.2-12.18.1.2011
on Minecraft 1.10.2

#### Your most recent log file where the issue was present: 

NA

**Comment by mindforger** [comment]
press and hold F3 + C to forcibly crash your game for a crashlog :)
did you use chickenchunks chunkloaders? replace them (with MFR or RailCaft Chunkloader), they are bogus ...

**Comment by utoc** [comment]
@mindforger There are no chunkloaders present on the server; MFR and RC are not available for MC 1.10.2 anyway.  Also, what reason would I want to forcibly crash the client?

**Comment by mindforger** [comment]
to get a list of installed mods, your minecraft version and other installed modifications like optifine and stuff, to have a better view on your game since you (not personally meant) may have forgotten to post a details that could be important

a crash log always helps to narrow down issues to sources that you will never expect :)

**Comment by CrazyPants** [comment]
If this is still an issue with the latest RF tools / eio please re-raise the issue. It seems to have been fixed.
