### ISSUE TITLE
config not syncing between clien/server

### ISSUE THREAD

**Issue by xannor** [SleepyTrousers/EnderIO#3543]
#### Issue Description:
It seems the server does not push its configuration to the client (at least in my version) and if the configs are different you start to get sync issues.  The problem I was having was my client must have had an older config because all of the XP costs listed in JEI and on the anvil its self were incorrect. (4 was listed instead of 10 for the basic items I attempted). 

#### What happens:
Adding a feature via the anvil will "Consume" the 4xp but drop the original items. Causing an update to the players experience will "restore" the missing XP (sync issue)

#### What you expected to happen:
The correct XP cost as expected by the server to be listed in GUI's.

#### Steps to reproduce:

1. have different XP cost in config on client and server
2. attempt to use with only the XP cost the client knows about.
3. attempt with the server expected amount and it works.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.74
- EnderCore: 0.4.1.41
- Minecraft: 1.10.2
- Forge: 12.18.1.2018

#### Your most recent log file where the issue was present: 

Nothing is logged.

This is not a major issue and can be corrected by manually syncing the config between the client and server, but it can catch you off guard when not expecting them to be different.

**Comment by AnrDaemon** [comment]
To my knowledge, EIO doesn't push config to client at all.

**Comment by MatthiasMann** [comment]
Also several config settings must be available before you are able to connect to the server - which makes the whole idea of config syncing useless anyway.
