### ISSUE TITLE
Duplication bug on 1.10.2

### ISSUE THREAD

**Issue by BubbaVB** [SleepyTrousers/EnderIO#3544]
#### Issue Description:
Duplication bug.

#### What happens:
When you right click on a fluid tank with an empty bucket it produces 64 buckets of whatever fluid was in the tank.

#### What you expected to happen:
To fill the single empty bucket.

#### Steps to reproduce:

1.Right click on a fluid tank that contains fluid (i.e. - lava or water)
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  1.10.2-3.0.1.74_beta
- EnderCore:  1.10.2-0.4.1.41-beta
- Minecraft: 1.10.2
- Forge:  12.18.1.2014

#### Your most recent log file where the issue was present: 

N/A

**Comment by HenryLoenwind** [comment]
see #3507

**Comment by BubbaVB** [comment]
Thanks I didn't see the other bug report.
