### ISSUE TITLE
[Suggestion] Add the 'show range' button to the Farming Station

### ISSUE THREAD

**Issue by warlordjones** [SleepyTrousers/EnderIO#3545]
I noticed the Vacuum Chest has a really neat 'show range' button, and I'd like to suggest it'd be cool to have this functionality on the Farming Station (should be transferable fairly easily?) - especially as there's currently no ingame way to tell the exact range of a Farming Station without trial and error.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
this is a bit on hold, waiting for a UI redesign of the farm. There just no space left for a button at the moment

**Comment by warlordjones** [comment]
Fair enough. I see what you mean about the space.
