### ISSUE TITLE
Lava/water duplication bug with EnderIO fluid tank

### ISSUE THREAD

**Issue by garlicinyoureye** [SleepyTrousers/EnderIO#3546]
#### Steps to reproduce:

1. Place lava/water source in front of EnderIO fluid tank that has lava or water in it
2. Click through fluid source to tank with empty bucket
3. Yields 1000 buckets of fluid. 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.73_beta
- EnderCore: EnderCore-1.10.2-0.4.1.41-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2016

**Comment by HenryLoenwind** [comment]
see #3507

**Comment by garlicinyoureye** [comment]
@HenryLoenwind My apologies, thank you for the prompt response and link to the culprit =)
