### ISSUE TITLE
Insulated redstone cables no longer have an API

### ISSUE THREAD

**Issue by josephcsible** [SleepyTrousers/EnderIO#3548]
In Minecraft 1.7.10, our insulated redstone cables supported MineFactory Reloaded's RedNet API. MineFactory Reloaded doesn't support modern versions of Minecraft, leaving us without an API for insulated redstone cables in these versions. I brought this up on IRC, and tterrag suggested that we switch to the API from Charset ([GitHub](https://github.com/Vazkii/Charset), [Curse](http://mods.curse.com/mc-mods/minecraft/246634-charset)).

**Comment by HyperHamster** [comment]
This issue has been holding up compatability with TIS-3D for over a year now. I would really love for Ender IO to be my one-stop shop for everything cable-related but without a proper bundled redstone API for TIS-3D to implement I need to install Project Red with all it's overhead just to do what Ender IO should already be able to do.

**Comment by josephcsible** [comment]
Charset [doesn't have bundled redstone](http://asie.pl/Projects/Minecraft/Mods/Charset/Rejects) anymore, so we're back at square 1 now, either having to pick another mod or do our own API.

**Comment by bookerthegeek** [comment]
Stupid idea, why not just integrate and update the old api from MFR?

**Comment by josephcsible** [comment]
I don't think its license allows that.

**Comment by josephcsible** [comment]
Why was this closed? Was one added?

**Comment by asiekierka** [comment]
@josephcsible It's coming back. Same API.

**Comment by asiekierka** [comment]
Sorry for posting twice, but here it is: https://minecraft.curseforge.com/projects/simplelogic-wires

The API has been marked as un-deprecated as of the matching release of CharsetLib.
