### ISSUE TITLE
Incompatibility with Spice of Life textures

### ISSUE THREAD

**Issue by OddWhirled** [SleepyTrousers/EnderIO#3549]
#### Issue Description:

"Lunchbox", "Lunchbag", and "Food Journal" items from the mod "The Spice of Life" have missing textures when the mod is used with EnderIO.
#### What happens:

The Lunchbox and Lunchbag items have normal textures until they are opened (right click). They then turn into a missing texture. The Food Journal item has a missing texture all the time.
#### What you expected to happen:

When Spice of Life is used alone or with other mods (tested with over 15) the textures show up normally when right-clicked.
#### Steps to reproduce:
1. Add Spice of Life v1.3.3 for MC 1.10.2 to mods
2. Add AppleCore v1.3.5 for MC 1.10.2 to mods 
3. Right-click Lunchbag or Lunchbox item, view Food Journal item

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 3.0.1.75
- EnderCore: 0.4.1.41
- Minecraft: 1.10.2
- Forge: 12.18.1.2011
#### Your most recent log file where the issue was present:

This issue does not show up in the log but here it is anyway. The log is from starting the game, loading a world, opening the Lunchbox item to see the missing texture, and then closing the world.

http://pastebin.com/93iX5un9

I have contacted the author of Spice of Life about this as well.

**Comment by CrazyPants** [comment]
I have confirmed this happens with EIO, but not with just EC.
I have no idea how this could happen. I have raised an issue with SoL to see if they have anything to go on
https://github.com/squeek502/SpiceOfLife/issues/100
