### ISSUE TITLE
[1.7.10] Dupe with Crafter and Tome of Alkahestry

### ISSUE THREAD

**Issue by KendirkRS** [SleepyTrousers/EnderIO#3551]
Using the Tome of Alkahestry with Ender IO crafter

#### What happens:
Book Makes double items like it is meant to But doesn't take any redstone charge from the Tome of Alkahestry

#### What you expected to happen:
Items double Tome of Alkahestry loses charges (in video you will see what i mean by charges

#### Steps to reproduce:

https://onedrive.live.com/redir.aspx?cid=75154b561b98607e&resid=75154B561B98607E!371838&parId=75154B561B98607E!371837&authkey=!AGlmo7Cc2527zLU&ithint=video%2cmp4

1.need power source, crafter, chest, Tome of Alkahestry, redstone and items that wanted to be dupe (limited to compatibility with the tome)
2. set power crafter and chest together 
3.set the crafter to push pull into the chest set the tome and diamond recipe in crafter as per video put tome and diamond into chest and it will work itself from there 
____

- EnderIO: 2.3.0.425
- EnderCore: 0.2.0.34
- Minecraft: 1.7.10
- Forge:

**Comment by HenryLoenwind** [comment]
That's Reliquary's fault. We are properly asking the tome with getContainerItem() what should happen to it when crafting, but it just returns the unchanged tome.
