### ISSUE TITLE
Farming Station not planting wheat

### ISSUE THREAD

**Issue by richardmv** [SleepyTrousers/EnderIO#3552]
Farming stations are not replanting wheat seeds, despite having plenty available in inventory. The station will continue harvesting normally, but over time the number of empty blocks of tilled soil will increase. I also have stations with carrots and potatoes; these seem to be working fine (seeds are planted in all plots).

I have a number of mods that I am using along with EnderIO. Originally I suspected that the arcane lamp from Thaumcraft was placing light sources over the tilled soil, which was causing the farming station to treat the area as not being available for planting, but since this isn't affecting carrots or potatoes, I'm doubting that this is the issue.

My farming stations all use diamond hoes with unbreaking III, Double-Layer capacitors, and have most of the seed slots locked (except the first slot, which is always full of seeds). Wheat and excess seeds are constantly being piped out to another inventory. The stations are placed over a water source block in the center of a 9x9 area of tilled soil, on the same level as the wheat (one block above the dirt around it).

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.427
- EnderCore: 0.2.0.36
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

**Comment by bookerthegeek** [comment]
Just for clarification, you are planting on vanilla farmland?

**Comment by richardmv** [comment]
Yeah. I set down a 9x9 square of dirt (with the center removed for a water source), tilled it with Thaumcraft's Hoe of Growth, placed a stone brick block on one of the dirt blocks next to the water source (cursing my lack of foresight), placed a farm black against the stone brick, mined the stone brick, and re-tilled the dirt where the brick had been. Then I provided it with power and connected an item conduit to draw the wheat and excess seeds.

all of my farm plots were set up in a similar fashion (though with better planning :stuck_out_tongue:). The plots for carrots and potatoes work fine, but over time the wheat fields are becoming barren, and the farm block isn't replanting the empty plots. I have multiple wheat plots, and all of them are having this same issue. The land that isn't being replanted seems to change every time, so I don't think it's an issue with the specific dirt blocks themselves.

Also, I'd post a log, but this is on a server (I run this server, so I have access to the log) but there's no crash involved, so I can't imagine a log would reveal anything.

**Comment by JaSpr** [comment]
Why was this closed?  I'm having the same issue with both plain vanilla farmland and fertilized dirt.

SkyFactory 3 (3.0.8)
Forge: 12.18.3.2254
EnderIO: 1.10.2-3.1.173
EnderCore: 1.10.2-0.4.1.65-beta

**Comment by HenryLoenwind** [comment]
It was closed because there's nobody here who even remotely has the time to go through all open 1.7.10-tickets and do anything about it. We're barely keeping up with 1.10.2...

**Comment by JaSpr** [comment]
Ah ok.  Should I open a new ticket for 1.10.2, as that is where my issue is presenting itself.

**Comment by bookerthegeek** [comment]
@JaSpr If this issue is reproducing itself on 1.10 then yes. Otherwise no.
