### ISSUE TITLE
[1.7.10] Sag mill output chance always high [Question]

### ISSUE THREAD

**Issue by Skillotic0703** [SleepyTrousers/EnderIO#3553]
#### Issue Description:

The sag mill output chance is not accurate. 
#### What happens:

I put 64 stacks of iron ore in a sag mill (I checked several times that it was 64 stacks before doing it).
I obtained 13728 pulverized iron, 726 pulverized tin, 1391 pulverized ferrous metal and 2128 cobblestone. I made this with dark steel balls. There were dark steel balls all along.
#### What you expected to happen:

The chance of obtaining Pulverized Iron as output was (100%) x (150%)= 1.5
64 x 64 x 2 x 1.5 = 12288.
The chance of obtaining Pulverized Ferrous Metal was 4096 x 10% = 409,6
The chance of obtaining Pulverized Tin was (5%)x 4096 = 204,8
I just wanted to say that I always obtain more than I should.
#### Steps to reproduce:

1.Put down a sag mill
2.Put ores in it
3.Enjoy your unexpected bonus ores
...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.7.10-2.3.0.428_beta
- EnderCore: 1.7.10-0.2.0.36_beta
- Minecraft: 1.7.10
- Forge: 10.13.1614
#### Your most recent log file where the issue was present:

[pastebin/gist/etc link here]

**Comment by AnrDaemon** [comment]
You have at least one error in your calculation.
`The chance of obtaining Pulverized Ferrous Metal was 4096 x 10% = 409,6`
You forgot to apply 1.5 ball multiplier.

**Comment by Skillotic0703** [comment]
My bad, but that doesn't change anything

**Comment by AnrDaemon** [comment]
That actually matches the results you observe.
For every main output you get a chance for each extra output.
So, you get up to 3 main outputs, and thus a lot of extras.

**Comment by HenryLoenwind** [comment]
And you forgot to apply the 200% bonus on chance based outputs.

So iron dust is 2 dusts * 150%(amount) * (100*2)%(chance) with chance capping at 100% obviously.
Tin dust is: 1 dust * 150%(amount) * (5*2)%(chance),
Nickel dust is: 1 dust * 150%(amount) * (10*2)%(chance),
Cobble is: 1 item * 150%(amount) * (15*2)%(chance),

**Comment by AnrDaemon** [comment]
"Usually" =/= "necessarily". See: Silicon from Sand recipe.

**Comment by Skillotic0703** [comment]
Thank you for your explanations. However I still get some (Just a little bit) unexpected bonus powders.

**Comment by codewarrior0** [comment]
> For every main output you get a chance for each extra output.

I didn't know this! I find it a bit surprising. Does this mean that pulverizing Redstone Ore (main output: 8x Redstone, secondary: 10% Redstone Dust) gives you eight 10% chances to get the bonus dust, and twelve 20% chances when using dark steel balls?

**Comment by HenryLoenwind** [comment]
codewarrior0, no it just means you get the same chances for each output. See my calculation above. Or for your example:

    No balls:
    First output: 8 dusts * 100%(amount) * (100*1)%(chance)
    Second output: 1 dust * 100%(amount) * (10*1)%(chance)
    
    With dark balls:
    First output: 8 dusts * 150%(amount) * (100*2)%(chance) with chance capping at 100% obviously
    Second output: 1 dust * 150%(amount) * (10*2)%(chance)

**Comment by codewarrior0** [comment]
Ah. So the "Main Output" modifier really adds to *all* of the outputs, not just the first one, or not just the ones that have 100% chance. And the "Bonus Output" modifier is applied on top of the "Main Output", except that it can't bring the chance above 100%, so it doesn't apply to any of the guaranteed outputs.
