### ISSUE TITLE
Fluid tank duplicates buckets

### ISSUE THREAD

**Issue by bizarremonkey** [SleepyTrousers/EnderIO#3554]
#### Issue Description:
Fluid tank duplicates buckets

#### What happens:
Fluid tank is connected to reservoir by fluid conduit. Place empty bucket in top left slot in fluid tank and the bottom right slot fills with a stack of 1000 water buckets.

#### What you expected to happen:
One water bucket is filled.

#### Steps to reproduce:

1. Connect fluid tank to reservoir with fluid conduit.
2. Place empty bucket in fluid tank slot.
3. Profit...
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.75_beta
- EnderCore: 1.10.2-0.4.1.41-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2011

#### Your most recent log file where the issue was present: 

http://paste.ee/p/lLaDC

**Comment by HenryLoenwind** [comment]
see #3507
