### ISSUE TITLE
[1.10.2] Wireless Charger Doesn't Charge Off-Hand Item

### ISSUE THREAD

**Issue by oitsjustjose** [SleepyTrousers/EnderIO#3555]
#### Issue Description:
Very self-explanatory: off-hand items are not charged by the wireless charger (most notably the staff of traveling). I haven't tested but I'd be surprised if this _wasn't_ a bug on the 1.9.4 builds too, but I wouldn't make too much effort in back-porting if I were you - I don't think anyone else has noticed this bug since I couldn't find a pre-existing report.

#### What happens:
Off-Hand items are not charged

#### What you expected to happen:
Off-hand items to charge

#### Steps to reproduce:

1. Prepare Wireless Charger with any source of RF
2. Hold an RF storing item in the off-hand which is not fully charged
3. Lie down and cry

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.75_beta
- EnderCore: 1.10.2-0.4.1.41-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2018

#### Your most recent log file where the issue was present: 

**N/A**

**Comment by HenryLoenwind** [comment]
will be in next build
