### ISSUE TITLE
[1.10.2] Crash on entering world

### ISSUE THREAD

**Issue by Keridos** [SleepyTrousers/EnderIO#3556]
#### What happens:

Crash on entering single player world

#### Steps to reproduce:

1. Join singleplayer world.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.75_beta
- EnderCore: 0.4.1.41
- Minecraft: 1.10.2
- Forge: 12.18.1.2011

#### Your most recent log file where the issue was present: 
https://paste.ee/p/Zbz5O

**Comment by MatthiasMann** [comment]
This doesn't look like an EnderIO bug - something is wrong with the RF API in your installation.

**Comment by Keridos** [comment]
Means one mod does have a bugged RF API installed?

**Comment by way2muchnoise** [comment]
You might want to get rid of that 1.7.10 forestry (`forestry_1.7.10-4.2.14.62.jar`)

**Comment by Keridos** [comment]
I had extrautilities 2 times installed, too. Missed that in the log. Downloaded the wrong mod versions from curseforge sometimes apparently. Seems to work now, thanks for the help.
