### ISSUE TITLE
[1.7.10] Nutrient Distillation

### ISSUE THREAD

**Issue by CristinoValdigem** [SleepyTrousers/EnderIO#3557]
Hi, 
i was using a long time EnderIO-2.3.0.422_beta.jar  and  EnderCore-0.2.0.31_beta.jar.... Ok to here
i gonna update the both mods to latest version to minecraft 1.7.10 and when gonna check my mob farm he is full mob inside when i gonna check Vat, he's don't accept and don't appear on NEI the recipe to make Nutrient Distillation.... Why that liquid removed ?
Anyone can explain about it ? For solve my problem i recover my the oldest version of Ender Io and EnderCore

**Comment by HenryLoenwind** [comment]
You're not on latest, you on 424 which has a broken recipe

**Comment by CristinoValdigem** [comment]
I've Downloaded the Latest Version of Ender Io and Ender Core...
I Download the Ender Io - 2.3.0.428 and Ender Core - 0.2.0.36

**Comment by CristinoValdigem** [comment]
And When i checked my map the Vat stop producting Nutrient Distillation.... and the recipe of Nutrient Distillation is configured on Vat_User Config and in the game the recipe doesn't Work

**Comment by CristinoValdigem** [comment]
I Print the Picture from game and post here

**Comment by mindforger** [comment]
you can also hold F3 + C for 6seconds and force a crash to create a logfile that says more than thousands words ... well i t may itself say about 1000 words literally XD
also is this singleplayer or multiplayer? If MP then add a short log from the server (clear the log folder, start the server, login, do your not working work and shut it down after that)

**Comment by CristinoValdigem** [comment]
See that >
[VatRecipes_Core.txt](https://github.com/SleepyTrousers/EnderIO/files/389962/VatRecipes_Core.txt)

On VatRecipe_Core have the recipe to produce Nutrient Distillation but in the game...

![2016-07-29 8](https://cloud.githubusercontent.com/assets/16420781/17239347/c6023478-5539-11e6-8541-3333b2cd3c14.jpg)
![2016-07-29 7](https://cloud.githubusercontent.com/assets/16420781/17239356/d69837ba-5539-11e6-8b93-b68906a6d6d0.jpg)
![2016-07-29 9](https://cloud.githubusercontent.com/assets/16420781/17239360/dad5efca-5539-11e6-9738-ebf6e6a8b789.jpg)
![2016-07-29 10](https://cloud.githubusercontent.com/assets/16420781/17239363/e60b46ba-5539-11e6-9bd4-5f9d67f8276e.jpg)

**Comment by CristinoValdigem** [comment]
In Ender Io 2.3.0.422 and Ender Core 0.2.0.32

![2016-07-29 2](https://cloud.githubusercontent.com/assets/16420781/17239440/6ccdc588-553a-11e6-848a-1915846c748d.png)
![2016-07-29 3](https://cloud.githubusercontent.com/assets/16420781/17239441/6cdfca44-553a-11e6-9b3d-ea7a7e08b556.png)
![2016-07-29 5](https://cloud.githubusercontent.com/assets/16420781/17239439/6cb2a3e8-553a-11e6-94ce-de6806e6cf8b.png)
![2016-07-29 1](https://cloud.githubusercontent.com/assets/16420781/17239455/92f34350-553a-11e6-873a-9cc62b02ed8d.png)

**Comment by CristinoValdigem** [comment]
In Ender IO - 2.3.0.422 and Ender Core - 0.2.0.32

![2016-07-29 1](https://cloud.githubusercontent.com/assets/16420781/17239494/f97a6b62-553a-11e6-96e5-2841c69ac64c.png)
![2016-07-29 2](https://cloud.githubusercontent.com/assets/16420781/17239495/f97aef42-553a-11e6-8ac9-ed8841b5e0e7.png)
![2016-07-29 3](https://cloud.githubusercontent.com/assets/16420781/17239496/f97e18a2-553a-11e6-9edd-f03276c6c1ea.png)
![2016-07-29 5](https://cloud.githubusercontent.com/assets/16420781/17239500/ff079b40-553a-11e6-88f1-43b3c3948293.jpg)

**Comment by CristinoValdigem** [comment]
Any question or information you need... Tell me

**Comment by CristinoValdigem** [comment]
Thanksssssssss a Lot i've Downloaded here the new version (2.3.0.429) from 1.7.10 and The recipe of Nutrient Distillation Work :+1:
