### ISSUE TITLE
Alloy Smelter makes Electrical Advantage Solder out of EnderIO Tin Powder

### ISSUE THREAD

**Issue by MokahTGS** [SleepyTrousers/EnderIO#3558]
#### Issue Description:
Alloy Smelter makes Electrical Advantage Solder out of EnderIO Tin Powder

#### What happens:
Sending tin powder into the alloy smeltery set on furnace only or all smelt yields solder from the mod Electrical Advantage even though the recipe in JEI says otherwise. 

#### What you expected to happen:
You should make Tin ingots

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.77 beta
- EnderCore: 0.4.1.43 beta
- Minecraft: 1.10.2
- Forge: 2038

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by AnrDaemon** [comment]
Is there any other recipes in JEI that involve the same ingredients?

**Comment by HenryLoenwind** [comment]
It is using the ore dictionary here to give you only one type of tin for all kinds of tin powders, dusts and ores it can smelt.

**Comment by HenryLoenwind** [comment]
Should no longer happen randomly but only if there's a ordict preference for tin configured
