### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by MrAmericanMike** [SleepyTrousers/EnderIO#3560]
#### Issue Description:
Missing translations:

#### What happens:
The log reports missing translations when launching the mod.

#### What you expected to happen:
Clean launch.

#### Steps to reproduce:

1. Just launch any instance of the mod.
2. Watch at the log.
...

#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.77_beta
- EnderCore: EnderCore-1.10.2-0.4.1.43-beta
- Minecraft: 1.10.2
- Forge: Any

#### Your most recent log file where the issue was present: 

http://pastebin.com/uBULUb4H

**Comment by HenryLoenwind** [comment]
unfinished software ins unfinished

**Comment by MrAmericanMike** [comment]
Got you ;)

**Comment by HenryLoenwind** [comment]
I'll probably just disable that warning. those keys don't really need a translation.
