### ISSUE TITLE
Cape not hidden when wearing Dark Plate with Elytra upgrade

### ISSUE THREAD

**Issue by Meow-J** [SleepyTrousers/EnderIO#3561]
#### Issue Description:

When a cape is enabled and you are wearing the Dark Plate with Elytra upgrade, the cape is still rendered, resulting in the presence of both the elytra and the cape.

#### What happens:

The cape is not hidden:

![2016-07-31_02 58 22](https://cloud.githubusercontent.com/assets/5229241/17272604/57d84402-56cd-11e6-8e43-51fc4538596a.png)

#### What you expected to happen:

The cape is hidden just like when you are wearing an Elytra in vanilla Minecraft

![2016-07-31_03 26 04](https://cloud.githubusercontent.com/assets/5229241/17272652/d071c928-56ce-11e6-9580-48800b06e351.png)

#### Steps to reproduce:

1. Have a cape enabled
2. Grab the third Dark Plate in EnderIO creative tab and wear it
3. Exit the inventory GUI, press F5 to view the player in third-person

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.77
- EnderCore: 0.4.1.43
- Minecraft: 1.9/1.10
- Forge: 12.18.1.2043

#### Your most recent log file where the issue was present: 

don't think this is necessary

**Comment by HenryLoenwind** [comment]
Known issue, that part isn't yet implemented. Partly because I have no way to test the code I have to write...

**Comment by HenryLoenwind** [comment]
This should work in the next build. You you please report back here if it does? I have no way of testing capes... Thx.

**Comment by Meow-J** [comment]
tterrag's CI doesn't seem to be working right now. The latest build was built on Jul 29. http://ci.tterrag.com/job/EnderIO-1.10/

**Comment by Meow-J** [comment]
Yep, it's now fixed
