### ISSUE TITLE
[1.10.2] [Updated Report] Weather Obelisk Can't Connect to Fluid Conduits 

### ISSUE THREAD

**Issue by praetoras** [SleepyTrousers/EnderIO#3562]
#### Issue Description:

Fluid conduits will not connect to weather obelisk on any side.

#### What happens:

When attempting to use any of the three fluid conduits to feed necessary fuel fluids to the weather obelisk, it is impossible to connect the obelisk to the conduits, even with the Yeta Wrench to force it.

#### What you expected to happen:

I expect the conduits to connect to the obelisk, either automatically or by using the wrench.

#### Steps to reproduce:

1. Place obelisk and hook up to RF power. Insert rocket.
2. Place tank with choice of fuel (I used Liquid Sunshine) 
3. Place fluid conduits from tank up to obelisk.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.81_beta
- EnderCore: EnderCore-1.10.2-0.4.1.46-beta
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.1.2043-universal

#### Your most recent log file where the issue was present: 

No log file present. The server and client gave no errors. However, I do have an image.

![obeliskbug2](https://cloud.githubusercontent.com/assets/17558082/17422654/93e97ce0-5a79-11e6-8c42-45770b0eb933.png)

**Comment by Keridos** [comment]
You should probably do not use latest as decribing the version, as it is even stated in the text you completely erased when creating your bug report.

**Comment by praetoras** [comment]
Ah, you're right - I'll go ahead and update this report shortly.

**Comment by praetoras** [comment]
Issue has been updated with images, all versions, and... well, honestly, there isn't a lot of detail to include. You just stick a conduit next to the obelisk and it doesn't connect.

**Comment by HenryLoenwind** [comment]
fixed in next build
