### ISSUE TITLE
[1.7.10] Combustion Generator won't put out power

### ISSUE THREAD

**Issue by JFMillerUSA** [SleepyTrousers/EnderIO#3563]
Trying to store power in a capacitor from a combustion generator full of water and rocket fuel, it's power buffer is full and says generating 0RF. I have Enhanced Energy conduits connecting them both together.

EnderIO-1.7.10-2.3.0.428_beta and EnderIO-1.7.10-2.2.8.381
EnderCore-1.7.10-0.2.0.36_beta
Minecraft: 1.7.10
Forge 10.13.4.1614

**Comment by HenryLoenwind** [comment]
did you set the side opposite the conduit to "disabled"? If so, set it to none.

**Comment by AnrDaemon** [comment]
:D Should check.

**Comment by AnrDaemon** [comment]
Seems to work proper, but it takes a few moments to discover the sink.
Mine was ~20 blocks away behind an air gap and a blocked creative capacitor. Once I've found and fixed the gap, the energy gone through in ike 20 seconds.

**Comment by JFMillerUSA** [comment]
I've switch back to recommended Forge 10.13.4.1558, seems to work now. On a side note having problems with Enhanced Energy Conduits.
![2016-07-31_13 55 02](https://cloud.githubusercontent.com/assets/9157611/17278970/c1800ef4-5726-11e6-8304-8326d762fe66.png)
![2016-07-31_13 54 57](https://cloud.githubusercontent.com/assets/9157611/17278968/c17c741a-5726-11e6-97d1-d548f42cd9c8.png)
![2016-07-31_13 54 51](https://cloud.githubusercontent.com/assets/9157611/17278969/c17eb9a0-5726-11e6-93ba-0a10b919ae2e.png)

**Comment by sandalle** [comment]
I saw a similar problem on mine when I had my Rocket Fuel + Water coming in (whitelisted Ender Fluid Conduit set to "Insert" only) on the same interface as my power going out (Ender Energy Conduit set to "Extract" only), and the Combustion Engine interface was set to "Pull", which wouldn't let the power back out. Switching to "None" allows both the liquids to be inserted and the power to be extracted. There is no "Push/Pull" option, only "None", "Pull", "Disabled".

Pertinent Mods:
* Minecraft 1.10.2
* Forge Mod Loader (FML) 1.10.2-12.18.3.2185
* EnderCore 1.10.2-0.4.1.65-beta
* Ender IO 1.10.2-3.1.156
