### ISSUE TITLE
Localization Issues with Coordinate Selector and Creative Capacitor Bank

### ISSUE THREAD

**Issue by IBeCrayZ** [SleepyTrousers/EnderIO#3565]
- Coordinate Selector is called item.null.name and has no "shift" info (I assume localization)
- Creative capacitor bank is called tile.blockCapBank.none.name and has no texture when looking at it using Waila. (I assume a similar issue)

**Comment by HenryLoenwind** [comment]
Coordinate Selector is a useless item as the TelePad is disabled for reworking.

CapBanks is a bug in WAILA, try to look at a number of differently oriented vanilla anvils to see it there, too.
