### ISSUE TITLE
[1.7.10] Advanced Item Filter not working

### ISSUE THREAD

**Issue by JFMillerUSA** [SleepyTrousers/EnderIO#3567]
Here's my setup, a Killer Joe with a Dark Steel Sword and a Item Conduit coming out to a chest. In the Conduit Connector it's going Input/Extract with Advanced Item Filter in Extract mode and Fuzzy match for 75% damage. Problem is keeps extracting sword with 1506/1561 damage.

![2016-07-31_14 05 30](https://cloud.githubusercontent.com/assets/9157611/17279007/ecfd66fc-5727-11e6-8f80-88d613185b17.png)

![2016-07-31_14 05 49](https://cloud.githubusercontent.com/assets/9157611/17279006/ecf2911e-5727-11e6-8f5b-6301192406db.png)

![2016-07-31_14 05 58](https://cloud.githubusercontent.com/assets/9157611/17279008/ecff7898-5727-11e6-89b6-1df509ce40af.png)

EnderIO-1.7.10-2.3.0.428_beta
EnderCore-1.7.10-0.2.0.36_beta
Minecraft: 1.7.10
Forge 10.13.4.1558

**Comment by HenryLoenwind** [comment]
You got your filter backwards. It is set to pull out items with >=75% durability. You probably want to set it to NOT pull out items with >=75% (or 25%) durability.

**Comment by Simon-Bitdiddle** [comment]
Can you adjust the text to state "Fuzzy Match for greater than N% Damage" and add options for "Fuzzy Match for less than N% Damage"?
