### ISSUE TITLE
1.10.2 cropConfig.json being completely ignored by farming station

### ISSUE THREAD

**Issue by MysticAura** [SleepyTrousers/EnderIO#3568]
#### Issue Description:
Farming station refuses to right click any crops. Even when I test with just the default cropConfig.json. file it smacks wheat like there's no right click option.

#### What happens:
Crop not being right-click harvested

#### What you expected to happen:
Crop being right-click harvested

#### Steps to reproduce:

1. Fill out cropConfig.json (or even let it use defaults)
2. Set up farming station
3. Crops grow and get smacked down instead of right-click harvested
...

____
#### Affected Versions (Do *not* use "latest"):

MC Version: 
Forge Version: 2043
Core Mod Version: 
Mod Version: 

- EnderIO: 1.10.2-3.0.1.77-beta
- EnderCore: 1.10.2-0.4.1.44-beta
- Minecraft: 1.10.2
- Forge: 2043

#### Your most recent log file where the issue was present: 

Doesn't seem relevant in this case aside from verifying if the RightClickCropHandler is registering, and yes it is.  If you need the fml client log I can supply it, but that is the only log file possible to give, as it isn't a crash and gives no errors.

**Comment by MysticAura** [comment]
Hopefully at some point the farming station can be made aware of the right click crops added to endercore's crop config, but as this isn't a bug like I assumed it must be, I'm closing the issue.

**Comment by HenryLoenwind** [comment]
Right-click harvesting would be very useless for the farming station. Stuff would just drop on the ground...
