### ISSUE TITLE
[1.10.2] Crash on Server

### ISSUE THREAD

**Issue by DoughnutDev** [SleepyTrousers/EnderIO#3569]
Not sure which mod dev it is because it looks like IC2 (is not even in the pack), EnderIO and Mekanism is part of the issue. Here is the log http://hastebin.com/wuxeqivegu.coffee

EnderIO: 3.0.1.77
Mekanism: 9.1.0.288

**Comment by HenryLoenwind** [comment]
Looks like a bug in Mekanism.
