### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by origamerpro** [SleepyTrousers/EnderIO#3570]
#### What happens:

crashed server
#### What you expected to happen:

start server
#### Steps to reproduce:

1.stop server
2.Upgrade Academycraft mod to last version
3.Upgrade InventoryPets mod to last version
4. Start server
...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.7.10-2.3.0.427_beta
- EnderCore: 1.7.10-0.2.0.36_beta
- Minecraft: 1.7.10
- Forge:1614
  #### Your most recent log file where the issue was present: 

http://pastebin.com/7n36PjpW

**Comment by HenryLoenwind** [comment]
"An unsupported base software is installed: 'thermos, cauldron, craftbukkit, mcpc, kcauldron'. This is NOT supported."

I'd guess that's the problem

**Comment by origamerpro** [comment]
2 weeks to start and now suddenly a crash.

**Comment by HenryLoenwind** [comment]
Ok, let's see. Ender O worked before on that server. You added two mods, 

The class reference that is failing is stripped out by Forge unless a mod with the ID "Baubles|API" is loaded, too.

So I'd check those two mods (look inside the jar) and see if one of them ships with the Baubles API and if it is complete.
