### ISSUE TITLE
[Suggestion] Invisible Facades

### ISSUE THREAD

**Issue by 016Nojr** [SleepyTrousers/EnderIO#3572]
Implement a way to make invisible facades? Kind of like the transparent facades, but completely invisible.

**Comment by AnrDaemon** [comment]
Paint them with an invisible block.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by 016Nojr** [comment]
Ok
