### ISSUE TITLE
[1.10.2] Zombie Generator unbreakable, breaking attempt causes client crash.

### ISSUE THREAD

**Issue by Yandols** [SleepyTrousers/EnderIO#3573]
#### Issue Description & What happens:
The Zombie Generator can no longer be broken with a pickaxe or by hand, doing so will cause Minecraft to crash. Re-tested and persists after 3 tries. Currently the only way to reobtain a placed Zombie Generator is to shift-right-click it with a yeta wrench _(or any bc compatible wrench)_.

If I recall correctly, problem did not occur back in EnderIO-1.10.2-3.0.1.70_beta

#### Steps to reproduce:

1. Place Zombie Generator down.
2. Break Zombie Generator using a tinkers pickaxe or hand.
3. Minecraft freezes for about a minute.
4. Minecraft crashes.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.77_beta
- EnderCore: EnderCore-1.10.2-0.4.1.45-beta
- Minecraft: 1.10.2
- Forge: forge-12.18.1.2043

#### Your most recent log file where the issue was present: 

http://pastebin.com/b3HNMCNv

**Comment by HenryLoenwind** [comment]
That's a problem with Forge. The fix is here: https://github.com/MinecraftForge/MinecraftForge/pull/3132
