### ISSUE TITLE
[1.10.2]Key "R" is not work if enderIO installed

### ISSUE THREAD

**Issue by RarogCmex** [SleepyTrousers/EnderIO#3574]
#### Issue Description:

Key "R" (key 19) is not work if enderIO installed. Any keybinding for 19 key aren't work

#### What happens:
Key "R" can't work

#### What you expected to happen:
Install EnderIO

#### Steps to reproduce:
For example
1.Install Xray mod http://minecraftxray.net/downloads.html
2.Bind xray on "R"
3.R not work
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO EnderIO-1.10.2-3.0.1.77_beta
#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
I can't get it.

Sorry for my english

**Comment by RarogCmex** [comment]
EnderCore-1.10.2-0.4.1.45-beta
Minecraft:1.10.2
1.10.2-LiteLoader1.10.2-1.10.2-forge1.10.2-12.18.1.2044

**Comment by HenryLoenwind** [comment]
will be fixed in next build (sorry not today's build, I was too late for that one)
