### ISSUE TITLE
[1.10.2] Dark Plate with Elytra (Flight and Toggle) 

### ISSUE THREAD

**Issue by SteveKnowless** [SleepyTrousers/EnderIO#3576]
#### Issue Description:
Player is unable to Fly

#### What happens:
Player is Unable to Fly. Player Crouches and moves forward. Flight toggle only appears to Enable unless the button is held down. When toggle button is held down the screen will toggle between Enabled and Disabled rapidly.

#### What you expected to happen:
Player to Fly (Similar to Creative Mode Flight)

#### Steps to reproduce:

1. Craft or Give Dark Plate with Elytra Upgrade
2. Hit G Button "Glider/Elytra Toggle Default"
3. Elytra Active Shows enabled
4. Try to Fly
5. Hit G Button "Glider/Elytra Toggle Default" Again
6. Elytra Active Shows enabled

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.80
- EnderCore: 0.4.1.46
- Minecraft: 1.10.2
- Forge: 12.18.1.2045

#### Your most recent log file where the issue was present: 
No Errors in log file

**Comment by HenryLoenwind** [comment]
The Elytra upgrade works the same as the normal Elytra. The keybinding is a backup to either stop the Elytra if the ground detection fails or to enable it for people who cannot hit the fall-jump right (like me).

**Comment by SteveKnowless** [comment]
Thank you for that Information. I thought since the text read "Enables flying" that it would be similar to flying in creative. Thank you for clarifying.

**Comment by HenryLoenwind** [comment]
Ok, I'll think about chabging that text. Thx for pointing that out

**Comment by meepiable** [comment]
### _HELLO!_
