### ISSUE TITLE
2 conduit-related crashes

### ISSUE THREAD

**Issue by the-creamster** [SleepyTrousers/EnderIO#3578]
I was in the process of finding/reporting bugs for Tech Reborn(TR) so as to properly test its multiblock machines i setup some conduits to auto-extract the results and got 2 crashes(the second one i'm not quite sure about but it occurs when i'm placing/editing conduits/conduit connections). I've also noticed an unusual side effect of when editing a conduit connection it'll attempt to place the place-able block held in your hand and does so most of the time.

I've tried backdating 3-5 versions from the latest to beta 44(endercore) & beta 74(enderio) to get no success with trying to eliminate the crashes by finding a non-crashing version.

- EnderIO: beta 74+
- EnderCore: beta 44+
- Minecraft: 1.10.2
- Forge: build 2039

https://gist.github.com/the-creamster/f0e32e5b86c5b2045bea05ed964674d1
https://gist.github.com/the-creamster/cbd5ce95cebe3dbaf462c7a170182a14

**Comment by HenryLoenwind** [comment]
In the first one techreborn code is crashing, did you make syre it's not that code that's faulty first?

The second one looks like the single player integrated server stopped while the client wanted to connect.

**Comment by the-creamster** [comment]
The first crash i mentioned to the TR devs in a issue i had active and they said it was EIO. As for the second crash i got it after being in a world for sometime and when i attempt to rejoin a world which crashed me because of the first crash.

**Comment by HenryLoenwind** [comment]
found it, commented there https://github.com/TechReborn/TechReborn/issues/713

**Comment by HenryLoenwind** [comment]
Status update:

Crash 1: Still waiting for TechReborn

Crash 2: As I understand that is the client crashing after the integrated server crashed at a bad time for the client.
