### ISSUE TITLE
lava bucket glitch with tank

### ISSUE THREAD

**Issue by knoahj** [SleepyTrousers/EnderIO#3579]
Was playing FTB unstable 1.10.2 on curse launcher when i clicked on a tank with a empty bucket It gave me a stack of 1000 lava buckets.

1.Make tinkers construct smeltery
2.place two full lava tanks underneath seared tank
3.set bottom tank to push up to middle tank
4.set middle tank to push up to seared tank
5.click with 1 empty bucket

**Comment by HenryLoenwind** [comment]
See #3507
