### ISSUE TITLE
RFTools Item Filter Machine pull items not working

### ISSUE THREAD

**Issue by Keridos** [SleepyTrousers/EnderIO#3580]
#### What happens:
You cannot pull items via machine auto pull from an item filter from RFTools that is set to allow access to that item on a side. Might be because of either missing ISidedInventory support or capability support in one of both mods, gonna post an issue on RFTools if needed as well.

#### What you expected to happen:
Auto pull should work from the filters. Item Conduits work though.

#### Steps to reproduce:

1. Configure RFtools item filter and put items in it
2. place EnderIO machine next to it.
3. try to pull items via the configuration GUI in EnderIO

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.81_beta
- EnderCore: 1.10.2-0.4.1.46-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2022

**Comment by HenryLoenwind** [comment]
Could you please test if it works if you enable access to the side opposite the machine? If that works, I know what's wrong.

**Comment by Keridos** [comment]
Does not work on when I enable the opposite side.

**Comment by HenryLoenwind** [comment]
Not good. That means I have to go in with a debugger. Thx.

**Comment by Keridos** [comment]
This also happens with other RFTools machines like the modular storage.

**Comment by CrazyPants** [comment]
We didn't support capabilities on push / pull
