### ISSUE TITLE
Suggestion: Make Vanilla Item Frames Paintable

### ISSUE THREAD

**Issue by psychofad** [SleepyTrousers/EnderIO#3581]
As the title suggests, I would like to be able to paint vanilla item frames, specifically to paint them invisible so that it appears the item is just placed on the wall instead of in a frame.  Is this possible?

**Comment by HenryLoenwind** [comment]
There are plenty of mods out there that provide colored and invisible item frames. And as item frames are not blocks but mobs, it doesn't really fit Ender IO.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by psychofad** [comment]
If you would be so kind as to direct me to the mod that adds invisible item frames for minecraft 1.10.2 I would be very appreciative!

**Comment by VT-14** [comment]
I think I saw one from Tinker's Construct on one of Direwolf20's early 1.10.2 Forgecraft videos.
