### ISSUE TITLE
[suggestion] remote awareness / request filter

### ISSUE THREAD

**Issue by istasi** [SleepyTrousers/EnderIO#3582]
Love remote awareness!,posible to have a export based on remote awareness ?

eg. let it be a upgrade that goes in input slot on conduit called 'request filter' or something, then let it take items out of remote awareness enabled boxes

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
