### ISSUE TITLE
Ender IO block is not working

### ISSUE THREAD

**Issue by mikefun10** [SleepyTrousers/EnderIO#3583]
#### Issue Description:

The ender IO block can be remoted in to but does not allow inventories to be opened
#### What happens:

The ender IO block can be remoted in to by using the travel anchor or staff of travelling and it renders the area around it, but inventories like chests or other Ender IO machines don't work. It goes to open the inventory but then closes it instantly. 
Unless within a 7 block radius blocks from the inventory block.

But it does open the Gui for other travel anchors or Ender IO's(the block named Ender IO).
#### What you expected to happen:

Be able to use the chests inventory from a distance.
#### Steps to reproduce:
1. Place Ender IO(Block) within 3 blocks of a vanilla chest
2. Use travel anchor or staff from any distance that's greater then 7 from the inventory block
3. Use the ender IO and have the inventory gui close instantly 

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.10.2-3.0.1.81_beta
- EnderCore: 1.10.2-0.4.1.46-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2011
#### Your most recent log file where the issue was present:

http://paste.ee/p/yugrY
#### Notes:

This is my first time ever reporting a bug on git hub and in general, feel free to ask for any more information you'd need or want

**Comment by HenryLoenwind** [comment]
The functionality to keep inventories open that want to close has been removed from Forge.

**Comment by mikefun10** [comment]
Ohhhh, didn't know that. 

Thank you for replying :) 

and I hope it gets re added one day

**Comment by tterrag1098** [comment]
How exactly was it removed?

**Comment by HenryLoenwind** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/d1f4d71d93890a33362c4630cb724bcc75fcb93b

**Comment by CrazyPants** [comment]
This is on hold until we (or someone else) submits a PR to forge to re-implement this functionality
