### ISSUE TITLE
Telepad Block

### ISSUE THREAD

**Issue by Conmyster** [SleepyTrousers/EnderIO#3584]
*Feature Request*

I am guessing this is already in the pipeline but just wanted to check when will we be able to edit the locations within the Telepad. i.e The X,Y,Z and Dim.

I noticed locks next to these boxes however they currently do nothing. That way we won't have to go to the location each time with the co-ord selector.

**Comment by CrazyPants** [comment]
Try changing 'telepadLockCoords' in the config file.
