### ISSUE TITLE
Soul Binder bug

### ISSUE THREAD

**Issue by samiscool51** [SleepyTrousers/EnderIO#3585]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".
soul binder doesn't accept the villager or iron golem soul vials when a broken spawner is in there

#### What happens:
soul binder won't accept villager or iron golem soul vial with broken spawner and if forced with JEI and option for imputing xp doesn't show up

#### What you expected to happen:
what normally happens that broken spaweners with the entity type

#### Steps to reproduce:

1.get soul vial villager and iron golem
2.put in soul binder with broken spawner
3.become sad because it no work :(
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.81_beta
- EnderCore:1.10.2-0.4.1.46-beta
- Minecraft: 1.10.2
- Forge:12.18.1.2045

#### Your most recent log file where the issue was present: 
[logs.zip](https://github.com/SleepyTrousers/EnderIO/files/404853/logs.zip)\

#### extra info
just to let you know i tested with the max xp you can have in game and all soul vials to ensure that it was just these vials and the block was not broken,

**Comment by samiscool51** [comment]
sorry for my English it's bad

**Comment by MatthiasMann** [comment]
These 2 are disabled in the config by default.
