### ISSUE TITLE
Suggestion: Killer Joe + Mending, RF Vacuum Chest

### ISSUE THREAD

**Issue by Yusunoha** [SleepyTrousers/EnderIO#3588]
Recently Mojang added a new enchant, Mending, which allows you to repair the tool using experience orbs that you pick up.

I enchanted a dark steel sword with mending in the hope of putting the sword into a killer joe and seeing it get repaired when a killer joe picks up experience, because the killer joe should act as a player, so I thought it'd work, but sadly it did not.

It's probably due to balance reasons, but I just can't shake the thought out of my mind that this should work, so with a bit of hope I'm posting this suggestion.

To balance this as a feature, you could have the mending require either alot more experience to repair a sword or have the killer joe repair less durability with each experience orb it picks up, so you'd need to have the xp boost 3 enchant on a sword to be able to fully repair a sword in the killer joe. If the sword has any lower xp boost enchant the killer joe will not be able to fully repair the sword constantly.

Another suggestion I'd like to see added is an improved vacuum chest. Currently the chest pulls items towards itself and sucks them up when they're close enough, but if possible I'd like to see a more advanced version of this, perhaps by supplying the vacuum chest with RF. With this the vacuum chest would be able to instantly pick up any items inside it's range, and you can increase the range using capacitors. The chest could also be able to pick up experience when it's supplied with RF aswell, and it'll store a small amount of it in it's internal tank. The experience would first need to be piped out of the chest before it can pick up more.

The reason for this suggestion is mostly because of 2 things. The first reason is magnets. Whenever I get close to a vacuum chest while having a magnet (any kind of magnet added by mods) the items literally start to fly around all over the place. I could solve this by temporarily turning my magnet off, but if I often get close to that location I'd constantly need to be turning the magnet on and off. It also sometimes happens that the vacuum chest pulls an item, but the item gets stuck somewhere, and it gets stuck. Because of this it'd be really nice if the chest could instantly pick up any item within it's radius. The second reason is the farming station. I'm currently using this machine as a tree farm, but whenever I visit the farming station, there's items all over the place that the farming station didn't pick up. I could place down a vacuum chest, but I'd have to place several down to cover the whole area. If I could use a capacitor to increase the range of the vacuum chest, that'd really make things a whole lot easier and cleaner. In return just like with any other machine, the higher the capacitor, the more RF it'll use. And lastly the picking up of experience would be a nice addition, as sometimes I use the vacuum chest for picking up items near monster farms, but I also have to place down a killer joe to pick up the experience, but if the vacuum chest could pick up experience aswell, I wouldn't have to use a killer joe. Ofcourse for the vacuum chest to pick up experience, it'd need RF, and the chest only has a small internal tank, so you'd need to keep draining the experience if you want the chest to keep picking up experience.

**Comment by MatthiasMann** [comment]
Killer Joe can use mending when enabled in the config (off by default).

**Comment by Yusunoha** [comment]
it does? crap, I didn't notice

**Comment by HenryLoenwind** [comment]
Also, magnets and vacuum chests don't fight for items anymore. That leaves "xp pickup by vacuum chest", I believe.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
