### ISSUE TITLE
Cotton Seeds from Pams Harv.craft not working correctly in Farming Station

### ISSUE THREAD

**Issue by Keridos** [SleepyTrousers/EnderIO#3590]
#### What happens:
The Farming Station can plant the cotton seeds and harvest them when they are grown, but it only gets seed out of the harvest, not the cotton (which is the main product). When harvesting the cotton by hand it works fine.

#### What you expected to happen:
The farming station should not only get seeds, but the cotton itself.

#### Steps to reproduce:

1. Place Farming station with cotton seeds into it.
2. let it grow
3. take a look inside the farming station.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.81_beta
- EnderCore: 1.10.2-0.4.1.46-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2045

**Comment by HenryLoenwind** [comment]
looks normal: https://github.com/MatrexsVigil/harvestcraft/blob/1.9.4-1.10.2a/java/com/pam/harvestcraft/blocks/BlockPamCrop.java#L212

**Comment by Keridos** [comment]
Wow, that is werid, if I read correctly it only drops seeds?
Then why do I get cotton out of it when I manually harvest it?

**Comment by HenryLoenwind** [comment]
getItemDropped() will return seeds or produce, dependinf on the harvest state. getDrops() will then add seeds if the harvest stage is mature.

So no trickery here, everything is returned by getDrops()---which we call.

**Comment by CrazyPants** [comment]
I have just tested this with EnderIO-1.10.2-3.0.1.106_beta and Pam's HarvestCraft 1.9.4-1.10.2b and cotton is harvested as expected. If updating both mods doesn't resolve the issue please re-raise with the versions of both mods tested.
