### ISSUE TITLE
Pressurized conduits not connecting

### ISSUE THREAD

**Issue by wtfaatp** [SleepyTrousers/EnderIO#3592]
#### Issue Description:
When laying new conduits and connecting to old conduit with fluid in them they will not connect.. 

#### What happens:
Acts as if the pipes have different fluids..

#### What you expected to happen:
connect and have buffer fill both pipes.

#### Steps to reproduce:

1.Lay down Pressurized conduit pipes.
2.Have fluid enter a couple.
3.try to lay new pipes in connection
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.81_beta
- EnderCore: 1.10.2-0.4.1.46-beta
- Minecraft: 1.7.10
- Forge: 1.10.2-12.18.1.2045-universal

#### Your most recent log file where the issue was present: 

[13:08:56] [Netty Server IO #1/WARN] [Waila]: Catched unhandled exception : [cla
ss crazypants.enderio.conduit.TileConduitBundle] java.lang.NullPointerException
>

**Comment by MatthiasMann** [comment]
This is by design - use a wrench to connect them.
