### ISSUE TITLE
Killer Joe Crashes Server on player attack [1.10.2]

### ISSUE THREAD

**Issue by RylenWolf** [SleepyTrousers/EnderIO#3593]
#### Issue Description:
Killer Joe Crashes server when attacking player

#### What happens:

Killer Joe Crashes server when attacking player

#### What you expected to happen:

Killer Joe should not crash server when attacking player

#### Steps to reproduce:

1. Place Killer Joe
2. Add Diamond Sword (Happens with Enchanted, and disenchanted)
3. Server Crashes
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.74_beta.jar
- EnderCore: 1.10.2-0.4.1.41-beta.jar
- Minecraft: 1.10.2
- Forge:1.10.2-12.18.1.2014

#### Your most recent log file where the issue was present: 

http://pastebin.com/edwsz6jd

http://pastebin.com/BXDhYJYp

**Comment by HenryLoenwind** [comment]
Whow, that crash is happening really far away from the Killer Joe.

What's crashing is net.mysticdrew.esm.utils.ChatUtils.formatedName, please report there first. They will have to look at their code and will be able to tell you (and me) if it is cause by anything the Killer Joe (or one of the 3 other involved mods) does.

**Comment by RylenWolf** [comment]
ohh, it's probably because of the way it changes the name to a nickname somehow. Thanks for looking at it for me.

**Comment by HenryLoenwind** [comment]
Yes, I expect he's pulling some field from the killer joe fake player we don't populate. However, as we are using the Forge fakeplayer, that's crash with any mod using one, so it won't really be helpful if we populate that field just in the Killer Joe.

**Comment by mysticdrew** [comment]
RylenWolf, can you put your issue on my issue tracker please, I don't want to forget about it. I likely will not be able to fix it until this weekend. The issue tracker link is on the curse page. Thanks!

**Comment by RylenWolf** [comment]
@mysticdrew Didn't even notice it somehow, thanks to both parties for being available to help. :D

**Comment by RylenWolf** [comment]
It's been fixed, I forgot completely to let you know

**Comment by HenryLoenwind** [comment]
thx
