### ISSUE TITLE
[Suggestion] Change Config for Killer Joe + Mending to True.

### ISSUE THREAD

**Issue by VT-14** [SleepyTrousers/EnderIO#3595]
#3588, #3497, #3496, #3486, #3457 

Please consider changing that config option default to allow the Killer Joe to use the Mending Enchantment.  It's weird to blacklist a vanilla enchantment, so most people assume it's a bug or unintended inability for the Killer Joe that should be fixed.

Also, did I mention that it's weird to blacklist a vanilla enchantment?

**Comment by HenryLoenwind** [comment]
Not enabling an experimental feature by default is common practice. We are not "blocking" a vanilla feature, we have re-created a functionality that hopefully will behave the same way as the vanilla feature. Or it may transmute your golden sword into a lump of lead. ;)

Also, this feature was promoted from "experimental" to "regular" on July, 28th and is as such enabled by default.

**Comment by VT-14** [comment]
Ah. Sorry about that. I checked the changelog on Curse and didn't see any mention of it.  I've been carrying an old config from before then.  Apparently FTB Unstable did the same thing, as the version I downloaded yesterday (4.2.6) still has the old config as well.
