### ISSUE TITLE
Suggestion: Staff of Travelling Internal Battery Config

### ISSUE THREAD

**Issue by jarredhawke** [SleepyTrousers/EnderIO#3596]
As a method of balancing the Staff of Travelling I recommend adding a new option in EnderIO.cfg. This option will allow you to change the size of the internal battery in the Staff of Travelling.

This would be useful because a player/server admin/modpack creator will be able to combo increasing the internal battery size with the (already present) option of increasing the cost of teleportation per block. 

Default Staff of Travelling:
Internal battery - 250k RF
Teleport cost per block - 250 RF

What could be possible with the option I am proposing:
Internal battery - 1000k RF
Teleport cost per block - 1k RF

The above example would allow the staff to function in the same way but be more of a burden to keep charged.

**Comment by HenryLoenwind** [comment]
The staff is using darkSteelPowerStorageLevelTwo for it's buffer and travelStaffPowerPerBlockRF for its cost.
