### ISSUE TITLE
[1.7.10] Dimensional Transceiver not working

### ISSUE THREAD

**Issue by JFMillerUSA** [SleepyTrousers/EnderIO#3597]
I have a Dimensional Transceiver in the Nether on top of a RFTools Builder Block and another DT powered up in my Overworld base. The one in the nether has energy in its buffer but wont power up the Builder Block.

EnderIO: 2.3.0.428_beta
EnderCore: 0.2.0.36_beta
Forge: 10.13.4.1558

**Comment by Rakinare** [comment]
I could not confirm this. Working just fine for me. Would you mind telling me if you play on a modpack and also give screenshots of the configurations for the Transceiver?
