### ISSUE TITLE
[1.10.2] Enchanter missing texture after update

### ISSUE THREAD

**Issue by kwpugh** [SleepyTrousers/EnderIO#3598]
#### Issue Description:
After updating to the latest version, placed Enchanters have purple/black texture

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:   EnderIO-1.10.2-3.0.1.86_beta.jar
- EnderCore:   EnderCore-1.10.2-0.4.1.47-beta.jar
- Minecraft: 1.10.2
- Forge:  2046

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
thx, it will be textured again in the next build.
