### ISSUE TITLE
[1.10.2]Enchanter no texture

### ISSUE THREAD

**Issue by Gayanfalor** [SleepyTrousers/EnderIO#3599]
#### Issue Description:
The enchanter dont have texture, we can see the shape in pink and dark color and the GUI is working

#### What happens:
Enchanter lost its texture.

#### What you expected to happen:
Get its texture back ^^

#### Steps to reproduce:
I dont know i have just update the the latest version
1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.0.1.86_beta.jar
- EnderCore:EnderCore-1.10.2-0.4.1.47-beta.jar
- Minecraft: 1.10.2
- Forge:forge-1.10.2-12.18.1.2046-universal.jar

#### Your most recent log file where the issue was present: 

http://pastebin.com/iwJZsLSi

Ps: i know i'm using the latest version as you said up "do not use the lastest" but i wantes to report this, i dont know if its already known.

By tyhe way its not a really annoying bug its really minor, here is a pic:
![2016-08-10_12 52 58](https://cloud.githubusercontent.com/assets/10771109/17551629/8c2a08fe-5efb-11e6-9452-1da4581e5bfa.png)

**Comment by HenryLoenwind** [comment]
see #3598 

and that was meant as "do not just write "latest" but give us the exact version number"
