### ISSUE TITLE
"pre-painted conduits" to allow dense conduit systems up to 16 per block

### ISSUE THREAD

**Issue by iamamitten** [SleepyTrousers/EnderIO#360]
So we can run one of each conduit type in a block space, right? Why couldn't we use the painter to paint various conduits (which would then only connect to other conduits of the same type and colour, and machines) so we can have much more dense conduit systems? 

So instead of a paltry 4 conduits per blockspace (as pictured below), we could have up to 16 per blockspace. yes, it would make any "wetwork" with changing, removing, or wrenching the machine-conduit connections a little more of a pain than it is, but the potential gain of "hey, my processing facility for liquids is compact, I only need one line of conduits for all 13 of them" is pretty impressive.

![2013-12-17_22 57 45](https://f.cloud.github.com/assets/1870050/1771278/c147248e-67b1-11e3-90f4-46a90ae51773.png)

**Comment by HenryLoenwind** [comment]
with 16 channels for items, liquid and redstone, I think this can be closed.

@tterrag1098
