### ISSUE TITLE
Item Conduit Bug

### ISSUE THREAD

**Issue by dovahkiin4991** [SleepyTrousers/EnderIO#3602]
#### Issue Description:
I have an item conduit network. On 1 chest I have a conduit set to In/Out Unfiltered Priority 4 Redstone Always On with a redstone torch in it. In another chest I have a conduit set to In/Out Filtered{Redstone Things, Including redstone torch} Priority 5 Redstone Always On. Note. All channels are set to green so I can automate things, and use inventory panel.
#### What happens:
Nothing. It will not move the torch or anything else to filtered chests.

#### What you expected to happen:
The items to move to the higher priority chests that are filtered

#### Steps to reproduce:
1.Place 2 chests with item conduit setting matching above
2.Place items in unfiltered chest OR place in a 3rd chest set to extract
3.Will not go into correct destination
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.73_beta
- EnderCore: 0.4.1.41-beta
- Minecraft: 1.10.2
- Forge: Unknown

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by Rakinare** [comment]
Would you mind giving a screenshot or even a video of that problem? I'd like to try and reproduce it.

**Comment by dovahkiin4991** [comment]
I could do several screen shots but it seems to be working just fine if I have 2 separate conduits inserting and extracting. In each screen shot I show the chest and than the conduit above it
![2016-08-10_23 03 43](https://cloud.githubusercontent.com/assets/17730724/17577686/d9ba5bf2-5f4e-11e6-85b6-1f3efea3ff69.png)
![2016-08-10_23 04 06](https://cloud.githubusercontent.com/assets/17730724/17577690/defe40ec-5f4e-11e6-8790-c587b77c
![2016-08-10_23 04 12](https://cloud.githubusercontent.com/assets/17730724/17577692/e245678a-5f4e-11e6-8378-ad90abed1526.png)
7e68.png)
![2016-08-10_23 04 16](https://cloud.githubusercontent.com/assets/17730724/17577693/e5168f16-5f4e-11e6-94fa-31d67983a8a7.png)

**Comment by dovahkiin4991** [comment]
I got the 2 screen shots 1 of the chest the other of the other conduit I put all 4 in the file but it didn't put them all in
![2016-08-10_23 04 06](https://cloud.githubusercontent.com/assets/17730724/17577720/1ed941e4-5f4f-11e6-9b77-335228fbc58a.png)
![2016-08-10_23 04 12](https://cloud.githubusercontent.com/assets/17730724/17577724/23d642fa-5f4f-11e6-9b2b-2b00de16770a.png)

**Comment by dovahkiin4991** [comment]
I have an unstable server running that version and everything I just wanted to test it with just enderio to check if it was a mod compatability issue, does it in both. If you have time you can come on the server and see first hand the setup.

**Comment by Rakinare** [comment]
FTB Unstable you say? I can join, of course. I am not part of Ender IO tho, so I can just confirm the "bug" or looks what might be wrong.

**Comment by dovahkiin4991** [comment]
ok I have to go soon so you will have to hurry version 4.2.4 ip is 74.215.39.15

**Comment by Rakinare** [comment]
On my way.

**Comment by Rakinare** [comment]
Resolved. Wasn't a bug, just one error in the setup :)

**Comment by ktole1999** [comment]
was the extract set to redstone signal?

**Comment by Rakinare** [comment]
The problem was that he indeed whitelisted the ouput of redstone from one chest, but forgot to blacklist the output from redstone out of the other chest. Meant it instantly moved the redstone back to the first chest making it look like nothing happens at all.

**Comment by HenryLoenwind** [comment]
good catch, I would have overlooked that for a long time...
