### ISSUE TITLE
Inventory Panel crash client with JEI

### ISSUE THREAD

**Issue by Bodidl** [SleepyTrousers/EnderIO#3603]
#### Issue Description:

Client crash when looking up recipes in JEI while in the Inventory Panel. 
(I don't know if this is a Ender IO bug or if it is JEI making a mezz?)

#### What happens:

With Inventory Panel GUI open client crash once I click to view a recipe in JEI. Can only reproduce with the Inventory Panel GUI open. Can reproduce in single player and on a server (only client crashes).

#### Steps to reproduce:

1. Open Inventory Panel
2. Click a recipe in JEI
3. Swear!

__________________________

#### Affected Versions

- EnderIO: 3.0.1.86_beta
- EnderCore: 0.4.1.47-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2049
- JEI 3.8.0.241 beta
--and a lot more

#### Most recent log file where the issue was present: 
Crash-log:
[crash-2016-08-11_16.31.26-client.txt](https://github.com/SleepyTrousers/EnderIO/files/413566/crash-2016-08-11_16.31.26-client.txt)
Server logs (don't know if these are necessary?):
[fml-server-latest.txt](https://github.com/SleepyTrousers/EnderIO/files/413601/fml-server-latest.txt)
[latest.txt](https://github.com/SleepyTrousers/EnderIO/files/413602/latest.txt)

**Comment by Messorix** [comment]
According to your log the crash is in jei so you put it in the wrong github :P

**Comment by Bodidl** [comment]
Ok, thanks! That's why I asked in the description. I'll try posting it over there then.

**Comment by HenryLoenwind** [comment]
no, that one is on our side

**Comment by Bodidl** [comment]
Thanks for great mod and a quick response! I'll let mezz be then...

**Comment by HenryLoenwind** [comment]
fixed with build 88 and later
