### ISSUE TITLE
Green Slime Crystal instead of the Magma Slime Crystal in the Alloy smelter

### ISSUE THREAD

**Issue by marcin212** [SleepyTrousers/EnderIO#3604]
#### What you expected to happen:
When smelting Magma Slimy Mud in the Alloy Smelter, the result is a Green Slime Crystal instead of the Magma Slime Crystal. The vanilla furnace does it correctly.

#### Steps to reproduce:
1. Put Magma Slimy Mud in the  Alloy Smelter

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.86_beta.
- EnderCore: 1.10.2-0.4.1.47-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2046-universal

**Comment by HenryLoenwind** [comment]
This is a feature, not a bug. Smelting any ore will always yield the same kind of ingot, no matter what mod the ore was from.

But as the **ore** dictionary is full of stuff like tofu and crystals, this feature has been disabled recently.

**Comment by alucard87pl** [comment]
Your second sentence contradicts the first. And how is Magma Mud into Magma Crystal the same ore as Magma Mud into Green Slime?
