### ISSUE TITLE
SAG Mill Not crushing Ore?

### ISSUE THREAD

**Issue by MokahTGS** [SleepyTrousers/EnderIO#3605]
#### Issue Description:
SAG Mill does not allow the crushing of ore.

#### What happens:
The SAG mill does not allow the placement of ore into it.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO - 1.10.2-3.0.1.90_beta
- EnderCore:
- Minecraft: 1.10.2
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
sorry, you had very bad timing ;)
