### ISSUE TITLE
Mekanism

### ISSUE THREAD

**Issue by TheRealM18** [SleepyTrousers/EnderIO#3606]
#### Issue Description:
The conduits of gas for mekanism is not loaded when you have it in the 1.10.2 instant.

#### What happens:
Missing gas conduit

#### What you expected to happen:
To have a gas conduit

#### Steps to reproduce:

1. Load all Mekanism
2. load Ender io
3. check for the conduit and it is not there
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.92_beta.jar
- EnderCore: EnderCore-1.10.2-0.4.1.47-beta.jar
- Minecraft: 1.10.2
- Forge: 12.18.1.2056

#### Your most recent log file where the issue was present: 

Not a bug more of a feature missing.

**Comment by TheRealM18** [comment]
Mekanism-1.10.2-9.1.1.290.jar
MekanismGenerators-1.10.2-9.1.1.290.jar
MekanismTools-1.10.2-9.1.1.290.jar

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by UntouchedWagons** [comment]
What happened to the gas conduits that were already in EnderIO?

**Comment by HenryLoenwind** [comment]
The API changed again. And this time it's a massive change that'd need a complete re-implementation.

**Comment by UntouchedWagons** [comment]
That's a shame. I hope to see the Gas Conduits return because Mekanism's pipes are incredibly broken.

**Comment by taj1994** [comment]
I was definitely just wondering what happened to them as well. Would love to have them back if you guys are willing to work on it, since it makes making a more compact Mekanism setup easier

**Comment by tterrag1098** [comment]
The more I think about it, the more I realize the Mekanism gas API is pointless, and only serves as an unnecessary complication to the system. The forge **Fluid** API (and yes, gases *are* fluids) can handle gases just fine, see Thermal Expansion/Foundation's gaseous glowstone. Was it necessary a long time ago? Maybe, but it certainly isn't now. @aidancbrady I do wish you would consider deprecating this API in favor of the superior (and non-redundant) forge fluid API that has existed for years now. It would make issues like this one disappear, and I think your user base would be happier for it.

</rant>

**Comment by taj1994** [comment]
@tterrag1098 Agreed. It would make compatibility between new versions much easier if he switched to the Forge Fluid API

**Comment by HenryLoenwind** [comment]
Yes, using the Fluid API would make sense. Forge fluids already have isGaseous(), so it'd be no problem at all to have separate Fluid and Gas piping. Which I am considering doing for Ender IO---it's very easy to do.

**Comment by surtic86** [comment]
Any news about this Issue?
