### ISSUE TITLE
The frame can not be rotated after painting

### ISSUE THREAD

**Issue by PeakXing** [SleepyTrousers/EnderIO#3608]
Spraying the pipe frame can not rotate the direction of the stairs.
Is this normal design?
![image](https://cloud.githubusercontent.com/assets/21017556/17647499/57af45ee-6225-11e6-9664-c1adcf3668f8.png)

**Comment by VT-14** [comment]
For directional blocks, you have to use a Yeta Wrench set to whichever view lets you see facades.

...at least, that's how it worked for wood logs not too long ago.  I don't know if there is any difference with things like stairs or recent changes.

**Comment by PeakXing** [comment]
ok TKS! My bad
