### ISSUE TITLE
error while starting minecraft server

### ISSUE THREAD

**Issue by abendplays** [SleepyTrousers/EnderIO#3609]
Hi guys, 
first of all, I want to excuse my bad english skills, I don´t know the language a lot :D .
As I have some issues with my minecraft server, I want to ask you, if you could help me, to solve them. 
[crash-2016-08-14_18.21.48-server.txt](https://github.com/SleepyTrousers/EnderIO/files/417114/crash-2016-08-14_18.21.48-server.txt)

**Comment by AnrDaemon** [comment]
`UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) `

I stopped reading here.
Update your instance.

**Comment by abendplays** [comment]
How can I do this, when I am using a modpack?

**Comment by AnrDaemon** [comment]
Direct all modpack questions to the modpack maintainer.

**Comment by HenryLoenwind** [comment]
That, and it's HQM that is crashing.

**Comment by abendplays** [comment]
And what about the error in the bottow with ae2 and enderio?!

**Comment by mindforger** [comment]
@HenryLoenwind yeah, he is right, you could probably update to the rv3 API as rv2 is declared dead and bugged out mostly

**Comment by HenryLoenwind** [comment]
That's not an error, that's a diagnostic warning. If I could write code that could diagnose crashes itself and print out the reason for them, I'd have more money than notch...

**Comment by mindforger** [comment]
i was just hinting to switch when able :)

**Comment by abendplays** [comment]
where are the issues and how can I fix them?!

**Comment by HenryLoenwind** [comment]
HQM is crashing. Have you played on this map before? If so, try to delete your HQM data (no, I have no idea where it is stored). If that doesn't help, ask you modpack maker and the HQM guys (although I wouldn't expect an answer from them for 1.7).
