### ISSUE TITLE
Crash on Server Startup

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [SleepyTrousers/EnderIO#3611]
#### Issue Description:
Crash on Server Startup, I orginally thought it was a RFtools problem, but I updated everything but RFtools and had the same problem, so then I went back and updated everything except for EnderIO and the server started fine.

#### What happens:
http://pastebin.com/W4QMknUA

#### What you expected to happen:
Server to Start

#### Steps to reproduce:

1. Started Server Again
2. Updated all mods except RFtools
3. Updated all mods except for EnderIO (fixed problem)
...

____
#### Affected Versions (Do *not* use "latest"):
EnderIO: 1.10.2-3.0.1.92
EnderCore: 1.10.2-0.4.1.47
Forge: .2063

#### Your most recent log file where the issue was present: 

http://pastebin.com/W4QMknUA

**Comment by RedNesto** [comment]
Could you try with forge 2061.
Seems to be related to the recent [addition of WorldCapabilities](https://github.com/MinecraftForge/MinecraftForge/commit/bfddcfb4fc47d5bf233dfa7426654d7739b3d2d0) in forge 2062.

**Comment by awkwaRdcaRRot** [comment]
That's what another person suggested elsewhere. I plan on trying when I get home.
