### ISSUE TITLE
Fluid tank bug

### ISSUE THREAD

**Issue by huaji233** [SleepyTrousers/EnderIO#3612]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

Fluid box and the soul of the carpenter, you can brush minerals, fluid tank fluid is not 1000, but also to pick up a bucket.
Because a bucket of liquid is 1000, even if there is a drop of liquid in the tank, it can also be connected to a barrel.

#### What you expected to happen:

Fix this bug

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by AnrDaemon** [comment]
1. The template was there not for you to ignore.
2. Use search already. This has been reported ten times at least. And this is not an EIO bug.
