### ISSUE TITLE
[1.10.2] Telepad Request - Config Option

### ISSUE THREAD

**Issue by praetoras** [SleepyTrousers/EnderIO#3613]
#### Suggestion Description:

The telepad is great, and I love working with it. However, I would like the ability to turn off its "teleport anchor" behavior in the config, so that it doesn't show up or allow teleports when standing on teleport anchors, or when using the staff of travel/The Ender.

**Comment by mindforger** [comment]
very nice idea! one way teleport mechanism, could be very usefull when playing multiplayer

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
I like that one

**Comment by HenryLoenwind** [comment]
Thx for this request, it made me find some bugs with the current logic.

**Comment by mindforger** [comment]
"yeah this code works, but there are some quirks i got to check out .... nevermind ... got to work on another mor serious problem" .... several days later ... "did i forgot something? ... nah seems cool" ALWAYS XD

**Comment by praetoras** [comment]
Awesome to know it was helpful :D  I really appreciate all your work on the mod!
