### ISSUE TITLE
Unable to craft Inventory Panel Remote (1.10.2-3.0.1.92_beta)

### ISSUE THREAD

**Issue by xenoflot** [SleepyTrousers/EnderIO#3614]
Unable to craft the Inventory Panel Remote.
Playing FTB Unstable 1.10.2, upgraded with latest Forge, EnderIO and EnderCore.

#### What happens:
JEI tool tip tells me the recipe requires an Unpainted version of the Heavy Pressure Plates and so is not recognising vanilla plates w/o that flag.

#### What you expected to happen:
Recipe to accept vanilla Heavy Pressure Plates for this recipe

#### Steps to reproduce:

1. Craft components
2. Put in crafting bench
3. Fight existential dread
...
Profit (I'm the first to make that joke, yeah, really.)
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.92_beta (and 3.0.1.81_beta)
- EnderCore: EnderCore-1.10.2-0.4.1.47-beta (and 0.4.1.46-beta)
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2064 (and 2046)

#### Your most recent log file where the issue was present: 

No relevant logs available.

**Comment by HenryLoenwind** [comment]
And nobody has noticed this yet? I'm speechless...

**Comment by HenryLoenwind** [comment]
Fixed in next build.

In the meantime you can use painted pressure plates. The recipe ignores the paint, just like it ignores the RF level of the staff.

**Comment by xenoflot** [comment]
Now _that's_ service! Thanks!

**Comment by HenryLoenwind** [comment]
Bugs that I can actually find in our code can actually be fixed fast ;)
