### ISSUE TITLE
EnderIO Conduits & Mekanism

### ISSUE THREAD

**Issue by Utildayael** [SleepyTrousers/EnderIO#3615]
#### Issue Description:
EnderIO conduits have issues interacting with various Mekanism power storage devices.

#### What happens:
EnderIO conduits seem to have issues pulling power from Mekanism Induction Matrix multiblock. They can put power IN fine but can't pull it out. Talked to Mek author and he said the problem is something to do with EnderIO not implementing Tesla API properly.

This also happens using Mekanism universal cables on EnderIO machines and capacitator banks. In those cases they are unable to pull power FROM those EnderIO devices.

Commonality is issues with Mekanism/EnderIO playing nice together when it comes to power storage devices.

Issue reference: 
https://github.com/aidancbrady/Mekanism/issues/3593

#### What you expected to happen:
Power to flow in or out accordingly.

#### Steps to reproduce:
1. Create Mekanism Induction Matrix
2. Attach enderio cables and try to pull power from it

1. Create EnderIO Sterling Gen or Capacitator Bank
2. Attach mechanism cables and try to pull power from it

____
#### Affected Versions:

- EnderIO:  EnderIO-1.10.2-3.0.1.86_beta
- EnderCore:  EnderCore-1.10.2-0.4.1.47-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2050

#### Your most recent log file where the issue was present: 

n/a - not a crash

Thanks!

**Comment by mindforger** [comment]
you can force a crash by holding F3 + C for minimum 6seconds, the crashlog contains valuable informations

**Comment by Utildayael** [comment]
Roger. Will do that this evening and add log.

**Comment by HenryLoenwind** [comment]
No log needed. Enbder IO doesn not implement that TESLA-nonsense at all.

**Comment by Utildayael** [comment]
The joys of all these damn power APIs. I feel ya man. Sorry to hear I can't use my favorite cables with Mekanism tho. :(

Thanks
