### ISSUE TITLE
Feature: Vacuum Chest upgrade

### ISSUE THREAD

**Issue by MatthiasMann** [SleepyTrousers/EnderIO#3616]
An upgrade for the Vacuum chest which teleports (dropped) items directly into it's inventory instead of hovering them until they touch the vacuum chest.

This upgrade should be much more expensive (like requiring endermen heads / souls etc) and also consume fuel (like the one powering the remote inventory panel) based on distance of the item.

Possibly with an larger range than the normal vacuum panel as well.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
