### ISSUE TITLE
Suggestion: Mending working in Killer joe As Default.

### ISSUE THREAD

**Issue by HeavyDeception** [SleepyTrousers/EnderIO#3620]
Could we have it so that the mending works with the sword the killer joe is using.

Or if there is a configuration for this could it be default.

**Comment by AnrDaemon** [comment]
Could you just, you know, enable it in the configuration, instead of wasting everyone's time reporting a nonissue?

**Comment by HeavyDeception** [comment]
no need to be a prick about it.

**Comment by bookerthegeek** [comment]
@HeavyDeception if you look through the configuration you will see an option to enable that feature you requested.

Please close the issue.

**Comment by HeavyDeception** [comment]
@AnrDaemon When you type to someone Please be nicer like saying "There is a setting for that and its off by default. Plz Look at the configs for Enderio."

**Comment by tterrag1098** [comment]
It's fine, there are a lot of config options and it is easy to get lost in them.

**Comment by HeavyDeception** [comment]
@tterrag1098 thanks you.

**Comment by bookerthegeek** [comment]
@AnrDaemon do you want the repository owners to ban you? Cause being a D-bag to people when it is not needed is how you do that.

Not that I am much better but still...


Also, @tterrag1098 thank you for never banning me for my d-baggery. :)

**Comment by HenryLoenwind** [comment]
BTW, the config **is** on by default. If it is not working for you, you are either using an old version, your pack creator disabled it, your server owner disabled it, or there's a bug.

**Comment by HeavyDeception** [comment]
@HenryLoenwind Its and 1.10 enderio is 3.0.1.81 beta
