### ISSUE TITLE
RFtools tank monitor plus EIO Vat crashed server

### ISSUE THREAD

**Issue by seulil** [SleepyTrousers/EnderIO#3621]
#### Steps to reproduce:

1.place VAT
2.Place RFT fluid monitor near vat
3.open fluid monitor GUI and select VAT
4.try to adjust amount. percentage of fluid...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.81_beta 
- EnderCore:EnderCorePlugin (EnderCore-1.10.2-0.4.1.48-beta.jar)
- Minecraft: 1.10.2
- Forge:Forge{12.18.1.2053} forge-1.10.2-12.18.1.2053

#### Your most recent log file where the issue was present: 

Thread: Server thread
Stacktrace:
	at crazypants.enderio.fluid.SmartTankFluidHandler.get(SmartTankFluidHandler.java:29)
	at crazypants.enderio.machine.vat.TileVat.getCapability(TileVat.java:258)
	at mcjty.rftools.blocks.monitor.LiquidMonitorBlockTileEntity.checkStateServer(LiquidMonitorBlockTileEntity.java:135)
	at mcjty.rftools.blocks.monitor.LiquidMonitorBlockTileEntity.func_73660_a(LiquidMonitorBlockTileEntity.java:114)

**Comment by mindforger** [comment]
complete crashlog please :) as pastebin or attachment

**Comment by HenryLoenwind** [comment]
No logfile needed. I see what is happening.

RFTools is calling getCapabilities with "null" as side. However, TileEntitty.getCapability() is in a package that is annotated @ParametersAreNonnullByDefault, so null is not a valid value. Please report this to @McJty.

**Comment by McJty** [comment]
The annotation is wrong. Check the comment:

public interface ICapabilityProvider
{
    /**
     * Determines if this object has support for the capability in question on the specific side.
     * The return value of this MIGHT change during runtime if this object gains or looses support
     * for a capability.
     *
     * Example:
     *   A Pipe getting a cover placed on one side causing it loose the Inventory attachment function for that side.
     *
     * This is a light weight version of getCapability, intended for metadata uses.
     *
     * @param capability The capability to check
     * @param facing The Side to check from:
     *   CAN BE NULL. Null is defined to represent 'internal' or 'self'
     * @return True if this object supports the capability.
     */
    boolean hasCapability(Capability<?> capability, @Nullable EnumFacing facing);

**Comment by seulil** [comment]
sorry for delay heres the crash log
[crash-2016-08-19_03.09.11-server.txt](https://github.com/SleepyTrousers/EnderIO/files/426592/crash-2016-08-19_03.09.11-server.txt)

**Comment by Utildayael** [comment]
Same issue. Makes world unloadable. Isn't just a Vat issue, it's anything with EnderIO fluid conduits and RFTools Liquid Monitor. Reported to @McJty and was referenced here.
