### ISSUE TITLE
[1.10.2] Dimensional Transceiver gui doesn't close on "e" key

### ISSUE THREAD

**Issue by mezz** [SleepyTrousers/EnderIO#3622]
On Forgecraft, when I open a Dimensional Transceiver gui I have to press the Escape key to close it, pressing E (like any other gui) does not close it.
I suspect it has to do with the text entry box on some tabs, although this bug is about the tabs without the text entry field.
I tested some other EnderIO guis around my base and they work fine.

**Comment by AnrDaemon** [comment]
Um. Try advanced filter show info screen.

**Comment by mezz** [comment]
The filter tab has the same issue as the first tab. I can use Escape but not E.

**Comment by AnrDaemon** [comment]
What happens if you remap Inventory hotkey? I.e. to the Tab key?

**Comment by HenryLoenwind** [comment]
That won't help, we disable the inventory key so people can use names with "e" for channels...

**Comment by AnrDaemon** [comment]
Can't you do it only when an edit field have focus?

**Comment by HenryLoenwind** [comment]
That's why I didn't close the ticket;)

**Comment by AnrDaemon** [comment]
Point taken :)

**Comment by HenryLoenwind** [comment]
Yeah, this is one of those known quirks that are so old nobody remembers why they weren't fixed in the first place. I'll look into this in the weekend. I expect it to be just one or two lines of code...

**Comment by HenryLoenwind** [comment]
(last tag for the statistics only)
