### ISSUE TITLE
Class Not Found Exception when trying to load Ender IO/Ender Core in dev workspace.

### ISSUE THREAD

**Issue by Anime-Quatroctus** [SleepyTrousers/EnderIO#3624]
#### Steps to reproduce:

1. Create dev workspace
2.  Add Ender IO and Ender Core to devs mods folder
3. Run game.

- EnderIO: 1.10.2-3.0.1.92_beta
- EnderCore: 1.10.2-0.4.1.48-beta
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.2042

Link to the log file where the error occurs: http://pastebin.com/W0RKEE20

**Comment by HenryLoenwind** [comment]
Forge adds a command line parameter about frame recalculation to the launch profile. Remove it.
