### ISSUE TITLE
Farm doesn't accepts all axes

### ISSUE THREAD

**Issue by TonRZN** [SleepyTrousers/EnderIO#3625]
I've tried with various axes, Tinker's axes works fine but vanilla or the Dark Axe doesn't

**Comment by JonaBrackenwood** [comment]
Confirmed, only axes from certain mods (AbyssalCraft, Tinker's Construct) seem to work.

**Comment by MakeLord95** [comment]
Same thing happening on EnderIO version 1.10.2-3.0.1.92

**Comment by MakeLord95** [comment]
Works on forge .2067, with EnderIO .92 and EnderCore .48, so it's forge that broke it...
"Build 2068:
	bonii-xx: Expand getHarvestLevel to include player and blockstate (#3192)"

**Comment by HenryLoenwind** [comment]
yes, this is a Forge bug

https://github.com/MinecraftForge/MinecraftForge/issues/3210

**Comment by MakeLord95** [comment]
np :)
