### ISSUE TITLE
Player logs into a void then server crashes

### ISSUE THREAD

**Issue by Renadarain** [SleepyTrousers/EnderIO#3627]
Hi :)

#### Issue Description:
On player login the player is not loaded into the world properly.  If it's daytime you blue everywhere above and below, if it's night stars in all directions above the player is the moon. Player can look around but never actually fully loads.  After a about 30 seconds the player is kicked out as the server has crashed. Client does not crash.

#### Steps to reproduce:

This doesn't happen on every login. There doesn't appear to be any rhyme or reason as to when it will crash.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.91_beta.jar
- EnderCore: 1.10.2-0.4.1.48-beta.jar
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2065

#### Your most recent log file where the issue was present: 

http://pastebin.com/KvGXUvtv

Regards,
Renada

**Comment by HenryLoenwind** [comment]
#3524
