### ISSUE TITLE
EnderIO-JEI intergration crush

### ISSUE THREAD

**Issue by seulil** [SleepyTrousers/EnderIO#3628]
#### What happens:
Server crashed after clicking item in JEI item when Inventory Panel Remote (or any other Inventory panel) GUI opened in hand.
Crashes both with jei sync on and off.

#### Steps to reproduce:

1.Open inventory panel (any)
2.Try to get recipe for an item in JEI  by clicking on any item.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.0.1.81_beta
[crash-2016-08-21_13.57.49-client.txt](https://github.com/SleepyTrousers/EnderIO/files/428815/crash-2016-08-21_13.57.49-client.txt)

- EnderCore:EnderCore-1.10.2-0.4.1.49-beta
- Minecraft: 1.10.2
- Forge:(forge-1.10.2-12.18.1.2053
   -jei_1.10.2-3.9.0.245(tested also with JEI 244)
#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
update

**Comment by seulil** [comment]
lol didn't noticed that EnderIO wasn't updated thx
