### ISSUE TITLE
Basic Capacitor Recipe Not Working

### ISSUE THREAD

**Issue by fissionblue** [SleepyTrousers/EnderIO#3629]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

I follow the recipe as represented here:
http://wiki.enderio.com/Capacitors

#### What you expected to happen:

Basic Capacitor to appear in output slot. I also tried iron per the note in the wiki, to no avail. Screenshot attached.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.86_beta.jar
- EnderCore: EnderCore-1.10.2-0.4.1.48-beta.jar
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.1.2066

#### Your most recent log file where the issue was present:

N/A

[pastebin/gist/etc link here]

![2016-08-21_22 19 43](https://cloud.githubusercontent.com/assets/21157174/17837754/266b7ba0-67ee-11e6-8660-1628349da349.png)

**Comment by MatthiasMann** [comment]
The recipe depends on the configured difficulty level and can be found in the recipe_materials_core.xml file in your config folder.

This is the default receipt:
https://github.com/SleepyTrousers/EnderIO/blob/1.10/resources/assets/enderio/config/recipe_materials_core.xml#L293
When copper is available the CAPACITOR_METAL will be a copper ingot, otherwise a gold nugget.

**Comment by fissionblue** [comment]
Thanks a ton for the quick reply. I just took a look at the xml file and tried the following recipe with success:

![screenshot 2016-08-21 23 32 11](https://cloud.githubusercontent.com/assets/21157174/17838131/b5c3b9ee-67f7-11e6-942c-97899410a26e.png)

I will attempt to update the wiki entry as well as any others I find in need. Thanks again for the development and support of a fantastic mod.
