### ISSUE TITLE
Crash by building a machine

### ISSUE THREAD

**Issue by Machex** [SleepyTrousers/EnderIO#3631]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
A few friends and I have make an modpack and if you build a machine from ender io the game crash.

#### What you expected to happen:
If you build an machine you can see how you can craft it but if you have it or you place it the game crash.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.7.10
- EnderCore:1.7.10
- Minecraft: 1.7.10
- Forge:1.7.10

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by ShaCraft** [comment]
I'm not a part of this project, but I can tell you that you will need to provide the correct versions (Not 1.7.10 there are many versions for 1.7.10). You will also need to provide a crash log from the server/game. You can find the log in the crash-report directory of the root directory of the server/game. 
Sha
