### ISSUE TITLE
Chisel support doesn't connect to other facades

### ISSUE THREAD

**Issue by Susjin** [SleepyTrousers/EnderIO#3632]
#### What happens:
When i place an Facade painted with an chisel block that have connected textures next to another facade with same painting, they do not connect, but if i place the facade next to the chisel block that it is painted, it connect without problems

#### What you expected to happen:
To it connect too

#### Steps to reproduce:

1.Paint an Facade with an chisel block with connected textures
2.Paint another one with the same block.
3.Place the two facades next to each other
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.94_beta
- EnderCore: 0.4.1.49-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2070

Screenshot:
https://imgur.com/a/T7bml

**Comment by HenryLoenwind** [comment]
on-hold for a design decision.

Problem: At the moment we are caching our block renders. For facades that look different depending on their location that caches only the first "look" that is rendered. There is no way for us to detect if a block has this behavior, so we'd need to disable caching completely for this to work. But---facade rendering is a quite expensive operation...

**Comment by bookerthegeek** [comment]
Could you hook into the mods rendering code and just use that instead? Don't know if that would be easier or not.

**Comment by HenryLoenwind** [comment]
that is what we are doing and what makes that so expensive

**Comment by bookerthegeek** [comment]
Ah, OK.

**Comment by HenryLoenwind** [comment]
For static blocks this should actually about as fast as before. Chisel blocks now take 10-20 times as long to render, but that extra is what they also take when rendered on their own. Or overhead is about 10-20% of that on top.

**Comment by bookerthegeek** [comment]
That is pretty cool.
