### ISSUE TITLE
Suggestion: Ender I/O Remote Awareness Automation

### ISSUE THREAD

**Issue by teamMK** [SleepyTrousers/EnderIO#3633]
The Ender I/O need an Upgrade in the time of the Inventorypanel. The Ender I/O with the RAA Upgrade should give the player the abillity to autocraft things in the panel in this way:

In a range of 5x5x5 Blocksthe I/O with the RAA upgrade should be able to be linked to 3 Machines and hold 3 crafting recipies per machine. With each capacitor upgrade, the count of machines that can be linked to the I/O increase by 1 and recipie slots should increase by 2.
 
To function it need 1mb per action of "dew of the void" 

To create crafting tasks you have to encode crafting task crystals or something like that. A nice additon is that purple particles move from the I/O to the machine where your automatic crafting task is done.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
