### ISSUE TITLE
I/O button on all mashines turns screen blue. No crush. Just can't adjust I/O

### ISSUE THREAD

**Issue by seulil** [SleepyTrousers/EnderIO#3634]
Like title said...

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.0.1.94_beta
- EnderCore:EnderCore-1.10.2-0.4.1.49-beta
- Minecraft: 1.10.2
- Forge:Forge 12.18.1.2053

#### Your most recent log file where the issue was present: No Crash. Just bug.

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
known issue due to work in progress
