### ISSUE TITLE
configure io bug

### ISSUE THREAD

**Issue by PandaFrog** [SleepyTrousers/EnderIO#3635]
#### Issue Description:
When clicking on configure io it displays what looks to be the sky instead of the configure screen i've tested it on farming station, dimensional transceiver not sure of any other blocks tho.

#### What happens:
You just see the sky and not the proper configure io screen

#### Steps to reproduce:

1. open the ui of a machine
2. click configure io

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.94_beta
- EnderCore: 0.4.1.49-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2072

**Comment by seulil** [comment]
ye just need to wait so they fix that...already posted that issue...just get back to EIO 3.0.1.92 and You'll be cool..;p for now

**Comment by HenryLoenwind** [comment]
see #3634
