### ISSUE TITLE
Ticking tile entity from Vibrant Solar Panel causes crash

### ISSUE THREAD

**Issue by Zettt** [SleepyTrousers/EnderIO#3636]
#### Issue Description:
Breaking a vibrant solar panel with an enderio pick causes Minecraft to crash, and crash onload. Removing the ticking entity with mcedit makes the problem temporarily go away.

#### What happens:
It crashes.

#### What you expected to happen:
Not to crash.

#### Steps to reproduce:

1. Break Vibrant Solar Panel.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.94
- EnderCore: 0.4.1.49
- Minecraft: 1.10.2
- Forge: 2070

#### Your most recent log file where the issue was present: 

http://pastebin.com/nF2WcqBD

**Comment by HenryLoenwind** [comment]
```
at mcmultipart.block.BlockCoverable.func_185477_a(BlockCoverable.java:138)
```

That's not an Ender IO crash, that's mc multipart.
