### ISSUE TITLE
Crashed when looking up with Dark Steel Elytra(Minecraft 1.10.2)

### ISSUE THREAD

**Issue by RiolluCraft** [SleepyTrousers/EnderIO#3637]
Sorry, I can not speak English fluently because I'm Brazilian

#### What happens:
Note: I look up with dark steel reinforced with the elytra and the chunk unloads.

#### What you expected to happen:
that fly with the elytra without bugs.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.94_beta
- EnderCore: 0.4.1.49-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2056

Screenshot:
http://imgur.com/5mxRb6V

**Comment by CrazyPants** [comment]
I cant reproduce this. Can you give me any more information? For example, does it happen all the time? Does it crash the game? Is there any errors in the log file?

cheers

**Comment by mrtomwolf** [comment]
For me it didn't crash, I just went in no clip mode some how and ended up under bedrock, after a quick /ftb home command I found myself in flight mode just above the ground. Might be a conflict with Angel Rings?
