### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by cameronmyer0** [SleepyTrousers/EnderIO#3638]
i need help

---- Minecraft Crash Report ----

WARNING: coremods are present:
MDECore-Core (mdecore-1.10.2-1.0.jar)
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
IC2core (industrialcraft-2-2.6.1-ex110.jar)
EnderCorePlugin (EnderCore-1.10.2-0.4.1.46-beta.jar)
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
CCCDeobfPlugin (unknown)
DepLoader (BrandonsCore-1.10.2-2.1.0.36-universal.jar)
MalisisCorePlugin (MalisisCore-1.10.2.jar)
SimpleCore (Simple Quarry-1.9.4_1.0.0.jar)
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
ShetiPhian-ASM (ShetiPhianCore-1.10.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 8/23/16 7:42 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: codechicken/core/ClientUtils
at codechicken.enderstorage.network.TankSynchroniser.tickEnd(TankSynchroniser.java:265)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_171_TankSynchroniser_tickEnd_ClientTickEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.core.ClientUtils
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 15 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.10.2
Operating System: Mac OS X (x86_64) version 10.10.5
Java Version: 1.8.0_74, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 453138088 bytes (432 MB) / 4214489088 bytes (4019 MB) up to 4214489088 bytes (4019 MB)
JVM Flags: 25 total; -Xmx4G -Xms4G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.32 Powered by Forge 12.18.1.2073 Optifine OptiFine_1.10.2_HD_U_C2 79 mods loaded, 78 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJA mcp{9.19} Minecraft Coder Pack 
UCHIJA FML{8.0.99.99} Forge Mod Loader 
UCHIJA Forge{12.18.1.2073} Minecraft Forge 
UCHIJA CodeChickenCore{2.1.8.79} CodeChicken Core 
UCHIJA actuallyadditions{1.10.2-r57} Actually Additions 
UCHIJA armorplus{1.9.4-3.1.10.0} ArmorPlus 
UCHIJA BBG{5.0.0} BetterBedrockGen 
UCHIJA betterbuilderswands{0.6.5} Better Builder's Wands 
UCHIJA BetterSprinting{1.1.5} Better Sprinting 
UCHIJA ExtraUtils2{1.0} ExtraUtils2 
UCHIJA mantle{1.10-0.10.3.jenkins156} Mantle 
UCHIJA tconstruct{1.10-2.3.3a.jenkins271} Tinkers' Construct 
UCHIJA immersiveengineering{${version}} Immersive Engineering 
UCHIJA JEI{3.9.0.246} Just Enough Items 
UCHIJA blockdrops{1.0.10} Block Drops 
UCHIJA bookshelf{1.3.0.282} Bookshelf 
UCHIJA BrandonsCore{2.1.0} Brandon's Core 
UCHIJA cavern{1.0.8} Cavern 
UCHIJA chancecubes{1.10-2.1.3.115} Chance Cubes 
UCHIJA chisel{MC1.9.4-0.0.6.33} Chisel 
UCHIJA chiselsandbits{11.3} Chisels & Bits 
UCHIJA ComputerCraft{1.80pr0} ComputerCraft 
UCHIJA MineTweaker3{3.0.10} MineTweaker 3 
UCHIJA cxlibrary{1.2.2} CXLibrary 
UCHIJA D3Core{1.3.0.59} D³Core 
UCHIJA D3Commands{1.3.0.36} D3Commands 
UCHIJA Waila{1.7.0} Waila 
UCHIJA darkutils{1.1.3.71} Dark Utilities 
UCHIJA DimensionalResources{1.0.3} DimensionalResources 
UCHIJA DraconicEvolution{2.0.0} Draconic Evolution 
UCHIJA DurabilityShow{3.1.1} Durability Show 
UCHIJA EnderStorage{2.1.3.71} EnderStorage 
UCHIJA shetiphiancore{3.3.0} ShetiPhian-Core 
UCHIJA endertanks{1.4.0} EnderTanks 
UCHIJA EnderBags{2.0.1} EnderBags 
UCHIJA endercore{1.10.2-0.4.1.46-beta} EnderCore 
UCHIJA EnderIO{1.10.2-3.0.1.81_beta} Ender IO 
UCHIJA enderutilities{0.6.5-beta.1} Ender Utilities 
UCHIJA mdecore{1.10.2-1.0} MattDahEpic Core 
UCHIJA exchangeorb{1.10.2-1.0} Exchange Orb 
UCHIJA excore{1.6.2} EXCore 
UCHIJA expandedbonemeal{1.0.0} ExpandedBonemeal 
UCHIJA ezstorage{2.1.5} EZ Storage 2 
UCHIJA FastLeaveDecay{1.1} Fast Leave Decay 
UCHIJA ftfloocraft{1.7.5} Floocraft 
UCHIJA forestry{5.1.8.189} Forestry 
UCHIJA llor{1.1.0-mc[1.9-1.10.2]} Light Level Overlay Reloaded 
UCHIJA FEI{1.0.15} Forever Enough Items 
UCHIJA glass_shards{1.6.2} Glass Shards 
UCHIJA hopperducts{1.4.7} Hopper Ducts 
UCHIJA IC2{2.6.1-ex110} IndustrialCraft 2 
UCHIJA InventoryPets{1.4.8.1} Inventory Pets 
UCHIJA IronChest{7.0.6.794} Iron Chest 
UCHIJA itemscroller{0.5.1} Item Scroller 
UCHIJA malisiscore{1.9.4-4.0.1} MalisisCore 
UCHIJA malisisdoors{1.9.4-5.0.1} MalisisDoors 
UCHIJA MoreFurnaces{1.8.1} More Furnaces 
UCHIJA mysticalagriculture{1.0.0} Mystical Agriculture 
UCHIJA yurtmod{7.01} Nomadic Tents 
UCHIJA placemod{3.8} Placemod 
UCHIJA ProjectE{1.9.4-PE1.0.5B} ProjectE 
UCHIJA reborncore{2.5.4.1} RebornCore 
UCHIJA reborncore-mcmultipart{2.5.4.1} reborncore-MCMultiPart 
UCHIJA redstonepaste{1.7.4} Redstone Paste 
UCHIJA reinforcedTools{1.4.1} ReinforcedTools 
UCHIJA rftools{5.09} RFTools 
UCHIJA rftoolsdim{4.30beta46} RFTools Dimensions 
UCHIJA Roguelike{1.5.4} Roguelike Dungeons 
UCHIJA AS_Ruins{16.2} Ruins Spawning System 
UCHIJA simplequarry{1.9.4_1.0.0} Simple Quarry 
UCHIJA supercraftingframe{1.2.0.84} Super Crafting Frame 
UCHIJA lteleporters{1.1.3} Lemon's Simple Teleporters 
UCHIJA VeinMiner{0.34.0_1.9-58ffb13} Vein Miner 
UCHIJA VeinMinerModSupport{0.34.0_1.9-58ffb13} Mod Support 
UCHIJA WailaHarvestability{1.1.8} Waila Harvestability 
UCHIJA warpscrolls{1.0} warpscrolls 
UCHIJA worldhandler{3.8} World Handler Gui 
UCHIJA wuestUtilities{1.10.2} Wuest Utilities 
UD mdecore-core{1.0} MDE Core - ASM Tweaks 
Loaded coremods (and transformers): 
MDECore-Core (mdecore-1.10.2-1.0.jar)
com.mattdahepic.mdecore.asm.TickrateTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
cubex2.cxlibrary.CoreModTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)

EnderCorePlugin (EnderCore-1.10.2-0.4.1.46-beta.jar)
com.enderio.core.common.transform.EnderCoreTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
net.fybertech.nwr.NWRTransformer
CCCDeobfPlugin (unknown)

DepLoader (BrandonsCore-1.10.2-2.1.0.36-universal.jar)

MalisisCorePlugin (MalisisCore-1.10.2.jar)
net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
net.malisis.core.util.chunkblock.ChunkBlockTransformer
net.malisis.core.renderer.transformer.MalisisRendererTransformer
net.malisis.core.renderer.icon.asm.TextureMapTransformer
net.malisis.core.util.clientnotif.ClientNotifTransformer
SimpleCore (Simple Quarry-1.9.4_1.0.0.jar)
com.mrdimka.simplequarry.core.SimpleClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
codechicken.lib.asm.ClassHeirachyManager
codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
codechicken.core.asm.TweakTransformer
codechicken.core.asm.DelegatedTransformer
codechicken.core.asm.DefaultImplementationTransformer
ShetiPhian-ASM (ShetiPhianCore-1.10.2.jar)
shetiphian.core.asm.ClassTransformer
Pulsar/tconstruct loaded Pulses: 
- TinkerCommons (Enabled/Forced)
- TinkerWorld (Enabled/Not Forced)
- TinkerTools (Enabled/Not Forced)
- TinkerSmeltery (Enabled/Not Forced)
- TinkerGadgets (Enabled/Not Forced)
- TinkerOredict (Enabled/Forced)
- TinkerIntegration (Enabled/Forced)
- TinkerFluids (Enabled/Forced)
- TinkerMaterials (Enabled/Forced)
- chiselsandbitsIntegration (Enabled/Not Forced)
- WailaIntegration (Enabled/Not Forced)

CodeChickenCore: ignoreInvalidMCVersion state: false
D3Core: Debug: false Silliness: true AprilFools: true PastPost:true
EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
              * Optifine is installed. This is NOT supported.
             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
Detailed RF API diagnostics:
              * RF API class 'EnergyStorage' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/EnergyStorage.class
              * RF API class 'IEnergyConnection' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyConnection.class
              * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
              * RF API class 'IEnergyHandler' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyHandler.class
              * RF API class 'IEnergyProvider' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyProvider.class
              * RF API class 'IEnergyReceiver' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyReceiver.class
              * RF API class 'IEnergyStorage' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyStorage.class
              * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/TileEnergyHandler.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/TileEnergyHandler.class

Launched Version: 1.10.2
LWJGL: 2.9.2
OpenGL: ATI Radeon HD 4670 OpenGL Engine GL version 2.1 ATI-10.0.35, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.

**Comment by cameronmyer0** [comment]
does this mean i need to take out the brandon's core mod

**Comment by MatthiasMann** [comment]
This doesn't look like it has anything to do with EnderIO or EnderCore

**Comment by mindforger** [comment]
it looks like you have an invalid chickencore lib, delete the 1.10 folder from your mods folder and let your client reload all dependencies, check if you have the right version of chickenbones mods installed!
