### ISSUE TITLE
KillerJoe not work 

### ISSUE THREAD

**Issue by bzp2010** [SleepyTrousers/EnderIO#3641]
#### Issue Description:
KillerJoe not work
#### What happens:
In Minecraft1.7.10 and KCauldron
I install a CrazyLogin Plugin to save player.
But KillerJoe not work this time.
When i uninstall CrazyLogin.
KillerJoe is work

#### What you expected to happen:

I think it should be no permissions or not automatic login

#### Steps to reproduce:

1.Minecraft1.7.10
2.KCauldron
3.bukkit plugin : CrazyLogin7.23.4
4.KillerJoe

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:latest
- EnderCore:latest
- Minecraft: 1.7.10
- Forge:1614

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Kcauldron is not supported, and you already wrote that that plugin stops it from working, so report the problem there, please.
