### ISSUE TITLE
[Bug] Magnet not working anymore

### ISSUE THREAD

**Issue by Greg9711** [SleepyTrousers/EnderIO#3642]
#### What happens:
I updated Ender IO to the newest version and the magnet that was in my bauble slot wasn´t working, i moved it out in my normal inventory, deactivated and activated it again but it only worked for just a few seconds.

#### Steps to reproduce:

1.Have the magnet in the bauble slot 
2.Logout
3.Update to version EnderIO-1.10.2-3.0.1.96_beta from version EnderIO-1.10.2-3.0.1.94_beta
4.Relog

- EnderIO: EnderIO-1.10.2-3.0.1.96_beta
- EnderCore: EnderCore-1.10.2-0.4.1.51-beta
- Minecraft: 1.7.10
- Forge: Don´t know

**Comment by CrazyPants** [comment]
Still cant reproduce. If this is still happening with the latest versions of baubles and eio please re-raise issue
