### ISSUE TITLE
Inventory Panel Remote not opening GUI

### ISSUE THREAD

**Issue by ShadowDrakken** [SleepyTrousers/EnderIO#3644]
#### Issue Description:
Inventory Panel Remotes are not opening their GUIs. You can set their target and they consume nutrients when attempting to open them, but the GUI never opens. This started in 3.0.1.94 but still persists as of 3.0.1.96

#### What happens:
Inventory Panel Remotes are not opening their GUIs. You can set their target and they consume nutrients when attempting to open them, but the GUI never opens. This started in 3.0.1.94 but still persists as of 3.0.1.96

#### What you expected to happen:
Inventory Panel Remote should open the Inventory Panel GUI when right-clicked

#### Steps to reproduce:

1. Setup a functional inventory panel and storage
2. Create inventory panel remote
3. Set remote target
4. Attempt to open inventory panel remote

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.94, 3.0.1.95, 3.0.1.96
- EnderCore: 0.4.1.51
- Minecraft: 1.10.2
- Forge: 2073 currently, but have used multiple versions since this issue started

#### Your most recent log file where the issue was present: 

NA, not a crash

**Comment by XxZajoZzO** [comment]
Confirmed with the new FTB Unstable version

**Comment by Utildayael** [comment]
FWIW, seems fine on the 1.10.2 version. I'm on 3.0.1.95 and just made an item panel system today including the remote. My panel and remote both work fine.

MC 1.10.2
EnderIO 3.0.1.95
Forge 2065

**Comment by DilemmaMDB** [comment]
I just started to set up my EnderIO inventory system last night and i ran into this exact issue. I tried both the advanced inventory remote and the ender inventory remote. Both of them allow me to set the target panel by sneak+r-clicking, but when attempting to open the remote's GUI, nutrients are consumed but the GUI never opens, making it impossible to access the inventory remotely.

EnderIO: 1.10.2-3.0.1.96_beta.jar
EnderCore: 1.10.2-0.4.1.51-beta.jar
Minecraft: 1.10.2
Forge: 12.18.1.2053

**Comment by HenryLoenwind** [comment]
Please recreate with a current version and post the log messages (just the errors "Unexpected failure to get tileentity...")

**Comment by XxZajoZzO** [comment]
[18:59:34] [Server thread/WARN] [EnderIO]: Unexpected failure to get tileentity at BlockPos{x=-19, y=10, z=377} in dimension 0 for the Inventory Panel Remote. Got: null
EnderIO: EnderIO-1.10.2-3.0.1.101_beta
EnderCore: EnderCore-1.10.2-0.4.1.53-beta

**Comment by HenryLoenwind** [comment]
Thx. Are these the correct coordinates of your Inventory Panel in the Overworld?

**Comment by XxZajoZzO** [comment]
[EnderIO]: Unexpected failure to get tileentity at BlockPos{x=-19, y=10, z=377} in dimension 0 for the Inventory Panel Remote. Got: null
Actual coordinates are -19 42 377
It is setting Y value wrong.
If I move the panel to Y=10 without rebinding it works.

**Comment by HenryLoenwind** [comment]
fixed in next build
