### ISSUE TITLE
[1.10.2]Power monitor not properly resetting redstone

### ISSUE THREAD

**Issue by CreeperShift** [SleepyTrousers/EnderIO#3645]
#### Issue Description:

I use a power monitor to switch on certain generators when my power drops below a certain %. It all works fine when I'm around that area but when I use rf away from my base, and come back it continues to emit a redstone signal until I break the wires.

Power is almost completely full:
http://i.imgur.com/dctJ9rp.png

Settings (they work flawlessly when I'm around):
http://i.imgur.com/bWC2rxQ.png

With the above settings & power the redstone should be off (I use a miner with a transciever, power starts to drain, so the generator is turned on by the power monitor) 
http://i.imgur.com/CmzrdDN.png

When I break the wire and place it again:
http://i.imgur.com/LIf0w07.png
#### Steps to reproduce:
1. Setup a power monitor to output a signal
2. Leave the area and make it trigger the power monitor
3. Come back, fill up the storage and watch the signal never turn off

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.10.2-3.0.1.96_beta
- EnderCore: 1.10.2-0.4.1.51_beta
- Minecraft: 1.10.2
- Forge: 2073

**Comment by JelmarG** [comment]
Is the area properly chunk loaded?

**Comment by iPencil** [comment]
Yes, it switches on correctly after I leave the base, it's chunkloaded via FTB Utils and is right above exutils 2 water mills which also chunkload themselves.

It has no trouble turning on after I leave the base, it just doesn't properly turn off.

**Comment by mindforger** [comment]
try alternative chunkloaders from railcraft or MFR if available, stay away from chickenchunks chunkloaders for testing, but you can give them a shot too afterwards, they seem to work better than FTB but are known to be funky with AE2 and IE

**Comment by iPencil** [comment]
Persistent bits chunkloader has the same effect.

The other chunkloaders arent available and chinkenchunks isnt installed (where did I mention them? )

**Comment by mindforger** [comment]
i was just guessing
but i recently read that FTBU ticketing is doing funny stuff and noticed an compareable behavior like chickenchunks chunkloaders (long known and reported but never really dealt with yet)

railcraft chunkloaders are pretty rock solid with chunkloading, but sometimes they do not load unloaded dimensions on serverstart properly
from MFR i just heared positive reply but did not work with them my self, investing powe rto get a chunkloader running is a bit cheaty for my opinion XD i switched the fuel for railcraft personal and world acnhors to apatite, easy to get in fairly large quantities and limited, not produceable ... perfect to prevent people from holiday chunkloading XD

**Comment by iPencil** [comment]
Did you not realize this is a 1.10.2 issue?

**Comment by mindforger** [comment]
whoops i missed the 1.10 fact but this sounds so familiar with my own experience in 1.7.10

**Comment by iPencil** [comment]
Worked fine in 1.7.10 for me

**Comment by bdudek** [comment]
the graphical monitor works fine it just the regular power monitor that seams to have this problem

**Comment by iPencil** [comment]
I'll have to test that, thanks

**Comment by bdudek** [comment]
i have to make a correction the graphical monitor sometimes works there have been a few cases were it will emit the redstone signal and a few times it failed to do so.

**Comment by xenoflot** [comment]
I verify that I have this problem too. I have tested with regular and graphical monitors. The redstone comes ON as expected but usually doesn't go OFF when expected. I've tried with networks using only one type of Capacitor (Vibrant) and networks with 2 or 3 kinds. It seems to happen with or without chunk loading (extrautils2). In both cases I have a mix of Vibrant and regular energy conduits.

**Comment by CrazyPants** [comment]
I think this might be the issue: 
"In both cases I have a mix of Vibrant and regular energy conduits."
The power monitor will only monitor a single power network, and different tier energy conduits form different networks. If you expected it to take into account things connected to both types of conduit it def. would not behave as you expected

**Comment by HenryLoenwind** [comment]
Good catch, Crazy. If there are multiple networks connected to the power monitor, the network that is monitored when being loaded may differ from the one being monitored when a new conduit is placed.

I think I'll add a check for multiple networks tonight.

**Comment by blix** [comment]
I can reproduce this in the DW20 1.10 pack version 1.1.2. Screenshots below.

Setup: power monitor connected one conduit away from a capacitor bank (middle tier 5M RF storage). Configured for on at 50% off at 95%.
Resdtone conduit sits on the same cable as the power telling the capacitor to turn on input.
I put a lamp on the monitor to see if it emits a signal.
Capacitor is set to output only on the conduit feeding the monitored network.
Note that power input to the system in on a separate line that does not touch the monitor.

1st way to reproduce.
Starting with the bank sitting at around 90% I attach and remove a 2nd conduit on the same network to the power monitor, when I remove it the monitor turns on even though the bank is still about 90% full. To fix it I go in and retype 95% in the off part of the monitor UI.

2nd way. I leave the system running, let it drain until it goes below 50% then go back up. Even when full the lamp on the monitor does not turn off. Again I can retype 95% in the off part of the  monitor UI and the lamp turns off.

I also noticed that the conduit power storage shows as 0 out of ~500k on the monitor, not sure if that is related, but the monitor is storing power so the conduits are full.

![2016-12-08_00 00 04](https://cloud.githubusercontent.com/assets/40290/21002195/613144c8-bcd9-11e6-85ac-65c5892d8bc2.png)
![2016-12-08_00 00 14](https://cloud.githubusercontent.com/assets/40290/21002202/65a13cb6-bcd9-11e6-9a3e-af917944e0e1.png)
![2016-12-08_00 00 18](https://cloud.githubusercontent.com/assets/40290/21002205/672fab44-bcd9-11e6-90de-a46abab6dad0.png)
![2016-12-08_00 00 29](https://cloud.githubusercontent.com/assets/40290/21002208/6a423ebe-bcd9-11e6-878c-32e979411a2a.png)

**Comment by blix** [comment]
One more quick update. I moved it to the input network and while this didn't change the behavior i was actually watching the monitor when the power went over 95%. For a split second the power went down, then started going up again. So it looks like it toggled off then back on within a second or so.

Also the conduit reading was correct when I checked it earlier on this test but then after the quick toggle it was reading 0 RF on the conduit again.

**Comment by smasher816** [comment]
I am having this same issue on 1.10 using only a single Capacitor Bank and Ender Energy Conduits. I am also having the 0 of XXXX RF for the conduits in the power monitor (the capacitor banks are showing correctly though). The monitor will emit redstone when it drops below the low threshold, but it will NOT turn off after the capacitor banks are above the higher threshold. This is preventing me from having my generators automatically controlled.

**Comment by mukunku** [comment]
I'm also having the same issue in the FTB Infinity Evolved pack
