### ISSUE TITLE
GT chainsaw with an EnderIO treefarm

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#3648]
#### Issue Description:

Gregtech Chainsaw placed as an 'Axe' in the EnderIO Treefarm causes the farm to operate, even when the chainsaw's charge has been depleted. Also the chainsaw's durability is not decreasing.

Would it be possible to add a config option to add different Axes separately at least? In same way as Hoes are registered, to not allow the usage of the GT Tools if the fix is too complex.

Bit info about GregTech Chainsaw: It stores its charge as an NBT, but also has durability bar as well stored as NBT. It has 4% chance to consume durability on use.
#### What you expected to happen:

I expected the farm to stop operating once the chainsaw's charge has been depleted.
#### Steps to reproduce:
1. Make any GregTech chainsaw
2. Put it into Farming Station in Axe saw
3. It will start depleting its electricity charge, but when it hits 0 EU, it still operates
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 2.3.0.427
- EnderCore: 0.2.0.36
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

**Comment by HenryLoenwind** [comment]
I hate unbreakable tools, there's just no way to detect them being "depleted" apart from putting special handling for each and every one in.

**Comment by Vexatos** [comment]
In case special handling is being added, [this maybe useful](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/gregtech/EventHandlerGregTech.scala#L14-L22).
