### ISSUE TITLE
Feature request: RandomThings compat

### ISSUE THREAD

**Issue by NezcalSpindrake** [SleepyTrousers/EnderIO#3651]
Would it be possible to add 'magic damage' to the Ender, as an upgrade?
'Magic damage' is the only way to kill Spirits, which initially must be killed with splash potions of harming, and later the Spectre Sword(Which could be the item to upgrade with, or perhaps just a spectre ingot?).
It'd mostly just be a quality of life thing, not having to switch between weapons when farming for spirits.

**Comment by CrazyPants** [comment]
Request noted. Thanks
