### ISSUE TITLE
[Request] Item Panel JEI Integration Enhancement

### ISSUE THREAD

**Issue by Utildayael** [SleepyTrousers/EnderIO#3652]
#### Issue Description:
Ability to use @modname in Item Panel to show all items from mod.

#### What happens:
In AE2, Refined Storage and various other storage management mods you can type @modname and have it show items in that mod as an ad-hoc mod filter. This is also true in NEI and JEI which I believe had it first so I'm not sure if other mods tie IN to NEI/JEI or just made similar functionality. For example, I could type @chisel to show all Chisel items or even a partial name like @ender to show Ender IO [and any other Ender * mods] items. This is super handy when trying to find an item that you can't remember name for but know what mod it was in or if you just want to see like "show me all my EnderIO items" ...

While I realize you can do this with a  mod filter currently, that is very cumbersome and you have to lug around all the filters to swap out in your panel. Not saying to take the filter ability away as there are some very good use cases for it, but adding ability to just @modname in the search field would be very handy.

#### What you expected to happen:
See above

#### Steps to reproduce:
n/a - feature request

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-0.4.1.51
- EnderCore: 1.10.2-0.4.1.51
- Minecraft: 1.10.2
- Forge: 2065

#### Your most recent log file where the issue was present: 

n/a - feature request

Thanks :)

**Comment by MatthiasMann** [comment]
There is already mod filter support which uses @modname:
https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/machine/invpanel/client/ItemFilter.java#L24

Is that not working?

**Comment by Lukas45** [comment]
You mean like that right? Because it seems to be working just fine, both in JEI (1.10.2), NEI (1.7.10) and Refined Storage (0.9.2)
![58984524e618d8e7893e3718c9b7352b 1](https://cloud.githubusercontent.com/assets/4707702/18049706/20cf95ee-6dea-11e6-883e-b2f81666e326.png)
EnderIO 3.0.1.96
EnderCore 0.4.1.51

**Comment by HenryLoenwind** [comment]
No, it's about using that search string in the inventory panel, and yes, it's broken.

**Comment by Utildayael** [comment]
Yes that. Exactly. Thank you for confirming its not working as intended.

**Comment by HenryLoenwind** [comment]
Yeah, I was aware that it didn't work, I just assumed it being a missing feature. There are so many new things in 1.10, most of them half-finished...

**Comment by Utildayael** [comment]
Ha. Is this a JEI issue or a EnderIO issue?

1.10 mods right now are a total mixed bag as a whole. Fully agree.

**Comment by HenryLoenwind** [comment]
This has nothing to do with JEI at all
