### ISSUE TITLE
Missing textures on Turkish OS language

### ISSUE THREAD

**Issue by Battle-Bee** [SleepyTrousers/EnderIO#3653]
#### Issue Description:

This is more of a PSA rather than a bug report. If your PC's language is set to Turkish, some items from the mod will show up as missing, magenta-black textures. 
http://i.imgur.com/2YULmob.png

I've been recommended to contact mod authors whose mods are having this issue. Here's a Reddit post that explains this in detail:
https://www.reddit.com/r/feedthebeast/comments/3gdxk1/psa_for_developers_turkish_locale_breaks_stuff/

**Comment by HenryLoenwind** [comment]
I checked our code and found the problem in the fluid textures and the TelePad blockstates. However, you screenshot shows something else. Could you please post the "missing textures" messages from your logfile?

**Comment by HenryLoenwind** [comment]
Ok, I found the time to do some more in-depth analysis. Ender IO actually is clean, it's Forge and Vanilla that are full of toLowercase() without locales. Those will mess up all block models for us. It's a wonder that some textures do show up...
