### ISSUE TITLE
[1.10.2 Suggestion] Microblocks support

### ISSUE THREAD

**Issue by Lukas45** [SleepyTrousers/EnderIO#3654]
or should it be called MCMultipart API support? I don't know.
#### Issue Description:
After 1.8, Chisels & Bits came around, a mod that works a lot like Forge Microblocks, but with more detail available.
Is there chance to get support to use mods like Chisels & Bits around EnderIO cables?
I know there's already cable facades, but it's not the same. Cable Facades covers the entire block, rather than just the cable, which doesn't allow to nicely cover up cables that stick 1 block out from the rest of the structure, like here:
![What I want covered](https://i.gyazo.com/e644060cd26619244e91267fb1bde041.png)
Putting a solid block around the cables sticking out would look really silly, and ugly for that matter.

#### What happens:
Currently no support microblocks, so microblocks/bits/covers etc will have to go on the block next to it, rather in the cable block.

#### What you ~~expected~~ want to happen:
To be able to do like this, as I have done with Refined Storage and Mekanism cables:
![](https://i.gyazo.com/d24d35a36275a7e44bc5f55fe7c7827b.png)

#### Steps to reproduce:

1. Place a Mekanism wire
2. Start to put Chisels bits around it, and see how compact it can cover a cable
3. Try with an EnderIO cable
4. ???
5. Not happening :(

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.96_beta
- EnderCore: 0.4.1.51-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2064

#### Your most recent log file where the issue was present: 
*Suggestion post*

If this is already possible, then I apologize for clutter topic.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
