### ISSUE TITLE
Powered Spawner spawning mobs, but they instantly disappear

### ISSUE THREAD

**Issue by DilemmaMDB** [SleepyTrousers/EnderIO#3659]
#### Issue Description:
I'm playing Survival (with cheats enabled) using Curse Forge for Mac with Forge version 12.18.1.2053 and EnderIO-1.10.2-3.0.1.96_beta.jar
I found a Blaze spawner and converted it to a Wither Skeleton spawner, then combined the spawner with a powered spawner in an anvil. I excavated a room 11x11x7 and ran conduit down so the spawner is 3 blocks off the ground, giving a 1 block clearance all the way around to account for the spawner's range.
When I turn the spawner on, it charges and attempts to spawn. For a split second i can see the Wither Skeletons appear, then they instantly evaporate as though killed, but they don't drop anything, nor can they attack or be hit. I have also tried a Blaze spawner with the same results. These are legitimately obtained spawners, etc.

#### Steps to reproduce:

1. Obtain any spawner
2. Collect mob in Soul Vial
3. Combine Soul (wither skeleton) & Broken spawner
4. Combine new spawner (wither skeleton) and powered spawner in anvil
5. Power up new powered spawner (wither skeleton)
6. Watch as spawned wither skeletons go *POOF!*
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.96_beta.jar
- EnderCore: 1.10.2-0.4.1.51-beta.jar
- Minecraft: 1.10.2
- Forge: 12.18.1.2053

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Are you in peaceful mode?

**Comment by DilemmaMDB** [comment]
No, i wasn't. But I found that it was in "easy" mode. I guess I have my son to thank for that! I switched it back over to "Normal" and it immediately began spawning normally. Appreciate the input!
