### ISSUE TITLE
Inventory panel stops returning if a drawer is full of the item it tries to return and does not keep filling new drawer slots

### ISSUE THREAD

**Issue by GAJinWoo** [SleepyTrousers/EnderIO#3660]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
If you put together a working inventory panel + 2x2 storagedrawer setup and try to return for example 10 stacks of cobblestone it will return 8 stacks and put in it to a drawer slot. But after that it stops and does not continue to fill up the remaining slots.

Here is a video I put together to better show what happens:  https://www.youtube.com/watch?v=aAS3oeIvGn8
 

#### What you expected to happen:

In previous games the inventory panel would continue to fill up available drawerslot in the case that one slot would become full

#### Steps to reproduce:

1. Set up inventory panel + 2x2 storagedrawer setup 
2. Return 10 stacks of cobblestone
3. Notice how 8 stacks will be returned but nothing more, even though there are 3 slots in the drawer remaining
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.428_beta
- EnderCore: 1.7.10-0.2.0.36_beta
- Minecraft: 1.7.10
- Forge: 1614

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by GAJinWoo** [comment]
Not sure where the problem lies so I reported both here and to storagedrawers

**Comment by MatthiasMann** [comment]
The inventory panel itself it not involved in returning items - it is just like a chest from which the conduits extract.

Could you do a test and put a vanilla chest on your conduit network and let the conduit extract from it and insert into the drawer controller?

**Comment by GAJinWoo** [comment]
It tested what you suggested. If I use a hopper it works but item conduit still doesn't work

**Comment by GAJinWoo** [comment]
Found where the problem lies. It appears that spruce 2x2 drawers are the problem. Using 1x2 drawers or any other drawer works fine

**Comment by Undeadbear** [comment]
Is the issue with the spruce 2x2 drawers when I can connect a chest and use it to input items?

Items aren't inputted from the inventory panel,  but if I have a chest connected to the same item conduit with the same settings as the inventory panel the items are pulled from the chest, to the drawer controller this is strange :S
