### ISSUE TITLE
Crash on Start !!

### ISSUE THREAD

**Issue by khaduy15** [SleepyTrousers/EnderIO#3665]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

When i started my old world. I crash at the start. I don't know what happened. 
But i created a new world. Nothing happened.

Report file : 
""Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.1.0 from excompressum-mc1.7.10-1.1.143.jar).
                    It is a supported version, but that difference may lead to problems.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.1.0 from excompressum-mc1.7.10-1.1.143.jar).
                    It is a supported version, but that difference may lead to problems.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.""

#### What you expected to happen:
Please, tell me how to save my world.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.7.10_2.3.0.428_beta
- EnderCore:1.7.10_0.2.0.36_beta
- Minecraft: 1.7.10
- Forge: releae forge-10.13.4.1614

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://drive.google.com/file/d/0B2jjHSitThJWeTJaU3lVMzhhN2c/view?usp=sharing

**Comment by HenryLoenwind** [comment]
got o wyldmods.simpleachievements
