### ISSUE TITLE
Corrupts world 1.7.10 Redstone Conduit

### ISSUE THREAD

**Issue by allabovethis** [SleepyTrousers/EnderIO#3666]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Corrupts world after laying a 128m x 116m square of insulated redstone conduit for fence lighting. Used quartz brick hardened cable facade. no other structures built in new world. The regular redstone cable was very laggy after very long circle runs for lighting road bricks inside the  128m x 116m area. 

After the square run of insulated redstone conduit logged out and then logged in. Loads one chunk and disconnects and the server logs show the lag error only after trying to log in. Reboot didnt help. Load a backup before the square. Works perfect. tried on multiple PCs. No change. 

 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 132262ms behind, skipping 2645 tick(s)

#### What you expected to happen:
Be able to lay very long runs without lag or world corruption. 

#### Steps to reproduce:

1.Lay lots of normal or insulated redstone conduit
2.log out 
3.log back in. 

[Netty Client IO #2/ERROR]: NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException

[Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 132262ms behind, skipping 2645 tick(s)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.2.8.381 or EnderIO - 1.10.2-3.0.1.101_beta
- EnderCore: EnderCore-1.7.10-0.2.0.38_beta
- Minecraft: 1.7.10
- Forge: 1.7.10 - 10.13.4.1558

#### Your most recent log file where the issue was present: 

Logs show no errors other than [Netty Client IO #2/ERROR]: NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException
 after trying to log back in multiple times with no luck. Connection failed. restore backup. 

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment]
The version numbers you mentioned make no sense.

If you are really on 1.7.10 then EnderIO 2.2.8 is very old and you should really upgrade.
But the 1.10.2 version of EnderIO you mentioned is not compatible with the other versions you mentioned.
