### ISSUE TITLE
Painting with quite clear 

### ISSUE THREAD

**Issue by Dijkstra1** [SleepyTrousers/EnderIO#3668]
It my understanding that if paint something with quite clear glass it will be invisible, so to hide my pipe i though, clear conduit facade paint with quite clear would yield invisible conduits, well i can not see the conduits but i have instead if have line of quite clear glass. I remember be able to paint things invisible in 1.7.1.0 has this now been removes in 1.10.2

**Comment by HenryLoenwind** [comment]
The only things that go completely invisible when painted with QCG are the pressure plates. For everything else you'd need to find an invisible block as paint source.

**Comment by Dijkstra1** [comment]
You would not happen to know said invisible block, or can one added to EnderIO, is unplaceable  just used for make stuff invisible

**Comment by mindforger** [comment]
please do not remove the visibility of conduits through transparent blocks, i really like this feature! 
i don't get why people try to make things to make invisible that exists for purpose ... how odd does a pipe look that just ends at an glass block and magically continues on the other side!?

**Comment by HenryLoenwind** [comment]
@mindforger you're quite off-topic here...

**Comment by HenryLoenwind** [comment]
@Dijkstra1 Not at the moment, but once Ender IO Addons is ported to 1.10 it will have an invisible block.

**Comment by Dijkstra1** [comment]
@HenryLoenwind, thanks do with EAT on Ender IO Addons 1.10, guess util then I will come with some way explaining why glass on top of my machines.

**Comment by mindforger** [comment]
>@mindforger you're quite off-topic here...
i don't think so:
what he described was the trick to hide a cable invisible inside glass like it was before the mayor upgrade in the late 1.7.10 
i really liked that change where the conduits became visibe inside the glass, i just don't want it to be gone again!

**Comment by HenryLoenwind** [comment]
No, this as about not displaying the facade, not the conduits. For the conduits we already have two different kinds of facades and no plans to remove them again.

**Comment by mindforger** [comment]
okay, **totally** misunderstood then, sorry

**Comment by HenryLoenwind** [comment]
yeah, happens. not a problem
