### ISSUE TITLE
Alloy smelter not working

### ISSUE THREAD

**Issue by Radi0activegosze** [SleepyTrousers/EnderIO#3669]
#### Issue Description:
I'm playing on a server consisting of three people but when we try to use the alloy smelter it does not work. It can be used as a furnace but it does not create alloy ingots.

#### What happens:
The alloy smelter puts the items that you tried to use back in your inventory. 

#### What you expected to happen:
That the alloy smelter would create a new ingot.

#### Steps to reproduce:

1. Put ex. gold ingot and soul sand in the alloy smelter. 
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.96_beta
- EnderCore: 1.10.2-0.4.1.51-beta
- Minecraft: 1.10.2
- Forge: 2075

#### Your most recent log file where the issue was present: 

No crash log. Happy to provide what I can if it helps to resolve the issue.

**Comment by erindalc** [comment]
@Radi0activegosze Whatever output log your game did (fml_latest or something along those lines) should be posted.

**Comment by CrazyPants** [comment]
The start up log should print out any errors with recipes.
Also, please updated the latest version and report back on wether the issue still occurs
