### ISSUE TITLE
Inventory Sorting bug: everything goes into 1 chest

### ISSUE THREAD

**Issue by Falkan432** [SleepyTrousers/EnderIO#3670]
#### Issue Description:
Note: Using the Direwolf20 modpack

#### What happens: im working on some basic sorting, i have 3 chests with snapshot filters hooked up to a Sagmill, and an alloy smelter. all of this is working fine. then i added another unfiltered chest, intending it to be the place all the unsorted items go.
What instead happens is that the unfiltered chest attempts to collect everything from the filtered chests, this happens no matter what i do to the priorities or other options.

It also gets stuck moving items, as in a stack of wheat in one of the affected chests keeps jumping back and forth between 32 and 36 items...

#### Steps to reproduce:

1. 3 chests with snapshot filters, set to in/out, with extraction always active, and priority 1 
2. 1 chest, without filter, set to in/out, with extraction always active, and the priority doesnt seem to matter, i have the bug no matter what priority i use

...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.422_beta.jar
- EnderCore: 0.2.0.31_beta.jar
- Minecraft: 1.7.10
- Forge: -

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
works exactly as you configured it
