### ISSUE TITLE
Automatically using secondary hand when accessing gui's conduit

### ISSUE THREAD

**Issue by Zekralyx** [SleepyTrousers/EnderIO#3671]
#### Issue Description:
Undesired behavior when accessing gui's conduits (energy or item conduit) and you have an item/block that can be used/place in your secondary hand and no item on your main hand.

#### What happens:
The character automatically will interact with the world using the item in its secondary hand, right after accessing gui's conduit.

#### What you expected to happen:
The character must do nothing with its secondary hand when accessing a gui, it should just open it. 

#### Steps to reproduce:

1. Create a new World (with cheats enabled)
2. Place an energy conduit connected to a EnderIO machine.
3. Put some food on your secondary hand
4. Write this command: `/effect @p minecraft:hunger 3 100`
5. Access the conduit configuration through black box atached to the block with nothing in your main hand.
6. After the GUI shows up, the player will automatically eat the food.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.101 beta
- EnderCore: 0.4.1.56 beta
- Minecraft: 1.10.2
- Forge:12.18.1.2075

#### Your most recent log file where the issue was present: 

No log for this issue since the debug log doesn't show anything related to this.

**Comment by HenryLoenwind** [comment]
known issue, happens for the main hand, too
