### ISSUE TITLE
Suggestion : Allow Travel Anchor to function with Slab on top.

### ISSUE THREAD

**Issue by Chad077** [SleepyTrousers/EnderIO#3672]
It would be of tremendous value if you're able to use a travel anchor with a vanilla slab on top to stop spawning where light level is not a solution.

**Comment by HenryLoenwind** [comment]
The travel anchor is not a solid block, so there should be no mobs spawning on it...

**Comment by Chad077** [comment]
We've added EnderIO to the FTB Departed pack and I created a square 'test' area above ground consisting of 64 travel anchors. I've been monitoring that area for more than a two week and yesterday I discovered an aggressive mob on this test area. I'll cheat in some more anchors and increase the test area and will get back with my findings.

**Comment by Chad077** [comment]
So I decided to go nuts with the anchors and within 5 minutes I had a zombie and then a creeper spawn.

![2016-09-08_12 59 21](https://cloud.githubusercontent.com/assets/5823585/18333556/40d5b24c-75c4-11e6-90a4-8e6fc4276411.png)

**Comment by Chad077** [comment]
Tested tonight on the DW20 1.7 pack with the original and updated beta jars and the results were the same. 
forge-10.13.4.1558
EnderIO-1.7.10-2.3.0.429_beta
EnderCore-1.7.10-0.2.0.38_beta
