### ISSUE TITLE
1.10.2 - Reliquary's Tome of Alkahestry gets deleted in crafter

### ISSUE THREAD

**Issue by P3pp3rF1y** [SleepyTrousers/EnderIO#3675]
When using Crafter to either charge or craft items with Tome of Alkahestry, the tome gets deleted after the first crafting. 

In the past it just wouldn't use its charge and allow for duping items for free so I made a change to it so that it doesn't return itself in getContainerItem.

The reason that the crafting doesn't work is logic that's included in getRemainingItems method of Tome's recipes (new method to IRecipe with 1.8.9), that charges/uses tome's charge. EnderIO crafter doesn't have support for that so I am logging this here. Not a critical to me, but there are other mods using getRemainingItems as well (like Chisel and Bits) so you may want to add support for it. 
Forestry and RFTools have added support so you may use those as a reference.

#### Steps to reproduce:

1. Make a recipe with uncharged Tome of Alkahestry and redstone (both blocks and dust work) in Crafter
2. Once set and items are supplied the tome disappears

**Comment by CrazyPants** [comment]
Thanks :)

**Comment by scollenburg** [comment]
Hey guys -- I think this may have done a drive-by fix if the issue I was having automating Magical Crops & their Infusion Stones. When the stone was used, the stone would loose durability & the recipe would stop matching. Can I get a alpha build with this fix in it?

Thanks,
Shawn
