### ISSUE TITLE
Ceramics mod breaks JEI integration (due to bucket?)

### ISSUE THREAD

**Issue by bondgb** [SleepyTrousers/EnderIO#3677]
#### Issue Description:
I don't know who is to blame for this bug but I'm posting it on Ceramic's and EnderIO's issue trackers. Or is it JEI?

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.104_beta
- EnderCore: 0.4.1.54-beta
- Minecraft: 1.10
- Forge: 2076

#### Your most recent log file where the issue was present: 

https://gist.github.com/bondgb/974e5fa08131ac29613137fa04c27074

You can find the offending error at line 24034

**Comment by HenryLoenwind** [comment]
90% sure that's a bug in that other mod. Would you be so nice as to link to the other ticket? Thx.

**Comment by bondgb** [comment]
Sorry, forgot to add it - https://github.com/KnightMiner/Ceramics/issues/2

**Comment by KnightMiner** [comment]
Yeah, my fault. Missing a check to see if the liquid has a block form

**Comment by HenryLoenwind** [comment]
closing this ticket as confirmed and fixed in Ceramics. Thx fox the fast response, KnightMiner.
