### ISSUE TITLE
Suggestion: Solar upgrade should charge tools

### ISSUE THREAD

**Issue by Plurp13** [SleepyTrousers/EnderIO#3678]
Not much to elaborate there, and sorry if either that's already supposed to happen/in the works/whatever, or if this is the wrong place for suggestions. I just thought it would be cool if the solar upgrade to the dark helmet would charge at least dark tools as well as the armor. In a similar vein if there was some sort of back up battery option that holds large amounts of RF (i.e. like the flux capacitors from thermal expansion) that would be just as cool, and very helpful for long mining trips away from the sun. Maybe there is something like that and I've just missed it though, who knows.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by bookerthegeek** [comment]
@HenryLoenwind is thus a publicly viewable list?  Please?

**Comment by HenryLoenwind** [comment]
sure: https://github.com/SleepyTrousers/EnderIO/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3ASuggestion%20is%3Aclosed%20-label%3A%22Code%20Complete%22%20 and https://github.com/SleepyTrousers/EnderIO/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20-label%3A%22Code%20Complete%22%20label%3Aenhancement%20

**Comment by Hund** [comment]
Oh, so that's a feature and not a bug? I would like to see this as well since the charge the tools can hold is not very large and if you only have EnderIO as the only tech mod in your pack, you don't have any options to charge your tools when you're not home.
