### ISSUE TITLE
rash-reports

### ISSUE THREAD

**Issue by xaioai520** [SleepyTrousers/EnderIO#3680]
#### Issue Description:
CoFHCore: -[1.7.10]3.1.3-327
	ThermalFoundation: -[1.7.10]1.2.5-115
	ThermalExpansion: -[1.7.10]4.1.4-247
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	RedstoneArsenal: -[1.7.10]1.1.2-92
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.0-171
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from forestry_1.7.10-4.2.15.63.jar).
                    It is a supported version, but that difference may lead to problems.
                  * Our API got loaded from 安德EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                  * Our API got loaded from 安德EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                  * Our API got loaded from 安德EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                  * Our API got loaded from 安德EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:ON, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[02:48:45] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:354]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Chiba\AppData\Roaming\.minecraft\crash-reports\crash-2016-09-11_02.48.44-server.txt

After playing for some time crash
Shall be re-opened after a normal map

#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.36_beta
- Minecraft: 1.7.10
- Forge:  Forge10.13.4.1614-1.7.10

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
That is not a complete crash log

**Comment by xaioai520** [comment]
https://github.com/xaioai520/1134/wiki

**Comment by HenryLoenwind** [comment]
report this to "darkknight.jewelrycraft"

**Comment by xaioai520** [comment]
thanks
