### ISSUE TITLE
[1.10.2] [3.0.1.104] Painting a travel anchor as a sticky piston is a poor idea

### ISSUE THREAD

**Issue by Alaberti** [SleepyTrousers/EnderIO#3682]
#### Issue Description:
Crashes dedicated server when attempting to paint a travel anchor as a sticky piston. To be fair, it seemed like a good idea at the time.

Crash report: http://pastebin.com/TSt7TCaU

#### What happens:
Server crashes. Boom, headshot.

#### What you expected to happen:
A sticky-piston looking travel anchor or the inability to paint tile entities as other tile entities I guess.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.104
- EnderCore: 0.4.1.54
- Minecraft: 1.10.2
- Forge: 2075

**Comment by HenryLoenwind** [comment]
Vanilla bug.

Seems we'll have to add extra code for the piston here. :(
