### ISSUE TITLE
[Request] Bundled cable support OpenComputers

### ISSUE THREAD

**Issue by ShadowDrakken** [SleepyTrousers/EnderIO#3684]
Not sure what happened to this, I'm sure it was a thing in older versions, but I'd love to see the return of OpenComputers bundled cable support on the Insulated Redstone Conduits.

**Comment by HenryLoenwind** [comment]
What happened was the port to 1.8.9 that we started early February and which (with in updates to 1.9, 1.9.4 and 1.10.2) still isn't finished...

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
