### ISSUE TITLE
EnderIO/Travel Anchor Bugs

### ISSUE THREAD

**Issue by dovahkiin4991** [SleepyTrousers/EnderIO#3686]
#### Issue Description:

FTB Unstable 4.7.4 MC Version 1.10.2 EnderIO Version 1.10.2-3.0.1.95_beta EnderCore-1.10.2-0.4.1.51_beta
Lag Upon opening EnderIO
## Extremly Blurred EnderIO

Remote connections accessed from Staff Of Traveling Flicker with EnderIO/Travel Anchor
## Upon opening the EnderIO block, my game begins to get extremely laggy(Guessing around 3-4 fps, where as I get 50-70 fps normal). The EnderIO is also extremely blurred(as expected) and I recommend making it less.

Upon standing still and not moving cursor the connection flickers on and off constantly, never settling.
## Small amount more of lag, and as stated above, less blurred.

Stable connection while looking in a general direction
#### Steps to reproduce:
1. Open EnderIO
## 2. Watch FPS
1. Look at Travel Anchor/EnderIO with Staff Of Traveling
2. Observe 
   #### Your most recent log file where the issue was present: 
   http://pastebin.com/fxHaXW6n

**Comment by dovahkiin4991** [comment]
Upon further investigation the flickering has stoped although the lag is still occurent with the EnderIO

**Comment by CrazyPants** [comment]
The EnderIO block has been disabled for now, and is no longer craftable.
Hopefully we will find the time to fix it, but it is not planned 'soon'.

**Comment by dovahkiin4991** [comment]
Could I recommend making it able to access inventorys, such as other machines. I have not been able to get the to work in previous versions as well.

**Comment by HenryLoenwind** [comment]
That functionality has been removed from Forge, I'd recommend to complain there.

**Comment by HenryLoenwind** [comment]
closing this ticket, we are aware that the Ender IO is disabled and not fully ported to 1.8.9+
