### ISSUE TITLE
Location Printout Causing Crash

### ISSUE THREAD

**Issue by dovahkiin4991** [SleepyTrousers/EnderIO#3687]
#### Issue Description:

Clicking with location printout causes crash
#### What happens:

Crash/Instance Closes
#### What you expected to happen:

Not Crash( Never used a location printout before)
#### Steps to reproduce:

1.Click with location printout
---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO:1.10.2-3.0.1.95_beta
- EnderCore:1.10.2-0.4.1.51_beta
- Minecraft: 1.10.2
- Forge: Forge ???????
  #### Your most recent log file where the issue was present: 
  http://pastebin.com/qRU5nTjx

**Comment by CrazyPants** [comment]
We need the log with the crash report in it.

**Comment by dovahkiin4991** [comment]
http://pastebin.com/t7GxnuLU

**Comment by CrazyPants** [comment]
This doesnt show a crash at all, just a normal start up.

**Comment by AnrDaemon** [comment]
Use gist for logs. pastebin truncates the input.

**Comment by HenryLoenwind** [comment]
also, this is now really outdated. Does this crash still happen with a current version?

**Comment by dovahkiin4991** [comment]
ill check but this is when the location printout has no set target, and pointed out in the distance, and this is only do able on creative ill check as soon as I can get a but more time, been busy with school work, and such
