### ISSUE TITLE
Advanced Item Filter for Bee keeping

### ISSUE THREAD

**Issue by Valdee** [SleepyTrousers/EnderIO#3688]
Hi, i would like to ask, if you could add a setting to Advanced item filter for bee keeping.
At the moment, there is no decent automation for bee keeping for newest verssions of MC, like 1.10.2.
I would like to see something like Logistic Pipes item filter, where you could pick different genetic traits.
Some bees have a huge area efect, better than RF Tools machines, giving bonusses or even constant XP gain. 
Your transport system is the bestest i played with so far, but i truly believe it is missing this filtering options for Forestry. 
Thanks

**Comment by HenryLoenwind** [comment]
Personally, I feel it'd be a better idea for someone (who is actually playing with bees themselves) to implement this as standalone bee-sorter machine. The integration with dozens of mods was one of the things that made porting Ender IO to 1.10 so hard and lengthy.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
