### ISSUE TITLE
[1.10.2] World Crash using Electrical Advantage Pump With EIO Pressurised Fluid Conduit

### ISSUE THREAD

**Issue by Morpheus1101** [SleepyTrousers/EnderIO#3694]
![mmd crash](https://cloud.githubusercontent.com/assets/10524952/18509596/af79b1f6-7abc-11e6-942c-715c13ef6075.png)

The Above pic shows the exact setup i was using to make the crash happen. Essentially setting it up to transfer lava using the Electrical Adantage Pump to send the lava through fluid conduit into Dimensional trasciever hooked up to a Mk2 lava Generator in the overworld which is connected to a Dimensional trsciever set to recieve the lava.  I tested this same setup transfering water and it only crashed using Pressurised Fluid Conduits, normal Fluid Conduits work fine.
Crash Report @ http://pastebin.com/ueWBUBJy

**Comment by HenryLoenwind** [comment]
Th crashing code is in Electrical Advantage---my guess is that the Electric Pump doesn't like to be asked for liquid when it's empty.
