### ISSUE TITLE
EnderIO wiki expired?

### ISSUE THREAD

**Issue by xchoo** [SleepyTrousers/EnderIO#3695]
#### Issue Description:
EnderIO wiki domain has expired?

#### What happens:
When I go to wiki.enderio.com I get the message "This Domain Name Has Expired - Renewal Instructions."

#### What you expected to happen:
The wiki page to load. 😄 

#### Steps to reproduce:

1. Open browswer
2. Go to http://wiki.enderio.com
3. See error

**Comment by HenryLoenwind** [comment]
just kidding ;)

**Comment by xchoo** [comment]
Huzzah! 😄
