### ISSUE TITLE
Can't disable Elytra on dark steel armor

### ISSUE THREAD

**Issue by mrtomwolf** [SleepyTrousers/EnderIO#3696]
Works fine with gliders, I can enable and disable those. With Elytra they stay on no matter what. A bit annoying when you try to fly with angel wings and you have no choice but to enter elytra mode when you want to do a quick landing ;)

Luv EnderIO <3

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.107
- EnderCore: 0.4.1.54
- Minecraft: 1.10.2
- Forge: 12.18.1.2088

**Comment by HenryLoenwind** [comment]
The Elytra-Upgrade uses the vanilla mechanics

**Comment by mrtomwolf** [comment]
Was confused since the controll options said enable/disable glider/elytra. When I press the button for disabling it says "Enabled Elytra".

I figured it was a bug since it seemed like I should be able to disable them. Guess I have to stick to gliders.

**Comment by HenryLoenwind** [comment]
That is anoverride for disabling when it's stuck and for people who have problems with the "jump while falling" like me. ..
