### ISSUE TITLE
Applied Energistics 2 isn't comaptible?

### ISSUE THREAD

**Issue by Camospyro** [SleepyTrousers/EnderIO#3699]
Please help i'm having an issue (Here's the crash log http://pastebin.com/Kvku6R5u ) that i cant fix i could uninstall either mod and fix it but that deletes all my items and an ME system or 25,000,000,000 RF stored in a massive capacitor bank and i don't want either of those to happen, any way to fix this issue would be greatly appreciated. Also i would have to leave one of the two uninstalled if i uninstalled.
 EnderIO-1.7.10-2.3.0.423_beta.jar is the version of Ender IO

**Comment by Camospyro** [comment]
BTW EnderIO-1.7.10-2.3.0.423_beta.jar is the version of Ender IO

**Comment by Camospyro** [comment]
okay so i have fixed this but now im having this issue with optifine

**Comment by tterrag1098** [comment]
The crash looks like world corruption, and it doesn't mention EIO anywhere. Why did you post this here?

**Comment by Camospyro** [comment]
EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and my not work with newer version.

definitley has eio in it
