### ISSUE TITLE
[The One Probe integration] Capacitor Bank multiblocks read as separate blocks

### ISSUE THREAD

**Issue by TWJedi** [SleepyTrousers/EnderIO#3700]
I reported this issue to Mcjty, but he referred me to you.

Using The One Probe mod, when viewing Capacitor Bank multiblocks, the RF displayed is for each block rather than the whole bank. For example, a 10 million capacity Bank (2x regular Capacitor Banks) with 3 million RF stored reads as 2 blocks with 1.5 million RF each.

Additionally as a request, could you add functionality so that The One Probe also displays RF I/O rates on Capacitor Banks?

Thanks y'all for your hard work.

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 3.0.1.107_beta
- EnderCore: 0.4.1.55-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2088
- The One Probe: 1.1.1

**Comment by Susjin** [comment]
That thing is happening with RF Module of RFTools screens
