### ISSUE TITLE
Bug with painted (cobblestone) slabs

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#3701]
Every slab you see there is a painted cobblestone slab with  Reinforced Undead Planks.

Reinforced Undead Planks: https://i.imgur.com/D3HIU72.png
Painted Slabs: https://i.imgur.com/g11d59w.png

Every time I teleport, the slabs go "low".

Bug before: https://i.imgur.com/z4Ci8ki.jpg
Bug after: https://i.imgur.com/rVpDLni.jpg

I have to right-click every slab to correct them.
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: EnderIO-1.10.2-3.0.1.107_beta.jar
- EnderCore: EnderCore-1.10.2-0.4.1.55-beta.jar
- Minecraft: 1.10.2
- Forge: 1.10.2-forge1.10.2-12.18.1.2089

**Comment by PONYRYDE** [comment]
Have the same problem.

http://imgur.com/a/IZ1BA

In single player exit and relog to reproduce.

Tested with:

- EnderIO-1.10.2-3.0.1.120_beta.jar
- EnderCore-1.10.2-0.4.1.56-beta.jar
- Forge 1.10.2-forge1.10.2-12.18.1.2113

**Comment by HenryLoenwind** [comment]
Which mod adds the right-click-ability to slabs?

**Comment by PONYRYDE** [comment]
O_o  This is with only EnderIO installed but that sounds like a neat feature.
