### ISSUE TITLE
Ability to use redstone to control inputs.

### ISSUE THREAD

**Issue by yutang13** [SleepyTrousers/EnderIO#3703]
We can use redstone to control extractions but not insertions. As it is it can be very trick (or just impossible) to make certain systems without being able to control whether a conduit is inputting or not.

**Example case:**

Currently:
You have a large storage drawers system and you are always extracting from the controller to fill the inventory of some machines dotted around. You then decide you only want to insert items into one of the machines when you don't have enough of a product. You can use a inventory panel sensor to detect when to output a redstone signal but how do you stop items going in without stopping any items from coming out the drawer controller?

With the change:
You hook up a item level checker of some sort and run the redstone over to the machine where it stops the machine and stops items being inserted.

The **only** workaround I can think of is to fill a hopper which goes into the machine. But that is both ugly and needlessly large. 
Even if this functionality was added with an item conduit upgrade I would be happy.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
