### ISSUE TITLE
Issue with Fluid Pipes in 1.10.2

### ISSUE THREAD

**Issue by kaosjr** [SleepyTrousers/EnderIO#3704]
#### Issue Description:

While using EnderIO Fluid Conduits in 1.10.2, the game lags immensely while fluid is flowing through.
#### What happens:

[Link](https://youtu.be/6KmKufTYt2I)
That's a perfect example of it happening. It is not the heat generators from Mekanism, which were doing fine with Extra Utils 2 transfer pipes supplying them. The drum should be absolutely fine.
#### What you expected to happen:

The game NOT to lag immensely.
#### Steps to reproduce:
1. Place a small amount of enderIO fluid pipes.
2. Using a wrench, set a pipe to extract a fluid from a fluid source.
3. Lag.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.10.2-3.0.1.105_beta
- EnderCore: 1.10.2-0.4.1.54-beta
- Minecraft: 1.7.10
- Forge: 12.18.1.2076
#### Your most recent log file where the issue was present:

[Log](http://pastebin.com/xsQui7RD)

**Comment by CrazyPants** [comment]
A short term solution would be to use ender fluid conduits or cover the conduits in facades.

**Comment by kaosjr** [comment]
I figured out something that would explain why this is happening a lot better.
Minecraft, overall, is a very CPU intensive game, to say the least. I'm getting a new computer soon(ish) to replace my going on six years prebuilt i3 thing that I've upgraded numerous times.
Anyways, I'm also having issues like this with ender tanks (from two completely different mods no less), when not getting enough lava, the lighting will change rapidly, causing a fps decrease. I'm guessing that lighting post-1.7 was moved to the CPU's workload instead of the GPU's. This would explain why the game is lagging so heavily when trying to change lighting rapidly. I don't quite understand why it's happening with EnderIO, but since I've moved away from lava in my current playthrough due to many other issues I've had, it's not really relevant to me. I don't believe it's an EnderIO bug, but more of a vanilla changed this and it sucks for people with older computers bug. Thank you for your time.

**Comment by HenryLoenwind** [comment]
Lighting has always been a CPU task, Minecraft has never used any kind of GPU lighting except for shading the 3D item icons.

**Comment by Leasara** [comment]
We are experiencing this on the BiffaTech server, the console is FLOODED with this type of message:

` [Server] Server thread/WARN [EnderIO]: NetworkedInventory.itemExtracted: Inserted 2 Water Bucket but only removed 1`

The Inserted ranges between 2 and 5

**Comment by HenryLoenwind** [comment]
Leasara, that is a notification about item duplication from an item conduit.

**Comment by Leasara** [comment]
Yes, I expect so, and we're getting 2-3 every second

**Comment by Leasara** [comment]
I see!  I've found a user that was automating Pam's Harvestcraft Salt rpduction, disabled his rig and the messages stopped.  Thanks!

**Comment by HenryLoenwind** [comment]
light levels for fluid conduits can now be disabled in the config
