### ISSUE TITLE
[1.10.2] Crash on Post-Init with latest The One Probe installed

### ISSUE THREAD

**Issue by Gepett0** [SleepyTrousers/EnderIO#3706]
#### Issue Description:
With latest EnderIo-beta and latest The One Probe MC crashes at start.
Maybe a TOP problem? Will x-post.

#### What happens:
MC crashes while post-initializing

#### What you expected to happen:
Playing as normal

#### Steps to reproduce:

1. Install Forge
2. Install Ender IO + EnderCore
3. Install TOP
4. Play (at least try)
5. Crash on startup

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.110
- EnderCore: 0.4.1.55
- Minecraft: 1.10.2
- Forge: 2089+ (tested on 2089 and 2092)

#### Your most recent log file where the issue was present: 
http://pastebin.com/86ZA40i8

**Comment by mkleiman312** [comment]
Confirming same crash. Downgrading EnderIO resolves conflict.

The One Probe: 1.10.1.1.1
McJtyLib: 1.10.2.1.1
EnderIO: 3.0.1.110
EnderCore: 0.4.1.55
Minecraft: 1.10.2
Forge: 2092

http://pastebin.com/FM0gpHAp

**Comment by HenryLoenwind** [comment]
Will be fixed in next build.

And btw, here we see the whole idiocy of using Optionals to avoid NPEs...there will just be another exception and no compiler warning about it.

**Comment by tterrag1098** [comment]
Using Optionals *incorrectly*

**Comment by McJty** [comment]
I have already handled this better in the next (not yet released) version of The One Probe
