### ISSUE TITLE
NOClassDefFound Error (TeslaCapabilities)

### ISSUE THREAD

**Issue by MDR-DEV-GIT** [SleepyTrousers/EnderIO#3707]
#### Issue Description:
Having a FloodLight connected to Ender IO Electrical conduit causes a crash when on latest version of Ender IO

#### What happens:
Loading map crashes when EnderIO tries to SetNetwork->getPowerInterface -> getCapability on a Floodlight connected via Ender IO Electric Conduits. 

Since this happened on an upgrade I'm unsure the behavior when placing it in game.

#### What you expected to happen:

The map should load successfly

#### Steps to reproduce:

1. Connect a Floodlights Floodlight (https://mods.curse.com/mc-mods/minecraft/224728-floodlights#other-downloads) to an Ender IO Network and power it. 
2. Load the game (though it might crash on placing?)
3.
...

____
#### Affected Versions (Do *not* use "latest"):

Minecraft Version: 1.10.2
[Minecraft Forge] (forge-1.10.2-12.18.1.2092.jar) 
[EnderCore] (EnderCore-1.10.2-0.4.1.55-beta.jar) 
[Ender IO] (EnderIO-1.10.2-3.0.1.110_beta.jar) 
[Flood Lights] (FloodLights-1.10.2-1.9.4-1.3.0-7.jar) 

#### Your most recent log file where the issue was present: 

https://gist.github.com/MDR-DEV-GIT/ea5ea9beb38aca74b2df66672dd394bd

**Comment by HenryLoenwind** [comment]
That's Floodlights' fault, they have a hard dependency on Tesla they don't declare.
