### ISSUE TITLE
Suggestion : Dark Boots - Falling with style

### ISSUE THREAD

**Issue by Chad077** [SleepyTrousers/EnderIO#3708]
I just love the Dark Armor set but I really miss the one feature that was available on an early game item. Tinkers' Construct - Traveller's Wings with the Feather Fall 1 upgrade allowed for really nice air control while descending. The Dark Armor set with glider deployed only really gives you two options, glide forward or drop like a stone :). I know we can't have it all but having to swap to an early game when owning and upgrading a late game item just doesn't feel quite right. Maybe a "feather fall" feature can be linked to the feather fall enchant if added to the boots? Either way, I will continue loving the set with or without the added feature.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by MatthiasMann** [comment]
The boots should already absorb fall damage when powered

**Comment by HenryLoenwind** [comment]
I think this is more about the "nice air control", whatever that is.

**Comment by border999** [comment]
I would also suggest an optional mod integration with the PortalGun mod. I would suggest some way of binding together the Dark Boots with the Long Fall Boots, maybe to lessen or even negate fall damage all together.

**Comment by Chad077** [comment]
Falling with Style - Just for you Henry :) - Attempts 7-9 - https://www.youtube.com/watch?v=kJnxvQPlip0

Also the Traveller's Wings with the Feather Fall 1 has pretty much the perfect drop speed as to not give you that sliding feeling when dropping down 1/2 block. Very good example of the "sliding" is to activate the glider and run over a slab. You'll get airborne so letting go of the forward button would have no effect until the character is back on the ground.
