### ISSUE TITLE
[Request] [1.10] Configurable fertilizer for farming station

### ISSUE THREAD

**Issue by bondgb** [SleepyTrousers/EnderIO#3710]
It would be nice if the config file allowed for adding our own fertilizer items for the farming station, just like we can add our own hoes. I see fertilizers are hardcoded, but with a lot of new mods popping up for 1.10 it'll be hard to keep up.

**Comment by tterrag1098** [comment]
The problem is that every fertilizer out there has a different way to use it. We could maybe add a config that just tries to right click but beyond that hardcoding is the only solution.

**Comment by Unrepentant-Atheist** [comment]
Yea, I think right-click ought to do it. Most fertilizers work that way.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
