### ISSUE TITLE
Feature request: InGameInfoXML support

### ISSUE THREAD

**Issue by Rixius** [SleepyTrousers/EnderIO#3712]
#### Feature Request:
If possible, I would like to see support added for InGameInfoXML. This would allow players to add the energy for their tools and armor to their on-screen display. I've started looking into the code for both mods, but I'm rusty with Java, and new to Forge mods,  so I don't know how something like this would be handled correctly.

#### What you would like to see:
*rf, *rfleft, and *maxrf tags for mainhand, offhand, helmet, chestplate, leggings, and boots.

#### Additional information:
I would be more than willing to assist if you wish. Working on getting my head into forge and modding Minecraft.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
