### ISSUE TITLE
Server crash - ItemTools.doInsertItem Refined storage mod.

### ISSUE THREAD

**Issue by ProsperCraft** [SleepyTrousers/EnderIO#3713]
#### Issue Description:
On my multiplayer server I woke up to this crash log, not sure what the players were doing.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  EnderIO-1.10.2-3.0.1.110_beta
- EnderCore: EnderCore-1.10.2-0.4.1.55-beta
- Minecraft:  1.10.2
- Forge:  2092

#### Your most recent log file where the issue was present: 

http://pastebin.com/Q9Y4fXaM

**Comment by HenryLoenwind** [comment]
The Mojang "Watchdog" killed the server because "it took too long".

Sadly that is all information that is available---there's no way to see what "it" was, just what was happening at the moment the server was killed.
