### ISSUE TITLE
Cannot load EnderIO in dev env 1.10.2

### ISSUE THREAD

**Issue by p455w0rd** [SleepyTrousers/EnderIO#3714]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Try to load EnderIO/EnderCore in dev env in 1.10.2

#### What you expected to happen:
MC to load

#### Steps to reproduce:

1. Download latest EnderIO/EnderCore from CurseForge
2. Put jars in libs/ directory
3. Add jars (as libs) to project build path (as I do with JEI, DE, And TiC with no issues)
4. Launch MC (dev/debug)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.105_beta
- EnderCore: 1.10.2-0.4.1.54-beta
- Minecraft: 1.10.2
- Forge: 12.18.2092

#### Your most recent log file where the issue was present: 

http://pastebin.com/WTtEnpp1

**Comment by HenryLoenwind** [comment]
Check your Ender IO config file, is the key "xpJuiceName" set to an empty string?

**Comment by p455w0rd** [comment]
no, however I have an xpJuice fluid in my mod..this resolves this, I just do a check if EnderIO is loaded, is so, I don't load my custom xpJuice..thanks

**Comment by HenryLoenwind** [comment]
ok, I see what's happening. We're checking for OpenBlocks and register ours when that mod is not loaded. However, when there already is another xp fluid, that registration is ignored. That would be fine, but after that we use the new fluid we created instead of the actually registered one. Ooops.

**Comment by HenryLoenwind** [comment]
It'd be great if you try that again with our next build.
