### ISSUE TITLE
[Request] Chisels & Bits compatibility for E.IO glass

### ISSUE THREAD

**Issue by xenoflot** [SleepyTrousers/EnderIO#3715]
Hi guys,

As time and motivation permit, I'd like to be able to use Ender IO's glass with the Chisels & Bits saws and chisels. AlgorithmX2 says: "they can return true for isFullBlock, which in my testing seems to work fine for glass, or they can send an IMC to C&B to tell C&B that the block can be chiseled."

Full reply on this ticket: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/135

Thanks!
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.95_beta
- EnderCore: 1.10.2-0.4.1.51-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2073
- Chisels and Bits: 12.1

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
