### ISSUE TITLE
Auto Crafting System ?

### ISSUE THREAD

**Issue by TonRZN** [SleepyTrousers/EnderIO#3716]
A Autocrafting system is planned for the item storage/sorting system ? Or maybe an integration with the new one from RFTools Control ?

**Comment by VT-14** [comment]
I think he means request based autocrafting, like those seen in full logistics systems (like AE2 or Logistics Pipes).

**Comment by TonRZN** [comment]
Yes, similar to AE2

**Comment by CrazyPants** [comment]
Thanks for the suggestion. This is on the long term todo list already.
