### ISSUE TITLE
RF gauge crashes the game

### ISSUE THREAD

**Issue by tipeon** [SleepyTrousers/EnderIO#3717]
#### Issue Description:
The RF gauge throws a ClassCastException that crashes the game.

#### What happens:
When I look at the RF gauge, a ClassCastException crashes the game.
If I do not look at it, it does not crash.

The issue seems to have been introduced in release 3.0.1.110_beta

#### What you expected to happen:

To not crash and work the same as in 3.0.1.107_beta

#### Steps to reproduce:

1. New world with just JEI and Ender I/O
2. Put down a Stirling engine
3. Shift right-click a RF gauge on the stirling engine
4. crash

____
#### Affected Versions (Do *not* use "latest"):
	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2093.jar) 
	Forge{12.18.1.2093} [Minecraft Forge] (forge-1.10.2-12.18.1.2093.jar) 
	endercore{1.10.2-0.4.1.55-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.55-beta.jar) 
	JEI{3.10.0.263} [Just Enough Items] (jei_1.10.2-3.10.0.263.jar) 
	EnderIO{1.10.2-3.0.1.112_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.112_beta.jar) 

#### Your most recent log file where the issue was present: 

http://pastebin.com/Xjybb6hD

**Comment by HenryLoenwind** [comment]
Fixed in next build
