### ISSUE TITLE
[Feature Request] [1.10.2] Config option to disallow lava buckets into stirling generator

### ISSUE THREAD

**Issue by Alaberti** [SleepyTrousers/EnderIO#3718]
Just a request to have a config to allows/disallow lava buckets from entering stirling generators. Or whitelisted fuels if you're feeling generous.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by Alaberti** [comment]
...I wish my payroll peeps were as quick as you lol thanks
