### ISSUE TITLE
Mekanism basic universal cable don't output power from enderio capacitor bank

### ISSUE THREAD

**Issue by mcdodge34** [SleepyTrousers/EnderIO#3721]
Ok, I'm using the Avant 3 modpack (1.10.2 modpack on curse launcher) but I try to update most mods manually to solve this kind of problems whenever I can, right now I have a problem with Mekanism basic universal cables, they get the power fine from my 2 Mekanism Wind Generator and transmit it fine to the EnderIO Capacitor Bank, the problem is the same cable doesn't get the power out of the capacitor bank to anything, I have a sag mill and a alloy smelter right now but I also tried a metallurgic infuser from Mekanism to no avail.

EnderIO version I have end with .107 will one of the two most recent versions of enderio correct this issue or its on Mekanism side I should ask ???

**Comment by HenryLoenwind** [comment]
107 was the last version that had the old (extremely well tested and working for years) RF code. So thi sis definitely Mekanism.

**Comment by mcdodge34** [comment]
Sorry to ask about this here, I don't know anything about other energy format than RF and EU, Does this mean I'm screwed up and I won't be able to use RF to power machines from enderio, is that the end for my love of an awesome mod
