### ISSUE TITLE
Pressurized Fluid Conduits Voiding Lava

### ISSUE THREAD

**Issue by JathTyki** [SleepyTrousers/EnderIO#3722]
#### Issue Description:

Pressurized Fluid Conduits will void lava that is extracted from a tank. I have replicated this with multiple different tank holders. This also happens with regular fluid conduits.
#### Steps to reproduce:
1. Set the Pressurized Fluid Conduit to extract and the other end to insert, and it will instantly void every single drop of lava in the tank.
   ...
---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 3.0.1.112
- EnderCore: 2.0.4.1.55
- Minecraft: 1.10.2
- Forge: 2092
#### Your most recent log file where the issue was present:

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment]
Does this also happen with other fluids eg water?
Are there any messages in the log?
What tank do you extract fro, where do you insert?

**Comment by JathTyki** [comment]
I have not seen it happen to anything other than lava. I have some conduits hooked up for nutrient distillation and water,but lava is the only one I have exclusively seen this happen to.

No messages in log, which is actually why I didn't attach it. I searched it beforehand the extra moment I had the issue. Nothing in the log noticeable.

I extracted from both an Ender IO Tank, along with a Mekanism Ultimate Fluid Tank. There were a couple others I've tried, but the two mentioned above are what I've used the most and seen it happen to the most.

I've inserted into many different things - other tanks same as what I'm extracting from, TiC smeltery, Deep Resonance tank, etc.

I have not tested successfully extracting and inputting lava so far. All tests have come back negative.

**Comment by CrazyPants** [comment]
I cant reproduce this at all. I have tried every setup I can think of and never lose any lava. Would you be able to include a screen shot with the exact details of the conduit settings used?

**Comment by JathTyki** [comment]
Really? I can show you here. It doesn't happen with the Ender IO Tank anymore, but it still happens with Mekanism. I actually took a video of it so you can see it happen. From what I can tell, all of the settings look okay. Maybe it just happens with the Mekanism one.

Mekanism version is latest, 292.

**Comment by utoc** [comment]
This has been going on for some time but we've always ignored the issue because Mekanism is so incompatible with everything.  The issue is present with Mekanism 292, EIO 3.0.1.112, EnderCore 4.1.56.

Place down any Mek tank, lava and water are good examples, use an EIO fluid conduit to remove said Mek tank fluid into any container.  Voi la, the fluid has been scattered to the seven winds.

**Comment by CrazyPants** [comment]
This is an issue in mekanism. There was an issue in EIO which has now been fixed (as you noticed).
It is working fine with all other modded fluid containers I have tested against (EIO, Forestry, TiC etc)
