### ISSUE TITLE
[Suggestion] Dark Helm Night Vision costs a small amount of RF/t

### ISSUE THREAD

**Issue by Fokson** [SleepyTrousers/EnderIO#3723]
I just think it's a bit strange that Night Vision can be turned on and off, makes an awesome camera flash charging sound, but doesn't take energy of any kind to function (especially in light of the fact that Speed and Jump both DO consume RF).  Doesn't need to be too intense, even 1RF per tick would last 83 minutes 20 seconds with the lowest tier of Empowered.  Either way, thanks for your time! =)

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
