### ISSUE TITLE
Mekanism and EIO not transmitting power even with 3.0.1.112

### ISSUE THREAD

**Issue by yutang13** [SleepyTrousers/EnderIO#3724]
#### Issue Description:

I have the version of Ender IO which says it has support for Tesla API and so does mekanism but the two power pipes still don't connect to each other.
Don't know if this is enderio's fault or not. Looks like it as the universal cables try and connect to the power conduit but not the other way round.
#### What happens:

http://imgur.com/a/i2A4F
#### What you expected to happen:

Them to connect and transfer power
#### Steps to reproduce:

1.Place a power source
2.Place a Enderio power conduit
3.Place a universal cable next to it.
...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.10.2-3.0.1.112
- EnderCore: 1.10.2-0.4.1.55
- Minecraft: 1.7.10
- Forge: 12.18.1.2904
#### Your most recent log file where the issue was present:

http://pastebin.com/CPtPA7x0

**Comment by MatthiasMann** [comment]
Don't try to connect cables and conduits - put a capacitor, buffer or energy cube in between.

**Comment by yutang13** [comment]
@MatthiasMann But that worked before the "Tesla support" 

Anyway. The mekanism cables will quite happily output to the power conduits but the mekansim cables will *not* extract/accept energy from the capacitor banks.

**Comment by yutang13** [comment]
More importantly this wonky thing happens!

http://imgur.com/a/TSLCm

Advanced energy cube outputting to elite cables inputting to a capacitor bank with a max of 1,000RF in, recieving 1,280RF/t. AKA the max output of the energy cube.

**Comment by Utildayael** [comment]
Mekanism says it is a bug with how EnderIO implemented Tesla. Henry marked my bug as wontfix back in August. I do hope he reconsiders much like I also hope he brings back the gas conduits. ;)

#3615
