### ISSUE TITLE
Crafter returns duplicate container items.

### ISSUE THREAD

**Issue by Fokson** [SleepyTrousers/EnderIO#3725]
#### Issue Description:
When crafting an item that would use a bucket of something, it successfully crafts but then returns two buckets.

#### What happens / What was expected to happen / Steps to reproduce:

Inventory Crafting>
 1) http://puu.sh/rnGBr/5397f76aab.jpg
 2) http://puu.sh/rnGCp/b19b524f4c.jpg

Crafter Crafting>
 1) http://puu.sh/rnGId/e1565720c2.jpg
 2) http://puu.sh/rnGJ6/c5eb8de504.jpg

____
#### Affected Versions:

- EnderIO: 3.0.1.122-beta
- EnderCore: 0.4.1.55-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2093

#### The most recent log file where the issue was present: 
Not sure which one you're looking for; latest, fml-client, fml-server, etc.  I skimmed each and there was nothing apparently relevant to the issue.

**Comment by HenryLoenwind** [comment]
#3709

**Comment by Fokson** [comment]
My apologies; when I searched for the issue I used the keyword "bucket".
