### ISSUE TITLE
Crafter will not accept some recipes.

### ISSUE THREAD

**Issue by Fokson** [SleepyTrousers/EnderIO#3726]
#### Issue Description:

The crafter fails to recognize some recipes. (It seems to be mostly recipes from Immersive Engineering.)
#### What happens / What was expected to happen / Steps to reproduce:

Inventory Crafting>  http://puu.sh/rnHUd/f14924a49d.jpg

Crafter Crafting>  http://puu.sh/rnHX0/e818d2dc12.jpg

---
#### Affected Versions:
- EnderIO: 3.0.1.122-beta
- EnderCore: 0.4.1.55-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2093

**Comment by HenryLoenwind** [comment]
Could it be that those are all recipes involving the Forge Bucket?

**Comment by Fokson** [comment]
It doesn't appear so, as seen here:

> http://puu.sh/rnIFA/311d174373.jpg
