### ISSUE TITLE
Suggestion: Inhibitor obelisk recipe

### ISSUE THREAD

**Issue by bbgott** [SleepyTrousers/EnderIO#3729]
I noticed that the inhibitor obelisk doesn't yet have a recipe.  I also noticed a while back that a request was put out for ideas.  So here's my two cents worth, I think the item on the top of the obelisk should be an ender crystal, just like what is used in crafting the staff of traveling.  It's both difficult to get early game and has a sense of relation to teleporting.  While I realize that the inhibitor obelisk prevents teleporting, it just seems to me that the ender crystal makes sense for the recipe.  End of my two cents worth.

**Comment by HenryLoenwind** [comment]
Sounds good to me, @CrazyPants are you ok with this?
