### ISSUE TITLE
[1.7.10] GUI Problems

### ISSUE THREAD

**Issue by SourcePowered** [SleepyTrousers/EnderIO#3730]
#### What happens:

When installed EnderIO, GUI is bugged.
Please see the photo:

![1](https://cloud.githubusercontent.com/assets/20459998/18873062/39954746-84f0-11e6-8478-68162f754637.png)
![2](https://cloud.githubusercontent.com/assets/20459998/18873063/3a20de0a-84f0-11e6-8e1f-0abdb443f228.png)
![11](https://cloud.githubusercontent.com/assets/20459998/18873065/3a441898-84f0-11e6-9426-c14c0540ff9e.png)

**This must be EnderIO's problem, because If I delete it, there is no problem.**

#### What you expected to happen:

Normal interface.

#### Steps to reproduce:

1. Download EnderIO from Curse.
2. Install it.
3. GUI is buggy now.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta.jar
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta.jar
- Minecraft: 1.7.10
- Forge: 1614

#### Your most recent log file where the issue was present: 

Log file everything is normal, no need to upload.

**Comment by HenryLoenwind** [comment]
This is a known Forge bug in 1.7

**Comment by SourcePowered** [comment]
@HenryLoenwind But if this is forge bug, why installed EnderIO is bugged?

**Comment by HenryLoenwind** [comment]
Forge cannot handle Ender IO's icon correctly...
