### ISSUE TITLE
[1.7.10] Dupliate glitch with Capacitor Bank

### ISSUE THREAD

**Issue by lLuckyLukel** [SleepyTrousers/EnderIO#3732]
#### Issue Description:

Hi there! Found an old dupe glitch with Capacitor Bank working with latest version of EnderIO for 1.7.10. 
#### What happens:

Duplicating all items/blocks which using RF energy and can be charged in Capacitor Bank.
#### Steps to reproduce:

In video. But keep the sound off cuz it's in russian :)
https://www.youtube.com/watch?v=SX0JzGnvViU#t=01m10s
#### Affected Versions:
- EnderIO: 1.7.10-2.3.0.428_beta (Actually works with old versions)
- EnderCore: 1.7.10-0.2.0.38_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1566

Sorry if doubling other post :)

**Comment by HenryLoenwind** [comment]
Diagnosis: CapBank GUI Container keeps the master CapBank inventory alive even if the CapBank is modified and the master shifts to another CapBank.

**Comment by HenryLoenwind** [comment]
(that commit is for 1.10 and may be unrelated cases)

**Comment by lLuckyLukel** [comment]
Great to hear.

**Comment by linkinkov** [comment]
Any news to fix?

**Comment by lLuckyLukel** [comment]
@linkinkov Написал, вроде на 1.10 пофиксит же...

**Comment by linkinkov** [comment]
@lLuckyLukel Я пробовал его патч, не работает.
