### ISSUE TITLE
Elytra-upgraded Dark Chestplate interacts oddly with other creative-flight items (like angel rings)

### ISSUE THREAD

**Issue by starg09** [SleepyTrousers/EnderIO#3735]
#### Issue Description:

Dark Steel Chestplate (with elytra) seems to cause weird interactions with anything that gives creative flight (e.g. angel ring).
#### What happens:

If you disable, then enable "creative flight" while in mid air, it does not disable elytra capabilites. You keep gliding even when you're supossed to "float", and you cannot move with the WASD keys.

[Video showing the issue](https://streamable.com/ibxi)
#### What you expected to happen:

Elytra not to activate when "floating" and moving.
#### Steps to reproduce:
1. Equip Elytra-upgraded Dark Chestplate
2. Give yourself an angel ring. (Also generate 32 GP for it to work)
3. Enable creative-flight while being in survival.
4. Get in mid air, disable flight (double space-tap), then enable it again while gliding
5. Try to move around, check what happens. You keep gliding, even when "floating", and you cannot move at all. This ends once you reach the ground, when gliding stops

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.10.2-3.0.1.112_beta
- EnderCore: 1.10.2-0.4.1.56-beta
- Minecraft: 1.7.10
- Forge: 2094
- Extra Utilities 2: 1.0.1
#### Your most recent log file where the issue was present:

Log is from an unannounced pack, so I'm only able to share the log in private, if you need it.

**Comment by HenryLoenwind** [comment]
This is a known side effect of how we have to hack the flying information into vanilla. To avoid this we'd have to change and replace about 10 times as many things in multiple vanilla classes which would lead to potential conflicts with most mods that do anything to player movement.

**Comment by HenryLoenwind** [comment]
PS: That's one of the reason why the "glide" key also disables Elytra-flying.
