### ISSUE TITLE
[1.10.2] Machine side configuration glitches when used next to Environmental Tech's Void Miners

### ISSUE THREAD

**Issue by starg09** [SleepyTrousers/EnderIO#3736]
#### Issue Description:
Screen gets covered in a plain color if you try to configure a machine sides with this being next to any main block from an Environmental Tech "Void Ore/Resource Miner" multiblock. No issue doing it with the machine adjacent to the other blocks.

#### What happens:

[Screens goes gray.](http://i.imgur.com/ot1pgQU.png). GUI seems to keep working as intended, only the visual part is affected. Pressing ESC, or clicking the "side config" button again turns everything back to normal.

#### What you expected to happen:

Being able to check side config.

#### Steps to reproduce:

1. Create one of the mentioned multiblocks from EnviroTech. **EDIT:** Make sure the machine is functional (Power is not neccesary. Needs bedrock sight at the bottom of the laser)
2. Place any machine or block with a side config near the main part of the multiblock (Example: "Void Resource Miner Controller Tier 1)
3. Open the machine's GUI, press the side config button.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.0.1.112_beta
- EnderCore: 1.10.2-0.4.1.56-beta
- Environmental Tech: 1.10.2-0.10.4b
- Minecraft: 1.7.10
- Forge: 2094

#### Your most recent log file where the issue was present: 

Log is from an unannounced pack, so I'm only able to share the log in private, if you need it.

**Comment by starg09** [comment]
Whoops, forgot to check again in last update before reporting, sorry bout that -.-

**Comment by starg09** [comment]
...and I should check all conditions were tested. Forgot the machine needs to be enabled (as in, the void resource miner needs energy and direct view to the miner). So the problem is still there :|

**Comment by CrazyPants** [comment]
The Env. Tech. Machine must be leaving the GL state in a mess. Unfortunately this is not something we can fix on our side.

**Comment by starg09** [comment]
All right, I'll report it to them then.

**Comment by ValkyrieofNight** [comment]
The void miners use same code as vanilla beacon for beam rendering. Same problem exists with the vanilla beacon too.

**Comment by ValkyrieofNight** [comment]
Found the problem :) Have fixed on my side. Vanilla beacon will still have the problem though.

**Comment by HenryLoenwind** [comment]
Thx.

About the beacon: I'll add a workaround for that once someone convinces me that they actually put a machine next to one for real. ;)
