### ISSUE TITLE
Rendering Screen Crash When Viewing Vat Recipies in JEI

### ISSUE THREAD

**Issue by DMIL421** [SleepyTrousers/EnderIO#3737]
#### Issue Description:
When checking Vat fluid recipies in JEI, and changing to the Vat recipe tab, A client crash occurs. The server is not affected.

#### What happens:
Client Crashes

#### What you expected to happen:
Vat fluid recipe to be displayed

#### Steps to reproduce:

1. Open Inventory
2. Search JEI for Vat
3. Mouse over Vat and hit U
4. Hit the arrow to change to the Vat recipe tab
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.112_beta
- EnderCore: 2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: 2092

#### Your most recent log file where the issue was present: 
https://gist.github.com/DMIL421/deec1665abb9bd99ddaad1212eae57dc

I also posted this to JEI's Issue Tracker. They said it was a problem with EIO. 
https://github.com/mezz/JustEnoughItems/issues/458

**Comment by HenryLoenwind** [comment]
So what do you expect of us? That we hop into our time machine and change the old Ender IO versions to work with the new JEI?
