### ISSUE TITLE
[1.10.2] Servercrash

### ISSUE THREAD

**Issue by Gepett0** [SleepyTrousers/EnderIO#3739]
Hi,
sorry to open a new issue, but i couldn't find an open or closed issue with a similar crash report.
After leaving the server running a couple hours without anyone online the first time a buddy of me or me myself joins the server it crashes.
Playing a private modded forge server with a few mods.
Can't nail the problem with the crashlog by myself :-(

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.112_beta
- EnderCore: EnderCore-1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2093

#### Your most recent log file where the issue was present: 

http://pastebin.com/3NDbFEuA

**Comment by HenryLoenwind** [comment]
We have a number of those. That is Mojang saying "it takes too long, kill them all!!!"

That stacktrace is about as useful fro finding the issue (if there even is one) as the location of the last battle would be for finding out who started the 30-year war...

Sorry, nothing we can really do here.
