### ISSUE TITLE
new wordgen freez

### ISSUE THREAD

**Issue by JCampro** [SleepyTrousers/EnderIO#3740]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

new world gen is freezing

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.0.1.116_beta
- EnderCore:EnderCore-1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge:forge-1.10.2-12.18.1.2094

**Comment by JCampro** [comment]
[crash-2016-09-30_00.44.55-server.txt](https://github.com/SleepyTrousers/EnderIO/files/503794/crash-2016-09-30_00.44.55-server.txt)

**Comment by JCampro** [comment]
log

**Comment by HenryLoenwind** [comment]
at com.fireball1725.graves.common.world.WorldGeneration.setProfile(WorldGeneration.java:55)
