### ISSUE TITLE
[1.10.2] Liquids in JEI crash

### ISSUE THREAD

**Issue by SPMoo66** [SleepyTrousers/EnderIO#3741]
#### Issue Description:
When pressing the view recipe button in JEI on any fluid, immediately crashes

#### What happens:
Crash

#### What you expected to happen:
Look at ways to obtain/use fluid in JEI

#### Steps to reproduce:

1. Use recipe key over a fluid in JEI
2. Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.116
- EnderCore: 1.10.2-0.4.1.56
- Minecraft: 1.10.2
- Forge: 12.18.1.2094

#### Your most recent log file where the issue was present: 

http://pastebin.com/LCRjpqxc

**Comment by jkerr** [comment]
I think this is the same issue, but for more info: playing All The Mods newest version, opened JEI, clicked lava, see one recipe, clicked the arrows on top to see another way to get lava, crash.

`java.lang.IndexOutOfBoundsException: Index: 0`
`	at java.util.Collections$EmptyList.get(Unknown Source)`
`	at crazypants.enderio.integration.jei.TankRecipeCategory.setRecipe(TankRecipeCategory.java:181)`

**Comment by Unrepentant-Atheist** [comment]
Can confirm: https://gist.github.com/anonymous/ae16a5b2c5d287846dd6cbb564a149b8
