### ISSUE TITLE
3rd Party RF Power Crash

### ISSUE THREAD

**Issue by MeinKraft** [SleepyTrousers/EnderIO#3743]
http://pastebin.com/meVBa7By

Using Mekanism to supply RF to KillerJoe, after couple of minutes the server/game crashes

All details in the pastebin

UPDATE: even with EnderIO Creative Capacitor the game crashes server side. Seemed OK in singleplayer. Similar crash Null Pointer Exceptions

**Comment by AnrDaemon** [comment]
The issue template wasn't there for you to ignore it.

**Comment by HenryLoenwind** [comment]
Caused by: java.lang.NullPointerException
    at mca.data.PlayerMemory.<init>(PlayerMemory.java:50) ~[PlayerMemory.class:?]
