### ISSUE TITLE
Farming Station planting vanilla saplings as Forestry saplings (with Forestry installed)

### ISSUE THREAD

**Issue by Hjaldar** [SleepyTrousers/EnderIO#3744]
#### Issue Description:

Farming Station plants vanilla saplings as their forestry variants.
#### What happens:

Any vanilla saplings placed in a farming station are planted as their forestry variants. This is despite pollination of vanilla saplings being turned off in /config/forestry/common.cfg (B:pollinate.vanilla.trees=false).
#### What you expected to happen:

Vanilla saplings placed in a farming station to be planted as vanilla saplings. If I wanted Forestry saplings planted I would have placed Forestry saplings in the farming station.
#### Steps to reproduce:
1. Place a farming station on dirt.
2. Give it power.
3. Put any vanilla sapling in the farming station.
4. Wait until sapling is planted. It is planted as a Forestry sapling.
   ...
---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.10.2-3.0.1.116_beta
- EnderCore: 1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2094
- Forestry: 1.10.2-5.2.12.260
#### Your most recent log file where the issue was present:

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
That's because Forestry claims those sapling belong to it. We need to add a special case for that.

**Comment by Hjaldar** [comment]
@bdew Could you take a look at this please? I know this is the same behaviour as Forestry multi-farms but it breaks tree farms for vanilla saplings. Thanks.

**Comment by bdew** [comment]
I'll look into it later today. I don't think forestry API has anything to distinguish between it's saplings or vanilla ones being converted.

Worst case i'll just add a check for the item, as all forestry saplings use it's item (SaplingGE or somesuch).

**Comment by bdew** [comment]
PR with fix - #3757

**Comment by Hjaldar** [comment]
Confirmed fixed in EnderIO - 1.10.2-3.0.1.124_beta. Thanks all.
