### ISSUE TITLE
Feature Suggestion: Self Feeding Device

### ISSUE THREAD

**Issue by Badcholo** [SleepyTrousers/EnderIO#3745]
Feature Suggestion. A Block (Liquifier) that i can place food into and it will grind it up into food paste or nutrition juice points. A hand held device is placed inside the Liquifier and can be filled up with Nutrition Juice. A large amount of nutrition juice can be held inside the device and will auto feed the player just by being in their inventory. 
I hate eating, but i like having a reason to use food and i like the cost of surviving. Your mod has great armor and the machines and devices are amazing. With such advanced technology we should have some sort of self feeding right? I just came up with this idea out of nowhere and it is just used as an example of the self feeding feature suggestion i'm hoping for. There may be a much simpler way of achieving the same results, but this is the only way i could explain it. I lose hunger so fast in 1.10.2 it's strange that no mod has done something like this. I won't be offended if this issue is just closed and forgotten about. I understand your all very busy with much more important things. Thank you for your time.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by Badcholo** [comment]
Thank you
