### ISSUE TITLE
New Chisel version bug with painter

### ISSUE THREAD

**Issue by kragnoth** [SleepyTrousers/EnderIO#3746]
Newest version of Chisel makes chiseled blocks invisible if used as source block in painter.

Painted blocks are invisible if source block is chiseled block

Painted blocks are visible if source block is chiseled block
#### Steps to reproduce:
1. Chisel cobblestone
2. Paint glowstone or any other block with chiseled cobblestone
3. Place in world, and marvel at your world hole you just placed down
   ...
---
- EnderIO: EnderIO-1.10.2-3.0.1.116_beta.jar
- EnderCore: EnderCore-1.10.2-0.4.1.56-beta.jar
- Chisel: Chisel-MC1.9.4-0.0.6.48.jar
- Minecraft: 1.10.2
- Forge: 2094

**Comment by Susjin** [comment]
I'm having this issue too, it is happening after the update of chisel for version 0.0.6.48,i have a screenshot here
https://imgur.com/a/Q8AE7
That is an Painted Glowstone block with an Chiseled Stone

**Comment by HenryLoenwind** [comment]
Chisel is no longer using the vanilla model infrastructure to render its blocks.

**Comment by Harith163** [comment]
Well, doesn't @tterrag1098 also handle Chisel? Is there a realistic fix for this that can be implemented in a couple updates... or do I just throw my hands up in the air and rebuild my base?

**Comment by tterrag1098** [comment]
Chisel will fix this on our end

**Comment by Watchful1** [comment]
On latest chisel these blocks now show the purple and black missing texture instead of being invisible.

**Comment by tterrag1098** [comment]
Still probably on our end. I'll investigate tonight.

**Comment by tterrag1098** [comment]
Erm...Our end being chisel's.

**Comment by HenryLoenwind** [comment]
Probably needs a new Ender IO version with the longer lasting fake world fix, too.
