### ISSUE TITLE
[1.10.2] Recent EnderIO updates breaks waila integration,  rf/tick on capacitor banks etc

### ISSUE THREAD

**Issue by MrNinja93** [SleepyTrousers/EnderIO#3747]
#### Issue Description:
EnderIO intergration with WAILA seems to be broken in recent updates, WAILA used to display info on capacitor banks showing Rf stored/total possible and I/O for the bank.

EnderIO update 1.10.2-3.0.1.110_beta breaks this integration, No mention in changelogs of pulling of waila support and Waila compatibility files are still apparent in the jar file/code at https://github.com/SleepyTrousers/EnderIO/tree/1.10/src/main/java/crazypants/enderio/integration/waila

#### What happens:
WAILA no longer shows info from EnderIO machines

#### What you expected to happen:
Functionality to exist no mention of it being pulled in changelogs 

#### Steps to reproduce:

1. Install Waila/EnderIO 
2. Look at cap bank in world

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.110_beta to 1.10.2-3.0.1.116_beta
- EnderCore: 1.10.2-0.4.1.56-beta
- Minecraft: 1.10,2
- Forge: 2094

#### Your most recent log file where the issue was present: 
N/A

**Comment by HenryLoenwind** [comment]
WAILA hasn't been updated in months and is full of bugs. Not sure if it makes sense to put any more effort into this, WAILA seems to be on its way out.
