### ISSUE TITLE
Food Journal from Spice of Life texture missing

### ISSUE THREAD

**Issue by vlce-versa** [SleepyTrousers/EnderIO#3748]
#### Issue Description:
With Ender I/O installed and Spice of Life Mod, the texture for the Food Journal is missing, it just shows a pink cube

#### What happens:
see above

#### What you expected to happen:
To have the right texture for the Food Journal

#### Steps to reproduce:

1.Install Spice of Life Mod
2.Change Spice of Life config to give a Food Journal on Spawn
3.-
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.0.1.116
- EnderCore:1.10.2-0.4.1.56
- Minecraft: 1.10.2
- Forge:12.18.1.2084

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
#3549
