### ISSUE TITLE
Soulbound Enchantment - Stacks

### ISSUE THREAD

**Issue by xSable** [SleepyTrousers/EnderIO#3754]
#### Issue Description:

Soulbound Enchantment Bug with Item Stacks

#### What happens:

You can enchant a stack of cobble with soulbound, then using any other disenchant methods (other mods, etc) you can get a soulbound book from each individual cobble.

Turning one soulbound book into 64 soulbound books.

#### What you expected to happen:

Soulbound works on 1 item, not the entire stack.

#### Steps to reproduce:

1. Grab 64 Cobble or any other stack of items
2. Grab Soulbound Book
3. Put in Anvil
4. Take out 64 soulbound cobblestone
5. Separate and disenchant

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.2.8.381
- EnderCore: Not Used (Didn't download it, don't see it, still loaded)
- Minecraft: 1.7.10
- Forge: .1614

#### Your most recent log file where the issue was present: 

Logs don't show anything related.

**Comment by MatthiasMann** [comment]
Version 2.2.8 is very old - there won't be any patches for that.

**Comment by HenryLoenwind** [comment]
Also, the enchanting is done by vanilla code. We have no influence here.
