### ISSUE TITLE
Crash if i change the liquid that the Remote Inventory Panel uses

### ISSUE THREAD

**Issue by Susjin** [SleepyTrousers/EnderIO#3755]
#### Issue Description:
If i  change the type of liquid in the config, my game just crash when the world is loading

#### What happens:
The game just open fine, but when my world is loading, the game crash

#### What you expected to happen:
To load the world fine

#### Steps to reproduce:

1.Go to Ender IO config
2.In the type of fluid, put only nutrient_distillation
3.Go load an world
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:3.0.1.120_beta
- EnderCore:0.4.1.55_beta
- Minecraft: 1.10.2
- Forge:12.18.1.2095

#### Your most recent log file where the issue was present: 

http://pastebin.com/EkKTEznb

**Comment by VT-14** [comment]
Did you just delete the other two, or did you replace them?

I'm guessing that the 3 entries correspond to the different panels in order.  If you want all 3 to be nutrient distillation, try entering nutrient_distillation 3 times.
