### ISSUE TITLE
1.10.2 EnderIO energy stopped being compatible with ActuallyAddition/ImmersiveEngineer

### ISSUE THREAD

**Issue by LordHellscream** [SleepyTrousers/EnderIO#3758]
#### Issue Description:
Ever since updated to 3.0.1.117 (not sure exactly from which version this stopped working), Ender IO energy transfer seems to stopped being compatible with some of the items/blocks from other mods such as mekanism, actually addition, immersive engineering etc

#### What happens:
Specifically:
1. Capcacitor banks stopped transferring power through immersive engineering cable (it used to work before)
2. Ender IO items refused to be charged with anything but Ender IO charging methods (in the bank/generator etc). None of the weapons/armor can be charged by Actually addition batteries (these all use to work)
3. Mekanism charging pads used to work with Ender IO items, they don't work anymore.

#### What you expected to happen:

Things used to work still working

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.117_beta
- EnderCore: 1.10.2-0.4.1.56
- Minecraft: 1.10.2
- Forge: 2094

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment]
EnderIO no longer bundles the RF API - but if it is present it will use it. It also supports forge energy and Tesla (also not bundled).

I advice to update to EnderIO version 120 as that fixes a load order issue with these APIs.

**Comment by HenryLoenwind** [comment]
for 1: update Ender IO, should be fixed in latest
for 2+3: RF is no longer supported for Ender IO items

**Comment by LordHellscream** [comment]
I don't understand the ender IO are using RF, what do you mean by RF not supported?

**Comment by VT-14** [comment]
From my super basic understanding of power systems and APIs; the short story is that the RF API is no longer being developed.  Tesla or Forge Power will replace it.  Tesla is downloaded as a separate mod (you can download it now).  I don't know anything about Forge Power.
