### ISSUE TITLE
[1.10.2] Not Working With IE power?

### ISSUE THREAD

**Issue by Nephatrine** [SleepyTrousers/EnderIO#3759]
EnderIO power does not seem to interoperate with Immersive Engineering power.

#### What happens:
No power is transferred between the blocks.

#### What you expected to happen:
Power should be transferred.

#### Steps to reproduce:
1. Attach LV connectors and LV cabling between two EnderIO capacitors or similar.
2. Observe minor energy loss from cable (-2 RF/t in my setup) but no power transfer.
- OR -
1. Attach EIO conduit to two IE capacitors or similar.
2. Observe no power transfer.

#### Affected Versions (Do *not* use "latest"):
EnderCore 0.4.1.56
EnderIO 3.0.1.120
Immersive Engineering 0.10-44
Minecraft 1.10.2
Forge 12.18.1.2094

**Comment by MatthiasMann** [comment]
see #3758
