### ISSUE TITLE
Cable conduit

### ISSUE THREAD

**Issue by ElTodoFull** [SleepyTrousers/EnderIO#3760]
Suggestion.
The cabke conduit which can transport ic2s eu between macines, thats all.
The crafting might require the 6 composites and some energy crystals or glass fibre cable.
I think its a good idea.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
