### ISSUE TITLE
[Suggestion] Refresh Machine Recipe Configs In-Game

### ISSUE THREAD

**Issue by CookieTrains** [SleepyTrousers/EnderIO#3761]
**Suggestion: Refresh Machine Recipe Configs In-Game.**

I'm suggesting this as an idea since it's a real pain having to close and reopen Minecraft in order for the changes done to the machine configs to take place. It would also save modpack developers time when making a pack. It could be done by a simple command like; '/enderio_configs' or something along those lines.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
