### ISSUE TITLE
EnderIO rejects invalid configuration ALL TIME.

### ISSUE THREAD

**Issue by mrjewel** [SleepyTrousers/EnderIO#3762]
It always crashes when I load EnderIO to my mods, It doesn't matter if there's more mods, It crashes anyway.

I expected to "What happens If I remove all the mods and only have EnderIO, EnderCore and JEI, but it crashed again.
- EnderIO: EnderIO-1.10.2-3.0.1.120_beta
- EnderCore: EnderCore-1.10.2-0.4.1.56-beta 
- Minecraft: 1.10.2
- Forge: 1.10.2-forge1.10.2-12.18.1.2094

http://pastebin.com/Dcm6fWBQ

**Comment by MatthiasMann** [comment]
Did you edit the recipe_materials.xml ?
I suggest to temporary rename the enderio config folder in your instance and see if it still crashes with default config.

**Comment by mrjewel** [comment]
I tried even reinstalling minecraft, but I've noticed EnderIO's config name is "enderıo" I renamed it to "enderio" I'll edit if something happens. Thanks.

**Comment by MatthiasMann** [comment]
umm - where did you download the mod from?

**Comment by mrjewel** [comment]
From the https://minecraft.curseforge.com/projects/ender-io

**Comment by MrNinja93** [comment]
> I tried even reinstalling minecraft, but I've noticed EnderIO's config name is "enderıo" I renamed it to "enderio" I'll edit if something happens. Thanks.

Renaming the config is part of the issue, EnderIO.cfg is its default name it shouldn't be changed from that. I suggest deleting all enderio configs you have and let the mod regenerate them all and then dont rename any, see if that fixes the problem.
