### ISSUE TITLE
[1.10.2] [Multiplayer] Capacitor banks Input/output sets itself to 0 rf/t

### ISSUE THREAD

**Issue by MrNinja93** [SleepyTrousers/EnderIO#3763]
#### Issue Description:

Occasionally capacitor banks will reset input and output values to 0 rf/t I've only had this issue happen on a multiplayer server and it only seems to happen if a player opens the capacitor bank GUI (though its still random times during that action)

Same as reported in https://github.com/SleepyTrousers/EnderIO/issues/3577 Issue was closed and deemed fixed in EnderIO - 1.10.2-3.0.1.105_beta 

Haven't seen it reported since then so if its been reported since ignore.
#### What you expected to happen:

For capacitor banks to stay set to default input/output or player set I/O regardless of how many times the GUI is opened.
#### Steps to reproduce:

1.Be on server.
2.Open/Close GUI of capacitor bank until I/O set itself to 0 Rf/t

---
#### Affected Versions (Do _not_ use "latest"):

Server so not fully up to date on mods, Currently:-
- EnderIO: 1.10.2-3.0.1.112_beta
- EnderCore: 1.10.2-0.4.1.55-beta
- Minecraft: 1.10.2
- Forge: 2094
#### Your most recent log file where the issue was present:

N/A

**Comment by SummitSummit** [comment]
I'm getting this issue on Single Player too.  At first I thought it was whenever I loaded the world, but I tested a couple times, and it is not consistent. I'm using EnderIO-1.10.2-3.0.1.120_beta and EnderCore-1.10.2-0.4.1.56-beta.

**Comment by MrNinja93** [comment]
I tried testing in Singleplayer to see if I could trigger it but never could in either version 112 or 120, 

Commit added stacks up with what I was experiencing though, was always when client took it seemed slightly longer to open the GUI than usual whenever it happened. I'll try again and see if a super laggy world or lowering ram triggers it and if it does test with a custom build (Mod version with that commit isnt released yet)

**Comment by MatthiasMann** [comment]
@MrNinja93 the build is here http://ci.tterrag.com/job/EnderIO-1.10/121/

**Comment by MrNinja93** [comment]
Tested in 112 singleplayer with a download of my servers world (Laggiest singleplayer world I had, actually broke minecraft twice in one players base!)  teleported back and forth between peoples bases and cap banks (for chunk-load/unload) to see if I could get it to happen and no luck. Still mutiplayer only for me.

Will probably do a pack update soon for the server so I'll report back here whenever we put new versions of EnderIO with that commit in (will at-least wait for it to hit curseforge/a couple days extra to make sure it doesn't break something horribly)

**Comment by RubikMonat** [comment]
Getting this issue in single player, HermitPack. 
Ender IO version 1.10.2-3.0.1.117 Beta
Happened several times. Not sure if it's after restarts or after accessing the GUI
Multiblock of three lowest tier capacitors directly under an Environmental Tech  0.10.4b solar panel with a basic ender io conduit as an output heading down to the mine. I have been putting "Not Enough Wands" wands in it to charge.

**Comment by MrNinja93** [comment]
If you're getting the issue fairly often in single player it might be worth testing with a copy of your instance/world and version 121 linked above to see if it still happens, I couldn't reproduce it in single player but I hardly play singleplayer minecraft atm to notice it happening there like you might, some bugs need playtime to show themselves.

**Comment by nico1995doom** [comment]
im having the same issue with 1.10.2-3.0.1.120_beta, forge 12.18.2.2111 have you found a solution to the problem?

**Comment by MatthiasMann** [comment]
@nico1995doom no - as you can't read the solution posted above

**Comment by Aerolivier** [comment]
I'm also experiencing this issue. I don't think chunk unloads/reloads are the cause of it, because I've been in the same area for a while now and it's reset about 3~4 times in the space of 5 hours.
I'm also on single-player.

**Comment by MrNinja93** [comment]
@Aerolivier  Can you try that instance with version 121 of EnderIO from the EnderIO-Jenkins site here: http://ci.tterrag.com/job/EnderIO-1.10/121/ (or 122) and see if it still happens. 

(Issue I had in multiplayer wasn't chunkload/unload but I did so in single-player to try incorporate some extra lag to try trigger it)

**Comment by xenoflot** [comment]
A player on my server reported this problem today. Has this fix been rolled into the release? If so, it didn't work :)

We're currently on:
EnderIO 3.0.1.128_beta
EnderCore 0.4.1.58-beta

**Comment by HenryLoenwind** [comment]
so it didn't work...and I'm completely out of ideas what could cause this... :-(

**Comment by LewisHolt** [comment]
I'm getting this issue too, with the Direwolf20 1.1.0.2 pack.

So aggravating. :(

**Comment by HenryLoenwind** [comment]
FYI: I have reports that build 171 fixes this problem.

**Comment by roboderpy** [comment]
Bug appeared a loooong time ago at some 1.7.10 version
