### ISSUE TITLE
Clicking a TC Smeltery with a Wrench Clears its Contents

### ISSUE THREAD

**Issue by Flexico** [SleepyTrousers/EnderIO#3764]
I had an EnderIO Yeta Wrench in my hand when I tried to access my Tinkers Construct smeltery, and the wrench rotated the Smeltery Controller block. When I rotated it back and opened it up, all my molten metals had been cleared.

I'm not totally sure which mod I should report this to, so I'm doing both to be safe.

MC 1.10.2
Forge 12.18.1.2094
TC 2.5.3
EIO 3.0.1.117

**Comment by MrNinja93** [comment]
Resolved tinkers side so this can be closed now :) https://github.com/SlimeKnights/TinkersConstruct/issues/2463

**Comment by HenryLoenwind** [comment]
thx for the update
