### ISSUE TITLE
[1.10.2] Tesla ClassNotFoundException

### ISSUE THREAD

**Issue by hunter688** [SleepyTrousers/EnderIO#3766]
Im not using Tesla, but EnderIO at some situation want it:

http://pastebin.com/ERKqZdLt

**Comment by MatthiasMann** [comment]
Why did you delete the template instead of filling it out?

**Comment by hunter688** [comment]
forge build 2092
enderio build 120
endercore build 56

idk howto reproduce

**Comment by HenryLoenwind** [comment]
So you enable DEBUG logging and are surprised that the API diagnostics tell you the exact technical reason why it thinks Tesla is not installed?
