### ISSUE TITLE
Enderman Head glitch with Chisel2

### ISSUE THREAD

**Issue by NillerUdenDild** [SleepyTrousers/EnderIO#3770]
#### Issue Description:

Whenever you're near an Enderman Head, most items from Chisel 2 turn  #invisible:
#### What happens:

Whenever you're near an Enderman Head, most items from Chisel 2 stop showing.
You can see the effect in the screenshots bellow. The last two show, that breaking the head turn them normal again.
![2016-10-10_17 57 26](https://cloud.githubusercontent.com/assets/21295394/19244154/44bf5d84-8f1b-11e6-8046-75f0a3bfd4c9.png)
![2016-10-10_17 57 40](https://cloud.githubusercontent.com/assets/21295394/19244162/4b5e8dfe-8f1b-11e6-8efb-39a7e1659d88.png)
![2016-10-10_17 57 44](https://cloud.githubusercontent.com/assets/21295394/19244164/4c93b2a8-8f1b-11e6-8d1b-6c12de6423e2.png)
![2016-10-10_17 57 45](https://cloud.githubusercontent.com/assets/21295394/19244165/4d768178-8f1b-11e6-8cec-e07f407ac1c0.png)
![2016-10-10_17 57 53](https://cloud.githubusercontent.com/assets/21295394/19244166/4ee78aa2-8f1b-11e6-9a7b-aff71bf8c4a0.png)
![2016-10-10_17 57 55](https://cloud.githubusercontent.com/assets/21295394/19244167/512a259a-8f1b-11e6-81c6-a16059071a9b.png)
#### What you expected to happen:

Nothing
#### Steps to reproduce:
1. Place enderman head
2. Search for @chisel in JEI or NEI
3. Watch
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.10.2-3.0.1.120_beta
- EnderCore: 1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge:12.18.1.2092
#### Your most recent log file where the issue was present:

https://gist.github.com/NillerUdenDild/588531eafd4fb3bcd653d557d5c3ff48

**Comment by kvgeorge1** [comment]
This is also occuring when placing Experience Obelisk

**Comment by frenchiveruti** [comment]
I came here to report the same, breaking the Experience Obelisk makes all my Chisel Blocks render fine, if there is an Experience Obelisk around, all the blocks render wrong.

Pics:
Pre
![2016-11-15_17 20 25](https://cloud.githubusercontent.com/assets/1095997/20322435/db0e1a16-ab57-11e6-870c-46056093aaaf.png)
After
![2016-11-15_17 20 27](https://cloud.githubusercontent.com/assets/1095997/20322445/eb08844c-ab57-11e6-93f5-1a45760a90d9.png)
