### ISSUE TITLE
[1.10] Aversion obelisk not working with certain mobs.

### ISSUE THREAD

**Issue by MrNinja93** [SleepyTrousers/EnderIO#3771]
#### Issue Description:
The Aversion obelisk seems to not register some mobs as non valid to spawn in its range, commonly seen with EnderZoo skeletons and mekanism baby skeletons (note: vials for both in obelisk), I assume its something to do with NBT or Meta tags as they both commonly wear armour.  

#### What happens:
Mobs that are put into the aversion obelisk as soul vials still spawn in the aversion obelisks range.

#### What you expected to happen:
Aversion obelisk to stop spawning of mobs it has soul vials for.

#### Steps to reproduce:

1.Have Aversion obelisk
2.EnderZoo skeletons/Mekanism baby skeletons vial inside (and for testing purposes all other aggresive mobs so they wont outspawn them) 
3. EnderZoo skeletons and baby skeletons still spawn
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.112_beta
- EnderCore: 1.10.2-0.4.1.55-beta
- Minecraft: 1.10.2
- Forge:2094

#### Your most recent log file where the issue was present: 

N/A

**Comment by MatthiasMann** [comment]
Try updating EnderIO & Core - there has been a fix to the skeleton sub type handling.

**Comment by MrNinja93** [comment]
Derp, didn't do a proper search for an existing issue I'll check again with a fully up to date mod versions and see if its fixed/update and close this if it is.

**Comment by MrNinja93** [comment]
That'll teach me not to search 100% of the time, fix fixes both the mekanism's baby skeletons and EnderZoo's fallen knights spawning.

**Comment by HenryLoenwind** [comment]
thx @MatthiasMann, I didn't even notice it was an older version...and I completely forgot that I was actually able to fix that problem then. Off to bed with me!
