### ISSUE TITLE
1.10, Capacitor Bank not adapted to newer Baubles versions

### ISSUE THREAD

**Issue by ArukaAlter** [SleepyTrousers/EnderIO#3773]
Currently on EnderIO 1.10.2-3.0.1.120_beta, the Capacitor Bank GUI needs to be updated with the three new Baubles' slots.

![](https://i1.someimage.com/8UlyEfT.png)

**Comment by HenryLoenwind** [comment]
How did you get it to work with that? Last time I had a look, the crash was rather extreme...
