### ISSUE TITLE
Insulted Redstone conduit Suggestion

### ISSUE THREAD

**Issue by Frost212** [SleepyTrousers/EnderIO#3774]
1.7.10
Would it be possible to add in the ability to select Input OR output on the insulated redstone conduit connectors instead of just input/output. Much like we have with all the energy/fluid conduits? Another suggestion, would it be possible to make it so we can connect them directly to Comparators instead of having to use redstone dust as an intermediary?  (p.s has #3311 been fixed yet? =/)

**Comment by MatthiasMann** [comment]
ENderIO for 1.7.10 is no longer under active development - so it is very unlikely that the redstone conduits will be changed in that version.

**Comment by Frost212** [comment]
Unable to find a message fuction so...What versions are still in active dev? And if so, would it possible to just change this to a suggestion to one of those (Even 1.8.8/1.8.9 if it's still around)?
