### ISSUE TITLE
Cannot Place ingredients in Soul Binder 1.10.2 (3.0.1.117_beta)

### ISSUE THREAD

**Issue by revdave33** [SleepyTrousers/EnderIO#3775]
#### Issue Description:
In trying to use the Soul Binder to bind a new mob type to a broken spawner, I can either place the filled soul vial or the Broken Spawner, but not both at the same time.

#### What happens:
I have a Soul Vial filled with an Iron Golem. I have a Broken Spawner from a Cave Spider. I want to convert the Spawner to an Iron Golem spawner for use in the Powered Spawner. I can place the spawner but not the Vial, or I can place the Vial and not the Spawner.

#### What you expected to happen:
I see from the recipe that I should be able to make an Iron Golem Spawner. I expect to place the Filled Soul Vial with the Iron Golem in it, and the Broken Spawner from the Cave Spider and it would give me a Broken Iron Golem Spawner.

#### Steps to reproduce:

1. Open Soul Binder GUI
2. Place Filled Soul Vial
3. Attempt to place the Broken Spawner
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.117_beta
- EnderCore: 0.4.1.56-beta
- Minecraft: 1.10.2
- Forge:12.18.1.2095

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment]
There is a list in the enderio config folder called:
PoweredSpawnerConfig_Core.json and PoweredSpawnerConfig_User.json

By default these blacklist Villager and the Iron Golem. That's why the soul binder won't bind these to a broken spawner.
