### ISSUE TITLE
Post dependencies on your release sites

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [SleepyTrousers/EnderIO#3777]
Please include information that details required Forge builds and coremod dependencies. Seriously, those are REQUIREMENTS, right?

**Comment by HenryLoenwind** [comment]
![](http://i.imgur.com/vxT0LGQ.png)

**Comment by Rumpelstiltskinny** [comment]
...and Tesla API based on a crash report apparently....class not found

**Comment by MatthiasMann** [comment]
That are diagnosis messages - EnderIO doesn't require Tesla but it will use it if present.
The messages are there to help trace possible causes for a crash.
