### ISSUE TITLE
Tekkit Minecraft 1.7.10 Pack won't load world

### ISSUE THREAD

**Issue by SnowWhite8801** [SleepyTrousers/EnderIO#3778]
My world won't load in the 1.7.10 pack in Tekkit.

So I open the Technic launcher, open the 1.7.10 pack, it loads for a while, the main screen comes up and I go into single player and select my world, then it comes up with "Loading world", and after a few seconds the window closes and it goes back to the Technic launcher. It started doing this a couple of days ago. I hadn't changed anything or updated anything.

I've had a look through the logs and I have tried removing the following mods:

StevesAddons-1.7.10-0.10.16
SimplyJetpacks-MC1.7.10-1.5.3
logisticspipes-0.9.3.127
EnderIO-1.7.10-2.3.0.429_beta
IC2NuclearControl-2.4.2a

However, it still won't load. Sometimes the log won't give me an actual error (not that I'm great at reading logs. I've also had a look through some posts on GitHub and various other sites but I'm really stuck. I would love some help with this! It's always depressing when you have to start a new world if you've come far in the previous one, and this always seems to happen to me too!

Starting a new world works just fine. 

Here's the log:
[http://pastebin.com/iGNpvTG2]

**Comment by MatthiasMann** [comment]
The crash is caused by hardcorequesting - there is nothing related to EnderIO in the stack trace.

**Comment by SnowWhite8801** [comment]
Thanks for that.

I have removed the following mods:
HardcoreEnderExpansion  MC-1.7.10  v1.8.6
HQM-The Journey-4.4.4

The game still exits upon loading the world, and this is the log:
[http://pastebin.com/uBR83k40]

**Comment by MatthiasMann** [comment]
Now your world is corrupted - you can see that at the amount of NBT and chunk decoding errors.

**Comment by SnowWhite8801** [comment]
Oh no :( So just start a new world? And would you suggest not using hardcorequesting again so I can avoid this happening again? This has happened a few times to me now.

**Comment by MatthiasMann** [comment]
No idea - you are asking in the wrong mod. I can't give you any advice to other mods.

But I suggest you always make a backup of your World's save folder when you change anything with mods (either configs, updates etc). Removing mods on an existing world has a good chance to cause corruption - esp when combined with adding new mods.

**Comment by SnowWhite8801** [comment]
Alright. Well thanks so much for your help!
