### ISSUE TITLE
Item conduits causing Tick Loop

### ISSUE THREAD

**Issue by jelaw21** [SleepyTrousers/EnderIO#3779]
#### Issue Description:
We just installed EnderIO and we have been getting server lag. When they chunk load, the server crashes. Upon looking at the crash report, it details that an item conduit is casuing a tick loop. 

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.120
- EnderCore: 0.4.1.56
- Minecraft: 1.10.2
- Forge: 1.10.2  2096

#### Your most recent log file where the issue was present: 
[crash-2016-10-23_22.49.33-server.txt](https://github.com/SleepyTrousers/EnderIO/files/546869/crash-2016-10-23_22.49.33-server.txt)

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
This is caused by sponge.
