### ISSUE TITLE
[3.0.1.120_beta] Aversion Obelisk still permitting Mek's baby skeletons

### ISSUE THREAD

**Issue by xenoflot** [SleepyTrousers/EnderIO#3780]
Hi guys,

The problem raised in ticket #3727 is still happening after updating our server a few days ago. I have verified this extensively in the last 48 hrs by working on a large (~radius 260 blocks), flat, circular area. Aversion obelisks are keeping everything else at bay and I'm getting hammered every night by hordes of baby skels.

Thanks!

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.120_beta
- EnderCore: 1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2107
- Mekanism: 1.10.2-9.2.0.292

**Comment by HenryLoenwind** [comment]
Please confirm that you are using a Soul Vial with a Baby Skeleton in the Obelisk.

**Comment by xenoflot** [comment]
Ah, I see. I figured they would be taken care of with the adult version, as baby zombies are. 
All done, thank you very much!

**Comment by HenryLoenwind** [comment]
No, they are not. Baby zombies are a variant of zombies, baby skeletons are a new type of mob. We could add special code to treat them as a variant, but I'd rather not add too many special cases for more and more mods into Ender IO. It goes unmaintainable very fast (the Farming Station is a nightmare...).
