### ISSUE TITLE
Push / Pull feature sometimes broken

### ISSUE THREAD

**Issue by KillaKlown** [SleepyTrousers/EnderIO#3782]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. I will of course be reporting this to FTB, but wanted to post here as well. FTB Infinity for minecraft 1.7.10, modpack version 2.60.
#### What happens:

After server restarts the push / pull features on at least sag mills and alloy smelters ceases to function until you clear all machine configs, break the machine, place it back down, and reconfigure the side you want to push / pull. This happens with ANY connected inventory, it doesn't matter weather it be chests or ME interfaces.
#### What you expected to happen:

Items from connected inventory get pulled into machine, processed, and returned to inventory.
#### Steps to reproduce:

1.Place Machine
2.Connect it to an adjacent inventory and configure a side to push / pull or both at the same time.
3.Restart server.
...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:
#### Your most recent log file where the issue was present:

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment]
Why didn't you fill out the version numbers?

**Comment by KillaKlown** [comment]
Sorry i didn't notice that part. 
Ender IO: 1.7.10-2.3.0.428_beta
EnderCore: 1.7.10-0.2.0.36_beta
Minecraft: 1.7.10
Forge: 7.10.99.99
