### ISSUE TITLE
Uncompatibility with Chisel2?

### ISSUE THREAD

**Issue by ivanricsan** [SleepyTrousers/EnderIO#3783]
#### Issue Description:
Painting machine doesn't work with chisel2 blocks. After painting glowstone with any Chisel2 texture, the block appears as purple/black (the missing texture)

#### What happens:
You are able to paint the block but the texture is incorrect/missing.

#### What you expected to happen:
The glowstone block gets painted as the other block and so you expect a block to appear as normal but emit light

____
#### Affected Versions:

- EnderIO: 3.0.1.120
- EnderCore: 1.6.326
- Minecraft: 1.10.2
- Forge: 12.18.2.2099

**Comment by HenryLoenwind** [comment]
https://github.com/Chisel-Team/Chisel/issues/253
