### ISSUE TITLE
Client disconnect from nether with entity ID 5

### ISSUE THREAD

**Issue by Paul17041993** [SleepyTrousers/EnderIO#3785]
I literally cannot find a single thing about this particular bug, but when a player attempts to go to the nether they're instantly kicked off the server and left with a wonky "fatal error..." disconnect message. The problematic entity is EnderIO: 5, but what actually is that entity exactly...?
- EnderIO: 2.3.0.429
- EnderCore: 0.2.0.36
- Minecraft: 1.7.10
- Forge: 7.10.99.99

http://pastebin.com/Nnz3DGrk

**Comment by MatthiasMann** [comment]
Probably configuration mismatch between client and server.

**Comment by Paul17041993** [comment]
Which was the first thing I checked for, however I haven't found a difference between the files (yet)...

**Comment by Paul17041993** [comment]
Well I eventually got passed it by disabling 'replaceWitherSkeletons' on just the server, so it's something to do with that...

**Comment by razorrider7** [comment]
This was also happening to me, same versions. My friend was in the nether, and couldn't rejoin after randomly getting kicked.
