### ISSUE TITLE
[1.10.2] Vertical Fluid Conduits Texture Missing

### ISSUE THREAD

**Issue by Yandols** [SleepyTrousers/EnderIO#3787]
#### Issue Description:

Fluid and Pressurized Fluid Conduits, when placed vertically becomes invisible. Problem however does not occur when fluids are passing through it, only when empty.
#### Screenshots Provided:
1. https://i.zxicar.us/dttxa18_Y4v7.png - Conduit texture in the middle is missing.
2. https://i.zxicar.us/y3HEGcF_7bKO.png - Ditto, longer vertical conduit line.
3. https://i.zxicar.us/8RnS3E1Haq9C.png - Problem however does not occur when any conduits are connected to it horizontally.

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: EnderIO-1.10.2-3.0.1.120_beta
- EnderCore: EnderCore-1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: forge-12.18.2.2107
#### Your most recent log file where the issue was present:

N/A - Not a crash.

**Comment by MrNinja93** [comment]
Seen this in 112 too, not limited to vertical either, Seen it happen in horizontal ones that have been placed for a while and were visible at the start (Typical that I cant find any doing so now)

**Comment by MrNinja93** [comment]
Finally seen a conduit being invisible to grab a screenshot.

![2016-11-08_00 08 45](https://cloud.githubusercontent.com/assets/21979276/20081440/9999d11c-a547-11e6-9bd6-9bd884ed7356.png)

Some added quirkiness scrolling through the wrench view modes through to power shows the conduit but back to "show all" view it returns to rendering invisible again.

**Comment by HenryLoenwind** [comment]
This may help. Possibly.
