### ISSUE TITLE
Server lag due to Sawmill input recipes not cached

### ISSUE THREAD

**Issue by LemADEC** [SleepyTrousers/EnderIO#3790]
#### Issue Description:

Server lag in sawmill input checking.

https://i.gyazo.com/e9e6e45200d76faeffdf68d9babacbe4.png
#### What happens:

4% CPU usage due to continuous scan or recipes for valid input items in the SAG mill.
#### What you expected to happen:

Cache valid input items for the sag mills to prevent continuous scanning.

---
#### Affected Versions (Do _not_ use "latest"):

HermitPack 1.1.0
- EnderIO: EnderIO-1.10.2-3.0.1.120_beta.jar
- EnderCore: EnderCore-1.10.2-0.4.1.56-beta.jar
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.2.2107-universal.jar
#### Your most recent log file where the issue was present:

n/a

**Comment by HenryLoenwind** [comment]
That already is the cache...
