### ISSUE TITLE
[1.7.10] Lag with ME Conduits

### ISSUE THREAD

**Issue by Eufranio** [SleepyTrousers/EnderIO#3791]
I have a server, and a world with some months. Recently the server started lagging, I ran WarmRoast to see what is lagging, and it bring me to ME Conduits (compatibility with AppliedEnergistics2), which are part of EnderIO, could you guys take a look?

Report:
[WarmRoast.zip](https://github.com/SleepyTrousers/EnderIO/files/560187/WarmRoast.zip)

Versions:
- EnderIO: 1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 1614

**Comment by MatthiasMann** [comment]
The ME conduits don't do anything on their own - they just register as connection / wire inside AE2 - the rest is handled by AE2.

Also what you see is less than 2% of your total tick time:
crazypants.enderio.conduit.me.MEConduit.updateEntity()1.85%8200ms

AE2 itself uses more time:
appeng.hooks.TickHandler.onTick()5.19%23000ms
