### ISSUE TITLE
Farming Station does not completely chop down ID Menril Trees

### ISSUE THREAD

**Issue by rubensworks** [SleepyTrousers/EnderIO#3792]
#### Issue Description:

As repoted in CyclopsMC/IntegratedDynamics#75, the Farming Station does not completely chop down the Menril Trees from Integrated Dynamics.
Menril Trees consist of two blocks (each having several rotated variants), one for the regular log and another for "filled" logs.
The farming station successfully chops down all regular log blocks, but skips the "filled" logs.
Both blocks are registered in the oredict as "logWood".

Not sure if this can be considered as a bug, or if separate compatibility needs to be implemented for this.
#### What happens:

The Menril Tree is not completely chopped down, the "filled" variant blocks still remain.
#### What you expected to happen:

The Menril Tree must be completely chopped down.
#### Steps to reproduce:
1. Place Farming Station with axe and power
2. Add Menril Saplings to the Farming Station inventory
3. Wait until a tree grows and is (partially) chopped down

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 3.0.1.122_beta
- EnderCore: 0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2091

**Comment by HenryLoenwind** [comment]
The normal TreeHarvester will harvest all blocks that are the same as the starting block plus all kinds of leaves.

So yes, this tree needs a special harvester.

**Comment by SubsterNL** [comment]
On the latest development build of EnderIO and I have yet to see a simple Oak tree to be chopped down completely. There is always or mostly always 1 log left to be chopped down. Not sure why.
