### ISSUE TITLE
[1.10.2] Server thread crash placing Farming Station at Y=62 in a BoP Marsh

### ISSUE THREAD

**Issue by xenoflot** [SleepyTrousers/EnderIO#3796]
#### Issue Description:
OK, really weird one. A player on my server reported her newly-crafted farming station behaving strangely. During my investigation I was able to establish:

* The problem was not unique to her particular farming station. The problem also happened with a spawned one, and one I had been using at my base for a while.
* If placed at Y=62, we get a thread crash on the server. _If placed one block higher or lower, no problem._
* In the capacitor, we see power being drawn. In the farm, the energy buffer remains empty.
* Sometimes saplings are used but not placed.
* I couldn't replicate this problem at my base, so I flew around trying different biomes. Appears to be unique to the BoP Marsh biome and not dependent on chunk borders. I was only able to find two Marshes (opposite sides of the map). Tried in several vanilla and BoP biomes and the problem only appeared in the two marshes.
* A Vat did not exhibit the problem.
* Only happens when the farm tries to **_use_** power, but can be from a conduit or capacitor. For example, if the farm had some stored energy (from a negative test in a non-Marsh biome), simply placing the farm would result in the thread crash. Placing a capacitor next to it, would cause a second thread crash.

#### What you expected to happen:
* Normal farm operation.

#### Steps to reproduce:

1. Find a BoP "Marsh"
2. Place a power source
3. Place a farming station
4. Observe thread crash on server console

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.120_beta
- EnderCore: 0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: 2107
- BiomesOPlenty-1.10.2-5.0.0.2089-universal

#### Your most recent log file where the issue was present: 

http://pastebin.com/2zZgbstX

**Comment by HenryLoenwind** [comment]
That crash report has a truncated stack trace. Could you please look in the logfile for a full stack trace?

**Comment by xenoflot** [comment]
I'm not sure what a full trace looks like, sorry so here's the full log. 
http://southernarmada.org/logs/fml-server-latest.zip

**Comment by MatthiasMann** [comment]
Looks like a bug in BoP - can you report that there too?

**Comment by xenoflot** [comment]
Will do!

**Comment by HenryLoenwind** [comment]
yeah, I remember that...

https://github.com/Glitchfiend/BiomesOPlenty/issues/807
