### ISSUE TITLE
Mod Interaction (reporting else where too)

### ISSUE THREAD

**Issue by DnTheMn** [SleepyTrousers/EnderIO#3798]
#### What happens:
nothing

#### What you expected to happen:
the esd to pull items

#### Steps to reproduce:

1.get esd
2.get vacuum chest configure output 
3.place esd beside and watch as nothing gets pulled out
...

____

- EnderIO: 3.0.1.1,120_beta.jar
- EnderCore: 0.4.1.56
- Minecraft: 1.10.2
- Forge:2012

#### Your most recent log file where the issue was present: 

https://github.com/whatthedrunk/allthemods/issues/227
https://github.com/Ellpeck/ActuallyAdditions/issues/311

**Comment by MatthiasMann** [comment]
Have you tried with a hopper or item conduit to extract items from the vacuum chest?
