### ISSUE TITLE
[1.10.2] Wireless Powered Lights turning into Regular Powered Lights after breaking them after chunk unloads.

### ISSUE THREAD

**Issue by Yandols** [SleepyTrousers/EnderIO#3799]
#### Issue Description & What happens:
Wireless powered lights and its inverted variant turn into regular powered lights after breaking it after a chunk it is in was unloaded and reloaded _(explained better below)_. This ONLY occurs after a chunk has been unloaded. If the chunk still was not unloaded, breaking it will yield its correct form.

#### What you expected to happen:
Wireless powered lights and its inverted variant are supposed to drop themselves upon breaking.

#### Steps to reproduce:

1. Place down wireless powered lights or its inverted variant anywhere in the world
2. Go far enough away so that the chunk the lights are in unloads or simply save and stop the world
3. Go back to the chunk the lights were in or reload the world
4. Break the wireless powered lights
5. They turn into regular powered lights

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.120_beta
- EnderCore: EnderCore-1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: forge-12.18.2.2107

#### Your most recent log file where the issue was present: 

N/A - not a crash.

**Comment by HenryLoenwind** [comment]
I see inverted lights turning into power lights, but the wireless lights seem to work. 

I'll fixed the inverted lights and hopefully that will fix this issue, too.

**Comment by HenryLoenwind** [comment]
oh, I see. The information that a light is "on" destroys its type.
