### ISSUE TITLE
Error on start up

### ISSUE THREAD

**Issue by MCTyler** [SleepyTrousers/EnderIO#3800]
#### Issue Description:
Error on startup

#### What happens:
Several misconfigured config errors reported on startup...Just wondering if there is a way to fix them. This is just one of them...
`[EnderIO]: Missing translation: config.capacitor.attractor_power_intake`

#### What you expected to happen:
To have instructions to configure these items

#### Steps to reproduce:

1. Install EnderIO using default (generated) config files
2. Start server
3. Observer error logs
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.0___beta
- EnderCore: 1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-2116

#### Your most recent log file where the issue was present: 
`[EnderIO]: Missing translation: config.capacitor.attractor_power_intake`

Doesn't really effect game play, just trying to clean up log file.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
