### ISSUE TITLE
A round robin Conundrum

### ISSUE THREAD

**Issue by Haronobu** [SleepyTrousers/EnderIO#3801]
#### Issue Description:
Ender IO Sag Mill and Alloy Smelter on a new Industrial Age the Turning server (1.7.10) Server admins say it's a mod issue. Modpack author says it's not. and I'd like your opinion. If u think u might be able to help I'll repost with appropriate files, otherwise please just point me in the right direction. Thanks

#### What happens:
Sag Mill processes ores from all mods, but will not process "minecraft" items: coal, charcoal, Obsidian, Iron, Gold, Etc. (all these items processed fine in a Single Player world and worked on the official server b4 it shut down in September.
Alloy Smelter won't do Energetic Alloy or Soularium works in SP as above.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
server startup log would tell us what's happening with recipe registration.

**Comment by Haronobu** [comment]
Not a real technical person so where would i find server startup log?

**Comment by Haronobu** [comment]
Is this a log that would be found on the server or on my pc?
