### ISSUE TITLE
Suggestion For Dark Armor

### ISSUE THREAD

**Issue by TheyCallMeGreed** [SleepyTrousers/EnderIO#3802]
#### Description:
I have switftness upgrade on my dark steel leg piece, this causes it to drain 10x faster than other pieces so
if all pieces of the same level of empowered they could share power between tools? for more constistent recharge scedule and the possibilty to use armor as batpack for your tools?
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.120_beta
- EnderCore: 1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2099

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by AnrDaemon** [comment]
Why "of the same"? They could just share the expenses towards equal charge percentage. (So that no single item discharge before any other item.)

**Comment by TheyCallMeGreed** [comment]
i was thinking maybe game balance it would make upgrading all of the armor and tools to a high level maybe less apealing

**Comment by TheyCallMeGreed** [comment]
im not sure about it, it is just a suggestion after all and its up to the modder anyway

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
