### ISSUE TITLE
Problem with Stirling Generator

### ISSUE THREAD

**Issue by Reydenge** [SleepyTrousers/EnderIO#3803]
Hello, i've done my modpack for Minecraft 1.10.2 with this three mods - Tinker's Construct, EnderIO and ImmersiveEngineering. Also i have subsidiary mods like InventoryTweaks, Just Enough Items, Just Enough Resources, TreeChopper. And some addons for Tinker's Construct (TinkerToolLeveling), EnderIOAddons. Forge's versions is the last.
So i started the modpack, created new world, took Stirling Generator and Minecraft crashed. Can you help me with this problem? Thank you.
Here it is crash report. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 03.11.16 17:11
Description: Exception ticking world

java.lang.RuntimeException: info.loenwind.autosave.exceptions.NoHandlerFoundException: No storage handler found for field forceClientUpdate of type class crazypants.util.ResettingFlag of class crazypants.enderio.machine.AbstractMachineEntity
	at info.loenwind.autosave.Writer.write(Writer.java:48)
	at info.loenwind.autosave.Writer.write(Writer.java:117)
	at crazypants.enderio.TileEntityEio.createClientUpdateNBT(TileEntityEio.java:39)
	at crazypants.enderio.TileEntityEio.func_189518_D_(TileEntityEio.java:21)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:249)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
Caused by: info.loenwind.autosave.exceptions.NoHandlerFoundException: No storage handler found for field forceClientUpdate of type class crazypants.util.ResettingFlag of class crazypants.enderio.machine.AbstractMachineEntity
	at info.loenwind.autosave.engine.StorableEngine.cacheHandlers(StorableEngine.java:163)
	at info.loenwind.autosave.engine.StorableEngine.cacheHandlers(StorableEngine.java:180)
	at info.loenwind.autosave.engine.StorableEngine.cacheHandlers(StorableEngine.java:180)
	at info.loenwind.autosave.engine.StorableEngine.cacheHandlers(StorableEngine.java:180)
	at info.loenwind.autosave.engine.StorableEngine.store_impl(StorableEngine.java:120)
	at info.loenwind.autosave.engine.StorableEngine.store(StorableEngine.java:77)
	at info.loenwind.autosave.Writer.write(Writer.java:46)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at info.loenwind.autosave.Writer.write(Writer.java:48)
	at info.loenwind.autosave.Writer.write(Writer.java:117)
	at crazypants.enderio.TileEntityEio.createClientUpdateNBT(TileEntityEio.java:39)
	at crazypants.enderio.TileEntityEio.func_189518_D_(TileEntityEio.java:21)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:249)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: New World=
	All players: 1 total; [EntityPlayerMP['Reydenge'/238, l='New World=', x=-842,51, y=64,00, z=-576,71]]
	Chunk stats: ServerChunkCache: 1097 Drop: 0
	Level seed: -7288467288506973489
	Level generator: ID 04 - customized, ver 0. Features enabled: true
	Level generator options: {"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":0.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":8,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":4,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":4,"riverSize":4,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":9,"ironCount":21,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":9,"goldCount":2,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":8,"diamondCount":3,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":16,"lapisSpread":16}
	Level spawn location: World: (-32,64,256), Chunk: (at 0,4,0 in -2,16; contains blocks -32,0,256 to -17,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 171546 game time, 182392 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1906 (now: false), thunder time: 13703 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 42494216 bytes (40 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2117 Optifine OptiFine_1.10.2_HD_U_C3 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2117.jar) 
	UCHIJAAAA	Forge{12.18.2.2117} [Minecraft Forge] (forge-1.10.2-12.18.2.2117.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAA	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCHIJAAAA	JEI{3.13.0.338} [Just Enough Items] (jei_1.10.2-3.13.0.338.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.125_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.125_beta.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJAAAA	jeresources{0.5.4.67} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.4.67.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	treechopper{1.1.0} [Tree Chopper] (TreeChopper-1.10.2-1.1.0.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/2K/AppData/Roaming/.minecraft/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Reydenge'/238, l='New World=', x=-842,51, y=64,00, z=-576,71]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 7600M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by HenryLoenwind** [comment]
Please try to narrow down which other mod causes this by removing them one by one until it no longer crashes. Start with Optifine, then Inventory Tweaks.

That's faster than me finding those mods in those versions and adding them one by one to my dev env. Thank you.

**Comment by mindforger** [comment]
>crazypants.enderio.machine.AbstractMachineEntity
at info.loenwind.autosave.Writer.write(Writer.java:48)
at info.loenwind.autosave.Writer.write(Writer.java:117)
at crazypants.enderio.TileEntityEio.createClientUpdateNBT(TileEntityEio.java:39)

what the? is this tool calling client side data from a server entitity? or is the naming just off and does the same ?

also this "info.loenwind.autosave" is not listed as mod, where does that come from?

**Comment by HenryLoenwind** [comment]
that's "create the NBT to send as update to the client" or "create the ( (client update) NBT )"

**Comment by HenryLoenwind** [comment]
You have Ender IO Addons in your mod folder, which is a mod for Minecraft 1.7.10.
