### ISSUE TITLE
AE ME Conduit support on 1.10.2

### ISSUE THREAD

**Issue by Binero** [SleepyTrousers/EnderIO#3804]
The modification seems to no longer support AE2 ME Conduits on 1.10.

**Comment by mindforger** [comment]
AE **just** ported over, give em a bit time :)

**Comment by HenryLoenwind** [comment]
Oh, we still support the 1.7.10 ME conduits. If you manage to install an 1.7.10 AE2 in a 1.10.1 Minecraft, you'll see they still work as crappy as before.

.

.

.

Just kidding, the integration is commented out. **scnr**

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by b0bst3r** [comment]
But but it's a known issue that's its missing!!!

**Comment by Binero** [comment]
Yeah, this is a missing feature? Surely it should be an open issue?

**Comment by VT-14** [comment]
Adding support for a resource that Ender IO doesn't directly interact with (in this case, ME network data) is a feature request, not a bug or issue with Ender IO.

It doesn't matter that previous versions had support.  All that does is change the suggestion from "please add _____" to "please re-add _____."

**Comment by DerMax93** [comment]
+1 for a comeback of the conduits

**Comment by Rumpelstiltskinny** [comment]
Considering that the **introductory statement** for Ender IO on Curseforge reads thusly:

"_Compact conduits (RF, items, fluids, redstone, AE2, OC, Mek gas), highly configurable machines, farms, powered tools and armor, not to mention stuff and things!_" 

It seems that conduit compatibility would be high on the TO-DO list, not a feature that once was and is being reconsidered.

Maybe a little more attention to your release page information could ~~reflect~~ advertise the items that **currently** work.

**Comment by VT-14** [comment]
*Changing the description on CurseForge: ~5 minutes

*Reimplement ME Conduits: Likely several hours of work and is heavily dependent on the state of AE2's API.  Considering they are still in the process of porting AE2 to 1.10 (it's in alpha), the API is likely not ready to be used without having to update it almost every time AE2 updates (which is nightly using the download link on their GitHub).

**Comment by Rumpelstiltskinny** [comment]
Either way, paying closer attention to updating STALE information on the release portal is better than ignoring advertised features in the hope that end users can figure out for themselves why advertised features aren't working properly.

**Comment by mindforger** [comment]
>Maybe a little more attention to your release page information could reflect advertise the items that currently work.

@VT-14 don't forget all the cursing about people complaining about details and stuff, this sure takes a lot of time too .... maybe people should write a mod themselfs first before spreading their mimimi about details while the mod officially still is beeing ported in every spare minute .... 

@Rumpelstiltskinny in the time the dev opens your text and shakes his head, he could already have written about 5 lines more code .... and in the same time you could have opened the timeline or use the search to find out that it is beeing worked on

sorry for the rant ... why can't people accept that if you have all hands full of work you can not pay attention to such meaningless details like an false advertised tiny text that will be working with the next release ?!

**Comment by Binero** [comment]
I'm not sure what you mean with your first point. I have actually written
my own minecraft mod, although it has been several years since I last
worked on it.

The only one who turned this into a long thread is Henry. This _is_ a
missing feature, this _is_ falsely reported on the mod page and thus
_should_ be an issue. If somehow you want to claim it is not, then
naturally people will try to get it reopened.

The solution can be to remove the feature from the main page and then mark
it as resolved, but closing an issue without any solution provided is just
not a good practise and it'll cause more trouble than fix it. A more
elegant solution of course would be to simply tag the issue and wait for
the API to become stable.

I'm unsure what the issue tracker is being used for if it is not for
tracking issues.

**Comment by mindforger** [comment]
it was simply Rumpelstiltskinny's annoying **persistence** to "fix" things that are beeing worked on or are beeing absolutely irrelevant to the **actual ongoing progress of porting stuff** 

just for you as an example, another mod dev did not release his mod for weeks and only provided a few people with running versions, everybody was ranting to get hands on it .... then he released it and people were ranting about the unfinished features ..., don't you see that with all that  ingratefull demands the people do, they upset the mod dev ... so when henry said "it is beeing worked on" you shouldn't continue to complain just because he closes the issue to have a shorter active issue list ... he never said he wouldn't fix it

**Comment by Binero** [comment]
This issue is not a rant. It's merely an issue. If the issue tracker isn't
being used for to track issues, than confused comments should come as no
surprise.

By closing unfinished issues, all you do it delay the problem. People will
comment under it saying the issue isn't resolved, and other people will
likely open new ones.

**Comment by HenryLoenwind** [comment]
I fixed the f*ing project description. Happy now?
