### ISSUE TITLE
Charging an item in a Farming Station

### ISSUE THREAD

**Issue by jazzpi** [SleepyTrousers/EnderIO#3805]
Not an issue, just a question: I have a Tinker's Construct lumber axe with a Flux modifier on it (Basic capacitor bank, so 1 MRF). I put this in a farming station to chop trees, but it runs out of power. I tried putting a wireless charger close to the farming station, but that didn't charge it. Is there any other way to charge the items in the farming station?
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 7.10.99.99
- SkyFactory: 2.5.5

**Comment by MatthiasMann** [comment]
Once it runs out of power it is transferred to the output slots - you can then use a chargeable item filter to put it into a capacitor bank and once it is full (same filter again) put it back into the farm.

**Comment by VT-14** [comment]
It would be cool if wireless chargers could charge items in Ender IO machines like the Farming Station, Killer Joe, or Slice n' Splice.  On the other hand it would eliminate the one situation where I though "I need that charge filter."  Still, potential feature request.

If I remember correctly, I saw a charge option in Extra Utilities's (1) Advanced Filter back when I was playing Sky Factory 2.5.  You could try that if the Ender IO version isn't available.

**Comment by MatthiasMann** [comment]
The idea to charge items in other machines besides Killer Joe has been brought up before - and always been declined. Killer Joe is at least a fake player.

The EnderIO chargeable item filter is in 1.7.10 - it works with the Killer Joe.
The question is if the farm will eject empty or broken items already in 1.7.10 or not.

**Comment by tterrag1098** [comment]
Charging items in inventories is a slippery slope of feature creep. If our charger can charge items in our inventories, why not every inventory in the game? The KJ's weapon gets charged by the wireless charger because A) it is "exposed" to the world and B) the KJ is a player, so it fits the existing rules for the wireless charger.

**Comment by tterrag1098** [comment]
Additionally, what @MatthiasMann said is correct, in 1.10 there is a way to remove chargeable items from the farming station.
