### ISSUE TITLE
Crash to desktop. Missing function??

### ISSUE THREAD

**Issue by Vascar** [SleepyTrousers/EnderIO#3806]
#### Issue Description:

From what I found online you seem to be referencing a function the doesn't exist. This causes a crash to desktop as something is generated in the world.

#### What happens:

I was exploring around in my new world and then i crashed to desktop. When I log back into the world it crashes a minecraft jams on the "building terrain" loading screen.

#### What you expected to happen:

To be able to play.

#### Steps to reproduce:

1. Create a world.
2. Roam around until crash.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.125_beta
- EnderCore: 0.4.1.58-beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2119

#### Your most recent log file where the issue was present: 

https://gist.github.com/Vascar/8e1cd0c3e04887efa5295376171da8a1

**Comment by tterrag1098** [comment]
And what exactly led you to believe this was caused by EnderIO? Nothing in the log mentions it.

**Comment by Vascar** [comment]
> EnderIO: ~~ERROR~~ NoClassDefFoundError: net/minecraftforge/fml/common/API

**Comment by tterrag1098** [comment]
That's not part of the crash
