### ISSUE TITLE
Powered zombie spawner weirdness 

### ISSUE THREAD

**Issue by Pallinaama** [SleepyTrousers/EnderIO#3807]
#### Issue Description:
After a lenghty absence, let's say 8 hours, powered spawner bugs out. Drains energy, no spawns and weird bugged area appears nearby.

#### What happens:
Placed powered zombie spawner and used a dropkill setup. After relog no spawns appear and energy drains. Plenty of room. Nearby, usually below spawner a 2x2 area where you cannot place solid blocks appears. You can place water, punji sticks and sand IF you drop the sand in from above. If i move the spawner it works again. Bugged spawner has plenty of room, no excessive entities nearby and spawn checks are disabled. Otherwise default settings. I'm not sure but server reset seems to fix the bugged area and the spawner.

Alternatively i need to move the spawner everytime i wish to disconnect. 

Using ftb utilities to keep area chunkloaded.
My theory is that this bugged block space is preventing monster spawns

#### What you expected to happen:
Spawner to keep spawning after relog.

#### Steps to reproduce:

1. Place spawner
2. Quit for a time, come back
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:3.0.1.120_beta
- EnderCore:0.4.1.56-beta
- Minecraft: 1.10.2
- Forge:12.18.1.2094

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
If you cannot place normal blocks somewhere that means there are mobs at the point. I'd guess there are enough invisible zombies there to prevent further spawns.

**Comment by Pallinaama** [comment]
hmmh latest anomaly is 1x2 area above spawner .. maybe ill just fill it with sand and see what happens.

**Comment by HenryLoenwind** [comment]
invisible, untouchable, unmovable, unkillable zombies, I'd say. I just don't know why they are bound to the spawner---we don't keep any references to the mobs we spawn.

**Comment by Pallinaama** [comment]
Moving the spawner horisontally (maybe too little ) had no effect but when i moved it up about 6 blocks it started spawning again normally. Not a solution obviously but it's something atleast.

**Comment by HenryLoenwind** [comment]
so maybe you just moved it out of range of the phantom mobs. That'd make sense.

**Comment by Pallinaama** [comment]
This would be my guess too. First I tried /kill @e[type=Zombie] with no luck. Just got some 'Killed Zombie messages with no visible results and still no spawning. Can't guess on the number of invis zombies but it's strange that they had no effect on game performance and the check for entities number was disabled in config.

**Comment by HenryLoenwind** [comment]
Just to double check; did you also set poweredSpawnerMaxNearbyEntities to 0 or just disable poweredSpawnerUseVanillaSpawChecks?

**Comment by HenryLoenwind** [comment]
I don't think I'll find what's happening today. Next time it happens, could you please enable hitboxes (F3+B) and have a look for invisible zombies/baby zombies/chickens? Thx!

**Comment by Pallinaama** [comment]
MaxNearbyEntities=0,MaxPlayerDistance=0 and vanilla checks false.  Tried the hitbox thing but saw nothing. First time this happened there was a number of chickens about on the ground, maybe left by baby zombies and I can't be sure but I seem to recall that after I killed those ( around 10 ) the spawner spawned 1 zombie once or twice.

**Comment by dualmoon** [comment]
https://t.gyazo.com/teams/airside/75d054f87f1650c78e4bc201da60bdd7.png

So I'm getting something similar and I'm wondering if it's related. That hole is where my spawner was. There's about 8 skeletons or so all stacked together. They take damage but when they're at about 4.5 health left they take no more damage. issuing a /kill says it kills a bunch of skeletons but these nerds remain.

**Comment by EnragedRabisu** [comment]
I'm having the same issue as dualmoon on Infinity Lite 1.8.0 (Minecraft 1.10.2 with EnderIO 3.1.156, EnderCore 0.4.1.65, and Forge 12.18.3.2254).

It only seems to halt my skeleton and wither skeleton spawners, and it seems to exclusively occur with skeletons. They spawn inside of a block and enter this glitched state. Using '/kill' doesn't affect them, nor does attacking them. Using a soul vial captures the mob, but the entity remains bugged in place.

**Comment by HenryLoenwind** [comment]
@EnragedRabisu Does the entity stay or are there multiple ones at the same location? (Reason for the question: I have code in the soul vial to make really, really sure captured entities don't stay around.)

**Comment by EnragedRabisu** [comment]
The first time it happened, there were definitely a lot of them (So many that touching them shoved me away at high speeds), but I pulled out skeletons for several minutes with a pair of soul vials. Second time it looked like only one or two, but I still pulled several out.

I left my spawners running for a few minutes and left the area. I came back to this: https://imgur.com/a/orsxL
I seem to pull the same skeleton out of the 'pile' every time as well. This time it has an enchanted bow.

Notably, I removed my Skeleton spawner, so I can only assume it has something to do with the wither skeleton spawner I still have in there. For completion's sake, I also have slimes, enderman, witches, creepers, zombies, spiders, and blazes. I'll remove the wither skeleton spawner this time before I leave for class to try and narrow things down further.

**Comment by tyler489** [comment]
Relates to #4362 prehaps?

**Comment by Darinth** [comment]
My base instinct for the initial problem is actually a problem with FTB Utilities chunk loading. It's bugged to all hell, at least in the 1.10 FTB Beyond pack. I ran into a wide variety of issues. It seems like it's doing something that is improperly keeping chunks loaded which resulted in all sorts of machines bugging out. I ultimately just enabled Extra utilities chunk loading wards and disabled the FTB Utilities chunk loading.
