### ISSUE TITLE
MP Dedicated Server Crash

### ISSUE THREAD

**Issue by GodsVictory** [SleepyTrousers/EnderIO#3808]
- EnderIO: 1.10.2-3.0.1.125_beta
- EnderCore: 1.10.2-0.4.1.58-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2099

#### Your most recent log file where the issue was present: 

https://gist.github.com/GodsVictory/0ce3b237da72f48d3a503d7ccd821ddf

**Comment by MatthiasMann** [comment]
Why do you think this has anything to do with EnderIO ?

**Comment by GodsVictory** [comment]
Looks like I attached the wrong log, my apologies. I'll come back if the other error comes back.
