### ISSUE TITLE
Energy conduit does not take power from thermoelectric generator Immersive engineering

### ISSUE THREAD

**Issue by TheMrCaveman** [SleepyTrousers/EnderIO#3809]
#### Issue Description:
Energy conduit does not take rf power from thermoelectric generator This used to work in 1.7.10!

#### What happens:
Place down a thermoelectric generator setup. 
Connect energy conduit from thermoelectric generator to vibrant capacitor bank.
No energy is transported

#### What you expected to happen:
rf flow from thermoelectric generator to capacitor bank 

#### Steps to reproduce:

1.Place down a thermoelectric generator setup.
2.Connect energy conduit from thermoelectric generator to vibrant capacitor bank.
3.Try to make working connection
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.125
- EnderCore:1.10.2-0.4.1.58
- Immersive Engineering 0.10-48 
- Minecraft: 1.10.2
- Forge:12.18.2.2114

**Comment by HenryLoenwind** [comment]
rf is "push" based, so it's up to the generator to push energy to the conduit. If the conduit visually connects, it is open to accept those pushes.

**Comment by TheMrCaveman** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1663 Done!

**Comment by HenryLoenwind** [comment]
IE's fixation of using its internal energy system and only interfacing using their connectors seems not to be too user friendly.
