### ISSUE TITLE
[1.10] Additional hoes to add

### ISSUE THREAD

**Issue by b0bst3r** [SleepyTrousers/EnderIO#3811]
****Amendments 
Remove or amend existing**
appliedenergistics2:item.ToolCertusQuartzHoe
appliedenergistics2:item.ToolNetherQuartzHoe
Railcraft:tool.steel.hoe

****Replace with**
appliedenergistics2:nether_quartz_hoe
appliedenergistics2:certus_quartz_hoe
railcraft:tool_hoe_steel

****Additions**
calculator:ReinforcedHoe
calculator:EnrichedGoldHoe
calculator:ReinforcedIronHoe
calculator:RedstoneHoe
calculator:WeakenedDiamondHoe
calculator:FlawlessDiamondHoe
calculator:FireDiamondHoe
calculator:ElectricHoe
embers:hoeDawnstone
embers:hoeCopper
embers:hoeSilver
embers:hoeLead
roots:livingHoe

I didn't add the draconic evolution hoe due to it's high RF capacity and the End Forged Hoe from calculator due it having no durability or the ender hoe from ender utilities because that seems to not have durability either.

**Comment by HenryLoenwind** [comment]
Thank you.
