### ISSUE TITLE
Killer Joe

### ISSUE THREAD

**Issue by maxiboy211** [SleepyTrousers/EnderIO#3812]
**#### Affected Versions:**
**- EnderIO:** EnderIO-1.10.2-3.0.1.120_beta
**- EnderCore:** EnderCore-1.10.2-0.4.1.56-beta
**- Minecraft:** 1.10.2
**- Forge:** forge 1.10.2-12.18.2.2121

Killer Joe doesn't accept swords from other mods by default. Don't know if it's intentional or not, sorry if it's not an issue and is there a config file for that? Also, are there any plans to add this?

**Comment by HenryLoenwind** [comment]
It is not intentional but forced onto us by the technical impossibility to correctly render other swords.
