### ISSUE TITLE
[Question] What is the preferred method for changing core EnderIO alloy recipes?

### ISSUE THREAD

**Issue by utoc** [SleepyTrousers/EnderIO#3813]
Simple question:

I want to change the bronze recipe in the EnderIO alloy smelter to spit out a specific mod's bronze ingot.  The bronze recipe is found in the Core AlloySmelter XML, how do I overwrite this core recipe in the user recipe file?  My understanding is that we shouldn't edit the core files, is this correct?

What I've got so far, editing the user file: http://i.imgur.com/tLvT8w1.png

The core recipe for oreBronze is at the top and the user recipe, techreborn:ingot:2 is at the bottom.

Thanks for taking a moment!

**Comment by HenryLoenwind** [comment]
To get a specific type of ingot you edit the oreDict preferences XML, not the recipe.

**Comment by utoc** [comment]
Thank you!
