### ISSUE TITLE
Fluid Conduit and lightning

### ISSUE THREAD

**Issue by excelmad** [SleepyTrousers/EnderIO#3814]
I'm playing with Ender IO 1.10.2  version 128 beta , it works pretty well i'm just here to ask you something for next update.

Could you please add an option in config file to remove light or reduce light when lava (or other liquid) is throwing a fluid conduit ?

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
