### ISSUE TITLE
Not All Hoes in Farming Stations Work

### ISSUE THREAD

**Issue by Darkosto** [SleepyTrousers/EnderIO#3815]
#### Issue Description:

A Supremium Hoe from Mystical Agriculture does not work in the Farming Station, even when marked as true in the config. This was working in past updates.

#### What happens:
The hoe will not work in the station.

#### Steps to reproduce:

1. Mark as true in config
2. Try to insert or shift-click it in
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.128
- EnderCore: 0.4.1.58
- Minecraft: 1.10.2
- Forge: 2122

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by JorgenHedlund** [comment]
I'm on 3.0.1.126 (part of allthemods modpack 1.43) and can confirm similar issue -- but with vanilla hoes. (been reporting to modpack owner too) https://mods.curse.com/modpacks/minecraft/242462-all-the-mods

**Comment by SubsterNL** [comment]
I have yet to find any hoe which is not vanilla to work in the station. Also the charged item filter doesn't appear to work. The same aplies to killer joe where it basically doesn't except any weapon except vanilla or 'the ender'.
