### ISSUE TITLE
Console/Log Spam

### ISSUE THREAD

**Issue by Darkosto** [SleepyTrousers/EnderIO#3816]
#### Issue Description:

I've been getting some pretty extensive console spam:

[16:28:46] [Server thread/WARN] [EnderIO]: NetworkedInventory.itemExtracted: Inserted 4 Rare Lootbag but only removed 1

This happens about twice a second while I'm using an Item Conduit to pull from a storage drawer and insert into another inventory. This happens in both single player and on servers.

#### Steps to reproduce:

1. Pull from a compacting drawer and insert into another with conduits
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

EnderIO: 3.0.1.128
EnderCore: 0.4.1.58
Minecraft: 1.10.2
Forge: 2122

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
That means that you are duping items. Could you please check your numbers if that really is the case?

The message says that the drawer said that we could remove 4 bags from it, but when we did so, we only got one.

**Comment by Darkosto** [comment]
Interesting! Let me do some testing and see what else I can come up with to help you out. Thanks for the initial response and hopefully I can get some more information :)

**Comment by Darkosto** [comment]
Alright, looks like after removing the conduits and replacing them has stopped the spam. The setup is the same, but looks like it fixed it up. If anything pops up again I will let you know. Thanks!
