### ISSUE TITLE
Latest updates breaks KillerJoe

### ISSUE THREAD

**Issue by SubsterNL** [SleepyTrousers/EnderIO#3818]
#### Issue Description:
KillerJoe has no XP slot anymore and spills all XP on floor after 1.10.2-3.0.1.122_beta build. Latest version still shows this behaviour.

#### What happens:
Killerjoe stopped working properly

#### What you expected to happen:
XP slot in KillerJoe should be there and XP should be absorbed

#### Steps to reproduce:

Works fine in 1.10.2-3.0.1.122_beta build. Upgrading to later build and newer endercore will break KillerJoe.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: Any version higher than 1.10.2-3.0.1.122_beta:
- EnderCore: Any version higher than 1.10.2-0.4.1.54-beta
- Minecraft: 1.7.10, 1.10.2
- Forge: 12.18.2.2122 (and previous versions as well)

#### Your most recent log file where the issue was present: 
[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
see changelog

**Comment by SubsterNL** [comment]
I'm sorry but what in the changelog should I be looking at. There is nothing there about this issue.

**Comment by SubsterNL** [comment]
No idea how to read the cryptic changelog. Killerjoe does not attract XP orbs anymore, they just float around.. The changelog says different. The current state basically makes it useless.

Not sure why anyone would remain using the killjoe if it all it does is kill. Easier and cheaper ways of doing it.

Please enlighten me :)
