### ISSUE TITLE
[1.10] magnet re-texture has some weirdness

### ISSUE THREAD

**Issue by b0bst3r** [SleepyTrousers/EnderIO#3819]
http://i.imgur.com/4gyyuzw.png

Seems to blank out the middle of it when in game

**Comment by HenryLoenwind** [comment]
please try with a texture that is one solid color to see what happens.

**Comment by b0bst3r** [comment]
100% white texture = http://i.imgur.com/laleZcA.png

**Comment by HenryLoenwind** [comment]
Um, yeah, I remember now. The magnet actually is a 3d model because it also is used to render on the player when in the baubles slot...

**Comment by HenryLoenwind** [comment]
I think this is answered now? You also need to edit the model if you want to retexture it. Just be aware that the model is used when rendering the magnet on the player. The space within the magnet has just the right size for the player's neck.
