### ISSUE TITLE
right click crop handler

### ISSUE THREAD

**Issue by s1ammykhan** [SleepyTrousers/EnderIO#3820]
#### Issue Description:
minecraft is crashing on me when i add in ender io to the modpack

#### What happens:
crash after phase 3 of mods initialisation finishes

#### What you expected to happen:
well that it wouldnt crash my game

#### Steps to reproduce:

1.place mod in modx folder
2.start up minecraft with forge
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: beta 2.3.0.428
- EnderCore: beta 0.2.0.39
- Minecraft: 1.7.10
- Forge: 1566

#### Your most recent log file where the issue was present: 

http://pastebin.com/4FNN8fyH

**Comment by HenryLoenwind** [comment]
Please check you endercore config file, it seems like there's an empty crop definition there.

**Comment by s1ammykhan** [comment]
@HenryLoenwind then i get this... which is what i tried to remedy in the first place

http://pastebin.com/K5vn2eKm

**Comment by s1ammykhan** [comment]
oh i see whats going on. i was supposed to deleted the whole section for beetroot. not just seed part. thank you for that! big help
