### ISSUE TITLE
Can't reset Vibrant caps in crafting grid

### ISSUE THREAD

**Issue by xenoflot** [SleepyTrousers/EnderIO#3821]
I'm sure that I used to be able to reset all EnderIO machines by putting them in the crafting grid. Found tonight that I was unable to do that with a Vibrant cap. Haven't tested with other machines.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.128_beta
- EnderCore: 1.10.2-0.4.1.58-beta
- Minecraft: 1.10.2
- Forge: 2122

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by xenoflot** [comment]
Just tested some more. Basic and regular cap banks are also affect.

Vats and Soul Binders reset in the crafting grid as expected.

**Comment by HenryLoenwind** [comment]
I had a look and we do not have a recipe to clear capBanks. Those are not "machines" on a technical level, so the "clear machine config" recipe doesn't engage. I'd call that an oversight.
