### ISSUE TITLE
Unable to infuse broken spawners with a soul vial

### ISSUE THREAD

**Issue by xenoflot** [SleepyTrousers/EnderIO#3822]
#### Issue Description:
Player reported that he can't infuse a broken spawner with a wither skeleton. He has no admin powers so will have acquired all the parts in survival.

#### What happens:
I tested by spawning in a Soul Binder, broken blaze spawner and soul vials for wither skel, ghast and bat.
The Soul Binder accepts the vial, spawner and XP then just sits there and does nothing. I reset the machine in crafting grid, tried various redstone settings and flipped a lever a few times. Nothing made it work.

This appears to be a new problem as I was able to infuse a whole bunch of spawners for my own base a few weeks ago.

#### Steps to reproduce:

1. Insert soul vial and broken spawner
2. Click "take xp from player"
3. XP goes 8/8 with green text.
... nothing further happens

____
#### Affected Versions (Do *not* use "latest"):

-    EnderIO: 1.10.2-3.0.1.128_beta
-    EnderCore: 1.10.2-0.4.1.58-beta
-    Minecraft: 1.10.2
-    Forge: 2122

#### Your most recent log file where the issue was present: 

Clients and server logging in debug but nothing related appearing.

**Comment by HenryLoenwind** [comment]
I tested both in singleplayer and multiplayer, it works fine for me. There may be either some other mod interfering or those mobs got blacklisted in the config server-side.

(You **did** power the Soul Binder?)

**Comment by xenoflot** [comment]
Worth asking, but yes I did :-)

I shall do some more testing after I've had some sleep and get back to you.

**Comment by xenoflot** [comment]
OK, I tested in SSP and it works fine. Tried again on the server and still no go. Server has restarted since, so it's not that. I guess the next step is to download the server and run it up locally.

We already run the server with debug logging. Is there additional debugdebug that I can activate for EnderIO?

**Comment by xenoflot** [comment]
Found it! 

I found that after deleting the enderio.cfg, it worked with the freshly created file so I compared the two and found I:soulBinderBrokenSpawnerLevels=8 vs my original of I:soulBinderBrokenSpawnerLevels=15.

When updating mods, we just put in the new mod.jar file and leave the existing config file in place. At some point recently it seems that you've adjusted the XP levels required for various things, including that required to infuse a broken spawner.

Our config file specified 15 levels but the Soul Binder GUI only wants, and only accepts, 8 levels. Switching I:soulBinderBrokenSpawnerLevels between 15 and 8 is the difference between it working and not working. So looks like the Soul Binder isn't supporting the config option at the moment.

Cheers!

**Comment by HenryLoenwind** [comment]
Did you keep those values in sync between client and server? The GUI (including the "use player XP button") uses the value from the client's file but the processing then uses the server value.

**Comment by xenoflot** [comment]
Perhaps initially but not during upgrades. I didn't set up the pack originally but I recently rebuilt the pack to use Solder. I noticed during my testing that EnderIO said that it was pulling a copy of the config down from the server which I figured was a good thing so I left it to it.

Since our server enderio.cfg was set to 15 but the clients were showing 8, that suggests either I screwed up or the copy from server didn't do that bit. I'll test that again later.

**Comment by xenoflot** [comment]
In retrospect, I may be confusing that config sync with tconstruct.  Sorry for wasting your time! Looks like it was just sloppy admin on my part.

As an aside, if you're bored, you might look at putting something on the client side that updates the local config to match what's on the server.

**Comment by HenryLoenwind** [comment]
It doesn't pull the whole config but only a select few critical values. Those that were critical when that sync feature was first implemented...

Our config is so huge, nobody wants to really touch it. But it is in need for reimplementation using one of the available frameworks which include full syncing.
