### ISSUE TITLE
XP vacuum doesn't work as good as killer joe did

### ISSUE THREAD

**Issue by Yadokingu** [SleepyTrousers/EnderIO#3823]
With the XP vacuum I have the problem of XP orbs getting stuck quite often, even when there is seemingly nothing in the way. I never had those problems with the killer joe it would reliably suck in orbs.
I have to add that there are killer joes close to the vacuum. Could it be that they are fighting over the orbs because they have mending swords inside? If so I don't see a good solution to that, since the vacuum has to be close to where things are killed. It seems this whole thing was a lot more consistent when the killer joes handled the XP.

1.10.2-3.0.1.125-beta

**Comment by HenryLoenwind** [comment]
Yes, mending would try to pull in some orbs, but in my test the Killer Joe had no problem wining the fight. It has the stronger pull.

Could you post a pic or two on the stuck orbs? I might be able to see what needs tweaking there.

**Comment by Yadokingu** [comment]
It got better after I changed the setup a bit more, but there is always one orb that bounces between the vacuum and killer joe. I guess mending doesn't use up all of the ball and the joe has nowhere to put the rest?
https://imgur.com/a/XPEBp

**Comment by HenryLoenwind** [comment]
Your guess is right.

I'll have a look if I can reduce the conflicts a bit on the weekend. They will never go away completely, as the KJ will start and stop attracting for its mending, but I think I can reduce it a good bit. First step would be to not start mending for each and every point of damage...

**Comment by SubsterNL** [comment]
I'm having the same issues. Sometimes having to even install 2 xp vacuums because the orbs even get stuck on something that appears flat like te top of a powered spawner.

Wouldn't stop mending on every point of damage make the ability useless?
 Since eventually your tool will break anyway?

**Comment by HenryLoenwind** [comment]
No, it would just not start mending unless durability got below, e.g., 90% and then men it up to 100% to stop again. Much like a laptop charges its battery.

**Comment by Yadokingu** [comment]
I can confirm what SubsterNL said though. XP orbs kept getting stuck even when I just had half slabs around the vacuum in the second picture. I had to actually remove all blocks around it to get it to work right. No such problem with the killer Joe, when it still sucked up XP. Just out of curiosity, was there a particular reason that feature got removed? The removal seems to cause quite a few problems.

**Comment by HenryLoenwind** [comment]
It got removed because (a) it had problems with orbs getting stuck and (b) we don't want the functionality being doubled.

You picture actually looks fine. The orbs are in pickup range, so I'd say the fluid conduit (or whatever you're using) is the limiting factor.
