### ISSUE TITLE
Inhibitor Obelisk doesn't prevent endermen from teleporting

### ISSUE THREAD

**Issue by Yadokingu** [SleepyTrousers/EnderIO#3824]
endermen don't seem to be phased by the obelisk. See attached picture, where the range that covers the entire area is visible in white and yet there are two endermen who teleported out of the spawner area.

Also there are minor graphical bugs. The power bar of the obelisk isn't quite right and when it's in the players inventory it screws up the graphic of the shield slot.

https://imgur.com/a/qal1c

1.10.2-3.0.1.125-beta

**Comment by HenryLoenwind** [comment]
The inhibitor prevents teleporting **into** its range, not out of. Also, I don't think it effects mobs, but I'll have to check the sources again.

About the rendering issues: I'll look into that.

**Comment by Yadokingu** [comment]
Okay. Maybe a tooltip that is a bit clearer would be good then. At the moment it says "prevents teleporting within it's range of effect.". I read that as there isn't any teleporting within it's range, period. It also says nothing about mobs not being effected.
These endermen teleported from one point inside the area of effect to another, still inside the area.

**Comment by HenryLoenwind** [comment]
So, this should do what's expected. There are two error cases left:

* teleporting **through** its area of effect still works, jus **into** and **out of** are prevented
* Shulkers are uneffected (see https://github.com/MinecraftForge/MinecraftForge/issues/3383 )
