### ISSUE TITLE
Null Pointer When Calling up Tesla API

### ISSUE THREAD

**Issue by paulccorey** [SleepyTrousers/EnderIO#3825]
#### Issue Description:
Running a HermitPack server, and every time the system crashes (4-5 times daily) it comes up with this error... I attributed it with lag, but it seems to be happening more and more lately.

http://pastebin.com/tQ3rC3aC

#### What happens:
From what I can tell from the error report, it gets a null pointer error whenever enderio is trying to use the Tesla API... which makes sense because the Hermitpack doesn't include Tesla

#### What you expected to happen:
... the server not to crash

#### Steps to reproduce:

1. Still
2. Working
3. On this.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.120_beta
- EnderCore: 1.10.2-0.4.1.56-beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2099

#### Your most recent log file where the issue was present: 

http://pastebin.com/tQ3rC3aC

**Comment by HenryLoenwind** [comment]
You annoyed that you get diagnostics on what is installed after a crash?

**Comment by DigitalSketch** [comment]
It would appear he's trying to figure out why Ender IO is giving a Tesla error over and over, There doesn't appear to be any Tesla mod installed, and Ender IO is trying to get to check for Tesla.  Would appear to be a bug report and that he's hoping for a resolution.  I didn't get any "annoyed that you get diagnostics" from that post..   Wish I could help ya out there paulcorey, hope you can get it resolved quickly and friendly.

**Comment by paulccorey** [comment]
That was slightly rude, but I understand... what I posted wasn't an error, it was just letting me know that Tesla wasn't installed.... thank you captain obvious.

Yeah I wasn't annoyed by the report... I misunderstood the report as being part of the error reporting, my bad.

**Comment by HenryLoenwind** [comment]
That label should explain why I'm a bit short tempered on this. Sry.
