### ISSUE TITLE
[Suggestion] Allow liquid lookups in JEI from gui tanks

### ISSUE THREAD

**Issue by mezz** [SleepyTrousers/EnderIO#3826]
A recent JEI API addition allows mods to define what ingredient is under the mouse. You can use this to let JEI know when there is a tank of some fluid under the mouse, for recipe lookups. It is defined in `IAdvancedGuiHandler`.

Forestry's implementation is here:
https://github.com/ForestryMC/ForestryMC/commit/2ae52451b23bc01550939cd1f9603de225fe7c3d

**Comment by HenryLoenwind** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/853e62fa917ffd39fc249d9757ea946920c8de5a

Thanx!
