### ISSUE TITLE
[Suggestion] Liquid XP -> Mending

### ISSUE THREAD

**Issue by VT-14** [SleepyTrousers/EnderIO#3827]
I would like to be able to use my massive supply of Liquid XP to repair items that have the Mending enchantment.  Compatibility with Tinkers' Construct Mending Moss would also be appreciated.  I can think of three possible implementations.

1) Glass bottles can be filled with liquid XP to make Bottle o' Enchanting bottles.  The Minecraft wiki states that a Bottle o' Enchanting will drop somewhere between 3 and 11 experience, and it would be quite reasonable for this to be a slightly inefficient method of mending tools.  I would suggest each bottle costs around 10 to 15 experience points worth of liquid xp (Ideally 11+ to ensure no cases where you might get more xp than you started out with).

2) Experience Obelisk gets 'drop as XP orbs' button(s).

3) Liquid XP can be used for mending directly in certain Ender IO machines.  This could be added to the Experience Obelisk; or a new machine could be added, like a Liquid XP Infuser.  The Killer Joe (or an upgraded version of it) could also accept liquid XP for mending and remove all experience orb attracting as an alternative fix for #3823.

**Comment by HenryLoenwind** [comment]
4. The Tank could treat items with mending like fluid containers that take liquid XP.

**Comment by BrainStone** [comment]
When this gets implemented it would be awesome if it also worked with TConstruct tools with Mending Moss!

**Comment by predakanga** [comment]
For reference, my go-to assumption in 1.10.2 was to try to find something like OpenBlocks' XP Shower. Not saying that EIO should necessarily take this route (I assume it's quite lag prone), but that is an established user experience to consider.

Regardless of implementation, would greatly appreciate this.

**Comment by HenryLoenwind** [comment]
Our version of the XP shower was in Ender IO Addons, which hasn't been ported to 1.10 yet because I was drafted to do the Ender IO porting. And now that I finally could find some time, 1.11 has arrived...

**Comment by HenryLoenwind** [comment]
This works with everything that has the vanilla enchantment, I don#t know how that moss is implemented.

More uses for liquid XP may come later.

**Comment by BrainStone** [comment]
I guess you would need to use the TConstruct API for the moss.
