### ISSUE TITLE
Bound Blade doesn't use LP in Killer Joe

### ISSUE THREAD

**Issue by Peach774** [SleepyTrousers/EnderIO#3829]
Bound Blade from Blood magic does not consume LP when placed in the killer joe.
This is in the newest Ender IO for 1.10.2 along with the newest blood magic.

**Comment by MatthiasMann** [comment]
Why did you delete the template?

**Comment by HenryLoenwind** [comment]
We do not care about LP, EU, RF, FE, IF, Mana, Damage, or whatever the weapon may or may not have, consume, spit out, ... We just tell it to hit the target.
