### ISSUE TITLE
[1.10.2] Baubles slot in Capacitor Bank GUI pass null to canEquip from Baubles

### ISSUE THREAD

**Issue by BrainStone** [SleepyTrousers/EnderIO#3830]
#### Issue Description:
When trying to put an item in the Baubles slot of a capacitor GUI the second parameter (EntityLivingBase) is null. Which will lead to a NullPointerException when you try to access it or members of it.

#### What happens:
A null reference gets passed and if accessed the game crashes with a NullPointerException.

#### What you expected to happen:
Getting passed a valid EntityLivingBase.

#### Steps to reproduce:

1. Implement an item that accesses the entity while calling canEquip from Baubles
2. Try to place the item in a Baubles slot in the Capaciot Bank GUI
3. Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-0.4.1.58-beta
- EnderCore: 1.10.2-0.4.1.58-beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2124

#### Your most recent log file where the issue was present: 

http://pastebin.com/i1BgkEZY

**Comment by HenryLoenwind** [comment]
```boolean isItemValidForSlot(int index, ItemStack stack);```

There's no player for us to pass to Baubles, I don't know where Baubles does (or in this case doesn't) get the player from.

**Comment by HenryLoenwind** [comment]
Smalls a bit like https://github.com/Azanor/Baubles/issues/121

**Comment by BrainStone** [comment]
Maybe try `Minecraft.getMinecraft().thePlayer`?

**Comment by HenryLoenwind** [comment]
Sorry, neither

```baubles.isItemValidForSlot(Minecraft.getMinecraft().thePlayer, stack)```

nor

```baubles.isItemValidForSlot(slotno, Minecraft.getMinecraft().thePlayer)```

compiles.

.

.

(scnr)

**Comment by BrainStone** [comment]
I see. So you're saying this is more of a Baubles issue, right?  
I can report it over there.

**Comment by HenryLoenwind** [comment]
Yes, that's what I was implying. Wanted to have a look at the Baubles code myself before stating it as fact, but time flies :-(

**Comment by BrainStone** [comment]
Reported. Azanor/Baubles#171

**Comment by mindforger** [comment]
didn't we had this issue earlier? in 1.7.10 already? clicking a capacitory crashing while having somethign in the bauble slots?

**Comment by HenryLoenwind** [comment]
Yes, @mindforger, that is the issue I linked in above.

**Comment by HenryLoenwind** [comment]
solved
