### ISSUE TITLE
[1.10.2] Successfully writing in the Access Code for a Travel Anchor does not allow travel

### ISSUE THREAD

**Issue by 501warhead** [SleepyTrousers/EnderIO#3836]
#### Issue Description:
Travel anchors, when set to "Protected" mode, are impossible to travel to even if you know the password.
After you validate the password nothing happens.

#### What happens:
In the following gyfcat the travel anchor "Pickles" is protected by the following passcode:
* Stone - Stone - Stone - Stone - Stone

And I attempt to travel to it.

https://gfycat.com/EarnestWarmEasternglasslizard

Wordy:
I attempt to travel, I input the stone into the slots, when I click "Validate" the GUI closes, I get no other notification or confirmation. Attempting to Travel again asks for the password again.

Also note, as per [this screenshot](http://i.imgur.com/4I7Z2C2.png), the Travel Anchor **is** validating the password. It seems to be the process after the correct password has been validated which is causing the problem.

#### What you expected to happen:
When I click validate I expect to either warp to the anchor or to become able to freely warp to the anchor.

#### Steps to reproduce:

1. Have someone else place down a Travel Anchor (You can always warp to your own no matter the setting)
2. Have them set it to Protected and give them the code to input, or if using Alternate Account input it on your own
3. Attempt to travel to the Anchor (Tested VIA both other anchor set to public and Staff of Travelling)
4. Fill out correct password
5. Click Validate
6. Attempt to travel
7. Steps 3-6 repeat

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.125_beta
- EnderCore: 1.10.2-0.4.1.58-beta
- Minecraft: 1.7.10
- Forge: 12.18.2.2120

As the pictures/gifs indicate this is inside of a mod pack. I made certain to only use vanilla items so that potential mod conflict causing these problems was at an absolute minimum, but the risk is still there that perhaps something was messing with the items themselves, although the validation does work so I do not believe this to be the case. Sadly I don't have time to recreate it in a clean, fresh installed forge w/ only EnderIO & EnderCore installed.

#### Your most recent log file where the issue was present: 

N/A - Gameplay problem

**Comment by HenryLoenwind** [comment]
has been broken since 2015-11-19...
