### ISSUE TITLE
Conduit recipes produce -1 product

### ISSUE THREAD

**Issue by Short-Circuit** [SleepyTrousers/EnderIO#3837]
#### What happens:
Crafting any conduit in any crafting interface creates -1 conduits. The item may still be used, but cannot be stacked, and does not consume when placing, making it essentially infinite. This bug occurs for all conduits.
[Screenshot 1](https://puu.sh/sizGA/eb9764bdd6.png)
[Screenshot 2](https://puu.sh/siAe2/61b7086d81.png)

#### What you expected to happen:
The recipe was expected to produce 1 conduit as usual

#### Steps to reproduce:

1. Place necessary ingredients for any conduit in any crafting interface
2. Attempt to craft the item

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.429_beta
- EnderCore: 0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1566

#### Your most recent log file where the issue was present: 

https://puu.sh/siAlM/45c098034c.log

**Comment by HenryLoenwind** [comment]
Check your Ender IO config file, the number of conduits per recipe is configured there.

**Comment by Short-Circuit** [comment]
Solved by fixing config file
