### ISSUE TITLE
Graphical Bug with the experience Obelisk [MC 1.7.10] [w/Optifine]

### ISSUE THREAD

**Issue by frenchiveruti** [SleepyTrousers/EnderIO#3838]
#### Issue Description:

The Experience Obelisk creates a graphical bug with my MC 1.7.10 and the Chisel world placed blocks, the problem is that this bug was not present in previous gaming sessions, Any idea on what could be causing it? I didn't touch any graphic config in Optifine either.

#### What happens:

Pics:
Pre
![2016-11-15_17 20 25](https://cloud.githubusercontent.com/assets/1095997/20322435/db0e1a16-ab57-11e6-870c-46056093aaaf.png)
After
![2016-11-15_17 20 27](https://cloud.githubusercontent.com/assets/1095997/20322445/eb08844c-ab57-11e6-93f5-1a45760a90d9.png)

1. Place any Chisel mod block on the floor, specially Marble with connected textures.
2. Place an EnderIO experience Obelisk.
3. The bug takes place.
4. Remove the Obelisk, and the bug disappears .
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO 1.7.10-2.3.0.428_beta
- EnderIO 1.7.10-0.2.0.36_beta
- Minecraft 1.7.10
- Forge 10.13.4.1614

#### Your most recent log file where the issue was present: 

[FeedThePaste](http://paste.feed-the-beast.com/view/83fc7883)

**Comment by HenryLoenwind** [comment]
Oops, that was the wrong label...also black and starts with "O" ;/

**Comment by frenchiveruti** [comment]
I know that the fact that I use optifine makes my report useless as you guys don't support it, but this issue started happening out of nowhere but I didn't edit any of my configs on the game.
Thanks for the reply and not closing it right away. :)
