### ISSUE TITLE
[Suggestion]: return of Mod compat conduits?: gas(mekanism), ME conduits & etc. for +1.10.2

### ISSUE THREAD

**Issue by mariodk** [SleepyTrousers/EnderIO#3844]
as the title says

maybe some extra conduits for like the AE2 like mods as a conduit if refined storage is installed

**Comment by melekaiah** [comment]
yes please, as well as the mechanism universal power cable. if possible ae4 beta is closing in now. and i have it working with enderio. looking forwards to gettting all these working together. as well as mechanism and rftools
