### ISSUE TITLE
Farming station harvests and dumps crops on locked sides.

### ISSUE THREAD

**Issue by Paul17041993** [SleepyTrousers/EnderIO#3845]
When two farming stations are situated near/next to each other for handling separate crops (ie; without ending up back-logged by one crop), the station on the east side will constantly up-root the grown crops on the west side and dump the drops on the ground, despite that side being locked to void.

- EnderIO: 2.3.0.429
- EnderCore: 0.2.0.36
- Minecraft: 1.7.10
- Forge: 7.10.99.99

**Comment by HenryLoenwind** [comment]
Farming stations will always handle their complete farmland, the locking is only for the kind of seeds it can plant there.

**Comment by Paul17041993** [comment]
So how do you suppose we get around the backlog issue...?

**Comment by HenryLoenwind** [comment]
Pull out the result faster? Set the Framing Station to push into the conduit, that should help, too.

Redesign of the station's UI is on out TODO list; that'll allow us to add even more output slots.

**Comment by Paul17041993** [comment]
http://prntscr.com/d8skyx
Unless the farming station's own output mode will keep at least one of each item in the output slots, or alternatively lock them, it's no different to normal conduit behaviour.
