### ISSUE TITLE
Ender Pearl Powder

### ISSUE THREAD

**Issue by GodNero** [SleepyTrousers/EnderIO#3846]
#### Issue Description:
While working on our pack, I was checking OreDictionary settings for the various materials in the pack when I noticed that the Ender IO "Ender Pearl Powder" is listed as a nugget and not a dust. I am curious if this is a Bug or As Intended.

#### What happens:

Ender Pearl Powder registers as a nugget, so recipes requiring dustEnder cannot utilize this material

#### What you expected to happen:

Ender Pearl Powder registers as a dust, so recipes requiring dustEnder can utilize this material as well as any other Ender Pearl based dust.

#### Steps to reproduce:

To see this in a client GUI:
1. Start and instance with Ender IO, Ender Core, and JEI in the pack
2. Create (or load) a world
3. Mouse over the "Ender Pearl Powder" and press "left shift"

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 0.4.1.58_BETA
- EnderCore: 3.0.1.128_BETA
- Minecraft: 1.10.2
- Forge: 12.18.2.2122

#### Your most recent log file where the issue was present: 

Screen shot from with in our Pack enviroment:
https://puu.sh/smFna/e307535ee0.png

Screen shot of Issue with only Ender IO, Ender Core, and JEI in instance.
https://puu.sh/smFMw/0d5a582b97.png

**Comment by HenryLoenwind** [comment]
It is a nugget because it is 1/9 of an ender pearl. Powders are 1/1 of their item.
