### ISSUE TITLE
Actually additions Battery charging. Support?

### ISSUE THREAD

**Issue by HeavyDeception** [SleepyTrousers/EnderIO#3847]
#### Issue Description:
The battery dose not seem to charge the armor or tools.

#### What happens:
RF is not put into the tools or armor when you have a battery in charge mod

#### What you expected to happen:
for it to charge the items.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
wrong project, you need to raise that with the battery...

**Comment by HeavyDeception** [comment]
@HenryLoenwind Ok I posted it there too I was not sure thank you.
