### ISSUE TITLE
**Electromagnet Upgrade**

### ISSUE THREAD

**Issue by HeavyDeception** [SleepyTrousers/EnderIO#3848]
It would be nice to have the electromagnet teleport XP and items into your inventory  instead of dragging them, that and to have a larger rang of 9 blocks.

I love that the electromagnet can help pick up xp its just that when it goes to move item the floating effect gets annoying after sometime and you just want the items to go directly into your inventory.

(ignore this really) and finally it uses power all the time (slowly) and it makes sense but I wish it didn't maybe every so often (this is more of an opinion).

**Comment by MatthiasMann** [comment]
The electromagnet runs for hours with one charge of only 100k - I think that is very good for game balance.

**Comment by HeavyDeception** [comment]
@MatthiasMann Ya that's just a me thing lol. ender IO has no battery for early game.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
