### ISSUE TITLE
Ender IO Requests

### ISSUE THREAD

**Issue by BurovB** [SleepyTrousers/EnderIO#3850]
I wrote this issue once more because I didn't have answer for my idea with Inventory Pannel.

**Comment by BurovB** [comment]
I think that Inventory Pannel would be better than AE if you would upgrade it.
1. It MUST be wireless(Maybe it would be something like Inventory Relay. You connect it to anything block with interface and it would work like(you can choose mode) ME Interface(you can put in Recipe Disk, and it would be autocraft) or Storage Bus(but you can't connect it to anything inventory anymore). After that you must connect all Inventory Relay to Inventory Interface)
2. It MUST have personal storage system(It will be a multiblock which is built for this rules: case will build from special blocks and inside the case can be six types of blocks:basic inventory bank, inventory bank, vibrant inventory bank, basic liquid inventory bank, liquid inventory bank and vibrant liquid inventory bank. Each of this blocks, if the ate inside multiblock case will add a certain amount of items or mB(and Inventory Relay in the storage bus mode must be connected to it)).

**Comment by BurovB** [comment]
I think that Ender IO is interesting enough, it would be more globally. It's be better if you add this:
1.Void Miner(Can mine resources(ores) from nothing. It will be a multiblock structure, and it must have bedrock block under a. If you put colored glass into machine it would working like linse which increase drop chance of something ores. 5000 RF/t. It will have an "Ender Upgrade" which wolud be work like a filter(you put into it ores) and when you took it into machine it will be more slower and "eat" 20000 RF/t, but it will mine only that ore which are in filter)/
I offer to "cut" Ender IO on modules:
1.Core(Craft components and basic machines for production this componets(Alloy Smelter, SAG Mil, The Vat, Soul Binder, Slice n' Splice))
2.Agriculture(Powered Spawner, Farming Station, mob breeding, Killer Joe)
3.Ender Tech(All magitech, Dimensional Transceiver,...)
5.Power(Generators, Capacitor Bank)
6.Conduits
7.Dark Steel Items, Armors, Tools
8.Other

**Comment by AnrDaemon** [comment]
One block per module?… Is that really worth the work?

**Comment by BurovB** [comment]
Which module?

**Comment by AnrDaemon** [comment]
Each module.

> I offer to "cut" Ender IO on modules:

**Comment by MatthiasMann** [comment]
The void miner is a rip of of systems already present in other mods.
And splitting the mod into modules will have a huge maintenance cost which is not doable currently and not reasonable for the future either.
As for storage - there are already other mods which provide storage that can be used by the inventory panel - eg Storage Drawers.
And there already exists a remote inventory panel.
