### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by NEXUS2345** [SleepyTrousers/EnderIO#3851]
I wonder if it would be possible to get shared private channels, akin to the 'Restricted' mode in the old TE/TD tesseracts, so that players can share channels between each other but not with the public.

In the same way that CoFH did it, it would just be a case of maintaining a list of people who can see those channels.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by NEXUS2345** [comment]
Thanks, is there a place we can view the current list of possible enhancements?

**Comment by HenryLoenwind** [comment]
https://github.com/SleepyTrousers/EnderIO/labels/Suggestion
