### ISSUE TITLE
SlicenSplice items in wrong slots

### ISSUE THREAD

**Issue by leglerm** [SleepyTrousers/EnderIO#3852]
#### Issue Description:
Version 3.0.1.128 (so not sure if this has been fixed in the just released version)
SlicenSplice is not automatable as it puts the items in the wrong slots
Setup is basically a chest behind the slicensplice where items can be put in (manual or automatic) and pulled into the slicensplice.

#### What happens:
Solarium/Zombie head worked fine but the 2nd silicon went into the redstone slot and therefore the redstone does not get pulled in. This also happens when manually shift clicking.

#### What you expected to happen:
Everything goes to the right slots

#### Steps to reproduce:

1. Put down slice and splice
2. Get materials for recipe
3. Shift click or use pull feature to put materials into the machine
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.01.1.128
- EnderCore:  0.4.1.58
- Minecraft: 1.10.2
- Forge: 12.18.2.2122

![2016-11-19_21 40 19](https://cloud.githubusercontent.com/assets/13408657/20458282/ce6ad7a8-aea0-11e6-9a56-2dd5b3b05c5e.png)

**Comment by HenryLoenwind** [comment]
ok, the Slice'n'Splice checks two things: (a) Is there any recipe that takes this item into that slot and (b) is there any recipe that takes this set of items as partial input. This may be the only case where both checks succeed but for different recipes...

**Comment by leglerm** [comment]
Checked it and i see that the skeletal contractor uses silicon in the bottom middle slot. At least in 1.7.10 there was no recipe that used silicon there. All other recipes zombie electorde, zlogic and ender resonator uses silicon in bottom left and right

**Comment by HenryLoenwind** [comment]
Yes.

The root of this is that we don't create one recipe object for each recipe in the XML config. We create one for the whole XML that can do everything that's in there. That's what's spreading those two checks over different recipes. I'm currently adding a final check that does a "is there really a recipe that takes this set of items and each of those items at those positions?"...
