### ISSUE TITLE
Adding custom hoes

### ISSUE THREAD

**Issue by BlakeBr0** [SleepyTrousers/EnderIO#3853]
#### Issue Description:
Adding hoes from Mystical Agriculture only works if you use the ingame config editor. Once you restart the game they no longer work.

#### What happens:
When I add a hoe (say mysticalagriculture:supremium_hoe) ingame via Farm Settings -> farmHoes it adds the hoe correctly and works perfectly ingame. Once I restart the game though, it stops working, unless I re-add it ingame again. If I were to add it from the config before launching the game it would add it to the list and not work.

#### What you expected to happen:

The hoe to continue to be usable in a farming station after a game restart.

#### Steps to reproduce:

1. Add the hoe to farmHoes ingame via the config (works)
2. Restart the game
3. Hoe can no longer be inserted into the farming station
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.136
- EnderCore: 0.4.1.60
- Minecraft: 1.10.2
- Forge: 12.18.2.2151

#### Your most recent log file where the issue was present: 

https://gist.github.com/BlakeBr0/27b2b140abd1bcc3bd4c8d7787ebc5a3

**Comment by BlakeBr0** [comment]
Works in Ender IO 3.0.1.125

**Comment by BlakeBr0** [comment]
After testing again I found out what the issue is. The EIO config processes the farmHoes hoes during preInit, while I register my tools/armor during init. Not sure if it would be possible to delay the hoe processing to a later point into initialization or not. If you can't I'll see what I can do on my end to fix it.

**Comment by HenryLoenwind** [comment]
init is too late, you need to register your blocks and items during preinit. Not just for Ender IO...

**Comment by BlakeBr0** [comment]
I will most likely do that. I just find it weird that the axes work with 0 issues as is, and that the hoes worked fine before that update where you changed the way addings hoes worked.

**Comment by HenryLoenwind** [comment]
Axes work because there is no list of axes but a check if an item is "effective" as "axe". No such runtime check available for hoes.

**Comment by BlakeBr0** [comment]
Alright, I'll do what I have to do then. Thanks for the help.

**Comment by BlakeBr0** [comment]
Would it be possible to add the Mystical Agriculture hoes to the default hoes list?
mysticalagriculture:inferium_hoe
mysticalagriculture:prudentium_hoe
mysticalagriculture:intermedium_hoe
mysticalagriculture:superium_hoe
mysticalagriculture:supremium_hoe

**Comment by HenryLoenwind** [comment]
BTW, there's another ticket about only some of the configured hoes working. If you run into that issue, give me a heads up, please.
