### ISSUE TITLE
Aversion Obelisk does not prevent mobs to spawn on Cursed Land

### ISSUE THREAD

**Issue by nefalem** [SleepyTrousers/EnderIO#3854]
Issue Description:

Aversion Obelisk does not prevent mobs to spawn on Cursed Land (extrautils).
My server runs FTB Direwolf20 1.10.

What happens:

Mobs still spawn in the area of the obelisk although the obelisk contains a soul vial containing the mob.
My obelisks are not fitted with any capacitor and have reliable power.
I have Cursed Earth tiles under the Aversion Obelisk.

What you expected to happen:

Mobs don't spawn.

Steps to reproduce:

Place and power an Aversion Obelisk on top of Cursed Earth tiles.
Add soul vial containing a mob
Wait for the mob to spawn.

Versions:
EnderIO-1.10.2-3.0.1.126_beta
EnderCore-1.10.2-0.4.1.58-beta
extrautils2-1.10.2-alpha-1.2.2

**Comment by HenryLoenwind** [comment]
Please raise this with extrautils, they are not firing the mob spawning event.

**Comment by AnrDaemon** [comment]
Cursed Earth explicitly disregard any spawn restrictions. This is in the very description of the block, with a warning written in big letters all over it.

**Comment by nefalem** [comment]
Well ok, my bad. I tried to search for that on extrautils but didn't find it -_-'.
Sorry, I close the ticket.

**Comment by HenryLoenwind** [comment]
Not a problem at all. This was one of the more sane "not a bug" tickets ;)
