### ISSUE TITLE
XP vacuum totally broke after 136 beta. Might have been broken 1 or 2 versions back.

### ISSUE THREAD

**Issue by SubsterNL** [SleepyTrousers/EnderIO#3856]
All XP spilled over the floor of a spawner room causing massive and massive lag.

It simply doesn't suckup anything anymore.

21-nov version of forge
1.10.2
136 beta of enderio and latest core

**Comment by SubsterNL** [comment]
Appologies.. Isn't an issue with ender IO. Please delete this report

**Comment by Iambecomeroot** [comment]
What was the issue? My xp vacuum isn't sucking anything up either
