### ISSUE TITLE
[Feature Suggestion] Add Industrial craft cables as conduits

### ISSUE THREAD

**Issue by MoonKill** [SleepyTrousers/EnderIO#3859]
Would it be possible to implement ?
E: I'm on 1.7.10 and I doubt you want to update that version but for 1.10/1.11 ?

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
No new features for 1.7.10 from us, we're struggling to keep up with 1.10.2. If someone would PR them, I'd be inclined to accept the PR.
