### ISSUE TITLE
Building more complex Sorting systems

### ISSUE THREAD

**Issue by Shirkit** [SleepyTrousers/EnderIO#386]
So, in order to build more complex sorting systems, one of the best mods out there that does this very well is the Immibis' Infinitubes.

I was thinking actually in two modes to build better systems:
- Allow a feature like ModBased ItemSink feature from LogisticsPipes (or the new Mod Sorting Pipe from Extra Utilities). This is one of the best features I know (and requested previously in other places), as it allows really good and complex sorting systems that behaves exactly the way you want them to behave. Keeping things organized is a must in Minecraft.
- Allow regex to be described as the filter for the Blacklist/Whitelist. although can be considered a bit powerful, it's also really useful as it would finally (finally!) allow a storage block that would contain all your ingots in one place, without the need of adding it to the rules every single time a new item (ingot for instance) appears.

If you agree to those changes, since I know you are a bit busy and likes keeping things organized (I've seen in this Github project, gratz) I can try to make a PR with with those changes.

Cheers

**Comment by HenryLoenwind** [comment]
A regex (or just simple contains()/startswith()/endwith()) filter would not be hard to implement. BUT, on which string should it match? The unlocalized name (what about subitems?)? The localized name in the current language? The localized en_US name? The oreDict ID? The only one that is visible to the player can also be changed by the player---breaking all regex filters badly. Even just changing the resource pack could then have this unexpected side effect...

**Comment by Shirkit** [comment]
Well, I honestly think that one could combine searching on different
places. I‘ve done similar work. You could combine different inputs to the
same mapping, so you simplify the work that needs to be done. Also,
following previous idea, you just input all different methods of search:
user language (current); en_US language; unlocalized en_US; and oredict.

A simpler approach would also be to restrict the user what he could do, by
explaining on what he could search. Displaying four checkboxes with those
four options would be enough to the user pick the correct thing that needs
to be done.
