### ISSUE TITLE
An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar)

### ISSUE THREAD

**Issue by Tschaeaen** [SleepyTrousers/EnderIO#3860]
I am running a modpack server and after some hours the server crashed. Then i updated some mods and now there is only one errror and i dont know what to do. The modpack is my own.

Here is the pastebin link for the crashlog http://pastebin.com/vkZJUETK

____
- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by HenryLoenwind** [comment]
Your world got damaged by the thread. Load your last backup from before it.

**Comment by Tschaeaen** [comment]
Where can i find the last backup?

**Comment by Tschaeaen** [comment]
http://pastebin.com/UuJ0uxhx

this is the crash log from the server, the other was the one from my client after i updated some mods and copied the world into singleplayer
