### ISSUE TITLE
EnderIO and Roots may not be getting along

### ISSUE THREAD

**Issue by belathus** [SleepyTrousers/EnderIO#3862]
#### Issue Description:
I just updated to EIO version 3.0.1.137 from 3.0.1.136. We started getting the following crash on server start: http://pastebin.com/raw/fXCZ0r9y

#### What happens:
Crash to desktop (or, in this case, crash to CLI)

#### What you expected to happen:
Server to run?

#### Steps to reproduce:
I'm guessing I have a pump from Embers next to EIO conduit?

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.137
- EnderCore: 0.4.1.60
- Minecraft: 1.10.2
- Forge: 12.18.2.2125
- Embers: 0.016

#### Your most recent log file where the issue was present: 

Crashlog: http://pastebin.com/raw/fXCZ0r9y
Full log: https://gist.githubusercontent.com/belathus/09d1badc4df6a00c09d5e0db24c1ec38/raw/9ad6cadfa936d6749d9f5c8911e8f7bd96a23e8a/log

**Comment by belathus** [comment]
Yeah, reverting back to 136 did not fix it. Maybe another mod is interfering?

**Comment by MatthiasMann** [comment]
This looks like either a world corruption - or roots is sending doing something strange with neighbor change updates (eg using the wrong coordinate).

**Comment by HenryLoenwind** [comment]
yes, world corruption seems most likely. An item conduit is trying to get the inventory of one of its neighbor, asks Minecraft for that block's TileEntity, which doesn't exist (but it should!), so Minecraft creates it and notifies all neighbors of that change. One of those neighbors is that pump, which tries to access a (presumably its own) TileEntity but gets a conduit Tileentity instead and chokes on it to death.

**Comment by belathus** [comment]
Well, good thing I am not overly attached to that world.

**Comment by belathus** [comment]
Looks like Embers was able to fix it; whatever it was.
