### ISSUE TITLE
Random crash on game load - MissingMods screen

### ISSUE THREAD

**Issue by iamomicron** [SleepyTrousers/EnderIO#3865]
#### Issue Description:
I'm the dev of DNS Techpack. Reporting an issue a couple of users have had that is extremely odd. Starting the game, on _certain_ instances causes a crash. The main menu should output a message of `Error: Missing Mod` or something along those lines. On most instances the pack will load fine, but so far I've had 2 reports of this issue.

**This is not 100% reproducible.** For some odd reason, the same installation of mods and configs on most machines works. On some however, it causes this crash. Removing EnderIO *fixes* the issue but is not an ideal fix.

Removing `CoreChickenCore`, `CodeChickenLib`, `EnderStorage`, `NEI` and `ChickenChunks` brings the main menu error back, saying that Brandon's Core relies on CCL to be installed.

Installing CCL brings the issue in question back.

#### Affected Versions:

- EnderIO: `1.10.2-3.0.1.137_beta`
- EnderCore: `1.10.2-0.4.1.60-beta`
- Minecraft: 1.7.10
- Forge: `12.18.2.2151`

[Crash log](https://cdn.discordapp.com/attachments/105689603133935616/252877574642991105/crashlog_1920.txt)

This issue was not present (as far as I know) with version `3.0.1.136_beta` of EnderIO.

**Comment by HenryLoenwind** [comment]
Congratulation on naming those instances exactly the same as a popular Russian cracked launcher.

Next build will do a better check for that, sorry.

**Comment by iamomicron** [comment]
Wait, they're using a cracked launcher?

**Comment by HenryLoenwind** [comment]
they may, but your crash log just used the same directory name by accident

**Comment by iamomicron** [comment]
I'm just forwarding their crash logs to here. It runs fine for me and most other players. It was just 2 instanced that had this issue. I'll investigate and get back to you.

Thanks for bringing this to my attention, I neglect to check for cracked launchers as it's not a common occurrence for us.

**Comment by iamomicron** [comment]
The directory listing `/Instances/` is from ATLauncher. They are using the correct launcher for the modpack download. I don't believe this is a cracked version.

**Comment by HenryLoenwind** [comment]
as I said, that crash log is from an installation that is using the same name by accident (and our code doing a check that is a tad too wide). The next build will fix that and only engage for a full name match, not a partial one.

**Comment by iamomicron** [comment]
Oh sorry, I misunderstood. Thanks for the help. I'll pass the information on.

**Comment by HenryLoenwind** [comment]
build 138 should fix this, plz test, thx!

**Comment by iamomicron** [comment]
Already on it! One user has reported back and it seems like it's done the job.  Thanks for the quick fix!
