### ISSUE TITLE
DUPING GLITCH

### ISSUE THREAD

**Issue by MiniDOBBS** [SleepyTrousers/EnderIO#3866]
#### Issue Description:
This Issue allows anyone to DUPLICATE ABSOLUTELY ANYTHING
using capacitor banks

#### What happens:
you start by having any power bank with any amount of power in it.
place a powered item in the bank to charge
use your hotkeys to take out the charging item
if done fast enough (its pretty slow) you will be able to take out a second of that same item
drop the first legit item
then drop anything you want out of your inventory 
then move the duplicated item anywhere in your inv
you now have duped items

#### Affected Versions (Do *not* use "latest"):

**EnderIO-1.10.2-3.0.1.126_beta
EnderCore-1.10.2-0.4.1.58-beta
Modpack: Direwolf20 (latest 1.0)**

**Comment by Vauxite** [comment]
This was solved in a recent update of the modpack (version 1.1.0.
