### ISSUE TITLE
Enderman head rendering is rather heavy/slow

### ISSUE THREAD

**Issue by way2muchnoise** [SleepyTrousers/EnderIO#3867]
It is rather interesting how the rendering of the EndermanSkull is taking this much client thread time.
Spotted in a profile @darkosto made while testing in his SF3 world. After removing the 2 skulls he had in his base he went from 180 fps to 300 fps.

Happend on EnderIO - 1.10.2-3.0.1.138_beta (latest on curse at this time), not sure about the forge version.

![](http://puu.sh/syxKU/659c50a8ee.png)

[.nps file](http://puu.sh/syxDS/2e7ff804ac.nps)

**Comment by HenryLoenwind** [comment]
<img width="1153" alt="screen shot 2016-11-29 at 20 19 32" src="https://cloud.githubusercontent.com/assets/1485873/20725175/433416f8-b671-11e6-88df-c2dddc5c90b7.png">

Not really our code that's slow. It's that "models will make rendering sooo much faster"-code of vanilla.

**Comment by HenryLoenwind** [comment]
Also, when looking at the other TESRs and scaling their total time by the number of times they are executed, they take about the same time.

**Comment by HenryLoenwind** [comment]
<img width="1165" alt="screen shot 2016-11-29 at 20 40 21" src="https://cloud.githubusercontent.com/assets/1485873/20726002/1f4e6100-b674-11e6-98bb-cbd945bb1859.png">

**Comment by way2muchnoise** [comment]
That is quite the lightmap update

**Comment by HenryLoenwind** [comment]
lex says, fry would need to take a look to see if those percentages are normal...

**Comment by Darkosto** [comment]
@HenryLoenwind Lex has been telling me to talk with Fry as well regarding the lighting updates. I think you may be able to have a more detailed conversation with him than I could. Is it possible for me to pass along any and all logs/samples to help point this issue out? I'd like to assist in, hopefully, eliminating that performance loss if possible :)
