### ISSUE TITLE
Conduit Facades let light through

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3868]
#### Issue Description:
Conduit Facades let light through

![2016-11-30_20 28 20](https://cloud.githubusercontent.com/assets/8670392/20767812/f1852b78-b73b-11e6-8da5-8f2c40f435d2.png)
![2016-11-30_20 28 32](https://cloud.githubusercontent.com/assets/8670392/20767813/f199862c-b73b-11e6-8257-791cd2932415.png)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.138_beta
- EnderCore: 0.4.1.60-beta
- Minecraft: 1.10.2
- Forge: 2135
- Mods: [list.txt](https://github.com/SleepyTrousers/EnderIO/files/622778/list.txt)

**Comment by Xiaminou** [comment]
I see you noted "report incomplete", what more information do you need?

**Comment by HenryLoenwind** [comment]
Mainly three things:

What are the facades painted with? (If they are e.g. painted with "Red Flower", it's expected that light goes through...)

What are the light levels while they are not hidden? (By default, the client world is re-lit when they are hidden so you can see the conduits. And the overlay displays the client light level...)

Which facades are that? (The transparent ones are not completely light tight to allow the Beacon beam through.)

**Comment by Xiaminou** [comment]
They're painted with Chisel's laboratory blocks that you can see on both sides. Light levels are the same while they're rendered (not hidden). It's most basic facade Ender IO has.

**Comment by Xiaminou** [comment]
So, I tested with a daylight sensor, looks like you were right about it being client sided only.

**Comment by Xiaminou** [comment]
Here, I tested it with a daylight sensor:
![2016-12-04_16 28 44](https://cloud.githubusercontent.com/assets/8670392/20867205/374fa01a-ba3f-11e6-9dc1-c53d349552b2.png)
![2016-12-04_16 28 52](https://cloud.githubusercontent.com/assets/8670392/20867206/3750e132-ba3f-11e6-95c5-6c96f37202d8.png)
![2016-12-04_16 28 54](https://cloud.githubusercontent.com/assets/8670392/20867207/377e6cf6-ba3f-11e6-99c5-70e7d7a1e418.png)

**Comment by itanshi** [comment]
Adding onto this. v 1.10.2 3.1.156

This is a dark clear glass painted on a non transparent facade. This renders the facade transparent.

![2017-03-01_02 34 22](https://cloud.githubusercontent.com/assets/373669/23451943/d08f5e4c-fe27-11e6-985b-0f784fe31229.png)

**Comment by Meryl** [comment]
I have an addendum to this bug. It seems to only happen when the facade is the last block you place. I have a 9x9 area divided into two areas vertically, seperated by stone with a stone-painted facade in the middle. If I place the facade last, the light from the bottom area bleeds into the upper area. If I then break a stone block next to the painted facade and replace it, the bleeding stops.

[https://gfycat.com/OrangeIllfatedAndeancockoftherock](Here's a video)

**Comment by HenryLoenwind** [comment]
ok, that narrows it down quite a bit, thank you.

So the problem isn't that the facades let light through, but that the re-lighting we have to do after adding the facade data to the block isn't working. (Background: The game first sets the block type ("conduit bundle"), re-lights the area, then allows us to transfer additional data ("facade") from the item to the block.)

**Comment by PapiDimmi** [comment]
I have the same issue. It is really annoying.

**Comment by MatthiasMann** [comment]
@PapiDimmi have you tried the work around suggested by Meryl?

**Comment by tofof** [comment]
I have tried the workaround and I don't believe it to be true. 
The video seems only to be addressing the visual appearance of light.

I, like the OP, am using Chisel versions of blocks (the 'Dark Lava Brick' Nether Brick) and regardless of other blocks placed afterward, directly below a facade in the ceiling is daylight; it triggers daylight sensors, etc.

It's light level 14 and mobs don't spawn under my solid-painted basic facade blocks.

**Comment by EpicSquid** [comment]
@Xiaminou can you open a new issue for the 1.12 version of this problem? Since it is quite different  behind the scenes and solving it for 1.12 won't solve it for 1.10

**Comment by Xiaminou** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/4577
