### ISSUE TITLE
NBSP Issue

### ISSUE THREAD

**Issue by Elvarion** [SleepyTrousers/EnderIO#3869]
When looking at the Capacitor Bank info screen there is a NBSP instead of a  , or just a space like all the items that uses RF now has. This happens when using a Swedish OS, If I change my OS language to English for example the NBSP goes away. This thing has been haunting me since the 1.7.x era and noticed now that the items dont have the NBSP anymore but the info screen still has, so it would be lovely if we could get rid of that symbol once and for all! :smile: 
![](https://i.gyazo.com/04c5ac8a3202b8d396a1599e72b40608.png)

Also found this strange rendering glitch.
Was able to reproduce it without much effort.
Place down a Capacitor bank (any version)
Make the North side the Info display and then make either the East or West side the Progress bar. It will now be rendered strange.
**Note:** Rendering tested with Only EnderIO and still present
![](https://i.gyazo.com/b2d43fa5be8348fd357391e40681927d.png)
____
Minecraft: 1.10.2
EnderIO-1.10.2-3.0.1.138_beta
EnderCore-1.10.2-0.4.1.60-beta
Forge-1.10.2-12.18.2.2171

**Comment by HenryLoenwind** [comment]
The number formatting and text rendering is done by vanilla.

I'll have a look at the gauge glitch tonight.

**Comment by Elvarion** [comment]
Then something changed in Vanilla between 1.7.x and 1.10.2 that changed the texture formatting and rendering? Because this is how EnderIO used to look for me back then..
![](https://i.gyazo.com/ddcba33f80e71caec32c89b5a358c90d.png)
(Now the only NBSP left is the one posted in the first picture)

Changed my formatting to UK standard and this made the NBSP appear as a , however even if going into the settings for Swedish formatting and making all the settings like they are in the UK will still give me a NBSP with Swedish formatting in Minecraft. So I am guessing Java is somehow messing things up and has its own default localization stored somewhere. Not sure if its possible to change that since im not very familiar with how Java works and such..

**Comment by HenryLoenwind** [comment]
I'm a bit surprised there was a change from 1.7.10 to 1.10.2. The code to fix the French number formatting was added on 2014-10-22, and that is what helps you, too. (So yes, we already have special code to work around that vanilla bug. Something new to learn every day...)

I'll have a look why it doesn't effect the capBank display.

**Comment by Elvarion** [comment]
Nice to know, Thanks for working around that bug. Its been driving me crazy trying to fix it ^^

**Comment by HenryLoenwind** [comment]
and that's for the render glitch. Seems the gauge was rendered with the font texture sheet instead of the block texture sheet.

**Comment by Elvarion** [comment]
@HenryLoenwind Sorry to bug you guys again.
Not sure if EnderIO handles all burnable items or not, but this does appear when only having EnderIO installed, so id post it here.

Noticed that Burnable items  that has more then 1000 ticks worth of fuel will display the NBSP in its tooltip.
https://gyazo.com/0cade2d08e5d6e9a59ae9a76a88cc638

//Maybe it would be possible for Forge to implement a fix for this, Shouldn't that fix it for everyone? And mods would not have to add codes to work around it. I dont know much about coding, so maybe thats not how it works :p

**Comment by HenryLoenwind** [comment]
Yes, that info is added by Ender IO, but this time the whole message is created by java.text.MessageFormat, which makes it a bit harder to fix--there's no NumberFormat exposed to our code...

**Comment by HenryLoenwind** [comment]
And yes, this would be very easy for Forge to fix. All it'd need would be to add

```if(car==160)return 4;```

to the beginning of net.minecraft.client.gui.FontRenderer.getCharWidth() and net.minecraft.client.gui.FontRenderer.renderChar()

**Comment by HenryLoenwind** [comment]
ok, our next build should convert those to spaces, too.

**Comment by Elvarion** [comment]
Awesome!
