### ISSUE TITLE
(Suggestion) Refined Storage Conduit

### ISSUE THREAD

**Issue by JaRyCu** [SleepyTrousers/EnderIO#3872]
This is just a feature suggestion.  With Refined Storage being a major storage mod in 1.10+ for Modded Minecraft, would it be possible to create a cable conduit?  It'd be similar to the ME conduits for AE2 integration that have existed since 1.7.10 days.  I'm not a coder, so I don't know if this would be easy or difficult, but it sure would be handy.

Thanks in advance for you consideration.

**Comment by HenryLoenwind** [comment]
RS has asked us to wait for their new capability API for this.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
