### ISSUE TITLE
[Potential bug] Unchanging custom recipes

### ISSUE THREAD

**Issue by GameSlayar** [SleepyTrousers/EnderIO#3875]
#### Issue Description:
Adding custom recipes in _SAGMillRecipes_User.xml_ doesn't work as it should. I have tried copying and pasting exactly how the example states, and exactly how it is done in _SAGMillRecipes_Core.xml_, and I get nothing ;-; 

No recipe change in JEI, and no change when testing in the world.

#### What happens:

No recipe change in JEI, and no change when testing in the world.
EG: When trying to change the recipe to make cobblestone yield at least _one_ gravel 100% of the time, it remains at the default 70%

#### What you expected to happen:

The recipe should update in JEI, and it should actually change in-game.

#### Steps to reproduce:

1. Change the recipes in _SAGMillRecipes_User.xml_ 

Current XML file as example: [_Pastebin_](http://pastebin.com/htQQh1Lj)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.138 (beta)
- EnderCore: 0.4.1.60 (beta)
- Minecraft: 1.10.2
- Forge: 12.18.2.2124

#### Your most recent log file where the issue was present: 

[_Pastebin_](http://pastebin.com/h0904Vt0)

**Comment by HenryLoenwind** [comment]
```<recipeGroup name="Modifications" >```

That's your problem, you're trying to override recipes in a group named "Modifications", which doesn't exist, so they are added as new recipes at the end of the list.

```  To change an existing recipe, just add the recipe to this file using the same recipe group and recipe name as found in
  the core file.```

**Comment by GameSlayar** [comment]
Hmm.. I apologize for that, I should have read the file more closely.

But it still doesn't seem to work :c 
No luck in changing the recipes, and I have looked in the core file to verify that the group name and recipe name are the same.
Unless I'm doing something wrong?

Current XML file: [SAGMillRecipes_User.xml](http://pastebin.com/uX4AC0Fj)

**Comment by HenryLoenwind** [comment]
Do you get any errors in the logfile?

You can also start Minecraft with the parameter -DINDEV to get full logging.

**Comment by GameSlayar** [comment]
_[18:40:29] [Server thread/DEBUG] [EnderIO/EnderIO]: Added user defined recipe group Modifications
[18:40:29] [Server thread/DEBUG] [EnderIO/EnderIO]: Added user defined recipe BlackQuartzOre
[18:40:29] [Server thread/DEBUG] [EnderIO/EnderIO]: Added user defined recipe UraniumOre
[18:40:29] [Server thread/DEBUG] [EnderIO/EnderIO]: Replacing core recipe Quartz Ore  with user defined recipe.
[18:40:29] [Server thread/DEBUG] [EnderIO/EnderIO]: Replacing core recipe Cobblestone  with user defined recipe.
[18:40:29] [Server thread/DEBUG] [EnderIO/EnderIO]: Replacing core recipe Gravel  with user defined recipe._

Supposedly it loaded all the recipes correctly with no errors, yet when I check JEI in-game on the server, the Quartz Ore recipe is unchanged. I have defined it to yield 4 pieces of Quartz, yet in-game it still makes 2 quartz with a 10% chance for Quartz dust.

**Comment by HenryLoenwind** [comment]
Jei is a client-mod, so it will report on the client recipes. Is this your problem here? If not, I'll recreate your setup later this week and go into it with the debugger.

**Comment by GameSlayar** [comment]
Right, yes. Sorry for the delay in response. It seems that the recipes do seem to work, I was a little too reliant on JEI showing me the server recipes. c:

Thank you anyway for the help!
