### ISSUE TITLE
auto sorting and crafting crashes the game

### ISSUE THREAD

**Issue by minimin1122** [SleepyTrousers/EnderIO#3876]
#### Issue Description:
client keep on crashing
#### What happens:
I have some magical crop farm with farming station going into a chest which eventually gets full pretty fast. so I set up some automated essences into corresponding ores which are fed into storage drawer from storage drawers. After I finished building it with energy conduit and item conduit, the game started to crash at random times, which sometimes it takes less then 5 min for client to crash while one time it can be 15 min.

P.S: I have just added cobalt seeds and essence into the system and immediately game crashed. maybe that is why?

P.S 2: I have just activated the one for lapis lazuli seeds and also crashed the game while gold seeds nor diamond seeds did not

#### What you expected to happen:
possibly problems with energy conduit going into storage drawers?

#### Steps to reproduce:

1. chest feeding items into storage drawers and crafter from enderio
2.connect the system with enderio energy conduit and item conduit
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 7.10.99.99

#### Your most recent log file where the issue was present: 
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 03/12/16 7:10 PM
Description: Rendering Block Entity

java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraftforge.client.model.obj.WavefrontObject.renderAll(WavefrontObject.java:181)
	at com.brandon3055.draconicevolution.client.render.tile.RenderTileEnergyPylon.func_147500_a(RenderTileEnergyPylon.java:62)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:772)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1334)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraftforge.client.model.obj.WavefrontObject.renderAll(WavefrontObject.java:181)
	at com.brandon3055.draconicevolution.client.render.tile.RenderTileEnergyPylon.func_147500_a(RenderTileEnergyPylon.java:62)

-- Block Entity Details --
Details:
	Name: draconicevolution:TileEnergyPylon // com.brandon3055.draconicevolution.common.tileentities.multiblocktiles.TileEnergyPylon
	Block type: ID #201 (tile.draconicevolution:energyPylon // com.brandon3055.draconicevolution.common.blocks.multiblock.EnergyPylon)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (232,84,-486), Chunk: (at 8,5,10 in 14,-31; contains blocks 224,0,-496 to 239,255,-481), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #201 (tile.draconicevolution:energyPylon // com.brandon3055.draconicevolution.common.blocks.multiblock.EnergyPylon)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:772)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['dudwo486486'/83, l='MpServer', x=194.18, y=85.74, z=-444.45]]
	Chunk stats: MultiplayerChunkCache: 729, 738
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (96,64,-232), Chunk: (at 0,4,8 in 6,-15; contains blocks 96,0,-240 to 111,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 27841890 game time, 28398076 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 34 total; [EntitySkeleton['Skeleton'/518, l='MpServer', x=26.21, y=-24.74, z=-12.75], EntityZombie['Zombie'/34, l='MpServer', x=208.00, y=18.00, z=-391.31], EntityBat['Bat'/1256501, l='MpServer', x=139.97, y=11.68, z=-398.28], EntityZombie['Zombie'/39, l='MpServer', x=253.68, y=50.35, z=-375.81], EntityBat['Bat'/1256500, l='MpServer', x=169.78, y=38.00, z=-365.41], EntityChicken['Chicken'/40, l='MpServer', x=253.59, y=50.00, z=-375.75], EntityZombie['Zombie'/48, l='MpServer', x=257.72, y=54.00, z=-396.91], EntityZombie['Zombie'/49, l='MpServer', x=266.50, y=56.35, z=-381.60], EntityChicken['Chicken'/50, l='MpServer', x=266.50, y=56.00, z=-381.50], EntityBat['Bat'/1247264, l='MpServer', x=178.91, y=40.00, z=-368.69], EntityZombie['Zombie'/53, l='MpServer', x=259.50, y=67.35, z=-370.60], EntityChicken['Chicken'/54, l='MpServer', x=259.50, y=67.00, z=-370.50], EntityZombie['Zombie'/1247530, l='MpServer', x=240.50, y=60.00, z=-385.50], EntityBat['Bat'/1241673, l='MpServer', x=199.84, y=42.00, z=-507.97], EntityClientPlayerMP['dudwo486486'/83, l='MpServer', x=194.18, y=85.74, z=-444.45], EntityBat['Bat'/1246572, l='MpServer', x=236.94, y=41.00, z=-515.44], EntitySkeleton['Skeleton'/1249429, l='MpServer', x=252.50, y=44.00, z=-365.50], EntityBat['Bat'/1229465, l='MpServer', x=231.25, y=57.10, z=-522.59], EntityChicken['Chicken'/151, l='MpServer', x=171.44, y=45.00, z=-521.56], EntityChicken['Chicken'/152, l='MpServer', x=163.41, y=69.00, z=-514.53], EntitySkeleton['Skeleton'/1249419, l='MpServer', x=239.50, y=49.00, z=-369.50], EntitySkeleton['Skeleton'/1249418, l='MpServer', x=242.50, y=49.00, z=-368.50], EntitySkeleton['Skeleton'/1249417, l='MpServer', x=243.50, y=49.00, z=-368.50], EntityBat['Bat'/1250959, l='MpServer', x=266.69, y=48.00, z=-504.50], EntityBat['Bat'/1250958, l='MpServer', x=264.94, y=49.00, z=-504.50], EntityChicken['Chicken'/164, l='MpServer', x=231.59, y=43.00, z=-514.47], EntitySpider['Spider'/820644, l='MpServer', x=-16.13, y=-2.00, z=-3.85], EntityZombie['Zombie'/172, l='MpServer', x=246.30, y=12.11, z=-519.06], EntityChicken['Chicken'/179, l='MpServer', x=259.72, y=66.00, z=-444.69], EntityBat['Bat'/1247401, l='MpServer', x=263.38, y=27.00, z=-501.53], EntityBat['Bat'/1255897, l='MpServer', x=256.91, y=33.00, z=-390.25], EntityCreeper['Creeper'/1242855, l='MpServer', x=262.50, y=53.00, z=-396.50], EntityBat['Bat'/1256165, l='MpServer', x=174.50, y=38.00, z=-365.91], EntityZombie['Zombie'/5881, l='MpServer', x=-42.78, y=-30.50, z=-37.41]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 386690032 bytes (368 MB) / 1145380864 bytes (1092 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 102
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D3 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	caveworld{2.3.2} [Caveworld 2] (Caveworld_1.7.10-v2.3.2.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	gravestonemod{1.7.10} [Gravestones] (GraveStones 1.7.10 -3.jar) 
	UCHIJAAAA	ibench{1.0.12} [iBench] (ibench-1.7.10-1.0.12.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCHIJAAAA	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.9.8} [Storage Drawers] (StorageDrawers-1.7.10-1.9.8.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	TiCTooltips{1.1.11b} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.1.11b.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3379' Renderer: 'Intel(R) HD Graphics 4600'
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from EnderIO-1.7.10-2.3.0.429_beta.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.2.0 - Build 10.18.10.3379, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D3
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.2.0 - Build 10.18.10.3379
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 8
[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
known crash caused by optifine

**Comment by minimin1122** [comment]
thank you very much! no more crashs!!
