### ISSUE TITLE
Crash when Killer Joe using SlashBlade Mod's blade.

### ISSUE THREAD

**Issue by frank89722** [SleepyTrousers/EnderIO#3877]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
When I put a blade from the mod called SlashBlade in to Killer Joe and the game crash.

#### What you expected to happen:
I think you can give a Killer Joe a black list in config or you can fix that :P

#### Steps to reproduce:

1.Install both mods.
2.Put any blade form slash blade in to killer joe and turn it on.
3.And Booom.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:3.0.1.138
- EnderCore:0.4.1.60
- Minecraft: 1.10.2
- Forge:2179

#### Your most recent log file where the issue was present: 

Crash report : http://pastebin.com/V8iex4Bj

**Comment by HenryLoenwind** [comment]
Some mod is either creating a second thread on the server and is changing itemstacks from there or is sharing objects between server and client. It's not us, and judging from the fact that it only happens with items from one mod...
