### ISSUE TITLE
Connection between Dense Cable and ME Dense Conduit renders as a ME Smart Cable connection

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3878]
#### Issue Description:
![2016-12-04_15 41 02](https://cloud.githubusercontent.com/assets/8670392/20867126/818b93de-ba3d-11e6-8b6f-fb0d630076f8.png)

#### What happens:
Renders as a Smart Cable connection.

#### What you expected to happen:
Should render as Dense Cable connection.
____
#### Affected Versions (Do *not* use "latest"):

- Mods: [list.txt](https://github.com/SleepyTrousers/EnderIO/files/629599/list.txt)
- EnderIO: 3.0.1.138_beta
- EnderCore: 0.4.1.60-beta
- Minecraft: 1.10.2
- Forge: 2135

**Comment by HenryLoenwind** [comment]
That's the AE cable's rendering, you're unhappy with, isn't it? So why raise this with us? (Honest question, I 'm no ae expert in any way)

**Comment by Xiaminou** [comment]
Well I didn't know if it was AE or EIO responsible. Now I do...

**Comment by HenryLoenwind** [comment]
Well, it may me that we're using the API incorrectly... I have no idea how it works;)

**Comment by Xiaminou** [comment]
Looks like Yueh has got your answer.

**Comment by HenryLoenwind** [comment]
oh, now I understand what you mean! A connection to a **dense** conduit renders the same as a connection to a normal conduit.

**Comment by Xiaminou** [comment]
Yes, sorry if that wasn't clear.

**Comment by HenryLoenwind** [comment]
yeah, that I didn't know what the ME cable tiers are didn't help ;). But I got it now, even if it's not showing up on github atm

**Comment by Xiaminou** [comment]
![2016-12-07_20 14 14](https://cloud.githubusercontent.com/assets/8670392/20982679/d62cce70-bcb9-11e6-88db-2cc92ba201da.png)
![2016-12-07_20 14 21](https://cloud.githubusercontent.com/assets/8670392/20982680/d642ccd4-bcb9-11e6-8952-8a0ef30d44ca.png)

**Comment by HenryLoenwind** [comment]
There is nothing to fix. All we really try to say to the cable is "render in your own style and don't feel restricted by us". What was wrong was that the dense ME conduit didn't allow a dense connection to be rendered---it was saying "I'm a non-dense cable that is dense" before. If the cable renders a different style than its own (I'm not sure from the pic as I don't know the cables good enough), then that would be an issue on AE2's side.

BTW: The last fix is in the latest Ender IO build, so you can test it.

**Comment by Xiaminou** [comment]
![2016-12-07_21 32 16](https://cloud.githubusercontent.com/assets/8670392/20985811/5983b282-bcc6-11e6-8067-5d1b6104db4c.png)

**Comment by HenryLoenwind** [comment]
This looks ok to me, the ME cable is being itself and is not changing style for the the connection to the conduit. What do you think?

**Comment by Xiaminou** [comment]
I'm wondering if it shouldn't look like this instead:
![2016-12-07_22 03 30](https://cloud.githubusercontent.com/assets/8670392/20986481/2e477ea2-bcc9-11e6-997f-e394356d2c72.png)
![2016-12-07_22 03 53](https://cloud.githubusercontent.com/assets/8670392/20986482/2e54e9de-bcc9-11e6-94b3-323c38326225.png)

**Comment by mindforger** [comment]
i am a little bit confused why the cable hub is showing there!

looks like a AE2 bug to me to some degree, as your dense conduit ist properly connected to the dense cable it should render as straight cable instead of showing this fat knob there (even with an cable anchor it should not render the hub)

**Comment by Xiaminou** [comment]
If you mean in the second to last screenshot, it is because of the cable anchor, which is a bug I already reported to AE2. But it was to show an example of what it could look like if it rendered the "fat knob" as you call it when connecting to Dense Conduit.
