### ISSUE TITLE
Powered Spawners with no AI

### ISSUE THREAD

**Issue by DigitalSketch** [SleepyTrousers/EnderIO#3879]
Not sure if this is an option in a config file or not, but might be useful to have a "No AI" option with the powered spawners.  We use them for resources, and we don't kill them manually anyway.  May help cut down on TPS lag if the mobs had no AI.

Just a thought for a feature :)

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
I actually like that.

**Comment by DigitalSketch** [comment]
:)

**Comment by DigitalSketch** [comment]
Had a secondary thought on this "No AI" thing... maybe another machine that will use a soul vial to extract random loot from the captured mob.  Similar to killing it, but just a machine that does it.  Maybe have upgrades for looting, or beheading, specific items etc.  Might be a cool alternative to "no AI"
