### ISSUE TITLE
[1.7.10] Crash in TileTank.doPull

### ISSUE THREAD

**Issue by deregges** [SleepyTrousers/EnderIO#3880]
#### Issue Description:

This crash occured serverside, with use of kcauldron.

#### What happens:

Crashes (crash report below), keeps crashing on restart

#### Steps to reproduce:

no idea, was not online at this point.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614

#### Your most recent log file where the issue was present: 

http://paste.ee/p/FzEcu
[FzEcu.txt](https://github.com/SleepyTrousers/EnderIO/files/630440/FzEcu.txt)

deregges

**Comment by HenryLoenwind** [comment]
The block that the tank is trying to pull out of is announcing it has a null tank, which is not a legal value (that would be "no tank" or "empty tank"). Please raise this against that mod.
