### ISSUE TITLE
Suggestion on version past 1.10.x of 5 Dec 2016

### ISSUE THREAD

**Issue by jiuribu** [SleepyTrousers/EnderIO#3881]
I had more often issue that octadic capacitor is not enough . Also i noticed that from old version of enderio to the New Machines are able to store almost everything , from burning process in the mid way up to items. I realy like it , this makes this machines are more mobile and this allow you always to move to another spot.

Some limits that i keep hitting over and over and over again.

Processing items not fast enough , darksteel ball + 8 flint = to make even better something + some grinded enderpearls to make even better than better one , as well that would last longer.

as for alloy smelter i could not figure how process is working , does it "pay" RF needed to finish process ?
so the only difference on octadic capacitor is that it is able to pay "RF" at rate of 100 / settime ?

overall i would like instead of making bizzilions of machines , spend more time and upgrade single ones
efficiency ( to reduce power cost of processes)
speed (by processing 2 or more items at ones , alloy smelter by basic smelting)

Sag Mill , if storing large numbers of RF cause some issue , why simply use different way
if up to x8 (octadic=?) cap , u increased amount of rf payed at once so going x16 x32 
instead of going higher battery cap and more payload , take part of reducing cost ? (part of higher payment and part of increased battery) 

this way it increase efficiency of machine

armor is another issue , i would like to go higher levels , as well as higher durability. 
also not using RF but fluid / mass , since enderio of mc 1.10 have so many own fluids , why not fuel the armor itself with brainmass or some sort of mixture.

problem on darksteel armor its weak vs some hardcore mods , GoG3 mobs tear this armor down in no time .

-----------------------

Blast Resistance upgrade for whole ender io mod is must for me

also charged creeper managed to blow up "reinforced obsidian"  in 1.7.10 skyblock

normal creeper , fed with witch water , went up in the air and "RO" did not stand a chance

--------------------

would like to see 1 storages like DSU or quantum storage unit

for fluids as well as for items (this removes need to install other mods that add this items)

------------------------

filters : sometimes 8 items is not enough 

-----------------------

capacitor bank of 25m RF i define as "smallest" one

would like to see energy that is worth of 20 RFs

-------------------
photovoltic cell MK1

i would like to see recipe that would allow to upgrade from MK1 up to MK3

right now only mk2 to mk3 is possible (at least in hermitpack 1.4.x)

----

transdimensional reciver filter at 1.7.10 was a bit too smal for me

not sure if that possible but how about every side could be configure able

sort of 6 tabs with 4? sub tabs
each tab has filters white/black list

subtabs could have 2 extra sub-export-import tabs ?

sort of this cube could support 6 different channels

------

in 1.7.10 farming station was burning RF for idle
that is the reason why i always would prefer to take another farming station over farming station(enderio)

--------------
vat in 1.7.10

it just need upgrades , i have had to run over 20 vats and it was not enough

speed , efficiency , proccesses at once , internal water gen (by installing 4 reservoirs inside)

i had and tried to set a fire under it or put lava , but that did not help

i would prefer internal upgrades over external , but any upgrades for vat is good , but probabably most important to me were one that would reduce cost for proccesses

-----

issue with JEI

when you look for items and recipes u often land on "decorative" ones , its realy hard to tell them appart

could u maybe add some way to look only for machines so if i enter "sag mill" i find sag mill and not decorative one

also creative items , like creative tanks , banks and so one stuff , would be nice "not to have" them listed in normal survival mode , it might be an issue that need to be dirrected to JEI developer.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
