### ISSUE TITLE
Energy Buffer does not display energy stored when pointing at the energy bar

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3882]
#### Issue Description:
You don't see the mouse on screenshot but I'm pointing at the energy bar.
![2016-12-04_23 13 07](https://cloud.githubusercontent.com/assets/8670392/20894643/8de0af6e-bb16-11e6-8958-e45ceae403cc.png)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.138_beta
- EnderCore: 0.4.1.60-beta
- Minecraft: 1.10.2
- Forge: 2135
- Mods: [list.txt](https://github.com/SleepyTrousers/EnderIO/files/622778/list.txt)

**Comment by Xiaminou** [comment]
bump, this is still present by the way.

**Comment by HenryLoenwind** [comment]
yes, the tooltips are still where the elements would be if the GUI was normal sized.

**Comment by Xiaminou** [comment]
Hmm I tried normal but still no tooltips:
![2017-11-23_15 16 27](https://user-images.githubusercontent.com/8670392/33177021-7572c6d6-d061-11e7-8f41-fd0b96a29bed.png)

**Comment by HenryLoenwind** [comment]
not the GUI scale, if the window wasn't smaller at the top than it should be...

(and I was acknowledging the bug)

**Comment by Xiaminou** [comment]
Oh I see.

Yeah just checking.
