### ISSUE TITLE
Fluid tank uses 16 buckets to refill EU2 watering can

### ISSUE THREAD

**Issue by charlesbevans** [SleepyTrousers/EnderIO#3883]
#### Issue Description:
When refilling an Extra Utilities 2 watering can, the EIO fluid tank uses 16 buckets of water. This is also the amount shown for filling in JEI.

#### What you expected to happen:
The can should only use 1 bucket to refill (tested with an EU2 drum).

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.138_beta
- EnderCore: 1.10.2-4.1.60_beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2171
- EU2: 1.0

Also reported to rwtema: https://github.com/rwtema/extrautilities/issues/1140

**Comment by HenryLoenwind** [comment]
This then isthe amount the watering can accepts when being offered. The fluid API works that way---a source sends an offer with the maximum amount available (16 buckets in case of the recipe check, one full tank) and the item that is being filled responds with the amount it actually took.

Pls raise this with exu and link that ticket in here. Thx

**Comment by charlesbevans** [comment]
Already done. Thanks.

**Comment by HenryLoenwind** [comment]
Thx, isn't that easy to see in the email notification

**Comment by HenryLoenwind** [comment]
After looking at the code that makes the JEI recipes, I'm fairly sure our code is right here.

**Comment by charlesbevans** [comment]
It's a matter of waiting for Tema to see it. There are 646 issues open on EU2 right now and no public source to let others pitch in.
