### ISSUE TITLE
ME Conduits break after server restart if you disconnect a side

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3884]
#### Issue Description:
If you disconnect a side of the ME Conduits by right-clicking with a YETA wrench it will break after server restart. Do note that this does not happen in all situations, some of them are just fine while others are broken.
![2016-12-05_18 34 57](https://cloud.githubusercontent.com/assets/8670392/20904463/ec2f6fe6-bb3f-11e6-80f0-3523b40a00f8.png)
![2016-12-05_18 35 00](https://cloud.githubusercontent.com/assets/8670392/20904464/ec2fd4ae-bb3f-11e6-9c43-4204f58bc854.png)
![2016-12-05_22 44 38](https://cloud.githubusercontent.com/assets/8670392/20904465/ec359330-bb3f-11e6-8536-c5fdc15ec06b.png)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.138_beta
- EnderCore: 0.4.1.60-beta
- Minecraft: 1.10.2
- Forge: 2135
- Mods: [list.txt](https://github.com/SleepyTrousers/EnderIO/files/622778/list.txt)

**Comment by HenryLoenwind** [comment]
That is a known limitation of the AE2 API and nothing we can change.

**Comment by HenryLoenwind** [comment]
@MatthiasMann This is what we had in 1.7.10 and you did some debugging for, isn't it?

**Comment by MatthiasMann** [comment]
The problem is that we are unable to ask AE2 if a connection would be possible or not. So EnderIO uses a heuristic to guess if a connection is possible or not.

But if you disconnect something that should be remembered. But I'm not sure what you mean it breaks after server restart - does it connect even so it should not?

**Comment by Xiaminou** [comment]
No, if you disconnect any part of the conduit it doesn't connect to anything anymore. Screenshot number 3 shows a good example of that. I disconnected the left connection and after restarting the server AE would not recognize the connection on the right, as you can see, the AE Cable on the right is not rendering a connection to the conduit.

**Comment by Xiaminou** [comment]
Just an update on this, it might be something different from what we first though. Today I found a case where I had disconnected a ME Conduit that was in the same blockspace as an Item Conduit. And after the server restart none of the conduits were working.
It looks like cutting a connection of an ME Conduit breaks all the conduits, need to do some more testing.
