### ISSUE TITLE
Game Crash when using Wireless lights and Architecture craft

### ISSUE THREAD

**Issue by help4tech** [SleepyTrousers/EnderIO#3885]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
When placing Architecture craft blocks in a wireless lights area it will crash the game.

#### Steps to reproduce:

1. Place wireless light
2. then place Architecture blocks within the range
3. crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.138_beta
- EnderCore: 1.10.2-0.4.1.60-beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2166

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
Unexpected error

java.lang.ClassCastException: crazypants.enderio.machine.light.TileLightNode cannot be cast to gcewing.architecture.ShapeTE
    at gcewing.architecture.ShapeBlock.getLocalBounds(ShapeBlock.java:152)

**Comment by HenryLoenwind** [comment]
This crash is happening in that other mod, report the crash there and link this ticket in there so I can provide assistance if needed. Thx

**Comment by help4tech** [comment]
Sadly they do not have a system for reporting a bug, so I have emailed them. This page will be linked for them.

**Comment by RedGuy54** [comment]
Any response?
