### ISSUE TITLE
Clearing Slice'n'Splice config in the 2x2 crafting slot

### ISSUE THREAD

**Issue by noobyaran9** [SleepyTrousers/EnderIO#3886]
#### Issue Description:
Crafting a configured Slice'n'Splice in the 2x2 crafting slot deletes everything in the machine including capacitor, axe and the shear.

#### What happens:
As the issue description.

#### What you expected to happen:
The machine resets w/o losing any item.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:3.0.1.138
- EnderCore:0.4.1.60
- Minecraft: 1.7.10
- Forge:12.18.2.2179

**Comment by HenryLoenwind** [comment]
Please state your problem, not just the expected result.

**Comment by VT-14** [comment]
It looks like he reset his machine and wasn't expecting the contents to be deleted.

I'm fairly certain that's intended behavior and there aren't any bugs here.  I mean, there is a red tooltip that states "this will clear all stored info!"  I'm curious what exactly noobyaran9 thought that would do.

Maybe add "... and contents!" to the end of that tool tip?

**Comment by noobyaran9** [comment]
I wasn't expecting the content to be deleted when resetting the machine.
