### ISSUE TITLE
[1.10.2] Reinforced Obsidian Duplication Bug

### ISSUE THREAD

**Issue by wstegema** [SleepyTrousers/EnderIO#3887]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".
Happens in Direwolf20 1.10.2, and still happens after updating to the latest enderIO and EnderCore as of 12/5/16

#### What happens:
When clicking on reinforced obsidian with a yeta wrench, it sends another reinforced obsidian out on the the floor in item form. The items are of all different sizes. 

![2016-12-05_19 41 07](https://cloud.githubusercontent.com/assets/24400617/20910390/c627d978-bb26-11e6-9b6c-b6dbb22f1673.png)

#### What you expected to happen:
Nothing should have happened

#### Steps to reproduce:

1. Place reinforced obsidian
2. Right click with yeta wrench
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.126_beta  and 1.10.2-3.0.1.138_beta
- EnderCore: 1.10.2-0.4.1.58-beta and 1.10.2-0.4.1.60-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2142

#### Your most recent log file where the issue was present: 

No change in the log file when it happens, does not crash or do anything else harmful

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
I have no idea why some of those items are that big. Or how they even can be that big...
