### ISSUE TITLE
request for decoration block - breathing dimensional transceiver

### ISSUE THREAD

**Issue by rahangar** [SleepyTrousers/EnderIO#3888]
Not sure if this is the right place to request a new block.  But here it goes.

Would you be inclined to add a block (for decoration) that looks like the dimensional transceiver and breaths like it?  It would really be cool if it could be chiselable via Chisels & Bits.

thanks!

**Comment by HenryLoenwind** [comment]
I don't think c&b can work with models that are not made up from bit-sized voxels, but you'd have to its author about that.

There is a third deco block on the roadmap for the rest of the machines. However, that breathing part is not (and cannot be) part of the block model, so it cannot be recreated by anything else but a dimTrans (or a completely new block that basically would be a dimTrans that doesn't work). So don't expect that to come, sorry.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by rahangar** [comment]
Understood.  Thanks for considering it.

Regards,
