### ISSUE TITLE
[enhancement] Creosote in Combustion Generator

### ISSUE THREAD

**Issue by LafinJack** [SleepyTrousers/EnderIO#3889]
Hi there, I'd just like to request creosote support for the Combustion Generator. When searching issues here I saw EIO already knows how to handle Railcraft and Immersive Engineering creosote appropriately, such as in the tanks, so I would think such a change should not be too difficult.

Thank you for the great mod!

Scott

**Comment by HenryLoenwind** [comment]
There are 3 sources for fuels:

* A build-in list
* The buldcraft fual registry
* self-registration by the mod that brings the fluid around

I'd have to look up how the other crosotes get in there, but I 'd expect it's no 3.

**Comment by HenryLoenwind** [comment]
I had the chance to look it up, the built-in list only contains the Ender IO fluids.

So please ask the mod(s) owning the fluid to register them accordingly (it's an IMC message they need to send).
