### ISSUE TITLE
Feature Request: Multi button input for redstone conduits

### ISSUE THREAD

**Issue by Damit84** [SleepyTrousers/EnderIO#3894]
I would love to have a single panel with multiple buttons on it to directly send a colored signal to the conduits.
A picture says more than a thousand words, so here is a little example:
![multi_button_example](https://cloud.githubusercontent.com/assets/8322579/21049542/b83376f0-be15-11e6-8d63-34a56edd3abe.PNG)

normal right click: standard button function (pulse)
shift + right click: toggle button like a lever. ( or configure the button: togge or pulse, pulse length, etc.)

**Comment by mindforger** [comment]
an equivalent display function would also be apriciated

**Comment by HenryLoenwind** [comment]
That one has been on my task list for ages, but it got displaced by "update to mc x.xx" several times.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by mindforger** [comment]
>but it got displaced by "update to mc x.xx" several times

i hope it doesn't get displaced again by 1.11 ... i already spotted the first request >_<

**Comment by Nuinethir** [comment]
My take on this...

https://github.com/SleepyTrousers/EnderIO/issues/4064

Added my vote for this idea here...

http://ideas.theideawall.com/EnderIO/Forum/TopicDetails/95456061-6b73-4cf4-9d24-4abf0aa12673
