### ISSUE TITLE
[1.10.2] Yeta Wrench config terminates server connection

### ISSUE THREAD

**Issue by 016Nojr** [SleepyTrousers/EnderIO#3895]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".
This needs to be reported anyway. (Direwolf20 1.0.0)

When changing the config option to disable the scroll wheel function for the Yeta Wrench, my connection gets terminated when I try to access an EnderIO machine.

#### Steps to reproduce:

1. Disable the scroll wheel config for the yeta wrench
2. Connect to a server
3. Try and access a Farming Station for example.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.126_beta
- EnderCore: 0.4.1.58-beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2124

#### Your most recent log file where the issue was present: 

http://www.mediafire.com/file/n6qukem4nn858k6/fml-client-latest.log (Log too big for pastebin)

**Comment by HenryLoenwind** [comment]
Please have a look, there may be a server crash log for 21:56:37 or so.

**Comment by 016Nojr** [comment]
If you give me a moment I will give you a fresh log. That log was actually from a week ago, but used in the same case before I knew it was EnderIO causing this.

**Comment by 016Nojr** [comment]
http://www.mediafire.com/file/l6173esa7dlsz63/fml-client-latest%282%29.log

**Comment by HenryLoenwind** [comment]
In the first log there was the whole server shutdown processing before the "client choking" messages. The second log had no server messages at all, were you connecting to a dedicated server?

**Comment by HenryLoenwind** [comment]
Ok, I do have a possible explanation: This is one of those config settings that absolutely have to match between server and client (when they are started). Is this your problem?

**Comment by 016Nojr** [comment]
Correct
