### ISSUE TITLE
Soul Machine painted stairs and slabs look like regular machines

### ISSUE THREAD

**Issue by meerple** [SleepyTrousers/EnderIO#3896]
#### Issue Description:
Cobblestone blocks get painted with soul machines correctly, but stairs and slabs get the regular machine texture.

#### What happens:
I put a Soul Machine blank machine and a cobblestone stair or slab in the painting machine. It gives me a stair or slab that says its painted with the soul machine, but it's the wrong color. 

#### What you expected to happen:
I expected to get stairs that were the same color as the soul machine block.

#### Steps to reproduce:

1. Put cobblestone stair and soul machine decorative block in painting machine
2. Look at the stair it gives you.
3. Visually compare the stair with the soul machine decorative block.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.138_beta
- EnderCore: 0.4.1.60-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by HenryLoenwind** [comment]
Oh, I see what's happening. For those blocks "```all```" textures are set to the same texture, but apparently the "```particle```" texture is not one of "```all```"...
