### ISSUE TITLE
Exception while updating neighbours

### ISSUE THREAD

**Issue by mrkarp** [SleepyTrousers/EnderIO#3897]
Hello,

This just started happening after this afternoon, unsure as to what was paced / moved / broken in the mean time but every time anyone connects to the server the following happens:

`**_Description: Exception while updating neighbours

java.lang.ClassCastException: crazypants.enderio.conduit.TileConduitBundle cannot be cast to com.rwtema.extrautils2.tile.XUTile_**`

Full Report:
http://pastebin.com/N0pvqZrG

We just updated to the latest version of Direwolf20 1.10.2 _v1.13_ in hopes it might have been an inevitable glitch with older versions.

Please let me know if there is anymore i can provide to assist. I also don't know if i should be reporting this to rwtema either as its interacting with his mod?

Thanks!

**Comment by mrkarp** [comment]
Currently rolling back 5 hours to test, will update.

**Comment by mrkarp** [comment]
Block: extrautils2:CreativeEnergy
    Block location: World: (672,61,1335) = EnderIO power conduit. 

Just had another one though, was an immersive engineering cable to a extrautils2 crusher?
http://pastebin.com/w48eFKn7

**Comment by MatthiasMann** [comment]
Sounds like a world corruption to me. Did you update/change any mods or settings before this happened or was the update you mentioned done after the corruption?

**Comment by HenryLoenwind** [comment]
Do you have a "extrautils2:CreativeEnergy" block in your world? If yes, report this to exu2, if not, you have world corruption.

**Comment by mrkarp** [comment]
There are no "extrautils2:CreativeEnergy" in the world and i thought it would be corrupted but really didn't want to start over. Weird part is this all started with client crashes that were caused by:
_-- Block being tesselated --
Details:
 Block type: ID #1754 (tile.blockFusedQuartz // crazypants.enderio.material.fusedQuartz.BlockFusedQuartz)_

So i don't know if some data didn't get updated when we removed glass / placed it, but i can assume the worst that our world is dead.

Thanks guys! Let me know if there is anything you can think of, imma just ride this world till its dead.
