### ISSUE TITLE
[1.7.10] Yeta Wrench config terminates server connection

### ISSUE THREAD

**Issue by Psithief** [SleepyTrousers/EnderIO#3899]
#### Issue Description:
Note: ~~If this bug occurs in a modpack, please report this to the modpack author.~~ 

Almost identical to #3895. Just providing another data point.

#### What happens:

Single-player server crashes, but the single-player client does not crash.

#### What you expected to happen:

No crashes.

#### Steps to reproduce:

1. Play Single Player.
2. Set `useSneakMouseWheelYetaWrench` to `false` in configuration via in-game "Mod Options" with `Apply Globally` checked.
3. Whilst playing, press the Yeta config key `Y`.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: forge-10.13.4.1614

#### Your most recent log file where the issue was present: 

https://gist.github.com/Psithief/aea942f97960c3b8ac5200fc1c54fc5c

**Comment by Psithief** [comment]
#### A known good version

* EnderIO: EnderIO-1.7.10-2.3.0.423_beta
* EnderCore: EnderCore-1.7.10-0.2.0.31_beta
* Minecraft: 1.7.10
* Forge: forge-10.13.4.1558

**Comment by Psithief** [comment]
Closing temporarily, will re-open if modpack author can't fix.

**Comment by HenryLoenwind** [comment]
Yes, I think this is the same cause, just another way to trigger an error from it. In that other case, client and server couldn't agree about network packets because the server knew one more than the client, in this case that "unused" network packet is actually used from somewhere else.

**Comment by Psithief** [comment]
Is there a last known good version between those two versions listed?

**Comment by HenryLoenwind** [comment]
That problem most likely has existed for ages, so no known good version...

**Comment by Psithief** [comment]
I gotta build my own version :+1:
