### ISSUE TITLE
[1.10.2] Tooltips not fitting on screen with GUI open

### ISSUE THREAD

**Issue by p75369** [SleepyTrousers/EnderIO#3900]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. 
It's occuring on HermitPack 1.4.0 and I've reported it to the team, but I can't see any evidence on their forum that they do anything with them, so better safe than sorry, here it is too.

https://forum.feed-the-beast.com/threads/enderio-loot-capacitor-doesnt-fit-on-screen-in-enderio-gui.201664/

Particuarly large tooltips are not correctly scaling to screen boundries when an EnderIO GUI is open.

#### What happens:

When looking at a large tooltip (say a "loot" capacitor tooltip, or "Impossibly hard wheat sticks" from Tinkers Construct) whilst an EnderIO GUI is open, the tooltip will not detect the left edge of the screen and will extend beyond it.

#### What you expected to happen:

Tooltips to automatically scale, wrap and position themselves to be completely on the screen, same as when any other GUI is open.

#### Steps to reproduce:

1. Aquire an item with a really big tooltip, eg, "loot" capacitor from EnderIO or "Impossibly hard wheat sticks" from Tinkers Construct
2. Open an EnderIO GUI.
3. Mouse over item to display tooltip

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.126_beta
- EnderCore: 1.10.2-0.4.1.58-beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2124

#### Your most recent log file where the issue was present: 

This would be on the server end?

**Comment by p75369** [comment]
only a "suggestion"? i would have thought "able to be read" was a critical feature of tooltips, which this interferes with.

**Comment by HenryLoenwind** [comment]
So, does that classify it as a "bug" or an "inquiry" then? Those are the three categories... "Make something new", "Repair something broken" and "How does that work"?

**Comment by p75369** [comment]
I suppose it depends on how you look at it. From an end user perspective, the tooltips are broken and need repairing. From a code perspective... I don't know, maybe the code hasn't been written yet, meaning it would be new code?

Sent from my phone.

---- Henry Loenwind wrote ----


So, does that classify it as a "bug" or an "inquiry" then? Those are the three categories... "Make something new", "Repair something broken" and "How does that work"?

-

**Comment by HenryLoenwind** [comment]
The point is that those are vanilla tooltips. And by definition vanilla is "not broken" when looking at a mod. So this is a new feature for us to fix vanilla tooltips... (like JEI does in vanilla GUIs)

**Comment by p75369** [comment]
(I know I'm being pedantic here, file it under whatever you want, just enjoying the debate)

But vanilla tooltips are never so large as to be a problem. It's only an issue because EnderIO creates excessively large tooltips with its "loot" capacitors. You can't blame Mojang because you created something bigger than the system was intended to support.

Sent from my phone.

---- Henry Loenwind wrote ----


The point is that those are vanilla tooltips. And by definition vanilla is "not broken" when looking at a mod. So this is a new feature for us to fix vanilla tooltips... (like JEI does in vanilla GUIs)

-
