### ISSUE TITLE
Fuzzy Match tooltip clarification and inversion

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [SleepyTrousers/EnderIO#3901]
Can you adjust the text for the Advanced Item Filter's fuzzy filter to state "Fuzzy Match for greater than N% Damage" and add options for "Fuzzy Match for less than N% Damage"?

**Comment by HenryLoenwind** [comment]
sounds good

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
