### ISSUE TITLE
Ender Rail missing

### ISSUE THREAD

**Issue by digitalseraphim** [SleepyTrousers/EnderIO#3902]
#### Issue Description:
This is happening in a modpack that I am the maintainer of (https://minecraft.curseforge.com/projects/digitalseracraft). I was trying to set up cart transport and was unable to find the "ender rail". I looked through the code and noticed that the recipe is commented out at:

https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/machine/soul/SoulBinderRecipeManager.java#L35

Is this intended? Is there something elsewhere that should be making the Rail show up? I know there is a newer version available on curse, but its an alpha version, so I've stayed away. I looked through the config files, and the rails are enabled in the main "EnderIO.cfg". 

Thanks for the help!

### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.138_beta
- EnderCore: 1.10.2-0.4.1.60-beta 
- Minecraft: 1.10.2
- Forge: 12.18.2.2122

#### Your most recent log file where the issue was present: 
There is no mention of the ender rail in my log file. If you would still like one, I would be happy to upload one.

**Comment by HenryLoenwind** [comment]
Seems someone forgot to remove those config settings...

The EnderRail got dropped in the 1.8.9 update because of game functionality changes.

**Comment by digitalseraphim** [comment]
Ok, thanks for the info!!!
