### ISSUE TITLE
Pressurized Fluid Tank does not show up in JEI

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3906]
#### Issue Description:
For some reason it doesn't show up in the list, even turned on JEI hiding mode to see if it was hidden, but it's not (the item showing up in the screenshot is the decoration version).
![2016-12-12_16 49 22](https://cloud.githubusercontent.com/assets/8670392/21105721/8e65fadc-c08b-11e6-970c-0803bda140c1.png)

- Server
- EnderIO: 3.0.1.139_beta
- EnderCore: 0.4.1.61-beta
- Minecraft: 1.10.2 
- Forge: 2185
- Mods: [list.txt](https://github.com/SleepyTrousers/EnderIO/files/646454/list.txt)

**Comment by HenryLoenwind** [comment]
It is in the Creative inventory, so there must be something weird with JEI. (And no, we don't have special code to hide it from JEI).

@mezz Any idea?

https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/machine/tank/BlockItemTank.java#L67-L71

**Comment by mezz** [comment]
JEI applies a default subtype interpretation to items that support fluid capabilities. It does not account for the meta value of the item, which means it is incorrectly merging your two types of fluids tanks together. This is almost certainly a JEI bug unless you have added your own subtype interpreter for the tank items.

**Comment by HenryLoenwind** [comment]
and fixed in JEI
