### ISSUE TITLE
No way to set energy buffer on Dimensional Transciever

### ISSUE THREAD

**Issue by Saereth** [SleepyTrousers/EnderIO#3907]
#### Issue Description:
EnderIO - 1.10.2-3.0.1.139_beta

When increasing the IO rate of the dimensional transceiver, (In this case to 500krf/t) the IO is rate limited by the internal buffer which is capped at 250krf/t. There doesn't seem to be anyway to increase this in the configs.

#### What happens:
IO config is set above 250k, transfer rate limited to 250k by internal buffer

#### What you expected to happen:
internal buffer scales with max/IO or has a separate config option.

#### Steps to reproduce:

1. increase Transceiver I/O in configs beyond 250krf/t
2. input more than 250krf/t and attempt to output somewhere else
3. only 250krf/t is transfered
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.139_beta
- EnderCore: 1.10.2-0.4.1.60-beta 
- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2185

**Comment by HenryLoenwind** [comment]
The config key you're looking for is called "transceiver_power_buffer".
