### ISSUE TITLE
Powered Spawner not producing mobs

### ISSUE THREAD

**Issue by TheVanoq** [SleepyTrousers/EnderIO#3909]
#### Issue Description:
The powered spawner receives energy, "works" until the flame reaches 100% and resets back to 0% without producing a mob.

#### What happens:
The powered spawner receives energy, "works" until the flame reaches 100% and resets back to 0% without producing a mob.

#### What you expected to happen:
A mob to spawn

#### Steps to reproduce:

1. Place Powered Spawner with the desired mob type inside
2. Power it
3. Receive no mob spawn
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.136_beta
- EnderCore: 1.10.2-0.4.1.60-beta
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2185

#### Your most recent log file where the issue was present: 

Logs show nothing when this happens

See video: https://gfycat.com/BlandTemptingAfricanharrierhawk

**Comment by TheVanoq** [comment]
Still happens in EnderCore-1.20.2-0.4.1.61-beta and EnderIO-1.10.2-3.0.1.139_beta as of today. The first couple of times the spawn works. After a few "waves" of mobs, nothing spawns.

**Comment by bookerthegeek** [comment]
Question, Are you using an entity limiter on your server? It sounds like if you are you have reached the max entities and it is stopping the spawn.

**Comment by TheVanoq** [comment]
No, nothing like that. And night/day doesn't matter btw. It happens randomly after a couple of "waves". (in case you're thinking of mob limit)

**Comment by TheVanoq** [comment]
Like I said before: The logfile shouldn't matter in this case. There is no output to the console. It just doesn't work. No errors.

**Comment by HenryLoenwind** [comment]
The logfile does matter. We've been getting plenty of reports over the last months that different blocks just stop working and we cannot see any reason for it. There certainly isn't any code in our blocks that decides to do something or just fake it. So there must be an outside influence. However, with nobody caring enough to even add a mod list, all we can do is twiddle our thumbs and facepalm hard.

Next build will add notification bubbles to the spawner; like those of the farm. Maybe that'll help you figure out what#s happening.

**Comment by bookerthegeek** [comment]
We have not had any reports on our server (Running DW20 1.10 so no idea of version off the top of my head) But we have not been having any issues. IF any come up, I will make sure to get you all the information. :)

**Comment by technolem** [comment]
I think I found the problem, it seems to be the dark utilities tether when using an enderman spawner. I ran into it while playing the DW20 1.10 pack, so I did some testing in creative. The wither spawner works, and the enderman only fail after a few waves of spawning into the tether. If you restart without the tether it works until you place the tether down again, then fails a few waves later.
