### ISSUE TITLE
Empowered Shear Duping

### ISSUE THREAD

**Issue by Ravin890** [SleepyTrousers/EnderIO#3911]
#### Issue Description:
When you empower the darksteel shears items that require shears get doubled.

#### What happens:
Whenever an empowered shear is used on an item that requires it, i.e. leaf blocks instead of getting 1 item, you get 2.

#### What you expected to happen:
When you break a block with the shears or shear a sheep you only get 1 of the block or a normal amount of wool.

#### Steps to reproduce:

1. Empower Darksteel shears
2. Break 1 leaf block from tree
3. Get 2 blocks instead of 1

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.141_beta
- EnderCore: 2-0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 2166

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

*I had not looked at minecraft version initially fixed...

**Comment by HenryLoenwind** [comment]
"wontfix" for 1.7.10

**Comment by Ravin890** [comment]
I messed up... i meany 1.10.2
