### ISSUE TITLE
Client Server Syncing Issue - Alloy Smelter

### ISSUE THREAD

**Issue by LordSkittles** [SleepyTrousers/EnderIO#3912]
#### Issue Description:
Whenever I attempt to create an alloy in the alloy smelter, ie Soularium, it doesn't register that I have placed the items in the inventory. I have tested in single player and it works fine, but the moment I hop onto my server, it cannot create the alloys. I have replaced the configs in the server with my local ones (just to make sure that wasn't the issue) and same with the mod versions.

#### What happens:
I don't get the items.....

#### What you expected to happen:
I expect to be able to get the items.

#### Steps to reproduce:

1. Place items in alloy smelter
2. Close the inventory
3. look at player inventory

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: Server (1.10.2-3.0.1.138_beta) Client (1.10.2-3.0.1.138_beta)
- EnderCore: Server (1.10.2-0.4.1.60-beta) Client (1.10.2-0.4.1.60-beta)
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2185

**Comment by LordSkittles** [comment]
Interesting development. It appears that all of the machines are experiencing this issue. only the furnace part of the alloy smelter is working

**Comment by LordSkittles** [comment]
[fml-client-latest.txt](https://github.com/SleepyTrousers/EnderIO/files/659103/fml-client-latest.txt)
[fml-server-latest.txt](https://github.com/SleepyTrousers/EnderIO/files/659104/fml-server-latest.txt)

**Comment by LordSkittles** [comment]
There is the server and client logs

**Comment by HenryLoenwind** [comment]
```
[04:19:23] [Server thread/ERROR] [EnderIO/EnderIO]: Could not load default recipes file /home/minecraft/server/config/enderio/SAGMillRecipes_Core.xml from EnderIO jar: /home/minecraft/server/config/enderio/SAGMillRecipes_Core.xml (Permission denied)
[04:19:23] [Server thread/INFO] [STDERR/EnderIO]: [crazypants.enderio.machine.recipe.RecipeConfig:loadRecipeConfig:36]: java.io.FileNotFoundException: /home/minecraft/server/config/enderio/SAGMillRecipes_Core.xml (Permission denied)
```

and so on for each single Ender IO config file on the server.
