### ISSUE TITLE
Turning on Powered Spawner Causes Crash

### ISSUE THREAD

**Issue by Megistus** [SleepyTrousers/EnderIO#3916]
#### What happens:

I have a powered spawner set to spawn blaze in a kill room with a killer joe, item vacuum, and xp vacuum. Spawner is set with a switch to turn system on and off. When turning on the spawner, game completely seizes and I have to force shut down minecraft. It throws the error that is attached.

#### What you expected to happen:

No crash

#### Steps to reproduce:

See Above

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.0.1.141_beta
- EnderCore:EnderCore-1.10.2-0.4.1.61-beta
- Minecraft: 1.10.2
- Forge:12.18.3.2185

#### Your most recent log file where the issue was present: 

[SpawnerCrash.txt](https://github.com/SleepyTrousers/EnderIO/files/653439/SpawnerCrash.txt)

**Comment by Megistus** [comment]
Oh ... and sword killer joe is a vanilla diamond sword enchanted with sharpness III

**Comment by Megistus** [comment]
I need to amend what I wrote as per the crash especially as I have further understood what I was reading in the crash report and have fussed around and realized that it is not the powered spawner.

It is Killer Joe that is causing the crash. 

I was able to get into my world through MCEdit and destroy the switch powering off Joe and was able to log back into my world. (SSP) On a hunch, I put a switch on another killer joe that had worked with previous versions of EnderIO (system was turned off previously through redstone lamps causing a vanilla spawner to be rendered inert). I deactivated the lamps allowing the spawner to spawn monsters which worked fine. Then I switched on Killer Joe and then Minecraft crashed again. Different Joe, different physical location, in a kill room that had previously worked successfully.  Crash report the same.

**Comment by HenryLoenwind** [comment]
This is a crash in "mca" (Minecraft Comes Alive?), report it there.

**Comment by Megistus** [comment]
Really? Because if I downgrade EnderIO to 137_beta then the issue goes away and the Killer Joe works as it is supposed to. MCA has not changed since August. Apparently the incompatibility issue arose in the last round of EnderIO updates.

**Comment by mindforger** [comment]
MCA hooks in the event of slashing a mob with the killer joe and crashes

it MAY be fault of EIO, but he can't look into the crashing code to find the fault, so link this issue to MCA and let's see what they say
