### ISSUE TITLE
Soulbound items overwrite other items

### ISSUE THREAD

**Issue by Yashimata** [SleepyTrousers/EnderIO#3917]
#### Issue Description:
Soulbound items delete items if they're still on your player after death.

#### What happens:
If items are bound to you in other ways (for example, anchored with Random Things), then soulbound items will, on death, overwrite items on your bar or in your inventory without checking if that inventory slot is empty.

#### What you expected to happen:
Soulbound items should probably be checking to make sure the slot they're trying to fill is empty before overwriting them.

#### Steps to reproduce:

1. Get any two items (for example, an iron sword and a bow).
2. Use Random Things (or another mod) to anchor the first item.
3. Enchant the second item with soulbound.
4. Place the anchored item in your first hotbar slot. The soulbound item can be anywhere.
5. Die however you like (mob, /kill, void).
6. Respawn
7. Notice that the first item in your hotbar has been replaced by the soulbound item, even though the first item never left your inventory. Gone forever.

You can scale this up with as many items as you want. If the first 5 items in your hotbar are anchored and you have 7 soulbound items, the 7 soulbound items will overwrite the 5 anchored items on your bar (and the two blank spots after, but nothing is lost there).

____
#### Affected Versions

- EnderIO: 1.10.2-3.0.1.141_beta
- EnderCore: 1.10.2-0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by VT-14** [comment]
From my memory, items with Soulbound don't move on death.  Have you reproduced this issue with only Ender IO and Random Things?  Have you reported the bug to Random Things as well?  Have you done any testing with "KeepInventory" set to true?

Also, Logfile?

**Comment by HenryLoenwind** [comment]
No, soulbound does check that the slot is empty (it puts the items into the first free slot, to be exact...). I'd say the other mod runs after soulbound and doesn't want to override the souldbound item but fails to either put its item somewhere else or to move it out of the way.

**Comment by HenryLoenwind** [comment]
(closing this as experience shows that soulbound issues are not our fault)
