### ISSUE TITLE
Remarkable Capacitor toolpit cannot be read

### ISSUE THREAD

**Issue by ExDomino** [SleepyTrousers/EnderIO#3918]
Hello. On my screen (1680x1050) the toolpit of the Remarkable Capacitor cannot be read (except if i set my gui scale to small) because of the text that is too long. In auto (the bigger), in large and even in normal, it is cut in the middle. For example, in normal, anything left of "Simple Hungry" is hidden. You should use line break for people that have small screen, and my screen is even not small.

**Comment by VT-14** [comment]
#3900
