### ISSUE TITLE
EnderIO / Applied Energistics compatibility issue crashing minecraft

### ISSUE THREAD

**Issue by AlHollandiyah** [SleepyTrousers/EnderIO#3921]
#### Issue Description:
When I try to load EnderIO together with Applied Energistic minecraft crashes at launch.

#### What happens:
Minecraft crashes at launch.

#### What you expected to happen:
Minecraft loading properly.

#### Steps to reproduce:

1. Put EnderCore, EnderIO and Applied Energistics in mods folder.
2. Launch Minecraft.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: v3.0.1.141_beta
- EnderCore: v0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Applied Energistics 2: v4_alpha_9

#### Your most recent log file where the issue was present: 

http://pastebin.com/wpZ9MDr9

#### Extra Information: 

As I am not sure which of the 2 mods is responsible I posted this in both githubs, the other ticket can be found here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2708

**Comment by HenryLoenwind** [comment]
![image](https://cloud.githubusercontent.com/assets/1485873/21281198/21faf7e0-c3eb-11e6-86b9-dc0ebe9b88ff.png)

**Comment by AlHollandiyah** [comment]
This is very weird, I tried it again and it still crashes. Also, I don't really know what logfile you are looking for as missing, because I did post a crashlog pastebin link above. If I know what you are missing I can provide it!

**Comment by AlHollandiyah** [comment]
Screenshots of modlist with either just EnderIO or just AE2:

![2016-12-17_00 02 48](https://cloud.githubusercontent.com/assets/9619351/21281350/3407d240-c3ec-11e6-914c-dadc367eb944.png)

![2016-12-17_00 01 36](https://cloud.githubusercontent.com/assets/9619351/21281349/34032e52-c3ec-11e6-9764-bb9c89e66e71.png)

**Comment by AlHollandiyah** [comment]
Tried to reinstall forge without mercurius as that seemed to be a major difference between your modlist and mine, but it still crashes.

Here is another crashlog: http://pastebin.com/u9E9Htuf

**Comment by HenryLoenwind** [comment]
Closing this one, see EA2 ticket for status.

**Comment by AlHollandiyah** [comment]
Just a little question, so I can make better reports in github in the future. This topic has "log missing" as a tag, what log other then the two crashlogs do I need to post that were missing now?

**Comment by HenryLoenwind** [comment]
Those are crash **reports** you posted. I wanted to have a look at the normal logfile of that run. The one that shows up in the launcher window. Because there I can see what happened before it finally crashed, e.g. if some mod wrote a line like "not registering oredict entry because there's a full moon today" or if one of those cracked launchers was used that corrupt the game startup process, or ...

**Comment by AlHollandiyah** [comment]
Ah, thats clear, I also asked that in a post above because I am more then happy to provide anything a mod author needs to find out what goes wrong! I will post both in future tickets, thanks for clarifying!

**Comment by HenryLoenwind** [comment]
Funny thing is: Whenever a report contains a full log and everything, I can diagnose the problem with a look at the first line of the stack trace and don't need anything more. ;)
