### ISSUE TITLE
Question: How to use Inventory storage system

### ISSUE THREAD

**Issue by Kaisoul** [SleepyTrousers/EnderIO#3922]
EnderIO - 1.10.2-3.0.1.141_beta

Inventory storage system blocks trying to figure out how there used but i can't seem to figure it out.

Mind providing an explanation on how there used.

**Comment by VT-14** [comment]
If Storage Blocks are new, then I assume they are meant to work with the Inventory Panel.

http://wiki.enderio.com/Inventory_Panel

**Comment by HenryLoenwind** [comment]
No magic. Craft them, connect them to an Inventory System, done.
