### ISSUE TITLE
Redstone Conduits and Bundled Cables

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3923]
I've done a search to see if there were any plans for integration with Project:Red Bundled Cables or more recently Super Circuit Maker's, and while there was a couple of issues mentioning it I'm still not sure where EnderIO stands.

What I would like to see is a conduit that can support multiple I/Os in each direction like bundled cable can or a block to convert from bundled cables into conduits, for easy transition between SCM and Conduits, instead of having to connect a dozen blocks for each signal color.
Has this ever been considered, or are there any plans for it?

While I'm at it I also would like to suggest an inverted redstone conduit, just so you don't have to place an ugly redstone torch next to your conduit line when you need to invert a redstone signal.

**Comment by HenryLoenwind** [comment]
Redstone logic is on the TODO list but has been pushed down by "Upgrade to 1.8.9", "Upgrade to 1.9", "Upgrade to 1.9.4", "Upgrade to 1.10.2" and "Upgrade to 1.11".

Bundled Redstone support is on the "I won't implement 200 different APIs, get together and define a standard" list.

**Comment by Xiaminou** [comment]
Yeah we really are moving through minecraft versions too fast, aren't we?

Bundled cables are becoming so common in minecraft there should really be a standard for it. The whole of redstone needs standards for the modded community.

**Comment by HenryLoenwind** [comment]
Btw, I made a draft for a standard: https://docs.google.com/document/d/1TLjHupjBVnHL9lKrZR26bj1cM_9slIE5WPRjepflbRg

**Comment by Xiaminou** [comment]
Good to know, how are people responding to it?

**Comment by HenryLoenwind** [comment]
Needs more people to respond ;)

**Comment by VT-14** [comment]
I know several mods are going to insist on 0-255 signal strengths.  It opens the door for more precision and possibilities, and is simply a factor of 17 (and rounding) to convert between 0-15 and 0-255.

I know Super Circuit Maker does 0-255, and I think Red Power does too, but I'm not certain on that one.

**Comment by HenryLoenwind** [comment]
Goot point @VT-14, I added a new chapter on signal encoding.

**Comment by Xiaminou** [comment]
Hopefully this will be used for comparators and devices that emit redstone signal based on storage. While Super Circuit Maker uses 0-255 signal strenght their version of the comparator still only has 16 states.

**Comment by VT-14** [comment]
+Xiaminou is that new?  The Inventory Scanner use to use all 255 signals.

**Comment by Xiaminou** [comment]
Does it? the few times I've used it it was only giving factors of 17. I might be wrong, needs to be double checked.

**Comment by HenryLoenwind** [comment]
If it read the comparator value of the target block using the vanilla API, it will only get a value of 0-15. The only way to get different values would be to read the inventory contents and calculate from there. Not quite what people expect a comperator to do, honestly.

**Comment by Xiaminou** [comment]
Well that's actually something I would like to see.
