### ISSUE TITLE
Ender IO + EU & Farming Station

### ISSUE THREAD

**Issue by BurovB** [SleepyTrousers/EnderIO#3925]
Can Ender IO use EU for running his machines and did Farming station can work with crops form IC2?

**Comment by HenryLoenwind** [comment]
no. yes.

**Comment by Nex4rius** [comment]
Does that mean the Farming Station can harvest the IC2 crops? It's not working for me.
<img src="http://i.imgur.com/8xzlZyK.jpg" width=700px>
EnderIO-1.7.10-2.3.0.429_beta
industrialcraft-2-2.2.826-experimental
