### ISSUE TITLE
[1.10.2] Gas conduits are not available even though enabled and mekanism api present

### ISSUE THREAD

**Issue by addrever** [SleepyTrousers/EnderIO#3926]
#### Issue Description:

Gas conduits are not being enabled even though the Mekanism API is present.

#### What happens:

Gas Conduits do not appear in jei

#### What you expected to happen:

Gas conduits appear and are craftable.

#### Steps to reproduce:

1. install enderio, jei and mekanism
2. load game
3. check jei for gas conduits
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.142_beta
- EnderCore: 1.10.8-0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Mekanism - 1.10.2-9.2.1.295
- Mekanism Generators - 1.10.2-9.2.1.295
- Mekanism Tools - 1.10.2-9.2.1.295

#### Your most recent log file where the issue was present: 

[EnderIO.txt](https://github.com/SleepyTrousers/EnderIO/files/659641/EnderIO.txt)
[2016-12-18-4.log.gz](https://github.com/SleepyTrousers/EnderIO/files/659642/2016-12-18-4.log.gz)

**Comment by addrever** [comment]
Checked closed issues and see that there requires a re-implementation of this feature and that this is a duplicate.  I apologize.  Can I ask for a status update on this though, please?

**Comment by HenryLoenwind** [comment]
Status still is "Mek is in such a bad state that I will not touch it with a ten foot pole." Sorry, if they'd use the Forge gas API instead of rolling their own, this'd be a non-issue.
