### ISSUE TITLE
Vacuum Chest should not attract items when not activated

### ISSUE THREAD

**Issue by SharkWipf** [SleepyTrousers/EnderIO#3929]
#### Issue Description:
Vacuum chests have a redstone setting. When they are disabled this way, they still suck items towards 'em, they just don't pick up the items. This makes this redstone setting fairly useless.

#### What happens:
Vacuum chests pull in items even when disabled/set to never active.

#### What you expected to happen:
Vacuum chests stop attracting items when disabled.

#### Steps to reproduce:

1. Set vacuum chest to "Never active"
2. Throw item on the ground
3. Watch item get pulled towards vacuum chest

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.142_beta
- EnderCore: 1.10.2-0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

N/A

**Comment by SharkWipf** [comment]
Hmm, on closer inspection it does seem to work this way already, not sure why it didn't work for me earlier. 
Closing.

**Comment by HenryLoenwind** [comment]
Possibly client-server desync. The Vacuum Chest is one of the few blocks that does the same work on the client and server. Most machines just do it on the server and send the "render as on"/"render as off" data to the client. Which means that our complete Redstone code is designed to run server-side and may not be as robust for the Chest as would be nice...

**Comment by HenryLoenwind** [comment]
(read that tag as "most probably it is a bug, but is is so minor and only cosmetic that it's not worth to fix it"

**Comment by SharkWipf** [comment]
Fair enough, if I figured out what was happening exactly earlier I wouldn't even have reported it in the first place, so works for me
