### ISSUE TITLE
Ender IO and EnderCore RF API crashing on multiple versions

### ISSUE THREAD

**Issue by AlligatorFarts** [SleepyTrousers/EnderIO#3930]
#### Issue Description:
FML crashes before title screen due to RF API

#### What happens:

The FML crashes right after the post-initialization stage

#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta also 28, 27. and 26
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta also 36
- Minecraft: 1.7.10
- Forge: 1.7.10-Forge10.13.4.1558-1.7.10

#### Your most recent log file where the issue was present: 

http://pastebin.com/DenFR1Nr

Thanks.

**Comment by HenryLoenwind** [comment]
This has absolutely nothing to do with RF. Not in the slightest. This is you trying to use beetroot in Minecraft 1.7.10. Hint: It was introduced with Minecraft 1.9.

**Comment by AlligatorFarts** [comment]
How do I fix this problem then?

**Comment by HenryLoenwind** [comment]
By removing the invalid config value you added...

**Comment by AlligatorFarts** [comment]
@HenryLoenwind I haven't added anything to my knowledge, I was just trying to put together a modpack. Which config value is it?

**Comment by HenryLoenwind** [comment]
cropConfig.json

**Comment by AlligatorFarts** [comment]
@HenryLoenwind Thank you very much! I believe that happened because I was playing on a 1.10.2 version before I decided to switch to 1.7.10.
