### ISSUE TITLE
crash on conduit rendering in 142 beta

### ISSUE THREAD

**Issue by jdratlif** [SleepyTrousers/EnderIO#3931]
#### Issue Description:

Looking at some conduits (redstone, ender energy, item) and cycling through the yeta wrench modes caused a crash in my game.

This was not happening before the 142 beta I just updated to. I downgraded to 141 and the crash stopped.

- EnderIO: 1.10.2 3.0.1.142
- EnderCore: 0.4.1.161
- Minecraft: 1.10.2
- Forge: 2185

Crash log is here.
http://pastebin.com/xxEUTVxy

I haven't been able to reproduce this crash in a single player world with a stripped down mod pack, so here is my mod pack and world file if you want it.

http://games.technoplaza.net/temp/phoenix-world-eio142_crash.zip - My world file
Mod Pack - https://minecraft.curseforge.com/projects/skyblock-phoenix (it's on curse) version 1.0-beta7

**Comment by Mohron** [comment]
Also experiencing this.
http://pastebin.com/EyfXpVJi

**Comment by jdratlif** [comment]
I haven't seen this issue in the 144 beta. I just updated to 145, but I've been played 144 almost since it came out.

I did see an invisible conduit coming out of a half slab facade, but it was a one time thing and I haven't seen anything like it since.
