### ISSUE TITLE
morph o tool and insulated redstone conduit causing crash

### ISSUE THREAD

**Issue by mahall1988** [SleepyTrousers/EnderIO#3932]
#### Issue Description:
while holding vazkii's morph o tool, if i look at a insulated conduit i crash and get the following crash log

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.0.1.142
- EnderCore:1.10.2-0.4.1.61
- Minecraft: 1.10.2
- Forge:12.18.3.2185

#### Your most recent log file where the issue was present: 

[crash-2016-12-19_14.17.44-server.txt](https://github.com/SleepyTrousers/EnderIO/files/661272/crash-2016-12-19_14.17.44-server.txt)

**Comment by mahall1988** [comment]
ok maybe not morph o tool as im now only using a simple yeta wrench and still crashing when interacting with conduits. this was an item conduit system this time

[crash-2016-12-19_18.07.22-client.txt](https://github.com/SleepyTrousers/EnderIO/files/661782/crash-2016-12-19_18.07.22-client.txt)

**Comment by HenryLoenwind** [comment]
#3931
