### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by Thunderheadz** [SleepyTrousers/EnderIO#3935]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".
When i launch minecraft 1.10.2 it slows down at 7/7 19/24 model loading baking. Then it crashes saying out of memory. It is crazy I have barely 30 mods, RAM to spare and then some, and I tried taking out some of the mods still didn't do a thing. Will continue to try but help would be nice thanks.

#### What happens:
crashes on start up

#### What you expected to happen:
to work

#### Steps to reproduce:

1.click play
2.wait
3.crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:most 1.10.2 but 3.0.1.138 through 144
- EnderCore:EnderCore-1.10.2-0.4.1.61-beta
[crash-2016-12-20_18.19.56-client.txt](https://github.com/SleepyTrousers/EnderIO/files/665093/crash-2016-12-20_18.19.56-client.txt)

- Minecraft: 1.10.2
- Forge:1.10.2-12.18.3.2185

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
I wouldn't call 1GB "§much" memory, that's barely enough for vanilla...

Give your game more RAM.

**Comment by Thunderheadz** [comment]
how do i add RAM to my game?

**Comment by AnrDaemon** [comment]
https://lmgtfy.com/?q=how+do+i+add+memory+to+minecraft
