### ISSUE TITLE
Crash Regarding Fuzed Quartz an Biomes of Plenty

### ISSUE THREAD

**Issue by john01dav** [SleepyTrousers/EnderIO#3939]
#### Issue Description:
This issue does occur in a modpack, but, [reporting it there does](https://forum.feed-the-beast.com/threads/server-crash-with-biomes-of-plenty-and-enderio.205228/) not yield any responses. I am hoping that I can get some help here.

#### What happens:
The attached stack trace happens randomly on my server, thus causing it to stop. Based on the stack trace, it looks like Biomes of Plenty is calling some function on fuzed quartz that isn't implemented. As such, I think the fix would be somewhat easy.

#### What you expected to happen:
I expect my server to continue running without crashing,  this bug is one of several that prevents that from happening.

#### Steps to reproduce:
NOTE: I don't know of exact steps, so, these are a guess.
1. Place fused quartz in the world near BOP grass.
2. Wait
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.138_betae
- EnderCore: 1.10.2-0.4.1.60-beta
- Biomes of Plenty: 5.0.0.2109
- Minecraft: 1.10.2
- Forge: 12.18.2.2171
- Forge Mod Loader: 8.0.99.99

#### Your most recent log file where the issue was present: 
https://gist.github.com/john01dav/798618dcce3e22d0623008d1717823c2

**Comment by HenryLoenwind** [comment]
See here: https://github.com/Glitchfiend/BiomesOPlenty/issues/924
