### ISSUE TITLE
Farming Station Failing To Harvest Specific (Vaild) Spots

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [SleepyTrousers/EnderIO#3941]
#### Issue Description:
The Farming Station skips valid planting spots

#### What happens:
I'm using the farming station to fertilize and reap Botania petals (I'm using other mods to actually get the petals planted, it would be REALLY nice if the farming station could be modified to allow it to plant them as well, but that's a separate issue) in a 9x9 square with the farming station in the middle.  Without any capacitor (and why exactly does the basic capacitor NEVER upgrade any machine?!?  It is a new part that must be crafted and added and that wasn't' there before, so why is that tier of upgrade completely skipped everywhere?) the farming station fully fertilizes (and  you have any plans to add the ability to add any other other mod's right-click fertilizers to the farming station?) and harvests all the petals in the 7x7 square around it.  Adding the double-layered capacitor allows the farmer to fertilize and shear all the petals in the valid 9x9 patch of grass around it, EXCEPT for four squares starting from the spot adjacent directly diagonal to the southwest and the three in a row from that square to the west.  That is, it's failing not only to reap the petal on the edge four spaces to the west and one south that was beyond the un-upgraded farming stations range, but also the three spots east of that back towards the farming station that it had previously been able to harvest.

#### What you expected to happen:
The farming station to completely fertilize and shear harvest all the buried petals in the 9x9 area around it.  I couldn't help but noticing that, unlike many other auto-farmers in Minecraft, the farming station appears to use a very haphazard and slap-dash approach to fertilizing and harvesting crops.  Rather than going through it's accessible space by rows or columns, it jumps around willy-nilly with no apparent pattern.  Not only do I suspect that this is how it's able to miss those spots when upgraded with the double-layer capacitor, but it also makes the farming station much less efficient and effective.  I had originally planned on having one farming station per petal color (16 in total, or better yet 4, had the farming station was able to plant the petals itself), but it's haphazard methodology prevents it from being able to actually farm the entire 9x9 grid.  When the entire farming space is full of buried petals, the farming station is only capable of fertilizing and harvesting a random five of them at at time.  That is, it starts randomly fertilizing about five then realizes it has waiting flowers it can harvest, stops fertilizing and harvests them, then repeats (sometimes it only does four, sometimes six, but that's the basic story), managing to never harvest 90% of the squares in the 9x9 ever at all.

I believe that if you were to clean up the mess in the farming station's fertilization and harvesting code so that it scans through the entire area it can effect, first to fertilize what it can, then to harvest, this would not only fix this problem, but make the farming station more efficient at its job.

#### Steps to reproduce:

1. Install Botantia and Ender IO
2. Make a 9x9 area of grass with stone/whatever, beyond.
3. Manually plant petals in the grass.
4. Place the farming station in the middle, provide with power, bonemeal, and shears.
5. Wait.  (It would be nice if the upgrades also made the farming station work faster...)

6. If you wish to automate the process as I have, install Actually Additions and use its phantom auto-placer three blocks above each square of the 9x9 of grass facing downward to plant the petals in the ground.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO - 1.10.2-3.0.1.145_beta
- EnderCore: EnderCore-1.10.2-0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 
There's not game crash or anything, so what log do you want?

**Comment by MatthiasMann** [comment]
Regarding the basic capacitor: that one is already part of the machine chassis.

**Comment by 7OOTnegaTerces** [comment]
@MatthiasMann Oh yeah, didn't think about that...  In that case, though, I think that it SHOULDN'T be a part of the machine chassis.  Instead, that spot should be left blank and the machine should require at least a basic capacitor in the capacitor slot in order to work at all.  That would make the whole capacitor issue much more transparent, and would save you one basic capacitor when you decided to upgrade.

**Comment by HenryLoenwind** [comment]
The capacitor is a side-effect of allowing capacitors to carry extended NBT data. So the old code to simply block all tier 1 capacitors had to go because they could have some NBT. Putting a new check in was forgotten.

**Comment by 7OOTnegaTerces** [comment]
@HenryLoenwind: Was this issue ever fixed?@?!?

**Comment by HenryLoenwind** [comment]
Never got around to reproducing it and I don't actually have an idea what could cause this. It's a bit weird that it wouldn't harvest only one kind of crop in some spots.
