### ISSUE TITLE
Power Conduit Prioritys

### ISSUE THREAD

**Issue by dovahkiin4991** [SleepyTrousers/EnderIO#3942]
In several mods you need power to create more power such as actually additions, but with a power network these generators may not be getting the needed power. If there could be a way to setup a priority system on these conduits it would help with several new mods. Ex. Oil Generator needs oil you get from canola press that requires power.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by MatthiasMann** [comment]
@dovahkiin4991 you can implement a priority system using capacitor banks, energy buffers, comparators or the power monitor of EnderIO. An alternative approach would be to use a separate generator to supply your energy generation.
