### ISSUE TITLE
Power usage rendering

### ISSUE THREAD

**Issue by Elvarion** [SleepyTrousers/EnderIO#3947]
#### Issue Description:
Placing a Dimensional Transceiver next to a Capacity Bank and adding a Receive channel to it will display inaccurate numbers. And the Buffer is also behaving strange. It never gets filled, its getting stuck at around 40k rf/t even when nothing is using the network except its own 10 rf/t

#### What you expected to happen:
Display accurate numbers

#### Steps to reproduce:

1. Place atleast two connected Capacity Banks with some energy in them (Needs to be able to power the Transceiver atleast) And make it so they display the in/out interface on the block.
2. Place Transceiver next to it
3. Make a channel and set it to receive. Even if the channel has no power the Cap bank will show some strange numbers. Should really just show a loss of 10 rf/t

This is a picture of placing just cap banks and adding completely random channels that are not in use anywhere except in the receiving parto f the transceiver.
https://gyazo.com/0667cf068f11702da74d9fd5a11c0b07
The numbers may also change after perhaps minutes or something. Saw it change perhaps 2-3 times during the writing of this post.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO-1.10.2-3.0.1.141_beta
- EnderCore-1.10.2-0.4.1.61-beta
- Forge1.10.2-12.18.3.2185
- Minecraft: 1.10.2

**Comment by HenryLoenwind** [comment]
Those numbers are accurate. The capBank will push energy into the transceiver and the transciever will push power back into the bank. You need to set either one to "in" or "out" if you don't want energy to in and out.

**Comment by Elvarion** [comment]
>Those numbers are accurate. The capBank will push energy into the transceiver and the transciever will push power back into the bank. You need to set either one to "in" or "out" if you don't want energy to in and out.

Ah, Yes that worked.
Reported it since it feels very strange when playing around with it :smile: 

Merry Christmas EnderIO team!

**Comment by HenryLoenwind** [comment]
Yes, it is a bit strange, but we had to remove the code that avoids that because people got confused when their CapBanks didn't output in some configurations...
