### ISSUE TITLE
Powered Spawner set to capture will auto break itself

### ISSUE THREAD

**Issue by Meller127** [SleepyTrousers/EnderIO#3948]
#### Issue Description:
Powered Spawner set to capture will auto break itself as soon it gets Power.

#### What you expected to happen:
Block remains placed

#### Steps to reproduce:

1. Place a powered spawner (empty) set to capture
2. Add power
3. The block will break itself
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.142
- EnderCore: 0.4.1.61
- Minecraft: 1.10.2
- Forge: 2185

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment]
We need the log file to see if there are any interactions with other mods.

**Comment by Meller127** [comment]
Server or client?

**Comment by HenryLoenwind** [comment]
Works as intended.

**Comment by Fokson** [comment]
I'd like to add to this, if I could.  The powered spawner breaks itself and retains both the power and the soul vial placed within it, making it impossible to ever place the spawner / retrieve the soul vial again.  If this works as intended, perhaps it should also fully reset the block and drop its inventory if any to avoid making dead weight and wasting the materials it was crafted with, should one forget that they hadn't yet attuned a soul to the device.

**Comment by HenryLoenwind** [comment]
Good point, however the real problem is that it wait for power before breaking. The breaking was added to drop spawners that got invalidated with an update, and I think the case of putting down a newly crafted spawner wasn't even in view then.
