### ISSUE TITLE
Black Frame when placing Conduits

### ISSUE THREAD

**Issue by davqvist** [SleepyTrousers/EnderIO#3949]
#### Issue Description:
I just updated to the new EnderIO version and now I get this weird black frame when placing conduits. Sometimes it doesn't happen, sometimes it stays for a long time until it goes away. In one existing test world one conduit had this frame even permanently. I had to break and replace the item conduit. See picture link below for how it looks when placing conduits.

#### What happens:
A black frame appears whenever you place anyone conduit, sometimes longer, sometimes shorter, sometimes none at all.

#### What you expected to happen:
That no black frame appears, just like before the update.

#### Steps to reproduce:

1. Grab any one conduit from the creative menu (I tested it with Energy and Item)
2. Place it down

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.147_beta
- EnderCore: 0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

Log won't help, but a picture:
http://imgur.com/a/RpMpX

**Comment by HenryLoenwind** [comment]
That frame is the model the conduit uses if it has no data to render on the client. We added it because people were complaining about conduits being invisible in that state.

If you want to complain that blocks are rendered before their data is synced from the server, try Mojang's bug tracker.

**Comment by davqvist** [comment]
Well I didn't know that, thanks for the quick answer.
