### ISSUE TITLE
Vibrant Capacitors losing "VIBRANT" thus making them worse

### ISSUE THREAD

**Issue by Hoffs-** [SleepyTrousers/EnderIO#3951]
#### What happens:
When crafting vibrant capacitor banks there is a chance to get normal capacitor. Basically you just get a vibrant capacitor but without the NBT Tag type tag "VIBRANT", insteasd it has "ACTIVATED". Another thing is that inventory renders that it has correct maximum value but when you place, it then shows ACTIVATED values.

#### What you expected to happen:
You're supposed to get it with type "VIBRANT" so it would read the correct rf value.

I was guessing that it could be related to minetweaker recipes, but it's not 100% that you get wrong type so I am not certain.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

Here is the log but I checked it and it doesn't show anything. Same with server side log.
http://pastebin.com/raw/j1a6E1bn

Also when doing /mt hand

> [13:01:36] [Client thread/INFO]: [CHAT] <EnderIO:blockCapBank:3>.withTag({hasFaces: 1 as byte, face5: 4 as short, hasDisplayTypes: 1 as byte, faceDisplay2: 1 as short, face0: 1 as short, type: "ACTIVATED", storedEnergyRF: 750000, face4: 4 as short, faceDisplay5: 2 as short})
> [13:03:02] [Client thread/INFO]: [CHAT] <EnderIO:blockCapBank:3>.withTag({hasFaces: 1 as byte, face5: 4 as short, hasDisplayTypes: 1 as byte, faceDisplay2: 1 as short, face0: 1 as short, type: "VIBRANT", storedEnergyRF: 500000000, face4: 1 as short, faceDisplay5: 2 as short})

Both are vibrant (blockCapBank:3), but one has VIBRANT tag, other has ACTIVATED.

**Comment by MatthiasMann** [comment]
Did you use a vanilla crafting table or a modded one? And did you take the crafted item out or shift clicked it out?

**Comment by Hoffs-** [comment]
QED and no shift clicking.

**Comment by MatthiasMann** [comment]
Then try to reproduce it with a vanilla crafting table.

**Comment by HenryLoenwind** [comment]
It's a while since I looked at 1.7.10 recipes, but if I'm not completely mistaken then a freshly crafted capBank should have no NBT values at all. Those come from breaking a capBank after it has been placed down in the world.
