### ISSUE TITLE
Yeta Wrench crashing client.

### ISSUE THREAD

**Issue by BleesTFE** [SleepyTrousers/EnderIO#3952]
#### Issue Description:
Yeta Wrench crashing client.
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Whenever i try put away the Yeta wrench after use it crashes my client. No matter where i put it, as long is i try to put it away, the client will crash.

#### What you expected to happen:
I expected to put it away because I was done using it.

#### Steps to reproduce:

1. Put Yeta wrench in main inventory bar
2. Use the yeta wrench
3. Shift item or try to drop/move the yeta wrench out of hand
4. Immediate crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.142_beta
- EnderCore: EnderCore-1.10.2-0.4.1.61-beta
- Minecraft: 1.1.10
- Forge: 1.10.2-forge1.10.2-12.18.3.2185

#### Your most recent log file where the issue was present: 

http://pastebin.com/umYMsGN1

**Comment by BleesTFE** [comment]
Wtf?

**Comment by HenryLoenwind** [comment]
you are 5 version behind...

**Comment by HenryLoenwind** [comment]
no, I use that "out of date" for stuff that was already fixed and where people just need to update
