### ISSUE TITLE
Fluid tank redstone control doesn't work

### ISSUE THREAD

**Issue by jeridan** [SleepyTrousers/EnderIO#3953]
#### Issue Description:
The redstone control of the fluid tank doesn't work as expected.

#### What happens:
The tank will pull/push fluids when sides are configured with no regard to the redstone control setting.  Even "never active" has no effect.

#### What you expected to happen:
Setting the redstone control to function with a lever off/on or turn off with never active setting

#### Steps to reproduce:

1.Place tank between source and destination.
2.Configure tank to pull from source and push to destination
3.Toggle redstone control to any setting has no effect.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.138_beta
- EnderCore: 1.10.2-0.4.1.60-beta
- Minecraft: 1.10.2
- Forge: 12.18.2.2171

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
That's how all Ender IO machines work. The Redstone mode controls their work, not the push/pull of their sides. For that there are item conduits that can be Redstone-controlled.

**Comment by jeridan** [comment]
What "work" is there for a fluid tank besides fill/hold/dispense a fluid?  Based on your explanation there is no need for redstone control on the fluid tank at all.

**Comment by VT-14** [comment]
Filling or emptying buckets and other fluid containers.

If you have lava in a tank, it can be used to void items.  Redstone control also turns that off.  Also, Liquid XP repairing on tools with the vanilla Mending enchantment.
