### ISSUE TITLE
Chickens Lava/Water Egg keeps filling Tanks beyond capacity

### ISSUE THREAD

**Issue by tgstyle** [SleepyTrousers/EnderIO#3954]
#### What happens:
Filling a tank with lava/water eggs keeps filling infinitely.

https://minecraft.curseforge.com/projects/chickens/files

#### What you expected to happen:

Lava/water Eggs to stop filling when the tank is full.

#### Steps to reproduce:

1. Build a fluid tank.
2. Place a lava or water egg in until it fills beyond capacity and keeps going.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.147
- EnderCore: 0.4.1.61
- Minecraft: 1.10.2
- Forge: 2185

![2016-12-27_20 55 45](https://cloud.githubusercontent.com/assets/5832709/21513587/b162accc-cc77-11e6-8762-bc655671a5f9.png)

**Comment by HenryLoenwind** [comment]
This is a bug in Chickens.

https://github.com/setycz/ChickensMod/blob/1.10.2/src/main/java/com/setycz/chickens/liquidEgg/LiquidEggFluidWrapper.java#L55

First, they do not respect the "doDrain" flag, destroying the egg also when it's only being asked what it contains. Second, they do not respect the maximum amount they are asked for, returning more then the target tank can take.

**Comment by tgstyle** [comment]
https://github.com/SleepyTrousers/EnderCore/commit/814629ff0fe62d0784b3d2ab20268ffce300c80a
