### ISSUE TITLE
World Crashes upon loading....java.lang.ClassCastException

### ISSUE THREAD

**Issue by AGWeeB** [SleepyTrousers/EnderIO#3957]
#### Issue Description:
Unable to load world as it crashes when loading..

java.lang.ClassCastException: crazypants.enderio.conduit.TileConduitBundle cannot be cast to com.rwtema.extrautils2.tile.XUTile

#### What happens:
Unable to load world as it crashes when loading..

#### What you expected to happen:
World should load an be playable :)

#### Steps to reproduce:

1. Load world
2. Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2.3.0.1.145_beta
- EnderCore: 1.10.2-0.4.1.61_beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

http://pastebin.com/WTCJKi7r

**Comment by MatthiasMann** [comment]
That looks like a world corruption.

**Comment by AGWeeB** [comment]
No didn't touch anything. Not sure what happened. It has actually happend twice. It happened once, then I restored a backup and redid some of the work I lost. Then it happened again. I guess something I did is causing it. No idea what tho.

**Comment by AGWeeB** [comment]
Does it look to be cause be some connection between a EnderIO block and a ExtraUtils2 block. I can restore my backup and try to redo the things I did where there would have been a connection between blocks from those mods and see if I can recreate.

**Comment by AGWeeB** [comment]
This appears to have been cause by a FTBUTils bug. The FTB Utils bug caused an exception in server tick error which corrupted the world. Anytime you tried to load the world after that first FTB Utils error you would get the error from my comment above and it would crash. Updating FTB Utils corrected the issue.

Thanks for the help.!
