### ISSUE TITLE
Unable to spawn chickens from Chickens Mod

### ISSUE THREAD

**Issue by TheAwayEnd** [SleepyTrousers/EnderIO#3959]
#### Issue Description:
Unable to spawn chickens from Chickens and More Chickens Mods even after amending the config file.

"# Entities listed here cannot be spawned and must be cloned from a captured entity instead (Attention: Possibility of item duping!)"

#### What happens:
Created a powered spawner to 'Capture' selected chicken but unable to release it from Soul Vial.

#### What you expected to happen:
After config change, ability to be able to spawn specific chicken from Soul Vial

#### Steps to reproduce:

1. Capture chicken from Chickens Mod in a Soul Vial and create a Powered Spawner with it
2. Set spawner to capture and wait for it to create the vial
3. Try to place the chicken in the world
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 149_beta
- EnderCore: 1.62
- Minecraft: 1.10.2
- Forge: 2185

#### Your most recent log file where the issue was present: 

https://gist.github.com/TheAwayEnd/937bef661a1b48084e50b948a586fe0c

**Comment by HenryLoenwind** [comment]
Try with build 151, when it's out.
