### ISSUE TITLE
Crash on load: Unknown config value 'staff settings:travelStaffEnabled'

### ISSUE THREAD

**Issue by Thyriel** [SleepyTrousers/EnderIO#3961]
#### Issue Description:
Ender IO crashes in forge loader (no other mods installed, fresh 1.10.2 MC forge installation):
"Unknown config value 'staff settings:travelStaffEnabled'" in "recipe_items_core.xml"

Happens in Versions:
1.10.2-3.1.152 and 1.10.2-3.1.154

### Workaround:
1. install EnderIO - 1.10.2-3.0.1.147_beta (i did not try the versions between 147beta and 152)
2. delete folder config/enderio
3. start minecraft (so the enderio config files are generated)
4. replace 147beta with 154 enderIO version & keep the config files.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.154 and 3.1.152
- EnderCore: 0.4.1.62-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 
http://pastebin.com/2E0zeqFR

**Comment by HenryLoenwind** [comment]
could you have a look at the timestamp of your core recipe files? they should be replaced every tim ethe game start...

**Comment by HenryLoenwind** [comment]
ok, forget it, I found the problem
