### ISSUE TITLE
Redstone conduits don't update properly when bulk-changed by non-conduit source

### ISSUE THREAD

**Issue by SharkWipf** [SleepyTrousers/EnderIO#3962]
#### Issue Description:
(Made a separate issue for 1.10.2 after the 1.7 issue #3311 got closed)
Redstone conduits don't properly update their outputs when more than 2 colors in 1 cable change at once. Only the first 2 colors get changed.

#### What happens:
Flip lever, only 2 lamps turn off or on.  
![What happens](http://i.imgur.com/mwrbaYu.png)

#### What you expected to happen:
Flip lever, all lamps should turn on or off (illustrated here by breaking the conduit, which does work).
![What should](http://i.imgur.com/l1lz2z1.png)

#### Steps to reproduce:

1. Set up line of lamps
2. Connect multi-color cables to lamps
3. Connect multi-color cables to line of redstone
4. Add redstone power source at end of line (see screenshots)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.149_beta
- EnderCore: EnderCore-1.10.2-0.4.1.62-beta
- Minecraft: 1.10.2 (your issue template still suggests 1.7.4 btw)
- Forge: forge-1.10.2-12.18.3.2185-universal

#### Your most recent log file where the issue was present: 
N/A, nothing is logged.

Haven't tested in the latest version yet, as I just updated everything last Friday, but the issue's been in for all of 1.10.2 so far so I assume it hasn't been fixed in today's release.

**Comment by HenryLoenwind** [comment]
Ok, I had a look into it and I don't think we can do anything here. What happens here is that there is a ping-pong between redstone network and conduit network. What both do when they are notified of a change is to shut themselves off and ask their neighbors for their signal. This happens about twice per connection between the two networks before it settles down. However, there is no way to actually make sure it settles in the correct state without creating an endless loop.

To circumvent this, you need to make sure there is no loop between 2 networks, e.g. like this:

![image](https://cloud.githubusercontent.com/assets/1485873/21579793/f409fa00-cfc2-11e6-8afe-73da48819e78.png)

Note that all redstone conduits that are connected to each other form one network, not one network per channel. It isn't actually a problem of a signal loop here, but it's an update loop. A signal loop gives even more weird results... ;)

**Comment by SharkWipf** [comment]
Ah! I see!  
Can confirm it does work fine like so: 
![Dark](http://i.imgur.com/EcoVDee.png)
![Light](http://i.imgur.com/oi3wKhL.png)

Thanks for looking into this and for providing a workaround. 
It indeed sounds like it'd be tricky to fix yeah, but at least we now know a workaround. 

Thanks again and happy new year!

**Comment by HenryLoenwind** [comment]
Yes, we do. And I thought up a way to fix this: Get rid of "in and out" mode for redstone conduits and have them either be "in" **or** "out". Would get rid of a good number of other problems, too. But that's a major change, so it won't come soon.

I'll close this ticket with "wontfix" and put an item onto my TODO list instead.
