### ISSUE TITLE
Crash on load: Unknown config value 'item enabling:gasConduitEnabled'

### ISSUE THREAD

**Issue by gkuba** [SleepyTrousers/EnderIO#3963]
#### Issue Description:
Crash on load with error loading config for gas conduit. 

#### What happens:
== Error Message ==
Unknown config value 'item enabling:gasConduitEnabled'
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.155
- EnderCore: 1.10.2-0.4.1.62
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 
http://pastebin.com/HJFGy7qv

**Comment by CelticChristoph** [comment]
Also having this issue. Crashes with nothing but EnderIO and EnderCore enabled.

I would post the crash report, but it would be redundant as it's exactly the same.

Possibly related to #3961 ?

**Comment by HenryLoenwind** [comment]
Why tf does it work here flawlessly... :-(

**Comment by HenryLoenwind** [comment]
New build is on its way.

Does using old config files really help? That's interesting, as (a) the bad line isn't new but has been there forever and must be removed and (b) the file it is in isn't read from the config directory but from the jar file...

**Comment by Thyriel** [comment]
With .155 i too had that gas conduit crash.
In the new .156 build everythings working again, thanks for the quick fix and a happy new year ;)

**Comment by HenryLoenwind** [comment]
Happy new year, to you, too!
