### ISSUE TITLE
Dark Steel Elytra: falling through world when flying straight up

### ISSUE THREAD

**Issue by SharkWipf** [SleepyTrousers/EnderIO#3964]
#### Issue Description:
I suspect this is related to/the same as closed issues #3784 and #3637, however I'm not crashing nor having problems with water, so submitting as a new issue.

#### What happens:
When flying with the dark steel armor with Elytra upgrade, looking straight up causes collision damage (if going fast enough) and locks the player into place horizontally, while falling through solid blocks and eventually the void vertically. This can, as far as I've seen, only be escaped by using a teleportation item like the Staff of Traveling or a charged porter.
An interesting side effect is that vector-based Psi spells always throw an out of range error during this, even when not visually out of range.
This also does not happen with the vanilla Elytra.

#### What you expected to happen:
Not falling through the world.

#### Steps to reproduce:
1. Get dark steel armor with elytra upgrade
(Mine is enchanted, haven't tested without yet)
![Dark Plate](http://i.imgur.com/gqjqxKl.png)
2. Fly
3. Look up

____
#### Affected Versions (Do *not* use "latest"):

EnderIO: EnderIO-1.10.2-3.0.1.149_beta
EnderCore: EnderCore-1.10.2-0.4.1.62-beta
Minecraft: 1.10.2 (your issue template still suggests 1.7.4 btw)
Forge: forge-1.10.2-12.18.3.2185-universal
Modpack: [Blockheadism](https://minecraft.curseforge.com/projects/blockheadism)

#### Your most recent log file where the issue was present: 
N/A

**Comment by HenryLoenwind** [comment]
Weird, we do nothing with the flight, we just tell vanilla that the player has an Elytra equipped...

**Comment by SharkWipf** [comment]
Hmm, weird. 
We do have several mods that mess with the Vanilla mechanics, like BetterFPS, FoamFix, Quark, and probably a bunch more (see "relations -> dependencies" on my modpack link). I haven't tested it on "pure" Ender IO yet, nor have I tested it in single player. 
With some luck I'll be able to test those tomorrow.

**Comment by HenryLoenwind** [comment]
That would be nice, as I tested flying straight up when I originally implemented it. If it doesn't happen with just Ender IO, could you try finding which other mod triggers the interaction? Thank you!

**Comment by SharkWipf** [comment]
Okay, figured it out. 
The culprit is [BetterFps](https://mods.curse.com/mc-mods/Minecraft/229876-betterfps) on default settings ("Riven's Half algorithm"). 
Haven't tried all other algorithms yet as each change requires a client restart, but at the very least the default causes this behavior. The next one in the list, "Java Math", seems to work fine. 

I see BetterFps has a similar bug open for the vanilla Elytra (Guichaguri/BetterFps#13), although I can't reproduce this with the vanilla Elytra and BetterFps, so I assume they made an exception for it somewhere. 
I assume this has to be fixed on the BetterFps side, if at all?

**Comment by SharkWipf** [comment]
BetterFps has implemented a fix for this issue already (see referenced issue report), so I'm closing it here too :)
