### ISSUE TITLE
Tinkers construct dusts/powder localization

### ISSUE THREAD

**Issue by IBeCrayZ** [SleepyTrousers/EnderIO#3965]
Latest TC, latest EnderIO

Cobalt and Ardite powder for me at least are not properly localized.

E.g. enderio.powderArdite.name
       enderio.powderCobalt.name

I assume this is an issue with EnderIO localization.

Thanks.

**Comment by HenryLoenwind** [comment]
Oops, I completely forgot to give those items names...

Fixed in next build (157).
