### ISSUE TITLE
Crash on 1.10.2 with no other mods

### ISSUE THREAD

**Issue by Razorfin8** [SleepyTrousers/EnderIO#3966]
#### Issue Description:
Crash on start up with no mods loaded. Crash log points to issue with missing reciple xml file. 

#### What happens:
Crashes on startup

#### What you expected to happen:
uuhh.. not crash?

#### Steps to reproduce:

1. Install forge, Ender IO, EnderCore
2. Start minecraft
3. ???
4. Not profit
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.155
- EnderCore: 1.10.2-0.4.1.62-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2185

#### Your most recent log file where the issue was present: 

http://pastebin.com/xHdZ67jK

**Comment by HenryLoenwind** [comment]
update

**Comment by Razorfin8** [comment]
I realized that it has probably been fixed as soon as I posted that.  I am now updated and running smoothly.  Thanks!
