### ISSUE TITLE
Temperature requirements for Tcon Smeltry to make Glowgas/Molten Redstone exceed Lava's heat.

### ISSUE THREAD

**Issue by ate0ate** [SleepyTrousers/EnderIO#3967]
#### Issue Description:
When trying to make either glowgas or molten redstone using the Tcon smeltery, the required temperature to melt the glowstone/redstone blocks exceeds the max temp that lava can provide. There seems to be no way to actually melt the block items into their respective fluids. Pyrotheum used to allow the smeltery to reach higher temps, but It doesn't seem to have an equivalent option in Ender IO. The dust versions of glowstone and redstone seem to smelt into liquids very slowly, but the blocks/ore/everything else cannot.

#### What happens:
Glowstone block will not melt and progress indicator in smeltry GUI turns blue
stating that there is not enough heat to melt the item.

#### What you expected to happen:
Melt Glowstone BLOCK into Glowgas

#### Steps to reproduce:

1.Place Glowstone/Redstone BLOCK in smeltery GUI
2.Recieve "not enough heat to melt item" message
3.OR just check recipes in JEI and note temps required
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.156
- EnderCore: 0.4.1.62beta
- Minecraft: 1.10.2
- Forge:12.18.3.2185

#### Your most recent log file where the issue was present: 
N/A

**Comment by AnrDaemon** [comment]
> It doesn't seem to have an equivalent option in Ender IO

There should be? Pyrotheum and its derivatives is a TE lang.

**Comment by ate0ate** [comment]
Yeah, I know its from thermal expansion, but the recent EnderIO updates added glowgas and molten redstone to replace the equivalent TE fluids and even added TCon recipes for them as well. There's just no good way of smelting them without something that burns hotter than lava. The only reason I suggested a "pyrotheum" equivalent was because they already matched TE fluids with the new Glowgas, Molten Redstone, and Liquidfied Ender Pearls. It really helps with compatibility between TCon, Extreme Reactors, and EIO since there is no TE for now.

**Comment by MatthiasMann** [comment]
Does rocket fuel work as a power source for TCon?

**Comment by bookerthegeek** [comment]
By itself I would think not as lava is hit by itself where fuel requires combustion the gain temp.

**Comment by ate0ate** [comment]
I originally went into creative and tried every fluid added by EIO and none raise the temp of the furnace unfortunately. Rocket fuel was my first thought too.

**Comment by HenryLoenwind** [comment]
Works as designed.

The dust forms can be smelted, and those are easy to produce from the blocks. And as soon as you add a mod into the mix that adds a hotter fuel, it will have a use.

Ender IO doesn't add a Pyrotheum because we don't use it for anything.

**Comment by ate0ate** [comment]
Makes sense. Thanks for getting back about it. Do you happen to know of any mod that does add a fuel that burns hotter than lava by any chance?

**Comment by HenryLoenwind** [comment]
TE does, once it's released. It *is* being worked on...

**Comment by VT-14** [comment]
Are there any other than Thermal Expansion?

Thermal Expansion will either add its own and make the recipe redundant, or not have TiC compat to add the hotter fuel.  Either way, the Ender IO block recipe won't be used unless there is a third mod.

**Comment by ate0ate** [comment]
I have a suggestion, its a bit long winded though. Perhaps switch up the liquid sunshine recipe, maybe make it a bit more netherish, and give that liquid the traits/temp desired? I was thinking how fluids added by mods are rather boring except for what TE normally does and playing with glowgas/liquidfied ender pearls is rather fun, so why not spice up some of the other "boring" liquids added by enderio? A fluid with the name "Liquid Sunshine" just sounds like it would be ridiculously hot. And bright, "blinding" even. Perhaps make the rainy weather liquid grow crops better when used in a vanilla farm setup or something like that. Nutrient distillate could replesnish health and hunger, Hooch/Firewater/and Rocket Fuel just sound like they're begging for some serious nausea or more interesting effects.I don't know. Just a suggestion. Maybe someone more thoughtful could make the liquids more interesting than what I said.

**Comment by HenryLoenwind** [comment]
Let's have a look at the the current liquid properties:

* Fire Water: Sets any entity on fire
* Hootch: Nausea for living entities
* Rocket Fuel: Jump Boost for living entities and explodes when on fire
* Nutrient Distillation: Feeds players
* Liquid Sunshine: Levitation and glowing for living entities
* Concentrated Coudseed: Blindness for living entities
* Vapor of Levity: Lifts living entities
* Molten Metals: like lava
* Glowgas: Levitation and glowing for living entities
* Molten Redstone: Haste, Jump Boost, Speed and Hunger for living entities
* Liquidfied Ender Pearls: Random teleporting for any entity

**Comment by ate0ate** [comment]
I apologize, I should have tested more things. I didn't even notice the rocket fuel or nutrient distillation effects and I played with cloud seed rather than concentrated cloudseed and just saw it had no effects and that liquid sunshine was a copy of glowgas. The Vapor of Levity is quite fun to play with for sure, but I stand by my liquid sunshine statements.Hot makes sense. This is in no way an attack or complaint man. You seem to get a little defensive pretty quickly when interacting with the community. I love this mod and only want to see it be the best it can be. You code it, I respect that fully, and respectfully support your decisions. Thank you.

**Comment by cha0s** [comment]
>Ender IO doesn't add a Pyrotheum because we don't use it for anything.

The use would be to get the smeltery hot enough :P
