### ISSUE TITLE
Crash upon player login on long running and usually empty server

### ISSUE THREAD

**Issue by enricotagliavini** [SleepyTrousers/EnderIO#3970]
#### Issue Description:
No modpacks, just a selection of mods I did. This is a family Minecraft server, 3-4 players. Server is always running, but most of the time nobody is logged in. When the server is running for a while (typically a day or so, hard to tell how long is exactly needed to trigger the issue), if a player logs in the server gets stuck. CPU usage of java process is 100% of one core, on the client world will only load partially and no interaction is possible, after 60 seconds the watchdog will kill the server. From the crash report it seems Ender IO stuff is causing the issue. The backtrace always points to AbtractCondiutNetwork calls. Attached is the full crash report. Now I honestly don't understand enough to be sure Ender IO is causing the issue. If this is not the case I apologize for the bother but I appreciate any hint that can be shared.

#### What happens:
Upon player login after some period of no use the server is stuck, watchdog kills it

#### What you expected to happen:
Server should not get stuck, gameplay should resume correctly.

#### Steps to reproduce:

1. Start the server and login to verify everything works as expected
2. Not sure if this is needed but the area where I login / logout has EnderIO stuff, SAG mill, two Alloy smelters, a stirling generator a capacitor bank and a power monitor. I use energy conduits to bring the power from the capacitor bank to the machines and a power monitor to turn on the generator when power goes below 90% (hence I also have redstone conduit). No other conduits are present
3. Logout and wait some time with no user logged in, typically a day. Not sure if can be reproduced with a shorter time. The first few logins will work as expected and that's the weirdest part
4. Log back in and notice the server gets stuck, after one minute you are kicked out by the watchdog shutting down the server.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.149_beta
- EnderCore: 1.10.2-0.4.1.62-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2185

#### Your most recent log file where the issue was present: 

[crash-2017-01-02_12.56.01-server.txt](https://github.com/SleepyTrousers/EnderIO/files/680737/crash-2017-01-02_12.56.01-server.txt)

**Comment by HenryLoenwind** [comment]
see #3756, #3504

but good crash log with the new diagnostics output. This allowed me to actual do something that may help here.

**Comment by enricotagliavini** [comment]
Oh sorry I didn't saw the issue was reported already. I assumed it was kind of recent, but I didn't accounted the fact I built Ender IO devices in the world only recently (it's a new server).

If I can help with more info let me know.

Thank you
