### ISSUE TITLE
Crafter Issues

### ISSUE THREAD

**Issue by xannor** [SleepyTrousers/EnderIO#3971]
#### Issue Description:
The crafter seems to have issues when the bufffering item stack mode is set to single.

#### What happens:
If there are multiple items in the crafter inventory and the mode is change, all items, beyond a single one in a slot, get ejected. Most seem to get ejected into the world but some I could find. In addition, anything beyond a single item in the output slot also gets ejected, which will have the craft start crafting a new batch, which in turn get ejected.

#### What you expected to happen:
Either the mode change only alters the insertion of items, not allowing them to exceed a single one, but allowing any excess to remain, and craft up to a full stack in the output buffer. This is how it seemed to work previously.
or.
 Keep the current ejection feature for the input slots, but not the output slot, and only allow one crafting operation to occur when the output slot is empty.

#### Steps to reproduce:

1. Place a crafter in the world.
2. Set a patteren, i.e. basic capacitor.
3. Pipe in materials
4. change mode from buffered to single
5. watch the popcorn come out of the crafter.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.156
- EnderCore: 0.4.1.62-beta
- Minecraft: 1.10.2
- Forge: 2185

#### Your most recent log file where the issue was present: 

No logs

**Comment by xerrio** [comment]
Can confirm. I have the same issue.
