### ISSUE TITLE
Making a mod that uses RF + compatibility

### ISSUE THREAD

**Issue by Anime-Quatroctus** [SleepyTrousers/EnderIO#3972]
#### Issue Description:
Using the energy capability system provided in forge for Minecraft version 1.10.2 and forge version 1.10.2-12.18.3.2202. It seems that I can only insert energy and can't extract from any of them. I expected to be able to extract from generators and capacitors. Note this also is the case with the RF API. I can provide the code I am using to attempt this if necessary.
To reproduce
1. Setup the forge workspace for a new mod or use an existing one.
2. Create a block that accesses the Energy capability from an adjacent TE either a generator or capacitor.
3. After accessing it try to extract from it.
______________________________________________________________________________________________________________

- EnderIO: 1.10.2-3.1.156
- EnderCore: 1.10.2-0.4.1.62-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2202

**Comment by MatthiasMann** [comment]
It is push based - the generators and cap banks will push energy to your block.

**Comment by Anime-Quatroctus** [comment]
What if my block is just supposed to interface with it to move the energy and not store it? I assume it is not possible.

**Comment by MatthiasMann** [comment]
The pull-based part in the RF API was always a cause for many bugs - it is good that this is now gone.

**Comment by Anime-Quatroctus** [comment]
Alright I will have to work around that then.

**Comment by tterrag1098** [comment]
Sure that's possible. when you receive energy, just immediately push it out to neighbors. not that complicated.
