### ISSUE TITLE
NPE Server Halt with Tesla API in Ender IO

### ISSUE THREAD

**Issue by Vaygrim** [SleepyTrousers/EnderIO#3973]
#### Issue Description:
We quite regularly have been getting server 'halts' (i.e. not actual CRASHES that generate a crash report. The server just generates some errors in the server logs, then stops.) These halts have not been generating crash reports, and I keep losing the information that it spams to the server console. Well I finally caught one. (Happens roughly 4 to 6 times per day, always with someone on the server at the time.)

#### What happens:
Server halts. Just ... 'stops', no crash.

#### What you expected to happen:
For it to NOT halt..?

#### Steps to reproduce:
1. Happens on its own once people have progressed on the server to using EIO Machines & Conduits.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.144_beta
- EnderCore: 1.10.2-0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2185

#### Your most recent log file where the issue was present: 
This is an excerpt from the server logs. Grabbed everything that looks relevant. Again, no associated crash report found with this server halt.
https://gist.github.com/Vaygrim/264ad86a0e87e2900c81f464266e1f49

**Comment by HenryLoenwind** [comment]
What you are seeing here is the side effect of a Minecraft crash report being generated and the logging being set to debug. Ender Io does diagnostics on the installed energy APIs, and if one of them is can not be loaded (e.g. because it is not installed), it writes the stack trace out as debug messages.

**Comment by tacogerbil** [comment]
@Vaygrim Same halt her every time at startup... Call it luck but I placed a ``` in front of Enderio's name making it load first and I can boot my server up now without this halt...
