### ISSUE TITLE
Dimensional Transceivers GUI: Channel list selection off while Minecraft at half screen

### ISSUE THREAD

**Issue by matthewmcgarvey** [SleepyTrousers/EnderIO#3974]
#### Issue Description:
While playing with game taking up half the screen, the ability to chose an option from the channel list in the dimensional transceivers GUI is doesn't square up with the visual listings of the channels.  Nothing happens when you click on the channels, you have to click off to the right side of the channel name a lot until you can find where the clickable area is or type the channel in the add channel box for it to bring you down to where you have it.

#### What happens:
Not able to click directly on the channel in the dimensional transceiver GUI, it's off to the right.

#### What you expected to happen:
Same as in fullscreen, able to click directly on the desired channel.

#### Steps to reproduce:

1. Resize Minecraft to the half screen size (left/right side of the screen)
2. Open dimensional transceiver GUI to energy/item/fluid tabs (where the channels are listed)
3. Attempt to pick a channel that is already added.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.138_beta
- EnderCore: 0.4.1.60-beta
- Minecraft: 1.10.2
- Forge:

#### Your most recent log file where the issue was present: 

Not necessary

**Comment by MatthiasMann** [comment]
You did not specify the forge version. Does it still happen with the latest version of EnderIO/Core on current forge?

**Comment by tnraptor14** [comment]
Forge is 12.18.3.2202

Yes, the problem persists in the latest releases
EnderIO: 3.1.156
EnderCore: 0.4.1.62-beta

I forgot to add: using the small GUI setting I was not able to find the bounding box at all.
