### ISSUE TITLE
[1.10.2 +] FEATURE REQUEST: Conduit facade compatibility with Chisels And Bits creations

### ISSUE THREAD

**Issue by garath77** [SleepyTrousers/EnderIO#3975]
I know you guys are kept busy by all the updates and other feature 'to do' lists, but I'd love to see compatibility with Chisels and Bits mod for the Conduit Facade. I'm making a 'realistic' floor by cutting out 'rafters/joists' out of oak planks, but I have conduits running thru part of that area. Being able to cover the floor from above, but still see the joists and conduits from below would be awesome.

Granted, I'm not much of a programmer, so I have no idea how much work it would be, or even if it's possible.

Keep up the good work! 

Thanks

**Comment by HenryLoenwind** [comment]
No, not possible. C&Bs are not simple blocks, they are TileEntities of their own.

**Comment by garath77** [comment]
That's too bad, thanks anyway.

 
 
  On Fri, Jan 6, 2017 at 6:35 PM, Henry Loenwind<notifications@github.com> wrote:   
No, not possible. C&Bs are not simple blocks, they are TileEntities of their own.
