### ISSUE TITLE
Redstone conduit 'network' is not lighting together

### ISSUE THREAD

**Issue by Ricket** [SleepyTrousers/EnderIO#3976]
#### Issue Description:
Connected redstone conduits don't all blink together. See gif: http://imgur.com/sFgysV0

#### What happens:

Interconnected conduits are blinking at different times.

#### What you expected to happen:

All the conduits should light up and unlight simultaneously.

#### Steps to reproduce:

1. Make a network of redstone conduit. Set up a system to turn it on and off at specific timings.
2. After some time come back to it, and it will be lighting up strangely.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO-1.10.2-3.1.156.jar
- EnderCore-1.10.2-0.4.1.62-beta.jar
- Minecraft: 1.10.2
- Forge: 2185
- Modpack: Direwolf20-1.10 version 1.3.2

#### Your most recent log file where the issue was present: 

N/A

**Comment by HenryLoenwind** [comment]
We have no influence over when the game re#renders our conduits. We can only tell it that they need to be re-rendered because the state changed.
