### ISSUE TITLE
Painting Machine Inputs allow painting facades

### ISSUE THREAD

**Issue by tomjn** [SleepyTrousers/EnderIO#3980]
#### Issue Description:

It's possible to put cobble into the facade slot of the painting machine, and then paint it with a facade, giving a block that renders incorrectly

#### What happens:

<img width="1280" alt="screen shot 2017-01-08 at 04 12 18" src="https://cloud.githubusercontent.com/assets/58855/21747266/1f6f3e80-d559-11e6-9dd2-cac27be6e0d0.png">

<img width="1280" alt="screen shot 2017-01-08 at 04 12 15" src="https://cloud.githubusercontent.com/assets/58855/21747267/27550dbe-d559-11e6-8182-be7ec840c372.png">

#### What you expected to happen:

I expect it to go into the other slot and paint the conduit facade, not be painted by it

#### Steps to reproduce:

1. Place cobble and conduit facades into a painting machine, but swap the slots around so that the facade is being painted on to the cobble
2. Place the result in the world

...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.145_beta
- EnderCore: 1.10.2-0.4.1.61-beta
- Minecraft: 1.7.10
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

_Not available at time of writing_

**Comment by HenryLoenwind** [comment]
Facades are no longer valid paint sources (code complete)

Your suggestion to remove the ability to paint cobblestone was moved to the suggestion tracker.
