### ISSUE TITLE
Updating from EnderIO-1.10.2-3.0.1.147_beta.jar to EnderIO-1.10.2-3.1.157.jar throws "Missing Blocks/Items" on server start

### ISSUE THREAD

**Issue by cha0s** [SleepyTrousers/EnderIO#3981]
#### What happens:

I updated my Ender IO version from EnderIO-1.10.2-3.0.1.147_beta.jar to EnderIO-1.10.2-3.1.157.jar and got:

```

[00:08:46] [Server thread/ERROR] [FML]: Unidentified block: enderio:blockEnderIo, id 1306
[00:08:46] [Server thread/ERROR] [FML]: Unidentified item: enderio:blockEnderIo, id 5718
[00:08:46] [Server thread/WARN] [FML]: Forge Mod Loader detected missing blocks/items.

There are 2 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
enderio:blockEnderIo
enderio:blockEnderIo

```

#### What you expected to happen:

Not that ;)

____

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.157
- EnderCore: 1.10.2-0.4.1.62-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2185-universal (?)

____

Also, sorry if I'm giving the wrong/not enough information. This is my first time reporting a forge mod bug. Let me know if you need more.

**Comment by MatthiasMann** [comment]
The EnderIO block has been removed as it is no longer possible to implement after changes in Minecraft/Forge.

**Comment by cha0s** [comment]
Understood. Out of curiosity, is there a (public) discussion anywhere about this? Not because I want to protest the decision, but I'm just interested in the "under the hood" stuff. :)

**Comment by HenryLoenwind** [comment]
Not much to discuss, the functionality we needed was removed from Forge and has not come back for half a year. I now removed the block that has been disabled so we don't need to maintain code that won't ever run...
