### ISSUE TITLE
Cap redstone mode fails when cap sides configured

### ISSUE THREAD

**Issue by kennymoto** [SleepyTrousers/EnderIO#3982]
#### Issue Description:
Power monitor cannot control cap bank once the cap bank sides have been configured as input output.

#### What happens:
Power monitor will control cap input if all cap sides are set to none, if set a side to input and one to output it no longer shuts off the input.

#### What you expected to happen:
I expect the input to be controlled no matter if configured or not
____
#### Affected Versions (Do *not* use "latest"):
1.10.2-3.1.156.jar in direwolf20 pack

**Comment by MatthiasMann** [comment]
Did you connect the power monitor via energy conduit to the cap bank (and not directly)?
The power monitor is monitoring a conduit network and all attached cap banks.

**Comment by kennymoto** [comment]
Yes I sure did - like i said it works fine if I remove the configuration of the sides

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by HenryLoenwind** [comment]
I'll look into it.

Get an email client that doesn't add advertisements to your mails.

**Comment by kennymoto** [comment]
Thanks for fixing this. I fixed my email signature. Have a good day!

Kenny

________________________________
