### ISSUE TITLE
[1.10.2-3.1.157]Farming station consumes durability of unbreakable axe

### ISSUE THREAD

**Issue by mainframecn** [SleepyTrousers/EnderIO#3983]
The Farming station consumes durability of unbreakable axe (Tinkers Construct).
I think the durability of an unbreakable axe shouldn't be consumed. The unbreakable attribute is gained by using reinforcement modifiers (5x) (Tinkers Construct).

- EnderIO: 1.10.2-3.1.157
- EnderCore: 1.10.2-0.4.1.62-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2202

**Comment by mindforger** [comment]
you sure it's 5 times? does it actally say "UNBREAKABLE" in the lore?
AFAIK you need reinforced 10 to get UNBREAKABLE

**Comment by HenryLoenwind** [comment]
The farming station only tells the item that it should take damage. It is the item's job to either decrease its durability, energy storage, mana or do nothing.

**Comment by mainframecn** [comment]
Fair enough, strangely other machines (non-enderio) don't seem to have this problem.

**Comment by HenryLoenwind** [comment]
To be sure I just looked it up:

```
if (type == ToolType.AXE) {
      tool.getItem().onBlockDestroyed(tool, worldObj, bs, bc, farmerJoe);
    }
```

So for axes, we don't even tell the item to take damage like we do foe hoes and shears (```tool.damageItem(1, farmerJoe);```) but only that is has been used to destroy a block. So it's all on the tool.

**Comment by mainframecn** [comment]
Thanks very much for taking the time to check.

**Comment by HenryLoenwind** [comment]
oops, "invalid" was the wrong label. You issue is valid, it's just not Ender IO's fault. (Unless boni can prove otherwise, I not that stubborn... ;) )

**Comment by mainframecn** [comment]
with you information i dug a bit deeper in the tool. You're quite right, it is an issue with the tool. If you use materials that are able to consume durability, ie. in exchange for a special ability, it will consume durability. 
Again thank you very much for the assistance.
