### ISSUE TITLE
Quark chests are being treated as connected when they are not

### ISSUE THREAD

**Issue by Ricket** [SleepyTrousers/EnderIO#3990]
..At least, that's my best guess as to what's going on here. I reproduced the issue with a fairly small setup but I haven't done a ton of fiddling with it otherwise.

Test setup:

![image](https://cloud.githubusercontent.com/assets/196978/21952031/9a643016-d9df-11e6-8a0f-825d8785c95e.png)

The left chests are set to extract, always, purple and cyan channels respectively. The right chests are set to insert with purple, pink, cyan.

The left left chest is a Spruce Chest, right one is Dark Oak Chest. Both added by Quark. (the three right chests are obviously plain oak chests but this works for any inventory)

I deposit a stack of cyan and purple wool into the respective left chests (matching the channel color). Now let's look at the contents of the right chests:

Purple chest:

![image](https://cloud.githubusercontent.com/assets/196978/21952039/e1c0c9c4-d9df-11e6-9388-06402d892cd6.png)

Cyan chest:

![image](https://cloud.githubusercontent.com/assets/196978/21952040/e9593b3a-d9df-11e6-8eeb-a61063f62e3b.png)

Pink chest is empty as expected.

My thought is EnderIO does not detect the different wood chests as separate, and instead is treating them as one connected chest.

EnderIO-1.10.2-3.1.156.jar
Quark-r1.1-70.jar
Pack is Direwolf20-1.10 v1.3.2.

**Comment by HenryLoenwind** [comment]
If they pretend to be vanilla chests, that's probably true. Vanilla chests always connect, so there's no way to ask them if they are connected or not. I need to check how to detect that for Q chests then.

**Comment by HenryLoenwind** [comment]
Oops, I still had 1.7.10 in my head. In 1.10.2, the "chest combining" is **not** done by our code anymore. Now the chests do that themselves.

Can you test what happens with a hopper? So

```
(Chest A)(Chest B)
         (Hopper)
         (Chest 3)
```

Put an item into chest A and see if the hopper pulls it out.

**Comment by VT-14** [comment]
With the following setup, the Acacia Chest is not above the hopper, but does lose its items to the hopper.  Looks like an issue in Quark.

![2017-01-14_07 54 14](https://cloud.githubusercontent.com/assets/12564251/21954972/cf2eda9a-da2e-11e6-8910-cc2c80e71869.png)


I even tested placing chests on all 4 horizontal sides of the chest on top of the hopper.  Only one double chest forms at a time (not visually).  Connections form East, then North, then West, and lastly South.

Minecraft 1.10.2
Forge 12.18.3.2209
Quark r1.1-70

**Comment by HenryLoenwind** [comment]
Yes, that's what I expected. Q extends vanilla chests but doesn't override their Forge-supplied inventory merging code.

**Comment by Ricket** [comment]
Thanks for reproducing it, I've been without Internet today and it turns out Curse won't even launch without Internet, so I can't load my game. (posting this from phone). Nevertheless, I think I found the appropriate quark bug, see link above.
