### ISSUE TITLE
EnderIO Piston Glitch while wrenching

### ISSUE THREAD

**Issue by ThomasAunvik** [SleepyTrousers/EnderIO#3993]
#### Issue Description:
The piston rotates when i wrench it. Nothing else happens.
i dont know how to explain it really so please watch the videos.

And when you remove the redstone source after the wrenching. it does not do anything. but when i wrench it again without the redstone signal it returns to the normal phase.

Here is another one, if your piston base is fased down. The block that is fased to dissapears. 

#### What happens:

https://vimeo.com/199477886
https://vimeo.com/199477948

How to break bedrock or any block:
https://vimeo.com/199478691

#### What you expected to happen:

I dont know.

#### Steps to reproduce:

1.Place down piston (any kind)
2.Place a redstone block at the corner of piston. meaning 1 block to the side, then 1 block up.
3.Wrench the extended piston.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.161
- EnderCore: 0.4.1.64-beta
- Minecraft: 1.10.2
- Forge:12.18.3.2209

#### Your most recent log file where the issue was present: 

http://pastebin.com/FgZtB0cf

**Comment by HenryLoenwind** [comment]
Please report this to Forge, we are just asking the block to rotate itself, the rotation code for vanilla blocks is added by Forge.
