### ISSUE TITLE
cant get

### ISSUE THREAD

**Issue by XX67Pranx** [SleepyTrousers/EnderIO#3999]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
ur websit link to curse is expired plz update so I can use thx

#### What you expected to happen:
to be brought to the download link

#### Steps to reproduce:

1.i click
2.it loads
3.it fails
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10
- EnderCore:
- Minecraft: 1.7.10
- Forge:1.7.10

#### Your most recent log file where the issue was present: 
enderio.com
[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
Our web admin @Nentify is unavailable right now. The site will be fixed in due time. Not a mod issue.

**Comment by Nentify** [comment]
I've updated the links to Ender IO and EnderZoo. I don't come on IRC much anymore and don't spend too much time with Minecraft anymore. I've also been away for most of January, so apologies for the delays!

I use Discord if you use that. :)
