### ISSUE TITLE
[Feature] Redstone panel

### ISSUE THREAD

**Issue by Frontrider** [SleepyTrousers/EnderIO#4002]
#### Issue Description:
The idea would be: be able to have a terminal where we can set up commands for the redstone conduits, with custom buttons. Maybe be able to set lenght and pulse amound as well, and to whitch channels to emit signal on. (emit signal on multiple channels at the same time)

#### What happens:
I could use this control to entirely replace ae type autocrafting. click the button in the terminal to start the process, and then either lenght/pulse amout is what I could read the amount from. (no need for any dynamic stuff, just set that property once)

Could also be used just to have a control panel for everything in any base.

Just an idea, if you think that its bad/ you don't want it then close it.

**Comment by HenryLoenwind** [comment]
Wrong tracker. http://ideas.theideawall.com/EnderIO/
