### ISSUE TITLE
[Suggestion] Enchanter, Dark Anvil and Liquid XP

### ISSUE THREAD

**Issue by p75369** [SleepyTrousers/EnderIO#4003]
I can't believe I'm the first to suggest this, but search didn't turn up anything.

Could the Enchanter and the Dark Steel Anvil be made to draw in LiquidXP the same way that the Soul Binder does? It is mildly irritating having to switch between the obelisk and the other machine constantly if you want to do alot of enchanting without wasting XP by drawing too many levels at once.

**Comment by HenryLoenwind** [comment]
http://ideas.theideawall.com/EnderIO
