### ISSUE TITLE
dupe bug with conduits

### ISSUE THREAD

**Issue by Sitherious** [SleepyTrousers/EnderIO#4006]
#### Issue Description:
EnderIO-1.10.2-3.1.156.jar

coduits dupe bug

#### What happens:

if your replaceing the enderio Enhanced energy conduits with Ender energy conduit from teir 2 to teir 3
right clicking with the green to the orange conduit, it replaces the conduit and gives you back the enhanced but doesnt take the energy

#### What you expected to happen:
when replacing it should take out the one for the one you replaced

#### Steps to reproduce:

1. place  any ammount of enhanced conduits down
2. right click with energy conduits
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.156.jar
- EnderCore: EnderCore-1.10.2-0.4.1.64-beta.jar
- Minecraft: 1.10.2
- Forge: Forge Mod Loader version 12.18.3.2185

#### Your most recent log file where the issue was present: 

no errors in console for this.

**Comment by HenryLoenwind** [comment]
You are using Sponge, aren't you?

**Comment by Sitherious** [comment]
Yes

**Comment by Sitherious** [comment]
Is it due to sponge if so I will post there

**Comment by HenryLoenwind** [comment]
see #3995
