### ISSUE TITLE
Illegal Argument Exception Crashes Server

### ISSUE THREAD

**Issue by Renari** [SleepyTrousers/EnderIO#4007]
#### Issue Description:
Server crashes on 1.10.2 

#### What happens:
Server crashes with the above exception.

#### What you expected to happen:
The server to remain running normally.

#### Steps to reproduce:
I haven't been able to consistently replicate the issue.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.157
- EnderCore: 1.10.2-0.4.1.62-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

[https://gist.github.com/Renari/43ac8a41a73bfe030d0410fd3feb3069](https://gist.github.com/Renari/43ac8a41a73bfe030d0410fd3feb3069)

**Comment by HenryLoenwind** [comment]
see #3939
