### ISSUE TITLE
Disable alloys recipe

### ISSUE THREAD

**Issue by Waisse** [SleepyTrousers/EnderIO#4008]
xml documentation isn't clear enough. I want to disable specifics alloys recipe.

**Comment by Waisse** [comment]
Trying to disable electrical steel : 

  <recipeGroup name="EnderIO" enabled="false" > 
    <recipe name="Electrical Steel" energyCost="10000" >
      <input>
        <itemStack modID="minecraft" itemName="iron_ingot" />
        <itemStack oreDictionary="dustCoal" />
        <itemStack oreDictionary="itemSilicon" />
      </input>
      <output>
        <itemStack modID="EnderIO" itemName="itemAlloy" itemMeta="0" exp="0.5" />
      </output>
    </recipe>
	</recipeGroup>

Doesn't work.

**Comment by MatthiasMann** [comment]
Try:
<recipeGroup name="EnderIO">
<recipe name="Electrical Steel"/>
</recipeGroup>

and then add your own recipe in a different group.

**Comment by Waisse** [comment]
I just want to disable the alloy recipe, not replace it. I'm using another mod to produce the alloy on my pack.
