### ISSUE TITLE
java.lang.ClassCastException 1.10.2 upon world load

### ISSUE THREAD

**Issue by SDUBZ** [SleepyTrousers/EnderIO#4009]
#### Issue Description:
loaded in my world and it crashed me back to desktop
#### What happens:
crashes me back to desktop upon world

#### What you expected to happen:
load up my world no problems

#### Steps to reproduce:

1.load up a old world that you were playing with prior enderio versions
2.select said world
3.crash back to desktop
...
not sure how to describe it better sorry :/

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.161
- EnderCore:1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge:1.10.2-2221

#### Your most recent log file where the issue was present: 
[fml-client-latest.txt](https://github.com/SleepyTrousers/EnderIO/files/722412/fml-client-latest.txt)

[pastebin/gist/etc link here]
[crash-2017-01-23_12.06.16-server.txt](https://github.com/SleepyTrousers/EnderIO/files/722410/crash-2017-01-23_12.06.16-server.txt)

**Comment by MatthiasMann** [comment]
Do you know which block is next to the crashing fluid conduit?

**Comment by HenryLoenwind** [comment]
Yes, this is the fault of the neighbor block, which I strongly suspect to not be an Ender IO block.

**Comment by SDUBZ** [comment]
any ideas how to track whats causing it to crash the fluid conduit?

**Comment by SDUBZ** [comment]
opened world with mcedit and it seems to be connected to ex nihilo crucible

**Comment by HenryLoenwind** [comment]
I'd just delete one of them (backup your world first) and see what happens when you start the world.

**Comment by SDUBZ** [comment]
im nailing this down to some world corruption or something like that because only 2 of the conduits errored out and when i removed them it was fixed 1.10.2 is wierd sometimes,but hey thanks for the advice @HenryLoenwind 👍

**Comment by HenryLoenwind** [comment]
There is no way this can be caused by world corruption, there's some programming error somewhere. It may only happen in specific circumstances, but it is there.

**Comment by SDUBZ** [comment]
well i will let you know if i get any triggers on openeye
