### ISSUE TITLE
mod conflict

### ISSUE THREAD

**Issue by Sitherious** [SleepyTrousers/EnderIO#4013]
#### Issue Description:
mod conflict

#### What happens:
using dark utils sneaky block with enderio causes client crash, similar issue 
https://github.com/Darkhax-Minecraft/Dark-Utilities/issues/38

darkhax commented
This would be an issue with EnderIO not checking if the block is actually their own block. Please kindly request that they add a check to detect this.

#### What you expected to happen:
mods to work together in harmony :)

#### Steps to reproduce:

1. place down a sneaky block
2.place almost any enderio block on sneaky block
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.156.jar
- EnderCore: EnderCore-1.10.2-0.4.1.64-beta.jar
-Minecraft: 1.10.2
-Dark Utilities: 1.1.6.105
- Forge: 2185

**Comment by HenryLoenwind** [comment]
Asking a block for data about another block is stupid and not valid. I will put in a check for it, but that will throw an InvalidParameterException.

**Comment by Sitherious** [comment]
i am sorry im not a programmer i wish i could help, i know everyone program's differently but i love both of the mods maybe you and @darkhax could find a workable solution ?

**Comment by darkhax** [comment]
HenryLoenwind has no obligation to help with this issue. Camo type blocks such as those in my mod are certainly edge cased. There are ways to deal with issues such as these but I have chosen to avoid such for performance reasons. That said, I appreciate the check and will look into developing a much friendlier system for this moving forward! Thanks again.

**Comment by HenryLoenwind** [comment]
btw, "place almost any enderio block on sneaky block" cannot be right, the fused quartz is the only block that actually accesses its own blockstate that way (reason: code reuse) for shouldSideBeRendered().

**Comment by Sitherious** [comment]
i am sorry about almost any comment, i was going by what my members have stated and did not have this issue myself, nect time i will double check myself to make sure its accurate statement.

**Comment by aaronmallen** [comment]
[crash-2017-01-21_01.28.21-client.txt](https://github.com/SleepyTrousers/EnderIO/files/735840/crash-2017-01-21_01.28.21-client.txt)
