### ISSUE TITLE
conflict mods, game crashes when I try to configure the liquid pipe 

### ISSUE THREAD

**Issue by KiraLinux** [SleepyTrousers/EnderIO#4014]
#### What happens:
Game crashes when I configure the liquid pipe

#### What you expected to happen:
supply of water from the pump Mekanism mod

#### Steps to reproduce:

1. I put the liquid pipe high pressure 
2. I went into its interface
3. included fluid flow and control disabled the red stone
I made these actions very quickly
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 1.7.10-Forge10.13.4.1614-1.7.10
 Maybe conflict with  OptiFine_1.7.10_HD_U_D6

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
[crash-2017-01-26_23.34.46-client.txt](https://github.com/SleepyTrousers/EnderIO/files/733536/crash-2017-01-26_23.34.46-client.txt)

**Comment by HenryLoenwind** [comment]
That's Optifine's fault.
