### ISSUE TITLE
1.7.10 initialization help

### ISSUE THREAD

**Issue by djthekiller321** [SleepyTrousers/EnderIO#4016]
#### Issue Description:
crashing during initialization 

#### What happens:
when forge finishes loading it will just go back to the pre-game screen i have downloaded from the curseforge site, the most recent 1.7.10 ender core and IO. also it says that:
java.lang.IllegalArgumentException: minecraft:beetroot_seeds is not a vaild string. Strings should be either an oredict name, or in the format objectname;damage (damage is optional)

#### What you expected to happen:
to just normally load up with the mods so i could play

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  1.7.10-2.3.0.415_beta
- EnderCore: 1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10 
- Forge: 10.13.4.1614-1.7.10

#### Your most recent log file where the issue was present: 

[[crash-2017-01-27_15.36.57-client.txt](https://github.com/SleepyTrousers/EnderIO/files/736435/crash-2017-01-27_15.36.57-client.txt)]

**Comment by djthekiller321** [comment]
and now it worked when i added another mod in, but i think that was because none of the other mods were initialized

**Comment by djthekiller321** [comment]
ok i think it is the post initialization process idk

**Comment by djthekiller321** [comment]
for now just gonna remove from mod list

**Comment by HenryLoenwind** [comment]
Beetroot seeds is a Minecraft 1.9 item. Seems you are using config files from the future...

**Comment by T1mbonator** [comment]
> Beetroot seeds is a Minecraft 1.9 item. Seems you are using config files from the future...

Hi! How do i change the config file to a 1.7.10 file/ What do i need to change?

**Comment by tyler489** [comment]
Delete the file and let it regen
