### ISSUE TITLE
Bad Version Detection

### ISSUE THREAD

**Issue by janagyjr** [SleepyTrousers/EnderIO#4017]
#### Issue Description:
Standard modded installation (not a modpack from Curse) of Minecraft 1.7.10, EnderIO errors out claiming a conflict with BuildCraft additions, saying it's too old.

#### What happens:
Start Minecraft, launch profile to play game, EnderIO incorrectly version detects BuildCraft Additions, crashes the initialization.

#### What you expected to happen:
Play modded minecraft with EnderIO

#### Steps to reproduce:

1. Add in EnderIO and Endercore with BuildCraft Additions 1.7.10-2.2.5 (and other requisite mods)
2. launch game
3. watch it crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-2.0.39_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1566

#### Your most recent log file where the issue was present: 

http://pastebin.com/k8D6sJ9T

I tried removing BuildCraft additions and Eureka (a BCA dependency) and it still errored out:

http://pastebin.com/W4GMYEs5

I have no idea what other mod is causing an error at this point

**Comment by HenryLoenwind** [comment]
BuildCraft Additions ships an ancient version of the RF API that is known not to work with Ender IO.

**Comment by janagyjr** [comment]
As you can see in the second paste, I removed BuildCraft Additions, the RF API error happens /after/ I remove BuildCraft additions

**Comment by janagyjr** [comment]
I've removed all traces of BCA from my installation and EnderIO is still crashing on the RF API thing.

**Comment by janagyjr** [comment]
@HenryLoenwind I upgraded my forge version and all the issues I had (no optifine support, BCA conflicts) went away. I am running Forge 10.13.4.1614 now and have loaded BCA and OptiFine 1.7.10_HD_U_D6 just fine along with EnderIO stuff

**Comment by HenryLoenwind** [comment]
btw, why did you never post your crash but only your system details?

**Comment by janagyjr** [comment]
I thought that last part /was/ the crash report. I had a stupid moment..
