### ISSUE TITLE
Recipe Crash? I am not a programmer!

### ISSUE THREAD

**Issue by dragonpc75** [SleepyTrousers/EnderIO#4018]
#### Issue Description:
Client Crash upon Clicking the enchanter recipe tab  (recipe tab at the top) for blaze rods in Jei.
It only happens when i click on the Ender IO enchanter recipe tab regarding blaze rods.

#### What happens:
Client Crashes

#### What you expected to happen:
Client not to crash when i click a recipe ;)

#### Steps to reproduce:

1.have blaze rod in inventory
2.press U while hovering on blaze rod
3.click the "enchanter" tab at the top
4.wait for crash report to build.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.0.1.64
- EnderCore:1.10.2-0.4.1.62
- Minecraft: 1.10.2
- Forge:2185

#### Your most recent log file where the issue was present: 
BOTH of these are the crash reports that i have for BOTH times it crashed, as it stated i must reproduce it.. these are both the reports.

[crash-2017-01-27_22.51.37-client.txt](https://github.com/SleepyTrousers/EnderIO/files/736760/crash-2017-01-27_22.51.37-client.txt)
[crash-2017-01-27_23.02.08-client.txt](https://github.com/SleepyTrousers/EnderIO/files/736759/crash-2017-01-27_23.02.08-client.txt)

**Comment by HenryLoenwind** [comment]
3.0.1.64? Really?? That version if from (Jul 8, 2016 3:22:52 PM)...
