### ISSUE TITLE
Editing recipe Help

### ISSUE THREAD

**Issue by LokyLive** [SleepyTrousers/EnderIO#4019]
Hello everyone ,

I'm trying to remove some alloy smelter but it doesn't works and i don't understand why could you help me please ?

http://pastebin.com/iABaw1pD

Forgot to say i'm using EnderIO-1.10.2-3.1.164

**Comment by HenryLoenwind** [comment]
Are you sure you're looking at the right recipe ingame? There are multiple variants for the glasses...

**Comment by LokyLive** [comment]
Edited and relaunch with all recipe removed and it still works. I don't understand what i'm doing wrong 

http://pastebin.com/dretyC5g

Screen of alloy smelting:

http://imgur.com/a/dvqXn

**Comment by HenryLoenwind** [comment]
What does the logfile say?

**Comment by LokyLive** [comment]
log file here
http://pastebin.com/nK5nBzsq

**Comment by HenryLoenwind** [comment]
```
[17:25:55] [Client thread/DEBUG] [EnderIO/EnderIO]: Removed recipe Enlightened Fused Quartz from Block 4 due to user config.
```

Looks good to me.

You might want to avoid having multiple blocks with the same ID in the file. The last one wins.

**Comment by LokyLive** [comment]
I don't understand , how to do xD  
I have to disable all recipe for this item so i have to tell him wich recipe disable  not wich item .
Could you give me an example to illustrate what you wanna mean ?

PS: Enlightened Fused Quartz from Block 4 still craftable ...

**Comment by HenryLoenwind** [comment]
```
<AlloySmelterRecipes>
 
  <recipeGroup name="EnderIO">
    <recipe name="Enlightened Fused Quartz"/>
    <recipe name="Enlightened Fused Quartz 2"/>
    <recipe name="Enlightened Fused Glass"/>
    <recipe name="Enlightened Fused Glass 2"/>
    <recipe name="Enlightened Fused Quartz from Block"/>
    <recipe name="Enlightened Fused Quartz from Block 2"/>
    <recipe name="Enlightened Fused Quartz from Block 3"/>
    <recipe name="Enlightened Fused Quartz from Block 4"/>
  </recipeGroup>
 
</AlloySmelterRecipes>
```

**Comment by LokyLive** [comment]
Awesome it works thanks for help ,p
