### ISSUE TITLE
Facades painted with logs

### ISSUE THREAD

**Issue by Hazmatik** [SleepyTrousers/EnderIO#4020]
Would it be possible to have conduit facades that are painted with logs place like logs. Meaning if I place it against the side of a block it renders the log horizontally. Currently it seems no matter what side of a block I place a facade painted with a log against it renders as a vertical log.

**Comment by Ravin890** [comment]
You need to right click on it with a yeta wrench thats not in conduit mode (the red x or in the wrench with gear icon) to turn it

**Comment by Hazmatik** [comment]
Thank you, I didn't know that was a thing.

**Comment by HenryLoenwind** [comment]
Yes, it is. And btw, I'd rather avoid adding special code for the default rotation of blocks...otherwise we'd end up with a huge list of them.

For the statistics: 1.10 or 1.7?
