### ISSUE TITLE
Killer Joe has no interface for XP

### ISSUE THREAD

**Issue by Zocki12** [SleepyTrousers/EnderIO#4021]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens: In the Killer Joe is no Interface for the XP i have searched an older Version of it and i found that from the Version "EnderIO-1.10.2-3.0.1.124_beta" the interface is gone. Then the xp vacuum was inserted. Or is that so wanted? If so how do I get then liquid xp?
Is that wanted?
(Sry for the bad English :))

#### Steps to reproduce:

1. Grab the Killer Joe 
2. Place it and fill it
3. Get angry
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.156
- EnderCore: EnderCore-1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: Forge 12.18.3.2221

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment]
You need to use the XP Vacuum to suck up XP orbs (it will output to adjacent tanks or fluid conduits).

**Comment by Zocki12** [comment]
Yes I know but I need only once a Liquid Xp bucket to activate this.

**Comment by HenryLoenwind** [comment]
There are 3 ways to get Liquid XP in Ender IO. The Killer Joe is no longer one of them.
