### ISSUE TITLE
[Question] Is EnderIO backward compatible?

### ISSUE THREAD

**Issue by ExDomino** [SleepyTrousers/EnderIO#4022]
Hello, my question is about the version of EnderIO. If I install on my server EnderIO for 1.10.2, and later you make the 1.11 version. Will I need to reset the map? Or the new version will be completely backward compatible with the old version?

I ask this question because I plan to create a stable server, with only mods that are backward compatible, and want to be able to upgrade minecraft to 1.11, 1.12, 1.13, and so on, without loosing the map at any time. In vanilla it's possible of course, but with mods, it's different, so I'm asking if you mod is one of the rare mods that are backward compatible, because usualy a mods need complete map reset each new minecraft version.

Thank in advance.

**Comment by HenryLoenwind** [comment]
Our block IDs, item IDs and mod ID are not 1.11 compatible, so will will have to change them...

**Comment by ExDomino** [comment]
So upgrade from 1.10 to 1.11 will need a map reset? The same will occur for 1.11 to 1.12 and so on?

**Comment by ktole1999** [comment]
depending on future game changes its not always possible to retain previous compatibility. always backup your world.
