### ISSUE TITLE
A duplicate mod Waila appeared when I want to develop EnderIO addon

### ISSUE THREAD

**Issue by xsun2001** [SleepyTrousers/EnderIO#4023]
A duplicate mod Waila appeared when I want to dependent EnderIO in ForgeGradle for my EnderIO addon.
![24](https://cloud.githubusercontent.com/assets/14010993/22470787/536bbcbc-e80b-11e6-98f7-5ec2f6fbba43.png)
Here are the crash log.
[fml-client-latest.txt](https://github.com/SleepyTrousers/EnderIO/files/742320/fml-client-latest.txt)

**Comment by SunshineXDev** [comment]
And that is what minecraft will be...
![25](https://cloud.githubusercontent.com/assets/14010993/22471007/0def08c8-e80c-11e6-9234-c4021d7e0f76.png)

**Comment by HenryLoenwind** [comment]
It seems you build env is ignoring this: https://github.com/SleepyTrousers/EnderIO/blob/master/build.gradle#L70

I also recommend to depend on Ender IO with ```transitive = false``` and adding the runtime dependencies to your gradle. Those are far less than our compile dependencies (only endercore).

**Comment by xsun2001** [comment]
Thank you very much!They are all useful suggestions.
