### ISSUE TITLE
Sheep color is forgotten when making a spawner

### ISSUE THREAD

**Issue by Ricket** [SleepyTrousers/EnderIO#4024]
#### What happens:

Capture colored sheep, turn into spawner, the spawner only spits out grayscale sheep (white/black/brown/light gray/dark gray)

#### What you expected to happen:

Expected the spawner to spawn sheep of the same color as was originally captured.

#### Steps to reproduce:

1. Capture colored sheep in soul vial
2. Use soul binder to bind it to a Broken Spawner. The tooltip only says "Sheep" so you have no idea what color it is, if the color is even saved.
3. Use anvil to combine a Powered Spawner with the sheep flavored broken spawner. The new Powered Spawner also only says Sheep in tooltip, did it remember the color?
4. Place the powered spawner and turn it on. It spawns random sheep which are white, black, brown, light gray, or dark gray. The original sheep color seems to have been totally forgotten.

Here is an example after running some spawners for a while (I already made 16 spawners, one for each color, before discovering that they all spit out random sheep from these 5 grayscale shades...)

![sample distribution of the colors](https://cloud.githubusercontent.com/assets/196978/22497494/17849632-e820-11e6-9839-02df0ed734c2.png)

____
#### Affected Versions:

- EnderIO-1.10.2-3.1.156.jar
- EnderCore-1.10.2-0.4.1.64-beta.jar
- Minecraft: 1.10.2
- Forge: 2185

**Comment by tterrag1098** [comment]
The powered spawner does not copy entities. It spawns new ones with vanilla rules (this includes the randomized color).

**Comment by HenryLoenwind** [comment]
As tt said.
