### ISSUE TITLE
Crash when walking on top of any conduit.

### ISSUE THREAD

**Issue by FlagrantFool** [SleepyTrousers/EnderIO#4025]
#### Issue Description:
Crash when walking on top of any conduit.

#### What happens:
Crash when walking on top of any conduit.

#### What you expected to happen:
No crash.

#### Steps to reproduce:

1. Install mods
2. Walk on conduit

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.161
- EnderCore: EnderCore-1.10.2-0.4.1.64-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2185

#### Your most recent log file where the issue was present:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.64-beta.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.1.185-universal.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.13.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.2.3.0.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 2/1/17 8:17 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at org.blockartistry.mod.DynSurround.util.MyUtils.append(MyUtils.java:80)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Association.add(Association.java:80)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Solver.addSoundOverlay(Solver.java:440)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Solver.findAssociationForPlayer(Solver.java:120)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Generator.simulateFootsteps(Generator.java:114)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Generator.generateFootsteps(Generator.java:76)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Isolator.onFrame(Isolator.java:58)
	at org.blockartistry.mod.DynSurround.registry.FootstepsRegistry.process(FootstepsRegistry.java:182)
	at org.blockartistry.mod.DynSurround.client.handlers.FootstepsHandler.process(FootstepsHandler.java:52)
	at org.blockartistry.mod.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:124)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_552_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.blockartistry.mod.DynSurround.util.MyUtils.append(MyUtils.java:80)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Association.add(Association.java:80)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Solver.addSoundOverlay(Solver.java:440)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Solver.findAssociationForPlayer(Solver.java:120)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Generator.simulateFootsteps(Generator.java:114)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Generator.generateFootsteps(Generator.java:76)
	at org.blockartistry.mod.DynSurround.client.footsteps.system.Isolator.onFrame(Isolator.java:58)
	at org.blockartistry.mod.DynSurround.registry.FootstepsRegistry.process(FootstepsRegistry.java:182)
	at org.blockartistry.mod.DynSurround.client.handlers.FootstepsHandler.process(FootstepsHandler.java:52)
	at org.blockartistry.mod.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:124)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_552_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Slim1'/182, l='MpServer', x=-623.11, y=50.20, z=707.67]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 09 - botania-skyblock, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-604,86,685), Chunk: (at 4,5,13 in -38,42; contains blocks -608,0,672 to -593,255,687), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 8276307 game time, 12472411 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 62 total; [EntityLeashKnot['entity.LeashKnot.name'/139, l='MpServer', x=-626.50, y=70.50, z=658.50], EntitySheep['Sheep'/11, l='MpServer', x=-639.50, y=70.00, z=649.73], EntityLeashKnot['entity.LeashKnot.name'/140, l='MpServer', x=-626.50, y=70.50, z=659.50], EntityRabbit['Rabbit'/12, l='MpServer', x=-625.50, y=70.00, z=658.03], EntityChicken['Chicken'/13, l='MpServer', x=-635.24, y=70.00, z=668.16], EntityCow['Cow'/14, l='MpServer', x=-625.93, y=70.00, z=663.70], EntityChicken['Chicken'/15, l='MpServer', x=-630.50, y=70.00, z=668.97], EntityItem['item.item.coal'/1935, l='MpServer', x=-619.27, y=82.00, z=703.71], EntityCow['Cow'/16, l='MpServer', x=-624.84, y=70.00, z=663.07], EntityChicken['Chicken'/17, l='MpServer', x=-638.45, y=70.00, z=663.85], EntityCow['Cow'/18, l='MpServer', x=-625.16, y=70.00, z=664.62], EntityCow['Cow'/19, l='MpServer', x=-618.80, y=70.00, z=663.57], EntityItem['item.item.coal'/1811, l='MpServer', x=-621.88, y=82.00, z=701.67], EntityChicken['Chicken'/20, l='MpServer', x=-630.49, y=70.00, z=672.17], EntityItem['item.item.egg'/21, l='MpServer', x=-637.97, y=70.00, z=663.67], EntityItem['item.item.egg'/22, l='MpServer', x=-629.99, y=70.00, z=663.60], EntityItem['item.item.egg'/23, l='MpServer', x=-635.93, y=70.00, z=667.78], EntitySpark['Spark'/25, l='MpServer', x=-632.50, y=84.50, z=672.50], EntitySpark['Spark'/26, l='MpServer', x=-627.50, y=83.50, z=672.50], EntityZombie['Zombie'/27, l='MpServer', x=-626.48, y=63.00, z=781.28], EntityCreeper['Creeper'/28, l='MpServer', x=-632.50, y=63.00, z=780.50], EntityItem['item.item.coal'/1692, l='MpServer', x=-619.68, y=82.00, z=699.13], EntityCow['Cow'/31, l='MpServer', x=-624.00, y=70.00, z=664.12], EntityCow['Cow'/32, l='MpServer', x=-622.95, y=70.00, z=665.86], EntityCow['Cow'/33, l='MpServer', x=-625.13, y=70.00, z=672.38], EntityCow['Cow'/34, l='MpServer', x=-616.45, y=70.00, z=666.26], EntityRabbit['Rabbit'/35, l='MpServer', x=-622.70, y=70.00, z=658.76], EntityCow['Cow'/36, l='MpServer', x=-620.60, y=70.00, z=662.64], EntityMooshroom['Mooshroom'/37, l='MpServer', x=-623.59, y=70.00, z=658.17], EntityCow['Cow'/38, l='MpServer', x=-618.16, y=70.00, z=665.48], EntityCow['Cow'/39, l='MpServer', x=-622.69, y=70.00, z=664.63], EntityZombie['Zombie'/40, l='MpServer', x=-627.72, y=89.00, z=668.45], EntityVillager['Villager'/41, l='MpServer', x=-614.28, y=82.00, z=672.42], EntitySkeleton['Skeleton'/51, l='MpServer', x=-611.50, y=63.00, z=777.50], EntitySpider['Spider'/52, l='MpServer', x=-618.50, y=63.00, z=779.50], EntityZombie['Zombie'/53, l='MpServer', x=-623.50, y=63.00, z=778.50], EntityCreeper['Creeper'/54, l='MpServer', x=-617.81, y=63.00, z=772.56], EntityItem['item.item.coal'/1848, l='MpServer', x=-621.76, y=82.00, z=703.10], EntityCow['Cow'/59, l='MpServer', x=-592.39, y=82.00, z=662.85], EntityItem['item.item.coal'/1979, l='MpServer', x=-617.95, y=82.00, z=703.58], EntityHorse['Mule'/60, l='MpServer', x=-601.40, y=69.00, z=685.62], EntitySpider['Spider'/61, l='MpServer', x=-601.50, y=63.00, z=780.50], EntityItem['item.item.coal'/1733, l='MpServer', x=-621.01, y=82.00, z=699.13], EntitySkeleton['Skeleton'/76, l='MpServer', x=-584.50, y=38.00, z=639.50], EntityWoman['Bloody Maiden'/77, l='MpServer', x=-585.50, y=38.00, z=661.50], EntityHorse['Donkey'/78, l='MpServer', x=-581.94, y=82.00, z=667.38], EntityHorse['Donkey'/79, l='MpServer', x=-578.40, y=82.00, z=666.84], EntityCow['Cow'/80, l='MpServer', x=-586.59, y=82.00, z=662.93], EntityHorse['Horse'/81, l='MpServer', x=-582.25, y=82.00, z=665.86], EntityHorse['Horse'/82, l='MpServer', x=-588.01, y=82.00, z=670.11], EntitySpider['Spider'/83, l='MpServer', x=-583.85, y=63.00, z=778.53], EntitySlime['Slime'/94, l='MpServer', x=-575.21, y=38.00, z=651.23], EntitySkeleton['Skeleton'/95, l='MpServer', x=-573.50, y=63.00, z=780.50], EntityItem['item.item.coal'/1888, l='MpServer', x=-620.63, y=82.00, z=703.71], EntityPlayerSP['Slim1'/182, l='MpServer', x=-623.11, y=50.20, z=707.67], EntityItem['item.item.coal'/2025, l='MpServer', x=-617.50, y=82.00, z=702.39], EntityEnderman['Enderman'/363, l='MpServer', x=-609.50, y=63.00, z=774.50], EntityZombie['Zombie'/364, l='MpServer', x=-605.74, y=63.00, z=779.40], EntityItem['item.item.coal'/1775, l='MpServer', x=-621.86, y=82.00, z=700.02], EntityItem['item.item.coal'/1648, l='MpServer', x=-618.32, y=82.00, z=699.13], EntitySpider['Spider'/369, l='MpServer', x=-605.50, y=63.00, z=774.50], EntityItem['item.item.coal'/2047, l='MpServer', x=-617.50, y=82.38, z=701.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 625172848 bytes (596 MB) / 2120679424 bytes (2022 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	buildingbrickshooks{1.10.2-2.0.13} [Building Bricks Hooks] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.1.185-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	dmonsters{1.142} [Deadly Monsters] (1.10.2_deadly_monsters_1.142.jar) 
	UCHIJAAAA	thinkbigcore{1.5.8} [§5§m===§r §e§lThink Big Core §5§m===§r] (Think Big Core V1.5.8 - 1.10.2.jar) 
	UCHIJAAAA	adinferos{1.2.4} [§e§k!!§6§k]]§c§kkk§4§lAd Inferos§c§kkk§6§k]]§e§k!!] (Ad Inferos V1.2.4 - 1.10.2.jar) 
	UCHIJAAAA	apple_shields{0.1.0} [apple_shields] (AppleShields-0.1.0.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.6.jar) 
	UCHIJAAAA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJAAAA	BaublesHud{3.2.0} [Baubles-Hud] (BaublesHud-1.10.2-3.2.0.jar) 
	UCHIJAAAA	XaeroBetterPvP{1.11.4} [Better PVP Mod] (Better-PvP-Mod-1.10.2.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	Botania{r1.9-340} [Botania] (Botania r1.9-340.jar) 
	UCHIJAAAA	buildingbricks{1.10.2-2.0.13} [Building Bricks] (BuildingBricks-1.10.2-2.0.13.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.1.185} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.1.185-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.0.100} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.100-universal.jar) 
	UCHIJAAAA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJAAAA	chickens{4.3.2} [Chickens] (Chickens-Mod-1.10.2.jar) 
	UCHIJAAAA	creeperchicks{v2.0} [Creeper Chicks] (CreeperChicks-1.10.2-v2.0.jar) 
	UCHIJAAAA	cyclopscore{0.9.1} [Cyclops Core] (CyclopsCore-1.9.4-0.9.1.jar) 
	UCHIJAAAA	dsurround{3.2.3.0} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.2.3.0.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.64-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.64-beta.jar) 
	UCHIJAAAA	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.161} [Ender IO] (EnderIO-1.10.2-3.1.161.jar) 
	UCHIJAAAA	valkyrielib{1.10.2-0.10.5f} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5f.jar) 
	UCHIJAAAA	environmentaltech{1.10.2-0.10.5i} [Environmental Tech] (environmentaltech-1.10.2-0.10.5i.jar) 
	UCHIJAAAA	evilcraft{0.10.19} [EvilCraft] (EvilCraft-1.10.2-0.10.19.jar) 
	UCHIJAAAA	forestry{5.2.17.362} [Forestry] (forestry_1.10.2-5.2.17.362.jar) 
	UCHIJAAAA	morebees{1.10.2-1.2} [More Bees] (morebees-1.10.2-1.2.jar) 
	UCHIJAAAA	exnihiloomnia{1.2.5} [Ex Nihilo Omnia] (exnihiloomnia-1.2.5.jar) 
	UCHIJAAAA	GardenOfGlass{sqrt(-1)} [Garden of Glass] (GardenOfGlass.jar) 
	UCHIJAAAA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJAAAA	JoypadSplitscreenMod{1.9.0-0.21} [Joypad / SplitScreen Mod] (JoypadMod-1.9-12.16.0.1842-1.9.jar) 
	UCHIJAAAA	simplecore{1.3.15.1} [SimpleCore API] (simplecore-1.10.2-1.3.15.1.jar) 
	UCHIJAAAA	netherrocks{1.4.7.2} [Netherrocks] (netherrocks-1.10.2-1.4.7.2.jar) 
	UCHIJAAAA	petbat{1.4.4} [Pet Bat] (PetBat-1.10.2.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.620} [Reliquary] (Reliquary-1.10.2-1.3.3.620.jar) 
	UCHIJAAAA	SaltMod{1.8.d} [Salty Mod] (SaltyMod-1.10.2-1.8.d.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.16} [Storage Drawers] (StorageDrawers-1.10.2-3.5.16.jar) 
	UCHIJAAAA	storagedrawersextra{1.10-1.0.0} [Storage Drawers Extras] (StorageDrawersExtras-1.10.2-1.0.0.jar) 
	UCHIJAAAA	switchbow{1.0} [Switch-Bow] (Switch-Bow-Mod-1.10.2.jar) 
	UCHIJAAAA	terrainCrystals{1.2.3} [Terrain Crystals] (Terrain Crystals 1.10.2 - 1.2.3.jar) 
	UCHIJAAAA	terrainCrystalsAddons{1.1.1} [Terrain Crystals Addons] (TC Addons 1.10.2-1.1.1.jar) 
	UCHIJAAAA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCHIJAAAA	wearablebackpacks{1.3.0} [Wearable Backpacks] (Wearable-Backpacks-Mod-1.10.2.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.64-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.1.185-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.BlockStateLoaderTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.13.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.2.3.0.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 5500'
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Son%20Of%20A%20Gun/AppData/Roaming/.minecraft/mods/valkyrielib-1.10.2-0.10.5f.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Son%20Of%20A%20Gun/AppData/Roaming/.minecraft/mods/AppleShields-0.1.0.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Son%20Of%20A%20Gun/AppData/Roaming/.minecraft/mods/AppleShields-0.1.0.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Son%20Of%20A%20Gun/AppData/Roaming/.minecraft/mods/valkyrielib-1.10.2-0.10.5f.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Son%20Of%20A%20Gun/AppData/Roaming/.minecraft/mods/valkyrielib-1.10.2-0.10.5f.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Son%20Of%20A%20Gun/AppData/Roaming/.minecraft/mods/AppleShields-0.1.0.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Son%20Of%20A%20Gun/AppData/Roaming/.minecraft/mods/valkyrielib-1.10.2-0.10.5f.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Son%20Of%20A%20Gun/AppData/Roaming/.minecraft/mods/valkyrielib-1.10.2-0.10.5f.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Son%20Of%20A%20Gun/AppData/Roaming/.minecraft/mods/valkyrielib-1.10.2-0.10.5f.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.4549, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4549
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by HenryLoenwind** [comment]
The mod " org.blockartistry.mod.DynSurround" is crashing here, Ender IO's code isn't even involved.

**Comment by HenryLoenwind** [comment]
That https://github.com/OreCruncher/DynamicSurroundings/issues I think
