### ISSUE TITLE
Allow all entity-containing items to be used with powered spawners and friends.

### ISSUE THREAD

**Issue by SoniEx2** [SleepyTrousers/EnderIO#4026]
I believe items such as vanilla mob spawners, mob eggs, powered spawners, soul vials, golden lassos, cursed lassos, safari nets, broken spawners, etc should all be allowed in the soul binder and powered spawner and stuff.

Those are all entity-containing items. Some of them can be emptied, while others cannot. Some of them are consumed, while others are not. Some of them can be rebound, while others cannot.

Mob eggs in a soul binder should consume the mob egg. Soul vials in a soul binder should do what they already do. Safari nets should empty them. Vanilla mob spawners should never be consumed. Powered spawners and broken spawners should also never be consumed, thus allowing cloning of a spawner type.

This might require a new forge API, which for some reason we still don't have. We've had entity-containing items for years but we have yet to have an API for entity-containing items. Maybe this'll push for one.

**Comment by HenryLoenwind** [comment]
Wrong tracker. Suggestions: http://ideas.theideawall.com/EnderIO

**Comment by SoniEx2** [comment]
"Wrong tracker" says you. "Bug reports & suggestions" says the fucking homepage.

**Comment by mindforger** [comment]
except for his bad wording he is right, i did not find any hint to the idea wall anywhere either

**Comment by HenryLoenwind** [comment]
@Nentify
