### ISSUE TITLE
ClassNotFound - Tesla (1.10)

### ISSUE THREAD

**Issue by Rob5Underscores** [SleepyTrousers/EnderIO#4029]
#### Issue Description:
[USING SPONGE - Version included below]

https://github.com/SleepyTrousers/EnderIO/issues/3766
The issue above is very similar to the one I'm facing, however, I haven't enabled debug logging - not knowingly and I don't know how to? (or to disable).

#### What happens:
Huge console spam -> http://pastebin.com/BaL0pHwC

#### Steps to reproduce:

1. My plugin which spawns items on certain block breaks seems to be related?

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.164
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10
- Forge: 2202
- Sponge: spongeforge-1.10.2-2221-5.1.0-BETA-2109

#### Your most recent log file where the issue was present: 

as above.

Apologies in advance if this a duplicate issue but I did look :/

**Comment by Rob5Underscores** [comment]
@HenryLoenwind apologies. pasted wrong link

**Comment by HenryLoenwind** [comment]
Two things: 

First:
```
        if (Log.LOGGER.isDebugEnabled()) {
          e.printStackTrace();
        }
```

Second: You game **is** crashing. But some mod is preventing the crash from stopping the game or printing a crash report. That is bad. (Hint: It's not Ender IO...)

**Comment by Rob5Underscores** [comment]
How do I disable the logger then?
