### ISSUE TITLE
ConduitNetworkTickHandler - Too many calls?

### ISSUE THREAD

**Issue by Rob5Underscores** [SleepyTrousers/EnderIO#4030]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

This is in a modpack - SkyFactory 3. FeedTheBeast essentially ignores issues so can't report it to them.

#### What happens:
https://gyazo.com/ff6314eb8db8d0e2d537e5d7de253b08
As seen in the picture above, the server (with 30 players online) has a huge amount of tick time spent on EnderIO conduits

#### Steps to reproduce:

NA
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.164
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10
- Forge: 2202
- Sponge: spongeforge-1.10.2-2221-5.1.0-BETA-2109

#### Your most recent log file where the issue was present: 

https://timings.aikar.co/?id=4f38cace15674b498fa3910adf4bad03&section=all
Full profiler. (Use all tree view to expand)

**Comment by HenryLoenwind** [comment]
Please use a profiler that doesn't report pure rubbish. I have never seen a trace from that tool that had any relation to reality.

**Comment by Rob5Underscores** [comment]
Is warmroast suitable?

**Comment by Rob5Underscores** [comment]
https://gyazo.com/b7f6e9a678d80b9302685ee69844380b

**Comment by HenryLoenwind** [comment]
that's more like it, yeah.

![image](https://cloud.githubusercontent.com/assets/1485873/22610116/302b29b2-ea64-11e6-8175-6fbef7df2c76.png)

Here you see where the time goes...Forge. Probably a variant of https://github.com/MinecraftForge/MinecraftForge/issues/3658 --- that SidedInvWrapper is pretty slow.

(Makes much more sense than "it goes into adding energy capabilities to chargeable Ender IO items", doesn't it? ;) )
