### ISSUE TITLE
Dark Pick with Travel issues

### ISSUE THREAD

**Issue by Lukas45** [SleepyTrousers/EnderIO#4034]
#### Issue Description:
When Shift-Right Clicking towards a Travel Anchor, it does nothing if you are currently targeting/in interact range with a block (will refer as Targeting). 
This is only an issue with the Dark Pick, functions like normal with The Ender and Staff of Traveling

Tested in a world with only EnderIO + JEI, and in a private modpack
Tested with max upgraded Dark Pick
Tested without Spoon
Tested with Empowered I + Travel

#### What happens:
Shift-Right Clicking towards an anchor does nothing if a block is targeted.
No energy consumed, no teleportation, no error messages.
https://i.gyazo.com/f2cbc157f215a76fc4735bcd03dba039.mp4

#### What you expected to happen:
Should teleport you as normal, just like The Ender and Staff of Traveling, and when not targeting a block

#### Steps to reproduce:

1. Get a Dark Pick with Travel
2. Set up a Travel Anchor behind some walls
3. Get behind the wall, while being in targeting range
4. Shift-Right Click towards the Travel Anchor
5. Notice no traveling occuring

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.168
- EnderCore: 0.4.1.65-beta
- JEI: 3.14.4.404
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

#### Your most recent log file where the issue was present: 

Nothing generated in fml-client-latest.log

**Comment by HenryLoenwind** [comment]
That is on purpose because it conflicts with the block placing.

Which can be disabled with the config setting ```darkSteelRightClickPlaceEnabled```. Which in the next build will enable travelling then.
