### ISSUE TITLE
"Push" no longer lets you insert items into machines

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4035]
#### Issue Description:
When setting a machine side to "Push" the machine will no longer accept items from that side. For example when you set up an Applied Energistics Interface to auto-craft with an EnderIO machine pushing the product back into that interface. This no longer works.

#### What happens:
Machine does not accept items.

#### What you expected to happen:
Machine should accept items.

#### Steps to reproduce:

1. Place an Alloy Smelter
2. Set a side to "Push"
3. Place Item Conduit pulling from a chest to that side
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.168
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 2185
- Mods: [list.txt](https://github.com/SleepyTrousers/EnderIO/files/758800/list.txt)

**Comment by HenryLoenwind** [comment]
works as designed

**Comment by HenryLoenwind** [comment]
Ender IO machines have 5 modes:

* NONE: do nothing but accept others to in- and output
* PUSH: push out and accept others to output
* PULL: pull in and accept others to input
* PULLPUSH: push out and pull in and accept others to in- and output
* DISABLED: do nothing, block all access

**Comment by Xiaminou** [comment]
So was "PUSH" bugged all along?

**Comment by HenryLoenwind** [comment]
Not really, but until recently it was the other block's responsibility to honour those restrictions. This changed with item capabilities. We have been using a Forge-provided compatibility layer to support item capabilities until now. With this version we provide out own handler. It is much faster and really good in respecting our restrictions.

**Comment by Xiaminou** [comment]
I see, well I'm just worried that one day I'll have a case of wanting to put items inside a machine without having it pull items from the nearby inventory, but with it pushing items into that inventory.
Which is to say I feel like the way it was acting was better.
