### ISSUE TITLE
Dark Pick Spoon and Snow

### ISSUE THREAD

**Issue by Lukas45** [SleepyTrousers/EnderIO#4036]
#### Issue Description:
Snow doesn't give Snowballs when used with Dark Pick with the Spoon enchant.
Could of course be intentional, but since it gives the pickaxe the functionality of a Shovel, I would think it should also be able to pick up snow.

Tested both in a world with only EnderIO+JEI and in a private modpack.
Tested with a fully upgraded Dark Pick
Tested with only Empowered I and Spoon Dark Pick

#### What happens:
The block just breaks with no drops, as if a non-shovel tool broke it (Dark Pick should be both mining pick + shovel)

#### What you expected to happen:
Snowballs should drop from the snow patches/blocks

#### Steps to reproduce:

1. Make a Dark Pick with Spoon enchant
2. Break snow with it
3. Snowballs doesn't drop

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.168
- EnderCore: 0.4.1.65-beta
- JEI: 3.14.4.404
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

**Comment by tterrag1098** [comment]
Annoyingly enough, the logic for this is in the item, so we'll have to override canHarvestBlock and check that it is `Blocks.SNOW_LAYER` and has the spoon upgrade.

**Comment by tterrag1098** [comment]
On second look, we already do this... are you sure your dark shovel has power?

**Comment by HenryLoenwind** [comment]
Sometimes it is really annoying that Java lets you compare two fields that cannot ever contain the same object just because both may be null...
