### ISSUE TITLE
Decoration Blocks will not rotate

### ISSUE THREAD

**Issue by Gkoliver** [SleepyTrousers/EnderIO#4039]
#### Issue Description:
Decoration blocks will not rotate

#### What happens:
The decorations only face south, as shown by the debug screen.

#### What you expected to happen:
The blocks to face the player (like the power monitor's screen facing where the player places it)

#### Steps to reproduce:

1. Get a decoration block (with the quotation marks around it)
2.  Place it down and note where it's placing
3. Turn in another direction, place it down again, and note what direction it is facing.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.168
- EnderCore: 0.4
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

#### Your most recent log file where the issue was present: 

http://pastebin.com/Chn8R6Sz

**Comment by HenryLoenwind** [comment]
works as designed.

The decoration blocks are not TileEntities, so they have no way to store any kind of rotation. (They work like vanilla wool.)

**Comment by HenryLoenwind** [comment]
PS: As a workaround you can paint a cheap machine with your deco block to get rotation. The underlying machine will have a TileEntity that stores rotation and we have special code that makes the deco blocks use that.
