### ISSUE TITLE
EnderIO Machines spill items when inserting into full containers

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4045]
#### Issue Description:
When EnderIO machines export items if they have a full stack in store they will try to export it even if there isn't room enough for it in the adjacent container, the rest will spill out into the world. Is that intended?
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.169
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 2185
- Mods: [list.txt](https://github.com/SleepyTrousers/EnderIO/files/785117/list.txt)

https://youtu.be/__WQO1HXQaw

**Comment by MatthiasMann** [comment]
What kind of container?

**Comment by HenryLoenwind** [comment]
Yes. The inventory we are trying to insert is first asked if it can take the items. If it says "yes" but then rejects the items we try to put them back...but you cannot put items into an output slot. So they spill...

**Comment by MatthiasMann** [comment]
This is the related issue: https://github.com/jaquadro/StorageDrawers/issues/396

**Comment by Xiaminou** [comment]
Oh, well then.
