### ISSUE TITLE
Can't extract buckets from Stirling Generator

### ISSUE THREAD

**Issue by aesguitar** [SleepyTrousers/EnderIO#4046]
#### Issue Description:
Using an item conduit, I am unable to extract an empty bucket from a stirling generator. I tested on a creative test world using both pressurized and normal fluid tanks. Item conduits were correctly configured.

#### What happens:
Buckets do not get extracted from stirling generators but can be inserted with item conduits.

#### What you expected to happen:
Empty buckets to be extracted from the stirling generator and placed back in to the fluid tank to be refilled with lava and sent back to the generator as a full bucket of lava.

#### Steps to reproduce:

1. Place fluid tank
2. Fill with lava
3. Place Stirling generator
4. Place item conduit between tank and generator
5. Configure conduit to be insert/extract on tank and generator (always active)
6. Extract from tank on green, insert on brown
7. Vice versa on generator

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.169
- EnderCore: 1.10.2.0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

#### Your most recent log file where the issue was present: 

http://pastebin.com/MUykk7Zg
![2017-02-18_11 09 15](https://cloud.githubusercontent.com/assets/6676966/23094708/09efd3ec-f5cc-11e6-8142-3525225d1767.png)
![2017-02-18_11 09 17](https://cloud.githubusercontent.com/assets/6676966/23094707/09edc552-f5cc-11e6-9144-3381586cc72f.png)
![2017-02-18_11 09 22](https://cloud.githubusercontent.com/assets/6676966/23094710/09f12666-f5cc-11e6-99e5-e523ca806aa4.png)
![2017-02-18_11 09 38](https://cloud.githubusercontent.com/assets/6676966/23094709/09f089c2-f5cc-11e6-8139-9825e8d962ed.png)

**Comment by MatthiasMann** [comment]
How is the side of the Stirling Generator configured? Have you tried that with the Stirling and the Tank next to each other and the side of the Stirling configured for push/pull mode?
Last time tried both (via conduit and using push/pull) it worked - but that was a few month ago.

**Comment by aesguitar** [comment]
I haven't tried with the tank and generator touching, but this is just a demo build to illustrate the bug in a real build I was doing with 15 stirling generators with 16 buckets all done the same way. When I first encountered the bug, I did try changing the side settings on the generator but that didn't help. This kind of build was functional in 1.10 in the past.

**Comment by HenryLoenwind** [comment]
There's a special case for the bucket in the legacy inventory code that needs to be duplicated into the inventory capability code.

**Comment by aesguitar** [comment]
Bug exists with tank and generator touching.
![2017-02-18_11 29 07](https://cloud.githubusercontent.com/assets/6676966/23094811/9945df18-f5cd-11e6-9da3-9fa8431599e0.png)
![2017-02-18_11 29 21](https://cloud.githubusercontent.com/assets/6676966/23094812/9946563c-f5cd-11e6-8c60-e16249c5d059.png)
![2017-02-18_11 29 27](https://cloud.githubusercontent.com/assets/6676966/23094813/9948c26e-f5cd-11e6-94aa-8929faa172cc.png)
