### ISSUE TITLE
Can't extract items from Killer Joe

### ISSUE THREAD

**Issue by MakeLord95** [SleepyTrousers/EnderIO#4047]
#### Issue Description:
I can't extract weapons from Killer Joe using item conduits

#### What happens:
Weapons stay inside Killer Joe even when sides are configured

#### What you expected to happen:
Weapons to get pulled out of Killer Joe

#### Steps to reproduce:

1. Place down Killer Joe with any vanilla sword or The Ender inside
2. Set conduit to extract without redstone
3. Place down chest with conduit set to import
4. Weapon stays inside Killer Joe

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.169
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

#### Your most recent log file where the issue was present: 

http://pastebin.com/G4E6gLhm

**Comment by HenryLoenwind** [comment]
same reason as #4046
