### ISSUE TITLE
Dark helm covers too much of player skin

### ISSUE THREAD

**Issue by ShaunDreclin** [SleepyTrousers/EnderIO#4048]
#### Issue Description:
Just a nitpick I guess, but the helmet just looks bad. When I wear it, it looks like I've got a big robotic smiley face. Maybe add a keybind to uncover your face à la robocop?

See screenshot:
![screenshot 584](https://cloud.githubusercontent.com/assets/5851433/23132168/bad79e30-f75a-11e6-82ff-3945f8be2c3f.png)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.168
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

**Comment by Amaxter** [comment]
That's gotta be the worst texture I've ever seen.

**Comment by VT-14** [comment]
Sidenote: you can paint it (painting machine) with almost any block for a humorous effect.

Ender IO does add an invisible block to make it look like you aren't wearing the helmet.  It does still show the solar panel (if you have one) though.

**Comment by ShaunDreclin** [comment]
>Ender IO does add an invisible block to make it look like you aren't wearing the helmet.
Oh sweet didn't know about that, whats it called? Do I craft it with the helmet?

**Comment by HenryLoenwind** [comment]
Random idea: Have two textures for the helmet front, one that is more normal and shows the eyes, and the current one which is used when the Nightvision or Sound Locator upgraded is installed.

**Comment by VT-14** [comment]
@HenryLoenwind I like that idea.

Can we also have the Solar Panel either not be shown when painted, or toggle-able (like the glider wings)?  It's a nice upgrade, but looks a bit weird, especially when it's floating a few inches above your head when the helm is painted with the invisible block.

**Comment by mindforger** [comment]
but but but ... it's like an angelic ring above your head for using renewable energy *sob* .... just kidding, configurable would be nice if possible

**Comment by HenryLoenwind** [comment]
it works well if you have a full block as paint....

Two reasons it's always there: (a) It's renderer doesn't know anything about the helmet. (b) I couldn't find a good way to check if the paint model works with the panel. (c) how should it catch the sun if light goes through it?

**Comment by VT-14** [comment]
point C is why I suggested "...or toggle-able (like the glider wings)."  I'm thinking the possibility to turn the upgrade off and pull the whole panel off your head when not used.  This could be similar to the faceplate you suggested for night/sound vision.

**Comment by HenryLoenwind** [comment]
oh, duh ;)

**Comment by Fokson** [comment]
> Random idea: Have two textures for the helmet front, one that is more normal and shows the eyes, and the current one which is used when the Nightvision or Sound Locator upgraded is installed.
I would second this idea, but instead have the visor show when the night vision/sound locator is "active", rather than just "installed".  I'm enthralled with the imagery of hitting the keybind to turn on night vision and having the face plate slide down =D

**Comment by HenryLoenwind** [comment]
While I like the idea of the moving faceplate, we already have problems syncing the state of the glider and other upgrades to other players. Those need to be tackled first before I add another status.
