### ISSUE TITLE
Block layer 'breaking' is leaking (was: Crash at world load with Chisel update 0.0.8.12 (1.10.2))

### ISSUE THREAD

**Issue by ate0ate** [SleepyTrousers/EnderIO#4049]
After Chisel's recent update my world crashes upon startup. I initially reported this issue to tterrag there, but he says the problem is an issue with EnderIO and to report it here. Here is a link to the issue report over on the Chisel Github...
https://github.com/Chisel-Team/Chisel/issues/361

Upon loading my single player world, things briefly render before the screen turns black and hangs for several seconds before crashing with this...
http://pastebin.com/f3CfcGde

The versions of relevant files are:
forge: 12.18.3.2221
Endercore: 0.1.4.65
EnderIO: 3.1.170
Chisel 0.0.8.12

**Comment by HenryLoenwind** [comment]
Yeah, I see the offending code. Was added by tterrag...

**Comment by ate0ate** [comment]
Haha, that's ironic:) Thank you much for looking into it.

**Comment by HenryLoenwind** [comment]
Yeah, I don't usually tell who authored a bug, but this is funny;)))

**Comment by tterrag1098** [comment]
I had no doubt it was related to my fix for the breaking animation on conduits, since that's the only place we deal with the null layer at all. My changes must be leaking in to the painted renderer, I guess.

**Comment by HenryLoenwind** [comment]
Yes, list that says which layers to copy. I'll fix it tonight.

**Comment by ate0ate** [comment]
Works perfectly for me. Thanks again for fixing tterrag's code! ;) 🥇
