### ISSUE TITLE
[1.10.2] Capacitor Bank Issue

### ISSUE THREAD

**Issue by Elvarion** [SleepyTrousers/EnderIO#4051]
#### What happens:
Capacitor Bank In/Out gets set to 0 after a server restart (Chunks are not loaded)
This is happening every time the server restarts.

This is not an issue when only EnderIO is installed.
So must be a mod conflict in my modpack that is causing some issues. Also had some issues with the Refined Storage computer not reacting to redstone. Could be some chunk loading issue or something.
(Not a mod dev, so ive got no clue really :p)

#### Steps to reproduce:
1. Place Capacitor Bank
2. Restart Server
3. Check Bank, Input/Output is now at 0
...

#### Modpack (My own custom)
http://pastebin.com/7QwpstLv

____
#### Affected Versions (Do *not* use "latest"):
- EnderIO-1.10.2-3.1.170
- EnderCore-1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge-1.10.2-12.18.3.2185

#### Your most recent log file where the issue was present: 
Not sure exacly what you guys need, so posted the last files and did a server restart before posting them.
https://dl.dropboxusercontent.com/u/128571833/fml-server-1.log
https://dl.dropboxusercontent.com/u/128571833/fml-server-2.log
https://dl.dropboxusercontent.com/u/128571833/fml-server-3.log
https://dl.dropboxusercontent.com/u/128571833/fml-server-latest.log

**Comment by HenryLoenwind** [comment]
see #3763

**Comment by HenryLoenwind** [comment]
Just to be sure, it's only the IO limits that reset and always both of them together? So the side config and the RF storage doesn't get reset?

**Comment by Elvarion** [comment]
Both IO always reset together. Ive not checked to see if sides get reset or not since ive not needed to setup the sides as im using it right now. RF Storage is kept between restarts. Gonna try out and see if the sides reset between restarts.

Sure, give me a build and ill run some tests

**Comment by HenryLoenwind** [comment]
Thx, I'll make one tomorrow.

**Comment by Elvarion** [comment]
@HenryLoenwind Have you made this build yet? (Just so I havent been missing anything like downloading it from a special page that I dont know about xD)

**Comment by HenryLoenwind** [comment]
Sorry, got side-tracked by Real Life. I'll start right now, expect a version in about 2 hours.

**Comment by HenryLoenwind** [comment]
Ok, build is running: http://ci.tterrag.com/job/EnderIO-1.10/172/

There's a chance that this already fixes the problem. If not, set the config value `debugTraceCapLimitsExtremelyDetailed` (server and client) and see what the logfile says. (Note: Going from "-1" (meaning "use defaults") to the actual default value is normal.)

**Comment by Elvarion** [comment]
No problem, Ill run some tests tomorrow (its 23:00 here) and ive been away the whole day
Ill post any finds tomorrow

**Comment by Elvarion** [comment]
First tests seems good. 3 Restarts and going far away to unload the chunks and the Cap banks retained their I/O settings on all tests.
Ill play around with it some more but it seems to be fixed, Nice!

**Comment by HenryLoenwind** [comment]
Ok, what I changed was: When the GUI is opened, all buttons and text fields are initialized with the values from the TileEntity. Whenever a button changes, it triggers a network packet to the server with all the GUI data. In combination, opening the GUI sent 4 packets...which usually contained just the existing data. I removed those 4 packets.

**Comment by Elvarion** [comment]
Logged in today and noticed 1 cap bank had its I/O reset to 0. The other are just fine.
Enabled the debug but cant seem to replicate the issue now. Will keep the debug enabled for awhile and see if I can catch when the issue happens

**Comment by HenryLoenwind** [comment]
Thx, for doing that. I'm quite sure I eliminated all instances of resetting the value with the GUI, but the resetting at other times, e.g. server start, is still unsolved.

**Comment by Elvarion** [comment]
Have not seen any of the Cap banks revert back to 0 I/O. So it feels like its fixed. Or that I doesn't want to show itself while the Debugging is enabled =D
Thanks for all the help Henry :)

**Comment by HenryLoenwind** [comment]
no, no, I have to thank you. Without people who can reproduce errors and who are willing to run debug versions, we'd never be able to fix all bugs.
