### ISSUE TITLE
Suggestion: use player's name as fakePlayer name for the killer Joe

### ISSUE THREAD

**Issue by gd71** [SleepyTrousers/EnderIO#4052]
#### Improvment proposal:
As discussed in the Minecolonies repo to prevent grief by other users in a protected area.
Minecolonies/minecolonies#645
It should be nice if the killerJoe fakePlayer could support the placers name in place of the generic one [EioKillera]

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.145_beta
- EnderCore:1.10.2-0.4.1.61-beta
- Minecraft: 1.10.2
- Forge:

Thanks for your feedback!

**Comment by HenryLoenwind** [comment]
I answered to the original ticket. Also, you are using an ancient version.

**Comment by gd71** [comment]
Understood, thanks for your feedback!

**Comment by Raycoms** [comment]
Also added an additional answer to the original ticket.
