### ISSUE TITLE
Enchanter recipes using wrong XP costs

### ISSUE THREAD

**Issue by Alan19** [SleepyTrousers/EnderIO#4054]
#### Issue Description:
When two enchanter recipes with the same enchant is added to the user xml file, the enchanter uses the xp cost of one of the recipes for both recipes

#### What happens:
An enchanter recipe that gave aqua affinity using aquarium blend costed 4 levels but it used the XP cost of the aqua affinity recipe which uses 8 levels. This also happens with other recipes that have the same enchant but different inputs and XP costs.

#### What you expected to happen:
The aquarium blend recipe should only use 4 levels and the lily pad recipe should use 8.

#### Steps to reproduce:

1.Use this custom user enchanter xml file
[https://github.com/belathus/Wanderlust-Renewed/blob/387943d601c4cc0ad69f7da03cfb3e672105f9ca/config/enderio/EnchanterRecipes_User.xml](url)
2.Check JEIs enchanter recipe costs
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.170
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2221

#### Your most recent log file where the issue was present: 

[https://gist.github.com/Alan19/d4529185446313a6f361a4dcf1ad6a1f](url)

**Comment by HenryLoenwind** [comment]
Supporting multiple recipes with the same name would be a new feature. Not detecting dupes while parsing the user recipe file would be a bug.
