### ISSUE TITLE
Mod Needs Other Mods

### ISSUE THREAD

**Issue by SuperSwinub** [SleepyTrousers/EnderIO#4055]
Well I Launched Ender io And the first thing to pop up is you need to get ender core so i do and i launched again and this time it says i need forge and there are no mods called forge and i am using forge to run these mods so whats my problem

**Comment by cloakable** [comment]
Does the version of forge you're using meet the minimum version needed?

**Comment by HenryLoenwind** [comment]
That message is from Forge, not us. https://github.com/MinecraftForge/MinecraftForge
