### ISSUE TITLE
Custom sag mill recipes not working

### ISSUE THREAD

**Issue by zwya** [SleepyTrousers/EnderIO#4056]
#### Issue Description:
Adding custom recipes to SAGMillRecipes_User.xml is not working.

#### What happens:
Adding any recipe to the file is not working even the default commented ones that came with config folder.

#### What you expected to happen:
Custom recipes should be added to the Sag Mill.

#### Steps to reproduce:

1. Use this config file: http://pastebin.com/4BmxZiux
2. Try the recipe.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.1.171
- EnderCore:1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge:1.10.2-12.18.3.2234

#### Your most recent log file where the issue was present: 
http://pastebin.com/HCYC79AS

#### Notes
My suspicion is that the user config isn't being loaded. There are two reasons for this. First, I am using notepad++ with the config file and whenever I restart my game. notepad++ warns me that all my config files should be reloaded because the game has modified them except SAGMillRecipes_User.xml. Second, I tried adding random crap between SAGMillRecipes /SAGMillRecipes just to force the recipeparser to output any errors but I didn't find any errors in the log.

**Comment by HenryLoenwind** [comment]
People were complaining about too many log outputs, so you need to crank up the logging to level DEBUG to see them nowadays.

You're giving an input material that doesn't exist.
