### ISSUE TITLE
hopefully fixable

### ISSUE THREAD

**Issue by Tenchu98** [SleepyTrousers/EnderIO#4058]
I am trying to use the farmer with hatcheries fertilized soil, but it won't till the soil. The dev for hatchery said it is something that would have to be resolved from your end. 

I am loving the mod as a whole, and couldn't manage my base without it, so was hoping this Integration could be fixed.

**Comment by HenryLoenwind** [comment]
At least link to the original ticket...

**Comment by Tenchu98** [comment]
What original ticket?

**Comment by bookerthegeek** [comment]
@Tenchu98 you said you talked to three other mod dev, usually that would have been in a ticket somewhere. He is asking for a link to that conversation

**Comment by ate0ate** [comment]
I was perusing the Hatchery issues and found this...
https://github.com/GenDeathrow/Hatchery/issues/72

Looks to be the original conversation. Not much here other than the dev isn't specifically using minecraft dirt as the tillable soil for his mod so ender io farming machines won't detect Hatchery soil.

**Comment by Tenchu98** [comment]
Sorry, didn't know you meant the one from hatchery.

**Comment by HenryLoenwind** [comment]
Oops, did I forget to write down my preliminary findings here? Sorry, I thought I did.

So, what happens here is that Minecraft has no generic mechanism for using a hoe or creating farmland. That means that we are not able to programmatically detect if an item is a hoe, detect if a block can be tilled, into which other block a block should be tilled, or how to do that. So we replicated the vanilla hoe's implementation of tilling into the Farming Station and have a list of hoes in the config file.

I'll have a look into adding the same kind of configuration for modded dirt-farmland combinations.

**Comment by Tenchu98** [comment]
That would be awesome

**Comment by bookerthegeek** [comment]
Would a simple IMC option so other mods could tell you that:
* This block can be hoed, and then the block it turns into
* This item can till blocks that are able to be hoed

This way other mods could add it them self, and you you don't have to maintain a massive list.

**Comment by Tenchu98** [comment]
Maybe as a temporary solution there could be a json file to specify tillable, harvestable, and tools that can be used with the farm station?
