### ISSUE TITLE
[1.10.2] Redstone conduits not updating through solid blocks

### ISSUE THREAD

**Issue by XFactHD** [SleepyTrousers/EnderIO#4059]
#### Issue Description:
Sending a redstone signal through a solid block to disconnect two redstone networks from each other leads to the receiving conduit not updating its on/off state until it is disconnected and reconnected with the wrench. This is not only a graphical glitch.
Example configuration:
![2017-02-24_21 12 37](https://cloud.githubusercontent.com/assets/11262040/23319618/9ee77aee-fad7-11e6-9076-d9dd32104c32.png)

#### Steps to reproduce:
1. Place any solid block
2. Place a redstone conduit on each side, force a connection to the solid block and set one of them to strong signal
3. Activate the conduit set to strong signal with a lever
4. Right click the receiving conduit with a wrench on any side but the side pointing towards to solid block, now the conduit will update

____
#### Affected Versions:
- EnderIO: 1.10.2-3.1.171
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2221

**Comment by HenryLoenwind** [comment]
Conduits don't react to redstone notifications from other conduits to avoid endless loops.

**Comment by XFactHD** [comment]
That sounds reasonable. Is there any other way to disconnect two networks from each other like that?

**Comment by MatthiasMann** [comment]
Put a redstone repeater in between?

**Comment by XFactHD** [comment]
Possible, but I need something disguisable.

**Comment by HenryLoenwind** [comment]
Use two different channels and place the connection block somewhere else?

BTW: I haven't closed this ticket because this is something I'd be happy to change if I can find a solution that doesn't re-introduce the bug this is fixing...

**Comment by XFactHD** [comment]
I will have to find space for that but yeah, it seems to be the only possibility for now.

**Comment by legodude17** [comment]
Shouldn't there be a way to force the conduit to get a redstone input from a side?

**Comment by Alex-hawks** [comment]
Maybe something like MFR's PRC?
