### ISSUE TITLE
EnderIO faces are relative to world coördinates, and not machine faces.

### ISSUE THREAD

**Issue by KiddieD** [SleepyTrousers/EnderIO#4061]
#### Issue Description:
This issue DOES happen within a modpack, but I believe the other mods are completely irrelevant to this bug and/or feature problem.

#### What happens:
When picking up an already configured machine, the machine retains its configuration relative to N/E/S/W rather than machine faces. This makes it so that if I turn the previously north face to south, the previously south configured output is now on the 'front' and no longer the 'side'.

#### What you expected to happen:
The faces are supposed to stay relative to the machine's front's defined directions Eg: Side Left, Side Right, Bottom, Etc.

#### Steps to reproduce:
Here's a video of the issue:
https://youtu.be/9-0-Ec-tbwY

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.145_beta
- EnderCore: 1.10.2-0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 
---Forge Modloader: 8.4.99.99
---Minecraft Forge: 12.18.3.2185
---Minecraft Coder Pack: 9.19

#### Your most recent log file where the issue was present: 
I doubt this might be necessary, but here's the current log. Minecraft was NOT closed.
https://paste.ee/p/79Voh

Thanks for your attention.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.
