### ISSUE TITLE
Infinite soulbound

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [SleepyTrousers/EnderIO#4062]
Its not a bug or something is more like a issue, if you have the enchanted book with soulbound you can enchant a lot of items in one row, and with this you can have even more soulbound in the items, (if you have a Disenchanting machine like evilcraft and draconic ones, you can disenchant the items that you have soulbound and put it again in other items. and you can do it forever if you have xp (its cost 1 or 2 levels if to enchant all the items).

**Comment by HenryLoenwind** [comment]
Applying an enchanted book in completely vanilla code, we are not involved in that at all.
