### ISSUE TITLE
about the Rf conduits

### ISSUE THREAD

**Issue by O-Barbaro-Desenhista** [SleepyTrousers/EnderIO#4063]
you gonna do more powerful conduits ? is just a ask.

**Comment by HenryLoenwind** [comment]
Why do you need to transfer more than 42,949,672,960 RF per second?

**Comment by O-Barbaro-Desenhista** [comment]
where I can make one of those? , I'm just asking because your conduits are the best to make energy and redstone work together.

**Comment by MatthiasMann** [comment]
@O-Barbaro-Desenhista there are 3 tiers of energy conduits - which are fully configurable in EnderIO's config file.
If you make a pack which has such insane energy generation/consumption then you need to adjust the conduit configuration to match your pack.
If you play an existing pack then you need to complain to the pack author about that.
