### ISSUE TITLE
[Request] Redstone Conduit Circuit Breaker

### ISSUE THREAD

**Issue by Nuinethir** [SleepyTrousers/EnderIO#4064]
I would love to see a block that connects to the Redstone Conduit that provides a signal output to any color, acting like a circuit breaker panel. This would eliminate the need for using multiple buttons/levers to control multiple devices which can take up a large space.

Features:
- A GUI with a 2x8 or 4x4 grid of switches (aka levers)
- Each switch has a channel color that corresponds to a Redstone Conduit channel color
- Each switch can be named so that a device's color doesn't have to be memorized by the player
- Turning a Redstone Conduit channel on/off is as simple as entering the GUI and clicking a switch

For example:

Red - "Smelter"
Green - "Farming Station"
Blue - "Powered Spawner A"
Black - "Powered Spawner B"

This would then work exactly like a circuit breaker (especially as they can be coupled with other EIO conduits) to turn machines/blocks on/off.

**Comment by HenryLoenwind** [comment]
http://ideas.theideawall.com/EnderIO/
