### ISSUE TITLE
Suggestion: "Remote Inventory Interface" block

### ISSUE THREAD

**Issue by StarkRG** [SleepyTrousers/EnderIO#4067]
I'm really liking playing with the Ender IO inventory system, however I've discovered a flaw: there's no machine-/other-mod-accessible way to extract items out of the system. My proposal is a block with no GUI that exposes the inventory system as if its contents were contained within the block. An extra feature could be a filter slot enabling the block to expose only those items that match the filter. You could think of it as a machine variant of the Inventory Panel.

I would say you should make the remote awareness upgrade ignore this new block so you don't end up with a feedback loop.

Bonus suggestion: the Inventory Sensor block should have the ability to ignore NBT, damage, and/or metadata.

**Comment by AnrDaemon** [comment]
Connectors do that. Or I don't understand your issue.

**Comment by HenryLoenwind** [comment]
wrong tracker. http://ideas.theideawall.com/EnderIO

**Comment by StarkRG** [comment]
Why is that page not listed on the website? Meanwhile there are other feature requests and suggestions on this tracker and the website's "suggestion" button leads here.

And, no, connectors don't expose the entire remote inventory system to a block. You can't attach an Integrated Dynamics inventory reader to an item conduit and have it read the contents of the whole system. Applied Energistics has the ME Interface that functions this way.

**Comment by HenryLoenwind** [comment]
because the only person who has access to the website is away. And I have changed every other link but those on enderio.com that I'm aware of. I I missed one, please tell me where.
