### ISSUE TITLE
Suggestion on Vacuum chest

### ISSUE THREAD

**Issue by GldnSabre74** [SleepyTrousers/EnderIO#4070]
Allow the use of advanced filters in them. 

Thank you.

**Comment by HenryLoenwind** [comment]
Really? There's one single link left that doesn't yell at you to take your suggestions to the suggestion tracker and 5 people a day use that one? @nentify

**Comment by GldnSabre74** [comment]
Came in from the github issues pages not your website and I did not see a suggestion link because I did not see one. on the github page. this is the link is usedhttps://github.com/SleepyTrousers/EnderIO/issues

**Comment by HenryLoenwind** [comment]
https://github.com/SleepyTrousers/EnderIO/wiki#feature-requests

The menu at the top is fixed, we cannot edit it (other than e.g. disable "wiki" by disabling that functionality).
