### ISSUE TITLE
Ghost Vacuum Chest [Bug] [1.10.2]

### ISSUE THREAD

**Issue by Mercenary4Hire** [SleepyTrousers/EnderIO#4071]
#### Issue Description:
On a Server, I administrate a Player had a 100% vanilla blaze grinder built with 1 Exception, he had placed a Vacuum chest at the bottom of it to collect the drops. At 1 point he decided to break the vacuum chest. When he broke the chest, it never dropped or showed in his inventory. He also at that point was unable to get drops from blazes, at that point he had me come to investigate the problem. 

I search the area and find no reason his blazes were not dropping stuff, till I had the Idea of throwing junk out of my inventory and fix it getting sucked into a piece of vanilla netherrack which was placed in the spot of his old vacuum chest. I searched the entire area made sure there was no hidden vacuum chest. I then had the idea to throw ~20 stacks of netherrack into the spot it was getting sucked up till it stopped. I have placed and removed blocks from the exact spot his chest was/ where items were getting sucked too, so it wasn't a simple matter of a block getting broken client side, but not server side.

This event did take place inside a FTB utilities claim. I have been unable to repeat this bug, nor do I have the faintest clue on what happened. Nor do I know if FTB led to this bug being created.

#### What you expected to happen:
You break a vacuum chest and you pick it up, and the area no longer tries to vacuum up items.

____
#### Affected Versions

- EnderIO: 1.10.2-3.1.157
- EnderCore: 1.10.2-0.4.1.62-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Other Mods that Might caused the problem FTBLib-1.10.2-3.2.3 & FTBUtilities-1.10.2-3.2.4

**Comment by HenryLoenwind** [comment]
I see what's happening. However, Ender IO is not involved here, that is pure Mojang code acting here. So this is either a vanilla bug or some other mod is messing with the world state (yes, FTBUtils is a good candidate). Ender IO certainly is not changing the way the world state is manipulated when a block is broken (and we won't start doing so, not even to make sure the state is consistent...)
