### ISSUE TITLE
Draconic Evolution's Flux Capacitors don't charge any Ender IO items

### ISSUE THREAD

**Issue by slaugaus** [SleepyTrousers/EnderIO#4072]
#### Issue Description:
The Wyvern, Draconic, and Creative Flux Capacitors do not charge any Ender IO items that can hold RF. This probably isn't your fault, but I'm posting here just in case it is.

#### What happens:
In "Charge Armor and Held Items" mode, all 3 of the Flux Capacitors don't charge Dark Steel Armor in the armor slots or any EIO item in any inventory slot (even when held).  
Capacitor Banks will charge DE's items, though.

#### What you expected to happen:
The capacitor would charge EIO items like an Actually Additions battery (for example) would.

#### Steps to reproduce:

1. Obtain a charged Draconic/Wyvern/Creative Flux Capacitor and any powered Ender IO item.
2. Shift-right-click the flux capacitor to cycle modes (charge items, charge armor, charge both)
3. Observe power bar on the EIO item.

____
#### Affected Versions:

- EnderIO: 3.1.171
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Brandon's Core: 2.1.4.92
- Draconic Evolution: 2.0.8.177

#### Your most recent log file where the issue was present: 

Probably won't help.
http://pastebin.com/7aszZRZB

**Comment by MatthiasMann** [comment]
EnderIO items only support forge energy or Tesla if installed.

**Comment by HenryLoenwind** [comment]
as Matthisas said.
