### ISSUE TITLE
Custom recipes Sagmill

### ISSUE THREAD

**Issue by wandersonbraz** [SleepyTrousers/EnderIO#4074]
Hello everybody good night
I am playing with the enderIO through FTB infinity lite 1.10.2 and I am having problems regarding silicon production since with sand it is 50% chance so I decided to add a custom recipe in the mod I went to the file following the instructions but in my game Does not work the custom recipe in any way I took my log and in the line of custom recipes the error below appears.
[20:24:03] [Client thread/ERROR] [EnderIO]: Could not load user defined recipes from file: SAGMillRecipes_User.xml

My XML
http://pastebin.com/5H4kY7V8
How can I fix this?

Thank you for your help.`

**Comment by wandersonbraz** [comment]
//<SAGMillRecipes>

  <grindingBalls>
    <grindingBall id="Flint" grindingMultiplier="1.5" chanceMultiplier="3.0" powerMultiplier="1.0" durationRF="500000" >
      <itemStack oreDictionary="itemFlint" />
    </grindingBall>

  <recipeGroup name="EnderIO" > 
    
    <recipe name="Silicon" energyCost="200" >
      <input>
        <itemStack oreDictionary="sand" />
      </input>
      <output>
        <itemStack modID="EnderIO" itemName="itemMaterial" number="1" itemMeta="0" chance="1" />
      </output>
    </recipe>

</SAGMillRecipes>//

**Comment by HenryLoenwind** [comment]
use an editor that has xml support, e.g. http://www.tutorialspoint.com/online_xml_editor.htm

**Comment by Lgk2** [comment]
I'm pretty sure the <grindingBalls> recipe should be within a recipegroup, either add one or move it to the group EnderIO.
