### ISSUE TITLE
[1.10.2] Thermal Expansion Integration Issues

### ISSUE THREAD

**Issue by oitsjustjose** [SleepyTrousers/EnderIO#4075]
#### Issue Description:
When using Thermal Expansion alongside EnderIO & Tinkers' Construct, Thermal Expansion's use of the destabilized redstone texture gets messed up.

It's EnderIO's integration with Tinkers' Construct (confirmed this by removing Tinkers' and keeping EnderIO, and keeping Tinkers' and removing EnderIO - both times reverted this bug).

#### What happens:
With EnderIO and EnderCore:
![2017-03-05_07 46 38](https://cloud.githubusercontent.com/assets/3887324/23587355/309573be-0178-11e7-92af-c9d04920572f.png)

As you can see, the texture inside is not even the right texture, and even if it was it is not colorized.

#### What you expected to happen:
Without EnderIO and EnderCore:
![2017-03-05_07 51 10](https://cloud.githubusercontent.com/assets/3887324/23587375/86b30f9a-0178-11e7-8f36-adbad65767b6.png)

Without Tinkers' Construct:
![2017-03-05_07 53 26](https://cloud.githubusercontent.com/assets/3887324/23587400/f69e1e30-0178-11e7-8288-58ef1eba5fac.png)

Like I mentioned, the texture being used is a completely different one (water style instead of lava style), and is properly colored (likely because Tinkers' fluids run heavily on the colorizer where Thermal Expansions aren't post-colorized at all).

#### Steps to reproduce:

1. Install Thermal Expansion 2.0.0.64 with its dependencies
2. Install EnderIO
3. Install Tinkers' Construct
4. Let the installation of both trigger EnderIO's extra fluid initialization
5. View energy conduit / energy cell

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.156 through 3.1.172 (did not test earlier versions)
- EnderCore: 0.4.1.64 and 0.4.1.65
- Minecraft: 1.10.2
- Forge: 12.18.3.2239

#### Your most recent log file where the issue was present: 

[Copied from latest run in an affected pack](http://puu.sh/uv5Ho/5f23080eff.txt)

Let me know if I can help with anything else! Fortunately it's not a game-shattering bug :)

**Comment by HenryLoenwind** [comment]
Does your logfile have the line "Thermal Foundation fluid 'redstone' is unexpectedly missing. Late registering our own."?

**Comment by oitsjustjose** [comment]
No it does not.

Just updated the original post with a log upload.

**Comment by Angelnightwing** [comment]
```
[08:16:48] [Client thread/WARN] [FML]: A mod has attempted to assign Block Block{null} to the Fluid 'redstone' but this Fluid has already been linked to the Block Block{enderio:fluidRedstone}. You may have duplicate Fluid Blocks as a result. It *may* be possible to configure your mods to avoid this.
[08:16:48] [Client thread/WARN] [FML]: A mod has attempted to assign Block Block{null} to the Fluid 'glowstone' but this Fluid has already been linked to the Block Block{enderio:fluidGlowstone}. You may have duplicate Fluid Blocks as a result. It *may* be possible to configure your mods to avoid this.
[08:16:48] [Client thread/WARN] [FML]: A mod has attempted to assign Block Block{null} to the Fluid 'ender' but this Fluid has already been linked to the Block Block{enderio:fluidEnder}. You may have duplicate Fluid Blocks as a result. It *may* be possible to configure your mods to avoid this.
```

Maybe this?

**Comment by oitsjustjose** [comment]
Ah, totally missed that line, but yeah - I did gather that the problem was partially caused by duplicated registration. I just can't tell (looking at the source code) why the registration is still happening when it *should* be disabled I would think... at least if the Loader.isModLoaded() check is working.

**Comment by HenryLoenwind** [comment]
see also https://github.com/CoFH/Feedback/issues/15

**Comment by oitsjustjose** [comment]
Confirmed - latest update fixed it. Thanks!!

**Comment by HenryLoenwind** [comment]
Tagged "Bug in other software" for TE being unable to correctly render color-based fluids. Tagged "Code complete" for the bug that we didn't detect TF correctly.
