### ISSUE TITLE
In/Out connection Issues

### ISSUE THREAD

**Issue by mikeskey** [SleepyTrousers/EnderIO#4077]
#### Issue Description:
When using the item conduits and setting them to the in/out setting they do not allow items to pass through in either direction

#### What happens:
For instance when connecting the conduits to a canola farm from actually additions or a forestry farm and attempting to use the in/out setting for instance to place the harvested canola into a storage drawer on green and then extract it on red to send to the canola press for processing. When making the in/out connection after setting everything up correctly items stop flowing into the storage drawer and do not continue on to the press. The only way to solve this issue is to use two connections to the same inventory, one to place items in and the other to take them back out and send them on. I have used ender IO for years so I know exactly how they work and I have no doubt I am setting them up correctly just as I have done for a long time.

#### Affected Versions (Do *not* use "latest"):
Pack-FTB Presents Direwolf20 1.10
- EnderIO: 1.10.2-3.1.156
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2239

**Comment by MatthiasMann** [comment]
You are on an outdated version.

I have the following setup in my world: AA farmer conduit(extract only: green, always extract) -> storage drawer conduit(insert: green, priority -1, extract: green, always extract) -> canola press conduit(insert: green, priority 0)
And it works as expected using EIO 172, AA 98
