### ISSUE TITLE
[Minor] TE Crescent Hammer support

### ISSUE THREAD

**Issue by 016Nojr** [SleepyTrousers/EnderIO#4079]
Make the Crescent Hammer (Thermal Expansion) able to wrench (Rotate and break) EnderIO machines/conduits

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
I just remembered: Rotating is not a function of the block but the wrench. So for that you have to open a suggestion with https://github.com/CoFH/Feedback
