### ISSUE TITLE
Dense ME Conduit's recipe is wrong

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4084]
#### Issue Description:
Recipe outputs 8 conduits instead of one, effectively turning 4 ME Conduits into 8 Dense. The recipe should output 1, following the Applied Energistics' Logic.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2

**Comment by NillerMedDild** [comment]
That issue has come up again in Minecraft 1.12.2, `EnderIO-1.12.2-5.0.44` - 4 Ender IO ME Conduits can be made into 4 Ender IO Dense Me Conduits. The ratio is 4 Regular to 1 Dense normally.

https://cdn.discordapp.com/attachments/589526583648190465/589569043267190784/unknown.png

**Comment by HenryLoenwind** [comment]
mmmmh... https://github.com/SleepyTrousers/EnderIO/commit/4a4c716555eab367a52793e7ce05cb791018d5fa#diff-38c0adfefbc4985b7d21a31241699932

@EpicSquid any reason you went for different amounts than the original recipes? (see commit from Mar 26, 2017 above)
