### ISSUE TITLE
EnderIO crashes if I do a thing

### ISSUE THREAD

**Issue by SoniEx2** [SleepyTrousers/EnderIO#4085]
#### Issue Description:

I tried (roughly) the following code:

```
if (tileentity.getClass().getName().startswith("enderio")) {
    World oldWorld = tileentity.worldObj;
    tileentity.worldObj = new FakeWorld() {
        public TileEntity getTileEntity(BlockPos bp) {
            return new DummyTileEntity(itemStack);
        }
    };
    tileentity.update();
    tileentity.worldObj = oldWorld;
}
```

and it crashed.

#### What happens:

It crashes.

#### What you expected to happen:

Power to go into my seeds.

#### Steps to reproduce:

1. Uh. Write a mod that does the above? I'm not gonna publish this code because IT CRASHES.

____
#### Affected Versions (Do *not* use "latest"):

No, seriously, can we just get PULL? This is getting kinda ridiculous, isn't it?

**Comment by tterrag1098** [comment]
Use broken code get broken results. We just so happen to explicitly prevent hacky crap like this, but in any mod it would eventually fail, just less obviously so. Your 3 strikes are up.
