### ISSUE TITLE
Way Too Many Overloaded Recipes!!!

### ISSUE THREAD

**Issue by ArkavianX** [SleepyTrousers/EnderIO#4086]
#### Issue Description:
This mod is very common among many mod packs, and I strongly suspect this suggest/psuedobug would be best from the source of EnderIO as the issue is the Alloy Smelter is being overwhelmed with too many recipes and similar materials from compatible mods. 

#### What happens:
In some packs it is to the point just putting in vanilla iron alone ends up smelted into other stuff before getting to any of the Ender IO alloys. Players have to add materials in a specific frustrating sequence to get the right product. 

#### What you expected to happen: 
EnderIO:Alloy Smelter already has a(n) furnace/alloy mode option, but there seriously needs a mod-selection-mode, that specifically allows only a certain mod for this particular alloy smelter(s).

#### Steps to reproduce:

1.  Skyfactory 3
2.  Misc Curse/Technic/Public Packs
3.  Custom
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: As a Feature Request: All
- EnderCore: N/A
- Minecraft: 1.7.10
- Forge: Whatever Curse currently uses.

#### Your most recent log file where the issue was present: 

N/A

**Comment by MatthiasMann** [comment]
This would be very difficult - and even more confusing for players. The would need to know which mod an item belongs to, select it and then add the items into the smelter.

The real issue at hand is that these mod packs (or the mods within) add smelting recipes or alloy recipes which conflict with each other or with the standard EnderIO recipes.

The real solution would be to have a mod specific element added in the recipes to avoid conflicts (eg like EnderIO conduit binder vs just smelting clay) - then it could also be automated.

**Comment by HenryLoenwind** [comment]
Neither alloy smelter recipes nor vanilla furnace recipes carry information to which mod they belong.

However, if there a recipe conflicts that's a sign that the modpack maker didn't do their job. Which may be because there's no way of finding out but manually comparing all recipes in JEI. I'll look into adding a recipe conflict checker.

**Comment by codewarrior0** [comment]
If you want a concrete example, SkyFactory 3 adds a recipe for smelting Iron Ingots into Refined Storage Basic Processors. This isn't a recipe conflict, it's just a consequence of the Alloy Smelter's "Both Furnace and Alloys" mode causing it to perform the Furnace recipe.

I'd suggest making the Alloy Smelter be in "Alloys Only" mode when first placed, but that doesn't work so well for EnderIO itself since the Smelter is also its only electric furnace.

**Comment by ArkavianX** [comment]
I figured it a tough call where to go/to do, but yea the poor smelter is being tortured in SF3 but nearly as bad as several packs I've played/compiled. As for the confusion, I would see the sequence required for a recipe is confusing enough vs knowing which mod the recipe comes from. NEI helps greatly with this, as could some minor tweaking to the recipe guides (what comes up when clicking recipes not books) 

I tried making energetic alloy, and ran into the Refined Storage Processors as soon as I put in the gold ingots. As long as I put in redstone or glowstone first, it was fine. Making Steel, ran into the issue twice due to 4:1 powdered coal:iron ingot and I ended up with a lot of basic processors as stated above.

**Comment by codewarrior0** [comment]
> As for the confusion, I would see the sequence required

Instead, have you tried switching the smelter to Alloys Only mode?

**Comment by ArkavianX** [comment]
I thought I had, just retried with a lot more material, and it seems to help as far as single item smelting (iron to processors etc) vs multi item.

**Comment by ArkavianX** [comment]
LoL, ran into the issue again with "Quite Clear Glass" vs "Vanilla Glass" 

Furnace Mode made vanilla, 
Alloy Mode did nothing.

**Comment by VT-14** [comment]
+ArkavianX  I think Quite Clear Glass was changed to use Vanilla Glass a while ago.  Sand in Alloy Mode shouldn't do anything unless a modpack adds something again.


For this modpack issue, I would suggest one of two things on Ender IO's side:
A) If an item can be used in both an alloy and furnace recipe, then an Alloy Smelter in "Both" mode will not process the item until the intended recipe is determined (either adding the rest of the ingredients to the alloy, or by selecting a specific operation mode).  When one of these items is in the Smelter alone, the GUI should give some indication of the problem and point the user to the mode switching button.  I would say an "X" over the progress bar with an arrow towards the mode button would be simple enough, possible with a tool tip explaining that a recipe conflict is detected.

B) A config option to disable the "both" option so modpacks can choose to keep furnace recipes and alloy recipes completely separate.

**Comment by ArkavianX** [comment]
Yea apparently i didn't wait long enough for the furnace mode to do its job, something cooked way too fast in it at the time and I didn't notice any benefit. Appears to be helping a lot now.
