### ISSUE TITLE
[1.10.2]Conduits are completely broken

### ISSUE THREAD

**Issue by Yoghurt4C** [SleepyTrousers/EnderIO#4087]
#### Issue Description:
I've been having this peculiar rendering issue with conduits since probably 3.1.164 (persists through 3.1.173) , and it's somewhat gamebreaking. _seems to only happen on 1.8_11 java, which opens a possibility of this issue being invalid_

#### What happens:
https://imgur.com/a/KLDZ0
-The conduits render only on when you place another conduit that connects to them (resets back to transparency on chunk unload or relog)
-Invisible conduits "corrupt" chunks they're located in, making certain things (for example, storage drawers labels or c&b bit blocks) not render

#### What you expected to happen:
for things to just work

#### Steps to reproduce:

1. get jdk 1.8_11
2. launch the instance through it
3. place conduits
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.173
- EnderCore: 0.4.1.65b
- Minecraft: 1.10.2
- Forge: 2254

#### Your most recent log file where the issue was present: 

http://pastebin.com/BKp8EcnL

**Comment by MatthiasMann** [comment]
Java 1.8_11 is terrible out dated - just from the security point of view you should update it.

**Comment by Yoghurt4C** [comment]
don't bully

**Comment by MatthiasMann** [comment]
Wtf?

**Comment by HenryLoenwind** [comment]
But yes, if you are using Java 8, use the latest one. I only fixed this because we still support Java 7 as there are some devices that cannot be easily upgraded to 8.
