### ISSUE TITLE
[Qustion/Suggestion] Liquid XP -> Bottle O' Enchanting

### ISSUE THREAD

**Issue by chimericdream** [SleepyTrousers/EnderIO#4088]
I'm not sure if this is possible already in EnderIO, but thought I would post here as a suggestion in case it isn't. It'd be nice to be able to right-click a tank containing liquid XP while holding an empty bottle. If there is enough XP in the tank, a small amount is drained and the bottle becomes a bottle o' enchanting. I don't know how much XP is stored in the vanilla BoE, but I'd guess this could be configurable so people could make it easier or harder to craft based on their goals or play style.

**Comment by HenryLoenwind** [comment]
The amount a bottle gives is random---that's why we don't do that already.

**Comment by chimericdream** [comment]
That makes sense. Is there a known max amount that a bottle can give? Maybe the manual crafting costs that much liquid XP to create a bottle, and you run the risk of getting back less XP from the bottle than it cost to make. Should help with balance, since there wouldn't be a potential for easy XP dupe.

(I can see it now... autonomous activator uses empty bottles on tank -> mechanical user breaks enchanted bottles -> xp vacuum grabs orbs for obelisk -> push liquid to tank -> rinse & repeat)

In my case, I have an obelisk attached to an XP vacuum near a mob grinder. So for me, even if there is a net loss when converting from liquid to bottle, it's an overall gain in terms of effort.

**Comment by HenryLoenwind** [comment]
One bottle gives 3-11 XP, which corresponds to 60-220 mB of liquid XP.

BTW, what do you use those bottles for?

**Comment by chimericdream** [comment]
In the pack I play on there are a handful of mods that use them in crafting recipes. I don't have the game open at the moment, so I can't remember specifically which items/mods.

**Comment by HenryLoenwind** [comment]
Interesting. The last time I saw them in crafting recipes it was in a modpack where you got them from the questing book. They were used a "gate" items... ;)

**Comment by VT-14** [comment]
I've seen them in a few recipes, but typically with things that are 'hard to get."  Feeding a bunch of Emeralds to any Cleric Villager (purple coat) is generally a reasonable difficulty for those items.

For reference, I'm thinking of things like Extra Utilities 2's new (and questionably valid due to Tema's reputation) recipe for the Law Sword; which also requires something like 8 Dragon Eggs.  (Does EU2 even add a way to get more than 1 Dragon Egg?)

If a mod decides to use Bottles o' Enchanting as something common, then I would say that it's up to that mod to add an easier way to get them.

**Comment by HenryLoenwind** [comment]
Yes, I am also a bit afraid to upset other mods' balance by making an easy way to get those bottles if they are used in recipes. That was the reason for me asking...I was contemplating adding our own bottles that looked and behaved the same way but had a fixed amount of XP. They would work if it was about the vanilla aspect (i.e. throwing them), but not with crafting.

**Comment by legodude17** [comment]
Like "Bottle of XP"? Sounds like a good idea, you could make some pretty cool XP showers. 😄

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
