### ISSUE TITLE
Farm Station fails to harvest entire mushroom

### ISSUE THREAD

**Issue by Cobra1117** [SleepyTrousers/EnderIO#4089]
#### Issue Description:
In a farming station, if the axe breaks before a large mushroom is entirely harvested, the remaining mushroom is left floating in the air. Because of the way that mushrooms grow (when bone mealed), this will often prevent additional mushrooms from growing. Ultimately this results in the farm stalling and wasting bonemeal.

#### What happens:
See above.

#### What you expected to happen:
Farming station should pick up where it left off after replacing axe. Alternatively, farming station could scan for harvestables above ground level (although this could cause unexpected/undesired side effects).

#### Steps to reproduce:
1. Set up farming station
2. Add mushrooms, bonemeal, and wooden axe
3. Wait for axe to break

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.173
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2239

#### Your most recent log file where the issue was present: 
N/A.

**Comment by HenryLoenwind** [comment]
Nope, server owners would be very upset if we'd start scanning the whole area for left-over blocks...

**Comment by Cobra1117** [comment]
That makes sense. Is it possible for the farming station to store the location of the last block when the tool broke, and then only check the next logical block when the tool is replaced?

**Comment by Cobra1117** [comment]
Here's a screenshot of what happens, in case you're interested. None of these mushroom blocks are breaking.

![2017-03-10_15 58 35](https://cloud.githubusercontent.com/assets/4811061/23812923/7651ca20-05aa-11e7-8ef8-25e5e011e54a.png)

**Comment by tterrag1098** [comment]
I mean, that's how trees work, more or less, so it should be doable. There must be a bug in the mushroom farmer code.

**Comment by roboderpy** [comment]
Notable thing: Farmer should work with mushrooms like it works with trees, e.g. cut from up to down. For now farming station cuts bottom block and replaces it with mushroom, then it cuts all left blocks before axe runs out.

**Comment by HenryLoenwind** [comment]
Thx for noting how the mushroom farmer works, I think changing it to work like the tree farmer (or just sorting the list of blocks to harvest by y-level) may be the easiest thing to do.

**Comment by HenryLoenwind** [comment]
Ok, I see what's happening. It *is* harvesting from the top, but after the harvest it tries to replant---and doesn't check if the planting location is free. So it overrides the stem of the big mushroom with a small mushroom.
