### ISSUE TITLE
Crash during the game launch.

### ISSUE THREAD

**Issue by MeHaNiK-Corp** [SleepyTrousers/EnderIO#4090]
**Issue Description:**

Kind time of the day, dear developers! I do not know very well English, so I write using Google Translate. I apologize for possible errors, this is my first message on GitHub. My problem is that after adding the mod EnderIO to my modpack, the game stopped running. I tried to run only EnderIO, of course with Ender Core. As a result, I got crash (http://pastebin.com/d3PPat5Y). At the moment I do not know how to fix this problem.

**What happens:**

After adding the mod, crash occurs.

**What you expected to happen:**

The game will start and I will be able to play with this mod.

**Steps to reproduce:**

1. Add EnderIO and EnderCore to the mods folder.
2. Start the game.
3. Get crash.

____
**Affected Versions:**

- EnderIO: 1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-0.2.0.36_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

**Your most recent log file where the issue was present:**

Log file: http://pastebin.com/eEeR2LQM
FML-Log file: http://pastebin.com/gWeXrcRz
Crash-report: http://pastebin.com/d3PPat5Y

**Comment by HenryLoenwind** [comment]
Is your Minecraft installation very old? If yes, then it may have a very old version of a library.

**Comment by MeHaNiK-Corp** [comment]
I recently reinstalled the game. As I understand, the latest versions of the libraries were downloaded. How can I find out their versions?

**Comment by vadz1999** [comment]
Have the same problem with the same crash report, but my friend does not.
Tried on clean minecraft installation.

Forge: 10.13.4.1614
endercore: 1.7.10-0.2.0.39_beta
EnderIO: 1.7.10-2.3.0.429_beta

Noticed that ny friend's game loads with lang3 lib ver 3.3.2, whether my loads with 3.1, also after deleting libraries folder(launchers are the same)

https://pastebin.com/UDNWwQAJ

**Comment by vadz1999** [comment]
@MeHaNiK-Corp if you still stuck on this issue then add commons-lang3 3.3.2 version to your mc installation. Edit .minecraft/versions/[ver]/[ver].json
