### ISSUE TITLE
Capacitor Bank I/O values not saving on dimension change

### ISSUE THREAD

**Issue by Buddy-xR** [SleepyTrousers/EnderIO#4091]
#### Issue Description:
Already reported on FTB Forums, report can be found [here](https://forum.feed-the-beast.com/threads/ender-io-switching-dimensions-causes-an-input-output-bug.221047/).  Basically, switching between dimensions sometimes causes capacitor bank input/output values to change to 0, this does not happen every time.

#### What happens:
When you switch from one dimension to another, such as overworld to nether, or vice versa... SOMETIMES the input/output values on the capacitor banks gets set to 0.  So far, I have had this issue with both the basic capacitor bank and vibrant capacitor bank, I have not tried any others.

#### What you expected to happen:
The input/output values of a capacitor bank to stay the same when switching between dimensions.

#### Steps to reproduce:

1. Place a capacitor bank and set the input/output values
2. Leave the current dimension and come back
3. Check the capacitor banks input/output values
4. If the values have not changed, continue hopping between dimensions and checking the capacitor bank until it happens, as it is not something that happens every time.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.156
- EnderCore: 1.10.2-0.4.1.65
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

#### Your most recent log file where the issue was present: 

Not available at the moment

**Comment by MatthiasMann** [comment]
There have been many changes to the capacitor banks regarding that issue between your version and the current one.

See https://github.com/SleepyTrousers/EnderIO/issues/3763 for details.
