### ISSUE TITLE
Killer Joe can't use Tinkers' Construct weaponry

### ISSUE THREAD

**Issue by Senophoe** [SleepyTrousers/EnderIO#4092]
#### Issue Description:
Killer Joe won't use any Tinkers' Construct weaponry. This has been reported before at issue #1794 back in 2015, and since then it was planned to come as a new feature. Not sure it was implemented, though.

This has become far more important after the release of the FTB Beyond modpack. It contains the Tinkers' Tool Leveling mod, which allows Tinkers' tools to gain levels as we use them. The leveling process is quite slow, and in case you spend too much time on a bad sword and decide to make a new one, the process can be quite grindy. This could be solved using Killer Joe to level up needed swords.

#### What happens:
Killer Joe won't use Tinkers' Construct weaponry.

#### What you expected to happen:
Tinkers' Construct weaponry should be usable.

#### Steps to reproduce:
Try to use any Tinkers' tool with Killer Joe.

____
#### Affected Versions:

- EnderIO: 3.1.156
- EnderCore: 0.4.1.65
- Minecraft: 1.10.2

#### Your most recent log file where the issue was present: 

Not necessary.

**Comment by mindforger** [comment]
automating tinker tool leveling is a no go in my eyes ... in the past i abused the dummy doll to level my sword ... i got punished (in a quiet humorus way) for that and now i thinkt this is part of the leveling and should not be circumvented .. maybe let the killer joe let use weapons and tools that reched master level but not to grind the levels onto the wepaons .. this is way to cheaty in my opinion

**Comment by HenryLoenwind** [comment]
Support for Tinkers' weapons was added in version 3.1.162. I *can* add it to your ancient 3.1.156---if *you* provide the time machine (and I get to keep it).




;)
