### ISSUE TITLE
Tooltip in Transparent Conduit Facade and Transparent Hardened Conduit Facade gives wrong info

### ISSUE THREAD

**Issue by dragon3025** [SleepyTrousers/EnderIO#4093]
#### Issue Description:
I read somewhere that the developers decided that the Transparent Conduit Facade and Transparent Hardened Conduit Facades shouldn't hide conduits, but have the wire appear in the block; the tooltip says that it hides it when the facade is painted with a transparent block. I'm new to Ender IO so I ended up having to search online out of confusion.

#### What happens:
Tooltip gives the wrong info.

#### Steps to reproduce:

1. Hold shift to view Ender IO Transparent Conduit Facade and Transparent Hardened Conduit Facade information.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.156
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

https://gist.github.com/dragon3025/10fffbac749495881a7be145b00f3a5e

**Comment by tterrag1098** [comment]
A long time ago, facades always hid the conduits inside. Even when painted with something like glass. I didn't think this made much sense, so back in 1.7.10 I made them show the conduits if the block was transparent. A lot of people liked the old way, so this block was added. A facade with a solid paint will never show conduits, but only the transparent conduit facades *can* show conduits. The tooltip is correct.

**Comment by dragon3025** [comment]
Okay, the Transparent Conduit Facade says it hides it with a non-solid block and I was thinking that see-through and transparent blocks were the same thing, so when I panted the Transparent Conduit Facade with glass then used it and the Conduit was still visible, I thought something was wrong.

I think somethings wrong now though, I painted 2 new Conduit Facades, 1 regular and one transparent, with Glass. Both of them are now hiding the conduit, even the Transparent Conduit Facade which didn't hide it earlier.

**Comment by tofof** [comment]
I confirm that the tooltip is correct, in that the behavior matches what the tooltip says in 1.10.2-3.1.1.73:
> **Transparent: hides** the conduits when painted with a non-solid block.

Emphasis mine. To reiterate: the *transparent* conduit facade *hides* the conduit even when painted with a non-solid block.

<br>

However, @tterrag1098 seems to have misspoken:
>   only the transparent conduit facades _can_ show conduits 

This was probably meant to read:
Only the ***regular*** conduit facades can show conduits. (And only when painted non-solid.)
The *transparent* conduit facades *hide* conduits - regardless of paint.

<br> 

<sup><sub> Posting to save any future readers the same confusion I had from the misspoken assertion, having settle the matter definitively for myself through experimentation.</sup></sub>
