### ISSUE TITLE
Transparent Conduit Facade aren't showing conduits inside them sometimes

### ISSUE THREAD

**Issue by dragon3025** [SleepyTrousers/EnderIO#4094]
#### Issue Description:
I misunderstood Transparent Conduit Facades earlier and thought they weren't working: https://github.com/SleepyTrousers/EnderIO/issues/4093

I confused Glass with being a non-solid because it was transparent, so I thought Conduits weren't supposed to show through Transparent Conduit Facades painted with Glass.

Afterwards, I painted 2 new Conduit Facades, 1 regular and one transparent, with Glass. Both of them are now turning the Conduit invisible, even the Transparent Conduit Facade which didn't turn it invisible earlier. I tested this a 2nd time this and the same thing still happened.

#### What happens:
Transparent Conduit Facades are turning the Conduits inside them invisible, even though the Transparent wasn't earlier.

#### What you expected to happen:
Conduits to appear inside Transparent Conduit Facades painted with Glass

#### Steps to reproduce:

1. Paint a Transparent Conduit Facade.
2. Cover a Conduit with it.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.156
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

https://gist.github.com/dragon3025/ad93b44fd5b6fc3b02714fbef04730b8

EDIT: I just loaded my world back up. The Transparent Conduit Facade isn't turning the conduit invisible anymore. Why did it in the first place?

EDIT: I reloaded the world and it's invisible again.

**Comment by MatthiasMann** [comment]
Your EnderIO version is outdated - can you try reproducing that with the latest version?

**Comment by dragon3025** [comment]
The newest version I can find for 1.10.2 3.1.173, but it's a beta version, are you saying to use that version?

**Comment by MatthiasMann** [comment]
yes

**Comment by dragon3025** [comment]
Thanks, I tested it out and it's working, and I haven't removed Optifine yet. If it messes up again, I'll remove Optifine first.
