### ISSUE TITLE
Crash on certain unsupported facade paint

### ISSUE THREAD

**Issue by Alex-hawks** [SleepyTrousers/EnderIO#4095]
#### Issue Description:
Crash on certain unsupported facade paint
In this case I painted an Item Buffer with an ExU2 TNT Generator

#### What happens:
It crashes. Here is the log from MultiMC
https://paste.ee/p/zLob1

#### What you expected to happen:
Either render properly, or fail at rendering and just render nothing

#### Steps to reproduce:

1. Paint Item Buffer with ExU2 TNT Generator.
2. Attempt to view inventory containing result
3. https://paste.ee/p/zLob1

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.169
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

#### Your most recent log file where the issue was present: 
https://paste.ee/p/zLob1

**Comment by HenryLoenwind** [comment]
Did you update ExU2 between painting the item and the crash?

**Comment by HenryLoenwind** [comment]
(Tagging for "vanilla bug but we need a workaround")

**Comment by Alex-hawks** [comment]
nope. it crashed as soon as I opened the Iron Chest that my Painting Machine auto-outputs to

**Comment by Alex-hawks** [comment]
To be honest, I was half expecting this to not work, by not rendering. I was just hoping it would. 
One way to fix it might be to catch the exception and return either air or the invisible block as the source block, if it has issues like this

**Comment by Alex-hawks** [comment]
One more note, the server didn't care that this happened. It just kept going

**Comment by bookerthegeek** [comment]
@Alex-hawks that is because the server does not render anything.

**Comment by Alex-hawks** [comment]
@bookerthegeek I'm well aware of that, I just felt I should mention that because this code can be called on the server

**Comment by HenryLoenwind** [comment]
BTW: I'm still looking into the reason for the blockState property rejecting one of its values. That should not happen in the first place.

**Comment by Alex-hawks** [comment]
Might be time to get input from @RWTema 
Also, the version of Extra Utilities 2 used for this was 1.3.0

**Comment by HenryLoenwind** [comment]
I contacted RW on IRC, I just cannot see if there's an answer from work. ;)
