### ISSUE TITLE
[Feature Request] Shift+Click items into Item Filters

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4098]
It would be nice if you could shift+click items into Filter and Advanced Filter so you don't have to drag them.

**Comment by Alex-hawks** [comment]
http://ideas.theideawall.com/EnderIO/
This is an ISSUE tracker

**Comment by Xiaminou** [comment]
Yes it is, but most mod also use issues trackers for suggestions. And I didn't know about that other website you linked.

**Comment by Alex-hawks** [comment]
Sorry for the "tone" I used. It was unneeded

**Comment by HenryLoenwind** [comment]
Let's call the tone "preemptive"...the majority of people react in a negative way when told nicely.
