### ISSUE TITLE
[Bug] Coordinate selector and paper.

### ISSUE THREAD

**Issue by Fokson** [SleepyTrousers/EnderIO#4099]
Issue Description:

Coordinate selector doesn't consume paper, but requires it in inventory to function.

Only one paper and a selector is in my inventory> http://puu.sh/uICXh/528be50880.jpg
I use the selector and the paper turns into coordinates> http://puu.sh/uICYV/765a531399.jpg
But if I click the empty space where the paper was> http://puu.sh/uID03/ae790f8bb6.jpg

If you have more than one paper in the stack, the quantity goes down but will revert to its previous value upon interacting with the stack.

Affected Versions:

    EnderIO: 3.1.156
    EnderCore: 0.4.1.65-beta
    Minecraft: 1.10.2
    Forge: 12.18.3.2221

**Comment by HenryLoenwind** [comment]
Sponge?

**Comment by Fokson** [comment]
I'm unsure of what you're asking.  Apologies on the lack of logfile, there was no log output produced by anything related to EnderIO during the issue (plus the logs tend to be over 12MB in size on a good day) so I didn't consider it.

**Comment by VT-14** [comment]
Sponge is a server utility that causes all sorts of havoc with mods and has been known to cause issues like this.  Other utilities like Cauldron, Spigot, etc. are also usually unsupported, and issues they cause should be reported to them.  For rendering problems, Optifine is also in the same boat.

A simple way to eliminate possible server problems is to try the test in single player (which you might have done).

You should always try to upload a log as it includes a lot of information beyond the stuff that particular mod is pointing out.  For example, a full mod list and system specifications.  If it's within reason, you can start up your instance or server, recreate the issue, and then shut it down to generate a reasonable sized log with all of the necessary information.  You can also do a manual debug crash on your client by holding F3 + C for 10 seconds, which could also be useful in some cases.


Sidenote; Do I see Thaumcraft aspects on that paper's tooltip in the last picture?

**Comment by Fokson** [comment]
The world you're seeing is, in fact, a single player world.  There are no server utilities in play.
Yes, you are seeing Thaumcraft aspects; I'm using Thaumcraft: http://puu.sh/uLaEo/f44616b11f.jpg
That's really interesting that you can induce a manual crash, I had no idea!  Here's the crash log for you.

http://puu.sh/uLaHo/c8e91b3972.txt
