### ISSUE TITLE
[Suggestion] Dark Steel Door

### ISSUE THREAD

**Issue by XFactHD** [SleepyTrousers/EnderIO#4100]
It would be awesome if you added a Dark Steel Door that could be painted much in the same way as the existing Dark Steel Trapdoor.

**Comment by VT-14** [comment]
Suggestions are now being tracked on:
http://ideas.theideawall.com/EnderIO/

Please post your suggestion there.

**Comment by XFactHD** [comment]
Thanks for the hint, I just saw that it was already suggested :D
