### ISSUE TITLE
[Suggestion] Basic logic gates for redstone output

### ISSUE THREAD

**Issue by Predhu** [SleepyTrousers/EnderIO#4101]
The  item conduits have some nice upgrades, the same idea could be applied to redstone conduits to allow to manipulate the signal transferred by the conduit.

The basic idea is that the upgrade applies only to the output of the conduit, has no effect on the input sides. Placing a NOT Gate upgrade into an endpoint applies the transformation to the output of that node, but leaves all other nodes untouched.

A common usage is when someone just wants to use a NOT gate to control a machine which reacts differently to others.

Another use case is when there are two channels in use and an AND gate would be nice to aggregate those. As an example, a signal comes from the monitor saying that the capacitators are under 25% (red channel) and a second from a lever on a different channel (green). The upgrade would apply a transformation saying, that output only when there is a signal on both channels (red & green).

To keep it simple, a node should accept only one of these upgrade cards and as mentioned above, the cards are affecting only the output on that node.

**Comment by VT-14** [comment]
Suggestions are now being tracked here:
http://ideas.theideawall.com/EnderIO/

I would definitely vote highly for the NOT gate.  The AND Gate, while possibly useful, seems a bit complicated to handle in a conduit connection.

**Comment by Predhu** [comment]
Moved to the idea wall: http://ideas.theideawall.com/EnderIO/Forum/TopicDetails/7541334d-788a-41f2-8b64-4fbc8f77d7bb

**Comment by HenryLoenwind** [comment]
Thanks
