### ISSUE TITLE
Painted Blocks do not show what they're painted with

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4102]
I've recently been painting blocks with Marble and Laboratory Blocks from Chisel which look very similar, it made me realise most EnderIO painted blocks (except for facades, buffers, glowstone...) do not indicate what they're painted with in the tooltip like facades do.
I guess it could be considered an enhancement, basically make all paintable blocks have the "painted with:" tooltip once they're painted.
![2017-03-15_18 09 31](https://cloud.githubusercontent.com/assets/8670392/23961434/34512080-09ab-11e7-9159-62a67202f530.png)

**Comment by Buddy-xR** [comment]
I agree, it would be nice to see this added.  With all the different blocks that mods add, a lot of them look similar and it is hard to tell which one is the one you want.
