### ISSUE TITLE
More conduits!

### ISSUE THREAD

**Issue by Teyson** [SleepyTrousers/EnderIO#4106]
This is not a bug report!

I just really love the different kinds of conduits and would love to see more added. On the top of my wishlist as of right now, is a Refined Storage conduit! Would be amazing to have one for that system just as there is a ME conduit.

**Comment by Alex-hawks** [comment]
Suggestions go [here](http://ideas.theideawall.com/EnderIO/)

**Comment by VT-14** [comment]
Has been suggested several times already.  RS asked Ender IO to hold off on adding RS Conduits until they released a new API, which they only did in 1.11.

You can view one of the more complete tickets at #3998.  You should search before reporting/suggestion something to avoid duplicates.  Ender IO suggestions are also now being tracked on http://ideas.theideawall.com/EnderIO (as Alex-hawks pointed out).

**Comment by PapiDimmi** [comment]
A Refined Storage conduit would be awesome! I’ve always wanted to use Refined Storage cables in the same block space as Ender IO conduits, as well as use conduit facades for Refined Storage cables.

**Comment by DarkHelmet433** [comment]
As near as I can tell, the RS people are telling folks asking about this that it's already being done for 1.11, however the code that's around is for 1.10.2 only, and in limbo.  There are some very complete changesets in the issues mentioned above.  This is less than optimal, to say the least.
