### ISSUE TITLE
1.10.2 - update to stable_29 mappings

### ISSUE THREAD

**Issue by p455w0rd** [SleepyTrousers/EnderIO#4108]
#### Issue Description:
stable_29 is the current stable 1.10.2 MCP mappings release. When depending on a project source as I am, it is imperative to stay current on mappings so compatibility can be sustained within a dev environment.

#### What happens:
Try to launch when depending on EnderIO as a project within Eclipse and MC crashes due to my mod using stable_29 mappings and EnderIO using outdated snapshot_20160518 mappings. (Specifically references to Minecraft.getMinecraft().thePlayer, Minecraft.getMinecraft().theWorld, and misc MathHelper methods)

#### What you expected to happen:
successful client launch

#### Steps to reproduce:

1. make a mod that uses stable_29 mappings and within dev env, depend on EnderIO as a project
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0
- EnderCore: 0.2.0
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
you're using the wrong type of dependency. You need a deobfCompile, see e.g. https://github.com/HenryLoenwind/TravelHut/blob/master/build.gradle#L57 , that's for exactly that case.

**Comment by p455w0rd** [comment]
I don't think you read what I typed. That or you don't understand what I'm saying. I'm using the project itself. Not something pulled from a maven. ![https://puu.sh/uWe4S/bc3111aa98.png](https://puu.sh/uWe4S/bc3111aa98.png)

Even if I wasn't, how is staying on an obsolete mapping version helpful in any way to anyone?
