### ISSUE TITLE
Empty soul vial can't pick up horse

### ISSUE THREAD

**Issue by KekPafrany** [SleepyTrousers/EnderIO#4109]
Hi,

I use a modpack Direwolf20 1.10 which contains Ender IO 1.10.2-3.1.156

I tried to use soul vials for transporting mobs. I had no problem with villagers, enemy mobs, but I had with horses:

Empty soul vials can't pick a horse, either tamed (or wild). When I tried with right click or in sneak mode, the horse only opened its inventory, (and the wild horse only neighed since I clicked on him with full hands)

I know it is not a big issue, I can't even be sure I am using it right, I'm curious if there is a solution (or fix) for this.
____

- EnderIO: 1.10.2-3.1.156
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2

**Comment by MatthiasMann** [comment]
Check the config files (from EnderIO) to see if the horses are black listed in that pack.

**Comment by HenryLoenwind** [comment]
I'm quite sure we are handling the "item on entity click" the only way possible. Which means that it's a base game mechanic that the "entity clicked by player" handling has precedence.

**Comment by KekPafrany** [comment]
Thank you MatthiasMann, it solved my problem. Horse was blacklisted in the modpack.

So the problem was at my end.
