### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by wandersonbraz** [SleepyTrousers/EnderIO#4110]
Hello, everyone. Good morning.

Well I would like a help with an accident that I recently had in my log shows EnderIO detecting the crash but I do not know which mod came the problem so I'm putting the crash part here together.

I apologize if the error is not from EnderIO.

Thank you very much in advance

http://pastebin.com/BziH3iyf

**Comment by MatthiasMann** [comment]
Did you even read what is written in that pastebin you posted?!? This is just diagnostic information and not the cause of the crash.

**Comment by wandersonbraz** [comment]
crash-2017-03-25_10.39.40-client log on pasterbin

http://pastebin.com/s6jSf6HC

**Comment by MatthiasMann** [comment]
Look at line 90 - seems to be either an issue with draconic evolution or with foamfix.
