### ISSUE TITLE
Painted pressure plates do not render textures properly

### ISSUE THREAD

**Issue by L0laapk3** [SleepyTrousers/EnderIO#4111]
If you paint a (in my case, stone) pressure plate with a block that has different textures on each side (in my case: matter transmitter), The incorrect texture will be used for the top side of the pressure plate as demonstrated here:
![image](http://i.imgur.com/uLTm4wd.jpg)

It should be obvious that the expected output is that the top texture is used for the top side of the pressure plate.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-0.4.1.65-beta
- EnderCore: 1.10.2-3.1.156
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by MatthiasMann** [comment]
Same issue as #4057
