### ISSUE TITLE
Ender IO Glasses should affect Beacon Beam Color

### ISSUE THREAD

**Issue by Drullkus** [SleepyTrousers/EnderIO#4112]
Currently using EnderIO-1.10.2-3.0.1.96_beta.

You can use this method found in the Block class `public float[] getBeaconColorMultiplier(IBlockState, World, BlockPos, BlockPos)` to provide a RGB Color Multiplier for the Beacon Beam when it passes through the glass. You can give an array of 3 floats between `0.0` and `1.0`.

![2017-03-26_12 53 08](https://cloud.githubusercontent.com/assets/5010174/24334663/2c9c3b88-1223-11e7-9200-330f3dc6154f.png)

**Comment by HenryLoenwind** [comment]
Thx!
