### ISSUE TITLE
Request: Teleport Events

### ISSUE THREAD

**Issue by An-Sar** [SleepyTrousers/EnderIO#4113]
I am wondering if you could fire the EnderTeleportEvent when players use travel staves, the ender, or other forms of teleportation. 

It appears this event fires when players throw vanilla ender pearls so it would seem consistent to apply it to player actions. It would be very useful to be able to wrap the EnderIO forms of teleportation under this single event.

Thank You

**Comment by Fokson** [comment]
I would propose that this be a config option if it is done.  Including a mod that has held-items that interrupt Enderman teleportation would have those items prevent you from teleporting around your base.  A great example is the "Ender Jammer" implant, from the mod "Cyberware".  It is designed to prevent Enderman nearby you from teleporting away.  Install this into your skull and you're suddenly never able to use a travel staff again.  An interesting trade-off to be sure, but I can see a lot of people disliking it.

**Comment by An-Sar** [comment]
Mods would also have the option to check if the entity teleporting is an enderman or player depending on the intended effects.

**Comment by tterrag1098** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/api/teleport/TeleportEntityEvent.java

**Comment by An-Sar** [comment]
That's even better. My bad, I looked through the repo but managed to miss that entirely.
