### ISSUE TITLE
Crash Regarding EntityWeatherRocket['entity.EnderIO.weather_rocket.name'/3110]

### ISSUE THREAD

**Issue by reddvilzz** [SleepyTrousers/EnderIO#4115]
#### Issue Description:
Crashes when witcher guards got killed by villagers. I am using ResonantRise 3 modified pack for private use. 

#### What happens:
So Witcher guards tries to kill some mobs, but accidentally hit one of the villager which causing the nearby villagers swarmed in and attack one of the guard until he died. When I saw his health is 0 the game freezes and then crashes.

I tried re-entering the game and load up the world the game instantly crash when loading up the world. So I think the world can't be played at all until the entity is cleared maybe.

And the mod that causes the villagers to retaliate on the guard is SpecialAI I think.

#### What you expected to happen:
The guard just die in peace maybe.

#### Steps to reproduce:

1. Enter the world, find nearby villages
2. Try to make the witcher guards attack one of the villagers, so the villagers will try and kill the guard
3. Wait until the guard is about/near to death
4. Crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: ENDERIO-1.7.10-2.3.0.429_BETA
- EnderCore: ENDERCORE-1.7.10-0.2.0.36_BETA
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1614-1.7.10-universal

#### Your most recent log file where the issue was present: 

https://pastebin.com/M1ELw81n

Edit: Test it 3rd time, this time there is no crash when I killed both villager, villager guard and even let the villagers killed the guard.

**Comment by reddvilzz** [comment]
Added test result. Will try and test it more.

**Comment by reddvilzz** [comment]
I'm on my 10th Test now and there is no more crashes. Does it mean it is a bit random to have it? But also it is quite fatal when it happens on a regular playthrough world because the world can't be played anymore.

How can I prevent this from happening?
Thank you.

**Comment by HenryLoenwind** [comment]
see also #3282

So: Do you really have a weather rocket there? If not, then there's something very fishy going on, as integrated server and client cannot be out of sync.

**Comment by reddvilzz** [comment]
No I don't think I have anything related to enderIO at all because it is really a fresh start. Just created the world hover around using creative just to check and make sure everything is okay and next thing I see a guard being attacked by mobs of villagers.

When he about to died my game froze and then crash.
