### ISSUE TITLE
“Ender IO” or “EnderIO”?

### ISSUE THREAD

**Issue by ghost** [SleepyTrousers/EnderIO#4117]
This has confused me for a while.

Is the name of the mod Ender IO or EnderIO?  
The official website of the mod calls it “EnderIO,” CurseForge calls it “Ender IO,” Minecraft Forum calls it “Ender IO,” GitHub calls it “EnderIO,” the FTB wiki calls it “EnderIO,” and so on. It’s different everywhere.

**Comment by VT-14** [comment]
The original forum thread is titled "Ender IO ..." so I assume that is the 'correct' spelling; though I would go out on a limb and say that both versions are acceptable and people shouldn't make a big deal about it.

**Comment by PapiDimmi** [comment]
I need an official explanation from one of the devs.
