### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Nicon4454** [SleepyTrousers/EnderIO#4118]
#### Issue Description:
I placed a farming station and then was digging under it to access it from the bottom and the server crashed.

#### What happens:

Server Crashes

#### What you expected to happen:

Not to crash

#### Steps to reproduce:

1. every time i go to the area the server crashes
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.179.jar
- EnderCore: EnderCore-1.10.2-0.4.1.65-beta.jar
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2254-universal.jar

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/vk5bLEG9 (Crash Report)
https://pastebin.com/wBrBDa1Q (FML Log)

**Comment by Nicon4454** [comment]
should i downgrade enderio and ender core?

**Comment by Nicon4454** [comment]
so this happens every time a farming station is placed in the world as soon as it gets power the server crashes. i downgraded to EnderIO-1.10.2-3.1.156 and kept the core the same.

**Comment by Alex-hawks** [comment]
Check the EnderIO Energy Diagnostic Info. BrandonCore ships with a version of the RF API from 1.7.10
