### ISSUE TITLE
The farming station does not work with dirt and grass from other mods

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4119]
The farming station doesn’t till and harvest crops on dirt and grass from other mods, like the silty grass and silty dirt from Biomes o’ Plenty.

Shouldn’t it use Ore Dictionary (blockGrass, dirt, blockDirt) for the blocks that it works on? That would be very useful.

**Comment by HenryLoenwind** [comment]
BoP grasses and dirts are not "grass" and "dirt" on purpose. Complaint o them.

(Sorry, I couldn't find a reference to the original source for that info. I'll link it in if/when I do.)

**Comment by HenryLoenwind** [comment]
PS: There's no ore dictionary for blocks. It's for items only.

**Comment by PapiDimmi** [comment]
Huh, okay. What do you mean by they’re not grass and dirt on purpose?

**Comment by HenryLoenwind** [comment]
That I complained to them that those blocks are not grass/dirt and they said it was on purpose.

**Comment by PapiDimmi** [comment]
If you know why it was on purpose, feel free to tell me, because I’d love to know. What does _not being dirt and grass_ mean?

**Comment by ktole1999** [comment]
maybe "dirt" block is not registered as dirt therefor its not treated as "dirt". i dont know just speculation.

**Comment by VT-14** [comment]
> What does not being dirt and grass mean?

I would assume that they are quite literally not dirt or grass.  BoP's Silty Grass/Dirt is a completely new block that could be a Block of Uranium for all Ender IO knows.  

Based on the conversation and confusion emojis, I would guess that BoP registers the items (things in the inventory) as dirt.  The block placed in the world is an entirely different thing and can't use the ore dictionary.

**Comment by PapiDimmi** [comment]
Is there an Ore Dictionary for blocks? Like, how can an item be registered as dirt? And what does it mean to be registered as dirt? I’m not a Minecraft mod developer, nor do I know much Java, but I just don’t understand what this means. At first I assumed that Ore Dictionary goes for placed blocks as well, but it turns out that I was incorrect.

How can a non-vanilla block, like silty grass, be registered as a vanilla block, like dirt, and how does it affect other mods? Is Ender IO configured so that the farming station works on vanilla grass and dirt blocks only, or is it configured so that it works on all blocks that are “registered” as grass or dirt? Biomes o’ Plenty’s dirt and grass blocks can be tilled, so I’m unsure whether this is because Biomes o’ Plenty is coded like that or if it’s because the blocks are “registered” as dirt and grass, respectively.

Anyway, a config option in Ender IO’s configuration file that can specify what blocks the farming station works on, in addition to the vanilla grass and dirt blocks, would be very useful and would save the developer of Biomes o’ Plenty and mods that add alternative grass and dirt blocks from doing anything.

**Comment by PapiDimmi** [comment]
Why does this have the “Duplicate” tag? Which issue is it a duplicate of? I searched and couldn’t find _anything_.

**Comment by Alex-hawks** [comment]
If you look [here](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.11.x-6.0.x/src/main/java/biomesoplenty/common/block/BlockBOPGrass.java#L119-L156) you'll see that the BOP grasses are very picky in what plants they support, and don't appear to be tillable

**Comment by PapiDimmi** [comment]
The grass blocks from Biomes o’ Plenty _are_ tillable, actually.

**Comment by bookerthegeek** [comment]
@HenryLoenwind if you like id be more then happy to maintain a list for you of tilable blocks and blocks that can be planted on if you so like?
