### ISSUE TITLE
1.7.10 Server crashes when placing Conduit next to extra utils furnace generator

### ISSUE THREAD

**Issue by kingcraftingnl** [SleepyTrousers/EnderIO#4121]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
1.7.10 Server crashes when placing Conduit next to me energy accepter

#### What you expected to happen:
Conduit should be placed

#### Steps to reproduce:

1.1.7.10 Server crashes when placing Conduit next to me energy accepter2.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.....3.0.429-batea
- EnderCore:EnderCore 1.7.10-0.2.0.83_beta
- Minecraft: 1.7.10
- Forge: 1.7.10-1614
- AE2-rv3-beta6

#### Your most recent log file where the issue was present: 
https://pastebin.com/pBhip62m

**Comment by HenryLoenwind** [comment]
Where did you get that 5th tier energy conduit from? We only have 3 tiers...

**Comment by kingcraftingnl** [comment]
Its not even a Furnace generator...,
Im talking about an Energy Accepter from ae2,

Steps to reproduce:

1.1.7.10 Server crashes when placing Conduit next to me energy accepter2.

**Comment by HenryLoenwind** [comment]
The crash log is quite clear here:

```
-- Block entity being ticked --
    Name: extrautils:generatorbase // com.rwtema.extrautils.tileentity.generators.TileEntityGeneratorFurnace
    Block type: ID #970 (tile.extrautils:generator // com.rwtema.extrautils.tileentity.generators.BlockGenerator)
```

That's the block in which work cycle the crash happens.

**Comment by Alex-hawks** [comment]
Is there any sanitation that stops users from giving themselves stupid shit that crashes the game, like this?

**Comment by HenryLoenwind** [comment]
@Alex-hawks no, vanilla can create any item or block with any meta value. However, I'm not yet sure this is the reason for the crash, that's why I asked the OP about it...

**Comment by Alex-hawks** [comment]
Line 256 might give some enlightenment
>     Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
