### ISSUE TITLE
Capacitors go into the wrong slot in the painting machine when shift-clicking

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4122]
Shift-clicking a capacitor when the GUI of the painting machine is open places it into the slot where blocks that should be painted go, rather than the capacitor/upgrade slot.

**Comment by ktole1999** [comment]
need version info incase it wasnt obvious.

**Comment by PapiDimmi** [comment]
Oh yeah, my bad.

**Forge version:** 12.18-3-2254 (latest version for 1.10.2)
**Ender IO version:** 3.1.179 (latest [beta] version for 1.10.2)

**Comment by HenryLoenwind** [comment]
I'll have a look later; if I can reproduce it here, I don't need the rest of the data.
