### ISSUE TITLE
The textures of painted blocks do not connect with non-painted blocks of the same material

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4126]
#### Issue Description:
Blocks that have connected textures do not connect with other blocks if they’re painted.

#### What happens:
_E.g._, a glowstone block painted as a glass block does not connect with actual glass blocks.

#### What you expected to happen:
The textures should connect; otherwise, it looks very out of place.

#### Affected Versions (Do *not* use "latest"):
* **Ender IO**: Latest for 1.10.2, 1.10.2-3.1.179.
* **EnderCore**: Latest for 1.10.2, 1.10.2-0.4.1.65-beta.
* **Minecraft**: 1.10.2.
* **Forge**: Latest for 1.10.2, 12.18-3-2254.

**Comment by VT-14** [comment]
Vanilla Glass does not have a connected texture.  I think that may be added by Optifine, but that is usually not supported.  It would probably have to be fixed on Optifine's side anyway.

If you are using non-vanilla glass, then please specify which mod.  I have seen painted connected textures working with Chisel on Foolcraft videos.

**Comment by VT-14** [comment]
If you would like to me to clarify what I said, please ask.  The confused emoji is rather unhelpful.

**Comment by PapiDimmi** [comment]
@VT-14 I used it more as “Aww, that’s a bummer” than “I’m confused.”
