### ISSUE TITLE
Inventory Storage Systems and Item Conduits

### ISSUE THREAD

**Issue by Fokson** [SleepyTrousers/EnderIO#4127]
**What happens / What you expected to happen / Steps to reproduce:**
Inventory Storage Systems will be recognized by an item conduit that is not attached to it (disabled) and/or does not have a remote awareness upgrade.  If an item conduit passes by more than one side of a single Inventory Storage System, Inventory Panels will show the items it contains at a multiplied quantity.

To reproduce, place an Inventory Storage System (I used the Extended Warehouse), place Item Conduits around it, sever their connections by setting them to 'Disabled', and attach an Inventory Panel.  Place a chest with another Item Conduit on another side (not attached to the first set of Item Conduits) and allow the conduit attached to the chest to extract without Redstone, and place some items inside.

Image: http://puu.sh/v8ETB/8eb834cdef.jpg

For every one item that is pulled from the chest and into the Inventory Storage System, two will be shown as available in the Inventory Panel (assuming you have the Item Conduit attached to the Inventory Panel "brushing" two sides of the Inventory Storage System.  If you have it "brushing" three sides, three will appear).

First and foremost, the panel and storage system should not be communicating in any way if the conduit is not attached.  Second, the contents of the storage system shouldn't be visible to the panel if the conduit attached to the storage system doesn't have a Remote Awareness Upgrade.  Lastly, the panel should only display the contents of any one storage system once, regardless of how many surfaces are connected with Item Conduits.
____
**Affected Versions:**

- EnderIO: 3.1.156
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

**Log:**
http://puu.sh/v8F15/73fe1408c6.txt

**Comment by HenryLoenwind** [comment]
re 2nd: The needed awareness upgrade is already included in the storage recipe. Works as designed.

**Comment by Fokson** [comment]
All right, understood.  Thanks for looking into it! =)

**Comment by HenryLoenwind** [comment]
I think I know what's happening: The integrated awareness upgrade wins over the connection status of the conduit. Oops.

And about the 3rd one: I'm reasonably sure this is on purpose. The storage network does not have any special code for different targets, so it has no way of knowing if different sides of a block have different inventories (e.g. yellow and orange sides of a TE machine) or not (e.g. chests). So it's a task for the player to not make multiple "aware" connections. Combine that with that bug...

**Comment by Fokson** [comment]
That's fine - if the conduit connects to the bank multiple times and gets duplicate item readouts but the player can disable the extra connections to fix the problem, then it's not really an issue. =)
