### ISSUE TITLE
The farming station does not plant rubber tree saplings from IndustrialCraft 2

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4129]

**Comment by VT-14** [comment]
I'm fairly certain the Farming Station has special coding for the IC2 rubber trees.  It will use a tree tap on them to get rubber rather than cut them down.

**Comment by PapiDimmi** [comment]
I had that in mind and tried putting a tree tap in one of the farming station’s slots, but it didn’t work.

**Comment by PapiDimmi** [comment]
I know that.

I just did some testing, and apparently, the farming station needs some space between the saplings to plant rubber tree saplings for some reason.

**Comment by HenryLoenwind** [comment]
Because rubber tree saplings don't grow unless all 6 neighboring block spaces are empty. (Disclaimer: I have no idea if IC2 changed since we added support for their rubber saplings.)

**Comment by PapiDimmi** [comment]
Why, though?

**Comment by legodude17** [comment]
@PapiDimmi you would have to ask the IC2 devs

**Comment by HenryLoenwind** [comment]
Just a quick update: There are at least 4 mods that have those rubber trees (IC2e, IC2c, TR, GT). Some of them require the space around the sapling, some don't. I won't go chasing which one is which way in which version...

**Comment by PapiDimmi** [comment]
Oh yeah, figuring out whether the rubber tree requires empty space between each sapling to grow for four different mods sounds like an extremely difficult task.

**Comment by PapiDimmi** [comment]
Figuring out whether the rubber tree requires empty space between each sapling to grow for four different mods doesn’t really sound like that difficult of a task to me, but that’s fine.

**Comment by legodude17** [comment]
@PapiDimmi If it isn't that hard then go do it yourself. 😄

**Comment by PapiDimmi** [comment]
@legodude17 Sure, I can ask the mod authors.

The thing is, I have no idea what IC2e or IC2c are.

**Comment by PapiDimmi** [comment]
@legodude17 Sure, I can ask the mod authors.

The thing is, I have no idea what IC2e and IC2c are.

**Comment by VT-14** [comment]
IC2e is the official [Industrial Craft](https://minecraft.curseforge.com/projects/industrial-craft).  The e stands for Experimental.

IC2c is [Industrial Craft Classic](https://minecraft.curseforge.com/projects/ic2-classic) by Speiger.

I think TR is Tech Reborn and GT is Greg Tech.

**Comment by PapiDimmi** [comment]
IC2c is out of the picture. It’s outdated, innit?
