### ISSUE TITLE
Items cannot be charged using Actually Addition’s batteries or energizer

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4130]
RF-using items from [Ender IO](https://minecraft.curseforge.com/projects/ender-io), such as the staff of travelling, cannot be charged using the energizer or batteries from Actually Additions.

I’m not sure if this is an an Ender IO bug or an Actually Additions bug.

**Ender IO version**: 3.1.156 (latest for 1.10.2)
**Actually Additions version**: r105 (latest for 1.10.2)
**Forge version:** 12.18-3-2254 (latest for 1.10.2)

(I also posted this on Actually Addition’s GitHub page: Ellpeck/ActuallyAdditions/issues/734)

**Comment by Ellpeck** [comment]
This is an Incompatibility issue that can be closed.

**Comment by VT-14** [comment]
Neither.  Install the Tesla API (it is a separate mod).

* Ender IO **items** can accept either Forge Energy or Tesla.  They do not accept the CoFH RF API.  Ender IO conduits and machines are able to use and convert CoFH RF.
* AA only works with Tesla or CoFH RF.
