### ISSUE TITLE
[Suggestion] Allow players to hide certain conduits when holding a conduit

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4131]
You can hide conduits using the yeta wrench, which is a very useful feature, but that doesn’t work when you’re holding a conduit. Can you allow shift-scroll to work when holding conduits, not just the wrench?

**Comment by VT-14** [comment]
Suggestions are tracked here: ideas.theideawall.com/EnderIO.  

"Conduit Hiding" has already been suggested.  The conversation on that subject suggested allowing the Yeta Wrench to hide conduits from the off-hand.

**Comment by PapiDimmi** [comment]
I don’t want to use the yeta wrench from my left hand; I just want to hide conduits whilst holding conduits. That’s probably much easier to implement.

**Comment by HenryLoenwind** [comment]
Because their is no voting system here, so I have no idea which suggestions have any kind of wider support in the player base and which ones are just made by loud people.

**Comment by mindforger** [comment]
@HenryLoenwind i too hate it to create an additional login just to vote... is just found http://poll.gitrun.com/ 
it is open source and it features github authentication but you can only manage entrys for gits you have access too ... and it would only create new issues, i will see if i can work into the code and give it a function where it fetches the "Suggestion" label and makes an automatic list of all those issues
