### ISSUE TITLE
1.10.2 -Farming Station doesn't detect a tinker's tool has Autosmelt

### ISSUE THREAD

**Issue by ariosos** [SleepyTrousers/EnderIO#4132]
Using the Foolcraft modpack -

1 - Place a Firewood hatchet or any tool with autosmelt in a farming station.
2 - Have the farming station chop trees.

- The farming station will collect logs, but not turn them into charcoal.

**Comment by dovahkiin4991** [comment]
If this is not implemented a way around this would be to collect the logs, if extrautilz is in the pack have one placing the logs and the other using the hatchet to break it with a hopper or other collected below picking up all the charcoal, or if there is an auto smelt enchantment using the mining would work as well, and collect it for you I believe.
