### ISSUE TITLE
The farming station plants rubber trees (from IC2) with spaces inbetween them

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4133]
Rather than placing all the rubber tree saplings next to one another, like it does with other types of sapling, it plants them two blocks away from the farming station and with one block of space between each sapling.

Is this intentional—and if so, why?

**Comment by MatthiasMann** [comment]
I think the IC2 rubber trees need the space for the rubber "spots" to generate.

**Comment by PapiDimmi** [comment]
What spots? They’re on the blocks themselves.

**Comment by MatthiasMann** [comment]
After talking with the IC2 developers it appears there is no requirement for spacing the trees apart.

**Comment by PapiDimmi** [comment]
It’s only possible to automate the production of sticky resin using Ender IO’s farming station, but you won’t get rubber wood or rubber wood saplings.

I’m not sure whether this is intended, but I don’t know why this would be a feature.
