### ISSUE TITLE
Water flows next to a conduit facade

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4134]
![2017-04-06_15 21 43](https://cloud.githubusercontent.com/assets/25916106/24756081/cfb61f7a-1adc-11e7-84cc-b1a40c36d41b.png)

As you can see, the water is flowing, even though it should be still.

**Comment by ktole1999** [comment]
if you place a block on the opposite corner does it resolve. this has always been like this. the corner dips to the opposing corner when no block is placed.

**Comment by PapiDimmi** [comment]
@ktole1999 Which corner are you talking about?

For clarity, here is the left side of the building:
![2017-04-06_15 59 51](https://cloud.githubusercontent.com/assets/25916106/24758261/217ffee8-1ae2-11e7-9de8-7f007c11d85a.png)
There’s no conduit facade there, so the water is fine.

Heree is the right side of the building. Because there’s a conduit facade there, the water appears to be flowing towards it.
![2017-04-06_15 59 55](https://cloud.githubusercontent.com/assets/25916106/24758289/382dbb12-1ae2-11e7-8f34-839158806324.png)

**Comment by ktole1999** [comment]
i see what you are saying now. i misread the image. if its just the conduit and no facade do you get same texture?

**Comment by PapiDimmi** [comment]
@ktole1999 Yes, the flowing animation still occurs without a conduit facade.

**Comment by ktole1999** [comment]
so its not the facade causing it. its the conduit :)

**Comment by PapiDimmi** [comment]
Yes, that is, indeed, correct.

**Comment by HenryLoenwind** [comment]
That's one of the dozen things in Minecraft where the support for blocks that can have different properties depending on some condition is broken. :(
