### ISSUE TITLE
The Ender with Travel does not always work properly with travel anchors

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4135]
My The Ender sword with Travel sometimes teleports me to a travel anchor when I just press shift, rather than pressing shift _and_ right-clicking. It also sometimes shows the travel anchor even when I’m not holding the sword in my hand.

**Minecraft version**: 1.10.2
**Ender IO version**: 3.1.179
**Forge version**: 12.18.3.2254

**Comment by MatthiasMann** [comment]
Are you standing on a travel anchor when these things happen?

**Comment by PapiDimmi** [comment]
Oh yeah, that’s probably it. Whoops.
