### ISSUE TITLE
[Suggestion] Allow multiple different energy conduits in one block space

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4137]
It’d be nice if you could place, say, an enhanced energy conduit and an ender energy conduit in the same block space.

**Comment by ktole1999** [comment]
can you explain a reason for running multiple cables in same block? If its to limit power to certain areas of network then use a capacitor or alternate energy cube to junction the lines.

**Comment by PapiDimmi** [comment]
I wanted to place an enhanced energy conduit and an ender energy conduit in the same block space.

**Comment by ktole1999** [comment]
thats what i am trying to understand. why?

**Comment by PapiDimmi** [comment]
Because I have some enhanced conduits and some ender conduits.

**Comment by ktole1999** [comment]
so just for looks or you updated your conduits and you dont want to waste the lower tiered leftovers?

**Comment by PapiDimmi** [comment]
I upgraded some of my conduits, but not all of them.
