### ISSUE TITLE
Are there possible issues upgrading to edge versions of EnderIO?

### ISSUE THREAD

**Issue by jarquafelmu** [SleepyTrousers/EnderIO#4138]
Not really an issue but more of a question.

I am currently running FTB Beyond 1.4.2 and one of my friends is getting the bug where his whole ender io network stops responding to the devices hooked up. Inventory panels go dark, machines are having their items extracted, etc.

The workaround that we've been using is to break an item conduit and replace it. This fixes the problem temporarily but it comes back. It used to come back every hour or so but now according to him, it's every 15 minutes now.

According to my research, this problem has been fixed as of EnderIO - 1.10.2-3.1.169 but this version hasn't made it into the last few FTB Beyond patches, sadly.

I would like to upgrade my server to one of the later versions. Either 169 or even go as far as using the latest version 179, but I am wondering if there are any known conflicts with FTB Beyond that I should be aware of.

I apologize if this is not the right place to ask this question. I just would really like to be able to solve my friend's issues.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.156
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- FTB Beyond 1.4.2

**Comment by PapiDimmi** [comment]
Yes, update to the latest version. Ender IO has gotten tons of bug fixes and balance changes since the version you’re using, and I highly recommend updating. I’m using the latest version, and everything’s fine; you’ve no worries.

**Comment by HenryLoenwind** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/360

**Comment by PapiDimmi** [comment]
@HenryLoenwind How is that related?

**Comment by MatthiasMann** [comment]
@PapiDimmi why did you put a thumbs down emoji - that FTBUtils bug is what is causing the problems described by the OP.

I suggest you read the linked issue and stop wasting peoples time by posting random comments/emoji without thinking.

**Comment by PapiDimmi** [comment]
I did read the post. I don’t see how it’s related to anything. Didn’t @jarquafelmu just ask if he or she should update to the latest version of Ender IO?

If I’m being completely honest, if you get mad because of an emoji on the Internet, you should probably take a break from the Internet for a while.

**Comment by MatthiasMann** [comment]
@PapiDimmi as you appear to be unable to read - here is the summary:
"I am currently running FTB Beyond 1.4.2 and one of my friends is getting the bug where his whole ender io network stops responding to the devices hooked up" => "So this leads me to believe there is something going on with the chunkloader causing these other mods to break. In the bug reports people have fixed them by using other chunk loaders."

So - I suggest you *actually* read things before posting your stupid emoji and annoying the people who are working on these mods and try to find solutions to real issues.

**Comment by PapiDimmi** [comment]
I did read both issues, but I didn’t draw a connection. I didn’t think that it was the same issue.

But what-_ever_. I really don’t understand what the big deal is.
