### ISSUE TITLE
Endermen heads cannot be worn on a player’s head like other heads can

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4139]

**Comment by HenryLoenwind** [comment]
The list of non-armour items that can be put into the head slot is hardcoded in net.minecraft.entity.EntityLiving.getSlotForItemStack().

**Comment by PapiDimmi** [comment]
What does that mean? Couldn’t you make it possible to wear endermen heads?

**Comment by MatthiasMann** [comment]
@PapiDimmi as Henry wrote - you can only wear helmets or a small finite set of items defined by vanilla minecraft.

So to avoid further misunderstandings => can't be fixed.

**Comment by PapiDimmi** [comment]
You can literally wear any block on your head, so I don’t understand why this would be impossible, but okay.

**Comment by mindforger** [comment]
Because a block is a block and the enderman head isn't

**Comment by PapiDimmi** [comment]
>Because a block is a block and the enderman head isn't

Yes, it is. It can be placed, can’t it?

**Comment by HenryLoenwind** [comment]
It's not about it working in the head slot, it is about putting it there. And any inventory that has armor slots is using the method I quoted above to determine if any item can be put there.

I can disable that check in the CapBank, then you can put any block---including the enderman head---there. And they will work. However, that still won't allow you to put it there using e.g. the player inventory.
