### ISSUE TITLE
The farming station doesn’t mine rubber wood trees from IC2

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4140]
The farming station harvests the leaves, but it leaves the logs untouched.

This has been posted before (#3550)—three and a half months ago—but it looks like nothing was ever done, since it still doesn’t work.
****
* **[Minecraft](https://minecraft.net) version**: [1.10.2](https://minecraft.gamepedia.com/1.10.2)
* **[Forge](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) version**: [12.18.3.2272](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) (latest for 1.10.2)
* **[Ender IO](https://minecraft.curseforge.com/projects/ender-io) version**: [3.1.179](https://minecraft.curseforge.com/projects/ender-io/files/2392869) (latest for 1.10.2)
* **[EnderCore](https://minecraft.curseforge.com/projects/endercore) version**: [0.4.1.65-beta](https://minecraft.curseforge.com/projects/endercore/files/2370656) (latest for 1.10.2)
* **[IndustrialCraft](https://minecraft.curseforge.com/projects/industrial-craft) version**: [2-2.6.188-ex110](https://minecraft.curseforge.com/projects/industrial-craft/files/2401711) (latest for 1.10.2)

**Comment by dovahkiin4991** [comment]
Papi it wont mine the logs, but if you give the station a tree tap, it will auto collect the rubber from the wood. If this is in a modpack I would recommend using moving wands to grab only the ones with rubber spouts, but if your trying to get just the wood for whatever reason, you will need to use something else, depending on how much you need you could set up a piece of dirt with a dispenser above and on the side to plant rubber trees(botania, and quark feature) than a mechanical user to use bonemeal really quick(extrautils2) than have a torch and repeater facing through the saplings so when it grows you detect a signal on the other side and a builder from rftools set to mine where the tree will grow sense its always strait up so when it gets a redstone signal it runs 1 cycle, cutting the tree replanting and cutting again should make a lot of rubber and rubber wood really quick. Possibly reusing some of the wood in a generator might make this system self sufficient.

**Comment by PapiDimmi** [comment]
I know that it harvests the leaves—and thus the sticky resin—but shouldn’t it harvest the wood, too? It harvests the wood of all other types of tree.

**Comment by dovahkiin4991** [comment]
its not meant to. If you seriously just need the wood read all of my post above.

**Comment by PapiDimmi** [comment]
How do you know that? It’s weird that the logs are always remaining.

**Comment by dovahkiin4991** [comment]
ive used the mechanic before. Make a moving wand from betterwands if its in your pack and find the rubber with just the spouts on it, pick it up and put it in the range, that way you have just the useful wood to maximize rubber production. When your autocrafting HV solars, you need a lot of rubber
