### ISSUE TITLE
Why do I sometimes get double the amount of dust from the SAG mill?

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4141]
Sometimes, when smelting certain ores, I get double the amount of dust. For instance, I just got four copper dusts—rather than two—from a single copper ore.

I _do_ use dark steel balls or flint, but JEI doesn’t tell me that I might get double the amount of dust. Is this a bug or a feature that I don’t know about?

**Comment by MatthiasMann** [comment]
Smelting in the SAG Mill?

If you look at the tooltip of the dark steel balls or flint you will see how much bonus you get from using them in the SAG Mill.

**Comment by PapiDimmi** [comment]
I thought the bonus applied for the extra items you can get, like gold dust from smelting copper ore.

**Comment by MatthiasMann** [comment]
That's why there is "Main Output" and "Bonus Output".

**Comment by PapiDimmi** [comment]
I see. I’d no idea. Thanks!
