### ISSUE TITLE
[Suggestion] Dark steel door

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4144]
There’s a dark steel trapdoor, so why’s there no dark steel _door_?

**Comment by Alex-hawks** [comment]
There is already a [suggestion for a dark steel door](http://ideas.theideawall.com/EnderIO/Forum/TopicDetails/51cbd84d-6209-411f-8bab-1083664658d8) on the [suggestions tracker](http://ideas.theideawall.com/EnderIO/)

**Comment by PapiDimmi** [comment]
I don’t like using a third-party website, and that website looks really bad, too. It looks like I time travelled back to 2007. I don’t get why we can’t just post suggestions on GitHub.
