### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by MyBigFan2** [SleepyTrousers/EnderIO#4145]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
I started the game with EnderIO-1.10.2-3.1.156 and EnderCore-1.10.2-0.4.1.65-beta, then I used forge then it crashed at Phase 2.

#### What you expected to happen:
I expected the game to load up properly and I can do some config stuff.

#### Steps to reproduce:

1.Download EnderCore-1.10.2-0.4.1.65-beta and EnderIO-1.10.2-3.1.156.
2.Download forge
3.Start the game
4.I used TLauncher 2.12 you might wanna download that if the game doesn't crash.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.1.156
- EnderCore:EnderCore-1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge:My forge is TLauncher's 1.10.2 Forge (I don't need to download forge on google, it comes with TLauncher)

#### Your most recent log file where the issue was present: 

https://pastebin.com/Ary0Tg4p

**Comment by HenryLoenwind** [comment]
Sorry, we don't support pirated Minecrafts.
