### ISSUE TITLE
Suggestion - Tooltip for configured Mod Item Filters

### ISSUE THREAD

**Issue by ariosos** [SleepyTrousers/EnderIO#4146]
Mod Item Filters that are configured with mods to filter should show a tool tip with the filtered mods when holding shift and mousing over the filter in the inventory.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
