### ISSUE TITLE
Power Monitor Include Machine Buffer for emitting signals 

### ISSUE THREAD

**Issue by dovahkiin4991** [SleepyTrousers/EnderIO#4148]
With draconic evolution, using the energy core it provides for storage is great, but when trying to control how much rf is in it, there are no none outlandish ways. With the power monitor, it will detect the core (through the pylon) as a machine buffer, and therefor not emit a signal when it is near empty. Possible solutions would be just include machine buffers, add a config file that users can add blocks to capacitor bank storage, or whatever else you smart people can find out to make it work :) Please fix this

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
