### ISSUE TITLE
Water interrupts the travel anchor

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4149]
You cannot see the travel anchor if water is in the way.

![2017-04-10_22 13 15](https://cloud.githubusercontent.com/assets/25916106/24880493/eea3cb74-1e3a-11e7-8ffe-2a8ab2e27554.png)
![2017-04-10_22 13 17](https://cloud.githubusercontent.com/assets/25916106/24880492/ee97c162-1e3a-11e7-9355-5e2857fd1429.png)
****
* **[Minecraft](https://minecraft.net) version**: [1.10.2](https://minecraft.gamepedia.com/1.10.2)
* **[Forge](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) version**: [12.18.3.2272](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) (latest for 1.10.2)
* **[Ender IO](https://minecraft.curseforge.com/projects/ender-io) version**: [3.1.180](https://minecraft.curseforge.com/projects/ender-io/files/2404956) (latest for 1.10.2)
* **[EnderCore](https://minecraft.curseforge.com/projects/endercore) version**: [0.4.1.65-beta](https://minecraft.curseforge.com/projects/endercore/files/2370656) (latest for 1.10.2)

**Comment by MatthiasMann** [comment]
Do you use Optifine or a shaders mod?

**Comment by PapiDimmi** [comment]
You can probably tell from the screenshots that I don’t use a shaderpack, but I _do_ use OptiFine; however, direwolf20 encountered the same problem [in his let’s play series](https://youtu.be/b097XqfVYNY?list=PLaiPn4ewcbkGKTGBeUPqI-S3NeZ8tTSeX&t=506), and he doesn’t use OptiFine, so it’s not an OptiFine issue.

**Comment by MatthiasMann** [comment]
Verify that the issue is still persisting after you removed Optifine.

**Comment by PapiDimmi** [comment]
Did you not read my comment?

**Comment by PapiDimmi** [comment]
I just proved that the issue occurs when not using OptiFine, though.

**Comment by MatthiasMann** [comment]
Citing DW20 and whether or not he uses Optifine is not a prove.
Or did you actually test without Optifine installed?

**Comment by HenryLoenwind** [comment]
TE culling in Forge for 1.10.2 is very broken, this and all other tickets about travel anchors going out of sight randomly will have to wait for 1.11.

**Comment by PapiDimmi** [comment]
>Citing DW20 and whether or not he uses Optifine is not a prove.

I _know_ that he doesn’t use OptiFine. I won’t go through the trouble of uninstalling and reinstalling OptiFine, because I know that OptiFine isn’t the cause of this bug.

>TE culling

What does that mean?

>this and all other tickets about travel anchors going out of sight randomly will have to wait for 1.11.

So does that mean that this won’t be fixed in the 1.10.2 version of Ender IO?

**Comment by PapiDimmi** [comment]
@HenryLoenwind Can you please reply?
