### ISSUE TITLE
Staff of Traveling bug

### ISSUE THREAD

**Issue by oTKum** [SleepyTrousers/EnderIO#4150]
#### What happens:
Other random players in multiplayer sometimes teleport to the coordinates where I was supposed to teleport. This also happens with other tools such as The Ender with the Travel.
If the player using the Travel and the target player are different dimensions, teleport to the corresponding coordinates in that dimension.

____
#### Affected Versions:

- EnderIO: 3.1.179
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by HenryLoenwind** [comment]
I had a look; Ender IO only ever teleports the player that sends the network packet.
