### ISSUE TITLE
EnderIO boots cause autojump regardless of user preference

### ISSUE THREAD

**Issue by avrildev** [SleepyTrousers/EnderIO#4151]
#### Issue Description:

I have turned autojump off in my client's Minecraft settings. I am still autojumping tho.

#### What happens:

Still autojumping.

#### What you expected to happen:

Autojumping to stop.

#### Steps to reproduce:

1. Turn off autojump.

2. Wear enderIO shoes. Mine have the following traits on them:
- Custom name
- Depth Strider III
- Unbreaking III
- Protection IV
- Empowered IV
- Jump III

3. Try running up a hill.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.179
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

https://gist.github.com/avrildev/b72b74a932099758a853e323b5123954#file-latest-log

**Comment by MatthiasMann** [comment]
The dark steel armor provides step assists when powered.

**Comment by avrildev** [comment]
@MatthiasMann And how does one turn this off?

**Comment by calloatti** [comment]
I use https://minecraft.curseforge.com/projects/client-tweaks for this

> Disable Step Assist (with keybind)
There's people who hate step assist, me included. But sometimes those step-assist granting items add some other cool perks that we want. So this option lets you disable the step-assist part only. With optional keybind to toggle.

**Comment by avrildev** [comment]
@calloatti That's very useful. But can someone tell me why this is even a feature anymore? It seems like it should be removed, as it's behavior now built into Minecraft, and having it enabled by wearing a certain type of armor causes confusion, and autojump isn't favored by everyone.


At the very least, there should be a config option built into EnderIO to disable it.

**Comment by HenryLoenwind** [comment]
1. You are not jumping (which costs hunger, jumps you all over the place and is generally annoying), this is step assist, which allows you to walk up 1-block high instead of just 0.6-block high.
2. It is part of the Jump Upgrade
3. It has a hotkey

**Comment by avrildev** [comment]
@HenryLoenwind Ah. That's not something I noticed. Fair enough, if it has a hotkey to toggle it.

**Comment by qm3ster** [comment]
Step assist is nothing like auto jump, it is beautiful
