### ISSUE TITLE
Quite clear glass does not have a breaking animation

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4159]
It only shows the breaking animation on the white edges of the block.
****
**Minecraft version**: 1.10.2
**Ender IO version**: 3.1.180

**Comment by legodude17** [comment]
This might be because the breaking animation is playing, but with completely transparent particles.

**Comment by PapiDimmi** [comment]
@legodude17 What do you mean by particles? I’m talking about the animation that causes cracks to appear on the block when breaking it. This animation is played when breaking any other type of glass block from other mods or vanilla Minecraft; therefore, this is an Ender IO bug.

**Comment by legodude17** [comment]
Ah, I thought you meant the little particles that fly out of the block.

**Comment by PapiDimmi** [comment]
@HenryLoenwind Why did you close this?
