### ISSUE TITLE
1.10.2 EnderIO Conduits Drain Power From Mekanism Machines

### ISSUE THREAD

**Issue by EZKatnipz** [SleepyTrousers/EnderIO#4161]
#### What happens:
Whenever an EnderIO Energy Conduit is connected to a Mekanism power generator, the power is then drained from the generator, even while the conduit is only connected to the power generator.

#### What you expected to happen:
Basically the opposite.

#### Steps to reproduce:

1. Place down Mekanism power generator of any kind.
2. Connect EnderIO Energy Conduit to power generator.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2 - 3.1.180
- EnderCore: 1.10.2 - 4.1.65
- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2281

#### Your most recent log file where the issue was present: 

Don't believe the log contains any information that would help, but I can provide it if you would like to take a look.

**Comment by HenryLoenwind** [comment]
1. Energy is moved by "push", meaning its the generator that pushes the energy somewhere.
2. Mek is a pile of bugs that's held together by "interesting" implementations.

**Comment by EZKatnipz** [comment]
In your opinion, should I just remove Mekanism entirely from my modpack then? It does have interesting features, but most of them can be obtained through other mods.

**Comment by HenryLoenwind** [comment]
That depends on whether you can live with its bugs or not. As far as I have heard, there are not "game killer" ones, just things like this one.

**Comment by ktole1999** [comment]
until the power communication issue is resolved between these 2 mods i would suggest keeping the cables with the mod they belong to. use an energy cube as the missing link to bridge the 2 together. works for me without error.
