### ISSUE TITLE
Bug? Combining a broken spawner with an Elder Guardian Soul Vial produces a Guardian spawner, not an Elder Guardian spawner.

### ISSUE THREAD

**Issue by calloatti** [SleepyTrousers/EnderIO#4163]
I don´t know if this is an EnderIO bug or oversight or a Minecraft peculiarity. If it is a Bug I will make a full report on versions and circumstances.

**Comment by MatthiasMann** [comment]
EnderIO spawners only use the entity name and not the NBT data for spawning new mobs.
Some mobs have the same entity name (eg vanilla Skeletons and Wither Skeletons) and only differentiate by 1 or more NBT data fields.

So it would need special code to support this.

Also one could argue that the elder guardian is a boss and as such is excluded from being spawned itself.

**Comment by HenryLoenwind** [comment]
Yes, I think it classifies a boss. So it should not be possible to pick it up in the first place. However, as said, it just is a "normal" guardian with a special internal flag...

**Comment by calloatti** [comment]
Oh well, no sponges for me I guess. Spent the only 2 elder guardians I got soul vialed crafting a spawner. Did it twice because I thought I picked the wrong guardian the first time.

Anyway, it would be great to be able to have an Elder Guardian  sponge farm, you know, we need those sponges...

**Comment by legodude17** [comment]
@calloatti Just a thought, have you tried Woot?

**Comment by calloatti** [comment]
@legodude17 No, but I will now. Looks good. Thanks.
