### ISSUE TITLE
problems with item conduit taking output from farming station

### ISSUE THREAD

**Issue by c0mical** [SleepyTrousers/EnderIO#4166]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

I have a farming station, connected to a chest via item conduits. I have successfully pulled items (a hoe) from the chest, but it will not output push items to the chest, showing 'output full'

I have set both ends to input/output and even set the output/input on that side of the farming station

#### What you expected to happen:

overflow item (potatoes in this case) to go to the chest

#### Steps to reproduce:

setup farm as per https://www.youtube.com/watch?v=1hZZ-XLAgTc&t=93s (01:41)

wait for the farm to fill up its output slots

output is not sent to chest

(I have made a simpler version with just a farming station and only item conduits but the same issue persists)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.180
- EnderCore: 1.10.2 - 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

#### Your most recent log file where the issue was present: 

https://pastebin.com/6bJjzHaj

**Comment by HenryLoenwind** [comment]
Have you enabled the conduits?

**Comment by c0mical** [comment]
#facepalm

it was the redstone activation on the output face

My apologies!

**Comment by HenryLoenwind** [comment]
Not a problem, it's a common mistake.
