### ISSUE TITLE
Feature Request: Add display options when shift-right clicking a capacitor bank

### ISSUE THREAD

**Issue by calloatti** [SleepyTrousers/EnderIO#4167]
When shift right clicking a capacitor bank block face you now have 3 options: charge bar, I/O or nothing. I propose to add the following to the cycle:

![image](https://cloud.githubusercontent.com/assets/12817862/25094681/b6012012-236e-11e7-84df-f9314428641c.png)

When 2 or more contiguous faces have text display, connect them them as now. If 2 or more contiguous faces have the same text display, join them and make the text display bigger.

Examples:

![image](https://cloud.githubusercontent.com/assets/12817862/25094902/8557e4ae-236f-11e7-9758-dceb140d487b.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25094953/be946184-236f-11e7-8de2-c51cd75f6c82.png)

**Comment by MatthiasMann** [comment]
That feature already exists and is toggle by just right clicking with an empty hand on a side of a capacitor bank.

Also you completely ignored the issue template.

**Comment by calloatti** [comment]
Fine. The template is for bugs: " If this bug occurs.."

This is a feature request, so versions and log file are of little use.

And the feature exists but works differently. But no worries, everyone is entitled to have bad days.
