### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by ulkunderscore** [SleepyTrousers/EnderIO#4169]
#### What happens:
The game crashes on loading the world.
It did not crash before I exited the world the last time, just on loading it.

#### Steps to reproduce:

1. I was playing around with RFTools endergenic generators and EnderIO "decoration" blocks (machine frames and machine frames with the lines)
2. Somewhere around is a single conduit facade placed in the world on a conduit, painted with an EnderIO "invisible" block
3. There are also maybe 50 uncovered redstone conduits and a painter around.
4. Exited the world and minecraft, started up the game again later and tried to reload it.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.180  (happened first with .179 but the crash report is the same)
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

#### Your most recent log file where the issue was present: 

[Crashlog](https://pastebin.com/PjUVzJ7t)

**Comment by HenryLoenwind** [comment]
Interesting. The game tries to render the hotbar before it initialized the render manager.

You should be able to get into your game if you mcedit the decoration block from your hotbar into your main inventory.

**Comment by ulkunderscore** [comment]
That worked, thanks!

**Comment by HenryLoenwind** [comment]
Version 3.1.183 has the fix for this.
