### ISSUE TITLE
[suggestion] Frank 'n' Zombie golem

### ISSUE THREAD

**Issue by EnderiumSmith** [SleepyTrousers/EnderIO#4171]
it would work similar to the killer Joe but it would be a whole mob instead of just a head. 
it would look like the killer Joe on a body made of soularium and dark steel with 2 additional tanks on the back. it would work off nutrient distillation but might have upgrades/tools that require RF. the wireless charger would work on these. 

you can set it to patrol on certain paths and attack specific mobs. like the dark steel armor it can be upgraded but is upgraded as a whole instead of individual parts. it can also be enchanted. it should be able to collect xp. 

it comes with a recharge pad that acts as a home point and will automatically go there when low on nutrient. since it has armor built in, it can't wear armor. player heads can be used to change how the head inside the main tank looks. to bring it to life in the first place it requires a lightning strike(weather obelisk).

it requires nutrient for moving and attacking.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
