### ISSUE TITLE
Minecraft keeps crashing whilst using ender io 

### ISSUE THREAD

**Issue by joe1208** [SleepyTrousers/EnderIO#4172]
this is the crash report
[crash-2017-04-19_19.36.43-server.txt](https://github.com/SleepyTrousers/EnderIO/files/937282/crash-2017-04-19_19.36.43-server.txt)
i am using minecraft 1.7.10 and the latest forge update
can somebody please help slove this. thanks.

**Comment by HenryLoenwind** [comment]
```
java.lang.NullPointerException: Exception in server tick loop
	at hardcorequesting.QuestingData.<init>(QuestingData.java:524)
	   ^^^^^^^^^^^^^^^^
```

that's what is crashing...

**Comment by joe1208** [comment]
this didnt work has now stopped me from being able to load worlds

**Comment by legodude17** [comment]
Try reporting it to HGM

**Comment by joe1208** [comment]
what is hqm

**Comment by legodude17** [comment]
Hardcore Questing Mode, that is the mod the crashed

**Comment by joe1208** [comment]
ok
