### ISSUE TITLE
OpenModularTurrets bases not accepting power from conduits

### ISSUE THREAD

**Issue by Liiw** [SleepyTrousers/EnderIO#4173]
#### Issue Description:
Turret bases from mod [OpenModularTurrets](https://mods.curse.com/mc-mods/minecraft/224663-openmodularturrets) do not accept power directly from EnderIO energy conduits. Bases accept power from other mods' means of power transfer without issue.

#### What happens:
RF meter on the turret base is not rising. Seems to rise a little bit when breaking/placing the conduit next to the cable. Could be a block update issue.

#### What you expected to happen:
RF meter on the turret base to rise to max level, when power is supplied (it is).

#### Steps to reproduce:

1. Place down turret base (any tier).
2. Place down energy source.
3. Connect the two with an EnderIO energy conduit (I used the "ender" tier).
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.180
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2281
- Spongeforge (on the server) - 1.10.2-2281-5.2.0-BETA-2274

#### Your most recent log file where the issue was present: 

I will produce it when it is necessary.

**Comment by MatthiasMann** [comment]
As you did not provided a log I don't see which mods/libs you have installed.
So I suggest you try adding Tesla - maybe that works with OMT.
EnderIO supports Forge Energy, Tesla and RF on the conduits - but it no longer bundles the RF API as it did in earlier MC versions.

**Comment by Liiw** [comment]
Hello, thank you for your reply!

I am attaching a link to the fml-client-latest.log I uploaded to Gist: 

https://gist.github.com/Liiw/502ce4ea79da3c1815b90b60c325aaf9

Will this suffice? If not, please specify which log files do you need excactly. I reproduced the conditions prior to exiting the server. 

I also noticed that whenever breaking/replacing the conduit connected directly to the base, the RF amount would increase by 12000 RF.

**Comment by MatthiasMann** [comment]
If energy is transferred only once when placing the conduit then that looks like a bug on the OMT side.

**Comment by Liiw** [comment]
I see. I will contact OMT mod author. Thank you!
