### ISSUE TITLE
Not a bug——about repost

### ISSUE THREAD

**Issue by forestbat** [SleepyTrousers/EnderIO#4176]
I'm an editor of an Chinese Minecraft encyclopedia website——www.mcmod.cn。Now we want to repost your mod there，do you agree to give us the authority？We will still clarify the offical website www.enderio.com。

**Comment by Alex-hawks** [comment]
Just link to the downloads on Cursforge. [Here](https://minecraft.curseforge.com/projects/ender-io) is a link to the EnderIO page there
