### ISSUE TITLE
Dark Armor Will Not Charge with Assorted Charging Ttems

### ISSUE THREAD

**Issue by Pinaz9** [SleepyTrousers/EnderIO#4177]
#### Issue Description:
Note: This is in a modpack, but the author just thought it was an intended feature.

Charging items (Actually Additions batteries, Draconic Evolution flux capacitors) will not charge dark armor. 

#### What happens:
Armor sits there, petulantly refusing to accept energy from activated charging items.

#### What you expected to happen:
Armor should feed on the power, drink it like I drink the b... nevermind.

#### Steps to reproduce:

1. Install Actually Additions, Draconic Evolution, Ender IO
2. Obtain dark armor of some description, drain it of energy.
3. Attempt to charge armor with items. Armor will not charge.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: - 1.10.2-3.1.180
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

I understand that things are a little in flux (no pun intended) right now, so if this is an issue that won't get solved before MC 1.11, that's okay.

**Comment by HenryLoenwind** [comment]
This is not a bug, this is us no longer supporting outdated APIs.

**Comment by MatthiasMann** [comment]
You can work around that issue (at least for AA) by installing TESLA.
