### ISSUE TITLE
Telepad dew of void

### ISSUE THREAD

**Issue by Evilkevin22** [SleepyTrousers/EnderIO#4182]
#### Issue Description:

We are having some problems on the server regarding "Dew of the void" But we want to be able to use the telepad without to much of a problem. Is there a config were I can disable it? I've seen it being only RF in some videos.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.180
- EnderCore: 1.10,2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 8.0.99.99

**Comment by calloatti** [comment]
`\config\enderio\EnderIO.cfg`

` # The max amount of fluid in mb used per teleport. If set to <= 0 fluid use will be disabled
 I:telepadFluidUse=0
`
