### ISSUE TITLE
"We do not support pirated minecrafts" quote

### ISSUE THREAD

**Issue by MyBigFan2** [SleepyTrousers/EnderIO#4185]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
I sent a issue about a start up crash and I got this quote 
"We do not support pirated minecrafts"
I wonder if this means the mod does not support pirated minecrafts or the issue page does not help bugs for pirated minecarft users? I want to use this useful mod for an private mod pack. Please, if the case is the mod doesn't support pirated minecrafts, please, make it so the mod supports pirated minecrafts, I don't really want to spend 100+ ringgit for a mod. :(

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MyBigFan2** [comment]
This's a 1.10.2 version of minecraft. I forgot to add that

**Comment by legodude17** [comment]
@MyBigFan2 AFAIK it is against the EULA to make a mod that supports pirated minecraft. Also, what do you mean "I don't really want to spend 100+ ringgit for a mod"? The mod is free and open source.

**Comment by MyBigFan2** [comment]
I don't want to spend 100+ ringgit to buy minecraft and use the mod. Because I am just a kid and I have to collect money to buy the game . I use pirated minecraft.

**Comment by mindforger** [comment]
how old are you? to be a kid is no excuse, but maybe your parents need a lesson to tell their kid to not steal stuff

**Comment by HenryLoenwind** [comment]
Stop stealing. 'Nuff said.
