### ISSUE TITLE
Panting machine don't work propably

### ISSUE THREAD

**Issue by 123456789101010100** [SleepyTrousers/EnderIO#4187]
In Sky Factory 3, I try to use the Painting Machine to paint my SAG Mill with other mod machine and then Minecraft crashed. Next time I only looked at there and it crashed again. Third time I set lava over it and broke it so it din't crash any more. Can someone fix this?

**Comment by MatthiasMann** [comment]
As you ignored the issue template completely we do not have any of the required information to help you.

**Comment by 123456789101010100** [comment]
What the "Logfile Missing" and "Report Incomplete" mean?

**Comment by bookerthegeek** [comment]
What it means is that you did not read when you created this issue.
