### ISSUE TITLE
[Feature Request] Ability to rotate items painted as slabs to the upper half of the block

### ISSUE THREAD

**Issue by forrester-marc** [SleepyTrousers/EnderIO#4188]
I am currently using conduit facades on fluid conduits carrying lava to create a strip lighting system around the floor.  The ability to do this in ceilings would be entirely awesome.

![enderio lighting](https://cloud.githubusercontent.com/assets/20112602/25559712/1ff27fc0-2d38-11e7-96a3-edb1a06a0dc9.png)

**Comment by HenryLoenwind** [comment]
This should work with the yeta wrench. Switch it to "facade" mode and right click the facade.

If not, I'll have to investigate what broke...

**Comment by HenryLoenwind** [comment]
PS: Unless you are talking about an Ender IO version that doesn't have that feature.

**Comment by forrester-marc** [comment]
EnderIO-1.10.2-3.1.183 - Is there documentation of the different wrench modes?  I'm not sure which icon represents facade mode.

**Comment by VT-14** [comment]
That sounds like a really cool idea so I tried it in a testing world.  Unfortunately, facade mode didn't work on facades painted as Stone Slabs (I tested a facade painted as an Oak log to make sure I was doing it correctly).  Ender IO 1.10.2-187


The Yeta Wrench modes will hide all other conduits (so you can see/interact/remove one particular type of conduit from a bundle of conduits).  "Facade Mode" is either the red X or the Wrench and Gear icon.  Both will let you see the facade as it is painted and allow it to be rotated using the Wrench's right click rotate feature.  It's worth noting that normal Stone Slabs cannot be flipped by the wrench either (logs can).

**Comment by HenryLoenwind** [comment]
thx VT-14

**Comment by forrester-marc** [comment]
Not just me being dense, then?  Good to know :D

**Comment by HenryLoenwind** [comment]
no, I think I now have all data I need. I'll leave the tag on for statistical reasons ;)
