### ISSUE TITLE
Various cases of insufficient server-side validation enabling arbitrary chunk generation, item creation, and teleportation

### ISSUE THREAD

**Issue by pau101** [SleepyTrousers/EnderIO#4189]
In several serverbound packets which query a block position a `World#isBlockLoaded` precondition is neglected enabling malicious packets to cause the generation of arbitrary chunks, consuming an excessive amount processing power and memory on the server:
* [PacketRedstoneMode](https://github.com/SleepyTrousers/EnderIO/blob/3e9c17e01f1b494c39827e6d84e00ba95a4493ff/src/main/java/crazypants/enderio/machine/PacketRedstoneMode.java#L55)
* [PacketMode](https://github.com/SleepyTrousers/EnderIO/blob/3e9c17e01f1b494c39827e6d84e00ba95a4493ff/src/main/java/crazypants/enderio/machine/PacketIoMode.java#L74)
* [PacketIoMode](https://github.com/SleepyTrousers/EnderIO/blob/3e9c17e01f1b494c39827e6d84e00ba95a4493ff/src/main/java/crazypants/enderio/machine/PacketIoMode.java#L74)
* [PacketItemBuffer](https://github.com/SleepyTrousers/EnderIO/blob/3e9c17e01f1b494c39827e6d84e00ba95a4493ff/src/main/java/crazypants/enderio/machine/PacketItemBuffer.java#L50)
* [PacketCapBank](https://github.com/SleepyTrousers/EnderIO/blob/3e9c17e01f1b494c39827e6d84e00ba95a4493ff/src/main/java/crazypants/enderio/machine/capbank/packet/PacketCapBank.java#L57)
* [PacketClientState](https://github.com/SleepyTrousers/EnderIO/blob/3e9c17e01f1b494c39827e6d84e00ba95a4493ff/src/main/java/crazypants/enderio/machine/alloy/PacketClientState.java#L46)
* [PacketAccessMode](https://github.com/SleepyTrousers/EnderIO/blob/3e9c17e01f1b494c39827e6d84e00ba95a4493ff/src/main/java/crazypants/enderio/teleport/packet/PacketAccessMode.java#L53)
* [PacketOpenAuthGui](https://github.com/SleepyTrousers/EnderIO/blob/55f22f15f1477c972113edaf0cb82e4683776a85/src/main/java/crazypants/enderio/teleport/packet/PacketOpenAuthGui.java#L42) ([Consecutive call](https://github.com/SleepyTrousers/EnderIO/blob/f69f02c03206e98d27a0d9bce0dd308f581f11c0/src/main/java/crazypants/enderio/GuiID.java#L118) invokes World#getBlockState)
* [PacketLabel](https://github.com/SleepyTrousers/EnderIO/blob/3e9c17e01f1b494c39827e6d84e00ba95a4493ff/src/main/java/crazypants/enderio/teleport/packet/PacketLabel.java#L61)
* [PacketConduitProbe](https://github.com/SleepyTrousers/EnderIO/blob/a646fbbfc53504f9d315f02ff679218876866b85/src/main/java/crazypants/enderio/item/PacketConduitProbe.java#L118)
* [PacketOpenConduitUI](https://github.com/SleepyTrousers/EnderIO/blob/168127865ea961e5671ab7b764184f03f6ed0995/src/main/java/crazypants/enderio/conduit/packet/PacketOpenConduitUI.java#L50)

Most of the above packets could be utilizing [MessageTileEntity](https://github.com/SleepyTrousers/EnderCore/blob/925499e89a311557a46ba882b4825c32e1312543/src/main/java/com/enderio/core/common/network/MessageTileEntity.java) which recently got this vulnerablity resolved. As well, many of these packets should be ensuring that the player is within reach distance.

[PacketUpdateLocationPrintout](https://github.com/SleepyTrousers/EnderIO/blob/0b25453a85110951349dd6eb022c4c8ba859509e/src/main/java/crazypants/enderio/teleport/telepad/packet/PacketUpdateLocationPrintout.java#L57) enables a malicous client to add arbitrary items to their inventory due to a lack of server-side validation.

[PacketDarkSteelPowerPacket](https://github.com/SleepyTrousers/EnderIO/blob/c7d68a342d130da6b99082403d385a018be52012/src/main/java/crazypants/enderio/item/darksteel/PacketDarkSteelPowerPacket.java#L37) enables the arbitrary mitigation of fall damage.
_Note: very minor considering it is possible with a vanilla packet_

[PacketTravelEvent](https://github.com/SleepyTrousers/EnderIO/blob/8e42cb43afa6b8093349ca04f42feb3da48c3ece/src/main/java/crazypants/enderio/teleport/packet/PacketTravelEvent.java#L104) enables arbitrary teleportation due to the lack of server-side validation.

This report is targeted towards 1.10 but these issues exist in all versions which contain the specified classes.

**Comment by HenryLoenwind** [comment]
Chunk loading attack? That's a new one. Does vanilla really protect against that?

**Comment by HenryLoenwind** [comment]
PacketTravelEvent needs a complete rewrite of all travel-related code. It's been in the queue for ages, as nobody wants to touch those. I think the biggest stopper here is the server-side raytracing which has to match what the player sees.

**Comment by pau101** [comment]
The vanilla packets do indeed protect against arbitrary chuck generation.

**Comment by HenryLoenwind** [comment]
- [x] PacketRedstoneMode
- [ ] PacketMode
- [ ] PacketIoMode
- [ ] PacketItemBuffer
- [ ] PacketCapBank
- [ ] PacketClientState
- [ ] PacketAccessMode
- [ ] PacketOpenAuthGui (Consecutive call invokes World#getBlockState)
- [ ] PacketLabel
- [x] PacketConduitProbe
- [x] PacketOpenConduitUI
- [x] PacketUpdateLocationPrintout
- [ ] PacketTravelEvent

**Comment by HenryLoenwind** [comment]
I call this finished, as the PacketTravelEvent needs major rework.
