### ISSUE TITLE
Cannot Place Conduits at Block Level 256 (last allowed height)

### ISSUE THREAD

**Issue by HIghCommander540** [SleepyTrousers/EnderIO#4191]
#### Issue Description:
This occurs in DW20 MC1.10 - version 1.8.1 

#### What happens:
Cannot place energy conduits at block level 256, even though all other items are allowed.

#### What you expected to happen:
Conduits allowed to be placed at 256 (not above), I have other items there.

#### Steps to reproduce:

1.Go to block level 256
2. Attempt to place energy conduit
3. Nothing happens
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.186
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
height goes from 0-255...
