### ISSUE TITLE
EnderIO-  * An unknown AE2 API is installed (rv3 from APPLIEDENERGISTICS2-RV3-BETA-6.jar).

### ISSUE THREAD

**Issue by mehga** [SleepyTrousers/EnderIO#4194]
#### Issue Description:
All the mods load and initialise but when the title screen is about to load it crashes.

#### What happens:

All the mods load and initialise but when the title screen is about to load it crashes.
I think this is causing the crash but I'm not sure.   EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from APPLIEDENERGISTICS2-RV3-BETA-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                  * An unsupportted old RF API is installed (1.7.10R1.0.1 from BUILDCRAFTADDITIONS-1.7.10-2.2.5.jar).
                    Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions.
                  * Our API got loaded from ENDERIO-1.7.10-2.3.0.429_BETA.jar. That's unexpected.
                  * Our API got loaded from ENDERIO-1.7.10-2.3.0.429_BETA.jar. That's unexpected.
                  * Our API got loaded from ENDERIO-1.7.10-2.3.0.429_BETA.jar. That's unexpected.
                  * Our API got loaded from ENDERIO-1.7.10-2.3.0.429_BETA.jar. That's unexpected.

#### What you expected to happen:

The game to load

#### Steps to reproduce:

1. Open Minecraft
2. Wait for all mods to initialize
3. Crashes while the title screen is about to load
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: ENDERIO-1.7.10-2.3.0.429_BETA
- EnderCore:  ENDERCORE-1.7.10-0.2.0.36_BETA
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1614-1.7.10-universal

#### Your most recent log file where the issue was present: 

https://pastebin.com/MPRuVpPp

**Comment by HenryLoenwind** [comment]
You want me to magically fix your system? Isn't it enough that Ender IO **tells** you what may be wrong?

**Comment by mindforger** [comment]
to give you a headsup, it is absolutely no problem rv2 and rv3 are fully compatible, rv3 is just way more debugged :)
