### ISSUE TITLE
Dark Steel Armor Elytra Rendering Crash - Please Read Complete Disclaimer First

### ISSUE THREAD

**Issue by Avetho** [SleepyTrousers/EnderIO#4195]
Disclaimer - Hear me out here, I know I shouldn't necessarily post about a problem in a modpack on the github of one mod, but I think the modpack creator would come here with the same report anyways as the problem seems to be an entity rendering bug in one mod, precisely EnderIO. If you wish to remove this by virtue of it being with a modpack, I urge you to give it a once over first and then remove it if you see it fit, my apologies at that point.

#### Issue Description:

Trying to equip fully upgraded dark steel armor from JEI with full power and all upgrades, with Elytra upgrade on chestplate causes game to crash instantly.

#### What happens:

I put on the chestplate and the game force closed with an error starting with:
[B#349]  Description: Rendering entity in world
[B#349]  java.lang.NoSuchFieldError: ELYTRA
I assume this is an Elytra rendering problem such as the field being misnamed. I've done this before in some of my programs.

#### What you expected to happen:

Everything to act normally with the regular features expected, like flying with the elytra on a barren planet.

#### Steps to reproduce:

1. Get a fully upgraded dark steel chestplate with the Elytra upgrade from JEI in Forever Stranded by GWSheridan on the technic launcher
2. Put it on your character's chest slot
3. Game crash, world crashes whenever I open my inventory or go into 3rd person. Any time I see the armor rendered on my player.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.65
- Minecraft: 1.7.10
- Forge: 12.18.3.2281

#### Your most recent log file where the issue was present: 

[crash-2017-05-02_17.33.03-client.txt](https://github.com/SleepyTrousers/EnderIO/files/972079/crash-2017-05-02_17.33.03-client.txt)

**Comment by Avetho** [comment]
Thankfully I can rescue the world by using a non-player-rendering inventory with the armor slots to remove the armor, like the EnderIO capacitor banks. Glad that's there :+1:

**Comment by HenryLoenwind** [comment]
What is crashing here is unmodified vanilla code accessing data from `com.mojang.authlib.minecraft`. Are you using a cracked Minecraft?

**Comment by Avetho** [comment]
I may have started up the wrong launcher. My bad :/

**Comment by SiebeDW** [comment]
Im getting this issue on my offline mode server. One of my players disconnects after joining.
Error from the player: https://paste.dimdev.org/epuqijowif.mccrash
EnderIO: 5.0.50
EnderCore: 1.12.2-0.5.65
Minecraft: 1.12.2
Forge: 14.23.5.2844
Optifine: Yes
SpongeForge: No
