### ISSUE TITLE
Alloy Smelter not showing changed Vanilla Furnace recipe in JEI

### ISSUE THREAD

**Issue by The-Arcanian** [SleepyTrousers/EnderIO#4196]
#### Issue Description:
Vanilla Furnace recipe changed with CraftTweaker works in Alloy Smelter but does not show the change in JEI.

#### What happens:
When I use MineTweaker to remove a Vanilla Furnace recipe, and then add one with the same input but a different output, it works in the Alloy Smelter but the shown recipe when I try to look it up is the old removed one.

#### What you expected to happen:
The new recipe to show and the old one to not show.

#### Steps to reproduce:

1. Use CraftTweaker to remove a Vanilla Furnace recipe.
2. Use CraftTweaker to add a Vanilla Furnace recipe with the same input as the old one but with a different output.
3. Look up uses for the input item in the Alloy Smelter.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.186
- EnderCore: 0.4.1.65 beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

#### Your most recent log file where the issue was present: 
https://gist.github.com/The-Arcanian/4bb8540865dc97beb490c002e14e5d52

**Comment by HenryLoenwind** [comment]
JEI asks us for our recipes once when the world is loaded. If anyone changes recipes after that, they have to convince JEI to ask us again.

**Comment by mezz** [comment]
Why does EnderIO repeat the vanilla smelting recipes in its own category? 
I think you should just add the Alloy Smelter as a category crafting item for the vanilla smelting recipes. Then only unique EnderIO recipes that you control are in the Alloy Smelter category, and nothing is repeated.

**Comment by HenryLoenwind** [comment]
@mezz couple of reasons, I think (guessing because Crazy did them originally): (1) to show the RF cost, (2) to show teh recipes if the user clicks on the "chow recipes" button of the machine, (3) to show the correct outputs (we have an oredict mapping config)

**Comment by mezz** [comment]
Ok. This will need to be handled in EnderIO's CraftTweaker integration's JEI integration.
