### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by Sossouille** [SleepyTrousers/EnderIO#4200]
**#### Issue Description:**

Server Crash on startup.

**#### What happens:**

Server Crash on startup.

**#### What you expected to happen:**

**#### Steps to reproduce:**

1. Restart server

**#### Affected Versions (Do *not* use "latest"):**

- EnderIO: 1.10.2-3.1.188
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

**#### Your most recent log file where the issue was present:** 

https://pastebin.com/0NTSkXkb (crash-2017-05-05_16.34.58-server)
https://pastebin.com/2YuR1987 (latest)
https://pastebin.com/U2LW3HEJ (fml-server-latest)

**Comment by HenryLoenwind** [comment]
#4199

**Comment by Sossouille** [comment]
Again, problem persists

**Comment by blazedd** [comment]
Also having this issue: https://pastebin.com/hcJB2Ni1

**Comment by blazedd** [comment]
This is fixed in version 1.10.2-3.1.189.
