### ISSUE TITLE
[Suggestion] Additional types of obelisks

### ISSUE THREAD

**Issue by Liiw** [SleepyTrousers/EnderIO#4201]
Hello!

I have been using EnderIO for quite some time and I must say that this mod is excellent! I have recently experimented with obelisks and it got me thinking about some additional obelisks I wish there were:

**No flight obelisks**
They would disable all jetpacks and creative flight equipment in their area of effect, except for OP-s of course. They could also be divided into two: an EMP obelisk for jetpacks etc; and a Disenchantment obelisk for creative flight equipment such as flying rings or dragon scale armor etc. They could also have a prewarning range for people to reconsider before entering the aoe.

The reasoning for these is that although it does not bother me when people are enjoying the benefits of flight, sometimes there need to be no-fly zones.

**Warding obelisk**
These would prevent people except for the owner (and perhaps people permitted by the owner) from breaking/placing blocks and manipulating objects in their aoe.

**Defense nullifier obelisk**
These would negate all armor of all players (and perhaps mobs) ecxept for the owner (and permitted friends). This would make it possible to have a safespace from aggressive players. Since these would mainly be defensive, they shouldn't have an enormous range. They should also require input of enormous power for prolonged time before becoming active (e.g. 10kRF/t for 40 minutes) as well as exponentially increased power consumption for each player's defense being nullified. This would  make it harder for someone to use it as an assault weapon.

**Also an idea for a feature regarding multiple obelisks:** 
Have the ability for obelisks to stack on top of each other like a totem pole or form a multiblock, when placing next to each other (e.g. five obelisks in a + formation). These multiblocks would be able to share energy between the obelisk bases from one source. It would be great to have the multiblock accepting one single redstone conduit, but the different obelisk bases could be configured to be active with different colored RS signals or all at once with one color.  Also have the obelisk floating elements intermingle on either the center of the + shaped multiblock or at the top of the totem pole.

These were the ideas I had about features I would like to see implemented. Please let me know, what you think about these.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
Most of them fall into the area of "right management", something Ender IO does not do. There are specialized mods out there for that.

**Comment by Liiw** [comment]
I see. Thank you for your feedback!
