### ISSUE TITLE
Inventory Panel Bugs

### ISSUE THREAD

**Issue by whitestarx0312** [SleepyTrousers/EnderIO#4202]
#### Issue Description:
1) Inventory panels display the incorrect amount of items stored.
2) There is a weird delay in seeing items still in the system after you take them out, and also a delay in items showing up after you put them in.
3) When shift clicking recipes in from JEI, the panel does not balance the recipe correctly.

#### What happens:
1) The panel displays item counts higher than they really are and upon taking the items out you are short items.
2) Items still show up in the system for a couple seconds even though you removed them. They also don't show up immediately when you put them in and sometimes require you to close the panel and reopen it.
3) When you shift click in a recipe, it only puts the majority of items in one slot. For instance, when you have 32 planks in a system and you shift click in the crafting table recipe, it will only fill 2/4 of the slots with wood.

#### What you expected to happen:
1) The correct number of items is displayed.
2) Items show up or go away as you put them in or take them out.
3) The panel will fill the crafting slots given the maximum amount of items present in the system.

#### Steps to reproduce:

1. Store a wide array of items in different quantities and some of them will be wrong. (Especially enchanted items)
2. Quickly take items in and out of the system and pay attention to what the panel says you still have available.
3. Try to craft a few recipes in the panel and the recipes don't balance the slots correctly, favoring some and leaving others completely empty.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.186
- EnderCore: EnderCore-1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: forge-12.18.3.2281

#### Your most recent log file where the issue was present: 

https://www.dropbox.com/s/nv0s35501j7zp02/latest.log?dl=0
http://imgur.com/a/skjVu

**Comment by MatthiasMann** [comment]
Looks like you have 2 connections to your storage - also update to the latest build (189+) as that has a fix for disable conduit connections to the inventory storage.

**Comment by whitestarx0312** [comment]
So updating to the latest build will fix all three issues I'm having?
