### ISSUE TITLE
Inventory System Storage Bug

### ISSUE THREAD

**Issue by whitestarx0312** [SleepyTrousers/EnderIO#4203]
#### Issue Description:
Inventory system storage is not storing its maximum capacity. 

#### What happens:
You start filling up the system storage with items and it caps out even though it is supposed to hold more.

#### What you expected to happen:
It would hold its full capacity.

#### Steps to reproduce:

1. Attempt to fill a system storage and it will cap out.

...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.186
- EnderCore: EnderCore-1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: forge-12.18.3.2281

#### Your most recent log file where the issue was present: 
https://www.dropbox.com/s/nv0s35501j7zp02/latest.log?dl=0
http://imgur.com/a/eaz8v

**Comment by VT-14** [comment]
The Inventory System Storage blocks are like massive chests.  They have a limited number of slots available.  What is most likely going on is that all slots are full, but the stacks are not (so TOP shows there is more room available).

**Comment by whitestarx0312** [comment]
Oh so these work similar to AE cells? I didn't know that.

**Comment by MatthiasMann** [comment]
@whitestarx0312 no - the inventory storage *are* chests without a GUI - you can only access them via automation (conduits, hoppers etc).

And they have the remote awareness upgrade build in - so you don't need one on the conduit connecting to it.

**Comment by HenryLoenwind** [comment]
> so you don't need one on the conduit connecting to it.

Which reminds me; in case anyone asks (or opens a bug report), with the latest version you cannot insert an awareness upgrade into the conduit when it is connected dto a storage anymore.
