### ISSUE TITLE
Farming Station doesn't farm creeper chili crystals from LCRDRFS

### ISSUE THREAD

**Issue by Lykrast** [SleepyTrousers/EnderIO#4204]
#### Issue Description:

As said in the title, the Farming Station won't harvest creeper chili crystals from the Laser Creeper Robot Dino Riders From Space mod (abreviated in the title). Even if it's probably not a very popular mod it would be nice to have support for it.

____
#### Affected Versions:

- EnderIO: 3.1.183
- EnderCore: 0.4.1.65
- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- [Laser Creeper Robot Dino Riders From Space](https://minecraft.curseforge.com/projects/laser-creeper-robot-dino-riders-from-space): 1.2.10

**Comment by HenryLoenwind** [comment]
I'd prefer it if the authors would implement one of the standard Forge or Vanilla plant interfaces. Then their stuff would instantly work with all harvesting machines from all mods...
