### ISSUE TITLE
powered spawner - endermen

### ISSUE THREAD

**Issue by c0mical** [SleepyTrousers/EnderIO#4207]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

spawner block just explodes / breaks when adding power, I've tried power buffers etc to reduce the amount of power that goes to it but doesnt seem to make a difference

other spawners are fine (that I've tried so far) just endermen spawner that have the issue

#### What you expected to happen:

spawns

#### Steps to reproduce:

create power spawner for endermen
apply power

____
#### Affected Versions (Do *not* use "latest"):

EnderIO: 1.10.2-3.1.180
EnderCore: 1.10.2 - 0.4.1.65-beta
Minecraft: 1.10.2
Forge: 12.18.3.2281

#### Your most recent log file where the issue was present: 

https://pastebin.com/cHqrBjKM

**Comment by MatthiasMann** [comment]
Is the spawner config file modified from the default one?

**Comment by c0mical** [comment]
not that I am aware

**Comment by c0mical** [comment]
let me clear it and try a fresh one

**Comment by c0mical** [comment]
sorry I was being a dingbat. I was trying to power an empty spawner not the enderman one right next to it :(

thanks for replying

**Comment by MatthiasMann** [comment]
heh - stuff like that happens :)

**Comment by calloatti** [comment]
> sorry I was being a dingbat. I was trying to power an empty spawner not the enderman one right next to it

Was going to tell you this. We have all been there and felt like idiots afterwards too. Don't worry.

**Comment by HenryLoenwind** [comment]
I feel like that every time I want to add an emoji reaction to a post in here...and hit the "edit comment" instead.
