### ISSUE TITLE
Remove the openjdk7 build job in .travis.yml

### ISSUE THREAD

**Issue by xsun2001** [SleepyTrousers/EnderIO#4211]
The code of 1.10's EnderIO used some java8's new features such as default method. But Travis CI build config still uses openjdk7 to build. And it caused the failure of some PRs. I suggest to remove openjdk7 in .travis.yml to prevent the failed build.

**Comment by HenryLoenwind** [comment]
Ender IO for 1.10.2 is still targeting Java6...

**Comment by mindforger** [comment]
to be honest, why staying on that version (i do not want to start an argument) because even minecraft itself provides a (truly outdated) java8 runtime by default
i just want to have some understanding for the decision (as i feel others may start an argument over that fact)

**Comment by tterrag1098** [comment]
because that is only on the new launcher which not everyone has access to. Once 1.12 is out and usable, we will officially move to j8 as vanilla has.

**Comment by mindforger** [comment]
thank you for the answer :) .. i honestly was under the impression the old launcher is dead already

**Comment by tterrag1098** [comment]
It mostly is, but the point is that vanilla supports j6, and so does forge, thus so do we.

**Comment by xsun2001** [comment]
Thanks for your response. It seems that it is not the time.
