### ISSUE TITLE
Electromagnet still works in spectator mode.

### ISSUE THREAD

**Issue by JaSpr** [SleepyTrousers/EnderIO#4214]
#### Issue Description:
When in spectator mode, if I go anywhere near entities, they will come toward me and end up getting picked up.  Without the electromagnet, you cannot even pick up items in spectator mode, as you're not supposed to be able to interact with the world at all.

#### What you expected to happen:
Electromagnet should NOT pull in (or in any way affect) items in the world, while in spectator mode.

- EnderIO: 1.10.2-3.1.180
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- ModPack: SkyFactory 3 (3.0.9)

**Comment by legodude17** [comment]
Does this occur with only EnderIO and EnderCore?

**Comment by JaSpr** [comment]
hm, I'd have to test.  Not sure.

**Comment by HenryLoenwind** [comment]
(fixed for 1.11)
