### ISSUE TITLE
Vacuum chest filters not working

### ISSUE THREAD

**Issue by kingchills** [SleepyTrousers/EnderIO#4215]
#### Issue Description:
Placing an basic item filter in a vacuum chest does not work as expected.

#### What happens:
Items are not accepted into the chest (whitelist) or excluded from the chest (blacklist) that are contained in the filter.

#### What you expected to happen:
If items are whitelisted, the chest should suck them up from within the range.  If the items are blacklisted they should not be sucked up by the chest if they are in range.

#### Steps to reproduce:

1. Place down a vacuum chest
2. Insert a basic item filter into the filter slot of the chest.
3. Add one or more items to the filter set to whitelist. 
4. Throw the items added to the filter on the ground along with some other items not on the filter.
5. Notice that items around the chest are not being sucked in, regardless if they match the filter or not.
6. Switch the filter to blacklist.
7. Notice that all items are now being sucked into the chest, regardless if they match the filter or not.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.186
- EnderCore: 0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

#### Your most recent log file where the issue was present: 
[Gist containing latest.log and fml-client-latest.log](https://gist.github.com/kingchills/440ea8a6ec8ddedf989962d1f6e0af40)

**Comment by tterrag1098** [comment]
This should already be fixed in the latest version (you are 4 builds behind)

**Comment by kingchills** [comment]
Ahhs, thanks for the heads up.  I didn't realize there were new alpha builds.  I had just grabbed the one in the Twitch App.
