### ISSUE TITLE
FOV bug with Dark Leggings - Speed

### ISSUE THREAD

**Issue by spc43893** [SleepyTrousers/EnderIO#4216]
#### Issue Description:
I'm playing a custom modpack. Single player, everything is fine. When someone else joins and they wear the Dark Leggings and toggle the speed boost, their FOV rapidly toggles back and forth between normal and zoomed in. Mine (as the host) do not cause this. If they host and I join, however, the FOV rapid toggle happens to me.

A second issue is that the second player, when joining my game, has issues with powering up the dark steel armor. Eg, trying to add the second level of speed boost just uses the XP levels and dumps the items (armor and upgrade item) on the ground w/o the upgrade. If the items are handed to me (the host) I can upgrade them normally. It seems to affect anything with multiple levels (Empower, Speed) - the initial level works fine but not past that.

#### What you expected to happen:
For the non-host to not get insta-vomits from the screen wobbling.

- EnderIO: 1.10.2-3.1.190
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

**Comment by Ravalli03** [comment]
I am also having the same issue with using the speed upgrade on  the leggings, with the screen zooming in and out. I'm playing single player with the most up to date mod pack of "All the Mods" for version 1.10.2

**Comment by einsteinsci** [comment]
I can confirm, I have the same issue with Sky Factory 3 (Ender IO version 1.10.2-3.1.193.

**Comment by mindforger** [comment]
that was an issue back then in 1.7.10 with another mod ... i believe ichuns or modular power suit ... one tried to use the effect for scoping and keeps resetting the FOV while wearing the boots

please try a binary search with your modpack until you find the mod combination causing this!

Binary search means, you remove half the mods and check for the issue, if it persists, remove again half the mods left over 
if you do not experience the issue anymore, restore the half and remove the other half .... until you find the combo

**Comment by HenryLoenwind** [comment]
If I remember correctly, there's a config setting to disable FOV correction for the dark steel armor.

I don't think this is caused by another mod, as it happens to a player not wearing the armor. This seems to be problem with the client being a server for another player. I hate LAN mode ;)

**Comment by roboderpy** [comment]
Any way to disable that in current (1.12) version? It is really annoying

**Comment by grydian** [comment]
I believe it's optifine's dynamic fov.  I disabled that and now have no problems with the armor and fov issues.  You can do it in the options in game.
