### ISSUE TITLE
Farming Station Crash with Mystical Agriculture [1.10.2]

### ISSUE THREAD

**Issue by ImperfMage** [SleepyTrousers/EnderIO#4218]
#### Issue Description:
Basically game crashes when I put in the farming station , t3 inferium seeds from mystical agriculture

#### What happens:

So i just created a farming station , and I was putting in the t3 seeds of Inferium from Mystical Agriculture. And my game crashed , and when i try to re enter the world it continues to crash

#### What you expected to happen:

To farm the seeds, and harvest without crashing 

#### Steps to reproduce:

1.Make farming station 
2.put the tier 3 inferium seeds in
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.1.190
- EnderCore:1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge:12.18.3.2281

#### Your most recent log file where the issue was present: 

[Log file
](https://docs.google.com/document/d/14CHXzkLekSJ4AK-_GW9e05Wb6GMDYI1IejbL0G3lEqk/edit?usp=sharing)

**Comment by ImperfMage** [comment]
@HenryLoenwind  I put the log file as the link

**Comment by ImperfMage** [comment]
So after further testing , I found out , everything works fine when using normal dirt, but once I use a BoP dirt it automatticaly crashes

**Comment by HenryLoenwind** [comment]
All I get is an empty Google Docs document,

Guessing from your comment, I'd say your BoP is outdated.

**Comment by ImperfMage** [comment]
oops , sorry I can fix the doc , and the version of BoP is 1.10.2-5.0.0.2162  .. which for me shows the latests ver.

**Comment by HenryLoenwind** [comment]
Found it, that's a BoP error. I would send you there to report it, but as I'm the one who'll have to fix it anyway...
