### ISSUE TITLE
Farming Station Crash after login (Sponge server)

### ISSUE THREAD

**Issue by mkrtes** [SleepyTrousers/EnderIO#4220]
#### Issue Description:
Crash server after login
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.190
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Sponge: spongeforge-1.10.2-2281-5.2.0-BETA-2317

#### Your most recent log file where the issue was present: 

Crashlog: https://pastebin.com/mCUi7wuN

**Comment by HenryLoenwind** [comment]
#4217
