### ISSUE TITLE
KillerJoe potentially crashing server.

### ISSUE THREAD

**Issue by mauroh135** [SleepyTrousers/EnderIO#4222]
#### Issue Description:
Placed down killer joe and gave it the End sword and left it going with an enderman spawner whilst I went upstairs.

#### What happens:
Server crashed after I'm assuming the endermen spawner kicked in. Can't even restart the server because the server crashes on start.

#### What you expected to happen:
Killerjoe to work and not crash server and farm my endermen.

#### Steps to reproduce:

1. Place killer joe and give him the end sword.
2. place endermen spawner 2 blocks away and leave area.
3.wait for endermen to spawn and potential crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.7.10-2.3.0.429_beta
- EnderCore:EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1614

#### Your most recent log file where the issue was present: 
https://pastebin.com/kJ8vTNNr

**Comment by HenryLoenwind** [comment]
see https://github.com/WildBamaBoy/minecraft-comes-alive/issues/817

**Comment by Lokibane** [comment]
I have the same issue and the same steps to reproduce.  I am using Crafting of The Titans pack and there is no MCA in the pack.

**Comment by MatthiasMann** [comment]
@Lokibane then you can't have the same crash - don't do "me too" reports when your setup is different in the central part of the issue at hand.
