### ISSUE TITLE
Feature request: Pause conduit

### ISSUE THREAD

**Issue by 7eggert** [SleepyTrousers/EnderIO#4224]
#### What you expected to happen:

1) Add a condiut, e.g. an item or a fluid conduit
-or-
1) Place a tank / machine (e.g. the vat) next to a fluid conduit
2) Select the correct settings

#### What happens:

- Chests fill with random stuff, spread their contents; from and to channels of different colors
- Before you even have a chance to change anything or while cycling through the settings, a tank gets filled or extracted from, filling it or the conduit with the wrong liquid.

#### What's my idea 1:

- A conduit clamp
- adds to a conduit bundle like adding a conduit
- looks like a small block around the center of the conduit
- Clamped conduits don't interact with anything but other conduits (it does not separate the conduit network)
- Crafting: 1 Conduit binder, 1 Wool (bonus idea: Colors ...)
- Removing: Behaves like a conduit; Yeta wrench mode

#### What's my idea 2:

Have a way to change conduit settings that would be available if there was a machine - before actually placing it. (Also helps while splitting/reconnecting conduits in confined spaces)

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
