### ISSUE TITLE
Feature request: Yeta googles

### ISSUE THREAD

**Issue by 7eggert** [SleepyTrousers/EnderIO#4225]
Yeta googles is a way to have the yeta wrench transparency effects while not holding the wrench.

Variant a) Put the wrench into the head slot
Variant b) Craft a yeta googles "helmet" using a wrench and a glass block

As long as you don't use a tool binding the yeta key, it will toggle like when holding the wrench. The settings of a wrench are synchronized with the helmet's settings. Other yeta tools (conduit probe) will override the helmet's effect while in hand until you grab something else.

(Bonus idea, IDK if it's easy: Variant b may behave like an oxygen helmet if you have a mod with e.g. space helmets or diving gear.)

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
