### ISSUE TITLE
Feature request: Name the yeta modes // probe modes

### ISSUE THREAD

**Issue by 7eggert** [SleepyTrousers/EnderIO#4226]
After using the yeta wrench for dome time, I found the modes:
- RS conduit
- Item conduit
- Energy condiut
- liquid conduit
- conduit cover?
- huh?
- What's that?
- IDK!
- ...

Having names would tell me what it's supposed to do. For now I just select a different mode until I can work with that.

Also when not being an experienced user, telling the probe modes apart isn't as easy as it should be. At first I had to try it out, too. Maybe it's enough to colorize "probe mode" and "copy mode" using the corresponding colors.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
