### ISSUE TITLE
[Feature/Addon Request] Better farm management GUI.

### ISSUE THREAD

**Issue by Mystara0001** [SleepyTrousers/EnderIO#4228]
An interface add-on (Maybe through a machine upgrade) for the farm that would allow the user to designate each square up to the max (15 x 15, not counting the center) as to which seed to plant there?

Lock is defined as the current lock system for the GUI.
Unlock is defined as the current unlock system for the GUI.
Exclude is defined as completely ignoring or skipping that spot. (i.e. treating as if that spot were obstructed so not planting or harvesting within.

The user should be able to:
Lock/unlock/exclude individual squares.
Lock/unlock/exclude entire rows/columns.
Lock/unlock/exclude squares via group selection by mouse. (Think standard Windows selection rules. Left click for first item. Ctrl+Click for non contiguous items. Shift + click on last item for contiguous selection.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
