### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Siriuo** [SleepyTrousers/EnderIO#4229]
#### Issue Description:
Not sure if the issue is due to storage drawers or enderio. Hopefully the crash report will help.

#### What happens:
EnderIO Conduits sometimes connected to storage drawers are causing the server to crash

#### What you expected to happen:
Server not to crash

#### Steps to reproduce:

1. Log Into Server
2. Server Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.186 - 190
- EnderCore: 1.10.2-0.4.1.66
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

#### Your most recent log file where the issue was present: 

https://pastebin.com/dysBFmwR

**Comment by MatthiasMann** [comment]
As this crash is a few calls inside Storage Drawer's code - I think it is more likely an Storage Drawer issue.
Could you also open this issue on Storage Drawer's github page and then post a link to it in here?

**Comment by Siriuo** [comment]
See StorageDrawers issue at: https://github.com/jaquadro/StorageDrawers/issues/487
