### ISSUE TITLE
item ducts acting wierd

### ISSUE THREAD

**Issue by takanas** [SleepyTrousers/EnderIO#4230]
#### Issue Description:

idk if this is the right place to post this but i cannot get my item conduit to insert ores to furnace=(

#### What happens:

nothing

#### What you expected to happen:

put ores in furnace

#### Steps to reproduce:

1.http://prntscr.com/fby8p1
2.http://prntscr.com/fby8tq
3.http://prntscr.com/fby91r
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.2.8.381
- EnderCore:
- Minecraft: 1.7.10
- Forge:forge-1.7.10-10.13.4.1492-1.7.10-universal

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
See http://minecraft.gamepedia.com/Hopper for how to automate furnaces.
