### ISSUE TITLE
Item buffer redstone mode has no effect

### ISSUE THREAD

**Issue by nohelix** [SleepyTrousers/EnderIO#4233]
#### Issue Description:
Item buffer still transferring items in any redstone mode (even never active). As far as I can tell, the presence or absence of signal makes no difference either way.

#### What happens:
2 vanilla single chests with Item buffer in the middle with one side on pull and the other on push in any redstone mode will transfer items.

#### What you expected to happen:
Namely no transfer when the redstone mode is in "never active".

#### Steps to reproduce:

1. Set up 2 vanilla single chests with Item buffer in the middle
2. Set item buffer sides to pull on left and push on right. (Also tried opposite arrangement and with push/pull on one side & pull on the other).
3. Put the item buffer in any redstone mode.
4. Put items in the left chest and they will be transferred.
5. Change redstone mode and reset - items will still be transferred regardless of the presence/absence of signal.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.190
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

#### Your most recent log file where the issue was present: 

[latest.log.txt](https://github.com/SleepyTrousers/EnderIO/files/1033872/latest.log.txt)

**Comment by nohelix** [comment]
Edited OP for clarity.

**Comment by tofof** [comment]
I've noticed this as well. 
It also applies to fluid tanks - they similarly push or pull liquids regardless of what redstone mode they're in or what redstone signal they get.

**Comment by HenryLoenwind** [comment]
Redstone mode only controls the working of the machine, not its push/pull mechanism. In the case of the buffer, which does not have any, I'll look into what can be done there. The tank however does has a working function (filling and emptying containers, voiding items) which are properly controlled by the redstone mode.

**Comment by calloatti** [comment]
Well, in the case of the item buffer, "the working of the machine" is its push/pull mechanism if so configured, so it would make sense in that case that a redstone signal should control that.

But that is just my opinion. I have been bitten by this too, logically assuming that the primary function of the item/power buffer should be controlled by a redstone signal.

**Comment by osirisgothra** [comment]
as an afterthought future versions possibly could maybe do something, the thing is the iconButton for the redstone mode, is the only other button and is grouped right above the 'configure I/O' button. In my world, we usually group things when they are related, which is probably why people are getting confused, just saying... delete me or whatever just was itching to say

**Comment by spikespaz** [comment]
@HenryLoenwind You closed the issue, and this # as not been mentioned in any commit. Has this changed? Still observing the faulty (non-present) behavior of "redstone mode" on item buffers in 1.12, EIO 5.3.7.

**Comment by tyler489** [comment]
> Redstone mode only controls the working of the machine, not its push/pull mechanism. In the case of the buffer, which does not have any, I'll look into what can be done there. The tank however does has a working function (filling and emptying containers, voiding items) which are properly controlled by the redstone mode.

It was closed because it was intended behavior @spikespaz 
With that being said, I did bring it up to the 1.19 porting team, to see if maybe this can be changed.

**Comment by spikespaz** [comment]
> Well, in the case of the item buffer, "the working of the machine" is its push/pull mechanism if so configured, so it would make sense in that case that a redstone signal should control that.
> 
> But that is just my opinion. I have been bitten by this too, logically assuming that the primary function of the item/power buffer should be controlled by a redstone signal.

Do you see the four little :+1: reactions on that message? I can hear the cries of agreement; they are synonymous with my own.

The redstone mode button currently does *nothing*. I understand that it is present because it is drawn by the abstract `GuiScreen` that you inherit from, however if this is truly the intent, it should be removed so that people don't have to come looking for this issue.

The item buffer currently offers one benefit over a chest, the push/pull functionality. The primary purpose of it can be accomplished with one or two conduits and a vanilla chest at a minimum. Yet, the crafting recipe requires several alloys and an industrial machine chassis?

Please, add some value to the machine. I do not think that removing the button is a proper remediation. If you don't want to allow conditional insertion on conduits, please, allow this.

@tyler489

**Comment by tyler489** [comment]
1.12 is unsupported, as the new team is focusing on porting to 1.19, I doubt this will be added to 1.12
