### ISSUE TITLE
[1.10.2] Creative Capacitor Bank not full (minor bug)

### ISSUE THREAD

**Issue by Tomson124** [SleepyTrousers/EnderIO#4235]
#### Issue Description:
It seems the Creative Capacitor Bank is not full but can not be charged either which maybe causes issues.

#### What happens:
One of the players of my mod reported an issue to me where the client crashes if he has a Creative Capacitor Bank in the hand or looks at it in inventory... I will add an checker, which should prevent the crash. But I guess the cause is that the Creative Capacitor Bank can not be charged but is not full either. This probably leads to my Jetpacks trying to charge it over and over again, which is not working.

#### What you expected to happen:
The Creative Capacitor Bank is full, can not be charged and Energy will not be drained from it even Energy is used.

#### Steps to reproduce:

1. Equip a SimplyJetpacks2 Jetplate or Fluxpack
2. Equip a Creative Capacitor Bank in the active Hand
--> Crash
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.190
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

- SimplyJetpacks2: 2.1.1.47 (probably other mods which try to charge things, too)

#### Your most recent log file where the issue was present: 

[https://pastebin.com/HXRMNstq](url)

**Comment by MatthiasMann** [comment]
It's not a bug - it's a feature - it allows the creative capacitor bank to be used as both an energy source and an energy sink.
