### ISSUE TITLE
Can't use Ender IO in private modpack

### ISSUE THREAD

**Issue by Mkez45634** [SleepyTrousers/EnderIO#4237]
#### Issue Description:
At the second part of the Forge loader (initialization part 1), the Minecraft launcher doesn't respond and promptly crashes.

#### What happens:

Minecraft launcher does the 'not responding' thing when attempting to load Ender IO with Forge.

#### What you expected to happen:

Ender IO to work, like it does in other modpacks
(great work btw!)

#### Steps to reproduce:

1. get mods from https://drive.google.com/open?id=0Bzefn5ytDiNleUQ2SWc1RmVydGs
2. install Forge version 1.10.2 12.1.8.3.2254 using windows installer
3. ???
4. profit
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2 - 1.3.1.180
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.1.8.3.2254 (lastest release build threw an error?)

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/Z9Mn1yFv

edit:

Pastebin has lots of missing translator configs at the end, what does that mean?

**Comment by MatthiasMann** [comment]
This is not the correct location to download the mod from - download it from https://mods.curse.com/mc-mods/minecraft/ender-io and https://mods.curse.com/mc-mods/minecraft/231868-endercore

Also I don't see any crash in your pastebin.

**Comment by Mkez45634** [comment]
I think (I removed it from the mods folder) that I'm running out of RAM.
the google docs were all the mods I have installed reuploaded, I got Ender IO from https://minecraft.curseforge.com/projects/ender-io as well as the ender core.

I'll go try more RAM

**Comment by Mkez45634** [comment]
First: fuck McAfee
Secondly, Chrome + 1G allocated to Minecraft launcher = bad idea

Sorry for wasting your time! (3G worked)

**Comment by calloatti** [comment]
MC 1.10 with 100+ mods and 3GB allocated? Sorry, but barely playable. You need at least 5-6 GB.

I have 8GB and allocate 6GB to MC.

**Comment by Mkez45634** [comment]
I have 8G, the modpack work with 5, I really need to update to 16G.

**Comment by MatthiasMann** [comment]
You might also want to look into using foamfix from Asie - it can reduce the memory usage a bit.

**Comment by Mkez45634** [comment]
Link?

**Comment by MatthiasMann** [comment]
http://asie.pl/Projects/Minecraft/Mods/FoamFix/

**Comment by Mkez45634** [comment]
ty
