### ISSUE TITLE
Only forge+enderIO - crash client (1.10.2)

### ISSUE THREAD

**Issue by mkrtes** [SleepyTrousers/EnderIO#4240]
#### Issue Description:
Client does not start. Only forge+enderIO+enderCore
#### What happens:
Crash
____
- EnderIO: EnderIO-1.10.2-3.1.186
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: MinecraftForge v12.18.3.2185

Crashreport: https://pastebin.com/dykLRVXi
fml-client-lates-log: https://pastebin.com/27vts7Q2

**Comment by HenryLoenwind** [comment]
We do not support pirated software.
