### ISSUE TITLE
Alloy Smelter in Alloy Only mode produces Soul Glass

### ISSUE THREAD

**Issue by TheQuadShot** [SleepyTrousers/EnderIO#4241]
EnderIO-1.10.2-3.1.183
EnderCore-1.10.2-0.4.1.66-beta
Forge-12.18.3.2281
Minecraft 1.10.2

When making Soularium(1 Soul Sand + 1 Gold) it outputs Soul Glass(1 Soul Sand = 1 Soul Glass) which is not an alloy recipe. I am feeding the Smelter via an item conduit from a chest. I can also reproduce by putting the chest directly on top of the Smelter and having it pull from the chest.

latestlog 
https://pastebin.com/UxdRWn83

ModList
https://pastebin.com/1L6sGcnJ

**Comment by mindforger** [comment]
i would call it a consistency thing but a tough one anyways

when you drop ordinary sand into the smelter it smelts quiet clear glass in alloy mode and vanilla glass in furnace mode ... i for my opinion find it consistent but this issue with recipes stacking was a thing in the past already but not yet an issue when only using EIO

**Comment by TheQuadShot** [comment]
It is not consistent, when the Smelter is in any mode it produces Soul Glass. But in Alloy Only mode I cannot make any kind of glass from sand. The recipe for Quite Clear Glass is, 1 Glass = 1 Quite Clear Glass and can auto feed to a Smelter in Alloy Only mode

**Comment by HenryLoenwind** [comment]
What mod is Soul Glass from?

Also, please check the startup log to see if that mod registers a recipe with the alloy smelter. I'm quite sure we don't have code that calls the vanilla recipe registry just for one specific item when it is disabled.

**Comment by TheQuadShot** [comment]
It's from Natura. Where is the start up log at? I can't find it anywhere. I know it exists, when I enable it in the launcher I can see it but I can't find it, and the launcher window that show's it also seems to dump it or go blank if I tell it to keep all.

**Comment by HenryLoenwind** [comment]
Ok, Natura I can check. No, it doesn't register an alloy recipe and I cannot reproduce that behavior here.
