### ISSUE TITLE
Crash painting With XU2 blocks

### ISSUE THREAD

**Issue by KendirkRS** [SleepyTrousers/EnderIO#4242]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

Just wanted to see if i could paint Alloy smelters to look like XU2 Furnaces and got this crash
Tried with crushers too

#### What happens:

Crash to desktop with this report https://pastebin.com/rgfVSTVg

#### What you expected to happen:

To get a painted Alloy smelter that looked like a furnace

#### Steps to reproduce:

1. Put Furnace into Painter
2. Put alloy smelter to be painted
3. Wait
4. get a java.lang.IllegalStateException: Optional.get() cannot be called on an absent value Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.66-Beta
- Minecraft: 1.10.2
- Forge:  12.18.3.2297

#### Your most recent log file where the issue was present: 

https://pastebin.com/rgfVSTVg

**Comment by HenryLoenwind** [comment]
see #4095
