### ISSUE TITLE
Client Crash with Unexpected Error

### ISSUE THREAD

**Issue by CocoVanChoco** [SleepyTrousers/EnderIO#4243]
#### Issue Description:
The Game freezed and after that few seconds it Crashed to the Desktop and pulled out 
the Log.

#### What happens:
Tried to place an ArchitectureCraft Block i created to my Base Wall and near that was 
the EnderIO Painting Machine. Wich wasnt connected to anything except an Vibrant Energy Box
and prolly 5 Blocks away from the Place i worked on the Wall wich had a few Painted Stone Slabs
on top. So i tried to place my block like i said. 

#### What you expected to happen:
That my Block were placed there instead of that Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.190
- EnderCore: 1.10.2-0.4.1.66-Beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

#### Your most recent log file where the issue was present: 

[https://pastebin.com/1wD22WPX]

**Comment by HenryLoenwind** [comment]
Report this to ArchitectureCraft
