### ISSUE TITLE
[Feature Request] Split Transceiver buffer config into local and I/O buffers

### ISSUE THREAD

**Issue by SDPhantom** [SleepyTrousers/EnderIO#4245]
#### Issue Description:
Currently, when you set the config for the Transceiver's buffer size, it splits this value evenly between the local and I/O buffers. In trying to tweak the config to increase the RF/t throughput to make it a viable replacement for the Thermal Dynamic's Tesseract (not available in 1.10 yet), I ran into a problem in which the Transceiver is unable to send more than what's in the I/O buffer per tick. Fair enough, I increase the buffer size to match and now I'm looking at a Transceiver with impossibly high local buffer that it wants to fill on both ends before actually sending power through. Ideally, I'd like to set up a Transceiver that would have a local buffer of 50,000 and an I/O buffer of somewhere around 2,000,000,000 (near cap of what a Java signed Int can hold).

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.189
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2297

**Comment by HenryLoenwind** [comment]
This won't work because the receiving transceiver needs its local buffer to provide the received energy to other blocks.

**Comment by SDPhantom** [comment]
I guess I might've been looking at it wrong, thinking the local buffer was the same idea as a machine buffer for its own RF/t cost. I've been pulling too many late nights working on a test project using EnderIO conduits/Transceiver on a Draconic Evolution reactor. I've blown it up quite a few times just by placing a single conduit section on the output and it instantly draining the reactor to zero without being connected to anything else. I can work around it, but not exactly what I was expecting.
