### ISSUE TITLE
Crash while starting

### ISSUE THREAD

**Issue by OmegaRogue** [SleepyTrousers/EnderIO#4249]
#### Issue Description:
crashes every time when loading during Initialization since I installed the lastest beta version because it was required by a mod

#### What happens:
it crashes

#### What you expected to happen:
it doesnt crash and it loads

#### Steps to reproduce:

1.download my modpack (crash report alpha version because its only uploaded for this report)
https://minecraft.curseforge.com/projects/all-names-are-taken/files/2430922
2.install the modpack
3. start minecraft
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: forge-10.13.4.1614

#### Your most recent log file where the issue was present: 

https://www.dropbox.com/s/52ozhv6gb2jbpxi/latest.log?dl=1

**Comment by HenryLoenwind** [comment]
It's rejecting a bad configuration value in the cropConfig, that not a bug.

**Comment by OmegaRogue** [comment]
what value is it rejecting?

**Comment by HenryLoenwind** [comment]
```
java.lang.IllegalArgumentException: Natura:barley.seed is not a vaild string. Strings should be either an oredict name, or in the format objectname;damage (damage is optional)
	at com.enderio.core.common.util.ItemUtil.parseStringIntoRecipeItem(ItemUtil.java:104)
	at com.enderio.core.common.util.ItemUtil.parseStringIntoItemStack(ItemUtil.java:164)
	at com.enderio.core.common.handlers.RightClickCropHandler$PlantInfo.init(RightClickCropHandler.java:42)
	at com.enderio.core.common.config.ConfigHandler.loadRightClickCrops(ConfigHandler.java:163)
```

BTW: Looking over the log, I see plenty of other mods complaining about invalid items, too. e.g. HQM is substituting quest rewards. Also, your PoweredSpawnerConfig_User.json is malformed. And you potion IDs are conflicting.

**Comment by OmegaRogue** [comment]
how can i fix PoweredSpawnerConfig_User.json and how can i fix the potion ids?

**Comment by OmegaRogue** [comment]
ok there was a comma missing after Villager
