### ISSUE TITLE
[1.10.2] EnderIO causes issue with Enchanting plus hanging a SP world on generation

### ISSUE THREAD

**Issue by Morpheus1101** [SleepyTrousers/EnderIO#4250]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Game fails to generate a SP world

#### What you expected to happen:

For the game to successfully generate a SP world

#### Steps to reproduce:

1. Load Pack
2. Create a SP World
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.192
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: *.2297

#### Your most recent log file where the issue was present: 

https://puu.sh/wfbMA/667326f3ef.log

https://github.com/Darkhax-Minecraft/Enchanting-Plus/issues/71

**Comment by HenryLoenwind** [comment]
```
Caused by: java.lang.NullPointerException
	at net.darkhax.eplus.item.ItemScroll.enchantScroll(ItemScroll.java:58) ~[ItemScroll.class:?]
	at net.darkhax.eplus.item.ItemScroll.createScroll(ItemScroll.java:47) ~[ItemScroll.class:?]
	at net.darkhax.eplus.item.ItemScroll.func_150895_a(ItemScroll.java:119) ~[ItemScroll.class:?]
```
