### ISSUE TITLE
modded swords for killer joe

### ISSUE THREAD

**Issue by ptk2003** [SleepyTrousers/EnderIO#4252]
#### Issue Description:
Killer JOE not accepting draconic and wyvern sword from Draconic Evolution.

#### What happens:
Can not invest draconic and wyvern sword in gui killer joe.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.192
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta.jar
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2281-universal
- Draconic-Evolution-1.10.2-2.0.12.222-universal
- BrandonsCore-1.10.2-2.1.7.102-universal
#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by Gandalf360one** [comment]
http://ideas.theideawall.com/EnderIO/Forum/TopicDetails/1c115822-880e-4687-ab97-587344bffd4c
