### ISSUE TITLE
[1.10.2] EnderIO not loading after Applied Energistics

### ISSUE THREAD

**Issue by Robijnvogel** [SleepyTrousers/EnderIO#4254]
#### Issue Description:
Because EnderIO mentioned that [this guy](https://forum.feed-the-beast.com/threads/frequent-crashes-lately.229021/page-3#post-1887511) was using a way outdated RF API, included in BrandonsCore, 
`Ender IO needs at least 1.4.0 and will NOT work with older versions.`
I advised him to rename the EnderIO jar file to AEnderIO.jar, in an attempt to change the mod loading order and load the RF API in EnderIO instead, however, this caused a crash:

#### What happens:
Since the crash log told him [this](https://forum.feed-the-beast.com/threads/frequent-crashes-lately.229021/page-3#post-1887923), I am assuming that EnderIO does only coincidentally loads itself after Applied Energistics because of its mod jar name and not because this is actually coded into EnderIO, like it should. (confirmed by looking at the code)

#### What you expected to happen:
EnderIO should load after Applied Energistics, no matter what the mods' jar names are.
Could probably be fixed by adding a (non-required) after for applied energistics on [this line](https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/EnderIO.java#L78).

#### Steps to reproduce:

1. Install EnderIO and Applied Energistics
2. Rename either of both files' names so that the alphabetical order changes.
3. Run Minecraft.
...

____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: 3.1.183
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: build 2254

**Comment by BrisingrAerowing** [comment]
As a side note, I have discovered that adding AE2Stuff (by BDew) causes Ender IO to load correctly, no matter what the files are named. I honestly have no idea why, but it does. That may be a workable workaround for some.
