### ISSUE TITLE
[1.10.2] Vacuum Hoppers not accessible by non-Ender IO conduits

### ISSUE THREAD

**Issue by s0uthw3st** [SleepyTrousers/EnderIO#4257]
#### Issue Description:

Items are not extracted from the Vacuum Hopper and placed into valid attached inventories when using conduit systems other than Ender IO's Item Conduits.

Discovered in DW20 1.10.2 Modpack version 1.12.1, verified with a clean install of Ender IO + Extra Utilities 2 + CoFH mods.

#### What happens:

Items are not extracted from the Vacuum Hopper using Thermal Dynamics Itemducts and Servos or Extra Utilities 2 Item Transfer Nodes.

#### What you expected to happen:

Items can be extracted from the Vacuum Hopper using Thermal Dynamics Itemducts and Servos or Extra Utilities 2 Item Transfer Nodes.

#### Steps to reproduce:

1. Attach other conduit (tested with ExU2 Item Transfer Node and Thermal Dynamics Itemduct+Servo) to any face of the Vacuum Hopper on one side and a valid inventory (e.g. a Chest) on another and enable item extraction if necessary.
2. No items are extracted from the Vacuum Hopper.
3. Remove other conduit and replace with Ender IO Item Conduit and enable item extraction and insertion to the Vacuum Hopper and Chest respectively.
4. Items are extracted from the Vacuum Hopper and inserted into the chest

Example: http://imgur.com/ltYc0k5
One item was inserted into each vacuum hopper - as shown, only the Ender IO conduit moved the item to the destination chest.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.183
- EnderCore: 0.4.1.66
- Minecraft: 1.10.2
- Forge: 12.18.3.2316

Other mods tested: 
- Thermal Dynamics: 2.0.2.4
- CoFH Core: 4.1.2.157
- CodeChickenLib: 2.5.9.267
- CodeChickenCore: 2.4.1.102
- Thermal Expansion: 5.1.1.93
- Thermal Foundation: 2.1.0.82
- Extra Utilities 2: 1.4.4

#### Your most recent log file where the issue was present: 

N/A - no errors encountered

**Comment by MatthiasMann** [comment]
Probably because the vacuum chest doesn't support CapabilityItemHandler.ITEM_HANDLER_CAPABILITY.

**Comment by s0uthw3st** [comment]
Any reason for that? As far as I can tell it's the only Ender IO block that behaves that way (haven't tested all of them, but the Vacuum Hopper stands out).

**Comment by HenryLoenwind** [comment]
Rather simple reason...the vacuum chest isn't a machine but a chest...

**Comment by s0uthw3st** [comment]
But standard chests can be extracted from - is this intended behavior then?
