### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by blockbreaker1361** [SleepyTrousers/EnderIO#4258]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Crash on startup

#### What you expected to happen:
Start the game

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: Latest
- EnderCore: Latest
- Minecraft: 1.10.2
- Forge: 12.18.3.2316

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/GeeFrHYZ

**Comment by Lgk2** [comment]
Same crash and log file here.

Affected Versions (Do not use "latest"):

EnderIO: 1.10.2-3.1.192.jar
EnderCore: 1.10.2-0.4.1.66-beta.jar
Minecraft: 1.10.2
Forge: 12.18.3.2316

**Comment by HenryLoenwind** [comment]
Note: The reason I blame Chisel here is that we can either work with the old version and crash with the new or vice versa. There is no way for us to either work with both versions or even to just not work with one of them.

**Comment by AnthonyKane5528X** [comment]
Thank you Henry.
Just to be clear: reverting back to a previous version of Chisel WILL NOT fix this once its been done right?

**Comment by psynchro** [comment]
FYI: This now seems to be fixed with Chisel-MC1.10.2-0.0.11.24.jar and CTM-MC1.10.2-0.1.0.10,jar.
(For 1.10.2-3.1.192, at least.)
