### ISSUE TITLE
CRASH on Startup

### ISSUE THREAD

**Issue by AnthonyKane5528X** [SleepyTrousers/EnderIO#4259]
#### Issue Description:
-This shouldn't have effected anything but I will state these events as they may help to pin down the cause of the crash.
-Downloaded latest version of Chisel-MC1.10.2-0.0.11.23
-Downloaded latest version of CoFHcore1.10.2-4.1.3.5
-Downloaded latest version of Thermal Dynamics-1.10.2-2.0.3.5
-Downloaded latest version of Thermal Expansion-1.10.2-5.1.2.3
-Downloaded latest version of Thermal Foundation-1.10.2-2.1.1.3

I did nothing to EnderIO, but if you read through the crash log you'll see it has something to do with EnderIO and Chisel.

Attempted to load.  Game Crashed.  Undid all updates.  Attempted to load.  Game crashed AT LAUNCH.

Here is the paste pin for the crash:
https://pastebin.com/V7Ytfjbm

The game will not attempt to load anymore.  Once "Play" is clicked the launcher begins and then immediately crashes.  

#### What happens:
-Click "PLAY" button at launcher.  Game attempts to start to load and then crashes.

#### What you expected to happen:
-Click "Play" and Game Loads

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  1.10.2-3.1.1.183
- EnderCore: 1.10.2-0.4.1.66
- Minecraft: 1.10.2
- Forge:  12.18.3.2254

#### Your most recent log file where the issue was present: 
https://pastebin.com/V7Ytfjbm

**Comment by HenryLoenwind** [comment]
see #4258
