### ISSUE TITLE
[1.10.2] All Conduit Facades Invisible In-World with CTM Installed

### ISSUE THREAD

**Issue by oitsjustjose** [SleepyTrousers/EnderIO#4261]
#### Issue Description:
[Here's a video demonstration](https://youtu.be/2S5XNQdzJ3c).

Conduit facades painted with any texture (Vanilla, Chisel or any other mod) do not render in-world. Their hit box is still there, so it's not as though the facade thinks I'm holding a facade-hiding item; they simply don't render. I know you just changed this rendering system some for the new CTM library for Chisel, so I tried a few things to help debug and actually found something quite interesting:

The rendering bug only occurs when the CTM is loaded. **Not** having CTM installed allows the facades to work as expected, but as soon as CTM is installed (like in my test instance with only CTM and EnderIO) all facade rendering goes invisible.

#### What happens:
Facades are invisible!

#### What you expected to happen:
Non-invisible facades to be not-invisible!

#### Steps to reproduce:

1. Install EnderIO + EnderCore
2. Install CTM (tested with CTM 0.1.0.13)
3. Observe invisible, untextured facades in-world!

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.193
- EnderCore: 0.4.1.65
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

#### Your most recent log file where the issue was present: 

No crash.

**Comment by HenryLoenwind** [comment]
I traced it out and found that CTM ASMs Ender IO's BlockConduitBundle.canRenderInLayer(BlockRenderLayer) destroying our rendering.

@tterrag1098 That's why @LexManos always says that people who do coremods are retards. While I don't agree in general, could you ASM a bit more careful, please?

**Comment by oitsjustjose** [comment]
That's actually really funny. Thanks for the wonderful work, the all of you!

**Comment by HenryLoenwind** [comment]
I fail to feel the joke...it took me nearly 2 hours of single-stepping through the rendering code to find this.

**Comment by oitsjustjose** [comment]
Oh no, I totally understand that. The only thing I found humor in was that you were supporting CTM and CTM was trying to support you, and in the end it just caused more problems!

I can't imagine how irritating it was to sit there and think something is your fault when it's just someone else messing with your code. None of my mods have ever used ASM for pretty much this reason - I've always been afraid of breaking someone else's code with my own :|

**Comment by PanSzelescik** [comment]
Travel Anchors also have no texture

**Comment by tterrag1098** [comment]
@oitsjustjose Could you test this build to see if the problem persists? http://ci.tterrag.com/job/ConnectedTexturesMod/branch/1.10%252Fdev/14/

**Comment by oitsjustjose** [comment]
Confirmed; that fixed it!:

![2017-06-18_23 19 41](https://user-images.githubusercontent.com/3887324/27268284-b2e315c2-547c-11e7-8439-57e57a16ea46.png)

![2017-06-18_23 19 40](https://user-images.githubusercontent.com/3887324/27268285-b47eb85a-547c-11e7-903c-bb63eccd6335.png)

Thanks!

**Comment by HenryLoenwind** [comment]
Good
