### ISSUE TITLE
Entity Count increase by using EIO Item Conduits

### ISSUE THREAD

**Issue by CharZinta** [SleepyTrousers/EnderIO#4263]
#### Issue Description:
Minecraft 1.10  Custom Mod Pack (I am the owner and reporting for multiple players)
Entity Count increase when using EIO Conduits

#### What happens:
When using EIO ITEM conduits to move items, doesn't matter what it connects to, the entity count will continue to increase until the player must idle at spawn, or some other neutral location, for approximately 5 minutes so the count goes down.

#### What you expected to happen:
Entity counts to not increase into the thousands and tens of thousands.

#### Steps to reproduce:

1. Use an item conduit with or with a basic item filter to move items around within a chunk.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.186
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

#### Your most recent log file where the issue was present: 

No errors generated so no crash log to pastebin.

NOTE: 
We have several players who have tried different events to track this down. Using Mekanism conduits for one mod, not using EIO conduits across chunks, as well as testing in SP VS MP.

**Comment by mindforger** [comment]
you can press and hold F3 + C for at least 6 seconds while ingame to force a crash, it gives an insight on your setup to help analyze :)

**Comment by ktole1999** [comment]
gist it

**Comment by HenryLoenwind** [comment]
The only entities conduits can create are dropped items if there's some inventory that says it can accept items but then rejects them. Should be easy to find those.

**Comment by MatthiasMann** [comment]
Storage Drawers can exhibit this behavior: https://github.com/jaquadro/StorageDrawers/issues/396

**Comment by HenryLoenwind** [comment]
Oh, and before someone suggests I implement it the other way around: I can either have items spill if the receiving inventory lies or dupe items if the source inventory lies. I prefer spilling to duping.

**Comment by MatthiasMann** [comment]
The best way to solve this would be to provide an accurate simulation - after all there can be no other action between doing the simulation and the insertion (except the extraction - but that shouldn't be able to invalidate the simulation result even if you extract and insert into the same storage).

**Comment by Robijnvogel** [comment]
I wonder why no-one has asked whether those entities have been counted by the server (using some tool, like Opis or Lagfix) or by the client (F3).

**Comment by HenryLoenwind** [comment]
Robijnvogel, because nobody is doing anything about this unless someone states that is it NOT spilled items from a lying target inventory. *Then* we would start thinking about way of either finding out what kinds of entities the OP has, or a way of reproducing it. But it seems this is another of those "I see something, dump some info into a ticket and never come back again" tickets. That works for things like "there's typo in that tooltip" or "soul vials don't work on X", but not for something that clearly doesn't happen for everyone.
