### ISSUE TITLE
Transparency bug on QuiteClearGlass

### ISSUE THREAD

**Issue by emanuele6** [SleepyTrousers/EnderIO#4264]
#### Issue Description:
I am able to place RedAlloy Wires from ProjectRed on QuiteClearGlass

#### What happens:
![schermata da 2017-06-20 20-34-52](https://user-images.githubusercontent.com/20175435/27352025-981c0f12-55ff-11e7-959c-c24b073d86ff.png)
I reported this graphical issue to MrTJP (https://github.com/MrTJP/ProjectRed/issues/1195) and he sustain that you probably are not reporting the transparency of the block correctly, because RedAlloy Wires should not be placable on trasparent surfaces.
![schermata da 2017-06-20 21-36-07](https://user-images.githubusercontent.com/20175435/27352309-81d2990a-5600-11e7-9677-1cbbf7e106db.png)
Strangely I am able to place them on all sides but the top

#### What you expected to happen:
I expected to be able to place wires on all or none sides.
____
#### Affected Versions:

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

**Comment by emanuele6** [comment]
same issue with FusedQuartz

**Comment by tterrag1098** [comment]
This isn't really a bug, their model just doesn't have any render on the bottom.

**Comment by emanuele6** [comment]
i know... I was just wondering why i can place on every side but the top

**Comment by emanuele6** [comment]
I also have tried to place wires on other transparent blocks from other mods like managlass from botania, glass and glowstone from minecraft and clear glass from Tinkers' Construct.
I am not able to place wires on them like MrTJP claims.

**Comment by HenryLoenwind** [comment]
I think he mixed up transparency with solidness. Our glasses are solid and transparent, where e.g. a fence is not solid but transparent. But it's hard to say without him naming which method he calls.
