### ISSUE TITLE
Farming Stations creating multiple fake worlds resulting in performance decrease

### ISSUE THREAD

**Issue by Rubbertjuh** [SleepyTrousers/EnderIO#4265]
#### Issue Description:
https://hastebin.com/sapofozevo.vbs Sponge is emitting this stacktrace several times per ten minutes (about 3 times, sometimes more), I'm worried that multiple fake worlds are being creates at the same time, causing lag.  
Everytime when this stacktrace is emitted, a fake world is created, resulting in performance decrease.

#### What happens:
Farming Stations creating multiple fake worlds, I think this is unintended 

#### What you expected to happen:
I expect that there would only be 1 fake world for all Farming stations.

#### Steps to reproduce:

1. Set up SpongeForge
2. Set up EnderIO 
3. Set up Farming Station
4. Wait?

...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.190
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2316

#### Your most recent log file where the issue was present: 
https://hastebin.com/sapofozevo.vbs

**Comment by HenryLoenwind** [comment]
Ender IO is not creating worlds, it only is wrapping the real world. And it is only doing this once per Farming Station. So (a) Sponge mixes up World with WorldServer/WorldClient and (b) your farming station is in a chunk that get loaded and unloaded quite often.
