### ISSUE TITLE
Crash when Tinkers Sword in Dark Anvil with Enchanting Book

### ISSUE THREAD

**Issue by ReportBot9009** [SleepyTrousers/EnderIO#4268]
#### Issue Description:
This occurs in a heavily modded/customized FTB Beyond. Placing a Tinkers sword into a Dark Anvil with the Sharpness V enchant on a book causes a crash.

#### What happens:
When I placed a Tinkers Rapier into a Dark anvil with the Sharpness V enchant to see if I could add it to the sword nothing happened. It had a big red "X" on the crafting progression arrow. When I clicked on the name of the item to rename it, the game crashed.

#### What you expected to happen:
Hopefully to enchant a Tinkers sword with Sharpness V. I was sure it probably wouldn't work, but the crash was unexpected.

#### Steps to reproduce:

1. Place Tinkers Rapier into Dark Anvil with Sharpness V Enchant book.
2. Click to rename item.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

#### Your most recent log file where the issue was present: 

https://paste.ee/p/xhJGD

Hope that's enough. Thanks for a great bug reporting template!

**Comment by MatthiasMann** [comment]
That has nothing to do with EnderIO - the dark steel anvil is just a retextured vanilla anvil with different durability. The GUI and everything related to enchanting or renaming items is pure vanilla.

So I think this is likely a problem with the Tinkers' Rapier.

**Comment by HenryLoenwind** [comment]
I wouldn't be too fast here, we **do** override the container. Our code seems to not be involved in the crash, but you never know. Please try to reproduce this crash in a vanilla anvil. If it doesn't crash there, I'll have a look.
