### ISSUE TITLE
Conduit

### ISSUE THREAD

**Issue by HeavyDeception** [SleepyTrousers/EnderIO#4269]
#### Issue Description:
Conduit Facade are clear and show nothing no mater what you paint them.

#### What happens:
Place block and it goes away but is still there.

#### What you expected to happen:
For it to hide the conduit and show the block.

#### Steps to reproduce:

1. Place Conduit
2. Place Facade
3. That's all.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.192
- EnderCore: 0.4.1.66
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

#### Your most recent log file where the issue was present: 

There Is no crash log. But here is a pic https://drive.google.com/file/d/0B2IewM42X78HaTBzODZCQkVDakE/view?usp=sharing

**Comment by HenryLoenwind** [comment]
#4261

**Comment by HeavyDeception** [comment]
@HenryLoenwind I even search this time Sorry about that and thanks for the link.
