### ISSUE TITLE
[1.10.2] EnderIO 3.1.193 Soul Vial issue w/Mo' Creatures

### ISSUE THREAD

**Issue by dfox20** [SleepyTrousers/EnderIO#4270]
#### Issue Description:
Basically the soul vial wont work on a tamed mob in mo'creatures unless i'm in creative mode. (Tested on Grizzly Bear[has to be cub to be tamed]). As far as i'm aware it works on all untamed mobs.

#### What happens:
Nothin happens, it won't go in the soul vial. If I go into creative mode it works but then there is duplicate versions of that mob.

#### What you expected to happen:
The soul vial to pick up the mob.

#### Steps to reproduce:

1. Spawn Grizzly Bear until a cub/small one appears
2. Cheat in Soul Vial and steak
3.  Use steak on cub to tame it and give it a name.
4. Get out of creative mode
5. Try using soul vial on tamed mob
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Custom Mob Spawner(need for Mo' Creatures): 3.10.1
- Mo' Creatures: 10.0.6

#### Your most recent log file where the issue was present: 
https://pastebin.com/KDKfxJKf

**Comment by MatthiasMann** [comment]
Check the spawner config file if these are black listed.

**Comment by dfox20** [comment]
what is the file name for the spawner config sorry?
