### ISSUE TITLE
Experience Obelisk copy XP

### ISSUE THREAD

**Issue by VerniyDespair** [SleepyTrousers/EnderIO#4272]
#### Issue Description:
Using bug to get XP(I am Chinese and I am not fluent in English, so machine translation is very abrupt and don't mind)

#### What happens:
XP Double

#### What you expected to happen:
Fix it

#### Steps to reproduce:

1.The XP deposit Experience Obelisk
2.Over and over again deposit and take out
3.And then use it XP
4.suicide
5.XP Change back to original form
6.Be careful I only tried it on the server,A single mode Can you succeed Uncertain
7.When you quit the server, it will expire
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
1.7.10-2.2.8.381
- EnderCore:
I don't remember.
- Minecraft: 1.7.10
- Forge:
I don't remember.

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by VerniyDespair** [comment]
Sorry to forget to delete Sorry to forget to delete

**Comment by VerniyDespair** [comment]
Sorry to forget to delete Do not use "latest"

**Comment by AnrDaemon** [comment]
Update to the latest EIO (2.3.0.429) and test again.
