### ISSUE TITLE
Disable Auto Output

### ISSUE THREAD

**Issue by MissPotato** [SleepyTrousers/EnderIO#4276]
I am developing a pack based loosely around the early days of just IC and BC. In hopes to try and fit EnderIO into this theme I was looking for a config option to disable the pushing and pulling that EnderIO machines do. For example, a playing could set the top of the block to input mode, but this would only allow a different block or pipe to insert into the slot, notfor the block to pull from a chest. For mods like IC2-exp this is possible by disabling the upgrade that allows this behavior, but as EnderIO has this built into the machines GUI, it isn't possible from what I can tell.

**Comment by HenryLoenwind** [comment]
This is one of the core features of Ender IO...
