### ISSUE TITLE
Mod request [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [SleepyTrousers/EnderIO#4277]
Hello!
I came to ask you if you as a programmer, could help me by creating a simple mod, which is based on the "SoulBound" charm feature.
I have several public servers, and I'm in a dilemma using Sponge Forge for 1.10.2. There are not many plugin options and therefore I thought a mod would work the same way, and more if you already have part of the code created with that enchantment.
What I have in mind, is a mod that adds 1 item, for example an enchanted golden key, but its characteristic of that item would be that having it in the player's inventory, it would not lose its items when it died, it would practically save all its Complete inventory.
In the case of players who do not have it in their inventory, all things would fall to the floor.
If you are available to help, please respond to this request.
Regards!

**Comment by ktole1999** [comment]
i think there are other methods/plugins for achieving this task.

**Comment by HeberonYT** [comment]
There is nothing, I have reviewed it many times in the forum and no plugin has been developed for that.
Remember I'm talking about a Sponge Forge server. If my server was bukkit, I would not be here xD

**Comment by ktole1999** [comment]
have you tried the keepinventory game rule?

**Comment by HeberonYT** [comment]
If I have tried it, but I do not want to activate it in general. My wish is for a special item to achieve that, as does the Enchantment Enchantment.

**Comment by ktole1999** [comment]
similar to golden bag of holding?
