### ISSUE TITLE
Filter Soul Vials

### ISSUE THREAD

**Issue by duncanwebb** [SleepyTrousers/EnderIO#4278]
#### Issue Description:
I do hope that you don't mind this question or feature request.

Is it possible to filter Soul Vials, like just allow Soul Vials with Zombies to pass through? I guess that this would be filtering data on NBT fields. I've searched and not found any hints is this is possible.

I would like to automate making crystals and catching Enderman, Zombies is not a problem using a powered spawner and a mechanical user, feeding XP into the Soul Binder is not a problem using an Ender Tank in push mode.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

**Comment by MatthiasMann** [comment]
The powered spawner can spawn directly into a soul vial ...

**Comment by duncanwebb** [comment]
That's awesome! Helps a lot.

Filter would be nice too.

**Comment by HenryLoenwind** [comment]
EpicSquid, a "mob type" filter for our vials, broken and powered spawners would be nice. Those all use the same NBT/tool class.

**Comment by EpicSquid** [comment]
Will look into it. Should be simple enough.
