### ISSUE TITLE
Could not set value config entry enchantmentWitherArrowRarity

### ISSUE THREAD

**Issue by fcpwiz** [SleepyTrousers/EnderIO#4279]
#### Issue Description:
Error on startup.

#### What happens:
https://gist.github.com/fcpwiz/f7f57b79661bff5591a80c2428fb35f0 (EnderIO) & https://gist.github.com/fcpwiz/0a98ed78c318e6ff8ddacbd0f92722bf (EnderCore)

#### What you expected to happen:
No error on startup.

#### Steps to reproduce:

1. Launch server.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.193.jar
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta.jar
- Minecraft: 1.10.2
- Forge: 2281 (SpongeForge)

#### Your most recent log file where the issue was present: https://gist.github.com/fcpwiz/c01ffe2b8357f0af7a5e34c3609de26b

[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
Your config is invalid. The option `enchantmentSoulBoundWeight` accepts only `COMMON`, `UNCOMMON`, `RARE`, or `VERY_RARE`, not numbers.

**Comment by fcpwiz** [comment]
Ah I forgot to regen the config when updating to 1.10.2. Thanks!
