### ISSUE TITLE
[1.10]Crafter doesn't craft with IC2 recipes

### ISSUE THREAD

**Issue by fluid-uu-matter** [SleepyTrousers/EnderIO#4280]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
I tried to use the EnderIO crafter to craft IC2 Plantball which is regeistered as IC2 recipes,But the crafter doesn't do.

#### What you expected to happen:
The crafter crafts with IC2 recipes.

#### Steps to reproduce:

1.Place down the EIO crafter
2.Program an IC2 recipe into the crafter
3.Insert the ingredients
4.Power the crafter with RF

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.10.2-3.1.183
- EnderCore:EnderCore-1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge:1.10.2-forge1.10.2-12.18.3.2316

#### Your most recent log file where the issue was present: 

No log is needed
Minecraft didn't crash

**Comment by chezpaul** [comment]
Same thing happens to me too but with Uranium 236 and 238 to create Enriched Uranium.
Running latest of everything as of Oct 6th 2017
