### ISSUE TITLE
EnderIO Duplication Glitch 1.10.2 (Tested)

### ISSUE THREAD

**Issue by MrCoby220** [SleepyTrousers/EnderIO#4282]
Issue Description:
This is a glitch where when you take 2 soul vial 1 in your hand and 1 in your off hand and then right click an entity it will give you this same entity 2 time this can be used as a dupe glitch if you do this on a zombie holding an item that you gave him i found this glitch by my self when making some Ender Crystal.

 
What happens:
When you dupe a zombie it will give you 2 soul vial with the exact same NBT's this mean when you spawn back the zombie it will still have the item you gave him and then you can kill him to get this item and pop up the 2nd zombie that still has this item and dupe him and do this process over and over again

What you expected to happen:
I did not expect anything to happen when the soul vial was in the off hand i would expect it to not take the same entity with the same NBT's i was just expecting it to only take the entity in the first hand

Steps to reproduce:

1. Have 2 soul vial (1 in your hand 2nd in your off hand)
2. Place down the block or item you want to dupe near a zombie and wait for him to pick it up
3. Once the zombie picked up the item or block you want to dupe than use the 2 soul vial at the same time as noted in step 1
4. Spawn 1 of the 2 copy of the zombie, kill him and then spawn the 2nd copy and dupe him and do this over and over again

____
Affected Versions:

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.7.10
- Forge: 1.10.2-12.18.3.2316

Your most recent log file where the issue was present: 

No log when this glitch is done

**Comment by HenryLoenwind** [comment]
update to version 3.1.193 or later

**Comment by macks2008** [comment]
yeah this is related to the empty duplication glitch I already reported (see #4248) and that HenryLoenwind apparently fixed
