### ISSUE TITLE
Exception while updating neighbours

### ISSUE THREAD

**Issue by CitrusFruit** [SleepyTrousers/EnderIO#4283]
#### Issue Description:
I'm honestly not sure, when I try to launch my server it instantly crashes.

#### What happens:
Server crashes upon starting.

#### What you expected to happen:
I expected my server to work fine.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1614-1.7.10-universal

#### Your most recent log file where the issue was present: 
Error - https://pastebin.com/nvkUTPGd

Crash report - https://pastebin.com/NxWyVnBJ

**Comment by mindforger** [comment]
looks familliar, is sponge involved? Those type of classcast issues were reported in AE2 pretty much and were never really solved but yet not in 1.7.10

**Comment by HenryLoenwind** [comment]
Yes, that's another "corrupted world" crash. We never found wich mod is doing the corrupting...

**Comment by CitrusFruit** [comment]
Anyway to solve this without starting with a fresh world?

**Comment by mindforger** [comment]
if i remember right, launch without sponge should work ... but oh well :)

**Comment by CitrusFruit** [comment]
I don't use Sponge though, I'm using Forge.

**Comment by HenryLoenwind** [comment]
Open the world in mcedit and find the turtle at -4304,63,787. One of the neighbor blocks is a "light node", (that is a block that looks and feels like air but gives off light). Delete it. Get back into the game, switch the electric light that produced that light node off and on again.

**Comment by CitrusFruit** [comment]
There is no turtle at those co-ords, when I goto the co-ords I am taken to an ocean biome with nothing else.

**Comment by HenryLoenwind** [comment]
Interesting. I took that ccordinate from the crash report:

```
Block location: World: (-4304,63,787), Chunk: (at 0,3,3 in -269,49; contains blocks -4304,0,784 to -4289,255,799), Region: (-9,1; contains chunks -288,32 to -257,63, blocks -4608,0,512 to -4097,255,1023)
```

**Comment by CitrusFruit** [comment]
Yeah, literally nothing there apart from an ocean, I also know for a fact no one has got a 'turtle'.

**Comment by HenryLoenwind** [comment]
No turtle? Then this means that the ID mapping of your world got corrupted, possibly by an earlier crash. Restore it from a backup...

Background: The save file stores the numeric ID of the blocks to keep the size down. For vanilla those IDs stay the same as vanilla always has the same blocks. But with modded what blocks are available varies and can even change over time. This is what happened here. Between when you started the world and now some mod(s) got updated, resulting in a different mapping. As long as the original mapping is available, the game can handle that just fine---existing blocks keep their IDs and new blocks get unused IDs at the end. But if that mapping is lost it has to recreate it, and new blocks get IDs at their natural position, meaning that the IDs in the world save no longer correspond to the right blocks. In your case, the ID that was used for a conduit bundle before, now is a light node. And something else now is a turtle.
