### ISSUE TITLE
Why is 1.11.2 EnderIO is taking so long?

### ISSUE THREAD

**Issue by BENDY123** [SleepyTrousers/EnderIO#4284]
Why it's taking so long?
It's because you don't want to do?
Or just making new things to the mod?

**Comment by BENDY123** [comment]
Creator of EnderIO you need to awnser this questions

**Comment by andyb2** [comment]
"Status for the update to 1.11.2: Time spent: ~180 hours. Updated: ~30%. Stop nagging us, or we might notice we know ways to spend our time doing things that are more enjoyable."  Surprised they havent deleted your post yet
