### ISSUE TITLE
[Suggestion]Add more Dark tools

### ISSUE THREAD

**Issue by fluid-uu-matter** [SleepyTrousers/EnderIO#4285]
I really love the Dark Axe and the Dark Pick. They are very cool because They are long-last, upgradeable, and rechargeable. So I also want some other tools:
Dark hoe which can be upgraded for pre-moistening the tilled soil. 
Dark Treetap powered by RF for IC2, can tap all the tappable rubber wood in an area, and the area is based on the energy tier. Only enables if IC2 is installed.
Dark scyche. Can harvest leaves and plants from a large area such as Thermal Foundation ones does,but range can be upgraded by upgrading storage.
Ender sparyer which can spary IC2 Construction foam and other blocks that has liquid form like IE concerete from a distance and with 3 modes: Single,3x3x3 and random.
Ender Drill. Has the same upgrades as the Dark pick's, but only the drill head is destructable. Craft with expensive ingredients, and drill head is craft from a lot of dark steel.
Tier 4 Capacitors. Only appears as a rare treasure capacitor, only works as a machine upgrade, and has twice the speed and the energy storage of the Octadic one. When inserted in generator, gain 150% effiency.
I also want a change on existing item:
Electromagnet wil has a slot to insert filter in. Once inserted, It won't suck the blacklisted items like the vacuum chest does.

**Comment by mindforger** [comment]
>Electromagnet wil has a slot to insert filter in. Once inserted, It won't suck the blacklisted items like the vacuum chest does.

how about a block (not a full block but something placeable, like a torch with an coil, or maybe a variant of an obelisk) that inhibits magnetism/vaccuum in a resizeable area? something like an attraction nullifier ... this way one could also limit the effective area of a vaccuum chest too ;D

**Comment by MatthiasMann** [comment]
@mindforger The botania flower also works on the electro magnet

**Comment by mindforger** [comment]
yeah i know .. i woukld love to have that feature without botania :) i try not to mix magical stuff and technical too much normally

**Comment by VT-14** [comment]
Ender IO's suggestion tracker is here: ideas.theideawall.com/EnderIO

There are already loot capacitors.  I personally don't see a major benefit of having an RF mod add IC2 content that IC2 already adds.  Otherwise, I'm liking the ideas here.

**Comment by Ezoteric** [comment]
TBH it would be nice to have the IC2 treetap work in the farm station tho :)

**Comment by VT-14** [comment]
IC2 treetaps already do work in the farming station.

**Comment by Ezoteric** [comment]
not here it does not :S 
using 1.10.2 tho

**Comment by RogueWarrior76** [comment]
Wouldn't mind a Dark Steel hammer for skyblock hammering of cobble, gravel, sand, etc...

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
