### ISSUE TITLE
Different Farming Station Crash

### ISSUE THREAD

**Issue by AtaxiaGames-GM** [SleepyTrousers/EnderIO#4287]
#### Issue Description:

Using Ender IO on Minecraft 1.10.2 with FML 2185:
When placing minecraft:diamond_axe inside of an Ender IO Farming Station, the server crashed. This was then tested in a single player environment using minecraft:stone_axe to the same effect. I believe that using any axe would lead to a crash in this case.

#### What happens:

Set an Ender IO Farming Station
Place an axe in said Farming Station (again, only actually tested with minecraft:stone_axe and diamond_axe.
Server crashes with [this crash report](https://pastebin.com/V9vFKEj2), which appears to also have a reference to Toast's Special AI - Toast has also been notified of this issue.

#### What you expected to happen:

Set an Ender IO Farming Station.
Place an axe in said Farming Station.
Farming Station becomes active if there is power to it.

#### Steps to reproduce:

1. Set an Ender IO Farming Station
2. Place an axe in said Farming Station.
3. Watch crash occur.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66
- Special_AI: 1.1.3 (appears to be related in the crash report)
- Minecraft: 1.10.2
- Forge: Build 2185

#### Your most recent log file where the issue was present: 

[Crash Report](https://pastebin.com/V9vFKEj2)

**Comment by HenryLoenwind** [comment]
Tell Toast toi use the getter, that's what it's there for...

```
    public VillageCollection getVillageCollection()
    {
```

**Comment by AtaxiaGames-GM** [comment]
Is it possible for  one of you (a fellow developer) to tell that to him. I imagine that devs don't like the users to tell them how to dev... especially because I am not a dev.

**Comment by AtaxiaGames-GM** [comment]
Is it possible for  one of you (a fellow developer) to tell that to him? I imagine that devs don't like the users to tell them how to dev... especially because I am not a dev.

**Comment by HenryLoenwind** [comment]
Just link in this ticket or vice versa.

**Comment by AtaxiaGames-GM** [comment]
[Cross-post Link](https://minecraft.curseforge.com/projects/special-ai?comment=19)

**Comment by mindforger** [comment]
i think he has an github repo https://github.com/FatherToast/SpecialAI
