### ISSUE TITLE
Arraylist 

### ISSUE THREAD

**Issue by lAimBotl** [SleepyTrousers/EnderIO#4288]
This wan't said to me but I didn't see him report this here so I decided to do it.
Hope I ain't wasting your time, I don't know java/coding stuff.

"OvermindDL1 :

"at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
at java.util.ArrayList$Itr.next(Unknown Source)
at com.enderio.core.common.util.Scheduler.runTasks(Scheduler.java:120)
at com.enderio.core.common.util.Scheduler.onClientTick(Scheduler.java:113)"

This means that enderio is  adding/removing elements from an arraylist while they have an open iterator to that arraylist. Report it to them.

there is arraylist mutation happening through calls after calls after calls in a an iteration loop that are hell to track down. Never ever ever ever allow any arraylist that can be iterated to be exposed publicaly and be sure to batch alterations to them for after the iteration is done (set a sentinel value and if set put 'modification commands' in another list then iterate that one to modify the main one every time an iteration of the main one is complete)."

**Comment by alakazamimserous** [comment]
Okay, so how do I set a sentinel value and where? Sorry, ain't quite keen on this

**Comment by tterrag1098** [comment]
This is a bug which is long since fixed, just update.
