### ISSUE TITLE
[1.10.2] [Suggestion] Use OrdDict for fertilizer in Farming Station

### ISSUE THREAD

**Issue by s4msung** [SleepyTrousers/EnderIO#4290]
As I added all the fertilizer variants in my private pack to ore:fertilizer, i tried to figure out how i could make the farming station use them.

So here my suggestion: make it configurable or just use the oredict version for fertilizer

**Comment by HenryLoenwind** [comment]
Method of application is different for different items, that's why there is no list in the config like dere is for hoes...
