### ISSUE TITLE
wither skel replacement: connection terminated without generating log data

### ISSUE THREAD

**Issue by shadoxxhd** [SleepyTrousers/EnderIO#4292]
#### Issue Description:
when skeleton replacement is enabled, the client shows 'a fatal error has occured, connection was terminated'. server console registers a normal disconnect while the client log shows no sign of any issue.

goal of issue post: some sort of error logging for wither skeleton issues - I don't expect you to fix every possible weird mod interaction

#### What happens:
'a fatal error has occured, connection was terminated', no error description

#### What you expected to happen:
working wither skeletons or description of error, so fixing it on the other mods side (or by private bytecode mod) is possible

#### Steps to reproduce:
1. come as close to my modpack as possible
2. change replaceWitherSkeleton to true
3. try to connect to server
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.492_beta
- EnderCore: 0.0.2.39_beta
- Minecraft: 1.7.10
- Forge: 7.99.40.1614

using a modified infitech 2 modpack; modlist: https://pastebin.com/Cs3aChfG

#### Your most recent log file where the issue was present: 
irrelevant; exactly the same as normal, but you DC on first game tick

**Comment by shadoxxhd** [comment]
btw ... wouldn't it be easier to add a wither bool to soul vials + powered spawners instead of replacing a vanilla entity?

**Comment by HenryLoenwind** [comment]
replaceWitherSkeleton is off by default and was removed in later versions for a reason...

**Comment by shadoxxhd** [comment]
does this mean you won't even add error logging? if not, please consider adding another way of making it possible to spawn wither skeletons, like flags or 'exact copy' mode.
