### ISSUE TITLE
Incorrect behaviour when shift clicking crafting result in inventory panel

### ISSUE THREAD

**Issue by PhilGooodInc** [SleepyTrousers/EnderIO#4296]
#### Issue Description:
Incorrect behaviour when shift clicking crafting result in inventory panel

#### What happens:
Shift Clicking the crafting result only crafts one item, not all possible  eg 10 wood logs placed in crafting grid, should craft 40 planks with a shift click, but instead only crafts 4 at a time

#### What you expected to happen:

All possible crafting results to be created at once with a shift click.

#### Steps to reproduce:

1. Use Inventory Panel
2. Insert 10 wood into crafting grid
3. Shift click planks

Happens in both mod pack, and fresh instance with just EnderIO and EnderCore of same versions

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.193
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2316

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://gist.github.com/PhilGooodInc/6117c08587e432dcf24fed58106348b7

**Comment by A-UNDERSCORE-D** [comment]
Confirming this for 1.10.
EIO version 1.10.2-3.1.183
EnderCore version 1.10.2-0.4.1.66-beta
There were other mods present
logs:
https://gist.github.com/A-UNDERSCORE-D/4a4c073274042607df6f52184747e014
