### ISSUE TITLE
Farming station + chorus fruit on SpongeForge server = crash

### ISSUE THREAD

**Issue by kaal-1** [SleepyTrousers/EnderIO#4297]
#### Issue Description:
Farming station crashes SpongeForge server, apparently when used to farm chorus fruit only.

#### What happens:
The server crashes.

#### What you expected to happen:
The server not crash.

#### Steps to reproduce:
1. Plant some chorus fruit
2. Power a farming station
3. Wait

____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: EnderIO-1.10.2-3.1.193
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 2281
- SpongeForge 1.10.2-2281-5.2.0-BETA-2464 

#### Crash report:
https://hastebin.com/ijufafovun.http

**Comment by HenryLoenwind** [comment]
That's on Sponge's side.

**Comment by liach** [comment]
It is still the fake world bug.

**Comment by kaal-1** [comment]
Fixed on sponge side https://github.com/SpongePowered/SpongeCommon/commit/f6d98e6401ca92029dc20e9b2f89cb9cab1963e7
