### ISSUE TITLE
Ender IO crash 1.7.10

### ISSUE THREAD

**Issue by ultravioletthd** [SleepyTrousers/EnderIO#4298]
#### Issue Description:
I installed the latest version of Ender IO for 1.7.10 from curse, upon launch it immediately crashed. I looked at the crash report and it reads: Initializing game

java.lang.IllegalArgumentException: minecraft:beetroot_seeds is not a vaild string. Strings should be either an oredict name, or in the format objectname;damage (damage is optional)
	at com.enderio.core.common.util.ItemUtil.parseStringIntoRecipeItem(ItemUtil.java:104)  
that is not the whole script as it is very long. just to be clear, Ender IO was the only mod i had installed

#### Steps to reproduce:

1. install forge and Ender IO versions listen below
2. launch game (if you are unable to reproduce the crash I apologize for wasting your time)
3.
...

____
#### Affected Versions:

- EnderIO: 1.7.10-0.2.0.39
- EnderCore: 1.7.10-2.3.0.429 
- Minecraft: 1.7.10
- Forge: 1.7.10-Forge 10.13.1566

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
beetroot_seeds doesn't exist in 1.7.10. remove it from your crops.json

**Comment by HenryLoenwind** [comment]
PS: You are using config files from an 1.10.2 installation with 1.7.10. Don't do that.

**Comment by Reactorcorefan213** [comment]
HELP I HAVE THE SAME!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Reactorcorefan213** [comment]
oh ik maybe remove beetroot seeds form the json?
