### ISSUE TITLE
[Request] Fluid conduit pipes transparancy

### ISSUE THREAD

**Issue by Ezoteric** [SleepyTrousers/EnderIO#4300]
Got a question here about the fluid conduits

im using sphax, and i made the ender fluid conduit looking the same as the normal conduit hoping to see its liquid flowing throug it but i cannot see fluid :( is this code wise disabled or is it still a texture problem ?

If it is code wise could there be a option to make it viewable ? :) i love eyecandy :D

**Comment by HenryLoenwind** [comment]
Ender fluid conduits don't have contents. Same as item c. They teleport directly from source to target.

**Comment by Ezoteric** [comment]
Aaah that explains :) Thnx m8
