### ISSUE TITLE
EnderIO Item Filter Bug (1.7.10)

### ISSUE THREAD

**Issue by geong1** [SleepyTrousers/EnderIO#4301]
Issue Description: Placed an itemfilter into a insert node. Set to whitelist. Placed a extractor node on another chest, going into the insert node. Turned it on.

Setup like so: (Chest1) -> (Extractor node, turned on) -> (Item Conduit) -> (Insert Node - with nothing whitelisted, but whitelist selected) -> (Chest2)

All the items drained out of the chest1 and into chest 2.

Why does it not filter the items?

Steps to reproduce:

1. Do the above setup
2. Setup as I described above: (Chest1) -> (Extractor node, turned on) -> (Item Conduit) -> (Insert Node - with nothing whitelisted, but whitelist selected) -> (Chest2)
3. Profit????

____
Affected Versions : I know it said not to post for unreleased...Does beta count as unreleased???

- EnderIO:  1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-0.2.039_beta
- Minecraft: 1.7.10
- Forge: 7.10.99.99

Your most recent log file where the issue was present: 

The server didn't detect this as a crash worthy bug, do I need to post something here?

**Comment by HenryLoenwind** [comment]
Works as designed. Empty filter does nothing.

**Comment by geong1** [comment]
It's set to whitelist, shouldn't that block everything trying to get through it...?

**Comment by HenryLoenwind** [comment]
No, it's in "unconfigured" mode when set that way.

**Comment by geong1** [comment]
Hold on - Changing it to blacklist one specific item to test.

**Comment by geong1** [comment]
Thanks for your help! Guess I'm spoiled by the Whitelist Filters in Thermal Dynamics. :)
