### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by SpikeVanHellsing** [SleepyTrousers/EnderIO#4302]
#### Issue Description:
Randomly crashes when using the pipes and i cannot figure out why.

#### What happens:
It crashes my modpack when interacting, looking at, covering with a facade or sometimes on world load.

#### What you expected to happen:
Not crash.

#### Steps to reproduce:

Not sure as it doesnt always happen.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-0.2.39_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

#### Your most recent log file where the issue was present: 

open eye log: https://openeye.openmods.info/crashes/6172b170e66981744396133b36aeaac3
minecraft log: https://pastebin.com/XT7JRVxF

**Comment by HenryLoenwind** [comment]
That's Optifine.

**Comment by SpikeVanHellsing** [comment]
ah ok, would you suggest updating it or removing it?

**Comment by tterrag1098** [comment]
Either or both
