### ISSUE TITLE
Unable to paint wood planks

### ISSUE THREAD

**Issue by wolfrunner86** [SleepyTrousers/EnderIO#4303]
#### Issue Description:
I am unable to paint any wood planks  version 1.10.2-3.1.183

#### What happens:
i put in source block and a plank and it wont paint it

#### Steps to reproduce:
1.put a block in slot 1 
2.put a wood plank in slot 2
3.nothing happens
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:3.1.183
- EnderCore:0.4.1.66
- Minecraft: 1.10.2
- Forge:12.18.3.2316

#### Your most recent log file where the issue was present: 

[latest.txt](https://github.com/SleepyTrousers/EnderIO/files/1202617/latest.txt)

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Where did you get the idea that wood planks could be painted from?
