### ISSUE TITLE
[1.10.2] Farming Station with Silent's Gems' Hoe causes crash

### ISSUE THREAD

**Issue by thephoenixlodge** [SleepyTrousers/EnderIO#4304]
#### Issue Description:
As per title, using a hoe from SG in the farming station results in a crash when the farming station tries to work. I expect this is due to outdated compatibility.
Reproduced both in the Sprout modpack, and in an instance with only EnderCore, EIO, SilentLib, SG and JEI.

#### What happens:
Crash.

#### What you expected to happen:
Farming station to work as per normal.

#### Steps to reproduce:

1. Place farming station
2. Add SG Hoe, any sort of seed and power (basically, meet reqs for the station to run with a SG Hoe).
3. Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.193
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2422
- SilentLib: 1.10.2-2.1.5-63 (also reproduced on 1.10.2-2.2.6-66)
- Silent's Gems: 2.3.16-186 (also reproduced on 2.4.5-213)

#### Your most recent log file where the issue was present: 
https://pastebin.com/Zzdqne3M

**Comment by MatthiasMann** [comment]
That crash happens within the Silent Gem's mode code - so report it to them.
