### ISSUE TITLE
[1.7.10] Ender IO Problem (Crash)

### ISSUE THREAD

**Issue by TheLyroVZ** [SleepyTrousers/EnderIO#4308]
#### Issue Description:
Everything works fine. Then I build something with Ender IO and now it crashs every few minutes.
(It's a self made modpack).
Maybe it's not Ender IO but it crashs since I used Ender IO.

#### What happens:
I only used the Ender Conduits and now it's crashing. 

#### What you expected to happen:

No crash

#### Steps to reproduce:

1.Start minecraft
2.Wait
3.It crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 1.7.10-10.13.4.1614

#### Your most recent log file where the issue was present: 

Crash:
https://pastebin.com/eiF51TcR

Log:
https://pastebin.com/cm98thSx

**Comment by HenryLoenwind** [comment]
1. Optifine is not supported.
2. There's nothing about Ender IO in the crash:

```
    at vazkii.botania.client.render.tile.RenderTilePool.renderIcon(RenderTilePool.java:157)
    at vazkii.botania.client.render.tile.RenderTilePool.func_147500_a(RenderTilePool.java:141)
    at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
    at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
```

**Comment by TheLyroVZ** [comment]
So I can't play with Optifine? Or is there a specific version of Optifine that works?
