### ISSUE TITLE
Soul Vial Doesn't Stay In Hand

### ISSUE THREAD

**Issue by natedogith1** [SleepyTrousers/EnderIO#4310]
#### Issue Description:
When capturing mobs with a soul vial, the filled soul vial will end up in a different spot in your inventory, even if the soul vial had a stack of size 1.  If your inventory is full, the filled soul vial will be dropped on the ground, instead of being in the now empty space where the empty soul vial was.

#### What happens:
The filled soul vial will be in your first available inventory slot.

#### What you expected to happen:
The filled soul vial will remain in the same slot.

#### Steps to reproduce:

1. get a single empty soul vial
2. right click a mob with it

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.192
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2316

**Comment by HenryLoenwind** [comment]
"Out of date" as in "already changed in 1.11"
