### ISSUE TITLE
[Crash] Nullpointerexception

### ISSUE THREAD

**Issue by Chemox** [SleepyTrousers/EnderIO#4311]
#### Issue Description:
When placing an advanced sensor next to an enderio inventory scanner the game instantly crashes with a "nullpointerexception"

#### What happens:
The game crashes with an "nullpointerexception"

#### What you expected to happen:
Nothing

#### Steps to reproduce:
1.  Place Xnet advanced blue connector
2.  Place enderio inventory scanner next to it
3.  Client Crash

#### Affected Versions (Do *not* use "latest"):
- Minecraft{1.10.2}
- Forge{12.18.3.2316}
- Endercore{1.10.2-0.4.1.66-beta}
- EnderIO{1.10.2-3.1.193}
- xnet{1.3.2} and xnet{1.4.0}

#### Your most recent log file where the issue was present: 
Only xnet+enderio: [https://pastebin.com/JTEuGvdY](https://pastebin.com/JTEuGvdY)
In FTBBeyond: [https://pastebin.com/epFhWJ3j](https://pastebin.com/epFhWJ3j)

#### Reported to xnet --> Closed by modauthor
[https://github.com/McJty/XNet/issues/148](https://github.com/McJty/XNet/issues/148)

**Comment by MatthiasMann** [comment]
EnderIO expects the side to be non null (even so it is not annotated that way).

**Comment by HenryLoenwind** [comment]
Look at the Javadoc and call pattern. Null is a valid value here. It means that a block that is diagonally below the block is checking. Used in vanilla for redstone to go up.
