### ISSUE TITLE
[Suggestion] Block Exchange Item

### ISSUE THREAD

**Issue by Vastrix** [SleepyTrousers/EnderIO#4312]
#### Feature Suggestion:
Would it be possible to add an item that replaces blocks (in a certain radius) with another type of block?

Kinda like the wand of equal trade (TC), or the exchanger from ender tech..
but then the better and improved Ender-IO version? :)

**Defense:**
It fits the mod's theme more than any other.. I mean.. Ender ... IO
We're Inputting new blocks and Outputting the old ones in the inventory through the magic of Ender.. :)

Thanks!

**Comment by HenryLoenwind** [comment]
Plenty of mods have this, I don't see much sense in us duplicating those...

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
