### ISSUE TITLE
[Suggestion]Allow hiding of travel anchors from the staff/travel UI

### ISSUE THREAD

**Issue by Glockshna** [SleepyTrousers/EnderIO#4314]
If possible it would be nice to be able to hide travel anchors completely in the travel UI. I'm using them as elevators as well as travel points and the UI gets very cluttered since every travel anchor in my base is doubled to I can access the 'sewers' for cable maintenance and so forth. I'd like to hide the lower ones.

[Here's](https://dl.dropboxusercontent.com/s/j3kijz28wbuzb8w/2017-08-15_15-35-41.png) an example of what it looks like. This works with the scale turned down but from certain locations in my base it gets difficult to hit the right anchor.

**Comment by xenxero1** [comment]
It'd be nice to have a checkbox for them when you set up the anchor. "Visible with staff", "Visible from Anchor", "Visible to All" especially with the security settings we have already.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
