### ISSUE TITLE
[Suggestion] ability to combine any conduit before placing them.

### ISSUE THREAD

**Issue by RepoDraghon** [SleepyTrousers/EnderIO#4317]
I'd like to add the ability to combine the conduits as if I place them normally but be able to combine them and disassemble them as I want in the crafting grid for 1.12

For reference, Iron Backpacks (not yet for 1.12) uses the crafting grid to add upgrades and take those upgrades off. The same could, I assume, be used the same way for the disassembly...

I don't know if this makes any sense but it does to me, just getting it to do it the way I would like is not easy to express...

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
