### ISSUE TITLE
Error FR Api in EnderIO-1.7.10-2.3.0.429_beta.jar

### ISSUE THREAD

**Issue by DatRalf** [SleepyTrousers/EnderIO#4320]
#### Issue Description:

Error in RF Api and Minecraft Server crash:

EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.1.0 from SonarCore-1.7.10-1.1.3.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

#### Steps to reproduce:

1. Placing the EnderIO Versions in my mods folder
2. Starting Server
3. Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta.jar
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta.jar
- Minecraft: 1.7.10 yes
- Forge:forge-1.7.10-10.13.4.1614-1.7.10-universal

#### Your most recent log file where the issue was present: 

https://www.pastiebin.com/599ed2635e65c

**Comment by mindforger** [comment]
Did you even read what you posted?

It is a supported version, but that difference **may** lead to problems.
This **may** have caused the error. **Try reproducing the crash WITHOUT this/these mod(s) before reporting it**.

the error is right at the start of your crashlog .... something between mekanism and codechicken chunkloaders

**Comment by DatRalf** [comment]
I am sorry this is my first experiency with crash logs.
