### ISSUE TITLE
Milk Dupe Bug

### ISSUE THREAD

**Issue by zack-emmert** [SleepyTrousers/EnderIO#4324]
#### Issue Description:
Milk duplication occurs when EnderIO is installed and a milk bucket is added to tanks from any mod besides EnderIO

#### What happens:
When a milk bucket is placed into a tank from a non-enderio mod, the tank gains milk without the bucket emptying.

#### What you expected to happen:

The bucket should empty, adding 1000mB of milk into the tank

#### Steps to reproduce:

1. Install EnderIO and any other mod that ads fluid tanks (eg: Mekanism, Tinker's, OpenBlocks)
2. Place milk bucket into non-enderio tank

____
#### Affected Versions\:

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.66
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2422

#### Your most recent log file where the issue was present: 

Issue not reflected in logs

**Comment by HenryLoenwind** [comment]
Just to clarify: When you use the vanilla milk bucket with a another mod's tank, you get another mod's milk liquid and keep the vanilla milk bucket?

If that's correct, I don't really know what's happening. Ender IO isn't involved there at all. For one, it does nothing with or to milk or the milk bucket, and it is not mess with other mod's block's or the milk bucket's right-click interaction.

Have you tried it with milks that were added by different mods? If not, I'd suspect that the mod that is adding the milk fluid may be registering its bucket interaction incorrectly.

**Comment by zack-emmert** [comment]
Hmmm... I thought EnderIO was involved because EnderIO tanks were the only ones handling it properly. But if EnderIO doesn't touch it than I'm not sure what to think

**Comment by MatthiasMann** [comment]
@zack-emmert have you tried these other mod tanks / milk buckets in a world without EnderIO and EnderCore installed?

**Comment by PapiDimmi** [comment]
Milk’s easy to get anyway.

**Comment by CenTdemeern1** [comment]
what he meant: use an enderio conduit to get that bucket into the tank from ex. TConstruct
