### ISSUE TITLE
copy filter configurations

### ISSUE THREAD

**Issue by GizmoTheGreen** [SleepyTrousers/EnderIO#4325]
#### Issue Description:
feature request
I have a configured basic filter, now I want to replace it with an advanced for the extra slots to expand my automation, now I have to re-acquire all the blocks/items to remake the configuration

it would be nice to have a way to just copy the config between item filters (between different ones where it makes sense, like basic -> advanced)

I searched the Issues but didn't find anything relevant but feel free to close/remove this if I missed one

#### What happens:
for example let's do it with the conduit probe
shift rightclick conduit with the old filter inside

nothing happens currently (to the filter that is)

#### What you expected to happen:
rightclick same conduit or other conduit with advanced filter to repopulate the config with block/items

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2422

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
