### ISSUE TITLE
Fatal Error Found :<

### ISSUE THREAD

**Issue by Hyperbear88** [SleepyTrousers/EnderIO#4326]
#### Issue Description:
"Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION."
A severe problem during mod loading that has caused the game to fail
cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: redstone_lamp
#### What happens:
When Forge is launched with EnderIO and EnderCore placed in the mods folder for Forge, this exception was thrown.
java.lang.NoSuchFieldError: redstone_lamp
	at crazypants.enderio.conduit.redstone.InsulatedRedstoneConduit.<clinit>(InsulatedRedstoneConduit.java:67) ~[InsulatedRedstoneConduit.class:?]
#### What you expected to happen:
The game would launch as usual, with the extra funtionallity of Ender IO and EnderCore added.

#### Steps to reproduce:

1.Place Ender IO (EnderIO-1.7.10-2.3.0.428_beta-dev) and Endercore (EnderCore-1.7.10-0.2.0.35_beta) inside the Forge mods folder
2.Launch the game
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.428_beta-dev
- EnderCore: EnderCore-1.7.10-0.2.0.35_beta
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1558-1.7.10

#### Your most recent log file where the issue was present: 
[latest.txt](https://github.com/SleepyTrousers/EnderIO/files/1285320/latest.txt)

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
https://www.google.de/search?q=java.lang.NoSuchFieldError%3A+redstone_lamp

**Comment by Hyperbear88** [comment]
This bug is still present on a none dev version of Ender IO - EnderIO-1.7.10-2.3.0.429_beta.
