### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Hyperbear88** [SleepyTrousers/EnderIO#4327]
#### Issue Description:
Fatal error was detected during the transition from POSTINITIALIZATION to AVAILABLE.

#### What happens:
Once Forge reaches the Postinitializtion stage, Minecraft crashes.

#### What you expected to happen:
Nothing

#### Steps to reproduce:

1. Place EnderCore-1.7.10-0.2.0.39_beta.jar or EnderCore-1.7.10-0.2.0.35_beta.jar &
EnderIO-1.7.10-2.2.8.379.jar into Forge Mods Folder
2. Launch Forge.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.2.8.379.jar
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta.jar or EnderCore-1.7.10-0.2.0.35_beta.jar
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

(https://github.com/SleepyTrousers/EnderIO/files/1289619/latest.-.Copy.1.txt)

**Comment by MatthiasMann** [comment]
Your config file is invalid:
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 15 column 21
