### ISSUE TITLE
[Suggestion] Blacklist for Wireless Charger

### ISSUE THREAD

**Issue by DerMax93** [SleepyTrousers/EnderIO#4328]
The wireless charger will charge any item in your inventory if you are in range of it.
For some items (eg Draconium blocks) it might not be desirable to have them charged this way.
Maybe you could consider adding a config-option to blacklist certain items from being charged by the wireless-charger.
It isn't a big problem per se but can be quite confusing at first and can get annoying if the differing levels of charge prevent the blocks from stacking.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
