### ISSUE TITLE
Feature Request: Counting Fluid Filter?

### ISSUE THREAD

**Issue by Zetharion** [SleepyTrousers/EnderIO#4329]
#### Issue Description:
There is a counting item filter for keeping only certain amounts of items in a connected inventory.  Would it be possible to do the same for fluids to keep a connected inventory full of only a certain amount of a fluid?

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.10.2
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
