### ISSUE TITLE
EnderIO wiki down

### ISSUE THREAD

**Issue by Sinhika** [SleepyTrousers/EnderIO#4331]
#### Issue Description:

EnderIO wiki is down, with a domain expired message

#### What happens:

I go to the usual bookmark, www.enderio.com, and get a "Domain expired" message

#### What you expected to happen:

I expected to view the main documentation for the EnderIO mod via the EnderIO wiki

#### Steps to reproduce:

1. Open the web browser of your choice
2. Enter URL http://wiki.enderio.com/Main_Page
3. Get empty page with "This Domain Name has expired"
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: all

#### Your most recent log file where the issue was present: 

N/A

**Comment by danielhickman** [comment]
[Archive.org](https://web.archive.org/web/20170608054139/http://wiki.enderio.com/Main_Page) works if you just need to check something. The domain was registered a few days ago and there's still nothing on it. Hopefully, it isn't a squatter. GitHub's wiki could always be updated and used in the future.

**Comment by tterrag1098** [comment]
I'm still in control of the domain, I just need to rehost the website.

**Comment by D3nnis3n** [comment]
Hooray, already thought this mod was dead. One of the best mods ever. Sooo much conduits in one block.

**Comment by tterrag1098** [comment]
The website is now up again, the wiki will take a bit more work, but both should at least no longer 404
