### ISSUE TITLE
The RF API that is being used differs from the one being loaded.

### ISSUE THREAD

**Issue by jacobyzx** [SleepyTrousers/EnderIO#4332]
#### Issue Description:
The RF API that is being used differs from the one being loaded. It tells me this and then a different mod each time it crashes. I don't know what to do and this is not an official modpack. I also didn't know which developer I should write to because of all the different mods that it has listed. I'm sorry if I broke any guidelines I'm new to the modding scene as the last time i played modded minecraft was back in 1.4ish.

#### What happens:
I start the game and after loading for a little bit it crashes and gives me a crash report.

#### What you expected to happen:
I expected my game to load up without crashing.

#### Steps to reproduce:

1. I have tried several times disabling different mods, but each time it says another mod is the issue.
2. It has said "The RF API that is being used differs from the one being loaded" and then listed a mod. It has listed several different mods. 
3. Mods that have been listed include SolarFluxReborn, p455w0rdslib, valkyrielib, mcjtylib, EngineersWorkshop, Mekanism, quantumflux, CoFHCore. Sometimes no changes have been made and it still switches which mod it blames.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.183
- EnderCore: 0.4.1.66
- Minecraft: 1.10.2
- Forge: 12.18.3.2488

#### Your most recent log file where the issue was present: 

https://pastebin.com/6bDdSD5z

**Comment by mindforger** [comment]
>EnderIO: Found the following problem(s) with your installation (**That does NOT mean that Ender IO caused the crash or was involved in it in any way**. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.

>    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

>java.lang.NullPointerException: Initializing game
    at net.minecraft.client.renderer.block.model.ModelBakery.func_177596_a(ModelBakery.java:441)

and just by google i can link you this https://minecraft.curseforge.com/projects/craft-of-the-titans/issues/196
and to hand you to the maybe solution right away: 
# If true replaces the vanilla milk bucket so milk can be placed in the world.
B:MilkBucket=false

 this an MFR Issue page that shows that it fixes

https://github.com/skyboy/MineFactoryReloaded/issues/600

**Comment by jacobyzx** [comment]
I am no longer crashing and I disabled the milk bucket for both forestry and MFR but i can still place milk. Do you know of any other mods that add that feature because I want to make sure this never happens again? If not that's fine. Thank you so much for your help. I'm really sorry that I bothered you with the RF API thing. I just didn't know what to do and as you can probably tell I have no idea what I'm doing. So I sincerely apologize. I know it said not to post here if it wasn't an ender io problem but since I have no idea what I'm doing I didn't know where to post. Also do you know of a general support place so I don't post in the wrong place again?

**Comment by mindforger** [comment]
i was just mildly annoyed (yeah i know this word has a very negative taste but i don't mean to sound mean ...) thats why i wrote it that way

i mean there sure is a iteral ton of indormations in this reports but the informations below the modliste are pure diagnostic and have nothing to do with the issue in 99% of cases but they still get reported over and over 

the other thing is, by using google on the first 2 or 3 lines of an exception printout like this:
>java.lang.NullPointerException: Initializing game
at net.minecraft.client.renderer.block.model.ModelBakery.func_177596_a(ModelBakery.java:441)

you can find out really quick if you either have an alsready known issue or something new (when google only shows a hand full of responses)

also a hint for future issues, 
look down the full trace and focus on the package names like "net.minecraft." ... if you see multiple mods interacting 
especially if there is something called blabla**OF** or optifine as clear text, always try to remove optifine first, same goes for FTBU or anything related to chunkloading stuff like chickenchunks and similar

**Comment by jacobyzx** [comment]
Ok thank you I'll put that info to future use.  I thought the diagnostic thing meant the stuff below it not above it since it tells you to scroll up. That just confused me a little. Again I am really sorry that you had to deal with me.

**Comment by mindforger** [comment]
>Again I am really sorry that you had to deal with me.

that made me laugh XD
you did nothing wrong to apologize this much, you just hit the nail's head dead on that was sticking inside a fleshwound sprinkled with salt ... and i was at the beginning of my first coffee of the day ... coincidence and heavy triggering on my side, i am sorry too

**Comment by jacobyzx** [comment]
I just don't like annoying the people that put effort into making my life easier.
