### ISSUE TITLE
Staff of Traveling can teleport through world border.

### ISSUE THREAD

**Issue by disba1ancer** [SleepyTrousers/EnderIO#4334]
#### Issue Description:
Staff of Traveling (and other like items) can teleport through world border.

#### What happens:
Teleporting happens through world border.

#### What you expected to happen:
Teleporting has to happen like through bedrock wall.

#### Steps to reproduce:

1. Go to world border.
2. Teleport through world border by Staff of Traveling (or other like item).

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.183
- EnderCore: 0.4.1.66
- Minecraft: 1.10.2
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HempNight** [comment]
the dev is a piece of shit good luck getting help
