### ISSUE TITLE
Client crash when painting Travel Anchor with demon metal

### ISSUE THREAD

**Issue by scalda** [SleepyTrousers/EnderIO#4335]
#### Issue Description:
been reported to the foolcraft issues page https://github.com/scalda/FoolCraft/issues/780

#### What happens:
when painting travel anchors with demon metal the client crashes

#### What you expected to happen:
the travel anchors to come out painting with the demon metal texture

#### Steps to reproduce:

1. get a painting machine
2. place travel anchors and demon metal block in
3. game will crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.193
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2422

#### Your most recent log file where the issue was present: 

[[pastebin/gist/etc link here]](https://pastebin.com/VE7iBzSi)

**Comment by HempNight** [comment]
Stop wasting ur time postin here the mod owner is a piece

**Comment by HempNight** [comment]
Don't dislike my post look for ur self no up dates in for month's fuck the mod dev

**Comment by mindforger** [comment]
you know this is a lie and the dev is working hard
he is doing it in his free time dude for FUCKING FREE ... he owes you nothing and if you follow the repo you will see he works **every fucking day** ... so shut up and play something else if you have an issue with his work

i am utterly sorry for taking the bait and ranting in this issue, please feel free to remove my post whenever you feel

**Comment by HempNight** [comment]
Lol every fucking there has been no work in 4 months his web site and wiki are down. The mod is dead and that piece of shit dosint tell any one

**Comment by tterrag1098** [comment]
Did you post this to the wrong issue? I can't really figure out what you're reacting so strongly to, this seems like a pretty standard bug report to me.

**Comment by mindforger** [comment]
the offending posts got removed and i can't edit mine on mobile, you can delete it

**Comment by HenryLoenwind** [comment]
This is a combination of a vanilla bug and demon metal having broken block states. (ok, one could argue that it's not a bug for vanilla to crash on broken block states...)
