### ISSUE TITLE
[Suggestion] bundled redstone API

### ISSUE THREAD

**Issue by octarine-noise** [SleepyTrousers/EnderIO#4336]
I'd like to see an extension to the API to allow blocks/TEs to connect to the insulated redstone conduit as a whole, and provide/receive the full set of signals.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
