### ISSUE TITLE
Chromaticraft + EnderIO Dedicated Server Crash

### ISSUE THREAD

**Issue by TsumiHokiro** [SleepyTrousers/EnderIO#4337]
When trying to start a server with EnderIO and Chromaticraft (along with their dependences) you get a "Exception in server tick loop: NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP". To note, when starting Chromaticraft alone the server does not get this error, and without the need of stating, EnderIO also does not have this problem.

#### Steps to reproduce:

1. Put both Chromaticraft (along with DragonAPI) and EnderIO on mods folder
2. Start a Forge Server
3. Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10-2.3.0.422_beta.jar
- EnderCore: 1.7.10-0.2.0.39_beta.jar
- Minecraft: 1.7.10
- Forge: 10.13.4.1614-1.7.10-universal.jar
- ChromatiCraft 1.7.10 V18b.jar
- DragonAPI 1.7.10 V18b.jar

https://pastebin.com/rSmKAJPh

**Comment by GhostShot3** [comment]
I play with the 2 mod and not crash, it can probably be something else.

**Comment by TsumiHokiro** [comment]
Hm, that's strange indeed. Would you mind sharing with me the version of Chroma, DragonAPI, EnderCore, EnderIO and the Forge dedicated server version, and if it's not original Forge, which other modded server you're using?

**Comment by HenryLoenwind** [comment]
This is caused by Chromaticraft sending a client-only message to EnderIO. Bug on their side.

**Comment by TsumiHokiro** [comment]
Thanks for the help. It wasn't pointed out here that the EnderIO wasn't up to date, nor was it pointed out here that the error was indeed due to EnderIO. Nonetheless, the issue was solved in a later update from EnderIO.
