### ISSUE TITLE
Status on 1.11.x and 1.12.x ??

### ISSUE THREAD

**Issue by TheEmeraldGuy** [SleepyTrousers/EnderIO#4338]
#### Issue Description:
The status on update of EnderIO has not been updated for a while now. I ask this because I really want to play with it. Thank you for reading.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft:
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by Fungie2134** [comment]
I do not know, jenkins builds are unusable thought.

**Comment by GalacticWolf541** [comment]
To get updated and more accurate information, please join the discord server here: https://discord.gg/sgYk3Jr

**Comment by PapiDimmi** [comment]
It’s at the top of the [mod page](https://minecraft.curseforge.com/projects/ender-io).
