### ISSUE TITLE
Suggestion: Add the possibility to disable TiC weapon use in Killer Joe

### ISSUE THREAD

**Issue by vlce-versa** [SleepyTrousers/EnderIO#4339]
Would it be possible to add a config option to disable the use of TiC weapons in Killer Joe, because one could use it to level the weapons with Tinker Tool Leveling and the weapon still does damage even when it's broken, so it's like an unbreakable weapon for the Killer Joe.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.193
- EnderCore:0.4.1.66
- Minecraft: 1.10.2
- Forge:2488

**Comment by HenryLoenwind** [comment]
Last time I tested this, broken TiC weapons did not do damage...
