### ISSUE TITLE
Farming Station and Natura Cotton Crops causes server crash

### ISSUE THREAD

**Issue by Tipsied** [SleepyTrousers/EnderIO#4342]
#### Issue Description: 
Server crashes when Farming Station harvests Natura Cotton seeds on SF3 1.10.2

#### What happens:
The server will crash when the Farming Station tries to harvest a Natura cotton seed. Upon logging back in, the Farming Station is turned into a chest. 

#### What you expected to happen:
Allow the farming station to harvest Natura cotton seeds with no problems.

#### Steps to reproduce:

1. Create a farm of Natura cotton seeds
2. Place a farming station with power
3. Input a diamond hoe

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.193
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2422

#### Your most recent log file where the issue was present: 

pastebin link [here](https://gist.github.com/Aiidoneus/1e2a67fa77caf0292c6a6958b83fb20e)

**Comment by mindforger** [comment]
there is sponge in this issue, try without sponge and report it to them if removeing sponge helps this issue probably
