### ISSUE TITLE
[1.10.2] [Question] Where is the energy capability of items?

### ISSUE THREAD

**Issue by bxz2311196368** [SleepyTrousers/EnderIO#4347]
#### Issue Description:
Want to insert energy to EnderIO's item cap bank ,tools ,armor and other hold energy item.
But can't find the energy capability for items.
I find this  [https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/power/ItemPowerCapabilityBackend.java](url)

where the capability exactly is.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66
- Minecraft: 1.10.2
- Forge: 2422

**Comment by HenryLoenwind** [comment]
Here: https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/energy/CapabilityEnergy.java

**Comment by bxz2311196368** [comment]
Thank you! Solved this.
