### ISSUE TITLE
[1.10.2] Crash at Reloading-Model Manager ~ ModelLoader: baking

### ISSUE THREAD

**Issue by Linde0404** [SleepyTrousers/EnderIO#4353]
#### Issue Description:
Minecraft/Forge crashes at:
Step 7/7 ~ Reloading-Model Manager ~ ModelLoader: baking

#### What happens:
Crash

#### What you expected to happen:
Play with EnderIO

#### Steps to reproduce:
Use the version of EnderIO and EnderCore seen below

____
#### Affected Versions 
- EnderIO: 1.10.2 - 3.1.193
- EnderCore: 1.10.2 - 0.4.1.66
- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2185

#### Your most recent log file where the issue was present: 

https://pastebin.com/5WAmBJQe
or
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/1430633/latest.log)
:

**Comment by Tahakk** [comment]
How much RAM you have allocated for game?

**Comment by Linde0404** [comment]
Default: 1G

Am 31.10.2017 13:27 schrieb "Tahakk" <notifications@github.com>:

**Comment by Linde0404** [comment]
Thanks, now it's working absolutely fine😊👍


​


Am 31.10.2017 14:04 schrieb "Tahakk" <notifications@github.com>:

Add more. If I understand it correctly, this ->
*1060:* java.lang.OutOfMemoryError: Java heap space

Means you ran out of RAM

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SleepyTrousers/EnderIO/issues/4353#issuecomment-340755603>,
or mute the thread
