### ISSUE TITLE
1.10.2

### ISSUE THREAD

**Issue by xablaurx** [SleepyTrousers/EnderIO#4354]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
MEU MODPACK TEM APENAS 4 MODS AINDA:
appliedenergistics2-rv4-stable-1
EnderIO-1.10.2-3.1.183
EnderCore-1.10.2-0.4.1.65-beta
jei_1.10.2-3.14.7.420
MAS,SEMPRE QUE TENTO ABRIR O LAUNCHER QUEBRA.
#### What you expected to happen:
NÃO SOU MUITO EXPERIENTE, POR ISSO, PRECISO SABER OQUE ESTÁ ACONTECENDO POR FAVOR, AJUDA.
#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
First off, I don't speak Portuguese, but google translate got me the gist. Second, you should try posting an actual issue, instead of just asking for help.

**Comment by xablaurx** [comment]
I was using the T-launcher with "auto-optifine". Sorry, I've tried a million times before posting to the forum. Please advise anyone else who has the same problem, you need to enter the optifine as a MOD to be loaded to work.
Thank you.
PS: - I'm also fluent in Google.Translate.



________________________________
De: tterrag <notifications@github.com>
Enviado: sábado, 4 de novembro de 2017 02:27
Para: SleepyTrousers/EnderIO
Cc: xablaurx; Author
Assunto: Re: [SleepyTrousers/EnderIO] 1.10.2 (#4354)


First off, I don't speak Portuguese, but google translate got me the gist. Second, you should try posting an actual issue, instead of just asking for help.

**Comment by HenryLoenwind** [comment]
T-Launcher? Sorry, no support for piracy tools.
