### ISSUE TITLE
Network Conduit disconnecting OC components (and then reconnecting them a moment later)

### ISSUE THREAD

**Issue by Darinth** [SleepyTrousers/EnderIO#4357]
#### Issue Description:
I noticed playing FTB beyond that my OC programs were occasionally failing with component missing errors. After playing around with and checking events I noticed that indeed at times, in particular when I left the area (despite it being chunk loaded) anything connected via Ender IO OC cable was getting disconnected and then reconnected.

I setup a minimal test pack (ChickenChunks-1.10.2-2.2.0.52-universal for chunk loading, journeymap-1.10.2-5.5.2 for teleporting away, EnderIO-1.10.2-3.1.183, EnderCore-1.10.2-0.4.1.66-beta, OpenComputers-MC1.10.2-1.6.2.7) and while I wasn't able to replicate the exact issue, I was able to replicate some similar effects that I hope are related.

#### What happens:
Anytime new network conduit is removed from a conduit bundle, all devices connected to that set of conduit are disconnected, even if they're completely unrelated to the change that was done. Adding a piece of network conduit just sticking off randomly and then either breaking it or wrenching it off disconnects all devices and reconnects them. I suspect that something is causing a similar event in my much more complex/convoluted base setup.

#### What you expected to happen:
Unless a removed piece of network conduit severs the connection to the computer, I expect all components to remain connected.

#### Steps to reproduce:

1. Build an OC computer and connect a series of transposers to it, connected by network conduit.
2. Install OpenOS, etc... going through usual setup for a computer.
3. Utilize the event debugger program located at: https://pastebin.com/tdHuYGDe
4. Add a piece of network conduit to it, then break said piece of conduit.
5. Check monitor to see disconnect/reconnect events.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.183.jar
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

#### Your most recent log file where the issue was present: 

No log files. Though I'll provide a picture of my test setup.

![2017-11-10_12 06 13](https://user-images.githubusercontent.com/4502486/32669751-99f6f9ac-c60f-11e7-97e0-7174498b2546.png)
In this setup, the leftmost 3 transposers are all disconnected any time network conduit is removed. The right 2 transposers are correctly only disconnected (and thus not reconnected) when the cable going to them is actually severed.

**Comment by HenryLoenwind** [comment]
Please re-test in 1.12

**Comment by Darinth** [comment]
Just wanted to let you know that I have seen this and do plan on testing, it'll likely be a while though.

**Comment by HenryLoenwind** [comment]
One thing I can say about this: Every time you change the conduit layout, the conduit network is rebuilt. That's because you potentially are splitting the network into 6 parts, or merging 6 networks into one. In theory this should not effect OC, as this all is done in one operation. Should...
