### ISSUE TITLE
massive tps lagg with ender io bundles

### ISSUE THREAD

**Issue by unstablecraft** [SleepyTrousers/EnderIO#4360]
#### What you expected to happen: an option to disable this

mc version: 1.10.2
enderio version:  EnderIO-1.10.2-3.1.193.jar
forge: 2477
modpack: Age Of engineering

dont see this as an bug but as enhancement

**Comment by Carnaxus** [comment]
So...basically you want an option to disable lag put into the config.

How many conduits do you have in the single bundle, and how much data is passing through them on average?

**Comment by ktole1999** [comment]
if you dont want bundle lag then dont bundle them. maybe its your computer or base build.

**Comment by unstablecraft** [comment]
your reaction adds nothing to this  we run on an 7700k on 4 to 5 Ghz and nvme drives so it isnt the server  :D

**Comment by ktole1999** [comment]
ok so now you have ruled out hardware. what about the way conduits are being used. Have you tried this with only eio installed? are you running sponge or another server side environment that could impact the blocks? saying my reaction adds nothing is incorrect.

**Comment by HenryLoenwind** [comment]
oh, stop it, y'all.

Your server specs are completely unrelated to this. it's like complaining that the strongest man alive fails to lift a bag of feathers---which would be completely expected if that bag contained 40tons of feathers.

Then, there is no magic setting "diasbleAllLag". Or one "disableAllBugs". Even expecting something like that to exist is...inhumanly naive.

Third. "TileConduitBundle" is the block for conduits. A single type of block that is used for all conduits that are placed in the world. No matter how many conduits, or which types you place down, you get one TileConduitBundle per block. If we had different blocks for different conduit combinations, we'd need 8191 different blocks.

Fourth. "It doesn't work, make it work" is the worst way to write a ticket. It is completely useless to me and anyone else. The only answer I have for it is "Do it that other way, then it will work."

Fifth. If you have any kind of performance problems, use a profiler. Ender IO feeds very detailed data to Minecraft's built-in profiler.

**Comment by roboderpy** [comment]
ok
![javaw_2018-04-22_10-09-33](https://user-images.githubusercontent.com/6339511/39090964-4672d2f2-4615-11e8-986d-0a479ed16999.png)
