### ISSUE TITLE
SkyFactory 2.5.6 crash [1.7.10]

### ISSUE THREAD

**Issue by NathanZook** [SleepyTrousers/EnderIO#4361]
#### Issue Description:
I have a crash on SF 2.5.6.  The money quote appears to be here:
Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.

EnderIO: Found the following problem(s) with your installation:
* An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
Ender IO was build against API version rv2 and may or may not work with a newer version.
This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

#### A fresh build?
I don't know if it is reasonable to try to get a build for 1.7.10 against rv3 or not.  I've not a java guy, but I know my way around a Linux prompt.  If you would like to give me pointers for a build, I could play with that.

#### What happens:
"Random" crash

#### Steps to reproduce:

1. Install FTB 2.5.6, with Thermal expansion moved to an available release
2. ???
3. crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 1.7.10-10.13.4.1558-1.7.10

#### Your most recent log file where the issue was present: 
https://gist.github.com/NathanZook/a38635db823d54a6c148942c0b3eac28

**Comment by HenryLoenwind** [comment]
This output has been updated in later versions to read:

> Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):

**Comment by mindforger** [comment]
>This output has been updated in later versions to read:

and still people are ignoring it :D

**Comment by NathanZook** [comment]
Thanks for the help.  Sorry for the noise.
