### ISSUE TITLE
Cryo-Stabilized Fluxduct

### ISSUE THREAD

**Issue by GhostShot3** [SleepyTrousers/EnderIO#4363]
The "Thermal Dynamics" mod has a "Cryo-Stabilized Fluxduct" power conductor that transmits infinite rf/tick ,if you make a capacitor of 25,000 RF or more and put it at its maximum output and connect this using "Cryo-StabilizedFluxduct" of "ThermalDynamics", it will not send all the 25,000 rf/tick what was to happen.

- EnderIO: EnderIO-1.7.10-2.2.8.381
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

**Comment by GhostShot3** [comment]
Why incomplete ?

**Comment by mindforger** [comment]
>Why incomplete ?

>(lastest)

>#### Affected Versions (Do **not** use "latest"):

**Comment by GhostShot3** [comment]
Ok

**Comment by GhostShot3** [comment]
why wontfix ?

**Comment by bookerthegeek** [comment]
@GhostShot3 because they will not fix things that are reported with incomplete information.

**Comment by HenryLoenwind** [comment]
I wouldn't go that far, bookerthegeek. This goes onto the wontfix list simply because it's for 1.7.10 and we're currently working on porting to 1.12...

**Comment by bookerthegeek** [comment]
Lol... Gotcha. Did not even see that.

**Comment by GhostShot3** [comment]
Where is incomplete ?

**Comment by mindforger** [comment]
![grafik](https://user-images.githubusercontent.com/2683555/33753794-774d9790-dbe9-11e7-92fe-b0ffcbe62450.png)

well he edited it but no one noticed :)

@GhostShot3 but still 1.7.10 is not maintained anymore

**Comment by GhostShot3** [comment]
Will this problem will not be fixed?

**Comment by bookerthegeek** [comment]
Not unless you can confirm this issue still happens in the version they are currently support

1.7.10 is [EoL](https://en.wikipedia.org/wiki/End-of-life_(product)) (End of Life)

**Comment by GhostShot3** [comment]
@mindforger remove incomplete

**Comment by mindforger** [comment]
@ghostshot3 i didnt add the tag, i only explained

**Comment by GhostShot3** [comment]
@mindforger if this poblem will not be resolved close

**Comment by bookerthegeek** [comment]
@GhostShot3 Just saying you are sounding demanding. If he wants to close it he will.

OR... He could be waiting for the next version to be released to test if this issue still exists. Either way you should practice how you sound. Just saying.

**Comment by mindforger** [comment]
@ghostshot3 this is not Applied Energistics i can't do shit here i am just commenting like you, so give me a break. You just rage against me because i was following the devs plans and closed a few of your issues WITH REASON .. Your behaviour is very arrogant

**Comment by GhostShot3** [comment]
I'm not angry, I just asked a question with all respect.

**Comment by GhostShot3** [comment]
I just said 2 things with all respect
1 - "if this poblem will not be resolved close"
2 - "remove incomplete"
I did not understand

**Comment by tterrag1098** [comment]
1.7.10 is no longer in active development, especially not for low-priority interaction bugs like this one. Sadly, we just don't have enough time to go around.

**Comment by GhostShot3** [comment]
Ok
