### ISSUE TITLE
Thermal Dynamics/Buildcraft Item Pipe Buffer Crash

### ISSUE THREAD

**Issue by ghost** [SleepyTrousers/EnderIO#4366]
#### Issue Description:
Minecraft crashes after (or shortly after in some cases) an item goes through a itemduct from TD, when it's linked to a Buffer.

#### What happens:
Minecraft crashes after (or shortly after in some cases) an item goes through a itemduct from TD, when it's linked to a Buffer. The save is also corrupted, and any attempts to load a world which this has occurred on crashes on load.

#### What you expected to happen:
To be able to link my BC and TD pipes and void my items. (Or crash, this has happened multiple times)

#### Steps to reproduce:

1. Create a chest. (This can be any chest, I was trying to use Gold Chests from IC, but I tested with vanilla)
2. Link it with TD itemducts(any itemduct) to a buffer, and out through a BC pipe.(I'm not sure if BC is the definite reason why it crashes, but it's crashed every time with BC pipes)
3. Activate the itemduct.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1566
- Buildcraft: 7.1.23
- Thermal Dynamics: 1.2.1-172

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/YT2JymkE

**Comment by HenryLoenwind** [comment]
All I see is that thermaldynamics want to create a crash reports and crashes while doing so.

**Comment by mindforger** [comment]
at least you can read that it is cause by an item transfer initiated by an servo through an itemduct while simulating the transfer to check if the routing is valid ... quite the readable code i have to say :)

**Comment by MatthiasMann** [comment]
Then report it to TD - there is no EnderIO in the stack trace.
