### ISSUE TITLE
Can not build EnderIO-Base 1.11

### ISSUE THREAD

**Issue by haza1608** [SleepyTrousers/EnderIO#4367]
#### Issue Description:
After downloading the enderio-base 1.11 github branch and trying to run "gradlew eclipse" you get "BUILD FAILED"

#### What happens:
Error:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'EnderIO-Base'.
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve net.sengir.forestry:forestry_1.11.2:5.3.3.95.
     Required by:
         com.enderio:EnderIO-Base:1.11.2-4.0.0
      > Could not resolve net.sengir.forestry:forestry_1.11.2:5.3.3.95.
         > Could not get resource 'http://maven.ic2.player.to/net/sengir/forestry/forestry_1.11.2/5.3.3.95/forestry_1.11.2-5.3.3.95.pom'.
            > Could not GET 'http://maven.ic2.player.to/net/sengir/forestry/forestry_1.11.2/5.3.3.95/forestry_1.11.2-5.3.3.95.pom'.
               > Connection to http://maven.ic2.player.to refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 35.27 secs

#### What you expected to happen:
Build succeeded?

#### Steps to reproduce:

1.Download EnderIO-Base 1.11
2.Run "gradlew eclipse" in enderio directory
3.Build failed
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.11
- EnderCore:1.11
- Minecraft: 1.11
- Forge:N/A

#### Your most recent log file where the issue was present: 

https://pastebin.com/4QVui0pZ

**Comment by tterrag1098** [comment]
Forestry maven is down, disable that dependency or wait for it to be online again.
