### ISSUE TITLE
[1.10.2] Massive Conduit Lag in Chunks that are unloaded or semi unloaded.

### ISSUE THREAD

**Issue by KaneHart** [SleepyTrousers/EnderIO#4373]
#### Issue Description:
Pfft, of course I'm using a modpack but then again I just copy/pasted in my own instance and called it Kane pack so now It's my Modpack!

#### What happens:
When someone leaves their chunk as in logoff or leave their chunk area and they unload the conduits start performing some really crazy strange lag every 30 seconds or so. Maybe some sort of reconnect maybe the chunks are still half loaded, etc. Sadly as we know some mods force chunks open still, etc.

#### What you expected to happen:
When chunks unload the conduits don't cause lag!

#### Steps to reproduce:

As far as we know bases with a bunch of conduits that complex tend to lag once the chunks unload. I can't really reproduce it outside that. 

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.193.jar
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta.jar
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2477-universal.jar

#### Your most recent log file where the issue was present: 
https://pastebin.com/a5mSwUBj

**Comment by HenryLoenwind** [comment]
Enable the *vanilla* profiler. Ender IO reports comprehensive profiling data on the conduits.

**Comment by KaneHart** [comment]
Thanks, I will attempt to find out how to do that and provide results asap.

**Comment by KaneHart** [comment]
Interesting so it's for sure something buggy I think conduits might be still playing a role with the error but at the same time it might be related to world save. Does this happen every 30 seconds? 

I picked 3 bases using Conduits and teleported to all 3 and went to spawn. 100% vanilla forge no Sponge here during testing.

**In console it would spam this every 30 seconds during the debug mode:**
https://pastebin.com/nigdivb1

**And the results from the debug:**
https://pastebin.com/Hd63CDxw

I also tested again if I keep those chunks loaded it does not seem to lag.

**Comment by KaneHart** [comment]
I threw sponge on as well as it has very nice timings system. I think might actually piggy back on vanilla's as well but I could be wrong. Either way what is the harm in my profile results. If this could fix something for the future then lets do it. 

https://timings.aikar.co/?id=25751b8cb9024619b6ddd776181b2bf2

**Comment by HenryLoenwind** [comment]
um, unfortunately "root.levels.world.tick.entities.blockEntities" doesn't get shown in its full glory in the profiler report (I'll investigate why). You can see that there is more detailed data in there from the log file. However, the logfile warnings cut out too high-level, too.

And the aikar timings report weird data again. Basically the opposite of the vanilla report...
