### ISSUE TITLE
EnderIO Dont Opened 

### ISSUE THREAD

**Issue by DarkTimes3000** [SleepyTrousers/EnderIO#4378]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What you expected to happen:
I want play Minecraft with EnderIO

#### Steps to reproduce:

1. I dont Know
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66 beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
Please provide some amount of useful information if you want help.

**Comment by DarkTimes3000** [comment]
Hey I upload the mod but minecraft dont run Why

**Comment by grydian** [comment]
Without a crash log they cannot help you.  Try using the curse launcher it makes installing mods simple and easy.

**Comment by pinkphoenix1990** [comment]
I'm not sure, Dark, but it seems like there is a communication barrier here. What exactly is happening? Will Minecraft not launch at all for you? Does it give you an error when Minecraft crashes? Are you able to get in, but you do not see EnderIO loaded? 

As much of a hassle as it may seem, the bug report/suggestion templates need to be filled out as much as possible. It really helps the developer, and other awesome people, to look into the issue with you. 

So, if you could, sort of walk us through what you have done up to this point. Did you download the EnderIO jar file? Where did you download it? What version of Minecraft do you have installed? Do you have Forge installed? If so, what version? Did you put the EnderIO jar file in the Mods folder? Are you able to launch Minecraft, or does it immediately crash? If it crashes, does it give you an error? If it does crash (i.e. you click to play, it appears to start... and then returns to the launcher with something like 'an unexpected error occurred.), you should use a search engine to find out how to locate your Minecraft log file, upload it to a site (like pastebin, etc.) and give us a link to it here!

**Comment by DarkTimes3000** [comment]
-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 217952256 bytes (207 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_E3 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	NotEnoughItems{2.1.3.207} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.207-universal.jar) 
	UCHI	OpenComputers|Core{1.7.0.124} [OpenComputers (Core)] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHI	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHI	chiselsandbits{12.16} [Chisels & Bits] (chiselsandbits-12.16.jar) 
	UCHI	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHI	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCHI	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHI	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHI	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHE	EnderIO{1.10.2-3.1.180} [Ender IO] (EnderIO-1.10.2-3.1.180.jar) 
	UCHI	exnihiloadscensio{0.1.5} [Ex Nihilo Adscensio] (exnihiloadscensio-1.10.2-0.1.17.jar) 
	UCHI	excompressum{2.0.87} [Ex Compressum] (ExCompressum_1.10.2-2.0.87.jar) 
	UCHI	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCHI	ichunutil{6.5.0} [iChunUtil] (iChunUtil-1.10.2-6.5.0.jar) 
	UCHI	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHI	lootbags{2.3.9} [Loot Bags] (LootBags-1.10.2-2.3.9.jar) 
	UCHI	mob_grinding_utils{0.1.8.22} [mob_grinding_utils] (MobGrindingUtils-0.1.8.22.jar) 
	UCHI	nuclearcraft{2.5a} [NuclearCraft] (NuclearCraft-2.5a--1.10.2.jar) 
	UCHI	OpenComputers{1.7.0.124} [OpenComputers] (OpenComputers-MC1.10.2-1.7.0.124.jar) 
	UCHI	omlib{3.0.0-129} [OMLib] (omlib-1.10.2-3.0.0-129.jar) 
	UCHI	ompd{3.0.0-22} [Open Modular Passive Defense] (ompd-1.10.2-3.0.0-22.jar) 
	UCHI	openmodularturrets{3.0.0-223} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-223.jar) 
	UCHI	wailaplugins{MC1.10.2-0.3.0-26} [WAILA Plugins] (WAILAPlugins-MC1.10.2-0.3.0-26.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.207-universal.jar)
  codechicken.nei.asm.NEITransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.7.0.124.jar)
  li.cil.oc.common.asm.ClassTransformer
	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)
=======================================================================
== ENDER IO FATAL ERROR ==
=======================================================================
Cannot register recipes as configured. This means that either
your custom config file has an error or another mod does bad
things to vanilla items or the Ore Dictionary.
=======================================================================
== Bad file ==
recipe_materials_core.xml or recipe_materials_user.xml
=======================================================================
== Error Message ==
Rejecting crafting recipe without any items, only empty spaces in <grid>
=======================================================================

=======================================================================
Note: To start the game anyway, you can disable recipe loading in the
Ender IO config file. However, then all of Ender IO's crafting recipes
will be missing.
=======================================================================

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	OptiFine Version: OptiFine_1.10.2_HD_U_E3
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.8545 Release
	OpenGlRenderer: Radeon X1650 Series (Microsoft Corporation - WDDM)    
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2
-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 217952256 bytes (207 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_E3 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	NotEnoughItems{2.1.3.207} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.207-universal.jar) 
	UCHI	OpenComputers|Core{1.7.0.124} [OpenComputers (Core)] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHI	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHI	chiselsandbits{12.16} [Chisels & Bits] (chiselsandbits-12.16.jar) 
	UCHI	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHI	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCHI	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHI	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHI	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHE	EnderIO{1.10.2-3.1.180} [Ender IO] (EnderIO-1.10.2-3.1.180.jar) 
	UCHI	exnihiloadscensio{0.1.5} [Ex Nihilo Adscensio] (exnihiloadscensio-1.10.2-0.1.17.jar) 
	UCHI	excompressum{2.0.87} [Ex Compressum] (ExCompressum_1.10.2-2.0.87.jar) 
	UCHI	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCHI	ichunutil{6.5.0} [iChunUtil] (iChunUtil-1.10.2-6.5.0.jar) 
	UCHI	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHI	lootbags{2.3.9} [Loot Bags] (LootBags-1.10.2-2.3.9.jar) 
	UCHI	mob_grinding_utils{0.1.8.22} [mob_grinding_utils] (MobGrindingUtils-0.1.8.22.jar) 
	UCHI	nuclearcraft{2.5a} [NuclearCraft] (NuclearCraft-2.5a--1.10.2.jar) 
	UCHI	OpenComputers{1.7.0.124} [OpenComputers] (OpenComputers-MC1.10.2-1.7.0.124.jar) 
	UCHI	omlib{3.0.0-129} [OMLib] (omlib-1.10.2-3.0.0-129.jar) 
	UCHI	ompd{3.0.0-22} [Open Modular Passive Defense] (ompd-1.10.2-3.0.0-22.jar) 
	UCHI	openmodularturrets{3.0.0-223} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-223.jar) 
	UCHI	wailaplugins{MC1.10.2-0.3.0-26} [WAILA Plugins] (WAILAPlugins-MC1.10.2-0.3.0-26.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.207-universal.jar)
  codechicken.nei.asm.NEITransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.7.0.124.jar)
  li.cil.oc.common.asm.ClassTransformer
	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/FEEL/AppData/Roaming/.minecraft/mods/CoFHCore-1.10.2-4.1.12.17-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)
=======================================================================
== ENDER IO FATAL ERROR ==
=======================================================================
Cannot register recipes as configured. This means that either
your custom config file has an error or another mod does bad
things to vanilla items or the Ore Dictionary.
=======================================================================
== Bad file ==
recipe_materials_core.xml or recipe_materials_user.xml
=======================================================================
== Error Message ==
Rejecting crafting recipe without any items, only empty spaces in <grid>
=======================================================================

=======================================================================
Note: To start the game anyway, you can disable recipe loading in the
Ender IO config file. However, then all of Ender IO's crafting recipes
will be missing.
=======================================================================

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	OptiFine Version: OptiFine_1.10.2_HD_U_E3
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.8545 Release
	OpenGlRenderer: Radeon X1650 Series (Microsoft Corporation - WDDM)    
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by DarkTimes3000** [comment]
Thats crush log

**Comment by mindforger** [comment]
for our eyes sake, please edit this monster of a post and put the crashlog into pastebin and link it instead of spamming this massive textwall

also the crashlog tells you your issue 
>== Bad file ==
recipe_materials_core.xml or recipe_materials_user.xml
== Error Message ==
Rejecting crafting recipe without any items, only empty spaces in

**Comment by DarkTimes3000** [comment]
For God's sake, please tell me step by step what I should do

**Comment by mindforger** [comment]
why this swearing, i mean it should be obvious to yourself that a textwall with letter size 100 is not readable at all ... why do i have to tell you to make it readable?

i also wrote everything you should do!

1. find your minecraft folder where you installed the modpack
2. go into it and open the configs folder
3. find the recipe_materials_core.xml and recipe_materials_user.xml and rename both to something that you like to keep the broken ones for later repair (also please attach them to you anwser so we could have a look at it, **attach as file not as text!**)
4. start your minecraft, it should regenerate the files and launch, **but if this is a modpack your recepise may be inconsistent** and you have to contact the mod**pack** author to fix it!

**Comment by DarkTimes3000** [comment]
Thats config

**Comment by DarkTimes3000** [comment]
[Config of EnderIO.zip](https://github.com/SleepyTrousers/EnderIO/files/1564844/Config.of.EnderIO.zip)
Thats Config of EnderIO

**Comment by DarkTimes3000** [comment]
You can hate from Turkish but I am From turkish And I cant Understand you sometimes Im so sorry but I cant do anythink

**Comment by mindforger** [comment]
mhh nothing that looks odd from a first glance

now i am lost as i have no idea how exactly the used items are determined
my guess would be that one of the items on this recipes is not registered anymore becasue of a mod update or something similar

try renaming all the recipes files that end in .xml and let them regenerate by launching your minecraft, if it still crashes there have to be something wrong with items registered from other mods

**Comment by HenryLoenwind** [comment]
Ok, Turkish was the key to this. Minecraft Forge is broken in the Turkish locale (because it relies on i<->I ). Set the game to any other language. Sorry, this is not something we can fix in Ender IO.

**Comment by HenryLoenwind** [comment]
Another solution may be this coremod I just made: http://loenwind.info/EnderFixer-1.10.2-0.1.0.1.jar

Please report if it helps, thank you.

**Comment by DarkTimes3000** [comment]
I love you henry It's workıng man Thank you so much

**Comment by HenryLoenwind** [comment]
Great to hear. I uploaded it to curseforge so other people may benefit from it: https://minecraft.curseforge.com/projects/turkish-locale-fixer

**Comment by pau101** [comment]
Use the established mod to work around this issue: https://minecraft.curseforge.com/projects/localefixer

**Comment by pau101** [comment]
Use the established mod to fix this issue: https://minecraft.curseforge.com/projects/localefixer
