### ISSUE TITLE
I don't even know...

### ISSUE THREAD

**Issue by RayyaanAKhtar5t4r** [SleepyTrousers/EnderIO#4382]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: minecraft:beetroot_seeds is not a vaild string. Strings should be either an oredict name, or in the format objectname;damage (damage is optional)

#### What you expected to happen:
The game would just load up fine.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.8.9-3.0.0.26_alpha.jar
- EnderCore: EnderCore-1.8.9-0.3.0.14-beta.jar
- Minecraft: 1.8.9
- Forge:1.8.9-forge1.8.9-11.15.1.2318-1.8.9

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Why are you using a 1.9/1.10.2 configfile with 1.8.9?

**Comment by HenryLoenwind** [comment]
PS: http://lmgtfy.com/?q=minecraft%3Abeetroot_seeds+is+not+a+vaild+string
