### ISSUE TITLE
Game won't start. API version rv2 Ender IO

### ISSUE THREAD

**Issue by FredricoFiasko** [SleepyTrousers/EnderIO#4388]
The game won't start. Error: 
EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (@aeversion@ from DragonAPI 1.7.10 V19c.jar).
                    Ender IO was build against API version rv2 and may not work with newer version.

- EnderIO: 1.7.10-2.3.0.429_beta
- EnderCore: 1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1614-1.7.10-universal

https://pastebin.com/F0XSYsVL

**Comment by FredricoFiasko** [comment]
Please help!!!

**Comment by Tahakk** [comment]
If you would wonder why it got closed my guess would be that 1.7 is not supported, or you didn't post whole crash log :)

**Comment by mindforger** [comment]
well it also is only a warning, not the actual crash
