### ISSUE TITLE
Combustion Generator won't provide power to adjacent machines

### ISSUE THREAD

**Issue by MatanShahar** [SleepyTrousers/EnderIO#4396]
#### Issue Description:
The Combustion Generator won't provide power to adjacent machines placed after the generator.

#### What happens:
When you place a new machine adjacent to a Combustion generator the generator will not provide any power.

#### What you expected to happen:
The Combustion Generator should detect the newly placed block and provide power to it.

#### Steps to reproduce:

1. Place a Combustion Generator.
2. Place any machine adjacent to it.
3. The machine will not receive power.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: next (1.11)
- EnderCore: next (1.11)
- Minecraft: 1.11

**Comment by HenryLoenwind** [comment]
thank you
