### ISSUE TITLE
New builds testing

### ISSUE THREAD

**Issue by Manuepolis23** [SleepyTrousers/EnderIO#4412]
Is there a way to test the build for 1.11.2?
I try using the build from jenkins and I get this : https://pastebin.com/Rhb4naF3

**Comment by HenryLoenwind** [comment]
Try this: http://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Combined/ --- the nightly is meant for something else.

Also, hey, didn't you notice that I'm working on that just now? tsk...

**Comment by Manuepolis23** [comment]
I think is the same error
https://pastebin.com/F38bJMNN

**Comment by HenryLoenwind** [comment]
Yes, the new build script doesn't manage to create correct jars yet. We might have a new build in 6-8 hours, as we have to wait for the one who made it to fix some details.

**Comment by Manuepolis23** [comment]
thanks a lot
