### ISSUE TITLE
[1.10.2] Ender-IO Crash 

### ISSUE THREAD

**Issue by BuyWhy** [SleepyTrousers/EnderIO#4416]
İ try to make modpack for myself but ender IO crashed and I tried only with the ender IO and still gives the same crash.

#### Affected Versions:

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2488

Pastebin : https://pastebin.com/x0K6ZT61

**Comment by HenryLoenwind** [comment]
Are you on a Turkish locale?

**Comment by BuyWhy** [comment]
Yes.

**Comment by HenryLoenwind** [comment]
then: https://minecraft.curseforge.com/projects/turkish-locale-fixer

**Comment by BuyWhy** [comment]
Thanks, fixed ;)
