### ISSUE TITLE
Server Crashed, but I have no idea why.

### ISSUE THREAD

**Issue by voxasor** [SleepyTrousers/EnderIO#4429]
#### What happens:
I've got a server on Nitrado, and it used to work perfectly.
But for some reason since yesterday it just stopped working.
The server starts and at the end it just stops again with an error.

I've attached the server crash report here, does anybody know/ see what seems to be the problem?

[Server Crash Report.txt](https://github.com/SleepyTrousers/EnderIO/files/1631344/Server.Crash.Report.txt)

Thanks!

**Comment by mindforger** [comment]
just a hint for future issues

the part before/above
>A detailed walkthrough of the error, its code path and all known details is as follows:

contains a complicated looking structure that contains all invloved componentes and mods in this crash

in your case it starts with
>appeng.api.features.IInscriberRegistry.getRecipes()Ljava/util/List;

hinting to applied energistigcs (appeng) but the lower you get in this trace you will see 

>at net.bdew.ae2stuff.machines.inscriber.TileInscriber.findFinalRecipe(TileInscriber.scala:128)

a lot "ae2stuff" which is an addon mod for applied energistics

you can safely ignore from bottom up any calls to "net.minecraft" stuff, but the first entry that hints on a mod is often the root for the crash but it can also be somewhere upwars from that

in this case i would blame ae2stuff and to be more specific something about something they do with recipes ... and a wild guess would be soemthign about that change that forge did a while ago to recipe handling, try updating ae2stuff and/or ae2

**Comment by HenryLoenwind** [comment]
You are using a ae2stuff version for AE2 rv2, but have AE2 rv3 installed. Use The ae2stuff for AE2 rv3.

And please explain to me why you are asking *us* fro help?
