### ISSUE TITLE
[1.11.2] Crash With Forestry

### ISSUE THREAD

**Issue by EmosewaGamer** [SleepyTrousers/EnderIO#4431]
#### What happens:
 The 1.11.2 version of Ender IO, when together with Forestry crashes the game when it's loading

#### Steps to reproduce:

1. Put Ender IO and Forestry in the same 1.11.2 instance
2. Load the game

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 4.0.65-NIGHTLY-72cb1c1
- EnderCore: 0.5.16
- Minecraft: 1.11.2
- Forge: 13.20.1.2588

#### Crash log: 
https://pastebin.com/9dahxXwc

**Comment by HenryLoenwind** [comment]
1. Please don't create issues for the nightly build, post you logs on the Discord
2. Mod integration for 1.11 is not up-to-date, this is on hold for 1.12 (there won't be a public 1.11 release)
3. You're using a beta version of Forestry instead of the release
