### ISSUE TITLE
[1.10.2] Transfer via Universal Cable and Fluxducts

### ISSUE THREAD

**Issue by Jason505** [SleepyTrousers/EnderIO#4433]
#### Issue Description:
When are two Capacitor Cells connected with Universal Cable from Mekanism, or Fluxduct from Thermal Expansion, it's transfering only half of possible"voltage". E.g. when I have two Capacitor Cells with maximal I/O 2 000 RF/t, these conductors are only transfering 1 000 RF/t.

#### What happens:

Described above.

#### What you expected to happen:

There should be flow 2 000 RF/t.

#### Steps to reproduce:

1. Connect two Capacitor Cells via mentioned cables.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66 Beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

#### Your most recent log file where the issue was present: 

No record of an issue in the log.

**Comment by HenryLoenwind** [comment]
Probably a bug in the cables. Have you checked that they are not sending half the energy back to the capbank it came from?

**Comment by Jason505** [comment]
Tested and it seems like it's really sending half of the energy back. If the I/O are defined, the problem is solved.
Strange, that this are doing only these types of cable. EnderIO cables, even an GalactiCraft Aluminium Wires are fine.
Anyway, thanks for help! Really appreciate it.

**Comment by HenryLoenwind** [comment]
As I said, buggy cables. People just don't care if their cables work with anything else but their own mod's machines. Both mods probably only have batteries that cannot send and receive on the same side.
