### ISSUE TITLE
Farming station GUI,  swap south with north

### ISSUE THREAD

**Issue by oliverjanik** [SleepyTrousers/EnderIO#4436]
Farming station GUI is disorenting.

It's arranged like this
```
SW SE
NW NE
```

This is very confusing because:
1) when looking north E and W are correct by N and S are swapped
2) when looking south,  E and W are swapped

Correct arrangement should be:
```
NW NE
SW SE
```

**Comment by HenryLoenwind** [comment]
works as designed

**Comment by oliverjanik** [comment]
What now? Care to elaborate?
