### ISSUE TITLE
Electric Diamond duplication via Conductor, Item Conduits and AE2 interface.

### ISSUE THREAD

**Issue by reifnotreef** [SleepyTrousers/EnderIO#4438]
Playing up to date version of Age Of Engineering
* Forge Version: forge:1.10.2-12.18.3.2422
 * Calculator Version: Calculator-1.10.2-3.2.5
 * SonarCore Version: SonarCore-1.10.2-3.2.9
 * EnderIO Version: EnderIO-1.10.2-3.1.193
 * AE2 Version: appliedenergistics2-rv4-stable-1
 * Multiplayer or Singleplayer: Single player survival, hosted via Open to Lan option.
 * Crash Report Link: N/A, No Crash
 * Affected Features: 
 * Description: 
I am trying to automate creating electric diamonds in a conduster mast. I have item conduits putting in fire diamonds and pulling out the electric diamonds.

I am using an AE2 interface with a chest on top of it, with conduits from the chest to the condutor. And another conduit from the conductor to the AE2 interface.

When I call to create an electric diamond it gets made, and then sits in the conductor mast.
W/e I thought, let me check my conduit settings... they're all good. I check in my AE2 storage, and my electric diamond count is skyrocketing.

It seems like the item conduit is telling the interface it is pulling the electric diamond out, but it really isn't. So AE2 is getting more electric diamonds, when I'm not actually making any. I now have about 2000 electric diamonds, and I've only requested to make 1.

Not sure if this is an EnderIO, Calculator or AE2 bug. Will try to report to all 3.

**Comment by tterrag1098** [comment]
I'm going to guess this is on Calculator...both ours and AE2s item transfer code is well tested and doesn't have issues with other bugs. Plus it wouldn't be the first dupe bug I've encountered in Calculator.

**Comment by hron84** [comment]
@reifnotreef Could you link the other issues (especially Calculator ones) here? It would be easier to track.

**Comment by mindforger** [comment]
this sounds oddly known, can you do a minimal setup of this and try once with extracells/ae2stuff/etc. addon mods and once without any AE2 addon mods?!

i can't exactly tell which one, but one was known to produce a dupe bug somehow under certain conditions

**Comment by hron84** [comment]
cc @SonarSonic

**Comment by HenryLoenwind** [comment]
Just to comment on a bit in the original report. This is how Ender IO's file transfer works:

1. Hey source block, what would you give me if I was to take this item out?
2. Hey target block, what would you take if I was to give you this item?
3. Ok, source block, now give me that item.
4. Ok, target block, here is what I just got, take it.
5. (optional) Um, source block, can I put back whatever the target block didn't take even so it promised it would?
6. (optional) Help I got items with no place to put them. World, can you drop them for me, pretty please?

**Comment by SonarSonic** [comment]
You can close this, these are outdated versions of Calculator and SonarCore
