### ISSUE TITLE
[Suggestion] EMC Conduits

### ISSUE THREAD

**Issue by Atticool** [SleepyTrousers/EnderIO#4440]
My idea is that you create a new type of conduit, allowing for transfer of EMC from Project E. The conduits would use speed upgrades to increase the speed of the EMC transfer. This would also be able to extract EMC directly from Energy Condensers and Anti-Matter Relays. 
I hope this idea gets seen.
Thank you

**Comment by BenjaminUrquhart** [comment]
You can just generate items (dirt, iron, whatever) in an energy condenser and use item conduits to transfer those items...

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
