### ISSUE TITLE
Help please Inventory system problem

### ISSUE THREAD

**Issue by Pinkrhino13** [SleepyTrousers/EnderIO#4443]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.1.183
- EnderCore:1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge:1.10.2-12.18.3.2316

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
Sorry, could you elaborate a bit? Where are you putting the items? What exactly happens?

**Comment by MatthiasMann** [comment]
Sounds like you put an awareness upgrade on the conduit on the back of the panel. Remove that upgrade and instead tell the conduit to extract items from the panel and let it insert these into your storage.
