### ISSUE TITLE
Ender IO item conduits crashes minecraft when placed

### ISSUE THREAD

**Issue by Mazak16661** [SleepyTrousers/EnderIO#4445]
I've a problem with Ender IO. When i place an item conduit, my minecraft crashes. Could someone help me? Here is the crash report:

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 03.02.18 11:19
Description: Unexpected error

java.lang.AbstractMethodError: crazypants.enderio.conduit.TileConduitBundle.collisionRayTrace(Lnet/minecraft/util/Vec3;Lnet/minecraft/util/Vec3;)Lnet/minecraft/util/MovingObjectPosition;
	at mods.immibis.core.multipart.MultipartSystem.hook_collisionRayTrace(MultipartSystem.java:396)
	at crazypants.enderio.conduit.BlockConduitBundle.IM__collisionRayTrace(BlockConduitBundle.java:1124)
	at crazypants.enderio.conduit.BlockConduitBundle.func_149731_a(BlockConduitBundle.java:925)
	at net.minecraft.world.World.func_147447_a(World.java:1221)
	at net.minecraft.world.World.func_72901_a(World.java:1029)
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:92)
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:55)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:70)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_587_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.immibis.core.multipart.MultipartSystem.hook_collisionRayTrace(MultipartSystem.java:396)
	at crazypants.enderio.conduit.BlockConduitBundle.IM__collisionRayTrace(BlockConduitBundle.java:1124)
	at crazypants.enderio.conduit.BlockConduitBundle.func_149731_a(BlockConduitBundle.java:925)
	at net.minecraft.world.World.func_147447_a(World.java:1221)
	at net.minecraft.world.World.func_72901_a(World.java:1029)
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:92)
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:55)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:70)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_587_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Mazak16661'/1333, l='MpServer', x=-217,70, y=21,54, z=426,92]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-168,64,252), Chunk: (at 8,4,12 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2630654 game time, 2852694 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 70 total; [EntityClientPlayerMP['Mazak16661'/1333, l='MpServer', x=-217,70, y=21,54, z=426,92], EntitySkeleton['Szkielet'/262, l='MpServer', x=-197,50, y=67,00, z=346,50], EntityZombie['Zombie'/263, l='MpServer', x=-203,03, y=25,00, z=431,25], EntityZombie['Zombie'/264, l='MpServer', x=-205,44, y=25,00, z=432,44], EntitySpider['Pająk'/265, l='MpServer', x=-204,25, y=25,00, z=445,17], EntitySpider['Pająk'/9742, l='MpServer', x=-163,72, y=64,00, z=353,72], EntitySkeleton['Szkielet'/1294, l='MpServer', x=-186,53, y=50,00, z=502,88], EntitySkeleton['Szkielet'/1297, l='MpServer', x=-201,50, y=26,00, z=472,50], EntityCreeper['Creeper'/9745, l='MpServer', x=-229,50, y=18,00, z=493,50], EntitySkeleton['Szkielet'/1298, l='MpServer', x=-202,50, y=26,00, z=471,50], GoldCow['Golden Apple Cow'/1300, l='MpServer', x=-194,38, y=72,00, z=468,91], EntitySkeleton['Szkielet'/284, l='MpServer', x=-196,59, y=76,00, z=391,88], EntityZombie['Zombie'/1308, l='MpServer', x=-220,50, y=77,00, z=470,50], EntityZombie['Zombie'/285, l='MpServer', x=-188,50, y=82,00, z=392,50], EntityItem['item.tile.extremetorch'/157, l='MpServer', x=-264,53, y=56,13, z=383,31], EntityCreeper['Creeper'/1309, l='MpServer', x=-223,50, y=76,00, z=467,50], EntitySkeleton['Szkielet'/286, l='MpServer', x=-184,94, y=23,00, z=415,56], EntityItem['item.tile.extremetorch'/158, l='MpServer', x=-261,13, y=59,13, z=382,88], EntityBat['Nietoperz'/287, l='MpServer', x=-179,63, y=17,79, z=419,75], EntityItem['item.item.sulphur'/1311, l='MpServer', x=-217,88, y=64,13, z=456,78], Firefly['Firefly'/159, l='MpServer', x=-266,67, y=63,37, z=394,60], Firefly['Firefly'/160, l='MpServer', x=-268,43, y=64,68, z=403,46], EntityCreeper['Creeper'/9635, l='MpServer', x=-172,50, y=37,00, z=466,50], EntityCreeper['Creeper'/9636, l='MpServer', x=-171,50, y=37,00, z=468,50], EntityCreeper['Creeper'/1316, l='MpServer', x=-247,41, y=63,00, z=503,00], EntityItem['item.name.lootbags_lootbagUncommon'/1317, l='MpServer', x=-204,84, y=69,13, z=461,56], Molenoid['Molenoid'/1318, l='MpServer', x=-180,45, y=72,88, z=442,75], Firefly['Firefly'/1319, l='MpServer', x=-231,79, y=65,08, z=459,66], EntityItem['item.item.tconstruct.strangefood.edibleslime'/2215, l='MpServer', x=-208,91, y=33,13, z=441,75], EntityItem['item.name.lootbags_lootbagUncommon'/2216, l='MpServer', x=-209,69, y=33,13, z=441,78], EntityXPOrb['Kula doświadczenia'/299, l='MpServer', x=-166,44, y=71,25, z=431,16], Firefly['Firefly'/9773, l='MpServer', x=-260,43, y=63,16, z=423,40], EntityZombie['Zombie'/302, l='MpServer', x=-155,44, y=66,00, z=370,00], GoldCow['Golden Apple Cow'/303, l='MpServer', x=-154,44, y=64,00, z=391,72], EntitySkeleton['Szkielet'/304, l='MpServer', x=-148,78, y=70,00, z=411,84], EntityCreeper['Creeper'/307, l='MpServer', x=-148,50, y=71,00, z=437,50], RockBase['Rock'/191, l='MpServer', x=-248,88, y=76,00, z=399,19], EntitySquid['Kałamarnica'/9663, l='MpServer', x=-245,56, y=61,06, z=421,75], EntityCreeper['Creeper'/9919, l='MpServer', x=-207,78, y=33,00, z=450,13], RockBase['Rock'/192, l='MpServer', x=-247,66, y=76,00, z=393,44], EntitySquid['Kałamarnica'/9664, l='MpServer', x=-252,66, y=61,97, z=423,84], EntityZombie['Zombie'/9792, l='MpServer', x=-191,56, y=72,00, z=493,06], RockBase['Rock'/193, l='MpServer', x=-245,19, y=76,00, z=396,63], EntitySquid['Kałamarnica'/9665, l='MpServer', x=-243,69, y=61,38, z=429,50], EntitySquid['Kałamarnica'/9666, l='MpServer', x=-240,53, y=62,31, z=429,50], RockBase['Rock'/195, l='MpServer', x=-245,63, y=76,00, z=394,41], EntitySquid['Kałamarnica'/9667, l='MpServer', x=-247,44, y=62,00, z=418,50], RockBase['Rock'/197, l='MpServer', x=-243,13, y=90,00, z=394,97], EntityWitch['Wiedźma'/9797, l='MpServer', x=-215,50, y=20,00, z=359,50], EntitySkeleton['Szkielet'/9798, l='MpServer', x=-220,50, y=20,00, z=357,50], EntitySkeleton['Szkielet'/9799, l='MpServer', x=-219,50, y=20,00, z=361,50], EntitySkeleton['Szkielet'/9800, l='MpServer', x=-215,59, y=20,00, z=352,94], EntitySpider['Pająk'/9673, l='MpServer', x=-163,25, y=69,00, z=420,72], EntitySkeleton['Szkielet'/9801, l='MpServer', x=-217,72, y=20,00, z=356,84], EntitySkeleton['Szkielet'/9678, l='MpServer', x=-199,50, y=72,00, z=419,50], EntityCreeper['Creeper'/9935, l='MpServer', x=-259,50, y=72,00, z=454,50], EntitySkeleton['Szkielet'/9937, l='MpServer', x=-207,50, y=89,00, z=411,50], EntityHorse['Koń'/212, l='MpServer', x=-236,28, y=76,00, z=351,72], EntityHorse['Koń'/214, l='MpServer', x=-234,72, y=76,00, z=353,28], RockBase['Rock'/215, l='MpServer', x=-225,13, y=63,00, z=416,88], RockBase['Rock'/216, l='MpServer', x=-231,13, y=69,00, z=426,88], RockBase['Rock'/217, l='MpServer', x=-228,13, y=73,00, z=427,88], RockBase['Rock'/218, l='MpServer', x=-233,13, y=68,00, z=429,88], RockBase['Rock'/219, l='MpServer', x=-235,13, y=66,00, z=430,88], RockBase['Rock'/220, l='MpServer', x=-234,13, y=66,00, z=429,88], RockBase['Rock'/221, l='MpServer', x=-228,13, y=81,00, z=431,88], EntitySkeleton['Szkielet'/9693, l='MpServer', x=-204,09, y=73,00, z=493,50], EntitySkeleton['Szkielet'/9697, l='MpServer', x=-226,50, y=78,00, z=383,50], EntityCreeper['Creeper'/250, l='MpServer', x=-213,00, y=20,00, z=358,50], EntityHuman['Malvina the Guard'/251, l='MpServer', x=-218,34, y=20,00, z=391,00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:30)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 818284512 bytes (780 MB) / 1643118592 bytes (1567 MB) up to 1724383232 bytes (1644 MB)
	JVM Flags: 4 total; -Xmx1850M -Xms800M -XX:PermSize=256M -XX:MaxPermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 66 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ImmibisMicroblocks{59.0.0} [Immibis's Microblocks] (Immibiss-Microblocks-Mod-1.7.10.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) 
	UCHIJAAAA	securitycraft{v1.8.2} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.2.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	thirstmod{1.8.8} [Thirst Mod] (_Thirst-Mod-1.7.10.jar) 
	UCHIJAAAA	adventurebackpack{0.1} [Adventure Backpack] (Adventure-Backpack-Mod-1.7.10.jar) 
	UCHIJAAAA	mod.ymt.air.HariboteAirCraft{172v3 hiten} [HariboteAirCraft] (AirCraft-Mod-1.7.10.zip) 
	UCHIJAAAA	ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.23} [BuildCraft] (buildcraft-7.1.23.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.23} [BC Factory] (buildcraft-7.1.23.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.23} [BC Silicon] (buildcraft-7.1.23.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.23} [BC Robotics] (buildcraft-7.1.23.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.23} [BC Energy] (buildcraft-7.1.23.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.23} [BC Builders] (buildcraft-7.1.23.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenters-Blocks-Mod-1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-Mod-1.7.10-Recommended.jar) 
	UCHIJAAAA	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_mod-1.7.10d.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	props{1.10} [Decocraft] (DecoCraft-Mod-1.7.10.zip) 
	UCHIJAAAA	Forestry{4.2.14.62} [Forestry for Minecraft] (Forestry-Mod-1.7.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12 (1).jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	tc{4.3.1_008} [Traincraft] (Traincraft-Mod-1.7.10.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V16d.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	hbm{1.0.4} [HbM's Nuker Mod] (hbm1.0.5.jar) 
	UCHIJAAAA	ImmibisCore{59.1.4} [Immibis Core] (Immibis-Core-1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4} [JourneyMap] (journeymap-1.7.10-5.1.4-unlimited.jar) 
	UCHIJAAAA	lootbags{2.0.17} [Loot Bags] (LootBags-Mod-1.7.10.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJAAAA	moreplayermodels{1.7.10} [MorePlayerModels] (More-Player-Models-2-Mod-1.7.10.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UCHIJAAAA	ppapmod{1.3} [PPAP Mod] (PPAP Mod-1.7.10-1.3.jar) 
	UCHIJAAAA	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V16d.jar) 
	UCHIJAAAA	punt{1.7.10-10.13.0-14.0} [Punt] (Small-Boats-Mod-1.7.10.jar) 
	UCHIJAAAA	whitehall{1.7.10-10.13.0-14.0} [Whitehall] (Small-Boats-Mod-1.7.10.jar) 
	UCHIJAAAA	hoy{1.7.10-10.13.0-14.0} [Hoy] (Small-Boats-Mod-1.7.10.jar) 
	UCHIJAAAA	smallboats{1.7.10-10.13.0-14.0} [SmallBoats (base)] (Small-Boats-Mod-1.7.10.jar) 
	UCHIJAAAA	spawnercraft{1.7.10-2.2.1} [SpawnerCraft] (SpawnerCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (StorageDrawers-1.7.10-1.10.9.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAAAA	WLM{1.4.1} [The Wasteland Mod] (Wasteland mod-1.4.1.jar) 
	UCHIJAAAA	craftingmanager{0.7.4} [Crafting Manager] (zCraftingManager 0.7.5 mc1.7.10.zip) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3308' Renderer: 'Intel(R) HD Graphics 4000'
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	Mantle Environment: Environment healthy.
	ThermalExpansion: -[1.7.10]4.1.5-248
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	EnderIO: No known problems detected.
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3308, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Polski (Polska)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by SrGexj** [comment]
How did you solved it?
