### ISSUE TITLE
Facades don't work with connected texture blocks

### ISSUE THREAD

**Issue by 23Link89** [SleepyTrousers/EnderIO#4458]
#### Issue Description:
The connected textures between blocks and facades won't connect properly

#### What happens:
If I take a block with connected textures and place a painted facade version of it and the original block, they won't connect textures completely, the facade will try to connect, but the original block won't. Though facades painted with connected textures will connect with other facades. It's not just blocks from Chisel this also includes the EnderIO 'quite clear glass block'

#### What you expected to happen:
The facades should connect normally to the regular block

#### Steps to reproduce:

1. Place a block with connected textures
2. Paint a facade with that block and place it right next to the block from before

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.106
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

#### Your most recent log file where the issue was present: 

https://pastebin.com/h7aBsDf6

**Comment by HenryLoenwind** [comment]
You are 87(!) versions behind...

**Comment by 23Link89** [comment]
Sorry, you had them listed as betas so I didn't get a notification from the twitch client telling me to update
