### ISSUE TITLE
1.10.2 EnderIO conduits not accepting redstone signal from Computercraft

### ISSUE THREAD

**Issue by Skullywag** [SleepyTrousers/EnderIO#4461]
#### Issue Description:
Using a computercraft computer and placing a redstone conduit on the back of it, then placing a lamp on the end of the conduit does not allow redstone signal to pass through to the lamp from the computer.

#### What happens:
Nothing

#### What you expected to happen:
The redstone signal to light the lamp

#### Steps to reproduce:

1. Place computercraft computer
2. Place redstone conduits on back of computer
3. place lamp on the other end of the conduit
4. open computer (right click), type "lua" to enter lua promp
5. type redstone.setOutput("back", true)
6. see the lamp not light up
7. remove conduit and put lamp directly on back of computer
8. repeat steps 4 and 5
9. see lamp light up with conduit not in the mix.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.193
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2511

#### Your most recent log file where the issue was present: 

Nothing in logs while this happening.

**Comment by Skullywag** [comment]
Well turns out the signal wont go into the conduits directly but will go into a block and then you connect the conduit to that forcibly with the wrench and then it works....is that how its supposed to be?

**Comment by MatthiasMann** [comment]
Conduits "collect" redstone power from the block the connector is facing - not the conduit bundle itself.

**Comment by hron84** [comment]
@MatthiasMann The problem is redstone power usually affects the block itself but not necessarily the same manner as the conduit. I could imagine a "signal acceptor" upgrade that can be placed on the bundle facing-dependent and can provide RS power for the connectors in the bundle.
