### ISSUE TITLE
Issue with Inventory Sensors

### ISSUE THREAD

**Issue by Cryptoman100** [SleepyTrousers/EnderIO#4464]
#### Issue Description:
I am using Ender IO's Inventory System and I made auto smelting system that will continually make ingots until the chest are full. I don't want it overflowing my inventory system storage warehouses so I am using inventory sensors to limit the amount of items that flow through. Everything works great if I am there but once I leave the chunk load range the sensors are sending a redstone signal to the extract item conduit. This is overflowing my inventory system and I have deduced that it is the sensors because it doesn't do it without the sensor in a test setup.

#### What happens:
Inventory sensor is sending a redstone signal when the chunks aren't loaded and letting items pass

#### What you expected to happen:
Then Inventory sensor to keep the signal that it is suppose if the chunk is unloaded

#### Steps to reproduce:

1.Have a chest full of items and an Inventory panel connected to a separate warehouse
2.Connect ender item conduit to the chest and set it to extract with redstone signal connecting to the warehouse
3. Hook up a inventor system in front of the chest and and connect the senor to the chest with redstone conduit
4. Program the sensor to set a limit on the Item in inventory panel
5. Let it reach that limit. It stops the redstone signal and the items stop flowing, as intended.
6. leave the chunk load range then comeback. while gone items pumped into the warehouse over the limit.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.193
- EnderCore: 1.10.2-0.4.1.66
- Minecraft: 1.10.2
- Forge: 12.18.3.2477

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Your report makes no sense. If a chunk is not loaded, nothing happens there...the chunk sit on your harddrive which is not capable of running any code.

**Comment by Cryptoman100** [comment]
Well this issue only happens when I am far away from it. It never happens when I am near the chunk it is in.

**Comment by Cryptoman100** [comment]
I am pretty sure it has something to do with the Inventory Panel Remote.
