### ISSUE TITLE
Function Upgrade Item show all creative tabs

### ISSUE THREAD

**Issue by SteveKunG** [SleepyTrousers/EnderIO#4465]
#### Issue Description:
The `item_function_upgrade` show all creative tabs, This can be fixed by add `tab == EnderIOTab.tabEnderIO`

https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-conduits/src/main/java/crazypants/enderio/conduit/item/ItemFunctionUpgrade.java#L52

#### What happens:
![2018-03-03_19 25 52](https://user-images.githubusercontent.com/6128413/36934297-abdaa980-1f19-11e8-9d8e-6ce42c615557.png)

#### Steps to reproduce:
- Just look all creative tabs.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: Latest 1.12.2 Dev
- EnderCore: Latest 1.12.2 Dev
- Minecraft: 1.12.2
- Forge: Latest build

**Comment by SteveKunG** [comment]
I know you told me that do not use the latest version, I just saw this bug during testing.

**Comment by tyler489** [comment]
All upgrades do this. Will be fixed soon.

**Comment by EpicSquid** [comment]
This was fixed a while ago
