### ISSUE TITLE
Can't rotate conduit facade

### ISSUE THREAD

**Issue by Phantom329** [SleepyTrousers/EnderIO#4477]
#### Issue Description:
I cannot rotate certain types of conduit facade.

#### What happens:
I try to rotate greatwood log [Thaumcraft 6 B7] conduit facade the way I do with oak wood conduit facade.

#### What you expected to happen:
Greatwood facades rotate like oak wood facades

#### Steps to reproduce:
 try to rotate greatwood conduit facade with yeta wrench

#### Affected Versions (Do *not* use "latest"):
- EnderIO: 3.1.183
- EnderCore: 0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

**Comment by HenryLoenwind** [comment]
If the greatwook block doesn't react to rotation there's nothing we can do about it.
