### ISSUE TITLE
Problem with Dark Hekmet and Night Vision

### ISSUE THREAD

**Issue by demycat** [SleepyTrousers/EnderIO#4488]
- EnderIO: 2.3.0.429
- EnderCore: 0.2.0.35
- Minecraft: 1.7.10
- Forge: 1.2.0.347
Today I encountered a problem, the helmet does not want to add an improvement in night vision (previously such problems were not observed)
![2018-03-25_22 47 48](https://user-images.githubusercontent.com/34833284/37879293-5c7fb66a-307f-11e8-9196-b1a0d763b8e7.png)
![2018-03-25_22 47 50](https://user-images.githubusercontent.com/34833284/37879294-5c9dabde-307f-11e8-8233-7d945a6d5af9.png)

**Comment by tyler489** [comment]
What version of nightvision is that

**Comment by demycat** [comment]
@tyler489 Initially, as before, they used the potion for 3 minutes

**Comment by KreativeKngYT** [comment]
still happening, tried all version of Night Vision pot, and am on the latest vers of EnderIO for 1.7.10 which is 2.3.0.430
