### ISSUE TITLE
EnderIO 1.12 crashes at start

### ISSUE THREAD

**Issue by Lyror** [SleepyTrousers/EnderIO#4504]
#### Issue Description:
I added EnderIO to the FTB Revelations-pack.

#### What happens:
Modpack crashes on startup

#### What you expected to happen:
Modpack start without crashes

#### Steps to reproduce:

1. Add EnderIO and Core to the Modpack
2. Start Modpack

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.20
- EnderCore: EnderCore-1.12.2-0.5.18
- Minecraft: 1.12
- Forge: forge-14.23.2.2613

#### Your most recent log file where the issue was present: 

https://pastebin.com/FB3ZrRPS

**Comment by MatthiasMann** [comment]
This crash is caused by exchangers - seems it's recipes are not compatible withe EnderIO 5.0

**Comment by Lyror** [comment]
I could solve my problem with updating the pack to 1.8.0

close
