### ISSUE TITLE
Incompatibly with Diet Hoppers

### ISSUE THREAD

**Issue by Ravin890** [SleepyTrousers/EnderIO#4505]
#### Issue Description:
Causes a fatal error which requires you to disable recipes to work.

#### What happens:
Unable to start game

#### Steps to reproduce:

1. Add mods into mod folder
2. Start profile with mods
3. Get Issue

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.20
- EnderCore: 0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2634
- DietHopper: 1.1
https://cdn.discordapp.com/attachments/193471124552679425/430109377823899678/unknown.png

**Comment by HenryLoenwind** [comment]
https://github.com/rwtema/DietHopper/issues/5

**Comment by Bircko** [comment]
idk but it works for me with diethopper

**Comment by tifkat** [comment]
Would it be worth making a workaround? Check for BlockHopper or BlockDietHopper?

Is there a way to modify recipes/items.xml without it getting overwritten on the next launch?

**Comment by xAlicatt** [comment]
I have DietHoppers ver 1.1 installed and the 5.0.20 EIO beta and no crash.
