### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by theg280amer** [SleepyTrousers/EnderIO#4506]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:The game crashed whilst initializing game
Error: java.lang.RuntimeException: java.lang.ClassNotFoundException: crazypants.enderio.integration.top.TheOneProbeUpgrade

#### Steps to reproduce:

1.load game
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.12.2
- EnderCore:1.12.2
- Minecraft: 1.7.10
- Forge:1.12.2

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by EpicSquid** [comment]
Don't use 1.12 versions on the wrong minecraft version
