### ISSUE TITLE
[1.12.2]Energy Gauge bug

### ISSUE THREAD

**Issue by xILikepuddingx** [SleepyTrousers/EnderIO#4509]
As already mentioned on discord, there is a little bug with the energy gauge. this bug occurs on both vanilla and modpacks / with other mods.

#### Issue Description:
faulty texture, not clickable so no gui, you can go through it

#### What happens: + Steps to reproduce:

https://files.pudding.tk/q1v4yop4rv.mp4

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.20
- EnderCore: 0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by HenryLoenwind** [comment]
I see nothing in you video that doesn't work as it should.

**Comment by tyler489** [comment]
They dont have a hitbox prehaps.. or the the power bar renders on the inside face of the machine instead of the outside... @HenryLoenwind
