### ISSUE TITLE
Item Conduit Isn't Working?...

### ISSUE THREAD

**Issue by kenijey** [SleepyTrousers/EnderIO#4510]
#### Issue Description:
sorry if i'm stupid about using EnderIO. in vanilla + endercore+enderio; 
1-i put a sagmill, and charged it with creative capacitor (connected with advanced energy conduit)
2-inserted a capacitor(item) then put some ores(diamond ore)
3-connected it to a single vanilla chest (1x) with item conduit
4-configured the output of the machine, configured also item conduit input-output ways
BUT, items won't transfer to the chest. am i wrong at somewhere? i used Forge 2652. thanks.

tried everything with yeta wrench

#### Affected Versions:

- EnderIO: 5.0.20
- EnderCore: 0.5.18 
- Minecraft: 1.12.2
- Forge: 2652
- Installed mods: Nothing except EnderCore and EnderIO

i didnt think it needs logs becus of vanilla+mod, but if needed just tell me

**Comment by tyler489** [comment]
Put the chest next to the machine and have the machine "push"  things into it. No item conduit needed

**Comment by kenijey** [comment]
what if i need to connect to something with item conduit? shouldn't it work with item conduit?

**Comment by tyler489** [comment]
Is the conduit set to redstone mode on?

**Comment by tyler489** [comment]
A screenshot might help

**Comment by kenijey** [comment]
ok i will record a video for it today.

**Comment by kenijey** [comment]
oh god, i just created a new world then it started working. have NO idea, i tried it with even vanilla. im shocked...

**Comment by kenijey** [comment]
i think i found what happened, i forgot the redstone mode for item conduit. i've deleted the world that i experienced this problem yesterday. today i changed redstone modes for sagmill and conduit correctly i think, then it worked, this is why i think. sorry anyway..
