### ISSUE TITLE
[1.12.2]Strange lags... i don`t know

### ISSUE THREAD

**Issue by Rumaruka** [SleepyTrousers/EnderIO#4512]
#### What happens:

I don`t get Grains of Infinity

#### What you expected to happen:
If chance will provoke drop GoI, than i near sound, but item don`t droped

#### Steps to reproduce:

1. Going bedrock
2. Light bedrock with flint and steel
3. Nothing
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.20
- EnderCore: 0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2652

#### Your most recent log file where the issue was present: 
Log file: https://www.dropbox.com/s/bctvhm2m8dpydbv/latest.log?dl=0
YT link: **https://youtu.be/juVd3BHhIao**

**Comment by HenryLoenwind** [comment]
Do you have any mod that changes damage from burning?

**Comment by Rumaruka** [comment]
Maybe,  but I don't sure - Better With Mod or Iguana Tweaks Reborn 
But, again I don't sure,  I'm testing pack without this mod and open issue were.
Please,  don't close issue I'm checked and write more information about this) 
Thank you for answer

**Comment by Ommina** [comment]
Flux Networks (which is in the OP's pack) has a crafting step in which the player tosses redstone into fire to get a different item back.  Does that count as damage from burning?

**Comment by tyler489** [comment]
No

**Comment by Rumaruka** [comment]
@tyler489 Nope firetick on

**Comment by Rumaruka** [comment]
Im stupid IDIOT
Ohhhh- Quarry in mod Simple Quarry can magnetize object, even in the off state
Sorry again
Close
