### ISSUE TITLE
[1.12.2] CraftTweaker Recipes not working

### ISSUE THREAD

**Issue by Bircko** [SleepyTrousers/EnderIO#4516]
#### Issue Description:
EnderIO prevents CraftTweaker Scripts/Recipes from working.

#### What happens:
Recipes that changed with CraftTweaker appear in JEI like they should but can only crafted in the default way.

#### What you expected to happen:
Recipes should be Craftable in the Way they got changed

#### Steps to reproduce:

1. Install CraftTweaker
2. Make a Script for change a Recipe

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.20
- EnderCore: 0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2618

**Comment by HenryLoenwind** [comment]
We have no support (nor the opposite) for CraftTweaker.
