### ISSUE TITLE
Game crash during Pre-initialized

### ISSUE THREAD

**Issue by uuk0** [SleepyTrousers/EnderIO#4519]
#### Issue Description:
Add core + main jar file in mcreator's mod dir, run. at the end of the Pre-initialion, the game crashed

#### What you expected to happen:

Run normaly

#### Steps to reproduce:

1. past files into mod-dir of mcreator 1.7.8 and run with mcreator

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.20
- EnderCore: 5.0.20
- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- MCreator: 1.7.8

#### Your most recent log file where the issue was present: 

[net.minecraft.init.Bootstrap:printToSYSOUT:629 ---- Minecraft Crash Report ---- WARNING: coremods are present:   EnderCorePlugin (EnderCore-1.12.2-0.5.18.jar) Contact their authors BEFORE contacting forge // Hi. I'm Minecraft, and I'm a crashaholic. Time: 4/3/18 10:15 AM Description: Initializing game java.lang.RuntimeException: ModObject:create: Could not create instance for class crazypants.enderio.machines.machine.teleport.telepad.BlockTelePad using method create_telepad    at crazypants.enderio.base.init.ModObjectRegistry.throwCreationError(ModObjectRegistry.java:147)    at crazypants.enderio.base.init.ModObjectRegistry.createObject(ModObjectRegistry.java:158)    at crazypants.enderio.base.init.ModObjectRegistry.createBlock(ModObjectRegistry.java:179)    at crazypants.enderio.base.init.ModObjectRegistry.registerBlocks(ModObjectRegistry.java:66)    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_82_ModObjectRegistry_registerBlocks_Register.invoke(.dynamic)    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:736)    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)    at net.minecraft.client.Minecraft.init(Minecraft.java:513)    at net.minecraft.client.Minecraft.run(Minecraft.java:421)    at net.minecraft.client.main.Main.main(Main.java:118)    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke(Method.java:498)    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke(Method.java:498)    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)    at GradleStart.main(GradleStart.java:25) Caused by: java.lang.reflect.InvocationTargetException    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke(Method.java:498)    at crazypants.enderio.base.init.ModObjectRegistry.createObject(ModObjectRegistry.java:156)    ... 24 more Caused by: java.lang.NoSuchFieldError: field_149783_u    at crazypants.enderio.machines.machine.teleport.telepad.BlockTelePad. (BlockTelePad.java:60)    at crazypants.enderio.machines.machine.teleport.telepad.BlockTelePad.create_telepad(BlockTelePad.java:49)    ... 29 more A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Client thread Stacktrace:    at crazypants.enderio.base.init.ModObjectRegistry.throwCreationError(ModObjectRegistry.java:147)    at crazypants.enderio.base.init.ModObjectRegistry.createObject(ModObjectRegistry.java:158)    at crazypants.enderio.base.init.ModObjectRegistry.createBlock(ModObjectRegistry.java:179)    at crazypants.enderio.base.init.ModObjectRegistry.registerBlocks(ModObjectRegistry.java:66)    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_82_ModObjectRegistry_registerBlocks_Register.invoke(.dynamic)    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:736)    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)    at net.minecraft.client.Minecraft.init(Minecraft.java:513) -- Initialization -- Details: Stacktrace:    at net.minecraft.client.Minecraft.run(Minecraft.java:421)    at net.minecraft.client.main.Main.main(Main.java:118)    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke(Method.java:498)    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke(Method.java:498)    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)    at GradleStart.main(GradleStart.java:25) -- System Details -- Details:    Minecraft Version: 1.12.2    Operating System: Windows 8.1 (amd64) version 6.3    Java Version: 1.8.0_162, Oracle Corporation    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation    Memory: 434975816 bytes (414 MB) / 943194112 bytes (899 MB) up to 1814036480 bytes (1730 MB)    JVM Flags: 0 total;     IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0    FML: MCP 9.42 Powered by Forge 14.23.2.2611 14 mods loaded, 14 mods active    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored    | State | ID                         | Version       | Source                           | Signature |    |:----- |:-------------------------- |:------------- |:-------------------------------- |:--------- |    | UCH   | minecraft                  | 1.12.2        | minecraft.jar                    | None      |    | UCH   | mcp                        | 9.42          | minecraft.jar                    | None      |    | UCH   | FML                        | 8.0.99.99     | forgeSrc-1.12.2-14.23.2.2611.jar | None      |    | UCH   | forge                      | 14.23.2.2611  | forgeSrc-1.12.2-14.23.2.2611.jar | None      |    | UCH   | testenvironmentmod         | 1.0           | modid-1.0.jar                    | None      |    | UCH   | endercore                  | 1.12.2-0.5.18 | EnderCore-1.12.2-0.5.18.jar      | None      |    | UCH   | enderio                    | 5.0.20        | EnderIO-1.12.2-5.0.20.jar        | None      |    | UCH   | enderiointegrationtic      | 5.0.20        | EnderIO-1.12.2-5.0.20.jar        | None      |    | UCH   | enderiobase                | 5.0.20        | EnderIO-1.12.2-5.0.20.jar        | None      |    | UCH   | enderioconduits            | 5.0.20        | EnderIO-1.12.2-5.0.20.jar        | None      |    | UCH   | enderiointegrationforestry | 5.0.20        | EnderIO-1.12.2-5.0.20.jar        | None      |    | UCH   | enderiointegrationticlate  | 5.0.20        | EnderIO-1.12.2-5.0.20.jar        | None      |    | UCH   | enderiomachines            | 5.0.20        | EnderIO-1.12.2-5.0.20.jar        | None      |    | UCH   | enderiopowertools          | 5.0.20        | EnderIO-1.12.2-5.0.20.jar        | None      |    Loaded coremods (and transformers):  EnderCorePlugin (EnderCore-1.12.2-0.5.18.jar)   com.enderio.core.common.transform.EnderCoreTransformer    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.3.12618 Compatibility Profile Context 13.251.9001.1001' Renderer: 'AMD Radeon HD 7310 Graphics'    Ender IO: No known problems detected.    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!You are looking at the diagnostics information, not at the crash.       !!!    !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    Launched Version: 1.12.2    LWJGL: 2.9.4    OpenGL: AMD Radeon HD 7310 Graphics GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.    GL Caps: Using GL 1.3 multitexturing. Using GL 1.3 texture combiners. Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported. Shaders are available because OpenGL 2.1 is supported. VBOs are available because OpenGL 1.5 is supported.    Using VBOs: Yes    Is Modded: Definitely; Client brand changed to 'fml,forge'    Type: Client (map_client.txt)    Resource Packs:     Current Language: English (US)    Profiler Position: N/A (disabled)    CPU: 2x AMD E1-1500 APU with Radeon(tm) HD Graphics

**Comment by HenryLoenwind** [comment]
-> Forge
