### ISSUE TITLE
behaviour with the silicon from AE2 

### ISSUE THREAD

**Issue by TheBlackLuigi** [SleepyTrousers/EnderIO#4521]
#### Issue Description:
When Ender-IO and AE2 are installed, the AE2 Silicon will be changed into "this item is disabled".
Also the Ender-IO Silicon cannot be used as a material for the Inscriber.

#### Steps to reproduce:

1. Install AE2 
2. Cheat in some Silicon and place an Inscriber with the silicon-press
3. Install Ender-IO

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.20
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2624
-AE2: appliedenergistics2-rv5-stable-11

#### Your most recent log file where the issue was present: 

This issue did not cause a crash.

**Comment by ate0ate** [comment]
AE2 can be fickle. I'm currently experiencing this as well as a similar issue with wooden gears and a different mod than Eio. A temporary workaround is going into the AE2 config, scrolling down to the "orecamouflage"  section, finding the entry for itemSilicon and setting it to "B:SILICON=false."

**Comment by ate0ate** [comment]
Haha, sorry about that lol. Works fine for me, but like I said, its fickle:)

**Comment by HenryLoenwind** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3437
