### ISSUE TITLE
[1.12.2] Omni buffer GUI outta line (EnderIO-1.12.2-5.0.287-nightly)

### ISSUE THREAD

**Issue by b0bst3r** [SleepyTrousers/EnderIO#4522]
#### What happens:

Power bar out of line on Omni buffer GUI

https://i.imgur.com/CWEhkAc.png

Can't adjust this as the background bar slot is as high as it can go on the GUI template, the actual energy bar needs to be moved down so it can fit in.

You can align it using a resourcepack but it's still too high up 

https://i.imgur.com/SdIiOoL.png
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.287-nightly
- EnderCore: EnderCore-1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2652

**Comment by tyler489** [comment]
Fixed with https://github.com/SleepyTrousers/EnderIO/commit/7eb3ce423d12c158da9d6439e8fa6050800dc055

**Comment by EpicSquid** [comment]
General bug for all power bar machines

**Comment by EpicSquid** [comment]
Fixed in dev version now
