### ISSUE TITLE
Stuff Missing sagmill recipy

### ISSUE THREAD

**Issue by tyler489** [SleepyTrousers/EnderIO#4523]
Plants Mod (seperate file)
Aroma sticky ore
BOP Hive Block
Magma Block
Heat Sand?
JAOPCAC chunkOre (seperate file)

**Comment by EpicSquid** [comment]
JAOPCA should *technically* be handling that bit themselves

**Comment by tyler489** [comment]
JAOPCA does but JAOPCAC doesnt. They use a seperate oredict from oreOre

**Comment by tyler489** [comment]
https://minecraft.curseforge.com/projects/aobd-ore-chunks

**Comment by EpicSquid** [comment]
Right, different mod
