### ISSUE TITLE
[1.12.2] Crafttweaker

### ISSUE THREAD

**Issue by Bircko** [SleepyTrousers/EnderIO#4524]
#### Issue Description:
EnderIO brekas Crafttweaker Recipes....

Why this issue got closed you don't need to have crafttweaker support but your mod breaks whole crafttweaker mod.

#### What happens:
Recipes that changed with CraftTweaker appear in JEI like they should but can only crafted in the default way.

#### What you expected to happen:
Recipes should be Craftable in the Way they got changed

#### Steps to reproduce:

1. Install CraftTweaker
2. Make a Script for change a Recipe

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.20
- EnderCore: 0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2618

#### Your most recent log file where the issue was present: 

Why this issue got closed you don't need to have crafttweaker support but your mod breaks whole crafttweaker mod.

**Comment by tyler489** [comment]
Did you retart the pack after making the  recipy

**Comment by HenryLoenwind** [comment]
We do nothing with or to Crafttweaker. Open a ticket with them.
