### ISSUE TITLE
Suggestion for Attractor Obelisk

### ISSUE THREAD

**Issue by BloshJ** [SleepyTrousers/EnderIO#4525]
Not sure if this is the right place for suggestions, remove if its not and please direct me to the correct place.

My suggestion is to add a config option to remove the need for soul vials in the attractor obelisk. There could even be 3 options: 0=soul vials needed, 1=octadic capacitor replaces need for soul vials, 2=no soul vials needed. Or even a blacklist/whitelist function, so you still have the option of targeting specific mobs.
I don't how it could be implemented but it would be very useful, especially in packs that have 100s of mobs and it would also help balance it, as fans are a lot cheaper and require no power.

**Comment by EpicSquid** [comment]
Better to post a suggestion like this here http://ideas.theideawall.com/EnderIO/Forum/Details/
