### ISSUE TITLE
Item Conduits Not always respecting filters

### ISSUE THREAD

**Issue by Moobien** [SleepyTrousers/EnderIO#4526]
#### Issue Description:
Have discovered an issue where Item Conduits do not always respect Filters.
#### Steps to reproduce:

1. Sag Mill and Alloy Smelter side by side.
2. Sag Mill set to PUSH to the right into Alloy Smelter
3. 1 Conduit on top in extract mode and also 1 on the back.
4. TOP Conduit has basic filter whitelisting Cobblestone, Flint, Gravel, Sand & EnderIO Silicon
5. BACK Conduit has basic filter whitelisting Nettherack, Sulphur and crushed coal
6. Insert 35 Iron Ore into SAG Mill
7. My results had 4 Nickel Dust and 44 Iron dust pulled out into output chest.

Screenshots: https://imgur.com/a/plRJC

Setup can be inspected by Devs on EnderIO Test Server at Coordinates -383, -1027, 71 In Mining Dimension.

____

**Comment by tyler489** [comment]
Can confirm but unable to reproduce

**Comment by EpicSquid** [comment]
Simple case of needing to turn on match meta
