### ISSUE TITLE
[1.12.2] NoSuchFieldError crash when loading EnderIO in a development environment

### ISSUE THREAD

**Issue by desht** [SleepyTrousers/EnderIO#4527]
#### Issue Description:
When loading EnderIO in a development environment (IntelliJ), the instance crashes during pre-init with a NoSuchFieldError.  See below for the attached stacktrace.

#### What happens:

The missing field is ``field_149783_u`` referenced by the BlockTelePad constructor at line 60:
```java
useNeighborBrightness = true;
```
I verified the MCP mapping - ``field_149783_u`` does indeed appear to map to ``Block#useNeighborBrightness``

EnderIO loads fine outside a development environment.  Within the dev environment, I tested with a minimal mod framework and no other mods in ``run/mods``, and the crash still occurs.

A little bytecode editing on the JAR file to remove that one line allowed EnderIO to load into the dev environment OK, so the issue is definitely limited to that one line of code - the ``useNeighborBrightness`` reference.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.20
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: tested with 14.23.2.2611 and 14.23.2.2654

#### Your most recent log file where the issue was present: 

 [crash.txt](https://github.com/SleepyTrousers/EnderIO/files/1874963/crash.txt)

**Comment by HenryLoenwind** [comment]
Open this one against Forge/fml

**Comment by EpicSquid** [comment]
This is fixed as of forge 14.23.3.2679. Set your enderio development environment to use that version to fix this issue.
