### ISSUE TITLE
[EnderIO-1.12.2-5.0.20] Simple Alloy Smelter doesn't accept some items

### ISSUE THREAD

**Issue by VallenFrostweaver** [SleepyTrousers/EnderIO#4530]
#### Issue Description:
Simple Alloy Smelter doesn't accept some items. Example: Coal ore. Iron Powder or Ore.

#### What happens:
I tried to place these items in the SAS and it won't allow the items to be placed in the slot.

#### What you expected to happen:
The items to be accepted and smelted as per the JEI image.

#### Steps to reproduce:
1. Place a poweded SAS down and try to place any of the above example items in the input slot.
____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: 1.12.2-5.0.20
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2624

JEI image showing recipe is available for BOTH SAS and AS:
![jei](https://user-images.githubusercontent.com/13642054/38315065-91c9115c-381f-11e8-948a-5f92f9376ef0.png)

Actual UI and attempted (but failed) placement of items:
![iron powder](https://user-images.githubusercontent.com/13642054/38315074-96635434-381f-11e8-9bbc-d8a4f0f6b69e.png)
![coal ore](https://user-images.githubusercontent.com/13642054/38315080-99863514-381f-11e8-9308-2801be9db9b3.png)

**Comment by EpicSquid** [comment]
Simple alloy smelter is only for alloys, you have to upgrade the alloy smelter to use it as a furnace

**Comment by EpicSquid** [comment]
Though it might be good to better indicate this in Jei, I will look into it

**Comment by VallenFrostweaver** [comment]
Cool. I thought that may be the case but I wasn't sure. Thank you.

**Comment by HenryLoenwind** [comment]
There's no way to get JEi to remove the SAS for just some recipes. The only way to have this differently would be to have two different categories, both with all alloy recipes...

**Comment by VallenFrostweaver** [comment]
Bleh. That's not very encouraging.

**Comment by EpicSquid** [comment]
@tyler489 we already have that
