### ISSUE TITLE
[1.12.2] MC crash when opening wired charger GUI

### ISSUE THREAD

**Issue by LordDiablo** [SleepyTrousers/EnderIO#4533]
#### Issue Description:
Minecraft crashes when I try to open wired charger GUI. Already postet the crash report to the modpack creators but they couldn't find any mod specific issue for that and asked me to post it here.

#### What happens:
Minecraft crashes immediately when I right click the wired charger.

#### What you expected to happen:
Wired charger gui opens ;)

#### Steps to reproduce:
1. Place wired charger (whether connected to any power source or not)
2. Right click wired charger
3. Minecraft crashes instantly

____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: EnderIO-1.12.2-5.0.20.jar
- EnderCore: EnderCore-1.12.2-0.5.18.jar
- Minecraft: 1.12.2
- Forge: 14.23.1.2554

#### Your most recent log file where the issue was present: 
https://pastebin.com/yA54mSBG

**Comment by EpicSquid** [comment]
Fixed in dev branch
