### ISSUE TITLE
[1.10.2] Server crashes on every startup | Farmingstation

### ISSUE THREAD

**Issue by Marcel40625** [SleepyTrousers/EnderIO#4535]
#### Issue Description:
Server crashes on every startup

#### What you expected to happen:
Server runs fine like the last 20 days :)

#### Versions:

- EnderIO: 1.10.2-3.1.193
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

#### Logs:
https://pastebin.com/kjKWje95

**Comment by HenryLoenwind** [comment]
Tree too big error. Use mcedit.
