### ISSUE TITLE
[1.12.2] AdvancedRocketry + EnderIO = Crash

### ISSUE THREAD

**Issue by slava110** [SleepyTrousers/EnderIO#4538]
#### Issue Description:
EnderIO and AdvancedRocketry crash

#### What happens:

Crash

#### What you expected to happen:

Working game without crash

#### Steps to reproduce:

1. Start client
2. Wait some time
3. Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.20
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2654

#### Your most recent log file where the issue was present: 

Crash log:
https://pastebin.com/zsbX102v

**Comment by tyler489** [comment]
This is an advanced  rocketry issue caused by an entity being rendered outside the world according to the dev. See https://github.com/zmaster587/AdvancedRocketry/issues/1235

**Comment by slava110** [comment]
Oh, thanks, sorry for useless issue
