### ISSUE TITLE
Liquefied Ender Pearls conflict with Resonant Ender

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4544]
#### Issue Description:
When processing Ender Pearls in Thermal Expansion's Magma Crucible I am supposed to get Resonant Ender, however I am getting Liquefied Ender Pearls instead.
It sounds like there's a recipe conflict between TE's Resonant Ender and EIO's Liquefied Ender Pearls and the server just picks one of them randomly every time it starts. Right now I'm stuck with Liquefied Ender Pearls.
The problem being that I can't fill my Transporter or even buckets with Liquefied Ender Pearls, so I have no way to use it.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.20
- EnderCore: 5.18
- Minecraft: 1.12.2
- Forge: 2641
- Mods: [list.txt](https://github.com/SleepyTrousers/EnderIO/files/1888018/list.txt)

**Comment by tyler489** [comment]
What do you need resonate ender for?

**Comment by HenryLoenwind** [comment]
This is how the Forge liquid system works...

**Comment by Xiaminou** [comment]
I'm sure it is, but right now I can't fill my Transporter with Liquefied Ender Pearls, that's the issue. The compatibility is broken somehow.

**Comment by tyler489** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/3e93dc15f6955e887ae1acb6bf1180c46cedaf34 should fix it not being able to be bucketed

**Comment by Xiaminou** [comment]
It did.
