### ISSUE TITLE
[1.12.2] Missing Texture

### ISSUE THREAD

**Issue by Yhuxz** [SleepyTrousers/EnderIO#4545]
Issue Description:
Painting glasses on facades.

What happens:
I'm trying to make my old see thru mob grinding box using facades to cover up the conduits beneath. Holding a conduit in-hand doesn't trigger a texture error

https://i.imgur.com/Jk60Dbc.png
https://i.imgur.com/LRAFgYI.png

What you expected to happen:
Just those glass, no conduits showing, no missing texture

Steps to reproduce:

1. Use any type of facade in painter. (Tested with Transparent Hardened Conduit Facade)
2. Use any type of glass to paint with. (Tested with Dark Fused Quartz)
3. Line a 5 conduit (any type) and use a painted facade on them
4. Hold a conduit in hand to check (optional)

Affected Versions:

- EnderIO: EnderIO-1.12.2-5.0.20
- EnderCore: EnderCore-1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.2.2611

Your most recent log file where the issue was present: 
https://gist.github.com/Yhuxz/8b6b5c2a43d4bcc9a5bb7d20b8d50263

**Comment by Yhuxz** [comment]
Why out of date? Is it because Im still using the recommended forge?

**Comment by EpicSquid** [comment]
This has been fixed in the dev version

**Comment by Yhuxz** [comment]
Thanks for the heads up
