### ISSUE TITLE
[1.12.2] Forgetful Dimensional Transceiver

### ISSUE THREAD

**Issue by andr9528** [SleepyTrousers/EnderIO#4546]
#### Issue Description:

Dimensional Transceiver being very forgetful, losing all saved channels on closing minecraft completely

#### What happens:

All Channels that have been created previously are wiped, upon closing minecraft.

#### What you expected to happen:

All Channels to be kept until the user chooses to delete them.

#### Steps to reproduce:

1.  Put down Dimensional Transceiver
2. Create a Channel (Energy is the one i'm using right now)
3. Save and Exit the world
4. Close Minecraft
5. Reopen minecraft and world
6. Open Dimensional Transceiver to find channels gone.

#### Affected Versions:

- EnderIO: 1.12.2-5.0.20
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2653

#### Your most recent log file where the issue was present:

Link includes Top half of latest.log. (file too large to copy all) 
https://pastebin.com/zJqaB6Mr

**Comment by andr9528** [comment]
didn't happen for me when my minecraft crashed and i opened it again, might need to actually restart pc for the problem to happen, as the error first happened 2 days ago, then again yesterday, and lastly when i came on today, so only once per start of PC, which is really weird, are the data stored in RAM, even after minecraft closes?

**Comment by tyler489** [comment]
They looked into this and couldn't figure it out  it seems to be only private channels as far as my testing goes

**Comment by andr9528** [comment]
i'm using public channels, as it is in single player

**Comment by ShadwDrgn** [comment]
I'm experiencing this with private channels as well. Client forgets when i log off server, and entire server forgets on restarting. EnderIO-1.12.2-5.0.26.jar forge 2705.

**Comment by HenryLoenwind** [comment]
Please have a look in your logfiles. Both at the end of one session and st the start of the next one. I'd need those lines that mention `ServerChannelRegister` only (unless there's a stack trace near them).

**Comment by ShadwDrgn** [comment]
Here's a bunch of relevant server-side stuff. Virtually nothing in the latest.log or debug.log clientside at the time of login. Though some info during what appears to be client startup. Also included relevant server debug and latest logs for login, logout, and startup. I tried to keep this concise. Hopefully this is all relevant. Let me know if you need more context or full logs.

[serverLtst-startup.txt](https://github.com/SleepyTrousers/EnderIO/files/2120829/serverLtst-startup.txt)

[serverDbg-logout.txt](https://github.com/SleepyTrousers/EnderIO/files/2120820/serverDbg-logout.txt)
[serverDbg-login.txt](https://github.com/SleepyTrousers/EnderIO/files/2120821/serverDbg-login.txt)
[serverDbg-serverup.txt](https://github.com/SleepyTrousers/EnderIO/files/2120822/serverDbg-serverup.txt)
[clientDbg-startup.txt](https://github.com/SleepyTrousers/EnderIO/files/2120823/clientDbg-startup.txt)

**Comment by kyle-sama** [comment]
I get the same problem, every time i log off, all my channels dissappear, however, channels of another player on my server never do

**Comment by HenryLoenwind** [comment]
1 current version?

2 bought or pirated account? (Or offline mode server?)

3 do your channels work whilst you're on?

4 any errors in server log?

**Comment by kyle-sama** [comment]
1. 1.12.2-0.5.22
2. bought, online multiplayer server, twitch launcher, All the mods 3 modpack v5.9.6b
3. Yes
4. not sure, I don't run the server, i'll see if I can find them. But no errors locally

**Comment by HenryLoenwind** [comment]
.22 is quite old, .29 is current. Channel code changed since then, so no idea if fixed now or not...

Thx for rst

**Comment by mughoj** [comment]
I've experienced this problem as well in EnderIO-1.12.2-5.0.26. It seems to have gone away for me when all my transceivers are chunkloaded by another mod.
