### ISSUE TITLE
[1.12.2] Killer_Joe "kills" Server. (Block Entity being ticked).

### ISSUE THREAD

**Issue by Gyromax** [SleepyTrousers/EnderIO#4548]
#### Issue Description:
Server shuts down, after entering the AoE of a Killer_Joe, doesn't matter if aktiv or not.

#### What happens:
Server shuts down and will crash everytime, until i use "/setblock" to switch the Killer_Joe with any other Block.

#### What you expected to happen:
I can walk in the Area of Effect from the Killer_Joe. If it's aktiv, i would recive Damage, if it's offline, i can just walk / build or collect there.

#### Steps to reproduce:

1. Build a Killer_Joe, give him any Sword (tried with 3 different Swords)
2. Let it work once (even without any Monster, just Nutrient and a Weapon).
3. Server crashes.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2 - 5.0.20
- EnderCore: 1.12.2 - 0.5.18
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.2.2654

#### Your most recent log file where the issue was present: 
Crash-Reports sorted by Sword-Type.
1. DIamond-Sword (Vanilla / latest)
https://pastebin.com/Kxstu5Di
2. Emeradic-Sword (Actually Additions)
https://pastebin.com/WZCcPVxr
3. Unbreakable Paper-Sword (Tinkers Construct / oldest)
https://pastebin.com/A6eyMuiw

If you need more Information, pls tell me and i'll bring them as fast as i can.
Thanks for your Time and your great Work!

**Comment by HenryLoenwind** [comment]
ftbutilities/ftblib is crashing here. Open a ticket there and link this one in.

**Comment by Gyromax** [comment]
thanks for the Info, I've just now seen, that they updated their Mods 3 Hours ago. Will try the new Versions tomorrow, and if it doesn't work, i'll do as you suggested.

**Comment by Gyromax** [comment]
Sorry for my late answer, got a suprise visit from a friend and didn't find time to test it.
With the following Versions it now works fine.

EnderIO: 1.12.2 - 5.0.21
EnderCore: 1.12.2 - 0.5.18
Minecraft: 1.12.2
Forge: 1.12.2 - 14.23.2.2666
FTBLib: 5.0.2.10
FTB Utilities: 5.0.2.10

Thanks again and i guess that means case closed.
