### ISSUE TITLE
Power system used

### ISSUE THREAD

**Issue by TheDutchMC04** [SleepyTrousers/EnderIO#4549]
#### Issue Description:
I want to know if its possible to use RF instead of uI for power. My whole pack is RF, except EnderIO. Could this maybe be added trough a config change?
#### Affected Versions:

- EnderIO: 1.12.2-5.0.20
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2654

**Comment by HenryLoenwind** [comment]
no
