### ISSUE TITLE
[1.12.2] JEI crash

### ISSUE THREAD

**Issue by bramw0** [SleepyTrousers/EnderIO#4551]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Whenever I start Minecraft with EnderIO and JEI version 159, it crashes at the Finishing Up part (6/7).

#### What you expected to happen:
I expected Minecraft would load normally, with all the mods I had installed.

#### Steps to reproduce:

1. Install Forge 1.12.2
2. Install Just Enough Items (JEI)
3. Install EnderIO + EnderCore
^ All through Twitch Launcher fyi.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.20
- EnderCore: 1.12-0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.3.2657
- JEI: 1.12.2-4.8.5.159

#### Your most recent log file where the issue was present: 

https://pastebin.com/wE9tziLp (Launcher crash screen)

https://pastebin.com/NCSDUe8g (Minecraft crash report)

https://gist.github.com/bramw0/07c7680bbd49dd9d9f37bed6ad718e04 (This one was too big for pastebin)

**Comment by tyler489** [comment]
Does this happen with forge 14.23.3.2655

**Comment by HenryLoenwind** [comment]
Bad Forge version.

https://github.com/MinecraftForge/MinecraftForge/issues/4865
