### ISSUE TITLE
Minecraft crashes after i place a Power Monitor

### ISSUE THREAD

**Issue by kekosminek** [SleepyTrousers/EnderIO#4552]
I have a modpack and when i place down a power monitor my game crashes

And i know it's a mod thing, but i don't know what mods add or remove or something else

#### Affected Versions (Do *not* use "latest"):

- EnderIO: enderio-2.0_beta.124
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 1.7.10-10.13.4.1614

Crash report:
https://gist.github.com/kekosminek/d4844cfa3498a03f4e82538932ac9c78

**Comment by tyler489** [comment]
Buildcraft
