### ISSUE TITLE
cannot display I/O or "usage progress bar" on horizontal planes of Capacitors

### ISSUE THREAD

**Issue by TheQuadShot** [SleepyTrousers/EnderIO#4558]
I can only get them to display on vertical planes.
Minecraft 1.10.2
Forge 12.18.3.2511
ModList: https://pastebin.com/cv5dXghF

EnderIO-1.10.2-3.1.193
EnderCore-1.10.2-0.4.1.66-beta

**Comment by HenryLoenwind** [comment]
Yes, works as designed.
