### ISSUE TITLE
Conduit issue with OpenModularTurret 

### ISSUE THREAD

**Issue by DEX47** [SleepyTrousers/EnderIO#4559]
Item Conduits do not connect to OpenModularTurret bases.  Energy Conduits behave as expected.

- EnderIO: 1.12.2-5.0.21
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2654

**Comment by tyler489** [comment]
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/410
