### ISSUE TITLE
Can't charge dark steel equipment with wired charger

### ISSUE THREAD

**Issue by SirGoldenTaco** [SleepyTrousers/EnderIO#4560]
#### Issue Description:
Wired Charger doesn't charge dark steel equipment

#### What happens:
Wired Charger doesn't charge dark steel equipment

#### What you expected to happen:
Dark steel equipment charges

#### Steps to reproduce:

1. Build "wired" charger
2. Place and interact with machine block
3. Place item in the Wired charger block
4. No power transfer

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.20.jar
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2654-universal

**Comment by EpicSquid** [comment]
Please update enderio, update ender core and downgrade forge (that version of forge is broken). Also, please actually provide a way to recreate this or screenshots.

**Comment by tyler489** [comment]
Cannot Reproduce https://gyazo.com/716cd191f606f5c74172048d7d7946f3
Also how are you using the wired charger as EnderIO: 1.12.2-5.0.20.jar Wouldn't let you open the gui without crashing the game

**Comment by SirGoldenTaco** [comment]
I'm currently playing on the "All the mods 3" pack with friends on a server
I'm not a minecraft techy so I don't know all the stuff I probably should.
But here are some screenshots of the situation

Mod folder: https://gyazo.com/dc75e1c5b1c543d7603a9c5c162ae7b4
In front of the machine: https://gyazo.com/0e71a4ec8031a7ee7694f52c110545e6
Open it up: https://gyazo.com/f54ce3441af2ae08116d1f0d34e32c39
More details: https://gyazo.com/b077d108c09285411bdc824bd40be022
(I've had to use the wireless charger to get some power in it, a bypass of sorts)

**Comment by tyler489** [comment]
Is it only the dark pick?

**Comment by SirGoldenTaco** [comment]
Just tested it with the dark helm no success
https://gyazo.com/a30fbc0a2c0426e53677cb4bfd42e9cf

**Comment by EpicSquid** [comment]
Please empower it so it can accept power

**Comment by SirGoldenTaco** [comment]
It is empowered, just brand new since I used cheat mode to create one real quick
