### ISSUE TITLE
inventory panel using gui class server side

### ISSUE THREAD

**Issue by deceet** [SleepyTrousers/EnderIO#4567]
#### Issue Description:
.21 update causes a fatal server crash since the inventory panel is using a gui class, which is client side only.

#### What happens:
see above.

#### What you expected to happen:
a running server :)

#### Steps to reproduce:

1.update to .21
2.start server
3.watch it crash gloriously
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: .21

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/CvvwsUSr

**Comment by HenryLoenwind** [comment]
Inventory Panel isn't even half-way ported yet...

**Comment by deceet** [comment]
I'm saying the .21 update makes my server crash, if it's not even half-way ported, why is it in the base enderio jar?

**Comment by EpicSquid** [comment]
Its not
