### ISSUE TITLE
JEI

### ISSUE THREAD

**Issue by AlexRover** [SleepyTrousers/EnderIO#4568]
Constant accident, I do not know whose fault it is, but without JEI I do not know how to play

EnderIO-1.12.2-5.0.21

[crash-2018-04-16_02.15.21-client.txt](https://github.com/SleepyTrousers/EnderIO/files/1913212/crash-2018-04-16_02.15.21-client.txt)

**Comment by tyler489** [comment]
You got the bugged version of forge downgrade to recomended 2655

**Comment by AlexRover** [comment]
I did not understand anything, I'm from Russia and do not know English, Google translator certainly translated, but I did not understand anything. Can you say specifically what needs to be done to make it work?

**Comment by tyler489** [comment]
Click http://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.3.2655/forge-1.12.2-14.23.3.2655-universal.jar
