### ISSUE TITLE
XP Dupe Bug

### ISSUE THREAD

**Issue by 2ndkirbyever** [SleepyTrousers/EnderIO#4572]
#### Issue Description:
Interaction between Thermal Foundation and Ender IO causes XP to be duped.

#### What happens:
Thermal Foundation's Tome of Knowledge is able to extract liquid XP from the experience obelisk. When I take the experience out of the obelisk with the tome then extract the levels, I get an extra level.

#### What you expected to happen:
The experience in the obelisk equals the experience in the tome when the tome takes the experience out.

#### Steps to reproduce:

1. Fill an obelisk with experience.
2. Right-click with the tome on the obelisk.
3. Extract experience from the tome by sneak right-clicking.
4. You have obtained an extra level of experience!

____
#### Affected Versions:

- EnderIO: 1.12.2-5.0.21
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.3.2688
- Thermal Foundation: 1.12.2-2.3.11.9

#### Your most recent log file where the issue was present: 

[Video of the bug in action](https://youtu.be/EnnhmJ5TmGw)

**Comment by KingLemming** [comment]
Just chiming in here - this doesn't happen with any other xp or fluid container in any other mod that I've tested.

The Tome follows the Minecraft xp formula exactly down to the point, so there's no rounding or fuzzy math.

**Comment by HenryLoenwind** [comment]
The time doesn't matter here, the right-click interaction is known to be off by one.

Known issue.
