### ISSUE TITLE
the wired charger causes game crash 

### ISSUE THREAD

**Issue by dragonup1793** [SleepyTrousers/EnderIO#4576]
I am using my own custom mod pack based on the world of dragons with storage drawers and ender io added as well as draconic evolution 
#### What happens:
I tried to open the wired charger to put my items in to be charged and as soon as I click on the placed charger the game crashes. even when unpowered and powered 

#### What you expected to happen:
the wired charger to open a gui 

#### Steps to reproduce:

1.click on the wired charger 
2. game crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO-1.12.2-5.0.20
- EnderCore:1.12.2-05.18
- Minecraft: 1.12.10
- Forge:14.23.3.2655

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen
https://pastebin.com/yXf2P2S6

**Comment by tyler489** [comment]
#4547  #4533
