### ISSUE TITLE
Conduit Facades let light through

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4577]
_(issue for 1.12 as requested)_
#### Issue Description:
Conduit Facades let light through

https://github.com/SleepyTrousers/EnderIO/issues/3868

- EnderIO: 5.0.22
- EnderCore: 0.5.20
- Minecraft: 1.12.2
- Forge: 2641

**Comment by Meryl** [comment]
Has there been any progress on this? This is still an issue in recent versions of EnderIO.

**Comment by Ace0fspadev** [comment]
Then Please stop closing pending issues.

**Comment by hypherionmc** [comment]
See the above mentioned issue. This was tested and could not be reproduced. If you can give the specific details of which type of facade was used, painted with which block and can accurately reproduce this multiple times, the feel free to re-open

**Comment by pixelblob** [comment]
Same problem here dude, they like store light from surrounding blocks and emit it when the blocks are no longer powered, can give a copy of my world, record a video, etc etc.
