### ISSUE TITLE
[12.2] Shift Click Deletes

### ISSUE THREAD

**Issue by Gadoon** [SleepyTrousers/EnderIO#4584]
I understand this may not solely be an EnderIO issue however I wanted to make you aware of it.

Issue Description:
So far it has only happened with Slice'n'Splice. It may be a conflict with InvTweaks and TooManyItems. However when I am trying to autoplace items into the slice'n'splice for recipes using TooManyItems clicking the + sign. However if I shift click it removes the items and does not place them into the machine effectively deleting them.

What happens:
Shift clicking items in Slice'n'Splice deletes them.

What you expected to happen:
Items to be place into the machine

Steps to reproduce:

1. Open Slice'n'Splice
2. Open recipe in TooManyItems
3. Hold Shift and press + sign to place into machine
4. Profit
...

____
Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.22
- EnderCore: 1.12.2-0.5.20
- Minecraft: 1.12.2
- Forge: 14.23.2.2618

Your most recent log file where the issue was present: 
[2018-04-22-1.log.gz](https://github.com/SleepyTrousers/EnderIO/files/1936332/2018-04-22-1.log.gz)

**Comment by Joeyrsp** [comment]
Just encountered this issue using the FTB Revelations pack.

**Comment by CritFlaw** [comment]
This still happens. EIO 5.0.37 
Forge 2772
