### ISSUE TITLE
Painted Dark Pressure Plates - texture error

### ISSUE THREAD

**Issue by TWJedi** [SleepyTrousers/EnderIO#4585]
Dark Pressure Plates have a black texture instead of being invisible, when painted with Quite Clear Glass.

- EnderIO: 5.0.22
- EnderCore: 0.5.20
- Minecraft: 1.12.2
- Forge: 14.23.3.2669

https://imgur.com/a/KOWPC27

**Comment by HenryLoenwind** [comment]
fixed
