### ISSUE TITLE
New 1.12.x versions not available on the maven

### ISSUE THREAD

**Issue by BrainStone** [SleepyTrousers/EnderIO#4586]
I tried to find EnderIO on the maven (http://maven.tterrag.com) but could only find the recent versions of EnderCore.

Unless you now can register recipes through the EnderCore API, then of course that isn't necessary.

**Comment by HenryLoenwind** [comment]
You can register recipes using the IMC XML API, there you don't need a maven dependency.

And you're also welcome to fix our build.gradle, we haven't had much luck there...

**Comment by BrainStone** [comment]
I apologize for asking, but where can I find the docs on the IMC XML API?

Also I didn't realize that it wasn't there because the build.gradle wasn't working.  
I'll see what I can do.

**Comment by HenryLoenwind** [comment]
np: https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-base/src/main/java/crazypants/enderio/api/IMC.java#L20

**Comment by BrainStone** [comment]
I'm trying to get the uploading to work, however I seem to be missing some keys or similar, as I get this error:

```
:mkKeyStore
Keytool-Fehler: java.lang.Exception: Schlüsselpaar wurde nicht generiert. Alias <signFiles> ist bereits vorhanden
:mkKeyStore FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mkKeyStore'.
> Process 'command 'keytool'' finished with non-zero exit value 1
```

I'm not sure how to get the error in English, so I'll just roughly translate `Schlüsselpaar wurde nicht generiert. Alias <signFiles> ist bereits `: `Key pair was not generated. Alias <signFiles> already exists `

Is there a simple way to avoid this, or add dummy files? I'd love to get the publishing to work.

**Comment by HenryLoenwind** [comment]
Either you have a global key with the alias "signFiles" (replace the two instances if "signFiles" in the build.gradle) or your build aborted leaving an 'eiostore.jks' behind (delete it).

**Comment by EpicSquid** [comment]
@BrainStone is that publish task producing a functioning maven build? If so I will look into adding it

**Comment by BrainStone** [comment]
It does.

**Comment by EpicSquid** [comment]
Are you able to post the output?

**Comment by BrainStone** [comment]
What outut do you mean? Of the script or the files?

**Comment by xxMattewxx** [comment]
@BrainStone I'm sure he meant the output you get from running the script you posted (what the gradlew outputs)

**Comment by BrainStone** [comment]
Well, since you changed the maven plugin, the call is now:

```
./gradlew :enderio-base:assemble --no-parallel
./gradlew :enderio-machines:assemble --no-parallel
./gradlew uploadArtifacts --no-parallel
```

(When setting a proper `mavenDir`, the files end up in the right dir. And only the main artifacts)

This is the output I got: https://gist.github.com/BrainStone/4f37bf79c9b4ed8ac0990beb94a6d235

**Comment by Keridos** [comment]
Any update on this?
