### ISSUE TITLE
1.12.2 crash on create/load world

### ISSUE THREAD

**Issue by Fez-Masta77** [SleepyTrousers/EnderIO#4587]
#### Issue Description:
I recently downloaded all of these mods (they should be all up to date) and would go to make a world and it would crash after the loading screen went away. In the crashlog I couldn't find anything else besides EnderIO and after a google search it seems I am the only one with this problem. (please correct me if I am wrong)

#### What happens:
My game crashes as I load a single player world.

#### What you expected to happen:
I expected to load in the world just fine.

#### Steps to reproduce:

1. Create a new world using biome bundle setting in OTG
2. Wait for world to be created (it gets to the point of where I am in game but no blocks are loaded)
3. crash
...
profit
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.22
- EnderCore: 0.5.20
- Minecraft: 1.12.2
- Forge: 14.23.3.2655

#### Your most recent log file where the issue was present: 

crash log: https://www.dropbox.com/s/4ztzslfilrjo665/crash-2018-04-24_21.45.04-client.txt?dl=0

**Comment by EpicSquid** [comment]
Can you please give either the download or raw paste of the crash log? This one is almost unreadable

**Comment by Fez-Masta77** [comment]
Here is a dropbox to the crash log txt: https://www.dropbox.com/s/4ztzslfilrjo665/crash-2018-04-24_21.45.04-client.txt?dl=0

**Comment by Fez-Masta77** [comment]
EpicSquid I updated the link

**Comment by Fez-Masta77** [comment]
Update: I disabled optifine and created an new world and the same error occurs. Could it be another mod creating the conflict?

**Comment by Adarcer** [comment]
Same Problem Without Optifine
https://pastebin.com/5UcgdErD
