### ISSUE TITLE
Unnecessary recipe book button conflict with Crafting Tweaks

### ISSUE THREAD

**Issue by blay09** [SleepyTrousers/EnderIO#4588]
#### Issue Description:

When playing with Ender IO, Crafting Tweaks and JEI installed, the recipe book button can not be detected by Crafting Tweaks, causing Crafting Tweaks' "hide recipe book" option to no longer work and the button to overlap with Crafting Tweaks' own buttons.

![](https://user-images.githubusercontent.com/4738934/39056420-87c254de-44ae-11e8-8a2d-58b9a6f0a97a.png)

#### What happens:

Ender IO takes the recipe book button and wraps it in a custom class with a different id making it impossible for other mods to find the button without specifically special-casing Ender IO. As a result, Crafting Tweaks is unable to either move the button out of the way, or hide the button (depending on the user config).

https://github.com/SleepyTrousers/EnderIO/blob/be323475483d6ace21ec450a86154b9d96e3de69/enderio-base/src/main/java/crazypants/enderio/base/handler/RecipeButtonHandler.java

https://github.com/blay09/CraftingTweaks/blob/1.12/src/main/java/net/blay09/mods/craftingtweaks/CraftingGuideButtonFixer.java

#### What you expected to happen:

Ender IO could listen to the ActionPerformed.Pre event instead of (unnecessarily?) wrapping the original button in its own class. Alternatively, it should probably use EventPriority to try and run its InitGui event handler last.

#### Steps to reproduce:

1. Place a Vanilla crafting table.
2. Open the crafting table to see Crafting Tweaks no longer being able to react to the recipe button as it should.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.22
- EnderCore: 0.5.20
- Crafting Tweaks: 8.1.8
- Just Enough Items: 4.9.1.168
- Minecraft: 1.12.2
- Forge: 14.23.3.2673

#### Your most recent log file where the issue was present: 
N/A

https://github.com/blay09/CraftingTweaks/issues/116
https://github.com/blay09/CraftingTweaks/issues/117

**Comment by HenryLoenwind** [comment]
Seen this?

```
(PersonalConfig.recipeButtonDisableAlways.get()
        || ((PersonalConfig.recipeButtonReplaceWithJei.get() || PersonalConfig.recipeButtonDisableWithJei.get())
```

**Comment by blay09** [comment]
Yes, but a config option is not a good solution to a compatibility issue, especially when most people won't even know where to find it (Ender IO isn't the kind of mod you would expect to alter Vanilla crafting tables, which is why it was initially difficult to even track this issue down).

**Comment by EpicSquid** [comment]
If a config option isn't a good solution, then how come is fine for crafting tweaks to use a config option? Also, it's much better for us to give the option then hard code support for every slight mod conflict out there

**Comment by blay09** [comment]
You got it the exact wrong way around though. You don't need hard code support for a specific mod, you just need to apply the fix I've mentioned in my first post that would preserve compatibility with any other mod trying to find the recipe book button. I am the one who would require hard coded support for Ender IO, which is completely unnecessary in this case for the reasons I have already outlined above.

Crafting Tweaks doesn't use a config option trying to avoid mod conflicts because it doesn't have this issue to begin with. It doesn't effectively wrap and hide the button from other mods. This is an issue in Ender IO's implementation of the RecipeButtonHandler regardless of which other mod is affected.
