### ISSUE TITLE
Grains of Infinity server impact?

### ISSUE THREAD

**Issue by ouroborus** [SleepyTrousers/EnderIO#4589]
How server friendly is the Grains of Infinity process?

My current setup involves placing/removing liquid pyrotheum (sets blocks around it on fire) and vacuuming up the grains. So that's a combination of flowing liquids, fire, and vacuum mechanics.

**Comment by EpicSquid** [comment]
Pyrotheum is from another mod, and doesn't need to be placed and replaced to cause fire. Also the performance is simply the same as having a fire.

**Comment by tterrag1098** [comment]
As @EpicSquid said, there is minimal impact beyond that of a normal fire being lit/extinguished.
