### ISSUE TITLE
Facades cannot be placed against adjacent blocks

### ISSUE THREAD

**Issue by Astewen** [SleepyTrousers/EnderIO#4590]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Conduit facades cannot be placed over existing conduits via right-click. It just ignores the right click.

#### What you expected to happen:
Conduit facade should be placed in the specified location hiding that portion of the conduit.

#### Steps to reproduce:

1. Place a conduit
2. Right click a facade to try to hide that block's portion of the conduit.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.22
- EnderCore: 1.12.2-0.5.20
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2673

#### Your most recent log file where the issue was present: 
None.

Mods loaded:

EnderCore-1.12.2-0.5.20
EnderIO-1.12.2-5.0.22
hud-1.3.9-1.12
InventoryTweaks-1.63
jei_1.12.2-4.8.5.159
journeymap-1.12.2-5.5.2
LLOverlayReloaded-1.1.4-mc1.12
LunatriusCore-1.12.2-1.2.0.42-universal
MCMultiPart-2.5.0
MoreCommands-1.12.2-6.0
MouseTweaks-2.8-mc1.12.1
QuickLeafDecay-MC1.12.1-1.2.4
VeinMiner-1.12-0.38.2.647+b31535a
WailaHarvestability-mc1.12-1.1.12
Wawla-1.12.2-2.5.246

[pastebin/gist/etc link here]

Example: cannot place a facade to cover the turn in this image (or any conduits for that matter):
https://pasteboard.co/Hiq4ZIH.png

**Comment by tyler489** [comment]
Conduit facades must be painted before they can be placed

**Comment by Astewen** [comment]
I found out what my problem was... silly me. I was clicking a block that I wanted the facade to be placed next to, like when you place stairs. Now I see that I need to click the conduit NODE that will be wrapped by the facade. Not a bug after all, just me forgetting how to use Endio IO!

**Comment by EpicSquid** [comment]
No worries

**Comment by HenryLoenwind** [comment]
The code for this is still there, but it seems to not work...
