### ISSUE TITLE
Ender IO Crafter is not available to be crafted and does not appear in JEI

### ISSUE THREAD

**Issue by Ishapza** [SleepyTrousers/EnderIO#4591]
#### Issue Description:
I am not playing a mod pack, but am using actually additions and extra utills.

#### What happens:
I can see the painted version of the crafter in JEI, but cannot craft it or see the the "real"version.
I downloaded the latest versions of all three and the issue persists.

#### What you expected to happen:
To craft it

#### Steps to reproduce:

1.load all three mods and see what's what.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by EpicSquid** [comment]
Since you did not include the version you are using I cannot tell you much, however if you are using 1.12 the crafter is not yet implemented. Closing due to a lack of information

**Comment by Ishapza** [comment]
Sorry, but I thought stating "latest versions" would be enough to imply
1.12.2

**Comment by EpicSquid** [comment]
It asks you not to use latest and by default says mc 1.7.10. Please include more details in future

**Comment by AnrDaemon** [comment]
"Latest" is not a version number.
