### ISSUE TITLE
EnderIO Energy Conduit do not connect to Drconic Crafting-Injektor

### ISSUE THREAD

**Issue by florian262000** [SleepyTrousers/EnderIO#4592]
#### Issue Description:
The EnderIO Conduit do not connect to the Draconic Crafting-Injektor. 
The Item-Conduit connect problemless to the Injector.

#### What happens:
The Fusin-Crafting get impossible

#### What you expected to happen:
Maybe, you will fix the Bug?!

#### Steps to reproduce:

1. place an Crafting-Injector 
2. try to connect an EnderIO Conduit to a Crafting-Injector
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.20
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 8.0.99.99

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
not needed

**Comment by tterrag1098** [comment]
This is a bug with DE, they do not support Forge Energy, which is the API that EnderIO uses.
