### ISSUE TITLE
One of the debug options in the config file is true by default instead of false

### ISSUE THREAD

**Issue by maestroke** [SleepyTrousers/EnderIO#4593]
[as seen here](https://www.reddit.com/r/feedthebeast/comments/8fl6q7/i_found_this_in_112_enderios_config_file/)

**Comment by tterrag1098** [comment]
The config option is intentionally true by default, the comment however is misleading.

**Comment by Soulflare3** [comment]
Could be changed to something like "DO NOT change" or "DO NOT modify" to avoid the confusion, and it would work for all of the settings
