### ISSUE TITLE
Redstone Conduit crashes the world

### ISSUE THREAD

**Issue by NimbusFox** [SleepyTrousers/EnderIO#4594]
#### Issue Description:
The server crashes when you place down a redstone conduit and the world becomes impossible to launch once the conduit is place

#### What happens:
After placing a redstone conduit down the game/server crashes

#### What you expected to happen:
Being able to place a conduit behind a power monitor and be able to read a redstone signal from a block

#### Steps to reproduce:

1. Place down a power monitor
2. Place a redstone conduit behind it

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.22
- EnderCore: 5.20
- Minecraft: 1.12.2
- Forge: 14.23.3.2655

#### Your most recent log file where the issue was present: 

https://gist.github.com/NimbusFox/4caaebebb5f91b6afbfb2182b8c6d3d7

**Comment by tterrag1098** [comment]
Some other mod is shipping an old version of our API, probably mcjtylib/rftools. Try updating those mods.
