### ISSUE TITLE
Dedicated server Crash and wont start after placeing conduits

### ISSUE THREAD

**Issue by spocane** [SleepyTrousers/EnderIO#4595]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

Dedicated server Crash and wont start after placing  ender liquid conduits and redstone conduits together

#### What you expected to happen:

not break the game

#### Steps to reproduce:

1.Placed Liquid + redstone conduits going from Tinkers Smeltery to casting basins
3. Disconnect parts of conduit to control better
3. Restart server to update mods
4. sever crashes on boot
5. remove affected conduits with MCEDIT
6. Server boots and functions fine
7. get screenshot in testworld of same setup
8. Games crashes same crashlog
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.22 
- EnderCore: 1.12.2-0.5.20
- Minecraft: 1.12.2
- Forge: 14.23.3.2673

#### Your most recent log file where the issue was present: 
Server
[https://paste.ee/p/bEsN8](https://paste.ee/p/bEsN8)
Single player
[https://paste.ee/p/RmNqY](https://paste.ee/p/RmNqY)
Example
[https://imgur.com/a/8r6zorV](https://imgur.com/a/8r6zorV)

**Comment by EpicSquid** [comment]
Fixed in dev
