### ISSUE TITLE
EnderIO incompatibility issues with Liteloader

### ISSUE THREAD

**Issue by Brisingr17** [SleepyTrousers/EnderIO#4596]
#### Issue Description:
After adding the 1.12.2 version of EnderIO, it seems to have some kind of incompatibility issue with Liteloader.

*Note Optifine was installed but it was also tested without it and still generated the same problem thus eliminating Optifine from being associated*

#### What happens:
This conflict causing the game to immediately crash upon finishing loading.

#### What you expected to happen:
Not cause some weird conflict with liteloader

#### Steps to reproduce:

1. Add EnderIO 1.12.2
2. Add Liteloader 1.12.2
3. Start and load the game
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.22
- EnderCore: 1.12.2-0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.2.2627

#### Your most recent log file where the issue was present: 

https://pastebin.com/pfaHsQqb

**Comment by AnrDaemon** [comment]
Why are you reporting MalisisCore crash to EnderIO ?

**Comment by EpicSquid** [comment]
This crash has nothing to do with enderio. Please post it to the relevant mod
