### ISSUE TITLE
java.lang.RuntimeException: ModObject:create: Could not create instance for class crazypants.enderio.machines.machine.teleport.telepad.BlockTelePad using method create_telepad

### ISSUE THREAD

**Issue by Boundarybreaker** [SleepyTrousers/EnderIO#4598]
Forge 14.23.3.2655, EIO 5.0.22

Inside a dev environment, crashing during launch

[crash-2018-05-01_00.38.50-client.txt](https://github.com/SleepyTrousers/EnderIO/files/1963233/crash-2018-05-01_00.38.50-client.txt)

**Comment by EpicSquid** [comment]
Can you please provide more context? Are you setting up your own enderio dev environment? Or are you trying to include enderio in your dev environment?

**Comment by Boundarybreaker** [comment]
Include it in a dev environment right now, just adding them to the /mods folder of the run instance.

**Comment by HenryLoenwind** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/4852

https://github.com/SleepyTrousers/EnderIO/issues/4527
