### ISSUE TITLE
Include ComputerCraft Networking Cable

### ISSUE THREAD

**Issue by angelnc1989** [SleepyTrousers/EnderIO#46]
I'm building my new base right now where I try to hide all cables and make everything as compact as possible. There I just realised, that there is no way to facade Networking Cables from ComputerCraft. So it would be really cool to have them added to this mod.

**Comment by beringtom** [comment]
I'm bumping this just because the CC cables does not support Forge MultiParts right now.

**Comment by MatthiasMann** [comment]
CC cables are very unlikely - but OC cables are on the road map.

**Comment by Vexatos** [comment]
Duplicate of #2288, #725.

**Comment by Vexatos** [comment]
It is virtually impossible to do anything with CC cables at all as there is no real way of properly accessing them, unfortunately.
