### ISSUE TITLE
Farming Station and Natura Cotton/Barley causes server crash [1.12.2]

### ISSUE THREAD

**Issue by lays24mc** [SleepyTrousers/EnderIO#4600]
#### Issue Description:

Server crashes when Farming Station harvests Natura Cotton and Barley seeds,

#### What happens:

The server will crash when the Farming Station tries to harvest a Natura cotton seed!

#### Steps to reproduce:

1. Create a farm of Natura cotton/barley seeds
2. Place a farming station with power
3. Input a diamond hoe
4. Wait of harvesting

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.22
- EnderCore: 1.12.2-0.5.20
- Minecraft: 1.12.2
- Forge: forge-14.23.3.2655

#### Your most recent log file where the issue was present: 

https://pastebin.com/n53wQnmb

**Comment by HenryLoenwind** [comment]
That "noppes.npcs" crashing, not us.
