### ISSUE TITLE
Alloy Smelter voiding items

### ISSUE THREAD

**Issue by Kimochii-x3** [SleepyTrousers/EnderIO#4601]
_This is the first ever bug/issue report I do, I have no idea is it ok as it is or not, this bug to happen also needs Aroma's mining dimension and I have no idea does it happen with the vanilla nether portal._
#### What happens:
Some sort of voiding of the (as discovered only) glass minecraft item being smelted into clear glass when I let the glass manually to smelt into clear glass and then jump into Aroma's mining dimension portal the glass seems to void and disappear from the alloy smelter

#### What you expected to happen:
Its expected that the glass continues to smelt while the chunk is loaded with chicken chunks's chunk loader

#### Steps to reproduce:

1. Have powered alloy smelter and aroma's portal close to it
2. Leave glass to be smelted in it and jump straight in the mining dimension

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.22
- EnderCore: 0.5.20
- Minecraft: 1.12.2
- Forge: 14.23.3.2655

#### Your most recent log file where the issue was present: 

Since pastebin has a limit, I archived the log file, look around times 1pm to 3pm or so around that time the voiding happened
https://cdn.discordapp.com/attachments/405181071160901649/441659405356761113/03-05-2018.rar

**Comment by tyler489** [comment]
Chunk unloading not saving the furnace "processing" prehaps?

**Comment by EpicSquid** [comment]
Cannot replicate this, please check your pack config
