### ISSUE TITLE
Aversion Obelisk disabled all spawn

### ISSUE THREAD

**Issue by MinoCraft** [SleepyTrousers/EnderIO#4602]
Hello, 

Minecraft version: 1.12.2
Forge version: 14.23.3.2675
Mods version: Ender Core 1.12.2-0.5.18
                       Ender IO  1.12.2-5.0.22

Aversion obelisk disabled completly vanilla spawners when you set a mob with soul vial.
I've seen that with my blaze farm and wither skeleton won't spawn on Curth Earth when it set in obelisk.
It's a bug or it's the new working methode ?

Thanks in advance !

**Comment by HenryLoenwind** [comment]
I have no idea what you are trying to tell us.

Also, that template for you to fill out wasn't there because we were bored.
