### ISSUE TITLE
how to turn off machine background that looks like bedrock

### ISSUE THREAD

**Issue by Goozen** [SleepyTrousers/EnderIO#4605]
How do i turn off the machine background it makes me lag when opening the machine interface

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
The form is there for a reason. Do you mean the power bar? You can change it with a resource pack but that isnt causing lag.

**Comment by EpicSquid** [comment]
Closing due to complete lack of any useful information
