### ISSUE TITLE
Tinker's Construct Direct modifier doesn't work with part replacement

### ISSUE THREAD

**Issue by hacatu** [SleepyTrousers/EnderIO#4608]
#### Issue Description:
Ender IO introduces a tinker's Construct material for vibrant alloy, and the direct tinker's construct attribute.  Tools with vibrant alloy handle or extra parts get direct, but it can also be added as a modifier using a vibrant alloy large plate.  Unfortunately, tools with large plates as a part, such as hammers, can't have this modifier applied because the large plate in the tool will get replaced instead.

#### What happens:
Replacing the existing large plate in a tool takes precedence over applying the direct modifier so tools with large plates can't get it.

#### What you expected to happen:
Applying the direct modifier should take precedence, or the recipe shouldn't conflict.

#### Steps to reproduce:

1. Have tinker's Construct 2.9.1.65 and ender IO 5.0.22 installed for Minecraft 1.12.2
2. Get any hammer that's not vibrant from the creative menu
3. Put it in a tool forge with a vibrant large plate

____
#### Affected Versions:

- EnderIO: 5.0.22
- EnderCore: 0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.3.2677

**Comment by EpicSquid** [comment]
As far as I am aware this is not an issue on our end, but rather with the way swapping parts works with tinkers.

**Comment by InjuredWolf** [comment]
Tinkers used to have this problem with Iguana Tinkers Tweaks' tool swapping when using the obsidian plate for the reinforced modifier. Perhaps a similar item might help?
