### ISSUE TITLE
OreDictionary Preferences

### ISSUE THREAD

**Issue by belathus** [SleepyTrousers/EnderIO#4611]
#### Issue Description:
In previous versions of EnderIO, we had an oredictionary preferences xml file ([like this one](https://github.com/belathus/Wanderlust-Renewed/blob/1.10.2/config/enderio/OreDictionaryPreferences_User.xml)). I cannot find a similar file in the current version of EnderIO. For some reason, EIO has defaulted to the ugliest dusts we have in the pack, and I'd love to fix this.

#### What happens:
Sagmill gives me libvulpes dusts.

#### What you expected to happen:
I'd just like to have the ability to change what dust that EIO machines give.

#### Steps to reproduce:
N/A

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.22
- EnderCore: 0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.3.2655

#### Your most recent log file where the issue was present: 
N/A

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by tyler489** [comment]
Just for reference enderio defaults to the first entry for that oredict.
