### ISSUE TITLE
crash on startup 1.12.2

### ISSUE THREAD

**Issue by KiraLinux** [SleepyTrousers/EnderIO#4614]
#### Issue Description:
I'm more than sure if there is no thaumcraft then crash solely because of this

#### Steps to reproduce:
I run the game and it loads a little and then it closes itself

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO-base-1.12.2-5.0.377-nightly
- EnderIO-conduits-1.12.2-5.0.377-nightly
- EnderIO-integration-forestry-1.12.2-5.0.377-nightly
- EnderIO-integration-tic-1.12.2-5.0.377-nightly
- EnderIO-machines-1.12.2-5.0.377-nightly
- EnderCore-1.12.2-0.5.24
- Minecraft: 1.12.2
- 1.12.2-forge1.12.2-14.23.3.2677

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
crash report 
https://pastebin.com/stqdC9D7
recent log
https://pastebin.com/nw57T6SM

**Comment by tterrag1098** [comment]
Fixed in 378, which was built before you made this issue...

**Comment by KiraLinux** [comment]
Thank you so much for the fix!
