### ISSUE TITLE
[1.12.2] Server Crash Ticking Player due to tinkers intergration issue

### ISSUE THREAD

**Issue by Morpheus1101** [SleepyTrousers/EnderIO#4619]
Crash log @ https://gist.github.com/Morpheus1101/c9521b4c7b608f59e2c7048b53f9792f

Forge v *.3.2678
EIO v 5.0.24
E.Core v0.5.22

**Comment by EpicSquid** [comment]
We have a format for issues for a reason. Please use it. I have no idea what you were doing to cause this.

**Comment by Morpheus1101** [comment]
It occured whilst i was away and told about the server crashing, so the only information i know is th euser had a trait on a Pickaxe and when mining the above mentioned crash occured, the user isnt around currently to ask any further information.

**Comment by HenryLoenwind** [comment]
That's the fault of the block that is being broken, it is implementing Block.getDrops() wrongly.

**Comment by Morpheus1101** [comment]
ok, i will replicate the pick in my dev testing world and figure out which mod is causing it.  thanks for 
 the information.
