### ISSUE TITLE
Shift-clicking a speed upgrade into a fluid conduit makes the item disappear.

### ISSUE THREAD

**Issue by xxMattewxx** [SleepyTrousers/EnderIO#4621]
#### What happens:
Shift-clicking an extract speed upgrade in a fluid conduit makes the speed upgrades disappear from the inventory and not show up in the fluid conduit.

#### What you expected to happen:
Either disallow the player's shift-clicking into a fluid conduit or the upgrade working in the conduit.

#### Steps to reproduce:

1. Place down a fluid conduit
2. Shift-click an extract speed upgrade
3. ???
4. Profit
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.22
- EnderCore: 0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.3.2676

**Comment by EpicSquid** [comment]
Fixed in latest dev build
