### ISSUE TITLE
Maximum Energy Calculation with Enderio Capacitor Banks and Xnet

### ISSUE THREAD

**Issue by FallenEagle1** [SleepyTrousers/EnderIO#4622]
Issue description: This seems to be a slight inconvenience for using Ender IO capacitor banks and the max/min for when to stop rf transfer. The number that is put into the controller is multiplied by the number of capacitor banks that are connected. So it a capacitor bank is meant to be capped at 1000 rf and there are 5 capacitor banks connected, the rf stored is capped at 5000 rf. This happens with all tiers of capacitor banks.

From what was mentioned by McJty, this was an issue here as his mods were using info from the API. This is from McJty/XNet#268

![2018-05-08_23 35 59](https://user-images.githubusercontent.com/22630113/39797319-a810f222-5318-11e8-9e05-e7f09b0d809b.png)
![2018-05-08_23 36 07](https://user-images.githubusercontent.com/22630113/39797320-a82ced56-5318-11e8-85c2-295f4c9f5e27.png)

Tested powercells from both RFTools and RFToolsPower just to double check other similar multiblocks and they don't have this issue.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2679
* McJtyLib: 2.6.7
* XNet: 1.6.9
* Enderio: 5.0.24

**Comment by tyler489** [comment]
#4571 might be related

**Comment by EpicSquid** [comment]
I will, we also need to re add our large based power storage api so other mods can read the cap bank properly.
