### ISSUE TITLE
Simple autocrafter not working as intended (checked with EpicSquid on discord)

### ISSUE THREAD

**Issue by xerrio** [SleepyTrousers/EnderIO#4627]
#### Issue Description:
Bug checked with EpicSquid and he can replicate it. 17h30 today in the #general channel on discord.
The simple crafter doesn't work correctly and output the ingredients instead of crafting the desired item. Further more, you get and extra "minecraft:spawn_egg" item sometimes randomly.

#### What you expected to happen:
I would like to get my crafter to craft! damnit :p

#### Steps to reproduce:
1. Placing a simple autocrafter next to a simple generator.
2. Placing a chest over the autocrafter
3. Turning the top face of the autocrafter to pull items from the chest to the autocrafter.
4. I added the simple chassis recipe on the left (like normally) annnd....
5. Happy wtf! The autocrafter will output the materials from the recipe and some "minecraft:spawn_egg" 💃 

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.24
- EnderCore: 0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.2.2653

#### Pictures: 
https://imgur.com/a/53y9oKf

**Comment by VT-14** [comment]
I also came across this issue in hourly build 386.  It also happens with the normal Crafter.

In addition, the stock single items/stacks button doesn't seem to work on the normal Crafter.

**Comment by eliandarkbrood** [comment]
I have the same thing except for some reason it completely deleted the crafting recipe... Well more like changed the result to air. I was just having them make wooden axes for a tree farm and it did it for both the wood to planks and planks to sticks. Checked in JEI, and the recipes changed and couldn't even craft by hand after that. Didn't do it all the time, but happened a few times for both. Reloading client fixes, but it happens again after a while. Couldn't track it through the logs nor could pinpoint any specific point at which it changed... Sorry that I cant help there.
