### ISSUE TITLE
Request Yeta Wrench Config change no longer sneak and scroll but right click and sneak

### ISSUE THREAD

**Issue by Mementh** [SleepyTrousers/EnderIO#4630]
when your using the yeta wrench its a bit annoying if your building and using the scroll wheel on the mouse and sneaking so you don't fall off and it gets stuck int he yeta config.

why not change it so the trigger to config is sneak and right click. something that wont happen accidentally

**Comment by EpicSquid** [comment]
Please put in suggestion tracker, github is for bugs

**Comment by tyler489** [comment]
http://ideas.theideawall.com/EnderIO
