### ISSUE TITLE
Magic Capacitors super common in Desert Temples

### ISSUE THREAD

**Issue by belathus** [SleepyTrousers/EnderIO#4631]
#### Issue Description:
Exploring a desert near my base, I was finding a large number of desert temples. After a few of them, I noted that I had a chest full of magic capacitors, and I wondered why. So I found this line in the LootManager: https://github.com/SleepyTrousers/EnderIO/blob/release/1.12.2/enderio-base/src/main/java/crazypants/enderio/base/loot/LootManager.java#L129

I'm pretty sure that should be 0.25F, and not 25.

#### What happens:
Lots of magic capacitors in the desert temples.

#### What you expected to happen:
Less?

#### Steps to reproduce:
Explore deserts. Notice the amount of loot capacitors you get from the pyramids.

#### Affected Versions (Do *not* use "latest"):
None of this really matters for this particular issue, does it?
- EnderIO: 5.0.24
- EnderCore: 0.5.22
- Minecraft: 1.12,2, but it looks like it affected previous versions.
- Forge: 14.23.3.2655

#### Your most recent log file where the issue was present: 
N/A

**Comment by EpicSquid** [comment]
Nice find, thanks!

**Comment by FlyingThunder** [comment]
Sorry, is this fixed in 1.12.2 aswell? Im using the twitch launcher with EnderIO 1.12.2 5.0.40 and the damn things are EVERYWHERE - i got around 20 from 4 chests from a pyramid!!

**Comment by HenryLoenwind** [comment]
0-3 per desert temple chest: https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-base/src/main/resources/assets/enderio/loot_tables/chests/desert_pyramid.json#L85
