### ISSUE TITLE
[1.7.10] Enchantment Withering I not aquireable through the EIO-Enchanter

### ISSUE THREAD

**Issue by chaos234** [SleepyTrousers/EnderIO#4633]
Referencing to issue #1704 it was stated that this error was resolved but it seems not to be resolved because of this log output:

```
[20:11:36] [Client thread/WARN] [EnderIO]: Could not find enchantment with name enchantment.enderzoo.witherArrow when parsing enchanter recipes.
[20:11:36] [Client thread/WARN] [EnderIO]: Could not find enchantment with name enchantment.enderzoo.witherWeapon when parsing enchanter recipes.
[20:11:36] [Client thread/WARN] [EnderIO]: Could not find enchantment with name enchantment.enderzoo.witherWeapon when parsing enchanter recipes.
[20:11:36] [Client thread/WARN] [EnderIO]: Could not find enchantment with name enchantment.soul_stealer when parsing enchanter recipes.
[20:11:36] [Client thread/WARN] [EnderIO]: Could not find enchantment with name enchantment.enderzoo.witherWeapon when parsing enchanter recipes.
[20:11:36] [Client thread/WARN] [EnderIO]: Could not find enchantment with name enchantment.enderzoo.witherWeapon when parsing enchanter recipes.
```

EnderIO and EnderZoo are the latest released Versions for 1.7.10
In addition, there is smth. wrong in EnchanterRecipes_Core.xml. It states that the wither poitins have metaID of 8203 (correct) and 8235 (false) which I corrected to 8267. I am not sure if this is maybe caused of one of our mods in the hole pack but even this change added into EnchanterRecipes_User.xml did not resolved the problem.

I then triggered a client crash while I have given the same ID to two enchantments and this is the report to it (includes the full mod list):

[crash-2018-05-14_19.57.02-client.txt](https://github.com/SleepyTrousers/EnderIO/files/2002054/crash-2018-05-14_19.57.02-client.txt)

Could it be that the entries in the XMLs are false since the crasreport states "class crazypants.enderzoo.enchantment.EnchantmentWitherArrow" which would then mean that the set name in both XML files are wrong?

Also I think that the enchantment "Soul Stealer" could be the Reaper Enchantment from Draconic Evolution but this isn't a problem since it was aquired already over the vanilla enchanter but not the Wither-Enchantment (even after uncountable tries in creative -.-#)

Would be nice to get little help here what is going wrong at this point if time is there for it to (re)solve this problem.

Edit: To be fair, here are the Versions to all used mods with name "Ender" in it:

```
EnderCore-1.7.10-0.2.0.39_beta
  EnderIO-1.7.10-2.3.0.429_beta
  EnderStorage-1.7.10-1.4.7.37-universal
  EnderTech-1.7.10-0.3.2.405
  EnderZoo-1.7.10-1.0.15.32
```

In addition I think smth. goes wrong with the enchantments, since they are currently set to 9, 10 and 11 (EIO Soulbound) but AntiIDConflict don't recognizes them. Maybe due to missing implementation but maybe smth. is going wrong since other enchantments are found.

AllIDs.txt:

[AllIDs.txt](https://github.com/SleepyTrousers/EnderIO/files/2002107/AllIDs.txt)

Maybe this could help too

**Comment by tyler489** [comment]
"soul stealer" do you have a soul shards mod?

**Comment by chaos234** [comment]
Hey  tyler489,

no, we have no soul shard specific mod in our pack. If we have from our current mods any kinds of soul shards is unknown for now, but I'll check NEI when I am back at home in a few hours.

**Comment by chaos234** [comment]
![2018-05-15_21 15 17](https://user-images.githubusercontent.com/340106/40078526-2404180c-5885-11e8-9faf-cd54f24d1f19.png)
 This is the only Soul Shard in our pack
