### ISSUE TITLE
Suggestion:  Increase the output capacity of the reservoir based off the count of blocks in the structure 

### ISSUE THREAD

**Issue by mahldcat** [SleepyTrousers/EnderIO#4635]
#### Issue Description:
Was watching several LP videos that used the reservoir as a water source, and the amount of water it produced was not able to keep up with the demand.  

As a suggestion, would it be possible to increase the "internal storage" of this block along with the total output capacity if this structure used more than 4 reservoirs in the structure?

#### What happens:
The reservoir in many cases would seem to empty, and then refill.  This fluctuation would then cause a "ripple" effect in other systems.

#### What you expected to happen:
What if instead of the 4 blocks to build this structure, this used a similar mechanic to the capacitor blocks:  the more blocks in the structure the more it can store, and the more it can store/output per tick.

**Comment by tterrag1098** [comment]
Hello, thank you for the suggestion. However, we want the list of open issues to reflect bugs in the mod. For suggestions, please use http://ideas.theideawall.com/EnderIO/

**Comment by mahldcat** [comment]
Side note:  I submitted this after clicking on the "bugs/issues/suggestions" button on the main enderio website: http://www.enderio.com/  which takes you to this issue board.  Might be worth updating this to include the new suggestion link.

**Comment by HenryLoenwind** [comment]
Why suggest stuff that already is that way? For every reservoir block after the first two you get 1B/s...
