### ISSUE TITLE
Capacitor bank fails outputting to another capacitor bank.

### ISSUE THREAD

**Issue by xxMattewxx** [SleepyTrousers/EnderIO#4636]
#### Issue Description:
When I open Minecraft and then open a world, the capacitor banks will sometimes not output unless I break & place them back. (Yes, they are all configured correctly).

#### What happens:
I've connected two arrays of capacitors and connected them together (one array is made of 4 Capacitor Banks, and the other one is made of 6 Basic Capacitor Banks.), so the array of 6 basic capacitors are outputting to an input in the 4 capacitor banks array.

#### What you expected to happen:
Basic capacitor array to output to the capacitor banks, as they are setup in that way.

#### Steps to reproduce:
Not sure how to reproduce it yet. I'm going to test in a creative world and post results soon tho.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.22
- EnderCore: 0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.3.2676

**Comment by EpicSquid** [comment]
Please also update to the latest ender IO version, that way we can rule out that issue as well.

**Comment by xxMattewxx** [comment]
Hey! Thanks for the quick reply. I've tried the latest (5.0.24, which is available in CurseForge - I don't know if there's any other version?) and the bug is still happening.

I've found a reliable way to reproduce that (atleast for me):
1. Grab two of each capacitor bank and a generator of choice. So 2 Capacitor Banks and 2 Basic Capacitor Banks.
2. Place down a basic capacitor and set one of its side to output. Connect the generator to that capacitor - A small generator btw, nothing that would fill the capacitor quickly -
3. Place down a normal capacitor and make it so its input side is the side receiving energy from the basic capacitor you've placed in step 2.
4. Add the other basic capacitor bank in the top of that basic capacitor bank you've placed.
5. Do the same as step 4, however using now the normal capacitor bank.
6. The normal capacitor array should've already stopped receiving energy. If not, restarting the game causes this to happen.

**Comment by xxMattewxx** [comment]
If you didn't understand part of the instructions or wasn't able to reproduce, please reply and I will try explaining better (I'm not a native English speaker).. Thx!

**Comment by HenryLoenwind** [comment]
with step 4 and 5 you created a loop---two capBanks that push energy into each other.

**Comment by xxMattewxx** [comment]
Well, that should be the problem I've been having then!
But having only the bottom side marked as output would mean the capacitor would only output through there, no?
I mean like that: (think of O as output, N as none and I as input)
N - N
O - I
Wouldn't that be telling the game that the first capacitor (in the left) should output the energy to the second capacitor? Because if that is correct, the loop shouldn't exist. There are no outputs in the second capacitor.

**Comment by EpicSquid** [comment]
Just confirmed this, the top 2 capbanks are sharing power between each other. This is intended and therefore not an issue.
