### ISSUE TITLE
Visual Glitch with Industrial Foregoing Machinery

### ISSUE THREAD

**Issue by rbandboy** [SleepyTrousers/EnderIO#4637]
#### Issue Description:
Visual Glitch with Industrial Foregoing Machinery

![2018-05-13_21 45 05](https://user-images.githubusercontent.com/4001839/40029174-4bd936ea-57a0-11e8-98c5-add5b92f7775.png)

Working with Futurepack's testpack server, "Futurepack Lives" (redsnake-games.de via teamspeak), version 1.0.10

#### What happens:
Rendering fails after disabling the machine (via its internal configuration, which disables its fluid inputs) then re-enabling.  The issue resolved itself after a bit, 

#### Steps to reproduce:

1.Disable Industrial Foregoing's Spore Recreator
2.Make sure the fluiduct has water inside
3.Enable the Spore Reactor
4.Scratch head as visual glitch occurs
5.Shrug after the visual glitch resolves itself.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.24
- EnderCore: 0.5.22

- Minecraft: 1.12.2
- Forge: 14.23.3.2678

Industrial Foregoing Version: 1.9.0-163
TeslaCoreLib Version: 1.0.14

#### Your most recent log file where the issue was present: 
No log generated, as no crash occurred.

**Comment by rbandboy** [comment]
[#329](https://github.com/Buuz135/Industrial-Foregoing/issues/329)

**Comment by HenryLoenwind** [comment]
Looks like the machine was not forcing the chunk to re-render when it changed its configuration.
