### ISSUE TITLE
Lag opening Simple Stirling Generator from EnderIO

### ISSUE THREAD

**Issue by DiamondGallery** [SleepyTrousers/EnderIO#4638]
#### Issue Description:

Computer/Game-stalling lag when opening simple stirling generator each time.

#### What happens:

3-4 second lag upon each attempt to open Simple Stirling Generator. Seems like game is going to crash but has always recovered so far.

#### What you expected to happen:

Expect to have no lag when opening a machine such as a Simple Stirling Generator.

#### Steps to reproduce:

1. Download all the mods 3 via twitch launcher. Run everything latest version, increase RAM slightly at first.
2. Once atm3 loaded, create default new survival SP world.
3. Acquire enough resources to build Simple Stirling Generator. Place it down, everytime its opened computer/game waits 3-4 seconds before responding.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.24
- EnderCore: 1.12.2-0.5.22
- Minecraft: Not sure but I think 1.12
- Forge: 14.23.3.2678

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by xxMattewxx** [comment]
I can't reproduce that. What are your computer specs? That may be causing the lag you mentioned (ATM3 is quite expensive to run in a few machines.)
Also, did you test if the other mods also cause this lag?
Good luck!

**Comment by EpicSquid** [comment]
Known issue, and is reproducible in large packs. Working on a solution

**Comment by DiamondGallery** [comment]
Thanks much for the replies! I thought it potentially had something to do with being in a large pack. My computer does get a bit stressed at times running All The Mods 3. I've tweaked my RAM allocation around a bit but will continue to report anything I find as I'm going to be playing around with it more.


My specs
i7-4790k @3.99GHz
16GB RAM DDR3
GTX970
ASUS Maximus Hero 6 Mobo
EVGA 850 G2 PSU

**Comment by EpicSquid** [comment]
@DiamondGallery can you try this again with the new release?

**Comment by EpicSquid** [comment]
Did it take longer from the second attempt onwards with the simple stirling generator? (In one session that is)

**Comment by DiamondGallery** [comment]
Each attempt after the first wasn't noticeably longer than the first, from what I can tell. There did seem to be an average amount of 3-4 seconds on each attempt. However, if there was some added delay on each sequential attempt past the first that does seem possible it could have been happening, however wasn't noticeable enough for me to conclude it yet. I will check on that again though when I get back to that world tonight and let you know.

**Comment by EpicSquid** [comment]
Good to know, we are caching fuels now so what you have had happen should happen. I will call this a success for now.
