### ISSUE TITLE
ender IO refined storage conduits requires a newer version than is publicly available.

### ISSUE THREAD

**Issue by border999** [SleepyTrousers/EnderIO#4644]
- EnderIO: 5.0.427
- EnderCore: 5.29
- Minecraft: 1.12.2

https://pastebin.com/HaRL6eLS

**Comment by tterrag1098** [comment]
There is nothing we can do about this, -34 is the only version that exists for dependencies.

**Comment by EpicSquid** [comment]
34 should be available on Cf now
