### ISSUE TITLE
Ender IO crashes on startup

### ISSUE THREAD

**Issue by border999** [SleepyTrousers/EnderIO#4645]
#### Issue Description:
Crash at startup.
#### What happens:
Hit play, loads for a bit, crashes.
#### What you expected to happen:
To load up and let me play my minecraft world.
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-base-1.12.2-5.0.429-nightly
- EnderCore: EnderCore-1.12.2-0.5.29
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.3.2698

#### Your most recent log file where the issue was present: 

https://pastebin.com/bvk0Zupj

**Comment by border999** [comment]
May I ask why you closed this issue?
@HenryLoenwind

**Comment by EpicSquid** [comment]
Inv panel isn't supported yet. Don't use it
