### ISSUE TITLE
Duplication bug with Thaumcraft destructive pickaxe and EnderIO machines

### ISSUE THREAD

**Issue by belathus** [SleepyTrousers/EnderIO#4646]
#### Issue Description:
Breaking a EIO machine that is in the area of effect of a pickaxe with the Destructive property from Thaumcraft will not break the machine, but the machine will drop anyway, resulting in a duplicate. I was not able to duplicate this bug using non-EIO machines, so I suspect it might have something to do with how EIO handles its machines being broken.

I've also reported the issue here: https://github.com/Azanor/thaumcraft-beta/issues/806

Further, @greenking13 made this gif: https://media.giphy.com/media/1NX437Gvox0CZ6oI7i/giphy.gif

#### What happens:
Breaking an EIO machine with a destructive pickaxe indirectly duplicates the machine.

#### What you expected to happen:
The machine drops only one copy of itself.

#### Steps to reproduce:

1. Make pickaxe of the core and place Destructive on it
2. Put an EIO machine next to, say, cobblestone.
3. Break the cobblestone with the machine in the Area of Effect of the destructive pickaxe.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.24
- EnderCore: 0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.3.2961

#### Your most recent log file where the issue was present: 
https://gist.github.com/belathus/0a7e95c1ef7ce0ace24ae1f078a20b92

**Comment by belathus** [comment]
Apparently this also happens with the Break focus, as mentioned here: https://github.com/Azanor/thaumcraft-beta/issues/734

**Comment by xxMattewxx** [comment]
Author of Thaumcraft has said the problem has been solved. https://github.com/Azanor/thaumcraft-beta/issues/734
