### ISSUE TITLE
EnderIO latest dev builds cause TCon to crash with IllegalAccessError, minecraft 1.12.2

### ISSUE THREAD

**Issue by ESTPlayer** [SleepyTrousers/EnderIO#4650]
#### Issue Description:

Using EnderIO latest dev builds, the TinkersConstruct integration is broken, causing TCon to crash on the last stage of loading. This has been confirmed by two people already on TCon's github, but because it is related to EnderIO being at fault, the issue is now opened here as well.

#### What happens:

Using TCon TConstruct-1.12.2-2.10.0.81
EnderCore-1.12.2-0.5.29.jar
EnderIO-1.12.2-5.0.426-nightly.jar - latest build 431 crashes with identical crashlog

#### What you expected to happen:

Not to crash. 

#### Steps to reproduce:

1. Download TConstruct-1.12.2-2.10.0.81 and latest Mantle from curseforge
2. Download EnderIO-1.12.2-5.0.426-nightly.jar or any newer build, with EnderCore-1.12.2-0.5.29.jar
3. Try to launch the game
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.391-nightly.jar and newer- this seems to be the last build which would have worked, because this build changed the TCon integration files.
- EnderCore:EnderCore-1.12.2-0.5.29.jar
- Minecraft: 1.12.2
- Forge:2702

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://paste.ee/p/VOyGx
https://paste.ee/p/ymJKO

The "fix bad method" commit, which should have fixed this crash, still causes it with identical crashlog.

**Comment by HenryLoenwind** [comment]
link-in https://github.com/SlimeKnights/TinkersConstruct/issues/3492
