### ISSUE TITLE
EnderIO combined with AE2 and ThermalExpansion 

### ISSUE THREAD

**Issue by 5pHiNxX** [SleepyTrousers/EnderIO#4651]
#### Issue Description:
EnderIO does not replace all Flour-Items from AppliedEnergistics2. The Pulverizer from ThermalExpansion normally produces AppliedEnergistics2 Flour, but in combination with EnderIO it just produces AppliedEnergistics2 Disabled Item. All other grinders (like SAG-Mill, Grindstone, etc.) produce the EnderIO dustWheat.

#### What happens:
ThermalExpansion's Pulverizer produces AppliedEnergistics Disabled Item.

#### What you expected to happen:
ThermalExpansion's Pulverizer should produce EnderIO's dustWheat.

#### Steps to reproduce:

1. Install AppliedEnergistics2, ThermalExpansion and EnderIO
2. Place a Pulverizer, power it and put Wheat in it.
3. AppliedEnergistics2 Disabled Item is produced
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.21
- EnderCore: 1.12.2-0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.3.2655
- AppliedenErgistics2: rv5-stable-11
- ThermalExpansion: 1.12.2-5.4.2.25-universal

#### Your most recent log file where the issue was present: 

https://pastebin.com/j70dXmY2

**Comment by HenryLoenwind** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3437
