### ISSUE TITLE
Obelisk duplication XP (on server SpongeForge)

### ISSUE THREAD

**Issue by yaroslav4167** [SleepyTrousers/EnderIO#4652]
I managed to do only on the server.

Steps to reproduce:
[https://youtu.be/_uZggOybblk](https://youtu.be/_uZggOybblk)
Look at the level
____
Versions:

- EnderIO: 5.0.24
- EnderCore: 0.5.22
- Minecraft: 1.12.2
- Forge: 2655
- SpongeForge: BETA-3105

**Comment by HenryLoenwind** [comment]
#4572

**Comment by phit** [comment]
@HenryLoenwind this looks like a different issue? and the version @yaroslav4167 is running already includes https://github.com/SleepyTrousers/EnderIO/commit/d576399c63ff0821de1885c039d7778393b37bcb

**Comment by HenryLoenwind** [comment]
d576399 is the commit that added the dupe bug...

**Comment by yaroslav4167** [comment]
Will you fix this?
Or can you add an option to disable the obelisk in the configurations?

**Comment by HenryLoenwind** [comment]
no, I will NOT hop into my time machine and fix this before I fixed it.

**Comment by phit** [comment]
the confusion stems from you calling this a dupe of #4572, which was closed by the commit that caused this?
