### ISSUE TITLE
Crash by EnderIO and RFTOOLS

### ISSUE THREAD

**Issue by IMINTH3R4D** [SleepyTrousers/EnderIO#4653]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

Hello i have error my server every crashed on loading EnderIO and RFTools can you help me.

The error: https://pastebin.com/Cv6LtBtd

Sorry for my bad english i'm french.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.8.9-3.0.0.26_alpha
- EnderCore: EnderCore-1.8.9-0.3.0.14-beta
- Minecraft: 1.8.9
- Forge: forge-1.8.9-11.15.1.2318-1.8.9

**Comment by HenryLoenwind** [comment]
The 1.8.9 was not even half-finished when it was abandoned...
