### ISSUE TITLE
1.12.2 Server crashes when any player trys to login

### ISSUE THREAD

**Issue by TheHeavenOnMoon** [SleepyTrousers/EnderIO#4654]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

We run a minecraft modded 1.12 server that uses the latest release version of EnderIO and EnderCore (and other mods). Last night the server crashed and since then nodbody is able to join the server without getting instant kicked. The server wont output a crash-report but we have console files that are stated below. BTW this is not depending on a specific user!

#### What happens:
The server crashes upon logging into it.

#### What you expected to happen:
The server running normal and not crashing upon logging in.

#### Steps to reproduce:

1. Start server
2. Logging into the server
3. Look in console and see that the server is crashed

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.24.jar
- EnderCore: EnderCore-1.12.2-0.5.22.jar
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2611

#### Your most recent log file where the issue was present: 

https://pastebin.com/qwZ9CwqL
(i know its not really that nice to read but i could not find a different way to present it to u :))

**Comment by HenryLoenwind** [comment]
Your world save is corrupted.

**Comment by TheHeavenOnMoon** [comment]
Ill try to loadup an backup :) thx so far
