### ISSUE TITLE
[Request] Processing (killing) of Soul Vial'ed mobs

### ISSUE THREAD

**Issue by andr9528** [SleepyTrousers/EnderIO#4659]
A Machine that when powered and supplied with soul vials with mobs within, kills the creature as if it had been spawned in to the world and slain by any other means of killing. Could also have different toggle able settings to allow for player only drops, experience and adding looting effect somehow, all theses effect would make it use more energy or time of course

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by andr9528** [comment]
Ok i will create a copy of the suggestion, on the mention site.
