### ISSUE TITLE
My game stops loading and crashed at building terrain

### ISSUE THREAD

**Issue by justmyname122** [SleepyTrousers/EnderIO#4660]
I only have a few mods installed, but as soon as I get endercore 1.12.2-0.5.22 and enderio 1.12.2-5.0.24, I run into a problem in which my game freezes after building terrain and the game has to close before I can enter a world. Here are some crash reports, I'm not sure if they help. Is me using forge+optifine+enderio  to blame? Because forge+optifine work for applied energistics
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 5/25/18 8:49 PM
Description: Exception ticking world

java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:39)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:255)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:39)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:255)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: nam jac
	All players: 1 total; [EntityPlayerMP['justmyname122'/312, l='nam jac', x=-223.86, y=67.00, z=166.20]]
	Chunk stats: ServerChunkCache: 743 Drop: 0
	Level seed: 1540654451166569860
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-249,64,230), Chunk: (at 7,4,6 in -16,14; contains blocks -256,0,224 to -241,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1319421 game time, 463306 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 133860 (now: false), thunder time: 53467 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 32066944 bytes (30 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.3.2698 Optifine OptiFine_1.12.2_HD_U_D3 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                         | Version                | Source                                | Signature                                |
	|:--------- |:-------------------------- |:---------------------- |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                  | 1.12.2                 | minecraft.jar                         | None                                     |
	| UCHIJAAAA | mcp                        | 9.42                   | minecraft.jar                         | None                                     |
	| UCHIJAAAA | FML                        | 8.0.99.99              | forge-1.12.2-14.23.3.2698.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                      | 14.23.3.2698           | forge-1.12.2-14.23.3.2698.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | appliedenergistics2        | rv5-stable-11          | appliedenergistics2-rv5-stable-11.jar | None                                     |
	| UCHIJAAAA | endercore                  | 1.12.2-0.5.22          | EnderCore-1.12.2-0.5.22.jar           | None                                     |
	| UCHIJAAAA | jei                        | 4.9.1.188              | jei_1.12.2-4.9.1.188.jar              | None                                     |
	| UCHIJAAAA | enderio                    | 5.0.24                 | EnderIO-1.12.2-5.0.24.jar             | None                                     |
	| UCHIJAAAA | enderiointegrationtic      | 5.0.24                 | EnderIO-1.12.2-5.0.24.jar             | None                                     |
	| UCHIJAAAA | enderiobase                | 5.0.24                 | EnderIO-1.12.2-5.0.24.jar             | None                                     |
	| UCHIJAAAA | enderioconduits            | 5.0.24                 | EnderIO-1.12.2-5.0.24.jar             | None                                     |
	| UCHIJAAAA | enderiointegrationforestry | 5.0.24                 | EnderIO-1.12.2-5.0.24.jar             | None                                     |
	| UCHIJAAAA | mantle                     | 1.12-1.3.2.24          | Mantle-1.12-1.3.2.24.jar              | None                                     |
	| UCHIJAAAA | tconstruct                 | 1.12.2-2.9.1.65        | TConstruct-1.12.jar                   | None                                     |
	| UCHIJAAAA | enderiointegrationticlate  | 5.0.24                 | EnderIO-1.12.2-5.0.24.jar             | None                                     |
	| UCHIJAAAA | enderiomachines            | 5.0.24                 | EnderIO-1.12.2-5.0.24.jar             | None                                     |
	| UCHIJAAAA | enderiopowertools          | 5.0.24                 | EnderIO-1.12.2-5.0.24.jar             | None                                     |
	| UCHIJAAAA | tinkertoolleveling         | 1.12-1.0.4.DEV.5d716b9 | TinkerToolLeveling-1.12-1.0.4.jar     | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['justmyname122'/312, l='nam jac', x=-223.86, y=67.00, z=166.20]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: KUDA-Shaders v6.1 Legacy
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX TITAN/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by EpicSquid** [comment]
You have run out of memory on your computer. You need to either assign more RAM or buy more memory if you don't have enough. This is not Ender IO's fault

**Comment by EpicSquid** [comment]
What launcher are you using? You need to put -Xmx 4G -Xms 4G into the jvm arguments. A simple google search can explain it further.

**Comment by EpicSquid** [comment]
Closing this since it isn't Enderio's fault
