### ISSUE TITLE
Missing GUI Charging Slots Capacitor Bank 

### ISSUE THREAD

**Issue by ragregory42** [SleepyTrousers/EnderIO#4661]
#### Issue Description:
There are no charging slots in the capacitor bank gui. 

#### What happens:
I have crafted the 5M RF capacitor bank and connected it to the RF network I have in place. The capacitor bank charges to 5M RF but the gui does not contain the slots to place tools for charging. 

#### What you expected to happen:

I was anticipating slots being present in the gui for charging tools. 

#### Steps to reproduce:

1. Craft capacitor bank. 
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO-1.12.2-5.0.24
- EnderCore-1.12.2-0.5.22
- Minecraft: 1.12.2
- Forge-14.23.3.2678

#### Your most recent log file where the issue was present: 

https://gist.github.com/ragregory42/cc14f2bdcf58ed1fec8c6dd151bb985b

https://imgur.com/a/TFslZxt

**Comment by HenryLoenwind** [comment]
and my car doesn't make coffee. should I report that as a bug, too?

**Comment by ragregory42** [comment]
Its supposed to have charging slots look on the wiki?

**Comment by ragregory42** [comment]
https://github.com/SleepyTrousers/EnderIO/wiki/Capacitor-Banks

**Comment by tyler489** [comment]
Also Did you read the whole wiki? As in at the bottom of the page where it says ```This wiki is being rewritten from scratch, and mechanics may change during the mod's development. Currently, the information on this wiki is largely incomplete and may be out of date. If you want to make this wiki better, here are directions on how to Contribute to the wiki.````
