### ISSUE TITLE
Conduit Probe not working sometimes

### ISSUE THREAD

**Issue by Keridos** [SleepyTrousers/EnderIO#4663]
#### Issue Description:
Conduit Probe unable to paste config

#### What happens:
Nothing

#### What you expected to happen:
Copying the config to the right click connector.

#### Steps to reproduce:

1. Switch Conduit Probe to copy mode
2. Shift right click a conduit connector with energy fluid and item connected
3. Right click the connector you want to paste to

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.24
- EnderCore: 0.5.22
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2703

#### Your most recent log file where the issue was present:

**Comment by EpicSquid** [comment]
Appears to be fixed in dev, let me know if it doesn't work as of the latest dev builds.
