### ISSUE TITLE
[Thaumcraft] Please add back Goggles of Revealing compat to dark helmet

### ISSUE THREAD

**Issue by hron84** [SleepyTrousers/EnderIO#4665]
It's just a wish, if you can add back compatibility with this Thaumcraft glasses for dark helmet.

**Comment by EpicSquid** [comment]
On the todo list, it wasn't a priority though as you can now wear them as a bauble. Since this is a suggestion, please put it on our suggestion tracker here http://ideas.theideawall.com/EnderIO/

**Comment by hron84** [comment]
Ohh, if it's on todo list, then I'm fine with it. It's absolute OK if it will come eventually. Just wanted to let you know this missing. Thanks.
