### ISSUE TITLE
[Enhancment][Request] Elytra and glider thruster

### ISSUE THREAD

**Issue by 7thCore** [SleepyTrousers/EnderIO#4666]
Maybe this has been asked before but would you be willing to implement an anvil enchantmen for the elytra and glider on the chestplate that when you add either one to it you get the option to add let's say a firework rocket to the chestplate and it would allow for continious flight? Ofc it would use power while flying and maybe add a config that the server admins can disable it and configure the power consumption of it?

7thCore

**Comment by EpicSquid** [comment]
Interesting idea, however this is the issue tracker and is for bugs only. Please add your suggestion here http://ideas.theideawall.com/EnderIO/ at a suggestion tracker.
