### ISSUE TITLE
[1.12.2] Crash when using Yeta Wrench on TE Tank

### ISSUE THREAD

**Issue by MasterEnderman** [SleepyTrousers/EnderIO#4667]
#### Issue Description:
The Game crashes when using the Yeta Wrench on a Thermal Expansion Tank

#### What happens:
The Game crashes.

#### What you expected to happen:
Toggle the Output State of the tank.

#### Steps to reproduce:

1. Place a Thermal Expansion Tank
2. Click on it with a Yeta Wrench
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.25
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/ixoruboyej.txt

**Comment by Keridos** [comment]
Is the fix already in the builds on the jenkins?

**Comment by EpicSquid** [comment]
Fixed in dev. Please wait for a release

**Comment by EpicSquid** [comment]
Released
