### ISSUE TITLE
Redstone Conduits don't update blocks when they are disconnected

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4668]
#### Issue Description:
https://www.youtube.com/watch?v=zxfuZEKbNm4&feature=youtu.be

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.25
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 2705
- Mods: [list-alphabetical.txt](https://github.com/SleepyTrousers/EnderIO/files/2055116/list-alphabetical.txt)

**Comment by EpicSquid** [comment]
Video out of date. Please update your version.

**Comment by Xiaminou** [comment]
I tested the new version before posting, it still happens. There's no reason to make a new video.

**Comment by EpicSquid** [comment]
I cannot replicate this by doing what you have done with the video. Please provide a new reproduction case for the latest version.

**Comment by Xiaminou** [comment]
Ok, you're right it works with just EnderIO, which means it's a mod compatibility issue.

**Comment by Xiaminou** [comment]
I re-installed all the mods, and... it's not happening anymore?

I'm not crazy, I have a screenshot...

https://cdn.discordapp.com/attachments/409134692688855040/451445504744751114/2018-05-30_20.01.43.png

**Comment by EpicSquid** [comment]
Are you saying it is still happening or not? I cannot reproduce this in dev.
