### ISSUE TITLE
Redstone Conduits don't deal well with strong signals

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4669]
#### Issue Description:
https://www.youtube.com/watch?v=PyzwrIIf5Jw

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.25
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 2705
- Mods: [list-alphabetical.txt](https://github.com/SleepyTrousers/EnderIO/files/2055116/list-alphabetical.txt)

**Comment by EpicSquid** [comment]
Video out of date. Please update your version

**Comment by Xiaminou** [comment]
I tested the new version before posting, it still happens. There's no reason to make a new video.

**Comment by depressed-pho** [comment]
This still happens on EnderIO-1.12.2-5.0.29.jar. ```RedstoneConduitNetwork::tickEnd``` probably should also call ```world.notifyNeighborsOfStateChange()``` for attached blocks when they are solid and opaque?

https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/redstone/RedstoneConduitNetwork.java#L271

**Comment by HenryLoenwind** [comment]
No, line 275 already does a full notification. The tick-end code is a bit wonky, but it only runs in addition to the normal notification and is only needed for things like the timer filter.
