### ISSUE TITLE
Redstone Conduit's default output is green but default input is red

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#4671]
#### Issue Description:
I think they should be the same color by default.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.25
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 2705
- Mods: [list-alphabetical.txt](https://github.com/SleepyTrousers/EnderIO/files/2055116/list-alphabetical.txt)

**Comment by EpicSquid** [comment]
Not an issue, this is intended to prevent people accidentally locking their conduits on by powering the same channel with both input and output by default.

**Comment by Xiaminou** [comment]
I don't understand, what do you mean by locking their conduits?

**Comment by EpicSquid** [comment]
If the redstone signal is input and output on the same connection, is the same colour and going to a redstone wire, if u power the redstone wire the network will then not be able to switch off the colour.
