### ISSUE TITLE
HarvestDropsEvent Exception 

### ISSUE THREAD

**Issue by evernife** [SleepyTrousers/EnderIO#4673]
#### Issue Description:
Getting this error spaming on my console!

#### What happens:

Error on the console.

#### What you expected to happen:

Have no error on the console.

#### Steps to reproduce:

1. don't know
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.25.jar
- EnderCore: EnderCore-1.12.2-0.5.30.jar
- Minecraft: 1.12.12
- Forge: 2705

#### Your most recent log file where the issue was present: 

https://pastebin.com/m6SDttTj

**Comment by EpicSquid** [comment]
Are you using sponge?

**Comment by evernife** [comment]
yes, forget to mention, sorry

**Comment by EpicSquid** [comment]
This is a sponge issue, please report it to them.

**Comment by phit** [comment]
was already fixed on Sponge's end https://github.com/SpongePowered/SpongeForge/issues/2181

**Comment by EpicSquid** [comment]
@evernife update sponge forge and see if that fixes the issue.

**Comment by evernife** [comment]
i will, if needed i will reopen
