### ISSUE TITLE
Enlightened Fused Quartz -> Painting Machine = Painted Fused Quartz [1.12.2]

### ISSUE THREAD

**Issue by TheQuadShot** [SleepyTrousers/EnderIO#4674]
If I try to paint it in the painter it gets painted, but its just painted fused quartz 
It loses the Enlightenment. This works on 1.10.2 (EIO 1.10.2-3.1.193)

Minecraft 1.12.2
Forge 14.23.3.2698

EnderIO-1.12.2-5.0.24.jar

**Comment by HenryLoenwind** [comment]
should be fixed

**Comment by TheQuadShot** [comment]
I can no longer paint Enlightened Clear Quartz. I am primarily a builder and loved this functionality and used it for lighting and setting a ambiance to my builds. I would like to have this functionality back. This is an images where I used this(in previous builds

![](https://i.imgur.com/5GAg6NE.png)
):

![](https://i.imgur.com/KRYSCs3.png)


![](https://i.imgur.com/F4iNwl1.png)

**Comment by HenryLoenwind** [comment]
There is no such thing as "Enlightened Clear Quartz"...

![image](https://user-images.githubusercontent.com/1485873/64476834-0c1b6e00-d194-11e9-9d1b-43712609d207.png)

However, Dark Fused Quartz's paintability if AWOL.

**Comment by HenryLoenwind** [comment]
Update: Ooops, I had gotten a colored one by accident.

![image](https://user-images.githubusercontent.com/1485873/64476895-e9d62000-d194-11e9-91ed-e4966d08b80d.png)

it actually works.

**Comment by TheQuadShot** [comment]
![Enlightened Clear Glass](https://user-images.githubusercontent.com/11265900/64477063-d0f54c80-d14b-11e9-9d25-d594aac017e1.png)
