### ISSUE TITLE
[1.12.2] [TiC] Grinding Balls Unsing Wrong Cast

### ISSUE THREAD

**Issue by Sanofus** [SleepyTrousers/EnderIO#4676]
I noticed that the grinding balls use the gem cast. But I think they should use the pan cast because they round and not "gem molded". 
![2018-06-01_17 51 51](https://user-images.githubusercontent.com/26455012/40850543-31f33cfc-65c5-11e8-9e3e-7b80081f54ae.png)
![2018-06-01_17 51 55](https://user-images.githubusercontent.com/26455012/40850550-375dfb78-65c5-11e8-98c0-fd0541ddbda0.png)

And this should be used instead.
![2018-06-01_17 53 32](https://user-images.githubusercontent.com/26455012/40850571-4435cc72-65c5-11e8-94b2-2491cdb5b50b.png)

**Comment by tyler489** [comment]
The reason gem was chosen was otherwise you wouldnt be able to have any pan made from enderio metals

**Comment by HenryLoenwind** [comment]
And how would you build a pan from our alloys if you got balls from casting the pan?

**Comment by Sanofus** [comment]
Stupid me. :D 
I don't thought about that. 


But wasn't there a ball cast in previous verions of TiC?

**Comment by tyler489** [comment]
Not that im aware of

**Comment by HenryLoenwind** [comment]
Unless some mod added it, no.
