### ISSUE TITLE
All capacitor configs missing?

### ISSUE THREAD

**Issue by Lukas45** [SleepyTrousers/EnderIO#4678]
#### Issue Description:
After updating from 5.0.24 to .25, all configs regarding machine speed are invalid. Machines are back to their default stats, despite the config being untouched. I created a fresh test client, and noticed all Capacitor related configs, which also controls machine speed, have gone missing.

#### What happens:
Machines speed/usage can no longer be configured

#### What you expected to happen:
Machines speed/usage to be configurable

#### Steps to reproduce:

1. Edit configs in .24 to make machines faster
2. Update to .25
3. Profit.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.25
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: .2705

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by EpicSquid** [comment]
They are now located in xml files. Please read the change logs.
