### ISSUE TITLE
 Farming Station Not working

### ISSUE THREAD

**Issue by Solverbolt** [SleepyTrousers/EnderIO#4679]
#### Issue Description:
FoolCraft 3 Modpack - Farming Station does absolutely nothing. 

Side note:, so we get all this combined for quicker time frame. 

Fluid Conduits will drop TPS to a stand still if they are moving fluid.

Crafter will delete items instead of craft the recipe it was given

#### Steps to reproduce:

1. Placed Down Farming station
2. Connect power
3. Add Tools, capacitor, seeds, bone meal
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2 5.0.24
- EnderCore: 1.12.2 0.5.22
- Minecraft: 1.7.10
- Forge: 1.12.2 2.4.2.58

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
Just wondering how you are using 1.12 enderio on 1.7 minecraft
Affected Versions (Do not use "latest"):
EnderIO: 1.12.2 5.0.24
EnderCore: 1.12.2 0.5.22
Minecraft: 1.7.10
Forge: 1.12.2 2.4.2.58

**Comment by EpicSquid** [comment]
Update ender io and Ender core then check your issues again.
