### ISSUE TITLE
Farming station doesn't shear leaves from some modded trees

### ISSUE THREAD

**Issue by belathus** [SleepyTrousers/EnderIO#4680]
#### Issue Description:
Farming station doesn't shear leaves added by some other mods. For example, it will not shear undead tree leaves from EvilCraft or silverwood or greatwood leaves from Thaumcraft.

Normally, the farming station breaks the leaves even without shears. In this case, it is failing to do so. I've noticed it also leaves the leaves behind when using a dark steel axe as well, which might be related.

#### What happens:
The farming station plants the saplings as expected, and chops down the logs, but it fails to do anything to the leaves. They just float there and decay naturally.

#### What you expected to happen:
I was hoping that the farming station would shear the leaves of the trees, as the undead leaves can be squeezed for blood.

#### Steps to reproduce:

1. Set up farming station
2. Fill farming station with undead saplings from Evilcraft
3. Give farming station shears and an axe
4. Wait.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.24
- EnderCore: 0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.3.2691

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Report that to the mod those leaves come from. They need to oredict them as "treeLeaves" so our code can recognize them as leaves.

**Comment by belathus** [comment]
... that's all that needs to be done? Hell, I can do that myself.

**Comment by tyler489** [comment]
I went ahead and opened issues on both there github for you ;) wait to see if they will comply with my request.

**Comment by HenryLoenwind** [comment]
Yes, the main tree harvester just needs oredicts for logs and leaves. Much easier than having to write a custom harvester for each type of tree as we had to do in the past. (That's still possible if some mod has weird trees, but they then should do it themselves, that's what we have an API for.)

**Comment by belathus** [comment]
I just went ahead and added the leaves to the oredictionary with CraftTweaker. I'll see if that works shortly.

https://github.com/belathus/Wanderlust-Renewed/blob/master/scripts/oredict.zs#L197-L199

**Comment by HenryLoenwind** [comment]
PS: And in case it comes up, the oredict needs to be on the ItemBlock of the Block, not on the dropped item.

**Comment by tyler489** [comment]
Anazor has agreed to comply.
