### ISSUE TITLE
Shift-Click Conduit Crash

### ISSUE THREAD

**Issue by mavrikfalkon** [SleepyTrousers/EnderIO#4681]
#### Issue Description:
Reproducible crash when shift clicking conduits to break.

#### What happens:
When shift clicking any enderio conduit to break it, Minecraft crashes

#### What you expected to happen:
I thought it would break the conduit

#### Steps to reproduce:

1.Shift click enderio conduit with yeta wrench.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.25
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

https://pastebin.com/zHj3tvEa

**Comment by EpicSquid** [comment]
This isn't enderio. Please report it to RFTools
