### ISSUE TITLE
Duplication bug with farming station.

### ISSUE THREAD

**Issue by triffman33** [SleepyTrousers/EnderIO#4683]
#### Issue Description:
Duplicating Red matter/Dark matter hoe in Farming Station. Foolcraft 3, Iskall_Dev.

#### What happens:
When the hoe is placed inside the farming station with no tilled earth around it, it'll "try" to till it and fail, but if it goes over a piece of tilled land it'll then output either the red matter or dark matter hoe at the same time as trying to place the seed (i used rice seeds from Actually Additions)

#### What you expected to happen:
The hoe just tilling the dirt/grass.

#### Steps to reproduce:

1. Place down Farming Station and power it.
2. Give it dark matter/red matter hoe and seeds.
3. Till ground manually around the farming station.
4. Dark matter/red matter hoe's will be put into the output slot of the farming station

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.24
- EnderCore: EnderCore-1.12.2-0.5.22
- Minecraft: 1.12.2
- Forge: forge-12.23.4.2705
- ProjectE: ProjectE-1.12.2-1.3.3

____
#### Extra Info
I'll be posting in the Project E github too incase its a bug with that mod, or if its a combination with both of the mods.

https://github.com/sinkillerj/ProjectE/issues/1700

**Comment by HenryLoenwind** [comment]
Sounds like Project E is moving the hoe to another inventory slot of the fakeplayer?

**Comment by triffman33** [comment]
I'm not too sure of the ins and outs of how mods work and such, so just gonna link the project E issue too so hopefully the 2 mod developers can come to a conclusion and a fix :) 
https://github.com/sinkillerj/ProjectE/issues/1700

**Comment by williewillus** [comment]
nope, just calling a method to till things and returning true

https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkHoe.java#L32

https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/gameObjs/items/tools/PEToolBase.java#L173

**Comment by HenryLoenwind** [comment]
Please re-test with a current Ender IO version. We changed the tilling code in the mean time.

Just post an answer if this still happens, I'll re-open the ticket if it does.
