### ISSUE TITLE
Painted glowstone dupe

### ISSUE THREAD

**Issue by yepidoodles** [SleepyTrousers/EnderIO#4684]
#### Issue Description:

Glowstone painted with any kind of block dupes when placed and broken.

#### What happens:

1. Paint Glowstone with any block.
2. Place and break block.
3. Glowstone block and glowstone dust drops.

#### What you expected to happen:

Either only the block or the dust drops.

#### Steps to reproduce:

1. Paint Glowstone with any block.
2. Place and break block.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 2707

#### Your most recent log file where the issue was present: 

I don't believe logs are applicable in this case, however I will provide them on request.

~ Alice

**Comment by HenryLoenwind** [comment]
I'm assuming you have the config flag "paintedGlowstoneRequireSilkTouch" enabled...
