### ISSUE TITLE
Can't combine two terrible capacitors in an anvil

### ISSUE THREAD

**Issue by belathus** [SleepyTrousers/EnderIO#4685]
#### Issue Description:
I have two capacitor duds. Trying to combine them in an anvil shows an output, but it has no level cost. I'm guessing that without a level cost, I cannot complete the recipe. Clicking ot the output does nothing, even though there is an item there. It just won't let me pull it out.

#### What happens:
Putting two capacitor duds in the anvil works, but I cannot pull out the result.
I tried this in both a regular anvil and the dark steel anvil. No luck either way.

#### What you expected to happen:
Being able to combine two duds into a slightly better capacitor.

#### Steps to reproduce:

1. give yourself two terrible capacitors. The two I have are the following:
 * /give player enderio:item_basic_capacitor 1 3 {eiocap: {sag_mill_power_use: 2.2214608f, level: 0.9341444f}, "enderio:capname": "Nice Crushed Capacitor Dud", display: {Name: "Nothing"}, "enderio:capno": 7, "enderio:glinted": 1}
 * /give player enderio:item_basic_capacitor 1 3 {eiocap: {sag_mill_power_use: 1.78561f, level: 0.8772197f}, "enderio:capname": "Nice Crushed Capacitor Dud", display: {Name: "Heaven Cent"}, "enderio:capno": 4, "enderio:glinted": 1}
2. try combining them in an anvil
3. There won't be a level cost, and you won't be able to remove the item from the anvil.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 14.23.3.2961

#### Your most recent log file where the issue was present: 
Available on request.

**Comment by tyler489** [comment]
You can only combine capacitors with the same Image.

**Comment by belathus** [comment]
They have the same image. Both have metadata 3.

**Comment by HenryLoenwind** [comment]
You can only combine loot caps if the output is at least somewhat better than the input. If there is no notable change, it won't allow you to waste levels on it.
