### ISSUE TITLE
[1.12.] Always crash on start up at Linux

### ISSUE THREAD

**Issue by Sanofus** [SleepyTrousers/EnderIO#4686]
Happens always on Linux not on Windows.
[crash-2018-06-06_17.52.45-client.txt](https://github.com/SleepyTrousers/EnderIO/files/2077128/crash-2018-06-06_17.52.45-client.txt)
[crash-2018-06-06_18.01.33-client.txt](https://github.com/SleepyTrousers/EnderIO/files/2077129/crash-2018-06-06_18.01.33-client.txt)
[crash-2018-06-06_18.07.46-client.txt](https://github.com/SleepyTrousers/EnderIO/files/2077130/crash-2018-06-06_18.07.46-client.txt)

**Comment by MatthiasMann** [comment]
Works fine for me with EnderCore-1.12.2-0.5.30.jar and EnderIO-1.12.2-5.0.26.jar

**Comment by MatthiasMann** [comment]
Linux Mint 18.3 with OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
