### ISSUE TITLE
EIO Quite Clear Glass and Clear Quartz lighten/change BeaconColor (Related:https://github.com/SleepyTrousers/EnderIO/issues/4599)

### ISSUE THREAD

**Issue by TheQuadShot** [SleepyTrousers/EnderIO#4687]
Related:https://github.com/SleepyTrousers/EnderIO/issues/4599
Vanilla Glass doesn't "touch" the color, nor does TiC.

Forge 12.18.3.2511
EnderCore-1.10.2-0.4.1.66-beta
EnderIO-1.10.2-3.1.193

Forge 14.23.3.2698
EnderCore-1.12.2-0.5.30
EnderIO-1.12.2-5.0.25

Enlightened Fused Quartz
https://imgur.com/GHj7ICQ

Fused Quartz
https://imgur.com/pcxjRkP

Quite Clear Glass
https://imgur.com/ADy7iIz

Vanilla Glass
https://imgur.com/bVO6913

Tinkers Quite Clear Glass
https://imgur.com/LIsEwE3

**Comment by HenryLoenwind** [comment]
Same as vanilla...

![image](https://user-images.githubusercontent.com/1485873/41051764-4b27e6d2-69b7-11e8-8d0a-2a07245259e5.png)

**Comment by TheQuadShot** [comment]
Not for me...
![2018-06-06_09 34 35](https://user-images.githubusercontent.com/11265900/41052157-ed782c94-696c-11e8-8177-9b7e0f2032ed.png)

**Comment by TheQuadShot** [comment]
Sorry, you are incorrect. This is a PURE Vanilla Minecraft
With accompanying log file of my exact test for this for this image:
https://pastebin.com/tE2XZbK5

![2018-06-06_15 08 32](https://user-images.githubusercontent.com/11265900/41067958-5982703c-699c-11e8-832f-b238e4cd1d4c.png)
