### ISSUE TITLE
EnderIO crash on startup, around mod ID mapping. "java.lang.IndexOutOfBoundsException"

### ISSUE THREAD

**Issue by solunareclipse1** [SleepyTrousers/EnderIO#4691]
#### Issue Description:
EnderIO crashes upon startup, with around 200 other mods. Only references that I can see from the report are from EnderIO / EnderCore. Last thing before crash says Forge is mapping mod ids. Might be another mod, I just installed a few, but I uninstalled the ones I remembered, and crash still occurred. 

#### What happens:

Game crashes around forge mod id mapping

#### What you expected to happen:

Game launches correctly

#### Steps to reproduce:

1. Launch game with possible unknown mod
2. Wait for mod ID mapping
3. Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.30
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/ohesolizix.mccrash

**Comment by HenryLoenwind** [comment]
No idea who is responsible, but it looks like some coremod is patching Java Runtime classes.

**Comment by HenryLoenwind** [comment]
PS: I just confirmed with the Forge devs that a coremod patching vanilla's NonNullList has been seen in the wild before. That could be the reason. Candidates are:

```
                                      AstralCore (astralsorcery-1.12.2-1.8.10.jar)
                                      OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
                                      LoadingPlugin (RandomThings-MC1.12.2-4.1.7.jar)
                                      ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
                                      LoadingPlugin (Quark-r1.4-123.jar)
                                      Plugin (NotEnoughIDs-1.5.4.2.jar)
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.8-88.jar)
                                      CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
                                      Wizardry Plugin (wizardry-0.8.5.jar)
                                      FMLPlugin (elulib-0.1.12.jar)
                                      ForgelinPlugin (Forgelin-1.6.0.jar)
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
```

**Comment by solunareclipse1** [comment]
Progress maybe? Removing VanillaFix gave me a different crash. NPE this time. With a quick glance, looks like something with recipes?

[New crashlog](https://hastebin.com/nikusaquxe.sql)

**Comment by EpicSquid** [comment]
I suspect the old crash is due to VanillaFix trying to stop your game from crashing then (don't re-add VanillaFix).

**Comment by solunareclipse1** [comment]
My thoughts as well. Kinda sucks, I quite liked the ability to not have to relaunch every time I crash, but oh well. In other news, I got what appears to be the exact same crash as the original, after removing a couple more (Colytra and RedstonePaste/NWRTweak)

[Report](https://hastebin.com/zebijuyole.sql)

**Comment by EpicSquid** [comment]
Also try downgrading forge to 2705

**Comment by HenryLoenwind** [comment]
The second one looks like some mod is adding a null into the ore dictionary...

**Comment by EpicSquid** [comment]
Remove elulib and open eye, then try again

**Comment by solunareclipse1** [comment]
Not sure what did it, but after removing a couple more things, it at least launched. Am currently attempting testing to see which of the ones i removed caused the issue

**Comment by solunareclipse1** [comment]
Couldnt pinpoint it. Might have forgotten one of them. either way, the game boots, so I'm just going to close this. Sorry if this was a waste of time :(
