### ISSUE TITLE
zh_ch.guess file error

### ISSUE THREAD

**Issue by a8022476** [SleepyTrousers/EnderIO#4694]
#### What happens:
At present,this version some items title is empty string for this package online.
i see the EnderIO_base dictionary,the zh_ch.guess file,more line with '#',the prev line is empty string behind '='.
#### What you expected to happen:
where i can download the lang file?
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.12.2
- Forge:

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
This is the input for a translator, if this already had data, would would a translator do?
