### ISSUE TITLE
crash when you click on a recipe in JEI

### ISSUE THREAD

**Issue by KiraLinux** [SleepyTrousers/EnderIO#4696]
#### Issue Description:
I go to JEI
I look at the recipes with the left mouse button, but when I want to see what can be done from this object and by pressing the right mouse button the game crashes

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderCore-1.12.2-0.5.30
- EnderIO-base-1.12.2-5.0.507-nightly
EnderIO-conduits-1.12.2-5.0.507-nightly
EnderIO-conduits-appliedenergistics-1.12.2-5.0.507-nightly
EnderIO-integration-forestry-1.12.2-5.0.507-nightly
EnderIO-integration-tic-1.12.2-5.0.507-nightly
EnderIO-invpanel-1.12.2-5.0.507-nightly
EnderIO-machines-1.12.2-5.0.507-nightly

- Minecraft: 1.12.2
- 1.12.2-forge1.12.2-14.23.4.2705

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
[crash.zip](https://github.com/SleepyTrousers/EnderIO/files/2086638/crash.zip)

**Comment by EpicSquid** [comment]
This is a nuclear craft bug. Please post it there. They are not registering their fluids correctly.

**Comment by KiraLinux** [comment]
Thank you

**Comment by KiraLinux** [comment]
[crash-2018-06-16_21.44.06-client.zip](https://github.com/SleepyTrousers/EnderIO/files/2108446/crash-2018-06-16_21.44.06-client.zip)
I removed that mod and still this problem is observed

**Comment by tyler489** [comment]
Can you put that on pastebin please. I cant open zips from my phone

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/41501549-d78e0c72-71a6-11e8-9c77-4ca11ea1b9c3.png)
completely different issue.

**Comment by HenryLoenwind** [comment]
I'd tell you to report this to industrialforegoing (that's the mod that is crashing), but you're using a quite old version.

**Comment by KiraLinux** [comment]
first they said it was a problem  nuclear craft bug
