### ISSUE TITLE
dark clear glass and dark fused quartz does not seem to be dark

### ISSUE THREAD

**Issue by scones** [SleepyTrousers/EnderIO#4698]
#### What happens:
When i place it to optically isolate an area from light, the light levels beyond that wall of dark quartz/glass is not lowered

#### What you expected to happen:
It should block the light

#### Steps to reproduce:

1. build dark fused quartz
2. surround yourself with the fused quartz
3. light levels are uneffected

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  5.0.26
- EnderCore: 0.5.30
- Minecraft: 1.12-2
- Forge: 2705

**Comment by Ar4093** [comment]
I've had something like this happen with EU2's Dark (Ineffable) Glass before, where light seemed to bleed in into a closed off room with dark glass on one side and solid walls (stone/cobble) on all others.

That might be the same issue, which only happened sporadically though (more frequently on servers).

**Comment by tterrag1098** [comment]
Do you have a screenshot example of this problem?
