### ISSUE TITLE
refined storage destructor issue.

### ISSUE THREAD

**Issue by Gamer95875** [SleepyTrousers/EnderIO#4699]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
i placed a destructor (from refined storage) accidentally on a refined storage conduit and it crashed the game, i assume the refined storage conduit connected and gave it power.

#### What you expected to happen:
the conduit to break and nothing else happening.

#### Steps to reproduce:

1.get refined storage
2.boot up the game
3.place a destructor
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.25
- EnderCore: 1.12.2-0.5.30
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

https://pastebin.com/Eh6Umk1S

**Comment by HenryLoenwind** [comment]
That's a bug in refined storage. He's calling getPickBlock() with `null` for the `target` parameter, but that parameter is annotated `@Nonnull`.

https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/network/node/NetworkNodeDestructor.java#L105

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/41422876-2e7cff92-6ffa-11e8-96cd-258d88b05031.png)
...

**Comment by raoulvdberge** [comment]
Weird. I have those annotations as well.

**Comment by HenryLoenwind** [comment]
Then check your Forge installation, there supposed to be package annotations all over the vanilla code.
