### ISSUE TITLE
Add support for Agricraft with Farming Station

### ISSUE THREAD

**Issue by kriNon** [SleepyTrousers/EnderIO#4700]
Issue Description:
Farming station doesn't harvest crops in agricraft crop sticks.

Realistically I believe that the support would typically be implemented on the agricraft side, but from the looks of it, it seems that development has stopped on agricraft (possibly temporary). If anything could be done to support it from the ender io side that would be much appreciated!

What happens:
The Farming station will ignore agricraft crop sticks entirely.

What you expected to happen:
I was hoping that the farming station would harvest and replant the seeds in the crop sticks.

Steps to reproduce:
Set up farming station
Set up crop sticks with seeds in them
Wait.

Affected Versions (Do not use "latest"):
EnderIO: 5.0.26
EnderCore: 0.5.30
Minecraft: 1.12.2
Forge: 14.23.4.2705

**Comment by EpicSquid** [comment]
This is something the agricraft farming station from Ender IO Addons handles. This is not a bug and just needs to be ported by someone.
