### ISSUE TITLE
Crash when loading minecraft

### ISSUE THREAD

**Issue by grydian** [SleepyTrousers/EnderIO#4701]
#### Issue Description:
Custom pack with forge 2705, and EnderIO-1.12.2-5.0.26.

#### What happens:
Crash when loading.  It appears to be a crash generated by the mod due to a mod conflict.  I cannot figure out what is conflicting.

#### What you expected to happen:
Minecraft to load

#### Steps to reproduce:

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 2705

#### Your most recent log file where the issue was present: 
https://pastebin.com/itjqZNF1
[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
also relevant: https://github.com/SleepyTrousers/EnderIO/issues/4505

**Comment by HenryLoenwind** [comment]
update endercore
