### ISSUE TITLE
Conduit Probe not functioning on bundles

### ISSUE THREAD

**Issue by TheOtherMorzie** [SleepyTrousers/EnderIO#4703]
#### Issue Description:
The Conduit Probe does not seem to be copying and/or pasting settings to bundled conduits, the conduit probe seems to work fine on a single conduit, i.e. a single Item conduit, but not if there is multiple in the same block.

While this is installed as part of the FTB Revelation modpack, I have tried this on multiple versions of the mod and because of the nature of the issue , I believe it is caused by the mod itself.

#### What happens:
Conduit Probe can not copy and/or paste settings with conduit bundles.
The conduit probe works on a single conduit, however if there is more than one conduit in the same block, the probe fails to paste the settings.

Not sure if this is how the conduit probe is intended to function but if the there is an extra conduit on either the copied conduit or the pasted conduit, the probe will just open the conduit GUI e.g. copying from an Item Conduit and a Ender Energy conduit and pasting to an Item conduit.

#### What you expected to happen:
The conduit probe should be able to paste conduit settings onto conduit bundles, not just single conduits.

Conduit probe should copy settings from present conduits, and paste them onto any conduits that are of the same type

#### Steps to reproduce:

1. Attempt to copy/paste settings on conduit bundles
2. Profit?

____
#### Affected Versions:

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.2.2627

**Comment by EpicSquid** [comment]
Can you please provide a very specific set of steps to reproduce this issue? I know it exists but can never replicate it myself. If possible can you test the steps with just Ender IO (and jei) installed please?

**Comment by TheOtherMorzie** [comment]
I'll test it with just Ender IO installed and see if it still happens.

Steps for reproducing are:
1. Place Item Conduits next to two machines
2. Place Ender Energy Conduits in the same space as the item conduits
3. Change the settings of one of the conduit connections to he machines
4. Copy settings from the changed conduit face
5. Paste the settings to the second conduit face

**Comment by EpicSquid** [comment]
Okay thank you, I will try this out later and see if I can work out what is wrong.

**Comment by TheOtherMorzie** [comment]
I just tested it on a fresh install, all the same versions and the problem still persists.
https://imgur.com/a/jJZ3oVc
Screenshot to help reproduce the issue.

**Comment by GitHubShawnMichael** [comment]
I have an observation. If you change the crouch key (shift) to something else like (ctrl), it prevents the Conduit Probe hotkeys from functioning altogether. If you switch back to the default control scheme, the hotkeys begin to work as normal. Please investigate and pass this along.

**Comment by rblacktree** [comment]
I ran into the same problem. I discovered that if I am holding something in my off hand, the probe didn't copy the settings. Once I removed the items from my off hand, the probe worked properly.
