### ISSUE TITLE
EnderIO Farmer causing server crash

### ISSUE THREAD

**Issue by Satellite27** [SleepyTrousers/EnderIO#4704]
Whenever a certain user on my server logs in the server instantly crashes

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.193
- EnderCore: EnderCore-1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.3.2511-universal.jar

#### Your most recent log file where the issue was present: 

https://gist.githubusercontent.com/Satellite27/cc391d221ab183e7f92404434f7b676e/raw/5354c40addfbb83f4aaa5461d4a9c77aeda108cc/gistfile1.txt

**Comment by EpicSquid** [comment]
Looks like a sponge error to me.

**Comment by tyler489** [comment]
Yes it is... and sponge wont support 1.10.2
