### ISSUE TITLE
Problem EnderIO

### ISSUE THREAD

**Issue by Leodragon08** [SleepyTrousers/EnderIO#4705]
#### Description of the problem:
Starting problem EnderIO, when I insert the mod with all its other components crashes the game, I tried to activate the mod out of the mod pack I'm doing but nothing has changed
Here's what a person told me about a forum:
The problem is a compatibility between MysticalAgriculture and EnderIO. Since you do not have MysticalAgriculture installed, obviously within EnderIO there is a part that uses it. Write to the authors and make the problem known, unfortunately as a user you can not do anything.
And so I write here.

#### What happens:
Crusha the game

#### What did you expect it to happen:
I was expecting the mod to work.

#### Steps to play:

1. Install the EnderIO, JEI, Endercore
2.Insert them in the "mods" folder
3. Start minecraft with Forge
...

____
#### Relevant versions (Do * not * use "latest"):

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

#### The most recent log file in which the problem occurred:

https://pastebin.com/3a4MeR5V

Goodbye Leonard

**Comment by HenryLoenwind** [comment]
You are using an endercore for 1.10.2 with the config file for 1.12. Don't do that.
