### ISSUE TITLE
Wired Charger compatibility issue [?]

### ISSUE THREAD

**Issue by TheQuadShot** [SleepyTrousers/EnderIO#4707]
Sorry if I'm presuming too much. I am under the impression that the Wired Charge(Really like it btw!) is a replacement for the "Charging" slot in Capacitors found in previous versions. I can't put Galacticraft batteries in the charger, but I can on version 1.10.2-3.1.193 put same battery(GC 1.10.2-3.0.1.177) in the "Charging" slot of a Capacitor(EIO 1.10.2-3.1.193).

Minecraft 1.12.2
Forge 14.23.3.2698

EnderCore-1.12.2-0.5.30.jar
EnderIO-1.12.2-5.0.25.jar

Galacticraft-Planets-1.12.2-4.0.1.177.jar
GalacticraftCore-1.12.2-4.0.1.177.jar
MicdoodleCore-1.12.2-4.0.1.177.jar

BTW Thanks for a Great Mod!! I really like the direction it's taking on this release!
Hope this helps:
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/items/ItemBattery.java

**Comment by HenryLoenwind** [comment]
Galacticraft only support Thermal Expansion energy, Mekanism Energy and IC2 energy...

(yes, that link helped to find that out quickly)
