### ISSUE TITLE
Farming Station crash with Rustic Berry Bush

### ISSUE THREAD

**Issue by NillerMedDild** [SleepyTrousers/EnderIO#4708]
#### Issue Description:
This issue occured in the modpack Enigmatica 2, of which I am the pack dev.

#### What happens:
One of my users reported a server crash, when his Ender IO Farming Station attempted to harvest a Rustic Berry Bush

#### What you expected to happen:
The Berry Bush to be harvested

#### Steps to reproduce:

1. Setup Farming Station with power and tools
2. Give it berry bushes, or place them within it's area
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft 1.12.2
- Forge 1.12.2-14.23.4.2705
- EnderCore-1.12.2-0.5.31
- EnderIO-1.12.2-5.0.26
- rustic-1.0.5

#### Your most recent log file where the issue was present: 

https://pastebin.com/bYBmD9NX

**Comment by tyler489** [comment]
https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/common/blocks/crops/BlockBerryBush.java

**Comment by NillerMedDild** [comment]
Thank you :)
