### ISSUE TITLE
Soulbound Enchant Not Working

### ISSUE THREAD

**Issue by NillerMedDild** [SleepyTrousers/EnderIO#4709]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

This issue occurs in the modpack Enigmatica 2: Expert, of which I am the dev.
The Soulbound enchant does nothing upon death, tested on a Diamond Chestplate, and a Stone Sword.
It may be a conflict our grave mod, Tomb Many Graves. I will open an issue on their tracker aswell.

#### What happens:
The item is put in my grave.

#### What you expected to happen:
The item to stay equipped upon death.

#### Steps to reproduce:

1. Enchant item with Soulbound
2. Die
3. The Item is lost (in ones grave)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2705
- Possible conflict, TombManyGraves: 1.12-4.1.0

#### Your most recent log file where the issue was present: 

https://gist.github.com/NillerMedDild/bed45cdc5a65897cc785c8637811d160

**Comment by HenryLoenwind** [comment]
And conformed, TombManyGraves2 is doing 'bad stuff'.

**Comment by NillerMedDild** [comment]
Alright then, thank you.
