### ISSUE TITLE
Missing Unpainted Stairs

### ISSUE THREAD

**Issue by Boolyman** [SleepyTrousers/EnderIO#4710]
#### Issue Description:
In one of the recent builds of EnderIO there were unpainted stairs that you could color in the painting machine.  I used them in my creative build, which will be going into a modpack.  Unfortunately, when I went into JEI today to grab a few more, they were nowhere to be found.  Did they get removed in a recent patch?  I checked the changelog for the last 3 updates and did not see anything about them being removed.  Will the be back?  They were very nice.

#### What happens:
I look bewildered when I can't find unpainted stairs.

#### What you expected to happen:
To not look bewildered because I could not find painted stairs.

#### Steps to reproduce:

1.  Press E for JEI
2.  Search for said unpainted stairs
3.  Commence bewilderment.
...
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2708

**Comment by HenryLoenwind** [comment]
That was an internal item JEI forced to be visible.

**Comment by Boolyman** [comment]
Damn.  They were a really nice feature.
