### ISSUE TITLE
Client crashes when joining server with a nullpointer

### ISSUE THREAD

**Issue by kaosjr** [SleepyTrousers/EnderIO#4712]
#### Issue Description:
I am a modpack author, and this issue is occurring in my pack so I'm reporting it here.
The client crashes upon joining a server.

#### What happens:
The client crashes.

#### What you expected to happen:
The client to not crash?

#### Steps to reproduce:
Step 1: Join server.
Step 2: Wait till the server loads.
Step 3: Client crashes.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

#### Your most recent log file where the issue was present: 
https://pastebin.com/gC78qdyB

**Comment by tyler489** [comment]
Are you using  a custom recipy prehaps?

**Comment by kaosjr** [comment]
No, Crafttweaker is installed but there are no custom recipies, and Modtweaker isn't installed.

**Comment by kaosjr** [comment]
The pack this is running on is Potentiality v4.0.4. Mod list is on CurseForge.

**Comment by HenryLoenwind** [comment]
Some coremod is messing with vanilla's NonNullList, but we don't know which one.
