### ISSUE TITLE
Elder Guardians treated as Boss Mob in Config.

### ISSUE THREAD

**Issue by TheLargeCactus** [SleepyTrousers/EnderIO#4713]
#### Issue Description:
Attempting to use a soul vial on an Elder Guardian from base minecraft results in an error being displayed and the entity not being captured unless a config option is flipped.

Issue happens in a modpack but is fixed by changing EnderIO config so I believe the bug is EnderIO specific.

#### What happens: 
On Soul Vial Use, when attempting to capture an elder guardian, the chat box displays an error: "permission denied - entity is blacklisted".

#### What you expected to happen: 
Elder Guardians, not being mobs with displayed boss bars should be able to be captured by soul vials, without changing the config option "B:soulVesselCapturesBosses=true". 

#### Steps to reproduce:

1. Change "B:soulVesselCapturesBosses=false" in EnderIO.cfg
2. Attempt to capture elder guardian with soul vial
3. Notice that the error is displayed upon attempting
4. Change "B:soulVesselCapturesBosses=true"
5. Attempt to capture elder guardian with soul vial
6. Notice it is now possible.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.24
- EnderCore: 1.12.2-0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 
Not Applicable.

**Comment by TheLargeCactus** [comment]
Also, potentially related bug: I cannot craft an elder guardian broken spawner in the soul binder. Attempting to insert any elder guardian soul vial with any broken spawner doesn't allow me to place them both in their respective slots simultaneously.

**Comment by tyler489** [comment]
Pretty sure this is intended... The Spawners are blacklisted.

**Comment by bunnyman14** [comment]
I would definitely count Elder Guardians as a boss. This is likely not a bug.

**Comment by TheLargeCactus** [comment]
That might warrant a config comment change then. It's a minor thing, but it specifically mentioned mobs with a "boss bar"

**Comment by EpicSquid** [comment]
You have to update the spawner recipe in the xml config. Follow the instructions in base.xml for how to do that.

**Comment by HenryLoenwind** [comment]
works as intended. while the elder guardian has no "boss bar", its spawning logic follows boss rules.
