### ISSUE TITLE
Advancement Error

### ISSUE THREAD

**Issue by AlexDAM** [SleepyTrousers/EnderIO#4717]
#### Issue Description:
I have made a very small modpack for me and my friends and we get some weird lag spikes on our server it might be just our pc or the server we do not know exactly but we saw this error on the server's console and we think that this might be the issue of our lag.

#### What happens:
This error appears on the console nothing visual is happening in the game

#### What you expected to happen:
We expected to not see this error and if it actually causes those lag spikes we also expected to not have them.

#### Steps to reproduce:
This error appears when the server is loading up we don't know if it is a specific mod that causes this error to happen

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.26
- EnderCore: EnderCore-1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.3.2655

#### Your most recent log file where the issue was present: 

https://images2.imgbox.com/13/a0/iNGmjacx_o.png

unfortunately we can't copy paste it so we took a picture of it i hope that you can read it

**Comment by tyler489** [comment]
thats just a generic warning that an advancement name was changed and we are still using the wrong name.. That by itself would not cause lag.
