### ISSUE TITLE
Crashing Server when placing OC conduits (in loop?)

### ISSUE THREAD

**Issue by NikkyAI** [SleepyTrousers/EnderIO#4720]
#### What happens:

when placing oc conduits or causing them to connect, sometimes (i think when creating a loop) the server crashes

#### What you expected to happen:

connected opencomputers ?

#### Steps to reproduce:

1. connect computer to oc wire
2. connect oc conduit
3. see if it crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- OpenComputers: 1.7.2.67
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://gist.github.com/NikkyAI/495f320873ef2fa7ed567217e778d99a

see also MightyPirates/OpenComputers/issues/2867

**Comment by HenryLoenwind** [comment]
#4672
