### ISSUE TITLE
Shift Clicking with Yeta Wrench Crashes Client

### ISSUE THREAD

**Issue by SAFCxHarter** [SleepyTrousers/EnderIO#4721]
#### Issue Description:
Shift + Right Click on a Capacitor Block with a Yeta Wrench crashes the client

#### What happens:
Client crashes

#### What you expected to happen:
The Capacitor Block to drop and be able to be picked up 

#### Steps to reproduce:

1. Get a Yeta Wrench
2. Place a Capacitor Block
3. Shift + Right Click to try pick it up - CRASH!

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.24.jar
- EnderCore: EnderCore-1.12.2-0.5.22.jar
- Minecraft: 1.12.2
- Forge: forge-14.23.3.2669

#### Your most recent log file where the issue was present: 

https://pastebin.com/wyhMuhBd

**Comment by EpicSquid** [comment]
FTBUtils problem, not ours.

**Comment by SAFCxHarter** [comment]
Is this a case of reporting this to FTBUtils then?

**Comment by SAFCxHarter** [comment]
Its okay it seems that this has been fixed in the latest version of FTB Utils :D I shall close the issue
