### ISSUE TITLE
Using soulbound enchantment enchant's objects will brush many of the same items after death.

### ISSUE THREAD

**Issue by DownPower** [SleepyTrousers/EnderIO#4722]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Use the soulbound enchantment book enchanted articles BUG!

#### What you expected to happen:
Constantly refresh the items

#### Steps to reproduce:

1.http://wx2.sinaimg.cn/mw690/868a70e4gy1fsixruxxt4j20ot062adj.jpg
Can lead to unlimited brushes

The specific operation method I will present in the form of pictures

2.http://wx2.sinaimg.cn/mw690/868a70e4gy1fsixs3ym7nj20g508xmyx.jpg

The text you see is Chinese, because I am from China.

3.http://wx1.sinaimg.cn/mw690/868a70e4gy1fsixrpjdqcj20fx0990ua.jpg

And then suicide

4.http://wx1.sinaimg.cn/mw690/868a70e4gy1fsixrsfv0mj20yh02paak.jpg

After the rebirth, the knapsack will appear twice the object possessed by the devil.

5.http://wx1.sinaimg.cn/mw690/868a70e4gy1fsixs0t8xyj20ag09cglv.jpg

Constantly committing suicide, the opportunity to produce double knapsack items.

6.http://wx3.sinaimg.cn/mw690/868a70e4gy1fsixsg415zj20mi0fggmk.jpg

in server gamerule keepInventory true
I don't know if it's a mistake of Enderio or other mod. I'll give it back to Enderio author first, hoping to get a reply.

Please forgive me for English.thanks！
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.12.2-5.0.26
- EnderCore:EnderCore-1.12.2-0.5.30
Minecraft : 1.12.2 */
SpongeAPI : 7.1.0-SNAPSHOT-43d8496 */
 SpongeForge : 1.12.2-2655-7.1.0-BETA-3105 */
Minecraft Forge : 14.23.3.2655

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by mindforger** [comment]
what do you mean with "brush"? your translation is not making sense.

**Comment by Philosyang** [comment]
Didn't manage to reproduce it in my sponge server. :(
朋友你好，我在我的sponge服务器里没能重现你的这个问题...

- EnderIO: 5.0.25
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-e39726a
- SponegForge: 1.12.2-2611-7.1.0-BETA-3002
- Forge: 14.23.2.2637

**Comment by Philosyang** [comment]
@mindforger 
brush means "to replicate items in survival mode"
brush表示“在生存模式刷东西”

**Comment by Philosyang** [comment]
In case of CH to EN translation problems, mention me.
I'm willing to help here.
如果有英汉翻译问题，请@我。
我愿意提供帮助。

**Comment by mindforger** [comment]
i suppose "in server gamerule keepInventory true" is the key here, there might be somethign that sponge handles different than normal MC

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/41715151-d4be0330-7552-11e8-88ef-a225483cd1f2.png)

=> ?

Sponge?

**Comment by Philosyang** [comment]
We've (@DownPower and me) found the problem.

**Comment by DownPower** [comment]
nucleus-1.4.3-S7.0
There is still no repair, and I'll report it to nucleus.
