### ISSUE TITLE
Soul Bundler and Electric Spawner Unable to work after synthesis

### ISSUE THREAD

**Issue by umbrella22** [SleepyTrousers/EnderIO#4724]
What happens:

**Synthesizer Soul Bundler and Electric Spawner Using Synthesizer,Afterwards, it is impossible for energy to enter the machine anyway. The capacitor has been inserted and the energy wire has been used. However, in the creation mode, the machine is directly taken out, and the energy can normally enter the machine and make it work normally.**

What you expected to happen:

**This should be a bug. I hope to be able to fix this bug. It has troubled me.**

 Steps to reproduce:

**1.Synthesize them in the synthesis table
2.Insert capacitor and connecting wire
3.You see this bug**

____
 Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.30
- Minecraft: 1.12.2
- Forge: forge1.12.2-14.23.4.2707

Your most recent log file where the issue was present: 
**No crashes appear in the log file without any relevant information**

**Comment by HenryLoenwind** [comment]
Was this machine translated? If so, please post in your native language...

**Comment by umbrella22** [comment]
well ，I'm not sure if you can understand my mother tongue，I'm from China. I'm sorry that my English is very bad. The Google translation is used. Now I will redescribe it in Chinese.
这两个机器是，电动刷怪笼和灵魂绑定器（中文翻译是这样的），在使用合成台合成之后，插入电容并且接入能量线缆接入发电机或者蓄电池，但是在左侧的能量槽中并没有能量进入，而且很奇怪的是，如果是在创造模式中直接拿出来使用是完全没有问题的，即使在minecraft中将语言切换英文依旧如此，我所使用的版本已经在有说明了，谢谢您的回复。 @HenryLoenwind

**Comment by tyler489** [comment]
Did you set a mob type to the spawner?

**Comment by umbrella22** [comment]
Chinese：问题是这两台机器根本不接收电量传输，直接不工作。
English:The problem is that these two machines do not receive electricity at all and can not work.
@tyler489

**Comment by tyler489** [comment]
You  need to combine with a broken  spawner to make it spawn mobs aand accept power

**Comment by umbrella22** [comment]
**Chinese：使用的是本MOD中自带的电容器和强化能量导管
English:The capacitor is used in this MOD and the energy intensive conductor is used.**

**Chinses：这是图片我指的就是这台机器，还有灵魂绑定机，问题在于合成之后机器中是没有电的，并不是不工作，而是没有电才不工作
English:This is the picture. I mean this machine, and the soul binding machine. The problem is that after the synthesis, the machine does not accept the power transmitted from outside to it.**

![qq 20180624152302](https://user-images.githubusercontent.com/19886152/41816895-c9f1c9ec-77c2-11e8-8b9f-2b8c6c2e33de.png)
![qq 20180624152251](https://user-images.githubusercontent.com/19886152/41816899-d7bb785c-77c2-11e8-85d9-8e59f79b757a.png)
![qq 20180624152238](https://user-images.githubusercontent.com/19886152/41816900-db7d0bb8-77c2-11e8-878a-8958ceb64c1c.png)

**Comment by tyler489** [comment]
Huh

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/41824313-9aea7f6c-780e-11e8-8785-e4756238d075.png)

**Comment by umbrella22** [comment]
Oh. I see.Thank you for your guidance.........
Oh,god
In my impression, always thought that the machine had to charge before adding items, sorry~~Sorry to trouble you.
@HenryLoenwind @tyler489
