### ISSUE TITLE
Capacitor Bank I/O Display Incorrect

### ISSUE THREAD

**Issue by znxster** [SleepyTrousers/EnderIO#4726]
#### Issue Description:

The visual display of input/output on the capacitor bank adds in/out which doesn't exist. The GUI does show the correct value.

#### What happens:

Switch capacitor side to display input/output and it is invalid, it seems to have added 602 to input/output.

#### What you expected to happen:

Valid input/output displayed.

#### Steps to reproduce:

1. Put down capacitor bank
2. Hit with wrench to switch side mode
3. Value incorrect
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.24
- EnderCore: 1.12.2-0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

No logs but I caught a screenshot. https://imgur.com/a/QTVrheI

**Comment by tterrag1098** [comment]
That screenshot is accurate, `-640 + 602 = -38`. The cap bank tracks input and output separately, the tooltip shows the net gain/loss to save space.

**Comment by znxster** [comment]
Maybe I should have been more explicit .. there is 0 input.

**Comment by tyler489** [comment]
What pipes are you using? The capacitor bank is pushing out power into the pipe and also pulling into the pipe showing thay

**Comment by tterrag1098** [comment]
Yes, whatever pipes you are using must be extracting and inserting at the same time. The IO reports are completely accurate so far, only get tripped up by other mods misusing the power API, which we can't really work around.

**Comment by znxster** [comment]
I am using only EnderIO conduits. I have two of them attached (a power input and another for power output).

**Comment by znxster** [comment]
Many thanks @tyler489 / @tterrag1098 that lead me to what was wrong .. the two conduits I had were crossed over at a different point within my setup (which I had missed) and thus were indeed pushing and pulling power.
