### ISSUE TITLE
EnderIO Conduits and Thermals FluxDucts not connecting

### ISSUE THREAD

**Issue by leojaxx** [SleepyTrousers/EnderIO#4728]
#### Issue Description:
When setting up some automation I was using some EIO Conduits for the one block capabilities but when trying to connect them to my current power set up which uses FluxDucts they wouldn't connect. I ended up placing a capacitor bank between them to connect to my power.

#### What happens:
Thermal Flux Ducts and EnderIO Power Conduits don't connect

#### What you expected to happen:
The two power transfer cables to connect to each other

#### Steps to reproduce:

1.Place thermal flux duct that's recieving power
2.Try to connect Ender IO Power Conduit to flux duct
3.NO Profit :(
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 
NA

Please let me know if you need anything else. And sorry if this has been reported fixed in dev. I couldn't find a mention of it

**Comment by tyler489** [comment]
I was told this was thermal using RF and to use a buffer between them

**Comment by tterrag1098** [comment]
This is not a bug, TD ducts do not support FE. If you want them to, make a feature request there. There's nothing we can do. Using a buffer is perfectly fine.

**Comment by leojaxx** [comment]
Ya, that makes sense. Sorry, so obvious now that you pointed it out lol

**Comment by froekoe** [comment]
Bit late to the party, the workaround that I found is using a mekanism universal cable in between fluxducts and conduits
