### ISSUE TITLE
Refined Storage connection is still working after breaking Refined Storage Conduit

### ISSUE THREAD

**Issue by PanSzelescik** [SleepyTrousers/EnderIO#4730]
#### Issue Description:
Refined Storage connection is still working after breaking Refined Storage Conduit
#### Steps to reproduce:
https://youtu.be/EMiTQeel0Co
____
#### Affected Versions (Do *not* use "latest"):
Tested with:
- EnderIO: 5.0.26
- EnderCore: 0.5.31
- Refined Storage: 1.6
- Minecraft: 1.12.2
- Forge: 2613

and:
- EnderIO: 5.0.541-nightly
- EnderCore: 0.5.33
- Refined Storage: 1.6
- Minecraft: 1.12.2
- Forge: 2613

**Comment by SplitInfinitive** [comment]
does this still occur if you break the conduit in survival mode with a pickaxe?  how about dismantling it with a yeta wrench?

**Comment by PanSzelescik** [comment]
Yes, tested with Diamond Pickaxe, Yeta Wrench it works too

**Comment by EpicSquid** [comment]
Does this issue occur with RS 1.5 as well?

**Comment by PanSzelescik** [comment]
Yes, tested with 1.5.34

**Comment by EpicSquid** [comment]
Should be fixed now. If not, this issue can be reopened.
