### ISSUE TITLE
RF in Ender IO

### ISSUE THREAD

**Issue by themaster5808** [SleepyTrousers/EnderIO#4731]
#### Issue Description:
In every my world, the Ender IO mod don't use RF but µI. 

#### What happens: 
I can't use Ender IO if it uses µI

#### What you expected to happen:
You tell me how can I use RF with Ender IO

#### Steps to reproduce:

1. what
2. does
3. it means? 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 
[2018-06-26-2.log.gz](https://github.com/SleepyTrousers/EnderIO/files/2145517/2018-06-26-2.log.gz)

**Comment by themaster5808** [comment]
So i must change resource pack? But, i'm not using any resource pack. What can i do?

**Comment by VT-14** [comment]
Just hook the Ender IO machines to the "RF" things and it will work fine 99.9% of the time.  It's just a label, not a different power system.

**Comment by themaster5808** [comment]
I'll try to do this. Thank you 👍

**Comment by themaster5808** [comment]
It works!!!! oh, thank you so much! But... is there a way to make him use RF?

**Comment by tyler489** [comment]
With the exception of deaconic evolution all mods that use RF also are compatible with FE. Some might have that renamed but its still FE its a 1:1 ratio so 20 rf is 20 fe or 20u|

**Comment by VT-14** [comment]
As I said, the label can be changed by Resource Pack.  I made one to change the label to FE (which is a more standard label for mods using only Forge Energy).
https://minecraft.curseforge.com/projects/ender-io-display-fe-forge-energy

While they should always be equivalent, RF and FE are technically different power systems, so I won't release one that changes the label to RF.  That said, the relevant file is all of 10 lines and can be edited in notepad.

@tyler489  Draconic Evolution has updated and its Fusion Crafting Injectors were fixed to accept FE, so they should work now.

**Comment by tyler489** [comment]
Good to know..

**Comment by VT-14** [comment]
https://github.com/VT-14/VTs_GeneralResourcePacks/blob/master/Ender%20IO/Ender%20IO%20Display%20FE/assets/enderio/lang/en_us.lang

Find and replace FE with RF, and Forge Energy with Redstone Flux.

I would still advise getting use to new labels.  There's also Immersive Engineerings' Immersive Flux (IF), and Actually Additions Crystal Flux (CF) (neither of which are resource pack friendly).  You also have mods like Refined Storage using the FE label, and AE2 changing their "RF P2P Tunnels" to "Forge Energy Tunnels."  "RF" is somewhat outdated and will only get harder to relabel as time goes on.

**Comment by themaster5808** [comment]
Thanks so much! The Redstone Flux energy is outdated, but it's my favourite label, i don't know why XD. Bye bye

**Comment by themaster5808** [comment]
Now that I have modified the file, what should I do?

**Comment by VT-14** [comment]
Put it into your resource pack and activate the pack in game.  There are guides online, and the github that I linked to can be used as an example.

Generic resource pack support does not belong on Ender IO's issue tracker, so I'm done responding here.

**Comment by themaster5808** [comment]
Ok, thanks!
Byeeee
