### ISSUE TITLE
Farming station deletes saplings

### ISSUE THREAD

**Issue by SplitInfinitive** [SleepyTrousers/EnderIO#4732]
#### Issue Description:
Farming station deletes saplings instead of placing them.

#### What happens:
If you set up a farming station for saplings to grow trees it just deletes them.

#### What you expected to happen:
Farming station to plant the saplings

#### Steps to reproduce:

1. Place Farming station, give it power and saplings.

note: the station DOES plant saplings properly if you place a hoe of any kind in it.  It also consumes durability on the hoe.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.539
- EnderCore: 0.5.33
- Minecraft: 1.12.2
- Forge: 2705

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
What kind of trees does it matter?

**Comment by SplitInfinitive** [comment]
I've only tested it with Spruce so far

**Comment by HenryLoenwind** [comment]
caused by https://github.com/SleepyTrousers/EnderIO/issues/4262

**Comment by BenjaminD-droid** [comment]
Maybe i am a bit late, but i had the same problem, i used a dark backhoe and it often just consumed the saplings without olacing them

i figured out that if i use a diamond or obsidian hoe from actually Additions for example, it works fine! so somehow the black backhoe was the fault for me
