### ISSUE TITLE
NetworkDispatcher exception - EncoderException: String too big

### ISSUE THREAD

**Issue by Tollainmear** [SleepyTrousers/EnderIO#4733]
#### Issue Description:
client could not connect to the server, it seems like the configs pack was too big to send to client.

sorry about no more info provided, if more info needed, plz tell me what else should I provide.

BTW, is there any potential factors might cause this problem?

#### What happens:
client was kicked.

#### What you expected to happen:
client connect to the server normally

#### Steps to reproduce:

1. (BG: this is a totally new server)
2. connect to the server
3. exception appeared (see gist below plz)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- Minecraft: 1.12.2
- Forge:
  - serverside : 2705
  - clientside : 2655

#### Your most recent log file where the issue was present: 

[gist link here](https://gist.github.com/Tollainmear/ace6ccf0741d1f3bb084a7f6f033ad98)

**Comment by tyler489** [comment]
Confused as to why you think this is enderio i see nothing in the log about it being enderio. Do you have a modslist or a pack name?

**Comment by Tollainmear** [comment]
I'm sorry about that, I have seen that the exception was appear after 
>  Sending server configs to client for com.enderio.core.common.config.ConfigHandler

and here is the modlist:
Minecraft
Minecraft Coder Pack
Forge Mod Loader
Minecraft Forge
SpongeAPI
SpongeForge
AE2 Stuff
AI Improvements
Advanced Machines
Advanced Solar Panels
Applied Energistics 2
Aroma1997Core
AromaBackup
AromaBackuprecovery
Avaritia
Avaritia Tweaks
BD Lib
Better Builder's Wands
Better Questing
Better Questing Quest Book
Brandon's Core
Carry On
Chisels & Bits
CoFH Core
CoFH World
CodeChicken Lib
Compact Solar Arrays
CosmeticArmorReworked
CraftTweaker JEI Support
CraftTweaker2
CreativeCore
CreativeCoreDummy
CustomNPCs
Draconic Evolution
Ender IO
Ender IO Applied Energistics Conduits
Ender IO Base
Ender IO Conduits
Ender IO Integration with Forestry
Ender IO Integration with Tinkers' Construct
Ender IO Integration with Tinkers' Construct
Ender IO Machines
Ender IO Open Computers Conduits
Ender IO Powertools
Ender IO Refined Storage Conduits
EnderCore
Environmental Tech
Extra Utilities 2
Fast Leaf Decay
Gravitation Suite
Immersive Cables
Immersive Engineering
Immersive Petroleum
Immersive Tech
Industrial Foregoing
IndustrialCraft 2
Infernal Mobs
InstantUnify
Integration Foregoing
Iron Chest
ItemPhysic
JAOPCA
Just Enough Items
LagGoggles
MCMultiPart
MTLib
Mantle
Mekanism
MekanismGenerators
MineTweakerRecipeMaker
Mod Tweaker
NuclearCraft
OnlinePictureFrame
OreDictInit
PlusTiC
Redstone Flux
Shadowfacts' Forgelin
Sky Compression
Sky Resources 2
Standard Expansion
TOP Addons
Tesla Core Lib
Tesla Core Lib Registries
The One Probe
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Tinkers Tool Leveling
Tinkers' Construct
Tree Growing Simulator 2016
Tri-Addon Controller
Universal Modifiers
Valkyrie Compat
Valkyrie Lib
Void Island Control
Wireless Crafting Terminal 2
WorldEdit
WrapUp
p455w0rd's Library

**Comment by Tollainmear** [comment]
I apologize for my own recklessness, this is not a problem with EIO, I found that I couldn't connect to the server even I have delete the EIO.
Sorry to bother you, I'll find the problem.
