### ISSUE TITLE
Loading crash with  integrated cables.

### ISSUE THREAD

**Issue by gconlon2002** [SleepyTrousers/EnderIO#4734]
#### Issue Description:
When loading up a profile with mutiple mods this error came up with VanillaFix which is a crash mod.

#### What happens:
Simply crashed my minecraft before it loaded up. It said it was an error with all the mod intergrated cables.

#### What you expected to happen:
My minecraft to load up normally.

#### Steps to reproduce:

1. Install the Enderio mods with refined storage, AE2.
2. 
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2708

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/onijabifat.mccrash

**Comment by tyler489** [comment]
```---- Minecraft Crash Report ----
// I blame HenryLoenwind, author of EnderCore.
```
HAHAHA even minecraft blames you now henry

**Comment by EpicSquid** [comment]
Please remove vanllia fix. What it does is really bad for your game. This bug does appear to be unrelated to that, but regardless please remove vanilla fix.

**Comment by gconlon2002** [comment]
I don't really see an issue with Vanilla fix it's been good so far

**Comment by EpicSquid** [comment]
If the game is crashing there is a reason for it. Stopping the crash is like disabling the air bags in your car. Sure that means you won't get hit in the face by an air bag, but there are far worse consequences that the air bags were preventing.
