### ISSUE TITLE
Tinkers' Construct's Mattock not correctly working with Farming Station

### ISSUE THREAD

**Issue by PanSzelescik** [SleepyTrousers/EnderIO#4736]
#### Issue Description:
Tinkers' Construct's Mattock not correctly working with Farming Station. I insert Mattock (axe, hoe in one tool) to Farming Station but is working only as hoe

#### What happens:
Mattock works like a hoe, but not like an axe

#### What you expected to happen:
I expected that Mattock would act as an axe and hoe

#### Steps to reproduce:

1. Insert any Mattock
2. Insert Saplings and Seeds
3. Saplings will be planted, Seeds will be sown (it shows that it acts as a hoe)
4. When the tree grows, Farming Station shows error: No axe
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- Minecraft: 1.12.2
- Forge: 2705

#### Your most recent log file where the issue was present: 
None
[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
The Mattock only works as an axe, it is not an axe...

**Comment by PanSzelescik** [comment]
Mattock works in Farming Station as an hoe
Mattock works as hoe, axe and shovel for dirt

**Comment by tyler489** [comment]
Mattock is not coded as a shovel.. it just happens to work as one.. will havd to check to see if it is coded to work as an axe

**Comment by PanSzelescik** [comment]
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/tools/Mattock.java#L49-L52 this?

**Comment by tyler489** [comment]
Yep. They hardcode the axes drop list from what it looks like.. to make it work like an axe and a shovel but not be an axe... am i reading that right @HenryLoenwind

**Comment by HenryLoenwind** [comment]
this: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/tools/Mattock.java#L62

`this.setHarvestLevel("mattock", 0);`

An axe would have "axe" there and then work in the Farming Station.

**Comment by PanSzelescik** [comment]
But only as hoe :-)

**Comment by HenryLoenwind** [comment]
Nothing we can fix.

And btw, there is no marker for hoes, that's why we have that mile-long list of known hoes in the config...
