### ISSUE TITLE
Overuse of power when inactive

### ISSUE THREAD

**Issue by Malcator** [SleepyTrousers/EnderIO#4737]
#### What happens:
Any Machine over uses RF/I power when inactive

#### What you expected to happen:
Machine to stop drawing power when inactive

#### Steps to reproduce:

1. Place any machine
2. Connect any creative power to a cell/bank
3.  cell/bank to any machine...
4. can reproduce with industrial machine
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2 - 5.0.26
- EnderCore: .0.5.31
- Minecraft: 1.7.10
- Forge: 14.23.4.2705
- FTB Revelations
#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
![2018-07-01_17 46 56](https://user-images.githubusercontent.com/40746020/42140662-2fdb9b04-7d57-11e8-8449-c5f5d21cef5d.png)
![2018-07-01_17 47 01](https://user-images.githubusercontent.com/40746020/42140663-2ff816c6-7d57-11e8-8c05-40c63ca8c80b.png)
![2018-07-01_17 47 09](https://user-images.githubusercontent.com/40746020/42140664-302bbf94-7d57-11e8-8cb3-8d7320675f84.png)

**Comment by EpicSquid** [comment]
That not any machine, that's a simple alloy smelter. It has power loss when inactive. Upgrade to a normal alloy smelter to stop this.

**Comment by Ommina** [comment]
But (going by the screenshot), 3.2 MRF in 5s?

**Comment by AnrDaemon** [comment]
Simple machines drain 1 RF/t. Add the machine buffer size to initial powercell drain. And test more thoroughly next time, you have 3 machines connecting and god knows what the third is and how it affects the tests.

**Comment by tyler489** [comment]
Creative energy from draconic. I do believe powerloss is configurable
