### ISSUE TITLE
Power Conduits break inside of Compact Machines on chunk reload

### ISSUE THREAD

**Issue by patricide** [SleepyTrousers/EnderIO#4738]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

Ender I/O Power Conduits (specifically in this instance, the Enhanced version) do not like transferring power through between sets of Compact Machines. I'm not sure if this is a CM issue, but the error being thrown is from Ender I/O. I also tried it with power pipes from other mods (specifically, Immersive Engineering, Alternating Flux, Thermal Foundation, and XNet) and could not reproduce the error with them. 

I have an Extreme Reactors reactor inside of one Large Compact Machine. I place Ender I/O Enhanced Power Conduits to pipe power out of the RF port (making sure it is active and extracting power) and through a tunnel. The power is then relayed out of the Machine into the overworld dimension and is piped into a different Compact Machine. The power is then piped to various machines inside the Compact Machine. They work just fine when initially placed.

It seems that every time the chunk that the machines are in are unloaded, the pipes fail. When I leave my dirt and stone hovel to retrieve something and come back I have to replace the Conduits to restore the pipe. 
 It's not really a big deal, but the console kind of pitches a hissy fit over it so I figured I'd report it.

#### What happens:
Power will not be extracted or inserted when connecting power conduits between multiple Compact Machines if the chunk containing the Compact Machines is unloaded.

#### What you expected to happen:

For the power conduits to remain functional when the chunk is reloaded.

#### Steps to reproduce:

1. Build two Large Compact Machines and place them with three blocks separating them.
2. Build an Extreme Reactor reactor inside one of the Compact Machines and pipe the power out of it using Enhanced Power Conduits through a Compact Machine Tunnel.
3. Connect the Power Conduit to the appropriate face and pipe the power to the nearby Compact Machine.
4. Place various machines inside and connect them to the power network. 
5. Go far enough away that the chunks are unloaded.
6. Return. 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

https://pastebin.com/mum0Up1G

**Comment by HenryLoenwind** [comment]
Compact Machines isn't properly unloading (or loading) the chunk. Hard to say which one from just that bit of logfile, but it looks like the conduit network still exists in the world but the conduit blocks (aka bundle) do not exist anymore.

**Comment by HenryLoenwind** [comment]
fire-and-forget report
