### ISSUE TITLE
"Ender IO Conduits" component mod not launching.

### ISSUE THREAD

**Issue by Hexblood** [SleepyTrousers/EnderIO#4740]
#### Issue Description:
Minecraft does not finish Launching with "Ender IO Conduits" mod installed. 

#### What happens:
Minecraft stops launching and says that it requires "enderio 5.0.0-97e9c05 or above." (No capitals)

#### What you expected to happen:
Game to launch

#### Steps to reproduce:

1. Install Forge, Ender IO Conduits, Endercore, & JEI (All most recent) [same with more mods]
2. Launch Minecraft Instance
3. Get error (No crashing)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO Conduits: 1.12.2-5.0.0-97e9c05
- EnderCore: 1.12.2-0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2727

#### Your most recent log file where the issue was present: 
No log as game does not even finish launching.

**Comment by CitiesXL2815** [comment]
you need enderio not enderio conduits

**Comment by Hexblood** [comment]
I am trying to load a world with the brand new component mod. This is intended to be used without the full mod to my understanding.

**Comment by CitiesXL2815** [comment]
this not issue you need EnderIO main mod enderIO conduits is was for dev build only, now you need the EnderIO mod instead of EIO conduits i'm having someone to close this non issue

**Comment by EpicSquid** [comment]
You need to install enderio-base as well. I will set up the dependencies on curse better when I can.

**Comment by HenryLoenwind** [comment]
New versions with correct version numbers and dependencies are up.
