### ISSUE TITLE
Crash when loading Tracer Round with Ender IO.

### ISSUE THREAD

**Issue by Wolframme** [SleepyTrousers/EnderIO#4741]
#### Issue Description:

All I know is Minecraft does not go any further other than halfway through loading when Tracer Round conflicts with Ender IO.

#### What happens:

Crash before Minecraft fully loads.

#### What you expected to happen:

Minecraft to load.

#### Steps to reproduce:

1. Launch Minecraft.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- Tracer: 0.2

#### Your most recent log file where the issue was present: 

https://pastebin.com/xzFCaUpW

**Comment by tyler489** [comment]
Well they dont have a github... or a place to look at there code... or a way to report issues at all... im going to guess this is on them from the crash report.

**Comment by DarkStar1998** [comment]
Yes, sadly they don't at all. :/ Oh well. Thanks.

**Comment by tyler489** [comment]
https://gyazo.com/8d030cd9427a35dd28384626031d3159

**Comment by tyler489** [comment]
https://gyazo.com/81ba6cf8cd5a5aa7d030f11cf46c9014
ill wait for someone else to chime in here to confirm.. i'm still learning

it seems to me that
They import the old package crazypants.enderio.item.darksteel.ItemDarkSteelBow
The new one is crazypants.enderio.base.item.darksteel.ItemDarkSteelBow
therefore the class is not loaded and results in a Null pointer exception
(i think)

**Comment by mindforger** [comment]
sorry for poking this issue even if it is old

https://github.com/Lunatrius/Tracer/issues

isn't that their git or is this just a similar named mod?

**Comment by HenryLoenwind** [comment]
That stuff is in `com.github.lunatrius.tracer`, the crash is in `com.empiricist.tracer`, so not the same mod.

**Comment by mindforger** [comment]
yeah i already figured that is why i asked, maybe the mod had switched owner recently because i can not find this particular mod from this particular build anywhere on curse
