### ISSUE TITLE
1.12.2 Version Unusable

### ISSUE THREAD

**Issue by HardInk** [SleepyTrousers/EnderIO#4742]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

Ender IO Fatal Recipe error

#### What happens:
 Client cannot load to start screen because of error

#### What you expected to happen:
Main menu Loading

#### Steps to reproduce:

1.Clean Instalation of Minecraft and Forge
2.Place Ender IO and Ender Core into mods folder
3.Open minecraft
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.28
- EnderCore: 1.12.2-0.5.32
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

#### Your most recent log file where the issue was present: 

https://pastebin.com/CYLqbMbd

**Comment by tterrag1098** [comment]
You are out of date.

**Comment by HardInk** [comment]
How so? these are the most up to date versions available on curse.

**Comment by HenryLoenwind** [comment]
No.

![image](https://user-images.githubusercontent.com/1485873/42262769-969b453a-7f6c-11e8-9a48-36b025eac971.png)
