### ISSUE TITLE
Multiple errors in the server log

### ISSUE THREAD

**Issue by Bulldog83** [SleepyTrousers/EnderIO#4743]
#### What happens:

I have a lot of errors in the server log on start up.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

https://gist.github.com/Bulldog83/72a4d9032fb40386624cabcf15b852c3

**Comment by HenryLoenwind** [comment]
Those are not errors, those are stupid messages from Forge.
