### ISSUE TITLE
Cant Open GUI 1.12.2

### ISSUE THREAD

**Issue by DaNeo61** [SleepyTrousers/EnderIO#4753]
#### Issue Description:
While rightclicking ender IO Machines
https://youtu.be/qFarDFJWqLw

#### What happens:
Items getting duplicated in inventory

#### What you expected to happen:
Open GUI

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.29
- EnderCore: 1.12.2-0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 
https://pastebin.com/JAWCL7T9 <- Logfile
https://pastebin.com/HuWZqbud <- Modlist

**Comment by tyler489** [comment]
#4723 #4727 
related prehaps? your inventory dupes because you are in creative mode.

**Comment by DaNeo61** [comment]
Iam not the complete Video in Creative.

Complete Logfile 
https://gist.github.com/DaNeo61/2dd537e92c79bbad063cf03403b832b8

**Comment by tyler489** [comment]
[13:57:06] [Netty Client IO #3/INFO]: Attempting connection with missing mods [opencomputers|core, controlling, ctgui, ctm, custommainmenu, defaultoptions, fastleafdecay, jehc, jeresources, moreoverlays, mousetweaks, norecipebook, opencomputers, resourceloader, thaumicjei, tipthescales, twilightforest, reauth] at SERVER

these mods are causing your issue by having Server side mods on the client but not on the server

**Comment by DaNeo61** [comment]
it is funny about to see that there are only to mods was missing on Server - twilightforest and fastleafdecay.
but that is not your problem i will test it now

**Comment by DaNeo61** [comment]
issue is gone with uploading missed mods, but this is still an issue
https://github.com/SleepyTrousers/EnderIO/issues/4744
