### ISSUE TITLE
some errors while starting on spongeforge

### ISSUE THREAD

**Issue by Pa4ok** [SleepyTrousers/EnderIO#4758]
#### What happens:
errors while starting on spongeforge
start on 119 line in the log (pastebin)

#### Affected Versions (Do *not* use "latest"):
- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2705
- SpongeForge: spongeforge-1.12.2-2705-7.1.0-BETA-3266.jar

#### Your most recent log file where the issue was present: 
https://pastebin.com/bgAne029 - log
https://ibb.co/gdk96o - all mods on server

**Comment by tyler489** [comment]
Duplicate #4747
