### ISSUE TITLE
Capabilities using AttachCapabilitiesEvent

### ISSUE THREAD

**Issue by LatvianModder** [SleepyTrousers/EnderIO#4760]
![](https://i.gyazo.com/cc8e7ff2039dd1ac2782b5245b6367c0.png)

Seems like it could easily be done with hasCapablity()/getCapability() for both items and tile entities. Isn't really a problem for TileEntities, but new ItemStack instances are created constantly, especially when there is AE/RS system.

Some places where its used:

https://github.com/SleepyTrousers/EnderIO/blob/6720c7319f1c53863d74e3ca99aaadd9bc97c83b/enderio-base/src/main/java/crazypants/enderio/base/item/darksteel/upgrade/energy/EnergyUpgradePowerAdapter.java#L19-L29

https://github.com/SleepyTrousers/EnderIO/blob/f026ef9c35a56159b4fef7b6c1990055014ac61a/enderio-base/src/main/java/crazypants/enderio/base/power/forge/ForgeAdapter.java#L66-L76

- [x] DS Items
- [ ] Other Items
- [ ] Old plugable cap infrastructure
- [ ] TEs

**Comment by tterrag1098** [comment]
If we do that we move the boilerplate into the implementation, requiring any subtype of IDarkSteelItem etc to copypaste code that can be done generically in this event instead.

**Comment by HenryLoenwind** [comment]
I actually plan on doing this, the current state is a side-effect of us supporting 3 different energy systems in the past.

**Comment by HenryLoenwind** [comment]
AttachCapabilitiesEvent replaced with MixIn acouple weeks ago.
