### ISSUE TITLE
EnderIO Recipes missing... Inventory Panel and Wireless Panel in 1.12.2 

### ISSUE THREAD

**Issue by Elkinsrg** [SleepyTrousers/EnderIO#4761]
When looking through JEI and NEI I cannot locate ANY reference to the Inventory Panel, Wireless Inventory Panel, or Remote Awareness Upgrades.

See Above for "What happens"

I expected to find recipes for the above mentioned items when looking for them in the JEI and NEI lists. Having been unable to find ANY documentation on current iterations of this mod has led me to come here as the old recipes fail to work as well, for the above mentioned items.  

Steps to Reproduce:

1. Have Minecraft. Have Forge 14.23.4.2708
2. Install EnderIO 1.12.2-5.0.29 and dependencies
3. Install NEI 1.12.2-2.4.1.233-unversal and dependancies.
4. Install JEI 1.12.2-4.10.0.198 and dependencies (If any, I didn't have any)
5. Run game from launcher.
6. Select Single/Multi Player.
7.1a Run a single player game in creative, for testing purposes and ease of use OR
7.1b Run a multi player game or server featuring THE EXACT SMAE MODS.
8. Using your favorite item search method, search for ANY of the above mentioned items/blocks
9. Don't find them.
10. Check all log files (Of which none are created because there is no error)
11. Find the Git Hub and make a post like this.

Affected Versions:

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2708

No log file found, as it is not an error according to the game. The recipes/Items just don't exist.

**Comment by 63502** [comment]
All inventory panel related things have not been implemented yet.
There are no crashes here and there are no errors here.

Officially, they will get here when they get here, as answered in the following:
#4648
#4647

**Comment by Elkinsrg** [comment]
As you stated above, your issues number in the thousands so I didn't see those replies before. Thank you for pointing them out. One question though, and please pardon my ignorance, but why is it the inventory panel that ALWAYS lags behind. I remember when it first came to the mod it was only in an experimental version but was stable and worked great... Is the inventory panel really hard to code or something? Or is it the redhead step child of all of the blocks?

**Comment by EpicSquid** [comment]
Inventory panel is big enough to be it's own mod. Also the dev who originally made the inventory panel isn't around any more. I have taken over working on it, and it's mostly functional in dev, but there is still no eta on release.

**Comment by Elkinsrg** [comment]
Fair enough, I wish I knew enough to help. It's a great part of the mod. Please keep up the good work and I look forward to the outcome. I'm sure you've heard this before but I only update minecraft now when there is an enderio version for it because I feel like it adds so much to the game. Thanks again
