### ISSUE TITLE
Extremely Annoying Change - Machines Not Painted

### ISSUE THREAD

**Issue by ZippityDoodah** [SleepyTrousers/EnderIO#4762]
#### Issue Description:
In EnderIO v5.0.26 as I found in the Revelations 1.12.2 Modpack, with the major overhaul of the EnderIO machines, such as the Sag Mill, Alloy Smelter, and so forth, the machines come Unpainted when upgrading from the Simple versions. So therefore all sides except most of the front appear as checkered pink and black texture as though it has no texture for any of the non-front sides. You then have to waist time and resources creating a Paint Machine (that is also Not Painted which means making a second painting machine just to paint the first one), and then more resources making the Decoration version of the same machine, just so you can paint the machine to look like what it's looked like for years in prior versions, without the texture missing non-sense. 

The new revisions to crafting the machines are much more involved, and I can understand that aspect of the changes. But not having to go out of the way to make the machines look like what they should already look like, once crafted. Without having to make the decoration version just to make them look like what they should already look like, and have looked like for years. They should always come pre-painted to look like what they should, with the option to repaint if you want to. Seems like more of a punishment then a feature, with them missing their textures because they are unpainted right off the bat. 

If this is not actually an issue with the Mod itself, but some change incurred by the mudpack makers, then I'll bring it up to them. But it would make no sense that FTB would do that, so I assume it is a part of the EnderIO Mod version they are using and not a change made by FTB. EnderIO has been one of my favorite Mod's in most modpacks it's been in for years now. But the unnecessary steps to make a block look like what it should already default to look like, feels clunky and not befitting of what I used to consider a top rate Minecraft Mod.

Thank you for the hard work and effort you are putting into this mod.

#### What happens:
Upgraded Machines missing Texture because they default as Unpainted.

#### What you expected to happen:
Mainline machines to have the Texture they've always had for years, without having to create the decorative version of them just to paint them with the texture they should already come with.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

**Comment by tyler489** [comment]
Yeah... Enderio is not doing that.... might be a mistake in their scripts...

**Comment by bunnyman14** [comment]
This sounds like a modpack issue. Go bring it to them so they know what's going on.

**Comment by tyler489** [comment]
@HenryLoenwind When upgrading from simple to "normal" machines they get the missing texture "painted" block... the internal one you use for painting recipes

**Comment by HenryLoenwind** [comment]
We don't have any "missing texture painted" whatever...

**Comment by tyler489** [comment]
The Internal ones that appear in JEI? although i reproduce in the pack.

**Comment by HenryLoenwind** [comment]
"Not painted" is in the tooltip of all paintable blocks...

**Comment by tyler489** [comment]
Correct.. im not having any Missing textures

**Comment by ZippityDoodah** [comment]
Sorry if I sounded like I was throwing hate, as that was not my intention. I just felt very annoyed having first experienced the latest changes to EnderIO, a mod I love a lot, and having to go through the extra steps to paint the textures onto the machines I felt should have had their textures all along... And I appreciate everyone's hard work on this Mod...

Here are some screen shots:
![2018-07-10_10 36 45](https://user-images.githubusercontent.com/20649870/42528266-74b27b16-846a-11e8-856c-bd3eb1136303.png)
![2018-07-10_10 46 45](https://user-images.githubusercontent.com/20649870/42528267-74d27e52-846a-11e8-81bf-97261b574739.png)

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/2181548/latest.log)

I included the latest log file, and I hope that helps as well... If this is indeed something more to do with the Mod Pack, then just let me know, and I will take this issue to FTB instead... Thanks again...

**Comment by HenryLoenwind** [comment]
Looks like you are using a resource pack---the model of the unpainted painting machine doesn't match our model.

That texture pack broke.

**Comment by ZippityDoodah** [comment]
I don't use resource packs on any pack I play, unless it's built into the pack... I'll get with FTB regarding the issue... Thanks again...

**Comment by HenryLoenwind** [comment]
still no logfile
