### ISSUE TITLE
[1.12.2] Conduit Replace Dupe / Config Option

### ISSUE THREAD

**Issue by yepidoodles** [SleepyTrousers/EnderIO#4766]
#### Issue Description:

Conduit replace dupes the conduit being placed

This dupe only happens on the server (it is also SpongeForge, not able to test on normal forge). I know that many mod developers do not support SpongeForge, so if you are not able or willing to fix this, I only ask for a config option to disable the replace.

#### What happens:

https://i.gyazo.com/eafe88a3bee2ff89ba3edc3127b13294.mp4

#### What you expected to happen:

One is replaced with the other, and that one is used.

#### Steps to reproduce:

See GIF

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2708
- SpongeForge: 3291

#### Your most recent log file where the issue was present: 

N/A

Many thanks for your time,

~ Alice

**Comment by HenryLoenwind** [comment]
Dupe. Caused bysonge

**Comment by pie-flavor** [comment]
https://i.imgur.com/6jhZLrn.png
https://i.imgur.com/tSes8yW.png
https://github.com/SleepyTrousers/EnderIO/blob/22717941f4313ccce6faa68ac386cd2abc9d2718/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/AbstractItemConduit.java#L157

**Comment by bloodmc** [comment]
@HenryLoenwind You seem to be returning a result of `EnumActionResult.FAIL` here
https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/AbstractItemConduit.java#L157

Sponge relies on this result being returned properly. If a result of FAIL is returned, Sponge will restore the item to its previous state. You always be returning `EnumActionResult.TRUE` when using an item is successful.

**Comment by HenryLoenwind** [comment]
`Sponge will restore the item to its previous state`---so, you're doing things differently than Forge.

This is `onItemUseFirst()`, so: PASS=pass on to the next item, FAIL=end processing here, SUCCESS=end processing here+swing arm+reset animations. So, while there's no reason we don't want the arm swing *in this case*, our usage of FAIL is correct.

**Comment by bloodmc** [comment]
Regardless of animations on client, a result of `FAIL` has always meant there were no changes made.  There are no cases, that I can find, where vanilla is making changes on item use and returning a result of `FAIL` just to avoid client-side animations. And yes I know this is `onItemUseFirst` but Forge copied this from `onItemUse` so the results should be treated the same.

https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/AbstractItemConduit.java#L141-L156

This is clearly being used as changes are being made.

How about you add a check for `!world.isRemote` and return `SUCCESS`? This way you can keep avoiding swing animation on client as you want and not affect server side actions that expect a proper result of `SUCCESS`.

**Comment by tterrag1098** [comment]
Let's not argue semantics when this is clearly a bug on our end. You can see it was added accidentally here: https://github.com/SleepyTrousers/EnderIO/commit/e67a982ccd4fa9d5099bc45a41d9d809cca8fe32
