### ISSUE TITLE
Crafter disables recipes

### ISSUE THREAD

**Issue by Ludeb** [SleepyTrousers/EnderIO#4769]
#### Issue description:
The crafter do the craft automatically a couple of times and then doesn't craft anymore, just moves items from input storage to output storage.

#### What happens:
I was trying to automatize some crafts with enderio's crafter, the crafter did good job for 2 or 3 minutes and then he was just taking the items from the input inventory, moving it into his inventory and then moved it out to the output inventory.
After this happens, the craft that was suppose to be done in the crafter isn't possible to be crafted in a vanilla crafting station. Then the craft is no longer available (either in crafter and in vanilla crafting table) until a reboot of the server.
The strange thing is that JEI still shows the craft's recipe and sometimes the result of the craft can appear a semi-second.

#### What you expected to happen:
The craft was supposed to be done continuously and should remain available in vanilla crafting

#### Steps to reproduce:
1. Place a crafter with an octadic capacitor inside it
2. Configure the crafter to have a face taking items from an input inventory and place a chest on that face (the face doesn't matter just be sure to separe input inventory and output inventory to see the materials transfer)
3. Configure the crafter to have a face pushing items to an output inventory and place a chest on that face
4. Make the model of any minecraft recipe on the left panel to say which craft you want to automatize
5. Put the materials needed in the input chest and let the crafter work for a little time.
6. In a pretty short time, the crafter won't craft anymore, he will only move materials from input chest to output chest and you won't be able to do the craft in a vanilla crafting table

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2691
- Ender IO: 5.0.26
- Ender Core: 0.5.31
- Modpack: Direwolf20 (ver 1.11.0) + the following modlist: https://pastebin.com/eJCrYAKC

Does this issue occur on a server? [yes/no] yes

#### Screenshots illustrating:
Exemple trying to craft emeralds with Mystical Agriculture:
    - In the vanilla crafting table:
https://user-images.githubusercontent.com/36891279/42715893-419b61a2-86f9-11e8-8b7e-e5965201e779.PNG

    - JEI recipe for the craft of emeralds:
https://user-images.githubusercontent.com/36891279/42715912-58307ede-86f9-11e8-9137-336c0d99322d.PNG

Exemple trying to craft Energy Cube from Mekanism:
    - In a vanilla crafting table
https://user-images.githubusercontent.com/36891279/42715949-818b3f4e-86f9-11e8-9707-a31ec10f1bd5.PNG

    - JEI recipe for the craft of energy cube:
https://user-images.githubusercontent.com/36891279/42715974-a04a2e54-86f9-11e8-8548-ddc0f9f0a493.PNG

Sorry if some grammar mistakes appears, I am french and my English isn't perfect.
Sorry too if you already solved an issue of the same kind, I didn't find it when I searched.

**Comment by tyler489** [comment]
Update enderio.. you are a few versions behind. It may be fixed already.

**Comment by EpicSquid** [comment]
Fixed in the latest curseforge release.
