### ISSUE TITLE
There's no documentation on the contents of the modular add-ons

### ISSUE THREAD

**Issue by GazbonicAcid** [SleepyTrousers/EnderIO#4770]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".
ummm...
Why is there absolutely no info/documentation on the modular add-ons?
I want to read up on them before downloading...but I can't because there isn't anything about it on the wiki.

#### What happens:
No documentation on the wiki about the modular add-ons integration.

#### What you expected to happen:
Documentation on the wiki about the modular add-ons integration.

#### Steps to reproduce:

1. Go to the [wiki](https://github.com/SleepyTrousers/EnderIO/wiki)
2. Look for the documentation
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: Not applicable
- EnderCore: Not applicable
- Minecraft: Not applicable
- Forge: Not applicable

#### Your most recent log file where the issue was present: 

Not applicable

**Comment by tyler489** [comment]
If you add All the modular addons then you get the same as the main jar. You need the enderio-base and whatever addons you want.

**Comment by GazbonicAcid** [comment]
Since the modules are in the monolithic install, why is there no
documentation on the stuff in the modules?

**Comment by HenryLoenwind** [comment]
Because I saw no need to duplicate what I wrote of curseforge?

**Comment by GazbonicAcid** [comment]
Okay... So why isn't it on the module's curse forge then?

**Comment by GazbonicAcid** [comment]
I just looked at the monolithic install's curseforge, no documentation on
the stuff found in the modules.
Nothing on it in the moduler core's curseforge.
And nothing on it in the main core either.

**Comment by EpicSquid** [comment]
If you would like documentation on what ender io is, please either contribute to the wiki or watch a YouTube video. There are thousands to choose from. The modules just have parts of enderio in them and those parts are evident in their name.
