### ISSUE TITLE
RF Tools Builder does not count EnderIO Dimensional Tranceiver as valid liquid tank

### ISSUE THREAD

**Issue by LuciusV** [SleepyTrousers/EnderIO#4772]
#### Issue Description:
RF Tools Builder does not count EnderIO Dimensional Tranceiver as valid liquid tank

#### What happens:

RF Tools Builder give a message about no suitable block found

#### What you expected to happen:

RF Tools Builder pumps liquid to Dimensional Tranceiver

#### Steps to reproduce:

Put down RF Tools Builder and EnderIO Dimensional Tranceiver on top of it. Builder will be able to collect blocks and put it into Tranceiver or place blocks taking them from Tranceiver. Builder will not be able to push/push liquids (capability which Tranceiver definitely has).

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.29
- EnderCore: 1.12.2-0.5.35
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2705
- RFTools: 1.12-7.55

I posted this to RFTools tracker and McJty told that issue is not on RFTools side
https://github.com/McJtyMods/RFTools/issues/1817

**Comment by HenryLoenwind** [comment]
The Dimensional Transceiver is not a tank, it it a fluid transport system. It tries to input fluids into the builder, but as the builder also is no tank, that fails.

**Comment by LuciusV** [comment]
So, it is impossible to use one builder for both liquids and items, hence it only can work with block above it which can either be liquid tank or item container?
