### ISSUE TITLE
Thaum robe upgrade not giving vis discount for Dark/Ender armor

### ISSUE THREAD

**Issue by jestesared** [SleepyTrousers/EnderIO#4775]
#### Issue Description:
Playing in Foolcraft 3 modpack, was directed to report it here after posting on that github.
Using the Thaumuturge robes upgrade on the EnderIO armor does not actually give any kind of vis discount for Thaumcraft 6.

#### What happens:
Using the Thaumaturge robes, leggings, boots as normal gives a vis discount, but when applied as an upgrade to Dark/Ender armor, it no longer gives the discount, as it says it should.

#### What you expected to happen:
As stated, I expect applying the robes as the upgrade would give the discount as it says it would. As an aside, its a little surprising the goggles cant be applied as an upgrade to the helm.

#### Steps to reproduce:

1.Have both EnderIO and Thaumcraft 6
2.Have Dark/Ender armor with the thaumaturge upgrade
3.See that it does not give the vis discount when working in thaum
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.29
- EnderCore:1.12.2-0.5.35
- Minecraft: 1.12.2
- Forge:14.23.4.2705

#### Your most recent log file where the issue was present: 

https://gist.github.com/jestesared/76513b3dad038249c14e5a65f112b7e1

**Comment by tyler489** [comment]
Potentially fixed by https://github.com/SleepyTrousers/EnderIO/commit/0920357265de219f9b6ae1dc7f0bde735bf55e3e
