### ISSUE TITLE
[Suggestion] Please add a way to disable the repellent enchant on mobs

### ISSUE THREAD

**Issue by mcdodge34** [SleepyTrousers/EnderIO#4779]
Please, would you kindly add a way to disable that repellent enchant on mobs, makes exploring dungeons impossible and on reddit, it turns out it crashes some servers that use mob spawners with a fake player to kill the mobs (mob masher in mob grinding utils and I'm guessing probably mechanical users from ExUtils 2)

**Comment by tyler489** [comment]
Already fixed in Dev

**Comment by HenryLoenwind** [comment]
and a dupe. #4745

**Comment by mcdodge34** [comment]
Good to see this will be fixed soon, I didn't know if it was a good idea to add a config as a suggestion at the same time, turns out I was wrong.

Maybe add something on the dark suit that could protect us from this, just an idea that got in my mind, if we're wearing the full enderio armor, we could be protected from theses enchants.
