### ISSUE TITLE
Game crash with ModernConv's Energy IO

### ISSUE THREAD

**Issue by bence98** [SleepyTrousers/EnderIO#4780]
#### Issue Description:
Issue reported by 45gfg9 on the CurseForge page of my mod, [ModernConverter](https://minecraft.curseforge.com/projects/modernconverter).

The game crashes when the Energy IO tries to push ForgeEnergy into the ConduitBundle.

#### What happens:
A NullPointerException.

#### What you expected to happen:
That the conduit either takes the power or reports being full.

#### Steps to reproduce:

1. Place an Energy IO from ModernConv and give it power
2. Put it in export mode and attach an EnderIO conduit to it
3. Game crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.30
- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- ModernConverter: 2.1.1

#### Your most recent log file where the issue was present: 
https://pastebin.com/cuTPxKPY

The relevant part in ModernConverters' code:
https://pastebin.com/PRMTTKvu

**Comment by tterrag1098** [comment]
Have you verified that it is not your own variable (`proxy`) which is null?

**Comment by HenryLoenwind** [comment]
You are trying to push energy on the client. Do that on the server.

**Comment by bence98** [comment]
@tterag1098
`getForgeEnergyProxy()` is non-nullable, so that is unlikely.
@HenryLoenwind
That might be the case. I'll check once I get home.

**Comment by HenryLoenwind** [comment]
Not just "might", the crash log says `Thread: Client thread`, so I'm quite sure you are ;)

And yes, returning true from hasCap() on the client-side is bad code we have in there to allow RS conduits to work.
