### ISSUE TITLE
EnderIO - Sponge conflict?

### ISSUE THREAD

**Issue by batteryhun78** [SleepyTrousers/EnderIO#4782]
#### Issue Description:

1.12.2-5.0.29 version of EnderIO, and any Version of Sponge Forge (I did test older) makes this problem, where essentially after putting the "Sponge Forge" "mod" into the mods folder in the server,  loading it, does this problem [Tested on Direwolf 2.1.0 Server]. What's the problem exactly? EnderIO Armors, so Dark Armor and the Ender Armor With my words, it looks like, something happening with the "absorbtion" where if it's empowered and fully charged,  you less likely to get damage from mobs because of the absorbtion when your suit is powered, as it is written.  When the two "mods" are present, something happens with these armors, and I got no protection at all.  As I tested, Zombies does the same damage as if I did not wear anything. I have already asked this on Sponge [First Link] but we did not get a definite conclusion. --> [Second Link] <--- This is the log, and the debug file, from my test server, where the two "mods" were together and where the problem occured. [Direwolf20 1.12, 2.1.0]

I tested, what if I delete all the other mods.
|1| Only EnderIO [EnderIO-1.12.2-5.0.29] and EnderCore EnderCore-1.12.2-0.5.35 Without Sponge--> Works
|2| EnderIO [EnderIO-1.12.2-5.0.29], EnderCore [EnderCore-1.12.2-0.5.35] and Sponge [spongeforge-1.12.2-2705-7.1.0-BETA-3320]  With Sponge --> Doesn't work [Third link] Contains debug and log file

#### What happens:
Something with the "damage" absorbtion

#### What you expected to happen:
- that the armor works the way it should be, and as it is written.

#### Steps to reproduce:

1. Put any SpongeForge version into the mods folder
2. Start the Server
3. Test if the absorbtion works when the armor is powered. Without Sponge--> Works | With Sponge --> Doesn't work
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.29
- EnderCore: EnderCore-1.12.2-0.5.35
- Minecraft: 1.12
- Forge: 14.23.4.2732
- Sponge: spongeforge-1.12.2-2705-7.1.0-BETA-3320, 3307 - but looks like any version of Sponge will create the same issue.

#### Your most recent log file where the issue was present: 

|1| https://imgur.com/a/s8q9hBw
|2| https://drive.google.com/open?id=1XQTjknLIC9bIA2A26-F2fFAmSlQyUQsX
|3| https://drive.google.com/open?id=1nzyNU40OX5H2QTdtKCy6nNl6W8ds1ZFf

**Comment by EpicSquid** [comment]
It is sponge forge's fault almost certainly. Remove sponge forge to fix the issue, as sponge is not supported. so just use normal forge.
