### ISSUE TITLE
1.12.2 compat issue with LiteLoader

### ISSUE THREAD

**Issue by RepoDraghon** [SleepyTrousers/EnderIO#4783]
#### Issue Description:
Contacted LiteLoader's error report, no reply.
getting an error saying it can't find a recipe for the hopper
LL error page with pic
http://develop.liteloader.com/liteloader/LiteLoader/issues/55

#### What you expected to happen:
Normal startup

#### Steps to reproduce:

1. Direwolf 1.12.2 pack with other mods such as LiteLoader

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: latest
- EnderCore: latest
- Minecraft: 1.12.2
- Forge: latest

**Comment by HenryLoenwind** [comment]
https://github.com/rwtema/DietHopper/issues/5

**Comment by RepoDraghon** [comment]
it's not the same issue, ONLY when adding LiteLoader the error appears, after taking it out the game works normally again, so it's not DietHopper
