### ISSUE TITLE
DW20 2.1.0 Draconic/EnderIO Compatibility Broken

### ISSUE THREAD

**Issue by insectdude1258** [SleepyTrousers/EnderIO#4786]
#### Issue Description:
Draconic wireless energy crystal will not stay bound to or provide power to ender i/o machines, but does work with other modded machines.

#### What happens:
Upon connecting with wrench, the beam will show for about 5 seconds and then disappear. No energy will be provided to the machine.

#### What you expected to happen:
Binding wireless energy crystal to Ender I/O machines should link and provide power.

#### Steps to reproduce:

1. Set up any power source
2. Put Draconic Evolution Energy I/O Crystal (any tier) on said power source
3. Bind Draconic Evolution Energy I/O Crystal to Draconic Evolution Wireless Energy Crystal
4. Bind Wireless Energy Crystal to any Ender I/O machine that accepts power

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12/1.12.2
- Forge: 14.23.4.2707 and 14.23.4.2732

#### Detailed Explanation

In a SP world, I used a EIO creative capacitor with all tiers of I/O crystals and linked it to all tiers of wireless crystals and attempted to link them to EIO machines as well as a machine from another mod (actually additions) as a known working variable. It worked in pack version 2.0.0, and is broken in pack version 2.1.0

I have tested the mod versions. It is the Ender I/O update that caused the incompatibility.

I updated only Ender I/O (and dependencies) in the prior pack version, and was unable to link the machines. I reverted and instead updated only DE (and dependencies), and it is able to power and link fine.

The issue seems to be with the update of ender i/o and endercore to versions 5.0.29 and 0.5.35 respectively.

**Comment by tyler489** [comment]
What version of Draconic evolution are you are using.

**Comment by insectdude1258** [comment]
2.3.11.290 and 2.3.12.297. Both work with the 5.0.26 version of enderio, but not the 5.0.2.9

**Comment by HenryLoenwind** [comment]
For symptoms of the kind "other mod's block doesn't behave as expected with Ender IO" always open an issue with the other mod first. We do NOT know what that block does, or to which properties of our blocks it reacts. Only when the other mod author states what he expects can we tell if that's a bug or not.

**Comment by tyler489** [comment]
Im thinking that Brandon might have forgotten to switch to FE for the crystals.... and they are still using RF

**Comment by insectdude1258** [comment]
Henry, it was working fine until the new version of enderio. In the previous version of the pack it was working.  I manually updated only enderio and it ceased working. It's something to do with the update to that version.

**Comment by HenryLoenwind** [comment]
@insectdude1258 That still doesn't magically make me know what DE's block actually does.

**Comment by insectdude1258** [comment]
the DE wireless crystal is supposed to wirelessly transmit power from a power holding/generating device fitted with a DE I/O crystal, through the wireless crystal, and to whatever machines you then link it to.  Normally you link it to the block and you will see a red beam and power will be going to the linked machine.  Since the last update, when you go to link it, you see the read beam for a few seconds, then it goes away and no power is ever transmitted. Everything was working until the latest version of EIO.

**Comment by EpicSquid** [comment]
I have tested this before and draconic did not support FE. I have no idea how this worked before as it never worked for me before.

**Comment by tyler489** [comment]
Recently they started porting there stuff to FE... but the last change to https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/blocks/energynet/tileentity/TileCrystalDirectIO.java stats its RF exclusive.

**Comment by insectdude1258** [comment]
@tyler489 im still confused as to why everyone thinks DE is the culprit.  The energy transfer works with the old version of EIO using BOTH new and old versions of DE. But as soon as you update to the new version of EIO, it no longer works with either version of DE.  Updating DE by itself does not break it, only when updating EIO.  Something had to of changed in EIO then right?

**Comment by EpicSquid** [comment]
I will try testing again. But last time I used any version of DE this did not work. And it is valid to say that since DE is using Rf not FE it may not work and it is on them.

**Comment by insectdude1258** [comment]
@EpicSquid if the problem is RF vs FE then why does it accept power just fine when using a draconic I/O crystal attached to the machine?  It's only with the wireless that it doesn't work anymore.  Notice in picture the blue line shows power going to the I/O crystal and the capacitors show they are getting power from it.  The red line shows the wireless link, which disappears after a few seconds and  provides no power.
![2018-07-26_13 28 51](https://user-images.githubusercontent.com/24449926/43286815-f81a28f4-90d7-11e8-8e21-b08ee34b899d.png)

**Comment by insectdude1258** [comment]
Here is the 2.0 version of DW20s pack. As you can see, the wireless link is indeed providing power to the capacitor without the need of an I/O crystal to receive.
![2018-07-26_13 46 20](https://user-images.githubusercontent.com/24449926/43287575-4f8fa6de-90da-11e8-95d1-eb3ef7a9fe78.png)
