### ISSUE TITLE
Multiplayer client freeze tied to water and darksteel boots with flippers enhancement

### ISSUE THREAD

**Issue by Attrael** [SleepyTrousers/EnderIO#4789]
#### Issue Description:
Minecraft client freeze in multiplayer tied to darksteel boots with flippers enhancement.

#### What happens:
On a multiplayer server, if there is a player wearing darksteel boots enhanced with the "flippers" ability, that player jumping in and out of water will randomly trigger a client freeze for anyone who is nearby.  This doesn't produce an actual crash or log message on either the client or the server end.  You have to end task the frozen client and restart it to get that player back in the game.  But if the player wearing the boots continues to jump in and out of water, the freeze will just occur again.

#### What you expected to happen:
The client shouldn't freeze up on other players.

#### Steps to reproduce: (Note: all this is done in survival mode)

1. Have one player wearing darksteel boots enhanced with the "flippers" enhancement.  In my case, I was wearing darksteel boots that were Empowered IV, Jump III, and had the "flippers" enhancement.  The player doing it to me (for testing) was using Empowered III, Jump III, flippers enhanced darksteel boots.
2. Have the other player pace back and forth nearby on land.
3. Take a bucket of water and drop down the source block.
4. Hop in and out of the water.  Jumping in place, hoping in and out, pick up the water and move it slightly letting it push you a bit, hop around some more.  Generally interact with the water in such a way that the game thinks you are constantly entering and exiting water.

Eventually (Only takes a minute or two in my testing) the other players client will visually freeze.  Their music still plays, and the server still thinks they are connected, but graphically the client is frozen and no longer responding such that the player just stands still in the game (and if also in water, will drown) until you forcefully terminate the frozen client.

We are currently working around this issue by stowing away our "flippers" enhanced boots in a chest and using darksteel boots without that enhancement.  So long as the boots don't have "flippers", this freeze can't be triggered in other players any longer.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.29
- EnderCore: 1.12.2-0.5.35
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2726

Other mods in use (I had gone through the process of painstakingly removing mods one at a time and retesting trying to pin this one down. Upon finding the crash still ocurred after removing a mod, I'd restore the server files from backup, put back the removed mod and try removing another one.  Freeze ceased after removing EnderIO which allowed me to focus more on it):

AbyssalCraft Integration: 1.12.2-1.6.4
AbyssalCraft: 1.12.2-1.9.4.10
Applied Energistics 2: rv5-stable-11
Baubles: 1.12-1.5.2
BiblioCraft: v2.4.5 for MC1.12.2
BloodMagic: 1.12.2-2.2.12-97
Bookshelf: 1.12.2-2.3.552 (I have all dictionary changes for this mod disabled in config. It's only needed for the elevator block mod)
Chisel: 1.12.2-0.2.0.31
Chisels And Bits: 14.17
Code Chicken Lib: 1.12.2-3.1.9.344-universal
CoFHCore: 1.12.2-4.5.2.19
CoFHWorld: 1.12.2-1.2.0.5
Connected Textures Mod: MC1.12.2-0.3.1.16
Elevator Block Mod: 1.12.2-1.3.6
Extra Utils 2: 1.12-1.7.6
GalacticraftCore: 1.12.2-4.0.1.181
GalacticraftPlanets: 1.12.2-4.0.1.181
GuideAPI: 1.12-2.1.5-60
Improved Backpacks: 1.12.2-1.2.0.3
IndustrialCraft: 2-2.8.73-ex112
Inventory Pets: 1.12-1.5.2
Iron Chest: 1.12.2-7.0.40.824
Just Enough Items: 1.12.2-4.11.0.202
Mantle: 1.12-1.3.2.24
MC MultiPart: 2.5.1
Mekanism: 1.12.2-9.4.13.349
MicdoodleCore: 1.12.2-4.0.1.181
Redstone Flux: 1.12-2.0.2.3-universal
Tinkers Construct: 1.12.2-2.10.1.87
The Betweenlands: 3.3.10-universal
Thermal Expansion: 1.12.2-5.5.0.29
Thermal Foundation: 1.12.2-2.5.0.19
Twilight Forest: 1.12.2-3.7.424-universal

#### Your most recent log file where the issue was present: 

This is a complete client freeze up (graphically anyways).  No log output is generated to give any hints as to a crash.  Process has to be terminated manually.

**Comment by tyler489** [comment]
#4715 
but with how to reproduce... Thanks
