### ISSUE TITLE
[1.12.2][Suggestion][Bug MAYBE]Sticky Mode works a little bit funny

### ISSUE THREAD

**Issue by zilla0088** [SleepyTrousers/EnderIO#4795]
Hi guys. I so glad Ender io make its way to 1.12. I use your mod all the time as I'm playing modded minecraft, and your mod make life (lives) sooo much easier;)

I found a funny fact about Adv Filter's Sticky Mode, not sure if it's a bug or you guys intended to make it so:

If someone set up a item conduit system with one input, one default-setting output, and one STICKY output, someone should found items always go to the sticky one. However, when items can't go into the sticky one (a full chest etc), they WILL GO INTO THE DEFAULT ONE.

I can't recall how Sticky Mode use to work, but in my thought(or imagination), Sticky Mode should prevent items go into any other non-sticky output. If the sticky ones are null, items should stay where they are, rather then move, as it's described. I thick the present Sticky Mode makes listed items owns the highest priorities, and when Sticky Mode failed , items look for the lower priority ends to go.

That's not very STICKY to me;) And I thick Sticky Mode should prevent items moves to non-sticky ends. 

Have a good day!

**Comment by tyler489** [comment]
i think he wants say all pistons to go to the sticky output and when that chest is full not to go to the non filtered output.... a simple solution would be to add a filter to the second output with a blacklist of the sticky items

**Comment by zilla0088** [comment]
Of cause I can put a black list in the second output to make it work, that why I said it's a suggestion rathe than a bug report.

I only want sticky mode fit the description, but not just works like a priority-overwrite. Just sayin', no hard feeling plz.

Thinks for your patience while reading, I don't write in English very often.
And thanks for the tag! I can't figure out how to add one using mobile phone;)

**Comment by zilla0088** [comment]
Of cause I can put a black list in the second output to make it work, that why I said it's a suggestion rathe than a bug report.

I only want sticky mode fit the description, but not just works like a priority-overwrite. Just sayin', no hard feeling plz.

Thinks for your patience while reading, I don't write in English very often.
And thanks for the tag! I can't figure out how to add one using mobile phone;)

**Comment by tterrag1098** [comment]
@tyler489 In that situation it would still be equivalent to just disconnect the second output. Unless either output is filtered, sticky mode has no use. "Only put items in this output and no others" is the same as only having one output.

**Comment by EpicSquid** [comment]
Not a bug, and sticky mode will be staying as is for now.
