### ISSUE TITLE
[1.12.2][Bug] Farming Station deleting contents when used with Natura crops.

### ISSUE THREAD

**Issue by Yamza** [SleepyTrousers/EnderIO#4796]
#### Issue Description:
EnderIO Farming Station deletes its contents (Capacitor, tool, and harvest crops) when used to harvest Natura crops.

Modpack: ATM3
EnderIO Ver: 1.12.2-5.0.26
Natura Ver: 1.12.2-4.3.2.49
Reported to ATM GitHUB: https://github.com/AllTheMods/ATM-3/issues/685

#### What happens:
EnderIO Farming Station deletes its contents (Capacitor, tool, and harvest crops) when used to harvest Natura crops.

#### What you expected to happen:
Farming crops without deleting machine contents.

#### Steps to reproduce:
1. Set up EnderIO farming station.
2. Plant Natura seeds (cotton, barley)
3. Wait for crop to be harvested.
4. When crop is harvested, machines' contents are wiped.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 1.12.2-2.4.2.60-universal

#### Your most recent log file where the issue was present: 
No Crash.

**Comment by tyler489** [comment]
Please update enderio.

**Comment by Pirateboy04** [comment]
The same thing happened to me in with:
EnderIO: 1.12.2-5.0.29
EnderCore: 1.12.2-0.5.35
Minecraft: 1.12.2
Forge: 14.23.4.27.39
Natura: 1.12.2-4.3.2.49

I did get a crash log, with no crash (for some reason). It is attached below.
[enderio_bug.txt](https://github.com/SleepyTrousers/EnderIO/files/2234436/enderio_bug.txt)

**Comment by tyler489** [comment]
Thats a different crash. Also Report it to the Pack dev and ask them to update to V 29

**Comment by HenryLoenwind** [comment]
no response from op
