### ISSUE TITLE
Farming station bugs

### ISSUE THREAD

**Issue by tyler489** [SleepyTrousers/EnderIO#4797]
#### Issue Description:

1) Axes with "fork" upgrade go in the hoe slot but do not get used as a hoe
1) Axes that are empowered use Durrability AND power
1) When planting saplings HOE is used
1) Farming Station displays No power when no capacitor is installed
1) when using an octodatic capacitor then clicking the machine with a basic capacitor the range of the farming station is not decreased till the machine is broken and replaced

- EnderIO:v29
- EnderCore:v35
- Minecraft: 1.2.12
- Forge: 2739

**Comment by HenryLoenwind** [comment]
1) Farming Station has no special support for DS tools => new feature
1) DS tools only have a chance of using power instead of durability. Are you sure that's not what you're seeing here?
1) It would use its hands if it had some...
1) Energy buffer size is 0, so this is technically correct
1) To be investigated, probably a bug

**Comment by tyler489** [comment]
1. Ok
2. it was using both power and durrability in the same tick
3. Fair.... 
4. would it be possible to display no capacitor
5. Yay 1/5

**Comment by HenryLoenwind** [comment]
re 2: I'll have a look
re 4: yes, => new feature

**Comment by VT-14** [comment]
Using a Chest and telling the Farming Station to input from that side also exceeds the stack limit for Bonemeal, so I would assume it's with the Farming Station.

**Comment by HenryLoenwind** [comment]
The issue with the fertilizer slots is the other way around. Fertilizer slots are not limited, but IInventory doesn't support limits per slot, only one global limit for the whole inventory.

Changed the GUI to bypass IInventory and talk to the machine directly.
