### ISSUE TITLE
Vanilla Items lost Aspects Thaumcraft-BETA.17/Thermal Foundation/Ender IO

### ISSUE THREAD

**Issue by Descus** [SleepyTrousers/EnderIO#4799]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:
Items like Snow/Ice, Rotten Flesh, Coal are loosing thaumcraft Aspects when Thermal Foundation / Ender IO/ Thaumcraft are installed

#### What you expected to happen:
Items to keep the Aspects

#### Steps to reproduce:

1.Removed all mods instead of Thaumcraft
2.Found that Thermal Foundation is involved
3.Tried to reproduce with Thermal foundation (didn't work)
4. added more mods till Ender IO (worked 100%)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.27.29
- Thaumcraft: 6.1.BETA17
- ThermalFoundation: 2.5.0.19

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/En3YtBpk

**Comment by HenryLoenwind** [comment]
#4688
