### ISSUE TITLE
Crash on cobblestone recipes

### ISSUE THREAD

**Issue by Kilmatar** [SleepyTrousers/EnderIO#4801]
#### Issue Description:
Cobblestone placed in Thermal Expansion's crusher.
Mouse over cobblestone and R pressed

#### What happens:
Minecraft crashes

#### What you expected to happen:
JEI recipes opened

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.29
- EnderCore: 1.12.2-0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
Yandex Disk link: https://yadi.sk/i/mkM8pb9a3ZZyu9

**Comment by tyler489** [comment]
Duplicate #4755
