### ISSUE TITLE
Concussion creepers teleporting is buggy/not behaving as expected

### ISSUE THREAD

**Issue by SplitInfinitive** [SleepyTrousers/EnderIO#4804]
#### Issue Description:
Concussion creepers currently teleport players larger then the config values allow for (assuming that the number in the config is blocks).

Concussion creepers also teleport players into lava/oil/water/other fluids and I understand that they shouldn't be doing that.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.600
- EnderCore: 0.5.36+
- Minecraft: 1.12.2
- Forge: 2705
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? server

**Comment by HenryLoenwind** [comment]
For the distance: https://www.javamex.com/tutorials/random_numbers/gaussian_distribution_2.shtml

**Comment by HenryLoenwind** [comment]
target check will include fluids in the next release
