### ISSUE TITLE
Setting up a Development environment fails

### ISSUE THREAD

**Issue by f03n1x** [SleepyTrousers/EnderIO#4809]
#### Issue Description:

I'm trying to setup a development environment for the mod, but I'm unable to due to do so, due to dependencies not being downloaded. I'm new to minecraft mod development so forgive me if I've set it up wrong but I've followed steps that I've found to setup the forge mod development environment and that worked fine.
 
#### What happens:

Command prompt shows all errors mid way during the installation.

#### What you expected to happen:

The development environment to be setup.

#### Steps to reproduce:

1. Download or clone the repo
2. Go to command prompt change directory to the source file location
3. type gradlew.bat setupDecompworkspace and hit enter

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: Latest commit 0dc8cc1 (currently up to date repo)
- EnderCore: Latest commit 0dc8cc1 (currently up to date repo)
- Minecraft: N/A
- Forge: N/A
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? N/A

#### Your most recent log file where the issue was present: 

https://pastebin.com/YhiZ5AJR

**Comment by EpicSquid** [comment]
Hey f03n1x, glad you want to help out with the mod! To get started, check out our setup guide here:
https://github.com/SleepyTrousers/EnderCore/wiki/Developer-Setup-Guide

I would also highly recommend coming to our discord to chat to us about development and helping out with ender io. You can find it here. https://discord.gg/sgYk3Jr

Jump on discord if you need any more assistance.
