### ISSUE TITLE
Looking up uses with hotkey in JEI crashes game

### ISSUE THREAD

**Issue by Syltann** [SleepyTrousers/EnderIO#4810]
#### What happens:

Game crashes while looking up uses in JEI (this time in the painting machine section). 

This has been happening quite a bit, in multiple packs, not just mine (current crash).
I remember hitting "uses" hotkey for simple machines to lookup recipes and have experienced same crash.

#### What you expected to happen:

Uses to show up without crash.

#### Steps to reproduce:

Hit uses hotkey on fluiduct and it pulled up JEI to the crafting section. 
When I click on the "painting machine" section this crashes game.

____
#### Affected Versions:

- EnderIO:  EnderIO-1.12.2-5.0.29
- EnderCore:  EnderCore-1.12.2-0.5.35
- Minecraft: 1.12.2
- Forge: forge-14.23.4.2739
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 

Crash 1: https://pastebin.com/TA5myze1
Crash 2 (latest): https://pastebin.com/L1b1vkLg

**Comment by EpicSquid** [comment]
It appears that the duct from thermal does not render correctly in the painting machine when it is used to paint a block. I believe this is most likely not our fault, however it could simply be an issue with mod interaction. Can you please open an issue there as well? 

Simplest solution for now will be to go into the config for Ender IO and disable the ability to use TileEntities in the painting machine.

**Comment by Syltann** [comment]
Thanks, and will do.

**Comment by Y0ungSandwich** [comment]
Same issue with Mech & Magic on ATLauncher/Twitch version 3.0.6
https://www.atlauncher.com/pack/MechMagic

Affected Versions:
EnderIO: EnderIO-1.12.2-5.0.29
EnderCore: EnderCore-1.12.2-0.5.35
Minecraft: 1.12.2
Forge: forge-14.23.4.2705
SpongeForge? yes
Optifine? no
Single Player and/or Server? Both
Your most recent log file where the issue was present:
https://pastebin.com/aNjCWqka

**Comment by HenryLoenwind** [comment]
This means that Thermal Expansion uses a bad custom model. Forge added an embedded sprite a couple of months back and they didn't adapt to that change.

**Comment by scalda** [comment]
https://github.com/scalda/Foolcraft_3/issues/234

**Comment by Microjet86** [comment]
https://github.com/CoFH/Feedback/issues/1231 covers1624 appears to be requesting that the ender io painting machine simply stop trying to paint ducts.

**Comment by tyler489** [comment]
Nope.. they return null on something that cant be null. Should be fixed on there end.

**Comment by Microjet86** [comment]
Just at a glance,
I see the Adapt to forge changes issue that was referenced xnet cables have the same problem where getParticleTexture() is called, I assume there are probably quite a few other blocks with custom models causing the same problem if they don't allow "something" to be returned by the called method above. 
Correct me if wrong, but I feel like ender io being the only one to try to force this method be used properly may not be enough pressure to correct the problem as a whole, Could put more pressure on by scanning for all textures during start up lol... seriously though I'm coming up short on how to properly address this without removing the pressure on other mods to update entirely.
