### ISSUE TITLE
Advanced Filter doesn't recognize IC2 Heat Exchanger Durability

### ISSUE THREAD

**Issue by miliapassum** [SleepyTrousers/EnderIO#4811]
#### Issue Description:

The Advanced Filter doesn't recognize the IC2 Heat Exchanger durability when i try to extract it into another chest/inventory.

#### What happens:

The Heat Exchanger stays in the chest whether i set the damage to More than 70%/50%/25% Damaged. It will only extract the item if the setting is set to Up to #% Damage totally ignoring item damage, I guess thats another problem.

![2018-07-30_00 08 12](https://user-images.githubusercontent.com/41884883/43378667-f522839a-938d-11e8-9fa6-d1d012912e88.png)

#### What you expected to happen:

Have the Heat Exchanger extracted into another chest/inventory.

#### Steps to reproduce:

1. Add the Heat Exchanger to the filter with the option Whitelist, More than 70%/50%/25% Damage.
2. Place the Heat Exchanger into the chest.

![2018-07-30_00 07 39](https://user-images.githubusercontent.com/41884883/43378665-f50aa162-938d-11e8-873d-8ff898adcda4.png)
____
#### Affected Versions:

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- SpongeForge? no
- Optifine? yes HD_U_E2
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

https://gist.github.com/miliapassum/993d35dc78cdf5a27923c3eebf9aa571

**Comment by HenryLoenwind** [comment]
Please enable advanced tooltips (F3-K ?) and have a look at the item to see if it has item damage.

**Comment by HenryLoenwind** [comment]
ok, I need to have a detailed look at that item in a dev environment. From the tooltip it is not clear if that is real durability or just some text added by the item.

**Comment by miliapassum** [comment]
yeah, the pickaxe does show 2 Durability indicators as the HE only 1, thank you

**Comment by miliapassum** [comment]
so i guess its not an ender io problem but IC2's, maybe the conduit wont extract the item because there is not damage/durability to look at

**Comment by HenryLoenwind** [comment]
Yes, IC2 items don't have "real" durability.
