### ISSUE TITLE
Crash with looking up JEI item usage

### ISSUE THREAD

**Issue by Artinaix** [SleepyTrousers/EnderIO#4812]
#### Issue Description:

When I look at an items uses, like a wooden slab for example, I get a crash that I suspect is because of the painter as the crash log seems to show, it appears to error with a liquid from tech reborn. (I will most likely make an issue report on their issue tracker aswell)

Unsure if this is the same as [this issue](https://github.com/SleepyTrousers/EnderIO/issues/4810) as the crashes seem to originate from the painter, but seem to be for different reasons.

I have already tried to set:
```
# When enabled blocks with tile entities (e.g. machines) can be used as paint targets. (synced from server) [default: true]
        B:allowTileEntitiesAsPaintSource=false
```
and

```
# If true, only a handful of sample painter recipes will be shown in JEI. Enable this if you have timing problems starting a world or logging into a server. [default: true]
    B:jeiUseShortenedPainterRecipes=false
```
to false for a possible fix to no avail.

#### What happens:

The games crashes right upon trying to look as uses of an item with JEI

#### What you expected to happen:

To show me uses without crashing

#### Steps to reproduce:

1. have tech reborn installed along with JEI and ender io
2. Open up JEI
3. Look for uses on a wooded slab (or others, haven't tested on others as of yet)

____
#### Affected Versions:

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 

[Latest Log](https://gist.github.com/Artinaix/9876fe3ff3bf1fd276cc70241cb15d03)

**Comment by tyler489** [comment]
Dulpicate #4744 

You were close

**Comment by HenryLoenwind** [comment]
Read the error message and don't shoot the messenger.

> java.lang.RuntimeException: Fluid nc.fluid.FluidCoolant@6d120ce3 (redstone_nak, class nc.fluid.FluidCoolant) from item 1xitem.techreborn.cell@0 returned an unregistered block from getBlock(). This is a major bug in the mod that fluid belongs to.

**Comment by tyler489** [comment]
You can fix this by going into the nuclearcraft config and enabling fluid blocks... but backup your world first...  the next update of nuclearcraft should have this fixed whenever it releases.
