### ISSUE TITLE
Weird crash on new version of EnderIO

### ISSUE THREAD

**Issue by TacticalUniverse** [SleepyTrousers/EnderIO#4816]
#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first. If you are using an unreleased version of Ender IO (a.k.a development/nightly version), please don't open an issue for features that have not been announced as "finished" or "working". Expect to be ignored if you ignore this template.

#### What happens:
When I launch my custom Modpack with the new updated version of EnderIo that was released yesterday that I get an error message telling me bad File = Capacitor_machines.xml

Error Message 'key' 'enderio:block_stirling_generator/burntime' is invalid.

#### What you expected to happen:
Some kind of way to fix it as I have no clue and I try removing the Capacitor_machine.xml and that did nothing.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.30.jar
- EnderCore: 1.12.2-0.5.37.jar
- Minecraft: 1.12.2
- Forge: 1.12.2 14.23.4.2747
- SpongeForge? yes/no no
- Optifine? yes/no no
- Single Player and/or Server? single player as of right now

#### Your most recent log file where the issue was present: 
https://gist.github.com/TacticalUniverse/215479a75abc09e313ee15d620498a00
Have fun reading this but it is huge so good luck
[pastebin/gist/etc link here]

**Comment by TacticalUniverse** [comment]
what log file missing lol

**Comment by TacticalUniverse** [comment]
Hopefully this can be fix asap or my custom pack is screwed cause I need to get on to fix other things with the pack.

**Comment by HenryLoenwind** [comment]
You have an old copy of the file capacitor_machines.xml in your user recipes. Fix it,
