### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Ezoteric** [SleepyTrousers/EnderIO#4819]
Plz make a config option for the new repellent enchant.

If mobs have them on gear you get ported to places you dont wanna visit :p 
Besides its also very OP to have yourself :p 

Thnx for the great mod and keeping it alive.

PS: love the new Gear

**Comment by HenryLoenwind** [comment]
Please ask @LexManos about making config options to not register enchantments.

**Comment by tyler489** [comment]
Also.. try updating enderio

**Comment by Ezoteric** [comment]
Ah thnx a lot ill use update :) will at least solve the mob problem :)
