### ISSUE TITLE
MC Version 1.12.2 EIO version 5.0.31

### ISSUE THREAD

**Issue by Vercalos** [SleepyTrousers/EnderIO#4820]
#### Issue Description:

Doors cannot be placed on block detectors

#### What happens:

Doors will either drop as item (entity) in the case of a vanilla door, or normal mod-added door, or in the case of MalisisDoors' Custom Door, vanish.

#### What you expected to happen:

To be able to place a door on top of the Block Detector, and for it to open when a block is in front of the detector.

#### Steps to reproduce:

1. Place a Block Detector
2. Place a Door on Block Detector
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.29 & 5.0.31 are the versions I tried
- EnderCore: 1.12.2-0.5.37
- Minecraft: 1.12.2 
- Forge: 14.23.4.2739
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

I have included a log on pastebin, but please note you'll not find anything relevant there, as the issue does not generate anything in the log.
https://pastebin.com/jnt1AmPD

**Comment by HenryLoenwind** [comment]
Detector blocks are only solid on the underside...
