### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot set property PropertyDirection on block randomthings:plate_extraction

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [SleepyTrousers/EnderIO#4822]
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 2745
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? idk

#### Your most recent log file where the issue was present: 

https://pastebin.com/zWLFxeZ6

**Comment by HenryLoenwind** [comment]
Stop shooting the messenger.
