### ISSUE TITLE
Server startup log spammed with NoSuchMethodException errors using Forge-1.12.2-14.23.4.2747

### ISSUE THREAD

**Issue by CatRabbit499** [SleepyTrousers/EnderIO#4823]
#### Issue Description:

Startup log spammed with NoSuchMethodException errors when using only EnderIO/EnderCore with Forge-1.12.2-14.23.4.2747

#### What happens:

Startup log displays
`[Server thread/WARN] [FML]: The declared version check handler method checkModLists on network mod id enderio is not accessible`
followed by a NoSuchMethodError:
`java.lang.NoSuchMethodException: crazypants.enderio.base.EnderIO.checkModLists(java.util.Map, net.minecraftforge.fml.relauncher.Side)`
and iterates through the same WARN statement and NSME for all EnderIO integrations/powertools/etc.

#### What you expected to happen:

Server starts up with EnderIO and EnderCore active with no errors

#### Steps to reproduce:

1. Install forge server into folder on desktop using forge-1.12.2-14.23.4.2747-installer-win.exe
2. Add EnderCore-1.12.2-0.5.37.jar and EnderIO-1.12.2-5.0.31.jar to mods folder
3. Start server with batch file:
```
@echo off
java -jar forge-1.12.2-14.23.4.2747-universal.jar nogui
pause
```
4. On startup, NSME and WARN statements spam the log

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.31
- EnderCore: EnderCore-1.12.2-0.5.37
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.4.2747-universal
- SpongeForge? no
- Optifine? no
- Single Player and/or Server:  localhost dedicated server (run from desktop)

#### Your most recent log file where the issue was present: 

https://pastebin.com/MtLkDjpi

**Comment by tyler489** [comment]
Duplicate https://github.com/SleepyTrousers/EnderIO/issues/4747
