### ISSUE TITLE
Minecraft 1.12.2 Crash with ender IO

### ISSUE THREAD

**Issue by GmanAtheist** [SleepyTrousers/EnderIO#4825]
#### Issue Description:

Minecraft 1.12.2 crash With latest Ender IO. Error -1. Crash report at bottom. 

#### What happens:
Crash on start up

#### Steps to reproduce:

1.Start Minecraft 1.12.2 
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.31
- EnderCore: EnderCore-1.12.2-0.5.37
- Minecraft: PC Java 1.12.2
- Forge: 14.23.4.2747
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

http://nellspace.co.uk/share/Crash%20report%20Minecraft%201.12.2.txt

**Comment by VT-14** [comment]
Ender IO isn't even installed in that crash log.

The stacktrace is mentioning Ancient Warfare and Chisels and Bits.

Also, it says OptiFine_1.12.2_HD_U_E1 is installed.

**Comment by tyler489** [comment]
1. Try without optifine
2. Enderio does not appear in that stacktrace at all.. its all anchient warfare and chisel and bits

**Comment by GmanAtheist** [comment]
OK. Sorry. That was a older report. I have now got it running fine. The problem was Thermal foundation. Still trying to sort that one. Thanks for the comments. Much appreciated. Have a great day. :-)
