### ISSUE TITLE
Searching Cobblestone, with JEI, EnderIO, and FactoryTech? installed

### ISSUE THREAD

**Issue by CrankySupertoon01** [SleepyTrousers/EnderIO#4828]
#### Issue Description:

I am the modpack author of Project Sky, i just got an issue about cobblestone, searching it with JEI and it crashing you.

#### What happens:

You search cobblestone in jei i guess and its a crash, maybe you hit U, but idk what he said because he didnt explain it well

#### What you expected to happen:

See the cobblestone recipe

#### Steps to reproduce:

1. Open JEI
2. Search Cobblestone
3. Hit U, or maybe R
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: .30
- EnderCore: .37
- Minecraft: 1.12.2
- Forge: 2739
- FactoryTech: 1.5.3
- JEI: .206
- SpongeForge? no
- Optifine? no
- Single Player yes

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/mavuhaluho.mccrash

**Comment by VT-14** [comment]
Looks like this may be #4755 again.

**Comment by CrankySupertoon01** [comment]
its different mods

**Comment by CrankySupertoon01** [comment]
https://github.com/mezz/JustEnoughItems/issues/1318
https://gitlab.com/dalapo/FactoryTech/issues/26

**Comment by HenryLoenwind** [comment]
We don't need a ticket for every buggy mod...

Also, why did you open this ticket in the first place? Ender IO tells you that factech has a bug and and you report that as a bug in Ender IO?
