### ISSUE TITLE
crashed game at startup

### ISSUE THREAD

**Issue by KiraLinux** [SleepyTrousers/EnderIO#4829]
#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO-base-1.12.2-5.0.642-nightly
EnderIO-conduits-1.12.2-5.0.642-nightly
EnderIO-conduits-appliedenergistics-1.12.2-5.0.642-nightly
EnderIO-endergy-1.12.2-5.0.642-nightly
EnderIO-integration-forestry-1.12.2-5.0.642-nightly
EnderIO-integration-tic-1.12.2-5.0.642-nightly
EnderIO-invpanel-1.12.2-5.0.642-nightly
EnderIO-machines-1.12.2-5.0.642-nightly
EnderIO-zoo-1.12.2-5.0.642-nightly

- EnderCore-1.12.2-0.5.37
- Minecraft: 1.12.2
- 1.12.2-forge1.12.2-14.23.4.2738
- SpongeForge? what it is?
- Optifine? yes
- Single Player 

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/QYRiaRwF
https://pastebin.com/ujyz8BVv

**Comment by KiraLinux** [comment]
With what software a problem?

**Comment by HenryLoenwind** [comment]
cofh is duplicating vanilla functionality under the *same name*. Very easy to select the wrong one...
