### ISSUE TITLE
Fluid Filter Issues

### ISSUE THREAD

**Issue by NillerMedDild** [SleepyTrousers/EnderIO#4831]
#### Issue Description:

Fluid Filters in Ender Fluid Conduits can not be configured, unless the block the Ender Fluid Conduit is in, contains other Conduit connections.

For example, if only Ender Fluid Conduits connect to a Fluid Tank, the option will not be displayed:
![billede](https://user-images.githubusercontent.com/21295394/43955317-d4ac5d00-9c9f-11e8-84e9-4155ce7b172a.png)
If an Item Conduit is placed in the same block as the Ender Fluid Conduit, the option will be displayed:
![billede](https://user-images.githubusercontent.com/21295394/43955343-f9e908f2-9c9f-11e8-9c6f-2174fcbadf3e.png)

#### What happens:
Fluid Filter cannot be configured when it's the only connection on that side, in the block.

#### What you expected to happen:
To always be able to configure the Fluid Filter

#### Steps to reproduce:

1. Place Ender Fluid Conduit next to a Fluid Tank
2. Insert Fluid Filter, observe
3. Place Item Conduit, look again
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.30
- EnderCore: 1.12.2-0.5.37
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2739
- SpongeForge? no
- Optifine? no
- Single Player and/or Server?
Single Player, have not tested server
#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by EpicSquid** [comment]
Please update ender io and confirm if this is still the case

**Comment by NillerMedDild** [comment]
Confirmed in `EnderIO-1.12.2-5.0.31`

**Comment by BadLucKWyvern** [comment]
I have noticed that holding the filter in your hands, and crouch right clicking on it, open the filter's config

**Comment by EpicSquid** [comment]
Found the bug, should be fixed soon
