### ISSUE TITLE
Game Crash with crash reference to EnderIO 

### ISSUE THREAD

**Issue by remclave** [SleepyTrousers/EnderIO#4833]
#### Issue Description: 
EnderIO version: 5.0.31.jar

#### What happens:
When using the Tinkers' crafting table to make slabs, I tried to look up _**uses**_ for stone slabs. The game immediately crashed and the launch screen indicated that EnderIO is the primary conflict. Not sure but something to do with the paint recipes?
The crash (whatever the cause) is repeatable with the same crash report issued.

#### What you expected to happen:
Expected the "use" recipe screen(s).

#### Steps to reproduce:

1. Place stone on crafting table for stone slab recipe.
2. Hover cursor over slab in recipe result window of gui and hit "U" on the keyboard.
3. Game closes and reports that a crash report has been generated.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.31
- EnderCore: 0.5.37
- Minecraft: 1.12.2
- Forge: 14.23.4.2747
- SpongeForge? yes/no (not sure. Modpack uses Sponge so probably yes?)
- Optifine? yes/no NO
- Single Player and/or Server? Server. Haven't tested on single player.

#### Your most recent log file where the issue was present: 

https://pastebin.com/tA2JLdc8

**Comment by tyler489** [comment]
#4755

**Comment by tyler489** [comment]
#4744

**Comment by remclave** [comment]
Okay. Thank your for your patience Tyler489. I will post to TinkerIO and/or TechReborn as needed.
