### ISSUE TITLE
crash client while trying see crafts with this item

### ISSUE THREAD

**Issue by Pa4ok** [SleepyTrousers/EnderIO#4836]
crash client while trying see crafts with this item

- EnderIO-1.12.2-5.0.31
- EnderCore-1.12.2-0.5.37
- 1.12.2
- forge:1.12.2-14.23.4.2739
- spongeforge-1.12.2-2705-7.1.0-BETA-3399.jar
- OptiFine_1.12.2_HD_U_E2
- client

https://gist.github.com/Pa4ok/dbd98f6a236abdae34b619a4039b08a5

**Comment by HenryLoenwind** [comment]
You are too lazy to read the error message and too lazy to see if there already is a report for this (or 20), so I'm too lazy to explain this to you.

**Comment by mindforger** [comment]
what the heck is this launcher class at the bottom of the trace?

**Comment by HenryLoenwind** [comment]
I'd bet one of the "features" is not having to buy Minecraft.

**locked**
