### ISSUE TITLE
We got new Chinese translation !

### ISSUE THREAD

**Issue by ReginaAlcazar** [SleepyTrousers/EnderIO#4837]
EnderIO has been translated into Chinese!
The version is  EnderIO-1.12.2-5.0.26.
If you still haven't lang file for Chinese yet, please add this translation into your mod :)
[zh_cn.zip](https://github.com/SleepyTrousers/EnderIO/files/2287371/zh_cn.zip)

**Comment by HenryLoenwind** [comment]
@3TUSK ?

**Comment by 3TUSK** [comment]
I was summoned before I decided to go to bed.  
Had a look in about 10 minutes (midnight 0:30am here at the time I am typing this), I am still not sure on this one. So... here comes a list of questions towards @ReginaAlcazar.

> `cat -n` is your friend
> paste bin is your friend, too.
> So here it is, paste bin version https://paste.ubuntu.com/p/qwMc8Dw8tT/

  1. 1852 行和 [`en_us.lang` 的 1174 行][ref-1]（计空行）对不上。合并了 `enderio-machine` 的那一部分？最近的版本是 `5.0.31`，你好像落后了 5 个版本。
  2. 有部分未翻译文本。
  3. 有部分翻译…… 值得商榷。举个例子，如果没有记错的话，之前的翻译中有这么一条 `enderio.config.farm.tooltip="The commune is for life!"` -> `“公社万岁！”` (approx. Long live the commune!)。再比如明显的失误 `tile.block_wired_charger.tooltip.detailed.line1=Charges items with µI` 不是 `收费物品µI`（charge 同时有“收费”和“充电”的意思，这里是“充电”）。又例如 `tile.block_crafter.name=工匠`，能用“工匠”这个词形容一个方块吗？
  4. `#` 开头的都是注释，没必要翻译——而且你的理解也有些地方不太对——`slice'n'splice` 是某个机器的名字，`sag mill` 也不是`落锤磨机`，`painter` 也是一个设备的名字…… 机翻吗？
    
````
      1736	# Types. smelting=合金冶炼速度,
      1737	# area=所有机器“区域”属性（例如农场），
      1738	# green=种植区, red=斯特林发电机发电，MOBBY＝生成加速，
      1739	# crushed=落锤磨机速度, cleancut=剪接'速度，tight=灵魂绑定速度，AA =画家，
      1740	# wet=大桶, kaboom=燃烧原子能Gen，FATMAN =原子弹的代号
      1741	#在长崎上空爆炸
````

  5. （我希望这不是酒石酸（@TartaricAcid）的 Weblate 上的那个版本……）请问这个版本的汉化是你自制的吗？

[ref-1]: https://github.com/SleepyTrousers/EnderIO/blob/54f6f9027d5b6ca980f3caec942a2e274e2ddb3f/enderio-base/src/main/resources/assets/enderio/lang/en_us.lang

**Comment by ReginaAlcazar** [comment]
-----------------------Why the translation is badly------------------
This translation was finished two month ago by admin team of my server.
At that time there's no chinese lang file in this mod.
So we decided to translate it by ourselves.
There's three members in our team.
We divided the tasks.
The file was divided into three parts.
One of us are a middle school student.
He translated the part he is in duty by using "baidu translation".
That's where problem come out.  XD

---------Why we decided to send this poor translation to you----------
1、We thought there's still no chinese translation of this mod.
2、We just want to help.

----------------------------Why so late-------------------------------
Only one reason.
We don't want other server surpass ours.

**Comment by tyler489** [comment]
Yeah... dont use Translation sites..... they get it wrong alot... thats why enderio doesn't have infinite translations.

**Comment by 3TUSK** [comment]
@ReginaAlcazar 
见 #4839。
我能理解你想帮忙的心情，但提交给 Mod 开发者的汉化不是给一个服务器用的，而是给所有用中文的 EnderIO 玩家用的，因此翻译的时候要慎重。有兴趣的话，可以考虑了解一下 @TartaricAcid 的汉化资源包项目。  

@HenryLoenwind 
#4839 should supersede this one - at least, for `enderio-base`. I need time to have a look at #4839 too...

**Comment by HenryLoenwind** [comment]
Thank you 3TUSK. I trust in you to decide on any Chinese translations.
