### ISSUE TITLE
possible problem with JEI/Random Things

### ISSUE THREAD

**Issue by Iashar** [SleepyTrousers/EnderIO#4838]
#### Issue Description:
Crashed when right clicking a quartz slab for more recipes in JEI.

#### What happens:
Game locked up, shut down internal server, then proceeded to close to desktop.

#### What you expected to happen:
Expected to get more options from JEI for what I could do with Quartz slabs.

#### Steps to reproduce:
I also have 'Random things' mod installed and that seems to be ~part~ of the problem.
Will be reporting this to them as well.
1.open recipes for Quartz blocks
2.Find where it tells you how to make quartz slabs
3.right click quartz slab
...crash

____
#### Affected Versions (Do *not* use "latest"):

- RandomThings-MC1.12.2-3.9.3.324-universal.jar
- EnderIO: 1.12.2-5.0.31.jar
- EnderCore: 1.12.2-0.5.37.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2747
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

https://pastebin.com/0NNPLskU

####Comments:
I really like your bug report form and may just take it with me if I need to report bugs elsewhere!

**Comment by HenryLoenwind** [comment]
read the damn error message

**Comment by Iashar** [comment]
Sorry for ruining your day. Didn't realize it had anything plaintext in it that I COULD read, as I don't understand half of what the crashlogs say in most games.

**Comment by HenryLoenwind** [comment]
sorry for exploding into your face, but we get about 2 of those each day.

**Comment by Iashar** [comment]
Yeah I can see how that would get aggravating. Apparently he updated RT on the 7th and I missed the memo. Should alleviate a bit of that.
