### ISSUE TITLE
Game will crash on startup after updating mods

### ISSUE THREAD

**Issue by Nawor3565** [SleepyTrousers/EnderIO#4841]
#### Issue Description:

After updating some mods, the game will crash with EnderIO installed. I tried uninstalling BuildCraft, and got a similar error. The game will launch fine without EnderIO. I tried using the version of the mod that worked before, but still got the crash.

#### What happens:

Game crashes on launch.

#### What you expected to happen:

---

#### Steps to reproduce:

1.---
2.---
3.--
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.31
- EnderCore: 0.5.38
- Minecraft: 1.12.2
- Forge: 14.23.4.2750
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Singeplayer

#### Your most recent log file where the issue was present: 

Normal crash log: https://pastebin.com/6uggeN11
Crash log with BuildCraft uninstalled: https://pastebin.com/k7fNPpZC

**Comment by HenryLoenwind** [comment]
That alpha version of endercore is for the next version of ender io.

**Comment by Nawor3565** [comment]
You're right, I downloaded EnderCore 0.5.37 and it works fine. You'd think they would mention somewhere that the latest version of Core isn't compatible with the latest version of IO.
