### ISSUE TITLE
EnderIO using 17% of total CPU. Spamming console occasionally

### ISSUE THREAD

**Issue by sfxworks** [SleepyTrousers/EnderIO#4842]
#### Issue Description:

Experiencing abnormally high cpu usage on server due to ender io. 

#### What happens:

Console gets flooded with erroneous messages and is taxing performance

#### What you expected to happen:

It not to do this

#### Steps to reproduce:

1. Start Lapito's Galacticraft Server
2. Play with Ender IO
3. Await random error messages
...

____
#### Affected Versions (Do *not* use "latest"):

-rwxr-xr-x  1 lapitos minecraft 599K Jul 28 00:03 EnderCore-1.12.2-0.5.31.jar
-rwxr-xr-x  1 lapitos minecraft 6.0M Jul 28 00:03 EnderIO-1.12.2-5.0.26.jar
-rwxr-xr-x  1 lapitos minecraft 219K Jul 28 00:03 EnderStorage-1.12.2-2.4.4.132-universal.jar

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-d453c3e
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3206
    Minecraft Forge: 14.23.4.2705
- SpongeForge? yes
- Optifine? no
- Server? yes

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://sparkprofiler.github.io/?CE8z04EfaY
![image](https://user-images.githubusercontent.com/5921035/44178284-aa3b2280-a0bf-11e8-97b4-2f5fcb5b78b8.png)

https://pastebin.com/mUtHVwfK

**Comment by mindforger** [comment]
Just make sure to chunkload properly and it will go away

**Comment by EpicSquid** [comment]
Since there is no update on this I am closing this issue.
