### ISSUE TITLE
Ender IO is not playing nicely with Liteloader

### ISSUE THREAD

**Issue by CanCallMeLJ** [SleepyTrousers/EnderIO#4845]
#### What happens:

So I'm trying to install liteloader into the Direwolf20 pack. I've taken the .jar file and put it into my "mods" folder. Afterwards I load minecraft up and it gives me an Ender IO Fatal Recipee Error. I have updated Ender IO, Ender Core, and Refined Storage. I've done 3 fresh installs and still the same problem. It crashes before I get to the main screen of Minecraft but the app doesn't close.

#### What you expected to happen:

I expect it to load up and play like normal allowing me to use .litemod

#### Steps to reproduce:

1. Download Direwolf20 pack
2. Download Liteloader and put the .jar file in the "mods" folder
3. Run the game
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.31
- EnderCore: 1.12.2-0.5.37
- Minecraft: 12.2.2
- Forge: 14.23.4.2739
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Don't get that far

#### Your most recent log file where the issue was present: 

https://pastebin.com/HphSxMXG

**Comment by EpicSquid** [comment]
Do you have diet hoppers? It replaces the default hopper block with it's own in the registry, which liteloader causes a compatibility issue with because we want to use the hopper in our recipe but it isn't there. Either remove diet hoppers or remove lite loader.

**Comment by CanCallMeLJ** [comment]
I removed Diet Hoppers and it gets all the way to 7/7 on loading the mods and sits there for about 30 seconds. Then it crashes.

**Comment by CanCallMeLJ** [comment]
https://pastebin.com/KHRb8fjD This is the crash report after removing Diet Hoppers and FoamFix. I removed Diet Hoppers and it said I needed to remove FoamFix or replace it with the Legacy Edition but there is no Legacy Edition for 1.12.2. So I just removed it.

**Comment by EpicSquid** [comment]
This is not an issue with ender io, but with lite loader. Please talk to them

**Comment by CanCallMeLJ** [comment]
I did. Then they told me to come to you. Sorry.

**Comment by EpicSquid** [comment]
Well you haven't provided me any new Information and your second crash is completely unrelated to us. Please stop commenting on a closed issue. We have told you a fix for what we are involved with and the rest is up to lite loader and diet hoppers.

**Comment by HenryLoenwind** [comment]
Also, *never* do a "someone said that-and-that" without linking to it.
