### ISSUE TITLE
ClassCastExpection with WirelessChargers

### ISSUE THREAD

**Issue by Shybella** [SleepyTrousers/EnderIO#4848]
#### Issue Description:
I had 3 Wireless Chargers and when I would break the item it would cause a Internal server error for everyone on the server.  When you logged back in the Charger would be gone but if you placed a block where the Charger was it would kick you out with the same error and same trace. Restarting the server will fix the problem and allow me to place a block where the charger was. I am trying to find a way to reproduce it but cannot. I will reply back if I do find a way.

Thank you guys.

Modpack: Direwolf20 1.12.2 - version 2.2.0 (Release)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.29
- EnderCore: EnderCore-1.12.2-0.5.35
- Minecraft: 1.12.2
- Forge: 2739
- SpongeForge? Yes
- Optifine? No
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/raw/f384cY5J

**Comment by Shybella** [comment]
Henry, thank you for looking into this. If you need any help or any additional information let me know.

**Comment by kreezxil** [comment]
I have this exact same problem, on my dedicated server apparently someone did the same thing. My stack trace is the same. Here's a full server crash report for you to inspect. http://paste.ubuntu.com/p/s5n5QZDHQH/

**Comment by Shybella** [comment]
This is also causing a nasty mem-leak. You seem to have pushed a fix for this as-well

Thank you, Henry.

**Comment by nzminecraftDOTcom** [comment]
Same issue here, interesting to know it is the cause of a memory leak as I'm having the same issue with the Foolcraft 3 pack using more than it should after a while.
This has been the cause of numerous server crashes too.
Crash report: https://pastebin.com/zEn6xVYZ

**Comment by Shybella** [comment]
This is still happening on EnderIO-1.12.2-5.0.31 and EnderCore-1.12.2-0.5.37

**Comment by Shybella** [comment]
Yeap, you are right that's in build 32 not 31.
