### ISSUE TITLE
simple furnace shift-click behavior disappoints me

### ISSUE THREAD

**Issue by seebs** [SleepyTrousers/EnderIO#4850]
#### Issue Description:

Furnace shift-clicking is slot-dependent in a surprising way.

#### What happens:

I shift-click on a stack that could be put in the furnace. It doesn't go. But only sometimes.

#### What you expected to happen:

Shift-click insert things in furnace.

#### Steps to reproduce:

1. Obtain several stacks of the same wood.
2. Put one in furnace.
3. Shift-click another. It goes in furnace, yay!
4. In fact, put some in all three slots.
5. Wait until first two slots are empty.
6. Try to shift-click in more of the same wood. It won't go!
7. Move the stack from the last slot to the first.
8. Shift-click in more. It works!

____
#### Affected Versions (Do *not* use "latest"):
EnderCore-1.12.2-0.5.37.jar
EnderIO-1.12.2-5.0.31.jar
Minecraft 1.12.2
Forge 1.12.2-14.23.4.2718
No spongeforge, no optifine, only tested in SMP with dedicated server.

#### Your most recent log file where the issue was present: 

N/A, no log entries.

**Comment by HenryLoenwind** [comment]
No idea if we have another github ticket for this or if it's only in our "open porting bugs" list...
