### ISSUE TITLE
weird crash clicking simple furnace recipe button

### ISSUE THREAD

**Issue by seebs** [SleepyTrousers/EnderIO#4852]
#### Issue Description:

Client crashed out clicking "recipe" on furnace.

#### What happens:

client crash

#### What you expected to happen:

recipe list

#### Steps to reproduce:

1. have this hugeass weird collection of mods a friend was maintaining, then add EnderIO and a couple of other things to it.
2. figure out how to make a simple furnace.
3. click recipes.
4. cry.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.31.jar
- EnderCore: EnderCore-1.12.2-0.5.37.jar
- Minecraft: 1.12.2
- Forge: 2715
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? SMP

#### Your most recent log file where the issue was present: 

https://gist.github.com/seebs/3a673ab26dc8d03af81b5fc10e98e239

**Comment by HenryLoenwind** [comment]
Which GUI did you have open? Crafting table?

**Comment by seebs** [comment]
simple furnace.

**Comment by HenryLoenwind** [comment]
oh, so "figure out how to make a simple furnace" is wrong? Because that would imply that you looked at the recipe of the simple furnace and pressed the [+] button on it.

**Comment by seebs** [comment]
sorry, i was unclear, and still fussy because i was confused by the 1.12 changes. i was referring to the thing where i couldn't figure out why my alloy smelter wouldn't make charcoal anymore.

so i made a simple furnace, and then in its gui, clicked the recipe button, and got this crash.

**Comment by HenryLoenwind** [comment]
ok, thanks. yes, that then probably is an error on our side
