### ISSUE TITLE
Crash after mining Wireless Charger

### ISSUE THREAD

**Issue by ProxyPlayerHD** [SleepyTrousers/EnderIO#4854]
#### Issue Description:

Mining a Wireless Charger (the antenna looking one), crashed the game.

#### What happens:

it Crashes.

#### What you expected to happen:

no Crash.

#### Steps to reproduce:

1. Open world
2. place one of those chargers, and power it
3. mine it

____
#### Affected Versions (Do *not* use "latest"):

All Version information is inside the Log, but alright.

- EnderIO: 5.0.31
- EnderCore: 0.5.37
- Minecraft: 1.12.2
- Forge: 14.23.1.2554
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 

[LOG](https://pastebin.com/Y9eEi03T)

**Comment by HenryLoenwind** [comment]
#4848
