### ISSUE TITLE
Fluid filter not configurable

### ISSUE THREAD

**Issue by BadLucKWyvern** [SleepyTrousers/EnderIO#4855]
#### Issue Description:

The fluid filter cannot be set (theres no ""Edit Filter Settings" button on GUI while interacting with the pipe

#### What you expected to happen: 
Like the item filter GUI, having a button called "Edit Filter Settings"

#### Steps to reproduce:

1.get a fluid pipe
2.put a fluid filter
3.see that we can't configure the fluid filter
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: Ender IO - 5.0.31
- EnderCore:EnderCore - 1.12.2-0.5.37
- Minecraft:1.12.2
- Forge:1.12.2-14.23.4.2757
- SpongeForge? yes/no what ?
- Optifine? yes/no yes
- Single Player and/or Server? single

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
#4831
