### ISSUE TITLE
Round robin Bug even with downgrade

### ISSUE THREAD

**Issue by AEONvs** [SleepyTrousers/EnderIO#4859]
#### What happens:
I've started to automate the recipe for Draconic evolution with Actually Addition Phantom face and ender io Item Conduit , so , When i say my system to craft some Awakaned Block , it send every needed item in chest and i pull it out with Item conduit into Phantom face linked to Fusion Crafting Injector , i've set the extract with Roud robin with a downgrade , but it send 2 item in one injector , sometimes 1 , but everytime the same amount in the same injector

#### What you expected to happen:
I wanted to get 1 item in one injector 

#### Steps to reproduce:

1.Get recipe of Awakened Block in a chest
2. Filter every phantom face insert
3.Extract on phantom face linked to injector
1.Send item

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.193
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2477
- SpongeForge? No
- Optifine? No
- Single Player and/or Server?  : Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by EpicSquid** [comment]
Use a limited item filter instead.

**Comment by AEONvs** [comment]
@EpicSquid Can't find it ?

**Comment by tyler489** [comment]
This is 1.10 not 1.12 epic :)

**Comment by EpicSquid** [comment]
Limited item filter does existed in 1.10, perhaps it is disabled in your pack?

**Comment by AEONvs** [comment]
No i'm talking with the man who setup the server and he didnt disabled anything from Ender IO , but in Sky factory 3 maybe it is ?

**Comment by EpicSquid** [comment]
Maybe, either way there is a filter in 1.10 in Ender IO that does it

**Comment by AEONvs** [comment]
I'm not sure of that x) 
![image](https://user-images.githubusercontent.com/30214878/45187843-6ce73200-b232-11e8-8789-d6036446c8ac.png)

**Comment by EpicSquid** [comment]
Its the one with the green glowing # on it

**Comment by AEONvs** [comment]
I can't find hwo to use the Counting filter ? :x
