### ISSUE TITLE
Wireless Charger Crashed Server ( 1.12.2 )

### ISSUE THREAD

**Issue by Rambut** [SleepyTrousers/EnderIO#4860]
#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first. If you are using an unreleased version of Ender IO (a.k.a development/nightly version), please don't open an issue for features that have not been announced as "finished" or "working". Expect to be ignored if you ignore this template.

#### What happens:
So I was breaking down my house and moving it and then I broke the wireless charger then the server crashed. 

#### What you expected to happen:
That it would not crash my server. 

#### Steps to reproduce:

1. To look at it and make sure the code it right
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.31
- EnderCore: 1.12.2-0.5.37 
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.4.2759
- SpongeForge? No
- Optifine? Yes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
https://pastebin.com/bMVzAzu5

**Comment by CitiesXL2815** [comment]
#4848 has been reported
