### ISSUE TITLE
[Suggestion] Config to remove enchantment descriptions

### ISSUE THREAD

**Issue by Lykrast** [SleepyTrousers/EnderIO#4863]
While they are helpful, enchantment descriptions on the Ender IO (and Ender Core) enchantments take a lot of place in the tooltip and could use having a client side config option to remove them.

**Comment by HenryLoenwind** [comment]
That option is called "language file"...

**Comment by Lykrast** [comment]
Having to make a resource pack _just_ for that still seems a bit excessive. I guess I'll have to make one.

**Comment by HenryLoenwind** [comment]
`description.enchantment.enderio.soulbound=description.enchantment.enderio.soulbound`

etc. should remove it completely

**Comment by Lykrast** [comment]
Seems like it doesn't work.

![image](https://user-images.githubusercontent.com/8684850/45375866-83a4d480-b5f6-11e8-83d5-3ee6021bc3e9.png)

Ender IO resource pack lang file:
```
description.enchantment.enderio.soulbound=description.enchantment.enderio.soulbound
description.enchantment.enderio.witherarrow=description.enchantment.enderio.witherarrow
description.enchantment.enderio.witherweapon=description.enchantment.enderio.witherweapon
description.enchantment.enderio.repellent=description.enchantment.enderio.repellent
description.enchantment.enderio.shimmer=description.enchantment.enderio.shimmer
```

Ender Core version 0.5.37
Ender IO whole package version 5.0.31

**Comment by HenryLoenwind** [comment]
oh, not good.

Yeah, I found that bug in the code. Will be fixed in the next endercore release.
