### ISSUE TITLE
AHHH HELP MAJOR CRASH

### ISSUE THREAD

**Issue by Notlucky101** [SleepyTrousers/EnderIO#4865]
#### What happens:

Client side crash

#### What you expected to happen:
Get a bucket from Applied Energetic System

#### Steps to reproduce:

1. Make a Magma Crucible
2.Make a Fluild Transponder
3.power up using energy conduits
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.31
- EnderCore:1.12.2-0.5.37
- Minecraft: 1.12.2
- Forge: 8.0.99.99
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Server

https://paste.dimdev.org/jacubonodo.mccrash

**Comment by Notlucky101** [comment]
what do mean invalid. That is the minecraft version I am using 1.12.2....and besides that what about the bug.....????

**Comment by Ommina** [comment]
"Invalid", presumably, because of line seven of your posted crash report:

> java.lang.RuntimeException: Fluid tinker_io.fluids.PureMetal@342c1534 (puremetal, class tinker_io.fluids.PureMetal) from item 1xic2.fluid_cell@0 returned an unregistered block from getBlock(). This is a major bug in the mod that fluid belongs to.

Which, if I'm reading it correctly, indicates that a fluid from Tinker's IO, stored in an item from IC2, is not registering a block for the fluid.

**Comment by tyler489** [comment]
Not exactly... tinkerio says Yes my fluid has a block form. Then when enderio aakes for that form it returns undefined and crashes... this is not a enderio issue
