### ISSUE TITLE
IMC added recipe not working although no errors

### ISSUE THREAD

**Issue by Tomson124** [SleepyTrousers/EnderIO#4868]
#### Issue Description:
I am trying to add recipes to the AlloySmelter through IMC (from my mod SimplyJetpacks 2). There is no error in the log but the recipe is not working either.

#### What happens:
The recipe is not added.

#### What you expected to happen:
The recipe is added.

#### Steps to reproduce:

1.  Use the XML: 
```xml
<enderio:recipes xmlns:enderio="http://enderio.com/recipes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enderio.com/recipes recipes.xsd ">
  <recipe name="Conductive Iron Armor Plating">
    <alloying energy="3200">
      <input  name="simplyjetpacks:metaitemmods:12" amount="1" />
      <input name="ingotConductiveIron"/>
      <output  name="simplyjetpacks:metaitemmods:13" amount="1" />
    </alloying>
  </recipe>
</enderio:recipes>
```
2. Load minecraft and world
3. Recipe for e.g. "Conductive Iron Armor Plating" is not working
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.31
- EnderCore: 1.12.2-0.5.37
- Minecraft: 1.12.2
- Forge: 14.23.4.1705
- SimplyJetpacks 2: 1.12.2-2.2.7.45
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? both

#### Your most recent log file where the issue was present: 

https://pastebin.com/cL9BG9ue

The file for adding the xml while init event looks like this:
```java
public static void addAlloySmelterRecipe(String name, int energy, ItemStack primaryInput, String secondaryInput, ItemStack tertiaryInput, ItemStack output)
	{
		SimplyJetpacks.logger.info("Registering EIO Alloy Smelter recipe");

		StringBuilder toSend = new StringBuilder();

		toSend.append("<enderio:recipes xmlns:enderio=\"http://enderio.com/recipes\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://enderio.com/recipes recipes.xsd \">");
		{
			toSend.append("<recipe name=\"" + name + "\">");
			{
				toSend.append("<alloying energy=\"" + energy + "\">");
				{
					if (primaryInput != null) {
						toSend.append("<input ");
						{
							appendItemStack(toSend, primaryInput);
						}
						toSend.append(" />");
					}

					if (secondaryInput != null) {
						toSend.append("<input name=\"" + secondaryInput + "\"/>");
					}

					if (tertiaryInput != null) {
						toSend.append("<input ");
						{
							appendItemStack(toSend, tertiaryInput);
						}
						toSend.append(" />");
					}

					toSend.append("<output ");
					{
						appendItemStack(toSend, output);
					}
					toSend.append(" />");
				}
				toSend.append("</alloying>");
			}
			toSend.append("</recipe>");
		}
		toSend.append("</enderio:recipes>");

		FMLInterModComms.sendMessage("enderio", "recipe:xml", toSend.toString());

		Log.info(toSend.toString());
	}

	private static void appendItemStack(StringBuilder sb, ItemStack stack)
	{
		if(stack != null)
		{
			sb.append(" name=\"" + stack.getItem().getRegistryName() + ":" + stack.getItemDamage() + "\" amount=\"" + stack.getCount() + "\"");
		}
	}
```

**Comment by Tomson124** [comment]
Sry for the delay.
I tried both:

- `required = "true"`: Didn't do anything, just started normal.
- `-DINDEV=1`: This did not throw an error either, instead it just shows me this: 
```
[19:51:13] [main/INFO]: Processing IMC message recipe:xml from simplyjetpacks
[19:51:13] [main/INFO]: Processing IMC message recipe:xml from simplyjetpacks
[19:51:13] [main/INFO]: Processing IMC message recipe:xml from simplyjetpacks
[19:51:13] [main/INFO]: Processing IMC message recipe:xml from simplyjetpacks
[19:51:13] [main/INFO]: Processing IMC message recipe:soulbinder from simplyjetpacks
```
Which, as far as I understand it, means that everything is registered fine...

**Comment by Tomson124** [comment]
I searched in the log for a entry where they are either skipped or registered but cannot fin any.
The log: https://pastebin.com/aQcHC1p5
This is really weird as the SoulBinder recipe is working, though not showing in the log as registered...

**Comment by HenryLoenwind** [comment]
`[19:51:14] [main/INFO]: INDEV: Registering XML recipe 'Dark Soularium Alloy'`
![image](https://user-images.githubusercontent.com/1485873/45844378-81dbbf00-bd22-11e8-9540-b044b71f0a38.png)

got it...

For now send all recipes in one message. Next version will use a list inside that map...
