### ISSUE TITLE
Loot Capacitors do not apply specialties to enhanced Alloy Smeltery.

### ISSUE THREAD

**Issue by Darkere** [SleepyTrousers/EnderIO#4872]
#### Issue Description:

The special attributes from loot capacitors do not apply to enhanced Alloy Smeltery. The machine uses the base level instead. 

#### What happens:

The enhanced alloy smeltery does not benefit from specialty capacitors.
Images:
Alloy smelter with basic capacitor 30 µI/t https://i.imgur.com/El1766m.png
Alloy smelter with "Nice Smelting Capacitor dud" 86 µI/t https://i.imgur.com/OYEYNIB.png

Enhanced alloy smelter with basic capacitor 45 µI/t https://i.imgur.com/HtGv5h8.png
Enhanced alloy smelter with "Nice Smelting Capacitor dud" 40 µI/t https://i.imgur.com/QcFjknQ.png
Capacitor: https://i.imgur.com/XWA5wYU.png
- EnderIO:5.0.31
- EnderCore:0.5.37
- Minecraft:1.12
- Forge: 2760
- SpongeForge? no
- Optifine? yes
- Server

**Comment by tyler489** [comment]
I do believe there is a seperate cap key for the advanced alloy smelter. I will have to look

**Comment by HenryLoenwind** [comment]
Yes, the loot specialties are specific to one one specific machine. And we don't have one for every machine---that is on purpose. Those are random goodies.
