### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by Daimerion** [SleepyTrousers/EnderIO#4873]
#### Issue Description:

After adding Mek 9 to this pack it crashes everytime

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.12.2-5.0.33
- EnderCore:1.12.2-0.2.39
- Minecraft:1.12.2
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

[https://pastebin.com/D8EkbmVA]

**Comment by SplitInfinitive** [comment]
your pastebin is complaining about a lack of owl eggs for ender zoo.  Please remove ender zoo and replace it with ender io zoo (now released on curseforge)

**Comment by Daimerion** [comment]
>           your pastebin is complaining about a lack of owl eggs for ender zoo.  Please remove ender zoo and replace it with ender io zoo (now released on curseforge)

Deleted the config and mod files of Ender Zoo and then added Ender IO Zoo. Same crash unfortunately. As stated this didn't start until adding Mek 9. IE: I remove Mek 9 and no crash.....

**Comment by Daimerion** [comment]
In case it's not the same, here's a new paste bin of the latest crash

[https://pastebin.com/Wbzsjd2Z]

**Comment by Daimerion** [comment]
I figured it out. Not sure why it throws Ender IO crashes, but it was Mekanism API. Removed and no crash. Didn't even realize I had the api in there. Apologies for time wasted, although I still find it interesting.
