### ISSUE TITLE
[1.12.2] Immersive Engineering X  EnderIO

### ISSUE THREAD

**Issue by GamingJason** [SleepyTrousers/EnderIO#4878]
#### Issue Description:

Immersive Engineering and EnderIO crashes game.

#### What happens:

Crashes the whole game but not the server. If anyone came to my base/chunk they will also crash and no possible way of leaving.

#### What you expected to happen:

Either works with Immersive Engineering Fluid Pipe or nothing happens.

#### Steps to reproduce:

1.Place Immersive Engineering Fluid Pipe
2.Place EnderIO Pressured Fluid Conduit beside the Fluid Pipe
3.Crashed.
4.Happened twice.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-5.0.31
- Minecraft: 1.12.2
- Forge: Not Sure
- SpongeForge? No
- Optifine? Yes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

Crash Report: https://pastebin.com/Pkxuy1ve
Modlist: https://pastebin.com/pNKPksij

**Comment by EpicSquid** [comment]
Update enderio
