### ISSUE TITLE
ender io + optifine

### ISSUE THREAD

**Issue by jesserobbins98** [SleepyTrousers/EnderIO#4879]
i run minecraft and it boots all the way through i try to load a world and it crashes.

https://pastebin.com/v5ZV8uPZ

**Comment by jesserobbins98** [comment]
oh yes sorry i should have mentioned 1.12.2 version sorry

**Comment by tyler489** [comment]
Can you reproduce without optifine?
Also what 1.12 version.. the issue template is there for a reason. :rage:

**Comment by jesserobbins98** [comment]
curse. no it works fine without optifine. and if you mean the mod version its ender io: 5.0.31 endercore: 0.5.37

**Comment by jesserobbins98** [comment]
anything else?

**Comment by tyler489** [comment]
I would put this on optifines issue tracker as i am 99% certain its on them.
https://github.com/sp614x/optifine/issues

**Comment by jesserobbins98** [comment]
ok i thank you :)
