### ISSUE TITLE
Travel 

### ISSUE THREAD

**Issue by felipeleite5w** [SleepyTrousers/EnderIO#4886]
#### Issue Description:

I wanna block travel in pickaxe and the ender sword 

#### What happens:

I dont know how to do that

#### What you expected to happen:

block travel skill 

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.429_beta
- EnderCore: 0.2.0.39_beta
- Minecraft: 1.7.10
- Forge:  7.10.99.99
- SpongeForge? yes/no no
- Optifine? yes/no yes 
- Single Player and/or Server?server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
Confused. Do you want to stop people using that upgrade in an area or do you not want it to work period.

**Comment by felipeleite5w** [comment]
Sorry, I dont wanna people using travel upgrade

**Comment by HenryLoenwind** [comment]
Use an Inhibitor Obelisk.

**Comment by felipeleite5w** [comment]
I wanna disable it in all the server .-.

**Comment by tterrag1098** [comment]
1.7.10 is no longer receiving feature updates.

**Comment by felipeleite5w** [comment]
I dont wanna a update .-. I wanna disable it, there is somehow ?

**Comment by HenryLoenwind** [comment]
I don't think so. But you can set the level cost to something like 99 levels...

**Comment by felipeleite5w** [comment]
how ?

**Comment by felipeleite5w** [comment]
how?
