### ISSUE TITLE
Refined Storage Enderio Cables - Exporting is not working.

### ISSUE THREAD

**Issue by eihns** [SleepyTrousers/EnderIO#4887]
#### Issue Description:

I really really love your refined storage cables, importing is working perfectly (even the filter is not working, you cant say only import this out of the machine).

But this bug report is about a bigger problem, **exporting via your cables is not working.**

#### What happens:
Nothing.

#### What you expected to happen:
I expect that the item in the whitelist gets exported into the inventory (chest or machine)

#### Steps to reproduce:

1. use refined storage enderio cables
2. place filter in there
3. set whitelist to what you want to export
4. nothing

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.33
- EnderCore: 1.12.2-0.5.39
- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server?
Singleplayer and network (via open to lan)

#### Your most recent log file where the issue was present: 
I post screenshots showing my problem in detail

![2018-09-28_00 50 36](https://user-images.githubusercontent.com/43281991/46178794-8ff88500-c2b8-11e8-9d72-2c5eeb705827.png)
![2018-09-28_00 50 41](https://user-images.githubusercontent.com/43281991/46178795-8ff88500-c2b8-11e8-9ace-4ce9862db0c2.png)
![2018-09-28_00 50 45](https://user-images.githubusercontent.com/43281991/46178796-8ff88500-c2b8-11e8-9695-1d466d5ee9a7.png)
![2018-09-28_00 50 48](https://user-images.githubusercontent.com/43281991/46178797-8ff88500-c2b8-11e8-9927-b3ebc417f0c7.png)

**Comment by eihns** [comment]
I reproduced in a fresh new install, just enderio, jei and refined storage. Just for the sake of it i also tried the limited and advanced item filter, nothing happens. 


![2018-09-29_00 14 51](https://user-images.githubusercontent.com/43281991/46235964-01017080-c37d-11e8-8170-847ca6e771b4.png)
![2018-09-29_00 14 57](https://user-images.githubusercontent.com/43281991/46235965-01017080-c37d-11e8-83d7-20cbbc76c0b3.png)
![2018-09-29_00 15 00](https://user-images.githubusercontent.com/43281991/46235966-019a0700-c37d-11e8-81dc-cb826a394b21.png)
![2018-09-29_00 15 03](https://user-images.githubusercontent.com/43281991/46235967-019a0700-c37d-11e8-9451-10bb2694690a.png)
<img width="824" alt="see" src="https://user-images.githubusercontent.com/43281991/46235968-019a0700-c37d-11e8-8f6e-09ed8cd73efd.png">

**Comment by EpicSquid** [comment]
Can you send screenshots of the exact RS setup in world for your test world?

**Comment by eihns** [comment]
controller, storage crate, pattern grid, crafting grid, enderio rs cables, filter.

Is that what you mean?

![2018-09-29_01 47 52](https://user-images.githubusercontent.com/43281991/46238152-b4706200-c389-11e8-99fe-decc16c30c19.png)

**Comment by EpicSquid** [comment]
Perfect. Ill look into it then.

**Comment by EpicSquid** [comment]
This exact setup works fine for me. I don't know why it is not working for you. When you have some time to help out some more, can you ping me on discord? We might have to try out a few builds to finally work out what is going on.

**Comment by eihns** [comment]
Since i really really hard want to get this working i will do whatever you want :D i come home in ~8-9hours then i will ping u on discord

**Comment by pip69** [comment]
I came here looking, because I'm having the same problem.  
As well, the import for this ignores black/white list and just imports everything.

**Comment by eihns** [comment]
Yeah, i have the same expierince with the importing too.

**Comment by tyler489** [comment]
Fixed in dev https://github.com/SleepyTrousers/EnderIO/commit/1fa900d6ef7b315b457ff061ae2c29763cf2b88f

**Comment by EpicSquid** [comment]
Fixed now, the importing bug is a separate issue @pip69 so please open a different issue for that.
