### ISSUE TITLE
[Information needed] Powered spawner showing "no space found" and "no viable space"

### ISSUE THREAD

**Issue by chris42** [SleepyTrousers/EnderIO#4888]
#### Issue Description:

I updated my own server to newer version of EnderIO. Since then the powered spawners stopped working. They show the error "no space found" and "no viable space". 
However to the placing in the world nothing changed and I checked with McEdit, there is nothing else around the spawners.
I saw some July commits, changing the spawners, however not sure what that does.
When I move them to other places in the world, they spawn as expected, however not in this (and some other) place.
Hence I assume it is some other rule that is now active, preventing the spawning.

How do I find out what it is? Can I activate some debugging?

#### What happens:
No spawning 

#### What you expected to happen:
Spawning should happen

#### Steps to reproduce:
Not applicable

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.31
- EnderCore: 1.12.2-0.5.37
- Minecraft: 1.12.2
- Forge: 14.23.4.2760
- SpongeForge? no
- Optifine? no
- Server

#### Your most recent log file where the issue was present: 
Nothing in logs

**Comment by tyler489** [comment]
do you have something blocking spawns in that area... like a mega torch or that astral sorcery ritual? also i would recomend using enderio 5.0.33

**Comment by chris42** [comment]
I checked for mega torches, could not find any, even removed the mod from the server. I don't have astral sorcery in the mods.
After updating to EnderIO 5.0.33 I now get a third error message: "Denied by another mod"
How can I find out which mod?

**Comment by tyler489** [comment]
No real way to tell. How about environmental controler from rftools

**Comment by chris42** [comment]
Is there anything I can add to the code to figure this? 

I really have no idea on what could be preventing spawning. In the beginning I used mega torches, but as said, all removed and even the mod uninstalled. Otherwise there is only the following in that area:
- Immersive Engineering flood lights
- Redstone controller from RF Tools
- Wither spawner, RFTools Shields
- Mob Crusher
- Ender Chests

In wider area you have a lot of machinery for Ore processing, ME Core, etc. however nothing I could consider spawn relevant.

Also it worked in the old version?! And is it normal, that I have all three error messages at the same time?

**Comment by chris42** [comment]
That solved it, thanks. I am slightly confused. So the flood lights prevent spawning even when turned off?
Will ask that over at immersive engineering...

**Comment by tyler489** [comment]
The third msg should replace the first 2 in newer versions if something is blocming it
