### ISSUE TITLE
Suggestion Compat with openblocks

### ISSUE THREAD

**Issue by Colton-Slayden** [SleepyTrousers/EnderIO#4891]
#### Issue Description:
Using elevator block in painting machine

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first. If you are using an unreleased version of Ender IO (a.k.a development/nightly version), please don't open an issue for features that have not been announced as "finished" or "working". Expect to be ignored if you ignore this template.

#### What happens:
Nothing

#### What you expected to happen:
Painting machine masks elevator as whatver block

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft:
- Forge:
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
suggestions should go on Discord
However why would u want this when the travel block from enderio can work like an elevator
