### ISSUE TITLE
Redstone Timer Filter GUI

### ISSUE THREAD

**Issue by MelanX** [SleepyTrousers/EnderIO#4892]
#### Issue Description:
Please change the way to configure this setting in the Redstone Timer Filter.

#### What happens:
I clicked 1480 times +

#### What you expected to happen:
Delete 20 and type in 1500.

#### Steps to reproduce:

1. Use a Redstone Timer Filter
2. Click 1480 times on +
3. Buy a new mouse and a new finger
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.33
- EnderCore: 1.12.2-0.5.39
- Minecraft: 1.12.2
- Forge: 14.23.4.2705
- SpongeForge? no
- Optifine? yes
- Single Player and Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/jQUgnSDV (sorry, it's not really a log, I just wanted to be funny)

**Comment by MelanX** [comment]
really? D: 
hm.. I used Autoclicker :D but this cannot be the solution
maybe it will be changed or I could use shift :)

**Comment by tyler489** [comment]
Shift was 10 ctrl was 20 per click

**Comment by tterrag1098** [comment]
Ctrl/Shift clicking has been added in dev
