### ISSUE TITLE
[Fatal recipe error] Impossible disable recipe at duplicate recipe load error

### ISSUE THREAD

**Issue by VladimirMangos** [SleepyTrousers/EnderIO#4897]
#### Issue Description:

Minecraft fail load with error:

[04:30:02] [main/ERROR]: Invalied recipe while parsing IMC:
[04:30:02] [main/INFO]: [crazypants.enderio.base.config.recipes.RecipeLoader:handleIMCRecipes:149]: crazypants.enderio.base.config.recipes.InvalidRecipeConfigException: Duplicate recipe Sagmill: Ender Dust at [row,col]:[1,78]

It happens with EnderIO-1.12.2-5.0.36.jar
but not with EnderIO-1.12.2-5.0.35.jar

Possible problem real but my attempt disable recipe by adding 

  `<recipe name="Sagmill: Ender Dust" disabled="true"/>`

to 

config\enderio\recipes\user\user_recipes.xml 

not resolve load problem

#### What happens:

Minecraft client not finish startup

#### What you expected to happen:

Or recipe error unexpected and bug or workaround to disable duiplicate recipe work.

#### Steps to reproduce:

Can be reproduced with minimal mods list

EnderCore-1.12.2-0.5.41.jar
EnderIO-1.12.2-5.0.36.jar
JAOPCA-1.12.2-2.2.8.94.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
thermalsolars-1.12.2-1.9.2.jar
WrapUp-1.12-1.1.3.jar

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.36.jar
- EnderCore: EnderCore-1.12.2-0.5.41.jar
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2770
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

https://paste2.org/K6vP3m1K

**Comment by tyler489** [comment]
```04:30:02] [main/ERROR]: == Bad file ==
[04:30:02] [main/ERROR]: IMC from the mod 'jaopca'
[04:30:02] [main/ERROR]: ```

**Comment by VladimirMangos** [comment]
As i note: I see problem not in reporting error at bad recipe, but imposability ignore this recipe in Ender IO but avoid generation Ender IO version of recipe for Sagmill.

**Comment by tyler489** [comment]
Soo you would rather not have that recipy in the base mod.. in the off chance that jaopca is installed? What if jaopca isnt installed?

**Comment by tyler489** [comment]
Also u cant disable it becausw the duplicate is comming from joapca.

**Comment by EpicSquid** [comment]
You are better off reporting this as a bug to jaopca, since they are responsible for it.

**Comment by HenryLoenwind** [comment]
um, stop, stop, stop.

Unless jaopca sends the recipe twice this should not give a duplicate error. IMC messsages are allowed to override core recipes.

I'll look into this.

**Comment by VladimirMangos** [comment]
> Soo you would rather not have that recipy in the base mod.. in the off chance that jaopca is installed? What if jaopca isnt installed?

If I remove any from mods from list in original post then problem not reproduced.

**Comment by tyler489** [comment]
> um, stop, stop, stop.
> 
> Unless jaopca sends the recipe twice this should not give a duplicate error. IMC messsages are allowed to override core recipes.
> 
> I'll look into this.
from what me and epic were discussing 
what happens here is IMC sends... Enderio processes IMC...... Enderio process Core... game detects and crashes... before loading the user recipys @HenryLoenwind

**Comment by VladimirMangos** [comment]
Maybe user recipes can be proccessed early for let user better control conflict mods recipes.
Strange thing: in prev. build of Ender IO this problem not happens.

**Comment by HenryLoenwind** [comment]
Please try again with http://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/760/ This should provide better error messages.

**Comment by VladimirMangos** [comment]
With removed custom changes in config\enderio\recipes\user\user_recipes.xml (so original file state at problem detection)
And updated 

EnderCore-1.12.2-0.5.41.jar ->EnderCore-1.12.2-0.5.42.jar
EnderIO-1.12.2-5.0.36.jar -> EnderIO-1.12.2-5.0.760-nightly.jar

Problem not showup for test mods list

And also minecraft world load fine for original mods (420 mods)

Thank you for fix problem!

**Comment by HenryLoenwind** [comment]
Could you please have a look into the log and see if there are messages with "is being replaced by a recipe from"? Thanks
