### ISSUE TITLE
remove steel recipe enderio 1.12

### ISSUE THREAD

**Issue by Celophy** [SleepyTrousers/EnderIO#4898]
i have this problem: for an 1.12 modpack i want to change the steel recipe from the simple alloy smelter to the normal alloy smelter or just remove it.

![2018-10-12_20 05 54](https://user-images.githubusercontent.com/41362064/46905694-96f9d700-cef7-11e8-93ca-bd0da5dc810a.png)

or if it isn't possible to remove the ingot, (from extreme reactors).
i tried minetweaker but it didn't work...

**Comment by HenryLoenwind** [comment]
https://streamable.com/cs1qu
