### ISSUE TITLE
1.12.2 Iron Alloy recipe sometimes blocks alloy smelter processing

### ISSUE THREAD

**Issue by LuciusV** [SleepyTrousers/EnderIO#4903]
#### Issue Description:

 Iron Alloy recipe is not smelting if both not-iron ingots go into 1-st smelter slot.

#### What happens:

I want to smelt 30 Iron Alloy ingots from 10 iron ingots and 20 copper ingots

If I put them in all slots equally (10 copper - 10 iron - 10 copper), it will smelt only 15 Iron Alloy Ingots, taking 2*5 copper ingots from left slot, 5 iron ingots from center slot, but 10 copper ingots in right slot left untouched.   

If I put all 20 copper ingots in left slot and 10 iron ingots in right slot, nothing happens.

Only way to manually smept 30 Iron Alloy ingots is to put 19 copper ingots in left slot, 10 iron ingots in middle slot and 1(!) copper ingots in right slot. 

This bug makes refined storage autocrafting unusable and blocks any complex recipe involving making Iron Alloy Ingot

#### What you expected to happen:

 Smelting processes normally with ingots placed in left/center slot at 2:1 ratio

#### Steps to reproduce:

1. Put items in smelter as described above
2. 
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.36
- EnderCore: EnderCore-1.12.2-0.5.41
- EnderIO-endergy: EnderIO-endergy-1.12.2-5.0.36
- Minecraft: 1.12.2
- Forge: 2678
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server?
both

**Comment by LuciusV** [comment]
In version 1.12.2-5.0.37 recipe now doesn't work at all: smelter does not allow copper in any slot if there is another slot with copper, and does not smelt 2 copper + 1 iron put into two slots leaving one slot empty (so smelting iron alloy is impossible mow)

**Comment by tyler489** [comment]
From Henry on discord "works as intended. the recipe now needs two different metals (something that originally could not be expressed)"
