### ISSUE TITLE
1.12.2 Anvil doesn't allow Stellar leggings Swiftness upgrade

### ISSUE THREAD

**Issue by LuciusV** [SleepyTrousers/EnderIO#4905]
#### Issue Description:
Anvil doesn't allow Stellar leggings Swiftness upgrade

#### What happens:
No anvil output for recipe   Stellar leggings + Potion of Swiftness

#### What you expected to happen:

Swiftness I, II, III upgrades

#### Steps to reproduce:

1. Make Stellar Leggings and Potion of Swiftness
2. Try to apply it on anvil
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.36
-  EnderIO-endergy:  EnderIO-endergy-1.12.2-5.0.36
- EnderCore: EnderCore-1.12.2-0.5.41
- Minecraft: 1.12.2
- Forge: 2678
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server?
both?

**Comment by LuciusV** [comment]
I found that upgrade works with 8-minute duration potions, this is feature or bug?

**Comment by tyler489** [comment]
Should be just the standard swiftness potion

**Comment by HenryLoenwind** [comment]
Complain to Mojang that they all have the same name. The JEI recipe correctly shows which one you need.
