### ISSUE TITLE
1.12.2 Dark Steel Armor Bug after update

### ISSUE THREAD

**Issue by SirAron111** [SleepyTrousers/EnderIO#4907]
#### Steps to reproduce:

1.Install, set configs 
2. cinfigs go missing when updateing to newest version and or are all messed up.
3. suddenly armor gets destroyed out of nowhere
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:Newest
- EnderCore:Newest
- Minecraft:1.12.2
- Forge:14.23.5.2768
- SpongeForge? dont know normal forge
- Optifine? No tested it with no other mods installed
- Single Player

#### Your most recent log file where the issue was present: No log for that

[pastebin/gist/etc link here]

**Comment by EpicSquid** [comment]
It literally says do not say "latest" in the template. Please give the version number you updated from. Energy usage values for Dark Steel is now stored in the capacitor key xml files
