### ISSUE TITLE
Simple Question - block ID confusion

### ISSUE THREAD

**Issue by ehmitchell3** [SleepyTrousers/EnderIO#4909]
Hey Devs,

I'm running into a too-many-hostiles error with clearlagg, and I'm trying to use adamantinesheld to locate specific blocks. Problem is that the blockID's for the powered spawner don't work.

Is it something different than "enderio:block_powered_spawner" or "enderio:powered_spawner"?

Thanks!

MC: 1.12.2
eio: 5.0.31

**Comment by HenryLoenwind** [comment]
enderio:block_powered_spawner is the correct one.
