### ISSUE TITLE
Ender IO Endergy causes both endergy and ender IO conduits to be unbreakable

### ISSUE THREAD

**Issue by DragonmasterDJ** [SleepyTrousers/EnderIO#4911]
#### What happens:

When placing a conduit, when broken it will replace itself every time.

#### What you expected to happen:

The conduit should break and fall to the ground

#### Steps to reproduce:

1. place a endergry conduit. such as the stellar one
2. try to break it, in both survival and creative

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.36
- EnderCore: 0.5.41
- Ender IO Endergy: 5.0.36
- Minecraft: 1.12.2
- Forge: 14.23.5.2769
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

[Latest.txt](https://github.com/SleepyTrousers/EnderIO/files/2497924/Latest.txt)

**Comment by tyler489** [comment]
Uh @epicsquid

**Comment by DragonmasterDJ** [comment]
crap sorry ill get the log. @HenryLoenwind I added it.

**Comment by DragonmasterDJ** [comment]
I also now have to mention it also effects normal ender IO conduits after playing around with them!

**Comment by Keridos** [comment]
Cannot reproduce this on my server running the same versions. So either it is SP only or some other mod is causing this.

**Comment by EpicSquid** [comment]
Journeymap is erroring on world unload, and Redstonic is erroring as well. This is not an Ender IO bug
