### ISSUE TITLE
AE2 Fluid interfaces and ender fluid conduits bug

### ISSUE THREAD

**Issue by Keridos** [SleepyTrousers/EnderIO#4913]
#### Issue Description:
Ender Fluid Conduits do not properly work with AE2 Fluid Interfaces. It only seems to pump out of the first tank of the interface. Check with filters on output of the conduits.

#### What happens:
Only one of the fluids from the interface is pumped out.

#### What you expected to happen:
It should pump out all fluids.

#### Steps to reproduce:

1. Set a AE2 Fluid Interface up with multiple different fluids.
2. Set up tanks for each one of those fluids.
3. Connect them via ender fluid conduits and filter the fluids on the input.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.36
- EnderCore: 0.5.41
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
tracked in #5005
