### ISSUE TITLE
crash with jei

### ISSUE THREAD

**Issue by dracula262** [SleepyTrousers/EnderIO#4914]
Issue Description:

when i open my modpack with ender io along with jei it crash

 What happens:
close minecraft automatically

What you expected to happen:

open normally

Steps to reproduce:

1.install forge
2.install ender io and ender core
3.open the game
...

____
Affected Versions (Do *not* use "latest"):

- EnderIO:5.0.36
- EnderCore:0.5.41
- Minecraft:1.12.2
- Forge:14.23.5.2768
- SpongeForge? No

- Optifine? Yes

Your most recent log file where the issue was present: 

https://pastebin.com/gsRpkicz

**Comment by dracula262** [comment]
[crash-2018-10-20_21.30.34-client.txt](https://github.com/SleepyTrousers/EnderIO/files/2499325/crash-2018-10-20_21.30.34-client.txt)

**Comment by tterrag1098** [comment]
> java.lang.OutOfMemoryError: Java heap space

You are running out of memory. Increase the allocation.
