### ISSUE TITLE
Ender Bow doesn't work with Thermal Innovation's Alchemical Quiver

### ISSUE THREAD

**Issue by nexfwall** [SleepyTrousers/EnderIO#4915]
#### Issue Description:

Ender Bow doesn't work with Thermal Innovation's [Alchemical Quiver](https://teamcofh.com/docs/thermal-innovation/alchemical-quiver/).

#### What happens:

Ender Bow doesn't recognize [Alchemical Quiver](https://teamcofh.com/docs/thermal-innovation/alchemical-quiver/) as ammo source and pretends there's no ammo at all in inventory. Even if equipped Quiver in offhand. However vanilla Bow works and Thermal Expansion's Reinforced Bow too.

#### What you expected to happen:

Ender Bow fire arrows from [Alchemical Quiver](https://teamcofh.com/docs/thermal-innovation/alchemical-quiver/) either it's [imbuing](https://teamcofh.com/docs/thermal-innovation/alchemical-quiver/#imbuing-arrows) activated (tipped arrows) or not (normal arrows).

#### Steps to reproduce:

1. Install Thermal Innovation and it's dependencies.
2. Spawn Alchemical Quiver from creative. You may use Creative one also.
3. Spawn a potion (any)
4. Spawn Ender Bow (charged)
5. Craft Alchemical Quiver with potion to charge it
6. If Alchemical Quiver is not creative, spawn some arrows to inventory and use Alchemical Quiver while it's in hand to charge it
7. Place charged (but not imbued) Alchemical Quiver in offhand
8. Select Ender Bow from hotbar
9. Enter Survival mode
10. Open fire to the nearby test subject
11. ...
12. Nothing happens
13. Activate Alchemical Quiver imbuing and place it back to offhand
14. Open fire to the nearby test subject
15. ...
16. Nothing happens.
17. Vanilla bow still works.

Make sure you don't have any free arrows in player inventory except the ones in the Quiver.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.36
- EnderCore: 1.12.2-0.5.41
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- SpongeForge? no
- Optifine? yes (does not matter on this case, not a rendering issue)
- Single Player, haven't tested on Server.

#### Your most recent log file where the issue was present: 

None.

**Comment by Trophonix** [comment]
@tyler489 Why does henry say it won't happen? It seems like it should be a reasonably easy fix. The project already has imported the CoFH core and is even using methods from it in the dark steel bow class itself. Adding the potion effect stuff may be a bit more of a pain, but you can get a good idea of what to write there from the thermal expansion bow's code.

**Comment by HenryLoenwind** [comment]
Update on this:

I had a very good look at the bow code (for other reasons) today. There are enough hooks in there to implement a quiver that doesn't need special support by other mods. Any item that extends ItemArrow has full control over (a) if its stack should be shrunk when fired or not and (b) what arrow entity is created (at which time it can shrink its arrow count). Only annoying thing is that if one wants to make the arrow pickupable, one needs to have ones own arrow entity class---the bow code links that flag with the stack shrinking.
