### ISSUE TITLE
Duplicate glitch liquids

### ISSUE THREAD

**Issue by BartolomeoDR** [SleepyTrousers/EnderIO#4917]
#### What happens:
duplicate glitch liquids

#### Steps to reproduce:

YouTube timecode:
https://youtu.be/9onFwKzi1Rs?t=143

1. Fill both tankers with liquid
2. Take away quickly and pour back the liquid
3. We get more than we had
...

- EnderIO: EnderIO-1.12.2-5.0.0-35ec615cb.jar
- EnderCore: EnderCore-1.12.2-0.5.41.jar
- Minecraft: 1.12.2
- SpongeForge?  yes
- Optifine yes
-   server

**Comment by HenryLoenwind** [comment]
see #4980
