### ISSUE TITLE
Redstone Sensor Filter not configurable

### ISSUE THREAD

**Issue by ouroborus** [SleepyTrousers/EnderIO#4919]
#### Issue Description:

Installing a Redstone Sensor Filter and clicking its gear button kicks you out of the interface and messes up your hotbar (client-side only).

#### Steps to reproduce:

1. Place an item or fluid conduit and a redstone conduit adjacent to a chest or tank
2. Open of the connector configuration, switch to the redstone tab, install a Redstone Sensor Filter.
3. A button with a gear icon will show up. Click that button.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2715
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? server

#### Your most recent log file where the issue was present: 

Nothing is logged (both client and server) when this happens.

**Comment by HenryLoenwind** [comment]
#4759
