### ISSUE TITLE
Server won't load with Custom Endergy Alloy Recipe, however Client will

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [SleepyTrousers/EnderIO#4923]
#### Issue Description:

When creating a custom recipe for one of the Endergy Alloys (in my case the Crystalline Alloy) the server refuses to boot up entirely while everything works smoothly in a singleplayer world.

#### What happens:

The server crashes giving me a StackOverflow error whenever I try to launch out with this custom recipe enabled. It doesn't matter whether the Endergy module is installed or not in this case, neither does it seem to matter whether I am using OreDict names, ItemStack names with metadata, or anything in between. The name of the recipe doesn't change anything either.

#### What you expected to happen:

I expected for the server to load normally since the client obviously did.

#### Steps to reproduce:

1. Edit the user_recipes.xml file and create a custom recipe with any of the Endergy Ingots as the output (i.e. ingotCrystallineAlloy)
2. Launch up the game on client-side and load up a world. The recipe should be there.
3. Try to launch up a server with the versions specified below. The server will crash.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: **5.0.36 (modular install, though all modules are on the same version)**
- EnderCore: **0.5.41**
- Minecraft: **1.12.2**
- Forge: **14.23.5-2772 (also tried on 2770)**
- SpongeForge? **no**
- Optifine? **no (since this is serverside)**
- Single Player and/or Server? **Server only**

#### Your most recent log file where the issue was present: 

Crash Report: https://hastebin.com/aberaweyux.rb

I can also provide a link to a larger portion, though not the entirety, of the full server log if you want me to do so.

**Comment by HenryLoenwind** [comment]
Please post the recipe you added

**Comment by MaxNeedsSnacks** [comment]
Here you go:

https://hastebin.com/tucufejewo.xml

**Comment by LumberWizard** [comment]
https://hastebin.com/jefitaxoja.sql Interestingly enough, I got this crash on my client, but my server started up fine.

**Comment by MaxNeedsSnacks** [comment]
Now hang on, this makes even less sense. Shouldn't my client be crashing as well then?

**Comment by LumberWizard** [comment]
The issue isn't caused by Endergy specifically, changing the same recipe to replace vibrant alloy gives the same crash.

**Comment by LumberWizard** [comment]
How can it still work if you're missing Actually Additions?

**Comment by MaxNeedsSnacks** [comment]
Oh no, I just forgot that mod in the list, I did install AA

**Comment by LumberWizard** [comment]
I think the issue is the fact the modid for ProjectRed includes a dash.

**Comment by HenryLoenwind** [comment]
This makes no sense. Yes, we have (had) a bug where having a "-" or "+" in the `name` attribute for `input` or `output` that was not after a "," would lead into this crash. But I don't see any stray "-"/"+" here, and it certainly wouldn't behave differently on client and server...

**Comment by MaxNeedsSnacks** [comment]
Even weirder right now is that testing with the CI version of EnderCore where the issue is fixed yields [another type of crash](https://hastebin.com/adekadutoq.rb)with EIO-OC Conduits, where as again, on the client, it's fine

**Comment by LumberWizard** [comment]
I thought we fixed that? The issue is that Forge doesn't like modids longer than 20 characters.

**Comment by HenryLoenwind** [comment]
lol. we fixed that one in ender io a while ago and added code to endercore to warn us the the future if we do the same again. However, that fixed eio isn't released yet...

**Comment by MaxNeedsSnacks** [comment]
Ah, so .41 doesn't include that added code and that's why it was able to launch with that before, but .43 does and so it crashes. Let me test whether it's all working with EIO-OC disabled for now, and then I'll get back to you

**Comment by HenryLoenwind** [comment]
thanks, that would have been my advice for now, too

**Comment by MaxNeedsSnacks** [comment]
Can confirm that on my end both client and server now work with the CI EnderCore version (and EIO-OC disabled), so this can probably be closed with the next CF release. Thanks again for helping out with this issue.

**Comment by MaxNeedsSnacks** [comment]
Closing this issue now as the CI EnderCore version referenced here has been released. As for the .37 version of EnderIO that fixes the EIO-OC modid, that is a separate issue so if you're reading this and you're a normal end user crashing with EnderIO-OpenComputers on this new version, just disable it until .37 is actually released.
