### ISSUE TITLE
OpenComputers Integration causing crashes?

### ISSUE THREAD

**Issue by SpudGunMcGee** [SleepyTrousers/EnderIO#4924]
#### Issue Description:

Severe crash on the latest versions of Forge, Ender IO, EnderCore and OpenComputers. Something to do with the OpenComputers conduits I think. Deactivating OpenComputers fixed the crash.

#### What happens:

Launch MC with relevant mods installed, crashes during initialization.

#### Steps to reproduce:

1. Create a 1.12.2 instance of minecraft
2. Install Forge 14.23.5.2772, EnderIO 1.12.2-2.4.5.135-universal and EnderCore 1.12.2-0.5.43
3. Install OpenComputers-MC1.12.2-1.7.2.67

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-2.4.5.135-universal
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 14.23.5.2772
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Client

#### Your most recent log file where the issue was present: 

https://gist.github.com/SpudGunMcGee/d6eb42908d401781bccb868d97cfcbac

**Comment by LumberWizard** [comment]
It's been fixed in dev and will be fixed in the next release of EnderIO.

**Comment by SpudGunMcGee** [comment]
Many Thanks
