### ISSUE TITLE
Crash when starting EnderIO Monolith and OpenComputers

### ISSUE THREAD

**Issue by TomatoCo** [SleepyTrousers/EnderIO#4925]
#### Issue Description:

Crash when starting EnderIO Monolith and OpenComputers due to java.lang.RuntimeException: Channel name 'enderioconduitsopencomputers' is too long for Forge. Maximum length supported is 20 characters.

#### What happens:

Game crashes during second stage of mod initialization.

#### What you expected to happen:

Game starts correctly.

#### Steps to reproduce:

Install EnderIO and EnderCore. Install OpenComputers. Start minecraft. Crash.

____
#### Affected Versions (Do *not* use "latest"):

- OpenComputers: 1.12.2-1.7.2.67 (this is not an alpha/beta)  
- EnderIO: 5.0.36 (this is not an alpha/beta)  
- EnderCore: 1.12.2-0.5.43 (this is not an alpha/beta)  
- Minecraft: 1.12.2  
- Forge: 14.23.5.2772  
- SpongeForge? no.  
- Optifine? no  
- Single Player and/or Server? Only tested singleplayer  

#### Your most recent log file where the issue was present: 

https://pastebin.com/a4rzyGxa

#### Aside

Removing the monolith and using modular Ender IO with Base, Conduits, and Machines allows the game to start correctly. Adding OC Conduits will begin crashing again.

**Comment by LumberWizard** [comment]
Duplicate of #4924.

**Comment by TomatoCo** [comment]
Quite right. I don't know how I glanced over that one. Sorry about that.
