### ISSUE TITLE
Game crashes when seeing uses in painting machine for screens from RF Tools

### ISSUE THREAD

**Issue by joshuasuperboy** [SleepyTrousers/EnderIO#4929]
#### Steps to reproduce:

1.Get 1.12.2-forge1.12.2-14.23.4.2718 forge version
2.Get RF Tools mod version 1.12-7.33
3.Get Ender io mod version 1.12.2-5.0.29
4.Then launch minecraft with those mod version installed.
5.Then open up a new world or a existing one.
6.Then look at the uses for RF Tools screen then click on the painting machine tab.
7.Then you should crash and get the crash report you see below or something similar.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.29
- EnderCore: 1.12.2-0.5.35
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.4.2718
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 

[https://paste.dimdev.org/retiqedonu.rb]

**Comment by tterrag1098** [comment]
You're 5 releases (about 4 months) out of date. This is already fixed.

**Comment by joshuasuperboy** [comment]
k thx
