### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by joshuasuperboy** [SleepyTrousers/EnderIO#4930]
#### Steps to reproduce:

1.There is no way to reproduce it because it happens only to 1 of my survival worlds. I can send you my whole mod pack and my world that is does it on if you need it to debug it. I just need to know where i can send it on if you do need it. The reason why is because the world it almost 3 gigs big. I really want some help with this world. I dont want to start fresh on another survival world. The reason why is because i have almost 3 years worth of progress on that world.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.37
- EnderCore: 1.12.2-0.5.43
- Minecraft:1.12.2
- Forge:1.12.2-14.23.5.2768
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 

[https://paste.dimdev.org/utehebibec.mccrash]

**Comment by mindforger** [comment]
what the? this crash looks like you have placed a LOT of painted doors all over the place O_o

or something acting funny making your world believe you'd have a set of chunks filled with doors

can you imagine anything in your world that matches my description ?

**Comment by HenryLoenwind** [comment]
Yes, plenty of doors that drop because there's no floor below them. That's vanilla logic and only shows up in our code because we had to copy it to add the paint data to the dropped item.

So either you managed to place a whole bunch of doors either into the air or on something like sand, or you've got a corrupt world save and those were not supposed to be doors.

**Comment by mindforger** [comment]
best guess would be to throw this world into mcedit and look at the given coordinates to look yourself whats wrong with the world at this spot

**Comment by joshuasuperboy** [comment]
No there is no painted doors any where

**Comment by joshuasuperboy** [comment]
i have never painted any doors thats why i need help my other blocks get scrambled and replaced with other blocks.

**Comment by joshuasuperboy** [comment]
Other blocks get changed to random blocks only when i add certain mods.

**Comment by joshuasuperboy** [comment]
l went into mc edit and i can see a bunch of doors from something but i did not place any doors

**Comment by joshuasuperboy** [comment]
also i wish i can send you a screen shot of the things that happens like my entire house got turned into air all that remains is just a bunch of doors

**Comment by joshuasuperboy** [comment]
this is my world in the working state
![desktop screenshot 2018 10 31 - 12 14 20 06](https://user-images.githubusercontent.com/32559193/47806038-03494880-dcf6-11e8-918c-c82174a15f8a.png)

**Comment by joshuasuperboy** [comment]
When i add a mod like thaumcraft imagine all these blocks got changed with other blocks or fluids.

**Comment by joshuasuperboy** [comment]
See this this is a steppe biome 
![desktop screenshot 2018 10 31 - 12 17 48 16](https://user-images.githubusercontent.com/32559193/47806221-6fc44780-dcf6-11e8-8c02-e2c43a138750.png)

**Comment by joshuasuperboy** [comment]
Imagine all these blocks get changed to fence gates or doors like you said when i update this mod or update other mods or add new mods like thaumcraft

**Comment by joshuasuperboy** [comment]
It just does not happen in one area it happens all over. I even tried switching dims to another dim that was not like that and it still crashed me. The reason why is because it even messes up my RFTools dims

**Comment by joshuasuperboy** [comment]
actually here is the pic i got from last time i tried this 
![3fusi4z](https://user-images.githubusercontent.com/32559193/47807033-51f7e200-dcf8-11e8-9b5c-5776e6f28b1f.jpg)

**Comment by joshuasuperboy** [comment]
i manged to get a pic of it before it crashed

**Comment by joshuasuperboy** [comment]
Im expecting to see this old pic again in game

**Comment by joshuasuperboy** [comment]
Also i think ima have to start fresh and i do not want to because i have almost 3 years worth of progress on this world

**Comment by joshuasuperboy** [comment]
i think more than 14K hours in that world i really dont want to give up on it

**Comment by HenryLoenwind** [comment]
We have absolutely nothing to do with world saving or id mapping. That's Forge's job.

**Comment by joshuasuperboy** [comment]
so its forge who broke my world?

**Comment by tterrag1098** [comment]
You have some mod hacking the ID limit like NotEnoughIDs? If so take it up with them.

**Comment by tyler489** [comment]
Please use the edit button next time... and keep it to relevent.. i get a email for every post and an alert for every email....
