### ISSUE TITLE
Suggestion - Creative machine Capacitor

### ISSUE THREAD

**Issue by DemonToaster** [SleepyTrousers/EnderIO#4931]

**Comment by tterrag1098** [comment]
How would this be faster/easier than using a creative capacitor bank?

**Comment by DemonToaster** [comment]
Because it would make the machine's processing speed faster , You need to put a capacitor in the machine regardless of having a creative capacitor bank. So why not 2 birds with one stone.

**Comment by tyler489** [comment]
Run this command /give @p minecraft:bedrock 1 0 {eiocap:{level:9.999f}}
