### ISSUE TITLE
EnderIO Endergy Conduits not obeying EnderIO conduit tier connection config

### ISSUE THREAD

**Issue by pupnewfster** [SleepyTrousers/EnderIO#4932]
#### Issue Description:

EnderIO Endergy does not obey the config option from EnderIO conduits about being able to connect different tiers. 

#### What happens:

EnderIO energy conduits and conduits from EnderIO Endergy do not connect even with `canDifferentTiersConnect` config option set to true in `enderioconduits.cfg`

#### What you expected to happen:

EnderIO energy conduits and conduits from EnderIO Endergy to connect.

#### Steps to reproduce:

1. Enable `canDifferentTiersConnect` in `enderioconduits.cfg`
2. Place an EnderIO Energy conduit down and place an EnderIO Endergy conduit next to it.
3. They do not connect.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.37 Monolithic and 1.12.2-5.0.37 Endergy
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 14.23.5.2772
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 

Nothing about it shows up in the log.

**Comment by tyler489** [comment]
Not really a bug.. more of an unimplemented feature on  endergys end.

**Comment by pupnewfster** [comment]
I figured it was just something that never got implemented, however I was keeping to the issue format. It still would be a nice feature to have implemented especially given logically as energy conduits it would make sense if they obey the config about energy conduits.

**Comment by HenryLoenwind** [comment]
Endergy energy conduits are not handled differently in any way than the standard ones. Are you sure this is only about them?

**Comment by pupnewfster** [comment]
Not sure how it happened but after doing some testing I found that my config file somehow looked like this https://pastebin.com/Fg87hUZt So the issue is that it was reading it as false. No idea how that happened especially as I had checked my config a few times before when I noticed that they would not connect but it works now.

**Comment by HenryLoenwind** [comment]
yes, that is a known issue with Forge's config system. No longer used values will just stay in there---like all those in "condit" when we fixed the spellng.
