### ISSUE TITLE
Bad compatibility with GT

### ISSUE THREAD

**Issue by Wettix** [SleepyTrousers/EnderIO#4936]
#### Issue Description:

Ender io add a bad compatibility for smelt dust

#### What happens:

i explain, i play with Gregtech CE on 1.12, and this mod add a mechanic for smelt certain dust, with only use a blast furnace, and ender io add a compatibility with these dust, they can smelt into a normal furnace and that break the logic of gregtech

#### What you expected to happen:

A way for delete this compatibility who add ender io

#### Steps to reproduce:

1. install only gregtech and jei, look up the way for smelt Tungsten dust for exemple, he can only smelt into GT blast furnace
2. now install gregtech, jei and ender io, tungsten can be smelt into a vanilla furnace

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.37
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12
- Forge: 14.23.2759
- SpongeForge? no
- Optifine? no
- Single Player and Server

#### Your most recent log file where the issue was present: 

i think is not useful

**Comment by tyler489** [comment]
just Disable the recipe in the XML. All Recipes are able to be customized.
