### ISSUE TITLE
Dimensional Tranciever - No MaxIO option avaible in config file

### ISSUE THREAD

**Issue by InvicTech** [SleepyTrousers/EnderIO#4937]
#### Issue Description:

For some reason the option to change the trancieverMaxIoRF config option was removed in one of the EnderIO Updates :(

#### What happens:

The Tranciever is stuck at it's stock value for MaxIO 208000 RF/t.

#### What you expected to happen:

I'd like to change this value in order to be able to run my entire power plant (Extreme Reactors) on one channel.

#### Steps to reproduce:

1. Look at the config file
2. Look at the source code for the config file of tranciever
[https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-machines/src/main/java/crazypants/enderio/machines/config/config/TranceiverConfig.java](url)
3. Have mercy with me and hear my prayers :D pls
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.36
- EnderCore: EnderCore-1.12.2-0.5.41
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2772-universal
- SpongeForge? no
- Optifine? N.A.
- Single Player and Server?

#### Your most recent log file where the issue was present: 

N.A.

**Comment by InvicTech** [comment]
Ok, adding these values from `capacitor_machines.xml` to `user_recipes.xml` works, but it's not displayed properly in-Game
`<capacitor key="enderio:block_transceiver/intake" base="409600" scaler="POWER" />`
`<capacitor key="enderio:block_transceiver/buffer" base="4000000" scaler="CUBIC" />`
![2018-11-06_21 01 00](https://user-images.githubusercontent.com/20909194/48090575-9a873200-e207-11e8-812d-75fe65191e0c.png)
![2018-11-06_21 01 08](https://user-images.githubusercontent.com/20909194/48090589-a1ae4000-e207-11e8-85ac-6f00a72e9d10.png)

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/48096444-6c115300-e217-11e8-9d64-139f881ef30b.png)

**Comment by InvicTech** [comment]
It was reproducable ;D
The reason for not showing the correct numbers was me only changing the values on server-side and not applying the changes to the client as well.

**Comment by tyler489** [comment]
Yep thats why
