### ISSUE TITLE
server tick took 90.00 seconds

### ISSUE THREAD

**Issue by instinxx** [SleepyTrousers/EnderIO#4938]
#### Issue Description:
Server crash possibly related to Extra Utils Trash Can,

#### What happens:
Server Crashed, I am not sure if this was someone's automated system or an active player.

#### What you expected to happen:
More ticky less crashy

#### Steps to reproduce:

1.From the logs it seems to be item conduits feeding an extra utilities 2 trash can.
2. extrautils2-1.12-1.9.8
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.12.2-5.0.36
- EnderCore:1.12.2-0.5.41
- Minecraft:1.12.2
- Forge:1.12.2-14.23.5.2768
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/LiVuRJKY

**Comment by tyler489** [comment]
I think this is an ex2 issue. From the looks of it enderio asked the chest if it can insert the chest replied yes.. then failed to take the item.

**Comment by HenryLoenwind** [comment]
A WatchDog report is completely useless. It only tells you what the server was doing the instant it fired, not how it spent that time it's complaining about. Install Sampler and get its stalling reports.

**Comment by HenryLoenwind** [comment]
"refinedstorage.apiimpl.autocrafting", sounds about right, RS autocrafting is famous for stalling.
