### ISSUE TITLE
machine explodes

### ISSUE THREAD

**Issue by avidgamer5918** [SleepyTrousers/EnderIO#4939]
#### Steps to reproduce:

1.place any machine that accepts capacitors 
2.place down a creative energy source from ex2 
3.watch it blow up amazingly 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:5.0.37
- EnderCore:na
- Minecraft:1.12.2
- Forge:14.23.5.2768
- SpongeForge? no
- Optifine? no
- Single Player and/or Server?single player

**Comment by tyler489** [comment]
Not a bug. Its a feature added to stop mods from spamming power packets bypassing enderios hard coded  limits to intake/output

**Comment by tterrag1098** [comment]
https://github.com/rwtema/Extra-Utilities-2-Source/blob/master/1.10.2/src/main/java/com/rwtema/extrautils2/tile/TileCreativeEnergy.java#L59-L67
