### ISSUE TITLE
[Tinkers' Construct] When I cast dark steel, the item disappears after cooling down

### ISSUE THREAD

**Issue by halpishooes** [SleepyTrousers/EnderIO#4940]
#### Issue Description: 
When I cast anything with dark steel, the casted item disappears after cooling down. [I have a video of it.](https://youtu.be/yHPCVkVXySE)

#### What happens:
The casted item simply vanishes. Nothing else.

#### What you expected to happen:
I expected the item to be kept on the casting table, so I could pick it up.

#### Steps to reproduce:

1. Smelt dark steel in a smeltery from Tinkers'
2. Try to cast anything with it
3. The casted item will disappear

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.36
- EnderCore: 0.5.41
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Tinker's Construct: 2.10.1.87
- Mantle: 1.3.2.24
- SpongeForge? No
- Optifine? Yes
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

It doesn't cause any crash.

**Comment by tyler489** [comment]
Did u  figure it out?

**Comment by halpishooes** [comment]
I'm sorry, I should have replied. Yes, I forgot I had put a hopper under my casting table.
