### ISSUE TITLE
Powered Spawner Automatic %100 Glitch

### ISSUE THREAD

**Issue by RikkoFrikko** [SleepyTrousers/EnderIO#4943]
#### Issue Description:

After automating the setup in my survival world and setting the spawner to require a redstone input I noticed with a lever in off position it would still increase spawner finish time slowly, but noticeably(I don't believe this is intentional either) and I don't believe it is consuming power either. I then changed to using a button, I always expected it to take a while so I would adventure in between waiting. However I became suspicious as at one point when I returned to check on the percentage it was already at %100 ready to spawn the mob, it shouldn't have been. so I initiated it to reset it. when it went back off it was at about %11, so I went out far enough to unload the chunk, but not too far to not be able to return within a few seconds(I had an Angel Ring to move fast and fly). Upon returning to the reloaded chunk the Spawner was at %100 and didn't consume any of the power of my generator. I'm using leadstone flux pipes to deliver power to the Spawner from an Extreme Reactor, did not try it with an Ender IO energy producing machines. Doing this only ends up consuming the energy the Spawner has stored and requires no additional energy. I did some quick math with my Wither Skeleton Powered Spawner. Normally it takes about just under 500,000 units of energy for about %10 progress with the Spawner, so it needs just under 5 million units of energy for this spawner to finish. Doing this though I only end up using just over 500,000 units of energy. That's ten times less then what it's intended to cost.

#### What happens:
unload chunk with Powered Spawner with any%. Reload chunk, Powered Spawner now at %100 and did not consume any power.

#### What you expected to happen:

Powered Spawner stays at % when reloading the chunk when it has any%

#### Steps to reproduce:

1. have spawner start off at any% where within reason it can not reach %100 upon reloading chunk
2. Travel far enough distance ~~at least 150 blocks away from chunk~~ to unload it, you can ~~teleport away or~~ fly away.
3. travel back on foot or flying to reload chunk with spawner, check on spawner now at %100
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.37
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2769
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
Does the same happen if its set  to redstone off and a block of redstone is placed ontop

**Comment by RikkoFrikko** [comment]
A redstone block on top of the spawner? I can try it, and report back with the results
