### ISSUE TITLE
Magnesium Diboride Alloy

### ISSUE THREAD

**Issue by NillerMedDild** [SleepyTrousers/EnderIO#4944]
#### Issue Description:
This bug occurs in the Enigmatica 2: Expert Skyblock modpack, of which I am the current maintainer.

#### What happens:
Lithium + Manganese Dioxide Ingots in the Alloy Smelter yield Magnesium Diboride Alloy

#### What you expected to happen:
Lithium + Manganese Dioxide Ingots in the Alloy Smelter yield Lithium Manganese Dioxide Ingots

#### Steps to reproduce:

1. Place and power an Alloy Smelter, give it any Capacitor
2. Supply Lithium Ingot and Manganese Dioxide Ingot
3. See the output
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.37
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

https://gist.github.com/NillerMedDild/bef4cc932a98c04ac627147eea36504f

**Comment by HenryLoenwind** [comment]
```
  <recipe name="Alloy: Magnesium Diboride Alloy (Nuclearcraft)" required="false">
    <alloying energy="4000" exp="0">
      <input name="ingotMagnesium"/>
      <input name="ingotBoron" amount="2"/>
      <output name="ingotMagnesiumDiboride" amount="3"/>
    </alloying>
  </recipe>

   <recipe name="Alloy: Lithium Manganese Alloy (Nuclearcraft)" required="false">
    <alloying energy="6000" exp="0">
      <input name="ingotManganeseDioxide"/>
      <input name="ingotLithium"/>
      <output name="ingotMagnesiumDiboride" amount="2"/>
    </alloying>
  </recipe>
```

so, what's the oredict name for the correct output? Tyler?

**Comment by VT-14** [comment]
According to the screenshot in the original issue, `ingotLithiumManganeseDioxide`

**Comment by tyler489** [comment]
Woops
