### ISSUE TITLE
Warning: smelting non-EnderIO recipes in EnderIO machines

### ISSUE THREAD

**Issue by mundik** [SleepyTrousers/EnderIO#4947]
#### What happens:
After starting a server, this warnings show for every recipe that isn´t from EnderIO, but can be made in Alloy Smelter. I don´t know if this can affect my server (lag spikes, crashing server etc.), but I want to be sure that my server is safe :)
- EnderIO: 1.12.2-5.0.33
- EnderCore: 1.12.2-0.5.39
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2768-universal
- Optifine: yes
- Server

![Server loading screen](https://user-images.githubusercontent.com/40388573/48408026-8fb52b80-e738-11e8-92c7-13bc97936394.png)

**Comment by tyler489** [comment]
Just some forge warnings telling mods to not use oredict it seems -_- its fine

**Comment by tyler489** [comment]
Just some warnings from forge. Not a big deal.

**Comment by mundik** [comment]
Just this, which must be created on 1st launch of mod:
```
<?xml version="1.0" encoding="UTF-8"?>
<enderio:recipes xmlns:enderio="http://enderio.com/recipes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enderio.com/recipes recipes.xsd ">
</enderio:recipes>

```

**Comment by tyler489** [comment]
not a big deal then.. just forge being forge
