### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by Smario9000** [SleepyTrousers/EnderIO#4948]
#### Issue Description:
Compact Mech. Blocks and Ender IO Conduits

#### What happens:
https://github.com/Sunekaer/stoneBlock/issues/588
Link for more info
But the  short version
Is I am trying to used item coudiuts with CM Blocks and I can't get it to work
Yes it is all set up right even tho the pictures say otherwise
Yes it is all chuckloaded
How do I know that this works
Because I can you the RF conduits and the fluids one too

#### What you expected to happen:

Be able to draw items from a drawer into a compact machine block into a compact machine block into an extreme reactor

#### Steps to reproduce:

Get steps here: https://github.com/Sunekaer/stoneBlock/issues/588

### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.37
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge:14.23.5.2768
- SpongeForge? no?
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by Smario9000** [comment]
It works with fluids, Rf, and refined system conduits but it does not work with item conduits for some reason 

I've even added a filter and personally changed all of the colors to match the right ones but it's still not pumping items out

**Comment by Smario9000** [comment]
There I updated the infor

**Comment by tyler489** [comment]
Does putting an item buffer next to the compact machine then pull from that fix it?

**Comment by EpicSquid** [comment]
Item conduits connect inventories. Since the compact machine doesn't count as an inventory it can't connect to them. This is more of a unfortunate interaction than a bug sorry.

**Comment by Smario9000** [comment]
The thing is he won't even pull it from the drawer and put it into the chess unless I'm in the same compact machine block
 but if I try pulling items from the drawer from a chest and put it into the compact machine block it doesn't read it

**Comment by diracs-delta** [comment]
For a small/medium Compact Machine (needing no more than 5 separate inputs), one can simply place your machines directly next to the tunnel inside the Compact Machine, and place the EnderIO conduit interface immediately outside. If done like this, EnderIO and Compact Machines v3 are perfectly compatible. The only downside is that you will need a separate tunnel to route power into the Compact Machine, as each tunnel is blocked by the machines.
