### ISSUE TITLE
[SUGGESTION] Option to disable Ender IO loot from chests

### ISSUE THREAD

**Issue by Sunconure11** [SleepyTrousers/EnderIO#4949]
I've been working on my pack, and I've come to the conclusion that this is needed. Mainly since I only have Ender IO Zoo in, and I am trying to shave off the other recipes to as much as possible.

**Comment by HenryLoenwind** [comment]
https://github.com/SleepyTrousers/EnderIO/wiki/Loot-Tables

**Comment by Sunconure11** [comment]
Sorry, need to ask a question regarding your loot tables, just to make sure I'm not missing something obvious. I also noted an issue when looking into this. https://github.com/Daomephsta/LootTweaker/issues/45

Would I use the pool `Ender IO` or `main` for getting the name? Since while` Ender IO` seems to work, it seems to throw an error anyways that LootTweaker picks up.

![screenshot 2018-11-13 23 55 48](https://user-images.githubusercontent.com/5614902/48461024-b490b980-e79f-11e8-91db-922ebb21505f.png)
![screenshot 2018-11-13 23 56 42](https://user-images.githubusercontent.com/5614902/48461047-c96d4d00-e79f-11e8-9642-405b0c2e6980.png)

https://pastebin.com/YfDWutVP

**Comment by HenryLoenwind** [comment]
For loottweaker=> https://github.com/Daomephsta/LootTweaker/issues/45
