### ISSUE TITLE
Crash relating to config options

### ISSUE THREAD

**Issue by Sunconure11** [SleepyTrousers/EnderIO#4950]
#### Issue Description:

It would seem that disabling certain config options causes the game to crash. I am trying to make only EnderIO Zoo show through

https://paste.dimdev.org/edemuyuyep.mccrash

Config used: https://pastebin.com/hHb742P6

#### What happens:

Crash

#### What you expected to happen:

No crash

#### Steps to reproduce:

1. Disable LoadCoreRecipes
2. ???
3. https://paste.dimdev.org/edemuyuyep.mccrash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.37 Base
- EnderCore: 0.5.43
- Minecraft: 1,12,2
- Forge: 2772
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Presumably, both

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/edemuyuyep.mccrash

**Comment by tterrag1098** [comment]
By disabling the core recipes you are responsible for filling in the missing content. Some things cannot be missing.
