### ISSUE TITLE
Potion Conflict with Inspirations mod

### ISSUE THREAD

**Issue by piedpipr314** [SleepyTrousers/EnderIO#4951]
#### Issue Description:

Levitation potion conflicts with Inspirations' Resist potion.

#### What happens:

If correct ingredients are placed in cauldron (Inspirations implement), EnderIO's potion is prioritized over potion of Resist.

#### What you expected to happen:

I expect a conflict, wasn't sure which would appear until I actually checked in creative.

#### Steps to reproduce:

1. Install Inspirations mod alongside
2. Place down cauldron with fire underneath it (netherrack on fire, works)
3. Place three water bottles inside cauldron (or bucket and take out one bottle)
4. Drop Nether Wart in cauldron
5. Drop Shulker Shell in cauldron
6. Right click cauldron with empty bottle.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.37
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 14.23.5.2772
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

I also placed this conflict here: https://github.com/KnightMiner/Inspirations/issues/94

**Comment by piedpipr314** [comment]
Mod Dev KnightMiner was wondering if the levitate potion can be disabled, I found no such way to do it with the configs.

**Comment by HenryLoenwind** [comment]
1. The floating potion uses an Owl Egg as ingredient.
2. All Ender IO potion recipes can be freely edited by the user.
