### ISSUE TITLE
Iron Alloy Ingots can be problematic for autocrafting

### ISSUE THREAD

**Issue by FloxyTek** [SleepyTrousers/EnderIO#4952]
#### Issue Description:

I did a setup for autocrafting all alloy with a single alloy smelter. If i request more alloys at the same time like invar and bronze i allways get iron alloy ingots

#### What happens:

Iron Alloy ingots are created when requesting invar and bronze at the same time ( hardened upgrad kit from thermal)

#### What you expected to happen:

Smelting Invar and Bronze not Iron Alloy ingots

#### Steps to reproduce:

1.setup refined storage with autocrafting for Invar and Bronze in an alloy smelter
2.request hardened upgrade kit from thermal or anything else that needs 2 different alloy with on containing iron
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5-0.36
- EnderCore:1.12.2-0.5.41
- Minecraft:1.12.2
- Forge:
- SpongeForge? yes/no
- Optifine? yes/no - yes
- Single Player and/or Server? server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
and what's your point?

**Comment by tterrag1098** [comment]
You're outdated, the recipe for construction alloy was changed in .37

**Comment by Gimpler** [comment]
Use a separate alloy smelter for invar and other iron related alloys.
