### ISSUE TITLE
Minecraft 12.1.2 Default Recipe Book not work properly with Ender IO--Not Crashed

### ISSUE THREAD

**Issue by lawrencekellie** [SleepyTrousers/EnderIO#4953]
#### Issue Description:

Problem: the default recipe book for 12.1.2 does not work.  It does open, but it lists ALL the recipes in one large group.

I am using a custom mod pack, and when I added Ender IO, the above-described action took place.

I then installed the mod pack Absolute Ender, and from the very start of using it, the above-described action also took place.

It does appear to be a conflict with (maybe) Just Enough Resources.  But it DOES occur when EnderIO is added

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  EnderIO-1.12.2-5.0.37
- EnderCore: EnderCore-1.12.2-0.5.43
- Minecraft: 12.1.2
- Forge:  14.23.4.2705
- SpongeForge? NO
- Optifine? No
- Single Player

#### Your most recent log file where the issue was present: 

No crash report as doesn't crash.

**Comment by VT-14** [comment]
Intended feature.  The vanilla recipe book doesn't work very well in modded, so Ender IO replaces it to open a list of all 3x3 crafting recipes in JEI.

This tweak is a client side config option under in Ender IO's config (under the Personal section) called "recipeButtonReplaceWithJei"

**Comment by lawrencekellie** [comment]
You state, "vanilla recipe book doesn't work very well in modded."  Are you meaning that the vanilla recipe book doesn't work very well in Ender IO, or are you saying in all mods?  I have never had this problem occur without having ender io installed.

Thank you for the config option.  I do take umbrage to your classifying the recipe button of vanilla minecraft (this is in the config file) as "annoying."  Please keep your opinions to yourself.  But again I thank you for sharing the config option.

Lawrence
