### ISSUE TITLE
The world disappears when i put water in the fluid tank.

### ISSUE THREAD

**Issue by Flowyan** [SleepyTrousers/EnderIO#4958]
#### Issue Description:

When I put water in the fluid tank the whole world disappears with the UI elements and everything.

#### What happens:

When I put water in the fluid tank the whole world disappears with the UI elements and everything.
This is how it looks like, when i have optifine on. When i dont use optifine then the whole world disappears (with the UI, inventory display and stuff like that).
![image](https://user-images.githubusercontent.com/26978520/48962962-4612df00-ef89-11e8-97a0-821415a18a89.png)

#### What you expected to happen:

That it would work normally as a FLUID TANK...

#### Steps to reproduce:

1. Play on a server i guess?
2. Place an empty fluid tank
3. Put water in it
4. If nothing happens, it might be my graphics card or smthing or something with a conflicting mod or settings.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.37
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2775
- SpongeForge? no
- Optifine? yes but works even without optifine
- Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/ptP2gEKE

**Comment by tyler489** [comment]
Odd.  Do you have any other  graphics modifing mods? Fastcraft foamfix?

**Comment by Flowyan** [comment]
I dont know if Betterfps counts for a graphic modifying mod but i have betterfps.

Yes but only for flags for the flagged mod.

And yes the tank opens a gui, but only when the water is not in it. When the water is in it the gui opens but its invisible because when the water is in the tank "the whole world disappears"

**Comment by HenryLoenwind** [comment]
The tank isn't doing anything weird, quite the opposite---rendering 5 fluid quads is as "standard" as it gets for a TESR.

So far you seem to be the only one to have this issue, so I'd recommend you do some testing to find out which combination of mods causes this. For that, remove mods until it stops happening. (You will want to create a creative world for this...)

**Comment by Flowyan** [comment]
The problem is, it only works on the server. And the server isnt owned by me. I cannot change anything. And it doesnt work in creative.

**Comment by Flowyan** [comment]
Ok i think i know the issue now. Its an issue with the flagged mod. For some reason the bug only happens when the flag and the tank are close to each other.
