### ISSUE TITLE
Conduits misbehaving and wrench interactions

### ISSUE THREAD

**Issue by DynoEnviro** [SleepyTrousers/EnderIO#4962]
#### Issue Description: Updated to EIO 5.0.38 and ECore 5.43 - restarted local and server, loaded fine - I DID NOT CREATE A NEW WORLD. Wrench interaction with conduits appears buggy. I'm reporting new issue, as I believe I read another similar issue that is closed as fixed. 

EDIT: was using EIO 5.0.33 and ECore 5.39 prior to update - that is what my world is based on, and in it the conduits exhibited the same behaviors reported here. Removed and relaid some of the existing conduits and they still behaved the same way.

#### Steps to reproduce:

1. lay some conduits that connect to receptive machines
2. use redstone conduits in the conduit bundle
3. attach lever, equip wrench, try to turn on and interact using wrench

#### Affected Versions (Do *not* use "latest"):  

- EnderIO: EIO 5.0.38
- EnderCore: ECore 5.43
- Minecraft: 1.12.2
- Forge: Forge Mod Loader version 14.23.4.2759
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Server

**Comment by tterrag1098** [comment]
This is intended behavior if the yeta wrench is in one of the special modes. Shift+scroll to switch to other modes.

**Comment by DynoEnviro** [comment]
So is the issue of the redstone conduits not working with the TE dynamo a TE problem? Apologies, I kind of mixed two issues together.

**Comment by tterrag1098** [comment]
Definitely not. If you have a separate issue, please report it separately.

**Comment by DynoEnviro** [comment]
Thanks T - I found a prior reported issue (closed) that gave me an idea to try, and was able to make the redstone conduits work. I realize it may be inheriting the channel color configuration, but it does feel a little wonky in the workflow that after laying the conduit and forcing a connection you have to change the output color (which I would swear I tried before, but maybe not) - would seem more natural (only for the redstone conduit) that the default input and output would be the same color since the most common usage is as "wire" vs. a binary flow path.  Disregard issue though - both were operator error!
