### ISSUE TITLE
Right click on Enhanced Combustion Generator with liquid stone pipe from BuildCraft

### ISSUE THREAD

**Issue by EvoWebFrance** [SleepyTrousers/EnderIO#4963]
#### Issue Description:
Right click on an Enhanced Combustion Generator with Liquid Stone Pipe for coolant liquid (water) from BuildCraft make the client crash. [Issue on BuildCraft ](https://github.com/BuildCraft/BuildCraft/issues/4305)

#### What happens:
Client crash

#### What you expected to happen:
Open Enhanced Combustion Generator GUI. I must break the pipe connected to the generator to have the GUI.

#### Steps to reproduce:
1. connect a Liquid Stone Pipe from BuildCraft
2. right click
____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: 1.12.2-5.0.36
- EnderCore: 1.12.2-0.5.41
- Minecraft: 1.12.2
- Forge: 14.23.5.2770
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 
[Link on the crash dump](https://1drv.ms/t/s!AlxEbPeMguZpgYJVMur8vLBZnsUvBA)

**Comment by HenryLoenwind** [comment]
Buildcraft has a FastTESR that wants to start drawing---which is the one thing FastTESRs cannot do.
