### ISSUE TITLE
Reproducible client freeze relating to water and Dark Steel Boots Jump III

### ISSUE THREAD

**Issue by mobro09** [SleepyTrousers/EnderIO#4966]
#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first. If you are using an unreleased version of Ender IO (a.k.a development/nightly version), please don't open an issue for features that have not been announced as "finished" or "working". Expect to be ignored if you ignore this template.

#### What happens:

Using just the dark steel boots in this mod alone with endercore... we tested plain dark steel boots, dark steel boots with flippers enchant only, and finally the culprits werethe boots which had empowered I and jump III. Passing through a stream of water while jumping (and occasionally while jumping on land), on a self hosted server with a friend of mine. Hard freeze with no crash report, need to end task to exit minecraft. Does not happen/is not reproduced in single player, and the freeze often happens to the player not in the water.

#### What you expected to happen:
Walk through the water or jump without a freeze.

#### Steps to reproduce:

1.Use just EnderIo and Endercore
2.Equip Jump III Dark steel boots
3.attempt to jump with another player present in a server hosted game. While in water will occur within seconds.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.38.jar
- EnderCore:EnderCore-1.12.2-0.5.43.jar
- Minecraft:1.12.2
- Forge: 14.23.4.2705
- SpongeForge? no
- Optifine? yes and no (tested with both)
- Single Player and/or Server? Server only. *with another player present* does not occur solo

#### Your most recent log file where the issue was present: 

No log file is presented as the game freezes and has to be ended manually.

[pastebin/gist/etc link here]

**Comment by mobro09** [comment]
I realise this is present in atleast 2 other threads in some shape or form, but me and my friend just spent about 20 hours or so testing to figure out why our game was freezing and narrowed it down to this after a lot of research. If you require any more finer details please feel free to comment

**Comment by HenryLoenwind** [comment]
When the game is frozen for a while, crash it by holding F3+C (I think it was C, look it up if it doesn't work) for 5 seconds. Attach that crash log here.

Also, please link in the old ticks if you are aware of them. While I'm not happy with dupes, sometimes shifting to a new clean ticket makes sense.

**Comment by HenryLoenwind** [comment]
you're right, manually crashing might not work if the game is not going through keyboard handling at all.

In that case you need an external debugger to get a thread dump. As you managed to reproduce this and we never managed that, I'd be grateful if you could do that. The easiest way probably is installing a JDK (Java Development Kit) and using the jvisualvm program that is included with it. Start that while the game is running and attach to the game by double-clicking it in the left pane of visualvm. One of the tabs will have a way to get a thread dump. Get one while the game is frozen, of better, get a couple of them as that will tell us more about which code is being processed.

If you need more help, I can make a couple of screenshots on how to do it tonight.

**Comment by mobro09** [comment]
That would be great man any help is appreciated, I'll check it all out and let you know the results

**Comment by mobro09** [comment]
Three thread dumps,  just after the game froze (within about 30 seconds of eachother) all with my friend wearing Dark Steel Boots; Empowered IV, Jump II, Flippers.

Thread dump 1:https://pastebin.com/q6P02zXZ
Thread dump 2:https://pastebin.com/4D9V9M1M
Thread dump 3:https://pastebin.com/8jyQjnvV

Hopefully this helps

**Comment by HenryLoenwind** [comment]
Yes, this is perfect.

Funny thing---we know this freeze, we just never knew how it happened...

**Comment by tterrag1098** [comment]
Seen this before...somehow a particle is accelerated to insane speeds which causes a collision check across millions or billions of blocks - effectively an infinite loop.

**Comment by mobro09** [comment]
Oh wow, yeah at first we thought this was relating to our java version, or our forge version, or a mod conflict, or the version of minecraft itself, we eventually stripped it back to vanilla and erased all modded blocks from our world and the water bug wasn't present. 


After this we somehow clued that it may be the boots as the freeze began around the time we produced the armour, then it all just became clearer.

So, is it something difficult to fix or not sure just yet?

**Comment by HenryLoenwind** [comment]
Jump boost spawns extra particles, not just water splash and ground ones. My current guess is those calculating wrong values when spawned for another player. Still that doesn't explain why it only happens in water. Maybe something adds up when they are spawned in water? But then it doesn't happen for the original player...

**Comment by Corosauce** [comment]
Ah yeah I was gonna suggest disabling the jump particles as a fix in the meantime if no real fix is coming soon, currently cant use jump boots cause of the chance of freezing.

**Comment by HenryLoenwind** [comment]
Yes, the motion data of other players is not sent to the client, as their movement is not speculative like mobs'. When another player laggs out, they freeze.

But it seems water movement doesn't know about that and puts values into there anyway. And because they are never cleaned up by any other physics (e.g. ground collision) they can get quite insane.

**Comment by jthantranon** [comment]
This bug has been happening for at least a year. Last year I narrowed it down to EnderIO armor (probably boots) as well. Exactly as described by everyone else here.
