### ISSUE TITLE
Please Register Loot Tables for Ender IO Zoo Mobs (suggestion, LootTweaker integration, possible bug)

### ISSUE THREAD

**Issue by khift363** [SleepyTrousers/EnderIO#4969]
In developing my modpack I discovered that Ender IO Zoo was only registering loot tables for two of its many mobs. The loot tables "enderio:enderminy" and "enderio:lovechild" are registered, but no such loot tables are present for the other mobs in the mod. While some of the mobs seem to piggy back off of vanilla loot tables (the Fallen Knight definitely uses the Zombie loot table, for example), others such as the Concussion Creeper are clearly using new loot tables provided by Ender IO Zoo and those loot tables are unregistered and therefore out of reach for LootTweaker.

To confirm that this wasn't a mod interaction with another mod in my pack, I made a new instance with the following details:

Minecraft v1.12.2
Forge v14.23.5.2795
CraftTweaker v4.1.13
Ender IO Base v5.0.38
Ender IO Zoo v5.0.38
EnderCore v5.43
LootTweaker v0.0.8

In this instance, I created a new world and used the command "/ct loottables all" to dump all registered loot tables. I then checked in the "[Instance]\dumps\loot_tables\enderio" directory and confirmed that only "enderminy.json" and "lovechild.json" were present.

Considering that two loot tables are registered and that the others are unregistered it may be that this issue is the result of a bug and not oversight. To that end I spoke to Leviathan, the developer of LootTweaker, on his discord server and he suggested "remind[ing] them that they need to make sure the loot tables are registered at a fixed time." I don't personally know what that means, but maybe that is helpful to you.

Thank you for your time and understanding.

**Comment by HenryLoenwind** [comment]
You needing them just pushed that entry on my TODO list to the top ;)

**Comment by tyler489** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/13c8a3e59541853bcd7205c33bddec25ab7a5367
