### ISSUE TITLE
disconnect on joining vanilla server with enderio installed on client

### ISSUE THREAD

**Issue by krisjenner** [SleepyTrousers/EnderIO#4974]
#### Issue Description:

Enderio 5.0.36
ATM3Remix
Using sponge but reproduced without

#### What happens:

Connect to fallback server via BungeeCord (using Waterfall) when ATM Remix server goes down. Players can't connect to lobby server as "EnderIO Failed mod's custom NetworkCheckHandler"

#### What you expected to happen:

Players join vanilla server and it ignores mods

#### Steps to reproduce:

1. Install EnderIO 5.0.36 on client
2. Connect to vanilla server (with bungeecord?)
3. either time out or get [ERROR](https://ibb.co/YQ5YKD7)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.36
- EnderCore: 0.5.41
- Minecraft: 1.12.2
- Forge: 1.12.2--2768
- SpongeForge? yes
- Optifine? no
- Server?

#### Your most recent log file where the issue was present: 

[[pastebin/gist/etc link here]](https://paste.ee/p/yavrN)

**Comment by HenryLoenwind** [comment]
> Players join vanilla server and it ignores mods

modding doesn't work that way...

**Comment by krisjenner** [comment]
Alright. So if I installed EnderIO on the receiving server, everyone connecting to that would need to have it installed too? I've connected to other servers with lobbies running the same pack. Is there no way around this at all?

**Comment by krisjenner** [comment]
error when enderio is on server too. Works without enderio/endercore/endergy installed. [error](https://pastebin.com/MvKTb7Nj)
