### ISSUE TITLE
Issue with Electric lights (inverted and/or normal)

### ISSUE THREAD

**Issue by Luf2K14** [SleepyTrousers/EnderIO#4983]
#### Issue Description:
Since i started to play modded minecraft 1.12.2 i wanted to use the  Stoneblock modpack but since my laptop is weak (3GB RAM) i had to customize it for my self only with 80 mods (including EnderIO) but since i installed im having crashes just because of Electric Lights (but the crash report aims at EnderIO, random Things and Forgelin) and its all updated (because its a part of the main modpack i have to do manual) and it stopped for a few hours and it cameback ...
#### What happens:
sometimes it crashes but i dont know when its random

#### What you expected to happen:

To work fine? maybe :/ i know that modded content its always unstable :D

#### Steps to reproduce:

put them the inverted ones (because i dont wanna have a mess with cables :/ )

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.38
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2772
- SpongeForge? no
- Optifine? yes 1.12.2_HD_U_E2
- Single Player only

#### Your most recent log file where the issue was present: 

https://gist.github.com/Luf2K14/bbe4cc1e4f6aab6e5d527e7fb4862e74

**Comment by HenryLoenwind** [comment]
looks like a duplicate for #4978

**Comment by Luf2K14** [comment]
yeah but i only use the light (not the electric neither the wireless one) might be an ID conflict maybe?

**Comment by Luf2K14** [comment]
i think i know how it happened that ... world edit ... because sometimes when i use world edit it stays the light source and i have to go manually remove by placing blocks randomly to remove light sources (the good thing is that im using only 20~ chunks of a huge map [which belonged to a server that shut down almost 2 months ago]) i will clear all the lights and use chisel to 'fix' the problem

**Comment by Luf2K14** [comment]
ok i have been removing some lights and adding way more and somehow fixed the issue im not having anymore crashes (i still suspect it was world edit that doesnt update light sometimes) so if the mods or owner wanna close it go ahead
