### ISSUE TITLE
[Suggestion] Add the ability to set priority for energy endpoints

### ISSUE THREAD

**Issue by chuggafan** [SleepyTrousers/EnderIO#4986]
Essentially, what I would love to see is the ability to separate my energy overflow trash can from my "I'm storing this" piping to keep energy generation at a constant, the main use I've found for this is so that I don't have to constantly trash all of my Extra Utilities 2 generator power because I need to keep the rainbow generator running with one or the other generators, I do not believe it's useful for many other purposes, but it's a general annoyance I've found that to the best of my knowledge, not one mod that has RF transfer (or energy transfer) allows for this at all.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by MatthiasMann** [comment]
@chuggafan you can use the power monitor and redstone controlled energy buffer for this
