### ISSUE TITLE
[ Bug ] Simple Wired Charger

### ISSUE THREAD

**Issue by ItHurtsLikeHell** [SleepyTrousers/EnderIO#4987]
_I tried a bit 'in the issues of github and I did not seem to find anything related to this bug._

#### Issue Description:

I can not insert the "_Scooporator MX200 Turbo_" (**GenDustry**) in the Simple Wired Charger even if it is "seen" in the recipes.

**If you have already created such issues, could you send me the number?**

_else_

Is there anything I can do to solve? a custom recipes or something like that?

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.4.5.135
- EnderCore: 0.5.43
- Minecraft: 1.12.2
- Forge: 14.23.52795
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single Player. (but I also believe on servers)

#### Your most recent log file where the issue was present: 

I do not know what to send sincerely, if you need something specific, write to me

-ItHurtsLikeHell

**Comment by tterrag1098** [comment]
in the *blah*? what is a blah?

**Comment by ItHurtsLikeHell** [comment]
> 
> 
> Sorry, _in the Simple Wired Charger_ (we are the same person but with a different account)

It's the truth

**Comment by MatthiasMann** [comment]
@ItHurtsLikeHell haven't tried it myself (I use Gendustry and EnderIo, but also IC2 which I use to charge Gendustry items) - but EnderIO only supports FE (forge energy) as an API.

For Gendustry you can enable/disable forge power in the config - but should be enabled by default:
https://github.com/bdew/gendustry/blob/mc1.12/resources/assets/gendustry/config/tuning.cfg#L184

**Comment by HurtsAsHell** [comment]
so should I create a config in "config \ gendustry \ overrides" and disable this `cfg Forge { // (Forge IEnergyStorage)
    Enabled = Y
  }`?

@MatthiasMann
