### ISSUE TITLE
Ender IO Endergy incorrect dependency listing.

### ISSUE THREAD

**Issue by Dragnier** [SleepyTrousers/EnderIO#4988]
#### Issue Description:

Ender IO Endergy error when loading says it requires Ender IO Machines while the mod description does not nor does the mod auto-download it as a dependency.

#### What happens:

Minecraft/Forge Errors before loading fully.

#### What you expected to happen:

Minecraft/Forge to load properly and function.

#### Steps to reproduce:

1. Download Ender IO Endergy and allow it to pull all dependencies using Curse Launcher
2. Hit Play in the Curse launcher and Minecraft launcher
3. Minecraft/Forge halts loading and puts up the following error:

![ender io endergy error](https://user-images.githubusercontent.com/19270499/50532323-c4f9bb00-0ae5-11e9-8af9-fee46e76cfb5.PNG)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIOBase: 5.0.39
- EnderIOEndergy: 5.0.39
- EnderCore: 0.5.44
- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 
none

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/50532517-8cc09f80-0b1a-11e9-87c1-47fd7f4a51b2.png)

fixed.

The dependency on the machines module probably is just a copy&paste error, Still on it.
