### ISSUE TITLE
RAM issue with AnvilRecipeWrappers.

### ISSUE THREAD

**Issue by mrAppleXZ** [SleepyTrousers/EnderIO#4990]
Hello!
Looks like the **AnvilRecipeWrapper**s registered [here](https://github.com/SleepyTrousers/EnderIO/blob/72d7e592d5a90403600002bb4a791704f1058ba6/enderio-base/src/main/java/crazypants/enderio/base/integration/jei/DarkSteelUpgradeRecipeCategory.java#L57) consume a plenty (about 800M) of RAM.

To check it out, I've built a custom version of EnderIO with [anvil recipes registration removed](https://github.com/mrAppleXZ/EnderIO/commit/da1738534b64263aa581d295a38ac575112f9195) and then captured heap dumps of Minecraft with standard and custom versions of EnderIO.
**Standard** EnderIO:
![image](https://user-images.githubusercontent.com/7630912/50549712-e98b9980-0c83-11e9-9c96-d478319b1c51.png)
EnderIO **without anvil recipes registration**:
![image](https://user-images.githubusercontent.com/7630912/50549714-f3ad9800-0c83-11e9-8dc5-cc0646086b63.png)

#### Affected Versions
- EnderIO: 5.0.39
- EnderCore: 0.5.44
- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- No SpongeForge
- No Optifine
- Single Player

**Comment by HenryLoenwind** [comment]
see https://github.com/SleepyTrousers/EnderIO/tree/feature/jei_improvements
