### ISSUE TITLE
Russian translate trouble

### ISSUE THREAD

**Issue by Whitebrim** [SleepyTrousers/EnderIO#4991]
#### What happens:

Simple Furnace in Ender IO - 5.0.39 is called "Простаяч печь", but should "Простая печь"

#### What you expected to happen:

Translator trouble

#### Steps to reproduce:

1. Fix transation.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.39
- EnderCore: 1.12.2-0.5.44
- Minecraft: 1.12.2

**Comment by tyler489** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/744a07eba02e97195d83072b3c7b34838dbda2c7/enderio-machines/src/main/resources/assets/enderio/lang/ru_ru.lang#L152

**Comment by Whitebrim** [comment]
Yes.
tile.block_simple_furnace.name=Простая электропечь 
And one more:
tile.block_solar_panel.tooltip.detailed.line2=Должна иметь свободное пространство к небу

https://github.com/SleepyTrousers/EnderIO/blob/744a07eba02e97195d83072b3c7b34838dbda2c7/enderio-machines/src/main/resources/assets/enderio/lang/ru_ru.lang#L276

**Comment by Whitebrim** [comment]
and there're some new blocks that're not translated:

tile.block_lava_generator.name=Геотермальный генератор
tile.block_lava_generator.tooltip.detailed.line1=Вырабатывает энергию, остужая лаву.
tile.block_lava_generator.tooltip.detailed.line2=Следите за перегревом!
tile.block_lava_generator.tooltip.detailed.line3=Может быть остужен, если разместить вокруг генератора лед или разлить холодные жидкости.
enderio.gui.lavagen.heat=Нагрев


P.S. Lava generator isn't actually cooling down by placing ice or cold liquids around... Is is still is progress?
