### ISSUE TITLE
Increased Memory Needed with Updating

### ISSUE THREAD

**Issue by FallenEagle1** [SleepyTrousers/EnderIO#4993]
While updating the ATM 3 Remix pack, I ran into an interesting change in memory needed to run the modpack and traced it back to Ender IO and Endergy. I was curious if you were aware of it, or would be able to shed some light on this.

Testing was done at the main menu of the pack, but this increased amount of memory needed would continue through with loading a world and playing as well.

#### Issue Description:
When updating Ender IO, Endergy, and EnderCore for the dependencies, the amount of ram needed to run the pack jumps quite a bit. At first I was thinking it was just the nature of updating so many mods, but looking into it closer I found that the increase needed was due to just updating these three.

Currently the pack is using v36 of Ender IO and Endergy (v41 for EnderCore) and when these are updated to v37 or higher (v43 of EnderCore) the amount of memory jumps roughly 1.5 Gb. This memory jump affects the latest versions of the mods as well, v37 is when this jump starts to occur.

#### Testing:
To test this, I was using Visual VM to watch the memory that was being used by the java instance. I ran the 1.0.1 update for remix to get a baseline, and did the same thing again with every mod updated. There were a couple other changes to the fully updated because of other mod interactions, mainly removing one mod and not fully updating one other mod. I would then run the pack and let it load. Once it is to the main menu, I would let it run a couple minutes the use Visual VM to force a garbage collection and see what the minimum memory it would be using. Below is a picture of the chart I was using to track the memory allocation. 

#### What you expected to happen:
The memory needed to be roughly the same unless there was a very large addition to the mods.

#### Steps to reproduce:
When testing with just the three mods, the jump did not seem as significant, but still could see it. The main change was when they were update in the full pack.
1. Grab ATM 3 Remix
2. Update Ender IO, Endergy, and EnderCore to any update more recent than what is in the pack
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.37+
- EnderCore: 0.5.43+
- Endergy: 5.0.37+
- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Just on launching client for now for the testing. Affects singleplayer playing, but don't currently have numbers to show.

#### Files Used in Testing: 

![image](https://user-images.githubusercontent.com/22630113/50568191-cc021280-0d0b-11e9-8d03-601d9bc1e275.png)

The numbers are part of the number system I used to keep track of which mods I updated while testing. The pastebin below is a link to match up which mod was which number.
https://pastebin.com/RnZGzHnD

**Comment by HenryLoenwind** [comment]
#4875, #4990

**Comment by FallenEagle1** [comment]
I guess my question is more; Is there anything that can be done about this now on the modpack end, or is this more just wait for a release? One of the ones referenced from September.
