### ISSUE TITLE
Enhanced Combustion Generator missing Animation in UI

### ISSUE THREAD

**Issue by VallenFrostweaver** [SleepyTrousers/EnderIO#4995]
#### Issue Description:

The Enhanced Combustion Generator is missing the "Capacitor missing" animation in the UI

#### What happens:

No animation present at all (unanimated or otherwise).

#### What you expected to happen:

A notice to pop up like the Combustion Generator (or other capacitor requiring machines).

#### Steps to reproduce:

1. Place ECG and open UI
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.39
- EnderCore: 0.5.43
- EnderIO Machines: 5.0.39
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 
N/A

#### Image:
![temp](https://user-images.githubusercontent.com/13642054/50592459-1d391000-0e8c-11e9-907d-90132ca020b9.png)

**Comment by StackDoubleFlow** [comment]
This seems to not only be a problem with the ECG, but instead with all enhanced machines.
