### ISSUE TITLE
Client crash with conduits (?)

### ISSUE THREAD

**Issue by TheSnowyChickens** [SleepyTrousers/EnderIO#4998]
#### Issue Description:
Client crash (with VanillaFix installed just a "back to main menu crash") with conduits. (I think)
"Ticking entity"

#### What happens:
I leave my mob farm and then I got the crash.

#### What you expected to happen:
No crash.

#### Steps to reproduce:
Difficult to say, because it's on a multiplayer map and I just leave my mob farm area.

#### Affected Versions:
- EnderIO: 5.0.39
- EnderCore: 0.5.44
- EnderIO-endergy: 5.0.39
- GasConduits: 1.0.0
- Minecraft: 1.12.2
- Forge: 2796
- SpongeForge? no
- Optifine? no
- on a Server, but only client crash

#### Crash log: 
https://paste.dimdev.org/jamiyofefa.mccrash

#### Picture from my area:
![grafik](https://user-images.githubusercontent.com/29357962/50618235-c6feb800-0ef1-11e9-8910-3ac9a2810144.png)

**Comment by EpicSquid** [comment]
Remove vanilla fix and try again

**Comment by TheSnowyChickens** [comment]
I only can it remove from the client, but I don't know how to recreate this crash, because I thinks its random with the loaded terrain.

**Comment by EpicSquid** [comment]
If it can't be reproduced without vanilla fix then it most likely is on them, otherwise there isn't enough to go off in the crash log alone

**Comment by HenryLoenwind** [comment]
This is vanilla code crashing because a vanilla data structure contains invalid data, That data structures is normally not accessible to mods, and the vanilla code that can access it would not be able to put invalid data in there without crashing itself. So some mod is forcing its way in there and is messing things up.

**Comment by TheSnowyChickens** [comment]
In the last modpack version (with EIO 38) we never had a crash like this, I try it now without VF.
Used modpack: https://minecraft.curseforge.com/projects/deep-night?create=success (version 1.7 atm)
