### ISSUE TITLE
Painted doors let light through

### ISSUE THREAD

**Issue by clragon** [SleepyTrousers/EnderIO#5001]
### Issue Description:

Painted doors let light through, making them distinguishable from the blocks they are painted with

### What happens:

When a painted door placed next to the block it is painted with, light is let through the painted door, making it look quite different from a solid block.

### What I expected to happen:

The door and the original block to be looking completely the same without it letting light through making it basically hidden.

### Steps to reproduce:

1. Paint a door (tested with oak) with block X
2. Make a closed room with block X
3. Break a hole into it and place painted door there
4. Be amazed as light is let into this entirely solid room with a not so hidden door.

____
### Affected Versions:

- EnderIO: 5.0.38
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- SpongeForge? no 
- Optifine? yes
- Single Player and/or Server? Single Player and Server

#### Solid room:
![2019-01-05_00 36 28](https://user-images.githubusercontent.com/11785085/50716488-196ede80-1082-11e9-8be7-16da1c0c8e04.png)

#### Room with painted door:
![2019-01-05_00 36 41](https://user-images.githubusercontent.com/11785085/50716497-25f33700-1082-11e9-812c-34d79e6c9d7a.png)

#### Expected room with painted door:
![2019-01-05_00 36 52](https://user-images.githubusercontent.com/11785085/50716507-2d1a4500-1082-11e9-9d8b-d168edb246a5.png)

**Comment by clragon** [comment]
On a side note, since doors can be placed two ways, placing them with their angle on the right side (like placing the second door of a double door, the _right part_ of the door) the painted texture facing you will be inverted and it will look very weird when paired with the same block. 
I don't know if this can be fixed, but I kinda would appreciate it.

**Comment by clragon** [comment]
moving this to suggestions on ideawall.

**Comment by HenryLoenwind** [comment]
The mirrored texture is cause by the vanilla door model, we just re-texture that. Reason is that we want the painted door to follow any model changes a texture pack does to the vanilla door.

The light is a bit tricky. It's no possible to block light only in one direction, or one side of the block. So if we would block light when painted with a solid block, it would also block light if the door was placed sideways, or was open.

**Comment by clragon** [comment]
I see, that makes sense. 
_Maybe_ this could be implemented by letting the player have control over if the door acts as a solid block or not with an item or wrench or similar which switches the state of the door.
