### ISSUE TITLE
Suggestion: Wearable Enderman head and tormented Enderman head

### ISSUE THREAD

**Issue by mser7** [SleepyTrousers/EnderIO#5002]

**Comment by HenryLoenwind** [comment]
Don't suggest stuff that is already in.

**Comment by mser7** [comment]
That was quick

**Comment by HenryLoenwind** [comment]
I just was working on a wiki page when you opened the ticket ;)

BTW: Endermen heads will be wearable in the next version, we just put that in a couple days ago.
