### ISSUE TITLE
Slice'N'Splice does not accept ProjectE Shear

### ISSUE THREAD

**Issue by LuciusV** [SleepyTrousers/EnderIO#5008]
#### Issue Description:
Slice'N'Splice does not accept ProjectE Dark(Red) Matter Shears be put in

#### What happens:
Dark(Red) matter shears can't be put into Slice'N'Splice. But Dark(Red) matter axe can be inserted without issues.

#### What you expected to happen:
Dark(red) matter shears can be inserted, just 
Dark(red) matter like the axe can be

#### Steps to reproduce:

1. Make dark matter shears and try to put into machine
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  EnderIO-1.12.2-5.0.39
- EnderCore: EnderCore-1.12.2-0.5.43
- ProjectE-1.12-PE1.3.2h
- Forge: 1.12.2-14.23.5.2768

**Comment by HenryLoenwind** [comment]
Minecraft has no way of marking an item as shears, it only has "axe" and "shovel".

So if ProjectE wants their item to be recognized as "shears" universally, they need to `extend ItemShears` . Ender IO also recognizes the oreDict "toolShears".
