### ISSUE TITLE
[Suggestion] the padding upgrade for the dark/end steel helm should be disableable

### ISSUE THREAD

**Issue by LordMZTE** [SleepyTrousers/EnderIO#5012]
it is just annoying that i put it onto my helmet not knowing what it did and not being able to somehow disable it.
i don't really get the point of it anyway because you could just turn your sounds down that also has the added bonus of controlling how loud specific things are

so this is basically useless and not being able to disable it just makes it worse

**Comment by HenryLoenwind** [comment]
We're working on upgrade managment at the moment but it will take a while to be finished...

**Comment by ammahieu** [comment]
Any update on this? The padding seemed nice, but I want to turn it off

**Comment by VT-14** [comment]
There's been a new upgrade system for for several months now.  Just open the Dark Steel Upgrade GUI using a Dark Anvil (which itself can be a Dark Steel Upgrade) and move the Muffle upgrade from its active slot to one of the Storage slots.

A guide for the new upgrade system is on this GitHub's wiki.
