### ISSUE TITLE
[Suggestion] upgradable armor

### ISSUE THREAD

**Issue by LordMZTE** [SleepyTrousers/EnderIO#5013]
it would be really cool to be able to upgrade dark steel armour to end steel armour and that to stellar armour (if endergy is installed) without losing its upgrades and enchantments

maybe it could be done by making an upgrade kit from 10 ingots of the next material (end steel) in an alloy smelter (maybe with some other ingredient for preventing it being crafted on accident) and combining the armour with it in an anvil for the cost of about 20 levels

**Comment by HenryLoenwind** [comment]
It has been a design desicion not not provide this upgrade. Sorry...
