### ISSUE TITLE
Render crash with techreborn Lamp and block conduit

### ISSUE THREAD

**Issue by parlador** [SleepyTrousers/EnderIO#5015]
#### Issue Description:

So my client crash when trie to mix techreborn flat lamp with block conduit (with energy conduit inside) When the lamp is light on the rending crash.

#### What happens:

The client crash when I check techreborn lamp on a block conduit 

#### What you expected to happen:

 do not crash

#### Steps to reproduce:

1. place conduit power cable  (the cable need a power source)
2. paint and place a conduit block on the cable
3. place techreborn lamp on the block 
4. check the lamp... and crash!

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.39
- EnderCore: 1.12.2-0.5.44
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- TechReborn: 2.20.3.899
- RebornCore: 3.13.2.411
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? server

#### Your most recent log file where the issue was present: 

https://paste.ee/p/c5CDL

**Comment by HenryLoenwind** [comment]
Crash looks to me like facade painted as lamp?

**Comment by parlador** [comment]
finaly the problem was from MalisisDoors/MalisisCore changing rendering process... After removing malisisdoors and core mods, all work fine.

So just the present of malisiscore can affect techreborn led lamp placed on enderio  block conduit.
