### ISSUE TITLE
the game crashes when the world loads

### ISSUE THREAD

**Issue by KiraLinux** [SleepyTrousers/EnderIO#5017]
#### What happens:

when i try to enter the world the game crashes
it doesn't always happen
____
#### Affected Versions (Do *not* use "latest"):

EnderIO-base-1.12.2-5.0.874-nightly
EnderIO-conduits-1.12.2-5.0.874-nightly
EnderIO-conduits-appliedenergistics-1.12.2-5.0.874-nightly
EnderIO-endergy-1.12.2-5.0.874-nightly
EnderIO-integration-forestry-1.12.2-5.0.874-nightly
EnderIO-integration-tic-1.12.2-5.0.874-nightly
EnderIO-machines-1.12.2-5.0.874-nightly
EnderIO-zoo-1.12.2-5.0.874-nightly

EnderCore-1.12.2-0.5.45
- Minecraft: 1.12.2
1.12.2-forge1.12.2-14.23.5.2807
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 
https://gist.github.com/KiraLinux/fba69cea5c94ed9540a77105ebd2b578

**Comment by LumberWizard** [comment]
Update to build 877.

**Comment by LumberWizard** [comment]
This seems like a world corruption, I haven't been able to reproduce it with build 877 andAE2 RV6-stable6.

**Comment by tterrag1098** [comment]
World corruption could not cause this error. Regardless the crash happens in AE2 code, conduits are just calling it.

**Comment by LumberWizard** [comment]
You're right, I dunno how I could have missed this is a NoClassDefFoundError :P
