### ISSUE TITLE
[Suggestion] Sensor filter doesn't have all capabilities of comparator.

### ISSUE THREAD

**Issue by Bellwar** [SleepyTrousers/EnderIO#5018]
Idea: Make the Sensor filter editable with compare and subtract mode, to a signal strength that can _be set_/_be used from a channel_

Situation: I have to tanks which are being filled up from one machine. I want the machine to stop running when both of the tanks are full. Naturally, I want AND filter on output and two Sensors filters on tanks. The AND gate takes any strength and outputs 15 if both are above 0. So for this to work the way I want it, I had to use 5 channels (instead of 3) and do something like this to make it work [(Imgur)](https://imgur.com/a/7JKYtr8)

Pardon me if there is a way to do this or it is planned to be added.

**Comment by HenryLoenwind** [comment]
No need for the sensor to do that, there are plenty of ways to process the signal that was picked up by it.

Also:

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
