### ISSUE TITLE
Dark Leggins Swiftnes

### ISSUE THREAD

**Issue by zedner** [SleepyTrousers/EnderIO#5019]
#### Issue Description:
Dark steel leggins anvil recipe dont work with potion of swiftness.
using forge-1.12.2-14.23.5.2806, EnderIO-1.12.2-5.0.39, EnderCore-1.12.2-0.5.43

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft:
- Forge:
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by VT-14** [comment]
Use JEI to figure out which version of the potion you need.  I think you need the extended length version (redstone).

**Comment by zedner** [comment]
yep , works with potion 8:00 mins. sry
