### ISSUE TITLE
Soul vial blacklist

### ISSUE THREAD

**Issue by SSKirillSS** [SleepyTrousers/EnderIO#5022]
#### Issue Description:

Hello. After upgrading to a newer version of the modification, the ability to create a black list or soul vial was lost from the configuration file(or am i just blind ¯\_(ツ)_/¯). I don’t really like players to collect GalactiCraft bosses in them.

P.S Sorry for my English

#### Affected Versions:

- EnderIO: EnderIO-1.12.2-5.0.40
- EnderCore: EnderCore-1.12.2-0.5.45
The remaining criteria do not affect this issue.

**Comment by HenryLoenwind** [comment]
config/enderio/recipes/spawner.xml

**Comment by SSKirillSS** [comment]
@HenryLoenwind, There was a little time and I decided to address this issue. Immediately I ran into a problem, after starting the client / server the spawner.xml file returns to its original form.
Can you please edit the current file with these mobs:
[spawner.zip](https://github.com/SleepyTrousers/EnderIO/files/2872428/spawner.zip)
```
    "galacticraftcore:evolved_skeleton_boss",
    "galacticraftplanets:creeper_boss",
    "extraplanets:extraplanets.evolvedfirebatboss",
    "extraplanets:extraplanets.evolvedghastboss",
    "extraplanets:extraplanets.evolvedgiantzombieboss",
    "extraplanets:extraplanets.evolvediceslimeboss",
    "extraplanets:extraplanets.evolvedmagmacubeboss",
    "extraplanets:extraplanets.evolvedsnowmanboss",
    "extraplanets:extraplanets.evolvedspacemanboss"
```


P.S. Apologize for disturbing :c

**Comment by tyler489** [comment]
```
<!-- 

These are the built-in recipes. You cannot change this file, it is a
reference for you only and will be generated every time the game starts.

To make changes to the recipes, copy the recipes you want to change to
a file in the 'user' folder.

You can also disable all built-in recipes with the setting "loadCoreRecipes"
in the Ender IO config file, so that only your files in the 'user' folder will
be loaded. Please be advised that a number of recipes are absolutely needed,
so you will have to copy those over into a 'user' file for the game to load.

Recipes that have entities that cannot be
found in-game are either skipped or an error, depending on their "required"
attribute.

More information on the syntax can be found in the recipes.xsd file. An
XML editor will display that as tooltips when editing this file.

 -->
```
