### ISSUE TITLE
Conduit filters don't show item names when hovered over.

### ISSUE THREAD

**Issue by Tfarcenim** [SleepyTrousers/EnderIO#5027]
#### Issue Description:

No item names appear on conduit filters when hovered over in the GUI.

#### What happens:

The item is still visible, but can be difficult to distinguish because of it being faded.

#### What you expected to happen:

To show the name on hover like it is in the player inventory.

#### Steps to reproduce:

1.  Get an item or ender fluid conduit and place it against the side of a chest/tank.
2.  Add a filter to configure it input/output works.
3.  After configuring is complete hover over the item.
4.  Where did the tooltip go?

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  5.0.40
- EnderCore: 5.0.45
- Minecraft: 1.12.2
- Forge: 2808
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and/or Server? Singleplayer

#### Your most recent log file where the issue was present: 

![2019-01-31_17 47 31](https://user-images.githubusercontent.com/44327798/52091081-4333fc00-2581-11e9-8640-108aefd1d01c.png)

**Comment by pupnewfster** [comment]
If this is done, the same should probably be done for fluid filters.
