### ISSUE TITLE
Powered Dark Backhoe in the Farming Station got moved to the output slot when it is out of powered

### ISSUE THREAD

**Issue by mser7** [SleepyTrousers/EnderIO#5030]
#### Issue Description:

I was using an Empowered IV dark backhoe for my farming station, I then fully charged it, but overtime, the station report to me that it has no hoe, inspecting it reveal that the hoe got moved to the output slots, after its power is used up, it happened twice before I decide to report

#### What happens:
Provided above

#### What you expected to happen:
The hoe should stay in the slot it is resigned to

#### Steps to reproduce:
Provided Above
____
#### Affected Versions (Do *not* use "latest"):

EnderIO-1.12.2-5.0.40
EnderCore-1.12.2-0.5.45
- Minecraft: 1.12.2
- Forge:14.23.4.2760
- SpongeForge? No
- Optifine? No
- SSP

#### Your most recent log file where the issue was present: 

Screenshot:
![2019-02-02_20 28 36](https://user-images.githubusercontent.com/22555489/52171637-f162c000-2792-11e9-8fb8-50dc4744e1c7.png)

**Comment by mser7** [comment]
After the incident I made a non-empowered hoe with only Unbreaking III and it is working for me

**Comment by Thunder-Nova** [comment]
I set up a conduit to pull hoe into a charger and once charged puts it back.

It is intended
