### ISSUE TITLE
Powered Spawners and Broken spawners don't work as expected

### ISSUE THREAD

**Issue by Zajcu37Fan** [SleepyTrousers/EnderIO#5031]
(I'm sorry for any gramar mistakes or poor documentation, I serched as much as I could in a limited time and also pretty tired)
#### Issue Description:
I am not used to this mod (I'm not used to any mod actualy) but I saw that  I am uncapable of fusing (combining) certain broken mob spawners with a 'Empty' Powered Spawner

#### What happens:
I was looking up on Jei (just enough items) on how to use the broken mob spawner, soul vial (Evoker) and maybe powered spawner (because I didn't know how to use these), and I realized that there where 
56 broken mob spawners (including some other entities/mobs from other mods like Botania and Stupid 

things) but only s i x powered spawners (including the Empty powered spawner)

I tried to make a broken vindicator broken spawner, and it worked, but when I tried to combine it with the empty powered spawner it didn't work (in both vanilla and dark steel anvils), I also tried with the enderman powered spawner, and it didn't work. Only with the: Elder guardian, Wither, Evoker, Snow and Iron golems and Villagers didn'twork. Which is understandable.

The only thing that I didn't understand is why bother making a broken mob spawner for each enity in the game? I guessed that it's because maybe other mods implemented such spawners, but you guys only allow a few mobs to spawn from powered spawners, so if you don't need that spawner, u can convert it into a spawner which is aceptable for this mod. but the mistake in my oppinion is that u guys allow for these broken spawners to be crafted with the soul vials, even tho they aren't useful at all

#### What you expected to happen:
If the broken mob spawner CAN be crafted from the respective vial and a random Broken spawner then it should be useful

#### Steps to reproduce:

1. Make it so that if the spawner can be crafted, then it can be used, otherwise you shouldn't be able to craft it
2. If the broken spawners can still be crafted it the same way, it should at least have a RED warning message on the certain required vial (exp:Evoker) and broken spawner ona pretty obvious spot saying that it *can't* be used to craft powered spawners with only this mod (EnderIO/EnderCore) installed
3. Add the other Powered spawners to the curent version of Jei and EnderIO (I mean the specifed versions down below sorry)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- EnderCore: 0.5.45
- Minecraft: 1.12.2
- Forge: 8.0.99.99 or 14.23.5.2810 (really not sure)
- SpongeForge? no
- Optifine? yes 1.12.2_HD_U_E3 (also not sure)
- Single Player and/or Server?
Only Single Player
#### Your most recent log file where the issue was present: 
uhh none?
[pastebin/gist/etc link here]
![2019-02-09_21 54 40](https://user-images.githubusercontent.com/47483904/52526095-6b77d500-2cbc-11e9-9950-77b936f0e826.png)

**Comment by HenryLoenwind** [comment]
Did you actually craft those broken spawners? That recipe should not allow those to be crafted.

If you got the broken spawners from the creative menu: Yes, that's an oversight.

**Comment by Zajcu37Fan** [comment]
I was able to craft the evoker spawner I didn't try with the other ones

**Comment by tterrag1098** [comment]
The way the broken spawners work is that they just have an NBT tag for the entity type. So there are not actually 56 (or however many mobs your modpack has) items, just slightly different data on the same item. The code that generates these variants for JEI does not care about the recipe system, it's just looping over every entity in the registry.

So this is a non-issue (beyond what Henry has already fixed), those mobs that you could not craft are intentionally blacklisted from the recipe.

**Comment by Zajcu37Fan** [comment]
understood

**Comment by Francois-Michaut-Epitech** [comment]
> The way the broken spawners work is that they just have an NBT tag for the entity type. So there are not actually 56 (or however many mobs your modpack has) items, just slightly different data on the same item. The code that generates these variants for JEI does not care about the recipe system, it's just looping over every entity in the registry.
> 
> So this is a non-issue (beyond what Henry has already fixed), those mobs that you could not craft are intentionally blacklisted from the recipe.

Well, i actually just crafted a Villager broken spawner in survival with a soul vial and all, but i couldn't mix it with a powered spawner. 

I was able to craft the broken spawner so i was expecting to have a Villager powered spawner but i couldn't. However I'm able to craft a Zombie one.

You said if the recipe allows me to craft the broken spawner i can use it right ?

**Comment by HenryLoenwind** [comment]
I just noted a tiny glitch in the system. Both the spawner blacklist and the souldbinding recipe are *recipes*. They get registered in no particular order, however, the soulbinding recipe refers to the spawner blacklist. So if it is registered before the blacklist, it won't see it.

The anvil recipe, in contrast, does the blacklist check at runtime. It's a code recipe, not an xml recipe.

**Comment by koopaconroy** [comment]
I seem to be having the villager spawner issue in version 5.1.55 Core 0.5.73.

**Comment by Kazuto** [comment]
I can't combine any broken spawner with a powered spawner in an anvil. I've mined Skeleton, Spider and Zombie spawners but none of these can be combined with a powered spawner. Version 5.2.57.
