### ISSUE TITLE
Server loading stuck at Updating Config

### ISSUE THREAD

**Issue by Runevoice** [SleepyTrousers/EnderIO#5033]
#### Issue Description:

I try to start server and when server gets to reload configs for EnderIO and EnderCore and server stucks at [Server thread/INFO] [enderio]: Updating config...

#### What happens:

After starting server it doesnt load on successfuly and stucks at [Server thread/INFO] [enderio]: Updating config...

#### What you expected to happen:

I expected to be able to play on my server.

#### Steps to reproduce:

1. Ive setted up server engine to Forge at my server hosting
2. Added mods that I like
3. Started server
4. Server got stuck

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.39
- EnderCore: 0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2811
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/Lj8P710S
[debug.log](https://github.com/SleepyTrousers/EnderIO/files/2865613/debug.log) Its too big to upload it on Pastebin without PRO

**Comment by HenryLoenwind** [comment]
Please also upload the debug.log, thank you.

**Comment by Runevoice** [comment]
Done

**Comment by HenryLoenwind** [comment]
Thanks. It nicely shows that the hang is completely unrelated to what you see in the normal logfile. It is, however, in the main initialization code of Ender IO. Which is about 2-3000 lines of code and the line `if (user==Runevoice) { sleep(1000 years); }` is absent for some weird reason...

Do you have a jdk installed and can trigger a thread dump instead of killing the process outright?

**Comment by Runevoice** [comment]
Sorry, I dont have it and even if I would I dont know how to use it.

**Comment by MatthiasMann** [comment]
When you install and run Minecraft with a JDK then you can run in another terminal the command "jstack" or "jconsole" to get a stack trace of the Minecraft process. Do this a few times while it hangs and upload the stack traces.
