### ISSUE TITLE
Compact machines ME conduit support

### ISSUE THREAD

**Issue by DemonfangArun** [SleepyTrousers/EnderIO#5034]
More info here (please read, contains dev suggested fix): https://github.com/thraaawn/CompactMachines/issues/373

Simply put: ME conduits don't work through compact machines tunnels.

**Comment by HenryLoenwind** [comment]
ME conduits implement AE2's API. So if compact machines doesn't support AE2's API and if AE2 doesn't support compact machines's API, we can do nothing about this.
