### ISSUE TITLE
Recipe registry plugin crashed

### ISSUE THREAD

**Issue by calloatti** [SleepyTrousers/EnderIO#5035]
#### Issue Description:

I get an noticeable delay and an error in the console when using a crafting table or a refined storage crafting grid when doing certain actions involving the use of JEI.

#### What happens:

When trying to close the crafting GUI that pops up when you click on an item in JEI, there is a long delay before the crafting GUI closes.

The delay is longer when using a refined storage crafting grid, and shorter when using a standard crafting table.

When checking the console logs to see if there was anything that could explain the delays, I found an error that seems to blame EnderIO

#### What you expected to happen:

No delay and no error when using JEI in a crafting table/crafting grid

#### Steps to reproduce:

1.Open a crafting table GUI and search for an item in JEI, for example brick:

![2019-02-15_15 49 58](https://user-images.githubusercontent.com/12817862/52877667-6b069080-3139-11e9-9e55-ec1f220c6343.png)

2. Now left click on the brick slabs block to bring up the recipe:

![2019-02-15_15 52 50](https://user-images.githubusercontent.com/12817862/52877774-c3d62900-3139-11e9-943f-39444fd944f2.png)

3. Now **RIGHT CLICK** in the bricks block, to see what recipes use that block. This is the key step that generates the error.

![2019-02-15_15 54 34](https://user-images.githubusercontent.com/12817862/52877873-03047a00-313a-11e9-87b2-37be0d21b4ae.png)

4. Now press the ESC key to exit the JEI GUI, wait a couple of seconds for the dialogbox to close, and check the console log:

```
[15:55:03] [Client thread/ERROR] [jei]: Recipe registry plugin crashed: class crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1
java.lang.NullPointerException: null
	at crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1.getWrappers(DarkSteelUpgradeRecipeCategory.java:127) ~[DarkSteelUpgradeRecipeCategory$1.class:?]
	at crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1.getRecipeWrappers(DarkSteelUpgradeRecipeCategory.java:98) ~[DarkSteelUpgradeRecipeCategory$1.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper.lambda$getRecipeWrappers$1(RecipeRegistryPluginSafeWrapper.java:30) ~[RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper.callPluginMethod(RecipeRegistryPluginSafeWrapper.java:42) [RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistryPluginSafeWrapper.getRecipeWrappers(RecipeRegistryPluginSafeWrapper.java:30) [RecipeRegistryPluginSafeWrapper.class:?]
	at mezz.jei.recipes.RecipeRegistry.getRecipeWrappers(RecipeRegistry.java:572) [RecipeRegistry.class:?]
	at mezz.jei.recipes.RecipeRegistry.getRecipeCategories(RecipeRegistry.java:550) [RecipeRegistry.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setFocus(RecipeGuiLogic.java:53) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:392) [RecipesGui.class:?]
	at mezz.jei.input.InputHandler.handleMouseClickedFocus(InputHandler.java:182) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.handleMouseClick(InputHandler.java:130) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.handleMouseEvent(InputHandler.java:99) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.onGuiMouseEvent(InputHandler.java:88) [InputHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2822_InputHandler_onGuiMouseEvent_Pre.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:500) [blk.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.40
- EnderCore:EnderCore-1.12.2-0.5.45
- Minecraft:1.12.2
- Forge:14.23.5.2808
- SpongeForge? no
- Optifine? no
- Single Player

Edit: This is a modified FTBPresentsStoneblock2-1.4.0-1.12.2 instance. Since I have updated some mods and made a few changes to the config, I am not reporting this to the mod pack devs.

#### Mods:

Mods:
  ActuallyAdditions-1.12.2-r145
  ActuallyBaubles-1.12-1.1
  ae2stuff-0.7.0.4-mc1.12.2
  AE2WTLib-1.12.2-1.0.6
  AkashicTome-1.2-12
  angelRingToBauble-1.12-0.3.1.50+d4e654e
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv6-stable-6
  architecturecraft-1.12-3.80
  AttributeFix-1.12.2-1.0.4
  AutoRegLib-1.3-24
  autowalk-1.12.2-1.0
  Avaritia-1.12.2-3.3.0.33-universal
  badwithernocookiereloaded-1.12.2-3.3.16
  base-1.12.2-3.11.0
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  bedpatch-2.2-1.12.2
  BetterBuildersWands-1.12.2-0.13.0.267+dc89c58
  BetterFps-1.4.8
  BetterPlacement-1.0.0-1
  blockcraftery-1.12.2-1.1.0
  bonsaitrees-1.1.2-b144
  Bookshelf-1.12.2-2.3.574
  Botania r1.10-359
  BrandonsCore-1.12.2-2.4.9.195-universal
  buildcraft-all-7.99.21
  BuildingGadgets-2.6.3
  CapabilityProxy-1.12.2-2.1.2
  Ceramics-1.12-1.3.6
  Chameleon-1.12-4.1.3
  ChanceCubes-1.12.2-3.2.3.242
  ChestTransporter-1.12.2-2.8.8
  chickens-6.1.0
  Chisel-MC1.12.2-0.2.1.35
  chiselsandbits-14.30
  ClientTweaks_1.12.2-3.1.11
  Clipboard-1.12-1.3.0
  Clumps-3.1.2
  CodeChickenLib-1.12.2-3.2.2.353-universal
  CoFHCore-1.12.2-4.6.2.25-universal
  CoFHWorld-1.12.2-1.3.0.6-universal
  CommonCapabilities-1.12.2-2.0.2
  compactmachines3-1.12.2-3.0.13-b236
  Controlling-3.0.6
  CookingForBlockheads_1.12.2-6.4.69
  CraftingTweaks_1.12.2-8.1.9
  CraftPresence-1.12.2-1.4.9.9
  CraftTweaker2-1.12-4.1.14
  CTM-MC1.12.2-0.3.3.22
  Cucumber-1.12.2-1.1.3
  CustomMainMenu-MC1.12.2-2.0.9
  cxlibrary-1.12.1-1.6.1
  Cyclic-1.12.2-1.17.16
  CyclopsCore-1.12.2-1.0.3
  DankNull-1.12-1.4.46
  DarkUtils-1.12.2-1.8.223
  DefaultOptions_1.12.2-9.2.8
  diethopper-1.1
  Draconic-Evolution-1.12.2-2.3.20.333-universal
  EnchantmentDescriptions-1.12.2-1.1.13
  EnderCore-1.12.2-0.5.45
  EnderIO-1.12.2-5.0.40
  EnderIO-endergy-1.12.2-5.0.40
  EnderStorage-1.12.2-2.4.5.135-universal
  engineers_doors-1.12.2-0.8.0
  environmentaltech-1.12.2-2.0.19.1
  Exchangers-1.12.2-2.8
  ExCompressum_1.12.2-3.0.26
  exnihilocreatio-1.12.2-0.3.7
  ExpandedEquivalence-1.12.2-11b
  ExtraCells-1.12.2-2.6.3aNIGHTLY
  extrautils2-1.12-1.9.8
  ExtremeReactors-1.12.2-0.4.5.63
  FannyPack-1.1
  FarmingForBlockheads_1.12.2-3.1.26
  FasterLadderClimbing-1.12-0.1-146
  FastFurnace-1.12.2-1.2.1
  FastLeafDecay-v14
  FastWorkbench-1.12.2-1.6.0
  flatcoloredblocks-mc1.12-6.7
  FluidCows-1.1.16
  fluxnetworks-1.12.2-3.0.19-21
  foamfix-0.10.3-1.12.2
  Forgelin-1.8.2
  ForgeMultipart-1.12.2-2.6.1.81-universal
  framland-1.12.2-1.0.7.11
  FTBLib-5.4.1.84
  FTBQuests-1.5.0.130
  FTBUtilities-5.3.0.81
  FullscreenWindowed-1.12-1.6.0
  GasConduits-1.12.2-1.0.0
  gravestone-1.10.2
  HammerCore-1.12.2-2.0.4.2
  hatchery-1.12.2-2.2.0
  iChunUtil-1.12.2-7.1.4
  ImmersiveEngineering-0.12-88
  industrialforegoing-1.12.2-1.12.5-229
  industrialmeat-1.12-1.0.2
  IntegratedDynamics-1.12.2-1.0.4
  IntegratedTunnels-1.12.2-1.6.5
  IntegrationForegoing-1.12.2-1.8.2
  InventoryTweaks-1.64-dev
  IronBackpacks-1.12.2-3.0.8-12
  ironchest-1.12.2-7.0.59.842
  ItemFilters-1.0.1.8
  JEHC-1.12.2-1.6.2.0
  jei_1.12.2-4.14.4.264
  journeymap-1.12.2-5.5.3
  JustEnoughEnergistics-1.12.2-1.0.6
  JustEnoughResources-1.12.2-0.8.10.50
  KleeSlabs_1.12.2-5.4.11
  letsencryptcraft-1.10.2-1.2.0
  llibrary-1.7.17-1.12.2
  LLOverlayReloaded-1.1.6-mc1.12.2
  LootTweaker-1.12.2-0.0.8
  MainMenuScale-1.2
  malisiscore-1.12.2-6.4.0
  malisisdoors-1.12.2-7.3.0
  Mantle-1.12-1.3.3.42
  mcjtylib-1.12-3.1.1
  Mekanism-1.12.2-9.4.13.349
  MekanismGenerators-1.12.2-9.4.13.349
  MekanismTools-1.12.2-9.4.13.349
  MightyEnderChicken-1.12.2-7.2.0
  minetogether-1.10.2-2.1.3
  missing_pieces-1.12.2-4.3.0
  MobGrindingUtils-0.3.13
  modnametooltip_1.12.2-1.10.0
  modtweaker-4.0.16
  morechickens-1.12.2-3.1.0
  MoreFurnaces-1.12.2-1.10.6
  moreoverlays-1.14-mc1.12.2
  Morph-1.12.2-7.1.2
  Morpheus-1.12.2-3.5.106
  Morph-o-Tool-1.2-21
  MouseTweaks-2.10-mc1.12.2
  MPUtils-1.12.2-1.5.6
  MrTJPCore-1.12.2-2.1.3.35-universal
  MTLib-3.0.5
  MysticalAgradditions-1.12.2-1.3.1
  MysticalAgriculture-1.12.2-1.7.1
  mysticallib-1.12.2-1.0.0
  Neat 1.4-17
  NoMobSpawningOnTrees-1.2.2-mc1.12.2
  noRecipeBook_v1.2.2formc1.12.2
  NoTemaStahp-1.12.2-1.0.1
  notenoughwands-1.12-1.7.3
  OpenBlocks-1.12.2-1.8
  OpenModsLib-1.12.2-0.12.1
  oreberries-1.12.x-0.5.0
  OreExcavation-1.4.137
  p455w0rdslib-1.12.2-2.0.36
  packcrashinfo-1.0.1
  Pam's HarvestCraft 1.12.2zb
  petrock-0.3.1
  Placebo-1.12.2-1.5.1
  plustic-7.0.5.0
  ProjectE-1.12.2-PE1.4.0
  ProjectEX-1.0.0.13
  ProjectIntelligence-1.12.2-1.0.2.16-universal
  ProjectRed-1.12.2-4.9.1.92-Base
  ProjectRed-1.12.2-4.9.1.92-compat
  ProjectRed-1.12.2-4.9.1.92-fabrication
  ProjectRed-1.12.2-4.9.1.92-integration
  ProjectRed-1.12.2-4.9.1.92-lighting
  ProjectRed-1.12.2-4.9.1.92-mechanical
  Psi-r1.1-70
  quantumflux-1.12.2-2.0.17
  randompatches-1.12.2-1.13.0.1
  RandomThings-MC1.12.2-4.2.6
  randomtweaks-1.12.2-2.4.3.1
  RealisticItemDrops-1.2.14
  reauth-3.6.0
  RebornCore-1.12.2-3.13.4.419-universal
  RebornStorage-1.12.2-3.3.2.79
  RedstoneArsenal-1.12.2-2.6.2.17-universal
  RedstoneFlux-1.12-2.1.0.6-universal
  refined_avaritia-1.12.2-2.4
  refinedstorage-1.6.12
  refinedstorageaddons-0.4.3
  refinedstoragerequestify-1.12.2-1.0.1-2
  ResourceLoader-MC1.12.1-1.5.3
  rflux-1.12-0.3.2
  rftools-1.12-7.61
  rftoolsctrl-1.12-1.9.3
  rftoolspower-1.12-1.1.2
  roost-1.12-1.3.0
  ServerLevelType-1.2
  ShadowMC-1.12-3.8.0
  SimpleStorageNetwork-1.12.2-1.5.6
  SimplyJetpacks2-1.12.2-2.2.10.63
  simplylight-0.6.0
  SmoothFont-mc1.12.2-2.0-alpha-6
  Snad-1.12.1-1.7.09.16a
  sonarcore-1.12.2-5.0.19-20
  SplashAnimation-0.2.0
  StoneBlockDimensions-1.0.3
  StoneBlockUtilities-2.1.4
  StoneChest-1.0.4
  StorageDrawers-1.12.2-5.3.8
  TConstruct-1.12.2-2.12.0.115
  tesla-core-lib-1.12.2-1.0.15
  Thaumcraft-1.12.2-6.1.BETA26
  ThaumicInventoryScanning_1.12.2-2.0.10
  ThaumicJEI-1.12.2-1.5.5-23
  ThaumicTerminal-1.0.10
  theoneprobe-1.12-1.4.28
  ThermalCultivation-1.12.2-0.3.2.11-universal
  ThermalDynamics-1.12.2-2.5.4.18-universal
  ThermalExpansion-1.12.2-5.5.3.41-universal
  ThermalFoundation-1.12.2-2.6.2.26-universal
  ThermalInnovation-1.12.2-0.3.2.11-universal
  TinkerToolLeveling-1.12.2-1.1.0
  tinyprogressions-1.12.2-3.3.32-Release
  TipTheScales-1.12.2-1.0.3
  tmel-1.12.2-1.3.2.1
  Toast Control-1.12.2-1.8.0
  topaddons-1.12.2-1.10.1
  torchmaster_1.12.2-1.7.1.74
  toughnessbar-2.0
  tramplestopper-1.12.2-1.2.3-universal
  Translocators-1.12.2-2.5.1.77-universal
  TS2K16-1.2.10
  UniDict-1.12.2-2.9.2
  Uppers-0.0.6
  valkyrielib-1.12.2-2.0.19.1
  VanillaFix-1.0.10-99
  voidislandcontrol-1.5.3
  WanionLib-1.12.2-2.2
  WirelessCraftingTerminal-1.12.2-3.11.88
  WR-CBE-1.12.2-2.3.1.30-universal
  xnet-1.12-1.7.6
  Xtones-1.12-1.0.8-11
  YABBA-1.1.2.40
  YNot-0.2.3
  zerocore-1.12-0.1.2.7
  zettaindustries-1.3-1.12.2-161

#### Your most recent log file where the issue was present: 

PART 1 https://paste.ee/p/TsYoe

PART 2 https://paste.ee/p/MOgf8

**Comment by Tanto17** [comment]
Same issue.

**Comment by Dimentive** [comment]
I’m having the same issue (with Ender IO version 5.0.40). I’m getting [this error](https://pastebin.com/raw/0su0UsFy) in the log.

**Comment by Dimentive** [comment]
Thanks for the fix!

**Comment by Xetaxheb** [comment]
Delay doesn't seem fixed, still getting it on 5.0.962  

Got this a few times but no other log message (besides "world can't keep up skipping ticks!"):  
Recipe registry plugin is slow, took 11.02 ms. class crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1

**Comment by HenryLoenwind** [comment]
"world can't keep up skipping ticks!" means that your server thread is running slow, "Recipe registry plugin is slow" means that your client thread is running slow. Unless you have a single-core CPU, those two threads run independently, so this seems to be more an issue of something that affects both causing an issue you only see because that's the only places that do performance measurements.

**Comment by mindforger** [comment]
>so this seems to be more an issue of something that affects both

GC load probably

**Comment by Xetaxheb** [comment]
All I can say is my experience and intuition knows that it is generally the same circumstances that was triggering the delay previously; enderio is definitely still the culprit. I cannot trigger these delays unless enderio is installed, but it happens reasonably commonly with it installed. I'm just not familiar enough with JEI's api to say exactly what the issue is.

My computer(and internal sp server) has zero issues with running mods, my specs are far above and beyond what's necessary since I use this for compiling and rendering and editing. I cap my fps at 65 and rarely drop below that even while flying through new chunks. This issue also happens in void dimensions with minimal building, it's certain to be something to do with enderio since it doesn't happen unless it's installed. It's not GC load, I have enough ram allocated and i've watched the lagometer for GC (brown spikes) when this happens.

It seems like the issue in 5.0.962 is more severe (longer and/or more-chaining-delays) compared to 5.0.40 but doesn't throw that same error, just causes the delay still (and JEI calls it out). The "skipping ticks" is just because enderio is causing a lockup in the client and the server freaks out as a result.. I'm not familiar enough with the client/server segregation to tell you why. I literally never get that error besides this circumstance and genning a new dim for the first time rarely.

**Comment by MatthiasMann** [comment]
While I haven't done any measurements yet - but I now get lots of wrong block updates when breaking blocks really fast (eg sand). Where the client thinks the block is gone but the server (in single player) still has the block and as a result the water doesn't update. This started after updating EIO ~2 days ago.
