### ISSUE TITLE
Item conduits don't connect to Fossils and Archeology mod's machines

### ISSUE THREAD

**Issue by mser7** [SleepyTrousers/EnderIO#5037]
#### Issue Description:

Conduits from Ender IO don't attatch to machines from Fossils and Archeology mod

#### What happens:

They don't connect to any side of the block

#### What you expected to happen:

They should, the machine can be insert and extract with normal hoppers

#### Steps to reproduce:
Put down a conduit next to these types of machine:
Feeder
Analyzer
Sifter
...

____
#### Affected Versions (Do *not* use "latest"):

* EnderIO: EnderIO-1.12.2-5.0.40
* EnderCore:EnderCore-1.12.2-0.5.45
* Minecraft:1.12.2
* Forge:14.23.5.2808
* SpongeForge? no
* Optifine? no
* Single Player

#### Your most recent log file where the issue was present: 

Related issue on Fossil's github
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1161
https://github.com/FossilsArcheologyRevival/FossilsArcheologyRevival/issues/1143

**Comment by tterrag1098** [comment]
EIO no longer supports IInventory. Maybe it should be a clue that conduits work with every mod EXCEPT that one, that it's theirs to fix?

**Comment by HenryLoenwind** [comment]
Ender IO doesn't support the pre-historic and long deprecated I(Sided)Inventory any more. "Fossils and Archeology" should (despite its name) put them to rest and implement IItemHandler like any other modern mod.
