### ISSUE TITLE
[enhancement]  MIMO conduits

### ISSUE THREAD

**Issue by DemonfangArun** [SleepyTrousers/EnderIO#5042]
Ender IO v. 5.0.39

Suggestion: have conduits be able to insert and extract on multiple colors/channels per connector type.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by DemonfangArun** [comment]
-makes a note of that-
