### ISSUE TITLE
Stuck at Phase 2, EnderIO

### ISSUE THREAD

**Issue by Gyunbie** [SleepyTrousers/EnderIO#5043]
#### Issue Description:

Gets stuck at EnderIO.

#### What happens:

When I start Project Ozone 3 (and many other modpacks), it gets stuck at Phase 2, EnderIO. Talked to the developer, we can't seem to find the issue of this.

I need to say what I did for this.
- Updating Java/Forge
- Clean install on Windows 10 (set twitch launcher settings too)
- Tried 5-6-7-8-9-10-11-12GB rams
- Starting the modpack minimized

I got it to work only one time. Yesterday, I did a clean install again and only installed Java u202 and GTX1070 driver. It was working very well. After that, I only rebooted my computer. Nothing installed, nothing touched. Then it got stuck again.

The strange thing is I am typing from Linux right now and it still does this issue. Java u201, Linux Mint with MultiMC and still stuck on there. What is going on?

#### What you expected to happen:

To start the modpack.

#### Steps to reproduce:

1.Starting the modpack(s)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:5.0.40
- EnderCore:5.0.40
- Minecraft:1.12.2
- Forge:14.23.5.2808
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Single player

#### Your most recent log file where the issue was present: 

latest.log - paste.feed-the-beast.com/view/1a9a7ed3
debug.log - paste.feed-the-beast.com/view/cbd4173d

Note here: On debug.log, it says [enderio]: PHASE INIT START, and it never goes past that.

**Comment by HenryLoenwind** [comment]
#5033
