### ISSUE TITLE
EnderIO crashes Minecraft when opening search tab

### ISSUE THREAD

**Issue by Teppynyx** [SleepyTrousers/EnderIO#5044]
Upon installing EnderIO and Endercore for Minecraft, anytime I tried to open the creative search or EnderIO tab it would crash my game. 

#### Steps to reproduce:

1. Install the mods/forge (I got the mods from Curseforge
2. Hit play and load up a creative world
3. Click the search tab or EnderIO tab and see if you get the same crash as me
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.429
- EnderCore: 0.2.0.39
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

#### Your most recent log file where the issue was present: 

https://pastebin.com/r57vr9ib

**Comment by HenryLoenwind** [comment]
This has nothing to do with Ender IO.

What happens here is: Caveworld's MiningPickaxe seems to be something that can upgrade or incorporate other pickaxes. It will then add the original pickaxe's tooltips to its own tooltip. However, there's a bug in that code that tells the other pickaxe to generate tooltips for the MiningPickaxe---which the other pickaxe naturally has no clue about. Many pickaxes just ignore the item they shouild produce tooltips for (assuming it's themselves), but draconic's pickaxe tries to read the amount of RF from the item to display it. But that MiningPickaxe is no draconic pickaxe, and so: booom

**Comment by HenryLoenwind** [comment]
PS: This is the bad code: https://github.com/kegare/Caveworld/blob/master/caveworld/item/ItemMiningPickaxe.java#L687
