### ISSUE TITLE
Abrupt crash trying to place an item conduit

### ISSUE THREAD

**Issue by BrisingrAerowing** [SleepyTrousers/EnderIO#5045]
#### Issue Description:

Crash when placing an item conduit. Crash seems to happen randomly and does not correlate to any specific blocks. Only happens if it can connect to a block.

#### What happens:

Crash

#### What you expected to happen:

The item conduit is placed

#### Steps to reproduce:

1. Place an item conduit next to something it can connect to.
2.?
3.Crash?
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- EnderCore: 0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2811
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 
[Crash Log](https://paste.dimdev.org/poxivowaxe.mccrash)

**Comment by HenryLoenwind** [comment]
Known bug that got lost because it was not reported as an issue before... ;)
