### ISSUE TITLE
No longer able to disable fluid use on Rod of Return (after new config system?)

### ISSUE THREAD

**Issue by ajthemacboy** [SleepyTrousers/EnderIO#5047]
#### Issue Description:

Modpack: Direwolf20 1.12, with EnderIO manually updated to version 5.0.40.

In EnderIO version 5.0.37, I was able to disable the Rod of Return's fluid use in the config by setting `fluidUsePerTeleport` to 0. Now, this doesn't work. I think it might be because the range for this config option [is now (1, 1000)](https://github.com/SleepyTrousers/EnderIO/blob/d54197f922b7b6fc1450fe2586e03567c6608821/enderio-base/src/main/java/crazypants/enderio/base/config/config/ItemConfig.java#L72).

I can still disable the Telepad's fluid use by setting `telepadFluidUse` to 0. This config option [uses `setMin(0)` instead of `setRange(1,1000)`](https://github.com/SleepyTrousers/EnderIO/blob/d54197f922b7b6fc1450fe2586e03567c6608821/enderio-machines/src/main/java/crazypants/enderio/machines/config/config/TelePadConfig.java#L17).

When I have time I will do my best to build the mod and see if `setRange(0,1000)` will fix it.

#### Affected Versions:
- EnderIO: 5.0.40 (and presumably 5.0.39)
- EnderCore: 1.12.2-0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- SpongeForge? no
- Single Player and/or Server? singleplayer

**Comment by HenryLoenwind** [comment]
This needs a proper way to disable fluid use; that setting it to 0 worked was pure luck.
