### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by ghost** [SleepyTrousers/EnderIO#5051]
#### Issue Description:
Acording to people on my server, it is crashing do to this error here: https://gist.github.com/Modpack-Support/33fd04a2630177e17a969c13fab8d916

#### What happens:
Not sure as I was not around at time of said crash

#### What you expected to happen:
A reason to why this is happening 

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.12.2-5.0.40
- EnderCore: 1.12.2-0.4.45
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2815-universal
- SpongeForge? yes/no no
- Optifine? yes/no no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Try without these:

```
LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
```

Those are candidates that may mess with java.util.ArrayList

**Comment by Leo40Git** [comment]
Neither should mess with ArrayList, to my knowledge.

By the way, @ghost, there's no reason to use Less Lag if you have VanillaFix installed, since the latter disables animations when they're not on-screen.

**Comment by HenryLoenwind** [comment]
Anyway, now that the crash log is gone, I cannot do anything. I don't even remember where it was crashing...
