### ISSUE TITLE
Advanced item filter still bugged in Refined Storage conduits

### ISSUE THREAD

**Issue by calloatti** [SleepyTrousers/EnderIO#5053]
#### Issue Description:

When using an advanced item filter in a Refined Storage conduit, the "Ignore NBT", "Ignore Metadata" and "Ignore Damage" flags are not used. Only the exact item set in the filter gets exported.

#### What happens:

The Advanced Item Filter does not work properly.

#### What you expected to happen:

The Advanced Item Filter to work properly.

#### Steps to reproduce:

Refined Storage test setup:

![image](https://user-images.githubusercontent.com/12817862/53513277-8f505e80-3aa3-11e9-954b-942a412645ab.png)

![image](https://user-images.githubusercontent.com/12817862/53513297-98d9c680-3aa3-11e9-82e6-6fe4decdab26.png)

![image](https://user-images.githubusercontent.com/12817862/53513320-a2632e80-3aa3-11e9-8eb2-3039b02274ea.png)

![image](https://user-images.githubusercontent.com/12817862/53513337-ae4ef080-3aa3-11e9-81a8-53d2741a1669.png)

RESULT:

![image](https://user-images.githubusercontent.com/12817862/53513350-b7d85880-3aa3-11e9-9d44-9fcc6d7aca95.png)

Chests and Item Conduits with the exact same filter and the exact same items:

![image](https://user-images.githubusercontent.com/12817862/53513383-cde61900-3aa3-11e9-9db8-222a55f45993.png)

![image](https://user-images.githubusercontent.com/12817862/53513390-d3436380-3aa3-11e9-9cf2-d5597093d9b8.png)

![image](https://user-images.githubusercontent.com/12817862/53513398-d9d1db00-3aa3-11e9-8cfd-df602dc12206.png)

![image](https://user-images.githubusercontent.com/12817862/53513407-ddfdf880-3aa3-11e9-9722-8ead32c8ae3e.png)

RESULT:

![image](https://user-images.githubusercontent.com/12817862/53513414-e35b4300-3aa3-11e9-98b7-113912b1ed71.png)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.40
- EnderCore: EnderCore-1.12.2-0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? : Single Player

Java: Eclipse OpenJ9 VM, version 1.8.0_202, running on Windows 10:amd64:10.0

#### Your most recent log file where the issue was present: 

https://pastebin.pl/view/8da4f348

**Comment by HenryLoenwind** [comment]
RS still doesn't support those.

**Comment by calloatti** [comment]
If I use a Refined Storage Exporter instead of an Ender IO RS conduit/filter, the Refined Storage exporter can ignore NBT data and ignore damage, so I think Refined Storage does support those.

![image](https://user-images.githubusercontent.com/12817862/53514572-c5dba880-3aa6-11e9-8a1d-98aa6a3a26c1.png)

![image](https://user-images.githubusercontent.com/12817862/53514590-ce33e380-3aa6-11e9-907b-fd44309c53c6.png)

The thing is having to use a Refined Storage Exporter at the end of an Ender IO RS conduit line kind of defeats the purpose of having RS conduits in the first place...

This works fine, but it looks ugly and cannot be covered with a facade:

![image](https://user-images.githubusercontent.com/12817862/53514747-279c1280-3aa7-11e9-9e8f-cd62a1a7d18b.png)

**Comment by calloatti** [comment]
Related:

https://github.com/SleepyTrousers/EnderIO/issues/4904

https://github.com/SleepyTrousers/EnderIO/issues/4887

This has not been fixed despite what EpicSquid says here: https://github.com/SleepyTrousers/EnderIO/issues/4887#issuecomment-426650022

**Comment by HenryLoenwind** [comment]
@EpicSquid your code, I can only relay potentially outdated infos

**Comment by calloatti** [comment]
Maybe reopen? Thank you for taking the time to review this. Any other testing needed/required I am available to help, as I have done in the past.

**Comment by calloatti** [comment]
The implementation of filters in RS conduits needs a major overhaul in my humble opinion.

https://github.com/SleepyTrousers/EnderIO/issues/5053

**Comment by HenryLoenwind** [comment]
Oops, I thought I re-opened it when I assigned Epic...

**Comment by HenryLoenwind** [comment]
Please not that export filtering is severely limited by RS's filtering capabilities. It will not export a *wrong* item, but it may get stuck when RS *wants* to export a wrong item and our filter stops it. As long as RS doesn't decide to export another item, nothing will happen.
