### ISSUE TITLE
Dimensional Transceiver GUI is transparent to mouse clicks

### ISSUE THREAD

**Issue by FlyingThunder** [SleepyTrousers/EnderIO#5055]
#### Issue Description:

When you open the side configuration on the D.T. and you try to "click the background" to rotate the model, your click goes right through to the inventory so you select items while scrolling around.

#### What happens:

![image](https://user-images.githubusercontent.com/39583733/53662116-675b2980-3c62-11e9-815a-4e0dc937c8a2.png)

#### What you expected to happen:

Clicks are blocked

#### Steps to reproduce:

1. open D.T. GUI
2. select "configure IO"
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.919 (it did also happen on 5.0.40)
- EnderCore: 0.5.48
- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

https://www.dropbox.com/s/xcm1cbe7sn64kpm/latest%20-%20Kopie.zip?dl=0

**Comment by HenryLoenwind** [comment]
This probably only happen in an area on the right side that's as wide as the extra margin to the left of the overview, does it?

**Comment by FlyingThunder** [comment]
Yep, only affects the 2 rightmost columns

**Comment by HenryLoenwind** [comment]
Ok, then it's the same issue we had in another GUI. Somehow moving the overlay area doesn't automatically move its click area...

**Comment by tyler489** [comment]
Confirmed Still an issue in v.46
