### ISSUE TITLE
Ender IO lower level conduits not limiting higher level conduits' power flow

### ISSUE THREAD

**Issue by flyingperson23** [SleepyTrousers/EnderIO#5056]
#### Issue Description:

Energy conduits not limiting power flow under certain circumstances

#### What happens:

When for example an ender energy conduit with a max energy flow of 20,480 uI/t is connected on either end of an energy conduit line with normal or enhanced energy conduits connected in between, the lower level conduits don't limit the power flow

#### What you expected to happen:

I expected the conduits in between to limit the power flow so that when running long conduit lines one does not need to use high-level energy conduits anywhere except the end-points

#### Steps to reproduce:

1. Edit setting in config to allow different tiers of energy conduits to connect
2. Place two creative capacitor banks with at least 3 block spaces in between
3. Connect ender energy conduits to each creative capacitor bank
4. Set one of the ender energy conduits to insert only and one to extract only
5. connect the two ender energy conduits with normal or enhanced energy conduits
6. The flow of power through the conduits will not be limited by the lower level conduits

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- EnderCore: 0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- SpongeForge? no
- Optifine? no
- Single Player

____

![2019-03-01_20 00 13](https://user-images.githubusercontent.com/48142902/53675655-252fe900-3c5e-11e9-983d-b6d6f71fd14c.png)

**Comment by MatthiasMann** [comment]
That's exactly the reason why this config option is set to disallow different tiers of conduits to connect. Only the end points / connectors decide how much energy can be tranferred.

**Comment by HenryLoenwind** [comment]
as Matthias said
