### ISSUE TITLE
Endergy Totemic Capacitor recipe unbalanced... [Can't applied Efficiency Enchant]

### ISSUE THREAD

**Issue by Fireztonez** [SleepyTrousers/EnderIO#5057]
#### Issue Description:
I have installed EnderIO and the Endergy Addon, and when I look the recipes and try each new capacitor, the Totemic one (how sincerly is probably one of the most difficult one to make) as just zero benifit over the Crystaline one (how is used into the recipe...). I compare the speed of the machine, the power consumption and the total amount of power capacity, everithing is same... This look totally illogical and unbalanced...

For sure, I can change the recipe my self (And I will probably do for my modpack), but, I think you should look to change somes things about that ;)

#### Steps to reproduce:

1.Install EnderIO + Endergy
2.Test!!
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- Endergy: 5.0.40
- EnderCore: 0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2806
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single Player, but for sure on server it will be the same!

#### Your most recent log file where the issue was present: I don't think you need logs, because this is not a bug, but possibly an Unexpected Feature!!

Fireztonez

**Comment by tyler489** [comment]
if you enchant it with efficiency it gets better. ALOT better

**Comment by Fireztonez** [comment]
I just try with differents enchants, but I can't find any enchant how boost the efficiency... For what I see now, the only big difference is the fack the Totemic Capacitor have durability, and the Crystaline one is unbreakable... So yeah, again, for me this is one look completly useless for the cost... For what I see, using an Octadic Capacitor in the recipe will be really more balanced than using the Crystaline one...

If you know whta enchant I can apply to make it more Efficient, I really whant to know!!

![enchants_totemic_capacitor](https://user-images.githubusercontent.com/19277301/53692216-06168180-3d5a-11e9-8f1d-f95a472dbdfb.png)

**Comment by Fireztonez** [comment]
Ok, sorry, I just saw that I had misread your answer @tyler489, so, indeed, to have tested with the enchante Effectiveness 5, it is rather Crazy !! But, I find myself with the problem that the capacitor can not receive the enchanted Efficiency in survival mode in my ModPack. But I just live on a clean instance it works, so the problem is on my side, I'll have to analyze which mod creates the problem.

Thank's for your help!

**Comment by Fireztonez** [comment]
My Bad, I just try again, and this is just impossible to apply Efficiency Enchant with an anvil on Totemic Capacitor in survival. So This look like a bug in your end...

<details><summary>Mods installed in the Dev Pack</summary><p>

> **Mods:**
>   CodeChickenLib-1.12.2-3.2.2.353-universal
>   CraftTweaker2-1.12-4.1.14
>   Cucumber-1.12.2-1.1.3
>   EnderCore-1.12.2-0.5.45
>   EnderIO-1.12.2-5.0.40
>   EnderIO-endergy-1.12.2-5.0.40
>   EnderTweaker-1.12.2-1.1.4
>   ExtendedCrafting-1.12.2-1.5.2
>   jei_1.12.2-4.14.4.267
>   mpbasic-1.12.2-1.4.5
>   MPUtils-1.12.2-1.5.4
</p></details>

So this test modpack is really clean, so, I don't thinkthis is a conflict with other mod...

Thank's
Fireztonez

**Comment by tyler489** [comment]
```public boolean canApplyAtEnchantingTable(@Nonnull ItemStack stack, @Nonnull Enchantment enchantment) {
    if (enchantment.getName().equals("efficiency")) {
      return true;```

**Comment by Fireztonez** [comment]
I cannot enchant the Capacitor in the Enchanting Table...

![totemic_capacitor_enchanting_table](https://user-images.githubusercontent.com/19277301/53703147-8da4d480-3ddc-11e9-9d10-afdf201277e5.png)

**Comment by HenryLoenwind** [comment]
Sorry I actually had a reply written but I didn't click the "comment" button to sand it for some reason.

Can you test that with just Ender IO? It works for us, but I want to rule out that there's something weird going on before I start blaming other mods...

**Comment by Fireztonez** [comment]
Like I said, I have try with only EnderIO somes small other tweak mods, but, the only mods real mod adding thing in that pack is Extended Crafting... You can see the list of mod installed into the small test pack...

But I have try to remove the 3 or 4 mods I have added, so, whit the smallest pack possible, with only EnderIO, JEI, Endergy and EnderCore, still doesn't work... I have no crafttweaker, nothing in that pack now, so, if this is still in my end, this is caused by forge or Java directly, but this really really look with a bug on your end...

![totemic_capacitor_only_enderio](https://user-images.githubusercontent.com/19277301/53704128-a36bc700-3de7-11e9-99f8-40b18c2110e1.png)

**Comment by tyler489** [comment]
Are you using the single jar of enderio and energy or the split jars?

**Comment by Fireztonez** [comment]
I use the complete EnderIO jar + the EnderIO Endergy jar in Curse Forge (So a total of 2 jar for that, plus the EnderCore Mod...)

**Comment by RonRicoSuave** [comment]
I also can't enchant it with efficiency...  I thought it might have been the quark matrix enchanting being screwy since that's still a beta feature, but it doesn't show up in JEI and the /enchant command with a non-enchanted totemic cap in hand doesn't work either, saying it can't be added to the item.  According to /ct enchants the efficiency enchant hasn't had an ID change... 

-<enchantment:minecraft:efficiency> - Efficiency I (at level 1, max level 5, treasure: no, enchant id 32)

Aside from the quark-modified vanilla table which works with everything else, tried the vanilla anvil which doesn't allow enchanting with any level of efficiency book,  the cyclic enchanter which doesn't do anything to it at all including allowed enchantments, and attempted to throw it on the botania mana enchanter but that won't accept it for whatever reason.  

Adding it manually via /give with the NBT data worked and retained the enchantment when combined with another on the anvil but that was the only way I could get it there.

**Comment by Fireztonez** [comment]
Other thing I saw, I don't know if this is intended or not, but Efficiency 5 clearly give a big Efficiency Boost, but, Efficiency 1 doesn't have any effect, I have don't try every level, but that what I saw after couples tests...

**Comment by RonRicoSuave** [comment]
> 
> 
> Other thing I saw, I don't know if this is intended or not, but Efficiency 5 clearly give a big Efficiency Boost, but, Efficiency 1 doesn't have any effect, I have don't try every level, but that what I saw after couples tests...

That looks like a bug to me... 

https://github.com/SleepyTrousers/EnderIO/blob/12df4e5aa3278ed0cac8f56a58f262e0726ec52b/enderio-endergy/src/main/java/crazypants/enderio/endergy/capacitor/ItemTotemicCapacitor.java#L74

Integer division by 2 of the enchantment level means level 1 does nothing, l2-3 add 1, and l4-5 add 2, so there doesn't seem to be a point to applying L1 (or L5 over L4) at the moment.   There should probably be a float cast in there so it scales evenly.

**Comment by tyler489** [comment]
@EpicSquid

**Comment by Fireztonez** [comment]
I rename the issue question of making the title more clear about what is exactly the issue. I hope this is fine for you...

**Comment by Fireztonez** [comment]
So, any news about that issue?
Do you have time to look in the code why this is not possible to enchant with Efficiency at all in survival and why Efficiency 1 doesn't give any bonus?

**Comment by Fireztonez** [comment]
The issue is still existing and is exacly the same with the new update:
Endergy: 5.0.43
Ender IO: 5.0.43
Ender Core: 0.5.52

Still impossible to enchant with efficiency the Totemic Capacitor and the Efficiency 1 still doesn't have any effect... Do you have look about that issue or not have time yet to look about that?

**Comment by Fireztonez** [comment]
@EpicSquid @HenryLoenwind @tyler489 
I want to know if you think you will be able to fix that issue one day, because, this have been open for more than 2 mouths, 4 EnderIO update later, and the ther ehave absolutly no advancements and no news about that. Without having that issue fixed, there have absolutly no poin ts to craft a Totemic Capacitor,  because you can't enchant with Efficiency at all, so, this is basically a downgrade for the Crystalline Capacitor...

I know this is not the only thing you have to do, and I can understand, but I just want to have somes news about that..

Thank's

**Comment by EpicSquid** [comment]
I still cannot replicate the issue in any tests I have used. Enchanting it with an efficient book in an anvil still works for me. I will take another look again soon, but it's still surprising me this issue has persisted

**Comment by Fireztonez** [comment]
@EpicSquid Have you try to enchant in survival, because in creative every enchant can be apply on anything with the anvil... I just try again, in a new instance with only EnderIO, Endergy, EnderCore and Just Enough Items and it still doesn't work.

For sure, I can enchant in creative mode, but, for sure, you have to be able to enchant with Efficiency in survival.

For now, in my modpack I have add custom crafting table recipe for the enchant with an Enchanted Book, the capacitor + somes XP level, question to be able to obtain the capacitor with the Efficiency Enchant...

If you are still not able to reproduce, I really wonder if the issue is not caused by something more specific with my machine... If it can help, I run the modpack on Windows 10, with Java 1.8.0.201... I install the mod with the Twitch App, but run by Multi-MC or directly by the Twitch app... 

Version:
forge-14.23.5.2838
EnderCore 0.5.57
EnderIO 5.0.44
EnderIO Endergy 5.0.44

Fireztonez

**Comment by Tfarcenim** [comment]
This is an Ender IO bug, nothing to do with mods.
