### ISSUE TITLE
Minecraft modpack crash.

### ISSUE THREAD

**Issue by lllooolll20** [SleepyTrousers/EnderIO#5061]
#### Issue Description:

I threw together some mods, for a multiplayer server me and my friends wanted to play on.
I got through most issues but now im stuck at this crash:
Thanks.
#### Affected Versions:

- SpongeForge? ???I guess not?
- Optifine? no.
- Want to play on Server.

#### Your most recent log file where the issue was present: 

[crash-2019-03-10_03.09.02-client.txt](https://github.com/SleepyTrousers/EnderIO/files/2949021/crash-2019-03-10_03.09.02-client.txt)

**Comment by tyler489** [comment]
soul shards reborn and chocolate quest are trying to add an enchantment to the same id id 52. try to configure them or remove one or the other.

**Comment by HenryLoenwind** [comment]
Nothing to do with Ender IO.

**Comment by lllooolll20** [comment]
Thanks, my bad for bringing it up in EnderIO
