### ISSUE TITLE
Incompatibility with conduit covers and botany ceramic tiles

### ISSUE THREAD

**Issue by RonRicoSuave** [SleepyTrousers/EnderIO#5062]
#### Issue Description:

The mod doesn't exclude the botany tiles from being crafted, but something about them causes a render error (red & white checkered tiles render as a solid pale green for example) and client thread error as follows.  This doesn't crash the game but repeats quite a bit and slows it down: 

> [02:45:09] [Client thread/ERROR] [minecraft/NetHandlerPlayClient]: Received invalid update packet for null tile entity at BlockPos{x=221, y=67, z=158} with data: {conduits:{size:0},forceClientRerender:1b,paintSource:{"enderio:paint":{Name:"botany:ceramicpattern"}},facadeType:0}

One mod or the other should probably remove these tiles from the machine recipes if they can't be made to work with it easily, but it may not be an enderio issue. 

#### What happens:

Tiles render incorrectly as flat aqua color.  Block indicates it was painted with "blank ceramic block" rather than the "full chequered ceramic block" that was actually used.   In-hand, the conduit covers show a plain white but retain the meta: integer tag botany uses to define the material.   After being placed and picked up again they lose their NBT data.  

#### What you expected to happen:

Tiles render correctly or are excluded from crafting in painter. 

#### Steps to reproduce:

1.  Craft a ceramic pattern in the tileworker
2.  Paint a conduit cover with it
3.  Apply to something in world

____
#### Affected Versions

- EnderIO:  5.0.40
- EnderCore:  1.12.2-0.5.45
- Minecraft:  1.12.2
- Forge:  8.0.99.99
- SpongeForge? no
- Optifine? no
- Single Player, local server.

-Binnie's Botany:  2.5.1.188

#### Your most recent log file where the issue was present: 

Error:  Too large to upload over crap 1996-quality DSL, sorry.  :P

**Comment by mindforger** [comment]
you can paste a bunch of lines from your log on pastebin and link the apste then here, just as a heads up :)

**Comment by tyler489** [comment]
all enderio is ask botany how to display there blocks if they are rendering wrong thats on botany
