### ISSUE TITLE
[Suggestion] Allow us to convert loot capacitors into stackable versions that take a slight performance hit

### ISSUE THREAD

**Issue by SadChimera** [SleepyTrousers/EnderIO#5063]
Most of these capacitors don't even work in an Anti-barrel and it gets dangerous to have too much NBT data stored in one area. Keeping all of the loot capacitors that came out of my mob farm/lootbags corrupted a chunk of mine. I'd like to put them through a crafter or something that can strip the NBT data and stack them without losing all of the benefits entirely.

**Comment by tyler489** [comment]
But the nbt data is how they are useable in machines. If you remove that they will be no longer usable in machines.

**Comment by SadChimera** [comment]
Could we make a machine that eats loot capacitors and spits out weaker generics? This would be a better solution than trashing all loot capacitors which is currently the only thing I can do to prevent chunk corruption from storing massive amounts of them.

**Comment by MatthiasMann** [comment]
You could make a shapeless recipe using CraftTweaker and then use the EIO Crafter or another auto crafting system.

**Comment by EpicSquid** [comment]
Yeah that's the best option. They really shouldn't be able to cause chunk corruption by themselves, unless you are storing thousands of them. It doesn't really make sense to add a mechanic to make them more generic since really, you can jue take a regular capacitor then.
