### ISSUE TITLE
logWood to sticks recipes add 1 recipe for each type of stickWood

### ISSUE THREAD

**Issue by Fireztonez** [SleepyTrousers/EnderIO#5064]
Hello,
I just see in JEI, the recipe from EnderIO to make 16 sticks with 2 logWood add 1 recipe for each type of stickWood in the game... this is really messy and add like 5 pages of Sticks recipes if you have mod like Natura adding 1 type of stick for each type of wood... I think you should cahnge the recipe for using only the first one on the oreDict or using simply the minecraft:stick like output...

Here what is look like in JEI right now (and this is a really small pack just to make sure the problem is not caused by other mod...):
![enderio_sticks_recipe_bug](https://user-images.githubusercontent.com/19277301/54237493-7e184080-44ec-11e9-8148-b2cae62f9b48.png)

So, heres the list of mods I have in the pack right-now:
```
  AutoRegLib-1.3-26
  CraftTweaker2-1.12-4.1.15
  EnderCore-1.12.2-0.5.45
  EnderIO-1.12.2-5.0.40
  Hwyla-1.8.26-B41_1.12.2
  jei_1.12.2-4.15.0.268
  Mantle-1.12-1.3.3.42
  natura-1.12.2-4.3.2.66
  Quark-r1.5-146```

Version:
Forge: v14.23.5.2806
EnderIO: 5.0.40
EnderCore: 0.5.45
JEI: 4.15.0.268

**Comment by HenryLoenwind** [comment]
Those are phantom recipes that only exist in JEI. We add them because people complain that they cannot find a recipe to craft their stuff if it's oredicted.

Try hitting "r" on a recipe ingredient in JEI that is cycling stickWood when it shows the exact type of sticks that is the first one in the oredict list.

**Comment by Fireztonez** [comment]
Ok I see...
But now this is anoying when you press "u" on JEI... I think this is just impossible to make everyone happy...

And there not a way to make the output toggling like the input, questions to have only one recipe show... I think I have see that multiple time for crafting table recipes but not sure witch mod use that...

Like that is easy to find with "r" and it doesn't take 3 or 4 pages when pressing "u"

**Comment by tyler489** [comment]
> Ok I see...
> But now this is anoying when you press "u" on JEI... I think this is just impossible to make everyone happy...
> 
> And there not a way to make the output toggling like the input, questions to have only one recipe show... I think I have see that multiple time for crafting table recipes but not sure witch mod use that...
> 
> Like that is easy to find with "r" and it doesn't take 3 or 4 pages when pressing "u"

Yep. So if you don't like it change it in user recipes

**Comment by HenryLoenwind** [comment]
Recipes with output lists are possible in JEI---but *crafting recipes* are an existing recipe type that doesn't support that.

To go a little bit into detail here: JEI keeps a list of "recipes" and a list of "objects that can get data from recipes for JEI". For crafting recipes the first list contains all vanilla crafting recipes (those don't support output lists) and the second one has a simple object that knows how to read those.

**Comment by Fireztonez** [comment]
ok I see...
Thank's for your reply.

So I think I can close that issue then...
