### ISSUE TITLE
Crash with Pixelmon trying to spawn in Pokemon [1.12.2]

### ISSUE THREAD

**Issue by zackeezy** [SleepyTrousers/EnderIO#5065]
#### Issue Description:

Pixelmon's Pokemon crash my game when attempted to be spawned using the powered spawner.

#### What happens:

I captured a Rattata in a soul vial, and combined it with a broken spawner to make a broken pixelmon spawner.  I then combined it with a powered spawner to make a powered Pixelmon spawner.  When I placed the spawner, it crashed my game.

#### What you expected to happen:

I'm not sure what I expected.  I tried this with a vanilla spawner and it didn't work, and when I tried to craft a stabilized spawner from Draconic Evolution, that also crashed my game.  I figured I'd test with Ender IO's powered spawner and it also crashed my game, but this time when placed.  

#### Steps to reproduce:

1. Capture pokemon in vial
2. Craft broken pixelmon spawner
3. combine broken pixelmon spawner with powered spawner
4. try to place powered spawner
5. crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- EnderCore: 0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2814
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

https://pastebin.com/WF9kny9H

**Comment by tyler489** [comment]
@HenryLoenwind other one that needs Specific NBT data (like chickens)

**Comment by MatthiasMann** [comment]
Well - then it's best to black list it in the spawner config.

**Comment by tyler489** [comment]
yeah after looking into it probably best...... 
Wild ratatta 
have over 15k characters in nbt

**Comment by HenryLoenwind** [comment]
So pixelmon crash when used in spawners of all mods you tried? So why do you think all mods are buggy and pixelmon is fine?

**Comment by zackeezy** [comment]
I don't think all mods are wrong, but Pixelmon blames everyone else.

**Comment by zackeezy** [comment]
Plus it seems like there is data not being stored.  You guys mentioned NBT, but I guess it's more an issue with how Pixelmon stores their pokemon.  And it is Reforged for whoever asked.

**Comment by HenryLoenwind** [comment]
Mobs should not crash the game when they are rendered as part of a spawner. Simple as that. Let's not talk about how they store their data or stuff until they actually stop crashing the game, ok?

**Comment by tyler489** [comment]
From what i understand Pixelmon controls there entity model by the name of the entity stored in nbt. By not providing a name the entity is null and has no model. Again this is just from what I understand I could be wrong

**Comment by zackeezy** [comment]
Yea try telling that to them.  I have brought up these crashes three times and they refuse to do anything about it.  They keep blaming the other mods.  Their best response was "you're not supposed to spawn Pokemon that way" okay so it should crash my game? I guess they should just be added to some blacklist or something.

**Comment by Renari** [comment]
I tried disabling pixelmon entities in soul vials or the spawner but this doesn't seem to work.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<enderio:recipes xmlns:enderio="http://enderio.com/recipes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enderio.com/recipes recipes.xsd ">
  <recipe name="Spawner, Pixelmon" required="false">
    <spawning>
      <entity name="pixelmon:*" costMultiplier="1.0" disabled="true" soulvial="false"/>
    </spawning>
  </recipe>
</enderio:recipes>
```

**Comment by tyler489** [comment]
Yes I also tried that and couldn't get it to work.

**Comment by Renari** [comment]
I got it working:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<enderio:recipes xmlns:enderio="http://enderio.com/recipes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enderio.com/recipes recipes.xsd ">
  <recipe name="Spawner, Pixelmon" required="false">
    <spawning>
      <entity name="pixelmon:pixelmon" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:npc_chatting" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:npc_relearner" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:npc_tutor" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:npc_nursejoy" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:npc_shopkeeper" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:breeding" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:npc_trainer" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:npc_trader" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:pixelmon" costMultiplier="1.0" disabled="true" soulvial="false"/>
      <entity name="pixelmon:statue" costMultiplier="1.0" disabled="true" soulvial="false"/>
    </spawning>
  </recipe>
</enderio:recipes>```
Was trying to disable some other mobs and found out wildcards don't work.

**Comment by tyler489** [comment]
Cool if I steal That and add That to default blacklist @renari ?

**Comment by Renari** [comment]
Sure
