### ISSUE TITLE
How are Energy Conduits handling Power loss?

### ISSUE THREAD

**Issue by Hexxonite** [SleepyTrousers/EnderIO#5068]
#### Issue Description:

I am playing with this mod in Enigmatica 2, however my question isnt directly related to the modpack but this mod.

#### What happens:

I was using the Energy Conduits for a while now and everything was great, however recently I have expanded my power network and now I seem to be loosing power even though the attached devices are inactive / disconnected from the conduits.
My guess now is, this happening due to energy loss  in the conduits due to their length or amount of attached devices. Can you confirm this behaviour?

#### What you expected to happen:

Ive searched for a while but couldnt find any information on ir or how this mod handles power loss in the conduits and at which rate.

#### Steps to reproduce:

1.  Have charged Power Source (Mekanism Advanced Energy Cube in my case)
2.  Place 20 "Energy Conduit" cables, 13 devices attached & disabled
3.  The Power Source is still using up power

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- EnderCore: 1.12.2-0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2781
- SpongeForge? no
- Optifine? no
- Server

#### Your most recent log file where the issue was present: 

Im not sure if you would need the client or server log, I'd be glad to provide it if it helps.

**Comment by tterrag1098** [comment]
Conduits have a buffer equal to their transfer rate. Are you sure it's not just this filling up?

**Comment by Hexxonite** [comment]
Well, I didnt know there was such a buffer - good to know.
Seems like this was the cause.
