### ISSUE TITLE
Enderman Evolution soul vials not added to creative tab.

### ISSUE THREAD

**Issue by Renari** [SleepyTrousers/EnderIO#5069]
#### Issue Description:
Enderman evolution soul vials do not show up in the soul vials creative tab.

#### What happens:
Soul vials are missing, for this mod but show for others.

#### What you expected to happen:
Soul vials to be in the soul vials creative tab.

#### Steps to reproduce:

1. Install enderio and enderman evolution.
2. Go to the soul vials creative tab.
3. These soul vials are missing.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.4
- EnderCore: 1.12.2-0.5.45
- Minecraft: 1.12.2
- Forge: 8.0.99.99
- Enderman Evolution:  1.12.2-1.0.16
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single

https://github.com/p455w0rd/EndermanEvolution/issues/32

**Comment by HenryLoenwind** [comment]
Are those declaring themselves as bosses?

**Comment by Renari** [comment]
Does not appear that way, they extend EntityEnderman.
https://github.com/p455w0rd/EndermanEvolution/blob/master/src/main/java/p455w0rd/endermanevo/entity/EntityEvolvedEnderman.java

**Comment by p455w0rd** [comment]
it functions fine?
![image](https://puu.sh/DbH3n/3d1684f462.png)

**Comment by Renari** [comment]
I was able to find this looking through a second time.
```
for soul in <enderio:item_soul_vial>.definition.getSubItems(<creativetab:enderio.mobs>) {
  if (soul.hasTag) {
    JEI.hide(soul);
  }
}
```
Apparently this hides all soul vials except 10 or so, I was under the assumption they were not being added to the creative tab. It seem they are so I'm not sure why they are not being hidden.
