### ISSUE TITLE
error with bungeecord servers

### ISSUE THREAD

**Issue by Nbgreen** [SleepyTrousers/EnderIO#5070]
#### Issue Description:
I'm currently trying to set up a hub server with bungeecord that will go to my main server with enderio on it but you cant connect to the hub server because of the error erderio gives off when its not on the hub server can you remove or add a config to disable the enderio custom NetworkCheckHandlers? full list of the error is pasted here (https://paste.dimdev.org/udatitiboy.shell)

#### What happens:
can not connect because of this error https://paste.dimdev.org/udatitiboy.shell

#### What you expected to happen:
to connect without an issue you shouldn't have to have the mod on the server to connect to it 

#### Steps to reproduce:

1.install forge with ender io
2.connet to any server that doesn't have enderio on it

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.39
- EnderCore: EnderCore-1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2768
- SpongeForge? yes
- Optifine? no
- Single Player and/or Server? server

#### Your most recent log file where the issue was present: 
https://paste.dimdev.org/udatitiboy.shell

**Comment by tyler489** [comment]
#4861 #4974 #4975

**Comment by Nbgreen** [comment]
Since you refuse to fix this issue I’ve had to remove the mod from my modpack Lapito’s Galaticraft. The pack is on page 2 of technic, page 1 of twitch, and rank 16 on the AT launcher. I hope that you fix this issue one day so we can add the mod back to the modpack till then it will not be in the pack.
