### ISSUE TITLE
1.7.10 crash during initialization

### ISSUE THREAD

**Issue by Goldenschmidt** [SleepyTrousers/EnderIO#5071]
#### Issue Description:

Minecraft 1.7.10 crashes, just as it's at its last stage of initializing the mods that have been installed.
I don't have any other mods installed, but Ender IO, and EnderCore.

#### What happens:

The game crashes during last initialization in launch.

#### What you expected to happen:

The game starts, and you're greeted with the Main Menu.

#### Steps to reproduce:

1. Install EnderIO-1.7.10-2.3.0.429_beta.jar and EnderCore-1.7.10-0.2.0.39_beta.jar .minecraft\mods
2. Launch Minecraft
3. *Crash*

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta.jar 
- EnderCore:EnderCore-1.7.10-0.2.0.39_beta.jar
- Minecraft: 1.7.10
- Forge: 1.7.10-Forge10.13.4.1558

#### Your most recent log file where the issue was present: 

Embedded.
[crash-2019-03-19_11.14.49-client.txt](https://github.com/SleepyTrousers/EnderIO/files/2982823/crash-2019-03-19_11.14.49-client.txt)

If Embedded doesn't work, then a link has been provided here:
https://pastebin.com/e5g52jCd

**Comment by HenryLoenwind** [comment]
Don't use 1.9 (or later) config files with 1.7.
