### ISSUE TITLE
Crash in 1.12.2 after adding EnderIO

### ISSUE THREAD

**Issue by hxck** [SleepyTrousers/EnderIO#5072]
#### Issue Description:

Adding EnderIO to an existing custom pack causes the server to stop.

#### What happens:

Description: Exception in server tick loop.

Server fails to start and outputs a crash log. I have a custom pack that was working fine before I added it, so I'm guessing it might be a collision of some kind. Mod list included at the bottom.

#### What you expected to happen:

For the server to start normally.

#### Steps to reproduce:

1. Add EnderIO and EnderCore
2. Start server
3. Server crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- EnderCore: 0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

Crash log: [Paste2](https://paste2.org/mWBf0IAB)

Modlist: [Paste2](https://paste2.org/mgJWeXEg)

**Comment by tyler489** [comment]
Try deleating your config file

**Comment by hxck** [comment]
> Try deleating your config file

Which one? The server doesn't load enough to create a config file for EnderIO.

**Comment by tterrag1098** [comment]
Can you provide the full start up log? It seems that AutoConfig is missing (a shaded dependency), which means forge isn't extracting it properly. My suspicion would be a file permissions issue. Do you see the `memory_repo` folder anywhere?

**Comment by hxck** [comment]
> Can you provide the full start up log? It seems that AutoConfig is missing (a shaded dependency), which means forge isn't extracting it properly. My suspicion would be a file permissions issue. Do you see the `memory_repo` folder anywhere?

Ah okay, I see it now. I wasn't really sure what to look for at first but you're right. Thanks for the info.

`[08:06:13] [main/ERROR] [FML]: An error occurred extracting dependency
java.io.IOException: Unable to create parent directories of ./mods/memory_repo/info/loenwind/autosave/AutoSave/1.12.2-1.0.9/AutoSave-1.12.2-1.0.9.jar`

**Comment by HenryLoenwind** [comment]
In my opinion, that error not stopping the startup is a bug in Forge...
