### ISSUE TITLE
Ender Pickaxe with Direct and Erebus crash bug

### ISSUE THREAD

**Issue by KitKat31337** [SleepyTrousers/EnderIO#5073]
#### Issue Description:

Ender Pickaxe with Direct crashes mining red gem from erebus.

#### What happens:

server crash

#### What you expected to happen:

mine the gem

#### Steps to reproduce:

1. get Ender Pickaxe with Direct Upgrade
2.Mine Red Gem in Erebus dimension

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- EnderCore:1.12.2-0.5.45
- Minecraft:1.12.2
- Forge: 14.23.5.2808  
- SpongeForge? no
- Optifine? no
- Server

#### Your most recent log file where the issue was present: 

[crash-2019-03-20_06.03.23-server.txt](https://github.com/SleepyTrousers/EnderIO/files/2988283/crash-2019-03-20_06.03.23-server.txt)

**Comment by HenryLoenwind** [comment]
That's the fault of the block. It puts the item(s) it drops into a list that cannot be modified.

**Comment by tyler489** [comment]
@HenryLoenwind https://github.com/vadis365/TheErebus/blob/8c6ecfa766b0861f2191a00edca4994e159a8604/src/main/java/erebus/blocks/BlockRedGem.java#L61-L69

Yep
