### ISSUE TITLE
1.13/1.14 plans

### ISSUE THREAD

**Issue by Zhastreaus** [SleepyTrousers/EnderIO#5074]
Hi,

First of all, thank you so much for the dedication in making this mod.

I would just like to ask if what are the plans/thoughts/status about having this mod in more recent versions of MC 1.13 (above)? 

Thanks for your time.

**Comment by tyler489** [comment]
It will be ported eventually... i mean forge doesnt even have a recomended build yet.

**Comment by olee** [comment]
What about now?

**Comment by Ommina** [comment]
Still no RB for Forge.  Last I checked, the fluid API was still unavailable as well.

Now that vanilla has (apparently) finished with 1.14, forge may be able to get itself caught up.  Maybe.

**Comment by 7934345** [comment]
> Fluids were reimplemented in #5983
I'll consider this accomplished once #6098 is done and merged.

>Calling this done. If there's something we missed in the current implementation, feel free to open followup issues.

[Fluid capabilities](https://github.com/MinecraftForge/MinecraftForge/issues/5848)

**Comment by VA7NFH** [comment]
Now that forge has been updated, do you have an estimate for when this will be done?

**Comment by StormCircuit** [comment]
ripperoni enderio-oni. I was hoping for any update? I would love to include your mod in a 1.15.2 modpack.

**Comment by WebDragon** [comment]
I too would love to see this in 1.15.2 - been puttering around with Botania, Immersive Engineering, and Refined Storage (plus a few QOL mods like JEI and Journeymap) but EnderIO is one of the few mods that I personally feel is a must-have.

**Comment by 7934345** [comment]
Read Pin Message on its Discord
[Here is A quick link](https://discord.com/channels/373534853259329536/373534853259329538/693550049854095490)

> EnderIO will be ported eventually, But there is only one person working on EnderIO and he doesn't want to port EIO alone, bc it's huge mod, So the other dev's have there own mods first, So don't expect EnderIO for 1.15.x and Future Version of forge for awhile and won't be backported. Also 1.14.x is being skipped.
