### ISSUE TITLE
The Tinkers’ Construct Direct trait not working on cleaver

### ISSUE THREAD

**Issue by Dimentive** [SleepyTrousers/EnderIO#5075]
### Issue description:
I made a cleaver with the Direct trait, but mob drops are not teleported to my inventory. The Tinkers’ Construct manual only mentions mined materials, but I’ve read online that it’s supposed to work with weapons and mob drops, too. Is this trait only intended to work with mining, or is it a bug?

### What happens:
I have a Tinkers’ Construct cleaver with the Direct trait, given by energetic alloy, but mob drops are still dropped by mobs rather than teleported to my inventory.

### Steps to reproduce:
1. Create a cleaver with a part made of energetic alloy (can’t be the head).
2. Slay a mob.

****

### Affected versions:

* Ender IO: 5.0.40
* EnderCore: 0.5.45
* Minecraft: 1.12.2
* Forge: 14.23.5.2781
* SpongeForge: No
* OptiFine: Yes
* Single-player and/or server: Locally hosted multiplayer server with one other person

**Comment by HenryLoenwind** [comment]
The trait is only for mining, not for mob drops.

**Comment by Dimentive** [comment]
All right. Thanks for the quick response.

I guess I just confused it with the enchantment of the same name for the Ender swords, which should work for mob drops, too. It’s a shame that’s not the case for the Tinkers’ Construct trait too.
