### ISSUE TITLE
Refined storage conduit exporting bug

### ISSUE THREAD

**Issue by PetNoire** [SleepyTrousers/EnderIO#5076]
#### Issue Description:
Refined storage conduits dont always export properly

#### What happens:
if you put a filter in to export, it will, but if you also put one to import, the exporting stops.
removing the import filter does not fix it, however altering the inventory does. (ex: adding or removing an item) 
opening the conduit gui causes it to stop again

#### What you expected to happen:
To import and export at the same time.

#### Steps to reproduce:

1. attach the conduit to an inventory
2. add an export filter and something to export
3. add a filter to import
4. exporting stops

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- EnderCore: 0.5.45
- Minecraft: 1.12.2
- Forge: 14.23.5.2808
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? server

![Screenshot_45](https://user-images.githubusercontent.com/17011227/54874926-37fb9080-4dba-11e9-9128-e9f9f57bad34.png)
![Screenshot_46](https://user-images.githubusercontent.com/17011227/54874931-5a8da980-4dba-11e9-891e-a66abf7f5d03.png)

**Comment by calloatti** [comment]
The implementation of filters in RS conduits needs a major overhaul in my humble opinion.

#5053

**Comment by PetNoire** [comment]
i also find sometimes they stop exporting just for the luls too. went offline with everything working and came back to nothing being exported at all

**Comment by auddie2015** [comment]
> i also find sometimes they stop exporting just for the luls too. went offline with everything working and came back to nothing being exported at all

I came here to report just this. They just stopped. Everything is still connected. Nothing has changed. They are importing just fine but all exporting has stopped.

I have no log to further help because nothing has crashed. They simply went on holiday!

**Comment by HenryLoenwind** [comment]
I haven't specifically check for this issue, but I've rewritten the whole import/export logic. Feel free to comment if this still happens after the next release.
