### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by ghost** [SleepyTrousers/EnderIO#5078]
#### Issue Description:

The wiki is incredibly out of date.

#### What happens:

I'm used to the old version of Ender IO (best mod ever btw) and want to know more about this new iteration.

#### What you expected to happen:

I go to the wiki and it tells me how things work.

#### Steps to reproduce:

1. Go to the wiki.
2. Read the self-aware footnote from half a year ago saying it's out of date.
3. Weep silently.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft:
- Forge:
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by mindforger** [comment]
>Read the self-aware footnote from half a year ago saying it's out of date.
Weep silently.

reading this in context with the cited text:

>here are directions on how to Contribute to the wiki.

makes me think if you ever visited the link
https://github.com/SleepyTrousers/EnderIO/wiki/Contributing-to-the-Wiki

and concider adding content, instead of complaining about nobody else doing it :)

**Comment by 500mnMaller** [comment]
While I appreciate your original and completely unexpected response, I find it hard to believe that asking players to write the official documentation for something they did not create is the best solution.

Especially in this new, more complex iteration of Ender IO I can't help but think that there are a ton of intricacies that are best described by the people who wrote the code for it.

**Comment by tyler489** [comment]
What would you prefer. No new content and bug fixes or a updated wiki? Because that wiki would take weeks or months to update
