### ISSUE TITLE
Endergy asking for EnderCore Version 5.0.48

### ISSUE THREAD

**Issue by Silencx** [SleepyTrousers/EnderIO#5080]
#### Issue Description:

When wanting to start with endergy it requires EnderCore 5.0.48 

#### What happens:

When wanting to start with endergy it requires EnderCore 5.0.48 

#### What you expected to happen:

That it starts normal

#### Steps to reproduce:

1. Add EnderCore 0.5.43 & endergy 5.0.43
2.Start Minecraft
3.endergy asks for EnderCore 0.5.48
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderCore: 0.5.43
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Start-up

#### Your most recent log file where the issue was present: 

https://pastebin.com/M12PHwg2

**Comment by Tfarcenim** [comment]
Update ender core then

**Comment by tyler489** [comment]
That's intended endercore had more versions than endergy.

**Comment by Silencx** [comment]
but why ask for 0.5.48 when it hasn't been released yet

**Comment by HenryLoenwind** [comment]
Looks quite released to me...

![image](https://user-images.githubusercontent.com/1485873/55037553-6f6a7700-501e-11e9-89b0-dd147efacc0f.png)

**Comment by tyler489** [comment]
Was just about to say...

**Comment by Silencx** [comment]
> Was just about to say...

Could you link me as i cant seem to find it

**Comment by Silencx** [comment]
Sorry im blind...
