### ISSUE TITLE
[1.12.2] Server Startup Crash

### ISSUE THREAD

**Issue by Nitair** [SleepyTrousers/EnderIO#5082]
#### Issue Description:
Minecraft Server is crashing at startup. I assume its EnderIO, but I'm not sure (because of the message ```enderioconduits Failed to load new mod instance.```. I've attached the error log.

#### Steps to reproduce:

1. Install all modular extensions of EnderIO
2. Start Server
3. See errors
____
#### Affected Versions (Do *not* use "latest"):
EnderIO Modular:
- EnderIO-conduits-appliedenergistics-1.12.2-5.0.43.jar
- EnderIO-base-1.12.2-5.0.43.jar
- EnderIO-conduits-1.12.2-5.0.43.jar	
- EnderIO-endergy-1.12.2-5.0.43.jar
- EnderIO-integration-forestry-1.12.2-5.0.43.jar
- EnderIO-machines-1.12.2-5.0.43.jar
- EnderIO-conduits-opencomputers-1.12.2-5.0.43.jar
- EnderIO-conduits-refinedstorage-1.12.2-5.0.43.jar
- EnderIO-integration-tic-1.12.2-5.0.43.jar
- EnderIO-zoo-1.12.2-5.0.43.jar
- EnderStorage-1.12.2-2.4.5.135-universal.jar
- EnderCore-1.12.2-0.5.52.jar

3rd Party:
- GasConduits-1.12.2-1.1.0.jar

Minecraft as Server: 
- 1.12.2 (minecraft_server.1.12.2.jar)

Forge: 
- forge-1.12.2-14.23.5.2823-universal.jar

Others:
- SpongeForge? no
- Optifine? no

Used OS:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
``` 

#### Your most recent log file where the issue was present: 

latest.log: https://gist.github.com/Nitair/513b69c1836b2420ec5b2330650d7f5f
debug.log: https://gist.github.com/Nitair/f7dcba105deb59f58ed92d645bb86fad
crash.log: https://gist.github.com/Nitair/225a82ed5fde519cd8e5eee2e51bd3fa
current modlist: https://minecraft.sunrage-network.com/modlist_latest.html

**Comment by HenryLoenwind** [comment]
```
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.conduits.oc.conduit.OCMixin
	at com.enderio.core.common.transform.EnderCorePlugin$MixinData.initialize(EnderCorePlugin.java:50)
```

@tterrag1098 what do you make of this?

**Comment by tterrag1098** [comment]
The package for eio-conduits encapsulates the package for oc-conduits, causing an attempt at classloading before the module is initialized.

**Comment by Nitair** [comment]
@tterrag1098 @HenryLoenwind Thanks a lot for the fast solution. How's your release plan for your project side at curseforge?

**Comment by HenryLoenwind** [comment]
usually about monthly, but I think for this I'll release early. Just give it a couple of days to see if there are other issues that pop up.
