### ISSUE TITLE
[1.7.10]crash when loading a world

### ISSUE THREAD

**Issue by tonimark** [SleepyTrousers/EnderIO#5083]
#### Steps to reproduce:

1.just load the world
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.7.10-2.3.0.429_beta
- EnderCore:1.7.10-0.2.0.39_beta
- Minecraft:1.7.10
- Forge:1.7.10-10.13.4.1614-1.7.10-universal
- SpongeForge? no
- Optifine?  yes versions:_1.7.10_HD_U_E7.
- Single Player and/or Server? singleplayer

#### Your most recent log file where the issue was present: 

crashlog:https://pastebin.com/hRHrL9K0

**Comment by mindforger** [comment]
Extracells is failing because it never got updated to the beta branch of ae2, check their issues, there is a Workaround

**Comment by tonimark** [comment]
what workaround

**Comment by tonimark** [comment]
oh ok so its a problem with extra cells let me report it
