### ISSUE TITLE
Duplicated recipes generates a lot of warns

### ISSUE THREAD

**Issue by InfinitexX** [SleepyTrousers/EnderIO#5084]
#### Issue Description:

A lot of warns are generated making the server long to start. 
List of the mods of the modpack : https://infinitemodpacks.000webhostapp.com/web/hisvmodpack.html

#### What happens:

When the server start, a lot of warns like this appears, making the server really slow to start.
`The supplied recipe BasicManyToOneRecipe [output=3xitem.item_alloy_ingot@9, recipe=Recipe [input=[RecipeInput [input=1xitem.tier9_items@5, useMeta=true], RecipeInput [input=1xitem.ingotIron@0, useMeta=true], RecipeInput [input=1xitem.thermalfoundation.material@134, useMeta=true]], output=[crazypants.enderio.base.recipe.RecipeOutput@63731f2a], energyRequired=10000]] for Alloy Smelter may be a duplicate to: BasicManyToOneRecipe [output=3xitem.item_alloy_ingot@9, recipe=Recipe [input=[RecipeInput [input=1xitem.thermalfoundation.material@134, useMeta=true], RecipeInput [input=1xitem.ingotIron@0, useMeta=true], RecipeInput [input=1xitem.tier9_items@5, useMeta=true]], output=[crazypants.enderio.base.recipe.RecipeOutput@63731f2a], energyRequired=10000]]`

#### What you expected to happen:

The server should take some minutes to start it tabut kes more than 10 min.

#### Steps to reproduce:

1. Launch a minecraft forge server with the same mods as the modpack
2. Just open the logs and see the flood of warns
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.40
- EnderCore: EnderCore-1.12.2-0.5.45
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2806
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

Logs: https://paste.ee/p/uGaCS

**Comment by Yahve83** [comment]
I have the same isssue but my server take almost 1 hour to boot ..
Modpack : Ragnamod V
EnderIO version on the logs..
Logs : https://puu.sh/DRpYJ/6892b795e8.log

**Comment by mundik** [comment]
Same problem....server boot twice as long, but i have my own modpack.

**Comment by mindforger** [comment]
That puush could not be found ... link broken or puush is omitting .log files from access
