### ISSUE TITLE
Ender IO Machine Break Crash

### ISSUE THREAD

**Issue by Cazadorsniper** [SleepyTrousers/EnderIO#5086]
#### Issue Description:
Any machine that is broken crashes the player. Trying to replace where the machine was with an air block. 

Was reported to me via: https://github.com/Cazadorsniper/PO3/issues/216

#### What happens:
Ender IO machines cause a crash on breakage.
Works fine as long as the player is in creative mode.

#### What you expected to happen:
I expected the machine to break and go to my inventory without crashing.

#### Steps to reproduce:

1. Place any enderio machine down.
2. Break with a pickaxe.
3. Crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.43
- EnderCore: 0.5.52
- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server, haven't been able to reproduce in singleplayer, but my friend was able on a server.

#### Your most recent log file where the issue was present: 

https://pastebin.com/8XVDeZiU

**Comment by HenryLoenwind** [comment]
This is a bug in Botania, they ask us about the AIR item---which our items obviously cannot answer.

https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/BotaniaAPI.java#L354 <-- creating an empty stack.

**Comment by Cazadorsniper** [comment]
Ok

**Comment by HenryLoenwind** [comment]
fixed there with https://github.com/Vazkii/Botania/commit/1701732aaccb02279b64ceeef3d6a0c0409a3bf5

**Comment by Carub37** [comment]
how do i fix this

**Comment by mindforger** [comment]
>fixed there with Vazkii/Botania@1701732

**Comment by Carub37** [comment]
Yes but how do i Apply that to my game

**Comment by tterrag1098** [comment]
Update the mod or wait for the change to be included in the next update
