### ISSUE TITLE
Ender IO Integration with Tinkers' Construct error

### ISSUE THREAD

**Issue by RoSirius** [SleepyTrousers/EnderIO#5087]
#### Issue Description:

I was sent here to report my problem with Ender IO + Tinkers' Construct mod.
I did not update the mod since I got it, but got information from KnightMiner that you are adding a broken recipe which caused fluids to be deleted in the smeltery. KnightMiner also suggested I tell you to fix the code to not add the recipe.

#### What happens:

Minecraft Forge crashes on "Ender IO Integration with Tinkers' Construct" (Step 2?)

#### What you expected to happen:

Everything to go as normal because I never changed any mods, only added some recommended mods like Thermal Foundation/Expansion, Embers, Immersive Engineering, codechickenlib, CoFHCore and CoFHWorld, all fresh out of the CurseForge oven.

#### Steps to reproduce:

1. Open Minecraft launcher
2. Have TConstruct and EnderIO
3. Play Minecraft forge 1.12.2
4. Might not be reproduced, if it would, it will crash on loading Ender IO Integration with Tinkers' Construct as a mod (Step 2?)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: Honestly, I don't know, I don't have the exact number. It's 1.12.2
- EnderCore: Same as above, 1.12.2
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2768
- SpongeForge? _**no**_
- Optifine? definitely a **_yes_**
- **_Single Player_**

#### Your most recent log file where the issue was present: 

**_https://pastebin.com/KP4j8pXV_**

**Comment by tyler489** [comment]
You are 17 versions out of date.. this was fixed in one of the earlier v30 builds
