### ISSUE TITLE
Step assist message Bug and doesn’t disappear. And Padding Sound Bugs with dynsurroundings

### ISSUE THREAD

**Issue by SirAron111** [SleepyTrousers/EnderIO#5088]
#### Issue Description:

The Step assist may be disabled by other mod messages keeps popping up infinitely overlapping with itself. Even thought step assist isn’t even disabled and the boots work fine but the moment you put them on you end up with this.

Also the Padding add-on still makes the game sound completely go insane. Can’t you implement a option to disable certain add-ons? For the armors?

#### What happens:

The Step assist may be disabled by other mod messages keeps popping up infinitely overlapping with itself. Even thought step assist isn’t even disabled and the boots work fine but the moment you put them on you end up with this.

Also the Padding add-on still makes the game sound completely go insane. Can’t you implement a option to disable certain add-ons? For the armors?

#### What you expected to happen:

The message to pop up once after boots equipping and then disappearing or not popping up at all!

#### Steps to reproduce:

1. Go into creative mode
2. Grab the armor 
3. Put it on

...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: Ender IO - 5.0.43
- EnderCore: EnderCore - 1.12.2-0.5.52
- Minecraft: 1.12.2
- Forge: 14.23.5.2822 
- Optifine? with and witouth
- Server and Singleplayer

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
If the message pops up all the time, that is because some other mod interferes with it all the time. It only gets send to the status line when the step height is set, either because step assist was turned on or because some other mod changed it, and a mod is installed that is known to forcefully disable it.

**Comment by SirAron111** [comment]
m ok but is there an option to disable the message? Since there isn’t actually a conflict and the step up works fine I would like to disable the message for my Modpack.

Same as an option to disable certain add-ons the incompatibility for padding and any mod that tweaks around sounds or adds custom noises is game breaking as there isn’t even a toggle button for padding like there is for other things like nigh vision. You basically have to throw away your helmet if you add it. As it will always turn the game sounds into crossfire of noises like you are in the middle of a war zone.

**Comment by Dimentive** [comment]
@HenryLoenwind I’m having the same issue with the step assist.

I updated from version 5.0.40 of Ender IO to 5.0.43 and from version 0.5.45 of EnderCore to 0.5.45 and updated, added, or removed no other mods (aside from updating JEI and two of its add-ons), and this started happening.

[Here’s a video of what it looks like.](https://giant.gfycat.com/LeftObviousImperatorangel.webm) The message keeps appearing and is, as SirAron111 described, infinitely overlapping. And just like for him, step assist is working perfectly fine for me. The message is extremely distracting, though, as it never goes away.

This did not happen before I updated to the latest versions of Ender IO and EnderCore. There has to be something wrong in the latest update of either mod, considering I didn’t update, add, or remove any other mod (other than JEI and a couple add-ons, as mentioned).

**Comment by SkippyMitch** [comment]
Posting comment here (and in the other step assist topic) instead of creating a new issue
I am using another mod for step assist in my pack, so there is constantly a message on the screen saying, "Step Assist may be disabled by another mod." until I toggle step assist of the DarkSteel armor (after every world load, which is often for me) I would ask for there at least to be an option to disable this error message.

**Comment by tterrag1098** [comment]
No. If the error message is displayed, some mod is *breaking* the step height value. We don't have a way to know which, though it sounds like you have a good idea. Maybe report it to them.

**Comment by Dimentive** [comment]
Step assist still works fine. The message keeps appearing and never goes away, yet step assist isn’t broken.

Some mod may be interfering with how step assist works in Ender IO, but as previously mentioned, this didn’t start happening until I updated to version 5.0.43 of Ender IO. There has to be a change in version 5.0.43 of Ender IO (or a change in version 0.5.45 of EnderCore) that affects step assist.

**Comment by tyler489** [comment]
The change was that msg was added... after several reports about it being broken with X Mod

**Comment by Dimentive** [comment]
Oh. So, whatever error is occurring was there all along, then; it just wasn’t being shown.

Still, for me and many other people, step assist _isn’t_ broken. The message says “Step Assist may be disabled by another mod,” but it’s not disabled. Step assist is working just fine. It’s a non-issue. The _real_ issue is Ender IO’s message itself, as it’s distracting and never goes away. Even if there _were_ a problem with the step assist, I wouldn’t want to see it constantly appearing on my screen and never going away. I also have no way to tell _what_ mod is causing the “conflict” as I’ve seen no errors in the console.

Currently, I have no option but to either downgrade to the previous version of Ender IO (which I don’t want to do since the latest version fixed a bug related to the vacuum chest) and never update the mod again or to live with a never-ending stream of “Step Assist may be disabled by another mod.”

I really love Ender IO; it’s one of the best mods out there, but I’d love a config option to disable the message, as it’s pretty annoying to deal with. 😄

**Comment by calloatti** [comment]
I have isolated the conflict to this mod:

https://minecraft.curseforge.com/projects/client-tweaks

Minecraft 1.12.2 with only this mods loaded:

Forge Mod Loader version 14.23.5.2825  
ClientTweaks_1.12.2-3.1.11
EnderCore-1.12.2-0.5.53
EnderIO-1.12.2-5.0.43

This happens:

![2019-04-10_03 35 45](https://user-images.githubusercontent.com/12817862/55856988-572c4900-5b42-11e9-8a7f-44f7331a3fcd.png)

But step assist is actually working fine. When I disable step assist I cannot climb steps:

![2019-04-10_03 35 58](https://user-images.githubusercontent.com/12817862/55857029-762adb00-5b42-11e9-971e-6df99ab29d40.png)

The clienttweaks mod config is the default one:

![2019-04-10_03 34 41](https://user-images.githubusercontent.com/12817862/55857060-8642ba80-5b42-11e9-90e1-841fff01aa90.png)

And I assigned a hotkey to step assist:

![2019-04-10_03 35 29](https://user-images.githubusercontent.com/12817862/55857114-a2465c00-5b42-11e9-9ec0-28b1393ec992.png)

And MC auto-jump is set to OFF:

![2019-04-10_03 35 17](https://user-images.githubusercontent.com/12817862/55857189-cc981980-5b42-11e9-8823-fd1c3fc78e30.png)

So it seems that Ender IO is determining that step-assist is disabled when it is actually not disabled, or the clienttweaks mod is setting some value in a wrong way.

**Comment by Dimentive** [comment]
That makes sense, as I, too, have [Client Tweaks](https://minecraft.curseforge.com/projects/client-tweaks) installed.

**Comment by Dimentive** [comment]
That makes sense, as I, too, have [Client Tweaks](https://minecraft.curseforge.com/projects/client-tweaks) installed.

Hopefully, this bug can be fixed, whether it’s on Client Tweaks’ end or on Ender IO’s end.

**Comment by blay09** [comment]
EnderIO's condition for resetting the step height is broken.

https://github.com/SleepyTrousers/EnderIO/blob/release/1.12.2/enderio-base/src/main/java/crazypants/enderio/base/handler/darksteel/DarkSteelController.java#L234-L241

The code posting the message and setting the stepHeight for step-assist runs if `stepHeight` is below `MAGIC_STEP_HEIGHT` (etc.).

Next tick, `stepHeight` will still be equal to `MAGIC_STEP_HEIGHT` - causing the `else if`-block to run, which resets the stepHeight back to `0.6`, even if the player is wearing Dark Steel Armor. Repeat from there.

**Comment by SirAron111** [comment]
There are many mods that mess with step assist for example I have client tweaks and everlasting abilities as well as ice and fire mod they all do something to step assist. But the assist still works fine and the option for the darksteel boots step assist and the toggle on/off work fine as well it’s just that the message pops up. If it ever didn’t work for some people making modpacks or the like and they complained they didn’t bother to check the config of the mods messing with step height etc.

But I still would like to have a config option to enable/disable this message on the ender io part. Since for a Modpack maker it’s hard to fix something that works fine but adding in a option to disable a display of a message shouldn’t be too hard to implement in the next update of ender io/ ender core.

Of course you could go to every mod dev that messes with step height and step assist in the future and now and tell them to make it fit the Ender io mod so the message doesn’t pop up even thought their step assist function works fine. But that doesn’t sound as easy as this config option implementation. Is what I think at least?

**Comment by Dimentive** [comment]
It looks like this was fixed in version [5.0.44](https://minecraft.curseforge.com/projects/ender-io/files/2708308) of Ender IO.
The changelog says “Fixed step assist logic.”

**Comment by permdaddy** [comment]
If you add ProjectE to Omnifactory, the message keeps popping up. It's very annoying.

**Comment by BigPancake2020** [comment]
This bug still exists and is so annoying.

**Comment by mindforger** [comment]
well, you found thios report, why don't you read it then?

how do you expect it to work? A) report a message to let you know there is an issue or b) silently fail, creating the same issue about the upgrade not working?!

**Comment by heatwaveqc** [comment]
Playing on Stoneblock 1.0.37 on a small multiplayer server. EnderIO version 5.1.55 on the server and client side. Experiencing this issue again.

**Comment by mindforger** [comment]
make a new proper report or read the rotting one you just commented on please
