### ISSUE TITLE
Cannot paint vanilla blocks, such as trapdoors

### ISSUE THREAD

**Issue by Dimentive** [SleepyTrousers/EnderIO#5089]
### Issue description:

The vanilla wooden trap door, iron trap door, and crafting table all have the tooltip “Not painted,” yet I am unable to paint them in the painting machine. I can’t place them in the right slot of the painting machine.

### Steps to reproduce:

1. Get a wooden trapdoor or iron trapdoor.
2. Try to paint it in the painting machine.

### Affected versions

* Ender IO: 5.0.40
* EnderCore: 0.5.45
* Minecraft: 1.12.2
* Forge: 14.23.5.2781
* SpongeForge: No
* OptiFine: Yes
* Single-player or server: Server

(By the way, while I’m here, does the farmer have the same ranges as the 1.10.2 version of Ender IO [15×15 with an octadic capacitor) in the 1.12.2 version?)

**Comment by HenryLoenwind** [comment]
works for me:

![image](https://user-images.githubusercontent.com/1485873/55275400-cfdf0a00-52e5-11e9-92c1-7c5d6f4ff32a.png)

**Comment by Dimentive** [comment]
Huh. I can’t even put a wooden or iron trapdoor in the right slot of the painting machine.

I’m playing the modpack [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579)).

Maybe it’s because of [MalisisDoors](https://minecraft.curseforge.com/projects/malisisdoors), a mod that causes vanilla doors to be animated upon opening and closing? The wooden trapdoor still says it’s from Minecraft, but maybe it does something weird to the door and trapdoor items. I don’t know. It’s probably not that.

I know that there have been three Ender IO versions since 5.0.40, but I couldn’t find anything related to trapdoors or painting blocks in general in the changelog for 5.0.43, and 5.0.41 and 5.0.42 no longer exist. It’s probably a mod conflict. I’m not sure. When the modpack updates to Ender IO 5.0.43, I’ll see if it works then, though.

**Comment by HenryLoenwind** [comment]
Do you also have LiteLoader in the pack? LiteLoader is known to interfere with Forge's feature to replace vanilla blocks and items.

**Comment by Dimentive** [comment]
![Now that’s a name I’ve not heard in a long time](https://user-images.githubusercontent.com/34230933/55283965-78847c80-536d-11e9-9936-ad071e8d90e5.png)

I’m not using LiteLoader.

**Comment by tyler489** [comment]
Can you get a debug crash report by holding f3 and c for 10 seconds and post it here so I can look at your mods list please.

**Comment by Dimentive** [comment]
Why was this closed?
