### ISSUE TITLE
Capacitors are lost when resetting devices in crafting

### ISSUE THREAD

**Issue by Dimentive** [SleepyTrousers/EnderIO#5092]
### Issue description:

Capacitors are permanently lost when resetting a device in a crafting window. This could be solved by giving the player the capacitor back when resetting a device in a crafting window.

However, this might be a non-issue, as the player should probably remember to take the capacitor out before resetting a device. Whether this is something that needs to be fixed is up to you.

### Steps to reproduce:

1. Create an Ender IO device, such as an alloy smelter.
2. Provide it with a capacitor.
3. Break it, either by mining it or using the yeta wrench.
4. Put it in a crafting window, either in your inventory or a crafting table, with nothing else.
5. The capacitor is lost.

### Affected versions

* Ender IO: 5.0.40
* EnderCore: 0.5.45
* Minecraft: 1.12.2
* Forge: 14.23.5.2781
* SpongeForge: No
* OptiFine: Yes
* Single-player or server: Server

**Comment by tyler489** [comment]
Kinda intended.. capacitor data is stored in nbt and crafting it in the crafting grid is intended to remove nbt.

**Comment by Dimentive** [comment]
I guess so. It would be nice if the mod detected that the machine has a capacitor in it and gives it to you when you reset the NBT data, but I’m not expecting this to be implemented. Besides, most people will probably remember to remove the capacitor anyway (not me, though 🤷‍♂️).

**Comment by HenryLoenwind** [comment]
Clearing a machine does exactly what it's supposed to do: it clears the machine and resets it completely.
