### ISSUE TITLE
Interaction with Botania Ring of Magnetism causing client crash on machine harvest

### ISSUE THREAD

**Issue by Water-Cat1** [SleepyTrousers/EnderIO#5093]
#### Issue Description:
When breaking an EnderIO machine while wearing a Botania Ring of Magnetism (since their latest updates) causes the client to crash. Singleplayer world cannot be loaded back into. Client cannot rejoin server until someone else comes along and picks up the machine item. Does not happen when throwing block on ground, only from harvesting. Tested so far with sag mill, alloy smelter and stirling generator.

#### What happens:
Client crashes when harvesting an enderio machine when holding a ring of magnetism

#### What you expected to happen:
Block drops from harvest and moves to inventory

#### Steps to reproduce:

1. Place EnderIO machine into world
2. Equip ring of magnetism
3. Harvest EnderIO machine so that it would drop as an item
4. Encounter crash

____
#### Affected Versions:

- EnderIO: 1.12.2-5.0.43
- EnderCore: 1.12.2-0.5.52
- Minecraft: 1.12.2
- Forge: 14.23.5.2824
- SpongeForge? no
- Optifine? no
- Single Player and Server?
- Botania: r1.10-360

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/otayagefon.mccrash

**Comment by HenryLoenwind** [comment]
#5090
#5086
https://github.com/Vazkii/Botania/issues/2878

**Comment by Water-Cat1** [comment]
Ah apologies. Thanks for the quick response.
