### ISSUE TITLE
Forge version mismatch 1.12

### ISSUE THREAD

**Issue by NVLMagic** [SleepyTrousers/EnderIO#5094]
#### Issue Description:
Trying to lauch but reports that it requires forge version 14.23.4.2705 or above.
I am using forge 14.23.5.2768 which is clearly above.
#### What happens:
Loader stops.
#### What you expected to happen:
Accept the newer forge version.
#### Steps to reproduce:
1. Use forga above
2. EnderCore-1.12.2-0.5.52.jar
3. EnderIO-1.12.2-5.0.43.jar
...

____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: EnderIO-1.12.2-5.0.43.jar
- EnderCore: EnderCore-1.12.2-0.5.52.jar
- Minecraft: 1.12
- Forge: 14.23.5.2768
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
That message is produced by Forge, not by us.
