### ISSUE TITLE
Extremely fast growth when using Acceleration Wand on Farming Station (All The Mods 3)

### ISSUE THREAD

**Issue by lmcintyre** [SleepyTrousers/EnderIO#5095]
#### Issue Description:
I tried to use my acceleration wand on the Ender IO Farming Station so it would harvest my crops faster. Instead, it grows everything around it at an extreme rate. I have reported this to the modpack authors and they mentioned they couldn't do anything about it specifically (understandable) and to report it here.

#### What happens:
Every crop in range of the Farming Station grows very quickly.

#### What you expected to happen:
The Farming Station's rate of _harvesting fully grown crops_ in the area is increased. Essentially, I tried this because I was wondering if it would iterate over its area faster.

#### Steps to reproduce:
1. Create a 15x15 area where a max range upgrade EnderIO Farming Station can harvest.
2. Populate its area with seeds of plants it can plant and harvest.
3. Automate item retrieval from output and supply plenty of power.
4. Hold Shift+Right click with the Acceleration Wand on the Farming Station. Crops will grow at an extreme rate.
Link to a video of this in action: https://www.youtube.com/watch?v=f6JLsRnYKlo
I realized after the fact that I never had a "control" sample, a clip of the crops without this occurring. Trust me when I say they grow nowhere near as fast normally.

____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: 1.12.2-5.0.36
- EnderCore: 1.12.2-0.5.41
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2768
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Server, did not test SSP.
- Modpack? Yes, All The Mods 3 version 5.11.2.

#### Your most recent log file where the issue was present: 
Seems unhelpful, but serverlog:
https://gist.github.com/lmcintyre/b2e776d6642962139ea148f95be3faea
Clientlog:
https://gist.github.com/lmcintyre/2547a279a333018c12ff2e45b73825bb

**Comment by tyler489** [comment]
Intended? Ish?
Farming stations apply an effect simular to bonemeal to crops ever so often. By accelerating the farming station "bonemeals" more often.

The config option to disable is should farmer joe take care of his crops or something like that

**Comment by MatthiasMann** [comment]
EnderIO machines by default have protection against being accelerated. The wand is probably applying an area effect which then only affects the crops.

**Comment by HenryLoenwind** [comment]
works as designed. And the protection against being sped up is off by default (no idea why...).
