### ISSUE TITLE
Random crash where screen goes blue, no UI or anything

### ISSUE THREAD

**Issue by Chupp4-Jo3** [SleepyTrousers/EnderIO#5097]
So I went to mess with my power setup after my Mekanism Fusion Reactor shut off randomly and my screen just went sky blue. no UI, no nothing. Game crashes after trying to load the world now with the same screen. Vanilla Fix means the crash goes to main menu with the crash report.

https://paste.dimdev.org/usalovizim.mccrash

No idea how specifically to reproduce sorry.

Note: MC version 1.12.2 so I'm leaving that part off of the mod version names.

- EnderIO: 5.0.43
- EnderCore: 0.5.52
- Minecraft: 1.12.2
- Forge: 14.23.4.2824
- SpongeForge? no
- Optifine? no
 SP

latest.log included as .zip attachment

[latest.zip](https://github.com/SleepyTrousers/EnderIO/files/3050654/latest.zip)

**Comment by Chupp4-Jo3** [comment]
Also as a side note, Vanilla fix recognises the 'culprits' as EnderIO and every EnderIO module (RS Conduits, EIO Machines, EIO compats etc.) instead of just EnderIO or one of the modules. Is this easy to fix; a VanillaFix issue; or just a result of the design of the mod? would be nice if it can be fixed for clarity but is just an afterthought :)

**Comment by HenryLoenwind** [comment]
That's a bug in WandWorker, report it to them: They are creating an empty itemstack of one of our items, which I'm 99% sure isn't their intention (because it makes no sense).

**Comment by Chupp4-Jo3** [comment]
@HenryLoenwind I don't have a mod by that name installed but googling it comes up with BetterBuildersWands. Do you know if they're the same or is it some part of a different mod entirely?

**Comment by HenryLoenwind** [comment]
um, I may have posted the class name from the stack trace without trying to map it to a mod name there... sry

**Comment by ProthosMP** [comment]
I have a builders wand (BetterBuildersWands mod) in my hand and I point towards an enderIO capacitor bank I get this crash. Going into MCEdit and deleting the capacitor bank solves the crash on trying to reload the world.
