### ISSUE TITLE
Looping world crash after placed me conduit.

### ISSUE THREAD

**Issue by Renari** [SleepyTrousers/EnderIO#5098]
#### Issue Description:
I placed a ME conduit down after which the server repeatedly restarts with the same crash. There appear to be a number of similar issues from 2015 which the fix was to update to rv2. However I'm running rv6.

#### What happens:
Server crashes.

#### What you expected to happen:
ME conduit connecting to the network.

#### Steps to reproduce:

1.  Place me conduit next to ME Controller

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.40
- EnderCore: 0.5.52
- Minecraft: 1.12.2
- Forge: 14.23.5.2824
- SpongeForge? no
- Optifine? no
- Server/Client
- Applied Energistics 2: rv6-stable-6

#### Your most recent log file where the issue was present: 

https://gist.github.com/Renari/abe0cc62019b0e8e767c84eec8086a0c

**Comment by tterrag1098** [comment]
Could you provide the entire startup log?

**Comment by Renari** [comment]
latest.log:
https://gist.github.com/Renari/47dc603bebee3ecde270f8152e31a1d1

video:
https://streamable.com/i7vu4

openeye log:
http://openeye.openmods.info/crashes/6686d18dde0c6b8709b7a5f640e20500

**Comment by HenryLoenwind** [comment]
SimpleMixinPatcher seems to not have run at all. weird.

**Comment by Renari** [comment]
Changed the title as this was reproduce-able in single player.

**Comment by tterrag1098** [comment]
It might be a large file, but could you upload a debug.log ?

**Comment by Renari** [comment]
[debug.log](https://github.com/SleepyTrousers/EnderIO/files/3056396/debug.log)

**Comment by HenryLoenwind** [comment]
oh, I see it now. Sorry, must have been blind the first time.

You're using the current EnderCore with an outdated Ender IO. Either downgrade EnderCore to 0.5.40 or upgrade Ender IO to 5.0.43.

**Comment by HenryLoenwind** [comment]
Just a bit of info what's wrong: We expanded the functionality in EnderCore that allows us (among other things) to have conduits in their own mods. During that process we noticed a flaw in the old implementation and fixed it. However, this also required the consumer (the conduit mods) to change their code. So newer EnderCores will only work for Ender IO modules that have the updated code.

**Comment by Renari** [comment]
Thanks, can confirm that fixed the issue.
