### ISSUE TITLE
Crashed when adding Ender.io to my modpack

### ISSUE THREAD

**Issue by FiliboyYT** [SleepyTrousers/EnderIO#5100]
#### Steps to reproduce:

1.Launch???
2.wait???
3.crash???
...

____
Affected Versions: 1.12.2

- EnderIO: 5.0.43
- EnderCore: 0.5.56
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2835
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 2019-04-12_14.21.08

[https://pastebin.com/yK81CEaU]

**Comment by LumberWizard** [comment]
Not related to EnderIO. You went over the block ID limit. Either uninstall mods or install a mod that extends the limit, such as Just Enough IDs.
