### ISSUE TITLE
Pointing a Better Builder's wand at a capacitor bank causes a crash to desktop

### ISSUE THREAD

**Issue by BinaryConstruct** [SleepyTrousers/EnderIO#5103]
#### Issue Description:
In the modpad FTB Sky Odyssey, pointing a Better Builder's wand at a capacitor bank causes a crash to desktop. This has been reported to FTB and is a cross post of https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/353

#### What happens:
Pointing a Better Builder's wand at a capacitor bank causes a crash to desktop

#### What you expected to happen:
Render the building squares for wand, no CTD.

#### Steps to reproduce:

1. Create new creative world.
2. Place vibrant capacitor bank, point better builder's wand at bank.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO-1.12.2-5.0.43
- EnderCore-1.12.2-0.5.53
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2815
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? SP

#### Your most recent log file where the issue was present: 
https://paste.feed-the-beast.com/view/2638f557

**Comment by HenryLoenwind** [comment]
#5097

**Comment by LatvianModder** [comment]
I'm pretty sure it's a bug in Ender IO, it seems to drop an ItemEntity with an empty ItemStack in it, perhaps only on client side. Possible fix is, don't drop item on client side, it will be sent from server. There was an issue recently with Botania magnets too, while botania fixed it on their end by adding !isEmpty() check, it's still EIO issue

**Comment by HenryLoenwind** [comment]
Ender IO isn't dropping an empty EntityItem, Builder's Wand is creating an empty ItemStack for our item. Which is a logic error as that stack is completely useless.

`new ItemStack(whatever, 0, 0)`

**Comment by LatvianModder** [comment]
Oh wtf.. my bad then 👌

**Comment by HenryLoenwind** [comment]
np; you don't want to know how long it took me to realize what's happening. Creating ItemStacks with a 0 size wasn't exactly on my "look out for it" list ;)...
