### ISSUE TITLE
Wither skele powered spawner does spawn

### ISSUE THREAD

**Issue by MrCjGames** [SleepyTrousers/EnderIO#5104]
#### Issue Description:

when i use any spawning type machine ive tried the powered spawner and draconic spawner to try to spawn wither skele but it says its denied by a mod anyone know whats doing this im on direwold20 pack  
![2019-04-15_04 29 57](https://user-images.githubusercontent.com/14237433/56118087-93dbb400-5f37-11e9-8db9-5190f8d8cefe.png)

**Comment by HenryLoenwind** [comment]
You have a mod installed that says "**NOOOOOOOOOOOOOOOOOOOOO, I FORBID IT. IT AIN'T ALLOWED!! IT'S VERBOTEN!!!**" when we try to spawn a mob.

Simple as that.

**Comment by MrCjGames** [comment]
so theres no way to get rid of it? so just do a normal skele spawner on the nether and do it that way then?

**Comment by tyler489** [comment]
Or find whatever mod is stopping spawns in that area
