### ISSUE TITLE
Crash when killing a mob with a projectile.

### ISSUE THREAD

**Issue by Azzezima** [SleepyTrousers/EnderIO#5105]
#### Issue Description:

Issue only seems to happen when using a projectile to kill a mob.
Melee doesn't trigger the crash.
Vanilla bow doesn't seem to trigger the issue though but most other projectiles do.

#### What happens:
Game crashes when killing a mob with most projectile types.

#### What you expected to happen:
The mob to die without it crashing the game

#### Steps to reproduce:

1. Shoot a mob with a bow or something like a magic mod projectile

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.43
- EnderCore: 1.12.2-0.5.57
- Minecraft: 1.12.2
- Forge: 14.23.5.2823
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 

https://pastebin.com/4GFViS4M

**Comment by HenryLoenwind** [comment]
Have you disabled half of Tinkers?

**Comment by Azzezima** [comment]
Removing Tinkers fixes the issue, disabling the modules of tinkers however did not.
Next thing i could try is installing the separate ender io modules except for the tinker integration one?

**Comment by HenryLoenwind** [comment]
I think I see what's the issue. Do you have "TinkerModifiers" pulse disabled? If yes, I know what to do.

**Comment by Azzezima** [comment]
I'm afraid i don't know how to even disable "TinkerModifiers". How do i check?

**Comment by HenryLoenwind** [comment]
Not sure. But let's make this easier for both of us: Just install the next dev build of Ender IO ( https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/ Build 948) when it's ready. If that helps, then I diagnosed the issue correctly.

**Comment by Azzezima** [comment]
Will do, will keep you posted when i test it.

**Comment by Azzezima** [comment]
Issue seems to be fixed. Tested with multiple types of projectiles and no crash.
