### ISSUE TITLE
Removing Grains of Infinity Recipe

### ISSUE THREAD

**Issue by JakeOTwitch** [SleepyTrousers/EnderIO#5106]
#### Issue Description:

I'd like to remove the Grains of Infinity recipes that involve lighting bedrock on fire or pouring fire water on it but I can't find the file where I might be able to disable them. Is there a way to do this?

**Comment by tyler489** [comment]
Why do you want to remove them?.

**Comment by LumberWizard** [comment]
The infinitypowder category in enderio.cfg has all the settings you care about.
