### ISSUE TITLE
Exploding Machines

### ISSUE THREAD

**Issue by WillBoy20101** [SleepyTrousers/EnderIO#5107]
Issue Description:

Whenever I put any machine that accepts any energy, even the ones that puts in capacitors the machine doesn't explode but it does make the sound that it is

Steps to reproduce:
1. Make any machine that has an energy input.
2. Then try to make the machine accept any energy
3. When the machine charges up it makes the explosion sounds and it doesn't stop and if you stand near the machine it does hurt you.

____
Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.43
- EnderCore: 1.12.2-0.5.57
- Minecraft: 1.12.2
- Forge: 14.23.5.2825
- SpongeForge? no
- Optifine? yes
- Single Player or/ Server? Both

Your most recent log file where the issue was present: 

Never get a crash log.

**Comment by SplitInfinitive** [comment]
What wire are you trying to connect to your machine?  The explosion noise is from EIO code telling you that something is trying to insert energy multiple times per tick (which some of the wires from other mods do).  It CAN be disabled via the config file.

**Comment by WillBoy20101** [comment]
> 
> 
> What wire are you trying to connect to your machine? The explosion noise is from EIO code telling you that something is trying to insert energy multiple times per tick (which some of the wires from other mods do). It CAN be disabled via the config file.

Where is the config for it and i'm was using Mekanism's universal cables

**Comment by tyler489** [comment]
In enderio off and yes Mekanism ducts are bad for attempting to bypass machine limits.

**Comment by WillBoy20101** [comment]
> 
> 
> In enderio cfg and yes Mekanism ducts are bad for attempting to bypass machine limits.

Can you show me where the config is?

**Comment by tyler489** [comment]
In the config directory where ever your Minecraft is saves to

**Comment by Yamza** [comment]
Since no one could actually be bothered to properly explain how to disable this absolutely asinine feature that was added:
Go into the config folder of your instance, find EnderIO.cfg, locate the following line: 

```
    # Should TEs protected their maximum energy input against multiple inserts? [default: HARD]
    S:protectAgainstEnergyOverflow=HARD
```
Change HARD to NONE

Than make sure to comment to the devs about how absolutely ignorant it was to add this feature and enable it by default.

**Comment by Ommina** [comment]
The whole point of capacitors is to provide an upgradable limit to the amount of energy a machine stores and accepts.  If Mod B decides to play fast and loose with the "n energy per tick" limit by doing multiple inserts, then I rather believe Mod B needs to rethink their design.

**Comment by Yamza** [comment]
Why not ask Mod B to change it then instead of annoying people who just want to play the game.

**Comment by mindforger** [comment]
Feel free to tell them

**Comment by Tearlow** [comment]
"We'll force others who don't follow our way of thinking!" - I... I don't even. I really don't. Always Opt-In not Opt-Out.

It's their mod, they can do as they see fit. But the total lack of proper responds (other than @Yamza) astounds me.

**Comment by Ommina** [comment]
I really feel I shouldn't reply to this, but I'm going to.  Sorry all.

Surely "It's their mod, they can do as they see fit" applies both ways, no?  Suggesting Mod B should have free reign on account of it being their mod and their code, but Mod A not having equivalent freedom with _their_ mod and code seems disingenuous, at best.

**Comment by Tearlow** [comment]
@Ommina Isn't that basically what I said though? It's why Opt-in should always be the default not the other way around. That does not mean I don't understand the reasoning behind it. But going out of their way to deny people to play how they want without changing settings to allow other mods to function as intended seems like a bad idea and not winning anyone over.

**Comment by tyler489** [comment]
The only reason this was set to hard was to see how many mods were bypassing energy limits once we got a good list these mod devs were informed and it was turned to soft by default in the next update. Also the explosion should only happen once and only be strong enough to blow up enderios machine.

**Comment by Tearlow** [comment]
> Also the explosion should only happen once and only be strong enough to blow up enderios machine.

Did you mean that the other way around? I've only seen the charging block blow up. Booted up Minecraft just to test and indeed- When I plop down a Solar flux panel the panel is blow up. The EnderIO machine still sitting there.

**Comment by tyler489** [comment]
nope the explosion is suppost to be only strong enough to blow up enderio's block that means that solar flux must have a 0 explosion resistance

**Comment by HenryLoenwind** [comment]
Correction: The explosion has minimum possible strength unless some mod is sending hundreds of energy push operation per tick. That's not even strong enough to blow up grass.

And expecting other mods to use an API correctly has nothing to do with "opt-in". If you cell phone charger was outputting 400 Volts instead of 5 Volts, you wouldn't just say "it blew up my iPhone in a fiery explosion, but hey, the manufacturer just didn't opt-in to the USB standard".
