### ISSUE TITLE
Pulverizing prismarine cristals

### ISSUE THREAD

**Issue by Clooooud** [SleepyTrousers/EnderIO#5108]
#### Issue Description:

Pulverizing prismarine crystals is giving back prismarine crystals with a little chance of getting another one so, it's duplicating the prismarine crystal

#### What happens:

I wanted to get prismarine crystals so, i pulverized prismarine shard and got 2 prismarine crystals, then i used this little bug to create energy with Thermal Expansion.

#### What you expected to happen:

It must give only one prismarine crystal when pulverizing the prismarine shard and prevent the pulverization of the prismarine crystal.

#### Steps to reproduce:

1. Take a prismarine shard
2. Put it in the SAG Mill
3. After some try, you can get 2 prismarine crystals.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.43
- EnderCore: 1.12.2-0.5.53
- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- SpongeForge? yno
- Optifine? yes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

There is no log needed so there is a screenshot of the craft.
![Screenshot](https://user-images.githubusercontent.com/42965520/56390282-fc72ab80-622b-11e9-9036-13cd6caafee5.png)

**Comment by tyler489** [comment]
can you put the cursor over the prismarine crystals as i dont see how that could happen with just enderio.

**Comment by HenryLoenwind** [comment]
Your report is a bit confusing do you start with a shard or a crystal? "1 shard => 1.1 crystals" is the recipe we add. We do not add any sagmill recipe that starts with crystals.
