### ISSUE TITLE
Barrier Block should probably be blacklist by default on "be blinked through"

### ISSUE THREAD

**Issue by Fireztonez** [SleepyTrousers/EnderIO#5110]
#### Issue Description:

Hello, I just do somes tests on compact Machine and I see, compact machines have about 4 blocks thick of Minecraft Barrier Blocks, plus the Solid compact machine wall, and we still can teleport outside of the box with the Staff of Traveling... I know I can add somes blocks to the blacklist and I will do for compact machine wall and barrier block, but I think, Barrier Block should probably be a default thing, because, it's made question of block the player and this is a vanilla things...

#### What happens (I think a picture will say eveything :D):
![image](https://user-images.githubusercontent.com/19277301/56466831-f70c9100-63e4-11e9-81aa-4461442ce890.png)

#### What you expected to happen: 
Barrier block should not alloow player to teleport trow...

#### Steps to reproduce:

1.Try to teleport outside of a Compact Machine and, enjoy the void Dim :D
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.43
- EnderCore: 0.5.57
- Minecraft: 1.12.2
- Forge: 14.23.5.2824
- SpongeForge? No
- Optifine? No (Don't want more trouble than I have ;) )
- Single Player and/or Server? Single player

**Comment by HenryLoenwind** [comment]
It doesn't need to be blacklisted, it's just that the check for `enableBlinkUnbreakableBlocks` needs to be done for "not blacklisted blocks", not for "blacklisted blocks"...

**Comment by HenryLoenwind** [comment]
BTW: You need to manually set `enableBlinkThroughUnbreakableBlocks` to true in your existing config file after updating to the next version.
