### ISSUE TITLE
Can not set quantity in Limited Item Filter

### ISSUE THREAD

**Issue by Nightcaste** [SleepyTrousers/EnderIO#5111]
#### Issue Description:

Can not set quantity in limited item filter in Sky Odyssey 1.1.0.  I don't know if this is a pack issue or a mod issue so you're both getting the report.

#### What happens:

Placing a stack of items in a Limited Item Filter slot sets the count to one, with no count indicated on the stack, and only passes one unit of that item into the attached inventory

#### What you expected to happen:
Expected to be able to set a specific quantity of items to be kept in attached inventory

#### Steps to reproduce:

1.  Set Limited Item Filter slot to any amount of an item
2. ???
3. Fail to profit
...

____
#### Affected Versions (Do *not* use "latest"):

EnderCore 1.12.2-0.5.52
EnderIO 1.12.2-5.0.43
- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- SpongeForge? I don't know how to determine this
- Optifine? god no
- Single Player and/or Server?  SSP

#### Your most recent log file where the issue was present: 

There wasn't a crash so I don't know what log would be relevant

**Comment by TemperedFool** [comment]
I posted the issue Niller linked above for E2:ES; I'm seeing the same behavior there, with the same versions, with just JEI, EnderIO, and EnderCore installed.
