### ISSUE TITLE
Old world loading with blocks missing

### ISSUE THREAD

**Issue by KvantVS** [SleepyTrousers/EnderIO#5115]
#### Issue Description:
MC 1.12.2.
-----
I have the world in version 1.10.2. After install and set up MC 1.12.2 and all previous mods I cannot load my world. The game shows me the Warning about 438 missing entities (items and blocks) from EnderIO mod (Monolithic installation, as always). What I have to do? 
I have switched from old MC versions (and all of mods) to new MC versions before without such problem with same mods... 
Now I load my world and ALL of Ender IO blocks, items, entities, pipes in world, in chests are VANISHED.
All the versions of mods are compatible with MC version (1.12.2).
I use Ender IO with few mods (not someone's modpack):
BetterFoliage-MC1.12-2.2.0
EnderCore-1.12.2-0.5.57
EnderIO-1.12.2-5.0.43
EnderIO-zoo-1.12.2-5.0.43 (before it I used EnderZoo-1.10-1.2.3.44)
Forgelin-1.8.2
HardcoreDarkness-MC1.12.2-2.0
industrialcraft-2-2.8.109-ex112
itemscroller-1.12.2-0.12.0
llibrary-1.7.18-1.12.2
OptiFine-1.12.2_HD_U_E3
SoundFilters-0.10_for_1.12
WorldControl-1.0.31
railcraft-12.0.0.

#### What happens:
World from 1.10.2 loads with missed all EnderIO content in 1.12.2

#### What you expected to happen:
World loads with all my EnderIO machines and items as it is.

#### Steps to reproduce:

1. Install minecraft 1.12.2
2. Install OptiFine-1.12.2_HD_U_E3 and Forge 14.23.5.2811
3. Install all aforemetioned mods .

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.43
- EnderCore: 1.12.2-0.5.57
- Minecraft: 1.12.2.
- Forge: 14.23.5.2811
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 

"latest.log", part 1 - https://pastebin.com/8jbKA6Nf
"latest.log", part 2 - https://pastebin.com/Pd5jsuH4

**Comment by EpicSquid** [comment]
Updating between mc versions is almost never possible for a clean update with your world. Lots of things internally in both mc and Ender io have changed, and as such 1.10.2 worlds and 1.12.2 worlds are not compatible.

**Comment by KvantVS** [comment]
It's strange. I had updated my world before, e.g. from 1.9.4 to 1.10.2 with same mods.
Then... is there any utility that can reassign IDs (in the world/in the whole game) as I want to?

**Comment by tyler489** [comment]
1.9 -1.10 was not as a big of change as 1.10 was to 1.12

And not that I'm aware of..

**Comment by KvantVS** [comment]
I thought MCEdit could help. In Ender IO 1.12.2 were renamed all of the blocks and entities. Maybe trouble in that fact? I tried rename enderman's skull name (non-digit ID) in my house from 1.10.2-name to 1.12.2-name, but nothing happens.

Hey, I don't want to start new game each half-year just because developers has no rules to name their variables and constants... If you (and developers) could give some advice how to solve it, how to change blocks' IDs or names or sort of workaround

**Comment by HenryLoenwind** [comment]
Complain to the Forge project that they forced us to rename everything. It's certainly not that we're stupid or planless.

**Comment by KvantVS** [comment]
Ok, thanks for reaction. Then my words can be applied to Forge developers... 
Btw, all IC2-machines remained and stayed in their places. It is all so strange and i'm loosing heart to play from zero-point again and again.
I'm a programmer. Maybe there is a possibility to create world-version converter or smth like it? Mainly for Ender IO. But i'm not familiar with forge and minecraft world data structure. It may would be useful utility for future versions. 
Sorry for my English
