### ISSUE TITLE
ender IO Crash

### ISSUE THREAD

**Issue by aervin85** [SleepyTrousers/EnderIO#5117]
#### Issue Description:

When playing, the game crashed without being prompted by anything I can determine. I attempted to reload the game and it gave the same crash information detailed in the screenshot. The day prior a Java update did come through which may be the problem, however, I was able to load Stoneblock 1 without issue on the updated version of Java..

#### Steps to reproduce:

1. Click on my file and load the game
2. Game crashes
3. 
...

____
#### Affected Versions:

- EnderIO: 5.0.43
- EnderCore: 1.12.2-0.5.57
- Minecraft: Stoneblock 1.11.0
- Forge: 14.23.5.2836
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Single player

#### Your most recent log file where the issue was present: 

https://paste.feed-the-beast.com/view/0eef8e68

**Comment by tyler489** [comment]
#5093 #5103
