### ISSUE TITLE
Killer Joe And Authme plug-in a problem of

### ISSUE THREAD

**Issue by Xing-C** [SleepyTrousers/EnderIO#5119]
My killer Joe can't do any damage to creatures because Authme treats killer Joe as a player but he's not logged in
I found a way to do this, the configuration file for Authme;
    unrestrictions:
        # Below you can list all account names that AuthMe will ignore
        # for registration or login. Configure it at your own risk!!
        # This option adds compatibility with BuildCraft and some other mods.
        # It is case-insensitive! Example:
        UnrestrictedName:
        - 'npcPlayer'

This method works, but I don't know which player ID is the killer Joe，Help Me :(

**Comment by LumberWizard** [comment]
Why don't you instead try to tell the devs of AuthMe not to treat fake players as players who aren't logged in, or perhaps not use plugins in a Forge environment when they weren't meant to.

**Comment by mindforger** [comment]
why do you use authme specifcally?

**Comment by Xing-C** [comment]
Because it's not a plugin error, it's just that I don't know the correct name, and I've tried these but they're not correct
        UnrestrictedName:
        - 'tile_killer_joe'
        - 'tilekillerjoe'
        - 'killer_joe'
        - 'killerjoe'

**Comment by mindforger** [comment]
try 'KillerJoe'

**Comment by Xing-C** [comment]
It doesn't work.

**Comment by mindforger** [comment]
i edited my comment a bit, if that does also not work, i point at my earlier question

**Comment by tyler489** [comment]
It's eio_killera or something like

**Comment by mindforger** [comment]
@tyler489 how is this defined? and with what did i come up then? 

is that the forge fake palyer?!

**Comment by Xing-C** [comment]
Thank you for your help
I still haven't found the right way, but maybe I should try changing the plugin

**Comment by HenryLoenwind** [comment]
As quoted before, the name is `[Killer Joe]`, see: https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-machines/src/main/java/crazypants/enderio/machines/machine/killera/Attackera.java#L26-L27 

However, any permission plugin/mod used in a Forge environment **needs** to understand Forge's `FakePlayer` API. There are just too many fake players around in plenty of mods (Ender IO alone has 5).

Also, we do **NOT** support using Ender IO on a server in 'offline' mode outside a development environment. Closed and locked.
