### ISSUE TITLE
Grains of Infinity not working in faction world

### ISSUE THREAD

**Issue by Trnrr** [SleepyTrousers/EnderIO#5120]
#### Issue Description:

Grains of infinity doesn't work on our faction world. The faction world is an overworld.

#### What happens:

We have a faction world that has custom generation. It is set as an overworld but Grains of Infinity doesn't work in that world. http://puu.sh/Dm73H/185486d67c.png Is there anyway to make it work in that world or will it only work in the 'main' server world? 

In the config I see 
`# Should making Infinity Powder be allowed in all dimensions? If not, it'll only work in the overworld. (synced from server) [default: false]`
`B:enableInAllDimensions=false`

If I set that to true will it work for the faction world? I know that setting will make it work in all dimensions as well. I'm just curious if there is a way to make it work without enabling it in all dimensions.

#### What you expected to happen:

It to work in the faction world since it is an overworld.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.43
- EnderCore: EnderCore-1.12.2-0.5.52
- Minecraft: 1.12.2
- Forge: 14.23.5.2807
- SpongeForge? Yes - 1.12.2-2768-7.1.6-RC3616
- Optifine? No
- Single Player and/or Server? Server

**Comment by tyler489** [comment]
Is the faction world Dim 0?

**Comment by Trnrr** [comment]
> 
> 
> Is the faction world Dim 0?
The faction world is dim2, but it's set as an overworld. The main world dim 0 is used for other things

**Comment by tyler489** [comment]
And Henry reads my mind with that comment..

**Comment by Trnrr** [comment]
@tyler489 sorry for the @. It looks like he implemented that feature which is sweet!! I see that there are dev builds. Do you know if they are stable enough to run on a live server? Or should I just wait for a new release on curseforge?

**Comment by tyler489** [comment]
I would say they are pretty stable but you can't use them on curse packs if that's a problem. You also need the dev build of endercore..   or you can wait for the new release hopefully this week.

**Comment by Trnrr** [comment]
> 
> 
> I would say they are pretty stable but you can't use them on curse packs if that's a problem. You also need the dev build of endercore.. or you can wait for the new release hopefully this week.

Ok thank you for the information. I will wait until the next build is released on curse.
