### ISSUE TITLE
Ender Io machine background seems to be broken. And configs don’t help

### ISSUE THREAD

**Issue by SirAron111** [SleepyTrousers/EnderIO#5121]
Ender Io machine background seems to be broken. And configs don’t help
Ok this is super laggy and annoying for some reason the new update made the machines have some strange background instead of the old ender man face and I can’t change it with any config. Need help here. Here are some pictures of what I mean and this thing is even animated to make it more laggy.

![2019-05-03_17 25 40](https://user-images.githubusercontent.com/39855956/57147922-e71f8480-6dc8-11e9-86e9-e84354783c6f.png)
![2019-05-03_17 25 42](https://user-images.githubusercontent.com/39855956/57147923-e71f8480-6dc8-11e9-8b6a-eab3a54dc2ed.png)
![2019-05-03_17 25 43](https://user-images.githubusercontent.com/39855956/57147924-e71f8480-6dc8-11e9-9ef2-6122bf7af4a9.png)

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/57148136-4a111b80-6dc9-11e9-81e9-ba352736d20b.png)

**Comment by SirAron111** [comment]
So it’s just today and I thought it’s a bug since I updated it today and couldn’t find any UI settings in the config for it. SRY
