### ISSUE TITLE
Capacitor banks going to negative values

### ISSUE THREAD

**Issue by Testo0987** [SleepyTrousers/EnderIO#5122]
#### Issue Description:
Hello, so i was experimenting on the configs for the EnderIO capacitor banks and when you set any capacitor bank value to its maximum, 2,000,000,000 for the I/O rate, and place multiple of the in a multiblock the transfer limit goes into the negatives.

#### What you expected to happen:
I expected it to just combine the energy rates.

#### Steps to reproduce:

1. Enter a new world
2. Set I/O rate in the configs for any capacitor bank to 2,000,000,000
3. Place multiple of them in a multiblock
4. Look at the GUI and see that the max input/output is negative
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-0.5.57
- EnderCore: 1.12.2-5.0.43
- Minecraft: 1.12.2
- Forge: 1.12.2 v2815
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Single player

#### Your most recent log file where the issue was present: 

[N/A]

**Comment by HenryLoenwind** [comment]
I'll have a look if there's an easy way to limit this.

**Comment by HenryLoenwind** [comment]
Oh, code to protect against this case already is in place. I just tweaked it a bit to actually work... ;/
