### ISSUE TITLE
[Suggestion] Ore Dictionary filter

### ISSUE THREAD

**Issue by Programie** [SleepyTrousers/EnderIO#5126]
It would be nice to have a filter which can use Ore Dictionary strings (containing placeholders like "*" or even regular expressions).

For example to only allow ores to go into a chest, I would like to add this filter and enter "ore*" into a text box. Similar to the [ME Ore Dictionary Export Bus](https://github.com/ExtraCells/ExtraCells2/wiki/Network#me-ore-dictionary-export-bus) from ExtraCells 2 (AE2 add-on).

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by Programie** [comment]
OK, sorry for posting it as an issue on GitHub. Thanks for the hint, I will post it as a suggestion on The Idea Wall.
