### ISSUE TITLE
Killer Joe drop my sword

### ISSUE THREAD

**Issue by GhostShot3** [SleepyTrousers/EnderIO#5128]
I'm having poblem with "Killer Joe", it kills some mobs and drop a sword on the ground

- EnderIO:EnderIO-1.7.10-2.3.0.429_beta
- EnderCore:EnderCore-1.7.10-0.2.0.39_beta
- Minecraft:1.7.10
- Forge:Forge 10.13.4.1566-1.7.10
- Optifine:OptiFine_1.7.10_HD_U_E7

**Comment by GhostShot3** [comment]
What happend?

**Comment by HenryLoenwind** [comment]
Our last 1.7.10 release was 4 years ago...

However, the Killer Joe doesn't (and never has) had code to drop anything to the ground. So some other mod is removing the sword.

**Comment by GhostShot3** [comment]
Ok, Thanks.
