### ISSUE TITLE
Endergy’s alloy ingots not appearing in JEI

### ISSUE THREAD

**Issue by Dimentive** [SleepyTrousers/EnderIO#5129]
#### Issue description

The alloy ingots added by [Ender IO Endergy](https://minecraft.curseforge.com/projects/ender-io-endergy) (crystalline alloy ingot, melodic alloy ingot, and stellar alloy ingot) do not appear in [Just Enough Items](https://minecraft.curseforge.com/projects/jei). Other items from Endergy do appear in JEI (some other items may be missing, but I haven’t noticed any others yet), but none of its four alloy ingots appears. Base Ender IO’s alloy ingots still appear. I can also see Endergy’s alloy ingots by looking at the recipes for items that require them and by looking at the uses of an item used to craft one of them. They’re also perfectly craftable. They just don’t appear when searching for them in JEI.

![Endergy – Alloys not appearing in JEI](https://user-images.githubusercontent.com/34230933/57735285-5f792600-76a4-11e9-994c-47dacc463829.png)

#### What happens
Endergy’s alloy ingots don’t appear in JEI.

#### What I expected to happen
I expected Endergy’s alloy ingots to appear in JEI.

#### Steps to reproduce

1. Download EnderCore, Ender IO, Endergy, and Just Enough Items.
2. Search for “alloy ingot” in JEI.
3. Witness Endergy’s alloy ingots not appearing.

****

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2816
* **EnderCore:** 0.5.57
* **Ender IO:** 5.0.44
* **Ender IO Endergy:** 5.0.44
* **Just Enough Items:** 4.15.0.277
* **SpongeForge:** No
* **OptiFine:** No
* **Single-player and/or server:** Single-player, no server

**Comment by LumberWizard** [comment]
I have not been able to reproduce the issue, on Forge version 2838 and JEI version 279.

**Comment by Dimentive** [comment]
I already did; they’re not hidden in JEI.

**Comment by Dimentive** [comment]
I already did; they’re not hidden in JEI. It might be an issue with this particular Forge version (2816) or this particular JEI version (277). It could also be caused by one of the other mods that I have installed. I have no clue.

**Comment by mindforger** [comment]
Can you provide a modlist?

**Comment by Dimentive** [comment]
<details><summary>Mod list – Click to expand</summary>

Doesn’t include library mods.

* [Actually Additions](https://minecraft.curseforge.com/projects/actually-additions) [add-on: [Actually Baubles](https://minecraft.curseforge.com/projects/actually-baubles)]
* [Advanced Rocketry](https://minecraft.curseforge.com/projects/advanced-rocketry)
* [Applied Energistics 2](https://minecraft.curseforge.com/projects/applied-energistics-2) [add-ons: [AE2 Stuff](https://minecraft.curseforge.com/projects/ae2-stuff), [ExtraCells2](https://minecraft.curseforge.com/projects/extracells2) (add-on: [XCPatch](https://minecraft.curseforge.com/projects/xcpatch)), [ME Capability Adapter](https://minecraft.curseforge.com/projects/capability-adapter), [PackagedAuto](https://minecraft.curseforge.com/projects/packagedauto), [PlaneFix](https://minecraft.curseforge.com/projects/planefix), [Wireless Crafting Terminal](https://minecraft.curseforge.com/projects/wireless-crafting-terminal), [Thaumic Energistics](https://minecraft.curseforge.com/projects/thaumic-energistics)]
* [Compact Machines](https://minecraft.curseforge.com/projects/compact-machines)
* [Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution)
* [Ender IO](https://minecraft.curseforge.com/projects/ender-io) [add-ons: [Ender IO - Endergy](https://minecraft.curseforge.com/projects/ender-io-endergy), [Loot Capacitor Tooltips](https://minecraft.curseforge.com/projects/loot-capacitor-tooltips)]
* [Environmental Tech](https://minecraft.curseforge.com/projects/environmental-tech)
* [Ex Nihilo: Creatio](https://minecraft.curseforge.com/projects/ex-nihilo-creatio) [add-on: [Ex Compressum](https://minecraft.curseforge.com/projects/ex-compressum)]
* [Flux Networks](https://minecraft.curseforge.com/projects/flux-networks)
* [Forestry](https://minecraft.curseforge.com/projects/forestry) [add-ons: [Binnie’s Mods](https://minecraft.curseforge.com/projects/binnies-mods), [Career Bees](https://minecraft.curseforge.com/projects/career-bees), [Gendustry](https://minecraft.curseforge.com/projects/gendustry)]
* [Industrial Foregoing](https://minecraft.curseforge.com/projects/industrial-foregoing) [add-on: [Integration Foregoing](https://minecraft.curseforge.com/projects/integration-foregoing)]
* [Immersive Engineering](https://minecraft.curseforge.com/projects/immersive-engineering) [add-ons: [Alternating Flux](https://minecraft.curseforge.com/projects/alternating-flux), [Engineer’s Decor](https://minecraft.curseforge.com/projects/engineers-decor), [Engineer’s Doors](https://minecraft.curseforge.com/projects/engineers-doors), [IE Cloche Compat](https://minecraft.curseforge.com/projects/ie-cloche-compat), [Immersive Cables](https://minecraft.curseforge.com/projects/immersive-cables), [Immersive Petroleum](https://minecraft.curseforge.com/projects/immersive-petroleum), [Immersive Tech](https://minecraft.curseforge.com/projects/immersive-tech), [Industrial Wires](https://minecraft.curseforge.com/projects/industrial-wires)]
* [IndustrialCraft 2](https://minecraft.curseforge.com/projects/industrial-craft) [add-on: [Compact Solars](https://minecraft.curseforge.com/projects/compact-solars)]
* [Integrated Crafting](https://minecraft.curseforge.com/projects/integrated-crafting)
* [Integrated Dynamics](https://minecraft.curseforge.com/projects/integrated-dynamics)
* [Integrated Terminals](https://minecraft.curseforge.com/projects/integrated-terminals)
* [Integrated Tunnels](https://minecraft.curseforge.com/projects/integrated-tunnels)
* [Mekanism](https://minecraft.curseforge.com/projects/mekanism) [add-on: [Gas Conduits](https://minecraft.curseforge.com/projects/gas-conduits)]
* [Mekanism Generators](https://minecraft.curseforge.com/projects/mekanism-generators)
* [NuclearCraft](https://minecraft.curseforge.com/projects/nuclearcraft-mod)
* [OpenComputers](https://minecraft.curseforge.com/projects/opencomputers) [add-ons: [ActuallyComputers](https://minecraft.curseforge.com/projects/actuallycomputers), [OpenComputers Drivers for Tinkers Construct](https://minecraft.curseforge.com/projects/opencomputers-drivers-for-tinkers-construct), [RFTools Power / OC Integration](https://minecraft.curseforge.com/projects/rftools-power-oc-integration), [Thaumic Computers](https://minecraft.curseforge.com/projects/thaumic-computers)]
* [Portality](https://minecraft.curseforge.com/projects/portality)
* [Psi](https://minecraft.curseforge.com/projects/psi) [add-on: [Random PSIdeas](https://minecraft.curseforge.com/projects/random-psideas)]
* [Railcraft](https://minecraft.curseforge.com/projects/railcraft)
* [RFTools](https://minecraft.curseforge.com/projects/rftools) [add-ons: [RFTools Control](https://minecraft.curseforge.com/projects/rftools-control), [RFTools Dimensions](https://minecraft.curseforge.com/projects/rftools-dimensions), [RFTools Power](https://minecraft.curseforge.com/projects/rftools-power)]
* [Thermal Expansion](https://minecraft.curseforge.com/projects/thermalexpansion)
* [Thermal Dynamics](https://minecraft.curseforge.com/projects/thermal-dynamics)
* [Astral Sorcery](https://minecraft.curseforge.com/projects/astral-sorcery)
* [Blood Magic](https://minecraft.curseforge.com/projects/blood-magic) [add-ons: [Animus](https://minecraft.curseforge.com/projects/animus), [Blood Arsenal](https://minecraft.curseforge.com/projects/blood-arsenal)]
* [Botania](https://minecraft.curseforge.com/projects/botania) [add-on: [Botanic Additions](https://minecraft.curseforge.com/projects/botanic-additions)]
* [Embers Rekindled](https://minecraft.curseforge.com/projects/embers-rekindled) [add-on: [Soot](https://minecraft.curseforge.com/projects/soot)]
* [Thaumcraft](https://minecraft.curseforge.com/projects/thaumcraft) [add-ons: [Thaumic Augmentation](https://minecraft.curseforge.com/projects/thaumic-augmentation), [Thaumic Inventory Scanning](https://minecraft.curseforge.com/projects/thaumcraft-inventory-scanning), [Thaumic Periphery](https://minecraft.curseforge.com/projects/thaumic-periphery), [Thaumic Tinkerer](https://minecraft.curseforge.com/projects/thaumic-tinkerer)]
* [Reliquary v1.3](https://minecraft.curseforge.com/projects/reliquary-v1-3)
* [The Aether (1)](https://minecraft.curseforge.com/projects/the-aether)
* [The Twilight Forest](https://minecraft.curseforge.com/projects/the-twilight-forest)
* [Dense Metals](https://minecraft.curseforge.com/projects/dense-metals)
* [Netherending Ores](https://minecraft.curseforge.com/projects/netherending-ores)
* [Skygrid](https://minecraft.curseforge.com/projects/skygrid)
* [Bouncy Creepers](https://minecraft.curseforge.com/projects/bouncy-creepers)
* [ArchitectureCraft - ElytraDev Version](https://minecraft.curseforge.com/projects/architecturecraft-elytradev)
* [BiblioCraft](https://minecraft.curseforge.com/projects/bibliocraft)
* [ChineseWorkshop](https://minecraft.curseforge.com/projects/chineseworkshop)
* [Chisel](https://minecraft.curseforge.com/projects/chisel) [add-ons: [Cathedral](https://minecraft.curseforge.com/projects/cathedral), [Unlimited Chisel Works](https://minecraft.curseforge.com/projects/unlimited-chisel-works)]
* [Chisels & Bits](https://minecraft.curseforge.com/projects/chisels-bits) [add-on: [Extra Bit Manipulation](https://minecraft.curseforge.com/projects/extra-bit-manipulation)]
* [Environmental Materials](https://minecraft.curseforge.com/projects/environmental-materials)
* [Fancy Lamps](https://minecraft.curseforge.com/projects/fancy-lamps)
* [Flat Covered Blocks](https://minecraft.curseforge.com/projects/flat-colored-blocks)
* [LittleTiles](https://minecraft.curseforge.com/projects/littletiles)
* [MalisisBlocks](https://minecraft.curseforge.com/projects/malisisblocks)
* [Xtones](https://minecraft.curseforge.com/projects/xtones)
* [Cosmetic Armor Reworked](https://minecraft.curseforge.com/projects/cosmetic-armor-reworked)
* [Decocraft2](https://minecraft.curseforge.com/projects/decocraft2)
* [Display](https://minecraft.curseforge.com/projects/display)
* [Hats](https://minecraft.curseforge.com/projects/hats) [add-on: [Hat Stand](https://minecraft.curseforge.com/projects/hat-stand)]
* [More Cauldrons](https://minecraft.curseforge.com/projects/more-cauldrons)
* [Aquaculture](https://minecraft.curseforge.com/projects/aquaculture)
* [Bird’s Foods](https://minecraft.curseforge.com/projects/birds-foods)
* [Culinary Construct](https://minecraft.curseforge.com/projects/culinary-construct)
* [Pam’s HarvestCraft](https://minecraft.curseforge.com/projects/pams-harvestcraft)
* [VanillaFoodPantry Mod](https://minecraft.curseforge.com/projects/vanillafoodpantry-mod)
* [XL Food Pantry](https://minecraft.curseforge.com/projects/xl-food-mod)
* [Animal Crops](https://minecraft.curseforge.com/projects/animal-crops)
* [Farming for Blockheads](https://minecraft.curseforge.com/projects/farming-for-blockheads)
* [Mystical Agriculture](https://minecraft.curseforge.com/projects/mystical-agriculture) [add-on: [Mystical Agradditions](https://minecraft.curseforge.com/projects/mystical-agradditions)]
* [Roost](https://minecraft.curseforge.com/projects/roost)
* [Woot](https://minecraft.curseforge.com/projects/woot)
* [Akashic Tome](https://minecraft.curseforge.com/projects/akashic-tome)
* [Avaritia 1.1x](https://minecraft.curseforge.com/projects/avaritia-1-10)
* [Building Gadgets](https://minecraft.curseforge.com/projects/building-gadgets)
* [Ceramics](https://minecraft.curseforge.com/projects/ceramics)
* [Horse Tweaks](https://minecraft.curseforge.com/projects/horse-tweaks)
* [Mekanism Tools](https://minecraft.curseforge.com/projects/mekanism-tools)
* [More Buckets](https://minecraft.curseforge.com/projects/more-buckets)
* [Morph-o-Tool](https://minecraft.curseforge.com/projects/morph-o-tool)
* [Nature’s Compass](https://minecraft.curseforge.com/projects/natures-compass)
* [Not Enough Wands](https://minecraft.curseforge.com/projects/not-enough-wands)
* [Pipe Master 2000](https://minecraft.curseforge.com/projects/pipe-master-2000)
* [Redstone Arsenal](https://minecraft.curseforge.com/projects/redstone-arsenal)
* [Scannable](https://minecraft.curseforge.com/projects/scannable)
* [Thermal Cultivation](https://minecraft.curseforge.com/projects/thermal-cultivation)
* [Thermal Innovation](https://minecraft.curseforge.com/projects/thermal-innovation)
* [Tinkers’ Construct](https://minecraft.curseforge.com/projects/tinkers-construct) [add-ons: [Construct’s Armory](https://minecraft.curseforge.com/projects/constructs-armory), [Pewter](https://minecraft.curseforge.com/projects/pewter), [Tinkers’ Complement](https://minecraft.curseforge.com/projects/tinkers-complement)]
* [Demagnetize](https://minecraft.curseforge.com/projects/demagnetize)
* [Extra Rails](https://minecraft.curseforge.com/projects/extra-rails)
* [Slab Machines](https://minecraft.curseforge.com/projects/slab-machines)
* [Super Sound Muffler](https://minecraft.curseforge.com/projects/super-sound-muffler)
* [TorchMaster](https://minecraft.curseforge.com/projects/torchmaster)
* [Custom Backgrounds](https://minecraft.curseforge.com/projects/custom-backgrounds)
* [/dank/null](https://minecraft.curseforge.com/projects/dank-null)
* [Ender Storage 1.8+](https://minecraft.curseforge.com/projects/ender-storage-1-8)
* [MetalChests](https://minecraft.curseforge.com/projects/metalchests)
* [Storage Drawers](https://minecraft.curseforge.com/projects/storage-drawers) [add-on: [Storage Drawers Unlimited](https://minecraft.curseforge.com/projects/storage-drawers-unlimited)]
* [V0id’s Smart Backpacks](https://minecraft.curseforge.com/projects/v0ids-smart-backpacks)
* [RedstonePlusPlus](https://minecraft.curseforge.com/projects/redstoneplusplus)
* [Charm](https://minecraft.curseforge.com/projects/charm)
* [Cyclic](https://minecraft.curseforge.com/projects/cyclic)
* [Dark Utilities](https://minecraft.curseforge.com/projects/dark-utilities)
* [Extra Utilities 2](https://minecraft.curseforge.com/projects/extra-utilities)
* [Future MC](https://minecraft.curseforge.com/projects/future-mc)
* [Inspirations](https://minecraft.curseforge.com/projects/inspirations)
* [OpenBlocks](https://minecraft.curseforge.com/projects/openblocks)
* [Random Things](https://minecraft.curseforge.com/projects/random-things)
* [Rustic](https://minecraft.curseforge.com/projects/rustic)
* [Quark](https://minecraft.curseforge.com/projects/quark)
* [Chunk-Pregenerator](https://minecraft.curseforge.com/projects/chunkpregenerator)
* [Effortless Building](https://minecraft.curseforge.com/projects/effortless-building)
* [FTB Utilities](https://minecraft.curseforge.com/projects/ftb-utilities)
* [FTB Utilities: Backups](https://minecraft.curseforge.com/projects/ftb-utilities-backups)
* [MemoryTester](https://minecraft.curseforge.com/projects/memorytester)
* [Morph](https://minecraft.curseforge.com/projects/morph)
* [OldJavaWarning](https://minecraft.curseforge.com/projects/oldjavawarning)
* [Ore Excavation](https://minecraft.curseforge.com/projects/ore-excavation)
* [Schematica](https://minecraft.curseforge.com/projects/schematica)
* [AttributeFix](https://minecraft.curseforge.com/projects/attributefix)
* [Bad Wither No Cookie - Reloaded](https://minecraft.curseforge.com/projects/bad-wither-no-cookie-reloaded)
* [Better Invisibility](https://minecraft.curseforge.com/projects/better-invisibility)
* [Bow Infinity Fix](https://minecraft.curseforge.com/projects/bow-infinity-fix)
* [Client Tweaks](https://minecraft.curseforge.com/projects/client-tweaks)
* [Clumps](https://minecraft.curseforge.com/projects/clumps)
* [Colytra](https://minecraft.curseforge.com/projects/colytra)
* [Diet Hoppers](https://minecraft.curseforge.com/projects/diet-hoppers)
* [Dirt2Path](https://minecraft.curseforge.com/projects/dirt2path)
* [Fast Leaf Decay](https://minecraft.curseforge.com/projects/fast-leaf-decay)
* [Fence Jumper](https://minecraft.curseforge.com/projects/fence-jumper)
* [IKWID (I Know What I’m Doing)](https://minecraft.curseforge.com/projects/i-know-what-im-doing)
* [Infinity & Mending Unnerf](https://minecraft.curseforge.com/projects/infinity-mending-unnerf)
* [[SBM] Jukebox](https://minecraft.curseforge.com/projects/sbm-jukebox)
* [Just Sleep](https://minecraft.curseforge.com/projects/just-sleep)
* [KleeSlabs](https://minecraft.curseforge.com/projects/kleeslabs)
* [Lapis Stays in the Enchanting Table](https://minecraft.curseforge.com/projects/lapis-stays-in-the-enchanting-table)
* [Login Shield](https://minecraft.curseforge.com/projects/login-shield)
* [Mending Fix](https://minecraft.curseforge.com/projects/mending-fix)
* [NetherPortalFix](https://minecraft.curseforge.com/projects/netherportalfix)
* [No Mob Spawning on Trees](https://minecraft.curseforge.com/projects/no-mob-spawning-on-trees)
* [No Night Vision Flashing](https://minecraft.curseforge.com/projects/no-night-vision-flashing)
* [Pam’s Get All the Seeds!](https://minecraft.curseforge.com/projects/pams-get-all-the-seeds)
* [Pam’s Llama Milking](https://minecraft.curseforge.com/projects/pams-llama-milking)
* [PlayersDropHeads](https://minecraft.curseforge.com/projects/playersdropheads)
* [RandomTweaks](https://minecraft.curseforge.com/projects/randomtweaks)
* [SlimyBoyos](https://minecraft.curseforge.com/projects/slimyboyos)
* [SwingThroughGrass](https://minecraft.curseforge.com/projects/swingthroughgrass)
* [Trample Stopper](https://minecraft.curseforge.com/projects/trample-stopper)
* [UniDict](https://minecraft.curseforge.com/projects/unidict)
* [WAIM - What am I missing?](https://minecraft.curseforge.com/projects/waim-what-am-i-missing)
* [Wither Skeleton Tweaks](https://minecraft.curseforge.com/projects/wither-skeleton-tweaks)
* [Inventory Tweaks](https://minecraft.curseforge.com/projects/inventory-tweaks)
* [Mouse Tweaks](https://minecraft.curseforge.com/projects/mouse-tweaks)
* [Better Than Bunnies](https://minecraft.curseforge.com/projects/better-than-bunnies)
* [Better Than Llamas](https://minecraft.curseforge.com/projects/better-than-llamas)
* [Chunk Animator](https://minecraft.curseforge.com/projects/chunk-animator)
* [MAGE (Graphical Tweaks)](https://minecraft.curseforge.com/projects/mage)
* [Proportional Destruction Particles](https://minecraft.curseforge.com/projects/proportional-destruction-particles)
* [Visuals](https://minecraft.curseforge.com/projects/visuals)
* [AppleSkin](https://minecraft.curseforge.com/projects/appleskin)
* [Armor Chroma](https://minecraft.curseforge.com/projects/armor-chroma)
* [Better Advancements](https://minecraft.curseforge.com/projects/better-advancements)
* [Controlling](https://minecraft.curseforge.com/projects/controlling)
* [Crafting Tweaks](https://minecraft.curseforge.com/projects/crafting-tweaks)
* [EasierVillagerTrading](https://minecraft.curseforge.com/projects/easiervillagertrading)
* [Enchantment Descriptions](https://minecraft.curseforge.com/projects/enchantment-descriptions)
* [JourneyMap](https://minecraft.curseforge.com/projects/journeymap)
* [Just Enough Items (JEI)](https://minecraft.curseforge.com/projects/jei) [add-ons: [Block Drops (JEI Addon)](https://minecraft.curseforge.com/projects/block-drops-jei-addon), [Gendustry JEI Addon](https://minecraft.curseforge.com/projects/gendustry-jei-addon), [JEI Bees](https://minecraft.curseforge.com/projects/jei-bees), [Just Enough Energistics (JEE)](https://minecraft.curseforge.com/projects/just-enough-energistics-jee), [Just Enough HarvestCraft (JEHC)](https://minecraft.curseforge.com/projects/just-enough-harvestcraft), [Just Enough Pattern Banners](https://minecraft.curseforge.com/projects/just-enough-pattern-banners), [Just Enough Petroleum](https://minecraft.curseforge.com/projects/just-enough-petroleum), [Just Enough Resources (JER)](https://minecraft.curseforge.com/projects/just-enough-resources-jer), [Just Enough Throwing In Fluids (JETIF)](https://minecraft.curseforge.com/projects/jetif), [JEI Villagers](https://minecraft.curseforge.com/projects/jei-villagers), [Thaumic JEI](https://minecraft.curseforge.com/projects/thaumic-jei), [Tinker’s JEI](https://minecraft.curseforge.com/projects/tinkers-jei)]
* [Mod Name Tooltip](https://minecraft.curseforge.com/projects/mod-name-tooltip)
* [More Overlays](https://minecraft.curseforge.com/projects/more-overlays)
* [Neat](https://minecraft.curseforge.com/projects/neat)
* [Notes](https://minecraft.curseforge.com/projects/notes)
* [The One Probe](https://minecraft.curseforge.com/projects/the-one-probe)
* [TipTheScales](https://minecraft.curseforge.com/projects/tipthescales)
* [ToroHealth Damage Indicators](https://minecraft.curseforge.com/projects/torohealth-damage-indicators)
* [AntiGhost](https://minecraft.curseforge.com/projects/antighost)
* [Calm Down Zombie Guy](https://minecraft.curseforge.com/projects/calm-down-zombie-guy)
* [RandomPatches](https://minecraft.curseforge.com/projects/randompatches)
* [VanillaFix](https://minecraft.curseforge.com/projects/vanillafix)
* [AI Improvements](https://minecraft.curseforge.com/projects/ai-improvements)
* [BetterFps](https://minecraft.curseforge.com/projects/betterfps)
* [Born in a Barn](https://minecraft.curseforge.com/projects/born-in-a-barn)
* [FastFurnace](https://minecraft.curseforge.com/projects/fastfurnace)
* [FastWorkbench](https://minecraft.curseforge.com/projects/fastworkbench)
* [FoamFix](https://minecraft.curseforge.com/projects/foamfix-for-minecraft)
* [FPS Reducer](https://minecraft.curseforge.com/projects/fps-reducer)
* [Phosphor](https://minecraft.curseforge.com/projects/phosphor)
* [Placebo](https://minecraft.curseforge.com/projects/placebo)
* [Surge](https://minecraft.curseforge.com/projects/surge)
* [TexFix](https://minecraft.curseforge.com/projects/texfix)
* [Unloader](https://minecraft.curseforge.com/projects/unloader)
* [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker) [add-on: [ContentTweaker](https://minecraft.curseforge.com/projects/contenttweaker)]
* [Custom Main Menu](https://minecraft.curseforge.com/projects/custom-main-menu)
* [Anger Management](https://minecraft.curseforge.com/projects/anger-management)
* [Baubles](https://minecraft.curseforge.com/projects/baubles)
* [Cooking for Blockheads](https://minecraft.curseforge.com/projects/cooking-for-blockheads)
* [ExtraDiscs](https://minecraft.curseforge.com/projects/extradiscs)
* [FTB Quests](https://minecraft.curseforge.com/projects/ftb-quests)
* [Hunger Presistence](https://minecraft.curseforge.com/projects/hunger-persistence)
* [It’s the little things](https://minecraft.curseforge.com/projects/its-the-little-things)
* [JAOPCA](https://minecraft.curseforge.com/projects/jaopca) [add-ons: [JAOPCAAgriculture](https://minecraft.curseforge.com/projects/jaopcaagriculture), [JAOPCASingularities](https://minecraft.curseforge.com/projects/jaopcasingularities)]
* [Spice of Life: Carrot Edition](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition)
* [Tomb Many Graves 2](https://minecraft.curseforge.com/projects/tomb-many-graves-2)
</details>

**Comment by HenryLoenwind** [comment]
Would you be willing to test with a development build of Ender IO? If so, I'd make one that prints information on stuff we hide in JEI. That'd allow us to determine if there's something wrong on our end, or if we need to find the needle in that haystack of mods.

**Comment by Dimentive** [comment]
Sure.

**Comment by HenryLoenwind** [comment]
Ok, I added the messages. When starting the game they will show up in the logfile shortly before the main menu is shown.

This is how your missing alloys look when Endergy is not installed:

```
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@0
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@0
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@1
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@1
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@2
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@2
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@3
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@3
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@4
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@4
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@5
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@5
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@6
[00:00:58] [main/WARN] [enderio]: Hiding ingredient in JEI: 1xitem.item_alloy_endergy_nugget@6
```

You can get the test version at https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/963/ in half an hour or so.

**Comment by HenryLoenwind** [comment]
PS: I copied the lines for the nugget by accident, shouldn't make a difference, nuggets, ingot, blocks and grinding balls are handled together.
