### ISSUE TITLE
Ender IO’s JEI plugin frequently causing the game to freeze

### ISSUE THREAD

**Issue by Dimentive** [SleepyTrousers/EnderIO#5130]
#### Issue description
Quite frequently, when I try to check the recipe or uses of an item in [JEI](https://minecraft.curseforge.com/projects/jei), even if that item is not added by Ender IO, my game freezes for upwards of five seconds before anything happens. When it freezes, I’m unable to do anything.

Relevant part of the log:

    [19:49:14] [Client thread/WARN] [jei]: Recipe registry plugin is slow, took 51.93 ms. class crazypants.enderio.base.integration.jei.DarkSteelUpgradeRecipeCategory$1
    [19:49:24] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 7799ms behind, skipping 155 tick(s)

#### What happens
JEI often freezes because of Ender IO’s JEI plugin.

#### What I expected to happen
I expected JEI not to freeze.

#### Steps to reproduce
1. Download EnderCore, Ender IO, and Just Enough Items.
2. Look at recipes and uses for items in JEI for a while.
3. Witness your game freezing for several seconds at a time at seemingly random times.

****

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2816
* **EnderCore:** 0.5.57
* **Ender IO:** 5.0.44
* **Just Enough Items:** 4.15.0.277
* **SpongeForge:** No
* **OptiFine:** No
* **Single-player and/or server:** Single-player, no server

**Comment by LumberWizard** [comment]
The log snippet suggests the plugin from EnderIO took a twentieth of a second. I assume the issue is the amount of mods you have, all their plugins, and the amount of recipes registered. I have not been able to reproduce that freeze in an instance with just JEI and EIO, nor have I experienced such an issue in an instance with around 200 mods (including child mods), so it is probably a different mod entirely, or it might just be your environment (Java version, arguments, hardware, etc.).

**Comment by HenryLoenwind** [comment]
Let me repeat what I said in the other ticket, just to keep things together:

"world can't keep up skipping ticks!" means that your server thread is running slow, "Recipe registry plugin is slow" means that your client thread is running slow. Unless you have a single-core CPU, those two threads run independently, so this seems to be more an issue of something that affects both causing an issue you only see because that's the only places that do performance measurements.

Looking at it again, even more confirms that. The recipe plugin takes 51 ms (1/20 of a second) on the client and then the server thread stalls for nearly 8 seconds. A recipe plugin has no means to stall the server, nothing on the client has those. The worst it could do is to get the client kicked for being unresponsive.

And let me stress something else again: There are very, very, very few places in the game where there is time measuring and logging. From vanilla there are 2 on the server (the one you get for the tick and the watchdog that kills the server after 60 seconds) and none on the client. Forge adds detailed time logging during the startup of the game, but nothing while it is running. JEI measures recipe plugins. And that's all I know of.

**Comment by Xetaxheb** [comment]
¯\_(ツ)_/¯ as stated previously, I get this on most decent sized packs with enderio installed, and can resolve the very obvious and clear issue by removing enderio entirely.
It doesn't touch the fps of my game, just the random nuking of 5-20 seconds of freezing; with the skipping ticks message only ever occurring during this.
And again, it's not "rare" or "unusual", it generally happens probably once every 10 minutes at minimum (NOT consistent, just a baseline and not tied to time at all) but only ever will trigger while doing something with JEI while enderio is installed.

**Comment by mindforger** [comment]
Do you have a modlist or can you provide a forced crashlog by holding f3 + c while ingame to get more details

**Comment by Dimentive** [comment]
It’s a custom pack. Here’s my mod list:

<details><summary>Mod list – Click to expand</summary>

Doesn’t include library mods.

* [Actually Additions](https://minecraft.curseforge.com/projects/actually-additions) [add-on: [Actually Baubles](https://minecraft.curseforge.com/projects/actually-baubles)]
* [Advanced Rocketry](https://minecraft.curseforge.com/projects/advanced-rocketry)
* [Applied Energistics 2](https://minecraft.curseforge.com/projects/applied-energistics-2) [add-ons: [AE2 Stuff](https://minecraft.curseforge.com/projects/ae2-stuff), [ExtraCells2](https://minecraft.curseforge.com/projects/extracells2) (add-on: [XCPatch](https://minecraft.curseforge.com/projects/xcpatch)), [ME Capability Adapter](https://minecraft.curseforge.com/projects/capability-adapter), [PackagedAuto](https://minecraft.curseforge.com/projects/packagedauto), [PlaneFix](https://minecraft.curseforge.com/projects/planefix), [Wireless Crafting Terminal](https://minecraft.curseforge.com/projects/wireless-crafting-terminal), [Thaumic Energistics](https://minecraft.curseforge.com/projects/thaumic-energistics)]
* [Compact Machines](https://minecraft.curseforge.com/projects/compact-machines)
* [Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution)
* [Ender IO](https://minecraft.curseforge.com/projects/ender-io) [add-ons: [Ender IO - Endergy](https://minecraft.curseforge.com/projects/ender-io-endergy), [Loot Capacitor Tooltips](https://minecraft.curseforge.com/projects/loot-capacitor-tooltips)]
* [Environmental Tech](https://minecraft.curseforge.com/projects/environmental-tech)
* [Ex Nihilo: Creatio](https://minecraft.curseforge.com/projects/ex-nihilo-creatio) [add-on: [Ex Compressum](https://minecraft.curseforge.com/projects/ex-compressum)]
* [Flux Networks](https://minecraft.curseforge.com/projects/flux-networks)
* [Forestry](https://minecraft.curseforge.com/projects/forestry) [add-ons: [Binnie’s Mods](https://minecraft.curseforge.com/projects/binnies-mods), [Career Bees](https://minecraft.curseforge.com/projects/career-bees), [Gendustry](https://minecraft.curseforge.com/projects/gendustry)]
* [Industrial Foregoing](https://minecraft.curseforge.com/projects/industrial-foregoing) [add-on: [Integration Foregoing](https://minecraft.curseforge.com/projects/integration-foregoing)]
* [Immersive Engineering](https://minecraft.curseforge.com/projects/immersive-engineering) [add-ons: [Alternating Flux](https://minecraft.curseforge.com/projects/alternating-flux), [Engineer’s Decor](https://minecraft.curseforge.com/projects/engineers-decor), [Engineer’s Doors](https://minecraft.curseforge.com/projects/engineers-doors), [IE Cloche Compat](https://minecraft.curseforge.com/projects/ie-cloche-compat), [Immersive Cables](https://minecraft.curseforge.com/projects/immersive-cables), [Immersive Petroleum](https://minecraft.curseforge.com/projects/immersive-petroleum), [Immersive Tech](https://minecraft.curseforge.com/projects/immersive-tech), [Industrial Wires](https://minecraft.curseforge.com/projects/industrial-wires)]
* [IndustrialCraft 2](https://minecraft.curseforge.com/projects/industrial-craft) [add-on: [Compact Solars](https://minecraft.curseforge.com/projects/compact-solars)]
* [Integrated Crafting](https://minecraft.curseforge.com/projects/integrated-crafting)
* [Integrated Dynamics](https://minecraft.curseforge.com/projects/integrated-dynamics)
* [Integrated Terminals](https://minecraft.curseforge.com/projects/integrated-terminals)
* [Integrated Tunnels](https://minecraft.curseforge.com/projects/integrated-tunnels)
* [Mekanism](https://minecraft.curseforge.com/projects/mekanism) [add-on: [Gas Conduits](https://minecraft.curseforge.com/projects/gas-conduits)]
* [Mekanism Generators](https://minecraft.curseforge.com/projects/mekanism-generators)
* [NuclearCraft](https://minecraft.curseforge.com/projects/nuclearcraft-mod)
* [OpenComputers](https://minecraft.curseforge.com/projects/opencomputers) [add-ons: [ActuallyComputers](https://minecraft.curseforge.com/projects/actuallycomputers), [OpenComputers Drivers for Tinkers Construct](https://minecraft.curseforge.com/projects/opencomputers-drivers-for-tinkers-construct), [RFTools Power / OC Integration](https://minecraft.curseforge.com/projects/rftools-power-oc-integration), [Thaumic Computers](https://minecraft.curseforge.com/projects/thaumic-computers)]
* [Portality](https://minecraft.curseforge.com/projects/portality)
* [Psi](https://minecraft.curseforge.com/projects/psi) [add-on: [Random PSIdeas](https://minecraft.curseforge.com/projects/random-psideas)]
* [Railcraft](https://minecraft.curseforge.com/projects/railcraft)
* [RFTools](https://minecraft.curseforge.com/projects/rftools) [add-ons: [RFTools Control](https://minecraft.curseforge.com/projects/rftools-control), [RFTools Dimensions](https://minecraft.curseforge.com/projects/rftools-dimensions), [RFTools Power](https://minecraft.curseforge.com/projects/rftools-power)]
* [Thermal Expansion](https://minecraft.curseforge.com/projects/thermalexpansion)
* [Thermal Dynamics](https://minecraft.curseforge.com/projects/thermal-dynamics)
* [Astral Sorcery](https://minecraft.curseforge.com/projects/astral-sorcery)
* [Blood Magic](https://minecraft.curseforge.com/projects/blood-magic) [add-ons: [Animus](https://minecraft.curseforge.com/projects/animus), [Blood Arsenal](https://minecraft.curseforge.com/projects/blood-arsenal)]
* [Botania](https://minecraft.curseforge.com/projects/botania) [add-on: [Botanic Additions](https://minecraft.curseforge.com/projects/botanic-additions)]
* [Embers Rekindled](https://minecraft.curseforge.com/projects/embers-rekindled) [add-on: [Soot](https://minecraft.curseforge.com/projects/soot)]
* [Thaumcraft](https://minecraft.curseforge.com/projects/thaumcraft) [add-ons: [Thaumic Augmentation](https://minecraft.curseforge.com/projects/thaumic-augmentation), [Thaumic Inventory Scanning](https://minecraft.curseforge.com/projects/thaumcraft-inventory-scanning), [Thaumic Periphery](https://minecraft.curseforge.com/projects/thaumic-periphery), [Thaumic Tinkerer](https://minecraft.curseforge.com/projects/thaumic-tinkerer)]
* [Reliquary v1.3](https://minecraft.curseforge.com/projects/reliquary-v1-3)
* [The Aether (1)](https://minecraft.curseforge.com/projects/the-aether)
* [The Twilight Forest](https://minecraft.curseforge.com/projects/the-twilight-forest)
* [Dense Metals](https://minecraft.curseforge.com/projects/dense-metals)
* [Netherending Ores](https://minecraft.curseforge.com/projects/netherending-ores)
* [Skygrid](https://minecraft.curseforge.com/projects/skygrid)
* [Bouncy Creepers](https://minecraft.curseforge.com/projects/bouncy-creepers)
* [ArchitectureCraft - ElytraDev Version](https://minecraft.curseforge.com/projects/architecturecraft-elytradev)
* [BiblioCraft](https://minecraft.curseforge.com/projects/bibliocraft)
* [ChineseWorkshop](https://minecraft.curseforge.com/projects/chineseworkshop)
* [Chisel](https://minecraft.curseforge.com/projects/chisel) [add-ons: [Cathedral](https://minecraft.curseforge.com/projects/cathedral), [Unlimited Chisel Works](https://minecraft.curseforge.com/projects/unlimited-chisel-works)]
* [Chisels & Bits](https://minecraft.curseforge.com/projects/chisels-bits) [add-on: [Extra Bit Manipulation](https://minecraft.curseforge.com/projects/extra-bit-manipulation)]
* [Environmental Materials](https://minecraft.curseforge.com/projects/environmental-materials)
* [Fancy Lamps](https://minecraft.curseforge.com/projects/fancy-lamps)
* [Flat Covered Blocks](https://minecraft.curseforge.com/projects/flat-colored-blocks)
* [LittleTiles](https://minecraft.curseforge.com/projects/littletiles)
* [MalisisBlocks](https://minecraft.curseforge.com/projects/malisisblocks)
* [Xtones](https://minecraft.curseforge.com/projects/xtones)
* [Cosmetic Armor Reworked](https://minecraft.curseforge.com/projects/cosmetic-armor-reworked)
* [Decocraft2](https://minecraft.curseforge.com/projects/decocraft2)
* [Display](https://minecraft.curseforge.com/projects/display)
* [Hats](https://minecraft.curseforge.com/projects/hats) [add-on: [Hat Stand](https://minecraft.curseforge.com/projects/hat-stand)]
* [More Cauldrons](https://minecraft.curseforge.com/projects/more-cauldrons)
* [Aquaculture](https://minecraft.curseforge.com/projects/aquaculture)
* [Bird’s Foods](https://minecraft.curseforge.com/projects/birds-foods)
* [Culinary Construct](https://minecraft.curseforge.com/projects/culinary-construct)
* [Pam’s HarvestCraft](https://minecraft.curseforge.com/projects/pams-harvestcraft)
* [VanillaFoodPantry Mod](https://minecraft.curseforge.com/projects/vanillafoodpantry-mod)
* [XL Food Pantry](https://minecraft.curseforge.com/projects/xl-food-mod)
* [Animal Crops](https://minecraft.curseforge.com/projects/animal-crops)
* [Farming for Blockheads](https://minecraft.curseforge.com/projects/farming-for-blockheads)
* [Mystical Agriculture](https://minecraft.curseforge.com/projects/mystical-agriculture) [add-on: [Mystical Agradditions](https://minecraft.curseforge.com/projects/mystical-agradditions)]
* [Roost](https://minecraft.curseforge.com/projects/roost)
* [Woot](https://minecraft.curseforge.com/projects/woot)
* [Akashic Tome](https://minecraft.curseforge.com/projects/akashic-tome)
* [Avaritia 1.1x](https://minecraft.curseforge.com/projects/avaritia-1-10)
* [Building Gadgets](https://minecraft.curseforge.com/projects/building-gadgets)
* [Ceramics](https://minecraft.curseforge.com/projects/ceramics)
* [Horse Tweaks](https://minecraft.curseforge.com/projects/horse-tweaks)
* [Mekanism Tools](https://minecraft.curseforge.com/projects/mekanism-tools)
* [More Buckets](https://minecraft.curseforge.com/projects/more-buckets)
* [Morph-o-Tool](https://minecraft.curseforge.com/projects/morph-o-tool)
* [Nature’s Compass](https://minecraft.curseforge.com/projects/natures-compass)
* [Not Enough Wands](https://minecraft.curseforge.com/projects/not-enough-wands)
* [Pipe Master 2000](https://minecraft.curseforge.com/projects/pipe-master-2000)
* [Redstone Arsenal](https://minecraft.curseforge.com/projects/redstone-arsenal)
* [Scannable](https://minecraft.curseforge.com/projects/scannable)
* [Thermal Cultivation](https://minecraft.curseforge.com/projects/thermal-cultivation)
* [Thermal Innovation](https://minecraft.curseforge.com/projects/thermal-innovation)
* [Tinkers’ Construct](https://minecraft.curseforge.com/projects/tinkers-construct) [add-ons: [Construct’s Armory](https://minecraft.curseforge.com/projects/constructs-armory), [Pewter](https://minecraft.curseforge.com/projects/pewter), [Tinkers’ Complement](https://minecraft.curseforge.com/projects/tinkers-complement)]
* [Demagnetize](https://minecraft.curseforge.com/projects/demagnetize)
* [Extra Rails](https://minecraft.curseforge.com/projects/extra-rails)
* [Slab Machines](https://minecraft.curseforge.com/projects/slab-machines)
* [Super Sound Muffler](https://minecraft.curseforge.com/projects/super-sound-muffler)
* [TorchMaster](https://minecraft.curseforge.com/projects/torchmaster)
* [Custom Backgrounds](https://minecraft.curseforge.com/projects/custom-backgrounds)
* [/dank/null](https://minecraft.curseforge.com/projects/dank-null)
* [Ender Storage 1.8+](https://minecraft.curseforge.com/projects/ender-storage-1-8)
* [MetalChests](https://minecraft.curseforge.com/projects/metalchests)
* [Storage Drawers](https://minecraft.curseforge.com/projects/storage-drawers) [add-on: [Storage Drawers Unlimited](https://minecraft.curseforge.com/projects/storage-drawers-unlimited)]
* [V0id’s Smart Backpacks](https://minecraft.curseforge.com/projects/v0ids-smart-backpacks)
* [RedstonePlusPlus](https://minecraft.curseforge.com/projects/redstoneplusplus)
* [Charm](https://minecraft.curseforge.com/projects/charm)
* [Cyclic](https://minecraft.curseforge.com/projects/cyclic)
* [Dark Utilities](https://minecraft.curseforge.com/projects/dark-utilities)
* [Extra Utilities 2](https://minecraft.curseforge.com/projects/extra-utilities)
* [Future MC](https://minecraft.curseforge.com/projects/future-mc)
* [Inspirations](https://minecraft.curseforge.com/projects/inspirations)
* [OpenBlocks](https://minecraft.curseforge.com/projects/openblocks)
* [Random Things](https://minecraft.curseforge.com/projects/random-things)
* [Rustic](https://minecraft.curseforge.com/projects/rustic)
* [Quark](https://minecraft.curseforge.com/projects/quark)
* [Chunk-Pregenerator](https://minecraft.curseforge.com/projects/chunkpregenerator)
* [Effortless Building](https://minecraft.curseforge.com/projects/effortless-building)
* [FTB Utilities](https://minecraft.curseforge.com/projects/ftb-utilities)
* [FTB Utilities: Backups](https://minecraft.curseforge.com/projects/ftb-utilities-backups)
* [MemoryTester](https://minecraft.curseforge.com/projects/memorytester)
* [Morph](https://minecraft.curseforge.com/projects/morph)
* [OldJavaWarning](https://minecraft.curseforge.com/projects/oldjavawarning)
* [Ore Excavation](https://minecraft.curseforge.com/projects/ore-excavation)
* [Schematica](https://minecraft.curseforge.com/projects/schematica)
* [AttributeFix](https://minecraft.curseforge.com/projects/attributefix)
* [Bad Wither No Cookie - Reloaded](https://minecraft.curseforge.com/projects/bad-wither-no-cookie-reloaded)
* [Better Invisibility](https://minecraft.curseforge.com/projects/better-invisibility)
* [Bow Infinity Fix](https://minecraft.curseforge.com/projects/bow-infinity-fix)
* [Client Tweaks](https://minecraft.curseforge.com/projects/client-tweaks)
* [Clumps](https://minecraft.curseforge.com/projects/clumps)
* [Colytra](https://minecraft.curseforge.com/projects/colytra)
* [Diet Hoppers](https://minecraft.curseforge.com/projects/diet-hoppers)
* [Dirt2Path](https://minecraft.curseforge.com/projects/dirt2path)
* [Fast Leaf Decay](https://minecraft.curseforge.com/projects/fast-leaf-decay)
* [Fence Jumper](https://minecraft.curseforge.com/projects/fence-jumper)
* [IKWID (I Know What I’m Doing)](https://minecraft.curseforge.com/projects/i-know-what-im-doing)
* [Infinity & Mending Unnerf](https://minecraft.curseforge.com/projects/infinity-mending-unnerf)
* [[SBM] Jukebox](https://minecraft.curseforge.com/projects/sbm-jukebox)
* [Just Sleep](https://minecraft.curseforge.com/projects/just-sleep)
* [KleeSlabs](https://minecraft.curseforge.com/projects/kleeslabs)
* [Lapis Stays in the Enchanting Table](https://minecraft.curseforge.com/projects/lapis-stays-in-the-enchanting-table)
* [Login Shield](https://minecraft.curseforge.com/projects/login-shield)
* [Mending Fix](https://minecraft.curseforge.com/projects/mending-fix)
* [NetherPortalFix](https://minecraft.curseforge.com/projects/netherportalfix)
* [No Mob Spawning on Trees](https://minecraft.curseforge.com/projects/no-mob-spawning-on-trees)
* [No Night Vision Flashing](https://minecraft.curseforge.com/projects/no-night-vision-flashing)
* [Pam’s Get All the Seeds!](https://minecraft.curseforge.com/projects/pams-get-all-the-seeds)
* [Pam’s Llama Milking](https://minecraft.curseforge.com/projects/pams-llama-milking)
* [PlayersDropHeads](https://minecraft.curseforge.com/projects/playersdropheads)
* [RandomTweaks](https://minecraft.curseforge.com/projects/randomtweaks)
* [SlimyBoyos](https://minecraft.curseforge.com/projects/slimyboyos)
* [SwingThroughGrass](https://minecraft.curseforge.com/projects/swingthroughgrass)
* [Trample Stopper](https://minecraft.curseforge.com/projects/trample-stopper)
* [UniDict](https://minecraft.curseforge.com/projects/unidict)
* [WAIM - What am I missing?](https://minecraft.curseforge.com/projects/waim-what-am-i-missing)
* [Wither Skeleton Tweaks](https://minecraft.curseforge.com/projects/wither-skeleton-tweaks)
* [Inventory Tweaks](https://minecraft.curseforge.com/projects/inventory-tweaks)
* [Mouse Tweaks](https://minecraft.curseforge.com/projects/mouse-tweaks)
* [Better Than Bunnies](https://minecraft.curseforge.com/projects/better-than-bunnies)
* [Better Than Llamas](https://minecraft.curseforge.com/projects/better-than-llamas)
* [Chunk Animator](https://minecraft.curseforge.com/projects/chunk-animator)
* [MAGE (Graphical Tweaks)](https://minecraft.curseforge.com/projects/mage)
* [Proportional Destruction Particles](https://minecraft.curseforge.com/projects/proportional-destruction-particles)
* [Visuals](https://minecraft.curseforge.com/projects/visuals)
* [AppleSkin](https://minecraft.curseforge.com/projects/appleskin)
* [Armor Chroma](https://minecraft.curseforge.com/projects/armor-chroma)
* [Better Advancements](https://minecraft.curseforge.com/projects/better-advancements)
* [Controlling](https://minecraft.curseforge.com/projects/controlling)
* [Crafting Tweaks](https://minecraft.curseforge.com/projects/crafting-tweaks)
* [EasierVillagerTrading](https://minecraft.curseforge.com/projects/easiervillagertrading)
* [Enchantment Descriptions](https://minecraft.curseforge.com/projects/enchantment-descriptions)
* [JourneyMap](https://minecraft.curseforge.com/projects/journeymap)
* [Just Enough Items (JEI)](https://minecraft.curseforge.com/projects/jei) [add-ons: [Block Drops (JEI Addon)](https://minecraft.curseforge.com/projects/block-drops-jei-addon), [Gendustry JEI Addon](https://minecraft.curseforge.com/projects/gendustry-jei-addon), [JEI Bees](https://minecraft.curseforge.com/projects/jei-bees), [Just Enough Energistics (JEE)](https://minecraft.curseforge.com/projects/just-enough-energistics-jee), [Just Enough HarvestCraft (JEHC)](https://minecraft.curseforge.com/projects/just-enough-harvestcraft), [Just Enough Pattern Banners](https://minecraft.curseforge.com/projects/just-enough-pattern-banners), [Just Enough Petroleum](https://minecraft.curseforge.com/projects/just-enough-petroleum), [Just Enough Resources (JER)](https://minecraft.curseforge.com/projects/just-enough-resources-jer), [Just Enough Throwing In Fluids (JETIF)](https://minecraft.curseforge.com/projects/jetif), [JEI Villagers](https://minecraft.curseforge.com/projects/jei-villagers), [Thaumic JEI](https://minecraft.curseforge.com/projects/thaumic-jei), [Tinker’s JEI](https://minecraft.curseforge.com/projects/tinkers-jei)]
* [Mod Name Tooltip](https://minecraft.curseforge.com/projects/mod-name-tooltip)
* [More Overlays](https://minecraft.curseforge.com/projects/more-overlays)
* [Neat](https://minecraft.curseforge.com/projects/neat)
* [Notes](https://minecraft.curseforge.com/projects/notes)
* [The One Probe](https://minecraft.curseforge.com/projects/the-one-probe)
* [TipTheScales](https://minecraft.curseforge.com/projects/tipthescales)
* [ToroHealth Damage Indicators](https://minecraft.curseforge.com/projects/torohealth-damage-indicators)
* [AntiGhost](https://minecraft.curseforge.com/projects/antighost)
* [Calm Down Zombie Guy](https://minecraft.curseforge.com/projects/calm-down-zombie-guy)
* [RandomPatches](https://minecraft.curseforge.com/projects/randompatches)
* [VanillaFix](https://minecraft.curseforge.com/projects/vanillafix)
* [AI Improvements](https://minecraft.curseforge.com/projects/ai-improvements)
* [BetterFps](https://minecraft.curseforge.com/projects/betterfps)
* [Born in a Barn](https://minecraft.curseforge.com/projects/born-in-a-barn)
* [FastFurnace](https://minecraft.curseforge.com/projects/fastfurnace)
* [FastWorkbench](https://minecraft.curseforge.com/projects/fastworkbench)
* [FoamFix](https://minecraft.curseforge.com/projects/foamfix-for-minecraft)
* [FPS Reducer](https://minecraft.curseforge.com/projects/fps-reducer)
* [Phosphor](https://minecraft.curseforge.com/projects/phosphor)
* [Placebo](https://minecraft.curseforge.com/projects/placebo)
* [Surge](https://minecraft.curseforge.com/projects/surge)
* [TexFix](https://minecraft.curseforge.com/projects/texfix)
* [Unloader](https://minecraft.curseforge.com/projects/unloader)
* [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker) [add-on: [ContentTweaker](https://minecraft.curseforge.com/projects/contenttweaker)]
* [Custom Main Menu](https://minecraft.curseforge.com/projects/custom-main-menu)
* [Anger Management](https://minecraft.curseforge.com/projects/anger-management)
* [Baubles](https://minecraft.curseforge.com/projects/baubles)
* [Cooking for Blockheads](https://minecraft.curseforge.com/projects/cooking-for-blockheads)
* [ExtraDiscs](https://minecraft.curseforge.com/projects/extradiscs)
* [FTB Quests](https://minecraft.curseforge.com/projects/ftb-quests)
* [Hunger Presistence](https://minecraft.curseforge.com/projects/hunger-persistence)
* [It’s the little things](https://minecraft.curseforge.com/projects/its-the-little-things)
* [JAOPCA](https://minecraft.curseforge.com/projects/jaopca) [add-ons: [JAOPCAAgriculture](https://minecraft.curseforge.com/projects/jaopcaagriculture), [JAOPCASingularities](https://minecraft.curseforge.com/projects/jaopcasingularities)]
* [Spice of Life: Carrot Edition](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition)
* [Tomb Many Graves 2](https://minecraft.curseforge.com/projects/tomb-many-graves-2)
</details>

However, this also happens in modpacks I’ve played, such as [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) and [Enigmatica 2: Expert](https://minecraft.curseforge.com/projects/enigmatica2expert). But the freezes aren’t as long in those modpacks, and they don’t happen as frequently, which is probably because they have much fewer mods than my custom modpack.

**Comment by mindforger** [comment]
>Doesn’t include library mods

i kind of wanted to know what optimizing mods are used so include them too please

i suspect a buildup of orphaned data causing high GC spikes and maybe some optimizing mod is provoking this

best bet would be if you can narrow down the modpack as much as possible to get a test setup to compare with

Henry said
>A recipe plugin has no means to stall the server

is fundamentally right on a direct approach, but if it leaves many orphaned objects (i don't mean leaks by the way) in the memory, the GC may take quite a while to recover the memory (hard GC may not be visible as it stalls the whole application)

**Comment by Dimentive** [comment]
Optimizing mods? The list does include any performance-improvement mods.

I can create a list of the library mods, but that’ll take a while. The fact that it also happens in Engimatica 2 and Enigmatica 2: Expert means that you can just look at their mod lists, though. This isn’t caused by any of the mods that are _only_ in my custom modpack.

**Comment by mindforger** [comment]
oh .. my fault i havent seen them in my first stroll through the list

**Comment by ChapperNi** [comment]
My friend is also getting this error in his log, its the last error and his game freezes up every time.

**Comment by selectL0L** [comment]
I had the exact same issue but I only noticed it when I went to punch a chicken because I don't have JEI installed and after I punched the chicken it time skipped through its jump, I thought it was something from Opti fine so I put all the performance setting down to as low as they could go and I still got the time skipping chicken jump so I removed Opti fine and it still happened but by a stroke of luck I decided to lower my render distance and boom problem fixed so I can reproduce your EXACT problem with JEI after spending a good amount of time messing around with the mods you have and I can safely say that for me reducing the render distance fixed the problem

**Comment by mindforger** [comment]
hm, funny idea, can you change your UI scale for testing please

so that JEI a) displays as much as possible items and b) as few as items as possible 

and then try again the render distance thing?! 

i want to check if there is a bias based on how many things get rendered/displayed (just to see if it maybe a general memory/GC issue) .. 

sorry for taking over the issue for random guesses, but i am having a lot of issues with ram/GC spikes in 1.12 on my own, but not that heavy and trying out myself stuff but without decend effect, though i can say changing the render distance did have an impact for me as well

**Comment by selectL0L** [comment]
okay after changing the scale and testing multiple times the render distance did reduce lag inside of JEI when looking for items and I had no freezes at all however on the smallest UI scale with alot of items showing I did see more lag however it wasn't very perceivable so I don't think its that much of a difference however I also noticed that the longer the render distance the more times the in game clock becomes out of sync and drops ticks but the less time per desync whereas on slightly lower I would simply freeze and skip at least 400 ticks however on render distance 22 (Opti fine setting 22 not base Minecraft) I did not lag at all and I also did the chicken punch test and all 3 chickens flew perfectly 1 after another that's bearing in mind that I do have an i5-4460 (slightly overclocked but didn't make much of a difference anyway since its SOOOOO old) paired with 16GB's of DDR3-1660 and I have 12 GB's allocated to Minecraft which gets maxed at around 24 render distance and past that both RAM and CPU get rammed at 100% utilization and I get the jump in time and I KNOW the issue is chunk updates because I get less and less chunk updates the higher the render distance until its completely unresponsive and since I usually only run at 12 render distance they are a non-issue however it seems whenever something triggers a chunk update (picking up lava/water or any flowing substance for that fact) I get less chunk updates so its something to do with the physics for me

**Comment by selectL0L** [comment]
sorry if there are any spelling mistakes or the such

**Comment by CitiesXL2815** [comment]
This issue being Close bc plugin has been Rewritten Completely and hasn't been freezing Jei
