### ISSUE TITLE
EIO Farming Station Crashes when using GTCE Tools

### ISSUE THREAD

**Issue by Vyraal1** [SleepyTrousers/EnderIO#5134]
#### Issue Description:

https://github.com/FTBTeam/FTB-Interactions/issues/617

Pack dev here, EIO Farming Station seems to crash when you input a GTCE Tool.

#### What happens:
As described above, there is a crash when the farming station gets the GTCE Tool.

#### What you expected to happen:
No crashing, the tool to be transformed to the correct durability per operation, and for the tool to break once the operations are done.

#### Steps to reproduce:
https://github.com/FTBTeam/FTB-Interactions/issues/617
1. Place farming station
2. Put GTCE Tool inside, Darmstadium variant tools taken from JEI 

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.44
- EnderCore: 0.5.57
- Minecraft: 1.12.2
- Forge: 2836
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 

https://pastebin.com/q5bkKFzq which is taken from the previously linked issue

**Comment by HenryLoenwind** [comment]
That's the tool crashing, not the farmer...

**Comment by HenryLoenwind** [comment]
You're using an outdated gregtech, that bug was fixed there a while ago.
