### ISSUE TITLE
Editing spawner.xml directs me to put files in nonexistent folder.

### ISSUE THREAD

**Issue by katubug** [SleepyTrousers/EnderIO#5136]
#### Issue Description:

I'm sorry, I'm not sure where to put this. I want to ban a creature from being placed into a Powered Spawner, so I'm looking in config/enderio/recipes/spawner.xml to do so.

It says the following: 

> "These are the built-in recipes. You cannot change this file, it is a
> reference for you only and will be generated every time the game starts.
> 
> To make changes to the recipes, copy the recipes you want to change to
> a file in the 'user' folder."

However, there is no "user" folder in my base minecraft directory, the config directory, or the recipes directory. I am unsure of where I should put one if I made it.

#### What happens:

n/a

#### What you expected to happen:

n/a

#### Steps to reproduce:

n/a
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.44
- EnderCore: EnderCore-1.12.2-0.5.57
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2838-universal
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Both.

#### Your most recent log file where the issue was present: 

n/a

**Comment by Tfarcenim** [comment]
Look in the /config/enderio directory

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/58207316-bf924c80-7ce2-11e9-9f7f-f742d834de9f.png)

**Comment by katubug** [comment]
I am thoroughly embarrassed to say that I simply didn't see it. I apologize for wasting your time.

**Comment by HenryLoenwind** [comment]
Not an issue at all, but please don't remind me of my "blind" moments... ;)
