### ISSUE TITLE
Dark Shears activate tripwire hooks when used to break string

### ISSUE THREAD

**Issue by TopPercentageRattata** [SleepyTrousers/EnderIO#5137]
#### Issue Description:
Dark shears don't have vanilla shears tripwire breaking feature

#### What happens:
Breaking tripwire(string) with dark shears activates tripwire hooks

#### What you expected to happen:
Tripwire hooks should not activate when the string is broken by shears

#### Steps to reproduce:

1. Place tripwire hooks and string
2. Break the string with dark shears
3. Watch tripwire hooks activate

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.43
- EnderCore: 0.5.57
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? SP

#### Your most recent log file where the issue was present: 
Probably not needed for this

**Comment by CitiesXL2815** [comment]
Vanilla logic not enderio

**Comment by Tfarcenim** [comment]
Still a bug

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/58373633-5e13ed00-7f31-11e9-8af3-1faa15672e57.png)
 This is the vanilla code ^

Feel free to report it to Mojang...

**Comment by Tfarcenim** [comment]
ugh, even in 1,13 it's a hardcoded == check and not a tag.

**Comment by HenryLoenwind** [comment]
Yes, vanilla code is really annoying that way. There's just so much item identity checks everywhere. Forge replaces a good number with isXXX() calls on the item, but not all.

I'll have a look if we can "manually" disarm the trip wire when the shears are used, but as this is in block breaking code I'm not too optimistic. Items have good control for handling of right-clicking, but not so much on left-clicking.
