### ISSUE TITLE
Electric lights Don't work with xnet

### ISSUE THREAD

**Issue by Eladin** [SleepyTrousers/EnderIO#5138]
#### Issue Description:

Electric lights and XNet connectors do not connect to each other.
It does work using older versions of EnderIO and EnderCore.

#### What happens:
<img width="1920" alt="Base Profile Screenshot 2019 05 26 - 12 41 12 55" src="https://user-images.githubusercontent.com/22264173/58385544-8ba37980-7fb7-11e9-9d17-48ac1309a519.png">

#### What you expected to happen:
<img width="1920" alt="Base Profile Screenshot 2019 05 26 - 13 02 05 10" src="https://user-images.githubusercontent.com/22264173/58385553-a5dd5780-7fb7-11e9-83f3-97e93c911a2a.png">

#### Steps to reproduce:

1. loaded minecraft with only 
EnderIO-1.12.2-5.0.44
EnderCore-1.12.2-0.5.57
mcjtylib-1.12-3.5.3
xnet-1.12-1.8.1
forge-14.23.5.2838
2. Place xnet connector next to electric light 

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.44
- EnderCore: 1.12.2-0.5.57
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Definitely single player, I would assume also multiplayer but I haven't checked.

#### Versions where it works

- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Previous issue report to XNet
McJtyMods/XNet#348

**Comment by HenryLoenwind** [comment]
sounds like it's related to #4760

**Comment by Sleeeper** [comment]
that's why xnet has redstone proxy block for

**Comment by Eladin** [comment]
A redstone proxy block is a work around for redstone control but does not help with power.
