### ISSUE TITLE
Right clicking on item conduit with another "pops" it off

### ISSUE THREAD

**Issue by Testo0987** [SleepyTrousers/EnderIO#5139]
#### Issue Description:
When i right click on an item conduit with an item conduit in my hand, it just gives me another item conduit that has some NBT data on it.

#### What happens:
When i right click on an item conduit with an item conduit in my hand, it just gives me another item conduit that has some NBT data on it.

#### What you expected to happen:
I expect to just place another conduit down.

#### Steps to reproduce:

1. Place an item conduit
2. Be holding another item conduit
3. Right click on the item conduit
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.4.4
- EnderCore: 0.5.57
- Minecraft: 1.12.2
- Forge: 1.12.2 v2815
- SpongeForge? No
- Optifine? Yes
- Single Player

#### Your most recent log file where the issue was present: 
YT video:
https://youtu.be/QRL9Y1857zI

Edit: You can see the item conduit popping the the hotbar that don't stack with the original.
[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
Looks like the conduit upgrade code works on item conduits?

**Comment by HenryLoenwind** [comment]
The issue is that "some NBT data". That should not be there and it tells our code "hey that conduit in the player's hand is not the same as the one in the bundle".

**Comment by tyler489** [comment]
Thats what i was assuming aswell... i wonder what Data that is..

**Comment by HenryLoenwind** [comment]
Yes, tyler, your analysis was point on. Line 140 above is where our code gets thrown off.

**Comment by Testo0987** [comment]
This is the NBT data for the item conduit that didn't stack:
https://imgur.com/a/fQJlUvw

**Comment by Testo0987** [comment]
Also, when i break a regular item conduit it also turns into the weirded out conduit.

**Comment by Testo0987** [comment]
I removed smith's core, and everything seems to be fine now.
