### ISSUE TITLE
Server Crash: Exception ticking world

### ISSUE THREAD

**Issue by LordAshford** [SleepyTrousers/EnderIO#5140]
#### Issue Description:

Server crashes when entering a location. EnderIO achievement can be seen upon entering the location. The crash log does not indicate the issue being caused by an entity as far as I'm aware.

#### What happens:

Server shuts down upon entering the location

#### Steps to reproduce:

1.Spawn in
2.Teleport to the afflicted area (x=515.31, y=3.00, z=24.61) [Can upload the server files on 
                                                                                                request]
3.Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:5.0.44
- EnderCore:0.5.57
- Minecraft:1.12.2
- Forge: 14.23.5.2836
- SpongeForge? no
- Optifine? yes 
- Single Player and Server?

#### Your most recent log file where the issue was present: 

https://pastebin.com/XRBpEFuS

**Comment by tyler489** [comment]
Something is messing with the tick list in disasterious ways

**Comment by LordAshford** [comment]
Do you have any idea what it might be? Or know a way of checking what it could be?

**Comment by HenryLoenwind** [comment]
"TickNextTick list out of synch" most likely is a vanilla bug
