### ISSUE TITLE
The Splitting Enchantment from Apothesis doesn't work on Anvils

### ISSUE THREAD

**Issue by Tfarcenim** [SleepyTrousers/EnderIO#5141]
#### Issue Description:

The Splitting Enchantment from Apothesis doesn't work on Anvils

#### What happens:

The Splitting enchantment can be applied like normal, but when attempting to split the books by dropping the anvil on them, it doesn't split the books and behaves like a normal anvil.

#### What you expected to happen:

To split the books like the vanilla anvil does when enchanted

#### Steps to reproduce:

1.  Install Apothesis and EnderIO together
2.  Enchant Dark anvil with splitting
3.  Attempt to Split Enchanted books with multiple enchantments on them by crushing them with the enchanted anvil
4. It fails to split the book

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.44
- EnderCore: 5.0.57
- Minecraft: 1.12.2
- Forge: 2838
- SpongeForge? no
- Optifine? no
- Single Player

Note: I did report to the dev of apothesis but they closed it and said it was up to other mods to implement it on their end

#### Your most recent log file where the issue was present: 

wouldn't be useful

**Comment by Tfarcenim** [comment]
issue link for further reference https://github.com/Shadows-of-Fire/Apotheosis/issues/46

**Comment by HenryLoenwind** [comment]
Issue of other mod implementing stuff that doesn't work with other mods.
