### ISSUE TITLE
Spider spawner spawns bugged Skeletons

### ISSUE THREAD

**Issue by labradoe** [SleepyTrousers/EnderIO#5142]
#### Issue Description:

Spider spawner spawns in bugged skeleton.

#### What happens:

Skeleton spawns right next to spawner. It does not move and cannot be killed. It will spawn inside blocks. The skeletons stack.
Creates a log entry "Fetching addPacket for remove entity" for each skeleton spawned.

#### What you expected to happen:

Skeleton should be riding spider and die.

#### Steps to reproduce:

1. Place spider spawner.
2. Power spider spawner.
3. Wait until Skeleton spawns. 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.44
- EnderCore: 1.12.2-0.5.57
- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? server

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3235364/latest.log)

![2019-05-29 23_47_21-Minecraft 1 12 2](https://user-images.githubusercontent.com/13971731/58607093-380d8600-826c-11e9-91df-fbe879761be7.png)

**Comment by tyler489** [comment]
Spiderjockys maybe

**Comment by tyler489** [comment]
#3470 man that's an old issue I was remebering

**Comment by labradoe** [comment]
I've seen a spider jockey successfully spawn and get killed once... but literally only once. Hopefully that's the solution and it's easy to fix!

**Comment by HenryLoenwind** [comment]
This is not the reason for this issue, but I found a logic error where an unspawned entity's passengers were not cleaned up for the Creative Spawner. No such error with the Powered Spawner...

**Comment by labradoe** [comment]
Hmm, I'm definitely using the Powered Spawner. Another thing to note is that the "entity" appears to take up a 2x?x2 (xyz plane) space. I cannot place blocks in the space taken by the entity. The entity appears to spawn in the dead center of the 2x2 (xz) space. Hopefully that helps...

**Comment by HenryLoenwind** [comment]
Found it. When removing the passengers of an entity that wasn't put into the world (e.g. because there was no space found for it), the entity itself also must be set to "dead". Otherwise the dead passengers won't actually die but become ghosts.

Making them unmount probably would help, too.

**Comment by labradoe** [comment]
Awesome! Thanks!
