### ISSUE TITLE
EnderIO Hanging Up Server

### ISSUE THREAD

**Issue by EmeraldTiger64** [SleepyTrousers/EnderIO#5143]
#### Issue Description:
Me and my friends are noticing a strange crash on our custom modpack's server.

#### What happens:
When I go within a certain set of chunks, which contain a massive nuclear power station, the server hangs up and eventually crashes. When it does hang up, it refuses to load any other chunks, even if I teleport away from the power station. The power station has a lot of ender energy and redstone conduits, as well as many powered lights to keep the building of the plant well lit inside.

#### What you expected to happen:
I would expect the server to run smoothly and load in the chunks as it unloads the power station's chunks.

#### Steps to reproduce:
It isn't really reproducible as it seems to only be affecting our server. I mean, the area does have a lot of EnderIO ender power and redstone conduits, as well as powered lights in it, so that might be why.

____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: 1.12.2-5.0.44
- EnderCore: 1.12.2-0.5.57
- Minecraft: 1.12.2
- Forge: 14.23.5.2772 (we can't update this though as it causes the server and game to not start at all)
- SpongeForge? No
- Optifine? Yes (1.12.2_HD_U_E2)
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 
https://pastebin.com/FwHqiDA0

**Comment by tyler489** [comment]
Crash reports from stall logs are pretty well useless if server was killed by watchdog. I would recommend installing sampler and attaching it's stall log when the server crashes again

**Comment by EmeraldTiger64** [comment]
Is there any way of disabling WatchDog as our server came with it?

**Comment by EmeraldTiger64** [comment]
https://pastebin.com/E7Q69ehk I have Sampler installed.

**Comment by EmeraldTiger64** [comment]
https://pastebin.com/VeUXLrcj Nevermind, I found a log that Sampler spat out. The server didn't crash, but it is because I got away from the power station by teleporting and then disconnecting.

**Comment by EpicSquid** [comment]
This looks to me just like you have a tonne going on in the chunk. The ender io conduits may not even be the cause of it, though massive conduit networks can take time to load and the server may just be timing out. It's mostly just a limitation of mc. Try breaking the network into smaller networks that aren't all interconnected

**Comment by EmeraldTiger64** [comment]
Here is the thing... I can't really break this network up as it is the full lighting system for the inside of my nuclear power station and there isn't a good way of breaking up the network, at least not without causing problems.

**Comment by EmeraldTiger64** [comment]
Also, I was getting this issue even before I had gone through and properly finished the lighting system for the power plant.

**Comment by EmeraldTiger64** [comment]
If this is something that an update off the mod is likely to fix, then I will wait for that. However, if an update doesn’t fix it, then I will have to journey into the little exclusion zone me and the others set up on the server and break the conduit network into smaller chunks, probably crashing the game multiple times. If it would help, I can upload the world files and provide a link for the modpack. It is just strange that this is happening still, as it was doing it before I finished the lighting system within the plant.

**Comment by HenryLoenwind** [comment]
I'd try to set up chunkloading for the whole area and running the game with the watchdog disabled. Once it is loaded (even if it takes an hour), it should work.

I had a look at that trace, but there's nothing in there that would take an extraordinary amount of time. It's not even that many setNetwork()s (worst case is one per conduit in a straight line), so my guess is that something is interfering with them while they are trying to build their network. You don't have a block breaker+placer that break+place redstone conduits when they get a redstone signal?

**Comment by EmeraldTiger64** [comment]
As to chunkloading, I could give that a try, but I am worried that since it is when anybody leaves the chunks it crashes the server. And as to the block placer/breaker, no I don't have one of those. I should mention the whole place is a nuclear power plant that is using an Extreme Reactors reactor and 16 of that mod's turbines. I was thinking that it could possibly be the amount of multiblocks within the chunks, but that is how we had the plant set up before we started having issues. Finally I should ask, is there a way to disable the watchdog? Because I am not sure how to do so.

**Comment by EmeraldTiger64** [comment]
Ok, so when I tried to break up the conduit network it didn't work and was still causing major crashes. I am gonna download a copy of the server world to my client and try it there. Maybe it will yield a more useful log.

**Comment by EmeraldTiger64** [comment]
Ok good news. It wasn't EnderIO at all. Turns out it was the massive Zetta Industries battery we were using to store the power the reactor was producing.

**Comment by HenryLoenwind** [comment]
Congratulations on finding this out. Watchdog issues are notoriously hard to find.

**Comment by EmeraldTiger64** [comment]
Well not quite fixed. It has been going fine for a little while now, but it is back to doing what it was before. I have posted a stall log for the server. I have removed the big battery and went over to using an EnderIO capacitor bank.

https://pastebin.com/67FRFJbd
