### ISSUE TITLE
Configurable axe tree chopping height/size

### ISSUE THREAD

**Issue by leagris** [SleepyTrousers/EnderIO#5145]
#### Suggest configurable tree chopping height

ForestryForMC mod has a Giant Sequoia with a 4×4×80+ blocks trunk.
Even using a Stellar Axe (or darkSteel Axe), this tree can not be chopped in one go.
The axe seems to stop looking for logWood blocks at y+31.

It would be convenient to have this axe chopping height, width or blocks count configurable. I'd boost it to y+127 when forestry is installed.

There would probably need to extend the Farming Station working height as well.

**Comment by HenryLoenwind** [comment]
Please note that the configuration for the Farming Station is in the base config, too. That's where the farming modules live.
