### ISSUE TITLE
Explosions when attaching EnderIO capacitor to TE Cryo-Stabilized FLuxducts

### ISSUE THREAD

**Issue by EmeraldTiger64** [SleepyTrousers/EnderIO#5147]
#### Issue Description:
There is an issue where whenever I place down a cryo-stabilized fluxduct from Thermal Expansion and attach it to a capacitor or power buffer from EnderIO, it begins to create explosion noises and explosion particles where the connection is made. It doesn't do this with any of the other TE fluxducts either. I have included a screenshot of this occurring.
![2019-06-06_22 51 43](https://user-images.githubusercontent.com/31394546/59080678-9ad7d080-88af-11e9-876e-c464392b3cc0.png)

#### What happens:
When I attach a Cryo-Stabilized Fluxduct to anything in EnderIO (like the capacitor banks and power buffers) it begins to create explosion noises and particles where the connection is made.

#### What you expected to happen:

I wouldn't expect it to be making explosions where the two connect.

#### Steps to reproduce:

1. Place down either a power buffer or a capacitor bank.
2. Attach a Thermal Expansion cryo-stabilized fluxduct to the power buffer/capacitor.
3. Power the cryo-stabilized fluxduct so power flows into the power buffer/capacitor.

____
#### Affected Versions (Do *not* use "latest"):

    EnderIO: 1.12.2-5.0.44
    EnderCore: 1.12.2-0.5.57
    Minecraft: 1.12.2
    Forge: 14.23.5.2772 (we can't update this though as it causes the server and game to not start at all)
    SpongeForge? No
    Optifine? Yes (1.12.2_HD_U_E2)
    Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
Working as intended, this is an issue with the other mod pushing power multiple times a tick, not EIO.
