### ISSUE TITLE
Damage by Elytra collisions isn't reduced by armor

### ISSUE THREAD

**Issue by RedBlockFilms** [SleepyTrousers/EnderIO#5149]
#### Issue Description:

Damage caused by running into blocks while using an elytra isn't reduced by any and all armors, especially noticeable while using the elytra upgrade for the chestplate.

#### What happens:

Normal levels of damage when running into walls with elytra, despite levels of Empowered.

#### What you expected to happen:

Damage by collisions with elytra is reduced by armor pieces depending on Empowered levels

#### Steps to reproduce:

1. Equip any EnderIO armor (stellar, ender, dark steel) with empowered, as well as an elytra or elytra upgrade on a plate.
2. Gain speed while using the elytra
3. Slam head face-first into wall
4. Take large amounts of damage and/or die by experiencing kinetic energy

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.44
- EnderCore: 5.0.44
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 

[https://pastebin.com/74qjRZMy](url)

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/59428862-c0e4ff80-8dde-11e9-8f3d-d69ac3198598.png)

That's a vanilla mechanic, if you think this a bug, please report it to Mojang.
