### ISSUE TITLE
Server Crush after wireless charger remove

### ISSUE THREAD

**Issue by Oshi41** [SleepyTrousers/EnderIO#5151]
#### Issue Description:

I saw a million issues about wireless charger but i didn't see the same logs so I decided to open it
Server is crushing after breaking wireless charge block. Tried with wrench and the first time with hand in creative. 100% result

#### What happens:
Goddamn crush!!!

#### What you expected to happen:
Keanu Reeves autograph
But really i just don't want my server to fall down

#### Steps to reproduce:

1. Be nice and cool
2. Remove wireless cahrger with wrench/pickaxe
3.???
4. Crush
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO 5.0.44:
- EnderCore 0.5.57:
- Minecraft 1.12.2:
- Forge 14.23.5.2815:
- SpongeForge? yes
- Optifine? yes
- Server

Some other mods 
- EnderIO-endergy-1.12.2-5.0.44.jar

#### Your most recent log file where the issue was present: 

https://pastebin.com/4rTSSupS

**Comment by HenryLoenwind** [comment]
That's a bug in whatever `aroma1997.tatw.ic2usesfe` is, they are using an outdated capability object.

**Comment by Oshi41** [comment]
Thank you so much.
I have no problem with latest build
https://minecraft.curseforge.com/projects/tatw

Sorry for panic :)
