### ISSUE TITLE
XP obelisk cant hold more than 65535 XP

### ISSUE THREAD

**Issue by resinate** [SleepyTrousers/EnderIO#5154]
Version 1.12.2 Ender IO - 5.0.44

XP max level seems to be stuck at 4802 Levels even tho config says this
any chance of converting this value to long value?

**Comment by EpicSquid** [comment]
"the config says this" - what is this? There is nothing there

**Comment by HenryLoenwind** [comment]
Max levels is 21862. That limit is not the XP but the liquid form (`Integer.MAX_VALUE / 20` mB).

![image](https://user-images.githubusercontent.com/1485873/60001811-9826fa80-9667-11e9-86df-7d88524936bc.png)

**Comment by HenryLoenwind** [comment]
Correction: 21862 is the maximum levels that can be stores as XP in an integer. When storing those XP as liquid (which is what the obelisk does) that limit gets reduced by a factor of 20 again, to 4902 levels.

**Comment by NotHotTryHard** [comment]
7 years later, and it still hurts.
