### ISSUE TITLE
Bug:Inhibitor Obelisk is not working

### ISSUE THREAD

**Issue by jagabata22** [SleepyTrousers/EnderIO#5155]
#### What happens:
Inhibitor Obelisk is not working

#### Steps to reproduce:
Inhibitor Obelisk function will not work at the following times:
When returning to Overworld from another dimension
When you enter the world
When the player is dead and respawn

-------------------------------------------
MODPACK:Modern skyblock3 Departed Ver.3.6.0
Minecraft Version:1.12.2
forge-14.23.5.2808
EnderCore-1.12.2-0.5.57
EnderIO-1.12.2-5.0.44
-------------------------------------------
(Normal world, not MODPACK WORLD)
Minecraft Version:1.12.2
forge-14.23.5.2815
EnderCore-1.12.2-0.5.57
EnderIO-1.12.2-5.0.44
-------------------------------------------

- SpongeForge? yes/no
- Optifine: NO
- Single Player: Single

**Comment by CitiesXL2815** [comment]
inhibitor obelisk stops enderman and other monster from teleporting and works fine for me

**Comment by mindforger** [comment]
i think leaving the 
>What you expected to happen:

part empty is the biggest issue here :)

**Comment by CitiesXL2815** [comment]
not enough information about issue your have inhibitor

**Comment by HenryLoenwind** [comment]
Inhibitor prevents teleporting, it does not prevent logging in or respawning---nor does it promote it would.

For dimension travelling: There is no way to hook into that to prevent it aside from blocking travelling to a dimension completely. We'd be happy to add this, but you need to first get Forge to add a suitable hook/event.

**Comment by CitiesXL2815** [comment]
Inhibitor Obelisk function will not work at the following times:
When returning to Overworld from another dimension
When you enter the world
When the player is dead and respawn

so these thing do not do any of this there use prevent teleportation like travel anchors enderman travel staff and sword ender fluid and so much more that involves teleporting

**Comment by jagabata22** [comment]
To HenryLoenwind

I am not good at English and can not explain this phenomenon well.
I translated using a translation site, but it does not seem to be transmitted well.
I am sorry that I can not communicate well.
