### ISSUE TITLE
Broken Elytra on Dark Plate outputs entire Elytra.toString()?

### ISSUE THREAD

**Issue by 1R1SHMAN04** [SleepyTrousers/EnderIO#5157]
#### Issue Description:
When the Elytra that you add to a Dark Plate runs out of durability, it displays what I assume to be the toString() of the Elytra, instead of it's durability. While I haven't seen the code for it, but I assume this happens because there is some clause to see if the Elytra durability gets to 0, remove it from the Plate, but this never actually gets fired. Then for insurance, there is a line that says
`if(Elytra.durability > 0) display(Elytra.durability) else display(Elytra.toString())`
because you assumed this would never be able to happen?
Also since
#### What happens:
When Elytra durability reaches 0, it displays
[`Elytra: TranslatableComponent{key='tooltip.colytra.broken', args=[], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}`](https://i.imgur.com/TD6KikA.png)
#### What you expected to happen:
When Elytra durability reaches 0, it should either display `Elytra 0/431`, or delete the Elytra altogether, or Remove the Elytra from the Dark Plate and add a broken Elytra to the Player's Inventory
#### Steps to reproduce:
1. Add an Elytra to the Dark Plate
2. Use the Elytra a lot
3. It is now broken
____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: **1.12.2-5.0.44**
- EnderCore: **1.12.2-0.5.57**
- Minecraft: **1.12.2**
- Forge: **14.23.5.2836**
- SpongeForge? yes/**no**
- Optifine? yes/**no**
- Single Player and/or Server? **Only tested on Single Player**
- Modpack: **Enigmatica 2: Expert version 1.64d**

#### Your most recent log file where the issue was present: 
[DarkSteel Elytra Bug Log](https://gist.github.com/1R1SHMAN04/53a7c92c74072681008827fa5dfbcceb)
I doubt this log will do much for you. As you can see on line 14927/14928, `[11:47:36] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Press [§bJ§f]`, is when the world finally loads. I then walked around jumped, tried to use the Elytra by falling off of a hill. Nothing activated so I hovered over the Dark Plate a few times and then quit the world, but nothing was recorded in the logs while I was doing that, as the line after the loading finishing, was the unloading starting.

**Comment by VT-14** [comment]
Elytra: TranslatableComponent{key='tooltip.**colytra**.broken'...

[Colytra](https://minecraft.curseforge.com/projects/colytra) is an unrelated mod.  If you want to use Ender IO's Elytra mechanics, then combine the Ender IO Chestplate with an Elytra in an Anvil.  Ender IO (and the few other mods that I've seen include Elytra mechanics) do not take durability damage on use.

**Comment by 1R1SHMAN04** [comment]
I thought I did combine it in an anvil...
I'll have a look in a second and see if that mod replaces the anvil capabilities or if I'm just stupid

**Comment by 1R1SHMAN04** [comment]
No it doesn't, I must just be stupid. Thanks for the quick response!

**Comment by 1R1SHMAN04** [comment]
You know what it was actually, I received the bauble version from a loot chest, and combining the bauble version in an anvil uses the Colytra mechanics
