### ISSUE TITLE
Electromagnet says it's a bauble but it has no slot...

### ISSUE THREAD

**Issue by RepoDraghon** [SleepyTrousers/EnderIO#5159]
1.12.2
Direwolf20 pack
Baubles has an amulet slot but the magnet will not go into the slot.
Also, what mod is creating these redout areas when I highlight an item? I need to get rid of it, it's annoying until I have a problem with a mod...
![2019-06-26_05 33 12](https://user-images.githubusercontent.com/8423696/60180536-1ce35700-97d5-11e9-9f0d-4bf87018e0dd.png)

**Comment by EpicSquid** [comment]
Quark makes the red overlays. And you have to turn the magnet on to put it in the slot.

**Comment by MatthiasMann** [comment]
@RepoDraghon you can also change the EnderIO configuration to allow the electro magnet to go into the baubles slot when inactive.
