### ISSUE TITLE
EnderIO crash with Tinker's construct when i try to add Thermal Fondation, expansion and dynamics

### ISSUE THREAD

**Issue by caimez323** [SleepyTrousers/EnderIO#5162]
Hello,
I was modding my minecraft with mods like EnderIO and Tinker's construct
When i run my Minecraft with only EnderIo and Tinker, everything is fine
But, When i try to add Thermal Dynamics, Thermal Expansion and Thermal Foundation, even with theirs core, my game crash and says there is a problem with EnderIO and Tinker

#### What happens:

My game crash with this message :

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ender IO Integration with Tinkers' Construct (enderiointegrationticlate)"

It's very strange that when i put an other mod it's those two there crash
____
#### Affected Versions :

- EnderIO: EnderIO-1.12.2-5.0.25
- EnderCore: EnderCore-1.12.2-0.5.30
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.5.2838
- SpongeForge? yes/no
- Optifine? no
- Single Player and/or Server? Crash

#### Your most recent log file where the issue was present: 

https://pastebin.com/NAeCKnzA

**Comment by big-lip-bob** [comment]
You are exactly 21 versions behind the latest stable updated release so your issue isnt pertinent anymore, update your EnderIO or all mods and retry

**Comment by tyler489** [comment]
Hey Look A dinosaur
