### ISSUE TITLE
Illegal Async Chunk Load with Sponge

### ISSUE THREAD

**Issue by clienthax** [SleepyTrousers/EnderIO#5163]
#### Issue Description:
Seems to be an issue with sponge when async lighting is in place (default)
Conduits attempt to return a light value based on the TE, which in turn causes this to load a chunk off thread.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.43.jar
- EnderCore: EnderCore-1.12.2-0.5.53.jar
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2838-universal.jar
- SpongeForge? yes
- Server

#### Your most recent log file where the issue was present: 

https://gist.github.com/clienthax/e8c6ce42e9dab57ddf946384c21804bb

**Comment by HenryLoenwind** [comment]
The code in question tried to get the TileEntity for the block that is being asked for it's data. That should *never* trigger a chunk load, for to ask a block for its data, that block must be loaded.

Also, it's Sponge who does this outside the World thread without using a ChunkCache, which violates vanilla's rules about thread-safety.
