### ISSUE TITLE
Request: Mattock ability to create path blocks

### ISSUE THREAD

**Issue by RepoDraghon** [SleepyTrousers/EnderIO#5164]
____
#### Affected Versions (Do *not* use "latest"):
- Minecraft: 1.12.2

I was thinking if Right click is Farmland then Crouch+Right click would be Paths?

if it already is, I can't get it to work...

**Comment by tyler489** [comment]
Mattock is not enderio. However it was added to the axe with the spoon upgrade

**Comment by RepoDraghon** [comment]
Oops, thought I was in the Tinkers Construct github...
