### ISSUE TITLE
EIO / TiCo liquid glass issue

### ISSUE THREAD

**Issue by Sakata-MC** [SleepyTrousers/EnderIO#5165]
#### Issue Description:

EnderIO pressurized conduit does not pour liquid glass into casting basin.   (This does NOT affect other liquids tested; iron, gold, etc pour fine)

Noted that in testing, pressurized conduit was only one affected, the normal liquid conduit is fine, as well as ender conduit.

#### What happens:

Nothing.

#### What you expected to happen:

Liquid glass to be put into casting basin

#### Steps to reproduce:

1. Make smeltery, put pressurised conduit, top extract on reddstone, bottom extract without redstone, stick levers next to them, flip em both down.
2. Insert sand, wait to cook
3. Watch liquid glass enter conduit but not casting basin.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  endergy-1.12.2-5.0.46
- EnderCore:  1.12.2-0.5.59
- Minecraft:  1.12
- Forge:  Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2 loading
- SpongeForge? yes
- Optifine? no
- Single Player and/or Server? both

#### Your most recent log file where the issue was present: 

nothing useful in logs.

**Comment by Sakata-MC** [comment]
possible issue with routing? 
When playing aroudn with it a bit more, I added a conduit to the derped one, and now its working...?
![image](https://user-images.githubusercontent.com/3158362/60688295-50cc1580-9e82-11e9-9ad5-f6612a184444.png)
![image](https://user-images.githubusercontent.com/3158362/60688317-748f5b80-9e82-11e9-940d-37410e1313d9.png)
![image](https://user-images.githubusercontent.com/3158362/60688326-7e18c380-9e82-11e9-9f5f-d82b70ec99ef.png)
![image](https://user-images.githubusercontent.com/3158362/60688338-8a9d1c00-9e82-11e9-93d1-3fde298c705b.png)

**Comment by HenryLoenwind** [comment]
Most likely the basin changed what it can accept without telling its neighbors that something has changed.
