### ISSUE TITLE
Energy Conduits Not Transferring Power

### ISSUE THREAD

**Issue by FeedCat02** [SleepyTrousers/EnderIO#5166]
#### Issue Description:

When you close the singleplayer world the vibrant conduits sometimes not transfer power so you have to break and replace them

#### What happens:

Conduit doesn't transfer power

#### What you expected to happen:

Conduit transfers power

#### Steps to reproduce:

No clue how to reproduce as it is only the case on one of my save files

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.46
- EnderCore: 1.12.2-1.1.7
- Minecraft: 1.12
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? yes
- Single Player 
#### Your most recent log file where the issue was present: 
During the joining phase
https://pastebin.com/fGusWTba

**Comment by FeedCat02** [comment]
https://github.com/Damien-Reave/Omnifactory/issues/138 is the issue filed on the pack I am playing on

**Comment by MatthiasMann** [comment]
Which block is it that needs to receive energy? it is likely that this block is not notifying it's neighbors after it updates it's capabilities.

**Comment by HenryLoenwind** [comment]
"(other non-gregtech machines still get energy tho)"

Yeah, seems like people think we have special code to transfer energy for each and every mod.

**Comment by FeedCat02** [comment]
the gregtech machine is the CEF which convert RF to EU not the conduits changing the power.  Also for me it happens to all the blocks on the conduit line, (Gregtech CEF, deep mob learning machines and ender io capacitor bank) but even then it is hard to find out which mod is causing it as I cant seem to reproduce it

**Comment by FeedCat02** [comment]
Keep it closed as it is not an issue with the conduits except an issue with the te dynamo I am using
