### ISSUE TITLE
Crash after setting a config to false

### ISSUE THREAD

**Issue by SoonBanned** [SleepyTrousers/EnderIO#5167]
#### Issue Description:

My issue is happens in a modpack built on twitch by myself but I'm using "EnderIO-1.7.10-2.3.0.429_beta" that is announced as a release on twitch so I hope you can help ^^

#### What happens:

So because the nether was laggy and I was spammed in the console by an known issue and the way to resolve it was to change this config in the file"Separates wither and normal skeletons into different entities, enables the powered spawner to treat them differently [EXPERIMENTAL - MAY CAUSE ISSUES WITH OTHER MODS]" from true to false and since this is the only thing that I changed from the config before this bug appears I definitly think it's linked. 
So I don't exactly know how but at what seams to be a random moment for me because I can't find any link between the moment it appears, some people on the server got this crash : https://pastebin.com/kmf4yUfe but I can't find any way to solve this crash.

#### What you expected to happen:

I expected to play with no lag anymore and that was the case but instead we have random crashes

#### Steps to reproduce:

1. set "Separates wither and normal skeletons into different entities, enables the powered spawner to treat them differently [EXPERIMENTAL - MAY CAUSE ISSUES WITH OTHER MODS]" to false
2. walk randomly in the server with physica apparently
3. crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.429_beta
- EnderCore: 2.0.39_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- SpongeForge? : no
- Optifine ? : yes
- Server 

#### Your most recent log file where the issue was present: 

https://pastebin.com/kmf4yUfe

Edit : (I'm french and I don't use translators so I hope there's no mistakes ^^)

**Comment by CitiesXL2815** [comment]
1.7.10 not supported anymore

**Comment by big-lip-bob** [comment]
^ https://www.howoldisminecraft1710.today/

**Comment by SoonBanned** [comment]
You can't help really ? please..

**Comment by CitiesXL2815** [comment]
for this is not EnderIO issue seems to nuclear from IC2 or techreborn

**Comment by HenryLoenwind** [comment]
The setting is different on client and server, making them talk disagree which entity gets which ID.

**Comment by SoonBanned** [comment]
> The setting is different on client and server, making them talk disagree which entity gets which ID.

I didn't though at all of this you're genius ! x)

**Comment by SoonBanned** [comment]
> for this is not EnderIO issue seems to nuclear from IC2 or techreborn

I was thinking it was linked with physica :/
