### ISSUE TITLE
Killer Joe Breaks Unbreakable Tools

### ISSUE THREAD

**Issue by JPitholz** [SleepyTrousers/EnderIO#5170]
#### Issue Description:

Killer Joe gets an unbreakable tool from TiCon. After killing a mob the tool ends up having the broken tag. 

#### What happens:

the tool gets the broken modifier

#### What you expected to happen:

The tool shouldnt break

#### Steps to reproduce:

1.Setup Killer Joe (with nutr. dest. supply)
2. give it a tool from TiCon with unbreakable modifier (Reinforced 5)
3. spawn mob 
4.  after it getting killed, weapon is broken
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.46
- EnderCore: 1.12.2-0.5.59
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Optifine? no
- Single Player and Server

**Comment by VT-14** [comment]
What tool are you using?

**Comment by HenryLoenwind** [comment]
Do you really expect us to have code that puts mod-specific tags on certain items? We don't. We just tell the item it is being used. In fact, for The Killer Joe we don't even do that. We give the item to a FakePlayer and tell it to attack a mob.

**Comment by MatthiasMann** [comment]
Maybe TiCon (or some other mod) detects that it's a fake player and brakes the tool to make automated mob farms harder.

**Comment by LumberWizard** [comment]
Does the tool have a magical wood tool part?

**Comment by NickelHub** [comment]
There had been a similar issue with Primitive Mobs. Brain Slime could break unbreakable helmets immediately. Which mob do you spawn? Does it set any additional damage to the tool? This could cause the problem.
