### ISSUE TITLE
"Could not read item filter with class name: crazypants.enderio.base.filter.redstone.DefaultInputSignalFilter from NBT"

### ISSUE THREAD

**Issue by katubug** [SleepyTrousers/EnderIO#5172]
#### Issue Description:

Lots of console spam on server upon startup.

#### What happens:

Console is spammed with dozens of pages of

`[15:43:29] [Server thread/ERROR] [enderio]: Could not read item filter with class name: crazypants.enderio.base.filter.redstone.DefaultInputSignalFilter from NBT: {"enderio:class":"crazypants.enderio.base.filter.redstone.DefaultInputSignalFilter"} Error: java.lang.IllegalAccessException: Class crazypants.enderio.base.filter.FilterRegistry can not access a member of class crazypants.enderio.base.filter.redstone.DefaultInputSignalFilter with modifiers "private"`

#### What you expected to happen:

I expect not to have that many duplications of the same error.

#### Steps to reproduce:
n/a
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.46
- EnderCore: EnderCore-1.12.2-0.5.59
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2838-universal
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Definitely server, not sure about singleplayer.

Link to full modlist with versions: http://enthusiasticraft.cf/modpack-update-1-5-5/#modlist

#### Your most recent log file where the issue was present: 

https://gist.github.com/katubug/5196bc8abf1613fb87782cee4bb0c972

All relevant errors are at the very bottom.

**Comment by HenryLoenwind** [comment]
That is a one-time conversion when the world is loaded with a newer version of Ender IO for the first time. Forge even warns about it earlier in the log.

**Comment by katubug** [comment]
Ah, my apologies. I'm just combing through the full log now, I should have finished that before reporting.
