### ISSUE TITLE
Elytra upgrade Bugs

### ISSUE THREAD

**Issue by tyler489** [SleepyTrousers/EnderIO#5179]
#### Issue Description:
Elyrtra can periodicly toggle in other Gamemodes such as spectator or creative as well as adventure. While It is useful in adventure mode it has drug me down out of the world in spectator mode. It can also be toggled while riding entitys such as minecarts

#### What you expected to happen:
BlackList elytra when in creative & spectator or when riding a entity

#### Steps to reproduce:

1. Equip darksteel/endsteel with eltra
2. go into gamemode
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 0.5.44
- EnderCore:0.5.57
- Minecraft: 1.12
- Forge:14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

**Comment by HenryLoenwind** [comment]
Yeah, I finally found where the creative mode check belongs---it's not checking for creative/spectator mode but for "isFlying". However, the check for riding something already is there, nothing more I can do.

The darn issue is that Forge *still* has no hook for adding custom Elytras. How long ago were they added to the game?
