### ISSUE TITLE
Powered Spawner config removed?

### ISSUE THREAD

**Issue by ipsk** [SleepyTrousers/EnderIO#5180]
Hello,

Was the powered spawner configuration removed?
I wanted to edit a few setting for it but the file is nowhere to be seen.
I searched and there was a PoweredSpanerConfig_Core.json file? Was it removed? Is there no other way to the powered spawner config now?

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/61335117-9d253700-a82c-11e9-9e29-6d4732bc2537.png)
