### ISSUE TITLE
Change recipe machine file but won't load

### ISSUE THREAD

**Issue by EarlyPacker** [SleepyTrousers/EnderIO#5181]
I don't know where ask this,  so sorry for issue, try to load custom machines.xml file, copy to user folder and change but nothing happen, how should I do it? Couldn't find any guides for it.
Thanks!

**Comment by tyler489** [comment]
where did u get the custom machines xml file from?

**Comment by EarlyPacker** [comment]
I copied it from the folder recipes, i simply dragged the machines.xml file there and edited it, restarted the server but no changes loaded into the game.
What is the discord link?

**Comment by tyler489** [comment]
https://discord.gg/sgYk3Jr
