### ISSUE TITLE
game crashes when adding Basic Fluid Filter, while redstone conduit is connected.

### ISSUE THREAD

**Issue by Its-treason** [SleepyTrousers/EnderIO#5182]
The game crashes when I try to insert a Basic Fluid Filter into filter upgrade slot while a Redstone conduit is connected. It works fine with any other conduit.

Steps to reproduce 
1. get yourself a Basic Fluid Filter
2. connect a Ender Fluid Conduit and a Redstone Conduit to a machine
3. open the filter menu and put the Basic Fluid Filter inside.

I also recorded it -> https://youtu.be/_TOB_3CjNqQ

- EnderIO: 5.0.46
- EnderCore: 0.5.59
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player 
- OS: Ubuntu 19.04 

Minecraft Crash Log: https://pastebin.com/BiKq1n1L
Minecraft Log: https://pastebin.com/s8S6NJA6

**Comment by GreaseMonk** [comment]
It just happened to me as well, i wasnt using a fluid filter but a normal item filter. 
Crash log:
https://pastebin.com/svQyvqZh
