### ISSUE TITLE
runtime exception

### ISSUE THREAD

**Issue by 3269199948** [SleepyTrousers/EnderIO#5183]
[err.txt](https://github.com/SleepyTrousers/EnderIO/files/3404469/err.txt)

The server did not crash, this error occurred during the run, this is all the logs I can find.

**Comment by 3269199948** [comment]
gameversion:1.12.2
EnderIO-1.12.2-5.0.46
EnderCore-1.12.2-0.5.59
Forge:2838
Optifine:no
Appear on the server
SpongeForge? No

**Comment by HenryLoenwind** [comment]
The code that's crashing ("setGoalTarget") is added by some coremod.

**Comment by 3269199948** [comment]
> The code that's crashing ("setGoalTarget") is added by some coremod.

Do you mean other problems, I don't quite understand

**Comment by tyler489** [comment]
another mod is messing with enderman and crashing when enderio tries to tell the enderman not to teleport

**Comment by 3269199948** [comment]
> another mod is messing with enderman and crashing when enderio tries to tell the enderman not to teleport

thank you, I know now
