### ISSUE TITLE
Limited Item Filter Suggestion

### ISSUE THREAD

**Issue by Xyrys** [SleepyTrousers/EnderIO#5184]
#### Issue Description:

Could we get behaviour for limited Item Filter changed by an extra button added so if you set it to say 2, it will only insert if there is 2 of the item to be inserted.

#### What happens:
Atm the filter works by inserting up to the number specified, not THE number specified.  So if you set it to 2, and only have 1 it will insert it.  The problem here is if your load sharing, say a multi machine processing setup the situation arises where you input 1 in one machine and say 14 in another but you need a total of 15 to begin the process.  Even with it set to a higher multiple say 16 if you needed 4 per process, it can put 13 in one machine and 3 in another, even with a cascading set of priorities.

However  when filter is put in the export slot it works perfectly.  if you set 2 it will only send if 2 are available..  But this makes it tedious in the extreme. 

#### What you expected to happen:
I would like for it to only insert the number specified if you select for that to happen.

Just a little quality of life suggestion.

**Comment by EpicSquid** [comment]
Try using an impulse hopper, it was designed exactly for this situation.

**Comment by Xyrys** [comment]
Tried that.  Its excellent btw.  However in a situation where you have a single line of conduit servicing in this case 28 machines in a row you can't use the impulse hoppers..  The wiring would be incredibly bad and remove the whole neatness and compactness of the processing build.  Which is why I love ender io conduits (since they were a thing).  Also thats ignoring it needs a fluid pipe as well to output/input at the same time.

![2019-07-20_16 32 22](https://user-images.githubusercontent.com/10042954/61575178-01d1e180-ab0c-11e9-8386-2b370716a7df.png)

I have a workaround which is a chest with 3 inputs (PUSH) on it (so 3 filters or 30 items) going in, then 3 output (PULL) going out.  By having the inputs with same exact filter as the output it makes certain the machine ONLY gets a full load, and makes sure the chest doesn't get overfilled.

![2019-07-20_16 40 34](https://user-images.githubusercontent.com/10042954/61575310-72c5c900-ab0d-11e9-8a5e-3dea145ffa9c.png)
![2019-07-20_16 40 41](https://user-images.githubusercontent.com/10042954/61575313-76595000-ab0d-11e9-8093-af72e646feb3.png)
 
However..  My suggestion removes the need for the workaround.

And yes I know I can do the same stuff with AE..  But this looks WAY better :-)

Thanks.

**Comment by Xyrys** [comment]
A better picture of how the workaround looks is this.
![2019-07-20_16 56 47](https://user-images.githubusercontent.com/10042954/61575464-6b072400-ab0f-11e9-95df-95916919b417.png)

**Comment by Xyrys** [comment]
Ok scratch that.. The workaround is only working for odd combinations.  But tried it with the impulse and it works.  Just need a lot more of them to do the same job the filter could do lol.

**Comment by Xyrys** [comment]
Although why does the export filter act that way..  Its acting opposite to the input filter.

If the export has a count of 6, it will leave 6 in the object its connected to and send everything else..  Shouldn't it only send 6 ?  

Atm it sends whatever is over 6 up to 6.  and makes sure theres 6 left..  so if you put 11 in there it will send 5 even though the filter says 6..  Odd behaviour ?
