### ISSUE TITLE
Enderio vibrant capacitor banks only output what there receiving input is

### ISSUE THREAD

**Issue by josh-65** [SleepyTrousers/EnderIO#5186]
#### What happens:
Vibrant capacitor banks only output what there receiving input is.

#### What you expected to happen:
It to output however much power is needed for the block

#### Steps to reproduce:
1. Place a full vibrant capacitor bank
2. Connect it to another power consuming block
3. See it out puting 1 iu/t

#### Affected Versions
- EnderIO: 5.0.46
- EnderCore: 5.0.59
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge?: no
- Optifine?: yes
- Single Player

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3414944/latest.log)

**Comment by SplitInfinitive** [comment]
how was it connected to the other block?  Directly touching it or conduit?  if conduit which one?  What was the block that was consuming power?  Was it running at the time?  If it was an ender IO machine what kind of capacitor was in it (if it wasn't a simple machine)?  How full was the machine's buffer?

**Comment by josh-65** [comment]
The conduit is a Cryo-flux one from thermal dynamics that can carry infinite rf and it's a full vibrant capacitor bank connected to a empty one and the max output is 25,000.

**Comment by SplitInfinitive** [comment]
can you try with one of EIO's conduits?  I understand that it will instead, be limited to the conduit's max.  The ender one being around 20k.  the Cryo ducts tend to have unusual side effects due to how they're coded.

**Comment by josh-65** [comment]
Ok i will try that.

**Comment by HenryLoenwind** [comment]
With ducts you *WILL* get feedback loops. They prefer to dump the energy back into the block they got it from instead of sending it somewhere else.

**Comment by josh-65** [comment]
The ender conduits work with the vibrant capacitor bank at full transfer but other block still go at 1 ui/t and I have tried it on an older version of minecraft and all the blocks go at full transfer.
Im mainly trying it on the flood lights mod and thut's elevators.

**Comment by josh-65** [comment]
Ok it seems to have fixed itself with most mods so im going to close this issue. Thanks for the help.
