### ISSUE TITLE
[Question] Armor Upgrade Configuration

### ISSUE THREAD

**Issue by TomConnery** [SleepyTrousers/EnderIO#5187]
Hello together!
I'm currently throwing together a modpack and I'd like to disable a few armor upgrade options of EIO in favor of items of other mods (looking at you, Botania and Thaumcraft!).

However, I can't seem to find any config entries for the armor upgrades that I wish to disable.

Am I right with my assumption that there's currently no way to configure them out of the game?

Best regards, Connery

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/61610359-37381580-ac59-11e9-9285-1197b447b169.png)

**Comment by TomConnery** [comment]
Oh wow, I do need to practice reading through stuff properly.
Thanks a bunch for the help!

**Comment by HenryLoenwind** [comment]
No problem, that config is huge. I try to keep in in a logical tree structure, but that doesn't always help.

Feel free to ask on our Discord if you need help with finding the IDs. Those are Forge Registry IDs like "enderio:tnt" and---as far as I know--not visible anywhere in-game.

**Comment by TomConnery** [comment]
Thanks for the hint! 
I took a different approach and skimmed the sources, stumbling upon the upgrades folder eventually.
Each upgrade has its own class, thankfully, so I only needed to line them up with the prefix you provided me with.
Works like a charm now!

I'll make sure to add an entry to the wiki / PR :)
