### ISSUE TITLE
EnderIO Zoo - No Such Method Error

### ISSUE THREAD

**Issue by 0rangeFox** [SleepyTrousers/EnderIO#5188]
#### Issue Description:
When someone join on server that reproduce the error, and server closes automatically.
____
#### Affected Versions:

- EnderIO: 5.0.46
- EnderCore: 0.5.59
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? No
- Optifine? Yes
- Server

#### Your most recent log file where the issue was present: 
https://pastebin.com/k6wKa7ss

**Comment by tyler489** [comment]
Full crash report please

**Comment by 0rangeFox** [comment]
Here go.
[crash-2019-08-01_10.27.23-server.txt](https://github.com/SleepyTrousers/EnderIO/files/3455944/crash-2019-08-01_10.27.23-server.txt)

**Comment by HenryLoenwind** [comment]
That's a kettle issue, you need to talk to them as I have no idea what's happening there.

**Comment by 0rangeFox** [comment]
Alright, i will talk with him. Thanks.
