### ISSUE TITLE
Mystical Argiculture

### ISSUE THREAD

**Issue by Notlucky101** [SleepyTrousers/EnderIO#5189]
It look like only the emerald essence which take 9 EnderIO-1.12.2-5.0.46 for 1 emerald not functioning on the  right side of the power crafter when I update to EnderIO-1.12.2-5.0.49. It works fine with EnderIO-1.12.2-5.0.46.

minecraft 1.12.2
forge 14.23.5.2838

also a invalid image shows when configuring the input and output.

**Comment by tyler489** [comment]
Mods list?

**Comment by gggg336** [comment]
It seems we have the same problem in regards to the crafter.

After setting the recipe in the crafter and giving it power (using the Stellar capacitor from Endergy) it seems that the crafter crafts just one of the item and gets stuck. The output slot does not show any items that comes from that one craft and neither auto output nor item pipes can extract the item that has been crafted. I have tried vanilla hopper recipes, 3X3 redstone block crafting and Mystical Agriculture recipes and it has the same problem. Also when selecting the input/output sides the mouseover overlay displays the missing textures purple and black textures (I have no resource packs enabled).
