### ISSUE TITLE
NoClassDefFoundError: ../BlockFluidEnder

### ISSUE THREAD

**Issue by Prasodym** [SleepyTrousers/EnderIO#5190]
#### Issue Description:

When I started the server I noticed that the server crashed.

#### What happens:
The server crashed at startup.

#### What you expected to happen:

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.49
- EnderCore: 1.12.2-0.5.65
- Minecraft: 1.12.2
- Forge: 14.23.5.2780
- SpongeForge? yes
- Optifine? no
- Server: yes

Further information about the versions can be found in the Crash reports.

#### Your most recent log file where the issue was present: 

[https://pastebin.com/42Nau2R9]

Greetings Prasodym

**Comment by Prasodym** [comment]
There are no problems on the client side.

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/62421579-3f09a800-b6a4-11e9-978d-e34067fd0992.png)

Seems like some other mod prevents Forge's fluid block class from loading.

**Comment by HenryLoenwind** [comment]
Update: Oh, it's that one again...

you are using `spongeforge-1.12.2-`**2825**`-7.1.6.jar` with `forge-14.23.5.`**2780**.

**Comment by HenryLoenwind** [comment]
see also https://github.com/SpongePowered/SpongeForge/issues/2805
