### ISSUE TITLE
Ender IO 5.0.50 freezes game

### ISSUE THREAD

**Issue by LuciusV** [SleepyTrousers/EnderIO#5191]
#### Issue Description:

Game freezes

#### What happens:

After updating to EnderIO 5.0.50 upon entering world there is huge lag spike that freezes game almost completely. Also happens in every new created world. There is small chance if I wait 5-10 minutes to unfreeze, but it will happen again on every load (or going through the portal). In most cases game is frozen completely. 

If I launch game without EnderIO, freeze disappears. It also disappears after downgrade EnderIO to 5.0.46

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.50
- EnderCore: 0.5.65
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2836
- SpongeForge? no
- Optifine? yes
- Single Player (server not tested)

#### Your most recent log file where the issue was present: 

 There is no crash log because this freeze did not give chance to make it.

**Comment by LuciusV** [comment]
Sorry EnderCore: 0.5.65. Cannot edit post for some reason

**Comment by Ommina** [comment]
While it may not have created a crash report, there will still be a log file.  The Powers That Be will need that.

**Comment by tyler489** [comment]
Is there someone else on the server a round you? I was having issues with darksteel freezing me in .49 but couldn't reproduce reliably

**Comment by BSKCorp** [comment]
Like to add I was having the same issue with the latest versions as well, first time installing it and it was eating my memory like the cookie monster in a cookie factory. I started with 4 GB which I have been running fine with a 70+ mod modpack and after adding in Ender IO and Ender Core. It maxed out my 4GB, added up to 8 GB and was still doing the same thing. Freezing up every few moments as it refreshed the memory to free up and only eat it up again. So like to say there is a memory leak with this version possibly?

**Comment by LuciusV** [comment]
I can no longer reproduce it...
