### ISSUE TITLE
Killer Joe Crash

### ISSUE THREAD

**Issue by ClashofJustYT** [SleepyTrousers/EnderIO#5193]
Issue Description:

I placed killer Joe, then the server crashed

What happens:

I placed killer Joe, then the server crashed

#### Steps to reproduce:

1. I placed killer Joe.
2. then the server crashed
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10 Forge
- Forge: forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
- SpongeForge? No
- Optifine? No
- Server

#### Your most recent log file where the issue was present: 
[crash-2019-08-06_11.15.08-server.txt](https://github.com/SleepyTrousers/EnderIO/files/3472002/crash-2019-08-06_11.15.08-server.txt)

**Comment by HenryLoenwind** [comment]
Bug in "Minecraft Comes Alive"
