### ISSUE TITLE
Question: Is it possible to add a config option to disable the charged weapons as loot?

### ISSUE THREAD

**Issue by SirAron111** [SleepyTrousers/EnderIO#5194]
Question: Is it possible to add a config option to disable the charged weapons as loot?

I wanted to ask if it’s possible to add a config option to stop Ender IO Weapons and Armor to be found in loot chests, or at least the powered up ones with strong abilities. I mean I want people to be able to find the random capacitors they are fun but having a loot chest full up with like 2 swords and 3 pairs of boots is literally to much especially if these items are configured in the config to be strong (to compete with other modded scaling dmg changes).

With many mods adding loot to chests these small things always end up overfilled if like 5 spots or more are taken by 3+ ender io swords.

I am not talking about some elaborate loot table tweaking just about having it as a config option to disable the armor/weapon part of loot injections.

Or at least an option to disable loot entirely!
With a simple you want loot? Turn this to true default true, you don’t want loot turn this to false thingy.

**Comment by HenryLoenwind** [comment]
That why vanilla made the complete loot system one big config file...

**Comment by SirAron111** [comment]
Ye great but I meant it as a config option a simple on of switch. For if a player wants loot injections or not. Adding a full loot table JSON change is way more taxing on a Modpack than simply having the mod who wishes to add the item injection say nop no item injections at all.
I mean where would I even start to change around the loot and if one by one.
Just a general on of switch for loot injections in config should be possible.
