### ISSUE TITLE
EnderIO Crashing

### ISSUE THREAD

**Issue by IKindaLikeDogsALittleBit** [SleepyTrousers/EnderIO#5199]
#### Issue Description:
When I try to launch Minecraft with forge, the game gets to the second step and crashes.

#### What happens:
The game crashes and the Minecraft launcher reopens and displays crash information.

#### What you expected to happen:
The game to successfully load up.

#### Steps to reproduce:

1. Install EnderIO and EnderCore
2. Launch game

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.50 and 5.0.49
- EnderCore: 0.5.65
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? No
- Optifine? Yes
#### Your most recent log file where the issue was present: 
https://pastebin.com/YvPFsjTV

**Comment by HenryLoenwind** [comment]
Please check if the file "AutoSave-1.12.2-1.0.11.jar" in your mods directory is corrupted. It should have a size of 90,467 bytes and be a valid jar file.

**Comment by IKindaLikeDogsALittleBit** [comment]
The file seems to be completely fine, is a valid jar file and is 90,467 bytes.

**Comment by tyler489** [comment]
what launcher are you using?
