### ISSUE TITLE
FTB Infinity Evolved Crash because of EnderIO/AppliedEnergistics

### ISSUE THREAD

**Issue by spookydascary24** [SleepyTrousers/EnderIO#5203]
#### Issue Description:

Minecraft crashes randomly throughout the game, sometimes leaving no crash report. I tried using an older version of FTB (3.0.2) but it still doesn't work, it runs fine for some minutes but then the crashes happen more often, same on FTB 3.1.0.

#### What happens:

Random crashes while playing without any warning. 

#### What you expected to happen:

I expected it to run normally without any issues

#### Steps to reproduce:

1. Open Twitch Launcher
2. Install FTB Infinity Evolved 3.0.2/3.1.0
3. Right click FTB Profile, Open Directory
4. Open mods folder and add HideNames Mod
5. Launch Minecraft
6. Join Server
7. Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: Yes
- SpongeForge? no
- Optifine? no
- Single Player and Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/uAamWSri

**Comment by CitiesXL2815** [comment]
1.7.10 forge is not supported anymore so don't except any fixes for enderio or the core bc devs have moved to latest version of mc 1.12.2

**Comment by tyler489** [comment]
Nothing to do with enderio
