### ISSUE TITLE
1.12.2 Server Randomly Crashes, Ender IO Error Spam in Log

### ISSUE THREAD

**Issue by Caaruzo** [SleepyTrousers/EnderIO#5204]
#### What happens:

Server randomly crashes or dont boot up with generating an hs_err_pid file but no crashlog. EnderIo also Spams errors in console. Dont know if Ender IO is the real reason for crash, but the Error Spams should get fixed anyway.

#### What you expected to happen:

Server booot up fine, run stable and mod using is possible.

#### Steps to reproduce:

1. boot up server with latest forge
2. taker a look into the log
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: **EnderIO-1.12.2-5.0.50**
- EnderCore: **EnderCore-1.12.2-0.5.65**
- Minecraft: **1.12.2**
- Forge: **forge-1.12.2-14.23.5.2838-universal**
- SpongeForge? **no**
- Optifine? **no**
- Single Player and/or Server? **Server**

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3489049/latest.log)
[hs_err_pid6920.log](https://github.com/SleepyTrousers/EnderIO/files/3489050/hs_err_pid6920.log)
[debug.log](https://github.com/SleepyTrousers/EnderIO/files/3489051/debug.log)

**Comment by Caeas** [comment]
@ Henry, you added the Label Logfile Missing, but they are all on bottom of my Issue attached.

**Comment by mindforger** [comment]
Those are google drive links without public access, why dont you use pastebin or similar instead?

**Comment by HenryLoenwind** [comment]
btw, I removed the links because of privacy concerns. Post files in a way that does not collect information about the accounts of people accessing them.

**Comment by Caeas** [comment]
i added them there in case of they are to large for pastebin. Cant add there, it hangs and crashes xD. That were direct links that could be read without download. Didnt seen i can add them here also for upload, sry. 

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3489049/latest.log)
[hs_err_pid6920.log](https://github.com/SleepyTrousers/EnderIO/files/3489050/hs_err_pid6920.log)
[debug.log](https://github.com/SleepyTrousers/EnderIO/files/3489051/debug.log)

**Comment by Caaruzo** [comment]
got the crahs itself resolved, was an CPU problem ofc. had problems with several protocolls. Anyway the spam still exists but dont crash the server. Just FYI
