### ISSUE TITLE
Redstone Conduit issues

### ISSUE THREAD

**Issue by PolyacovYury** [SleepyTrousers/EnderIO#5206]
#### Issue Description:

All those issues can be reproduced using a single redstone conduit.
1. Place a redstone conduit, put a lever on one side, and redstone dust on another. Make the side with the lever to be an input on red channel and turn off output. On the side with the dust, first turn on output from red channel, then briefly turn on **and then off** input from red line.
2. Place a redstone conduit. Place a lever on one side and redstone dust on another. Set the side with the lever to be input to red channel, the side with the dust - carefully, to avoid issue №1 - to be a *disabled* input to green channel and an output from red channel. Then, put a redstone timer filter into the input where the lever is - the dust starts blinking, that is normal - and then put a redstone sensor filter into the disabled input on the side with the dust.

#### What happens:

1. Conduits gets completely unresponsive - flicking the lever and changing settings on other sides of the conduit never turns off the redstone dust. The only way to get it out of that state is to break and replace the conduit.
2. Dust stops blinking, until you remove the sensor. The lever does not alter the situation in any way. Sometimes it even stops working entirely, as described in №1.

#### What you expected to happen:

1. My silliness/sloppiness shouldn't make an entire conduit network unresponsive - when I remove input and output from/to the same channel on the same conduit side, the conduit should start working again.
2. The sensor in a disabled input on a different channel shouldn't affect the timer's operation.

#### Steps to reproduce:

... Kinda described them above ^^
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.50
- EnderCore: 1.12.2-0.5.65
- Minecraft: 1.12.2 (duh)
- Forge: 1.12.2-14.23.5.2768
- SpongeForge? reproduced on the EnderIO Test Server, no idea if it is there
- Optifine? yes?
- Single Player and Server.

#### Your most recent log file where the issue was present: 

No crash, no log.

**Comment by PolyacovYury** [comment]
I must add, that my descriptions can be a bit unclear, so, if needed, I can log onto the test server and show those issues live. ;)

**Comment by weightmaker** [comment]
this is still an issue (version 5.1.52) and creates a HUGE issue when someone tries to learn to use these conduits. to be able to swap out different cards are essential for trial and error. 
So when some random conduit "Remembers" an out-of-date redstone signal, you dont get the expected result and either wont learn anything or learn it wrongly.

**Comment by tyler489** [comment]
doesnt matter as the entire redstone conduit system is being redone anyway.

@HenryLoenwind can you make sure this is fixed in your branch please <3
