### ISSUE TITLE
[Server Crashes on Player Death]

### ISSUE THREAD

**Issue by NikeSchuh** [SleepyTrousers/EnderIO#5210]
#### Issue Description:

You kill a Player and there is a Chance that your Server crashes. Its not crashing everytime sometimes ist just doing Nothing.

#### What happens:

After a couple of seconds the Server crashes with a error in the console

#### What you expected to happen:

That the Server is not crashing and my friend just dies normally without crashing the whole Server.

#### Steps to reproduce:

1.Put your Server in Offline-mode
2.Kill your friend and there is a Chance that the Server dies

____
#### Affected Versions 

- EnderIO: 5.0.50
- EnderCore: 0.565
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? Yes (HexaCord)
- Optifine? No optifine is not Installed.
- Single Player and/or Server? Its on a Server.

-----Crash Report----
[CrashReport.txt](https://github.com/SleepyTrousers/EnderIO/files/3497058/CrashReport.txt)
-----Latest Log-----
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3497073/latest.log)

**Comment by mindforger** [comment]
how do you think this is an EIO issue?! There is no trace of anything relating to EIO being the issue!? 

Does this happen in online mode?! 

because in the report it LITERALLY says * Offline mode for dedicated servers is NOT supported by Ender IO.

**Comment by LumberWizard** [comment]
Offline mode is not supported. Additionally, this crash doesn't seem to be caused by Ender IO at all--I find it much more likely to be caused by Sponge or one of your plugins. Something to do with the scoreboard.

Also, in the future, please upload your logs to a site like pastebin or gist, rather than uploading the files themselves, like the template says.

**Comment by HenryLoenwind** [comment]
looks like this is this crash: https://github.com/SpongePowered/SpongeForge/issues/2817
