### ISSUE TITLE
[1.12.2 Bug] Game Crashing after Breaking Conduits

### ISSUE THREAD

**Issue by SavageKiller13** [SleepyTrousers/EnderIO#5212]
#### Issue Description:

Game crashes after trying to break conduits.

#### What happens:

What happens is when I Try to pick up the conduits with a wrench or break them the game will crash on the instant of the conduit being clicked. Happens with bundles and stray conduits and happens multiple times.

#### What you expected to happen:

What I expected to happen was to be able to break or pickup the conduits easily. Can be fixed using creative mode or commands.

#### Steps to reproduce:

1. Place any EIO conduit down.
2. Take Pickaxe (or any tool to break conduits)
3. Start breaking the Conduit.
4. The game will crash on click.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.46
- EnderCore: 1.12.2-0.5.59
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2838
- SpongeForge? No
- Optifine? No
- Single Player Server

- If needed I am playing the modpack "Omnifactory" with no additional mods.

#### Your most recent log file where the issue was present: 

https://pastebin.com/raw/f2KCtdFb

**Comment by tyler489** [comment]
may be caused by https://bitbucket.org/Requios/effortless-building/issues

**Comment by HenryLoenwind** [comment]
Note: coming from net.minecraft.entity.player.EntityPlayer.getDigSpeed(IBlockState), PlayerEvent.BreakSpeed.getPos() is null (here Forge's Javadoc is wrong, btw), so 
Effortless Building is calling BlockState.getBlockHardness() with a null pos.

**Comment by HenryLoenwind** [comment]
PS: also, `net.minecraft.block.Block.handler$getPlayerRelativeBlockHardness$zzb000(Block.java:2760)` which causes the deprecated getDigSpeed() to be called is added by a coremod (no idea which one). getDigSpeed() is normally unused and should not be used.

**Comment by tyler489** [comment]
```
nl.requios.effortlessbuilding.EventHandler.breakSpeed(EventHandler.java:133
)```
