### ISSUE TITLE
Hard freezes and latency when rendering darksteel

### ISSUE THREAD

**Issue by tyler489** [SleepyTrousers/EnderIO#5214]
#### Issue Description:
Long latency or full lockup when rendering other people wearing dark steel
This may have the same root cause as
#4966 

#### What happens:
When another player is nearby wearing darksteel endsteel or the endergy metal armor with the solar upgrade results in an immediate freeze of Minecraft 
If another player is wearing Speed equipped pants I get a full 30 seconds of latency on the server before being disconnected for not sending packets.
It also seems to happen to other players when jumping in water with boots with multi jump and flippers. Although i have not had it happen to myself

#### What you expected to happen:
Duh

#### Steps to reproduce:

1.go into multiplayer
2.equip darksteel helmet with solar
3. Run near a player. Watch them freeze
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: v.47 through 5.0.50
- EnderCore: .63
- Minecraft:1.12
- Forge:
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Server May also apply to Lan worlds unable to test

#### Your most recent log file where the issue was present: 

Nothing in the log about this issue

**Comment by HenryLoenwind** [comment]
please try if this change helps. so far it's a pure guess...
