### ISSUE TITLE
Crash when I interact with "Experience Obelisk"

### ISSUE THREAD

**Issue by GhostShot3** [SleepyTrousers/EnderIO#5215]
I play in my modpack with 200+ mods, the minecraft crash when I interact with "Experience Obelisk"
[Crash report](https://pastebin.com/raw/t87vbfsy)

- EnderIO:EnderIO-1.7.10-2.3.0.429_beta
- EnderCore:EnderCore-1.7.10-0.2.0.39_beta
- Minecraft:1.7.10
- Forge:forge-1.7.10-10.13.4.1558-1.7.10-universal
- SpongeForge:No
- Optifine:Yes
- Single Player

**Comment by tyler489** [comment]
Something is disabling the exp liquid

**Comment by GhostShot3** [comment]
Is a mod conflict ?

**Comment by tyler489** [comment]
sorry though i responded here. Yes some mod is disabling the exp liquid that the experience obelisk needs

**Comment by GhostShot3** [comment]
Ok
