### ISSUE TITLE
Server nor Modpack won´t load Ender IO

### ISSUE THREAD

**Issue by BenjaminD-droid** [SleepyTrousers/EnderIO#5216]
#### Issue Description:

Server will stop starting & when i try to start the Modpack itself it wont start either but only when i add Ender IO.

#### What happens:

So i got my own Server from the ATLauncher and i added some Mods to the Modpack Mech&Magic Lite. When i tried to add Ender IO with the Endercore, both for the correct Version which is 1.12.2, the server will stop starting and the Modpack will crash as well when i try to start it. All other mods are working fine.

#### What you expected to happen:

Server and Modpack starting adn runninf fine with all other mods.

#### Steps to reproduce:

1.Download ATLauncher
2.Download Modpack Mech&Magic Lite for MC Version 1.12.2
3.Add the following mods which i added afterwards: Atum, buildcraft, Carpenter´s blocks v3.4.0, desertland, endercore, ender IO, huntingdimension, malisisblocks v6.1.0, malisiscore v6.5.1, malisisdoors v7.3.0, minecolonies-universal v0.8.7582, NetherEx, Optifine, RoguelikeDungeons v1.8.0, u_team_core v 2.2.4.107, useful_Backpacks v1.5.1.35, Xaeros-Minimap, YAMDA v1.0.2
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft:1.12.2
- Forge:
- SpongeForge? no
- Optifine? yes
- Single Player and Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/jn1GbPnx

**Comment by VT-14** [comment]
`   | LCHIJ | enderio                           | 5.0.25                   | Ender-IO-Mod-1.12.2.jar                            | None       `

Out of curiosity, where did you download that file?  5.0.25 is nearly 3 months old and had a file name of "EnderIO-1.12.2-5.0.25.jar"

Ender IO is public domain, so it's not illegal to rehost it, but whatever website you got that from is probably not trustworthy.

The 'official' public builds are uploaded to CurseForge, and the current version is 5.0.50.  https://www.curseforge.com/minecraft/mc-mods/ender-io

**Comment by LumberWizard** [comment]
3 months? You got the wrong year there :P

**Comment by VT-14** [comment]
Whoops.  A year + 3 months ago, so 15 months.  :P

**Comment by BenjaminD-droid** [comment]
I got it from http://www.9minecraft.net/ender-io-mod/
i will try to download a Version which is more uptodate

**Comment by VT-14** [comment]
Yeah, 9minecraft is one of many illegal rehost sites.  Refer to this list: https://github.com/StopModReposts/Illegal-Mod-Sites/blob/master/SITES.md

By downloading from a rehost site you are:
1) not supporting the mod author
2) risking someone slipping in something malicious
3) Are likely downloading an outdated version.

Most mod authors these days use Curseforge.  That should be your first stop when looking for new mods to add.

**Comment by BenjaminD-droid** [comment]
Thank you so so much <3
