### ISSUE TITLE
[Suggestion/Issue] Modular - Facade conduit unusable

### ISSUE THREAD

**Issue by lagonnebula** [SleepyTrousers/EnderIO#5217]
#### Issue Description:
Im using the modular installation of Ender IO with only Base, Conduit and TiC. 
We can't use Conduit facade without painting them but this machine is only on Ender IO Machines.
____
#### Affected Versions:
- EnderIO Base: 5.0.50
- EnderIO Conduit: 5.0.50
- Minecraft: 1.12

**Comment by tyler489** [comment]
https://minecraft.curseforge.com/projects/facade-painter

**Comment by lagonnebula** [comment]
@tyler489 Thank you ! I didn't saw it. 
But it would be great to have it in an "official" way

**Comment by tyler489** [comment]
sorry i should say Third Party not Unofficial
