### ISSUE TITLE
Console warns of debug options enabled when they aren't

### ISSUE THREAD

**Issue by katubug** [SleepyTrousers/EnderIO#5218]
#### Issue Description:
When starting up my server, I got the following notice:

```
[17:42:02] [Server thread/WARN] [enderio]: ========================================================
[17:42:02] [Server thread/WARN] [enderio]: == Debug Logging is ENABLED ============================
[17:42:02] [Server thread/WARN] [enderio]: ======================================================== 
[17:42:02] [Server thread/WARN] [enderio]: == This WILL slow down the game, so we recommend you  ==
[17:42:02] [Server thread/WARN] [enderio]: == disable it unless you need it. A log level of INFO ==
[17:42:02] [Server thread/WARN] [enderio]: == is enough for normal operation.                    ==
[17:42:02] [Server thread/WARN] [enderio]: ======================================================== 
``` 

However, I do not think I have anything enabled that shouldn't be? My config looks like this: https://pastebin.com/eGc6ML2Z

#### What happens:

As described above.

#### What you expected to happen:

I'd assume I wouldn't get this message, given that all config options are set to default?

#### Steps to reproduce:

1. Using version [1.6.0 of my modpack (EnthusiastiCraft)](http://enthusiasticraft.cf/modpack-update-1-6-0/#modlist), start server.
2. Observe console.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.50
- EnderCore: EnderCore-1.12.2-0.5.65
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2838-universal
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3513799/latest.log)
[debug.log](https://github.com/SleepyTrousers/EnderIO/files/3513800/debug.log)

**Comment by mindforger** [comment]
This is most likely an issue with your launcher command line and not your config, what launcher do you use?

**Comment by katubug** [comment]
I'm actually not sure how to answer that. The panel my server uses is Pterodactyl, and to the best of my knowledge it launches directly from the forge jar. Please let me know if that's not enough information.

**Comment by katubug** [comment]
Here are my startup arguments: `java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dio.netty.leakDetection.level=advanced -Dusing.aikars.flags=mcflags.emc.gs -jar custom.jar`

**Comment by mindforger** [comment]
The last part was what i meant, unfortunately i so not have the parameter at hand for the debug level, need to look it up

**Comment by katubug** [comment]
Thank you, will do!

**Comment by HenryLoenwind** [comment]
Sorry I'm late to this, but:

Have a look at your debug.log. See all those log messages with loglevel DEBUG and TRACE? All in all, the game had to write 30,000 entries per minute. That takes time, and at that volume it adds up.

**Comment by katubug** [comment]
Thank you for the response, and my apologies for the incorrect report. I'm not at all sure how I turned on debug logging, but I'll see if removing the `-Dio.netty.leakDetection.level=advanced` makes the difference. If that fails, I'll ask over at the ptero discord/github.

Thank you again for your help!

**Comment by tyler489** [comment]
nope thats suppost to be true... its the only one set that way

**Comment by Velocihater** [comment]
I’m having the same problem too...I’m using multimc

**Comment by katubug** [comment]
Hey, I wanted to update this - I genuinely think there is an issue with the later versions' configs not working correctly. I decided to see if the issue persisted in singleplayer, and it does.

I created a custom MultiMC instance with just Ender IO/Core, JEI, and The One Probe (in retrospect I did not need TOP or JEI, but I usually do when testing so I leave them in). In all instances, the MC version is 1.12.2 and the forge version is 2838. Between each test I completely deleted the `config` and `logs` folders to allow them to regen. I started the game up each time just to get the initializing logs, and then closed it without entering a world.

What I found was that Ender IO version 5.1.46 did not display the debug warning when paired with both EnderCore 0.5.68 and 0.5.69. All other versions of EnderIO did display the debug warning despite the configs presumably being the same, since they were always default. Additionally, while I didn't analyze the debug logs line-by-line, they were all slightly bigger during the "accidentally debugging" ones. It wasn't a huge difference, however.

Here is a zip of all my `latest.log` and `debug.log` from the tests I did: 
[enderio.zip](https://github.com/SleepyTrousers/EnderIO/files/3587225/enderio.zip)

**Comment by katubug** [comment]
One additional note - just tested it with my full modpack on my server, and the debug.log went from being 19mb to 6mb, when using 5.1.46 vs 5.1.50.

**Comment by geobr1990** [comment]
Just popping in to say that I too have been seeing this with newer versions of EnderIO/Core on both my personal server and single player worlds.

**Comment by Velocihater** [comment]
any update on this?

**Comment by nfrosa** [comment]
having the same issue, and my only command line args are -Xmx5120M -Xms512M -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512M. my debug.log is full of enderio messages, with the occasional FML message. makes me wonder if it's an enderio thing or a forge thing.

**Comment by nrgbistro** [comment]
I'm having the same message show up as well. Using the latest forge and EnderIO with MultiMC as my client. When I disable EnderIO on my server I notice a very marginal performance increase (and every bit counts here)

**Comment by Velocihater** [comment]
Same as well, load times also increase a lot

**Comment by dmb7116** [comment]
Hey for me this is still an ongoing issue. Cant find a place to disable debug mode and the debug logs show a lot of Ender IO. I have even tried disabling "B:debugProfilerAntiNuclearActivist=true" just to see if it did anything, and it did not remove messages.  Console also says "Debug Logging is ENABLED" like op stated.

**Comment by Trnrr** [comment]
Same issue for me. Nothing in diagnostics is set to true besides `B:debugProfilerAntiNuclearActivist=true` which is the default and above says it's suppose to be that way.

It still shows it even though it is disabled.
`[22:43:29] [Client thread/WARN] [enderio]: ========================================================
[22:43:29] [Client thread/WARN] [enderio]: == Debug Logging is ENABLED ============================
[22:43:29] [Client thread/WARN] [enderio]: ======================================================== 
[22:43:29] [Client thread/WARN] [enderio]: == This WILL slow down the game, so we recommend you  ==
[22:43:29] [Client thread/WARN] [enderio]: == disable it unless you need it. A log level of INFO ==
[22:43:29] [Client thread/WARN] [enderio]: == is enough for normal operation.                    ==
[22:43:29] [Client thread/WARN] [enderio]: ========================================================  `
My config:
https://gist.github.com/Trnrr/54f7eedc590c4724be10ed81b5b80c8c

**Comment by KiddieD** [comment]
Chiming in to add I am also experiencing this. Definitely not OP's fault.

**Comment by Matt4499** [comment]
Having same issue, it's debugging everything causing mass server lag. All configs were left at default. Forge 1.12.2

**Comment by katubug** [comment]
@HenryLoenwind - sorry to ping but would you consider removing the "invalid" tag from this issue, in light of my findings and the additional reports?

Thanks for your time!

**Comment by HenryLoenwind** [comment]
This still is invalid. It doesn't matter that Forge has trace level debugging enabled by default---that doesn't make a message telling you about it a bug.

**Comment by katubug** [comment]
May I ask why this only occurs with newer versions of EnderIO, then? And if you happen to know how to change debugging level in forge, I'd appreciate the help. I attempted the logging.properties fix (I think I linked above) but it didn't work. I couldn't find another method.

**Comment by Trnrr** [comment]
Is this something relating to enderio or forge? I will check forge configs when I get home but is the error saying that you should disable forge debug logging? If its something relating to forge and enderio is just telling us the message should be more clear.. and if you think its clear enough it's obviously not since everyone is posting here confused about it.

**Comment by KiddieD** [comment]
In case enderIO is the only mod warning us of this actually forge debugging, should this be referenced on the forge forums? 

I've checked my forge configuration and can't find a debugging option. Perhaps forge has done an oopsie.

**Comment by katubug** [comment]
I couldn't find any similar issues in the forge github, so I filed one myself. Hopefully we can get to the bottom of this!

**Comment by pau101** [comment]
I would consider the existence of this warning a bug. Debug mode being enabled has been standard configuration for some time, there should be no reason for EnderIO to complain. The reason this only started occurring with newer versions is because that is when this "warning" was added.

Now, something I did notice while checking out the logging EnderIO does, is it specifically does less efficient logging by its own wrapper [Log](https://github.com/SleepyTrousers/EnderIO/blob/73d4d8d77ad1db524da0b67b9b0e87969a4765d8/enderio-base/src/main/java/crazypants/enderio/base/Log.java) class that introduces unnecessary object allocation which normal operation of Log4J does not do any of (zero GC is one of Log4J's selling points). The logging statements present in EnderIO should be using builtin parameter substitution and zero string concatenation, e.g. `LOGGER.debug("answer: {}", 42)`. Granted though, the extent to which this impacts performance pales in comparison to average game code, but if this "warning" is given I would at least expect logging best practices to be followed.

**Comment by DylanHameleers** [comment]
Not trying to necro an old thread, but I have the same issue and I'm wondering if you managed to fix it?

**Comment by Rsslone** [comment]
Same here, I am not sure what this means I'm looking for this debug to disable it, but I can't find it.

**Comment by pau101** [comment]
There is no issue with your game, it is safe to ignore this "warning", it's just simply unfounded complaining.

**Comment by DylanHameleers** [comment]
It was concerning me because of performance and the space log files take, but okay I'll just ignore it then I guess

**Comment by pau101** [comment]
Oh you're totally fine to want to configure logging differently, it just has nothing to do with EnderIO. But I really would not advise disabling debug mode, unless you don't mind being unable to provide meaningful information for bug reports.
