### ISSUE TITLE
Lightning Issue light come through, Mobs Spawn inside colored stairs / blocks

### ISSUE THREAD

**Issue by Caaruzo** [SleepyTrousers/EnderIO#5219]
#### Issue Description:
After i painted stairs or Steps with Marble from project Red or Basalt from ProjectRed there come light still through. There also spawn mobs sometimes in thoose stairs, cause i cant light up the face below the stair. but if i use F7 i can see red lined below the stairs. 

#### What happens:

Light come through painted Stairs or steps

#### What you expected to happen:

that light dont come through painted blocks and mobs dont spawn half inside steps.

#### Steps to reproduce:

1. Paint a unpainted Step (for example stone slap step) with ProjectRed Marble
2. Place step inworld
3. wait until mob spawns or use F7 amd look a bit arround to see the red mark below the stair.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.50.jar
- EnderCore: EnderCore-1.12.2-0.5.65
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2838-universal
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

nothing in log to see cause it dont cause any errors or outputs.

**Comment by Caeas** [comment]
Got it to make some screenshots now. Thats the inside of my house where is used a stone slap as decoration for outside.

![Inside](https://user-images.githubusercontent.com/39491096/63381010-14079f80-c398-11e9-9d13-70cbdf76c773.png)

Thats the Outside. Below painted stairs or slaps is always dark, and it cant be lighten up in any way. The Mobs spawn also inside thoose blocks.

![Outside](https://user-images.githubusercontent.com/39491096/63381011-14079f80-c398-11e9-833d-0f5db5ffdc71.png)

I hope that helps a bit more as reference :)
