### ISSUE TITLE
Removing redstone filter does not remove effects

### ISSUE THREAD

**Issue by mifrai** [SleepyTrousers/EnderIO#5221]
#### Issue Description:

Only tested with the NOT filter. Adding the filter to a redstone output and then removing it will not remove the effects of the filter.

#### What happens:

When removing the NOT filter from a redstone output, the signal continues to have NOT applied.

#### What you expected to happen:

When removing the NOT filter from a redstone output, the signal goes back to normal.

#### Steps to reproduce:

1. Set up a lever -> conduit -> 2 outputs: ![Setup](https://user-images.githubusercontent.com/1335923/63487973-0c143200-c462-11e9-88bc-64772b593e9e.PNG)
2. Add the NOT filter to one output
3. Remove the NOT filter
4. Toggle the lever, observe

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.50
- EnderCore: 1.12.2-0.5.65
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single player

#### Your most recent log file where the issue was present: 

https://gist.githubusercontent.com/mifrai/6bae5e961a7c653ce2597266dff584e5/raw/07e8ff535606cf45b1b4641f93cdf2227c67a47d/gistfile1.txt

**Comment by tyler489** [comment]
Related #5206
