### ISSUE TITLE
Redstone can lock a conduit to always output signal

### ISSUE THREAD

**Issue by mifrai** [SleepyTrousers/EnderIO#5222]
#### Issue Description:

When the following is true:
* a redstone is placed next to a redstone conduit 
* the conduit's input/output is set to the same channel
* a positive redstone signal is put into that channel

That channel on the conduit gets locked into the on state.

See the example screenshot. The top is the setup. The bottom is example of the broken state where all red stone inputs are removed. 
![Capture2](https://user-images.githubusercontent.com/1335923/63488886-56e37900-c465-11e9-8794-260f047e7e95.PNG)

#### What happens:

When the source redstone signal is removed, you still get a signal on the channel -- even if all signals are removed.

#### What you expected to happen:

When the source redstone signal is removed, you stop getting a signal on the channel.

#### Steps to reproduce:

1. Add a conduit to the world
2. Add a redstone, connected to the conduit
3. Enable input and output on the conduit, change to use the same channel
4. Add a redstone torch and make sure the conduit inputs to the same channel
5. Remove the redstone torch
6. All output on that channel will now be 'on'

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.50
- EnderCore: 1.12.2-0.5.65
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single player

#### Your most recent log file where the issue was present: 

https://gist.githubusercontent.com/mifrai/6bae5e961a7c653ce2597266dff584e5/raw/07e8ff535606cf45b1b4641f93cdf2227c67a47d/gistfile1.txt

**Comment by tyler489** [comment]
May relate to #5206
