### ISSUE TITLE
Refined Storage conduit import-filter only working when matching the slot position 

### ISSUE THREAD

**Issue by swannet** [SleepyTrousers/EnderIO#5223]
#### Issue Description:
The import-filter of the RS-conduits are not processing (importing) items if the slot position does not match between the inventory importing from and the filter.

Here are some screenshots form my setup
![2019-08-23_06 27 51](https://user-images.githubusercontent.com/550021/63567584-80d69180-c572-11e9-809c-36b0841c699b.png)
![2019-08-23_06 27 56](https://user-images.githubusercontent.com/550021/63567596-8e8c1700-c572-11e9-8675-f4f06d2359c1.png)
![2019-08-23_06 28 21](https://user-images.githubusercontent.com/550021/63567601-921f9e00-c572-11e9-85ed-f58bb98b2d10.png)
Where I change the order of the items the import is not working
![2019-08-23_06 28 30](https://user-images.githubusercontent.com/550021/63567604-93e96180-c572-11e9-994f-a8ee663477ae.png)

If needed I can provide my world.

Possibly related to:
#5053 and/or  #4904 

#### What happens:
When I’ve set an import-filter the RS-conduit only process importing when the slot position in the filter matches the postion of the item in the inventory

#### What you expected to happen:
When I’ve set an import-filter I expect the RS-conduit import the items specified in the filter regardless of the slot position  

#### Steps to reproduce:
1. Setup a basic RS-network (power, RS controller, RS StorageBlock, eventually a grid to show items in network) and place a chest nearby
2. Attach a EnderIO RS-Conduit between the chest and the RS-network
3. Add a Ender OI-filter to the import slot
4. Add 3 items to the filter (lets say dirt, sand, cobblestone) in position 1, 2 and 3
5. Add  Dirt, Sand and Cobble to the chest (in slot 1: Dirt, 2: Sand, 3: Cobble)
6. See the items are imported to the RS-network
7. Add Sand, Cobble, Dirt to the chest (in slot 1: Sand, 2: Cobble, 3: Dirt)
8. See the items are not importing to the RS-network
9. Move the items (in slot 1: Dirt, 2: Sand, 3: Cobble)
10. See the items are importing now

____
#### Affected Versions (Do *not* use "latest"):
* EnderIO: EnderIO-1.12.2-5.0.50
* EnderCore: EnderCore-1.12.2-0.5.65
* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* SpongeForge? no
* Optifine? no
* Single Player and/or Server? Single player and Server

#### Your most recent log file where the issue was present: 
https://gist.github.com/swannet/32c1abd6c2d9a52a11e224b988246a6e

**Comment by tyler489** [comment]
definitly #5053

**Comment by swannet** [comment]
Side note: it is not only the advanced filter that have this problem. All the item filters have the same behaviour

**Comment by MaximumPotato** [comment]
Hey so I've noted something similar, but I am not sure if it's effectively the same thing you are experiencing or if I should open a new issue. When comparing the Refined Storage conduit and the regular EnderIO Item Conduit, the Refined Storage conduit feels like it operates as a First In, First Out item stack which grabs import-filtered items from the Refined Storage network in a random order. If there's no space in the destination inventory for the first item that was pulled out, item transfer stops completely.

In comparison, the EnderIO "Item Conduit" cables do not appear to share this behavior, and fill all slots as space becomes available.

I'm completely exhausted so not 100% sure if we're experiencing the same issue and I just misinterpreted what I've been seeing. Will have to test tomorrow.
