### ISSUE TITLE
Disable block

### ISSUE THREAD

**Issue by MrByryndyk** [SleepyTrousers/EnderIO#5225]
#### Issue Description:
Is it possible to completely disable the unit in the configuration

#### What happens:
I need to disable some scam for my modpack. But I did not find this function in the configurations

#### What you expected to happen:
Something like this in the configuration file:
Alloy_Smelter_Enable = true/false
Sag_Mill_Enable = true/false
...
I need only Painter from "Ender IO Machines" module.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO Base: 5.0.50 
- EnderIO Machines: 5.0.50
- EnderCore: 0.5.65
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player and Server

#### Your most recent log file where the issue was present:

**Comment by MatthiasMann** [comment]
You can disable the recipes in the config folder.
Or you could use https://www.curseforge.com/minecraft/mc-mods/facade-painter and remove the machine module instead.

**Comment by MrByryndyk** [comment]
Oh, that's what I need. Thank you very much.
