### ISSUE TITLE
cant export using refined storage ender io cable

### ISSUE THREAD

**Issue by flamingram** [SleepyTrousers/EnderIO#5228]
#### Issue Description:

trying to export ore from my system 

#### What happens:

nothing
#### What you expected to happen:

to export my ores

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.12.2-5.0.46.jar
- EnderCore:EnderCore-1.12.2-0.5.59.jar
- Minecraft:1.12.2
- Forge:forge-14.23.5.2838
- SpongeForge? NO
- Optifine? NO
- Server
![2019-08-28_13 29 06](https://user-images.githubusercontent.com/34726796/63890712-64828c80-c998-11e9-9cc3-b6df07363c74.png)
![2019-08-28_13 29 08](https://user-images.githubusercontent.com/34726796/63890732-6ea48b00-c998-11e9-9096-43015e104ca8.png)
![2019-08-28_13 29 11](https://user-images.githubusercontent.com/34726796/63890734-706e4e80-c998-11e9-9144-782b49054d48.png)

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
one or more of #5223, #5073, #4904, #5053, #5334
