### ISSUE TITLE
Missing recipe for Thaumaturge Boot upgrade

### ISSUE THREAD

**Issue by magerooster** [SleepyTrousers/EnderIO#5229]
#### Issue Description:

As simple as that. The recipe to combine the blank dark steel upgrade with the thaumaturge's boots is missing. (It's just fine for the chest and legs)

#### What happens:

https://imgur.com/a/7PSkq2p

#### What you expected to happen:

https://imgur.com/WUy2JrX

#### Steps to reproduce:

1. Attempt to craft 'Dark Steel Upgrade "Thaumaturge's Boots"'
2. ...
3. Profit!
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.50
- EnderCore: 1.12.2-0.5.65
- Minecraft: 1.12.2
- Forge: 14.23.5.2844
- SpongeForge? NO
- Optifine? NO
- Single Player and/or Server? Both SP and MP.

- Thaumcraft: 1.12.2-6.1.BETA26

#### Your most recent log file where the issue was present: 

https://pastebin.com/3vjcc959

**Comment by HenryLoenwind** [comment]
-> #5209
