### ISSUE TITLE
Duplication Glitch with Dark Anvil and Dark Paper Anvil

### ISSUE THREAD

**Issue by piisfun** [SleepyTrousers/EnderIO#5230]
Removing Items from output slot of Dark Paper Anvil via Shift-Click results in inputs not being removed.
Immediately exiting the anvil interface results in the inputs being returned to the inventory, leaving two copies of the item, one processed, the other not.

Works with both Dark Anvil and Dark Paper Anvil.

EnderIO 1.12.2-5.1.51

EnderCore 1.12.2-0.5.67

Forge 14.23.5.2844

Version 1.12.2

**Comment by tyler489** [comment]
@HenryLoenwind Might want to look this over again. seems it didnt work https://github.com/SleepyTrousers/EnderIO/commit/48e6fcca41688ba564ed877b16ea330c70c47dcb

**Comment by HenryLoenwind** [comment]
tyler, those are different slots.

**Comment by piisfun** [comment]
This only works on when **shift-clicking** the anvil output.  Both inputs are left in the input slots, and can be removed either manually or by closing the interface.

i.e. putting in one enchantment book and an **unenchanted** diamond sword will yield one **unenchanted** diamond sword, one **enchanted** diamond sword, and one enchanted book.

**Comment by HenryLoenwind** [comment]
yes, that output slot is one of the few slots that does something when its content is removed. I think I found the code that removes the stack when shift-clicking and does not tell the slot about it.

**Comment by HenryLoenwind** [comment]
Note that is is an endercore issue, so you need to update endercore.
