### ISSUE TITLE
EnderIO creates many empty OreDictionary entries

### ISSUE THREAD

**Issue by OneEyeMaker** [SleepyTrousers/EnderIO#5231]
#### Issue Description:

While parsing recipes EnderIO creates many empty OreDictionary entries. 
I assume, that the cause is usage of ```OreDictionary.getOres(String)``` instead of ```OreDictionary.getOres(String, boolean)```. (The first method creates empty entry, if fails to find existing one; second method just returns existing entry when second argument is ```false```).

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.51
- EnderCore: 0.5.68
- Forge: 1.12.2 - 14.23.5.2844

**Comment by HenryLoenwind** [comment]
This is necessary so the recipes using those oredict entries work if another mod adds items into them later in the startup process.
