### ISSUE TITLE
[18:36:05] [Netty Client IO #0/INFO] [FML]: Rejecting connection SERVER: Ender IO: Failed mod's custom NetworkCheckHandler FMLMod:enderio{5.1.51}

### ISSUE THREAD

**Issue by BedrockLegends** [SleepyTrousers/EnderIO#5234]
#### Issue Description:
[18:36:05] [Netty Client IO #0/INFO] [FML]: Rejecting connection SERVER: Ender IO: Failed mod's custom NetworkCheckHandler FMLMod:enderio{5.1.51}
Ender IO Applied Energistics Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsappliedenergistics{5.1.51}
Ender IO Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduits{5.1.51}
Ender IO Integration with Forestry: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationforestry{5.1.51}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationtic{5.1.51}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationticlate{5.1.51}
Ender IO Machines: Failed mod's custom NetworkCheckHandler FMLMod:enderiomachines{5.1.51}
Ender IO Open Computers Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsopencomputers{5.1.51}
Ender IO Powertools: Failed mod's custom NetworkCheckHandler FMLMod:enderiopowertools{5.1.51}
Ender IO Refined Storage Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsrefinedstorage{5.1.51}
Ender IO Zoo: Failed mod's custom NetworkCheckHandler FMLMod:enderiozoo{5.1.51}
Ender IO endergy: Failed mod's custom NetworkCheckHandler FMLMod:enderioendergy{5.1.51}
[18:36:05] [Netty Client IO #0/INFO] [FML]: Rejecting connection SERVER: Ender IO: Failed mod's custom NetworkCheckHandler FMLMod:enderio{5.1.51}
Ender IO Applied Energistics Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsappliedenergistics{5.1.51}
Ender IO Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduits{5.1.51}
Ender IO Integration with Forestry: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationforestry{5.1.51}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationtic{5.1.51}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationticlate{5.1.51}
Ender IO Machines: Failed mod's custom NetworkCheckHandler FMLMod:enderiomachines{5.1.51}
Ender IO Open Computers Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsopencomputers{5.1.51}
Ender IO Powertools: Failed mod's custom NetworkCheckHandler FMLMod:enderiopowertools{5.1.51}
Ender IO Refined Storage Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsrefinedstorage{5.1.51}
Ender IO Zoo: Failed mod's custom NetworkCheckHandler FMLMod:enderiozoo{5.1.51}
Ender IO endergy: Failed mod's custom NetworkCheckHandler FMLMod:enderioendergy{5.1.51}

#### What happens:

Comes up inside log file, so not sure if its broken or meant to be there

#### What you expected to happen:

A fix for it, if its a bug

#### Steps to reproduce:
There is none as I found it in a log file
1. 
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  1.12.2-5.1.51
- EnderCore: 1.12.2-0.5.68
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2844
- SpongeForge? yes/no no
- Optifine? yes/no no
- Single Player and/or Server? not sure but found on a single player log

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Complain to Forge that we are not allowed to present your with a readable error message like "Cannot connect to a server that doesn't have Ender IO installed".
