### ISSUE TITLE
Server crash while shift-right clicking dark steel upgrade onto boots

### ISSUE THREAD

**Issue by shroomdog27** [SleepyTrousers/EnderIO#5237]
#### Issue Description:
While trying to shift click a dark steel upgrade onto a pair of ender boots while using a dark steel anvil, the server crashes. Placing the upgrade onto the anvil with the normal drag and drop mechanic does not crash the server. This crash does not happen in single player.

#### What happens:
The server crashes.

#### What you expected to happen:
The server to not crash.

#### Steps to reproduce:

1. Get a dark steel anvil, ender boots, and any upgrade card.
2. Place the anvil and go to the tab to apply the upgrade.
3. Attempt to apply the upgrade by shift right clicking the upgrade onto the anvil.
4. Server will crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.51
- EnderCore: EnderCore-1.12.2-0.5.68
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2846
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server Only

#### Your most recent log file where the issue was present: 

Server Crash Report: https://pastebin.com/U0QMcLyj

#### Additional Information (Edited in later)
In a setting with just enderio and endercore (still using forge1.12.2-14.23.5.2846), the server does not crash. Instead, it prints a similar error in the log without crashing.

https://pastebin.com/fBq550GZ

**Comment by shroomdog27** [comment]
Using the latest version of endercore, the shift click issue is fixed for inserting filters in fluid conduits. For using the dark steel anvil and upgrades, the game no longer crashes but upgrades still aren't inserted into the slot.

**Comment by HenryLoenwind** [comment]
I know. That requires an Ender IO upgrade, I had to adapt the GUI to what I had to change in the library.
