### ISSUE TITLE
Ender IO Painted Facade missing texture using carpet and chisel blocks

### ISSUE THREAD

**Issue by EconBrony** [SleepyTrousers/EnderIO#5239]
#### Issue Description:

Ender IO Painted Facade missing texture using carpet and chisel blocks

#### What happens:
When block is placed on conduit on anywhere in the world the conduit 

#### What you expected to happen:
The facade to show the texture of the block I painted it with

#### Steps to reproduce:

1. Painted Facade
2. Placed over conduit or in world
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.51
- EnderCore: 1.12.2-0.5.69
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Server

#### Your most recent log file where the issue was present: 

Screen Shot: https://i.imgur.com/3QK30bj.png

https://drive.google.com/file/d/16Y-Yg0Smr0TKjwxgC3VE5v4-ddTGDDg5/view?usp=sharing

**Comment by tyler489** [comment]
#4876
