### ISSUE TITLE
Recipe error message when updating to 5.1.51

### ISSUE THREAD

**Issue by Boolyman** [SleepyTrousers/EnderIO#5240]
#### Issue Description:
Previously working user recipe file is now throwing an error message when updating to 5.1.51 
Recipe file:   https://pastebin.com/PZPwp62A

![2019-09-08 23_15_52-Greenshot](https://user-images.githubusercontent.com/24765883/64503075-fd65b180-d28e-11e9-9555-3e7c850047b9.png)

#### What happens:

Previously working user recipe file is now throwing an error message when updating to 5.1.51

#### What you expected to happen:

For the previously working user recipe file not to cause an error message after updating to 5.1.51

#### Steps to reproduce:

1. Have previously working user recipe XML
2. Update to EnderIO version 5.1.51
3. Get error message when launching modpack.
4. Regret yet again having issues with the XML file configs.
...

____
#### Affected Versions (Do *not* use "latest"):

EnderIO: 1.12.2-5.1.51
EnderCore: 1.12.2-0.5.69
Minecraft: 1.12.2
Forge: forge-14.23.5.2838
SpongeForge? no
Optifine? no
Single Player and/or Server? both

#### Your most recent log file where the issue was present: 

https://pastebin.com/m6yrJfeX

**Comment by MatthiasMann** [comment]
The "<?xml " at line 166 is invalid XML. This must have created an error also in the previous version.

**Comment by HenryLoenwind** [comment]
Actually, the old versions ignored everything after the `</recipes>`. There should be a bug report about that around somewhere...
