### ISSUE TITLE
[suggestion] Redstone Filters "level emitter" 

### ISSUE THREAD

**Issue by CarpentierMartin** [SleepyTrousers/EnderIO#5241]
A nice addition would be to have a filter (input ?) acting in a similar way to a Level Emitter from [AE2](https://ae-mod.info/ME-Level-Emitter/).

It would be kinda like a Inventory Sensor Filter but instead you could set an inventory level limit and it would emit a redstone signal (or not) based on that limit.

For exemple if you connect a Redstone Conduit to a Drawer filled with cobblestone and put a "level emitter" filter in it, you could set it to emit a signal if it contains 1000 or more cobblestone.

I'm guessing it depends on what info is available from the Drawer (or any other inventory).

**Comment by tyler489** [comment]
There is the comparator filter but you can't specify quantity it works just like vanilla comparators

**Comment by HenryLoenwind** [comment]
Also, there's a level emitter in the (unfinished) Inventory Panel package.
