### ISSUE TITLE
Telepad Crashes Server after teleport

### ISSUE THREAD

**Issue by Siiriiks** [SleepyTrousers/EnderIO#5243]
#### Issue Description:

Telepad crashes Server and Client using it.

#### What happens:

After teleporting to the location the Server crashes and so does the Client who used the teleporter. Nobody else on the server crashes.

#### What you expected to happen:

The Client to teleport to the location safely.

#### Steps to reproduce:

1. Set the coordinates to the Telepad to a different dimension.
2. Use the Telepad
3. After about 2 seconds they crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.50
- EnderCore: 0.5.69
- Minecraft: 1.12.2
- Forge: 1.12.2 14.23.5.2846
- SpongeForge: spongeforge-1.12.2-2838-7.1.7-RC3910
- Optifine: HD_U_E3
- On a Server

#### Your most recent log file where the issue was present: 

[https://pastebin.com/fURdHz3r](url)

**Comment by tyler489** [comment]
Please report this to Better portals that crash is 100% caused by them and or sponge
