### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by drago87** [SleepyTrousers/EnderIO#5246]
When adding NoCubes to a modpack i'm working on with ender io the game crashes

OpenEye Crash report
https://openeye.openmods.info/crashes/761a73e8b69462d73d6818944c937b62

Vanilla Crash report
[crash-2019-09-14_17.32.30-client.txt](https://github.com/SleepyTrousers/EnderIO/files/3612882/crash-2019-09-14_17.32.30-client.txt)

Posted here becouse ender io was reported as the culprit by OpenEye
I will also post  this at the NoCube github to as that was the mod added.

**Comment by tyler489** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/6148
