### ISSUE TITLE
Port wont open

### ISSUE THREAD

**Issue by BenjaminD-droid** [SleepyTrousers/EnderIO#5247]
#### Issue Description:

So i got a minecraft server with some friends, now i transfered all the files to another friend so he can host it. Now we set up the port forwarding but it wont work.

#### What happens:

Server is starting, he can join if he types in his private ip adress (10.0.0.19).
I checked if the port was open via the site https://canyouseeme.org/ and it said that it is closed so i oppened it in the firewall aswell, which didnt change anything

#### What you expected to happen:
Everyone shoulb be able to join the server, not only the host

#### Steps to reproduce:

cant realy reproduce because the same files with the same configuration worked on the other pc which worked as the host before

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.12.2
- Forge:
- SpongeForge? yes/no
- Optifine? yes
-  Server

#### Your most recent log file where the issue was present: 

dont have one bcs the only problem is the port which jsut wont open

**Comment by SplitInfinitive** [comment]
Not an EIO problem.  Not a minecraft problem.

Your Firewall/Router is not configured correctly, I suggest googling how to port forward for your specific operating system/firewall/router.

**Comment by BenjaminD-droid** [comment]
i know that it's a Problem with the Firewall or Router, as i wrote, the Port isnt open, but i succesfully made a portforwarding like 10 Times, but now it Just wont work but i did it excactly the same way

**Comment by CitiesXL2815** [comment]
dude do not report server issue in less something do with EIO

**Comment by HenryLoenwind** [comment]
This has absolutely nothing to do with Ender IO.
