### ISSUE TITLE
onBlockHarvest error

### ISSUE THREAD

**Issue by clienthax** [SleepyTrousers/EnderIO#5248]
#### Issue Description:

Following appears in log
https://pastebin.com/raw/6YwtEvkM

#### What you expected to happen:
No errors in the log :')

#### Steps to reproduce:

Unknown at this point.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.50.jar
- EnderCore: EnderCore-1.12.2-0.5.65.jar
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2838-universal.jar
- SpongeForge? spongeforge-1.12.2-2838-7.1.7-RC3886.jar
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 
https://pastebin.com/raw/6YwtEvkM

**Comment by tterrag1098** [comment]
Reproduce on latest version.

**Comment by Tfarcenim** [comment]
I blame spongeforge

**Comment by HenryLoenwind** [comment]
That's a bug in whatever block you are harvesting. They are dropping an unmodifiable list of items, which is not valid.
