### ISSUE TITLE
Glowstone Nano-Particles

### ISSUE THREAD

**Issue by xordac** [SleepyTrousers/EnderIO#5249]
#### Issue Description:

Maybe I just don't know how. I do like the awesome new particles, but is there a way to remove them from the area once they have been applied?

#### What happens:
After applying Glowstone Nano-Particles area gets lit up.

#### What you expected to happen:
Would be good to have a way to remove them once they are applied.

#### Steps to reproduce:

1. Make the particles
2. Apply the particles
3. Attempt to remove
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.51
- EnderCore: EnderCore-1.12.2-0.5.68
- Minecraft: 1.12.2
- Forge: 2846
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 
Not Applicable

**Comment by tyler489** [comment]
If i remember correctly you can wash them away with water.
