### ISSUE TITLE
Ender Leggins Speed Upgrade can't be toggled with hotkey

### ISSUE THREAD

**Issue by bogstefan** [SleepyTrousers/EnderIO#5250]
#### What happens:
When setting the hotkey for "speed" under controls, a text popup appears, notifying that the speed upgrade is enabled/disabled. But this has no effect, since the speed upgrade is always active. It works on night vision, step assist, jump though.

#### What you expected to happen:
Toggling speed

#### Steps to reproduce:
1. Set hotkey for speed
2. Press hotkey
3. Run

____
#### Affected Versions
- EnderIO: 1.12.2-5.1.51
- EnderCore: 1.12.2-1.9.452
- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single Player

**Comment by weightmaker** [comment]
Works flawlessly on version 5.1.52 for me atleast. im even using custom mouse buttons which generally is the most unreliable keybinds. 
are you sure its not a keybind conflict?
