### ISSUE TITLE
Vacuum chest causing lags

### ISSUE THREAD

**Issue by TriADeX** [SleepyTrousers/EnderIO#5252]
**Issue Description:**
Vacuum chest causing lags
Screens 
https://i.ibb.co/y5Qcwr7/javaw-2019-09-18-18-36-31-842.jpg
https://i.ibb.co/4JxFRNs/javaw-2019-09-15-19-37-42-610.jpg

**What you expected to happen:**
No errors

**Steps to reproduce:**
Unknown. :(

**Affected Versions:**
EnderIO - EnderIO-1.12.2-5.1.51
EnderCore - EnderCore-1.12.2-0.5.69.jar
Minecraft - 1.12.2
Forge - forge-1.12.2-14.23.5.2847-universal.jar
SpongeForge? - spongeforge-1.12.2-2838-7.1.7-RC3924.jar
Optifine? - no
Single Player and/or Server? - server

**Comment by tyler489** [comment]
Try using the vanilla profiler

Vanilla's profiler is ran using /debug start, waiting a few minutes (while somewhere where the game is lagging), and then /debug stop.  It creates a text file in a debug folder in the pack instance folder.
