### ISSUE TITLE
Farming Station consumes saplings without planting when hoe is not present

### ISSUE THREAD

**Issue by Sibusten** [SleepyTrousers/EnderIO#5253]
#### Issue Description:
If a hoe is not present when using the Farming Station to farm trees, the Farming Station will still use up the saplings from the seed slots, but no trees will be planted.

#### What happens:
Saplings are consumed when they aren't planted

#### What you expected to happen:
Saplings should not be consumed unless they are planted

#### Steps to reproduce:

1. Set up Farming Station with power and capacitor (I had double-layer)
2. Add saplings, but do not add a hoe
3. Farming station will use up saplings, but no trees are planted
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.51
- EnderCore: 1.12.2-0.5.69
- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- SpongeForge: no
- Optifine: no
- Server

**Comment by roboderpy** [comment]
How is this still not fixed

**Comment by tehbookseller** [comment]
Still not fixed. I have been using the Farming Station for years and never encountered this issue. I have a setup that feeds saplings into my station, and I've lost thousands of saplings at this rate.

**Comment by jk1895** [comment]
Also, it uses two saplings for one plant. One stack (64) saplings gives only 32 trees.

**Comment by HenryLoenwind** [comment]
Oops, forgot to tag this one.

I'll have a look at the double use tonight, that's a new lead.

**Comment by jk1895** [comment]
Hello,
I can reproduce the both bugs easily in a fresh installation with these mods:
https://imgur.com/a/IDSPrz1
Greetings

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/70669510-e7450400-1c76-11ea-8dec-bcdc2b953031.png)

um, the *tree farming code* is fine...

**Comment by jk1895** [comment]
Sorry, but when will you fix this nasty bug? It's so annoying!
