### ISSUE TITLE
quite clear glass painted stairs are not transparent.

### ISSUE THREAD

**Issue by jgilmore** [SleepyTrousers/EnderIO#5254]
#### Issue Description:

Quite clear glass painted stairs are not even transparent, much less quite clear.
![2019-09-20_09 02 55](https://user-images.githubusercontent.com/424437/65350889-fe0e1a00-dba3-11e9-8149-192bbf90f438.png)

#### What happens:

quite clear glass painted stairs are not even transparent, much less quite clear. Normal glass painted stars, OTOH, are transparent as expected. See screenshot.

#### What you expected to happen:

I expected them to be transparent, AND have join lines erased to be invisible just like quite clear glass.

#### Steps to reproduce:

1. Make quite clear glass & regular glass.
2. Make cobblestone stairs.
3. Put both in painting machine, and paint stairs with some of each type of glass.
4. Place anywhere, and observe that the clear stairs are flat grey instead of clear, and the normal glass stairs look correct.

I'm assuming here since this is ALL enderIO stuff, it's *probably* not dependent on other mods. I would test a more recent version of enderIO, but other mods don't work with recent versions of forge, etc. It gets complicated. And it's so simple to reproduce I figured I'd just hand it off, and if it's not an issue in recent versions, then good.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.12.2-5.0.35.jar
- EnderCore:EnderCore-1.12.2-0.5.41.jar
- Minecraft: 1.12
- Forge: forge-1.12.2-14.23.4.2705
- SpongeForge? No
- Optifine? yes
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 

No crash, visual glitch only.

Complete mod list:
ae2stuff-0.7.0.4-mc1.12.2.jar
AkashicTome-1.2-10.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
appliedenergistics2-rv5-stable-11.jar
astralsorcery-1.12.2-1.9.4.jar
AutoRegLib-1.3-20.jar
badwithernocookiereloaded-1.12.2-3.1.14.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
BloodMagic-1.12.2-2.3.3-101.jar
Botania+r1.10-362.jar
CodeChickenLib-1.12.2-3.2.0.345-universal.jar
CoFHCore-1.12.2-4.5.2.19-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
CookingForBlockheads_1.12.2-6.4.65.jar
CraftTweaker2-1.12-4.1.11.jar
CustomOreGen-1.12-1.8.1.jar
DummyCoreUnofficial-2.4.112.5.jar
EnderCore-1.12.2-0.5.41.jar
EnderIO-1.12.2-5.0.35.jar
extrautils2-1.12-1.9.4.jar
ExtremeReactors-1.12.2-0.4.5.49.jar
forestry_1.12.2-5.8.1.322.jar
furniture-5.13.0-1.12.2.jar
gravestone-1.10.1.jar
Guide-API-1.12-2.1.6-61.jar
InventoryTweaks-1.63.jar
jei_1.12.2-4.12.1.217.jar
LibEx-1.12.2-1.0.8.jar
MagicBees-1.12.2-3.1.10.jar
Mantle-1.12-1.3.2.24.jar
mcjtylib-1.12-3.0.5.jar
mystcraft-1.12.2-0.13.6.00.jar
mysticallib-1.12.2-1.3.7.jar
MysticWorld-1.12.2-1.4.4.jar
OptiFine_1.12.2_HD_U_E2.jar
Pam's+HarvestCraft+1.12.2zf.jar
Patchouli-1.0-20.jar
ProjectE-1.12-PE1.3.1B.jar
Psi-r1.1-62.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
roots-2-0.104.jar
Ruins-1.12.2.jar
Tainted-Magic-r7.82.jar
Thaumcraft-1.12.2-6.1.BETA25.jar
thaumicbases-3.2.265.4r-BBF.jar
ThaumicEquivalence-1.12.2-1.0.5.jar
ThaumicJEI-1.12.2-1.5.3-20.jar
ThermalDynamics-1.12.2-2.5.1.14-universal.jar
ThermalExpansion-1.12.2-5.5.0.29-universal.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar
Treecapitator-1.12-at_0.9a.jar
twilightforest-1.12.2-3.8.689-universal.jar
WIT-1.12-1.0.24-43.jar
Xaeros_Minimap_1.18_Forge_1.12.jar
zerocore-1.12-0.1.2.2.jar

**Comment by tyler489** [comment]
Does this occur without optifine?

**Comment by HenryLoenwind** [comment]
Does this occur with an Ender IO version that's not 11 months old?
