### ISSUE TITLE
Camera Issues (Carry On)

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [SleepyTrousers/EnderIO#5256]
#### Issue Description:

(with carry on mod)
When I Grab Any Entity On Telepad, Camera Issues Happen For 1 Minecraft Tick Before Being Normal again, Sometimes CRASH!

#### What happens:

If Grab Any Entity on Telepad Block, Camera Issues Happen For 1 Minecraft Tick Before Being Normal again, Sometimes CRASH!

#### What you expected to happen:

If Grab Any Entity on Telepad Block, It will Teleport With You

#### Steps to reproduce:

1. Build The Telepad (3x3)
2. Put Command Block At North Side of Telepad
3. Put the Stone Pressure Plate At Bottom of Telepad
4. Type On Command Block Like This "clone ~ ~-1 ~2 ~ ~-1 ~2 ~ ~1 ~1"
5. Put Any Entity On Stone Pressure Plate (top)
6. Do That Grab

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 04/08/2019
- EnderCore: 19/08/2019
- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

No CRASH = No Log

**Comment by tyler489** [comment]
There should still be a log in the logs folder.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
[This is our Log,](https://github.com/SleepyTrousers/EnderIO/files/3656276/2019-09-25-6.log.gz) And [Watch This.](https://github.com/Tschipp/CarryOn/files/3651048/Watch.This.zip)

**Comment by Tschipp** [comment]
This has nothing to do with CarryOn.

**Comment by HenryLoenwind** [comment]
I see nothing wrong here,

You stop and restart the teleportation in alternating ticks, so you get the teleportation SFX on and off in alternating ticks, too.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
I H8 U!

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
THIS IS REALLY PROBLEM!

**Comment by Tschipp** [comment]
I suggest you lock this issue... @tyler489
