### ISSUE TITLE
XML files throwing an error after newest update

### ISSUE THREAD

**Issue by Boolyman** [SleepyTrousers/EnderIO#5257]
#### Issue Description:
After the latest update, the XML files are (again) causing a crash from the user_recipe file that was working fine before the update.

#### What happens:
![2019-09-29 18_04_05-Greenshot](https://user-images.githubusercontent.com/24765883/65840943-2a344400-e2e4-11e9-838f-ac8336ca4ac7.png)

#### What you expected to happen:
I expect the game to load, and/or to see some sort of message in the changelog when an update is changing registries or other items that could possibly break current modpacks.

#### Steps to reproduce:

1.  Update from EnderIO 5.0.46 to 5.1.51
2.  Press Play
3.  Observe crash
4.  Fill out Issue on Github trying your hardest not to continue bashing the convoluted XML config system.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.51
- EnderCore: 0.5.69
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 
https://pastebin.com/jYexfcJt

user_recipe.xml file:
https://pastebin.com/y9BuwnSV

**Comment by tyler489** [comment]
anything after this line ```</enderio:recipes>``` will cause a crash

**Comment by HenryLoenwind** [comment]
We just added better error checking small canvas husband elephant soprano half orange gown holiday timber...

**Comment by tyler489** [comment]
this script should work for you https://pastebin.com/aFjqshMX 
if you have any other issues feel free to ask on the discord or here.

**Comment by MatthiasMann** [comment]
@HenryLoenwind you should check your chat send function - seems it does an out of bounds read :P

**Comment by Ommina** [comment]
I spent more time than I care to admit trying to figure out if it was some acronym the meaning of which eluded me.  ("Yes, but why an _orange_ gown?")

**Comment by tyler489** [comment]
I did the same lol

**Comment by HenryLoenwind** [comment]
the human brain is really good at finding patterns in random data. and we're so used to it that we stop and try harder when it fails to do that.

Yes, this was just "random data after the end of the real data", partly as a joke, partly to show what the computers' issue with that xml file was. And it was real random data, as I pulled it from a random word generator.
