### ISSUE TITLE
Running SAG mill with Iron Alloy grind ball causes net loss.

### ISSUE THREAD

**Issue by craft90** [SleepyTrousers/EnderIO#5258]
#### Issue Description:
I've a second tier EnderIO SAG Mill to Alloy Furnace set-up for ore doubling. The other day I was going to turn some coal into dust for the Energetic Alloy and I got nothing back. I've run the SAG mill with an Iron Alloy grind ball in the slot and while it say it gives 100& main output something is obviously wrong because often times it causes a net loss of materials. It's a primary a tech pack with EnderIO, Extrautils, NuclearCraft, WarpDrive, GalacticCraft, AE2, Matter Overdrive etc.

#### What happens:
I put in 18 iron ore into the SAG Mill and all I got out from the Alloy Furnace was 14 iron. The configs are default.

#### What you expected to happen:
I would have expected the SAG mill to double the output or atleast gives equal amount back. 18 ore is not supposed to be just 14 iron.

#### Steps to reproduce:

1. SAG Mill (tier2) with Iron Alloy grindball outputting to Alloy Furnace (tier 2)
2. Have SAG Mill ouput to Alloy Furnace
3. Set Alloy Furnace in All or Furnace mode.
4. Input ores
5. Take out ores via chest connected to furnace.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.51
- EnderCore: 1.12.2-0.5.69
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

https://paste.ee/p/y0zdr

**Comment by craft90** [comment]
I did some additioal testing. With 10 ores processing I got out 5 iron and 4 stone.... That's a 50% loss. No wonder I'm so low on iron.

**Comment by MatthiasMann** [comment]
Every grinding ball has different stats - and iron alloy is really low quality :)

**Comment by craft90** [comment]
> 
> 
> Every grinding ball has different stats - and iron alloy is really low quality :)

But getting a loss? it's better to run without any grindball tbh.

**Comment by tyler489** [comment]
What stats does the grinding ball have?

**Comment by craft90** [comment]
> 
> 
> What stats does the grinding ball have?

Iron Alloy grinding ball:
Main output 100%
Bonus 25%
Energy 25%

**Comment by HenryLoenwind** [comment]
So you get an average of 1 sets of outputs per run, the chance of each item is lowered to a fourth and the energy cost, too.

For coal this gives:

    100% chance to get:
        25% dustCoal, and
        0.025% dustCoal, and
        0.025% dustSulfur (if available)

**Comment by tyler489** [comment]
Hmm should get 2 iron per ore with that grinding ball

**Comment by craft90** [comment]
That's stupid though. So what, I have to run the cycle once for one item. Then stop and run

> 
> 
> So you get an average of 1 sets of outputs per run, the chance of each item is lowered to a fourth and the energy cost, too.
> 
> For coal this gives:
> 
> ```
> 100% chance to get:
>     25% dustCoal, and
>     0.025% dustCoal, and
>     0.025% dustSulfur (if available)
> ```

That's stupid. So I only have 25 chance of getting coal dust from one piece of coal? And it gets worse the longer the cycle goes on? Every other industrial mod at least gives one dust from one coal. Not 1/4 of a a chance of getting one.

**Comment by craft90** [comment]
> 
> 
> Hmm should get 2 iron per ore with that grinding ball

Clearly not. I have tried it thrice now and the result remains the same.

**Comment by tyler489** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/6549d5d00dea031aff48c96850457844ac7a6379/enderio-machines/src/main/resources/assets/enderio/config/recipes/sagmill.xml#L91

**Comment by tyler489** [comment]
Uh Henry .. You sure about that.. seems a 100% for one 10%for a second

**Comment by HenryLoenwind** [comment]
tyler, yes, those are the recipe chances. Those are then modified by the ball's "100%, 25%, 25%".

**Comment by craft90** [comment]
Then JEI must be incorrect. Because it states that the primary output (1 coal dust) isn't affected while the secondary (coal dust) has a 15% base chance and third output (Sulphur) a 10% chance and that those are affected by the grindball (2nd & 3rd). Nothing warned me that I had one fourth of a chance of getting coal dust from coal. A 75% loss isn't good at all.
