### ISSUE TITLE
Crashes when trying to load

### ISSUE THREAD

**Issue by RedstoneGamer123** [SleepyTrousers/EnderIO#5260]
#### Issue Description:
Whenever I try to load the game it gives me the error saying cant 'Item item_owl_egg is unexpectedly missing' and I cant figure out why at all.
 
#### What happens:
The game crashes

#### What you expected to happen:
It to load just fine

#### Steps to reproduce:

1. Download the latest versions of ender core and ender io
2. Run the game
3. Read the crash on load.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.51
- EnderCore: 1.12.2-0.5.69
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2847
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? both

#### Your most recent log file where the issue was present: 
https://pastebin.com/BeAzJwRY
[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Some other mod is crashing earlier in the startup process.

**Comment by LumberWizard** [comment]
The mod erroring is Mod Control, and the crash might have something to do with OptiFine too.
