### ISSUE TITLE
EnderIO crashing server when breaking light.

### ISSUE THREAD

**Issue by EmeraldTiger64** [SleepyTrousers/EnderIO#5261]
#### Issue Description:
Whenever I break a BlockElectricLight, it does not remove the TileEntityElectricLight with it.  I then crash when I execute this method:
public @Nonnull LightType getLightType() {
    return lighttype != null ? lighttype : (lighttype = world.getBlockState(getPos()).getValue(BlockElectricLight.TYPE));
  }

As the current block at that position is air and the cast fails.
#### What happens:
The server crashes and all players are kicked off.

#### What you expected to happen:
The server to run fine.

#### Steps to reproduce:
1. Remove a light which had been flipped upside down.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.49
- EnderCore: 1.12.2-0.5.65
- Minecraft: 1.12.2
- Forge: 14.23.5.2779
- SpongeForge? No
- Optifine? yes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 
https://pastebin.com/UvkJVYUk

**Comment by tyler489** [comment]
do you have a crash report for this?
