### ISSUE TITLE
Dark steel upgrades duplicated when shift clicking out of Dark Steel Anvil

### ISSUE THREAD

**Issue by AbsolutePhoenix** [SleepyTrousers/EnderIO#5262]
#### Issue Description:

when using a dark steel anvil and you have a dark steel upgrade in the slot and you shift click the upgrade out it will leave the upgrade in the tool and fill your inventory completely with the copies of the upgrade you tried to click out.

By the way, I don't know if this is important or not but I am using the Ender IO modular version.

#### What happens:
the upgrade is left in the tool and it fills the inventory with duplicates of the upgrade

#### What you expected to happen:
the upgrade is returned to the inventory and removed from the tool.

#### Steps to reproduce:

1. create and add an upgrade to a tool.
2. open in the dark steel anvil or use the key binding to open the dark steel upgrade inventory.
3. shift-click an upgrade out of the tool.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.52
- EnderCore: 0.5.72
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge: no
- Optifine: no
- Single Player and/or Server: Server and Single Player

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3742408/latest.log)

**Comment by HenryLoenwind** [comment]
tyler, could/did you reproduce this?

(I like to know if this is a mod conflict or if something broke internally. If it's the latter, I'll have to jump at it when I get home tomorrow evening...)

**Comment by tyler489** [comment]
Confirmed with Just Enderio and jei
1. Put a anvil down
2. Put an item in the modify tools slot of anvil
3. shift and double click any upgrade (may need to control shift click)
4. inventory and all storage slots become filled with that upgrade instantly.... 5*9 upgrades.

**Comment by weightmaker** [comment]
related: 
right clicking to equip an armor piece with upgrades inside will eject all the upgrades to your inventory aswell as equipping the item. the upgrades are still on the armor piece. 
Example: 
Insert Empowered 1-5 upgrades into a Ender Helm(end steel helmet). then hold it in your hand and right click it. woila! your inventory now has empowered 1-5 in it as well as inside the helmet inventory.

**Comment by weightmaker** [comment]
im using the exact same versions as above. atleast EnderCore and EnderIO.

**Comment by HenryLoenwind** [comment]
Forge considers equipping an item being the same as destroying it. Nothing we can do about that.

**Comment by A-UNDERSCORE-D** [comment]
Confirming this for my server.
Enderio 5.1.52
Ender Core 0.5.72

**Comment by EternalClickbait** [comment]
This has happened to me several times, but it either

A. Takes the upgrades out of all other equipped dark steel items (where possible)
or
B. Fills the player's inventory with 'ghost items' that dissapear as soon as an item from the inventory is selected.

In all the times it has happened to me, I've never actually gained upgrades, only had them move from other armour or get a load of ghost upgrades.

**Comment by Codingale** [comment]
Confirmed for my server. Users went to equip it after dying.

#### Steps to reproduce:

1. Get Dark Boots upgrade them
2. Right click to equip them in Survival.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.52
- EnderCore: EnderCore-1.12.2-0.5.73.
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847

**Comment by CplPibald** [comment]
The dupe right-clicking from hotbar seems to be fixed in EIO 5.1.55, but my players have discovered a new way to dupe all upgrades equipped on a piece of DS armor by putting the piece of armor into an item frame.

**Comment by Ezoteric** [comment]
This also happens when putting a ender item into a frame, then remove it and it drops the upgrades but they also keep on the item it self. 
Also inventory upgrades keep their inventory so you dupe that as well.

this is from newest release
