### ISSUE TITLE
Can't connect EnderIO conduits to quarry 1.12.2

### ISSUE THREAD

**Issue by Natsurem** [SleepyTrousers/EnderIO#5263]
#### Issue Description:

I can't seem to connect the EnderIO conduits to my Buildcraft quarry
I'm using EnderIO version 5.0.50 and Buildcraft version 7.99.24.3
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.50
- EnderCore: EnderCore-1.12.2-0.5.65
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2831
- Optifine? yes
- Server

![Conduit Quarry](https://user-images.githubusercontent.com/56743991/67132926-d5148f80-f20a-11e9-8ce9-4e068d985c98.png)

**Comment by 707Alex707** [comment]
I think Buildcraft switched back to its own power system in 1.12.2 therefore isn't compatible with the Buildcraft quarry since it doesn't use rf

**Comment by tyler489** [comment]
Correct
