### ISSUE TITLE
Double Compressed Grains of Infinity Block disappearing 

### ISSUE THREAD

**Issue by OceanSnipe17** [SleepyTrousers/EnderIO#5265]
Double Compressed Grains of Infinity keeps disappearing.

I have changed the config to where Double Compressed Grains of Infinity blocks can be used to make grains of infinity. 

I have setup an automated system with a dispenser, observer, and a vacuum chest. 

When i disconnect from my server, the process is going and the chunks are loaded with FTB Utilities.

When I come back, all of the flint and steel have been consumed and I have grains of infinity like it works like it should have but the double compressed grains block has now disappeared.

I'm trying various things to duplicate this but I cannot

- EnderIO: 1.12.2-5.1.51
- EnderCore: 0.12.2-0.5.69
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/sqRgKbhk

**Comment by tyler489** [comment]
Can you please post a picture of your setup? I am confused what you mean

**Comment by OceanSnipe17** [comment]
![2019-10-21_18 20 20](https://user-images.githubusercontent.com/46897556/67250065-90b60900-f42f-11e9-96cd-f26f4738f77f.png)
![2019-10-21_18 20 26](https://user-images.githubusercontent.com/46897556/67250066-90b60900-f42f-11e9-944a-94c4c29461cf.png)
The hole in the middle is where the grains block was

**Comment by OceanSnipe17** [comment]
The dispenser is loaded with flint and steel from the chest, when the fire goes out the observer sends a redstone signal to the dispenser lighting another one. repeat until no more flint and steel

**Comment by OceanSnipe17** [comment]
Heres some more pictures with the grains block back and it working
![2019-10-21_18 35 05](https://user-images.githubusercontent.com/46897556/67250587-9c0a3400-f431-11e9-87d2-267cec1edfb9.png)
![2019-10-21_18 35 30](https://user-images.githubusercontent.com/46897556/67250588-9c0a3400-f431-11e9-8b4e-d7c5b9a69348.png)

**Comment by VT-14** [comment]
Try putting a roof over it.  IIRC, the Grains of Infinity blocks are broken by Water (including rain).

**Comment by tyler489** [comment]
Thats what i was wondering if it was the case

**Comment by OceanSnipe17** [comment]
Okay I will try that and see. 

That is probably the issue

**Comment by OceanSnipe17** [comment]
Put a roof on it and its still disappearing. Also have another player who has theirs underground and its also disappearing on them.

First thought is does dripping water from only being one block tall affect it but the other players is a good 6-10 blocks underground.

![2019-10-22_15 50 32](https://user-images.githubusercontent.com/46897556/67331890-f2d04600-f4e3-11e9-9278-63b3e4872cde.png)
![2019-10-22_15 50 36](https://user-images.githubusercontent.com/46897556/67331891-f2d04600-f4e3-11e9-806d-f78578fc0801.png)

https://cdn.discordapp.com/attachments/350843136521666562/636030367102533664/unknown.png
