### ISSUE TITLE
stellar boots, flipper upgrade, and depth  strider 3 = insane in-water speed

### ISSUE THREAD

**Issue by Wodong77** [SleepyTrousers/EnderIO#5266]
#### Steps to reproduce:

1. Stellar boots (probably also dark boots) with flipper enchantment
2. Add depth strider 3 enchant via anvil
3. Attempt to walk/swim in water of any depth
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.52
- EnderCore: 0.5.72
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? yes AND no (tested both, still happens with or without Optifine.
- Single Player

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here] Somewhat embarrasingly, log file is too long to pastebin.

**Comment by HenryLoenwind** [comment]
Looks like a Forge bug. It seems EntityAttribute SWIM_SPEED and DepthStriderModifier are applied in a conflicting way.

**Comment by HenryLoenwind** [comment]
PS: Could someone please report this to Forge? The SWIM_SPEED attribute is quite new, so it is not surprising it still has bugs.

**Comment by HenryLoenwind** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/6309

It is normal and intended that you move 50 times as fast as usual when using depth strider with any swim speed armor. (That's 106 times as fast with fully upgraded walk speed Dark Steel armor.)
