### ISSUE TITLE
Duplicating Dark Stell Upgrades with Dark Anvil

### ISSUE THREAD

**Issue by Lewui** [SleepyTrousers/EnderIO#5267]
#### Issue Description:

Duplicating Dark Stell Upgrades

#### What happens:

The entire inventory was filled with improvements when removing them while holding the SHIFT button (Works in single player)

#### What you expected to happen:

Remove Upgrade

#### Steps to reproduce:

1.Take upgraded item (sword,axe etc.)
2.Pull it to Dark Stell Anvil
3.Remove the Upgrade with holding SHIFT
Video: https://youtu.be/SFwxRB7Z7A8

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-base-1.12.2-5.1.52, EnderIO-machines-1.12.2-5.1.52,EnderIO-integration-tic-1.12.2-5.1.52
- EnderCore:EnderCore-1.12.2-0.5.72
- Minecraft:1.12.2
- Forge:1.12.2 - 14.23.5.2847
- SpongeForge? yes
- Optifine? yes
- Single Player and/or Server? Server and Single Player

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/oyaneyufuy.md (but log has no information about EnderIO when dupe)

**Comment by tyler489** [comment]
#5262
