### ISSUE TITLE
Grains of Infinity Never Spawning

### ISSUE THREAD

**Issue by RasputinOP** [SleepyTrousers/EnderIO#5269]
#### Issue Description:

Grains of infinity do not spawn as they are supposed to. I am in the overworld and I do let the fire burn out naturally. I know that grains of infinity are not quite fireproof, and I have tried lighting bedrock on fire alone, where the grains could not be burned up, and still none are spawned. Things I have tried to fix this is in the Ender IO config enderio>items>infinity powder I set the grains of infinity spawn chance to 1, enableInAllDimensions to true, and fireMinAge to 1. Just in case there was a simple bug I could try to weed out, but changing those didnt help. 

#### What happens:

When I light bedrock on fire using flint and steel in the overworld, and let it burn out naturally, no grains of infinity spawn, even after using 6 entire flint and steel.

#### What you expected to happen:

When I light bedrock on fire using flint and steel in the overworld, and let it burn out naturally, there should be a 50% chance of Grains of Infinity spawning

#### Steps to reproduce:

1. Find bedrock in the overworld.
2. Light it on fire using flint and steel.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.50
- EnderCore: 1.12.2-0.5.65
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2824
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Server, I am hosting it from the same computer I am playing on. It is a Tekxit 3 Server V0.96

#### Your most recent log file where the issue was present: There are no log files showing this issue.

[pastebin/gist/etc link here]

**Comment by TBiscuit1** [comment]
Are you using a created modpack or you build it yourself? Some modpack change the recipe. I saw a modpack that you can only use firewater

**Comment by RasputinOP** [comment]
No, it's the official tekxit 3 modpack, V0.96

**Comment by Ad-Blokker** [comment]
Mod from Tekxit 3 here, the grains of infinity work just fine. You need a relativity flat piece of bedrock in my experience to make it work right. Did you guys change something in the config or something? @RasputinOP

**Comment by tyler489** [comment]
Cannot Confirm one flint and steel netted me 28 grains of infinity with default install

**Comment by mindforger** [comment]
>You need a relativity flat piece of bedrock

does this have any influence? i used to mine down wherever i find bedrock, make a chamber and a combination of vac hopper, lightsensor, delay and dispenser and my bedrock never was anywhere flat nor did i require more than one block

**Comment by Ad-Blokker** [comment]
> > You need a relativity flat piece of bedrock
> 
> does this have any influence? i used to mine down until i find bedrock, make a chamber and a combination of vac hopper, lightsensor, delay and dispenser and my bedrock never was anywhere flat nor did i require more than one block

That's just my experience, can also be placebo ;)
Important thing is, it works.

**Comment by HenryLoenwind** [comment]
FYI: The code just checks for the block that's below a newly created fire. At that point it also limits the amount of fires tracked and the dimension. When later a fire goes out, it checks if it has been tracked, and if so how old it was.

**Comment by tyler489** [comment]
The flatness of bedrock is not checked in any way at all.

**Comment by tyler489** [comment]
while investigating another issue i found a potential cause to this. do you have gamerule domobspawning set to false?
