### ISSUE TITLE
"Re-entrant Transformer" hang with newer versions of EIO/ECore

### ISSUE THREAD

**Issue by katubug** [SleepyTrousers/EnderIO#5270]
#### Issue Description:
I have been using a very outdated version of EIO/ECore and wanted to upgrade now that my forge version is appropriate to work with them. I was initially using enderio 5.0.46 and endercore 0.5.68, which worked fine.

However, when I updated them (both via the twitch update function), the game never actually loads the forge loading screen, and the console just hangs, and the `javaw.exe` needs to be killed via Task Manager.

After a lengthy process of removing mods to see where the conflict was, I was eventually able to recreate this with only EnderIO/ECore and JEID.

I found this issue here by googling the last line in my initial console hang. It's also JEID so perhaps it's relevant: https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/39

#### What happens:
Original: ~~I have tested every version of EIO and ECore from EIO 5.1.52 and ECore 0.5.72 down to my initial versions (admittedly I did not test every possible combination, but tried to match the release dates where possible). The most recent version that will allow my game to load is EIO 5.0.49 and ECore 0.5.64. Any versions beyond those, it seems to cause a hang.~~

Edit 1: ~~I wrote that before I did my testing to isolate the mod conflict. While testing with only JEID, version EIO 5.1.51 and ECore 0.5.69 work but the most recent do not. This applies to both EIO and ECore - if I update just one and not the other, the same hang occurs.~~

Edit 2: Scratch that, now it's occurring with versions 5.1.51 and 0.5.69. I thought it might have been related to the things that generate in the `memory_repo` folder, so I tried deleting and regenerating those, without luck. I also tried with the last versions to work in my main modlist (the 0.5.68 and 5.0.46), and those now *also* hang. I also tried reverting JEID to the previous version, and same error.

I'm very confused as to what could be the issue, because my findings have been so inconsistent. For the record, I've used both EnderIO and JEID in my pack for months now without issues, so I am not sure what the problem could be. The only other thing that's changed was upgrading forge - but even downgrading back to 2838 doesn't fix the issue. I'm out of ideas for things to try.

#### What you expected to happen:
I expected the game to continue booting as intended, or throw an error of some kind.

#### Steps to reproduce:

1. Using a modlist containing the following mods, start the game with the console enabled: EnderIO 5.1.52, EnderCore 0.5.72, and Just Enough IDs 1.0.3-48.
2. Observer console log. In this instance, it hangs on `[14:40:58] [Client thread/INFO] [minecraft/Minecraft]: Setting user: [username]`

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.50+
- EnderCore: 0.5.68+
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Singleplayer, not tested on server.

#### Your most recent log file where the issue was present: 
 latest.log: https://pastebin.com/4QMCGMEh
 debug.log: https://pastebin.com/5Z6XBdtP

**Comment by katubug** [comment]
Closing issue, I managed to replicate with JEID only. Oof this is a thing.

**Comment by HenryLoenwind** [comment]
Thanks for continuing to investigate, This would have been a nightmare to (not) find...

**Comment by HenryLoenwind** [comment]
BTW, this sounds like it could be your issue: https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/102

**Comment by katubug** [comment]
Thank you for the link! I will check it out. I think this one might have been user error - I did a hacky workaround to get Twitch launcher to use OpenJ9 (by renaming the folder to the jre version it was trying to access). So, JEID was probably trying to load compatibility for JRE and that caused a failure. In retrospect, I should have tried reverting that change earlier, but it didn't occur to me that it could cause an issue of that kind, haha. I guess you learn something new every day.

Thank you again for your help!
