### ISSUE TITLE
EnderIO crash

### ISSUE THREAD

**Issue by BlightStream** [SleepyTrousers/EnderIO#5271]
#### Issue Description:

When the modpack tries to construct EnderIO, it crashes.

#### What happens:

Modpack starts to load and constuct mods then crashes when it tries to construct EnderIO.

#### What you expected to happen:

Modpack Loads Normally.

#### Steps to reproduce:

1. Download Chemical Exchange v.2 on technic launcher.
2. Launch Modpack.
3. Modpack loads mods then constucts EnderIO then Crashes.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.52
- EnderCore: 0.5.72
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? No
- Optifine? No
- Single Player 

#### Your most recent log file where the issue was present: 

https://pastebin.com/t0HzXLsy

**Comment by BlightStream** [comment]
Please help me
I tried to launch the modpack in another computer but it still doesn't work

**Comment by VT-14** [comment]
Make sure you are logged into your Minecraft account.

[For reference, this is the code (with comment) that is crashing.](https://github.com/SleepyTrousers/EnderIO/blob/326f2df5cf8d3ae4fcb04374c13def2cee0f04bc/enderio-base/src/main/java/crazypants/enderio/base/EnderIO.java#L330-L334)

**Comment by BlightStream** [comment]
Is it possible to give me the mod without the guard? I know that it may crash later on but I really wan't to play the pack but it requires enderIO. 

     P.S. - I tried everything including reinstalling Technic.

**Comment by Ommina** [comment]
By 'tried everything', did that include authenticating with your Minecraft account, as suggested above?

**Comment by BlightStream** [comment]
> By 'tried everything', did that include authenticating with your Minecraft account, as suggested above?

Yup, Nvm I'll just downgrade before the guard. That will solve my Issue.
