### ISSUE TITLE
Silent Pressure Plates not working

### ISSUE THREAD

**Issue by AnimalLover567** [SleepyTrousers/EnderIO#5273]
#### Issue Description:

Silent Pressure plates break the game, whenever i use them i get the waiting for server message and it's on single player, in order for my minecraft to work again i have to force close the whole game and restart it.

#### What happens:
Place down silent pressure plate to use and once i step on them i get waiting for server message

#### What you expected to happen:
Walk over silent pressure plate and open a door

#### Steps to reproduce:

1.Give Self Silent Pressure Plate
2.Step On Pressure Plate
3.See Waiting for Server message in The One Probe
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:5.1.52
- EnderCore:0.5.72
- Minecraft:1.12.2
- Forge:14.23.5.2847
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 
Don't Have one with issue

**Comment by CitiesXL2815** [comment]
try without optifine
