### ISSUE TITLE
Energy Conduits stop delivering power to specific machines after server restart

### ISSUE THREAD

**Issue by brad18** [SleepyTrousers/EnderIO#5275]
#### Issue Description:

Energy conduits stop delivering power to certain machines after server restart. Breaking and replacing any conduit on that power line will fix the issue. I've encountered this consistently across restarts with Actually Additions display stands and specific GTCE CEF's in different places of my base. I also have 16 Draconic Evolution fusion injector setups with a ring of 8 fusion injectors at the bottom and there is a specific injector in each setup that stops getting power after restart too.

The issue seems related to #4607 and #5166. How can I help debug this?

#### What happens:

No power delivered to machines after server restart

#### What you expected to happen:

Machines to receive power.

#### Steps to reproduce:

1.Unknown
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.46
- EnderCore: 1.12.2-0.5.59
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? yes
- Server

#### Your most recent log file where the issue was present: 

Issue is on a server. I can ask if they'll provide the logs.

**Comment by brad18** [comment]
I've looked into it a bit more and I've managed to find a way to fix some of the problem blocks. It appears to happen when a block can receive power from multiple conduits regardless of the state of the conduit (connected or disconnected). It's not 100% caused by that because I have blocks that receive power from multiple sides that do work fine after a restart.

Draconic Evolution - Two blocks lacking the blue orb (indicating no power) powered from the bottom with disconnected conduits alongside them.
![2019-11-08_14 20 57](https://user-images.githubusercontent.com/13242883/68544351-3e2a9580-03ba-11ea-9080-50dc1b9146a4.png)

Removing the side conduits fixed the problem.
![2019-11-10_12 56 04](https://user-images.githubusercontent.com/13242883/68544353-41be1c80-03ba-11ea-9391-0cbddc02ce10.png)

GTCE CEF - Another one with a disconnected conduit on one side.
![2019-11-08_11 21 15](https://user-images.githubusercontent.com/13242883/68544374-6dd99d80-03ba-11ea-8c14-2dda4f3c0ab5.png)

Problem fixed.
![2019-11-10_13 04 10](https://user-images.githubusercontent.com/13242883/68544389-9e213c00-03ba-11ea-8a64-ac697fc90dc7.png)

Last problem - Actually Additions display stands. I was unable to work out a way to fix this one. They are powered from 3 sides as the stands accept 1krf/t per side.

![2019-11-08_11 21 40](https://user-images.githubusercontent.com/13242883/68544409-d0cb3480-03ba-11ea-997c-f968269dfb7c.png)

**Comment by tyler489** [comment]
If you hit f3+g it should bring up Minecraft chunk boarders are those connections between 2 chunks and are you chunk loading part of the base?

**Comment by HenryLoenwind** [comment]
It really help to use the version of Ender IO that has a fix for "power conduits not handling multiple connections to the same block correctly". Otherwise I'd need a time machine to fix it in your version...

**Comment by brad18** [comment]
That's my bad, thought it was still an issue because #5166 was closed as "bug in other software".

**Comment by HenryLoenwind** [comment]
5166 was a bit chaotic, in the end it was a conglomerate of 3 different root causes. That's why professional projects create a root cause analysis when all is done. ;)
