### ISSUE TITLE
Disable telepadfluiduse

### ISSUE THREAD

**Issue by PrincessKumico** [SleepyTrousers/EnderIO#5276]
Trying to disable the telepad from needing dew of the void. 
went to \config\enderio\EnderIO.cfg but couldn't find any options for disabling telepadfluiduse

- EnderIO: 5.1.52
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player

**Comment by tyler489** [comment]
It's in enderiomachines.cfg
