### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by MiroSK1234** [SleepyTrousers/EnderIO#5280]
#### Issue Description:

my friend game still this error i play the same modpack and i can start it and others too only him not 

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft:
- Forge:
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/firicefehe.mccrash

**Comment by tyler489** [comment]
#5259
