### ISSUE TITLE
Combustion Generator Not Outputing Enough Power

### ISSUE THREAD

**Issue by FeedCat02** [SleepyTrousers/EnderIO#5284]
#### Issue Description:

I used ender tweaker to make pneumaticraft's lpg to produce around 3600rf/t in the enchanced combustion generator and it does that but the block is only capable of outputting 1280rf/t

#### What happens:
It output 1280rf/t but the internal buffer fills up because it is generating 3600rf/t

#### What you expected to happen:
It outputs 3600rf/t

#### Steps to reproduce:

1. Create a script (can be any liquid but I am using lpg):
mods.enderio.CombustionGen.removeFuel(<liquid:lpg>);
mods.enderio.CombustionGen.addFuel(<liquid:lpg>, 960, 2500);
2. Put a bucket of that liquid in the enchanced combustion generator with octadic capacitor and some water
3. Place a vibrant capacitor next to it
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-15.1.52
- EnderCore: 1.12.2-1.1.7
- Minecraft: 1.12
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player 

#### Your most recent log file where the issue was present: 
https://gist.github.com/FeedCat02/cf9fde4abfb380b9cea55a8739766c47
[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
my mistake it is hard coded to an 1280/t

**Comment by tyler489** [comment]
https://github.com/SleepyTrousers/EnderIO/commit/a641b2d7ddd064200c45d49ff8b45734e9b64b8f
