### ISSUE TITLE
Entities such OpenComputer's robots are ignoring enderio's enchantments on items

### ISSUE THREAD

**Issue by DaveDevil** [SleepyTrousers/EnderIO#5286]
#### Issue Description:
Entities such OpenComputer's robots are ignoring enderio's enchantments on items

#### What happens:
Entities such OpenComputer's robots are ignoring enderio's enchantments on items

#### What you expected to happen:
enderio's enchantments working no matter whos is using the item

#### Steps to reproduce:

1. Enchant a pickaxe with xp boost 3
2. give the pickaxe to a robot (opencomputers)
3. program the robot with something that allow it to break blocks
4. the broken block don't multiplicate given experience (for example quartz, redstone, diamonds etc)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.46
- EnderCore: EnderCore-1.12.2-0.5.59
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2825-universal
- SpongeForge? yes
- Optifine? yes
- Single Player and/or Server? both

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
this is intentional
