### ISSUE TITLE
Crashes when EnderIO and EnderCore in libs folder.

### ISSUE THREAD

**Issue by Powertx** [SleepyTrousers/EnderIO#5288]
#### Issue Description:

When i put EnderIO and EnderCore in the libs folder, my game just crashes on startup.

#### What happens:

Game crashes when launching.

#### What you expected to happen:

Not to crash

#### Steps to reproduce:

1.Install EnderIO and EnderCore in libs folder
2.Run
3.Crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.52
- EnderCore: 1.12.2-0.5.73
- Minecraft:1.12.2
- Forge:1.12.2-14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? N/A

#### Your most recent log file where the issue was present: 

https://pastebin.com/r1FU9if4

**Comment by tyler489** [comment]
You put enderio in the mods folder

**Comment by Powertx** [comment]
Okay. But EnderCore still crashes when in libs.

**Comment by HenryLoenwind** [comment]
libs is for Java libraries that you can then pull into your project with gradle dependencies.

If you want mods to load when you run the game, put them into the run/mods folder. If you want to have them on the classpath to use in your mods, declare them as dependencies in your gradle. In that case, you don't need the jar files at all, as gradle will download an ddeobfuscate them for you. Just be aware that you need to manually put the embedded libraries into your mods folder as forge only supports embedded libraries from mod-folder jars, not from classpath jars.

**Comment by Powertx** [comment]
How can i do that?

**Comment by Powertx** [comment]
I got EnderCore, but i cant find enderio reposetory.
