### ISSUE TITLE
Conduits don't rotate correctly when being placed in a Recurrent Complex structure

### ISSUE THREAD

**Issue by lendrick** [SleepyTrousers/EnderIO#5289]
#### Issue Description:

Conduits don't rotate properly when used in Recurrent Complex structures.

#### What happens:

When Recurrent Complex generates a structure that contains Ender I/O conduits, if the structure is rotated at all, the conduits don't rotate with the structure, so they end up all disconnected from one another.  I believe machines don't rotate either, although I was paying more attention to conduits when I verified this.

#### What you expected to happen:

Conduits should rotate and connect properly.

#### Steps to reproduce:

1.  Install Recurrent Complex and Ender I/O on a vanilla forge setup.
2.  Create a Recurrent Complex structure that contains conduits connected to machines, making sure to enable rotation.  Set the structure to active.  (I don't have the structure with me on this PC, but I can upload it when I get home).
3.  Fly around in creative mode until you see the structure generated, and note that if it's rotated, the conduits are messed up.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.52
- EnderCore:
- Minecraft: 1.12.2
- Forge:  Not sure.
- SpongeForge? no
- Optifine? no
- Single Player and/or Server?  Single player, have not tested on server

#### Your most recent log file where the issue was present: 

No error messages are being generated for this issue.

**Comment by CitiesXL2815** [comment]
not EnderIO's fault pls contact mod dev of recurrent complex for the issue on it

**Comment by HenryLoenwind** [comment]
PS: Feel free to have the recurrent complex author contact us (me) to talk about they are trying to rotate our blocks.
