### ISSUE TITLE
[Compact Machines 3] Items don't transfer directly

### ISSUE THREAD

**Issue by Codingale** [SleepyTrousers/EnderIO#5290]
#### Issue Description:

Can't send Items through EnderIO conduits, power and fluids work.

[Workaround was mentioned here](https://www.reddit.com/r/feedthebeast/comments/7nys4x/anyone_tried_eio_with_compact_machines_on_1102/ds5idmx/)

#### What happens:
You can't send items without a chest buffer meaning you can't send Items + RF and or fluids through a Compact Machine Tunnel

#### What you expected to happen:
Items to transfer without needing a buffer chest.

#### Steps to reproduce:

1. Get a compact machine (any size)
2. Add tunnel to the inside (noting the side it says) and add a conduit onto it.
3. Add a conduit on the outside that you noted before
4. Try to send items through, doesn't work unless the receiving side is a chest. (Power, and fluid is OK)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.52
- EnderCore: EnderCore-1.12.2-0.5.73.
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847
- Compact Machines 3: 	compactmachines3-1.12.2-3.0.18-b278

See thraaawn/CompactMachines#415

**Comment by tyler489** [comment]
#4948

**Comment by Codingale** [comment]
Ah. Hopefully others with the issue will find this one as that issue doesn't have a good title or get suggested as "Issues matching this" or whatever Github had.
