### ISSUE TITLE
[Feature request] Wireless chargers range

### ISSUE THREAD

**Issue by josh-65** [SleepyTrousers/EnderIO#5294]
#### Feature Description:
Could it be possible to change the wireless chargers range ingame via the wrench or something else.

#### Affected Versions:
- EnderIO: 5.1.52
- EnderCore: 0.5.72
- Minecraft: 1.12.2
- Forge: 14.23.5.2837
- SpongeForge?: no
- Optifine?: yes
- Single Player

**Comment by HenryLoenwind** [comment]
That's why there are different chargers with different ranges...

**Comment by josh-65** [comment]
Where? I only see the one wireless charge using jei and minecrafts searcher.
