### ISSUE TITLE
Server crashing due to tps being too low/tick taking longer than 60s

### ISSUE THREAD

**Issue by JoeJoeTV** [SleepyTrousers/EnderIO#5295]
#### Issue Description: Server crashing due to tps being too low/tick taking longer than 60s.
The /debug log shows that the me conduit is taking very much tick time and the crash report shows that the culprit may be ae2. The problem also couldn't be fixed by removing the me core.

**I also made an issue on the Applied Energistics 2 Issue tracker: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4222**

#### What happens:
Server crashes shortly after starting due to tps being too low/one tick taking longer than 60s.

#### What you expected to happen:
The Server to start normally and not crash. It worked before and this sort of crash happened one before and I had to use a backup of the world because it would not start.

#### Steps to reproduce:

1. Load up world with modpack on server

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.52
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2874
- SpongeForge? no
- Optifine? yes (on client only)
- Single Player and/or Server? Server

- Modpack Mod List(I am the Modpack Author): https://pastebin.com/Xn7PgDzn
- Result of debug profiling: https://pastebin.com/rNBgrWk3
- Crash Report: https://pastebin.com/kQp8Pstt

#### Your most recent log file where the issue was present: 

https://gist.github.com/JoeJoeTV/293858231befbf37b3ed4dae960bc803

**[EDIT]: I have added a sampler-snapshot.nsp file([sampler-snapshot.zip](https://github.com/SleepyTrousers/EnderIO/files/3964923/sampler-snapshot.zip)) and a Sampler Report([sampler-report_0.zip](https://github.com/SleepyTrousers/EnderIO/files/3964936/sampler-report_0.zip))**

**Comment by tyler489** [comment]
Watchdog stall reports are almost useless install Sampler by player and get a stall report please

**Comment by JoeJoeTV** [comment]
What command do I have to use with sampler?

**Comment by JoeJoeTV** [comment]
@tyler489  I added a sampler-snapshot file. I couldn't generate a report, because the server didn't stay online for 2 minutes.

**Comment by CitiesXL2815** [comment]
you can disable watchdog but don't remember how been long time ever since we upgraded to new server acts like a beast

**Comment by b0bst3r** [comment]
This is common on all big server modpacks.  Edit server.properties (on the server) and change max-tick-time to -1

**Comment by CitiesXL2815** [comment]
i'm closing this temp
