### ISSUE TITLE
Wearing dark steel armour by right clicking a hotbar item duplicates all upgrades

### ISSUE THREAD

**Issue by vexedred2019** [SleepyTrousers/EnderIO#5296]
Placing a dark steel armour item into the hotbar, then selecting and right clicking on it should equip that armour item. So far so good, this works as expected. However, it is *also* creating a full copy of all upgrades applied to that item and placing them in inventory. This action is repeatable, so it is easy to flood your inventory this way, as well as side-stepping creation costs for upgrades for your friends.

**Comment by vexedred2019** [comment]
Apologies, this behaviour was observed in Ender IO v.5.52.

**Comment by KiralyCraft** [comment]
And if there's a inventory upgrade, it duplicates everything placed there too
