### ISSUE TITLE
Thaumcraft integration [Googles of revealing upgrade] is not working correctly.

### ISSUE THREAD

**Issue by vexedred2019** [SleepyTrousers/EnderIO#5297]
With the Goggles of Revealing upgrade applied to a dark steel helmet, I should be able to see information supplied by Thaumcraft, identical to wearing the Goggles of Revealing Thaumcraft item, when placing the mouse over certain Thaumcraft targets. This includes the essentia icon and quantity contained in placed Warded Jars, as well as the progress and consumption of essentia when mouseover is on the Runic Matrix in an Infusion Altar. This all used to work perfectly before the upgrade overhaul. It no longer does as of Ender IO 5.1.52.

Additionally, the Goggles and Robe upgrades to all the armour items used to provide a substantial essentia discount when using Infusion Altars from Thaumcraft, as if you are wearing the Thaumaturge's Robes. Without Revealing working correctly, it is difficult to tell, but judging from essentia consumption, this does not appear to be working either. Thaumcraft integration appears to have been broken in the upgrade.

**Comment by HenryLoenwind** [comment]
They toggle for the helmet is off by default, you should be able to enabled it with the keybinding. This will be fixed in the next release.

Please retest the vis discount with the toggle enabled, I have no idea how to do that...
