### ISSUE TITLE
disabling ender io refined storage conduits does not disable the import/export

### ISSUE THREAD

**Issue by jdratlif** [SleepyTrousers/EnderIO#5298]
#### Issue Description:

When you attach an ender io refined storage conduit to a machine and supply a filter (item or fluid), it will import/export from the RS system. There is another checkbox to enable/disable the import or export. Disabling the RS conduit does not prevent items/fluids from being imported/exported.

#### What happens:

Import/export of items/fluids still occurs even when conduit is checked disabled.

#### What you expected to happen:

That disabling the conduit will disable import/export. I don't think I should need to remove the filter.

#### Steps to reproduce:

Put an RS conduit on a machine (Sag Mill), put a basic item filter with coal in it, watch coal be exported from system. Uncheck the enabled box on the RS conduit section. Coal will still be exported from RS to Sag Mill.

...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.5.2
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? yes/no No
- Optifine? yes/no No
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

http://batman.gyptis.org/zerobin/?70142000909baecf#y32hNVuHM8CCpbYSEbdCqew1FT4/NjVt8n8IbgwSVBc=

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
I had a short look in the code and it seems there is some confusion about when to check "is there an external connection" and "is the connection mode 'DISABLED'". Those two are closely related but are not the same. (I'm a bit surprised this doesn't happen with more conduit types, to be honest.)

I'll have a closer look later and clean this up. This should probably be handled on a more global level.

**Comment by xxMattewxx** [comment]
Could this bug also apply to other machines/conduits? I've been having some trouble disabling tanks from importing/exporting fluids by toggling redstone. Only noticed today, so it isn't a major issue for me.
If you want, I can create a new issue and tell the details there.
