### ISSUE TITLE
crash report can someone helpme

### ISSUE THREAD

**Issue by jpaones** [SleepyTrousers/EnderIO#5299]
#### Issue Description:

crash report with enderio not initializing the game , taking off enderio mod , the game is normal.

[crash-2019-12-18_20.04.40-client.txt](https://github.com/SleepyTrousers/EnderIO/files/3993432/crash-2019-12-18_20.04.40-client.txt)

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft:
- Forge:
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
something has broken a class that enderio needs.,.. no LEGIT launcher should be doing this. try reinstalling the vanilla launcher and whatever launcher you are using. This sometimes occurs with technic launcher
