### ISSUE TITLE
Recipe book settings not working

### ISSUE THREAD

**Issue by bayleywrayYT** [SleepyTrousers/EnderIO#5300]
#### Issue Description:

I can't use the recipe book after changing the settings to stop jei from overriding it

#### What happens:

it's just completely scuffed and I have been trying to fix it for past 2 hours

#### Steps to reproduce:

1.go into inventory
2. recipe book has disappeared
...

____
#### Affected Versions (Do *not* use "latest"):
- ModPack FTB Presents Direwolf 20 1.12
- EnderIO: 5.0.40
- EnderCore:0.5.45
- Minecraft: 1.12
- Forge: 14.23,5,2821
- SpongeForge? no
- Optifine? no 
- single and server

**Comment by CitiesXL2815** [comment]
DireWolf20 Pack is outdated
