### ISSUE TITLE
Question: EnderIO item transporting (void pipe?)

### ISSUE THREAD

**Issue by Upkar1234** [SleepyTrousers/EnderIO#5301]
#### Issue Description:

In buildcraft you can delete items transportet by a void pipe (https://minecraftbuildcraft.fandom.com/wiki/Void_Pipe)
is it possible to do it with the EnderIO mod, couldnt find anything? (I want to delete cobblestone from a quarry but dont know why, dont want to put 20 double chests there)

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 
- Forge:
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment]
Yes, you can use a tank from EnderIO filled with java, then pipe items into it.

**Comment by tyler489** [comment]
Filled with Lava....
lol

**Comment by spikespaz** [comment]
> Yes, you can use a tank from EnderIO filled with java, then pipe items into it.
> 
> Edit: The tank doesn't need to be full - one bucket is enough.

This doesn't seem to work for me. The following configuration should be trashing everything, yet things still show up in my ME storage.

![2022-12-01_06 49 15](https://user-images.githubusercontent.com/12502988/205069779-55702943-0de0-47ce-8b64-90348c06fb3a.png)
![2022-12-01_06 49 25](https://user-images.githubusercontent.com/12502988/205069790-24f6ce4a-ec0f-4bbf-9605-b43ef99df8b1.png)

**Comment by Mournfulpuma** [comment]
> > Yes, you can use a tank from EnderIO filled with java, then pipe items into it.
> > Edit: The tank doesn't need to be full - one bucket is enough.
> 
> This doesn't seem to work for me. The following configuration should be trashing everything, yet things still show up in my ME storage.
> 
> ![2022-12-01_06 49 15](https://user-images.githubusercontent.com/12502988/205069779-55702943-0de0-47ce-8b64-90348c06fb3a.png) ![2022-12-01_06 49 25](https://user-images.githubusercontent.com/12502988/205069790-24f6ce4a-ec0f-4bbf-9605-b43ef99df8b1.png)

Did you make sure the Liquid Tank has the Void Mode selected as "Void Slot Accepts All Items"
![MinecraftEnderio](https://github.com/SleepyTrousers/EnderIO-1.5-1.12/assets/140352924/5a785687-5599-4aeb-9f68-137291ff6a36)
