### ISSUE TITLE
Flux Controller network creation crashes game!!!!!

### ISSUE THREAD

**Issue by TheLanceShipment** [SleepyTrousers/EnderIO#5302]
#### Issue Description:

I am currently playing on FTB Stone Block 2 version 1.16.0, and minecraft version 1.12.2

#### Steps to reproduce:

1. place flux controller
2. Click create new network 
3. Boom instant crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.51
- EnderCore: 1.12.2-0.5.69
- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 
[https://paste.dimdev.org/latapaqanu.mccrash]

**Comment by MatthiasMann** [comment]
This is clearly not a crash caused by EnderIO - it is clearly Flux Networks which crashes.
