### ISSUE TITLE
Armor Module Duping

### ISSUE THREAD

**Issue by cyberdragon442** [SleepyTrousers/EnderIO#5303]
#### Issue Description:

Armor modules dupe when trying to put on armor.

#### What happens:

If you shift right click armor with modules installed, it dupes all installed modules to your inventory and any subsequent attempts, even after relogging to use right click to equip it will dupe the modules

#### What you expected to happen:

Armor upgrade GUI to open and normal armor equipping.

#### Steps to reproduce:

1. Install modules into EnderIO armor (Stellar was used in this case)
2. Take off an armor piece
3. Shift right click it, the modules should now be duped
4. try to requip it with normal right click, it should dupe again
5. this is now irreversable, your armor is doomed to keep duping

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.52
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? yes (but irrelevant, non-graphical issue)
- Single Player and/or Server? Server
- Modpack: AetherColonies on Technic

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by CitiesXL2815** [comment]
it has been reported already https://github.com/SleepyTrousers/EnderIO/issues/5262
