### ISSUE TITLE
Wearing Stellar Helmet disables god mode fly by Monk mod

### ISSUE THREAD

**Issue by markuszeller** [SleepyTrousers/EnderIO#5305]
Wearing Stellar Helmet disables god mode fly of [Monk mod 1.4](https://www.curseforge.com/minecraft/mc-mods/the-monk-mod/files/2601488). Taking it off, flying is enabled, again. I have no other armor yet.

#### What happens:
Put the helm on and no flying possible. When putting the helm on during flight, you will fall down. I've crafted already almost every upgrade, but taking them all off keeps the problem.

#### What you expected to happen:
Being still able to fly.

#### Steps to reproduce:

1. Wear helmet
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.51
- EnderCore: 1.12.2-0.5.69
- Minecraft: 1.12
- Forge 14.23.5.2844
- SpongeForge? yes/no (what's that?) 
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

Did not find any error hint in the log.

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/71625419-0be22b00-2be8-11ea-8194-9c900b246087.png)

:facepalm:

**Comment by markuszeller** [comment]
My bad. I've overseen that. Thanks for investigation.
