### ISSUE TITLE
Dark Steel Upgrade "Speed" isn't working anymore since update to 1.12.2-5.1.53.jar

### ISSUE THREAD

**Issue by WWWonderWoman** [SleepyTrousers/EnderIO#5309]
#### Issue Description:

Dark Steel Upgrade "Speed" isn't working anymore since update to 1.12.2-5.1.53.jar

#### What happens:
Dark Steel Upgrade "Speed" isn't working anymore since update to 1.12.2-5.1.53.jar

#### What you expected to happen:
Dark Steel Upgrade are working fine after updating

#### Steps to reproduce:

1. back to 1.12.2-5.1.52.jar 
2. Speed Upgrades are working fine
3. update to 1.12.2-5.1.53.jar 
4. Speed Upgrades aren't working!

____
#### Affected Versions: 

- EnderIO: 1.12.2-5.1.53.jar
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: release forge-14.23.5.2847
- SpongeForge? no
- Optifine? yes 1.12.2_HD_U_F5
- Single Player and/or Server? Singe Player

**Comment by HenryLoenwind** [comment]
Does your armor have energy? Also check the hotkey, it could be off.

**Comment by WWWonderWoman** [comment]
> Does your armor have energy? Also check the hotkey, it could be off.

Yes, off course the armor have energy, I didn't change anything there while downgrading to the prior version. Also the hotkey is aktive.

Would a list of all of the mods I have installed be helpful here?

**Comment by WWWonderWoman** [comment]
Same problem after updating to EnderIO-1.12.2-5.1.55.jar so I downgraded again to the .52 version.

**Comment by jk1895** [comment]
I had the same problem but additionally jumping was not working. For incomprehensible reasons it's by default off. You have to go to the settings and set the keys for Speed and Jump. Now you can toggle it on.

**Comment by WWWonderWoman** [comment]
> I had the same problem but additionally jumping was not working. For incomprehensible reasons it's by default off. You have to go to the settings and set the keys for Speed and Jump. Now you can toggle it on.

Yes this works here, too! Thank you very much and sorry @HenryLoenwind in fact I didn't check if the settings were changed by the update... 😣

**Comment by HenryLoenwind** [comment]
It's not off by default, it's just that the "on" value of the previous version looks like "off" to the current version. Ooops, that wasn't on purpose...
