### ISSUE TITLE
After Updating to EnderIO-1.12.2-5.1.53 all painted blocks are black/pink

### ISSUE THREAD

**Issue by TheRealDadbeard** [SleepyTrousers/EnderIO#5310]
#### Issue Description:

After upgrading to EnderIO-1.12.2-5.1.53 every single painted block just became black/pink

#### What happens:

Painted blocks are black/pink

#### What you expected to happen:

Them not to be black pink

#### Steps to reproduce:

1.Have EnderIO-1.12.2-5.1.52
2.Update to EnderIO-1.12.2-5.1.53
3.Have black/pink painted blocks
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.53
- EnderCore: EnderCore-1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 2847
- SpongeForge? yes
- Optifine? yes
- erver?

#### Your most recent log file where the issue was present: 

server
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/4050124/latest.log)

client
[2020-01-12-1.log](https://github.com/SleepyTrousers/EnderIO/files/4050127/2020-01-12-1.log)

**Comment by TheRealDadbeard** [comment]
Rolling back fixes it FYI

**Comment by HenryLoenwind** [comment]
Found it. Chisel is cheating and our new code did not expect that.

**Comment by TheRealDadbeard** [comment]
glad you could fix it
