### ISSUE TITLE
Issue with the New EnderIo Update

### ISSUE THREAD

**Issue by BedrockLegends** [SleepyTrousers/EnderIO#5311]
#### Issue Description:
As soon as I launched it crashes at 4 out of 7
Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first. If you are using an unreleased version of Ender IO (a.k.a development/nightly version), please don't open an issue for features that have not been announced as "finished" or "working". Expect to be ignored if you ignore this template.

#### What happens:
Launch game and it crashes

#### What you expected to happen:
a fix

#### Steps to reproduce:

1. Updated Ender Io in my pack
2.wait till like 4 out of 7 
3. then crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.54
- EnderCore:1.12.2- 0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? yes/no no
- Optifine? yes/no no
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 
https://paste.dimdev.org/cedorixene.mccrash
[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
-> EIOP
