### ISSUE TITLE
Enchantments disabled but still usable on gear?

### ISSUE THREAD

**Issue by Yourname942** [SleepyTrousers/EnderIO#5312]
#### Issue Description:
The enchantments from EnderIO are able to enchant gear and apply their effects, even after being disabled in the config.

#### What happens:
1) I'm able to enchant my gear with witherarrow and witherweapon, even when disabled in config. 
2) the witherarrow enchantment is able to applied to a sword and causes wither to mobs

#### What you expected to happen:
1) l expected the enchantments that I disabled to be disabled.. ( B:enabled=false ), but they are still available to use and apply their effects to gear.
2) I expected wither enchantment for ranged weapons to only be applied to ranged weapons and not on a sword

#### Steps to reproduce:

1. create a new world: 
    a) cheats enabled
    b) superflat 
2. press E and get an anvil, a diamond sword, wither sword enchantment, and wither arrow enchantment
3. place an anvil down
4. insert diamond sword into anvil
5. combine with wither sword
6. attack a mob (they get withered)
7. press E and get a new diamond sword
8. insert the new/ different diamond sword into anvil
9. combine with wither arrow
10. attack a mob (they get withered)
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.55.jar
- EnderCore: EnderCore-1.12.2-0.5.73.jar
- Minecraft: 12.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/4055613/latest.log)

**Comment by CitiesXL2815** [comment]
EnderIO has two enchants that wither for bows and Decay for swords

**Comment by tyler489** [comment]
I believe that wither arrow is an endercore enchant not enderio although I could be wrong.

**Comment by HenryLoenwind** [comment]
Please test in survival mode. Creative mode skips most of the enchanting checks.
