### ISSUE TITLE
Crash with VanillaFix?

### ISSUE THREAD

**Issue by xJon** [SleepyTrousers/EnderIO#5313]
#### Issue Description:
This recent crash has EnderIO traces; any idea why?
https://paste.dimdev.org/walageciqo.mccrash

 Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.52
- EnderCore: 0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and Server

**Comment by HenryLoenwind** [comment]
Because you don't have a world loaded but are processing particle spawns from a world.

**Comment by xJon** [comment]
So it's a simple case of lag issues?

**Comment by HenryLoenwind** [comment]
Could be some mod changing vanilla code to change the timings of things, could just be a random timing event.

I'll add some protection code there.
