### ISSUE TITLE
[1.12.2] Padding Helemnt upgrade conflicts with super sound muffler

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [SleepyTrousers/EnderIO#5318]
#### What happens:
The Padding upgrade on the Dark Steel Helmet conflicts with the Super Sound Muffler bauble's black list in some sounds. Wearing the helmet with the padding upgrade causes the sounds to be heard, even though they are being blacklisted by the super sound muffler.

So far I have reproduced this with the Actually Additions reconstructor, The Draconic Evolution celestial manipulator, and Draconic Evolution Fusion crafting

#### What you expected to happen:
I would expect the super sound muffler's blacklist of the sounds to prevent them from being heard.

#### Steps to reproduce:

1. Have a super Sound muffler bauble with the AA reconstructor blacklisted equipped in the baubles slot
2. Equip a black steel helmet with the padding upgrade
3. Still hear the AA reconstructor
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player (only tested on singlplayer)

-Super Sound Muffler: 1.0.2.10

#### Your most recent log file where the issue was present: 

latest.log
https://gist.github.com/ALongStringOfNumbers/8e965113a68cc914afe14739b863169b

**Comment by CitiesXL2815** [comment]
pls also report to Super Sound Muffler's issue tracker bc may not be us might be on there end
