### ISSUE TITLE
Please, HELP!

### ISSUE THREAD

**Issue by AnpyHelp** [SleepyTrousers/EnderIO#5319]
Hello, Guys, I have a problem with minecraft. 
This is my crash report:
===========================================
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 22 total; [EntityWheel['entity.Wheel.name'/64, l='MpServer', x=846,25, y=236,06, z=-29,09], EntityGib['неизвестно'/1504, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['неизвестно'/1505, l='MpServer', x=0,00, y=0,00, z=0,00], EntityClientPlayerMP['Anpy'/65, l='MpServer', x=924,93, y=244,04, z=46,03], EntityVehicle['Chopper'/37, l='MpServer', x=845,50, y=237,00, z=-30,50], EntityCamera['неизвестно'/1415, l='MpServer', x=841,50, y=237,00, z=-18,50], EntityCamera['неизвестно'/1417, l='MpServer', x=845,50, y=237,00, z=-30,50], EntitySeat['entity.Seat.name'/52, l='MpServer', x=841,50, y=237,00, z=-18,50], EntitySeat['entity.Seat.name'/53, l='MpServer', x=841,50, y=237,00, z=-18,50], EntitySeat['entity.Seat.name'/54, l='MpServer', x=841,50, y=237,00, z=-18,50], EntitySeat['entity.Seat.name'/55, l='MpServer', x=841,50, y=237,00, z=-18,50], EntityWheel['entity.Wheel.name'/56, l='MpServer', x=842,41, y=236,06, z=-19,88], EntityWheel['entity.Wheel.name'/57, l='MpServer', x=840,66, y=236,06, z=-19,91], EntityWheel['entity.Wheel.name'/58, l='MpServer', x=840,56, y=236,06, z=-17,16], EntityWheel['entity.Wheel.name'/59, l='MpServer', x=842,31, y=236,06, z=-17,13], EntityVehicle['Audi Q7 2009 blau'/28, l='MpServer', x=841,50, y=237,00, z=-18,50], EntitySeat['entity.Seat.name'/60, l='MpServer', x=845,50, y=237,00, z=-30,50], EntityWheel['entity.Wheel.name'/61, l='MpServer', x=846,44, y=236,06, z=-31,81], EntityWheel['entity.Wheel.name'/62, l='MpServer', x=844,72, y=236,06, z=-31,94], MCH_ViewEntityDummy['McHeliDummyEntity'/1502, l='MpServer', x=0,00, y=-4,00, z=0,00], EntityWheel['entity.Wheel.name'/63, l='MpServer', x=844,53, y=236,06, z=-29,22], EntityGib['неизвестно'/1503, l='MpServer', x=0,00, y=0,00, z=0,00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11788769632 bytes (11242 MB) / 13723762688 bytes (13088 MB) up to 15871246336 bytes (15136 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx15117M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 119 mods loaded, 119 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	itemphysic{1.1.2} [ItemPhysic] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems_1.7.10_1.0.5.120_universal.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCHIJAAAA	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UCHIJAAAA	ClientFixer{1.0} [ClientFixer] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.3.2} [Damage Indicators] (1.7.10DamageIndicatorsMod_3.3.2.jar) 
	UCHIJAAAA	securitycraft{v1.8.13} [SecurityCraft] (1.7.10SecurityCraftv1.8.13.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] (1.7.10Treecapitator_universal_2.0.4.jar) 
	UCHIJAAAA	MCP_API{1.4} [MC+ API] (1.7.10v1.3.0_MC_Cart_.jar) 
	UCHIJAAAA	MCP_Wheel{1.1.2} [MC+ Wheel] (1.7.10v1.3.0_MC_Cart_.jar) 
	UCHIJAAAA	MCP_Cart{1.3.0} [MC+ Cart] (1.7.10v1.3.0_MC_Cart_.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft_2_2.2.827_ex1.7.10.jar) 
	UCHIJAAAA	AdvancedMachines{1.1.6} [IC2 Advanced Machines Addon] (advancedmachinesas-1.7.10.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanels.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft_1.7.10_1.5.0.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2_mc1.7.10_rv3_beta_6.jar) 
	UCHIJAAAA	ArmorStatusHUD{1.27} [ArmorStatusHUD] (armorstatushud_mod_1.7.10.jar) 
	UCHIJAAAA	astikoor{7.0.3} [Astikoor] (astikoor_1.7.10_7.0.3.jar) 
	UCHIJAAAA	babyanimals{1.7.10-4} [Baby Animals Model Swapper] (BabyAnimals_1.7.10_4.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack_2.0.1_1.7.x.jar) 
	UCHIJAAAA	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraftv1.11.6MC1.7.10.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenters_Blocks_v3.3.8.1_MC_1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks_1.7.10_Recommended.jar) 
	UCHIJAAAA	ChickenShed{1.1.3} [Chicken Shed] (ChickenShed-Mod-1.7.10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	crackedzombiemod{1.7.10} [CrackedZombie Mod] (crackedzombie_mod_1.7.10.jar) 
	UCHIJAAAA	craftablehorsearmour{1.1} [Craftable Horse Armour [CHA&S]] (Craftable_Horse_Armour_and_Saddle_Mod_1.7.10.jar) 
	UCHIJAAAA	creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.24 mc1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d29oct17.jar) 
	UCHIJAAAA	DarkRoleplay{0.1.3} [DarkRoleplay] (DarkRoleplay_0.1.3_Pre.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft_2.4.1_1.7.10.jar) 
	UCHIJAAAA	props{2.4.1} [Decocraft] (Decocraft_2.4.1_1.7.10.jar) 
	UCHIJAAAA	DynamicLights{1.3.5} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.5} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (enchantingplus_1.7.10_3.0.2_d.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.36_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.36_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila_1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.428_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.428_beta.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.1.0k} [Extra Utilities] (extra_utilities_mod_1.7.10.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (extracells-1.7.10-2.3.14b200.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans_Mod_1.7.10_4.10.0.jar) 
	UCHIJAAAA	flenixroads{0.10.0} [FlenixRoads] (FlenixRoads_1.7.10_0.10.0_b40.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite_1.7.10_2.0.3.jar) 
	UCHIJAAAA	IC2CA{1.14.5.06} [IndustrialCraft 2 Combo Armors] (ic2ca-1.7.10-1.14.5.06.jar) 
	UCHIJAAAA	IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2] (IC2NuclearControl_2.3.3a_Exist.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil_1.7.10_4.2.3.jar) 
	UCHIJAAAA	InfernalMobs{1.5.4} [Infernal Mobs] (infernal_mobs_mod_1.7.10.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks_1.7.10_1.59_dev_152.jar) 
	UCHIJAAAA	IronChest{6.0.41.729} [Iron Chest] (iron_chests_mod_1.7.10.jar) 
	UCHIJAAAA	ISM{3.0.0} [MaggiCraft's Instant Structures Mod] (ism-3.0.0.jar) 
	UCHIJAAAA	ismII{3.0.0} [MaggiCraft's Instant Structures Mod II] (ismII-3.0.0.jar) 
	UCHIJAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap_1.7.10_5.1.0_unlimited.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	mcheli{1.0.4} [MC Helicopter] (mcheli) 
	UCHIJAAAA	MobAmputation{4.0.0} [MobAmputation] (Mob-Amputation-Mod-1.7.10.jar) 
	UCHIJAAAA	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment_1.7.10_4.0.0.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks_2.4.4_mc1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.81.7.10.jar) 
	UCHIJAAAA	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons1710.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons1710.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons1710.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons1710.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons1710.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons1710.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons1710.jar) 
	UCHIJAAAA	neiintegration{1.1.1} [NEI Integration] (NEIIntegration.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pams_HarvestCraft_1.7.10k.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	PowerUtils{1.7.10-1.0.4} [PowerUtils] (PowerUtils_1.7.10_1.0.4.jar) 
	UCHIJAAAA	primitivemobs{1.0} [Primitive Mobs] (primitivemobs_1.0c_1.7.10.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-Base.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-Integration.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-Integration.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-Lighting.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-World.jar) 
	UCHIJAAAA	reccomplex{0.9.7.1} [Recurrent Complex] (RecurrentComplex_mc1.7.10_0.9.7.1.jar) 
	UCHIJAAAA	rivalrebels{1.7.10Z1} [Rival Rebels] (rivalrebels_1.7.10Z1.jar) 
	UCHIJAAAA	RTG{1.7.10-1.1.1} [Realistic Terrain Generation] (RTG_1.7.10_1.1.1.jar) 
	UCHIJAAAA	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UCHIJAAAA	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	UCHIJAAAA	soundfilters{0.4_for_1.7.X} [Sound Filters] (sound_filters_mod_1.7.10.jar) 
	UCHIJAAAA	supersolarpanel{1.7.10-1.1.1-release} [Super Solar Panel] (SSP-1.1.2-NEW-Photonic_Solar_Panel_1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAAAA	tlauncher_custom_cape_skin{1.0} [TLSkinCape] (tlskincape_1.7.10-1.4.jar) 
	UCHIJAAAA	torchLevers{1.4} [Torch Levers] (torch_levers_mod_1.7.10.jar) 
	UCHIJAAAA	toxicworld{0.0.1} [Toxic World] (Toxic_World.jar) 
	UCHIJAAAA	tumbleweed{1.7.10-0.2} [Tumbleweed] (tumbleweed_1.7.10_0.2.jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
	UCHIJAAAA	WLM{1.4.3} [The Wasteland Mod] (Wasteland-1.7.10-1.4.4.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla_1.7.10_1.0.5.120.jar) 
	UCHIJAAAA	wildcaves3{0.4.3.6} [Wild Caves 3] (wild_caves_mod_1.7.10.jar) 
	UCHIJAAAA	wolfarmor{1.3.0} [Wolf Armor and Storage] (wolfarmor_1.7.10_1.3.0.1.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit_forge_mc1.7.10_6.1.1_dist.jar) 
	UCHIJAAAA	WorldEditCUI{1.7.2_02} [WorldEditCUI] (WorldEditCUI.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1660/PCIe/SSE2'
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	ThermalDynamics: -[1.7.10]1.2.1-172
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from EnderIO-1.7.10-2.3.0.428_beta.jar).
                    It is a supported version, but that difference may lead to problems.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2_mc1.7.10_rv3_beta_6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithful_1.7.zip, Tissous-Zombie-Pack-1.7X.zip, PresenceFootstepsOfficial.zip]
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MatthiasMann** [comment]
That's not a crash report - that's just the general info section.

**Comment by AnpyHelp** [comment]
I edit to all text of config

**Comment by MatthiasMann** [comment]
There is nothing related to any mod in the stacktrace.

**Comment by AnpyHelp** [comment]
> There is nothing related to any mod in the stacktrace.

I can give you the log file

**Comment by AnpyHelp** [comment]
> There is nothing related to any mod in the stacktrace.

How I can give you it?
