### ISSUE TITLE
[1.12.2] Fluid conduits disconnect from Tconstruct Tinker Tank

### ISSUE THREAD

**Issue by ghostbuster3210** [SleepyTrousers/EnderIO#5323]
#### Issue Description:
Fluid conduits and Pressurized fluid conduits will disconnect from the tinker tank, as if not identifying it as a valid container. i've only noticed this happening when exiting and re-entering a world. The pipe will re-connect if it is updated, such as placing/breaking a block next to it, or pressing a button infront of it.

#### What happens:
Trying to connect fluid conduits to a tinker tank, some conduits will disconnect upon leaving and re-entering the singleplayer world, while others seem to work just fine, with no real indication as to what is causing it.

#### What you expected to happen:
I expect the pipes to stay connected.

#### Steps to reproduce:

1.create a tinker tank?
2.hook up some conduits to it
3.exit and enter the world
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:5.1.55
- EnderCore:0.5.73
- Minecraft:1.12.2
- Forge:1.12.2-14.23.5.2847
- SpongeForge? no
- Optifine? yes
- Single Player 

#### Your most recent log file where the issue was present: 

https://gist.github.com/ghostbuster3210/4abc48c18008d5f0fd05029b5a677ffe

Below are images of conduits on the tinker tank, displaying the randomness of whether they will connect or not. Before exiting the world and re-entering, all conduits in the image were connected to the tank and would work without issue.

![Image 1](https://user-images.githubusercontent.com/12783873/74201828-654e6880-4c30-11ea-9647-b13459a385b9.png)
![Image 2](https://user-images.githubusercontent.com/12783873/74201862-7eefb000-4c30-11ea-8af6-eb242e212906.png)

**Comment by HenryLoenwind** [comment]
Known bug in Tinkers. Their (multi)blocks change their connectability without telling their neighbors about.

**Comment by deKilla** [comment]
Easy ingame fix is to cause a block update to the connection (like placing a block next to it).
Not a permanent fix, unless you can cause an automated block update everytime the server (re)starts.
