### ISSUE TITLE
Client Crash with the Vat 

### ISSUE THREAD

**Issue by idnthvn** [SleepyTrousers/EnderIO#5325]
#### Issue Description:
On a multiplayer server, looking in JEI for Vat recipe, i can see the recipe how to make the vat. however, when i look to see what the Vat can make (liquids) it crashes the client. Server is untouched. 
In Single player, it works fine.

#### What you expected to happen:
To open the liquid recipes for the Vat

#### Steps to reproduce:

1.Launch MC with mods
2.Look for VAT in JEI and rightclick to see what it makes
3.Client Crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.52
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge:1.12.2 2847
- SpongeForge? yes version 7.1.10RC3994
- Optifine? yes - I also removed this and still crashes
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/hefoxepuyu.mccrash

**Comment by CitiesXL2815** [comment]
it might be spongeForge issue bc are server doesn't cause any clients to crash to the vat

**Comment by idnthvn** [comment]
i removed spongeforge, and still same crash on server

**Comment by CitiesXL2815** [comment]
what Version is JEI is it latest or no

**Comment by idnthvn** [comment]
Version 1.12.2 4.15.0.293

**Comment by CitiesXL2815** [comment]
is this full crashlog

**Comment by idnthvn** [comment]
yes, that is the full crash log. When Optifine was installed, there was only another line, half way down the first section that was in there (thought optifine was the cause and got rid of that too on the client)
Sry i updated my last comment so i didnt double answer.

**Comment by CitiesXL2815** [comment]
some information in crashlog is missing

**Comment by idnthvn** [comment]
[crash-2020-02-14_22.17.56-client.txt](https://github.com/SleepyTrousers/EnderIO/files/4207738/crash-2020-02-14_22.17.56-client.txt)
-Without Optifine
[crash-2020-02-14_22.33.45-client.txt](https://github.com/SleepyTrousers/EnderIO/files/4207739/crash-2020-02-14_22.33.45-client.txt)
-With Optifine

**Comment by tyler489** [comment]
That second report has nothing to do with enderio. Are you sure that's the right report?

**Comment by idnthvn** [comment]
I fixed it (now the optifine crash log is correct

**Comment by idnthvn** [comment]
Fixed: 
Issue was mod name: WOOT was installed on client, and was not on server.  Removed it off of client and works just fine. Have NO idea why it would cause an issue with EnderIO but this has been resolved. and i will close it.
