### ISSUE TITLE
EnderIO Upgrades do not work. At all. Only responds with no valid items

### ISSUE THREAD

**Issue by Solverbolt** [SleepyTrousers/EnderIO#5326]
#### Issue Description:

Using just Current version of EnderIO. All dark steel upgradable items are not recognized as valid. Meaning that you cannot empower them, or any other upgrades. tested every single one.  And this is using just EnderIO on a modified Vanilla loading.

#### What happens:
Absolutely Nothing happens, except that it tells me no items are upgradable. 

#### What you expected to happen:

For it to give me some form of option to pick something to upgrade

#### Steps to reproduce:

1. make Blank, then load blank with upgrade, charge it with experience
2. Right Click either object or tool
3. Error from Enderio stating nothing is upgradable
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.51.jar
- EnderCore: EnderCore-1.12.2-0.5.69.jar
- Minecraft: 1.12.2
- Forge: 12.23.5.2846
- SpongeForge? yes/no: no
- Optifine? yes/no : no
- Single Player and/or Server? Both single and attempted in multiplayer

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
Are you doing this in a darksteel anvil?

**Comment by Solverbolt** [comment]
yep. tried every available pathway and pattern style.

**Comment by CitiesXL2815** [comment]
are you doing right upgrade bc it works just fine

**Comment by Solverbolt** [comment]
ya know what. I stated clearly, that I followed not just the steps listed, but also further tested other methods. But if this is going to be the responses i get, then this mod no longer needs to be used in modpacks, as it is clearly broken, and the dev/assistants clearly want to falsify any bug claims, just to make themselves look good.  It never seems to stop, this idea that devs can continue to push broken content to people, claiming it works, just to promote their work, and they will brown nose whatever modpack developer they can to use their broken stuff with pretty lies and false claims of plans to fix it.   Reminds me of why i stopped playing Ark, because this is the EXACT same way they treated the people using their work. just fuck off.  its obvious i wont get any intelligent or truthful responses other than from trolls who spawn items in to claim the mod is working correctly

**Comment by CitiesXL2815** [comment]
dude i just tested it in game right now seems to work just fine your must be doing it wrong

**Comment by CitiesXL2815** [comment]
plus we didn't close the issue just yet it can still be bug so i tag 1.12 we'll see what Henry says

**Comment by HenryLoenwind** [comment]
stop spewing 4-letter words if you want to be taken seriously.
