### ISSUE TITLE
Putting upgraded Dark Steel Armor into vanilla item frame duplicates upgrades

### ISSUE THREAD

**Issue by CplPibald** [SleepyTrousers/EnderIO#5327]
#### Issue Description:
Duplicate DS armor upgrades by putting armor into item frame.  Similar to #5262, but different repro steps

#### Steps to reproduce:

1. Place a vanilla item frame
2. Hold in your hand a DS chestplate with several upgrades
3. Shift-right click the armor into the item frame

Expected: Upgrades stay on item in frame

Observed: All upgrades pop out of the armor into your inventory, but item in frame still has all of the upgrades, resulting in duplicated DS upgrade items.

...

____
#### Affected Versions

- EnderIO: 5.1.55
- EnderCore: 0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Dedicated Server

**Comment by tyler489** [comment]
Yay another case of "equipping" destroying the item... thanks forge...

**Comment by EnterFor** [comment]
I have also encountered this problem and am just ready to give feedback.
Dark steel sword also has this problem, can it be fixed?

**Comment by bigenergy** [comment]
+1 same problem

**Comment by Nothingness-Void** [comment]
I have the same problem too

**Comment by last903347** [comment]
same problem, every player in my sever started use this bug copy items

**Comment by FreezePhoenix** [comment]
There's another bug that I'm not sure if it got fixed, but in Seablock, if you shift + click an upgrade out of the upgrade menu, it fills all available slots in your inventory and the storage slots in the item with that upgrade, and produces an error that is caught by VanillaFix that would otherwise crash the game.
