### ISSUE TITLE
Elytra error while launching modpack.

### ISSUE THREAD

**Issue by RainRahni** [SleepyTrousers/EnderIO#5333]
#### Issue Description:

I am launching Texkit 3 modpack.

#### What happens:
. When launchin in the first mod initializing phase when reaching Ender IO it stops and shows that it is stopped because something has happened to Ender IO. 

#### What you expected to happen:

I expected it to initialize without any error.

#### Steps to reproduce:

1.Reinstall launcher
2.Reinstall modpack
3.Update mods.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.52
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and Server

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/zukajabequ.mccrash

**Comment by HenryLoenwind** [comment]
#5259
