### ISSUE TITLE
ME Conduit Render Exception

### ISSUE THREAD

**Issue by Erosion139** [SleepyTrousers/EnderIO#5334]
#### What happens:
Placing an ME conduit causes a render exception error and the conduit becomes invisible. Checked similar issues and I haven't seen the ME conduit specifically cause render issues without also crashing the client/server. Might have to do with VanillaFix. All other conduits work perfectly with bundles. 

#### What you expected to happen:
The conduit to be visible and not give me an error. 

#### Steps to reproduce:

1. Place a random conduit (redstone energy item) 
2. Bundle an ME conduit with the previous conduit.
3. Break the ME conduit
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? (yes)
- Optifine? (yes) but reproducable without
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/4298908/latest.log)

Extra contextual image
![image](https://user-images.githubusercontent.com/52477940/76094779-2c848380-5f91-11ea-98a5-23d0f21fd235.png)

**Comment by HenryLoenwind** [comment]
#5158
