### ISSUE TITLE
Graphical error displaying the field of view when shooting Dark and Ender bows.

### ISSUE THREAD

**Issue by MrLador** [SleepyTrousers/EnderIO#5336]
When shooting bows, part of the image field of view disappears.
How to repeat:
Quickly pull the bow and release, to secure repeat several times in a row. Missing parts of the field of view appear at the edges.
<a href="https://imgur.com/3564Rrk"><img src="https://i.imgur.com/3564Rrk.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/FfcYISj"><img src="https://i.imgur.com/FfcYISj.png" title="source: imgur.com" /></a>
- EnderIO: 5.1.55
- EnderCore: 0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge no
- Optifine no
- Single Player

**Comment by CitiesXL2815** [comment]
is your graphics card up to date bc i don't have any issue with this try reproduce the issue as well

**Comment by MrLador** [comment]
I have an RX570 with the latest drivers. If you consider that in other games, for example in Shadow of the Tomb Raider, The Witcher 3 Wild Hunt, there are no problems at all .

**Comment by MrLador** [comment]
https://radikal.ru/video/UWH7IOtAVQd

**Comment by MrLador** [comment]
I think this is already an emphasis on the minecraft engine, from the rapid approximation of the buggy download of the review.

**Comment by HenryLoenwind** [comment]
That's a known bug in Minecraft itself.
