### ISSUE TITLE
Powered spawner with sheep not working

### ISSUE THREAD

**Issue by GhostyCake** [SleepyTrousers/EnderIO#5338]
#### Issue Description:
Powered spawned won't spawn sheep I have met all the spawning requirements.

#### What happens:
The spawned says "No viable space, No space found, Denied by another mod"

#### What you expected to happen:
I expected it to spawn sheep

#### Steps to reproduce:

1. Place a powered spawned with sheep
2. Surround it with grass
3. Give it power
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.52
- EnderCore: EnderCore-1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2847
- SpongeForge? no
- Optifine? no
- Server

![image](https://user-images.githubusercontent.com/46168788/76348154-026ff000-6308-11ea-9ddf-9b9759d87848.png)

**Comment by HenryLoenwind** [comment]
Why do you call us reporting that spawning was "Denied by another mod" a mistake we made?
