### ISSUE TITLE
[1.7.10] Crash when starting up mod pack

### ISSUE THREAD

**Issue by Zsashas** [SleepyTrousers/EnderIO#5340]
#### Issue Description:

Now, I know this is for 1.7.10. I don't expect a fix. I just have been trying to figure out why this is crashing, this is the fourth unique crash in the last several hours at this point, each from different mods. This whole thing started from trying to add Thaumic Energistics, and AE2. Before that, this whole pack otherwise worked perfectly. Since then, AE2, Chromaticraft, Thaumic Tinkerer, and AE2 itself have all crashed for various reasons that have since been fixed. Now it's EnderIO's turn, it seems.

#### What happens:

Crashes when trying to load the game.

#### What you expected to happen:

Not that.

#### Steps to reproduce:

1. Launch the game
2. Wait
3. Read crash report

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.429_beta
- EnderCore: 0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 7.99.40.1614 (I hope this is the right number)
- SpongeForge? No
- Optifine? Yes and No (tried both with and without, made no difference)
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

https://gist.github.com/Zsashas/edffd243532aa7f1cbb990b340f3e06a

**Comment by HenryLoenwind** [comment]
`Caused by: java.lang.SecurityException: class "cofh.api.tileentity.IRedstoneControl"'s signer information does not match signer information of other classes in the same package`

Looks like the COFH API is being loaded from 2 different signed jars. My suggestion would be to download the pure API jar and rename it something like "aaaaaa.jar" so it is loaded first.

**Comment by Zsashas** [comment]
Would that be the CoFH Core mod or something else?

**Comment by Zsashas** [comment]
Hoyl hell, that worked. You have saved me SO MUCH time and frustration. THANK YOU.
