### ISSUE TITLE
Off-hand 'blink' with The Ender non-functional due to equipment mini-anvil being called

### ISSUE THREAD

**Issue by Matakor** [SleepyTrousers/EnderIO#5341]
#### Steps to reproduce:

1. Turn on blink off hand
2. Use blink off hand
3. ???
4. Anvil page either opens or you only get text saying 'no upgradeable dark steel items equipped'. No profit, no blink. :(

____
#### Affected Versions (Do *not* use "latest"): 

- EnderIO: 5.1.55
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single player

This is in the latest E2:E pack, but I haven't seen any newer versions of the mods to test against.

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
No log output references this particular fault (maybe not verbose enough?)

**Comment by CitiesXL2815** [comment]
sword weapon not really for off hand teleporting staff of travelling other hand works

**Comment by Matakor** [comment]
You can put the traveling modifier on it. I don't see why you can't use it for that purpose.

**Comment by CitiesXL2815** [comment]
sword and pick that has travelling does not work in off hands that's way was coded staff of travel only one that works in off hand
