### ISSUE TITLE
Missing recipes and uses in JEI

### ISSUE THREAD

**Issue by TheK0tYaRa** [SleepyTrousers/EnderIO#5342]
#### What happens:
missing:
JEI 
     uses for 
            - [ ] Infinity Reagent
            - [ ] Glowstone Nano-Particles
     recipe of 
             - [ ] Confusion Powder
             - [ ] Ender Fragment

#### What you expected to happen:
Ender Fragment      - [ ] 
Confusion Powder  - [ ] 
                              having at least Info tab

____
#### Affected Versions (Do *not* use "latest"):

- JustEnoughItems: 4.15.0.293
- EnderIO: 5.1.52
- EnderCore: 1.12.2-0.5.72
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Optifine: 1.12.2_HD_U_F5
- Single Player and Server

**Comment by HenryLoenwind** [comment]
"Infinity Reagent" is only visible in JEI when Endergy is installed. It then also has uses.

"Glowstone Nano-Particles" don't have any uses as they are not a crafting component but an block to be placed.

"Confusion Powder" and "Ender Fragment" don't have recipes as they are mob drops and are only visible in JEI when Enderio Zoo is installed.

**Comment by TheK0tYaRa** [comment]
No Enderio Zoo or Endergy installed

**Comment by HenryLoenwind** [comment]
Depends on what your issue actually is.

(a) Are you seeing those 3 items in the JEI ingredient list without having endergy/zoo installed?

(b) Did you expect JEI to hide recipes for hidden items?

**Comment by VT-14** [comment]
All of those items are in Ender IO's Base module (for consistency, and in case add-ons or pack authors want to use them).  They are typically hidden from the JEI list when they aren't being used, but other add-ons or custom recipes could be messing with that 'hide these useless items' feature.

You'll always be able to find them when combing through recipes; the recipes you are seeing are in Ender IO Base as well.

No, I don't think this is worth bothering JEI over.  If you are seeing them in the JEI list and are being bothered by 3 clutter items, then JEI has a built-in item hiding option.

**Comment by TheK0tYaRa** [comment]
The items themselves aren't searchable by the way. Can't hide them.

**Comment by tyler489** [comment]
Working as intended then
