### ISSUE TITLE
i cant open my inventory , i cant die ,and i dont have hearts

### ISSUE THREAD

**Issue by tzlil17377** [SleepyTrousers/EnderIO#5345]
i cant open my inventory , i cant die ,and i dont have hearts

**Comment by tzlil17377** [comment]
iam playing with some crazy craft mods and i have inventory pets mod so when i died it bring me back to life but when i open my inventory i so my character was dead but everything was fine so i keep doing my thing then i couldnt open my inventory i didnt have any hearts ,where my hearts used to be where just my armor i didnt saw my hearts they war gone

**Comment by tyler489** [comment]
so report this to inventory pets
