### ISSUE TITLE
Owls don't ever hoot

### ISSUE THREAD

**Issue by SSyl** [SleepyTrousers/EnderIO#5348]
#### Issue Description:

Owls don't hoot regardless of the config settings of their volume or hoot interval. This happens regardless of the time of day. However, if you do the /playsound enderio:owl.hootsingle or enderio:owl.hootdouble command, it does play the sound in-game. So, the sound is definitely registered. Just the entity won't play it by itself. Also, Owls *do* play their hurt noise naturally.

#### What happens:

Owl's don't ever hoot.

#### What you expected to happen:

Owls to hoot at night.

#### Steps to reproduce:

1. Spawn owls (it happens with any amount)
2. Wait or set the time to night
3. Owls won't hoot
____
#### Affected Versions (Do *not* use "latest"):

-EnderIOZoo: 1.12.2-5.1.55
- EnderIO: 1.12.2-5.1.55
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Happens in both. However, the log file is from Single Player.

#### Your most recent log file where the issue was present: 

https://pastebin.com/Hdc5vyHv

**Comment by CitiesXL2815** [comment]
this known bug reported already in discord lol
