### ISSUE TITLE
Combining Powered Spawn and broken spawner in anvil doesn´t worke

### ISSUE THREAD

**Issue by Stooorzi** [SleepyTrousers/EnderIO#5350]
#### Issue Description:

I craeted my own modpack with twitch. Now I want to craft an powered spawner in anvil with a broken spawner. The problem is that it wount worke, the crafting recipie dont worke. 

I installed the mods: ender IO, Ender IO Endergy, Ender Tweaker, Ender Storrage 1.8+, Ender Zoo, Ender Core

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no 
- Optifine? yes
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 
Pastebin ist to small
[2020-03-31-2.log](https://github.com/SleepyTrousers/EnderIO/files/4411800/2020-03-31-2.log)

**Comment by MatthiasMann** [comment]
Which mob?

**Comment by Stooorzi** [comment]
All Mobs don't worke

**Comment by Stooorzi** [comment]
> Which mob?

All Mobs don't worke

**Comment by tyler489** [comment]
are you doing the powered spawner first?

**Comment by Stooorzi** [comment]
> are you doing the powered spawner first?

Yes of course

**Comment by CitiesXL2815** [comment]
![2020-03-31_16 40 32](https://user-images.githubusercontent.com/8730524/78085006-8731b500-736e-11ea-9b2e-28746385ac8c.png)

**Comment by CitiesXL2815** [comment]
works just fine

**Comment by Stooorzi** [comment]
> works just fine

But not in my Modpack

Try it Twitch: MCStorzi

**Comment by CitiesXL2815** [comment]
pack custom as well with 289 mods
 so this is not a issue sorry

**Comment by Stooorzi** [comment]
> pack custom as well with 289 mods
> so this is not a issue sorry

But can you help me I just want to fix it

**Comment by BillBodkin** [comment]
I found using the dark steel anvil worked in my pack while the vanilla one did not, so maybe give that a go. @Stooorzi
