### ISSUE TITLE
Killer Joe - The Ender braking causes crashes 

### ISSUE THREAD

**Issue by RouNNdeL** [SleepyTrousers/EnderIO#5351]
#### Issue Description:

The server crashes when _The Ender_ placed in the _Killer Joe_ is being destroyed. _The Ender_ put into the _Killer Joe_ was from a loot chest and had some upgrades on already. However these have been removed before using it in the _Killer Joe_. 

#### What happens:
The server crashes.

#### What you expected to happen:
_The Ender_ should get destroyed.

#### Steps to reproduce:
I'm not 100% sure of this.

1. Find _The Ender_ in a loot chest
2. Remove all it's upgrades
3. Put it into the _Killer Joe_
4. Wait for _The Ender_ to break
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 0.5.73
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2847
- SpongeForge? yno
- Optifine? yes
- Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/twuDKWUd

**Comment by RouNNdeL** [comment]
I've managed to recover the server by setting the difficulty to peaceful and taking _The Ender_ out. Then I used it on some entity and it broke without crashing.

**Comment by RouNNdeL** [comment]
I updated the issue, do you also need a full server log, or is the crash log enough?

**Comment by tyler489** [comment]
@HenryLoenwind don't drop items when the ender is not in a player inventory or things like this can happen

**Comment by RouNNdeL** [comment]
Wouldn't it be possible to drop the items on the ground so that the vacuum chest would pick them up? I'm not a modder, but as a player I wouldn't expect the upgrades to just disappear into thin air.

**Comment by HenryLoenwind** [comment]
Nothing to do with the Killer Joe, what happens is that there's an item in the Ender's upgrade inventory and the dropping code thinks it's an active upgrade.
