### ISSUE TITLE
Ender Fluid Conduit priority setting not working/being ignored

### ISSUE THREAD

**Issue by SevenChords** [SleepyTrousers/EnderIO#5352]
#### Issue Description:

i have a astral sorcery lightwell connected to different cyclic tanks using ender fluid conduits.
i set one with a priority of 1, the other with a priority of 10.

#### What happens

the liquid starlight is distributed evenly across both tanks instead of filling up the higher priority one first.

#### What you expected to happen:

the tank with the higher priority should be filled up first, and only if that one is full the other one should be receiving liquid starlight

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 0.5.7.3
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

**Comment by Ommina** [comment]
Clarification: Is Round Robin on or off?  (See #4774)

**Comment by SevenChords** [comment]
thanks, disabling that solved the issue, although i'm wondering why round robin overrides the priority, since that doesn't make sense to me
