### ISSUE TITLE
EnderIO Suggestion! Salvage

### ISSUE THREAD

**Issue by Devalut** [SleepyTrousers/EnderIO#5357]
majority of the time I find boots in dungeon loot, i've gotten so many boots that I'm beginning to wonder if the author of this mod has a foot fetish.

I have a few ideas for getting uses out of old tools or machines:

1. Why not add a recipe for the sag mill to chew up old boots and upgrades, I'd love to be able to reclaim that sweet dark steel and use it for something else, or hell salvage the piston or vibrant crystal from the upgrade piece for something else.

2. Trash compactor that creates a junk cube/item, activating the junk cube results in a draw to get all the individual parts that make up the item, ex. The Ender sword with empowered, would results in individual chances for two dark steel ingots, a stick, and an empowered upgrade.

**Comment by CitiesXL2815** [comment]
won't work you got take the upgrades out first before sag milling it

**Comment by Devalut** [comment]
Sticks are a necessary and noble sacrifice I'm willing to make.

**Comment by CitiesXL2815** [comment]
it makes no sense stick really easy to get

**Comment by Devalut** [comment]
I think we have a misunderstanding, I'm saying don't care about the sticks.

**Comment by CitiesXL2815** [comment]
i'm sorry this may not work with armor or tools having upgrades it does work when there are no upgrades installed and the upgrade mechanics has been changed you take them out with dark steel anvil

**Comment by CitiesXL2815** [comment]
oh tinkers smelter works as well without upgrades
