### ISSUE TITLE
Redstone Conduits - No output signal

### ISSUE THREAD

**Issue by Klaasgow** [SleepyTrousers/EnderIO#5358]
#### Issue Description:

Having the following installed:

Only forge and EnderIO / EnderCore

#### What happens:

Providing a redstone conduit with a signal works, but they won't forward them / give no output signals

#### What you expected to happen:

An output signal

#### Steps to reproduce:

Setup small contraption with redstone conduits:
1. Any machine, or redstone lamp on one side
2. redstone block, torch, anything that emits a signal on the other side
3. Signal Probe logs that a signal is provided, but no output
...

____
#### Affected Versions (Do *not* use "latest"):

Minecraft v1.12.2
Minecraft Coder Pack v9.42
Forge Mod Loader v8.0.99.99
Forge v14.23.5.2847
EnderCore v1.12.2-0.5.73
EnderIO v5.1.55

Optifine? no
Single Player and Server? Yes

#### Your most recent log file where the issue was present: 

https://pastebin.com/SFg8f8GK

![2020-04-04_01 44 33 EnderIO_test](https://user-images.githubusercontent.com/63097106/78413038-f8df5c80-7615-11ea-8a9a-60aeacc4c595.png)

**Comment by CitiesXL2815** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/5206 same issue

**Comment by VT-14** [comment]
The default input color channel is Red.  The default output color channel is Green.  They are different to prevent accidental signal transmission when adding stuff to an existing line (see also the Item Conduits extract being never active by default).

Your picture is lined up in such a way that I can't see both the inputs and outputs on a single line, but all of the visible inputs are Red and the only output I see on the Alloy Smelter is Green.

**Comment by Klaasgow** [comment]
> 
> 
> #5206 same issue

I don't know if it is exactly the same issue, because you don't have to flick on and off anything: Just put a redstone block next to a conduit that's next to an alloy smelter and it already doesn't work...

**Comment by Klaasgow** [comment]
> 
> 
> The default input color channel is Red. The default output color channel is Green. They are different to prevent accidental signal transmission when adding stuff to an existing line (see also the Item Conduits extract being never active by default).
> 
> Your picture is lined up in such a way that I can't see both the inputs and outputs on a single line, but all of the visible inputs are Red and the only output I see on the Alloy Smelter is Green.

-.- Okay, time to go to bed: Yep output was green indeed... Sorry for wasting your time!
