### ISSUE TITLE
Not able to modify max transfer rates of a Dimensional Transceiver

### ISSUE THREAD

**Issue by xDefcon** [SleepyTrousers/EnderIO#5359]
As the title says I can not find a way to edit the default energy transfer rates (per tick) of a Dimensional Transceiver with its relative capacitor types. Is it possible via config?

**Comment by xDefcon** [comment]
Is it possible or not?

**Comment by CitiesXL2815** [comment]
actually can you re-post but use template this time we also need the information what versions the affect and the game version also forge that why template there for reason so we can help you know what i'm saying
