### ISSUE TITLE
Destroying the Overclocked Generator with Direct upgrade crashes 

### ISSUE THREAD

**Issue by RouNNdeL** [SleepyTrousers/EnderIO#5360]
#### Issue Description:

When attempting to destroy the Overclocked Generator from Extra Utilities with the Ender Pickaxe with a Direct upgrade applied, the server crashed. After the server restarted the generator was not destroyed and was duplicated into the inventory as well.

#### What happens:

The server crashes.

#### What you expected to happen:

The block should be placed in the inventory.

#### Steps to reproduce:

1. Place the Overclocked Generator
2. Destory it with a tool with Direct Upgrade applied.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 0.5.73
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2847
- SpongeForge? yno
- Optifine? yes
- Server

#### Your most recent log file where the issue was present: 

The log is massive, almost 1MB - all player NBT.
https://gist.github.com/RouNNdeL/c61260b6d911bb2794c768a2909d322e

**Comment by HenryLoenwind** [comment]
That's a bug in the mod that block belongs to. They are giving the list of items they drop as an unmodifyable list which violates Forge's API.
