### ISSUE TITLE
Game crashes when i hold fused quartz.

### ISSUE THREAD

**Issue by HenryC94** [SleepyTrousers/EnderIO#5362]
Issue Description:
Fused Quartz is broken.

What happens:
The modpack i have the issue is one of my own: https://www.curseforge.com/minecraft/modpacks/evolving-infinity . I'm using the latest released version of enderIO (EnderIO-1.12.2-5.1.54), when i hold fused quartz glass, only tried with clear, but must crash with the other types, the game crashes and says this: https://pastebin.com/3ivHfnDx

What you expected to happen:
I was just expecting to make the fused quartz and it would not crash my game.

Steps to reproduce:

1. Just grab Fused Quartz.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.55
- EnderCore: EnderCore-1.12.2-0.5.75
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847
- SpongeForge? no
- Optifine? yes
- Single Player and Server

**Comment by CitiesXL2815** [comment]
![2020-04-07_14 52 14](https://user-images.githubusercontent.com/8730524/78722984-6e318280-78df-11ea-9142-1c708fbeab7d.png)
hmm holding fused quartz but no crash

**Comment by HenryC94** [comment]
The issue was with unifier. Thanks anyway.
