### ISSUE TITLE
Vacuum Chest not working

### ISSUE THREAD

**Issue by CrimeBerry** [SleepyTrousers/EnderIO#5363]
What happens:
The Vacuum Chest doesn't shows the Interface/Settings
![image](https://user-images.githubusercontent.com/42157725/78731325-bb454100-793f-11ea-8add-ed7e0b300e47.png)

What you expected to happen:
That the Settings show

Steps to reproduce:

1. Launch FTB Presents Crackpack (v1.1.0)
I addet the mods Hats-4.0.1 , HatStand-4.0.0 , MalisisCore-1.7.10, MalisisDoors-1.7.10 , OptiFine_1.7.10_HD_UD6 , SolarExpansion-Basic.1,6a
       
2. Open a world (Single/Multiplayer)

3. Place a Vacuum chest and open it 

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.7.10 - 2.2.8.381
- EnderCore: 1.7.10 - 0.2.0.36_beta
- Minecraft: 1.7.10
- Forge: 10.13..4.1614
- SpongeForge: no
- Optifine: yes
- Single Player and/or Server: - Both

**Comment by CitiesXL2815** [comment]
We don't support 1.7.10 anymore we moved on to 1.12.x
