### ISSUE TITLE
EnderIO crashes on my friend's PC, but not on mine

### ISSUE THREAD

**Issue by TheCoolMouseK** [SleepyTrousers/EnderIO#5365]
#### Issue Description:

We both use the same Java version (the latest). Now that I think of it, EnderIO never ran on his machine (he tried different modpacks in the past, even tried running the mod by itself)

#### What happens:

title

#### What you expected to happen:

Minecraft to run

#### Steps to reproduce:

1. Go to Technic Launcher
2. Download the modpack name "MWUCR"
3. Run the modpack and see if it crases or not
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55, but as I said this issue appears on older versions too
- EnderCore: 0.5.73, but as I said this issue appears on older versions too
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

https://pastebin.com/60jKWB04

**Comment by VT-14** [comment]
#5259
