### ISSUE TITLE
[1.12.2] Can't disable the Logs to Sticks recipe with CraftTweaker

### ISSUE THREAD

**Issue by aaronhowser1** [SleepyTrousers/EnderIO#5366]
#### Issue Description:
![image](https://user-images.githubusercontent.com/15698722/79138178-b2a69d80-7d79-11ea-8f1d-9df6ef032f30.png)
Both of these recipes only show up when EnderIO is installed. Only the first one can be disabled with CT2.

#### What happens:
When I use the CT script `recipes.remove(<minecraft:stick>);`, only the first one gets removed.

![image](https://user-images.githubusercontent.com/15698722/79138419-1a5ce880-7d7a-11ea-833d-b8ac58a557cf.png)

The second recipe also doesn't say it's added by Ender IO, but it goes away when I remove the mod
![image](https://user-images.githubusercontent.com/15698722/79138512-40828880-7d7a-11ea-8cb9-9adb11043b34.png)

Interestingly, the recipe doesn't actually work. In that case, what's up with *that*?

#### What you expected to happen:

The recipe should be removed.

#### Steps to reproduce:

1. Use a script to remove stick recipes
2. Observe as stick recipe is not gone
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.55
- EnderCore: EnderCore-1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 
https://pastebin.com/BzBgD6YG

**Comment by VT-14** [comment]
Ender IO has its own custom recipe system (which controls many other configuration abilities) in the configs.  The developers weren't interested on adding 1st party support for an effectively duplicate feature.

There is a 3rd party add-on mod called EnderTweaker which should bridge the two systems.

**Comment by aaronhowser1** [comment]
Would changing the `/config/enderio/recipes/user/user_recipes.xml` file to read
```xml
<?xml version="1.0" encoding="UTF-8"?>
<enderio:recipes xmlns:enderio="http://enderio.com/recipes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enderio.com/recipes recipes.xsd ">
    <recipe name="Tweak: Stick from Wood" required="false" disabled="true">
        <crafting>
            <grid size="1x2">
                <item name="logWood"/>
                <item name="logWood"/>
            </grid>
            <output name="minecraft:stick, stickWood" amount="16" />
        </crafting>
    </recipe>

    <recipe name="Tweak: Chest from Wood" required="false" disabled="true">
        <crafting>
            <grid>
                <item name="logWood"/><item name="logWood"/><item name="logWood"/>
                <item name="logWood"/><item/><item name="logWood"/>
                <item name="logWood"/><item name="logWood"/><item name="logWood"/>
            </grid>
            <output name="minecraft:chest, chestWood" amount="4" />
        </crafting>
    </recipe>

    <recipe name="Tweak: Wood Hopper" required="false" disabled="false">
        <crafting>
            <grid>
                <item name="IRON"/><item name="logWood"/><item name="IRON"/>
                <item name="IRON"/><item name="logWood"/><item name="IRON"/>
                <item/><item name="IRON"/><item/>
            </grid>
            <output name="minecraft:hopper, blockHopper" />
        </crafting>
    </recipe>
</enderio:recipes>
```
disable the recipes?

**Comment by VT-14** [comment]
You left the Wood Hopper one enabled (2 logs rather than a chest).

Without testing it, that looks like it should work.  You've got some extra stuff in there (you don't need the recipe you are disabling), but it should be harmless.

**Comment by aaronhowser1** [comment]
So just
```xml
<?xml version="1.0" encoding="UTF-8"?>
<enderio:recipes xmlns:enderio="http://enderio.com/recipes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enderio.com/recipes recipes.xsd ">
    <recipe name="Tweak: Stick from Wood" required="false" disabled="true">
    </recipe>

    <recipe name="Tweak: Chest from Wood" required="false" disabled="true">
    </recipe>

    <recipe name="Tweak: Wood Hopper" required="false" disabled="true">
    </recipe>
</enderio:recipes>
```
would work?

**Comment by VT-14** [comment]
Yup!

The Examples folder has a few examples that disable recipes (especially the legacy_recipes.xml when disabling all of the Simple Machines).  It looks like `<recipe name="Simple Stirling Generator"><disabled/></recipe>` should also work, if you encounter issues.
