### ISSUE TITLE
[Question/Suggestion] Custom input/output rates for  the Dimensional Transceiver

### ISSUE THREAD

**Issue by xDefcon** [SleepyTrousers/EnderIO#5368]
#### Issue Description:

The current limit of energy transmission for a Dimensional Transceiver (that depends by the capacitor installed) is a maximum of 204000 energy per tick. I would like to increase or modify these limits.

#### What happens:
I can't find a way in the config to change those limits.

#### What you expected to happen:
Something in the config to edit the max energy transfer rate for each capacitor installed in the Dimensional Transceiver.

____
#### Affected Versions:

- EnderIO: 5.1.51
- EnderCore: 0.5.73
- Minecraft: 1.12.2

**Comment by tyler489** [comment]
they are values that can be changed  in the xml files

**Comment by VT-14** [comment]
I believe power usage of all machines is part of config/enderio/recipes/capacitor_machines.pdf.

Directions on how to edit them included in that file.

**Comment by xDefcon** [comment]
> I believe power usage of all machines is part of config/enderio/recipes/capacitor_machines.pdf.
> 
> Directions on how to edit them included in that file.

That is what i was searching for, thanks!
