### ISSUE TITLE
Redstone conduit not working through dim transceiver

### ISSUE THREAD

**Issue by Kennifoo** [SleepyTrousers/EnderIO#5369]
#### Issue Description:
Whenever you try to send a redstone signal through a dim transceiver, nothing happens.

#### What happens:
Redstone signal doesn't get sent.

#### What you expected to happen:
Redstone signal to appear on the other dim transceiver.

#### Steps to reproduce:

1.Allow redstone to go through transceiver
2. Profit
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft:
- Forge:
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by CitiesXL2815** [comment]
dim transceiver only transfer items power and fluids not redstone signals
