### ISSUE TITLE
EnderIO Multiple Attraction Obelisk Log Spam

### ISSUE THREAD

**Issue by thecodingchicken** [SleepyTrousers/EnderIO#5370]
#### Issue Description:
Placing multiple Attraction Obelisks in order to attract the same mob in larger quantities causes log spam.  

#### What happens:
The log gets filled up with messages such as "[21:13:02] [Server thread/WARN] [enderio]: Attractor Obelisk: Don't know how to attract minecraft:enderman".  Enderman were used in this case, and a further test with zombie pigmen did not result in such log spam.  

#### What you expected to happen:
No log spam would result from having multiple active attraction obelisks.  

#### Steps to reproduce:

1. Go to the end
2. Place down several(2+) attraction obelisks, give them a capacitors(octadic works well), and put an enderman soul vial inside each obelisk.
3. Supply the obelisks with power, and ensure that your game is not in peaceful.  
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no, although the same issue exists with Optifine
- Single Player and/or Server? both, first discovered on a server with a 31MB log file

#### Your most recent log file where the issue was present: 
Test Log: https://paste.ee/p/h1SEb
My original log: https://github.com/thecodingchicken/logs/blob/master/2020-04-20-1.log
[pastebin/gist/etc link here]

**Comment by CitiesXL2815** [comment]
![Annotation 2020-04-22 192314](https://user-images.githubusercontent.com/8730524/80052163-ddf26080-84ce-11ea-9429-0ebb7f4189fe.png)
![2020-04-22_19 21 16](https://user-images.githubusercontent.com/8730524/80052181-e5196e80-84ce-11ea-874e-e7a031256d10.png)
hmm

**Comment by CitiesXL2815** [comment]
actually i did little bit hard testing and it does spam the log

**Comment by ItzzGamma** [comment]
so whats the solution to this wtf..
