### ISSUE TITLE
Redstone conduits misbehave with multiple inputs. 

### ISSUE THREAD

**Issue by jgilmore** [SleepyTrousers/EnderIO#5371]
## What happens:
Restore colors with multiple inputs set to the same channel (red, for example) don't register changes on the corresponding outputs on signal change.

In fact, the outputs get stuck on, and only destroying both inputs was sufficient to fix the issue.

#### What you expected to happen:
I expected the output to be on if either input was on.

#### Steps to reproduce:

1. Place at least three red conduits.
2. Configure two as input, with the same channel
3. Configure the third as output, again with the same channel, and place Redstone so the state of the output may be easily observed.
4. Using a torch or block and lever, turn both inputs on.
5 turn both off and observe that the output is still on.
...
This was initially observed as interaction with botania's floating torches.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.35
- EnderCore:0.5.41
- Minecraft: 1.12.2
- Forge:14.23.5.2847
- SpongeForge? yno
- Optifine? yes
- Single Player and/or Server? Dedicated server

#### Your most recent log file where the issue was present: 

Er... I'll add this later... 
[pastebin/gist/etc link here]

**Comment by CitiesXL2815** [comment]
same issue https://github.com/SleepyTrousers/EnderIO/issues/5206
