### ISSUE TITLE
Weird particle effects whenever opening an EnderIO GUI

### ISSUE THREAD

**Issue by Unhook** [SleepyTrousers/EnderIO#5374]
#### What happens:
Whenever an EnderIO GUI is opened weird particles show up in the background. Initially occured in Celestial Journey, however tested it with basically just EnderIO installed and it's still happening. See this GIF: https://media.giphy.com/media/SAOdns9fgu2QZPczKr/giphy.gif

#### What you expected to happen:
Not get particle effects in the background when opening an EnderIO GUI

#### Steps to reproduce:

1. Install EnderIO and open a GUI.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.55.jar
- EnderCore: EnderCore-1.12.2-0.5.73.jar
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2854
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Tested on singeplayer.

#### Your most recent log file where the issue was present: 

https://pastebin.com/Ty0S6xkc

**Comment by Unhook** [comment]
Never mind, space day.

**Comment by tyler489** [comment]
Correct :wink:
