### ISSUE TITLE
[Possible Bug] Open Computers Conduit causes components to be disconnected

### ISSUE THREAD

**Issue by hypherionmc** [SleepyTrousers/EnderIO#5375]
#### Issue Description:

When using open computers with a component connected by the OC Conduit, and you move far enough for the computer chunk to be unloaded, and later revisit the computer, you will find that the computer is now turned off. There are no errors on the game log or on the OC Analyzer. This could be a possible ender io bug because when you use the exact same setup but replace the conduit with the OC Cable, the computer works fine

#### What happens:
See above description

#### What you expected to happen:
To not have the components connected with the conduit to disconnect from the computer when moving a certain distance away.

#### Steps to reproduce:

1. Create a new world
2. Setup a computer (Any tier) and connect the screen with the OC Conduit
3. Install OpenOS on the computer and leave it running
4. Leave the computer running and move a great distance away for 5 minutes or more
5. Return to the computer and you should find the computer either turned off or frozen with the screen still on
6. Replace the OC conduit with the OC Cable and repeat steps 4-5, except you should find the computer still working

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.55
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- OC Version: 1.12.2-1.7.2.67
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 
 
Cannot provide as no errors are being logged at all

**Comment by CSX8600** [comment]
I'm getting the same thing.  In addition, when I have an adapter hooked up to a Basic Capacitor Bank, the computer won't see it as a component unless I either break the adapter and re-place it, or break the Basic Capacitor Bank and re-place it.  Might be cause for another Issue, as well.  It makes it super hard to make an automated power plant with this issue :/

**Comment by hypherionmc** [comment]
@CSX8600 I found that my issue is caused by chunk loading. When chunkloading the entire OC network, it works fine. I won't call this an enderio bug, as chunk loading is best left to chunk loaders.

As for your issue, this might have been fixed in the latest versions. If not, feel free to open an new issue
