### ISSUE TITLE
Fake player name

### ISSUE THREAD

**Issue by caribhunt** [SleepyTrousers/EnderIO#5376]
Trying to make the Killer Joe machine on my server to bypass authme protection. So I need to add the fake player name to the whitelist. Searched through the code, but couldn't find it. Can someone help with the name?

**Comment by HenryLoenwind** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-machines/src/main/java/crazypants/enderio/machines/machine/killera/Attackera.java#L32-L33
