### ISSUE TITLE
Crash when trying to remove machine with wrench (+230 mods)

### ISSUE THREAD

**Issue by Devalut** [SleepyTrousers/EnderIO#5377]
#### Issue Description:

Attempting to remove a machine with the Yeta wrench results in crash, that is sneaking and right clicking the machine, not expecting much since this is a heavily modded world
____
- EnderIO: 5.1.55
- EnderCore: 1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Server

[crash-2020-05-05_17.37.10-client.txt](https://github.com/SleepyTrousers/EnderIO/files/4584406/crash-2020-05-05_17.37.10-client.txt)
[pastebin/gist/etc link here]

**Comment by CitiesXL2815** [comment]
Try without optifine i have no issue shift right clicking on machines

**Comment by tyler489** [comment]
PLease report this to OpenTerrainGenerator.

**Comment by Devalut** [comment]
@tyler489 
Removed it long ago

**Comment by Devalut** [comment]
@Tyler works, seems having the files in there regardless of .jar.disabled tag results in it fiddling with it
Thank you.

**Comment by tyler489** [comment]
technicly it was OTG core which auto installs from OTG base that was causing the issue I believe

**Comment by HenryLoenwind** [comment]
OTG comes in 2 parts. The mod itself and then the parts that are specific for Forge (or Bukkit). This crash happens when only the Forge-specific part is active, as it tries to access the (missing) mod without checking if it is there.
