### ISSUE TITLE
Dimensional Transceivers are buggy with fluids

### ISSUE THREAD

**Issue by FreezePhoenix** [SleepyTrousers/EnderIO#5384]
#### Steps to reproduce:

1. Place two dimensional transceivers 1 block apart from each other, insert any tier of capacitor into them, and place a creative capacitor bank between them.
2. Create a fluid channel. Set the transceiver on the left to send, and the one on the right to receive. 
3. Place a Thermal tank on top of each one, use a crescent hammer on the left tank so that it is set to auto output.
4. Put water in the first tank. Note it immediately goes to the second tank.
5. Use TheOneProbe to inspect the left transceiver (You must have the Probe upgrade on a Dark Steel or Ender helmet). Note how it appears to be linked to the tank on the right.
6. Exit and re-enter world, and use TheOneProbe on the transceiver again. It is now linked to two tanks!
7. Attempt to put a water bucket into the tank on the left. It pops into the tank on the right, as expected.
8. Try putting another bucket in the left tank, and it empties, but nothing happens. The water has gone into the "ghost" tank, and vanished forever. You can see this by using TheOneProbe on the left transceiver.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 0.5.74
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single.

**Comment by FreezePhoenix** [comment]
A temporary fix that has been discovered over time is to completely exit the MC instance, and re-launch it. It appears to be an issue with Ender IO's caching system of the network.

**Comment by FreezePhoenix** [comment]
@HenryLoenwind Is this fixed then?

**Comment by tyler489** [comment]
yes

and hopefully soon.
