### ISSUE TITLE
Can't start game with ender IO in mod folder

### ISSUE THREAD

**Issue by Sylvesterng** [SleepyTrousers/EnderIO#5385]
#### What happens:
crashes instantly

#### What you expected to happen:
start the game normally

#### Steps to reproduce:

1.Put ender io and ender core in mods folder
2.start the game
3.crashes instanly
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.7.10-2.3.0.429_beta
- EnderCore: EnderCore-1.7.10-0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: Forge10.13.4.1558-1.7.10
- SpongeForge? no
- Optifine? no
 Single Player

#### Your most recent log file where the issue was present: 

[https://pastebin.com/L5u2H2jd]

**Comment by tyler489** [comment]
the crop config is for 1.10+ delete the configs and let it regen.
