### ISSUE TITLE
Unable to compile with EnderIO as a dependency on 1.12.2, mavens outdated metadata?

### ISSUE THREAD

**Issue by LemADEC** [SleepyTrousers/EnderIO#5386]
#### Issue Description:
Project with dependency on EnderIO can no longer compile as gradle can't find any 1.12.2 version on both mavens.

#### What happens:
https://maven.tterrag.com/com/enderio/EnderIO/maven-metadata.xml only holds 1.7.10 to 1.11 versions while in practice, we can find 1.12.2 version here: https://maven.tterrag.com/com/enderio/EnderIO/1.12.2-5.0.36/

also, https://maven2.tterrag.com/com/enderio/EnderIO/1.12.2-5.0.36/ is timing out.

#### What you expected to happen:
Maven access to EnderIO 1.12.2 versions through gradle script

#### Steps to reproduce:
Do a fresh compilation of https://github.com/An-Sar/Cyberware

#### Your most recent log file where the issue was present: 
https://gist.github.com/LemADEC/5442e4c2b80d5d4257c7595f74507772

**Comment by hypherionmc** [comment]
The maven issues have been fixed. We now only make use of https://maven.tterrag.com. All the files from Maven 2 are now merged into one maven.

If after updating your build file you still have an issue, feel free to re-open this issue :)
