### ISSUE TITLE
1.12.2 world crash

### ISSUE THREAD

**Issue by Vincent98740** [SleepyTrousers/EnderIO#5388]
[crash-2020-05-29_17.43.54-server.txt](https://github.com/SleepyTrousers/EnderIO/files/4701264/crash-2020-05-29_17.43.54-server.txt)
[crash-2020-05-29_18.20.54-server.txt](https://github.com/SleepyTrousers/EnderIO/files/4701265/crash-2020-05-29_18.20.54-server.txt)

**Comment by HenryLoenwind** [comment]
Your wold is corrupted.
