### ISSUE TITLE
Dimensional Transceiver no teleport Gas  

### ISSUE THREAD

**Issue by AlexLoberti** [SleepyTrousers/EnderIO#5389]
#### Issue Description:

Mod add Gas conduit, but Dimensional Transceiver not teleport gas

#### What happens:

Mod add Gas conduit and Dimensional Transceiver got to beam gas

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.55
- EnderCore:1.12.2-0.5.73
- Minecraft: 1.12.2
- Forge:latest
- SpongeForge? /no
- Optifine? yes
- Single Player and/or Server? - single and server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by VT-14** [comment]
Gas Conduits are added by the 3rd party add-on "Gas Conduits," not Ender IO itself.

https://github.com/pupnewfster/GasConduits

Also, Mekanism has the Quantum Entagloporter which can transfer Gasses long distances already.  In general, Ender IO doesn't want to undercut another mod's existing wireless mechanics.  See also conduits but no Dimensional Transceiver support for Applied Energistics 2, Refined Storage, or OpenComputers in Ender IO itself.
