### ISSUE TITLE
farm station bug?

### ISSUE THREAD

**Issue by runescapejon** [SleepyTrousers/EnderIO#5391]
#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first. If you are using an unreleased version of Ender IO (a.k.a development/nightly version), please don't open an issue for features that have not been announced as "finished" or "working". Expect to be ignored if you ignore this template.

#### What happens:

 I had ran into an issue. It's basically you place down and power the farm station. Then you use another mod called "Thaumic Additions: reconstructed" and it has seeds but with all the same ID *(thaumadditions:vis_seeds)* but with different NBT
You then place an certain seed within the mod into the farming station gui. The farming station begin to plants all seeds regardless of the NBT data 

#### What you expected to happen:
A simple fix that farming station will listen out for any changes to the nbt not just ID/meta

#### Steps to reproduce:

1. Setup a basic farm station, I'd used for power the creative capactior. Also, used Octadic capacitor and any hoe
2.  Select one Vis Seeds, I'd used Ignis Vis Seeds
3. put the seed you'll selected into the farm station gui
4. You can check what actually farm and you'll see it's not the seed you'll selected but all seeds within the mod 

GIF: https://gyazo.com/614387ef6045b79610aa4dd6afa18f2f
here in the gif I had middle click the farmed seeds showing you that it's not the seed that i put 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.1.55
- EnderCore: 1.12.2-0.5.75
- Minecraft: 1.12.2
- Forge:  14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? both

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
That's a limitation of Forge's plant system.

====

References:

![image](https://user-images.githubusercontent.com/1485873/83508643-80d4cc00-a4ca-11ea-91fd-f3298a524403.png)

https://gitlab.com/DragonForge/ThaumicAdditions/-/blob/1.12.2/src/main/java/com/zeitheron/thaumicadditions/items/seed/ItemVisSeeds.java

**Comment by runescapejon** [comment]
Is there a way to blacklist the seeds from being put into the farm station?

**Comment by tyler489** [comment]
If they are registered as IPlantable the farming station will allow them into the gui.

**Comment by HenryLoenwind** [comment]
this ^ may or may not work

**Comment by runescapejon** [comment]
Yeah it didn't work I'd used this https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/1182/
`EnderIO-1.12.2-5.1.1182-nightly.jar`

**Comment by runescapejon** [comment]
I had just saw the issue 

`Farming Station: 'Thaumic Additions: reconstructed' integration for farming not loaded`

i think it's wrong here https://github.com/SleepyTrousers/EnderIO/blob/1d60e56d7106c37644890917aac4f12851a5daec/enderio-base/src/main/java/crazypants/enderio/base/integration/thaumicadditions/ThaumicadditionsUtil.java#L18

and the item id it's this https://gyazo.com/e69f24c522e8aa4940938b7bab27cbee

**Comment by tyler489** [comment]
I don't see the difference

**Comment by runescapejon** [comment]
He put `"item:thaumadditions:vis_seeds"` that the item id right, but in game it's

`"thaumadditions:vis_seeds"` without the `item:`

**Comment by HenryLoenwind** [comment]
Please try again with EnderCore 0.5.76.

(The isValid() check on the item container did not compensate for being called during registry events.)

**Comment by runescapejon** [comment]
Yes it work very good! Thank you
