### ISSUE TITLE
After Humans modpack crashes after placing Enhanced Energy Conduit

### ISSUE THREAD

**Issue by nxmxlxss** [SleepyTrousers/EnderIO#5393]
#### What happens:
I tried to place some enhanced energy conduit on my big reactor (for some reason it can't connect to the reactor power tap so i used 1 hardened energy conduit (thermal expansion)  to place it on the power tap and keep building with the enhanced energy conduit

#### What you expected to happen:
Probably meeting someone who had / has the same problem like me so maybe he / she could help me out with that.

#### Steps to reproduce:

1. changed the Enderio version (no success)
2. deleted the "cropConfig.json (no success)
3. re-installed the modpack (no success)
4. re-installed endercore (no success)
...

____
#### Affected Versions (Do *not* use "latest"): 

- EnderIO: EnderIO-1.7.10-2.2.8.381.jar
- EnderCore: EnderCore-1.7.10-0.2.0.36_beta-sources.jar
- Minecraft: 1.7.10
- Forge: I'm sorry but i couldnt find out which one i have installed right now.
- SpongeForge? yes/no  -  no
- Optifine? yes/no  -  yes
- Single Player and/or Server?  -  Single Player

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

[2020-06-06-7.log](https://github.com/SleepyTrousers/EnderIO/files/4740964/2020-06-06-7.log)

& here is the crash report (latest)

[crash-2020-06-06_22.39.43-client.txt](https://github.com/SleepyTrousers/EnderIO/files/4740968/crash-2020-06-06_22.39.43-client.txt)

**Comment by CitiesXL2815** [comment]
sorry we don't support 1.7 anymore we moved onto 1.12.2

**Comment by HenryLoenwind** [comment]
and you're not even on the latest version for 1.7.10.

BTW, I'm quite sure I found the reason for your crash:

**Comment by nxmxlxss** [comment]
Thanks alot! I removed optifine and now everything works fine. Yes i'll remember that in the next thread, sorry for that.

Have a nice day / evening and stay healthy. :)
