### ISSUE TITLE
Anchor visibility bug

### ISSUE THREAD

**Issue by Intezium** [SleepyTrousers/EnderIO#5395]
#### Issue Description:

After reload chunks, no visibility all anchors.

#### Steps to reproduce:

https://youtu.be/l7MGnxxpl6U

____
#### Affected Versions (Do *not* use "latest"):

 -EnderIO > 5.1.55
 -EnderCore > 0.5.73 and 0.5.76
 -Minecraft > 1.12.2
 -Forge > 14.23.5.2847 and 14.23.5.2854
 -SpongeForge? > Yes and not
 -Optifine? > Yes and not
 -Single Player and/or Server? > Single Player and Server

*Included WorldEdit-CUI-Forge-Edition-2-2.2.0-mf-1.12.2-14.23.5.2768

**Comment by skid9000** [comment]
Hello,

from what issue is this a duplicate ? I'm unable to find it.

Also i can reproduce on EnderIO 5.2.66 (with zoo and endergy) and EnderCore 0.5.76 on Forge 2854.
