### ISSUE TITLE
Farming Station not picking up all "seeds" when harvesting.

### ISSUE THREAD

**Issue by xenoflot** [SleepyTrousers/EnderIO#5396]
#### Issue Description:
Farming station is working as expected but it's not collecting all seeds when it harvests. This includes potatoes which are their own seeds.

Playing Material Energy^5 v 1.0.5. I have also reported it over there.

#### What happens:
I got five stacks of wheat seeds in my inventory when I got within magnet range!

#### What you expected to happen:
I expect it to collect all seeds.

#### Steps to reproduce:

1. Set up a farming station
2. Let it do its thing
3. Wait. Seeds will sometimes be left behind on a harvest.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.55
- EnderCore: EnderCore-1.12.2-0.5.74
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? SSP

#### Your most recent log file where the issue was present: 

Nothing of interest in latest.log. Just saving chunks and inventorytweaks.

debug.log also has nothing unexpected, except chunks being saved and this line spammed 4 times in between saves:
[20:47:43] [Server thread/DEBUG] [enderio]: Saving ServerChannelRegister with gen=0

**Comment by xenoflot** [comment]
Curious that this would be flagged "cannot reproduce" within 1 minute of me posting (I still had it open on screen). That's not a lot of time to try reproducing.

Anyway, closing as it turns out the problem was a dark spot in my field.

**Comment by Breadabix** [comment]
What do you mean by a Dark Spot, Im having this issue on 1.12 and cant figure it out, the farming station has the required range and is planting and breaking crops fine, just not collecting drops.

**Comment by xenoflot** [comment]
Initially I thought it was not picking up seeds after harvesting. However, it turned out there was a literal dark spot, a small area with no light, and when there's insufficient light, the seeds will pop out of the ground. This is vanilla behaviour and is pretty obvious when you're planting by hand but I didn't immediately realise because the machine was doing the planting. 

Good luck. I hope you find the source of your problem.

**Comment by Breadabix** [comment]
Ah ok, thanks for responding so quickly.
