### ISSUE TITLE
If you throw the Staff of Levity while it's on, you continue to float

### ISSUE THREAD

**Issue by aaronhowser1** [SleepyTrousers/EnderIO#5397]
#### Issue Description:
If you sneak click a Staff of Levity, it gives you Levitation until you use it again. But if you throw it, you don't lose the levitation effect.

#### What happens:
You keep floating upwards forever

#### What you expected to happen:
You stop floating

#### Steps to reproduce:

1. Use Staff of Levity
2. Throw it
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.55
- EnderCore: EnderCore-1.12.2-0.5.75
- Minecraft: 1.12
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/4776379/latest.log)

**Comment by tyler489** [comment]
technicly intended but being changed next release
