### ISSUE TITLE
Painted

### ISSUE THREAD

**Issue by Ace0fspadev** [SleepyTrousers/EnderIO#5398]
#### Issue Description:

FTB Revelation with SEUS Renewed Shader 

Painted Blocks are waving like leaves, Painted conduit Facades not.

#### What happens:

Painted Blocks waving

#### What you expected to happen:

Painted solid blocks should also be solid

#### Steps to reproduce:

1.Install EnderIO-1.12.2-5.1.51
2.Install OptiFine_1.12.2_HD_U_F5
3. Install SEUS-Renewed-v1.0.1
4. Paint blocks and put it somewhere outside
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.51
- EnderCore: EnderCore-1.12.2-0.5.68
- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- SpongeForge? no
- Optifine? yes
- Single Player and Server?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
![bug1 1](https://user-images.githubusercontent.com/56428540/84693522-e94e8f00-af47-11ea-9932-085257c9baf0.png)
![bug1 2](https://user-images.githubusercontent.com/56428540/84693527-ea7fbc00-af47-11ea-8242-662ce79ba9e1.png)
![bug1 3](https://user-images.githubusercontent.com/56428540/84693533-ec497f80-af47-11ea-97ec-a1c87671df64.png)
![bug1](https://user-images.githubusercontent.com/56428540/84693537-ece21600-af47-11ea-92ca-c33cb4f67030.png)

**Comment by HenryLoenwind** [comment]
The shader decides which blocks to "wave". Nothing to do with us.

**Comment by Ace0fspadev** [comment]
really good explained...    i thought there must be a flag or sth in the blog config
