### ISSUE TITLE
 Conduit Facades let light through

### ISSUE THREAD

**Issue by Ace0fspadev** [SleepyTrousers/EnderIO#5399]
#### Issue Description:

FTB Revelation

Conduit Facades let light through

#### What you expected to happen:

no light through solid conduit facades

#### Steps to reproduce:

1.Install EnderIO-1.12.2-5.1.51
2.Install use conduit facades
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.1.51
- EnderCore: EnderCore-1.12.2-0.5.68
- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- SpongeForge? no
- Optifine? yes
- Single Player and Server
![conduit_facade](https://user-images.githubusercontent.com/56428540/84695723-924ab900-af4b-11ea-868b-da817c0be8fa.png)

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by CitiesXL2815** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/4577 same issue

**Comment by CitiesXL2815** [comment]
also try without optifine
bc i have no issues with the facades letting light through

**Comment by hypherionmc** [comment]
Tested this and cannot reproduce this issue.

Test Versions used:
EnderCore: **1.12.2-0.5.75**
EnderIO: **5.1.55**

Tested this with all the facade types.

![image](https://user-images.githubusercontent.com/63595580/84699009-0fc4f800-af51-11ea-8bfc-7af41adac5a7.png)

![image](https://user-images.githubusercontent.com/63595580/84699040-1f444100-af51-11ea-9048-54196e51c7b0.png)

![image](https://user-images.githubusercontent.com/63595580/84699021-17849c80-af51-11ea-9911-e7020be7585d.png)
