### ISSUE TITLE
[Question] Plans for 1.14/1.15

### ISSUE THREAD

**Issue by bootzin** [SleepyTrousers/EnderIO#5400]
Any plans on moving this to newer versions? Forge already has a 1.15 RB, although I'm not sure their API is enough for this mod, but I believe there is nothing preventing a 1.14 version

I really like this mod, so I'd really want to see it moving forward (:

**Comment by CitiesXL2815** [comment]
there only one person working on EIO and he doesn't want to port EIO by himself to 1.15.x and future versions likely 1.14.x is being skipped and no backporting either the other devs have there mods first
