### ISSUE TITLE
Controls GUI error

### ISSUE THREAD

**Issue by MeatSh1eld** [SleepyTrousers/EnderIO#5405]
#### Issue Description:

Controls GUI error

#### What happens:

when you goto settings and goto controls it get completely messed like everything starts in the middle but i do not know if this is a config conflict but im really shur its not. but this is my favorite mod ever so if you need anything else at all let me know i will send anything that is needed

#### What you expected to happen:
the GUI to be fine

#### Steps to reproduce:

1.download ender.io
2.put ender.io in mods folder
3.start minecraft
4.goto settings
5.goto controls

#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.2.59
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2 
- Forge: forge-14.23.5.2847
- SpongeForge? no
- Optifine? both with it on, off and with no other mods installed
- Single Player

#### Your most recent log file where the issue was present: 

i could not find the error that did this so heres a screen shot

![image](https://user-images.githubusercontent.com/61996812/86998864-458b8400-c17f-11ea-8425-b3555f52838a.png)

**Comment by CitiesXL2815** [comment]
paste the latest log with using pastebin or gitgist link it here

**Comment by MeatSh1eld** [comment]
https://hastebin.com/pipugevavi.md

**Comment by CitiesXL2815** [comment]
nvm https://gist.github.com/CitiesXL2815/4686dbc3fbf82e96644ce7681d4ced55 got copy of it from a build

**Comment by MeatSh1eld** [comment]
oh ok

**Comment by CitiesXL2815** [comment]
lol oh well guest @HenryLoenwind look at both

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/87036088-91274780-c1ea-11ea-8330-f15f48762998.png)

It's as wide as it need to be to contain all text. Not really our problem that Mojang's code doesn't take the available space into account when determining how wide to make that column. Also nothing we can change.

**Comment by MeatSh1eld** [comment]
Is their anyway i can fix it because my screen is not big enough

**Comment by hypherionmc** [comment]
@MeatSh1eld would you mind giving our latest dev build a test to see if you still have this issue?

You can find it here: https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/1221/

**Comment by MeatSh1eld** [comment]
Ok

**Comment by hypherionmc** [comment]
Considering this fixed for now. If you still have an issue, please re-open this ticket
