### ISSUE TITLE
Conduit Facade rendering issues with Chisel and GregtechCE

### ISSUE THREAD

**Issue by Kortako** [SleepyTrousers/EnderIO#5406]
#### Issue Description:

EnderIO Conduit Facades painted with Chisel blocks are invisible and do not render correctly, and it seems like the error lies with some conflict with facades from Gregtech Community Edition (see stack trace). Removing GTCE from my testing environment seems to alleviate the problem.

This issue was originally brought up in the [GTCE issue tracker](https://github.com/GregTechCE/GregTech/issues/1134), and they have confirmed it as well, but they directed me here instead.

#### What happens:

Conduit facades painted with Chisel blocks render invisibly when GTCE is also installed.  See the GTCE issue for screenshots and more information.

#### What you expected to happen:

Conduit facades work as expected.

#### Steps to reproduce:

1.  Install GTCE alongside Chisel and EnderIO (with all related dependencies)
2.  Use the painting machine to paint a conduit facade with a Chisel block
3.  Place the conduit facade down, it will turn invisible, especially if it is near a GTCE machine block.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.2.59
- EnderCore: 1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2847 
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Both

- GTCE: 1.9.2.515
- Chisel: 1.0.2.45
- CTM: 1.0.2.31

#### Your most recent log file where the issue was present: 

https://hastebin.com/egamucitec.cs

**Comment by HenryLoenwind** [comment]
see original ticket.
