### ISSUE TITLE
Resetting/Emptying Fluid tank deletes all objects still inside.

### ISSUE THREAD

**Issue by Ncrpts** [SleepyTrousers/EnderIO#5407]
#### Issue Description:

When placing a fluid tank wich contain an item inside a crafting area to reset it, all items contained inside it are deleted.

#### What happens:

After placing the fluid tank, all items that were inside are gone.

#### What you expected to happen:

Either the object still present stay inside, or are ejected when breaking the fluid tank.

#### Steps to reproduce:

1. Place fluid tank, insert water bucket inside tank, leave bucket inside.
2. Break fluid tank block. 
3. Place fluid tank item in crafting area, pickup the "reset" one.
4. Place fluid tank in the world again.
5. Bucket has disappeared.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.59
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

n/a

**Comment by CitiesXL2815** [comment]
dude this not issue reset block craft grid delete everything in that block include items that are in the tank

**Comment by Ncrpts** [comment]
Yeah I was not sure if this was per design or not, it's always annoying to lose sponges like this. also maybe adding a way to "empty" a fluid tank directly from it's GUI could be useful and prevent tragic accidents like that.
