### ISSUE TITLE
Crafter suggestion

### ISSUE THREAD

**Issue by Nazgulup** [SleepyTrousers/EnderIO#5408]
#### Issue Description:

The crafter can't keep or doesn't have option to keep the supporting item in it.

#### What happens:

We have a private server that have some mods on it. We trying to use the crafters to make some kind of food. The recipes are include some kind of supporting items, which will not be consumed while in crafting. The crafter will put them into the output box and the craft will be stopped and will take more time to move that item back to the crafter.

#### What you expected to happen:

The material area should not be push out and can keep the supporting item in the material area.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.59
- EnderCore: 1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 1.12.2-forge-14.23.5.2854
- SpongeForge? no
- Optifine? no
- Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
This is how it was in 1.7.10, but it had to be changed when Mojang changed the crafting system. Now there's no way of distinguishing between a recipe leaving behind an empty bucket or an unchanged item. And just leaving it in the crafting area is no solution either, as the crafting system doesn't indicate which item fails the recipe.

Just enable "self feed" on the extracting item conduit.
