### ISSUE TITLE
Conduits disconnecting from Quantum Entangloporter

### ISSUE THREAD

**Issue by Basedgod199** [SleepyTrousers/EnderIO#5410]
#### Issue Description:

Any energy conduits (including ones from the endergy addon) will disconnect from the Quantum Entangloporter after leaving and re-joining the world.

#### What happens:

Conduits disconnect and the Quantum Entangloporter stops receiving power

#### What you expected to happen:

Conduits staying connected to the Quantum Entangloporter

#### Steps to reproduce:

1.Attach energy conduits to Quantum Entangloporter, and configure Quantum Entangloporter (and the other one that receives power)
2.Leave the world.
3.Re-join the world. Conduits are now disconnected.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.12.2-5.2.59
- EnderCore:1.12.2-0.5.7.6
- Minecraft:1.12.2
- Forge:14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Singleplayer (unfortunately I don't have a server to test it on)

#### Your most recent log file where the issue was present: N/A (I can still post a log if you wish but I've looked through it for errors and I didn't find any)

[pastebin/gist/etc link here]
https://pastebin.com/VEvYzvqQ (latest.log)

![image](https://user-images.githubusercontent.com/32063145/88581435-03c55f00-d002-11ea-952a-fff91b8d0c89.png)

**Comment by HenryLoenwind** [comment]
That's a bug in the Quantum Whatsitsname. It needs to seed a block update when in changes from "cannot connect energy" to "can connect energy". You do *not* want energy conduits to ask all their neighbours 20 times a second if they changed their mind about being able to be connected to...
