### ISSUE TITLE
advanced redstone logic for impulse hopper

### ISSUE THREAD

**Issue by DoomSquirter** [SleepyTrousers/EnderIO#5411]
#### Issue Description:

When impulse hopper was in EIO additions, it had the high wave/low wave redstone signalling which made it quite useful.  w/o those, setups I had used this in no longer work w/o alot of extra work if at all.

as stated in #4478
https://github.com/SleepyTrousers/EnderIO/pull/4478
quoted:
Advanced redstone modes currently are not implemented, as they need to be ported and most likely implemented for all machines that use redstone modes.

any eta when these other redstone modes might be added, if at all?

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.12.2-5.2.59
- EnderCore:EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player

**Comment by CitiesXL2815** [comment]
there no ETA and we don't give ETA anyways lol and idk when it'll be implemented hopefully soon for all

**Comment by DoomSquirter** [comment]
I should have worded that better.  Not really looking for an eta, is it on the roadmap at all?  I only ask since that merge I mentioned was from march 2018.  so, like over 2 years ago.

**Comment by HenryLoenwind** [comment]
The roadmap is that it’s in my stack of things that should be done. However, not very high because for those modes to be useful for other machines, all machines need to be adapted to have a concept of a “task”. Just switching e.g. a sagmill on for one tick on a redstone state change won’t do anything, its work is not instantaneous like the hopper’s.

**Comment by DoomSquirter** [comment]
yeah, I totally see that.  in fact, the impulse hopper is the only thing I think benefits from it really.

without those extra redstone modes tho, the impulse hopper truly suffers for it....
