### ISSUE TITLE
Applied energistics and Ender IO conflicting?

### ISSUE THREAD

**Issue by aszsdfhbv** [SleepyTrousers/EnderIO#5412]
#### Issue Description:

I create a world and as soon as it loads it crashes

#### What happens:

I create a world and as soon as it loads it crashes

#### What you expected to happen:

Load in the world

#### Steps to reproduce:

1. Open Minecraft with the mods
2. Press single player
3. And play a world
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.429
- EnderCore: 0.2.0.39
- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

https://pastebin.com/TaG7zZWd

**Comment by VT-14** [comment]
A) The stacktrace heavily indicates that OreSpawn is the cause of the crash.  It seems to be causing problems when the game tries to load the block located at 230, 64, 229.

B) Ender IO stopped supporting 1.7.10 several years ago.  On a related note, the debug info at the bottom that probably lead you here has had its wording changed in later version to make it clear it's almost never the problem.
