### ISSUE TITLE
1.16.1 pls?

### ISSUE THREAD

**Issue by MrScautHD** [SleepyTrousers/EnderIO#5413]
pls make a 1.16.1 forge version!

**Comment by CitiesXL2815** [comment]
https://cdn.discordapp.com/attachments/348482348666454019/731227942922879036/Annotation_2020-07-10_121749.png

**Comment by VT-14** [comment]
First off, pestering mod developers to update is generally considered very rude.  People make mods as a hobby, and *constantly* (sometimes multiple times a day) being asked to put in loads of work to port a mod every time vanilla updates gets very frustrating.

Second, this Issues tracker is for issues.  Ender IO uses another forum to manage suggestions (http://ideas.theideawall.com/EnderIO/) where people can vote, and has a Discord for more informal questions (with your question addressed with a pinned message that Cities linked).

****

Now, to answer your request/question.  No.

Ender IO will eventually be ported (the mod is Public Domain and popular), and the current developer(s) does want to port it, but porting past the 1.13+ hurdle requires weeks of full-time work for one person, and again, this is a hobby.  Meanwhile, 1.16.2 is estimated to be out in a few weeks, and mods generally port to the most up-to-date version.  Ender IO *might* get a 1.16.x release, but 1.16.1 is extremely unlikely.
