### ISSUE TITLE
Tank disallows insertion of concrete powder

### ISSUE THREAD

**Issue by snydej** [SleepyTrousers/EnderIO#5414]
#### Issue Description:
Even though tanks are supposed to be able to accept concrete powder they won't unless they already contain water.

I'm trying to automate production of concrete and I have a Refined Storage recipe that has a concrete powder and a bucket's worth of water as inputs. The crafting fails because the Tank rejects the concrete powder.

#### What happens:
An empty tank won't allow you to insert concrete powder.

#### What you expected to happen:
The concrete powder should go in the appropriate slot and just sit there until water is put into the tank, similar to how it just sits there if the tank runs out of water.

#### Steps to reproduce:

1. Place a Tank in the world
2. Try to put concrete powder in it.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.59
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 
N/A

**Comment by CitiesXL2815** [comment]
it requires water first before transforming into concrete

**Comment by snydej** [comment]
Did you even read this before closing it? How can you say it could be RS's fault when I can't even manually put in the concrete powder? RS couldn't insert it because the tank itself rejected the item.

**Comment by snydej** [comment]
Also I don't know what you mean by "AE2 seems pull item out of the tank even crafting them". That looks like a word salad to me.

**Comment by CitiesXL2815** [comment]
https://youtu.be/3bzRxutebZU actually did some testing about it lol

**Comment by snydej** [comment]
So as I understand it, RS checks that every ingredient in a recipe is able to be put into an inventory before it actually puts anything in so that it can avoid putting in a partial recipe (doing so might cause problems with automation, I think. I know the alloy smelter at least can start making something different from what was intended if it doesn't get everything all at once). RS has no way of knowing that there's a special dance it has to do to get both the water and the concrete powder into the tank. I could prefill the tank with water but I wanted to use that tank to make lava buckets too.

I ran into a similar issue where a Slice'n'Splice didn't want to accept ingredients for a z-logic controller. I was able to work around it by having RS dump everything into a chest and having the Slice'n'Splice pull from the chest. I can't do that here because I'd need buffer inventory that can hold both the powder and the water.

To me it just seems that having the tank reject concrete powder when it's empty only creates problems.

**Comment by tyler489** [comment]
As far as i know tanks have 3 different fluid -> item "uses" water for concrete... lava for item voiding.... and experience for mending..  does this happen for mending tools as well? will they not go into the tank if there is no exp?

**Comment by HenryLoenwind** [comment]
Works as designed. The fluid determines which recipes it can execute. The tank is primarily a tank, the recipes are just an addon, that's why we don't lock the tank functionality to match the items.

**Comment by snydej** [comment]
I'm not asking for you to "lock the tank functionality". If someone puts concrete powder in the tank and then fills the tank with lava who cares? You can already do that: 1. Put a single bucket of water in 2. Put a stack of powder in (which empties the tank) 3. Pump lava in.

This idiosyncratic locking system doesn't help players in any way when it comes to the tank. It just creates incompatibilities with with mods that don't special case how they interact with Ender IO machines.
