### ISSUE TITLE
Modules aren't modular

### ISSUE THREAD

**Issue by Eonasdan** [SleepyTrousers/EnderIO#5417]
#### Issue Description:
What's the point of the modules if you still have to have all of them anyway?

#### What happens:
Use Ender Io Conduits so I can use conduits and energy banks. I can't craft fluid conduits without Quite Clear Glass, which requires the alloy furnace. Can't craft most of the energy items without the allow furnace. The conduit facades are practically worthless without the pairing machine.

I realize both of those are machines, but you can't **use** the module without them.

#### What you expected to happen:
I don't really care about the other machines so I didn't install that. I expected to be able to play with the module I included.

#### Steps to reproduce:

1. Install conduit module
2. Close minecraft
3. Uninstall module
4. Install monolith
5. hide stuff with jei

**Comment by VT-14** [comment]
The modules are provided so people (especially modpack makers) can include only the parts of the mod they want.  They are designed to be used with Custom Recipes, which Ender IO natively supports in its configs using xml files.
