### ISSUE TITLE
Items in Vacuum Chest Will Return Once Removed

### ISSUE THREAD

**Issue by GlennHS** [SleepyTrousers/EnderIO#5418]
#### Issue Description:
Items removed from **Vacuum Chest** will return themselves to the vacuum chest they were taken from upon viewing any inventory other than the player's regular inventory (as accessed by pressing 'E'). Items removed from the vacuum chest will be treated as though not in the player's inventory, disappearing upon being used/placed

#### What happens:
When a player places a vacuum chest and allows it to collect items these items will be irrecoverable from the vacuum chest in question unless piped out via conduits. Any attempt to remove them manually will make them "enter" the player's inventory but disappear as soon as they are interacted with, whether this be by clicking, placing or using them

#### What you expected to happen:
I would expect to be able to retrieve items manually without needing conduits or other item movement apparatus

#### Steps to reproduce:

1. Place down an EnderIO Vacuum Chest
2. Drop items near it and let it suck them up
3. Attempt to retrieve the items from said chest

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: **EnderIO-1.12.2-5.1.51**
- EnderCore: **EnderCore-1.12.2-0.5.68**
- Minecraft: **1.12.2**
- Forge: **forge-14.23.5.2846**
- SpongeForge? **no**
- Optifine? **no**
- Single Player and/or Server? **Server, have not tested single-player**

#### Your most recent log file where the issue was present: 

https://pastebin.com/akmaqcQn

Link to video displaying issue: https://imgur.com/XvHHvx4

P.S: This bug was found on _FTB Revelation ver3.21_

**Comment by hypherionmc** [comment]
Would you mind giving this a test in single player mode? This sounds like a desync issue between the client and the server. 

Also, the enderIO version used is a bit out of date. If possible, it would be worth considering an update

**Comment by HenryLoenwind** [comment]
Something is preventing you from taking those items. However, that "something" is only doing so on the server, that's why you don't see it. Your client thinks it can remove those items just fine. And we are using vanilla tech to sync between server and client (as does your normal "E" inventory), which won't pick up on "weird" server-side inventory changes. Other mods send the complete data to the client, no matter what. That's why opening a modded GUI will cure the desync.

**Comment by GlennHS** [comment]
@hypherionmc Have tested this in a creative superflat (Redstone Ready preset) world and found I could not reproduce the issue so I reckon you're right about it being a desync issue. if that's the case I doubt there's much you can do there.

Since I'm playing in a modpack best I can do is message the creator and see if they can update their version of EnderIO I guess. Don't know much about all that though. As it is, I'm perfectly happy with just piping stuff out into containers

@HenryLoenwind Thanks for the explanation, that's really interesting! I've always found modded minecraft and the actual "meat" behind it fascinating so thanks 😄

Thank you both for such fast, helpful replies, you guys are exactly the kind of devs I aspire to be

**Comment by hypherionmc** [comment]
I am closing this for now. If you still experience this problem, feel free to re-open :)
