### ISSUE TITLE
Config reset

### ISSUE THREAD

**Issue by BigPouley** [SleepyTrousers/EnderIO#5420]
#### Issue Description:

When I try to edit the config and restart the server, it just resets it with default settings. To be exact I'm trying to enable some spawners that are disabled by default.

#### Affected Versions:

- EnderIO: EnderIO-1.12.2-5.0.50
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Server: Mohist-dde44c8 1.12.2

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/5080785/latest.log)

**Comment by VT-14** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/fd60c87e6e374d3defa5df08819abdefcc1fab66/enderio-machines/src/main/resources/assets/enderio/config/recipes/spawner.xml#L4-L24

**Comment by VT-14** [comment]
When you make your changes, please note that the 'recipe' you want to change starts with with `<recipe ...>` and ends with `</recipe>`.  If you are changing vanilla mobs you will need to copy lines 33-88 to a user file.

In the examples folder there should be [cheaty_spawners.xml](https://github.com/SleepyTrousers/EnderIO/blob/fd60c87e6e374d3defa5df08819abdefcc1fab66/enderio-machines/src/main/resources/assets/enderio/config/recipes/examples/cheaty_spawner.xml) which does most of what you want.  You may want to tweak some of the numbers, especially with power.  It's an example file.

In later versions (yours is 9 versions behind the latest) the default recipe files were replaced with PDFs to make it clear you aren't supposed to change them.

**Comment by BigPouley** [comment]
Thanks
