### ISSUE TITLE
[BUG] Ender Inventory Panel Remote doesn't work "anywhere"

### ISSUE THREAD

**Issue by hypherionmc** [SleepyTrousers/EnderIO#5423]
#### Issue Description:
The Ender Inventory panel Remote is supposed to work across any dimension/place in the world when the entire network is chunk loaded, but it only works from within the same dimension/world.

#### What you expected to happen:
To be able to access the INV panel from the nether or anywhere else when the panel and network is chunkloaded

#### Steps to reproduce:

1. Setup an Inventory Panel network
2. Link an Ender Inventory panel remote to said panel
3. Setup chunk loading for the entire network
4. Try to access the panel from hundreds of block away (it should work)
5. Now try accessing it from the nether for example. It does not
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.2.1224 (Dev build)
- EnderCore: 1.12.2-0.5.76 (Dev build)
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? yes and no
- Single Player and/or Server? Both

#### Your most recent log file where the issue was present: 
N/A as no errors are logged

**Comment by tyler489** [comment]
Blame Hypherion for his bad code 😜

**Comment by hypherionmc** [comment]
Blame me for bad testing, but blame epic or crazy for the code (or whoever ported it to 1.12.2 lol)
