### ISSUE TITLE
No Owl Eggs

### ISSUE THREAD

**Issue by CitiesXL2815** [SleepyTrousers/EnderIO#5425]
#### Issue Description:
Owls are having hard time laying Owl Eggs there literally not plopping out reported this 10,000 times on discord but no fixes and no anwsers

#### What happens:
well nothing happen no eggs come out of owls lol

#### What you expected to happen:
Owl egg should be laying

#### Steps to reproduce:

1. Owls should plop out eggs
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: latest builds on Nightly
- EnderCore: latest
- Minecraft: 1.12.2
- Forge: 2854
- SpongeForge? nope
- Optifine? nope
- Single Player and/or Server? both

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
For anyone who'll find that in the future: Owls need to be sitting on leaves to lay eggs. They won't just drop them everywhere like stupid chickens ;)
