### ISSUE TITLE
Inconsistent crash when launching game

### ISSUE THREAD

**Issue by SirOMGitsYOU** [SleepyTrousers/EnderIO#5426]
#### Issue Description:

When launching the game there is a chance Ender IO will just crash the game on the early loading process.

#### What happens:

Game Crashes

#### What you expected to happen:

Not to crash?

#### Steps to reproduce:

1. Launch this specific assortment of mods
2. Pray it crashes(?)
3. crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.59.jar
- EnderCore: 0.5.76
- Minecraft: 1.12.2 
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? n/a

#### Your most recent log file where the issue was present: 

https://pastebin.com/raw/u6zT9TAe

**Comment by HenryLoenwind** [comment]
https://github.com/SleepyTrousers/EnderCore/issues/107
