### ISSUE TITLE
Instant crash when starting client

### ISSUE THREAD

**Issue by wanou067** [SleepyTrousers/EnderIO#5427]
#### What happens:
The game crash when forge contruct mods

#### What you expected to happen:

I want to start the game

#### Steps to reproduce:

1. Download EnderIO And Endercore
2. Add to the custom launcher
3. Start
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.59
- EnderCore: 0.5.76
- Minecraft: 1.12.2 
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Single Player (Client)

#### Your most recent log file where the issue was present: 

https://pastebin.com/5VNfSyNW

**Comment by HenryLoenwind** [comment]
You have a mod installed that contains a partial Applied Energistics API.

**Comment by wanou067** [comment]
Wich mod ? I don't install this kind of mods
![mods](https://user-images.githubusercontent.com/40696590/94371983-ada49300-00fa-11eb-8df2-d63d178011ca.png)
![image](https://user-images.githubusercontent.com/40696590/94371996-bbf2af00-00fa-11eb-830e-eed69bcbc84c.png)
![image](https://user-images.githubusercontent.com/40696590/94371999-c4e38080-00fa-11eb-8d5c-ee04c9754d65.png)
