### ISSUE TITLE
Sagmills causing large tps hit on server

### ISSUE THREAD

**Issue by Enterprise12nx01** [SleepyTrousers/EnderIO#5429]
#### What happens:
Using Lagoggles to discover what is lowering our server tps on a host and a sagmill setup is hitting our tps by 4-6
I have screenshots of the setup
Our host is using the latest i7/i9 processors and we are on one at 4.8Ghz with nvme ssds and 12gb ram
when we disabled these our tps went up by 3-4

The sagmills are processing ores with vibrant alloy grinding balls and octadic capacitors

#### What you expected to happen:
Good tps and performance

#### Steps to reproduce:

Just using sagmills, at least in this setup

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.59
- EnderCore: 1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? yes
- Optifine? no
- Single Player and/or Server?: Server

#### Your most recent log file where the issue was present: 
I do not have a log file that records these issues, but here are the screenshots with lag goggles, if theres some info i can provide please lmk

![2020-09-01_02 50 43](https://user-images.githubusercontent.com/69404529/91812872-c7d47980-ebff-11ea-8528-a6d91ce0b07d.png)

**Comment by Enterprise12nx01** [comment]
This can be closed! i did some very deep digging and found out Cryo fluxducts from Thermal Dynamics is the culprit, every time something puts power in to its network, it iterates every single output node meaning it does that several times per tick.

This was causing any profiler to label the machines as the issue, when its in fact the fluxducts ticking so much.
I reported this to the dev, although they already know saying "its coded the best way it already can be"

**Comment by tyler489** [comment]
I was pretty sure that was going to happen. Profilers such as laggogogles often misreport that as the machines fault for accepting energy when really its the ducts pushing it. Same with items.

**Comment by HenryLoenwind** [comment]
And here's a nice label for the statistics.

And people wonder why I dislike both laggoggles and cryo fluxducts...I *do* have my reasons...
