### ISSUE TITLE
fluid glowstone's texture gone

### ISSUE THREAD

**Issue by Nanamiya738** [SleepyTrousers/EnderIO#5432]
[Sugestion]
Seems that Thermal Foundation have the same fluid, then all the bucket and gui just become the missing block's texture.
and the files are normal, no texture file is missing.

So maybe you can make a Related Fix？

#### What you expected to happen:

Please tell me what to do is the best , It looks so strange,

#### Affected Versions

- EnderIO: 5.2.59
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge  no
- Optifine  no
- Single Player 

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Please retest with the latest release.
