### ISSUE TITLE
Ender IO Zoo Requires Ender IO and Ender Core

### ISSUE THREAD

**Issue by KenyMylankca** [SleepyTrousers/EnderIO#5436]
![1](https://user-images.githubusercontent.com/41585837/93495989-63abf800-f917-11ea-8793-7b00d7a270aa.PNG)
![2](https://user-images.githubusercontent.com/41585837/93496006-660e5200-f917-11ea-974d-eca1c9423ce4.PNG)
???

**Comment by HenryLoenwind** [comment]
If we set them to "required", the cf client will install both. That won't work either and you _cannot_ make it only install one. However, you _can_ manually select which one you want...

**Comment by hypherionmc** [comment]
You do infact need both of those. The curse page needs to be updated.

**Comment by KenyMylankca** [comment]
how about ender core?
