### ISSUE TITLE
[1.12.2] Crash after teleporting to overworld

### ISSUE THREAD

**Issue by Basedgod199** [SleepyTrousers/EnderIO#5437]
#### Issue Description:

I was in my void world (which is added by SimpleVoidWorld) and i went to go back to the overworld and then i crashed

#### What happens:

I crash

#### What you expected to happen:

To end up in the overworld without crashing

#### Steps to reproduce:

1.go to the void world.
2.go back to overworld.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.2.60
- EnderCore: 1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player yes, smp not tested

#### Your most recent log file where the issue was present: 

crash log:
https://pastebin.com/csNYcndz

**Comment by HenryLoenwind** [comment]
Looks like Lagggoggles is ticking TileEntities for a dimension that is not loaded. Not an issue with our code.
