### ISSUE TITLE
Fake Player Kills causes mobs to drop 50 skulls

### ISSUE THREAD

**Issue by lectavison** [SleepyTrousers/EnderIO#5440]
#### Issue Description:

in latest release of ender io for 1.12.2, Fake Player Kills causes mobs to drop 50 skulls

#### What happens:

when you use any type of Fake player, AKA Killer Joe/MobGrinder, to kill mobs  it causes the mob to drop 50 skulls

#### What you expected to happen:

I expect it to only drop 1 skull out of every 5 to 10 kills

#### Steps to reproduce:

1. grab a killer joe
2. provide it with Nutrient Distillation and a sword
3. put a mob in its range 
4. collect skulls

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.60
- EnderCore: 1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? both

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by lectavison** [comment]
I tested this in a singleplayer world and a multiplayer world where the only thing that was installed was Ender IO, Ender Core, and JEI

**Comment by VT-14** [comment]
Already fixed for the next update.

https://github.com/SleepyTrousers/EnderIO/commit/3d3ee8d84dff7d9bd97d3bc6aa5c77060fe1a117

Keeping this issue open for now as it's still active in the release version.

**Comment by evernife** [comment]
IS there a place for me to download the dev build?

**Comment by lectavison** [comment]
> IS there a place for me to download the dev build?

as this mod is open source you are free to download the source your self and build the jar file.

**Comment by evernife** [comment]
Sure, I was just asking though.

As this is one of the biggest minecraft mods project, i thought that there would be some dev builds available.

I was not trying to offend or demand :D

**Comment by lectavison** [comment]
sorry did not mean to sound like I was taking offence to your question. they may have a tester role in there discord, but don't know for sure as i have yet to join there discord server.

**Comment by VT-14** [comment]
Links to all of the dev builds are publicly posted on the Discord (in the Builds channel).  They are on tterrag's Jenkins.

At time of writing, this is the most recent one: https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/1235/

Insert the standard 'dev builds may be unstable' here.
