### ISSUE TITLE
[Suggestion] Alloy Iron Alloy to Be Turned On/Off in Configs

### ISSUE THREAD

**Issue by DizzyDJW** [SleepyTrousers/EnderIO#5441]
Currently using 1.12.2.

This is just a simple suggestion. Please add in the ability to enable/disable iron alloy in configs, I can understand that some modpacks may use it, but in every one I've played thus far I've never had to.

**Comment by CitiesXL2815** [comment]
there already one turn off iron alloy but one of the XML files in the recipe folder
