### ISSUE TITLE
[1.12.2] Crash on Startup

### ISSUE THREAD

**Issue by Manuepolis23** [SleepyTrousers/EnderIO#5443]
#### Issue Description:
After updating to latest version of ender io ( on 30.09.2020) i get a crash on launch

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.2.61
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player 

#### Your most recent log file where the issue was present: 

https://paste.ee/p/gLMTc

**Comment by HenryLoenwind** [comment]
This is caused by TickCentral modifying our code.

**Comment by TheXTrunner** [comment]
is it the same as this one? https://paste.ee/p/xGe99

**Comment by TheXTrunner** [comment]
https://github.com/TerminatorNL/LagGoggles/issues/125#issuecomment-701743083

so who's responsible then?

**Comment by HenryLoenwind** [comment]
No, completely unrelated.
