### ISSUE TITLE
Crash on startup with Ender IO 5.2.61

### ISSUE THREAD

**Issue by lllMohandarlll** [SleepyTrousers/EnderIO#5445]
#### Issue Description:

I've downloaded the latest Ender IO release here https://www.curseforge.com/minecraft/mc-mods/ender-io/files/3068701 
to update from 5.2.59, idk if I missed something or something changed or what but the game fail on startup when forge loading  reach EnderIO

#### What happens:

it crash on loading saying it miss a class for the TileCreativeSpawner

#### What you expected to happen:

the game to launch but idk, it's late here I should take some sleep, maybe I've done some mess (which I don't think but who knows) or I've not read something, but what is sure is that I deleted the old file and dragged the new one in;
I've also deleted the old config though, just in case, but same result

#### Steps to reproduce:

probably downloading Hazardous Industries modpack and trying to replace enderIO 5.2.59 with 5.2..61

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.2.61
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

crash
https://pastebin.com/aypD0HC6

latest log
https://pastebin.com/s3hpSiQK

**Comment by HenryLoenwind** [comment]
#5443

**Comment by lllMohandarlll** [comment]
Oh, I see, should I report that to TickCentral?
