### ISSUE TITLE
EnderIO modpack dont work need help

### ISSUE THREAD

**Issue by JavaErrorAPI** [SleepyTrousers/EnderIO#5447]
EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.3.1 from CoFHCore-[1.7.10]3.1.4-329.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

**Comment by VT-14** [comment]
1) 1.7.10 hasn't been supported by Ender IO in several years.

2) That debug note has a 99.9% chance of *not* being related to your issue.  The stacktrace that tells you what code was being run is much closer to the top of the crash report.
