### ISSUE TITLE
Simple Machines (Simple SAG Mill, Simple Alloy Smelter, etc.) fall like sand if no block underneath

### ISSUE THREAD

**Issue by darthvader45** [SleepyTrousers/EnderIO#5448]
#### Issue Description:
Simple machines having gravity like sand and gravel.

#### Steps to reproduce:

1. Craft simple machine.
2. Place it against a wall, one block above the floor.
3.  It falls.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.60
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? yes/no NO
- Optifine? yes/no YES
- Single Player and/or Server? Singleplayer

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by hypherionmc** [comment]
You can disable that in the configs. It's an option called Respects Gravity

**Comment by darthvader45** [comment]
Ah, didn't see that.  Will do.
