### ISSUE TITLE
enderio crash on startup

### ISSUE THREAD

**Issue by TheNimbleNinja** [SleepyTrousers/EnderIO#5450]
#### Issue Description:

crash on startup

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.12.2-5.2.61
- EnderCore:1.12.2=0.5.76
- Minecraft:1.12
- Forge:14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player 

#### Your most recent log file where the issue was present: 

https://gist.github.com/TheNimbleNinja/b06a650d791031a060e2ae019e5f662f

**Comment by HenryLoenwind** [comment]
#5443
