### ISSUE TITLE
Issues Loading version 5.2.61 for 1.12.2

### ISSUE THREAD

**Issue by CamaroKing59** [SleepyTrousers/EnderIO#5451]
#### Issue Description:
I updated the version of the mod that I have in my modpack and the client keeps crashing

#### What happens:
I updated to the latest version (5.2.61) press play. it load for min or 2 then crashed with this error (net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: crazypants/enderio/machines/machine/spawner/creative/TileCreativeSpawner)

#### What you expected to happen:
I expected it to load properly

#### Steps to reproduce:

1. Update to 5.2.61
2. press play
3.let it load
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.61
- EnderCore:0.5.76
- Minecraft:1.12.2
- Forge:14.23.5.2854
- SpongeForge? yes/no no
- Optifine? yes/no no
- Single Player and/or Server? server and single player

#### Your most recent log file where the issue was present: 

[https://pastebin.pl/view/75aac289]

**Comment by HenryLoenwind** [comment]
#5443
