### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Jamonster123** [SleepyTrousers/EnderIO#5452]
If You Can Not Help Me I Understand

#### Issue Description:
When i load a world it crashes.

#### What happens:
When i load a world it takes a long time to say anything on screen and then it just freezes and windows says its not responding and it just never loads the world

#### What you expected to happen:
I just wanted the energy from this mod and i use a money mod which has a seller which sells forge energy and i wanted to sell this mod's energy

#### Steps to reproduce:

1. I made a custom modpack for me to play with 70 mods so im not going to list them all
2. I have custom config files for lots of mods
3. Here's a few of the mods: Adminshop, Immersive Engineering, Industrialcraft 2, Mekanism, Thermal Foundation
#### Affected Versions

- EnderIO: 0.5.76
- EnderCore: 5.2.61
- Minecraft: 1.12.2
- Forge: Not sure what version
- SpongeForge? No
- Optifine? Yes
- Single Player and/or Server: Single Player

#### Your most recent log file where the issue was present:
there is no crash report or log i have to close it manually using task manager which brings up "exit code: 0"

**Comment by CitiesXL2815** [comment]
provide with Crashlog using Pastebin or gitgist

**Comment by Jamonster123** [comment]
Well it only happens when i add enderio to the mods list...
