### ISSUE TITLE
Early crash

### ISSUE THREAD

**Issue by JWTHDYTWA** [SleepyTrousers/EnderIO#5454]
#### Issue Description:

The game crashes on early startup stage.

#### Steps to reproduce:

1. Install EnderIO 5.2.61 + EnderIO Endergy with some other mods
2. Press «Play»

___
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.61
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 2847
- SpongeForge? no
- Optifine? yes

#### Your most recent log file where the issue was present: 

https://gist.github.com/JWTHDYTWA/16c0622f5b3069272effa6cb42c5b764

**Comment by CitiesXL2815** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/5443
