### ISSUE TITLE
[1.12.2] Containers Not Opening

### ISSUE THREAD

**Issue by DonovanDMC** [SleepyTrousers/EnderIO#5457]
#### Issue Description:

This isn't occurring in an established modpack per se, but it is occurring with a lot of other mods, so I suspect some incompatibility issues, though I couldn't find a list anywhere. I cannot get any containers to open when I click on them, and I cannot see this happening with anything from other mods

#### What happens:
Containers do not open.

#### What you expected to happen:
Containers open properly.

#### Steps to reproduce:

1. Place down any alloy smelter
2. Attempt to open it

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.61
- EnderCore: 1.12.2-0.5.67
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 
https://pastebin.com/A1FajuYk

**Comment by HenryLoenwind** [comment]
```
[18:48:16] [Client thread/ERROR]: Error thrown whilst accessing JEI internals!
java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getActiveAdvancedGuiHandlers()
	at codechicken.nei.jei.proxy.JEIProxy.getExtraAreas()
...
	at codechicken.nei.handler.NEIClientEventHandler.containerInitEvent() [NEIClientEventHandler.class:?]
...
	at net.minecraft.client.Minecraft.displayGuiScreen()
```

Nothing to do with us, NEI is crashing here.

**Comment by DonovanDMC** [comment]
Didn't see that one earlier, remove NEI and still getting the same issue, and I don't see any mention of NEI or JEI anywhere

https://pastebin.com/3mk75RYm

**Comment by HenryLoenwind** [comment]
![image](https://user-images.githubusercontent.com/1485873/96346804-0a61f080-109e-11eb-9ed4-f75a7e5c6d2a.png)

**Comment by DonovanDMC** [comment]
It should be unlisted now, though according to pastebin, it's "potentially offensive".
