### ISSUE TITLE
[1.12.2] crash on 5.2.61

### ISSUE THREAD

**Issue by xemnes** [SleepyTrousers/EnderIO#5458]
#### Issue Description:

crashing on startup with ender io 5.2.61

the crash screen claims its ender io powertools module.

this issue doesnt happen with ender io 5.2.59 which is what i upgraded from due to the gas conduits addon requiring 5.2.60

update: tried 5.2.60 and the same crash happens, downgrading back to 5.2.59 causes no crash

#### What happens:
gets to about 5/7 in initialization then crashes
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.61
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 2847
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? crashes on both client and server with the same issue

#### Your most recent log file where the issue was present: 
crash report: https://pastebin.com/qzz5t4ge

**Comment by HenryLoenwind** [comment]
Nope, that's something new.

Some mod called "sledgehammer" is trying to modify our code and crashes.

Still not our problem.

**Comment by xemnes** [comment]
so i need to report it to them, ok.
