### ISSUE TITLE
Where is the ManagedTESR file

### ISSUE THREAD

**Issue by Robocraft999** [SleepyTrousers/EnderIO#5459]
#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first. If you are using an unreleased version of Ender IO (a.k.a development/nightly version), please don't open an issue for features that have not been announced as "finished" or "working". Expect to be ignored if you ignore this template.

#### What happens:

i can't find the file "ManagedTESR.java"

#### What you expected to happen:

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: master branch

**Comment by HenryLoenwind** [comment]
as github ticket? really...

https://github.com/SleepyTrousers/EnderCore/blob/1.12/src/main/java/com/enderio/core/client/render/ManagedTESR.java

**Comment by Robocraft999** [comment]
thanks
