### ISSUE TITLE
Crash at Startup.

### ISSUE THREAD

**Issue by C4J3** [SleepyTrousers/EnderIO#5462]
#### Issue Description:

Crash at Startup.

#### What happens:

See title.

#### What you expected to happen:

not to crash at startup

#### Steps to reproduce:

1. install mods
2. launch 
3. crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.61
- EnderCore: 0.5.76 
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

https://pastebin.com/WTNsaWD1

Not sure if I can provide more info but let me know otherwise!

**Comment by HenryLoenwind** [comment]
#5443
