### ISSUE TITLE
The problem of vanilla alternative crafting

### ISSUE THREAD

**Issue by SanyokJons** [SleepyTrousers/EnderIO#5464]
Hello, I ran into a problem. I need to disable alternative vanilla recipes. They are added when the EnderIO mod is installed on the client. I could not find information on how to disable them anywhere. Also, there are no custom recipes in the file in the directory. The EnderIO version is 1.12.2-5.1.55.
![image](https://user-images.githubusercontent.com/49972534/97433922-ad84f680-1937-11eb-8a74-870823fcdc17.png)
![image](https://user-images.githubusercontent.com/49972534/97433955-bbd31280-1937-11eb-97a1-5f654c86f961.png)

**Comment by HenryLoenwind** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-base/src/main/resources/assets/enderio/config/recipes/misc.xml

**Comment by SanyokJons** [comment]
Thank you very much, the information helped.
