### ISSUE TITLE
How can i solve this? (only happens on the server)

### ISSUE THREAD

**Issue by Reibom** [SleepyTrousers/EnderIO#5473]
on server I can't enchant the dark steel upgrade.

what should i do on the server to resolve this?
![xzczxc](https://user-images.githubusercontent.com/25437369/98444310-ac9a5480-20ef-11eb-921b-7bcfc53b290f.png)

**Comment by tyler489** [comment]
Shift Click it in or right click it to use player exp.

**Comment by HenryLoenwind** [comment]
Not sure what "this" is. If you're talking about the red overlay---that's not by us, some other mod must be messing with our GUI there.

**Comment by tyler489** [comment]
that's Quark doing the red boxes I think.
