### ISSUE TITLE
Crash while loading with Antimatter Chemistry modpack

### ISSUE THREAD

**Issue by Lagorsirion** [SleepyTrousers/EnderIO#5474]
#### Issue Description:

Hello,
i play on the antimatter chemistry modpack and tryed to install enderio as a surplus. But it won't even load. Does anyone has a clue/solution how i can get it to work? Or is an change in the modpack necessary?

#### What happens:

Does not load crashes when it trys to load enderio

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.61
- EnderCore: 0.5.76
- Minecraft: 1.12.1
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 

[crash-2020-11-09_12.27.25-client.txt](https://github.com/SleepyTrousers/EnderIO/files/5510083/crash-2020-11-09_12.27.25-client.txt)

**Comment by tyler489** [comment]
https://github.com/TerminatorNL/TickCentral/issues/13
