### ISSUE TITLE
Issue with machine GUI

### ISSUE THREAD

**Issue by Toloxus** [SleepyTrousers/EnderIO#5477]
#### Issue Description:

GUI not working, cant open any machine gui.

#### What happens:

When I right click on any enderio machine console throws error. No crash at least.

#### What you expected to happen:

To open gui ;)

#### Steps to reproduce:

1. Destroy machine
2. Get new from JEI
3. Place machine
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.2.61
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? Yes
- Optifine? Yes
- Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/s8JNc39r

**Comment by Rover656** [comment]
This seems to be an issue relating to the following mod, rather than Ender IO:
https://www.curseforge.com/minecraft/mc-mods/forge-to-bukkit-permissions
