### ISSUE TITLE
Level underflow at crazypants.enderio.base.xp.XpUtil.getExperienceForLevel

### ISSUE THREAD

**Issue by domingasp** [SleepyTrousers/EnderIO#5479]
#### Issue Description:

Rogue-adventures and Dungeons but I have added EnderIO to it.

#### What happens:
My game crashes anytime I try to open the XP Obelisk. Other EnderIO interfaces work fine. Happens both in a server and in single player.

#### What you expected to happen:
I expected the GUI to open and allow me to use the Obelisk.

#### Steps to reproduce:

1. Download Rogue-adventures and dungeons pack.
2. Add Ender core and EnderIO mods.
3. Get an XP Obelisk and try to right click it.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.12.2-0.5.76
- EnderCore:1.12.2-5.2.62
- Minecraft:1.12.2
- Forge:14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Both in single player and on server (server does not crash only client side)

#### Your most recent log file where the issue was present: 

[https://pastebin.com/HZ4F8XwA]

**Comment by HenryLoenwind** [comment]
workaround: make sure you have at least one level when opening the obelisk

**Comment by domingasp** [comment]
When trying this I had 9 levels.

**Comment by hypherionmc** [comment]
Would it be possible to test with this build: https://ci.tterrag.com/job/EnderIO-Modules/job/EnderIO-Hourly/lastSuccessfulBuild/artifact/build/libs/EnderIO-1.12.2-5.2.1274-nightly.jar?

**Comment by domingasp** [comment]
Thank you, that build works.

**Comment by hypherionmc** [comment]
Thank you for the feedback. The fix will be part of the next release (which might be soon)
