### ISSUE TITLE
Level Underflow error when opening Soul Binder or Experience Obelisk

### ISSUE THREAD

**Issue by alfieatkinson13** [SleepyTrousers/EnderIO#5481]
#### Issue Description:

When trying to open a soul binder or experience obelisk my game crashes with an underflow error

java.lang.ArithmeticException: level underflow

I think it is to do with the experience level inside of them as this appears in the crash

at crazypants.enderio.base.xp.XpUtil.getExperienceForLevel(XpUtil.java:95)
at crazypants.enderio.base.xp.ExperienceContainer.getExperience(ExperienceContainer.java:47)

along with many other lines about xp

#### What happens:

I right click on either of these machines and the game instantly crashes

#### What you expected to happen:

The interface of the machines to open

#### Steps to reproduce:

1. Right click on soul binder or experience obelisk (may happen with other machines I haven't tested all)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.2.63
- EnderCore: 1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and Server

#### Your most recent log file where the issue was present: 

https://pastebin.pl/view/23531d27

**Comment by Stevphen** [comment]
I have come across this issue as well. Is it just that EnderIO is now out of date? What version was this interaction not an issue?

**Comment by Codingale** [comment]
The label says duplicate but I can't find another issue that references `XpUtil.java`, was this updated in a new version today if so what commit? Kinda in the dark and just updated to `Ender IO - 5.2.63` and now I see `Ender IO - 5.2.65`, so I assume it's fixed in https://github.com/SleepyTrousers/EnderIO/commit/7f35efe1945d5abcbc4ef9be51c3c16f9129203e @Stevphen

**Comment by Stevphen** [comment]
I didn't have this issue in 5.2.61. I updated my server to from 5.2.61 to 5.2.63 on 11/22/20 which is when this issue first occurred. I just tried updating to 5.2.65 and I get "A Fatal Error Has Occurred This Connection is Terminated." Returning to 5.2.61 fixes the issue.

**Comment by Stevphen** [comment]
Also here is the crash report after updating to 5.2.63 and attempting to open Soul Binder. 
[crash-2020-11-24_21.42.15-client.txt](https://github.com/SleepyTrousers/EnderIO/files/5598409/crash-2020-11-24_21.42.15-client.txt)

**Comment by Codingale** [comment]
Try version `Ender IO - 5.2.65` which works for me

**Comment by Stevphen** [comment]
When I try 5.2.65 I get the "A Fatal Error Has Occurred This Connection is Terminated" crash. It doesn't even generate a crash report or log when I try that.

**Comment by Codingale** [comment]
@HenryLoenwind I can confirm I too get that message, if every user joins at the same time however this does not happen. Only change has been the update for me.

```
[02:10:20] [Netty Client IO #2/ERROR]: There was a critical exception handling a packet on channel autoconfig
java.lang.NullPointerException: null
```
Curse doesn't have a new version pushed in case you forogt it seems like https://github.com/SleepyTrousers/EnderIO/commit/9bcd2664b936d134f36cd6849435e2606b5771eb might be a fix?

**Comment by HenryLoenwind** [comment]
Please don't hide new bugs in tickets for unrelated fixed ones. I could have released a fixed build 2 days ago...
