### ISSUE TITLE
Server Crash: EnderIO Recipe Manager and Evilcraft-Compat

### ISSUE THREAD

**Issue by Trellinane** [SleepyTrousers/EnderIO#5483]
#### Issue Description:

Server crash on loadup during mod initialization phase.

#### What happens:
Minecraft will not load up and crashes to launcher.

#### What you expected to happen:
To play minecraft

#### Steps to reproduce:
Launch minecraft

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.2.64 (also happens with 62 and 63, version 61 is fine)
- EnderCore: 1.12.2-0.5.76
- CyclopsCore: 1.12.2-1.6.6
- Evilcraft: 1.12.2-0.10.78 
- Minecraft:1.12.2
- Forge: 14.23.5.2854
- SpongeForge? yes/no No
- Optifine? yes/no No
- Single Player and/or Server? only tried in SP

#### Your most recent log file where the issue was present: 

[crash-2020-11-24_08.47.40-client.txt](https://github.com/SleepyTrousers/EnderIO/files/5590369/crash-2020-11-24_08.47.40-client.txt)

[2020-11-24-1.log](https://github.com/SleepyTrousers/EnderIO/files/5590375/2020-11-24-1.log)
[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EvilCraft-Compat (evilcraftcompat)`

Tell them to use our API instead of poking around in our internals.
