### ISSUE TITLE
Enderio Armor dont seem to register armor value

### ISSUE THREAD

**Issue by Veggetossj** [SleepyTrousers/EnderIO#5484]
Recently started playing on a server with the pack Infinity Evolved: Reloaded (Version 3.3.2, Minecraft 1.12), wich has Ender IO (version 5.2.61) and I just made some Ender Armor and slapped some Empowered I upgrades on them and charged them

As i fought some mobs, its seems that the armor and armor toughness values dont register server side as i takes full damage as if i wasnt wearing any armor at all. 

I know the server i play on uses plugins such as Sponge and plugins.

I tested it in SSP and it works fine in the pack, just SMP doesnt seem to register the armor values somehow.

Is it the mod that might be doing something wrong server-side or might the server i play on mess with the values via a possible plugin?

**Comment by HenryLoenwind** [comment]
Sponge applies damage to armor in a way that bypasses the way Forge provides for mods to do something about it. Known issue with their code, #4782 https://github.com/SpongePowered/SpongeForge/issues/2320
