### ISSUE TITLE
[1.12] cant log into server: fatal error occured, connection terminated

### ISSUE THREAD

**Issue by xemnes** [SleepyTrousers/EnderIO#5485]
#### Issue Description:

unsure if this is ender io or not but i was told to report it here first since someone said the code somewhat hinted to enderio apparently?
basically, my server restarted and i suddenly could no longer log in, i get this error: "A fatal error has occurred, this connection is terminated"
with this error in the log: https://pastebin.com/MBAnZZSz
the error is extremely ambiguous and the only hint i mightve got from it was the loenwind.autoconfig part

#### What happens:
when i log in, i briefly see the world for a few seconds then immediately get disconnected with the above error.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.65
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 2854
- SpongeForge? no
- Optifine? yes (on the client)
- Single Player and/or Server? server only

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/5618174/latest.log)

**Comment by HenryLoenwind** [comment]
Thank you for notifying us about a bug we fixed 2 days ago. We will now jump into our time machines and fix it 3 days ago instead.

**Comment by xemnes** [comment]
oh goodness, sorry... even though i follow ender io on curse, curse didnt notify me that a new version was released!

**Comment by HenryLoenwind** [comment]
Not a big issue, happens a lot. Nobody expects quick bugfix updates just after they downloaded a new release.
