### ISSUE TITLE
Minecraft crashes with soul binder

### ISSUE THREAD

**Issue by PrinceKajub** [SleepyTrousers/EnderIO#5486]
#### Steps to reproduce:

1.place soul binder
2. right click soul binder
3. crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.2.63
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? both

#### Your most recent log file where the issue was present: 

[crash-2020-12-01_14.10.11-client.txt](https://github.com/SleepyTrousers/EnderIO/files/5625263/crash-2020-12-01_14.10.11-client.txt)

**Comment by hypherionmc** [comment]
Update to version 64

**Comment by HenryLoenwind** [comment]
.66

**Comment by PrinceKajub** [comment]
we tried running the server on version 66 and now the server wont start up. does it require a world wipe to start up?

**Comment by hypherionmc** [comment]
It shouldn't. Can you provide us with your server log?
