### ISSUE TITLE
Mod incompatibility with Placement Preview

### ISSUE THREAD

**Issue by embermctillhawk** [SleepyTrousers/EnderIO#5492]
#### Steps to reproduce:

1. Install Forge, EnderCore, Ender IO, Placement Preview
2. Run game
3. Create world
4. Use shift+f3 to open debug profiler
5. Wait a little. It can take anywhere from several seconds to a fraction of a second, but it will crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.66
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? singleplayer

Placement Preview 0.3.2

#### Your most recent log file where the issue was present: 

[crash-2020-12-10_18.01.06-client.txt](https://github.com/SleepyTrousers/EnderIO/files/5676462/crash-2020-12-10_18.01.06-client.txt)
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/5676463/latest.log)

Somehow version .66 crashes but version .61 is fine. Only thing I can see is that when you have both .66 and Placement Preview loaded, there's an extra entry in the profiler.

![image](https://user-images.githubusercontent.com/23393595/101853415-cb3fa100-3b1c-11eb-8d04-28482d427d57.png)

If the issue is on the other end, or generally can't be fixed without removing the mod or downgrading Ender IO then aight, I just need someone whose brain hasn't been melted by 7 hours straight of isolating mods to take a look at this and go "Wow."

**Comment by HenryLoenwind** [comment]
Placement Preview is causing our server code to be executed on the client---that's the WorldTickEvent entries you see in the *client* profiler. I'm not surprised that that causes issues, and I'd say your crashes are the least of them. None of the code called there is safe to run client-side.

**Comment by embermctillhawk** [comment]
i n c r e d i b l e .

Well, that's a good enough answer for me. If anyone else is bored in this quarantine and wants to dig deeper, be my guest.

As for me, I'm just trying to develop a modpack, and I've got a 3 year old dead nonessential mod which is wrongly invoking server-only code in an active up to date essential mod. The fix for me and what I want, is obvious.

Thank you for a quick and informative answer.



now the question is why didn't google tell me a week ago that the reason my dark steel armor doesn't work properly on the `FTB: Revelations` server is because SpongeForge and all of this is very available to read on Github and it only gave it to me while trying to investigate THIS issue? oy.

**Comment by HenryLoenwind** [comment]
hehe, I've been thinking about starting a blog for common issues and stuff for years. Maybe I really should do it, those get found on Google better than some vague github issues, I think. ;)
