### ISSUE TITLE
Simple Redstone Conduit issue

### ISSUE THREAD

**Issue by SteamDoge9000** [SleepyTrousers/EnderIO#5494]
#### Issue Description:

Simple issue revolviog around the Redstone Conduits and the NOT gate

#### What happens:

when the NOT gate is removed it conintues to emit a redstone signal dispite no power source powering it

#### What you expected to happen:

tha the singal will cease to produce a redstone signal

#### Steps to reproduce:

1. it should be simple, have a redstone conduit face a redstone affected block (use a lamp for this, it shold do the same)
2. Insert the NOT logic Filter in the output slot
3. Remove the NOT Logic FIlter
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.2.66
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 

Preferred not to unless absolutely necessary

**Comment by hypherionmc** [comment]
Yes we know about this. It will be fixed in the next release :)

**Comment by HenryLoenwind** [comment]
Isn't it funny how new bug reports for age-old issues pop up the moment you finish fixing those bugs? I swear, it happens *every* single time... ;)

**Comment by hypherionmc** [comment]
Haha true. It's like they smell the fix lol

**Comment by SteamDoge9000** [comment]
I would also like to say thankyou to the creators of the conduits concept

because of this, Integrated Tunnels and AE2, I was able to automate something that was Not automated before

so yea, thanks :)
