### ISSUE TITLE
Latest update causes crash when also EvilCraft is present

### ISSUE THREAD

**Issue by AssassinLV** [SleepyTrousers/EnderIO#5497]
The version 1.22.2-5.2.66 causes the game to crash when 'EvilCraft-1.12.2-0.10.78' is present in the modpack.

From the last stable version '1.22.2-5.2.61' works fine together with EvilCraft.

My modpack where issue was found: https://www.curseforge.com/minecraft/modpacks/vis-se

**Comment by Natedogwoooof** [comment]
:(
