### ISSUE TITLE
Enderio Conflict with HT's Treechop 

### ISSUE THREAD

**Issue by big-poppy** [SleepyTrousers/EnderIO#5501]
#### Issue Description:

Creation of ghost blocks when simple machines are places then broken in survival mode

#### What happens:
Simple Alloy Smelter, SAG Mill, or Stirling Generator is placed, player attempts to break previously placed simple machine with pickaxe, simple machine is turned into ghost block and cannot be removed.

#### What you expected to happen:
Simple Alloy Smelter, SAG Mill, or Stirling Generator is placed, player attempts to break previously placed simple machine with pickaxe, simple machine is broken and drops in block form so player can move to optimal position

#### Steps to reproduce:
IN SURVIVAL MODE
1. craft a Simple Alloy Smelter, SAG Mill, or Stirling Generator
2. Place crafted simple machine in world
3. Break previously placed simple machine with pickaxe
...

____
#### Affected Versions:

- EnderIO: 1.12.2-5.2.66
- EnderCore: 1.12.2-0.5.76
- HT's Treechop: 1.12.2-0.11.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

file:///Users/zac/Library/Application%20Support/gdlauncher_next/instances/Testing1/logs/latest.log

P.S. Wasn't sure if I should post this here or at the EnderCore Issue Tracker sorrynotsorry

**Comment by mindforger** [comment]
> file:///Users/zac/Library/Application%20Support/gdlauncher_next/instances/Testing1/logs/latest.log

a local file link will not work over the internet, use pastebin/gist.github or similar to paste the content and link it here please

**Comment by hammertater** [comment]
Hi Ender folks, looks like the problem is on TreeChop's end. I'll take care of it, sorry about that.

**Comment by hammertater** [comment]
It's fixed. Anyone with this issue should update their TreeChop to 0.11.4 or later.
