### ISSUE TITLE
1.16.5?

### ISSUE THREAD

**Issue by MrScautHD** [SleepyTrousers/EnderIO#5502]
1.16.5?

**Comment by hypherionmc** [comment]
We are working on it, but due to lack of devs, it's taking longer than it should

**Comment by flobernd** [comment]
Is there already a public branch/repo where potential contributors could have a look?

**Comment by Spacemanspark** [comment]
No.

**Comment by hypherionmc** [comment]
Yes there is. Don't anawer if you not sure about the information: https://github.com/hypherionmc/EnderCore/tree/1.16

**Comment by flobernd** [comment]
@hypherionmc Thanks! I might be able to help out a little in the future.

**Comment by hypherionmc** [comment]
You're more than welcome. We need all the help we can get

**Comment by zKyros** [comment]
Any update? Maybe a beta of 1.16.5?

**Comment by Skulaurun** [comment]
Any news or updates? ETA for 1.16.5?

**Comment by hypherionmc** [comment]
I'll only say this once. We have no ETA, we NEVER give ETA's. When it's ready, it will be on Curseforge. If it's not on curseforge, it's not ready

**Comment by BazZziliuS** [comment]
Still believe in you

**Comment by githubuser98k** [comment]
> Still believe in you
well he give up, now he's tried on 1.18,what a mistry

**Comment by hypherionmc** [comment]
We gave up on 1.16, because 1.18 is now the next big version and we don't have enough developers to maintain both versions. It doesn't make sense to port to 1.16.5, only to port to 1.18/1.19 a week or 2 later

**Comment by githubuser98k** [comment]
that's sad, but it's time to go the 1.18 after Mekanism port to 1.18

**Comment by Luuuuuucky** [comment]
> We gave up on 1.16, because 1.18 is now the next big version and we don't have enough developers to maintain both versions. It doesn't make sense to port to 1.16.5, only to port to 1.18/1.19 a week or 2 later

Still in progress ? or abandoned?

**Comment by tomek7667** [comment]
they abandoned it unfortunately. Such a shame :(
