### ISSUE TITLE
Possibly excessive RAM usage

### ISSUE THREAD

**Issue by GodMorduk** [SleepyTrousers/EnderIO#5503]
#### Issue Description:

There are certain parts of EnderIO which are using too much memory, found it out while I was checking a dump. I don't know if it is intended or not, but possibly if those issues can be solved it would help heavy modpack makers and people with low-end pc.

#### What happens:

I have my own heavy modded client, so it is not a "pure".

1. Tank recipe JEI integration eating about 63mb of retained heap which is way much more than expected. This is probably happening because there are many fluids from different mods. I don't think such recipes are really important for all players, so config option to turn off JEI integration for tank recipe would be really helpful (if possible).

![image](https://user-images.githubusercontent.com/22483969/107334820-421afb00-6ac8-11eb-8b41-bc6738ee8ceb.png)

2. I'm not sure about this one, but stuff in "things" also taking too much RAM. If this is expected it is fine, just noticing it. 

![image](https://user-images.githubusercontent.com/22483969/107334867-5232da80-6ac8-11eb-9ec9-ecb497e9ab97.png)

#### What you expected to happen:

I don't think it is applicable. I expect EnderIO to use less memory (if it is possible).

#### Steps to reproduce:

1. Start game.
2. Create dump.
3. Check it using EMA or whatever you wish.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.2.62
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no 
- Optifine? yes
- Single Player and/or Server? single player

#### Your most recent log file where the issue was present: 

I don't think it is relevant. I will provide if asked, of course.

**Comment by HenryLoenwind** [comment]
1. Use the existing config options
2. "Things" is every single list of items and/or blocks in Ender IO. Things$1 actually is net.minecraftforge.oredict.OreIngredient and yes, that class is using too much memory, but there's nothing we can do about it...

**Comment by GodMorduk** [comment]
Okay, thank you for reply. Sorry for taking your time. Hope disabling tank integration would help about it.
