### ISSUE TITLE
 Crash Report

### ISSUE THREAD

**Issue by 3269199948** [SleepyTrousers/EnderIO#5504]
#### Steps to reproduce:

1.I don't know. All I know is I got a pipe

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:  EnderIO-1.12.2-5.2.66.jar
- EnderCore:  EnderCore-1.12.2-0.5.76.jar
- Minecraft:  1.12.2
- Forge: 2855
- SpongeForge  no
- Optifine no
- Single Player and/or Server?   Server

#### Your most recent log file where the issue was present: 
https://paste.ubuntu.com/p/vH9stvgQRW/

**Comment by CitiesXL2815** [comment]
pls describe your issue your having and what happen and how to reproduce the issue

**Comment by 3269199948** [comment]
> pls explain your issue what happened and how did it crashed steps to reproduce it crash log does help but we also need to know how it crashed

Farming Station  ！！！！

Turn on the electricity and insert the capacitor will collapse indefinitely

(My English is very poor, I do not know if you understand!)  ):

**Comment by HenryLoenwind** [comment]
Your "forge                             | 14.23.5.8888           | CatServer-1.12.2-2019-11-27-server.jar" is not compatible with Forge 2847.

**Comment by 3269199948** [comment]
what forge 8888?

**Comment by 3269199948** [comment]
> Your "forge | 14.23.5.8888 | CatServer-1.12.2-2019-11-27-server.jar" is not compatible with Forge 2847.

Version degradation can solve this problem
