### ISSUE TITLE
conduits sometimes invisible when in transparent facades

### ISSUE THREAD

**Issue by sossololpipi** [SleepyTrousers/EnderIO#5509]
this only happens when the conduits are in specific positions.

![image](https://user-images.githubusercontent.com/43117641/110162817-3962cf80-7dbd-11eb-9f33-f88f41081be5.png)

![image](https://user-images.githubusercontent.com/43117641/110162842-3f58b080-7dbd-11eb-9d61-b851b02ee26c.png)

these images were taken on enigmatica 2 expert with the modded and vanilla faithful 32x texture pack.

as you can see, some conduits are invisible in the facades while others are visible. to reproduce this bug, simply place conduits inside transparent facades so that they can make different connections. these particular facades are made of fused quartz.

**Comment by sossololpipi** [comment]
other players are perfectly able of seeing this. it seems like the texture packs are causing the issue.

**Comment by hypherionmc** [comment]
I've had this issue before with Optifine and a texture pack I used. Can't remember the name though

**Comment by sossololpipi** [comment]
the issue persists after removing the texture packs. any help would be appreciated.

**Comment by hypherionmc** [comment]
Gonna need some more details. There's a reason we have an issue template...

**Comment by CitiesXL2815** [comment]
try updating enderio to latest version you are using outdated version see if it still exists and provide us with either paste bin or github gitgist of the latest log file no downloads pls just link of pastebin or gitgist log file paste in either those two

**Comment by VT-14** [comment]
There are two kinds of facades.  One that should hide the conduits, and another that should show the conduits.  Which ones are you using here?

**Comment by sossololpipi** [comment]
> There are two kinds of facades. One that should hide the conduits, and another that should show the conduits. Which ones are you using here?

oh, i'm sorry! i was using the non-transparent version. thank you.
