### ISSUE TITLE
Inventory Panel Deletes Inventory Items When Clicking On Item Already Selected

### ISSUE THREAD

**Issue by AbieTheFishman** [SleepyTrousers/EnderIO#5512]
#### Issue Description:
When right clicking on an inventory item in in the Inventory Panel 32  of the items ( if there is a stack or greater of that item) are selected. If that item is clicked again - 32 of that item are deleted. If the inventory item is less than a stack 1/2 the count of that item are selected. Clicking on that item again delete 1/2 the items "in hand" and 1/2 the items in inventory.

Items are also deleted in the similar manner when Left Clicking.

#### What happens:
Description above

#### What you expected to happen:
I would think nothing should happen. Noting is deleted and items selected are kept "in hand"

#### Steps to reproduce:

1. Create 100 Stone Slabs in inventory
2. Right click on Stone Slabs in inventory - 32 slabs are selected and 68 remain in inventory
3. Right click again on slabs - 32 slabs remain selected but only 36 slabs remain in inventory
4. Right click again - Now only 18 slabs are selected and only 18 slabs remain in inventory
...

____

EnderIO: 1.12.2-5.66
EnderCore: 1.12.2-0.5.76
Minecraft: 1.12.2
Forge: 14.23.5.2854
SpongeForge? no
Optifine? yes
Single Player

**Comment by hypherionmc** [comment]
This issue has been fixed already, but hasn't been released yet. If you're on our discord, you can grab the latest dev build to solve this problem.

The fix will be part of our next release

**Comment by AbieTheFishman** [comment]
Thumbs Up - Thanks
