### ISSUE TITLE
Inventory Panel Remote crashes when I type in the search bar

### ISSUE THREAD

**Issue by Sobek88** [SleepyTrousers/EnderIO#5513]
#### Issue Description:

When I type anything into or remove anything from the search bar in the Inventory Panel Remote, the game crashes. When I looked at the crash report, I found that the cause was a NullPointerException in crazypants.enderio.invpanel.invpanel.TileInventoryPanel.setGuiParameter(TileInventoryPanel.java:316)

#### What happens:

The game just crashes.

#### What you expected to happen:

The ability to search

#### Steps to reproduce:

1. Create a functioning storage system using chests (I used gold and diamond chests from IronChest)
2. Bind the inventory panel remote (doesn't matter which one) to the inventory panel
3. Feed items in
4. Search, and watch it crash

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.2.66
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? single player

#### Your most recent log file where the issue was present: 

[crash-2021-04-03_11.38.23-client.txt](https://github.com/SleepyTrousers/EnderIO/files/6253061/crash-2021-04-03_11.38.23-client.txt)

**Comment by hypherionmc** [comment]
Been fixed already but hasn't been released yet. If you're in our discord, you can download the latest test build from there where it's fixed

**Comment by Sobek88** [comment]
do I go into the #builds channel?

Also, thank you so much! I thought I would not be able to use the remotes.

**Comment by Sobek88** [comment]
Edit: installed

**Comment by Krutoy242** [comment]
Experience same. Would wait CF release
