### ISSUE TITLE
Server start error: EnderIO]: Failed to write Transciever Channels on exit: java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by KitsuKura** [SleepyTrousers/EnderIO#5517]
Got this error message on my crundeecraft server:
**EnderIO]: Failed to write Transciever Channels on exit: java.util.concurrent.ExecutionException: java.lang.NullPointerException**
Its been working fine for weeks 
[crash-2021-05-18_16.55.11-server.txt](https://github.com/SleepyTrousers/EnderIO/files/6502237/crash-2021-05-18_16.55.11-server.txt)

**Comment by CitiesXL2815** [comment]
We dont support 1.7.10 anymore
