### ISSUE TITLE
Organic Green and Brown dyes

### ISSUE THREAD

**Issue by Diababloss** [SleepyTrousers/EnderIO#5519]
#### Issue Description:

With the last update, build 5.3.67 i can no longer craft green and brown dyes with the smelter.

#### What happens:

The two items we get from flora, Twigs & Prunnings and Clipping & Trimmings can no longer be put inside the smelter.

#### What you expected to happen:

To craft the dyes just like before. With twigs or trimmings coupled with an egg or a slimeball

#### Steps to reproduce:

1. Just try to put twigs/clipping inside the smelter
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.3.67
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- SpongeForge? no
- Optifine? yes
- Single Player

**Comment by Pelotrio** [comment]
You are also unable to insert any other material from enderio into the alloy smelter
