### ISSUE TITLE
Class not found: crazypants.enderio.base.events.EnderIOLifecycleEvent$ServerStarting$Dedicated

### ISSUE THREAD

**Issue by DoctorWeirdGuy** [SleepyTrousers/EnderIO#5522]
#### Issue Description:

New error message that shows up in the latest release build of EnderIO (5.3.68, monolithic).

#### What happens:
Having updated to the monolithic 5.3.68 version of EnderIO, including Endergy and Zoo,  the following error message has started showing up in the console:
`java.lang.RuntimeException: java.lang.ClassNotFoundException: crazypants.enderio.base.events.EnderIOLifecycleEvent$ServerStarting$Dedicated` (also see latest.log)

#### What you expected to happen:
To not see any classnotfound exceptions.

#### Steps to reproduce:

1. Install EnderIO 5.3.68
2. Launch
3. See console log

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.3.68
- EnderCore: 1.12.2.0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? fuck no
- Single Player

Tested with just JEI and Endergy/EnderIO Zoo and Loot Capactor tooltips, which did not affect anything.  Also disabled any other mod (Buildcraft, Torcherino, Fluid Tanks, FTB lib/utils) after uploading the latest.log, but the same error occurs. 
#### Your most recent log file where the issue was present: 

https://pastebin.com/raw/cDpyC0ZQ

**Comment by Pelotrio** [comment]
I have the same problem

**Comment by HenryLoenwind** [comment]
Added a workaround for Forge doing I don't know what...
