### ISSUE TITLE
Alloy smelter wont accept certain items

### ISSUE THREAD

**Issue by uhhhggg** [SleepyTrousers/EnderIO#5525]
The alloy smelter refuses to accepts certain items, despite them appearing in the JEI recipe function. I cannot make endsteel for example because it just wont let me put dark steel into it

**Comment by DoctorWeirdGuy** [comment]
Which version of EnderIO are you playing with?

**Comment by hypherionmc** [comment]
This issue was fixed already. It's part of the 3.70 release
