### ISSUE TITLE
Inventory panel will only connect to the fluid conduit

### ISSUE THREAD

**Issue by Namlohk** [SleepyTrousers/EnderIO#5530]
My storage machine was previously working fine and there was no issue. Now it reads as no connection. The data and item conduits both do not connect to the panel and refuse to move to the panel. I tried placing the panel on different areas on the pipe and all resulted in the same thing. I replaced all the conduits and inventory panel, still to no avail. It was working fine, and I was just adding filters through my chest area with build craft, so I have no idea why it would randomly stop working.

**Comment by CitiesXL2815** [comment]
pls use Template it's there for reason
