### ISSUE TITLE
Server Crash with Ender Core

### ISSUE THREAD

**Issue by IronworksProductions** [SleepyTrousers/EnderIO#5531]
#### Issue Description:

When attempting to start a server with a custom modpack of my creation, the server crashes with a crash report saying "java.lang.NoClassDefFoundError: com/enderio/core/common/command/CommandScoreboardInfo"

#### What happens:
Server crashes on boot with java.lang.NoClassDefFoundError: com/enderio/core/common/command/CommandScoreboardInfo

#### What you expected to happen:
Server starts without an issue

#### Steps to reproduce:

1.Start Magma server with mods in modpack
2.Wait a bit,
3.Server Crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.12.2-5.3.70
- EnderCore:1.12.2-0.5.76
- Minecraft:1.12.2
- Forge:1.12.2 - 14.23.5.2855
- SpongeForge? no
- Optifine? no
- Single Player and/or Server?
server
#### Your most recent log file where the issue was present: 
https://gist.github.com/nacjm/9f72d06a7bde7130182cdb948806692b
https://gist.github.com/nacjm/d04e4eae41579f3b4331f4da3eaeff6c

**Comment by mindforger** [comment]
> Caused by: java.lang.SecurityException: class "com.enderio.core.common.command.CommandScoreboardInfo"'s signer information does not match signer information of other classes in the same package

looks more like a broken file to me or maybe duplicate files with different versions or different version between core and mod file .. hard to say you modlist is gigantic

**Comment by Ommina** [comment]
In addition, per the Ender IO CurseForge description page:

> The following mods are known to crash (that means that the OTHER mod crashes, not that Ender IO crashes. Really, why do we need to explain this?) or cause malfunctions when Ender IO is installed. This is not Ender IO's fault.
> 
>     Moar Tinkers
>     LiteLoader
>     Laggoggles
> 

Give it a try without Laggoggles.  Maybe unrelated, but easy to test.

**Comment by IronworksProductions** [comment]
> > Caused by: java.lang.SecurityException: class "com.enderio.core.common.command.CommandScoreboardInfo"'s signer information does not match signer information of other classes in the same package
> 
> looks more like a broken file to me or maybe duplicate files with different versions or different version between core and mod file .. hard to say you modlist is gigantic

IKR, we are trying to outplay ATM3 at having "All the mods". But in all seriousness I am trying to remove laggoggles now and see it fixes it. I will update this issue if it does.

**Comment by IronworksProductions** [comment]
Laggoggles was the culprit. Ima mark this closed for now.
