### ISSUE TITLE
Step Assist Not Working

### ISSUE THREAD

**Issue by ShionWayne** [SleepyTrousers/EnderIO#5534]
**What Happened:**
The Dark Steel Upgrade Step Assist is not working in  my 1.12.2 forged Minecraft modpack. I cannot automatically go up a block with the Step Assist Dark Boots. 

**What Is Expected To Happen:**
When I wear the upgraded Boots on, I can go up a block without jumping. 

**How to reproduce:**
1. Open Minecraft and grab Dark Boots with all upgrades in creative inventory or JEI.
2. Put it on.
3. Find a one-block-high platform and walk towards it. 

**Affected Version:**
- EnderCore: 1.12.2-0.5.76
- EnderIO: 1.12.2-5.3.70
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Single Player

**Mods Installed:**
![@LDNQ2GCZPW3ETD%~`Q4WKJ](https://user-images.githubusercontent.com/37065575/129476371-41af5aa9-2acb-47c8-a030-e1311edf1dfb.png)
![CC NHUCU~D0L%36H}1QW_8](https://user-images.githubusercontent.com/37065575/129476380-7baafd46-2197-41f6-a0d0-f159e5322a36.png)
![@I M%$~%(7FRN9X6NTWZXIY](https://user-images.githubusercontent.com/37065575/129476383-4f80e387-0c12-4e08-a811-ff2d42cb2a07.png)

**Comment by hypherionmc** [comment]
Can you try to replicate this with just enderio installed, please?

**Comment by ShionWayne** [comment]
> Can you try to replicate this with just enderio installed, please?

Okay, now it works perfectly. So some mod above conflicts with EnderIO and disabled the step assist somehow. I wonder if this can be avoided. I'll try to find the mod that causes this.

**Comment by ShionWayne** [comment]
> > Can you try to replicate this with just enderio installed, please?
> 
> Okay, now it works perfectly. So some mod above conflicts with EnderIO and disabled the step assist somehow. I wonder if this can be avoided. I'll try to find the mod that causes this.

Now I believe the mod that causes this is Zollern Galaxy.

**Comment by tyler489** [comment]
> > > Can you try to replicate this with just enderio installed, please?
> > 
> > 
> > Okay, now it works perfectly. So some mod above conflicts with EnderIO and disabled the step assist somehow. I wonder if this can be avoided. I'll try to find the mod that causes this.
> 
> Now I believe the mod that causes this is Zollern Galaxy.

PLease file an issue with them, most of the times when this occurs they override enderio's step hight per tick, rather than just when their items are worn.
