### ISSUE TITLE
Mod causing incompatibilities with Legends mod's Grappling Gun #1.7

### ISSUE THREAD

**Issue by SonYoureAdopted** [SleepyTrousers/EnderIO#5536]
#### Steps to reproduce:

1. Download Legends mod with Ender I.O.
2. Put on a batman suit and use the grappling gun a couple times
3. after a while it will stop having use in survival
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: enderio-1-7-10-2-3-0-429-beta-jar
- EnderCore: endercore-1-7-10-0-2-0-39-beta-jar
- Minecraft: 1.7.10
- Forge: (10.13.4.1614
- SpongeForge? yes/no (NO)
- Optifine? yes/no (YES)
- Single Player and/or Server? (Server, but does the same in singleplayer)

#### Your most recent log file where the issue was present: There is no log for this I believe because it's not a crash

[pastebin/gist/etc link here]

**Comment by CitiesXL2815** [comment]
we don't support 1.7.10 anymore we moved onto 1.12.2 soon in the Future 1.16.5

**Comment by SonYoureAdopted** [comment]
sad :(
