### ISSUE TITLE
Crash with EnderIO

### ISSUE THREAD

**Issue by User928848849** [SleepyTrousers/EnderIO#5540]
Minecraft crash with mod EnderIO-1.7.10-2.3.0.422_beta and EnderCore-1.7.10-0.2.0.33_beta

- EnderIO: yes
- EnderCore: yes
- Minecraft: 1.7.10
- Forge: yes
- SpongeForge: no
- Optifine: yes
- Single Player

Crash log: 
**https://pastebin.com/N7GdmSxF**

**Comment by VT-14** [comment]
You are using a config file from a later version of Minecraft.  Beetroot Seeds weren't added until 1.9 (next Ender IO/Core version 1.10), you are playing 1.7.10.  Deleting your configs (both Ender IO and Ender Core, this config is the right click harvest in Ender Core) will allow them to regenerate with that version's default values.

Also, 1.7.10 support was dropped several years ago.

**Comment by User928848849** [comment]
> You are using a config file from a later version of Minecraft. Beetroot Seeds weren't added until 1.9 (next Ender IO/Core version 1.10), you are playing 1.7.10. Deleting your configs (both Ender IO and Ender Core, this config is the right click harvest in Ender Core) will allow them to regenerate with that version's default values.
> 
> Also, 1.7.10 support was dropped several years ago.

Thank you, now all is ok)
