### ISSUE TITLE
some kind of crash dont know what it is

### ISSUE THREAD

**Issue by resinate** [SleepyTrousers/EnderIO#5541]
"Caught exception from EvilCraft-Compat (evilcraftcompat)"

https://pastebin.com/Q6Kjzb1v

crash on server boot up
i dunno why this is triggered - i dont even see evil craft installed on my server

**Comment by justliliandev** [comment]
EvilCraft is present: EvilCraft-1.12.2-0.10.78.jar search for this file

**Comment by resinate** [comment]
its some config option u have to enderIO option in evilcraft to false

**Comment by justliliandev** [comment]
This issue here for evilcraft: https://github.com/CyclopsMC/EvilCraft/issues/807
fix: B:enderio=false in evilcraftcompat.cfg
