### ISSUE TITLE
Server kicks me when I try joining.

### ISSUE THREAD

**Issue by Vincent0006** [SleepyTrousers/EnderIO#5542]
Connection Lost Server Mod rejections : Ender 10 Failed mod's custom NetworkCheckHandler FML Mod : enderio ( 5.3.70 ) Ender IO Applied Energistics Conduits : Failed mod's custom NetworkCheckHandler Ender IO Conduits : Failed mod's custom NetworkCheckHandler FML Modienderioconduits ( 5.3.70 Ender IO Integration with Forestry : Failed mod's custom NetworkCheckHandler Ender IO Integration with Tinkers Construct : Failed Mod's custom NetworkCheckHandler FMLModenderiointegrationtiolate 5.3.70 ) Ender 10 Integration with Tinkers ' Construot : Failed mod's custom NetworkCheckHandler FMLMod : enderiointegrationtio { 5.3.78 ) Ender 10 Inventory Panel Failed Mod's custom NetworkCheckHandler FML Modenderioinupanel 5.3.78 ) Ender Io Machines : Failed Mod's custom NetworkCheckHandler FML Mod : enderiomachines ( 5.3.70 ) Ender 10 Open Computers Conduits : Failed mod's custom NetworkCheckHandler Ender IO Powertools : Failed mod's custom NetworkCheckHandler FML Modenderiopowertools ( 5.3.70 ) Ender 10 Refined Storage Conduits : Failed mod's custom NetworkCheckHandler FML Mod : enderioconduitsrefinedstorage ( 5.3.70 )

**Comment by hypherionmc** [comment]
EnderIO is missing from the server/client
