### ISSUE TITLE
Deco blocks always face south.

### ISSUE THREAD

**Issue by Primitive-Human** [SleepyTrousers/EnderIO#5550]
#### Issue Description:
Decoration blocks (Deco), when placed, ALWAYS face south, regardless of which direction you were facing when placing deco blocks. I attempted to use a wrench to rotate them after placing them, which doesn't work either. 

#### What happens:
Placed decoration blocks always face south, ignoring which direction the player was facing. Deco blocks also cannot be rotated with a wrench, unlike vanilla pistons. 

#### What you expected to happen:
Placed deco blocks to respect the direction players were facing, and to be able to rotate deco blocks with a wrench.

#### Steps to reproduce:

1. Craft any Decoration block.
2. Place deco blocks while facing different directions (south, north, east, west). 
3. Observe the direction placed deco blocks are facing. The F3 blockstate also states they face south. 
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.3.70
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player 

#### Your most recent log file where the issue was present: 
No related errors or crashes found in the log, and I look at the MultiMC console log often.

**Comment by joshrdane** [comment]
It appears as though this behavior is intentional?

> The deco blocks have 256 different blockstates, but Minecraft can only save 16 of them into the world. To store the data for the rest, you need a TileEntity or 31 more block IDs.
>And because people are always complaining about TileEntities, I opted to not give those blocks one by default. And because it allows them to be used with c&b, pistons, ...
>I split them into 2 blocks, to give you 32 states to access directly. To get the other states, you need to provide them with a compatible TileEntity by painting an Ender IO machine with them.

https://www.reddit.com/r/feedthebeast/comments/5tbq7v/enderio_1102_whats_the_deal_with_the_decoration/

File in question:

https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-base/src/main/java/crazypants/enderio/base/block/decoration/BlockDecorationFacing.java
