### ISSUE TITLE
"enderio:item_conduit_probe" error

### ISSUE THREAD

**Issue by 0Atrox0** [SleepyTrousers/EnderIO#5555]
#### Issue Description:

Getting a "missing item for ModObject enderio:item_conduit_probe" error

#### What happens:

I try to launch the game and load into a world, then it crashes.

#### What you expected to happen:

The game to load and be playable.

#### Steps to reproduce:

1. Launch Minecraft
2. Start a New or Existing World
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.3.70
- EnderCore: 0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2860
- SpongeForge? no
- Optifine? yes 1.12.2 HD U G5
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

https://paste.ee/p/c3rcP

**Comment by CitiesXL2815** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/5500
