### ISSUE TITLE
Warning Messages In Server Log

### ISSUE THREAD

**Issue by daftinquisitor** [SleepyTrousers/EnderIO#5557]
#### Issue Description:

Several "Warning" messages pop up when starting the server, all relate to an interaction between Forge and enderio, stating "The declared version check handler method checkModLists on network mod id XXX is not accessible"
XXX -> one of several enderio packages, I counted about 11 different ones this is popping up for.

See line 166 and on from the Pastebin linked below

#### What happens:
There are warning messages. I can't say that I notice anything specific happening in game, but I also don't fully know what this affects to know it isn't affecting something.

#### What you expected to happen:
No warning message

#### Steps to reproduce:

1. Launch Minecraft Server
2. Check Log File
3. See warning messages

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.3.70
- EnderCore: 0.5.67
- Minecraft: 1.12.2
- Forge: 14.23.5.2860
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

https://pastebin.com/Bm5LjSRs

**Comment by CitiesXL2815** [comment]
just ignore warning, if server doesn't load up then there problem
