### ISSUE TITLE
Redstone conduit does not update

### ISSUE THREAD

**Issue by GebakkenLucht99** [SleepyTrousers/EnderIO#5558]
#### Issue Description:

the signal does not update

#### What happens:

if the output of the redstone source drops to the redstone conduit, the input of the conduit will not be updated.

#### What you expected to happen:

that the input from the conduit is also lost

#### Steps to reproduce:
![2022-02-02_15 21 18](https://user-images.githubusercontent.com/98844401/152174265-e62a1f4a-f93e-440a-8524-0e1a8acbce29.png)

I am playing stoneblock 1 mod pack.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player 

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by CitiesXL2815** [comment]
your Using Outdated Version of EnderIO

**Comment by GebakkenLucht99** [comment]
I can see that, but then come the question can I just download the newer version and install it, because i downloaded this mod pack with this version installed. the origanal stoneblock modpack.

**Comment by GebakkenLucht99** [comment]
> your Using Outdated Version of EnderIO

**Comment by mindforger** [comment]
you can always try and report and link this to the modpack author
