### ISSUE TITLE
Crash during transition from PREINIT to INIT in EnderIOGlassesStateMapper - ftb beyond 1.11.0

### ISSUE THREAD

**Issue by FlamingViolet** [SleepyTrousers/EnderIO#5559]
Hi there,
sorry to bother you with my issue, however after looking into this crash for a day, I conclude that I cannot find the causing problem alone. Maybe someone can point me in the right direction or confirm the crash.

#### Issue Description:

During startup, minecraft (forge) crashes on transition from PREINITIALIZATION to INITILIAZITATION. A few hours before the crash occurred the first time, everything was running fine. I finally bet the ender dragon and closed the game. Now, I cannot start it at all. Feels like the dragon cursed me :O

Reinstalling minecraft, launcher and purge every possible config or cache file didn't help. No OS updates have occurred and to be best of my knowledge nothing else seems to have changed on that computer except that it had a reboot. There is literally no other third-party application on the designated computer (Ubuntu Linux 18.04) installed, as I only use it to play minecraft on it.
The server, running on a different device, is still working.

To be certain that this might have something to do with EnderIO, I manually removed the EnderIO mod file (not the core) and  started the game. Forge successfully loads all other mods and I am presented with the main menu of minecraft. However, I cannot join my (local) server as EnderIO is missing.

#### What happens:

On startup, forge begins to load mods and crashes to desktop after phase 1. 

#### What you expected to happen:

No crash, just loading all mods and being able to join a fitting server.

#### Steps to reproduce:

(Unknown what is otherwise necessary to trigger this crash on other systems)

1. Start minecraft with FTB Beyond 1.11.0 installed
2. 
3.
...

____
#### Affected Versions (Do *not* use "latest"):

(this is FTB Beyond 1.11.0 as-is)

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2422
- SpongeForge? No?
- Optifine? No?
- Single Player and/or Server? Client

#### Your most recent log file where the issue was present: 

[[pastebin/gist/etc link here]
](https://pastebin.com/Mzj4iE51)

---

Has someone an idea where conflicting files might be stored? I can try purging the whole OS, but that seems like an overkill. Furthermore, I do not understand what caused the crash in the first place.
I looked into the source code of the offending line. But I know to less about Minecraft Mods and internal mechanics to comprehend at which point the StateMapper used a NullPointer. It's Java ¯\\_ (ツ)_/¯.
Any help is highly appreciated :) Thanks!

**Comment by CitiesXL2815** [comment]
we don't support 1.10.2 anymore we moved onto 1.12.2

**Comment by FlamingViolet** [comment]
Thanks...

**Comment by tyler489** [comment]
You can try removing foam fix

**Comment by FlamingViolet** [comment]
Good idea @tyler489 , but it still crashes for the same exception (after removing foam fix) :/
