### ISSUE TITLE
EnderIO crashing right after finishing 2/7

### ISSUE THREAD

**Issue by TheOnlyUserr** [SleepyTrousers/EnderIO#5560]
#### Issue Description:

So when I was trying to load 1.10.2 with ender IO and endercore it crashed right after finishing 2/7 (Also I use linux mint 20) But the weird part is that it worked yesterday but now its not working, I have tried to update java, restart my laptop and launcher and forge

#### What happens:
Crashing After 2/7

#### What you expected to happen:
Loading up Minecraft with both EnderIO and endercore mod

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.193
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: Official Launcher 
- Forge: 1.10.2 - 12.18.3.2511
- SpongeForge? no
- Optifine? no
- Crash on StartUp

#### Your most recent log file where the issue was present: 

https://pastebin.com/LeGMAyAX

Thank you

**Comment by CitiesXL2815** [comment]
we don't support 1.10.2 anymore, we moved onto 1.12.2
