### ISSUE TITLE
AgriCraft crash on Ender IO

### ISSUE THREAD

**Issue by Mrorik1** [SleepyTrousers/EnderIO#5570]
Sorry,my English is not good.So please forgive me if there is any improper expression.
---
when enderio:block_farm_station harvest crop on agricraft:crop_sticks.That will make server crash.
This crash reports:
[crash-2022-07-20_08.45.12-server.txt](https://github.com/SleepyTrousers/EnderIO/files/9146143/crash-2022-07-20_08.45.12-server.txt)

**Comment by CitiesXL2815** [comment]
pls fill template it's there for a reason, and we won't have fix for it bc we are porting to 1.19+
