### ISSUE TITLE
FTB APP Crash as of 4-29-23

### ISSUE THREAD

**Issue by micschaller** [SleepyTrousers/EnderIO#5574]
this error has been preventing me from running the app on windows of over a month I cannot find out why. here is the error as stated on the crash page:

EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.3.1 from CoFHCore-[1.7.10]3.1.4-329.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

Please answer the question on solving this problem. Thank you.

**Comment by CitiesXL2815** [comment]
We don't support 1.7.10 anymore, we moved onto 1.12.2 which isn't maintain anymore bc of an complete rewrite of EIO for 1.19+

**Comment by mindforger** [comment]
micshaller, the lines quoted are not the issue, those were added for hints, but never were really helpfull in the end. For future reports, please always include the full crashlog by copy and paste it to pastebin.com and linking it in the issue, never paste the whole thing as text
