### ISSUE TITLE
ENDER IO | WATERFALL

### ISSUE THREAD

**Issue by FullGreenGN** [SleepyTrousers/EnderIO#5575]
#### Issue Description:

I i'm using waterfall as server proxy, when i want to connect i go this error

#### What happens:

![image](https://user-images.githubusercontent.com/61293366/235803969-c3ce87ec-221c-48ab-802d-1063ee48918b.png)

#### What you expected to happen:

I can't connect to my server

#### Steps to reproduce:

1. Connect to a server with enderIO

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.1.55
- EnderCore: 0.5.73
- Minecraft: 1.12.2
- Forge: 2860
- SpongeForge? no Mohist
- Optifine? np
- Single Player and/or Server? Server

**Comment by mindforger** [comment]
You wont get support here because 1.12 is way too old but 1.12 waterfall seems to do strange stuff, when you check their github page but they also did not seem to fix those in the past

**Comment by tyler489** [comment]
#5070
