### ISSUE TITLE
Soularium issues

### ISSUE THREAD

**Issue by FResetFrisk** [SleepyTrousers/EnderIO#5578]
#### Issue Description:

using alpha release of enderIO and soularium is not being made in the alloy smelter.

#### What happens:

i put gold and soulsand/soil into alloy smelter and it does not start smelting it however does work in the primitive alloy smelter

#### What you expected to happen:

i expected to get soularium

#### Steps to reproduce:

1.put gold and soulsand/soil into alloy smelter

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 6.0.5-alpha-all
- EnderCore:
- Minecraft: 1.20.2
- Forge: 47.1.1
- SpongeForge? not sure
- Optifine? hell no
- Server

#### Your most recent log file where the issue was present: 

Log Report Link: https://gist.github.com/FResetFrisk/bf5f0580f213e4586e4e1bbc45b6dd87

**Comment by CitiesXL2815** [comment]
pls report issue your having in this github instead https://github.com/SleepyTrousers/EnderIO-Rewrite/issues

**Comment by FResetFrisk** [comment]
didnt realize there was a second github. thanks for tellin me
