### ISSUE TITLE
Crafter grid can be used to /give ingredients

### ISSUE THREAD

**Issue by g33sys** [SleepyTrousers/EnderIO#5584]
#### Issue Description:

Clicking or right clicking on an ghost item in the recipe grid switches that item with whatever you have in your hand, effectively giving you anything you want. This can also be used for duping by filling the grid manually with any item and then switching it out for e.g. wood. Even remembers nbt, so you can dupe drawers full of items.

#### Steps to reproduce:
see above

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.20.1-6.0.21-alpha.jar
- ModPack ATM 9.0.2.14
- MP

**Comment by CitiesXL2815** [comment]
Pls Report it here https://github.com/Team-EnderIO/EnderIO
