### ISSUE TITLE
Powered Light Texture Issues

### ISSUE THREAD

**Issue by TPalmer8099** [SleepyTrousers/EnderIO#5587]
#### Issue Description:

The powered light in EnderIO is unresolved (black/purple). 

#### What happens:
Missing texture for the power light.

#### Affected Versions (Do *not* use "latest"): 1.20.1 all Alphas

- EnderIO:

**Comment by CitiesXL2815** [comment]
pls report it to new https://github.com/Team-EnderIO/EnderIO
