### ISSUE TITLE
Chunk Corruption - EnderIO / Obelisk

### ISSUE THREAD

**Issue by christianwdev** [SleepyTrousers/EnderIO#5588]
#### Issue Description:

Chunk corruption when using Experience Obelisk with Experience Hopper. I apologize for not having more information regarding it on which it is specifically, but I originally thought I had corrupted my chunk from using Refined Storage so I let it go, wiped the chunk, rebuilt everything. Then this time I separated the chunks, rebooted the server, and only the chunk using the Obelisk and Experience Hopper were effected and my storage system chunk was fine. You can generally tell in advance the chunk is corrupted due to the world will not save and will hang when trying to either shut down or using save-all in prior to closing the server.

#### What happens:

Chunk corruption, world is unable to start up without using MCASelector to delete specific chunks.

#### What you expected to happen:

The world to load as normal

#### Steps to reproduce:

1. Create an grinder that collects EXP, in my case, I had a skeleton spawner feeding into a XP Vacuum with a Obelisk
2. Let it run for a while, unfortunately unsure how much experience had collected but it would've been 40+ levels.
3. Restart the world, the world will fail to start without using MCASelector to delete the chunk

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.20.1-6.0.25-alpha
- Minecraft: 1.20.1
- Forge: 1.20.1-47.2.21
- SpongeForge? no
- Optifine? no
- Server

#### Your most recent log file where the issue was present: 

[[pastebin/gist/etc link here]](https://pastebin.com/xFbGBRkr)

**Comment by CitiesXL2815** [comment]
pls use the other issue tracker here https://github.com/Team-EnderIO/EnderIO
