### ISSUE TITLE
Error: java.lang.IllegalStateException: Server tried to update attributes of a non-living entity (actually: EntityWeatherRocket['entity.EnderIO.weather_rocket.name'/193, Crashes internal server

### ISSUE THREAD

**Issue by DKarelian** [SleepyTrousers/EnderIO#5589]
Issue Description:

Upon entering the nether the game crashes, i've seen this issue reported before on multiplayer servers, but I am playing singleplayer and I don't know how to resync configs for singeplayer worlds

 What happens:

I entered the nether and now the game crashes

What you expected to happen:

Just being in the nether

#### Steps to reproduce:

1. Enter the nether
2. Wait for an entity to spawn
3. Crash

____
Affected Versions (Do *not* use "latest"):

- EnderIO: EnderCore-1.7.10-0.2.0.39_beta
- EnderCore: EnderIO-1.7.10-2.3.0.429_beta
- Minecraft: 1.7.10.
- Forge: 1.7.10 - 10.13.4.1614
- SpongeForge? no
- Optifine? no
- Single Player 

Your most recent log file where the issue was present: 

https://pastebin.com/ZRSdpbXF

**Comment by DKarelian** [comment]
Wrong repo

**Comment by CitiesXL2815** [comment]
we don't support 1.7.10 anymore

**Comment by HenryLoenwind** [comment]
No, right repo.

But it's a dupe, have a look here: https://github.com/SleepyTrousers/EnderIO-1.5-1.12/issues/3282 We never found out what---aside from manually configuring server and client differently, caused this.
