### ISSUE TITLE
Crash when moving Basic Filters while editing

### ISSUE THREAD

**Issue by Volpamonhub** [SleepyTrousers/EnderIO#5592]
**#### What happens:**

I was editing 9 Basic Filters (the editing window was open), and I moved the Basic Filters from my hotbar to my inventory while the filter editing window was still open. The server immediately crashed. After the server rebooted, the filters had disappeared from my inventory.

**#### What you expected to happen:**

What I expected to happen was either the hotbar to be locked, preventing item movement, or the editing window to automatically close when moving the filters.

**#### Steps to reproduce:**

1. Open the filter editing window for several Basic Filters (I had 9 filters).
2. While the filter editing window is still open, move the Basic Filters from your hotbar to your inventory.
3. Observe that the server crashes immediately after moving the filters.

____
**#### Affected Versions (Do *not* use "latest"):**

- EnderIO: 7.0.8
- Minecraft: 1.21.1
- NeoForge: 21.1.61
- Optifine? No
- Server

#### Your most recent log file where the issue was present: 

[[pastebin/gist/etc link here]](https://gist.github.com/Volpamonhub/eac29e62e089b7a390d4f53de0eeeac8)

**Comment by Rover656** [comment]
Nice catch, could you please open this on the correct repository (this repo is for MC 1.5-1.12.2) so we can track this? Thanks! [Team-EnderIO/EnderIO](https://github.com/Team-EnderIO/EnderIO)
