### ISSUE TITLE
can not find allow recipes in emi

### ISSUE THREAD

**Issue by sophienix** [SleepyTrousers/EnderIO#5593]
#### What happens:
was not able to find most recipes mostly alloys 

#### What you expected to happen:
to be able to see the alloy recipe

#### Steps to reproduce:

1. install emi and ender io
2.start world 
3.look up alloy recipes
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:6.2.4
- EnderCore: not installed
- Minecraft:1.20.1
- Forge:47.3.12
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? both

**Comment by CitiesXL2815** [comment]
wrong issue tracker
report it here https://github.com/Team-EnderIO/EnderIO/issues
