### ISSUE TITLE
Enhancement request - allow for conduit textures at different aspect ratio than 1:1

### ISSUE THREAD

**Issue by kardain** [SleepyTrousers/EnderIO#642]
Version 1.1.0a45, MC 1.7.2, Forge 10.12.1.165

By conduit textures, I'm referring to this...

http://imgur.com/gB2MtI9

(retexture of assets/blocks/redstoneInsulatedConduit.png)

The current default texture for this block item (and similar overlays) is 32x32. Along the length of the conduit, the pixel spacing seems fine. However due to how the overlay is handled, the pixel width appears 4x smaller than the length. By allowing a 1:4 aspect ratio (32x128 for example), it would fill one small gap in many resource packs by allowing a custom texture for the conduit overlays without having a stretched look.

Not sure if this is possible, but figured I'd ask :)

**Comment by beringtom** [comment]
Before I open a new enhancement request would this also stop the pipes from streatching texture in general?

I linked a SS of the pipe, and the texture from the texturepack I'm working on.
http://imgur.com/r9ddU3t 
http://imgur.com/utKvVaF
