### ISSUE TITLE
OpenComputers/ComputerCraft Networking Cable conduit

### ISSUE THREAD

**Issue by MyNameIsKodos** [SleepyTrousers/EnderIO#725]
Feature Request: A conduit that would enable networking of OC/CC computers, possibly adding in bundled cable support with the advanced redstone conduits as well.  This would be exponentially easier with OC, as it has an API and its source code is open source.  This could also open up possibilities for maybe offering OC support with Capacitor banks, allowing the creation of power monitor programs, or conditional redstone applications from within an OC program. Sorry if that last bit doesn't make sense.

**Comment by kayila** [comment]
Personally, I'd love to see Ender IO conduits support the open computers cable. It'd be so useful to be able to run power and data on the same line!

**Comment by Selim042** [comment]
Personally, I don't use OpenComputers, but I do use ComputerCraft, but I think adding conduits for them would be VERY useful and make SO many systems more compact.  Curently one of my projects is ComputerCraft storage system comparable to an Applied Energistics ME system, but that means I need to run ComputerCraft Networking Cables and Item Conduits to every "ME Interface" (Turtle) that is connected to a machine.

**Comment by Vexatos** [comment]
It's unfortunately pretty much impossible to properly do ComputerCraft conduits. the cables in ComputerCraft are hardcoded and have lots of special handling involved.

OpenComputers networking conduits would be easy to do.

**Comment by Selim042** [comment]
Awww ;(

**Comment by edgard** [comment]
@Vexatos possibility to go ahead and do the opencomputers cable conduits? please? :D :D

**Comment by HenryLoenwind** [comment]
I'll have a look at this. Seems possible.
