### ISSUE TITLE
[Feature Request] Mekanism Gas Conduits...

### ISSUE THREAD

**Issue by ate0ate** [SleepyTrousers/EnderIO#829]
Mekanism adds gases as a crucial part of its tech tree, especially in upcoming versions, and seeing as how EnderIO works so well with it already, it'd be great if a conduit could be added, or even an upgrade for the existing fluid conduits, to allow transfer of Mekanism gases. In 1.7.10, EnderIO's fluids are already compatible with mekanisms rotary condensentrator allowing for them to be transformed from liquids to gases and stored accordingly. Some way for EnderIO to handle the gaseous versions of its own liquids would make sense and be quite useful.

**Comment by PastorBones** [comment]
+1  

I would love this feature to be added!!

**Comment by MatthiasMann** [comment]
EnderIO already has ME conduits and Mekanism gas conduits
