### ISSUE TITLE
[Feature Request] Fluid Filtering and Routing

### ISSUE THREAD

**Issue by ph1x3r** [SleepyTrousers/EnderIO#835]
On item conduits, we have both extraction and insertion filters. Also, setting the color on the in/out node effectively separates that wire from the rest of the network.

I would like to see this functionality in fluid conduits.

Although we can set the signal color on the extraction node, there is currently no way to select the color for an insertion node.

Mod Version:
-----------------
EnderIO-1.6.4-1.0.6.376.jar

**Comment by krakentoa** [comment]
I would like, besides the above functionality, to have the priority field.
(I guess what makes it complicated is that fluid slowly travels through the cables)
