### ISSUE TITLE
There is no way in game to clear the configuration on blocks or filters.

### ISSUE THREAD

**Issue by Sciruss** [SleepyTrousers/EnderIO#865]

**Comment by TylorBane** [comment]
dont know if me adding something in here will re-open this or not, im still playing on 1.12, why can this not be done with things like the capacitor blocks? not trying to get it added, just seems silly that the feature was lost to begin with

**Comment by Tidychin** [comment]
Had the same problem with the Telepad on the Omnifactory modpack, I just put the Telepad back into the crafting table and it erased the NBT Data (the current configuration).
Don't know if it will still work tho

**Comment by TylorBane** [comment]
> Had the same problem with the Telepad on the Omnifactory modpack, I just put the Telepad back into the crafting table and it erased the NBT Data (the current configuration). Don't know if it will still work tho

all of the machines have it yes, but the capacitor banks specifically dont for whatever reason, (though i havent checked since i originally posted this
