### ISSUE TITLE
Soul Stealer for ender io enchantment table  

### ISSUE THREAD

**Issue by tgur32** [SleepyTrousers/EnderIO#880]
this is what i have for the enchament i couldnt get diamonds to go in or these heads was putting it in the EnchanterRecipes_User file  trying to get it to be 10 zombie heads per level of soul stealer i took out the </ because it wasnt showing up

enchaterRecipes>
enchantment name="Soul Stealer" costPerLevel="10">
    itemStack modID="minecraft" itemName="zombie heads" /> 
  enchantment>
enchaterRecipes>

**Comment by p75369** [comment]
Here we go, the config for the Soul Stealer enchant using a Soul Shard.

Not so sure about the cost. It does have 5 levels, so you'd need to make 16 books to max it.

And I don't know what's up with the "item.null", but that's what NEI reporting and it works so...

<enchantment name="enchantment.Soul Stealer" costPerLevel="2">
    <itemStack modID="SSR" itemName="item.null"/>
  </enchantment>

**Comment by tterrag1098** [comment]
item.null is not the item's registered name. Use NEI's item dump to get the real name.

**Comment by p75369** [comment]
I did, that's where I got it from, full line from the dump:

SSR:item.null,6750,false,SSR,ssr.gameObjs.items.SoulShard

**Comment by tterrag1098** [comment]
Please post your entire file and if you can, upload the NEI dump so I can confirm.

**Comment by p75369** [comment]
Think this'll work, not used to sharing files.

https://drive.google.com/file/d/0B4UCt4Fls0GUR1QzNGhrcE5UNmM/view?usp=sharing
