### ISSUE TITLE
Idea for new tool and block form request

### ISSUE THREAD

**Issue by whyohwhy1366** [SleepyTrousers/EnderIO#908]
I had an idea for a Dark Spade/Shovel. When its empowered and digs a gravity effected block (e.g. sand & gravel) it removes the blocks above the dug block. I was thinking 3 blocks for Empowered 1, 5 for 2, 8 for 3 and 12 for 4, or something like that. Also can you add a block form of the alloys, esp. Dark Steel, Energetic Alloy, Vibrant Alloy, and Pulsating Iron.

**Comment by tterrag1098** [comment]
Block forms have been added for all ingots
