### ISSUE TITLE
Reinforced Obsidian not Wither Proof

### ISSUE THREAD

**Issue by Staegrin** [SleepyTrousers/EnderIO#929]
![2014-08-27_00 36 54](https://cloud.githubusercontent.com/assets/8494635/4052931/b2280654-2d71-11e4-8411-fa799fe77995.png)
setup
![2014-08-27_00 37 21](https://cloud.githubusercontent.com/assets/8494635/4052935/b61f366a-2d71-11e4-8331-c2607fee676c.png)
aftermath

On the tool tip the material is labelled as Wither Proof. Sadly this isn't true. Spawning a wither in a 5 wide, 5 high and 3 thick cube of reinforced obsidian will not contain the mob. If the roof is only one layer thick the Wither glitches through the ceiling. If the ceiling is made two layers thick it destroys the blocks.

**Comment by PotatoSauceVFX** [comment]
Not fixed in 1.10.2 :( EnderIO v3.1.169
