### ISSUE TITLE
[Enhancement] Unbreakable upgrade for Dark Steel Armor

### ISSUE THREAD

**Issue by psychofad** [SleepyTrousers/EnderIO#936]
I love the Dark Steel Armor and all of it's upgrades.  The only thing I hate about the armor is how it still gets damaged so easily after spending so many levels and resources on adding all of the upgrades.  What do you think about maybe adding an upgrade that negates the durability for the armor 100%.  So that after the upgrade the armor takes only hits to the power in the armor instead of damaging the armor.  Of course this means that the armor would use more power to deflect the damage due to the upgrade....so instead of it only taking 1/2 the durability damage it would now take 2x the power it did but the armor would remain unharmed as long as it had power to deflect the damage.  What do you think?

**Comment by tukpot** [comment]
Was that implement deleted?

**Comment by HenryLoenwind** [comment]
the energy settings for dark steel items just got moved to capacitor.xml.
