### ISSUE TITLE
Ender fluid conduits ignoring filter when connected to Mekanism Electrolytic Separator

### ISSUE THREAD

**Issue by Killgore32** [SleepyTrousers/EnderIO#963]
I have set up a 1.7.10 test world to test a proposed mod pack that includes Both Ender IO and Mekanism among others.  

In the process of setting up Mekanism's ore processing I set up an ender fluid conduit network to transfer water from an Ender IO reservoir to both a salinization plant, and one electrolytic separator to convert water into hydrogen and oxygen.  On the salinization plant there are 2 valves, an input that is filtered to send water into the unit and an output filtered to send brine back into the fluid conduit network.  The intent was then to connect the Brine output to a second Electrolytic separator to produce sodium and chlorine, but if I connect a fluid conduit from that network to the back of the separator, even after setting the filter first on the input conduit, the tank fills with water.  If the conduit is connected to anything else, like a portable or dynamic tank, the filter works properly.  

As a workaround, I use a dynamic tank as a buffer between the conduit network and the separator.  Brine fills the tank, goes out a separate valve and conduit into the separator, then to further processing.

**Comment by tterrag1098** [comment]
This is ancient, is it still an issue?
