### ISSUE TITLE
enderio overwriting applied energistics 2 silicon recipe?!

### ISSUE THREAD

**Issue by Nightreaver** [SleepyTrousers/EnderIO#970]
I'm running a server with enderio and app eng 2 (both latest versions - from today).

When i try to make silicon in a furnace from appeng2 i cant do that with enderio installed.
When i remove enderio, everything is working fine.

Please have a look at this.

Thanks

**Comment by prs722** [comment]
I changed the settings because I'm using but it seems only EnderIO silicon works in EnderIO recipes. Is there a way to change this in the config of EnderIO.
