### ISSUE TITLE
Fuel compatibility (Galacticraft)

### ISSUE THREAD

**Issue by homemmakako** [SleepyTrousers/EnderIO#985]
I am playing Bevo's tech pack (version 10-FULL) and I was shocked when I found out that you can't use Ender IO fuels with GalactiCraft. The GC wiki says that you CAN use other forge fuels as well, which makes me think that is a GC bug. Anyways, can you make your fuels compatible with GC (at least rocket fuel, since that would make a lot of sense) or is it impossible to make that without hacking micdoodle8's mod?

**Comment by radfast** [comment]
Galacticraft 3.0.10 now accepts EnderIO rocket Fuel Buckets as fuel.  Each will add 1000mB of fuel to a Fuel Loader.
http://wiki.micdoodle8.com/wiki/Whats_New
(Support for piped in Rocket Fuel will be added next build.)

I don't see that any of the other EnderIO Vat liquids are suitable for cross-mod support in Galacticraft as they do not have equivalents.

Question:  would it unbalance EnderIO if we allow buckets of Rocket Fuel to be __filled__ in Galacticraft machines?

**Comment by tterrag1098** [comment]
In what way? What would it cost? Rocket fuel is a *very* potent fuel, and
is usually quite difficult to make.

**Comment by radfast** [comment]
That's what I mean.  Players who have advanced into late game can make Fuel in large quantities in Galacticraft.  Especially on Mars, if you have plenty of electricity there (which could come from solar), an infinite Fuel factory can be built without any resource cost once it starts working.  http://wiki.micdoodle8.com/wiki/Methane_Synthesizer

Currently we do not allow Fuel -> Rocket Fuel conversion, and sounds like it will be best if it stays that way.
