### ISSUE TITLE
Add a Fertilizer Machine

### ISSUE THREAD

**Issue by Xaw4** [SleepyTrousers/EnderIO#994]
I would really like something to speed up the growth of plants. especially in combination with the farmer.

One thing i have in mind would be an other 'Preseved Head' machine. Maybe using a Skelleton head this time (Skelleton.. bones .. bonemeal .. fertilizing).

The Manure John [yes.. that's the name i give it] needs power(RF) and Nutrient Destillation* to work. It sprays the fluid on the ground, to fertilize the plants on it.

Things to consider / I am not sure of / Additional ideas:
* it doesnt need Nutrient desstillation to work, but a Fluid Fertilizer - made in the Vat, using Nutrient Dest. + bonemeal + "compostable" (Leaves, wheat, apple, sapling ...)
* not sure if it should target the area in front of it, or the area around it.
  * if you choose, to make it the area around it, it maybe should check also in y-1 and y+1, to be able to put it right underneath and below The Farmer.. and that combination would be the main purpouse of making it target around. (if you do so .. a + would be, to let the head spin ^^)
* i am not sure what method to implement that is the best. i've heard some mods increase the random tick rate/force ticks, and others apply bonemeal with a random chance. i guess, the first method would be better for a greater variety of plants (nether wart, enderlillies ..) but also be harder to implement, and i guess it will probably have a higher bug rate.

**Comment by tterrag1098** [comment]
Fertilizer machine is no longer needed as the farming station supports fertilization

**Comment by Badcholo** [comment]
I just place a chest on top of the farming machine with bonemeal and hoes. It works great when i set it to input/output. pulls what it needs outputs what it produces.
